### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by lzrobots** [facebookresearch/detectron2#10]
which script is used for inference? I didn't see the `test_net.py` used for inferencing.

**Comment by ppwwyyxx** [comment]
If by "inference" you mean evaluate a model on a dataset, `train_net.py` has an `--eval-only` flag.
If you want to run inference on some images, see https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-with-pre-trained-models
