### ISSUE TITLE
Is there a publication that established the 3x training schedule?

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#1003]
#119 explains the difference of the 1x and the 3x training schedule. 

If I'm not mistaken, the 1x training schedule was established in the [original Mask RCNN publication](https://arxiv.org/abs/1703.06870). Is there also a publication that established the 3x training schedule?

**Comment by ppwwyyxx** [comment]
Maybe you can count https://arxiv.org/abs/1811.08883. Other than that there isn't.
But we'll be using 3x more frequently, e.g. in https://arxiv.org/abs/1912.08193.
