### ISSUE TITLE
outputs.pred_boxes format

### ISSUE THREAD

**Issue by usholanb** [facebookresearch/detectron2#1005]
Hi,

First of all, great work!

When I use a model like this:

object_det = build_model(cfg)  # returns a torch.nn.Module
DetectionCheckpointer(object_det).load(f'{CLASSIFIERS_DIR}/model_final.pth')
outputs = model([{'image': image} for image in image_l]) 

where each image is numpy array (height, width, channel)

In which format should I expect outputs.pred_boxes?

I expected outputs[0]['instances'].pred_bboxes to be a tensors of shape [N x 4] where 4 values are x1, y1, x2, y2

But when I draw those boxes they seem to be on the upper left corner and quite larger than I expected.

Did I interpret those values correctly and it's just my model?

**Comment by ppwwyyxx** [comment]
The interpretation is correct.

The easiest way to test inference code is to use an official config+model.

**Comment by yh673025667** [comment]
@usholanb Hi, I guess i have met the same problem with you, do you figure it out why those boxes are quite larger than expected?

**Comment by usholanb** [comment]
Hi @yh673025667 . Yes. I tried to avoid predictor because it takes only one example at a time. But then I modified it and it works for multiple examples

The reason we get large boxes:
I can be wrong, please correct me if so, but my guess is that by default detectron2 does some data augmentations that involve reducing the size of the input images. Only after those augmentations the transformed image is fed to the model. The model makes the predictions(very very small bboxes) which then are enlarged by Visualizer. So if you don't make the same augmentation (by the way their predictor does those augmentations) then your bboxes will be of normal sizes and then visualizer will make them too large.
So I would suggest to go with their predictor have your own custom version like the one below.
Hope it helps

**Comment by usholanb** [comment]
##############################################################################################################
# This module gives additional feature of predicting on multiple inputs
##############################################################################################################
from detectron2.engine import DefaultPredictor
import numpy as np
import torch
import detectron2.data.transforms as T
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.data import (
    MetadataCatalog,
)
from detectron2.modeling import build_model


class CustomPredictor(DefaultPredictor):
    def __init__(self, cfg):
        super(DefaultPredictor, self).__init__()

        self.cfg = cfg.clone()  # cfg can be modified by model
        self.model = build_model(self.cfg)
        self.model.eval()
        self.metadata = MetadataCatalog.get(cfg.DATASETS.TEST[0])

        checkpointer = DetectionCheckpointer(self.model)
        checkpointer.load(self.cfg.MODEL.WEIGHTS)

        self.transform_gen = T.ResizeShortestEdge(
            [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
        )

        self.input_format = cfg.INPUT.FORMAT
        assert self.input_format in ["RGB", "BGR"], self.input_format

    def __call__(self, original_images):
        """
        Args:
            original_images (np.ndarray): an image of shape N x (H, W, C) (in BGR order).

        Returns:
            predictions (dict): the output of the model
        """
        if isinstance(original_images, np.ndarray):
            original_images = [original_images]
        with torch.no_grad():  # https://github.com/sphinx-doc/sphinx/issues/4258
            height, width = original_images[0].shape[:2]
            inputs = []
            for orig_image in original_images:
                if self.input_format == "RGB":
                    # whether the model expects BGR inputs or RGB
                    orig_image = orig_image[:, :, ::-1]
                image = self.transform_gen.get_transform(orig_image).apply_image(orig_image)
                image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))
                inputs.append({"image": image, "height": height, "width": width})
            predictions = self.model(inputs)
            return predictions
