### ISSUE TITLE
Nan AP for one class

### ISSUE THREAD

**Issue by GiovanniPasq** [facebookresearch/detectron2#1008]
i trained retinanet on cityscape dataset and then i tested on cityscape-foggy. For the car class i have nan value, what does it mean? I have images with car in my dataset...
<img width="778" alt="Screenshot 2020-03-08 at 18 16 18" src="https://user-images.githubusercontent.com/33225259/76167698-f39f0700-6168-11ea-8e67-8c2e2dc2fb4a.png">

<img width="568" alt="Screenshot 2020-03-08 at 18 15 56" src="https://user-images.githubusercontent.com/33225259/76167711-0b768b00-6169-11ea-97c6-a83c8d2aabed.png">

**Comment by ppwwyyxx** [comment]
No valid score can be computed, for example, if the model makes no predictions of car.
