### ISSUE TITLE
How to apply mask_rcnn segmentation on a balloon video ?

### ISSUE THREAD

**Issue by gireeshkbogu** [facebookresearch/detectron2#101]
Hi, I am going through the google colab example tutorial. 

I am trying to apply mask_rcnn segmentation on a random youtube balloon-video instead of an balloon-image to detect balloon only (one class).

How can I assign .yaml and .pkl files that were generated using images earlier in the tutorial to a random video? thanks

I tried the foolowing but it didn't work. I think I am having trouble assign the trained config and model files. 

```
!cd detectron2_repo && python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --video-input ../video-clip_b.mp4 --confidence-threshold 0.6 --output ../video-clip_b_testing1.mkv \
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

**Comment by ppwwyyxx** [comment]
You can find the following config in the tutorial, which is used to train the balloon model:
```
cfg.DATASETS.TRAIN = ("balloon/train",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)
```
the config file you're running demo.py with does not have these changes, so it won't work.

The model you trained will be in `os.path.join(cfg.OUTPUT_DIR, "model_final.pth")`, as you can find in the tutorial as well. You need to set `MODEL.WEIGHTS` to it for inference.

**Comment by gireeshkbogu** [comment]
Do I need to do something like this?

```
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")

!cd detectron2_repo && python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --video-input ../video-clip_b.mp4 --confidence-threshold 0.6 --output ../video-clip_b_testing1.mkv \
  --opts MODEL.WEIGHTS cfg.MODEL.WEIGHTS
```

**Comment by ppwwyyxx** [comment]
`cfg.MODEL.WEIGHTS` is a python statement. The second line is a shell command. No python variables will be available in the shell command.

**Comment by ppwwyyxx** [comment]
Similarly, all the changes you made to `cfg` affect the python variable. It does not affect the shell command you run, which reads config from the given config file.

**Comment by gireeshkbogu** [comment]
Ok now it is working but the output is the same as input with no segmentation. 


```
!cd detectron2_repo && python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --video-input ../video-clip_b.mp4 --confidence-threshold 0.6 --output ../video-clip_b_testing2.mkv \
  --opts MODEL.WEIGHTS ../output/model_final.pth
```

**Comment by ppwwyyxx** [comment]
> all the changes you made to cfg affect the python variable. It does not affect the shell command you run, which reads config from the given config file.

Which means you need to change the config file given to `demo.py`.

**Comment by gireeshkbogu** [comment]
to something like this? 

```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../output/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
```

**Comment by ppwwyyxx** [comment]
You need to create a yaml file which has the same content as `configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml`, except for the extra changes mentioned above in https://github.com/facebookresearch/detectron2/issues/101#issuecomment-542987444.

**Comment by gireeshkbogu** [comment]
I think that is what I did. I am writing all the steps just to be clear. 

1. First I ran this to create config on balloon train samples

```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("balloon/train",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml looks like the following ..
```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

```
2. So I manually created a yaml file like this in a different (/content/gdrive/My Drive/fastai_files/datasets/test_samples/balloon.yaml)? 
ps: should I move this new yaml file to config/COCO-InstanceSegmentation directory to avoid the error?

```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../output/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
```

3. and then finally ran like the command using my own yaml file and model weights

```
!cd detectron2_repo && python demo/demo.py --config-file '/content/gdrive/My Drive/fastai_files/datasets/test_samples/balloon.yaml' --video-input ../video-clip_bb.mp4 --confidence-threshold 0.7 --output ../video-clip_bb_testing_1.mkv \
  --opts MODEL.WEIGHTS ../output/model_final.pth
```

**Comment by ppwwyyxx** [comment]
> all the changes you made to cfg affect the python variable. It does not affect the shell command you run, which reads config from the given config file.

What the command run is `demo.py`. Running `demo.py` has nothing to with the changes 
```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("balloon/train",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)
```
that you made during training, because these changes are not in `demo.py`, and not in the config file you gave to `demo.py` either.

You need to add these changes either to `demo.py`, or to the config file you provided to `demo.py`.

**Comment by gireeshkbogu** [comment]
This time I forked Detectron2 and reran everything and added changes to the [demo file](https://github.com/gireeshkbogu/detectron2/blob/master/demo/demo_balloon.py) but still have errors. You can access/edit my code [here](https://drive.google.com/file/d/18fHAyo4w7IBy_K4xyj5ZOW_o6zlZ9Bts/view?usp=sharing).

Error
```
Failed to load OpenCL runtime
[10/18 22:37:08 detectron2]: Arguments: Namespace(confidence_threshold=0.7, config_file='configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml', input=None, opts=['MODEL.WEIGHTS', '../output/model_final.pth'], output='../video-clip_bb_testing_1.mkv', video_input='../video-clip_bb.mp4', webcam=False)
Traceback (most recent call last):
  File "demo/demo_balloon.py", line 79, in <module>
    cfg = setup_cfg(args)
  File "demo/demo_balloon.py", line 23, in setup_cfg
    cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/content/detectron2_repo/detectron2/config/config.py", line 23, in merge_from_file
    loaded_cfg = _CfgNode.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 47, in load_yaml_with_base
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
```

**Comment by gireeshkbogu** [comment]
This time I forked Detectron2 repo and re-ran all the code by adding config changes to the [demo file](https://github.com/gireeshkbogu/detectron2/blob/master/demo/demo_balloon.py) but still have issues. 

Here is my colab [code](https://drive.google.com/file/d/18fHAyo4w7IBy_K4xyj5ZOW_o6zlZ9Bts/view?usp=sharing). You can edit if you want to. 


```
!cd detectron2_repo && python demo/demo_balloon.py --config-file 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' --video-input ../video-clip_bb.mp4 --confidence-threshold 0.7 --output ../video-clip_bb_testing_1.mkv \
  --opts MODEL.WEIGHTS ../output/model_final.pth


```
```
Failed to load OpenCL runtime
[10/18 22:35:43 detectron2]: Arguments: Namespace(confidence_threshold=0.7, config_file='configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml', input=None, opts=['MODEL.WEIGHTS', '../output/model_final.pth'], output='../video-clip_bb_testing_1.mkv', video_input='../video-clip_bb.mp4', webcam=False)
Traceback (most recent call last):
  File "demo/demo_balloon.py", line 79, in <module>
    cfg = setup_cfg(args)
  File "demo/demo_balloon.py", line 23, in setup_cfg
    cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/content/detectron2_repo/detectron2/config/config.py", line 23, in merge_from_file
    loaded_cfg = _CfgNode.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 47, in load_yaml_with_base
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
```

**Comment by ppwwyyxx** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: './detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'

As the error says, your code is trying to read a file that does not exist. Since your command has "cd detectron2_repo", you should remove "detectron2_repo" from the path.

**Comment by gireeshkbogu** [comment]
Thank you now having the following issue

```
Failed to load OpenCL runtime
[10/18 23:13:30 detectron2]: Arguments: Namespace(confidence_threshold=0.7, config_file='configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml', input=None, opts=['MODEL.WEIGHTS', '../output/model_final.pth'], output='../video-clip_bb_testing_1.mkv', video_input='../video-clip_bb.mp4', webcam=False)
WARNING [10/18 23:13:30 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/demo_balloon.py", line 81, in <module>
    demo = VisualizationDemo(cfg)
  File "/content/detectron2_repo/demo/predictor.py", line 24, in __init__
    self.metadata = MetadataCatalog.get(cfg.DATASETS.TEST[0])
IndexError: tuple index out of range
```

**Comment by ppwwyyxx** [comment]
Set `cfg.DATASETS.TEST = ("balloon/val",)`

**Comment by gireeshkbogu** [comment]
Thank you. Seems to be running but got stuck here

```
Failed to load OpenCL runtime
[10/18 23:37:22 detectron2]: Arguments: Namespace(confidence_threshold=0.7, config_file='configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml', input=None, opts=['MODEL.WEIGHTS', '../output/model_final.pth'], output='../video-clip_bb_testing_1.mkv', video_input='../video-clip_bb.mp4', webcam=False)
WARNING [10/18 23:37:22 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (2, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (2,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (4, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (4,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (1, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (1,) in the model! Skipped.
  5% 9/181 [00:04<01:26,  1.99it/s]Traceback (most recent call last):
  File "demo/demo_balloon.py", line 145, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/content/detectron2_repo/demo/predictor.py", line 127, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/content/detectron2_repo/demo/predictor.py", line 96, in process_predictions
    vis_frame = video_visualizer.draw_instance_predictions(frame, predictions)
  File "/content/detectron2_repo/detectron2/utils/video_visualizer.py", line 90, in draw_instance_predictions
    labels = _create_text_labels(classes, scores, self.metadata.thing_classes)
  File "/content/detectron2_repo/detectron2/data/catalog.py", line 116, in __getattr__
    key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'thing_classes' does not exist in the metadata of 'balloon/val'. Available keys are dict_keys(['name']).
  5% 9/181 [00:05<01:37,  1.77it/s]
```

**Comment by ppwwyyxx** [comment]
This error is addressed by 22e04d1432363be727797a081e3e9d48981f5189

**Comment by gireeshkbogu** [comment]
If I have to add this new change do I need to repeat the forking/install and rerun things?

**Comment by ppwwyyxx** [comment]
If you install detectron2 in the same way as the tutorial, then `git pull` in the repo is sufficient.

**Comment by gireeshkbogu** [comment]
All ran well but the output is the same as the input. There was no object detection in the video.

**Comment by ppwwyyxx** [comment]
As I said in https://github.com/facebookresearch/detectron2/issues/101#issuecomment-542987444

> The model you trained will be in os.path.join(cfg.OUTPUT_DIR, "model_final.pth"), as you can find in the tutorial as well. You need to set MODEL.WEIGHTS to it for inference.

You load a wrong model.

**Comment by gireeshkbogu** [comment]
In the tutorial .pkl file was set to weights. Setting .pth is the same as .pkl?
Also when I build the model with balloon data, where does it save the .pkl file?

**Comment by ppwwyyxx** [comment]
> In the tutorial .pkl file was set to weights. Setting .pth is the same as .pkl?

Both file extensions are supported.

> Also when I build the model with balloon data, where does it save the .pkl file?

I do not know what you mean by "when I build the model", and when saying "the .pkl file" it is unclear to me what pkl file you're referring to.

**Comment by gireeshkbogu** [comment]
Here is the line from the tutorial where *.pkl file set to model weights in the demp.py 

`#cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"`

**Comment by ppwwyyxx** [comment]
Yes

**Comment by gireeshkbogu** [comment]
Yey!!! it is working. Thank you for being so patient with me.
I really really appreciate your help even at this time. I hope you have a nice weekend :)

**Comment by Haow235** [comment]
> Set `cfg.DATASETS.TEST = ("balloon/val",)`
@ppwwyyxx 
I trained just like the balloon tutorial, got the trained result, and I have the same error when predict in my own new dataset, which doesn't have label, only image, I think it's because I don't set the config correctly, would you please tell me how to set the cfg correctly when predict in new dataset.
The following is my code:
`from google.colab.patches import cv2_imshow

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 6  # only has one class (ballon)
# cfg.DATASETS.TEST = ("balloon_val", )
predictor = DefaultPredictor(cfg)
outputs = predictor(im)`
`IndexError                                Traceback (most recent call last)

<ipython-input-15-b0efd18b9574> in <module>()
      6 cfg.MODEL.ROI_HEADS.NUM_CLASSES = 6  # only has one class (ballon)
      7 # cfg.DATASETS.TEST = ("balloon_val", )
----> 8 predictor = DefaultPredictor(cfg)
      9 outputs = predictor(im)

/content/detectron2_repo/detectron2/engine/defaults.py in __init__(self, cfg)
    157         self.model = build_model(self.cfg)
    158         self.model.eval()
--> 159         self.metadata = MetadataCatalog.get(cfg.DATASETS.TEST[0])
    160 
    161         checkpointer = DetectionCheckpointer(self.model)

IndexError: tuple index out of range`

anyhelp is appreciate, thank you so much!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/issues/101#issuecomment-544001707

**Comment by Haow235** [comment]
thank you, I figured it out. I need to register the test data before using it, and then do as you say. thanks a lot~
