### ISSUE TITLE
Can't install Detectron2 on Linux machine with Anaconda

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/detectron2#1010]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
I followed all the steps I could on the Detectron2 page for installation (Google collab) 
However I am not using Google collab, Im using a Linux machine because I want to run Mesh R-CNN ultimately, but need to install Detectron first.

2. what exact command you run:

Create anaconda env:
-conda create --name Mesh_RCNN_v07 python=3.6

Install Detectron2 Dependencies
Conda install -c pytorch torchvision
Conda install -c anaconda cython
Conda install -c anaconda pyyaml
Conda install -c conda-forge opencv
pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

Everything above works ok, but the next step 'Build detectron2 from source' fails:
pip install 'git+https://github.com/facebookresearch/detectron2.git'

3. what you observed (including the full logs):
The error message is super long, but the last paragraph is this:

error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /home/13787650/anaconda3/envs/Mesh_RCNN_v07/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"'; file='"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-90lrbp3a/install-record.txt --single-version-externally-managed --compile --install-headers /home/13787650/anaconda3/envs/Mesh_RCNN_v07/include/python3.6m/detectron2 Check the logs for full command output.

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

There was an obvious error

It is an installation error, not an error with running a model

**Comment by ppwwyyxx** [comment]
Please post full logs and environment information as the  [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md). says.
