### ISSUE TITLE
Can't install Detectron2 with Anaconda (Linux)

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/detectron2#1012]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
I followed all the steps I could on the Detectron2 page for installation (Google collab)
However I am not using Google collab, Im using a Linux machine because I want to run Mesh R-CNN ultimately, but need to install Detectron first.
```
2. what exact command you run:

conda create --name Mesh_RCNN_v07 python=3.6

Install Detectron2 Dependencies
Conda install -c pytorch torchvision
Conda install -c anaconda cython
Conda install -c anaconda pyyaml
Conda install -c conda-forge opencv
pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

Everything above works ok, but the next step 'Build detectron2 from source' fails:
pip install 'git+https://github.com/facebookresearch/detectron2.git'

3. what you observed (including the full logs):
```
The error message is super long, but the last paragraph is this:

error: command 'gcc' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/13787650/anaconda3/envs/Mesh_RCNN_v07/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"'; file='"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-90lrbp3a/install-record.txt --single-version-externally-managed --compile --install-headers /home/13787650/anaconda3/envs/Mesh_RCNN_v07/include/python3.6m/detectron2 Check the logs for full command output.
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Run `python -m detectron2.utils.collect_env` in the environment where you observerd the issue, and paste the output.
If detectron2 hasn't been successfully installed, use `python detectron2/utils/collect_env.py` (after getting this file from github).
Detectron was not successfully installed: after running 'python detectron2/utils/collect_env.py':

python: can't open file 'detectron2/utils/collect_env.py': [Errno 20] Not a directory

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

I have been through these steps, but cannot get further than this step:
pip install 'git+https://github.com/facebookresearch/detectron2.git'

**Comment by ppwwyyxx** [comment]
For the 4th time, please post __FULL LOGS__, no matter how long it is. The last paragraph is not useful. If you don't know how to save logs, google it. If it's too large and github does not allow it, upload it as an attachment.

> If detectron2 hasn't been successfully installed, use python detectron2/utils/collect_env.py (__after getting this file from github__).

The file can be obtained from github at https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/collect_env.py
