### ISSUE TITLE
Problems inference video using pre-trained model

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1013]
When I run demo with image (*.jpg) everything is ok.
But when I run with a video:
`python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --video-input ../Downloads/gh020374.mp4 --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
`
It just run 20 first frames and then stop.
`[03/09 00:06:11 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input='../Downloads/gh020374.mp4', webcam=False)
[03/09 00:06:12 fvcore.common.checkpoint]: Loading checkpoint from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/09 00:06:12 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached in /home/n/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/09 00:06:12 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
  1%|▌                                        | 20/1596 [00:07<10:16,  2.56it/s]`

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
diff --git a/datasets/README.md b/datasets/README.md
deleted file mode 100644
index 2536a6f..0000000
--- a/datasets/README.md
+++ /dev/null
@@ -1,90 +0,0 @@
-
-For a few datasets that detectron2 natively supports,
-the datasets are assumed to exist in a directory called
-"datasets/", under the directory where you launch the program.
-They need to have the following directory structure:
-
-## Expected dataset structure for COCO instance/keypoint detection:
-
-```
-coco/
-  annotations/
-    instances_{train,val}2017.json
-    person_keypoints_{train,val}2017.json
-  {train,val}2017/
-    # image files that are mentioned in the corresponding json
-```
-
:

```
2. what exact command you run:
`python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --video-input ../Downloads/gh020374.mp4 --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl`

Video available here: [https://drive.google.com/file/d/1ZpawIDnYGjrDO42QtptlsPPTioWim6xo/view?usp=sharing](https://drive.google.com/file/d/1ZpawIDnYGjrDO42QtptlsPPTioWim6xo/view?usp=sharing)
3. what you observed (including the full logs):
```
[03/09 00:06:11 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input='../Downloads/gh020374.mp4', webcam=False)
[03/09 00:06:12 fvcore.common.checkpoint]: Loading checkpoint from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/09 00:06:12 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached in /home/n/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/09 00:06:12 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
  1%|▌                                        | 20/1596 [00:07<10:16,  2.56it/s]
```
4. 
these steps is quit simple, no private data, no additional resources to run.
## Expected behavior:
I expect that demo will run on all of the frames.
I don't know if this is a bug or not.

## Environment:
`(base) n@n-Precision-3630-Tower:~/detectron2$ python -m detectron2.utils.collect_env
------------------------  ----------------------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                     1.17.2
detectron2                0.1.1 @/home/n/detectron2/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.2
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/n/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Quadro P4000
CUDA_HOME                 /usr/local/cuda-10.2
NVCC                      Cuda compilation tools, release 10.2, V10.2.89
Pillow                    6.2.0
torchvision               0.5.0 @/home/n/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0-dev
------------------------  ----------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

I confirm detectron2 has been successfully installed. 2 month ago, in v0.0, I run demo inference on videos successfully.
At first, I think this may relate to my Opencv, when I run demo with a model I trained myself
```
(base) n@n-Precision-3630-Tower:~/detectron2$ python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --video-input ../Downloads/gh020374.mp4 --output 'out.mp4' --opts MODEL.WEIGHTS output/model_final.pth MODEL.ROI_HEADS.NUM_CLASSES 1 MODEL.ROI_HEADS.SCORE_THRESH_TEST 0.8 
[03/08 23:08:25 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', input=None, opts=['MODEL.WEIGHTS', 'output/model_final.pth', 'MODEL.ROI_HEADS.NUM_CLASSES', '1', 'MODEL.ROI_HEADS.SCORE_THRESH_TEST', '0.8'], output='out.mp4', video_input='../Downloads/gh020374.mp4', webcam=False)
[03/08 23:08:27 fvcore.common.checkpoint]: Loading checkpoint from output/model_final.pth
OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
  1%|▌                                        | 20/1596 [00:05<06:34,  4.00it/s]

```
So I uninstall my opencv (pip uninstall opencv-python; pip uninstall opencv-contrib-python) and then install opencv from source with cmake sucessfully.
But even with the most basic demo with pre-trained model from detectron2 model_zoo, it still run with only 20 first frames.
Thanks for reading!

**Comment by ppwwyyxx** [comment]
I believe your video is in a non-standard or corrupted format so opencv cannot read it properly.

Closing as it's unrelated to detectron2.

**Comment by pvtien96** [comment]
@ppwwyyxx 
You're brilliant!
Checked and fixed. Thanks!
