### ISSUE TITLE
Can't install Detectron2 with anaconda (Linux)

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/detectron2#1014]
(Sorry, I'm new to this. Thanks for your patience.  Please don't delete the posts, I use them to create corrected posts.  I will delete any erroneous posts myself)

If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
I am following the steps to run Detectron2 on google collab.  Eventually want to run Mesh R-CNN. I am running it on a Linux machine, in an anaconda environment
```
2. what exact command you run:

conda create --name Mesh_RCNN_v04 python=3.6

Conda install -c pytorch torchvision (pyTorch 1.4.0)

Conda install -c anaconda cython (cython 0.29.15)

Conda install -c anaconda pyyaml

Conda install -c conda-forge opencv (opencv 3.4.2)

 pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

(Everything up until here is fine. The error occurs when I run:)

pip install 'git+https://github.com/facebookresearch/detectron2.git'

3. what you observed (including the full logs):
```
Error log available [here](https://github.com/jamalknight/misc)


```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

There was an obvious error.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

I am not running a model, I can install Detectron2

## Environment:

Run `python -m detectron2.utils.collect_env` in the environment where you observerd the issue, and paste the output.
If detectron2 hasn't been successfully installed, use `python detectron2/utils/collect_env.py` (after getting this file from github).

Running python detectron2/utils/collect_env.py:

----------------------  ------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) [GCC 7.3.0]
numpy                   1.18.1
detectron2._C           failed to import
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/13787650/anaconda3/envs/Mesh_RCNN_v07/lib/python3.6/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0                   Quadro M5000
CUDA_HOME               /usr
NVCC                    Cuda compilation tools, release 7.5, V7.5.17
Pillow                  7.0.0
torchvision             0.5.0 @/home/13787650/anaconda3/envs/Mesh_RCNN_v07/lib/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
cv2                     3.4.2
----------------------  ------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

Tried running these steps, still get errors.

**Comment by ppwwyyxx** [comment]
The log you provided has the reason of the failure:
> error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
   #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
