### ISSUE TITLE
Where to change  "each GPU 2 images per batch" ? 

### ISSUE THREAD

**Issue by nemonameless** [facebookresearch/detectron2#102]
if train on 4 gpus,  I need 4 images per batch each gpu  to keep bs=16. Where to change  "each GPU 2 images per batch" ?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/951417e2d54744cbb75b73f1af40e96d827d1ab4/detectron2/config/defaults.py#L500-L503

**Comment by nemonameless** [comment]
@ppwwyyxx Thanks, do you mean if I train with 4GPUS and keep _C.SOLVER.IMS_PER_BATCH = 16 , then it will automatically change to "each GPU 4 images per batch" ?

**Comment by ppwwyyxx** [comment]
Yes.
