### ISSUE TITLE
How can I get the dense feature of object?

### ISSUE THREAD

**Issue by yestinl** [facebookresearch/detectron2#1023]
## 🚀 Feature
I want to get the dense feature of the object. 

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers --
we only consider papers that have enough significance and prevalance.

We do not take requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory
contains many of such examples.

**Comment by ppwwyyxx** [comment]
I don't know what do you mean by dense feature but it's probably answered in https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model
