### ISSUE TITLE
Retraining a model with a new class, keep existing ones

### ISSUE THREAD

**Issue by ortegatron** [facebookresearch/detectron2#1024]
Hi, 
I'm trying to FasterRCNN with a dataset of my own so it learns to detect two classes this dataset adds, but keeping the existing classes of COCO. Or at least, the classes that are relevant to the case, the ones seen on the dataset.
I'm thinking on retraining only with my dataset, but running first the Default FasterRCNN on it, and add that detections to the ground truth data. This way, the model should't decrease performance on seen COCO classes, while learning to detect the new ones.
Does this have sense?

Also, what about the cfg.MODEL.ROI_HEADS.NUM_CLASSES? Should it be COCO + #custom classes, or just COCO seen classes on data set + #custom classes.
Thanks

**Comment by ppwwyyxx** [comment]
This sounds like something you can do.

You can set NUM_CLASSES in any way as long as it agrees with the data you provide to the training.

**Comment by pvtien96** [comment]
Hi, @ortegatron I'm very excited.
I'm also working on a small project similar to your. So did you try @ppwwyyxx 's recommendations? Does it work?
