### ISSUE TITLE
Issue installing Detectron2 from dockerfile

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/detectron2#1027]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
Trying to install Detectron2 for Mesh R-CNN
```
2. what exact command you run:

Install docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

Make this file executable
sudo chmod +x /usr/local/bin/docker-compose

Go into /docker (repository download location)
sudo USER_ID=$UID /usr/local/bin/docker-compose run detectron2

<let it run>

Shows error message:

ERROR: Cannot create container for service detectron2: Unknown runtime specified nvidia

3. what you observed (including __full logs__):
```
ERROR: Cannot create container for service detectron2: Unknown runtime specified nvidia
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
---------------------  -----------------------------------------------------------------------
sys.platform           linux
Python                 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                  1.17.2
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.0.1 @/home/13787650/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build    False
CUDA available         True
GPU 0                  Quadro M5000
CUDA_HOME              /usr
NVCC                   Cuda compilation tools, release 7.5, V7.5.17
Pillow                 6.2.0
torchvision            0.2.2 @/home/13787650/anaconda3/lib/python3.7/site-packages/torchvision
torchvision            unknown
cv2                    4.1.1
---------------------  -----------------------------------------------------------------------
PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: GPU 0: Quadro M5000
Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch3d                 0.0.1                    pypi_0    pypi
[conda] torch                     1.0.1                    pypi_0    pypi
[conda] torchvision               0.2.2                    pypi_0    pypi

```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
You docker does not support nvidia gpus and you need https://github.com/NVIDIA/nvidia-docker
