### ISSUE TITLE
How to show classes's name while visualize prediction with instance segmentation?

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1028]
## ❓ How to use Detectron2

In colab tutorial, when you inference trained model, it show the image
![image](https://user-images.githubusercontent.com/25927039/76398695-eaec4200-63af-11ea-9878-8bf59b7f50eb.png)
How to show the label of the class, in this case show "balloon ", like the image below
![image](https://user-images.githubusercontent.com/25927039/76398758-09ead400-63b0-11ea-9fef-40b7619b59c5.png)

I think this relates to the way I register MetadaCatalog, thing_classes, thing_dataset_id_to_contiguous_id?
I've read https://detectron2.readthedocs.io/tutorials/datasets.html# , but maybe I missed something here?
Many thanks!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets has code on how to set names

**Comment by pvtien96** [comment]
Yes, but in the colab tutorial, you set names 
```
for d in ["train", "val"]:
    DatasetCatalog.register("balloon_" + d, lambda d=d: get_balloon_dicts("balloon/" + d))
    MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])
```
But it stills don't show the class's name (I mean "balloon", for example).
Is this relate to #546 @davidbunk 's comment:
"you can map your category IDs to the proper range by following instructions at
https://detectron2.readthedocs.io/tutorials/datasets.html
for setting
thing_dataset_id_to_contiguous_id
in the metadata of your dataset."
Please tell me more detail, @ppwwyyxx . Thanks

**Comment by ppwwyyxx** [comment]
It is designed with logic to not show class names when there is only one class.

**Comment by pvtien96** [comment]
I got i, thanks!
