### ISSUE TITLE
Unexpected error after updating detectron2 repo

### ISSUE THREAD

**Issue by ahiranandani** [facebookresearch/detectron2#1032]
After updating detectron2 repo on local, 

The following line does not work (was working fine until yesterday). Has something changed? 

from detectron2.export.caffe2_inference import ProtobufModel, ProtobufDetectionModel

Error: No module named 'caffe2.proto'; 'caffe2' is not a package

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
