### ISSUE TITLE
Difference in evaluation caffe2 

### ISSUE THREAD

**Issue by ahiranandani** [facebookresearch/detectron2#1033]
Hi
Ran the caffe2 converter successfully create model.pb and model_init.pb files. (Used --run_eval) and results are close to original detectron2 results.
Used Caffe2Model __call__ function to do inference on a new image. however, the results obtained by Caffe2Model.__call__ are not the same as --run_eval in the converter script. 
Can you please help? Heres how I'm testing it:

import cv2
img = cv2.imread('test.png')
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
caffe2_model = Caffe2Model.load_protobuf('../detect2/')
caffe2_model([data])

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ppwwyyxx** [comment]
Closing as a dup of #1034
