### ISSUE TITLE
Difference in evaluation caffe2

### ISSUE THREAD

**Issue by ahiranandani** [facebookresearch/detectron2#1034]
Ran the caffe2 converter successfully create model.pb and model_init.pb files. (Used --run_eval) and results are close to original detectron2 results.
Used Caffe2Model call function to do inference on a new image. however, the results obtained by Caffe2Model.call are not the same as --run_eval in the converter script.
Can you please help? Heres how I'm testing it:

1. 
import cv2
img = cv2.imread('test.png')
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
data = {'image': image, 'height': image.shape[1], 'width': image.shape[2]}
caffe2_model = Caffe2Model.load_protobuf('../detect2/')
caffe2_model([data])

2. 
The result is [{'instances': Instances(num_instances=11, image_height=3301, image_width=2550, fields=[pred_boxes: Boxes(tensor([[ 551.2294, 1889.8937, 1059.4714, 1930.9833],
          [2180.2307,  150.9417, 2377.2971,  198.2487],
          [1967.0961, 2793.0317, 2116.5515, 2820.5757],
          [ 128.7229, 1083.7495,  261.8251, 1170.0981],
          [ 342.7892, 1087.0898,  474.7463, 1171.7368],
          [1980.7639, 1717.2264, 2111.9656, 1751.3134],
          [1995.1256, 3120.3853, 2204.7437, 3160.6655],
          [1962.4979, 1088.9863, 2119.3704, 1168.1924],
          [ 554.0389, 1720.8916,  634.1976, 1751.2236],
          [2222.2424, 1716.0865, 2353.4958, 1749.5145],
          [ 307.8203,  128.1414,  548.1573,  267.4652]])), scores: tensor([0.8167, 0.8988, 0.8582, 0.8340, 0.8145, 0.8125, 0.7608, 0.7593, 0.7548,
          0.7507, 0.7402]), pred_classes: tensor([5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])])}]

which is the correct format but wrong output. 

Expected output is different : the output is exactly the same as detectron2 inference output. 
Can you please check the code to give image input to Caffe2Model.

**Comment by ppwwyyxx** [comment]
> which is the correct format but wrong output.
Expected output is different : the output is exactly the same as detectron2 inference output.

why do you think it is wrong output?

**Comment by ahiranandani** [comment]
The same input image is put through detectron2 inference script (no caffe2) and the output is different. Thats why...

**Comment by ppwwyyxx** [comment]
What is "detectron2 inference script"? Could you show what you did with the script, how you run the script, the full logs you observed with the script, as the issue template asks for?

**Comment by ahiranandani** [comment]
All I'm asking is, if the way to read and provide Caffe2Model with the input image
i.e. 
import cv2
img = cv2.imread('test.png')
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
data = {'image': image, 'height': image.shape[1], 'width': image.shape[2]}
caffe2_model = Caffe2Model.load_protobuf('../detect2/')
caffe2_model([data])

is correct or not?

**Comment by ppwwyyxx** [comment]
It is correct.

**Comment by ahiranandani** [comment]
Great, thanks a lot
