### ISSUE TITLE
FN, TP, FP during evaluation

### ISSUE THREAD

**Issue by DINOUS11** [facebookresearch/detectron2#1035]
## ❓ How to use Detectron2

I want to get the FN, TP, FP during evaluation for **mask rcnn**. Where do I write the code and what do I use?

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/evaluation.html

**Comment by DINOUS11** [comment]
@ppwwyyxx  
![image](https://user-images.githubusercontent.com/62002655/76507130-97e9bc00-648f-11ea-9859-f96aed2d03db.png)

I create Counter class and also import DatasetEvaluator, DatasetEvaluators but it only run COCOEvaluator and not printing anything from Count

**Comment by ppwwyyxx** [comment]
I do not know what you did or what you observed so cannot help you. 
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by DINOUS11** [comment]
I use the https://detectron2.readthedocs.io/tutorials/evaluation.html but it only prints the total prediction not FP, FN and TP for mask rcnn @ppwwyyxx

**Comment by ppwwyyxx** [comment]
You're supposed to write code to compute metrics you want to compute
