### ISSUE TITLE
How to train COCO dataset on Google Colab?(The dataset is placed in google drive)

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/detectron2#1036]
Hello, I am trying to train coco on Google Colab.

I've placed the dataset in the google drive.

However, if I use 'cp' to copy the dataset to the 'datasets' dir from google drive, it is extremely slow.

Then, I want to use 'ln -s' to put the 'coco' dir under the 'datasets' dir, 
`!ln -s ./drive/My\ Drive/coco ./detectron2/datasets`
but  it won't work, still saying that cannot find the dataset.

Are there any solutions for me to train the model with dataset placed in google drive? Thanks very much!

**Comment by ppwwyyxx** [comment]
The directory should be put into "./datasets", relative to your current directory.

**Comment by CraigWang1** [comment]
You can use this command to download zip files into colab from google drive:

(Replace the FILEID and FILENAME with your drive link's file id and the name that you would like to save it as)

`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=FILEID" -O FILENAME && rm -rf /tmp/cookies.txt `

Source: https://gist.github.com/iamtekeste/3cdfd0366ebfd2c0d805

After that, you can unzip the file in colab uzing `!unzip`.

Then, you could move it with `!mv /content/DATADIR /content/detectron/dataset

Hope this helps!
