### ISSUE TITLE
Run detectron on CUDA9.2

### ISSUE THREAD

**Issue by InfluencerNGZK** [facebookresearch/detectron2#1038]
## How to use Detectron2 under CUDA9.2 environment

![image](https://user-images.githubusercontent.com/54970620/76494117-2863d480-646f-11ea-9055-88c9d00d7fd4.png)
I follow the directions above to install the detectron2 for CUDA9.2, but how to install the detectron2 directory to run my own code in it.

**Comment by ppwwyyxx** [comment]
If you mean you want to modify the source code, then you cannot install a pre-built detectron2.

**Comment by InfluencerNGZK** [comment]
![image](https://user-images.githubusercontent.com/54970620/76494483-ed15d580-646f-11ea-8ea9-646c20e98ff0.png)
For CUDA10.1, I found the directions above which download a detectron2 directory and I can put my own code in /tools directory to train. Then I switch to CUDA 9.2 and want to do the same thing on another machine. So what should I do after pre-built detectron2?

**Comment by ppwwyyxx** [comment]
You should redo everything on another machine.

**Comment by InfluencerNGZK** [comment]
Yeah, I did but when I run the demo code below it turns out that my CUDA driver is too slow. But my CUDA driver version is about  410.48, even higher than CUDA 9.2 required.
![image](https://user-images.githubusercontent.com/54970620/76495722-67dff000-6472-11ea-9d4d-b3e55a1f0054.png)

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by InfluencerNGZK** [comment]
OK. Thanks for your corporation.
