### ISSUE TITLE
Don't understand, how to output prediction classes as words

### ISSUE THREAD

**Issue by bazanovvanya** [facebookresearch/detectron2#1040]
I need to list the objects that are recognized by detectron. But detectron outputs prediction classes in numeric format. How to output prediction classes as words, or where can i find to which number which object belongs?
![Untitled](https://user-images.githubusercontent.com/57997673/76519350-da9c9b80-6471-11ea-8508-f1240355dc35.png)

**Comment by ppwwyyxx** [comment]
```
name = MetadataCatalog.get("dataset_name").thing_classes[id]
```

see https://detectron2.readthedocs.io/tutorials/datasets.html
