### ISSUE TITLE
How to train rpn only with detecton2?

### ISSUE THREAD

**Issue by airqj** [facebookresearch/detectron2#1042]
## How to train rpn only in faster rcnn with detecton2?
- the pth file is large for emdbedded devices,and my dataset only have one class,so i want to get a weight file as small as possible

**Comment by ppwwyyxx** [comment]
There are RPNs in the model zoo: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#rpn--fast-r-cnn
