### ISSUE TITLE
Maximum number of instances per image

### ISSUE THREAD

**Issue by EBJames** [facebookresearch/detectron2#1045]
Hi,

I'm using maskrcnn in Detectron2  to count the number of bacteria in an image using a custom dataset, and the tutorial jupyter notebook and I've noticed that for every image I use I get a maximum of 100 instances. Is this a strange coincidence, or does detectron2/mask max out at 100 instances per image?

Cheers,

Ed

**Comment by ppwwyyxx** [comment]
You can set `cfg.TEST.DETECTIONS_PER_IMAGE = 1000`
