### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by ZhihuaGao** [facebookresearch/detectron2#1046]
When I run the script query_db.py of densepose project I got this problem. The file densepose_head.py import dataclasses but doesn‘t find this python package and neither I. Could you help me?

**Comment by ananthu-aniraj** [comment]
This is an issue with your version of Python. "Data Classes" (https://docs.python.org/3/library/dataclasses.html) was introduced in Python 3.7. However, you can download the implementation of it for Python 3.6 using this link: (https://pypi.org/project/dataclasses/). That should fix the error

**Comment by ppwwyyxx** [comment]
@ananthu-aniraj  is correct. Thanks!
We'll update the readme to reflect this
