### ISSUE TITLE
Decreasing the size of a trained model

### ISSUE THREAD

**Issue by rasmusGrift** [facebookresearch/detectron2#1047]
## ❓ Decreasing the size of a trained model 

The size of trained model (model_final.pth) I have is 351mb. Is it possible to decrease the size of this model? This to get it as lightweight as possible.
I have read some things that you can only save the parameters by a get.parameters function which will decrease the size but I'm not sure how to do that on detectron2 and how to load those parameters again.

**Comment by ppwwyyxx** [comment]
You can modify the checkpoint however you want, with `torch.save` and `torch.load`.

**Comment by geoexploring** [comment]
same question as [#771](https://github.com/facebookresearch/detectron2/issues/771).
as the reply said, you can use the code: [FCOS/tools/remove_solver_states.py ](https://github.com/tianzhi0549/FCOS/blob/master/tools/remove_solver_states.py).
