### ISSUE TITLE
How to do semantic segmentation with detectron2?

### ISSUE THREAD

**Issue by Simon32** [facebookresearch/detectron2#1055]
## ❓ How to use Detectron2 to do semantic segmentation
Q: How to do semantic segmentation with detectron2?
Does anyone have any tutorials?  Thx.

**Comment by GiovanniPasq** [comment]
see the official tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

**Comment by pvtien96** [comment]
@GiovanniPasq the colab has instance segmentation.
@Simon32 I'm also trying to write a semantic segmentation with detectron2.
you can use check this: https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/semantic_R_50_FPN_1x.yaml

**Comment by Simon32** [comment]
> see the official tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

Not this one, I want to do semantic segmentation. The official tutorial doesn't provide the corresponding tutorial.

**Comment by Simon32** [comment]
> @GiovanniPasq the colab has instance segmentation.
> @Simon32 I'm also trying to write a semantic segmentation with detectron2.
> you should have a look on this: https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/semantic_R_50_FPN_1x.yaml

Hello, I want to use my custom dataset to do semantic segmentation.  
Do you know how to preprocess the custom dataset?
Do you have any tutorials? thx.

**Comment by vdopp234** [comment]
@pvtien96 I'm also trying to do semantic segmentation using detectron2. Is the config in the link you sent for Mask-RCNN?

**Comment by pvtien96** [comment]
@Simon32 maybe yes. but what is the format of your datasets?
@vdopp234 I''m not sure. I'm training and will feedback later.

**Comment by Simon32** [comment]
> @Simon32 maybe yes. but what is the format of your datasets?
> @vdopp234 I''m not sure. I'm training and will feedback later.

The coco format dataset.

**Comment by pvtien96** [comment]
> > @Simon32 maybe yes. but what is the format of your datasets?
> > @vdopp234 I''m not sure. I'm training and will feedback later.
> 
> The coco format dataset.

So it's easy. Just follow the official Colab tutorial.

**Comment by liuqibj** [comment]
I checked the turotial but it seems how to prepare the data for semantic segmentation is not described.

**Comment by Cyril9227** [comment]
> 
> 
> > > @Simon32 maybe yes. but what is the format of your datasets?
> > > @vdopp234 I''m not sure. I'm training and will feedback later.
> > 
> > 
> > The coco format dataset.
> 
> So it's easy. Just follow the official Colab tutorial.

Have you managed to make it work ? 
Can you explain how to register a dataset with the expected input for semantic segmentation ? It's unclear how we should do that

**Comment by singhalnus** [comment]
Hello, any sample code for performing inference using "Semantic Segmentation

-  no sample for Semantic Segmentation available in the official document.

**Comment by benkoger** [comment]
There are some examples here for using DeepLab for semantic segmentation with detectron2: https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab

**Comment by ppwwyyxx** [comment]
As mentioned above, there are instructions in https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab and https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend
