### ISSUE TITLE
Cityscapes Multi-machine evaluation

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#1058]
From `CityscapesEvaluator.py`,  I see that  

> Note:
        * It does not work in multi-machine distributed training.
        * It contains a synchronization, therefore has to be used on all ranks.
        * Only the main process runs evaluation.

Are there any plans for multi-machine distributed training?

**Comment by ppwwyyxx** [comment]
No there isn't.

If all the machines share a distributed, strongly consistent file system, then it already works out of the box.
