### ISSUE TITLE
detectron2.evaluation.COCOEvaluator gives warning no predictions from object detection model 

### ISSUE THREAD

**Issue by nihal-rao** [facebookresearch/detectron2#1059]
I have trained an object detection model following the official detectron2 colab tutorial, just modified for object detection only using config file faster_rcnn_R_101_FPN_3x.
Training on custom dataset works fine. 
As in the colab notebook, I try to evaluate trained model on test dataset ( named as rpc_val, my custom dataset).  
 However **coco_evaluation** gives warning **no predictions from model**. Also the **coco_instances_results.json file is empty**.
However, **passing images to model as follows** :
 ```
from detectron2.utils.visualizer import Visualizer

predictor = DefaultPredictor(cfg)
dataset_dicts = DatasetCatalog.get("rpc_val")
for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    print(d["file_name"])
    v = Visualizer(im[:, :, ::-1],
                   metadata=rpc_val_metadata, 
                   scale=0.5, 
                     # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2_imshow(v.get_image()[:, :, ::-1])
```
**results in correct output with detected bboxes** .
Why is this happening?
Please help.
How do I get the right output?
## Instructions To Reproduce the Issue:
1. I run code as follows (rpc_val is my  custom dataset):
```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("rpc_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "rpc_val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```
This gives the warning no predictions from model as shown below:

```
Inference done 5975/6000. 0.0870 s / img. ETA=0:00:03
[03/17 16:12:48 d2.evaluation.evaluator]: Total inference time: 0:14:24.526801 (0.144208 s / img per device, on 1 devices)
[03/17 16:12:48 d2.evaluation.evaluator]: Total inference pure compute time: 0:08:41 (0.086994 s / img per device, on 1 devices)
[03/17 16:12:48 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[03/17 16:12:48 d2.evaluation.coco_evaluation]: Saving results to ./output/coco_instances_results.json
[03/17 16:12:48 d2.evaluation.coco_evaluation]: Evaluating predictions ...
WARNING [03/17 16:12:48 d2.evaluation.coco_evaluation]: No predictions from the model!

OrderedDict([('bbox',
              {'AP': nan,
               'AP50': nan,
               'AP75': nan,
               'APl': nan,
               'APm': nan,
               'APs': nan})])
```
## Expected behavior:
Return values of test metrics.
## Environment:

```
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/usr/local/lib/python3.6/dist-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0+cu100 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla P100-PCIE-16GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    7.0.0
torchvision               0.5.0+cu100 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
Full code is not provided so I cannot say for sure. But I think in `predictor = DefaultPredictor(cfg)` you're loading a model detectron2 provided, rather than a model you trained.

**Comment by nihal-rao** [comment]
The code can be found here : 
https://github.com/nihal-rao/RPC-Object-detector/blob/master/My_notebook.ipynb

Also, I change the cfg file according to my dataset as follows, so I am loading the model I trained :
```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("rpc_train",)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 200
 

cfg.MODEL.WEIGHTS = os.path.join('/content/drive/My Drive/output5k', "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1  # set the testing threshold for this model
cfg.DATASETS.TEST = ("rpc_val", )
trainer = DefaultTrainer(cfg)
predictor = DefaultPredictor(cfg)

```

**Comment by ppwwyyxx** [comment]
Since you create a new trainer after training, you need to load the model to the trainer. See https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer

**Comment by nihal-rao** [comment]
Thanks a lot, it works!

**Comment by DUZHUJUN** [comment]
> Thanks a lot, it works!
@nihal-rao 
HI，I met the same problem ,and it still doesn't work,please help,what's wrong with my code?

the code:

cfg = get_cfg()
cfg.merge_from_file("../configs/faster_rcnn_X_101_32x8d_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model

cfg.OUTPUT_DIR = '/mnt/prj_DLA/outputs/frcnn_r101/'
cfg.MODEL.WEIGHTS = '/mnt/prj_DLA/outputs/frcnn_r101/model_final.pth'
cfg.DATASETS.TEST = ("DLA_test", )
cfg.DATASETS.TRAIN = ("DLA_train",)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
# predictor = DefaultPredictor(cfg)
evaluator = COCOEvaluator("DLA_test", cfg, False, output_dir="/mnt/prj_DLA/outputs/frcnn_r101/")
val_loader = build_detection_test_loader(cfg, "DLA_test")
inference_on_dataset(trainer.model, val_loader, evaluator)

WARNING is No predictions from the model!

**Comment by ferisita** [comment]
@DUZHUJUN 
I had the same problem as well. After training I just added the following:

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.8   # set the testing threshold for this model
cfg.DATASETS.TEST = ("custom_val", )
predictor = DefaultPredictor(cfg)

and finally I loaded the model to the trainer that I had defined for training:

trainer.resume_or_load()

I did not define a new trainer with cfg = get_cfg(), because this loads everything from defaults again.

**Comment by yakupakkaya** [comment]
@ferisita you should set bool arg as True when you want to evaluate only with your trained model;

trainer = DefaultTrainer(cfg)
trainer.resume_or_load(**resume=True**)
