### ISSUE TITLE
Inference time for Faster R-CNN R50-FPN is much lower than the one in MODEL_ZOO

### ISSUE THREAD

**Issue by nmoutinho** [facebookresearch/detectron2#106]
Hi,

first of all, congratulations for the project! 

I am testing detectron2 for the "Faster R-CNN R50-FPN" model (faster_rcnn_R_50_FPN_3x.yaml). According to the [MODEL_ZOO](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md) document, the inference time for this model should be around 0.047s/image (or 21.27fps). 

Even though the image resolution is not specified anywhere in MODEL_ZOO, I've performed some inference tests (in a GeForce GTX 1080TI, in opposite to the V100 depicted in MODEL_ZOO) for different image resolutions. Here are the results:

- 720p -> inference time=0.11s/image (9.09fps)
- 360p -> inference time=0.105s/image (9.52fps)
- 180p -> inference time=0.098s/image (10.2fps)

From the results I detect two problems:
- **problem 1**: the image resolution appears to have no effect on the inference time which seems strange
- **problem 2**: the inference time corresponds to half of the time I was expecting from the results in MODEL_ZOO

What could be the problem? Did anyone test the inference times for all the available models and compare them to the benchmark values?

Thanks!

Edit: changed inference times

**Comment by nmoutinho** [comment]
Actually, the values I get are very similar to the ones from detectron (v1), when checking its [MODEL_ZOO document](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md).

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md). In particular, I don't know __how__ you measure the fps.

The fps for models in the model zoo is measured by `train_net.py --eval-only`.

**Comment by nmoutinho** [comment]
Thank you for your reply.

--

## To Reproduce

1. what changes you made / what code you wrote

I've created custom code in /demo folder named test_inference.py (adapted from demo.py) which runs the model for 1000 images placed in a directory named /images_dir:

`# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
import argparse
import glob
import multiprocessing as mp
import os
import time
import cv2
import tqdm
import numpy as np

from detectron2.config import get_cfg
from detectron2.data.detection_utils import read_image
from detectron2.utils.logger import setup_logger

from predictor import VisualizationDemo

# constants
WINDOW_NAME = "COCO detections"


def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    # Set score_threshold for builtin models
    cfg.MODEL.RETINANET.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = args.confidence_threshold
    cfg.freeze()
    return cfg


def get_parser():
    parser = argparse.ArgumentParser(description="Detectron2 Demo")
    parser.add_argument(
        "--config-file",
        default="configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument("--webcam", action="store_true", help="Take inputs from webcam.")
    parser.add_argument("--video-input", help="Path to video file.")
    parser.add_argument("--input", nargs="+", help="A list of space separated input images")
    parser.add_argument(
        "--output",
        help="A file or directory to save output visualizations. "
        "If not given, will show output in an OpenCV window.",
    )

    parser.add_argument(
        "--confidence-threshold",
        type=float,
        default=0.5,
        help="Minimum score for instance predictions to be shown",
    )
    parser.add_argument(
        "--opts",
        help="Modify model config options using the command-line",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser


if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)
    args = get_parser().parse_args()
    logger = setup_logger()
    logger.info("Arguments: " + str(args))

    cfg = setup_cfg(args)

    demo = VisualizationDemo(cfg, parallel=False)

    for i in range(1000):
        start_time = time.time()
        img_dir = "/images_dir/" + "{}".format(i + 100).zfill(4) + ".jpg"
        img = cv2.imread(img_dir)
        scale_factor = 1.
        img = cv2.resize(img, (0,0), fx=1./scale_factor, fy=1./scale_factor)

        time1 = time.time()
        print("preparation",time.time() - start_time)

        predictions, visualized_output = demo.run_on_image(img)
        print("inference", time.time() - time1)
        logger.info("{}: detected {} instances in {:.2f}s, {}fps".format(i, 0, time.time() - start_time, 1./(time.time() - start_time)))

        cv2.imshow("img", visualized_output.get_image()[:, :, ::-1])
        cv2.waitKey(1)
`

Note: I've commented the pos-processing code in the predictor.py (lines 49 to 64) in order to measure only the inference time.

2. what command you run

The command I run is:

`python3.6 demo/test_inference.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl`

3. what you observed (full logs are preferred)

I am measuring the inference time for 720p images and getting an average of ~0.11s/image, which is different from the one in model zoo. The output of the program for some images:

`preparation time 0.00871729850769043 s
inference time 0.0990748405456543 s
[10/17 17:07:42 detectron2]: 3: detected 0 instances in 0.11s, 9.275411547205195fps
preparation time 0.008713960647583008 s
inference time 0.10476160049438477 s
[10/17 17:07:42 detectron2]: 4: detected 0 instances in 0.11s, 8.810841128562997fps
preparation time 0.009654521942138672 s
inference time 0.10262203216552734 s
[10/17 17:07:43 detectron2]: 5: detected 0 instances in 0.11s, 8.904782629926308fps
preparation time 0.009800434112548828 s
inference time 0.10435056686401367 s
[10/17 17:07:43 detectron2]: 6: detected 0 instances in 0.11s, 8.758679736214537fps
preparation time 0.009174108505249023 s
inference time 0.10106396675109863 s
[10/17 17:07:43 detectron2]: 7: detected 0 instances in 0.11s, 9.069510576004083fps
preparation time 0.008594751358032227 s
inference time 0.08986425399780273 s
[10/17 17:07:43 detectron2]: 8: detected 0 instances in 0.10s, 10.154519571575216fps
preparation time 0.008659124374389648 s
inference time 0.09723305702209473 s
[10/17 17:07:43 detectron2]: 9: detected 0 instances in 0.11s, 9.441867166114394fps
preparation time 0.008728981018066406 s
inference time 0.09248065948486328 s
[10/17 17:07:43 detectron2]: 10: detected 0 instances in 0.10s, 9.878433884764668fps`

## Expected behavior

(1) You're unable to reproduce the results documented in detectron2 model zoo.

I am unable to reproduce the results in model zoo. I was expecting to reach at least 20fps but for some reason, I am not even able to reach 10fps (only when the pos-processing code is commented).

## Environment

---------------------  -----------------------------------------------------------
Python                 3.6.8 (default, May  7 2019, 14:58:50) [GCC 5.4.0 20160609]
Detectron2 Compiler    GCC 5.4
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0
PyTorch Debug Build    False
CUDA available         True
GPU 0                  GeForce GTX 1080 Ti
Pillow                 6.2.0
cv2                    4.1.1
---------------------  -----------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
You benchmarked the time needed to make predictions and visualize them. The visualization takes some time as well.

**Comment by nmoutinho** [comment]
I am measuring the inference time right before visualization, so visualization is not affecting the measurement, as you can see in this code snippet:

```
start_time = time.time()
img_dir = "/images_dir/" + "{}".format(i).zfill(4) + ".jpg"
img = cv2.imread(img_dir)
scale_factor = 1.
img = cv2.resize(img, (0,0), fx=1./scale_factor, fy=1./scale_factor)

time1 = time.time()
print("preparation",time.time() - start_time)

predictions, visualized_output = demo.run_on_image(img)
print("inference", time.time() - time1)
logger.info("{}: detected {} instances in {:.2f}s, {}fps".format(i, 0, time.time() - start_time, 1./(time.time() - start_time)))

        cv2.imshow("img", visualized_output.get_image()[:, :, ::-1])
        cv2.waitKey(1)
```

**Comment by ppwwyyxx** [comment]
` demo.run_on_image` does the visualization (it computes "visualized_output")

**Comment by nmoutinho** [comment]
You are right ;) That's why I've commented the pos-processing code that computes the "visualized_output" in the /demo/predictor.py file (lines 49 to 64) in order to measure only the inference time.

**Comment by ppwwyyxx** [comment]
Sorry for the confusion. I did not see this change. I'll take a closer look and run some benchmarks.

**Comment by nmoutinho** [comment]
No problem ;) I hope you can help me run this at ~21fps for 720p images. Thanks for your help.

**Comment by ppwwyyxx** [comment]
Btw, the resolution does not affect the speed much, because all images are resized first. You can see #73 on how to disable this behavior (set the config to 0).

I did get reasonable speed by running 
```
$ python tools/train_net.py --num-gpus 1 --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --eval-only MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
```
this gives me 0.074 s/img on a GTX1080Ti.

The difference from your run is mainly at preprocessing: your benchmark will include time to resize the input image, as well as transpose the image to pytorch-style (https://github.com/facebookresearch/detectron2/blob/ed6105be2d3001376beab419c721289fe22bb1de/detectron2/engine/defaults.py#L172-L173). These time are excluded in the above command. Although I think these shouldn't be slow.

**Comment by nmoutinho** [comment]
I've set the input size to 0 in the cfg file as mentioned in #73 but I am getting the same error `ValueError: height and width must be > 0`. Is there any other way to disable the initial preprocessing?

**Comment by nmoutinho** [comment]
I've applied the changes as in this [fix](https://github.com/ppwwyyxx/detectron2/commit/065ab259f2ac16a583f6a749aa95f4d7d5c39831) in order to disable the resize but I am still getting 10fps. Could you please try running the following code on 720p images to see if you can reach the 0.074 s/img mark?

```
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
import argparse
import glob
import multiprocessing as mp
import os
import time
import cv2
import tqdm
import numpy as np

from detectron2.config import get_cfg
from detectron2.data.detection_utils import read_image
from detectron2.utils.logger import setup_logger

from predictor import VisualizationDemo

# constants
WINDOW_NAME = "COCO detections"


def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    # Set score_threshold for builtin models
    cfg.MODEL.RETINANET.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = args.confidence_threshold
    cfg.freeze()
    return cfg


def get_parser():
    parser = argparse.ArgumentParser(description="Detectron2 Demo")
    parser.add_argument(
        "--config-file",
        default="configs/quick_schedules/e2e_mask_rcnn_R_50_FPN_inference_acc_test.yaml",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument("--webcam", action="store_true", help="Take inputs from webcam.")
    parser.add_argument("--video-input", help="Path to video file.")
    parser.add_argument("--input", nargs="+", help="A list of space separated input images")
    parser.add_argument(
        "--output",
        help="A file or directory to save output visualizations. "
        "If not given, will show output in an OpenCV window.",
    )

    parser.add_argument(
        "--confidence-threshold",
        type=float,
        default=0.5,
        help="Minimum score for instance predictions to be shown",
    )
    parser.add_argument(
        "--opts",
        help="Modify model config options using the command-line",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser

if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)
    args = get_parser().parse_args()
    logger = setup_logger()
    logger.info("Arguments: " + str(args))

    cfg = setup_cfg(args)

    demo = VisualizationDemo(cfg, parallel=False)

    start_time = time.time()
    img = cv2.imread("[[INSERT_IMAGE_PATH]]")

    time1 = time.time()
    print("preparation time",time.time() - start_time, "s")

    predictions, visualized_output = demo.run_on_image(img)
    print("inference time", time.time() - time1, "s")
    logger.info("{:.2f}s, {}fps".format(time.time() - start_time, 1./(time.time() - start_time)))
```

**Comment by ppwwyyxx** [comment]
First, your code is not the correct way to benchmark. The inference should run in a loop, where the time for the first few iterations are ignored because they may be typically slower depend on your environment.
Running `DefaultPredictor` on 1080p images does give me 0.8~0.9 s / im on 1080Ti, slightly slower than the benchmark I showed above. The reason is because resizing the input image using the Pillow library is slow, and is not considered part of the model time.
We are planning to replace Pillow by other libraries.

**Comment by shidi518** [comment]
I change the 
`INPUT:
  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 0`
I do increase the inference time. From 1.6 it/s to 2.5it/s.But it still very slow. I don't know how to increase the inference time. I want to know if I can use tensorRt to increase the inference time.
The input video frame size is 480p. The model I used is `mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl`.
Hope you can give me some advice.
Thank you very much

**Comment by ppwwyyxx** [comment]
Closing as there hasn't been a report of slower speed using the correct benchmark method `train_net.py --eval-only`.
