### ISSUE TITLE
how to remove pred_masks of class

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1061]
i seen the detectron2.structures.instances
know to remove the field called `name`     
but how to remove  one of them?

thank you

**Comment by ppwwyyxx** [comment]
I don't understand exactly what do you want to remove from it. But `pred_masks` as the [document](https://detectron2.readthedocs.io/tutorials/models.html#model-output-format) says is a pytorch tensor, and pytorch documentation will have information on how to do anything about a pytorch tensor.
