### ISSUE TITLE
how to visualize the inference result of PointRend which trained on a custom dataset

### ISSUE THREAD

**Issue by crissallan** [facebookresearch/detectron2#1066]
How to visualize the inference results of PointRend?
Hi, I recently train the PointRend model on a cutomized dataset. The training process works fine, however, when I tried to do inference on some images and visualize the result, I met an Error as below:

##assert predictions.has("pred_masks"), "ColorMode.IMAGE_BW requires segmentations"
##AssertionError: ColorMode.IMAGE_BW requires segmentations 

why the "prediction" object doesn't has a 'pred_mask' attribute?
*********
The inference code is basicly followed the Colab Notebook of the Detectron2 Tutorial. The inference code is shown below:
*********

if __name__ == "__main__":

    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    cfg = set_up(args)
    cfg = get_cfg()
    cfg.MODEL.WEIGHTS = os.path.join('./output', "model_final.pth")
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7
    cfg.DATASETS.TEST = ("digisky_val",)
    predictor = DefaultPredictor(cfg)
    val_dataset_dicts = get_digisky_dicts('/home/digisky/HuYalun_Projects/DATA/down_annote')

    for d in val_dataset_dicts:
        img = cv2.imread(d["file_name"])
        # outputs is a dict, key is "instances", value is "<class 'detectron2.structures.instances.Instances'>"
        outputs = predictor(img)

        v = Visualizer(img[:, :, ::-1], metadata=val_meta_data, scale=0.8, instance_mode=ColorMode.IMAGE_BW)
        v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
        cv2.imshow('result', v.get_image()[:, :, ::-1])
        cv2.waitKey(1)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ppwwyyxx** [comment]
Closing as there is no response.
