### ISSUE TITLE
Sorry to disturb you

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1068]
Sorry to disturb you, we noticed that you implemented the Cascade R-CNN with multiscale training / inference, a stronger backbone (ResNeXt-152), mask supervision, etc. This enhanced Cascade R-CNN surpassed SNIP by 5.2 points. Can You upload this trained weight file in the model zoo?

**Comment by ppwwyyxx** [comment]
Please be more clear which model you are talking about.

**Comment by limengfei3675** [comment]
> Please be more clear which model you are talking about.

![image](https://user-images.githubusercontent.com/33457812/77043389-68d7cb00-69f8-11ea-8bfb-a20deedcfba3.png)
This image was taken from the paper Cascade R-CNN: High Quality Object Detection and Instance Segmentation. I refer to the Cascade R-CNN ∗ ⋆ in the bottom of the image. Can you upload training weights for this model?

**Comment by limengfei3675** [comment]
I refer to Cascade R-CNN∗⋆  from the paper "Cascade R-CNN: High Quality Object Detection and Instance Segmentation", the most advanced model you have proposed. Can you upload training weights for this model?

**Comment by ppwwyyxx** [comment]
We did not write the paper, so it's not a model we proposed. So we cannot upload its weights.
