### ISSUE TITLE
need for speed: RotatedBoxes edition

### ISSUE THREAD

**Issue by cbasavaraj** [facebookresearch/detectron2#1070]
Hi, 
Thanks to @ppwwyyxx for [this post](https://github.com/facebookresearch/detectron2/issues/21#issuecomment-595522318) on [Issue 21](https://github.com/facebookresearch/detectron2/issues/21) which helped me get started. I just have a question now on the speed for training / inference with rotated boxes. 

With seven angles `ANGLES: [[-90, -60, -30, 0, 30, 60, 90]]`, I see that training is 3x slower than the simple faster-RCNN with just one angle `ANGLES: [[0]]`. Inference is taking ~170 ms as opposed to ~100 ms. 

Anyone else who's working with RotatedBoxes, do you have similar numbers? Thanks

**Comment by ppwwyyxx** [comment]
As you know we do not have official configs/models for Rotated R-CNN, and therefore no official speed numbers we can provide.
