### ISSUE TITLE
How to combine detectron2 with tracking problems?

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1071]
Can I use detectron2 in problem of object segmentation while tracking?
I'm working on a project of tracking and segment custom object, like in this project:
https://github.com/foolwood/SiamMask
![687474703a2f2f7777772e726f626f74732e6f782e61632e756b2f7e7177616e672f5369616d4d61736b2f696d672f5369616d4d61736b5f64656d6f2e676966](https://user-images.githubusercontent.com/25927039/77086217-dc1d1500-69d7-11ea-87a7-d791f233d928.gif)
So is there anything related between detectron2 and this task?
Or may I build another project on top of detectron2?
What references should I read?
Is detectron2 model just work on discrete frames? 
Do all the detectron2 model use any temporal information in a video?
Any recommendations is appreciated. Thanks!

**Comment by ppwwyyxx** [comment]
> Or may I build another project on top of detectron2?

It seems reasonable.

> What references should I read?

We only answer questions specific to detectron2.

> Is detectron2 model just work on discrete frames?

Yes.

> Do all the detectron2 model use any temporal information in a video?

No video is used.
