### ISSUE TITLE
why images are padded in the function ' from_tensors', but don't transform the boxes and semseg gt?

### ISSUE THREAD

**Issue by Anikily** [facebookresearch/detectron2#1072]
why images are padded in the function ' from_tensors', but don't transform the boxes and semseg gt?

**Comment by Anikily** [comment]
I think its more specific to put this step in the datamapper function?

**Comment by Anikily** [comment]
Are the image_size of roi_heads results equal to the image size before padding or the original size before augmented?

**Comment by Anikily** [comment]
I have found out the reason

**Comment by cloudfool** [comment]
Could you please explain to me ? I have also met this question.
