### ISSUE TITLE
Model Sharding/Parallelism

### ISSUE THREAD

**Issue by ad12** [facebookresearch/detectron2#1078]
Is model parallelism (sharding) supported? See [docs](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#combine-ddp-with-model-parallelism) for more info

**Comment by ppwwyyxx** [comment]
Pytorch supports model parallelism so you can use it when implementing new models with detectron2.

I don't know what it means for detectron2 to support model parallelism - we most likely would not include any models with sharding inside because how to shard the model should be defined by users.
