### ISSUE TITLE
pycocotools not installing

### ISSUE THREAD

**Issue by caseybasichis** [facebookresearch/detectron2#1080]
Following the instructions, i get this error message:

    pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ppwwyyxx** [comment]
Unrelated to detectron2.
You need to install python headers.
