### ISSUE TITLE
Is there a way to do cross validation or leave one out validation with detectron2

### ISSUE THREAD

**Issue by ciaobladoo** [facebookresearch/detectron2#1081]
I have a relatively small dataset of bbox labels for object detection task and I am thinking of doing leave-one-out validation to evaluation the generalizability. Is there a convinient way of using existing detectron2 modules to calculate, say the mAP for leave-one-out validation?

**Comment by ppwwyyxx** [comment]
There is no existing code in detectron2 that does this.
