### ISSUE TITLE
how to remove one of the instances

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1082]
i use pred_mask to know what kind of instances is overlapping, and how can i remove it?
i read structures.instances only can remove field called `name` not instances.

**Comment by ppwwyyxx** [comment]
You need to create a new `Instances` with new values for the fields.

**Comment by ppwwyyxx** [comment]
`new_instances = old_instances[indices]` can keep those selected by by `indices` (an integer tensor or a boolean mask tensor).

**Comment by alanotmt** [comment]
> `new_instances = old_instances[indices]` can keep those selected by by `indices` (an integer tensor or a boolean mask tensor).

sorry, but how to create a new Instances ?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances
