### ISSUE TITLE
How to deal with binary numpy format mask?

### ISSUE THREAD

**Issue by YangHongCCNU** [facebookresearch/detectron2#1086]
## ❓ How to deal with binary numpy format mask?

I tried to use a custom dataset from [matterport's shape dataset](https://github.com/matterport/Mask_RCNN/blob/master/samples/shapes/shapes.py)
the mask format is binary numpy, I attempted to convert my segmentation mask of 0s and 1s into RLE format by `pycocotools.mask.encode(np.asarray(mask, order="F"))`, but it seems 'BoxMode.XYXY_REL' mode is not supported, 
```
     68             BoxMode.XYXY_REL,
     69             BoxMode.XYWH_REL,
---> 70         ], "Relative mode not yet supported!"
     71 
     72         if from_mode == BoxMode.XYWHA_ABS and to_mode == BoxMode.XYXY_ABS:
AssertionError: Relative mode not yet supported!
```
How can I deal with this situation? 
Do I need to transform my mask into a list of polygons and how can I do that?

**Comment by ppwwyyxx** [comment]
As the error says, relative box mode is not yet supported and you should not use them.

If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
