### ISSUE TITLE
How do I get average precision metrics for box proposals?

### ISSUE THREAD

**Issue by nihal-rao** [facebookresearch/detectron2#1087]
I'm using a Region proposal Network (**rpn_R_50_FPN_1x.yaml** ) as an object detector (my dataset contains only one class). When using inference_on_dataset as follows :
```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("data_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "data_val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```
I get only average recall metrics. Any pointers on how to get average precision metrics as well?

**Comment by ppwwyyxx** [comment]
There is no such feature and you can use https://detectron2.readthedocs.io/tutorials/evaluation.html to implement any evaluation metrics you need.

It's uncommon to use average precision for RPN so we will not include this feature.
