### ISSUE TITLE
TypeError: len() of unsized object When using COCOEvaluator

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#1088]
Hello,
I trained a Keypoint R-CNN model on a custom dataset.
After it was done training I tried using the COCOEvaluator as implemented in the colab notebook

```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "balloon_val")
inference_on_dataset(trainer.model, val_loader, evaluator)`
```

it seems to be workingm printing this: 
```
Start inference on 21 images
inference done 11/21. 0.4591 s / img. ETA=0:00:04
```

Until it returns this error: 
```
assert len(coco_eval.params.kpt_oks_sigmas) == num_keypoints, (
TypeError: len() of unsized object
```

I made sure to set up cfg.TEST.KEYPOINT_OKS_SIGMAS = Num of keypoints in my model (16). 

Did this happen to anyone? Any suggestions?

Thanks!

**Comment by ppwwyyxx** [comment]
Please see what KEYPOINT_OKS_SIGMAS  is https://detectron2.readthedocs.io/modules/config.html#config-references and set it properly.
