### ISSUE TITLE
Promotion of  “NUM_CONV=4,NUM_FC=1”  in mask rcnn ROI_BOX_HEAD when using SyncBN ？

### ISSUE THREAD

**Issue by nemonameless** [facebookresearch/detectron2#109]
Why set “NUM_CONV=4,NUM_FC=1”  in mask rcnn ROI_BOX_HEAD when using "SyncBN"？
Is the promotion due to more convolutions？
Thanks.

**Comment by ppwwyyxx** [comment]
As said in the model zoo:
> (Note: The baseline uses 2fc head while the others use 4conv1fc head. According to the GroupNorm paper, the change in head does not improve the baseline by much)

The mmdet paper https://arxiv.org/abs/1906.07155 has more detailed analysis on this topic.
