### ISSUE TITLE
Thanks very much. 

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1090]
Thanks very much. How many AP (50) and AP (0.50: 0.95) corresponding to the config file cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml configured on the coco dataset can reach? ? ?

**Comment by ppwwyyxx** [comment]
See model zoo https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#how-to-read-the-tables
