### ISSUE TITLE
custom_dataset using train_net.py

### ISSUE THREAD

**Issue by Kevin-Delnoije** [facebookresearch/detectron2#1093]
Hey I succesfully added a custom dataset in a jupyter notebook using the steps below.
(mostly following the balloon tutorial notebook)
 * define custom_function to create list[dict]
 * DatasetCatalog.register(name, lambda: custom_function(dirname) )
 * MetadataCatalog.get(name)
 * add train/test to config
 * instantiate DefaultTrainer(cfg) 
 
Now i am trying to move the code out of a jupyter notebook into a similar training script as
[train_net.py](https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py)
the confusing part for me is where the coco/lvis/pascal are normally registered and what setup magic is hidden behind ```default_setup(cfg, args)```

It is possible to use the same steps as in the notebook, but if possible I would like to modify the ```train_net.py``` as little as possible so i can enjoy the  nice default settings :)

**Comment by ppwwyyxx** [comment]
You can register the dataset in `train_net.py` the same way as in the notebook - I'm not sure what exactly you're trying to ask.

`default_setup` is documented in the API docs: https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.default_setup

**Comment by Kevin-Delnoije** [comment]
I don't know how the coco dataset is registered in train_net.py and i would like to understand that

**Comment by ppwwyyxx** [comment]
It's automatically registered by default by detectron2 at https://github.com/facebookresearch/detectron2/blob/125e4ff9d2e628a2d9db77e787570093c1ecf522/detectron2/data/datasets/builtin.py#L217
