### ISSUE TITLE
Polygonmask of the cityscape dataset 

### ISSUE THREAD

**Issue by abhigoku10** [facebookresearch/detectron2#1094]
@likethesky @Celebio @colesbury hi how to obtain the polygon mask from cityscapes dataset when i try to visualize the data after generating mask i am getting like the following image 
![image](https://user-images.githubusercontent.com/22094053/77471633-a72a1b80-6e38-11ea-8120-99ad89c73d34.png)

**Comment by ppwwyyxx** [comment]
No indication that it is related to detectron2. Closing.
