### ISSUE TITLE
Optimize demo.py

### ISSUE THREAD

**Issue by Auth0rM0rgan** [facebookresearch/detectron2#1096]
## 🚀 Feature

Thanks for the great work. Is there a plan to optimize the `demo.py` and `predictor.py`?

## Motivation & Examples

To achieve higher FPS in the real scenarios.     

## Note

It's really hard to achieve ~25-30 fps with Detectron2 even by using lightweight pretrained models.
Yolact (https://github.com/dbolya/yolact/blob/master/eval.py) has visualization tools that optimized very well to achieve high fps. It would be nice to reach ~25fps with detectron2 as well!

**Comment by ppwwyyxx** [comment]
Thanks. In our context, "real scenarios" do not use python, so we currently don't have much motivation to make demo.py faster.
Plans on releasing faster models are tracked in separate issues https://github.com/facebookresearch/detectron2/issues/696. For now I'm not sure when they can be released.

**Comment by Auth0rM0rgan** [comment]
@ppwwyyxx, you are completely right but it would be nice to achieve ~25Fps with python as well :)
