### ISSUE TITLE
Loss became infinite or NaN

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1099]
I focal loss the FPN features with segmentation ground truth. But get loss infinite error.
`FloatingPointError: Loss became infinite or NaN at iteration=2!
loss_dict = {'focal_loss': tensor(476790.9375, device='cuda:1', grad_fn=<AddBackward0>), 'loss_rpn_cls': tensor(nan, device='cuda:1', grad_fn=<MulBackward0>), 'loss_rpn_loc': tensor(inf, device='cuda:1', grad_fn=<MulBackward0>)}`
My guess is that the gradient is too large and the rpn changes too much. So I want to know hou to use pretrained RPN module and keep constant while training other parameters.

**Comment by Yoline777** [comment]
I try to remove RPN loss. But RPN become unused paremeter.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
