### ISSUE TITLE
ImportError: No module named 'fvcore'

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#11]
```
detectron2/detectron2/checkpoint/model_zoo.py", line 3, in <module>
    from fvcore.common.file_io import PathHandler, PathManager
ImportError: No module named 'fvcore'

```

**Comment by lzrobots** [comment]
`pip install git+https://github.com/facebookresearch/fvcore.git`

**Comment by jinfagang** [comment]
@lzrobots  It seems not support 3.5 ubuntu 16.04? Some syntax error happened.

**Comment by jinfagang** [comment]
@lzrobots  It seems not support 3.5 ubuntu 16.04? Some syntax error happened.

**Comment by ppwwyyxx** [comment]
Please see [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#requirements).
It requires fvcore and python >= 3.6

**Comment by JacobAtExp4531** [comment]
> `pip install git+https://github.com/facebookresearch/fvcore.git`

i have installed fvcore using the above link, still showing error message as `ModuleNotFoundError: No module named 'fvcore.common.registry'`

**Comment by ppwwyyxx** [comment]
You need to update it with `pip install -U git+https://github.com/facebookresearch/fvcore.git`

**Comment by AlexisLapeze** [comment]
> You need to update it with `pip install -U git+https://github.com/facebookresearch/fvcore.git`

Hi everyone ! I do this but i have the same error :/

 `Traceback (most recent call last):
  File "trainer.py", line 1, in <module>
    from detectron2.data.datasets import register_coco_instances
  File "/home/alexis/Bureau/detectron2/detectron2/data/__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
  File "/home/alexis/Bureau/detectron2/detectron2/data/transforms/__init__.py", line 2, in <module>
    from .transform import *
  File "/home/alexis/Bureau/detectron2/detectron2/data/transforms/transform.py", line 6, in <module>
    from fvcore.transforms.transform import HFlipTransform, NoOpTransform, Transform
ModuleNotFoundError: No module named 'fvcore'`

**Comment by prameshbajra** [comment]
@AlexisLapeze Hi,

Did you solve it? If yes, can you please share how you did it?
