### ISSUE TITLE
How to ignore prediction masks if doing simple bounding box object detection? 

### ISSUE THREAD

**Issue by sidsathi** [facebookresearch/detectron2#110]
I have trained a model with RetinaNet and when I try to do inference, I get the following error. 
![image](https://user-images.githubusercontent.com/16242989/67047059-6807d980-f0e6-11e9-8717-61ae34f0b332.png)
I don't want a segmentation mask for my images, hence my usage of RetinaNet. How can I work around this issue?

**Comment by ppwwyyxx** [comment]
`IMAGE_BW` mode is unsupported for bounding box models. Removing that line would work.
I'll make the error messages more clear.

**Comment by sidsathi** [comment]
Ahhh go it thank you!
