### ISSUE TITLE
How to increase recall of fasterrcnn predictions in mask_rcnn_R_101_FPN_3x model.

### ISSUE THREAD

**Issue by wkoziej** [facebookresearch/detectron2#1100]
## ❓Increase recall of fasterrcnn predictions
Hi everyone. Thanks for great project. 

To the point...

I've trained model based on COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml configuration and got predictions on my test set with where all (?) are almost 100% "sure". The scores are >= 0.99. So precision is great (almost 100%) but the recall is poor.

I've tried to change 
MODEL.RPN.NMS_THRESH = 0.1 (during training) and got lower loss (156k+ steps)
![image](https://user-images.githubusercontent.com/138819/77631938-93240e00-6f4d-11ea-9084-32ea923f7806.png). I've also tried MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.001 during predictions.

But results are almost the same (very good precision and poor recall). 

How should I configure training/prediction to get better recall (and of course not so good precision)? 

Thanks in advance.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
