### ISSUE TITLE
flop_count_operators for MaskRCNN models

### ISSUE THREAD

**Issue by mauann** [facebookresearch/detectron2#1101]
## 🚀 Feature

detectron2/utils/analysis.py function `flop_count_operators` should work also for MaskRCNN.

## Motivation & Examples

In detectron2/utils/analysis.py there is a function for the evaluation of the number of FLOP. For now it seems implemented only for FasterRCNN and RetinaNet but it would be useful to make it work for every Detectron2 model.

**Comment by ppwwyyxx** [comment]
It works for Mask R-CNN.
If you think it's not, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
