### ISSUE TITLE
We want to train cascade_mask_rcnn_R_50_FPN_3x.yaml on COCO with eight 2080Ti GPUs. What parameters need to be modified, such as learning rate?

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1103]
We want to train cascade_mask_rcnn_R_50_FPN_3x.yaml on COCO with 8 2080Ti GPUs. What parameters need to be modified, such as learning rate?

**Comment by ppwwyyxx** [comment]
As https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#introduction says, 
> Running tools/train_net.py with this config file and 8 GPUs will reproduce the model.
