### ISSUE TITLE
Explain PreciseBN internals

### ISSUE THREAD

**Issue by AlexFridman** [facebookresearch/detectron2#1104]
Could you please explain what this [code](https://github.com/facebookresearch/detectron2/blob/d1afdf4b7fc2efd58d342c11a3882a10f16f04d1/detectron2/engine/hooks.py#L414) does?

```python
for num_iter in itertools.count(1):
    if num_iter % 100 == 0:
        self._logger.info(
            "Running precise-BN ... {}/{} iterations.".format(num_iter, self._num_iter)
        )
```

Regards, Alex

**Comment by ppwwyyxx** [comment]
See https://github.com/facebookresearch/fvcore/blob/master/fvcore/nn/precise_bn.py
