### ISSUE TITLE
ResNet backbone and DataParallel

### ISSUE THREAD

**Issue by jsaric** [facebookresearch/detectron2#1105]
So, I wanted to use GeneralizedRCNN class in some custom setup with basic DataParallel wrapping. 

I ran into a couple of problems, so you may want to check it.

1. In GeneralizedRCNN pixel_mean and pixel_std are not registered as buffers,
so when Pytorch replicates the model these tensors stay at the original gpu device,
and later breaks the parallel execution because of device missmatch.

2. In ResNet backbone in the constructor we have something like this:
```
stage = nn.Sequential(*blocks)
self.add_module(name, stage)
stages_and_names.append((stage, name))
```
and later in the forward method:
```
for stage, name in self.stages_and_names:
    x = stage(x)
    if name in self._out_features:
        outputs[name] = x
```
Note that in the forward pass we use stage module referenced in the `self.stages_and_names` list,
and not the module referenced directly in the self object.
This, again, breaks the parallel execution because in the replicas we reference the module which is on the original gpu, and not the one belonging to the replica. Thus, I get the error that the weights and inputs are not on the same device. 
This is just my understanding of the issue, and I could be easily wrong.
Quick fix could look like this:
```
for _, name in self.stages_and_names:
    stage = getattr(self, name)
    x = stage(x)
```

I understand that detectron2 supports the distributed execution, but these changes could make it easier for other custom projects. I am not sure if my changes would break the original detectron2 distributed execution, but I think it should not.

Thank you for your time and effort.

**Comment by ppwwyyxx** [comment]
We currently do not plan to support DataParallel.
