### ISSUE TITLE
How to train heterogeneous dataset?

### ISSUE THREAD

**Issue by ferfera** [facebookresearch/detectron2#1106]
How to train heterogeneous dataset?

I want to train a custom dataset, but one of my classes doesn't have segmentation attributes, is it possible to train with half of my classes with segmentation and bounding box and the other half only with bounding box?

**Comment by ppwwyyxx** [comment]
You will need to customize the model code (https://detectron2.readthedocs.io/tutorials/write-models.html) in ROIHeads to handle such data.
