### ISSUE TITLE
Using Custom Data Loader for Augmentation

### ISSUE THREAD

**Issue by ncate** [facebookresearch/detectron2#1107]
Hello,

I've read #527 and #791 regarding implementing data augmentation and I've looked over the documentation at https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader.
However, I'm still confused as to where to implement my custom mapper. The mapper is as follows:
```
from detectron2.data import build_detection_train_loader
from detectron2.data import transforms as T
from detectron2.data import detection_utils as utils

def custom_mapper(dataset_dict):
    # Implement a mapper, similar to the default DatasetMapper, but with your own customizations
    dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below
    image = utils.read_image(dataset_dict["file_name"], format="BGR")
    transform_list = [T.Resize(1200,1200),
                      T.RandomFlip(prob=0.5, horizontal=True, vertical=True),
                      T.RandomContrast(0.8, 3),
                      T.RandomBrightness(0.8, 1.6),
                      ]
    
    image, transforms = T.apply_transform_gens(transform_list, image)
    dataset_dict["image"] = torch.as_tensor(image.transpose(2, 0, 1).astype("float32"))

    annos = [
        utils.transform_instance_annotations(obj, transforms, image.shape[:2])
        for obj in dataset_dict.pop("annotations")
    ]
    instances = utils.annotations_to_instances(annos, image.shape[:2])
    dataset_dict["instances"] = utils.filter_empty_instances(instances)
    return dataset_dict
```

Then my training routine I've taken from the detectron2 tutorial:
```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
# cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("acorn_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
# cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.0001  # pick a good LR
cfg.SOLVER.MAX_ITER = 800    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(label_dict.keys())  # only has one class (ballon)
cfg.OUTPUT_DIR = model_dir
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

I'm unclear where I need to specify the mapper as my custom mapper. In the docs there is the additional line:

`data_loader = build_detection_train_loader(cfg, mapper=custom_mapper)
`
Does this need to be included after the cfg parameters but before the trainer variable is defined?

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/data_loading.html#use-a-custom-dataloader

**Comment by ncate** [comment]
As I indicated in the question, I've read that page and am still unclear.

The page provides a link to the densepose training script. Do I simply need to include the new trainer class in my code, but adjust the mapper to my custom mapper? Something like this:

```
class Trainer(DefaultTrainer):

    @classmethod
    def build_test_loader(cls, cfg: CfgNode, dataset_name):
        return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapper(cfg, False))

    @classmethod
    def build_train_loader(cls, cfg: CfgNode):
        return build_detection_train_loader(cfg, mapper=custom_mapper(cfg, True))
```

**Comment by ppwwyyxx** [comment]
yes

**Comment by jianchaoci** [comment]
> As I indicated in the question, I've read that page and am still unclear.
> 
> The page provides a link to the densepose training script. Do I simply need to include the new trainer class in my code, but adjust the mapper to my custom mapper? Something like this:
> 
> ```
> class Trainer(DefaultTrainer):
> 
>     @classmethod
>     def build_test_loader(cls, cfg: CfgNode, dataset_name):
>         return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapper(cfg, False))
> 
>     @classmethod
>     def build_train_loader(cls, cfg: CfgNode):
>         return build_detection_train_loader(cfg, mapper=custom_mapper(cfg, True))
> ```
It is also unclear for me if the argumentation is execute even I have simply added this part in my code. Do you got the answer how can we verify if the argumentations is work?
 
 class Trainer(DefaultTrainer):
       def build_test_loader(cls, cfg: CfgNode, dataset_name):
       return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapper(cfg, False))

**Comment by morganOliveira2018** [comment]
@ncate @jianchaoci was wondering if you managed to implement the above code?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/c152862a18182544b9f41dac0519e87c5ff8ac6c/projects/PointRend/train_net.py#L102-L108 is one example that uses custom augmentations.

**Comment by robosina** [comment]
Hi @ppwwyyx, thanks for the help. I'm new to the detectron2 and would like to add blurring to the augmentation process. I've overridden the `build_train_loader` method and added a transform list that is used by the `DatasetMapper` as the below.
```
    @classmethod
    def build_train_loader(cls, cfg):
        transform_list = [T.RandomApply(T.RandomFlip(prob=0.5, horizontal=True, vertical=False), prob=1),
                                   ... # so on
                          ]

        data_loader = build_detection_train_loader(cfg,
                                                   mapper=DatasetMapper(cfg, is_train=True,
                                                                        augmentations=transform_list,
                                                                        use_instance_mask=True))
```
The detecton2 website provides some examples for custom augmentation (accessible via this [LINK](https://detectron2.readthedocs.io/en/latest/tutorials/augmentation.html)). In my first attempt, I created a class like the following in augmentation_impl.py

```
class MyBlur(Augmentation):
    def __init__(self):
        self._init(locals())
    def get_transform(self, image):
        image = cv2.resize(image,(300,300))
        h, w = image.shape[:2]
        return BlurTransform(image)
```

Which I have created a BlurTransform class in transform.py, which is inherited from Tranform, and in this class I have written apply_image method as follows:
```
    def apply_image(self, img: np.ndarray) -> np.ndarray:
            return cv2.blur(img,(5,5)) # just for example
```

Imported this class into augmentation_impl.py. Could you suggest a better approach? I think my approach is overkill. Thank you.

**Comment by ppwwyyxx** [comment]
`augmentations=[MyBlur()]` will be equivalent to `augmentations=[T.Resize((300, 300), BlurTransform()]`. So the class `MyBlur` doesn't seem needed.

Regarding imgaug, I just added an issue https://github.com/facebookresearch/detectron2/issues/3054 and discussions can continue there
