### ISSUE TITLE
How to detect person only by pretrained model?The mask part didn't show

### ISSUE THREAD

**Issue by yaodonggggggg** [facebookresearch/detectron2#1108]
The code runs good at all classes.I want to detect person only,so I changed the code in 

> detectron2/detectron2/utils/visualizer.py

line 337 to
`new_classes=[]`
`new_scores=[]`
        `ids=[]`
        `need_set=[0]`
        `for i,x in enumerate(classes):`
 `      `      ` ` `if int(x) in need_set:` 
`       `     `   ` `new_classes.append(int(x))`
`      `      `   ` `new_scores.append(scores[i])`
`     `   `  `     ` ids.append(i)`
        `boxes=boxes[ids] if boxes is not None else None`
        `labels = _create_text_labels(new_classes, new_scores, self.metadata.get("thing_classes", None))`
line 342 
`masks = np.asarray(predictions.pred_masks)`
to
`masks = np.asarray(predictions.pred_masks[ids])`

The bboxs of output show will,but the mask dispeared .
How should I change the code?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by yaodonggggggg** [comment]
> If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Maybe the detectron2'code that I used is too old,I download the newest code,then it works well.Thank you.
