### ISSUE TITLE
image size problem

### ISSUE THREAD

**Issue by kl720** [facebookresearch/detectron2#1109]
## Instructions To Reproduce the Issue:
i got a caffe2model from maskrcnn ,training the model with my own dataset,the origin image is 1920*1080, as the input which can have a good result,but when i change the image size,then the model can not verify the instance.
1. what changes you made (`git diff`) or what code you wrote
```
height, width = image.shape[:2]
        transform_gen = T.ResizeShortestEdge(
            [600, 600], 800
        )

        image = transform_gen.get_transform(image).apply_image(image)
```
2. what exact command you run:

def initCaffe2Model():
    global caffe2Model
    caffe2Model = Caffe2Model('', '')

    caffe2Model = caffe2Model.load_protobuf('../caffe2_model/')

    logger.info('init caffe2model success!!!!')
# 转换图片格式,符合模型参数定义
def processImg(image):
    batch_images = []
    batch_images.append(image)
    # batch_images.append(image1)

    batch_inputs = []
    for i in range(len(batch_images)):
        image = batch_images[i]
        height, width = image.shape[:2]
        transform_gen = T.ResizeShortestEdge(
            [600, 600], 800
        )

        image = transform_gen.get_transform(image).apply_image(image)

        # image = cv2.resize(image, (0, 0), fx=0.5, fy=0.5, interpolation=cv2.INTER_NEAREST)
        result = Image.fromarray(image)
        result.save('tt.jpg')
        image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))

        inputs = {"image": image, "height": height, "width": width}
        batch_inputs.append(inputs)
    return batch_inputs

app = flask.Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():
    # Initialize the data dictionary that will be returned from the view.
    data = {"success": False}

    # Ensure an image was properly uploaded to our endpoint.
    if flask.request.method == 'POST':
        if flask.request.files.get("image"):
            # 获取图片附属信息
            j_data = flask.request.form

            # Read the image in PIL format 图片字节流
            image = flask.request.files["image"].read()

            image = cv2.imdecode(np.frombuffer(image,np.uint8),cv2.IMREAD_COLOR)
            start_time = time.time()
            if  caffe2Model=='':
                initCaffe2Model()

            result = caffe2Model(processImg(image))
3. what you observed (including __full logs__):
```
<put logs here>
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
There is no guarantee that the model produces the same outputs given different input sizes.
So it's not an unexpected issue, therefore closing.
