### ISSUE TITLE
Is momentum used by default in DefaultTrainer?

### ISSUE THREAD

**Issue by nihal-rao** [facebookresearch/detectron2#1110]
I am using DefaultTrainer with **faster_rcnn_R_50_FPN_3x.yaml** as provided in the model zoo, without any changes.It does not set `SOLVER.MOMENTUM`.
However in the source code for `detectron2.solver.build_optimizer` I notice the optimizer is called as
`optimizer = torch.optim.SGD(params, cfg.SOLVER.BASE_LR, momentum=cfg.SOLVER.MOMENTUM)`

So if I do not set cfg.SOLVER.MOMENTUM, is momentum not used? Or, is some default value being used?

**Comment by Kevin-Delnoije** [comment]
https://detectron2.readthedocs.io/modules/config.html#config-references
at line 495 the momentum is defined.
Before training you can print the config and then you can see the default value aswell

**Comment by ppwwyyxx** [comment]
@Kevin-Delnoije is correct that a default value is defined there.
