### ISSUE TITLE
Train with PanopticSegmentation

### ISSUE THREAD

**Issue by danglive** [facebookresearch/detectron2#1111]
Hi, 
I would like to ask you the problem train with PanopticSegmentation. I have set the configuration for training with panoptic_fpn_R_101_3x.yaml. But it does not work:

_______________________________________________________________________
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"))
cfg.DATASETS.TRAIN = ("balloon_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
_________________________________________________________________________

The error is following as:

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1832         raise ValueError('Expected 2 or more dimensions (got {})'.format(dim))
   1833 
-> 1834     if input.size(0) != target.size(0):
   1835         raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
   1836                          .format(input.size(0), target.size(0)))

AttributeError: 'NoneType' object has no attribute 'size'

Could you explain this, please?

Thank you.

**Comment by ppwwyyxx** [comment]
`balloon_train` is not a panoptic segmentation dataset so you cannot train panoptic segmentation models on it.

**Comment by danglive** [comment]
> `balloon_train` is not a panoptic segmentation dataset so you cannot train panoptic segmentation models on it.

Hi,

I try to configure the COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml for training my dataset, but it does not work as InstanceSegmentation. The error that I have mentioned above "AttributeError: 'NoneType' object has no attribute 'size"

Is the PanopticSegmentation use only for the predictor without training?

Thanks.

**Comment by ppwwyyxx** [comment]
Then your dataset is probably like `balloon_train` and is not a panoptic segmentation dataset. 
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

The config can be used to train on COCO according to the model zoo.

**Comment by danglive** [comment]
Hi,
That means that I must convert the dataset format detectron2 to the format of panoptic segmentation dataset?
