### ISSUE TITLE
How to set run name in tensorboard when using DefaultTrainer?

### ISSUE THREAD

**Issue by Kevin-Delnoije** [facebookresearch/detectron2#1112]
When training a model using the DefaultTrainer object the metrics get stored  to the output folder.
I can see the metrics in tensorboard, however when i train multiple similar models (same output dir) they all have the same name "." and therefore no separation of the graphs.
I would like to replace the run name "." with date of model run so i can toggle between metrics.

I am using training code similar to ```train_net.py```

**Comment by ppwwyyxx** [comment]
Tensorboard uses directory names. You can put logs in different directories and run tensorboard on upper level directory.
