### ISSUE TITLE
How to use the trained model "model_final.pth"?

### ISSUE THREAD

**Issue by LuisEdMB** [facebookresearch/detectron2#1113]
Hi,

How could i use the trained model with the custom dataset? When I have finished training a model with a new dataset, a "model_final.pth" file is created.

How could I call or use that model, and use it on another notebook?

Thanks for the reply.

**Comment by ppwwyyxx** [comment]
The colab tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 shows how to use a model.
