### ISSUE TITLE
`GLIBCXX_3.4.20' not found when import DefaultTrainer; however there is no issue if `import cv2` first.

### ISSUE THREAD

**Issue by ciaobladoo** [facebookresearch/detectron2#1114]
2. what exact command you run:
`from detectron2.engine import DefaultTrainer`
3. what you observed (including __full logs__):
```
from detectron2 import _C
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```
However, this error does not happen if I do
`import cv2`
first.
## Environment:

----------------------  -----------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 14:55:04) [GCC 7.3.0]
numpy                   1.18.1
detectron2._C           failed to import
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0+cu92 @/home/fengc/anaconda2/envs/detectron2/lib/python3.8/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0                   Tesla V100-SXM2-16GB
CUDA_HOME               /usr/local/cuda-9.2
NVCC                    Cuda compilation tools, release 9.2, V9.2.88
Pillow                  6.2.2
torchvision             0.5.0+cu92 @/home/fengc/anaconda2/envs/detectron2/lib/python3.8/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70
cv2                     4.2.0
----------------------  -----------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues already.
