### ISSUE TITLE
How to increase batch size?

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1117]
I try to train my model with 8G GPU. But ran out of memory while set batch size larger. Is there a way to use small memory train large batch size? Is there a parameter can solve this like iter size in caffe?

**Comment by ppwwyyxx** [comment]
There isn't one in detectron2. You can find how to implement it with pytorch in pytorch forums.

**Comment by Yoline777** [comment]
` for i in range(num_iters):
 
            optimizer.zero_grad() 
            batch_loss_value = 0

            for m in range(M):
                  (images, labels, indices) = train_loader.next():
                   outputs = net(Variable(images.cuda()))
                   loss    = criterion(outputs, Variable(labels.cuda()))
                   loss.backward()
                  
                  batch_loss_value += loss.cpu().numpy()[0]

            optimizer.step()
            batch_loss_value = batch_loss_value/M`
This is a way to implement iter size. I want to confirm whether overwrite SimpleTrainer can achieve this in detectron2.

**Comment by ppwwyyxx** [comment]
It can.

Alternatively, the code of SimpleTrainer suggests you using a custom optimizer: https://github.com/facebookresearch/detectron2/blob/db1614e65110fb8594c43a9088295d027587ea5a/detectron2/engine/train_loop.py#L222-L227
