### ISSUE TITLE
Error on loading weights after training on custom dataset

### ISSUE THREAD

**Issue by lalit-mohan** [facebookresearch/detectron2#112]
After training on a custom dataset and saving weights on Colab, I get an error when loading that pth file. I used mask_rcnn_R_50_FPN_3x.yaml. 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-e5d0fe69c4b9> in <module>()
      4 # Find a model from detectron2's model zoo. You can either use the https://dl.fbaipublicfiles.... url, or use the following shorthand
      5 cfg.MODEL.WEIGHTS = "/content/drive/My Drive/checkpoint2.pth"
----> 6 predictor = DefaultPredictor(cfg)
      7 outputs = predictor(im)

5 frames
/content/detectron2_repo/detectron2/engine/defaults.py in __init__(self, cfg)
    147 
    148         checkpointer = DetectionCheckpointer(self.model)
--> 149         checkpointer.load(cfg.MODEL.WEIGHTS)
    150 
    151         self.transform_gen = T.ResizeShortestEdge(

/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py in load(self, path)
     99             assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
    100 
--> 101         checkpoint = self._load_file(path)
    102         self._load_model(checkpoint)
    103         for key, obj in self.checkpointables.items():

/content/detectron2_repo/detectron2/checkpoint/detection_checkpoint.py in _load_file(self, filename)
     40                 return {"model": data, "__author__": "Caffe2", "matching_heuristics": True}
     41 
---> 42         loaded = super()._load_file(filename)  # load native pth checkpoint
     43         if "model" not in loaded:
     44             loaded = {"model": loaded}

/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py in _load_file(self, f)
    184                 to torch.Tensor or numpy arrays.
    185         """
--> 186         return torch.load(f, map_location=torch.device("cpu"))
    187 
    188     def _load_model(self, checkpoint: Any):

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    424         if sys.version_info >= (3, 0) and 'encoding' not in pickle_load_args.keys():
    425             pickle_load_args['encoding'] = 'utf-8'
--> 426         return _load(f, map_location, pickle_module, **pickle_load_args)
    427     finally:
    428         if new_fd:

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    618     for key in deserialized_storage_keys:
    619         assert key in deserialized_objects
--> 620         deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
    621         if offset is not None:
    622             offset = f.tell()

RuntimeError: unexpected EOF, expected 2275604 more bytes. The file might be corrupted.
```
I wonder if I need a different config file. How do I get that or do I have to create one? 
Or is it that the weights are not saved properly, how do I save the weights then?

**Comment by ppwwyyxx** [comment]
As the log said, the file might be corrupted.

That's either some misoperation of a bug in colab, and unlikely to be related to detectron2.

**Comment by lalit-mohan** [comment]
Yes, thanks. Colab did output an incomplete file on download, used torch to save state_dict to drive first:
```
import torch
torch.save(predictor.model.state_dict(), '/content/drive/My Drive/Colab Notebooks/checkpoint.pth')
```

**Comment by zsc1220** [comment]
Hi @ppwwyyxx 
When I want to evaluate the model I trained , such as:
'python tools/train_net.py \
	--config-file configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml \
	--eval-only MODEL.WEIGHTS output/model_final.pth'
It has the following error , the same to run the demo/demo.py
![Uploading image.png…]()
`Traceback (most recent call last):
  File "tools/train_net.py", line 168, in <module>
    args=(args,),
  File "/home/zsc/pythoncode/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 134, in main
    cfg.MODEL.WEIGHTS, resume=args.resume
  File "/home/zsc/anaconda3/envs/car/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 164, in resume_or_load
    return self.load(path)
  File "/home/zsc/anaconda3/envs/car/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 102, in load
    checkpoint = self._load_file(path)
  File "/home/zsc/pythoncode/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 42, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/home/zsc/anaconda3/envs/car/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 188, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/home/zsc/anaconda3/envs/car/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/zsc/anaconda3/envs/car/lib/python3.6/site-packages/torch/serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.
`
Im sure my val datas's format are as same as train datas

**Comment by ppwwyyxx** [comment]
The checkpoint file is corrupted.

**Comment by zsc1220** [comment]
What shoul I do , It means I should download the checkpoint file again ？ @ppwwyyxx

**Comment by zsc1220** [comment]
Problem was solved , That's problem in the previous training . I just retrained again , and it works !
