### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by oguchi-ebube** [facebookresearch/detectron2#1124]
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-40-451cd212ba37> in <module>()
      6     ret, image = cap.read()
      7 
----> 8     hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
      9     #print(hsv)
     10     # fgmask = fbgb.apply(image)

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
i keep getting that error when i tried using background segmentation in detectron2 to just detect only actions on the field only without detecting anything outside the field .please any help?

**Comment by ppwwyyxx** [comment]
The image is read from opencv and the error comes from using the image with an opencv function. So it's unrelated to detectron2.

**Comment by oguchi-ebube** [comment]
error Traceback (most recent call last)
in ()
6 ret, image = cap.read()
7
----> 8 hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
9 #print(hsv)
10 # fgmask = fbgb.apply(image)

error when i tried using background segmentation in detectron2
