### ISSUE TITLE
Using Detectron2 for video object detection

### ISSUE THREAD

**Issue by oguchi-ebube** [facebookresearch/detectron2#1125]
How do i save the output video after the detection process as been completed in colab using oppencv?

Aslo how do i achieve background subtraction in detectron2 using OpenCV

**Comment by ppwwyyxx** [comment]
Detectron2 provides output format documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format.

What to do with the outputs (write them to a video or background subtraction) is up to users and no longer relevant to detectron2.
Visualizers (demonstrated in colab) may help converting the outputs to images.

**Comment by Surya20794** [comment]
Output video is detecting the object. 


!git clone https://github.com/facebookresearch/detectron2
!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.8 --output video-output.mkv --opts MODEL.WEIGHTS /content/output/model_final.pth
