### ISSUE TITLE
Running detectron from c++ using PyBind is 10x slower. Why?

### ISSUE THREAD

**Issue by antithing** [facebookresearch/detectron2#1126]
I am trying to integrate detectron2 into a c++ application. i am doing this by passing cv::Mat data through shared memory to python, and running the Python functions via PyBind11.

When I run the this function using a Python window, the function time is around 1 second for the first frame, then around 160 ms thereafter. 

Python 
```
def testRun():
	
	# load an image
	shmem = mmap.mmap(-1, ctypes.sizeof(TransferData.TransferData), "TransferDataSHMEM")
	data = TransferData.TransferData.from_buffer(shmem)
	m = np.zeros((data.h, data.w, 3), dtype = "uint8")
	m = getbg(m, data.frame)
	im = m.copy()

	start = time.time()
	# create config
	cfg = get_cfg()
	cfg.merge_from_file("D:/Deep/detectron2/configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")
	cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7  # set threshold for this model
	cfg.MODEL.WEIGHTS = "detectron2://COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl"
	predictor = DefaultPredictor(global_cfg)
	start = time.time()
	outputs = predictor(im)
	end = time.time()
	print(end - start)

```

When I run it from c++, using:

```
Py_SetProgramName(L"PYTHON");
py::scoped_interpreter guard{};
py::module py_test = py::module::import("Vert_py");

int64 t0 = cv::getTickCount();
//process
py::object result = py_test.attr("testRun")();
int64 t1 = cv::getTickCount();
double secs = (t1 - t0) / cv::getTickFrequency();
```
The time taken by detectron is the same, but the total time is around 3.5 seconds the first run, then 1.5 seconds thereafter.

Why is this?

Timing non-Detectron2 functions such as:

```
def timeIt():
	print ('hello')
	start = time.time()
	for i in range(50000000):
		i = i + 200
	end = time.time()
	print(end - start)

I see no difference in time when running from c++ or Python.

What could be happening here? 

```

**Comment by ppwwyyxx** [comment]
We can only support the speed of :
```
start = time.time()
outputs = predictor(im)
end = time.time()
```
everything else is not considered the speed of inference of detectron2, and therefore we can't answer questions about them.

also note that creating the predictor is slower, and the first time a predictor is used is slower. A predictor can be used multiple times.

**Comment by antithing** [comment]
Ah thank you! it is the `predictor = DefaultPredictor(global_cfg)` creation that is slowing me down.

Is it possible to store predictor globally somehow?

**Comment by ppwwyyxx** [comment]
You can store it in any way the language allows - that's not related to detectron2.

**Comment by mrfloor** [comment]
Hello @antithing, i'm looking to use detectron2 with c++ for a project, and arrived at the possibility of using pybind11 for the speed. I just wanted to ask if you managed to make it work. Thanks

**Comment by sabrabano0** [comment]
i have same question as @mrfloor 
did you managed it to speed up?

**Comment by mrfloor** [comment]
@sabrabano0 I managed to make it run in c++ with a python embedded. Sadly i had to drop the protect, but it was much faster than running detectron2 transformed to run in c++. Weirdly enough i couldn't get the same speeds as running it directly in python, but i didn't test it that much. If you are interested i could try to dig up the code i used.
