### ISSUE TITLE
p6 features not used by RoI head, even though they are passed to RPN

### ISSUE THREAD

**Issue by nihal-rao** [facebookresearch/detectron2#1127]
I'm using **faster_rcnn_R_50_FPN_3x.yaml**, the base for which is `Base-RCNN-FPN.yaml`. 
I find the two definitions confusing : 
```
cfg.MODEL.RPN.IN_FEATURES: ["p2", "p3", "p4", "p5","p6"]
cfg.MODEL.ROI_HEADS.IN_FEATURES: ["p2", "p3", "p4", "p5"]
```
If I understand correctly, p6 is used by the rpn . However it is not used by the roi head.
So, are all the region proposals from p6 discarded by the roi head?

**Comment by ppwwyyxx** [comment]
> If I understand correctly, p6 is used by the rpn . However it is not used by the roi head.

yes

> So, are all the region proposals from p6 discarded by the roi head?

no. you can refer to the FPN paper on how the proposals are used by ROI head.
