### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

### ISSUE THREAD

**Issue by EBJames** [facebookresearch/detectron2#1128]
Hi,

I've been running detectron2 using the tutorial colab book. today, while training using a dataset that has previously worked I got the following error: 

`from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("3test",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.1
cfg.SOLVER.MAX_ITER = 10000  
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 100   
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 
cfg.TEST.DETECTIONS_PER_IMAGE = 2000

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()`

I get the following error after a few iterations:

FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

I'd really appreciate any way of getting past this error.

Cheers,

Ed

**Comment by ppwwyyxx** [comment]
You probably need a smaller learning rate.

As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.

**Comment by Tongtong-allure** [comment]
I want to know whether you solve the problem or not?

**Comment by MiXaiLL76** [comment]
> I want to know whether you solve the problem or not?

set
```
num_gpu = 1
bs = (num_gpu * 2)
cfg.SOLVER.BASE_LR = 0.02 * bs / 16  # pick a good LR
```

**Comment by octavflorescu** [comment]
Maybe what MiXaiLL76 has proposed is the real solution, but i want to state my issue in case it helps anyone:
I have encountered the same error, and applied MiXaiLL76's solution. Then training worked, but the model still did not train as expected. => Rookie mistake: make sure the dataset is provided correctly. In my case somehow i have switched Xs with Ys for the bboxes.

**Comment by MiXaiLL76** [comment]
I went back to this problem again, this time for resnet34.
I had to change a little code, for those for whom everyone will also try to work with it
```
num_g = 1
bs = (num_gpu * 2)
cfg.SOLVER.BASE_LR = 0.01 * bs / 16 # pick a good LR```

**Comment by zmxheart** [comment]
if you change config.py,rebuild the code. 1 python setup.py clean --all 2 python setup.py build develop 3 python setup.py build --force develop.

**Comment by ExtReMLapin** [comment]
For RESNET18 with non-conventional grayscales images, I had to lower 4 times the learning rate (compared to LR proposed for RESNET34)
No crash so far, will keep you updated.

**Comment by Taechai** [comment]
Nothing of the above worked with me, is there any way out ?
