### ISSUE TITLE
Is it possible to specify a certain mask color in instance segmentation？

### ISSUE THREAD

**Issue by Grim-John** [facebookresearch/detectron2#1129]
Hi，
I need the generated image for the next step. Can I modify a certain parameter to determine the mask color of a certain category?

**Comment by ppwwyyxx** [comment]
You can find available functions in https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.

Many functions like draw_binary_mask or draw_polygon let you pass in a color
