### ISSUE TITLE
How to check backbone parameter?

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1130]
My backbone is: build_resnet_fpn_backbone.
But self.backbone.bottom_up.stem.conv1.weight in init is different from forward. 
In init, I get this:
torch.min(self.backbone.bottom_up.stem.conv1.weight)=-0.1059
torch.max(self.backbone.bottom_up.stem.conv1.weight)=0.1061
but in forward, I get:
torch.min(self.backbone.bottom_up.stem.conv1.weight)=-0.6710
torch.max(self.backbone.bottom_up.stem.conv1.weight)=0.7043
After some iters, the parameter of self.backbone.bottom_up.stem.conv1.weight in seems keep same. But the output feature of the backbone changes a lot. I want to know which part of the param is variable.

**Comment by ppwwyyxx** [comment]
You're probably using `BACKBONE.FREEZE_AT=2` in the config so the weight is frozen.

If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
