### ISSUE TITLE
How to clear MetadataCatalog in detectron2?

### ISSUE THREAD

**Issue by fiveredlee** [facebookresearch/detectron2#1131]
## ❓ How to clear MetadataCatalog in detectron2?

I have registed a MetadataCatalog  in detectron2, and converted detectron2's standard dataset to COCO format. So there is "json_file='...coco_format.json'" in Metadata .
Now, that json file was deleted. I want to  clear MetadataCatalog and convert detectron2's standard dataset to COCO format again. 
Is there a method that looks like "**DatasetCatalog.clear()**"?

**Comment by ppwwyyxx** [comment]
I couldn't understand what you mean by "clear MetadataCatalog" and why you need to do so.
It would be better to describe what unexpected issue you're facing, rather than a solution that you hypothesis might solve the issue. See https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem
