### ISSUE TITLE
Output video has no annotation

### ISSUE THREAD

**Issue by morestart** [facebookresearch/detectron2#1136]
if i use one image to detect, i get this result:

```
{'instances': Instances(num_instances=1, image_height=1440, image_width=1080, fields=[pred_boxes = Boxes(tensor([[582.4388, 651.9112, 725.5215, 802.3826]])), scores = tensor([0.9994]), pred_classes = tensor([0]), pred_masks = tensor([[[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]]), ])}
```

but if i use this command 
`!python detectron2/demo/demo.py --config-file /content/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --output video-output.mkv \
  --opts MODEL.WEIGHTS /content/haibao.pth`
the output video has no annoation,but the code is running to the `process_predictions` function in predictor file

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
