### ISSUE TITLE
Getting COCO categories in the order in which it is trained

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#1145]
From the model zoo, I am using the Cascade Mask RCNN model pre-trained on MSCOCO. I would like to do model surgery for one of my applications. How can I find out the order of the COCO categories by which the pre-trained model was trained on MSCOCO? 
For instance, MaskRCNN-benchmark gives the order of the categories by which they trained Mask RCNN model [here.](https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/configs/cityscapes)

**Comment by ppwwyyxx** [comment]
You can print the "thing_classes" metadata of a dataset using the example at https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets
