### ISSUE TITLE
RandomRotate for training augmentation

### ISSUE THREAD

**Issue by timofurrer** [facebookresearch/detectron2#1146]
## Transformations

I've already consulted the documentation for the Data Loader and Dataset Mapper - and was able to successfully implement my own based on the `DatasetMapper` class.

My question is if any one already wrote a `RandomRotate` Transformer which I could use. I was kinda surprised that it's not yet part of `fvcore` nor `detectron2`. Is there a reason for that?

I'm also wondering if there is a chance to use the pytorch transformers from here: https://pytorch.org/docs/stable/torchvision/transforms.html

**Comment by ppwwyyxx** [comment]
Random rotation is supported in 2c00dc055a2a6de033fad17b9375d9ceae39cfe2.

**Comment by timofurrer** [comment]
@ppwwyyxx Thanks for implementing this. 
When will this be available from https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/index.html ?
