### ISSUE TITLE
The default value of 'cfg.MODEL.ROI_MASK_HEAD.POINT_HEAD_ON '   is False

### ISSUE THREAD

**Issue by Armin199608** [facebookresearch/detectron2#1148]
The default value is False.
Is this function not used by default?
Is this the same as the original Mask RCNN?
If I use the function of 'PointRend', I need to set this value to True, right?

**Comment by ppwwyyxx** [comment]
Usage of PointRend is in its readme. https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend
