### ISSUE TITLE
Use Models

### ISSUE THREAD

**Issue by zetyquickly** [facebookresearch/detectron2#115]
Hi there,

My question will be mainly about ow to properly use trained model to make test inference.

According to documentation https://detectron2.readthedocs.io/tutorials/models.html, one should use
`build_model(cfg)` to build a model and https://detectron2.readthedocs.io/modules/data.html#detectron2.data.DatasetMapper `DatasetMapper` to map the data to a model.
Working with DensePose project I found out that it is needed more thatn just `get_cfg()` to get a `cfg` (https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/train_net.py#L41) and one should call `DetectionCheckpointer` to load weights in model (https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/train_net.py#L58).

Is there a proper way to: 1) read whole config, 2) load model with weights, 3) feed data to a model?

**Comment by ppwwyyxx** [comment]
1. Create a config and call `merge_from_file` is the proper way to read a config file.
2. `DetectionCheckpointer` is always used to load weights.
3. `outputs = model(inputs)` is how to use the model and the inputs/outputs format for standard models is documented in the link you have seen.

**Comment by ppwwyyxx** [comment]
These are now clarified more in the documentation. Thanks for asking!
