### ISSUE TITLE
use DefaultPredictor detect image is very slow

### ISSUE THREAD

**Issue by zbsean** [facebookresearch/detectron2#1151]
I detect image by DefaultPredictor, I found is need 0.2s ,this is very slow, My GPU is RTX2080Ti.
I check source code, don't find anywhere set cuda device. it mean run CPU env. ?
How set DefaultPredictor is run in GPU env?

**Comment by ppwwyyxx** [comment]
It runs on GPUs if your config has `MODEL.DEVICE='cuda'`.

The speed of each model (and the correct way to measure speed) is given in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#how-to-read-the-tables

**Comment by AlexandrineRibeiro** [comment]
Hello,

@zbsean were you able to improve the inference time? If so, how?

Thank you.
