### ISSUE TITLE
Using the score metric to filter the output of a Keypoint RCNN trained on a custom dataset  

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#1156]
Hello everyone, 
I have trained a Keypoint RCNN model on a custom dataset. 
The training went well and I am getting very good results on my Val dataset. 

When using my model to get a prediction the third column (The one that indicates the score of each keypoint) doesn't seem to make much sense. Good points and bad points can get almost the exact same score. I tried to normalize this column and maybe find a threshold that works but couldn't find anything robust enough. Any suggestions? 

another strange thing is, when some points are not visible, instead of given them a low score and place them where they are supposed to be (if they had been seen) the model places them near their symmetry point [the one that is given when the dataset was registered (given as keypoint_flip_map) and trained on], does anyone get this? 

In the image bellow, the unseen (e.g. incorrect) points are 8 and 9, their symmetry points are 10 and 11. As you can see, the score that points 9 and 10 received are almost the same (9 is wrong while 10 is correct). 
You can also see that even though point 10 is correct its score is lower than 8 (which is incorrect).

![git_gub_exmaple](https://user-images.githubusercontent.com/49122015/78499429-55976000-7759-11ea-824c-bba3fe30d59b.png)

Thanks In advance:)

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
