### ISSUE TITLE
How to cutout image using Panoptic Segmentation mask❓

### ISSUE THREAD

**Issue by 22Zly22** [facebookresearch/detectron2#1157]
Hello, I am a beginner. I know how to use Instance Segmentation parameter “pred_masks” to cut image by mask for every instance. But Panoptic Segmentation doesn't have parameter like “pred_masks”.  

Like I want to keep the background area (like building area) from the image. I only can filter and overlay the mask on the image.

![building](https://user-images.githubusercontent.com/46485989/78500901-cce5e780-778b-11ea-8261-09d1bb8d2877.png)

**Comment by pvtien96** [comment]
+1

**Comment by ppwwyyxx** [comment]
The output format of panoptic segmentation is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

**Comment by animikhaich** [comment]
@ppwwyyxx 

> The output format of panoptic segmentation is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

The output format does not solve the issue mentioned by @22Zly22. 
What the OP is asking is to extract each segmentation layer and not the grayscale combined mask that Panoptic Segmentation model outputs by default.

Even I have the same requirement. 

For example, the panoptic model outputs the following segmented image:
![image](https://user-images.githubusercontent.com/16799596/83987497-0db1d680-a95e-11ea-9cef-236847fd5bf8.png)

However, I want each of the segmentation mask slices **Before** they get merged together into one image. And I believe that the OP requested the same. 

Please guide us regarding the same. 
Thanks

@22Zly22, please reopen the issue, it is not resolved.

**Comment by 22Zly22** [comment]
> @ppwwyyxx
> 
> > The output format of panoptic segmentation is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
> 
> The output format does not solve the issue mentioned by @22Zly22.
> What the OP is asking is to extract each segmentation layer and not the grayscale combined mask that Panoptic Segmentation model outputs by default.
> 
> Even I have the same requirement.
> 
> For example, the panoptic model outputs the following segmented image:
> ![image](https://user-images.githubusercontent.com/16799596/83987497-0db1d680-a95e-11ea-9cef-236847fd5bf8.png)
> 
> However, I want each of the segmentation mask slices **Before** they get merged together into one image. And I believe that the OP requested the same.
> 
> Please guide us regarding the same.
> Thanks
> 
> @22Zly22, please reopen the issue, it is not resolved.

@animikhaich Thank you so much for explaining this question further. I did not solve this problem. But I can't reopen this issue~ :(

**Comment by animikhaich** [comment]
@ppwwyyxx, as it is evident, the "solution" did not solve the problem of the OP as well. 

Requesting you to re-open this issue and provide the necessary solution to the same.

**Comment by ppwwyyxx** [comment]
> However, I want each of the segmentation mask slices Before they get merged together into one image. And I believe that the OP requested the same.

As https://detectron2.readthedocs.io/tutorials/models.html#model-output-format explains, all elements that have the same value forms the mask of one segment.
