### ISSUE TITLE
Calculate mask losses and bounding box losses from outputs of roi_heads.box_predictor and roi_heads.mask_head

### ISSUE THREAD

**Issue by ritvik-ranadive** [facebookresearch/detectron2#1158]
Hi,

I am performing domain adaptation in feature space using detectron 2 mask rcnn. I am using the COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml.
The idea is to 
1. extract features from the roi_heads.box_pooler and roi_heads.mask_pooler layers
2. run these features through a generator
3. run the output of the generator through roi_heads.box_head, roi_heads.box_predictor and roi_heads.mask_head layers
4. use the outputs of roi_heads.box_predictor and roi_heads.mask_head to calculate a loss which I can backpropogate through my generator

Can anyone please explain the outputs of the following layers and how the correspond to the ground truth bounding boxes and ground truth masks so that I can calculate the loss
roi_heads.box_predictor.cls_score - Linear(in_features=1024, out_features=16, bias=True)
roi_heads.box_predictor.bbox_pred - Linear(in_features=1024, out_features=60, bias=True)
roi_heads.mask_head.predictor - Conv2d(256, 15, kernel_size=(1, 1), stride=(1, 1))

Are there any existing methods in Detectron2 to calculate mask loss and bbox loss using these outputs? If yes, how to use them?

Thanks in advance!
Cheers,
Ritvik

**Comment by ppwwyyxx** [comment]
> Can anyone please explain the outputs of the following layers and how the correspond to the ground truth bounding boxes and ground truth masks so that I can calculate the loss

Please refer to the paper for an explanation of the layers.

> Are there any existing methods in Detectron2 to calculate mask loss and bbox loss using these outputs

`roi_heads.box_predictror.losses() ` computes losses. `mask_head.forward()` computes losses.
