### ISSUE TITLE
Custom COCO dataset register error 

### ISSUE THREAD

**Issue by steppige** [facebookresearch/detectron2#1161]
I am working on registering a Coco Dataset called Herbarium, for the recognition of plants through object Detection with detectron2.
Unfortunately I think I made something wrong because I get an error.
Below the first error, then I also attach the .ipynb file
[Detectron2_custom_Herbarium_Beta.ipynb.zip](https://github.com/facebookresearch/detectron2/files/4434977/Detectron2_custom_Herbarium_Beta.ipynb.zip)

> import random
import cv2
for d in random.sample(herbarium_metadata, 3):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=herbarium_metadata, scale=0.5)
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, 

**Output:**

> 

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-11beeec0d828> in <module>
      3 
      4 for d in random.sample(herbarium_metadata, 3):
----> 5     img = cv2.imread(d["file_name"])
      6     visualizer = Visualizer(img[:, :, ::-1], metadata=herbarium_metadata, scale=0.5)
      7     vis = visualizer.draw_dataset_dict(d)

TypeError: string indices must be

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
