### ISSUE TITLE
I changed the colormode category, why different colors still appear in the same category？

### ISSUE THREAD

**Issue by Grim-John** [facebookresearch/detectron2#1163]
hi，
I want the same type of object to cover the same color, change the colormode to SEGMENTATION, and specify the “thing_colors” of the class, but the color of the instance of the same type is still slightly different, how can I modify it?
   This is my prediction code：

from detectron2.utils.visualizer import ColorMode
balloon_metadata.thing_colors = [(0, 0, 255)]
dataset_dicts = get_balloon_dicts("balloon/val")
for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=balloon_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.SEGMENTATION   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2_imshow(v.get_image()[:, :, ::-1])

Below is my prediction result
![气球](https://user-images.githubusercontent.com/58287333/78543869-dfaff900-782b-11ea-8b02-0bd85aa20fb6.png)
![下载 (12)](https://user-images.githubusercontent.com/58287333/78543893-e9396100-782b-11ea-8eed-f37895a5f4a2.png)

Thanks！

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode

> SEGMENTATION
Let instances of the same category have __similar__ colors

**Comment by Grim-John** [comment]
> 在[https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode中](https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode)回答[](https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode)
> 
> > 分段
> > 让相同类别的实例具有**相似的**颜色

I have changed "ColorMode" to "SEGMENTATION". The colors of the same type of objects in the prediction result are similar, but there are still differences.For example, the same category will appear blue and dark blue

**Comment by ppwwyyxx** [comment]
The documentation says that the color will be "similar" but not the same.
You need to draw each item yourself if you want to specify its color.

**Comment by Grim-John** [comment]
> The documentation says that the color will be "similar" but not the same.
> You need to draw each item yourself if you want to specify its color.

Ok！thanks！！！
By the way， Can the polygon coordinates of the mask be output?  If so, how?

**Comment by ppwwyyxx** [comment]
> Can the polygon coordinates of the mask be output

There is no such feature.

**Comment by deepseek** [comment]
@Grim-John 
https://www.youtube.com/watch?v=eUSgtfK4ivk

**Comment by chengwen-afk** [comment]
> The documentation says that the color will be "similar" but not the same.
> You need to draw each item yourself if you want to specify its color.

how to draw a specify color for each item? I met the same problem as his

**Comment by AbhishekMaity001** [comment]
Hi @ppwwyyxx 
i have gone through the documentation... where ColorMode.SEGMENTATION part is shown and also in the  " Source code for **detectron2.utils.video_visualizer class** " it is written that there is no support for ColorMode.SEGMENTATION for videos yet... (only ColorMode.SEGMENTATION works on images)  ... Can you please tell me any alternative way or some other techniques to get same class/instances colors on Videos/webcam also in detectron2.

**Comment by sodi16** [comment]
hi @ppwwyyxx @Grim-John,
It didn't work for me, can you help me, I'm running Mask Rcnn on fews images, and object segmentation color change each frames.
Can I just get same color for a class?Thanks in advance

**Comment by chenruitao123** [comment]
I want to know the coordinate information of the target in the predicted picture. Where are the coordinates stored and how to output the coordinates?
