### ISSUE TITLE
Any specific reason not using ops.roialign?

### ISSUE THREAD

**Issue by 300LiterPropofol** [facebookresearch/detectron2#1165]
Hi,
I noticed that you directly use the package torchvision.ops.roi_pool but you didn't use the package
torchvision.ops.roi_align. Instead you write your own roi align algorirthm. I wonder is there any specific reason for not using the roi align package at hand in torchvision? Do you think there are problems with the package and not recommend to use or?

Thank you.

**Comment by ppwwyyxx** [comment]
The latest roialign in torchvision can be used by detectron2 but we need to support torchvision 0.4 whose roialign is different from ours.

**Comment by 300LiterPropofol** [comment]
Thanks for your reply, by the latest roialign, do you mean the torchvision.ops.ps_roi_align package?

**Comment by 300LiterPropofol** [comment]
Never mind. I got confused by myself.
For those who are upcoming, the latest roialign still means torchvision.ops.roi_align.
But you need to use the syntax torchvision.ops.roi_align(input, boxes, output_size, spatial_scale=1.0, sampling_ratio=-1, aligned=True)
The reference link is: 
https://github.com/pytorch/vision/blob/master/torchvision/ops/roi_align.py#L10

Here https://github.com/pytorch/vision/blob/master/torchvision/ops/roi_align.py#L33
they explained it.

**Comment by 300LiterPropofol** [comment]
PS. the version of torchvision is 0.5.1, which doesn't have a .whl fie on PYPI.
torchvision 0.5.0 doesn't support this.
