### ISSUE TITLE
Background Color Segmentation with OpenCV in Detectron2(COLAB)

### ISSUE THREAD

**Issue by oguchi-ebube** [facebookresearch/detectron2#1169]
Whenever i try processing/analysing a video using opencv in detectron2, i keep having having a disconnection in colab, any reason why this happens?

**Comment by ppwwyyxx** [comment]
It doesn't sound like a detectron2 issue. If you still think it's a detectron2 issue and need help to understand why, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
