### ISSUE TITLE
Background Segmentation/Detection Error in Detectron2

### ISSUE THREAD

**Issue by oguchi-ebube** [facebookresearch/detectron2#1171]
i tried doing background color segmentation on a soccer video using OpenCV in detectron2 but the result i got was not as expected, meaning that it was detecting only 3 players in all the video frames any reason why this is happening please?

**Comment by ppwwyyxx** [comment]
Please read and provide details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
