### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by weiweia92** [facebookresearch/detectron2#1173]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

1.Product bug when I run pip install -e . 
2. what exact command you run: pip install -e .
The bug is :
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Obtaining file:///home/weiweia92/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (1.1.0)
Requirement already satisfied: Pillow in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (7.0.0)
Requirement already satisfied: yacs>=0.1.6 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (0.1.6)
Requirement already satisfied: tabulate in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (0.8.7)
Requirement already satisfied: cloudpickle in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (1.3.0)
Requirement already satisfied: matplotlib in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (3.1.3)
Requirement already satisfied: tqdm>4.29.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (4.42.1)
Requirement already satisfied: tensorboard in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (2.2.0)
Requirement already satisfied: fvcore in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (0.1.dev200407)
Requirement already satisfied: future in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (0.18.2)
Requirement already satisfied: pydot in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from detectron2==0.1.1) (1.4.1)
Requirement already satisfied: PyYAML in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from yacs>=0.1.6->detectron2==0.1.1) (5.3)
Requirement already satisfied: numpy>=1.11 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1.1) (1.18.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1.1) (2.4.6)
Requirement already satisfied: cycler>=0.10 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1.1) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1.1) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1.1) (1.1.0)
Requirement already satisfied: markdown>=2.6.8 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (3.2.1)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (0.34.2)
Requirement already satisfied: grpcio>=1.24.3 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (1.28.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (1.13.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (2.22.0)
Requirement already satisfied: absl-py>=0.4 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (0.9.0)
Requirement already satisfied: six>=1.10.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (1.14.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (1.0.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (0.4.1)
Requirement already satisfied: protobuf>=3.6.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (3.11.3)
Requirement already satisfied: setuptools>=41.0.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (45.2.0.post20200210)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1.1) (1.6.0.post3)
Requirement already satisfied: portalocker in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from fvcore->detectron2==0.1.1) (1.6.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2019.11.28)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/weiweia92/anaconda3/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (3.1.0)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.1.1+cu101
    Uninstalling detectron2-0.1.1+cu101:
      Successfully uninstalled detectron2-0.1.1+cu101
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/weiweia92/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/weiweia92/detectron2/setup.py'"'"'; __file__='"'"'/home/weiweia92/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/weiweia92/detectron2/
    Complete output (98 lines):
    running develop
    running egg_info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/home
    creating build/temp.linux-x86_64-3.7/home/weiweia92
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/box_iou_rotated
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated
    creating build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/deformable
    gcc -pthread -B /home/weiweia92/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/vision.cpp -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/weiweia92/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/weiweia92/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                     from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:3:
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp: In lambda function:
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:446:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
       AT_DISPATCH_FLOATING_TYPES_AND_HALF(
       ^
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp: In lambda function:
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:497:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
       AT_DISPATCH_FLOATING_TYPES_AND_HALF(
       ^
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    gcc -pthread -B /home/weiweia92/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                     from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:3:
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp: In lambda function:
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:429:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
       AT_DISPATCH_FLOATING_TYPES_AND_HALF(input.type(), "ROIAlign_forward", [&] {
       ^
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp: In lambda function:
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /home/weiweia92/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:481:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
       AT_DISPATCH_FLOATING_TYPES_AND_HALF(grad.type(), "ROIAlign_forward", [&] {
       ^
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    gcc -pthread -B /home/weiweia92/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                     from /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated.h:3,
                     from /home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:3:
    /home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp: In lambda function:
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:103:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /home/weiweia92/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:67:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
       AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    /usr/bin/nvcc -DWITH_CUDA -I/home/weiweia92/detectron2/detectron2/layers/csrc -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/weiweia92/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/home/weiweia92/anaconda3/include/python3.7m -c /home/weiweia92/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o build/temp.linux-x86_64-3.7/home/weiweia92/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    error: command '/usr/bin/nvcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of detectron2
  Moving to /home/weiweia92/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1+cu101.dist-info/
   from /home/weiweia92/anaconda3/lib/python3.7/site-packages/~etectron2-0.1.1+cu101.dist-info
  Moving to /home/weiweia92/anaconda3/lib/python3.7/site-packages/detectron2/
   from /home/weiweia92/anaconda3/lib/python3.7/site-packages/~etectron2
ERROR: Command errored out with exit status 1: /home/weiweia92/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/weiweia92/detectron2/setup.py'"'"'; __file__='"'"'/home/weiweia92/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
but I don't know what wrong with me.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by alekseynp** [comment]
`nvcc fatal : Unsupported gpu architecture 'compute_75'`
Looks like you might have some kind of mismatch between cuda versions. I would suggest that you check your conda cudatoolkit, system cuda, pytorch, nvcc version, etc.

**Comment by xkszltl** [comment]
I saw `/usr/bin/nvcc`, which indicates you probably have old (< 10.0) nvcc on your system.
