### ISSUE TITLE
SOLVER.STEPS = (150000, 170000)

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1174]
SOLVER.STEPS = (150000, 170000), and later found that 170000 is too small, it was changed to (150000, 220000), but lr is still reduced when iterating 170,000 times, is this normal? ? How can it be set to 220000.

**Comment by ppwwyyxx** [comment]
It doesn't sound normal but I cannot comment more because I do not know what you did.
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
