### ISSUE TITLE
How to train Faster R-CNN

### ISSUE THREAD

**Issue by adesgautam** [facebookresearch/detectron2#1175]
Can i train any model of the Faster R-CNN ones? If yes how ?
Would [this](https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py) script help ?

Also, how many images i need to train a good Faster R-CNN model ?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md has basic usage of detectron2.

https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md has the models that detectron2 supports.

**Comment by adesgautam** [comment]
And, approx. how many images would be required for a decent model ?
