### ISSUE TITLE
How Detectron2 shuffle the dataset at each epoch?

### ISSUE THREAD

**Issue by tztztztztz** [facebookresearch/detectron2#1176]
## ❓  I don't understand how detectron2 shuffles the dataset at each epoch?

`detectron2.data.sampler.distributed_sampler.py`
```
class TrainingSampler(Sampler):
...

def _infinite_indices(self):
    g = torch.Generator()
    g.manual_seed(self._seed)
    while True:
        if self._shuffle:
            yield from torch.randperm(self._size, generator=g)
        else:
            yield from torch.arange(self._size)
```

From the code, I see that detectron2 uses the same seed at each epoch. 

https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/samplers/distributed_sampler.py#L48-L49

**Comment by ppwwyyxx** [comment]
`_infinite_indices` is only called once per training. It's not called once each epoch.
