### ISSUE TITLE
Why retry_if_cuda_oom only used in anchor matching in RPN?

### ISSUE THREAD

**Issue by 300LiterPropofol** [facebookresearch/detectron2#1179]
Hi!

The function retry_if_cuda_oom is very interesting!

I noticed that you only use this function as a safe belt when doing anchor matching in region proposal network. (The location is the link below)
https://github.com/facebookresearch/detectron2/blob/7fd276ffb7ff274d766d4a34324c473a6f0e1442/detectron2/modeling/proposal_generator/rpn_outputs.py#L279

When it comes to proposal target creator, i.e. subsampling roi that will be fed into ROIhead,
i.e. roi matching,
you don't use retry_if_cuda_oom this fuction. (The location is the link below)
https://github.com/facebookresearch/detectron2/blob/474c6b9ebc1a2475c5ffa2fe34c4a84ae4cacc63/detectron2/modeling/roi_heads/roi_heads.py#L237

They are both area matching and I guess will be both memory consuming.
I wonder why you don't use retry_if_cuda_oom when doing roi matching. Did you conduct some experiments which proved that roi matching is much less demanding than anchor matching so GPU memory will never encounter leakage in this process or any other specific reasons?

Thank you!

**Comment by ppwwyyxx** [comment]
>  roi matching is much less demanding than anchor matching

This is true by design of the algorithm. Only the top ~10^4 proposals will be used for matching while the number of anchors can be 10^5 to 10^6
