### ISSUE TITLE
Incoporate VideoPose3D in Detectron2

### ISSUE THREAD

**Issue by FamousDirector** [facebookresearch/detectron2#118]
## 🚀 Feature
Add the [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) algorithm into Detectron2.

## Motivation

There is another repo created by the Facebook Research team that would useful to be incorporated into the Detectron2 codebase. There was some preliminary work done in the repo to allow it to work with the original Detectron so that video from the wild could be annotated. It would be awesome to have it incorporated into the newer version.

## Pitch

Take the preexisting [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) and merge the code that allowed inferencing "in the wild"

**Comment by ppwwyyxx** [comment]
Since object detection is only a part of its whole algorithm, it is more reasonable for it to be a separate project that depends on detectron2, rather than being part of detectron2.
