### ISSUE TITLE
How to use sparse inputs ? 

### ISSUE THREAD

**Issue by Cyril9227** [facebookresearch/detectron2#1180]
Hello,

My issue is pretty simple, I would like to use sparse inputs, how can I achieve that ? I got an issue with the preprocess_image function in meta_arch/rcnn.py 

Thank you in advance

**Comment by ppwwyyxx** [comment]
What do you mean by sparse inputs?

**Comment by Cyril9227** [comment]
> What do you mean by sparse inputs?

I mean a torch.sparse.FloatTensor as input

**Comment by ppwwyyxx** [comment]
That's not supported and you can convert it to dense tensor instead.
There is currently no model here that can benefit from supporting sparse inputs, so it's unlikely we'll add support for it.
