### ISSUE TITLE
How to register META_ARCH?

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1181]
I try to register a META_ARCH and modify 'META_ARCHITECTURE' in yaml. But get error "No object named 'MyRCNN' found in 'META_ARCH' registry". How to recognize my meta arch.
```
@META_ARCH_REGISTRY.register()
class MyRCNN(nn.Module):
...
```

**Comment by Cyril9227** [comment]
Use import detectron2.xxx.meta_arch at the top of your script / notebook, should work

**Comment by Yoline777** [comment]
After add a empty config file. It works.
```
def add_myrcnn_config(cfg):
    pass
```

**Comment by Yoline777** [comment]
@Cyril9227 Thanks a lot. It works after add `import MyRCNN`
