### ISSUE TITLE
Register custom dataset question with VIA (VGG Image Annotation) label tool format

### ISSUE THREAD

**Issue by 0922james0922** [facebookresearch/detectron2#1182]
Dear @ppwwyyxx :

when I try to train custom dataset with VIA label tool, the process report error about this:
---------------------------------------------------------------------------------
[04/09 03:36:33 d2.data.datasets.coco]: Loaded 1 images in COCO format from ./image/via_export_coco.json
[04/09 03:36:33 d2.data.build]: Removed 1 images with no usable annotations. 0 images left.
[04/09 03:36:33 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|   orange   | 0            |
|            |              |
[04/09 03:36:33 d2.data.common]: Serializing 0 elements to byte tensors and concatenating them all ...
-------------------------------------------------------------------------
I try to use one image and one label category.
I am not sure if my label .json file fit your coco format. The VIA application can export coco .json format, but the detectron2 seemly cannot get the number of category. Please answer my question. Thank you~

**Comment by ppwwyyxx** [comment]
According to the log there is one category and one image with no valid annotations in your JSON. Please compare with the official COCO json file to see what's missing.

**Comment by 0922james0922** [comment]
Dear @ppwwyyxx :

In the"annotations"-"segmentation", I find out that VIA tool lacks one "[". For example, 

"annotations": [
        {
            "segmentation": [
                [
                    133.46583850931677,
                    144.3416149068323,
                    117.93788819875775,
                    169.80745341614906,
                    101.16770186335401,
                    240.61490683229812,
                    106.1366459627329,
                    267.94409937888196,
                    138.43478260869563,
                    285.3354037267081,
                    156.44720496894408,
                    283.47204968944095,
                    209.24223602484471,
                    229.43478260869563,
                    230.98136645962728,
                    209.5590062111801,
                    237.81366459627327,
                    153.03726708074532,
                    206.75776397515529,
                    120.7391304347826,
                    165.1428571428571,
                    118.87577639751552
                ]
            ],
            "iscrowd": 0,
            "area": 15584.661085606262,
            "image_id": 0,
            "bbox": [
                101.0,
                118.0,
                136.0,
                167.0
            ],
            "category_id": 1,
            "id": 1
        },

but, VIA tool format is:

"annotations": [
        {
            "segmentation": [
                
                    133.46583850931677,
                    144.3416149068323,
                    117.93788819875775,
                    169.80745341614906,
                    101.16770186335401,
                    240.61490683229812,
                    106.1366459627329,
                    267.94409937888196,
                    138.43478260869563,
                    285.3354037267081,
                    156.44720496894408,
                    283.47204968944095,
                    209.24223602484471,
                    229.43478260869563,
                    230.98136645962728,
                    209.5590062111801,
                    237.81366459627327,
                    153.03726708074532,
                    206.75776397515529,
                    120.7391304347826,
                    165.1428571428571,
                    118.87577639751552
               
            ],
            "iscrowd": 0,
            "area": 15584.661085606262,
            "image_id": 0,
            "bbox": [
                101.0,
                118.0,
                136.0,
                167.0
            ],
            "category_id": 1,
            "id": 1
        },

It cause the program could't catch the annotation imformation.

FIR~

Thanks your response.
