### ISSUE TITLE
Docker image problem

### ISSUE THREAD

**Issue by chansongoal** [facebookresearch/detectron2#1184]
I built a docker image through the Dockerfile. But when I run the demo.py something goes wrong. It turn out the library "tqdm" cannot be found and I cannot find pip command. Is there somebody know the reason or it there a docker image available? Thanks for your help!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/install.html mentioned that we have already provided a dockerfile.

**Comment by chansongoal** [comment]
Yes, you have already provided a dockerfile and I built it successfully. But I encountered the problem "no module named tqdm" when I run the demo.py in the container. Is there something wrong?

**Comment by chansongoal** [comment]
I did 2 steps as following:
1. build the docker image using the provided dockerfile successfully
2. run the demo.py in the container
and something goes wrong:
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import tqdm
ModuleNotFoundError: No module named ‘tqdm'

So did I do something wrong? I’ll appreciate it if you can help me.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Blind guess: need to use python3 in the container as the instructions said
