### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by chansongoal** [facebookresearch/detectron2#1186]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
I did't modify the code.

2. what exact command you run:
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
  [--other-options]
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

3. what you observed (including __full logs__):
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by ppwwyyxx** [comment]
As said in the previous comment: https://github.com/facebookresearch/detectron2/issues/1184#issuecomment-611394690, the instructions in dockerfile is to use `python3` not `python`.

**Comment by chansongoal** [comment]
sorry, I typed it wrong. What I exact run is:
python3 demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml 
--input input1.jpg input2.jpg 
[--other-options]
--opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

But the same error again.

**Comment by ppwwyyxx** [comment]
The dockerfile should install tqdm. Please provide the command you use to build the docker container, run the docker container, and their full logs.

**Comment by chansongoal** [comment]
the command build the docker container: "docker build .“
the command run the docker container: "docker run -it -v xxx:yyy -c /bin/bash bit:5000/gaocs-detectron2-pytorch-1.3“ (I ran it in GPU cluster)

[docker_build.log](https://github.com/facebookresearch/detectron2/files/4455125/docker_build.log)

**Comment by ppwwyyxx** [comment]
According to the logs tqdm was successfully installed.
When you run the code were you using user "appuser", or "root"? "appuser" is the account to which all the dependencies are installed.

**Comment by chansongoal** [comment]
thank you for your help. I have solved this problem by run the docker with appuser.
