### ISSUE TITLE
Is it possible to use cirular COCO annotations❓

### ISSUE THREAD

**Issue by YacobBY** [facebookresearch/detectron2#1187]
Hello,

I am trying to train a model with circular annotations.
I have tried annotating  with:
VGG VIA 2.09 > export to COCO 
and LabelMe > labelme2coco.py 

But in both instances I tested, any circular annotation I have get filtered out with the notification:
_[04/09 10:57:21 d2.data.build]: Removed 2 images with no usable annotations. 1 images left._

The image that is left is a polygon annotation to see if my annotations were exported correctly. It is able to train with this single image.

This leads me to believe that either the circlular annotations are not converted correctly, or Detectron2  doesn't accept circular inputs, which of course leads to my main question: Is it possible to train a model in Detectron2 with circular MSCOCO annotations?

**Comment by ppwwyyxx** [comment]
I do not know what those tools do, so I cannot comment on whether they are generating data that detectron2 does not support. 
The COCO format requires masks to be either polygons or COCO-style RLEs. Detectron2 is supposed to support both. If you found otherwise, please provide some JSON files that detectron2 does not support.

**Comment by 0922james0922** [comment]
@YacobBY 
Hi~I also use VIA tool to label for detectron2. I find out that the content of coco json file is not correct at all. First, at the "segmentation" in the content, lacked one "[" and one "]" are write in here. It must be "[[" and "]]" in here. Second, VIA tool sometimes can't generate "category_id" in here. Third, " image_id:"0" " must be " image_id:0 " not " image_id:"0" ". You can check it again. Although I still can't train detectron2 now...
