### ISSUE TITLE
Difference between 1x and 3x schedules

### ISSUE THREAD

**Issue by UmarSpa** [facebookresearch/detectron2#119]
Various config files end up with 1x and 3x suffix. I was just wondering what these represent ?
3x = 3 gpus ?

**Comment by rbgirshick** [comment]
These refer to the length of the training schedule.

From https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md:

> Most models are trained with the 3x schedule (~37 COCO epochs). Although 1x models are heavily under-trained, we provide some ResNet-50 models with the 1x (~12 COCO epochs) training schedule for comparison when doing quick research iteration.

1x = 16 images / iterations * 90,000 iterations in total with the LR reduced at 60k and 80k
3x = 16 images / iteration * 270,000 iterations in total with the LR reduced at 210k and 250k

**Comment by chinnumerinmathew** [comment]
Hi @rbgirshick Your reply is so helpful. Can u pls explain LR reduced at 60k and 80k

**Comment by glaw1300** [comment]
@chinnumerinmathew https://arxiv.org/abs/1811.08883 if you hadn't found it yet.
