### ISSUE TITLE
Is it possible to disable autoresize of image data? 

### ISSUE THREAD

**Issue by rtarquini** [facebookresearch/detectron2#1192]
## ❓ Is it possible to disable autoresize of image data, and use the raw image size?

I have very large images [20K x 20K]. Scaling them down would result in a lot of fidelity loss. Is there a way to disable the autoresize feature?

**Comment by ppwwyyxx** [comment]
Scaling is performed by dataloader, which you can implement yourself: https://detectron2.readthedocs.io/tutorials/data_loading.html

**Comment by rtarquini** [comment]
There are comments in defaults.py which lead me to believe there is scaling occurring outside of the data loader. 

config/defaults.py
# Size of the smallest side of the image during testing. Set to zero to disable resize in testing.
_C.INPUT.MIN_SIZE_TEST = 800
# Maximum size of the side of the image during testing
_C.INPUT.MAX_SIZE_TEST = 1333

**Comment by ppwwyyxx** [comment]
If you use [DefaultPredictor](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor), it also performs scaling as its documentation says. There are no other places that will perform testing.
