### ISSUE TITLE
Will Detectron2go be released / implemented?

### ISSUE THREAD

**Issue by ArtanisCV** [facebookresearch/detectron2#12]
## ❓ Will Detectron2go be released / implemented

In the official [blog](https://ai.facebook.com/blog/-detectron2-a-pytorch-based-modular-object-detection-library-/), a library named Detectron2go is introduced. It seems that this library is very helpful for model deployment.

By now, I cannot find related codes in the Detectron2 repo. Will Detectron2 provide similar features in the near future?

**Comment by wat3rBro** [comment]
@ArtanisCV Detectron2Go will also be open-sourced soon, stay tuned!

**Comment by choasup** [comment]
When will Detectron2go release in plan?

**Comment by wat3rBro** [comment]
@choasup we're targeting in November.

**Comment by cpoptic** [comment]
Hi Yuxin, any update on the release date for Detectron2Go?  Very excited for this

**Comment by wat3rBro** [comment]
@cpoptic we'll release the model exporting very soon and then efficient models for mobile after that, hopefully within next 1-2 weeks.

**Comment by jinfagang** [comment]
@wat3rBro Exporting model to which format? Is it onnx?

**Comment by startupgurukul** [comment]
@jinfagang i beleive caffe2( via onnx ) and mobile models would be with shufflenet or fbnet backbone. 

@wat3rBro  So many possibilities, looking forward

**Comment by MentalGear** [comment]
> @cpoptic we'll release the model exporting very soon and then efficient models for mobile after that, hopefully within next 1-2 weeks.

That be awesome. Currently deciding between Tensorflow Object Detection API and Detectron2. If mobile inference was possible on Dectectron, my decision would be made.

**Comment by wat3rBro** [comment]
@jinfagang, @startupgurukul is correct, with FBNet backbone.

**Comment by startupgurukul** [comment]
Can you pls elaborate if export  will be targeting pytorch mobile and
caffe2 or only caffe2.

Thanks in advance.

**Comment by wat3rBro** [comment]
@startupgurukul only caffe2 and "caffe2-style" torch script for now.

**Comment by startupgurukul** [comment]
Thanks for the response. Waiting to check if it's convertible to tensorflow
pb model via this,
https://github.com/onnx/onnx-tensorflow

If that can happen, detectron2 can work on browsers along with iOS and
Android via tensorflow.js. (onnx.js seems unmaintained)

Considering the way Detectron2 is making image models accessible to
everyone, JS compatibility would be super awesome
🤞  and in line with the vision of detectron2.

**Comment by ppwwyyxx** [comment]
@startupgurukul 

There is already a (very limited) tool that converts some standard detectron2 models to tensorflow, as mentioned in https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-tensorflow

It does not use onnx. I believe most detectron2 models cannot successfully convert to tensorflow through onnx.

**Comment by startupgurukul** [comment]
It is just awesome, going to the extent of supporting other frameworks, just increases the respect towards Detectron Team and can only imagine this being to **Portal** to visual apps of the future. 

Coming to getting to run in a browser, while converting to tf.js format got a complain that ValueError: Unsupported Ops in the model before optimization, MirrorPad, InvertPermutation

By setting --skip_op_check flag, it was bypassed and conversion succeded, yet to try the converted model, will keep you posted with the updates

Looking forward to come back with the news that detectron2 can also infer in the browser as well.

**Comment by mathpopo** [comment]
> @startupgurukul only caffe2 and "caffe2-style" torch script for now.

hello,i try to use maskrcnn2go (caffe2 style),when pyotrch version come ?

**Comment by startupgurukul** [comment]
My guess is pytorch mobile is still in active development and is yet to get
operator compatibility with pytorch, but that shouldn't delay detectron2
team from moving to production so for now they must have picked caffe2
export,

As of now it's now very kind of them to open source it, the and continue
adding more like export and help anyone working on visual models quickly
research and move to production super quickly also while providing mobile
friendly privacy preserving models(current ETA is Jan 2020 as per )

**Comment by shuxp** [comment]
any news about detectron2go...

**Comment by zhiqwang** [comment]
It seems that the newest [PR ](https://github.com/facebookresearch/detectron2/commit/914b91db4aa2380fba955af125f01014adbaacaa) is about detectron2go?

**Comment by jinfagang** [comment]
So, one year after does there any updates on such `detectron2go`?

**Comment by dragen1860** [comment]
Detectron2go still has a long way to go!

**Comment by hoangtubatu123** [comment]
when will Detectron2go be released??? I am very expected it.

**Comment by ppwwyyxx** [comment]
Exporting and running a model in caffe2 is already open source for a while. See https://detectron2.readthedocs.io/tutorials/deployment.html

The only other feature we currently plan to open source from detectron2go is efficient FBNet-based models, tracked in #696.

**Comment by shuxp** [comment]
> Exporting and running a model in caffe2 is already open source for a while. See https://detectron2.readthedocs.io/tutorials/deployment.html
> 
> The only other feature we currently plan to open source from detectron2go is efficient FBNet-based models, tracked in #696.

Is there a demo of how to use model.pb and model_init.pb? After pytorch merged caffe2, it is not wasy to find a caffe2 C++ example...

**Comment by jinfagang** [comment]
Does this pb model is essentially onnx model? Can it port to other framwork through this model such as TensorRT?
