### ISSUE TITLE
Visualize FPN and RPN outputs

### ISSUE THREAD

**Issue by timofurrer** [facebookresearch/detectron2#1200]
I'm working with the Mask R-CNN, ResNet50 with FPN configuration.

I'd like to "visualize" the outputs from the FPN and RPN Heads, much like it's being shown in the following two blog posts:

* [FPN visualization in the "Input and Output of FPN" section](https://medium.com/@hirotoschwert/digging-into-detectron-2-part-2-dd6e8b0526e)
* [RPN visualization in the "RPN Head" section](https://medium.com/@hirotoschwert/digging-into-detectron-2-part-4-3d1436f91266)

Another good example is the [matterport Mask-RCNN library](https://github.com/matterport/Mask_RCNN):

* [See the "Step by Step Prediction" section](https://github.com/matterport/Mask_RCNN/blob/master/samples/balloon/inspect_balloon_model.ipynb)

I think an easy way to access those outputs from detectron2 would help to better understand the models we are training .

What do you think?
Do you have any example where you are already doing this?
If not, can you briefly elaborate on how one could achieve this (even if it's no easy accessible from detectron2 yet, but just to make it work) ?

**Comment by ppwwyyxx** [comment]
You can execute a detectron2 model module-by-module to obtain all their outputs, like https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model

**Comment by kg512** [comment]
Would it possible to get a bit more detail on this, I am also interested in visualizing the RPN output.
