### ISSUE TITLE
Didn't get the rotation angle in the predicted output

### ISSUE THREAD

**Issue by mofibo** [facebookresearch/detectron2#1206]
Hello, 
I followed the [Colab Notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) , I changed the BoxMode from **XYXY_ABS** to **XYWHA_ABS** to get the rotation angle..
But after the training, I still have XYXY_ABS in the predicted output.
Is there anything to add in the code? Or which **.yaml** file to use?
Thanks in advance.

**Comment by ppwwyyxx** [comment]
More changes are needed to use predicted rotated boxes. We currently don't have an example for how to do it - this is discussed in #21
