### ISSUE TITLE
Hello, we always need to convert the model file into a torch script, and then call the torch script with c ++. But I found that the model file saved in this project cannot be converted into a torch script. Is there any difference between this model file and other pytorch model files?

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1210]
Hello, we always need to convert the model file into a torch script, and then call the torch script with c ++. But I found that the model file saved in this project cannot be converted into a torch script. Is there any difference between this model file and other pytorch model files?

**Comment by ppwwyyxx** [comment]
Duplicate of #46 

The difference is that the models in detectron2 are complicated and cannot be converted to torchscript yet.
