### ISSUE TITLE
How to detect small objects in detectron2 , with bbox ~10x20 pixels

### ISSUE THREAD

**Issue by vutatthanh1702** [facebookresearch/detectron2#1213]
## ❓ How to use Detectron2
I ve tried alot of changing parameter like this, but it cant detect object small than 103x60

#mAP 91.98%
 cfg.FPN_ON = True
 cfg.MULTILEVEL_RPN = True
 cfg.FPN_ON = "true"
 cfg.MULTILEVEL_RPN = "True"
 cfg.RPN_MAX_LEVEL = 8
 cfg.RPN_MIN_LEVEL = 3
 cfg.COARSEST_STRIDE = 256
 cfg.SCALES_PER_OCTAVE = 3
 cfg.ANCHOR_SCALE = 2
#mAP 92.141%
 cfg.MODEL.FPN.FPN_ON = True
 cfg.MODEL.FPN.MULTILEVEL_RPN = True
 cfg.MODEL.FPN.RPN_MIN_LEVEL = 1
 cfg.MODEL.FPN.RPN_MAX_LEVEL = 8
 cfg.MODEL.FPN.COARSEST_STRIDE = 256
 cfg.MODEL.FPN.SCALES_PER_OCTAVE = 3
 cfg.MODEL.FPN.ANCHOR_SCALE = 1
- 
 cfg.MODEL.RETINANET.RETINANET_ON = True
 cfg.MODEL.RETINANET.MULTILEVEL_RPN = True
 cfg.MODEL.RETINANET.ANCHOR_SCALE = 1
 cfg.MODEL.RETINANET.RPN_MIN_LEVEL = 2
 cfg.MODEL.RETINANET.RPN_MAX_LEVEL = 8
 cfg.MODEL.RETINANET.COARSEST_STRIDE = 256
 cfg.MODEL.RETINANET.SCALES_PER_OCTAVE = 3
- 
#mAP 90.7%
 cfg.MODEL.FPN.FPN_ON = True
 cfg.MODEL.FPN.MULTILEVEL_RPN = True
 cfg.MODEL.FPN.RPN_MIN_LEVEL = 3
 cfg.MODEL.FPN.RPN_MAX_LEVEL = 8
 cfg.MODEL.FPN.COARSEST_STRIDE = 256
 cfg.MODEL.FPN.SCALES_PER_OCTAVE = 3
 cfg.MODEL.FPN.ANCHOR_SCALE = 2
# mAP 89%
 cfg.MODEL.FPN.FPN_ON = True
 cfg.MODEL.FPN.MULTILEVEL_RPN = True
 cfg.MODEL.FPN.MULTILEVEL_ROIS = True
 cfg.MODEL.FPN.ROI_MIN_LEVEL = 2
 cfg.MODEL.FPN.ROI_MAX_LEVEL = 5
 cfg.MODEL.FPN.RPN_MIN_LEVEL = 2
 cfg.MODEL.FPN.RPN_MAX_LEVEL = 8
 cfg.MODEL.FPN.COARSEST_STRIDE = 256
 cfg.MODEL.FPN.SCALES_PER_OCTAVE = 3
 cfg.MODEL.FPN.ANCHOR_SCALE = 2
 cfg.MODEL.FPN.RPN_ANCHOR_START_SIZE = 5
 cfg.MODEL.FPN.RPN_ASPECT_RATIOS = (0.5, 1, 2)
- 
#mAP 92.205%
 cfg.MODEL.FPN.IN_FEATURES = ["res2", "res3", "res4", "res5"]
 cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[4, 8, 16, 32, 64, 128, 256, 512]]
 cfg.MODEL.RETINANET.IN_FEATURES = ["p3", "p4", "p5", "p6", "p7"]
- 
#mAP box 91.581% segm 93.130%
 cfg.MODEL.PIXEL_MEAN= [10.353, 11.628, 12.3675]
 cfg.MODEL.FPN.IN_FEATURES = ["res2", "res3", "res4", "res5"]
 cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[4, 8, 16, 32, 64, 128, 256, 512]]
 cfg.MODEL.RETINANET.IN_FEATURES = ["p3", "p4", "p5", "p6", "p7"]
 cfg.TEST.DETECTIONS_PER_IMAGE = 99000 #　need this because defalt detection number is 100
 cfg.TEST.AUG.MAX_SIZE = 990000
- 
#mAP 91.554% 174
 cfg.MODEL.PIXEL_MEAN= [10.353, 11.628, 12.3675]
 cfg.MODEL.FPN.IN_FEATURES = ["res2", "res3", "res4", "res5"]
 cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[4, 8, 16, 32, 64, 128, 256, 512]]
 cfg.TEST.DETECTIONS_PER_IMAGE = 99000 #　need this because defalt detection number is 100
 cfg.TEST.AUG.MAX_SIZE = 990000
 cfg.MODEL.FPN_ON = True
 cfg.MODEL.RPN.IN_FEATURES = ["p2", "p3", "p4", "p5", "p6"]

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
