### ISSUE TITLE
Support BitMasks.get_bounding_boxes()

### ISSUE THREAD

**Issue by DIYer22** [facebookresearch/detectron2#1216]
## 🚀 Feature

Support `BitMasks.get_bounding_boxes()`

## Motivation & Examples
When using bitmask mask, setting CROP.ENABLED True will raise NotImplementedError in [`BitMasks.get_bounding_boxes()`](https://github.com/facebookresearch/detectron2/blob/6e150b3adb3be1f18efd0bf940206d99c95dbbd8/detectron2/structures/masks.py#L201)

**code:**
```bash
... INPUT.MASK_FORMAT bitmask INPUT.CROP.ENABLED True 
# will raise NotImplementedError
```
As my opinion, CROP is a useful data augmentation, especially when there is insufficient data.

**Comment by ppwwyyxx** [comment]
added in https://github.com/facebookresearch/detectron2/pull/1758
