### ISSUE TITLE
`GLIBC_2.14' not found

### ISSUE THREAD

**Issue by EBJames** [facebookresearch/detectron2#122]
Hi, I hope this is the right place to put this!

I'm trying to follow through the install instructions on the collab book and keep getting the following error when I type: `pip install -e detectron2_repo`

Error:
`ERROR: Command errored out with exit status 1:
     command: /nethome/ebj26/apps/anaconda3/envs/detectron2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/nethome/ebj26/detectron2_repo/setup.py'"'"'; __file__='"'"'/nethome/ebj26/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /nethome/ebj26/detectron2_repo/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/nethome/ebj26/detectron2_repo/setup.py", line 7, in <module>
        import torch
      File "/nethome/ebj26/apps/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
        from torch._C import *
    ImportError: /share/sys65/root/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /nethome/ebj26/apps/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
I'm trying to install and run detectron in a conda environment using python 3.6.
Conda: 4.7.12
Python: 3.6.9
CentOS 6.5

I tried installing new GLIBC, but 2.14 was not an option to install, and newer versions of GLIBC gave a segmentation fault.

Thanks in advance for any help!

Ed

**Comment by ppwwyyxx** [comment]
From the error log, your command failed to `import torch`. Please reach out to pytorch forum or issues for pytorch installation questions.
