### ISSUE TITLE
PIL warnings for decompression bomb

### ISSUE THREAD

**Issue by xkszltl** [facebookresearch/detectron2#1221]
We're seeing some warnings in log during training:
```
/usr/local/lib/python3.6/dist-packages/PIL/Image.py:2800: DecompressionBombWarning: Image size (96487340 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
```
I think PIL is complaining about large normal images, and `Image.MAX_IMAGE_PIXELS = None` should be set since training data is usually "safe enough".

**Comment by ppwwyyxx** [comment]
closing as explained in https://github.com/facebookresearch/detectron2/pull/1223#issuecomment-619808236
