### ISSUE TITLE
Release Imagenet training Code or link to it

### ISSUE THREAD

**Issue by PhilipMay** [facebookresearch/detectron2#1225]
## Feature
Please release the code you used to train the backbone nets with imagenet. Or at least link to it.

## Motivation & Examples
The documentation sais how to train from scratch or how to finetune. What is missing is how to pretrain new backbones with imagenet. Do you use image augmentation for pretraining? An so on...

Could you please release or link to example code?

**Comment by ppwwyyxx** [comment]
ImageNet pre-training is not what this project mean to do.
There are many other open source projects that can train ImageNet models, such as https://github.com/facebookresearch/pycls, https://github.com/pytorch/examples
