### ISSUE TITLE
About canonical level

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#1229]
When you assign proposal boxes to feature level,
canonical box with a size of 224 is mapped to feature map level 4, where the anchor has a size of 128, right?
I just wonder why the canonical box does not match with level 5, where the anchor has a size of 256, which has a more similar size.

**Comment by ppwwyyxx** [comment]
This is what the paper https://arxiv.org/abs/1612.03144 describes, so it's not a question specifically about detectron2
