### ISSUE TITLE
Can you show the evironmet of the offical detectron2 docker images?

### ISSUE THREAD

**Issue by lyc6749** [facebookresearch/detectron2#1230]
## ❓ How to use Detectron2

I stll meet the problem of high gpu menmory coast during inference by docker? Can you show the details of the official evironment?

**Comment by ppwwyyxx** [comment]
the official docker is provided at https://github.com/facebookresearch/detectron2/tree/master/docker

**Comment by lyc6749** [comment]
but the network doesnt allowed me to install online,can you show `pip list` in your evironmet, then I can install offline.

**Comment by lyc6749** [comment]
when i run `USER_ID=$UID docker-compose run detectron2:` th error  Invalid interpolation format for "build" option in service "detectron2": "${USER_ID:-1000}"

**Comment by lyc6749** [comment]
> the official docker is provided at https://github.com/facebookresearch/detectron2/tree/master/docker

when i run  `USER_ID=$UID docker-compose run detectron2` the error Invalid interpolation format for "build" option in service "detectron2": "${USER_ID:-1000}"

**Comment by ppwwyyxx** [comment]
According to https://github.com/Mailu/Mailu/issues/853 it's because your docker-compose is old

Using the dockerfile directly with Nvidia runtime should also work.
