### ISSUE TITLE
Panoptic FPN Model Request 

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#1231]
## 🚀 Feature
Panoptic FPN weight trained on RestNet101 backbone and RestNext101 backbone.

## Motivation & Examples
It would be a nice baseline
I hope they could be included in a model zoo.

**Comment by ppwwyyxx** [comment]
One with ResNet 101 is already available. In general we don't take "model zoo requests"

**Comment by emjay73** [comment]
There was a lack of information. I meant the Panoptic FPN model with ResNet101 backbone which was trained with the cityscapes dataset.

**Comment by ppwwyyxx** [comment]
Then it is a duplicate of #610. We have plans on this so it's kept open. But not going to happen soon.
