### ISSUE TITLE
How do I load a previously trained model (model_final.pth file) and execute it to infer objects from a completely unvisited set of images (with no assigned COCO dictionary)? 

### ISSUE THREAD

**Issue by KevinG1002** [facebookresearch/detectron2#1232]
**Context**
- Deployed detectron2's "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml" model from the model zoo and trained it on a single-class custom dataset (both training and testing sets, as indicated in the tutorials, were accompanied with a COCO dict describing the dataset).
- Evaluated the model on a custom test dataset, and was pleased with the results. 
- Saved my model as "model_final.pth" file in the config output directory.  

**What I want to achieve**
I would like to write a separate script that loads my custom trained model (R50FPN) and runs an inference job on a completely unvisited set of images possessing no accompanying COCO dict or ground truth labels. 

What would be the best way to achieve this? 

Hereunder is a copy of the code I have written thus far to execute this process. 
`trained_model = os.path.join(model_path, 'model_final.pth')
    cfg = get_cfg()
    cfg.MODEL.DEVICE = "cpu"
    model = build_model(cfg)
    DetectionCheckpointer(model).load(trained_model)

    # DatasetCatalog.register("SunRefs_Test", )
    # MetadataCatalog.get("SunRefs_Test").set(thing_classes=["Sun Reflection"])
    # data_loader = build_detection_test_loader(cfg, "SunRefs_Test")

    cfg.MODEL.WEIGHTS = trained_model
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7
    predictor = DefaultPredictor(cfg)

    for idx, elem in enumerate(os.listdir(image_folder)):
        im = cv2.imread(os.join.path(image_folder, elem))
        output = predictor(im)
        v = Visualizer(im[:, :, ::-1],
                       metadata=None,
                       scale=0.8,
                       instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
                       )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    plt.imshow(v.get_image()[:, :, ::-1])
    plt.savefig(f"Inference_{idx}", dpi=300)`

**Comment by ppwwyyxx** [comment]
> I would like to write a separate script that loads my custom trained model (R50FPN) and runs an inference job on a completely unvisited set of images possessing no accompanying COCO dict or ground truth labels.

The tutorial  https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 does this already.
