### ISSUE TITLE
Can I use ROIAlignRotated as is for mask head?

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detectron2#1235]
## ❓ Can I use ROIAlignRotated as is for mask head?

I am able to modify Detectron2 to predict rotated bbox (x, y, h, w, angle) and associated instance masks.   The issue is the predicted rotated bboxes look perfect but the predicted masks boundaries are very jagged when compared to similar regular/non-rotated model trained on the same dataset.

The jagged mask boundaries lead me to suspect my model suffers a loss of spatial resolution somewhere in the network.   One suspect is the ROIAlignRotated CUDA implementation but it could be somewhere else.  Can someone confirm whether the existing ROIAlignRotated implementation should work with mask head or not?

My config:

MODEL:
  ANCHOR_GENERATOR:
    NAME: RotatedAnchorGenerator
    ANGLES: [[-40,-26,-13,0,13,26,40]]
  PROPOSAL_GENERATOR:
    NAME: RRPN
  RPN:
    BBOX_REG_WEIGHTS: (1,1,1,1,1)
  ROI_BOX_HEAD:
    POOLER_TYPE: ROIAlignRotated
    BBOX_REG_WEIGHTS: (10,10,5,5,1)
 ROI_MASK_HEAD:
    POOLER_TYPE: ROIAlignRotated
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  MASK_ON: True
  ROI_HEADS:
    NAME: RROIHeads
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05 #default 0.05
    NMS_THRESH_TEST: 0.5 #default 0.5
  RESNETS:
    DEPTH: 50

**Comment by alekseynp** [comment]
Am I right about the following?
You've had to write your own code to compute the ground truth mask for a given proposal.
You have had to write your own code for projecting predicted masks back into the original image space?
Either of those two pieces of code could be suspect and would make great contributions?

**Comment by ppwwyyxx** [comment]
I'm not aware of any project or papers that have done this. So it's more of a problem of __how__ to do this. 
The suggestions from @alekseynp sound reasonable. Or a simpler alternative of using non-rotated roialign for mask branch may also work. Either way you'll have to implement them and explore what works.

**Comment by jackkwok** [comment]
@alekseynp : You are correct. I have written all those pieces and more.
