### ISSUE TITLE
How to run Denspose with pre-trained model with only cpu.

### ISSUE THREAD

**Issue by frankkim1108** [facebookresearch/detectron2#1239]
## ❓ How to use Detectron2

Questions like:

1. How to run Densepose with pre-trained model with only cpu.

I have  downloaed Detectron2 with
`python3 -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html`

And I ran my code and got an error saying
**'Segmentation Fault"**

I searched it on issue and some people said it was becuase it was trying to run on GPU.
How do I run in on CPU only?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
