### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by ZHJ0125** [facebookresearch/detectron2#124]
## To Reproduce

I installed detectron2 on Windows and output the following error warning when configuring fvcore with pip:
> C:\Users\ZHJ>pip install git+https://github.com/facebookresearch/fvcore
Collecting git+https://github.com/facebookresearch/fvcore
  Cloning https://github.com/facebookresearch/fvcore to c:\users\zhj\appdata\local\temp\pip-req-build-85w3712z
  Running command git clone -q https://github.com/facebookresearch/fvcore 'C:\Users\ZHJ\AppData\Local\Temp\pip-req-build-85w3712z'
Collecting yacs>=0.1.6 (from fvcore==0.1)
  Using cached https://files.pythonhosted.org/packages/2f/51/9d613d67a8561a0cdf696c3909870f157ed85617fea3cff769bb7de09ef7/yacs-0.1.6-py3-none-any.whl
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda\install\lib\site-packages (from fvcore==0.1) (5.1.2)
Requirement already satisfied: tqdm in d:\anaconda\install\lib\site-packages (from fvcore==0.1) (4.36.1)
Collecting portalocker (from fvcore==0.1)
  Using cached https://files.pythonhosted.org/packages/60/ec/836a494dbaa72541f691ec4e66f29fdc8db9bcc7f49e1c2d457ba13ced42/portalocker-1.5.1-py2.py3-none-any.whl
Collecting termcolor>=1.1 (from fvcore==0.1)
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting shapely (from fvcore==0.1)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Command errored out with exit status 1:
     Command: 'D:\Anaconda\install\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ZHJ\\AppData\\Local \\Temp\\pip-install-y9hq5161\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\ZHJ\\AppData\\Local\\Temp\\ Pip-install-y9hq5161\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read() .replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'" 'exec'"'"'))' egg_info --egg-base pip-egg-info
         Cwd: C:\Users\ZHJ\AppData\Local\Temp\pip-install-y9hq5161\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ZHJ\AppData\Local\Temp\pip-install-y9hq5161\shapely\setup.py", line 80, in <module>
        From shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\ZHJ\AppData\Local\Temp\pip-install-y9hq5161\shapely\shapely\_buildcfg.py", line 200, in <module>
        Lgeos = CDLL("geos_c.dll")
      File "D:\Anaconda\install\lib\ctypes\__init__.py", line 364, in __init__
        Self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Environment
Windows10 + Anaconda (Python3.7) + torchvision-0.4.1 + pytorch-1.3.0 + cudatoolkit-10.1.168

How can I solve this problem? Thank you.

**Comment by ppwwyyxx** [comment]
The error comes from the installation of "shapely" library and therefore is unrelated to detectron2. Please reach out to the shapely project for help. Most likely you're missing the geos dependency of shapely.

I think we could make shapely an optional dependency since it's not used by the common pipeline.

**Comment by ZHJ0125** [comment]
I installed "geos" and "shapely" and the problem was solved.
Thank you.

**Comment by teja-cyber** [comment]
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
while installing kivy

**Comment by Jitesh7890** [comment]
C:\Users\Jitesh>pip install pandas2
Collecting pandas2
  Using cached https://files.pythonhosted.org/packages/a1/4f/e344f945afdeb0d87e0a54371415170e37bdafb104389ecf47f22854a678/pandas2-0.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jitesh\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jitesh\\AppData\\Local\\Temp\\pip-install-s6p_2wug\\pandas2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jitesh\\AppData\\Local\\Temp\\pip-install-s6p_2wug\\pandas2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Jitesh\AppData\Local\Temp\pip-install-s6p_2wug\pandas2\pip-egg-info'
         cwd: C:\Users\Jitesh\AppData\Local\Temp\pip-install-s6p_2wug\pandas2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jitesh\appdata\local\programs\python\python37-32\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jitesh\\AppData\\Local\\Temp\\pip-install-s6p_2wug\\pandas2\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

help!!!

**Comment by Ishikakhanna123** [comment]
I am trying to add some flask plugings in anacoda but the same error is coming.

Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by erselbey** [comment]
Collecting pycopy-filecmp
  Using cached pycopy-filecmp-0.0.0.tar.gz (610 bytes)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YFj__e/pycopy-filecmp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YFj__e/pycopy-filecmp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8IERTV
         cwd: /tmp/pip-install-YFj__e/pycopy-filecmp/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-YFj__e/pycopy-filecmp/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
