### ISSUE TITLE
Saving config file in detectron2

### ISSUE THREAD

**Issue by rezamirshahi** [facebookresearch/detectron2#1242]
I have actually 2 questions:
1. how can I save my current config file for using in deployment?
2. is it possible to obtain AUC in model evaluation?

**Comment by ppwwyyxx** [comment]
1. https://detectron2.readthedocs.io/modules/config.html#detectron2.config.CfgNode.dump
2. We produce standard metrics used for each task. If you need any other evaluation metrics see https://detectron2.readthedocs.io/tutorials/evaluation.html
