### ISSUE TITLE
ImportError: cannot import name '_C' from 'detectron2'

### ISSUE THREAD

**Issue by nmanhong** [facebookresearch/detectron2#1244]
Execute under windows
python -m detectron2.utils.collect_env
get
sys.platform win32
Python 3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
numpy 1.18.2
detectron2 0.1.1 @F: \ WorkSpace \ detectron2-master \ detectron2
detectron2._C failed to import
DETECTRON2_ENV_MODULE <not set>
PyTorch 1.4.0 @C: \ anaconda3py3.7 \ envs \ niepy \ lib \ site-packages \ torch
PyTorch debug build False
CUDA available True
GPU 0 GeForce GTX 960
CUDA_HOME E: \ Program Files \ NVIDIA_GPU_Computing \ Tookit \ CUDA \ v10.2
NVCC Not Available
Pillow 7.1.0
torchvision 0.5.0 @C: \ anaconda3py3.7 \ envs \ niepy \ lib \ site-packages \ torchvision
torchvision arch flags C: \ anaconda3py3.7 \ envs \ niepy \ lib \ site-packages \ torchvision \ _C.pyd; cannot find cuobjdump
cv2 4.2.0
---------------------- ---------------------------- -------------------------------------------------- ----------
PyTorch built with:
  -MSVC 191125547
  -Intel (R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel (R) 64 architecture applications
  -OpenMP 200203
  -CUDA Runtime 10.1
  -NVCC architecture flags: -gencode; arch = compute_37, code = sm_37; -gencode; arch = compute_50, code = sm_50; -gencode; arch = compute_60, code = sm_60; -gencode; arch = compute_61, code = sm_61;- gencode; arch = compute_70, code = sm_70; -gencode; arch = compute_75, code = sm_75; -gencode; arch = compute_37, code = compute_37
  -CuDNN 7.5.1
  -Magma 2.5.1
  -Build settings: BLAS = MKL, BUILD_NAMEDTENSOR = OFF, BUILD_TYPE = Release, CXX_FLAGS = / DWIN32 / D_WINDOWS / GR / w / EHa / MP / bigobj -openmp, DISABLE_NUMA = 1, PERF_WITH_AVX = 1, PERF_WITH_AVX2 = 1, USE_CUDA , USE_EXCEPTION_PTR = 1, USE_GFLAGS = OFF, USE_GLOG = OFF, USE_MKL = ON, USE_MKLDNN = OFF, USE_MPI = OFF, USE_NCCL = OFF, USE_NNPACK = OFF, USE_OPENMP = ON, USE_STATIC_DISPATCH = OFF

What should I do to solve this problem

**Comment by nmanhong** [comment]
I have installed GCC
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/8.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-8.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/lib -L/c/mingw810/prerequisites/x86_64-zlib-static/lib -L/c/mingw810/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**Comment by ppwwyyxx** [comment]
You probably did not install detectron2: https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

But in general we don't provide support for windows.
