### ISSUE TITLE
joint training of ROI head and RPN

### ISSUE THREAD

**Issue by nihal-rao** [facebookresearch/detectron2#1245]
In all models with the "**Generalized RCNN**" meta-architecture , the RPN is trained jointly with the ROI box detection head. The forward pass through the RPN generates region proposals which are treated as fixed,  pre-computed proposals when training a Fast R-CNN detector.

However in this method, if a model is now trained completely from scratch, I imagine there will be misclassified (anchors with IoU less than the threshold, wrongly classified as positive) regions from the RPN which will be sent to the ROI head for training. Won't this result in wrong gradient values quite early in the training and destabilize training?

How is this taken care of in detectron2?

**Comment by ppwwyyxx** [comment]
We follow the paper unless otherwise noted.
