### ISSUE TITLE
Trying to load my own balloon_dataset.zip file from my GitHub

### ISSUE THREAD

**Issue by Philliec459** [facebookresearch/detectron2#1247]
In the following tutorial there is a link to a notebook that makes a wget to a balloon_dataset.zip file:

https://detectron2.readthedocs.io/tutorials/getting_started.html

The following is the command line that executes this wget:

wget https://github.com/matterport/Mask_RCNN/releases/download/v2.1/balloon_dataset.zip

and it works perfect. 

I downloaded this same balloon_dataset.zip file and placed it on my own GitHub as a test to be able to read files from my GitHub. Using almost the same command as before, but with the link to my GitHub I have a problem:

wget https://philliec459.github.io/Marine/balloon_dataset.zip

_Message:
--2020-04-18 16:17:11--  https://philliec459.github.io/Marine/balloon_dataset.zip
Resolving philliec459.github.io (philliec459.github.io)... 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Connecting to philliec459.github.io (philliec459.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133 [application/zip]
Saving to: ‘balloon_dataset.zip’

balloon_dataset.zip 100%[===================>]     133  --.-KB/s    in 0s      

2020-04-18 16:17:11 (4.68 MB/s) - ‘balloon_dataset.zip’ saved [133/133]

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of balloon_dataset.zip or
        balloon_dataset.zip.zip, and cannot find balloon_dataset.zip.ZIP, period_._

I am not sure what I am doing wrong, but please help.

I would like to use this detrectron2 tutorial to train my own nautical themed objects, but some to

**Comment by ppwwyyxx** [comment]
unrelated to detectron2.
