### ISSUE TITLE
Make TensorMask work with lvis dataset

### ISSUE THREAD

**Issue by onexmaster** [facebookresearch/detectron2#1248]
I am Trying to train tensormask model on lvis dataset. For that i downloaded the lvis dataset and changed the train and test in base_tensormask.yaml from coco-2017 to lvis_2017_train/test and changed the batch size from 16 to 4,the data loads correctly, but unfortunately it gives me the following error.
`
File "/home/onexmaster2447/.local/lib/python3.7/site-packages/fvcore/nn/smooth_l1_loss.py", line 63, in smooth_l1_loss
    loss = torch.abs(input - target)
RuntimeError: The size of tensor a (37) must match the size of tensor b (47) at non-singleton dimension 0.
`
I tried to find the size of tensors , and this was the following output 

Pred shape is torch.Size([37, 4])
GT shape is torch.Size([47, 4]).

Any help would be appreciated.

**Comment by ppwwyyxx** [comment]
Detectron2 already contains builtin support for LVIS dataset, so you should not use some "lvis_2017_train", whatever it is.

If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by onexmaster** [comment]
Made the appropriate changes in the config file 
This is how my tensormask_R_50_FPN_1x.yaml looks like 
`_BASE_: "Base-TensorMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
   NUM_CLASSES: 1230
   SCORE_THRESH_TEST: 0.0001
INPUT:
 MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
    TRAIN: ("lvis_v0.5_train",)
    TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
`
Still I am getting the same error.

**Comment by ppwwyyxx** [comment]
The num_classes you should change is `MODEL.TENSORMASK.NUM_CLASSES`.

Again, If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
