### ISSUE TITLE
Will you add the function of displaying fps？

### ISSUE THREAD

**Issue by BIYTC** [facebookresearch/detectron2#1249]
## Motivation & Examples

Sometimes  I need to know if my code can implement real time，so I want to show the processing FPS and video playback FPS.

You can find the code in https://github.com/dbolya/yolact, they have a "--display_fps" to draw the FPS directly on the frame, thank you.

**Comment by ppwwyyxx** [comment]
There are many libraries that can draw text on images. It doesn't seem valuable to have it in detectron2 when it's unrelated to object detection and can be easily done with other libraries.
