### ISSUE TITLE
MaskRCNN Sync BN setting mismatch

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/detectron2#1250]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. I compared  https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml and https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/mask_rcnn_R_50_FPN_3x_syncbn.yaml

2. I found that 
![image](https://user-images.githubusercontent.com/11813362/79678440-3525d600-822e-11ea-8120-764169a4e43b.png)

why NUM_CONV and NUM_FC in ROI_BOX_HEAD need to be modified when add syncbn?

**Comment by ppwwyyxx** [comment]
This is a common practice. https://arxiv.org/pdf/1906.07155.pdf has some explanation and ablations.
