### ISSUE TITLE
Can detectron2 work as deb package?

### ISSUE THREAD

**Issue by TTamyy** [facebookresearch/detectron2#1252]
## 🚀 Feature
How to create deb package for detectron2 by stdeb

## Motivation & Examples

Help me to make automation of installing, upgrading, configuring, and removing computer programs for Debian in a consistent manner.

## Note

I try to but many fails for folder layer, you can try install stdeb and use python3 setup.py --command-packages=stdeb.command bdist_deb on ubuntu 18.04 to check.

**Comment by ppwwyyxx** [comment]
It may be possible but we have no plans to do so.
