### ISSUE TITLE
Visualize transformed annotations

### ISSUE THREAD

**Issue by timofurrer** [facebookresearch/detectron2#1253]
I'm having troubles visualizing the transformed annotations from sampled images using the `DefaultTrainer.build_train_loader(cfg)` loader. By using this *trainer / builder* I'm also using the default crop, resize and random flip transformers.

I've tried to use the `Visualizer`s `overlay_instances` method, like this:

```python
train_loader = DefaultTrainer.build_train_loader(cfg)

sample_image_batches = 2
f = plt.figure(figsize=(20, 10 * sample_image_batches))
idx = 1
for sample_image_batch_idx, train_image_batch in enumerate(train_loader):

    for idx, train_image in enumerate(train_image_batch):
        image = train_image["image"].numpy().transpose(2, 1, 0)

        # visualize ground truth
        gt_visualizer = Visualizer(
            image[:, :, ::-1], metadata=dataset_train_metadata, scale=1
        )
        gt_image = gt_visualizer.overlay_instances(
            boxes=train_image["instances"].gt_boxes, 
            masks=train_image["instances"].gt_masks, 
            labels=train_image["instances"].gt_classes
        )

        f.add_subplot(sample_image_batches, 2, (2 * sample_image_batch_idx) + idx + 1)
        plt.title(f"Image {train_image['file_name']}")
        plt.imshow(gt_image.get_image()[:, :, ::-1])

        break

plt.show()
```

I don't understand why the annotations are not in the correct place. 
As far as I can tell those should be transformed here:
https://github.com/facebookresearch/detectron2/blob/d1c7a4a63b4e24b02564cbef0bd18d28f757bc0d/detectron2/data/dataset_mapper.py#L127

**Comment by ppwwyyxx** [comment]
I can't tell from the issue why you think it is a detectron2 issue?

```
python tools/visualize_data.py --source dataloader --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --show
```
will visualize the data loader.

**Comment by timofurrer** [comment]
I'm not saying it's a detectron2 issue - maybe my usage is just wrong.

I've modified the Tutorial notebook slightly and added the code in question to illustrate the problem.
The notebook is here: https://drive.google.com/file/d/1aPRkNFnAEiYLg7HPXRlyLOVQ5trzhiqF/view?usp=sharing

And a screenshot of the results for convenience:

![image](https://user-images.githubusercontent.com/1008252/79699717-70a5bc00-8291-11ea-998f-918bac927288.png)

**Comment by timofurrer** [comment]
The issue was in the transformation of the tensor to an actual image, where I mixed up the width and height.
