### ISSUE TITLE
What's the reason for using 7x7 mask of the mask head?

### ISSUE THREAD

**Issue by yzlyty** [facebookresearch/detectron2#1257]
1. Why not directly use the original mask head of 28x28?
2. For semantic segmentation, do you experiment on the DeeplabV3+ model (only seen DeeplabV3 in the paper)?

**Comment by ppwwyyxx** [comment]
Issue does not belong to any category in https://github.com/facebookresearch/detectron2/issues/new/choose, closing.

Our github is for issues related to the code, not for discussing research topics.
