### ISSUE TITLE
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")

### ISSUE THREAD

**Issue by Philliec459** [facebookresearch/detectron2#1258]
How do I actually access/save the newly trained MODEL.WEIGHTS or even a model to be used as a new pre-train model for future deployment?

I have gone through the tutorials and now have a very good predictive model for image segmentation with detectron2 using Matterport's MASK_RCNN marine dataset. I would now like to save and have access to these model weights or even a new model.

![image](https://user-images.githubusercontent.com/56929340/79718094-7783fd00-8298-11ea-9e82-eb2760ab21a2.png)

**Comment by ppwwyyxx** [comment]
I think the title of your issue is the answer. If that does not answer your issue please be more specific about why it does not do what you expect.

**Comment by Philliec459** [comment]
I am sorry for the cryptic title. The tutorials have the following line for what I have interpreted as the path to the model weights. I am working in Colab. 

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")

You would think that I would find these weights. Somehow, I would like access to these weights data, but I am not sure how to actually get it to my mac. Maybe all I need to do is to literally define OUTPUT_DIR????

I would appreciate any suggestions.

**Comment by ppwwyyxx** [comment]
I still cannot understand what you expect. 
`os.path.join(cfg.OUTPUT_DIR, "model_final.pth")` is the path to the weights. If you can make predictions using it, you already have access to it.

**Comment by Philliec459** [comment]
OK, I figured it out. I am working in Colab. Colab stores all the checkpoint data under the ./output directory. However, I did not know how to access these data in Colab. Today l I found that if you tap on the folder icon to the very left in the Table of Contents, this brings up the files showing everything that is stored in Colab. I then right-clicked on each file under ./output and downloaded each file. The model_final.pth was 351 mB, so now I have it. Thanks for being patient with me on this.

**Comment by GeNiaaz** [comment]
Hi, how do you go about opening ur .pth file up to test in Colab ?

**Comment by Philliec459** [comment]
It has been a while since I did this, but I think all I did was load the model_final.pth as shown below. 

# Directory where output files are written
cfg.OUTPUT_DIR = "./output"

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = ("nautical_ecp", )
predictor = DefaultPredictor(cfg)

my issue was finding the model_final.pth in Colab that I had created through training. I found that under the little folder icon on the far left side of Colab. I downloaded this from Colab and used these weights on my mac. 


Best Regards, 
 
_______________________________
 
E. Craig Phillips
CEO and Chief Petrophysicist
Crested Butte Petrophysical Consultants
 







459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
email: craig@cbpetro.com
Website: www.cbpetro.com
GitHub: https://github.com/Philliec459



The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.

On Jun 26, 2020, at 10:49 PM, GeNiaaz <notifications@github.com> wrote:


Hi, how do you go about opening ur .pth file up to test in Colab ?
