### ISSUE TITLE
段错误 (核心已转储)  （segment fault（core dump））

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1262]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
I made no changes to the code.
```
2. what exact command you run:

./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cpu

3. what you observed (including __full logs__):
```
[04/20 19:15:04 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
[04/20 19:15:04 d2.data.common]: Serialized dataset takes 19.48 MiB
[04/20 19:15:04 d2.export.caffe2_export]: Exporting a Caffe2GeneralizedRCNN model via ONNX ...
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert tensor.dim() == 2 and tensor.size(-1) in [4, 5, 6], tensor.size()
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:373: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert box_regression.shape[1] % box_dim == 0
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:380: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_tensor_mode:
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:427: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  legacy_plus_one=False,
/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/tensor.py:461: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:441: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i, b in enumerate(int(x.item()) for x in roi_batch_splits_nms)
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:76: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  data_len = len(value)
/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return len(self.indices)
段错误 (核心已转储)
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

I'm running the example in Deployment, and it has been unsuccessful, so I don't know what results should be observed, but definitely should not appear "段错误 (核心已转储)"

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py

------------------------  -----------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
numpy                     1.17.4
detectron2                0.1.1 @/home/along/lmf_workspace/detectron2/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2080 Ti
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
torchvision               0.5.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  -----------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[Thread 0x7ffff7fcf740 (LWP 12380) exited]
[Inferior 1 (process 12380) exited normally]
No stack.

```

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues already. A result of https://github.com/pytorch/pytorch/issues/33003

**Comment by lyc6749** [comment]
> If you do not know the root cause of the problem / bug, and wish someone to help you, please
> post according to this template:
> 
> ## Instructions To Reproduce the Issue:
> 1. what changes you made (`git diff`) or what code you wrote
> 
> ```
> I made no changes to the code.
> ```
> 
> 1. what exact command you run:
> 
> ./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cpu
> 
> 1. what you observed (including **full logs**):
> 
> ```
> [04/20 19:15:04 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
> [04/20 19:15:04 d2.data.common]: Serialized dataset takes 19.48 MiB
> [04/20 19:15:04 d2.export.caffe2_export]: Exporting a Caffe2GeneralizedRCNN model via ONNX ...
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   assert tensor.dim() == 2 and tensor.size(-1) in [4, 5, 6], tensor.size()
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:373: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   assert box_regression.shape[1] % box_dim == 0
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:380: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if input_tensor_mode:
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:427: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   legacy_plus_one=False,
> /home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/tensor.py:461: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   'incorrect results).', category=RuntimeWarning)
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:441: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   for i, b in enumerate(int(x.item()) for x in roi_batch_splits_nms)
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:76: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   data_len = len(value)
> /home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   return len(self.indices)
> 段错误 (核心已转储)
> ```
> 
> 1. please also simplify the steps as much as possible so they do not require additional resources to
>    run, such as a private dataset.
> 
> ## Expected behavior:
> I'm running the example in Deployment, and it has been unsuccessful, so I don't know what results should be observed, but definitely should not appear "段错误 (核心已转储)"
> 
> ## Environment:
> Provide your environment information using the following command:
> 
> ```
> wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
> 
> ------------------------  -----------------------------------------------------------------------------
> sys.platform              linux
> Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
> numpy                     1.17.4
> detectron2                0.1.1 @/home/along/lmf_workspace/detectron2/detectron2/detectron2
> detectron2 compiler       GCC 7.5
> detectron2 CUDA compiler  10.1
> detectron2 arch flags     sm_75
> DETECTRON2_ENV_MODULE     <not set>
> PyTorch                   1.4.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch
> PyTorch debug build       False
> CUDA available            True
> GPU 0                     GeForce RTX 2080 Ti
> CUDA_HOME                 /usr/local/cuda-10.1
> NVCC                      Cuda compilation tools, release 10.1, V10.1.243
> Pillow                    6.2.1
> torchvision               0.5.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torchvision
> torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
> cv2                       4.1.2
> ------------------------  -----------------------------------------------------------------------------
> PyTorch built with:
>   - GCC 7.3
>   - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CUDA Runtime 10.1
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 7.6.3
>   - Magma 2.5.1
>   - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
> 
> [Thread 0x7ffff7fcf740 (LWP 12380) exited]
> [Inferior 1 (process 12380) exited normally]
> No stack.
> ```

have you solved this problem?

**Comment by ppwwyyxx** [comment]
the solution is answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
