### ISSUE TITLE
How to set relative path of datasets

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1270]
I make a new dir in projects directory. When I try to train my model. I get error
`No such file or directory: 'datasets/coco/annotations/instances_train2017.json'`
I had download COCO data and extract it into this format: https://github.com/facebookresearch/detectron2/tree/master/datasets#expected-dataset-structure-for-coco-instancekeypoint-detection
The datasets location is in a relative path '../datasets/coco/annotations/instances_train2017.json'. How to set relative path? Can the training script only be put under detectron2?

**Comment by Yoline777** [comment]
How to set DETECTRON2_DATASETS

**Comment by ppwwyyxx** [comment]
https://linuxize.com/post/how-to-set-and-list-environment-variables-in-linux/
