### ISSUE TITLE
it is confused about inference time with cpu

### ISSUE THREAD

**Issue by gloddream** [facebookresearch/detectron2#1273]
First, i trained the "COCO-Detection/faster_rcnn_R_101_FPN_3x" with custom data under GPU, get "model_final.pth" weight file corrected. Then, i use "caffe2_converter.py" getting "./caffe2_model" file corrected under CPU.
Both is running well.

But:
1、when testing an image with "model_final.pth" on detectron2 under CPU, the inference time is always 5 seconds.( using  'DefaultPredictor(cfg)' )
2、when testing the same  image with "./caffe2_model" under CPU, the inference time is always 10 seconds. ( using  'Caffe2Model.call' )

Why the inference time of 1 < the inference time of 2 , under the same conditions?

Thanks

**Comment by ppwwyyxx** [comment]
Because one uses pytorch and one uses caffe2, i.e. it's different code. They are probably also using different number of threads, etc.

**Comment by ppwwyyxx** [comment]
Not directly related, but when measuring speed using `caffe2_converter.py` we actually observe faster speed than pytorch.

**Comment by gloddream** [comment]
@ppwwyyxx Thanks for your prompt reply.
Maybe I didn't get it right,I always thought the deployment would be faster than others.
I will have a try with  code of 'caffe2_mask_rcnn.cpp'

**Comment by ppwwyyxx** [comment]
Like I said above, we did observe faster speed.

**Comment by DINOUS11** [comment]
Hi @ppwwyyxx  can u give more number about faster speed when convert to onnx? how faster can it be?

**Comment by pratiksparwatwar** [comment]
> 1、when testing an image with "model_final.pth" on detectron2 under CPU, the inference time is always 5 seconds.( using 'DefaultPredictor(cfg)' )

Can this time be reduced to less than 1 second?

**Comment by HOD101s** [comment]
> > 1、when testing an image with "model_final.pth" on detectron2 under CPU, the inference time is always 5 seconds.( using 'DefaultPredictor(cfg)' )
> 
> Can this time be reduced to less than 1 second?

Yes I'm working on a production model and my inference time is 5s. Need to reduce it to 1 . Any help would be great!
