### ISSUE TITLE
How to use 2 Mask-RCNNs in two branches simultaneously in Detectron2 framework?

### ISSUE THREAD

**Issue by SupreethN** [facebookresearch/detectron2#1276]
Suppose there is a new architecture that has two branches. 
Each branch has Mask-RCNN, say M1 and M2.
The input to this new network is an image, which is used by both M1 and M2.
Finally, I combine M1 and M2.

What is a good way to do this in the current framework?
Please note that I should use this framework not only for inference, but also joint training of M1 and M2.

**Comment by alekseynp** [comment]
Maybe if you went into more detail about what if anything is shared between M1 and M2 and what does combine really mean?

**Comment by SupreethN** [comment]
Okay, so here it goes:
A single image is passed to two MaskCNNs. One of them is being trained for segmenting, say, 100 classes. The other MaskRCNN is being trained for segmenting, say, 50 classes. But the second one accepts RoI pooled features from the first one corresponding to foreground objects of first MaskRCNN and then fuses (add or concatenate) such features with the RoI pooled features from itself. 

Now two cases,
1. I might freeze the parts of first network before ROI pooling, and train the other end-to-end.
2. Or I might train both of them end-to-end.

**Comment by theotheo** [comment]
Just for the sake of curiosity what are the reasons for using this architecture?

**Comment by ppwwyyxx** [comment]
Your question seems valid to __any__ deep learning libraries, and you can just: (1) call one model to get what you need (2) call another model to get what you need (3) combine them using some code
So, is there anything you like to know that's specific to detectron2? 

The documentation at https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model about how to use the model may help.

**Comment by SupreethN** [comment]
Let's say I want to build a config file for an architecture with two MaskRCNNs, and I want to freeze one of them. 
I was thinking to write scripts for Backbone, RPN, ROI heads to replace one MaskRCNNs with two.
But I am not sure this is a good idea.
Is there a more elegant way to do this?

**Comment by dhaivat666** [comment]
I have done something similar. Not in the context of MaskRCNN, but I have used a different Region proposal network to get the Region proposals, and passed it to stage-2 of a different Faster RCNN network, so the detections I get in stage-2 of the network are from different Region proposal network, and in detectron2, with modular functionality for backbone, RPN and stage-2, it's doable. You just need to go inside rcnn.py and see at what step do you want to stop executing the code.

**Comment by SupreethN** [comment]
Okay, that means I should allow my Config file to initialize two MaskRCNNs, and modify some functionalities of Backbone, RPN, and ROI heads?

**Comment by dhaivat666** [comment]
So if I understand correctly, you are doing RoI pooling from 2 different networks and fusing the features from both of them? For that you will have to ensure that the features you are adding indeed belong to exact same region of interest in the original image. Otherwise, adding them will give something gibberish. yes, you can initialize 2 MaskRCNNs with 2 configs, and overwrite train loop by passing both the models to the DefaultTrainer/SimpleTrainer, and implement your own training logic there.

**Comment by SupreethN** [comment]
Yes, you are right.
I am closing this issue now.
Thanks everyone for your help.
