### ISSUE TITLE
is there some parameter for Non max suppression ??

### ISSUE THREAD

**Issue by raammishra** [facebookresearch/detectron2#1277]
Hi ,
Thanks for easy to use library for object detection. I have trained my model and getting decent results but in few of the images i am getting multiple detection of same object. 
Is there any parameter for Non max suppression ?
or any other method by which it can be handled.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.

**Comment by raammishra** [comment]
yes, Thanks a lot.
