### ISSUE TITLE
Instructions to use docker's native GPU support without nvidia-docker

### ISSUE THREAD

**Issue by johndpope** [facebookresearch/detectron2#1281]
https://github.com/facebookresearch/detectron2/blob/0c045f269d69ecbf8a4c978ee9a9f61a46861b91/docker/docker-compose.yml#L9

Does this docker file require the (legacy?) nvidia-docker2 to work?

https://github.com/enric1994/detectron-api/issues/1

can detectron2 work with latest docker-compose? without specifying runtime-nvidia ? if so how?

**Comment by ppwwyyxx** [comment]
> Does this docker file require the (legacy?) nvidia-docker2 to work?

It does.

You might need to change the docker compose config file to use newer versions.

Marked this as an enhancement. PRs are welcome.

**Comment by ppwwyyxx** [comment]
Instructions are provided in https://github.com/facebookresearch/detectron2/blob/master/docker/
