### ISSUE TITLE
Types of data augmentation in detectron2

### ISSUE THREAD

**Issue by Ilbotre** [facebookresearch/detectron2#1283]
## ❓ What are the types of data augmentation that you use inside the default mapper?

note: 
I saw in the code that you use cropping if a dedicated flag has been activated before training but  I do not understand if you switch the naive images with the cropped one or if you keep both?
Are there other types of data augmentation?

**Comment by ppwwyyxx** [comment]
There are also resize and flip.
The original image is not used
