### ISSUE TITLE
Update to Cuda 10.2 and Pytorch 1.5

### ISSUE THREAD

**Issue by YacobBY** [facebookresearch/detectron2#1285]
## 🚀 Feature
Since the release of Pytorch 1.5 Cuda 10.1  is a bit obsolete. Cuda 10.1 is  not offered by default on the Nivida CUDA installation page, and needs to be found on a backpage with Google, making it less than ideal to currently base detectron2 on because it causes a lot of confusion in the installation.

It would be handy to update the Detectron Install.md to use Pytorch 1.5 as the latest version as well as include a Pytorch 1.5 with Cuda 10.2 wheel. I've built Detectron with Cuda10.2 and Pytorch 1.5 and my code seems to run the same as it used to, though more extensive testing might be necessaryTM

## Motivation & Examples
Far less confusion installing Detectron because it will use the same version of Cuda and Pytorch that is offered by default on their respective homepages. Also less people posting installation errors because of this.

**Comment by ppwwyyxx** [comment]
We follow the version pytorch uses, so in the next release we'll provide cuda10.2 + pytorch1.5 wheels

**Comment by kakoedlinnoe** [comment]
Hi, Yacob, thank you for your issue. You said that: I've built Detectron with Cuda10.2 and Pytorch 1.5. How did you do this?

**Comment by vineetrshenoy** [comment]
> We follow the version pytorch uses, so in the next release we'll provide cuda10.2 + pytorch1.5 wheels

@ppwwyyxx , Do you have a time estimate regarding when the next release will be? 

@YacobBY if you could provide some info about how you built it, that would be appreciated!

**Comment by ppwwyyxx** [comment]
Build instructions are in https://detectron2.readthedocs.io/tutorials/install.html#build-detectron2-from-source
We'll make a release in a week

**Comment by ppwwyyxx** [comment]
latest release 0.1.2 is built with pytorch 1.5 + cuda 9.2/10.1/10.2

**Comment by JoeyCarson** [comment]
@ppwwyyxx, I am interested in running detectron2 on pytorch container with cuda 10.2.  The colab notebook shows installing detectron2 using pip install detectron2==0.1.2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html

When I install this way, detectron2 still seems to be trying to open cuda 10.1.  Is there a different place to find the release that supports cuda 10.2?

Container image comes from here.
https://ngc.nvidia.com/catalog/containers/nvidia:pytorch

**Comment by ppwwyyxx** [comment]
The index file for cu102 was previously missing.
Now you can change 101 to 102: https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/index.html

**Comment by JoeyCarson** [comment]
@ppwwyyxx Excellent, thanks!  Yes I remember trying to use 102 and it not working.  Thanks for the quick turnaround.

**Comment by Surya20794** [comment]
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.6/index.html
giving this path but still it is searching for cuda 10.1
