### ISSUE TITLE
Can Detectron2 predict XYZ 3D keypoint coordinates of a human somehow?

### ISSUE THREAD

**Issue by ThereIsNoWindBag** [facebookresearch/detectron2#1287]
HI, I read [the Colab tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) and now I'm trying to extract human 3D keypoint coord values from an image.

Are there any ways to extract XYZ keypoint values from an image?
It seems keypoint_rcnn in the tutorial returns (X, Y, score) value.

Thank you!

**Comment by ppwwyyxx** [comment]
Detectron2 does not have an existing model that does this. You can implement something with it.
