### ISSUE TITLE
flop_count_operators for Faster-RCNN and RetinaNet

### ISSUE THREAD

**Issue by ljjyxz123** [facebookresearch/detectron2#1288]
1. what changes you made (`git diff`) or what code you wrote
```
I added :
`if __name__ == "__main__":
    unittest.main()`
in ./detectron2/tests/test_model_analysis.py
```
2. what exact command you run:
`python test_model_analysis.py`

3. what you observed (including __full logs__):
![image](https://user-images.githubusercontent.com/2631417/80174810-60416880-8626-11ea-9b64-462668d8fb8a.png)

My questions:
1. It means that, even the original test code for output flops didn't work;
2. There isn't test_model_analysis code for mask rcnn, is it exactly same with the ones of Faster RCNN and RetinaNet?

Thank you very much!

**Comment by ppwwyyxx** [comment]
The tests can pass on CI today: https://circleci.com/gh/facebookresearch/detectron2/885. Versions of some of your libraries (fvcore or pytorch) are probably incorrect.

The same code works for Mask R-CNN.

**Comment by ljjyxz123** [comment]
> The tests can pass on CI today: https://circleci.com/gh/facebookresearch/detectron2/885. Versions of some of your libraries (fvcore or pytorch) are probably incorrect.
> 
> The same code works for Mask R-CNN.

@ppwwyyxx 
My pytorch version is: 1.4.0, 
CUDA version is: 10.0
fvcore version is: 0.1.dev200418

I think it's corresponding to the library versions' requirements.

Could you give me some other instructions on checking list? 

Thank you!

**Comment by ljjyxz123** [comment]
> The tests can pass on CI today: https://circleci.com/gh/facebookresearch/detectron2/885. Versions of some of your libraries (fvcore or pytorch) are probably incorrect.
> 
> The same code works for Mask R-CNN.

@ppwwyyxx 

Hi~, this is my libraries list.

![image](https://user-images.githubusercontent.com/2631417/80184489-42333280-863d-11ea-9c23-c1030126f567.png)

![image](https://user-images.githubusercontent.com/2631417/80184479-3a738e00-863d-11ea-9486-78ca4a7c5e3e.png)

**Comment by ppwwyyxx** [comment]
You do need a newer version of fvcore, although I'm not sure if the error is related to it.

**Comment by ljjyxz123** [comment]
> You do need a newer version of fvcore, although I'm not sure if the error is related to it.

@ppwwyyxx 
Thank you, but as I installed fvcore from the github address, which I think is the latest version:
`pip install 'git+https://github.com/facebookresearch/fvcore'`

I may change to docker environment if this issue cannot be solved, thanks again~

**Comment by ljjyxz123** [comment]
@ppwwyyxx 

Although I still didn't know the reason why it didn't work under conda environment, I use docker environment, everything is okay now.

Thank you again~

**Comment by ljjyxz123** [comment]
@ppwwyyxx 

Also, the link you wrote is very useful:
 https://circleci.com/gh/facebookresearch/detectron2/885

I found the detailed docker running command list here.

Thank you!
