### ISSUE TITLE
How to work with mixed inputs?

### ISSUE THREAD

**Issue by lvaleriu** [facebookresearch/detectron2#1292]
## ❓ How to work with mixed inputs

1. How to work with **images that have 4 or more channels**? The forth channel may contain some extra information useful for the segmentation, whereas the 3 channels represent the image.

2. Is it possible to have a mixed input composed of an image and a pixel embedding data? i.e: rgb image of shape (h, w, 3) and a second pixel embedding input of shape: (h, w, emb_dim)

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by ppwwyyxx** [comment]
1. The existing models support any number of channels in input images.  You need your own dataloader to create the inputs https://detectron2.readthedocs.io/tutorials/data_loading.html
2. the input can be anything as long as the model you use understands them.
