### ISSUE TITLE
No error report but no training

### ISSUE THREAD

**Issue by AumXIV** [facebookresearch/detectron2#1294]
No error report but no training.

## Instructions To Reproduce the Issue:

1. I just finished train my dataset at iteration 9000 by using pretrained from model zoo.
```
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl" 
cfg.SOLVER.MAX_ITER = 9000
```
2. And I want to train in the same dataset but with my own pretrained. By max iteration 9000 the same as before.
```
cfg.MODEL.WEIGHTS = "output/LP2020/model_final.pth"
cfg.SOLVER.MAX_ITER = 9000
```
In addition, my pretrained weight has been train in the same pretrained model zoo weight for 9000 iters. I mean:
I train              : `Model zoo --9000iters--> my pretrained`
I just train       : `Model zoo --9000iters--> New train`
**I want to train** : `my pretrained --9000iters--> Second new train`

3. And this was happend when i run training:
```
[04/26 00:58:12 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[04/26 00:58:12 d2.data.build]: Using training sampler TrainingSampler
[04/26 00:58:13 d2.engine.train_loop]: Starting training from iteration 9000
[04/26 00:58:13 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
```
4. There is no error report but also no training. I don't think that the reason is  my dataset because I just train it. But maybe something wrong with iteration. Please help me solve this problem. 

## Expected behavior:

Training with other pretrained weight as normal. ^w^

## Environment:

My environment.
```
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     GeForce GTX 1080
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 9.0, V9.0.176
Pillow                    6.2.1
cv2                       4.1.0
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
this should not happen if you use detectron2 from github mater.

**Comment by dhaivat666** [comment]
if I understand correctly, your pretrained is trained for over 9000 iterations, correct? And now you want to train it for another 9000 iterations? I guess it's not training because your model_final.pth already has information about how long it has been trained for and hence the program is thinking that the training is already done. In that case, can you try the following and see if it works?


```
import torch
path = "output/LP2020/model_final.pth"
model = torch.load(path)
model_weights = model['model']
new_model_path = "output/LP2020/model_final_weights.pth"
torch.save(model_weights, new_model_path)
```

And then, you should give 

```
cfg.MODEL.WEIGHTS = "output/LP2020/model_final_weights.pth"
cfg.SOLVER.MAX_ITER = 9000
```
This should start your training, the model_final.pth has other information like number of iterations, optimizer state etc. And hence, when you load it, it's gonna be a dictionary. You only need 'model' key of the dictionary which contains weights of the model. So if you provide just the model, it won't have meta information about the model and hence, should start your training.

**Comment by ppwwyyxx** [comment]
The analysis from @dhaivat666  is correct and with detectron2's master and fvcore's latest version, only "model" will be loaded from `cfg.MODEL.WEIGHTS`.

**Comment by AumXIV** [comment]
@dhaivat666 That work!! 
@ppwwyyxx I download Detectron2 since December 2019, there might be some update. 
Thank you both of you @ppwwyyxx and @dhaivat666  
^w^
