### ISSUE TITLE
Why broadcast_buffers is set False as default?

### ISSUE THREAD

**Issue by nnop** [facebookresearch/detectron2#1297]
https://github.com/facebookresearch/detectron2/blob/4bd92bb9b993312c7598a59fb7c203ad24f3e4a5/detectron2/engine/defaults.py#L281

The [doc](https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel) of `torch.nn.parallel.DistributedDataParallel` says:
> **broadcast_buffers** (bool) – flag that enables syncing (broadcasting) buffers of the module at beginning of the forward function. (default: **True**)

So, it's reasonable to keep its default value(`True`). Why set `False` as default?

This issue is also mentioned in:
* https://github.com/facebookresearch/maskrcnn-benchmark/issues/692
* https://github.com/open-mmlab/mmdetection/issues/2539

**Comment by ppwwyyxx** [comment]
It's False because up to now the option is not known to be useful for any models that we have trained.
