### ISSUE TITLE
when I use demo to process a video I can't find the output file

### ISSUE THREAD

**Issue by BIYTC** [facebookresearch/detectron2#1298]
And I replace "fourcc=cv2.VideoWriter_fourcc(*"x264")" with fourcc=cv2.VideoWriter_fourcc(*"mp4v").
As is shown in Notes: some installation of opencv may not support x264 (due to its license), you can try other format (e.g. MPEG), and I use *"mp4v".

**Comment by ppwwyyxx** [comment]
As the note says it's an issue of opencv so we can't help.
