### ISSUE TITLE
How to get instances while not training

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1299]
I want to compare some data. It seems that batched_inputs don't have instances while not training. How to load instances.

**Comment by ppwwyyxx** [comment]
What is "compare some data"?

**Comment by Yoline777** [comment]
I want to implement CornerNet which get top-left and bottom-right corner from the network. Now I only get top-left point and I want to know the mistake. 
In a word. My script can't get final boxes and I want to debug my code by pilot process.

**Comment by ppwwyyxx** [comment]
I can't understand what you are asking. 

To make others unambiguously understand what you'd like to do, please provide the following:

1. what you will provide as inputs for the thing you want to do:

2. what you expect detectron2 to do with the inputs:

3. what you expect detectron2 to provide you as outputs:

If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Yoline777** [comment]
```
def forward(self, batched_inputs):
    if not self.training:
        return self.inference(batched_inputs)

def inference(batched_inputs):
	pred_tl = ...
	gt_tl = batched_inputs[0]['instances'].to(self.device)["gt_boxes"].tensor[:,:2]
	compare(pred_tl, gt_tl)
```
That's my code. I get key error. Batched_inputs don't have instances key. How to load it while inference.

**Comment by ppwwyyxx** [comment]
It will have instances key if you create `batched_inputs` with instances key and call your function with `batched_inputs`.

So I still cannot understand what is the question (and how it is related to detectron2). 

To make others unambiguously understand what you'd like to do, please provide the following:

If you need help to solve an unexpected issue you observed, please include details following the issue template.

**Comment by Yoline777** [comment]
While training I can get inference from batched_inputs. But can't get from inference.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ppwwyyxx** [comment]
If you don't care about the unexpected issue you observed, and only want to know how to make `batched_inputs` in the forward function have "instances", it's already answered in https://github.com/facebookresearch/detectron2/issues/1299#issuecomment-619512329. If that does not work, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
