### ISSUE TITLE
Pretrained model for class-agnostic variant of Mask-RCNN?

### ISSUE THREAD

**Issue by msuc** [facebookresearch/detectron2#130]
There exists a config for perhaps a class agnostic variant of Mask-RCNN in:
configs/Misc/mask_rcnn_R_50_FPN_1x_cls_agnostic.yaml
I could not find a corresponding model going through MODEL_ZOO entries. 
Is there a pretrained model somewhere available?

Thanks for your help.

**Comment by ppwwyyxx** [comment]
There is no pretrained model for it.
