### ISSUE TITLE
Panoramic segmentation, how to get the coordinates of the center point？

### ISSUE THREAD

**Issue by woshiwoyali** [facebookresearch/detectron2#1301]
Panoramic segmentation, how to get the coordinates of the center point, for example, if the panoramic segmentation graph contains a car, how can I get the coordinates of the center line point of this car?

**Comment by ppwwyyxx** [comment]
Panoptic segmentation by definition should produce segmentation masks, but not other outputs. The output format for the segmentation mask is described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format.
