### ISSUE TITLE
I set num-gpus is 2, but only one GPU work

### ISSUE THREAD

**Issue by zbsean** [facebookresearch/detectron2#1303]
I have 2 GPU, I set num-gpus is 2, but only one GPU work.I use detectron2 api.

def train(args):
    t1=time.time()
    prepare_data()
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.DATASETS.TRAIN = ("my_dataset_train",)
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.0025
    cfg.SOLVER.MAX_ITER = 500
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 45
    cfg.OUTPUT_DIR="../output_result"
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg) 

    trainer.resume_or_load(resume=False)
    trainer.train()

    evaluator = COCOEvaluator("my_dataset_valid", cfg, False, output_dir=cfg.OUTPUT_DIR)
    val_loader = build_detection_test_loader(cfg, "my_dataset_valid")
    inference_on_dataset(trainer.model, val_loader, evaluator)

**Comment by ppwwyyxx** [comment]
cfg.DATALOADER.NUM_WORKERS = 2 is not number of GPUs.

https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line has provided example code for multi gpu training.

**Comment by zbsean** [comment]
I use api and set num-gpus=2, refer example code, btw, I use my dataset is not coco dataset

CUDA_VISIBLE_DEVICES=0 python train.py \
      --config-file retinanet_R_101_FPN_3x.yaml \
      --num-gpus 2 \
      MODEL.WEIGHTS ../pre_model/retinanet_R_101_FPN_3x.pkl

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ppwwyyxx** [comment]
You should not set `CUDA_VISIBLE_DEVICES=0` because it enables only 1 GPU.

**Comment by volodymyrkepsha** [comment]
Hi, I'm having the same issue as the first one.
I'm using DefaultTrainer to train my model but it still uses only 1 gpu (out of 2)
I tried to use
`default_setup(cfg, args)`
with
```
args = default_argument_parser().parse_args()
args.num_gpus=2
```
before training training, and still only one gpu is used. 

Some more info:
```
sys.platform              linux
Python                    3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
Numpy                     1.18.1
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1                   GeForce RTX 2080
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
Pillow                    6.1.0
cv2                       4.1.2

```

**Comment by ppwwyyxx** [comment]
See https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py for example training code that uses multiple GPUs.

**Comment by ssusie** [comment]
> CUDA_VISIBLE_DEVICES=0 python train.py

Instead of 0 write GPU IDs (from nvidia-smi) that you wish to use. E.g. if you want to use gpu 0 and 2, run
```CUDA_VISIBLE_DEVICES=0,2 python train.py```
