### ISSUE TITLE
How to enable access to targets in RoI Heads even during evaluation?

### ISSUE THREAD

**Issue by SupreethN** [facebookresearch/detectron2#1304]
When using an ROI head, an optional ```targets``` parameter is passed to the ```forward``` method.
During training ``` targets``` contain  ground-truth information such as ```gt_boxes```, ```gt_classes```, ```gt_masks```, etc. But during evaluation it is ```None```.

Suppose for some task I need some ground-truth information even during evaluation. In such cases I do not want ```targets``` to be ```None```.  What should I do to enable ```targets``` to have the same information during evaluation as in training? 

Please see [the relevant code here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L550)

**Comment by SupreethN** [comment]
I have tried modifying the GeneralizedRCNN meta-architecture (please see [here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/rcnn.py#L111)).

For example, I added some parts of  ```forward``` method (lines 111 to 119, to be precise) to the ```inference``` method of GeneralizedRCNN in a hope that it would load ```gt_instances```.  But ```gt_instances```  was still ```None```.  

So maybe I need to do something even before GeneralizedRCNN?

**Comment by ppwwyyxx** [comment]
As long as you call a model with instances, it's forward will get the instances. It's by rule of python.

You can then customize your model so it does something different at https://github.com/facebookresearch/detectron2/blob/e6b1fd3313666d3286a95c4a6f2e42f60c10b75c/detectron2/modeling/meta_arch/rcnn.py#L163-L170 from the standard GeneralizedRCNN.

**Comment by SupreethN** [comment]
I checked whether ```gt_instances``` even at the very beginning of  the```forward``` method. But it is ```None``` during evaluation. 
So I think ```gt_instances``` is not available in ```batched_inputs``` argument during evaluation. 
Is there any way I can change this?

**Comment by ppwwyyxx** [comment]
> As long as you call a model with instances, it's forward will get the instances. It's by rule of python.

So the question is what data you use to call the model. If by "evaluation" you mean your data comes from `build_detection_test_loader`, it has no instances on purpose. And in that case you just need to prepare the data in a different way.

**Comment by SupreethN** [comment]
I see. Thanks.
