### ISSUE TITLE
How to plugin a custom predictor into the COCOEvaluator?

### ISSUE THREAD

**Issue by kierangilliam** [facebookresearch/detectron2#1305]
If I'm not mistaken, the COCOEvaluator gives results as to how well a trained model has done by using some sort of predictor on the test set and comparing the IoU of the real test set answers to the predicted results.

In examples I've seen, the test setup is akin to the following:

```
def test(instance, cfg, trainer, test_instance):  
  cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
  cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.75 
  cfg.DATASETS.TEST = (test_instance, )
  predictor = DefaultPredictor(cfg)
  # predictor = ExtendedPredictor(cfg)
  evaluator = COCOEvaluator(test_instance, cfg, False, output_dir=cfg.OUTPUT_DIR)
  test_loader = build_detection_test_loader(cfg, test_instance)
  result = inference_on_dataset(trainer.model, test_loader, evaluator)   # predictor never used
```

How come the predictor is not used in `inference_on_dataset`? Is there a way to run `inference_on_dataset` with a custom predictor?

**Comment by ppwwyyxx** [comment]
> How come the predictor is not used in inference_on_dataset?

Because that's the API: https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.inference_on_dataset. "predictor" has more limited functionalities.

> Is there a way to run inference_on_dataset with a custom predictor?

According to the API, you can use a custom model
