### ISSUE TITLE
about coco polygon 

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1307]
coco.json 
 "segmentation": [
                [
                    81.16883116883116,
                     308.55844155844153,
                    69.8051948051948,
                    292.64935064935065......
}
}

polygon position is decimal point, but we know on image pixels are integer point.
so decimal point will round it down or round it up in training?

**Comment by ppwwyyxx** [comment]
The polygon will be rasterized to a mask: https://en.wikipedia.org/wiki/Rasterisation
It will not be rounded in training.
