### ISSUE TITLE
convert pth to pt 

### ISSUE THREAD

**Issue by lyc6749** [facebookresearch/detectron2#1308]
## ❓ How to use Detectron2

How to convert the model.pth to model.pt？

**Comment by ppwwyyxx** [comment]
Please explain what is model.pth and what is model.pt

**Comment by lyc6749** [comment]
I want to convert the model to be loaded by libtorch.

**Comment by ppwwyyxx** [comment]
libtorch loads many different formats, so I need to know what you're asking

https://github.com/facebookresearch/detectron2/tree/master/tools/deploy loads the converted model using libtorch.

For torchscript format, please search existing issues.

**Comment by lyc6749** [comment]
when I use the `caffe2_converter.py` ，there is an error
![image](https://user-images.githubusercontent.com/33708958/80443459-dce38800-8941-11ea-9ed0-7640c337ecbb.png)

**Comment by lyc6749** [comment]
I want to gain the model of xxx.pt, which is gained by `traced_model = torch.jit.trace(model,tensor_inputs)
    traced_model.save('model.pt')`

**Comment by ppwwyyxx** [comment]
According to users https://github.com/facebookresearch/detectron2/pull/1208#issuecomment-614494634, tracing is already working. But we have not tried and it's not a feature that we support now.
