### ISSUE TITLE
I wanna know what's the differents between the MaskRCNN's R-50-FPN in maskrcnn-benchmark and detectron2

### ISSUE THREAD

**Issue by BIYTC** [facebookresearch/detectron2#1310]
I noticed in maskrcnn-benchmark, the size of the model "mask R-50-FPN" is 338M, while in detectron2,this size is 170M, why?

**Comment by pvtien96** [comment]
I think the docs explained, have a look at this:
https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-detectron-and-maskrcnn-benchmark

**Comment by ppwwyyxx** [comment]
Sounds like a duplicate of #1154. If not, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md): how do you get "the model" and how do you tell its size.
