### ISSUE TITLE
Converting to caffe2 

### ISSUE THREAD

**Issue by Tushig-creator** [facebookresearch/detectron2#1312]
Hello! I got some problem with converting detectron2 to caffe2.
I used the code:

<cd tools/deploy/ && ./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
	--output ./caffe2_model --run-eval \
	MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \
	MODEL.DEVICE cpu>
But i got some error 
![error](https://user-images.githubusercontent.com/59016484/80383978-e08df500-88d6-11ea-896b-aa3c2ac60d42.png)
I checked if there is no json file. But i got it 
![anot ppng](https://user-images.githubusercontent.com/59016484/80384219-319de900-88d7-11ea-8fd3-1690aa8ac8c0.png)
Help me with it. Thanks

**Comment by ppwwyyxx** [comment]
Answered at the beginning of https://github.com/facebookresearch/detectron2/tree/master/datasets

**Comment by rahulbhat44** [comment]
@Tushig-creator I am having the same issue, did you resolve it ? it would be nice if you could explain tell how you did that ?
