### ISSUE TITLE
ID to detected object in demo --webcam

### ISSUE THREAD

**Issue by vmpinho** [facebookresearch/detectron2#1314]
Is it possible to do some kind of tracking using the demo? I mean, having an id for when you have two objects of the same classe when using the demo --webcam would be already nice.

**Comment by pvtien96** [comment]
@vmpinho #1071 may help you.
I'm currently also working on a tracking-by-detection project.
I'm please to discuss with you further.

**Comment by pvtien96** [comment]
You may check my repo:
https://github.com/pvtien96/Detectron2DeepSortPlus

**Comment by ppwwyyxx** [comment]
Tracking is not a feature we plan to add. You can use detectron2's output to something like that yourself (e.g. like the above project).
