### ISSUE TITLE
draw_instance_predictions() in VideoVisualizer does not work when MODEL.ROI_HEADS.NUM_CLASSES=1

### ISSUE THREAD

**Issue by thelinuxmaniac** [facebookresearch/detectron2#1315]
If `MODEL.ROI_HEADS.NUM_CLASSES=1`, then [VideoVisualizer.draw_instance_predictions()](https://github.com/facebookresearch/detectron2/blob/9a07526dec6c04d3cc987066361053730e3b9f99/detectron2/utils/video_visualizer.py#L53) only draws bounding boxes but fails to draw object label because `labels` variable, in [_create_text_labels()](https://github.com/facebookresearch/detectron2/blob/9a07526dec6c04d3cc987066361053730e3b9f99/detectron2/utils/visualizer.py#L196) method, does not get initialized as `len(class_names) > 1` evaluates to `False`. Therefore, the [_create_text_labels()](https://github.com/facebookresearch/detectron2/blob/9a07526dec6c04d3cc987066361053730e3b9f99/detectron2/utils/visualizer.py#L196) method fails to draw class label. The [code should](https://github.com/facebookresearch/detectron2/blob/9a07526dec6c04d3cc987066361053730e3b9f99/detectron2/utils/visualizer.py#L207) be fixed as follows (to accommodate for the case when `len(class_names)` is `1`:

```
labels = None
    if classes is not None and class_names is not None and len(class_names) > 0:
        labels = [class_names[i] for i in classes]
```

I am creating this issue to understand if I am missing some details behind the current `len(class_names) > 1` code. I will send a pull request, if this is a bug. Please confirm.

**Comment by pvtien96** [comment]
![image](https://user-images.githubusercontent.com/25927039/80390025-15e61300-88d6-11ea-97d8-0f6ee427baa1.png)

**Comment by pvtien96** [comment]
#1028 may help you

**Comment by thelinuxmaniac** [comment]
Got it, thank you.

**Comment by ppwwyyxx** [comment]
Yes. Thanks @pvtien96  for the comment
