### ISSUE TITLE
Training with Quantization Noise by Facebook AI Research

### ISSUE THREAD

**Issue by deepseek** [facebookresearch/detectron2#1317]
## 🚀 Feature
Add the ability to train and quantize models with [Quantization Noise](https://github.com/pytorch/fairseq/tree/master/examples/quant_noise).

## Motivation & Examples

This will be very useful for:
- Reducing the model size, example of EfficientNet-B3 model from about 50 MB to 3.3 MB.
- Further tests are required to see the affect on inferencing time.

## Note

https://github.com/pytorch/fairseq/tree/master/examples/quant_noise
https://arxiv.org/abs/2004.07320

**Comment by ppwwyyxx** [comment]
This sounds like a good paper for model quantization, but it's not about object detection and is not a prevalent method used in the object detection field. They can be implemented using detectron2 but doesn't make sense being part of detectron2 today. See our general policy in https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/feature-request.md#note
