### ISSUE TITLE
OpenCV bug

### ISSUE THREAD

**Issue by XiaoJiNu** [facebookresearch/detectron2#132]
Hi, I installed opencv with  anaconda but met a bug as follow. How can I solve this problem?
bug:  cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:615: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

**Comment by ppwwyyxx** [comment]
The error is giving you the instructions. If that does not help, please seek help in opencv forum with full error messages.
