### ISSUE TITLE
C ++ failed to call model for inference with gpu.

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1321]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
When I use cpu to convert model:./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cpu
and use c++ to call the model:./caffe2_mask_rcnn --predict_net=../caffe2_model/model.pb --init_net=../caffe2_model/model_init.pb --input=000000002587.jpg, I succeed.
And I also can use gpu to convert model:./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cuda
But when I change the code caffe2::CPU to caffe2::CUDA in the file caffe2_mask_rcnn.cpp,It compiles normally but throws an error when running.
```
2. what exact command you run: ./caffe2_mask_rcnn --predict_net=../caffe2_model/model.pb --init_net=../caffe2_model/model_init.pb --input=000000002587.jpg
3. what you observed (including __full logs__):
```
./caffe2_mask_rcnn --predict_net=../caffe2_model/model.pb --init_net=../caffe2_model/model_init.pb --input=000000002587.jpg
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
段错误 (核心已转储)
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
------------------------  -----------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
numpy                     1.17.0
detectron2                0.1.1 @/home/along/lmf_workspace/detectron2/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2080 Ti
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
torchvision               0.6.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  -----------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
The c++ example is for CPU inference: https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python

**Comment by sun11** [comment]
I've done it, you just need to change this:
``` 
  // parse Mask R-CNN outputs
  // auto& bbox = BlobGetTensor(*workSpace.GetBlob("bbox_nms"), caffe2::CPU);
  // auto& scores = BlobGetTensor(*workSpace.GetBlob("score_nms"), caffe2::CPU);
  // auto& labels = BlobGetTensor(*workSpace.GetBlob("class_nms"), caffe2::CPU);
  // auto& mask_probs =
  //     BlobGetTensor(*workSpace.GetBlob("mask_fcn_probs"), caffe2::CPU);

  caffe2::Tensor bbox(workSpace.GetBlob("bbox_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
  caffe2::Tensor scores(workSpace.GetBlob("score_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
  caffe2::Tensor labels(workSpace.GetBlob("class_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
  caffe2::Tensor mask_probs(workSpace.GetBlob("mask_fcn_probs")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
```

**Comment by limengfei3675** [comment]
> I've done it, you just need to change this:
> 
> ```
>   // parse Mask R-CNN outputs
>   // auto& bbox = BlobGetTensor(*workSpace.GetBlob("bbox_nms"), caffe2::CPU);
>   // auto& scores = BlobGetTensor(*workSpace.GetBlob("score_nms"), caffe2::CPU);
>   // auto& labels = BlobGetTensor(*workSpace.GetBlob("class_nms"), caffe2::CPU);
>   // auto& mask_probs =
>   //     BlobGetTensor(*workSpace.GetBlob("mask_fcn_probs"), caffe2::CPU);
> 
>   caffe2::Tensor bbox(workSpace.GetBlob("bbox_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
>   caffe2::Tensor scores(workSpace.GetBlob("score_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
>   caffe2::Tensor labels(workSpace.GetBlob("class_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
>   caffe2::Tensor mask_probs(workSpace.GetBlob("mask_fcn_probs")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
> ```

It can solve my problem, most sincere thanks.

**Comment by ppwwyyxx** [comment]
thanks @sun11  for the suggestion. It seems worth adding to the example given how simple it is.

**Comment by limengfei3675** [comment]
> > I've done it, you just need to change this:
> > ```
> >   // parse Mask R-CNN outputs
> >   // auto& bbox = BlobGetTensor(*workSpace.GetBlob("bbox_nms"), caffe2::CPU);
> >   // auto& scores = BlobGetTensor(*workSpace.GetBlob("score_nms"), caffe2::CPU);
> >   // auto& labels = BlobGetTensor(*workSpace.GetBlob("class_nms"), caffe2::CPU);
> >   // auto& mask_probs =
> >   //     BlobGetTensor(*workSpace.GetBlob("mask_fcn_probs"), caffe2::CPU);
> > 
> >   caffe2::Tensor bbox(workSpace.GetBlob("bbox_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
> >   caffe2::Tensor scores(workSpace.GetBlob("score_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
> >   caffe2::Tensor labels(workSpace.GetBlob("class_nms")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
> >   caffe2::Tensor mask_probs(workSpace.GetBlob("mask_fcn_probs")->Get<caffe2::Tensor>(), caffe2::DeviceType::CPU);
> > ```
> 
> It can solve my problem, most sincere thanks.

Hi, have you tried to compile and run caffe2_mask_rcnn.cpp on windows system? I can now compile normally, but there will be an error when running:
[E .. \ .. \ caffe2 \ core \ init_intrinsics_check.cc: 43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may no t get the full speed of your CPU . [E .. \ .. \ caffe2 \ core \ init_intrinsics_check.cc: 43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may n ot get the full speed of your CPU. [E .. \ .. \ caffe2 \ core \ init_intrinsics_check.cc: 43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may no t get the full speed of your CPU. C: \ Users \ Hammer \ source \ repos \ callModel \ x64 \ Debug \ callModel.exe (process 17276) has exited, the return code is: Press any key to close this window ...
Have you encountered this problem?
