### ISSUE TITLE
DensePose is not working properly

### ISSUE THREAD

**Issue by SriRamGovardhanam** [facebookresearch/detectron2#1324]
1. Tried to run using google colab, here is the code
```
!pip install -U torch==1.4 torchvision==0.5 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install cython pyyaml==5.1
!pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())
!gcc --version


git clone https://github.com/facebookresearch/detectron2.git
!cd detectron2 && python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'



import detectron2
#from detectron2.utils.logger import setup_logger
#setup_logger()

# import some common libraries
import numpy as np
import cv2
import random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
#from detectron2 import model_zoo
#from detectron2.engine import DefaultPredictor
#from detectron2.config import get_cfg
#from detectron2.utils.visualizer import Visualizer
#from detectron2.data import MetadataCatalog
```

2. After that this is the command i ran
```
!cd detectron2/projects/DensePose && wget https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl

!cd detectron2/projects/DensePose && python apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml DensePose_ResNet50_FPN_s1x-e2e.pkl demo_im.jpg bbox,dp_segm -v


im = cv2.imread("/content/detectron2/projects/DensePose/outputres.0001.png")
print(im.shape)
cv2_imshow(im)
```
for that this is the output:
```
[04/27 19:15:37 apply_net]: Loading config from configs/densepose_rcnn_R_50_FPN_s1x.yaml
Config 'configs/densepose_rcnn_R_50_FPN_s1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[04/27 19:15:37 apply_net]: Loading model from DensePose_ResNet50_FPN_s1x-e2e.pkl
Shape of ann_index_lowres.bias in checkpoint is torch.Size([15]), while shape of roi_heads.densepose_predictor.ann_index_lowres.bias in model is torch.Size([2]).
ann_index_lowres.bias will not be loaded. Please double check and see if this is desired.
Shape of ann_index_lowres.weight in checkpoint is torch.Size([512, 15, 4, 4]), while shape of roi_heads.densepose_predictor.ann_index_lowres.weight in model is torch.Size([512, 2, 4, 4]).
ann_index_lowres.weight will not be loaded. Please double check and see if this is desired.
[04/27 19:15:42 apply_net]: Loading data from demo_im.jpg
[04/27 19:15:43 apply_net]: Processing demo_im.jpg
[04/27 19:15:43 apply_net]: Output saved to outputres.0001.png



```
![output](https://user-images.githubusercontent.com/35695549/80510167-fca59b00-8997-11ea-8899-004abbf1a104.png)

Didn't understand whats actually happening
please help me out !

**Comment by vkhalidov** [comment]
Hi @SriRamGovardhanam,
The reason you get strange results is that the config file you use is incompatible with the model weights you load.
Please use the [densepose_rcnn_R_50_FPN_s1x_legacy.yaml](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x_legacy.yaml) config file with the old weights [DensePose_ResNet50_FPN_s1x-e2e.pkl](https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl).
Or, even better, use the new [densepose_rcnn_R_50_FPN_s1x.yaml](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x.yaml) config file with the new weights [model_final_162be9.pkl](https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/165712039/model_final_162be9.pkl).
Please check the [model zoo](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/MODEL_ZOO.md) page for the details on different DensePose models performance.

**Comment by SriRamGovardhanam** [comment]
> Hi @SriRamGovardhanam,
> The reason you get strange results is that the config file you use is incompatible with the model weights you load.
> Please use the [densepose_rcnn_R_50_FPN_s1x_legacy.yaml](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x_legacy.yaml) config file with the old weights [DensePose_ResNet50_FPN_s1x-e2e.pkl](https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl).
> Or, even better, use the new [densepose_rcnn_R_50_FPN_s1x.yaml](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x.yaml) config file with the new weights [model_final_162be9.pkl](https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/165712039/model_final_162be9.pkl).
> Please check the [model zoo](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/MODEL_ZOO.md) page for the details on different DensePose models performance.

Thank you so much @vkhalidov 
now its working super good

**Comment by UlaMatt** [comment]
Hi, a question from an absolute beginner here. I was looking into google colab notebooks for running densepose tests on video or image, but they seem to be all outdated... I was wondering if anyone is aware of some more recent resources/ beginners guides? Many thanks

**Comment by vkhalidov** [comment]
@UlaMatt no, currently there are no notebooks for beginners. We plan to add some tutorials, but for now you can check the [Apply Net](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/TOOL_APPLY_NET.md) tool and its [source code](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/apply_net.py). It uses the [DefaultPredictor](https://github.com/facebookresearch/detectron2/blob/7007c4e85be451aa2d60e05be8b5ea983cfaf8cf/detectron2/engine/defaults.py#L160) class to perform inference and shows how to extract data from predictor outputs

**Comment by UlaMatt** [comment]
@vkhalidov thank you very much for your quick reply and all the info! This is very helpful.
