### ISSUE TITLE
Create .pkl file after training and evaluation

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#1327]
Hey,

I successfully trained and evaluated my model. Now I want to load my model in other projects like it works with the pretrained models:

```
# Create config
cfg = get_cfg()
add_tensormask_config(cfg)
cfg.merge_from_file("tensormask_R_50_FPN_1x.yaml")
# load weights from pretrained model
cfg.MODEL.WEIGHTS = "model_final_tensormask_pretrained.pkl"
# Create predictor
predictor = DefaultPredictor(cfg)
# Make prediction
im = cv2.imread("./input2.jpg")
outputs = predictor(im)
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 600,600)
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imshow('image',v.get_image()[:, :, ::-1])
cv2.waitKey(0)
```

I want to use my trained model with random images, like it is possible with the pretrained models.
How can I archive that?

I found https://detectron2.readthedocs.io/tutorials/models.html , but not sure if it's the way to go.
It seems like the .pkl file is doing the job, but how can I create one from my model_final.pth?

Thanks

**Comment by ppwwyyxx** [comment]
You can use model_final.pth the same way a `.pkl` is used.

**Comment by Bamil** [comment]
Thanks for your quick response !

When I apply my own trained "model_final.pth" in the above code, there are the labels associated with 'coco_2017_train' and not my own ones. In my code posted above the .yaml and .pkl files are the important ones for that I think. From that I conclude that there is missing some information in my 'model_final.pth'. 

How do I have to modify my 'model_final.pth', so I can use it with in other projects with my own labels and not the ones from 'coco_2017_train' ?

Thanks

**Comment by ppwwyyxx** [comment]
Because your code above uses `cfg.DATASETS.TRAIN[0]` which is coco.

You need to use your dataset that has metadata: https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by Bamil** [comment]
Ah ok, so if I want to use my model / 'model_final.pth' in another independent program I have to register the dataset and metadata to it like for evaluation after training from the original program which created the 'model_final.pth'. Thought there was a way to use my own model like the coco model above without doing all the register stuff again.

Thank you !
