### ISSUE TITLE
How to set minimal number of object detected by model?

### ISSUE THREAD

**Issue by cjwcommuny** [facebookresearch/detectron2#1328]
I'm using Detectron2 to detect object, and I want  the model to detect at least `K` object in an image, how can I do it?

**Comment by pvtien96** [comment]
Could you please clarify your case? What type of config you want to use? Detection or Segmentation, K object per class or K object per all classes/
By the way, I think you can only set maximum number of object detected by model, not the minimum:
![image](https://user-images.githubusercontent.com/25927039/80560986-1503cd00-8a0d-11ea-917e-24c543ec0c7b.png)
You may refer #1045 #1164 or you will get
If you need help to solve an unexpected issue you observed, please include details following the issue template.
![image](https://user-images.githubusercontent.com/25927039/80561047-598f6880-8a0d-11ea-903a-ba6722d0e443.png)

**Comment by cjwcommuny** [comment]
> Could you please clarify your case? What type of config you want to use? Detection or Segmentation, K object per class or K object per all classes/
> By the way, I think you can only set maximum number of object detected by model, not the minimum:
> ![image](https://user-images.githubusercontent.com/25927039/80560986-1503cd00-8a0d-11ea-917e-24c543ec0c7b.png)
> You may refer #1045 #1164 or you will get
> If you need help to solve an unexpected issue you observed, please include details following the issue template.
> ![image](https://user-images.githubusercontent.com/25927039/80561047-598f6880-8a0d-11ea-903a-ba6722d0e443.png)

Thank you for reply, the config I used is object detection and `k` objects per image. I know there is a way to set max object to be detected as you said, I'm just wondering how can I set the lower bound.

**Comment by pvtien96** [comment]
Assume there is 1 object in the image. You set the lower bound equals to 5 while the model predict there is 1 object. So how do you think about this?

**Comment by cjwcommuny** [comment]
> Assume there is 1 object in the image. You set the lower bound equals to 5 while the model predict there is 1 object. So how do you think about this?

In this situation, I think that, the model may choose 5 the most probable candidates. Although it seems to be weird, but sometimes we do have the need to control the number of object.

**Comment by pvtien96** [comment]
But where will the model get other 4 prediction as well as their properties (4 bounding boxes?)

**Comment by ppwwyyxx** [comment]
You can tune parameters like `SCORE_THRESH_TEST` but there is no guarantee on the minimum number of object detected and that's by design of the models and not related to detectron2.

**Comment by cjwcommuny** [comment]
> You can tune parameters like `SCORE_THRESH_TEST` but there is no guarantee on the minimum number of object detected and that's by design of the models and not related to detectron2.

If I want to fix the number of object detected in an image to be `k`, can I just set `cfg.TEST.DETECTIONS_PER_IMAGE = k` and  `SCORE_THRESH_TEST = 0` ？

**Comment by ppwwyyxx** [comment]
there is no way to fix number of object detected and that's by design of the models and not related to detectron2

**Comment by ppwwyyxx** [comment]
setting `SCORE_THRESH_TEST = 0` will result in more detected objects, though.
