### ISSUE TITLE
How to convert GT mask image to polygon?

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#1330]
I'd like to convert GT segmentation images to polygon type so that I can utilize it for training.
I found the class named "GenericMask" and it's member function named "mask_to_polygons" and
it seems like they are doing what I wanted to do. 
However, the fact that GenericMask class is included in "visualization.py" makes me guilty about using it for GT data conversion. It feels like I have to use those functions only for visualization.
Any suggestion?

**Comment by pvtien96** [comment]
#200 may help you.

**Comment by emjay73** [comment]
> #200 may help you.

It was really helpful!
Especially this part.

```
Now the default dataloader can work with RLE formats inside your dataset.
All you need is:

use RLE format (documented at https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts) in your dataset
set INPUT.MASK_FORMAT='bitmask'.
```
It seems working, but changing polygon masks to bitmasks seems quite a burden for my computer.
I'll update when related issues come up.
For now, I'll close the issue.
Thanks again!

**Comment by pvtien96** [comment]
@emjay73 Generally, detectron2 v0.1.1 supports bitmask conversion. You can search related topic in issues. It helps.
