### ISSUE TITLE
I load the trained model and evaluate it, the result is different with training log

### ISSUE THREAD

**Issue by xiongzihua** [facebookresearch/detectron2#1333]
I have trained a model, it's mAP is
![image](https://user-images.githubusercontent.com/28775927/80596883-a731c280-8a59-11ea-81f1-1d9a66f6e781.png)

model save time is
![image](https://user-images.githubusercontent.com/28775927/80597396-5ec6d480-8a5a-11ea-8133-3d00ba86fa21.png)

then i load and eval the model, use the code below
```python
trainer = Trainer(cfg)
trainer.resume_or_load()
# not do model.eval(), the result is same, i have naive BN in model
trainer.model.eval()
Trainer.test(cfg, trainer.model)
````
it's mAP is
![image](https://user-images.githubusercontent.com/28775927/80597116-fd066a80-8a59-11ea-8645-68976d2e9be3.png)

did any one tried this

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
