### ISSUE TITLE
How can I use non-picture format data as training data

### ISSUE THREAD

**Issue by luckywyy** [facebookresearch/detectron2#1334]
## ❓ How to do something using detectron2

1. How to do X with detectron2?
Can this project only read data from images?Can I read data from text?For example, I store the numpy matrix(maybe the numpy matrix is not suitable for storing images, such as JPG images ) in a text file, and then I read the data training from the text file.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/data_loading.html
