### ISSUE TITLE
How does detectron2 compute min_coordinate for nms_rotated?

### ISSUE THREAD

**Issue by AlenUbuntu** [facebookresearch/detectron2#1337]
Thanks a lot for your awesome detectron2 code. When I was reading the code, I have one question:

At line 140 of [detectron2/layers/nms.py](https://github.com/facebookresearch/detectron2/blob/master/detectron2/layers/nms.py), the min_coordinate is computed by 

`min_coordinate = (
        torch.min(boxes[:, 0], boxes[:, 1]) - torch.min(boxes[:, 2], boxes[:, 3]) / 2
).min()`

I am wondering why it is not the code below?

`min_coordinate = (
        torch.min(boxes[:, 0], boxes[:, 1]) - torch.max(boxes[:, 2], boxes[:, 3]) / 2
).min()`

**Comment by SuperIRabbit** [comment]
You're right, just fixed it, thanks for reporting!
