### ISSUE TITLE
How to execute box task only with MASK_ON

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#1338]
Like Extremenet. We need mask instance while training, but the prediction of our task is only box. Set MASK_ON can get mask info for training, but get segm task. I try to change the value of MASK_ON while evaluator, but get error.
```
class Trainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        cfg.MODEL.MASK_ON = False
```
`AttributeError: Attempted to set MASK_ON to False, but CfgNode is immutable`
Is there a way to use mask for training while not execute segm task.

**Comment by ppwwyyxx** [comment]
Writing a custom dataloader : https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader will let you access masks in the model regardless of config.
