### ISSUE TITLE
How to tranfer the norm.num_batches_tracked parameters in pretrained model myself to the norm layer in detectron2.

### ISSUE THREAD

**Issue by zyyupup** [facebookresearch/detectron2#1340]
I am pretty new to detectron2. I follow the operation in script [tools/convert-torchvision-to-d2.py](https://github.com/facebookresearch/detectron2/blob/master/tools/convert-torchvision-to-d2.py) to use resnet50 pretrained model by myself to mask_rcnn_R50-FPN.
But when i run tools/train_net.py i get the followinng warning:

The checkpoint contains parameters not used by the model:
    backbone.bottom_up.res2.0.conv1.norm.num_batches_tracked
    backbone.bottom_up.res2.0.conv2.norm.num_batches_tracked
    backbone.bottom_up.res2.0.conv3.norm.num_batches_tracked
    backbone.bottom_up.res2.0.shortcut.norm.num_batches_tracked
    ...
    backbone.bottom_up.res5.2.conv1.norm.num_batches_tracked
    backbone.bottom_up.res5.2.conv2.norm.num_batches_tracked
    backbone.bottom_up.res5.2.conv3.norm.num_batches_tracked

Anyone knows  whether these parameters are important or how to use them  in detectron2. 
Thanks.

**Comment by ppwwyyxx** [comment]
"num_batches_tracked" parameters are not useful.
