### ISSUE TITLE
Slack/Discord Channel

### ISSUE THREAD

**Issue by agent79** [facebookresearch/detectron2#1343]
## 🚀 Feature
I believe community for Detectron2 is expanding day by day. Is it possible to create a Slack/Discord channel where researchers can collaborate, discuss and share their learning ?

**Comment by ASKanse** [comment]
if this has been created can some one post the invite link here?

**Comment by agent79** [comment]
Nobody created it officially. 
But here's the unofficial one. Use the following link to join. 

https://join.slack.com/t/detectron2/shared_invite/zt-elxwz1x2-HHu91Sd_TQALkDf9oJ5pMA

**Comment by ppwwyyxx** [comment]
We have enabled "discussions" for this purpose: https://github.com/facebookresearch/detectron2/discussions
