### ISSUE TITLE
about reg loss and cls loss in ROI

### ISSUE THREAD

**Issue by Real-YeJ** [facebookresearch/detectron2#1346]
Hello, when I use maskrcnn_benchmark training, the cls loss in ROI stage is about twice of the reg loss. Perhaps this is because the cls loss calculates all the predicted instances, while the reg loss only needs to consider the foreground instances. But in detectron2, reg loss is greater than cls loss. Why?  thank you.

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/notes/compatibility.html
