### ISSUE TITLE
How disable tensorboard?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#135]
Got a bug inside tensorboard when training with own data, how to disable it?

**Comment by ppwwyyxx** [comment]
If you're using `DefaultTrainer`, you can overwrite its `build_writers` (https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.build_writers).

If not, then tensorboard is not enabled by default.
