### ISSUE TITLE
Does NMS really works or how should I make it work?

### ISSUE THREAD

**Issue by WilburZiWong** [facebookresearch/detectron2#1350]
I ran detectron2 using faster rcnn on my custom dataset and wrote a script to show detection results on raw images, which I found that there would be many overlapping bounding boxes in a certain area. So, I'd like to know does NMS really works or how should I make it work? Thank you!

**Comment by WilburZiWong** [comment]
![Snipaste_2020-05-04_00-11-39](https://user-images.githubusercontent.com/50853324/80919351-036b4e00-8d9c-11ea-9b63-92ed9917d6c6.jpg)
I captured the results of a certain category(category_id = 4) of an image(image_id = 2) and the bboxes' coordinates are so close, so, I thought the NMS did not work.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
