### ISSUE TITLE
I train retinanet and faster rcnn  set MODEL.ROI_HEADS.NUM_CLASSES

### ISSUE THREAD

**Issue by zbsean** [facebookresearch/detectron2#1351]
I train retinanet model, It need set MODEL.ROI_HEADS.NUM_CLASSES and MODEL.RETINANET.NUM_CLASSES, or only set MODEL.RETINANET.NUM_CLASSES?

same question,
I train faster rcnn mode, It need set MODEL.ROI_HEADS.NUM_CLASSES and MODEL.RETINANET.NUM_CLASSES, or only set MODEL.ROI_HEADS.NUM_CLASSES?

**Comment by ppwwyyxx** [comment]
Only one needs to be set. 
https://detectron2.readthedocs.io/tutorials/datasets.html
