### ISSUE TITLE
Unable to get prediction on custom model, Getting no boxes or class with image(s)

### ISSUE THREAD

**Issue by techwitz** [facebookresearch/detectron2#1354]
Hi,

I have trained a model to detect objects and model has been built successfully. But it's not working when i load built model and I get image without boxes.

I have followed all the step to train model as per notwebook https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=6ljbWTX0Wi8E. 

## Instructions To Reproduce the Issue:

**1. Configuration to train model,** 

Loaded image is correct, it's visualize the annotations of randomly selected samples in the training set:
![image](https://user-images.githubusercontent.com/19564411/80976918-ab872280-8e41-11ea-8f95-d25ee512d5b4.png)

`cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo

cfg.OUTPUT_DIR = "/content/drive/My Drive/Colab Notebooks/Webcam/coco-drive/Output"
cfg.DATASETS.TRAIN = ("cardriving_train",)
cfg.DATASETS.TEST = ("cardriving_val",)
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 2

cfg.SOLVER.MAX_ITER = 300

cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.5

cfg.SOLVER.BASE_LR = 0.001
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64  
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(tags) 

cfg.TEST.EVAL_PERIOD = 500

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()`

**2. making predictions by loading the model and setting a minimum threshold of 85% certainty at which we'll consider the predictions:**
`cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.85
predictor = DefaultPredictor(cfg)`

**3. Let's run the evaluator with the trained model:**
`evaluator = COCOEvaluator("cardriving_val", cfg, False, output_dir=cfg.OUTPUT_DIR)
val_loader = build_detection_test_loader(cfg, "cardriving_val")
inference_on_dataset(trainer.model, val_loader, evaluator)`

Output:
```
[05/04 11:16:49 d2.data.common]: Serializing 32 elements to byte tensors and concatenating them all ...
[05/04 11:16:49 d2.data.common]: Serialized dataset takes 0.02 MiB
[05/04 11:16:49 d2.evaluation.evaluator]: Start inference on 32 images
[05/04 11:16:50 d2.evaluation.evaluator]: Inference done 11/32. 0.0804 s / img. ETA=0:00:01
[05/04 11:16:52 d2.evaluation.evaluator]: Total inference time: 0:00:02.370774 (0.087806 s / img per device, on 1 devices)
[05/04 11:16:52 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:02 (0.079108 s / img per device, on 1 devices)
[05/04 11:16:52 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[05/04 11:16:52 d2.evaluation.coco_evaluation]: Saving results to /content/drive/My Drive/Colab Notebooks/Webcam/coco-drive/Output/coco_instances_results.json
[05/04 11:16:52 d2.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.11s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.794
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.970
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.826
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.745
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.832
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.035
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.322
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.825
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.789
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.856
[05/04 11:16:52 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|   AP   |  AP50   |  AP75  |  APs   |  APm   |  APl   |
|:------:|:-------:|:------:|:------:|:------:|:------:|
| 79.362 | 100.000 | 97.007 | 82.574 | 74.538 | 83.168 |
[05/04 11:16:52 d2.evaluation.coco_evaluation]: Per-category bbox AP: 
| category       | AP     | category   | AP   | category    | AP     |
|:---------------|:-------|:-----------|:-----|:------------|:-------|
| Person         | 83.168 | Hairing    | nan  | Thinking    | nan    |
| Looking Behind | nan    | Drinking   | nan  | Using phone | 75.555 |
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.15s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.774
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.799
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.740
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.803
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.031
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.309
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.805
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.825
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.772
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.828
[05/04 11:16:53 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
|   AP   |  AP50   |  AP75   |  APs   |  APm   |  APl   |
|:------:|:-------:|:-------:|:------:|:------:|:------:|
| 77.389 | 100.000 | 100.000 | 79.876 | 74.006 | 80.297 |
[05/04 11:16:53 d2.evaluation.coco_evaluation]: Per-category segm AP: 
| category       | AP     | category   | AP   | category    | AP     |
|:---------------|:-------|:-----------|:-----|:------------|:-------|
| Person         | 80.297 | Hairing    | nan  | Thinking    | nan    |
| Looking Behind | nan    | Drinking   | nan  | Using phone | 74.482 |
OrderedDict([('bbox',
              {'AP': 79.36161315697471,
               'AP-Drinking': nan,
               'AP-Hairing': nan,
               'AP-Looking Behind': nan,
               'AP-Person': 83.16782675330815,
               'AP-Thinking': nan,
               'AP-Using phone': 75.55539956064126,
               'AP50': 100.0,
               'AP75': 97.00720072007202,
               'APl': 83.16782675330815,
               'APm': 74.53824787864421,
               'APs': 82.57425742574257}),
             ('segm',
              {'AP': 77.3893063752636,
               'AP-Drinking': nan,
               'AP-Hairing': nan,
               'AP-Looking Behind': nan,
               'AP-Person': 80.29671117053869,
               'AP-Thinking': nan,
               'AP-Using phone': 74.4819015799885,
               'AP50': 100.0,
               'AP75': 100.0,
               'APl': 80.29671117053869,
               'APm': 74.00576120329802,
               'APs': 79.87623762376238})])
```

Eveything is going and I am getting expected result till here:
3. Now i want to load trained model and expecting image with predictions, So i wrote a new python file for my testing:

`file_path = "/content/drive/My Drive/Colab Notebooks/Webcam/coco-drive/Test/frame24.jpg"
im = cv2.imread(file_path)

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model

cfg.OUTPUT_DIR = "/content/drive/My Drive/Colab Notebooks/Webcam/coco-drive/Output"
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")

predictor = DefaultPredictor(cfg)

outputs = predictor(im)`

We can use Visualizer to draw the predictions on the image.

`v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(v.get_image()[:, :, ::-1])`

Output: 
![image](https://user-images.githubusercontent.com/19564411/80981070-0ff8b080-8e47-11ea-8f06-23acda2b2b08.png)

`outputs["instances"].pred_classes`
```tensor([], device='cuda:0', dtype=torch.int64)```

`print(cfg.DATASETS.TRAIN)`
```('coco_2017_train',)```

## Expected behavior:
I  should i get image with boxes (as shown below) that should highlight the object in image but i am getting plain image without predictions.

![image](https://user-images.githubusercontent.com/19564411/80983929-ce6a0480-8e4a-11ea-9eb4-1e77f98fa250.png)

I should get 'cardriving_train' dataset name from `cfg.DATASETS.TRAIN` but i am getting ```('coco_2017_train',)```  

I am not sure whether or not my model is loaded and if it's loaded then i should get expected result. I get error if i give wrong model path so It means model is being loaded. 

Please check the code and suggest how can i load my custom model for predictions.

## Environment:

I  should i get image with boxes that should highlight the object in image but i am getting plain image without predictions.

environment information:
```
------------------------  ---------------------------------------------------------
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
numpy                     1.18.3
detectron2                0.1.1 @/usr/local/lib/python3.6/dist-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla P100-PCIE-16GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.0.0
torchvision               0.5.0 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  ---------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

Thanks

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.

**Comment by jerryzhang-ss** [comment]
Hi, I am having exactly the same problem. Have you solved this issue?

**Comment by akhil342** [comment]
add number of classes while predicting the images

**Comment by gburlin** [comment]
> add number of classes while predicting the images

Hi, I have the same issue. Could you please be more explicit on your solution? Thanks.

**Comment by akhilkumar342** [comment]
> explicit

@gburlin can you please post your prediction script here?

**Comment by gburlin** [comment]
> > explicit
> 
> @gburlin can you please post your prediction script here?

Yes of course, here it is : 

cfg = get_cfg() 
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 
cfg.DATASETS.TEST = ('val_dataset',)
predictor = DefaultPredictor(cfg)
    
#list images to predict
dirs = os.listdir(opt.dataset)
dirs.sort()
    
#create output file
output_path = './result_detection/'
os.makedirs(output_path, exist_ok=True)
    
#prediction
for name_im in dirs:
    im = cv2.imread(join(opt.dataset, name_im))
    outputs = predictor(im)
    #enregistrer l'image avec les bounding boxes
    v = Visualizer(im[:, :, ::-1], MetadataCatalog.get('train_dataset'), scale=1.2)
    out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2.imwrite('{}{}'.format(output_path, name_im), out.get_image()[:, :, ::-1])

**Comment by akhilkumar342** [comment]
@gburlin 
add this line to the code and try 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_of_classes

**Comment by gburlin** [comment]
> @gburlin
> add this line to the code and try
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = num_of_classes

Yes it worked, thank you !
