### ISSUE TITLE
Better support for custom components

### ISSUE THREAD

**Issue by PhilipMay** [facebookresearch/detectron2#1356]
## 🚀 Feature
I would like to have better support for custom components. When I write a new backbone I can register it like here: https://detectron2.readthedocs.io/tutorials/write-models.html#write-models

The problem I see is this: When I use `tools/train_net.py` the registration code will not be executed and the model will not be registered / known. IMO the config language should be extended to specify additional packages that need to be imported. 

What do you think or did I miss something?

**Comment by ppwwyyxx** [comment]
It's better to write your own `train_net.py`. See:

https://github.com/facebookresearch/detectron2/blob/60205f80f300a7000373ea2dd6ff73574bf16978/tools/train_net.py#L4-L16
