### ISSUE TITLE
how to work using cpu ?

### ISSUE THREAD

**Issue by Mohammed-elsabri** [facebookresearch/detectron2#1358]
i am using detectron2 when lunch node i get error because i don't have cuda
can i use this node with cpu

**Comment by ppwwyyxx** [comment]
Some parts of detectron2 support CPU. Some parts do not.

I couldn't understand what is "node". Please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md) if you still have questions.
