### ISSUE TITLE
How can I run detecron2_ros on CPU or non NVIDIA devices ??

### ISSUE THREAD

**Issue by Eslamrady42** [facebookresearch/detectron2#1360]
(detectron2_ros) eslam@root:~$ roslaunch detectron2_ros detectron2_ros.launch
... logging to /home/eslam/.ros/log/07e33980-8e54-11ea-9763-64006afb8a06/roslaunch-root-2711.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://root:36767/

SUMMARY
========

PARAMETERS
 * /detectron2_ros/detection_threshold: 0.5
 * /detectron2_ros/input: semantic_mapping/RGB
 * /detectron2_ros/model: /home/eslam/catki...
 * /detectron2_ros/publish_rate: 100
 * /detectron2_ros/visualization: True
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    detectron2_ros (detectron2_ros/detectron2_ros)

auto-starting new master
process[master]: started with pid [2764]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 07e33980-8e54-11ea-9763-64006afb8a06
process[rosout-1]: started with pid [2775]
started core service [/rosout]
process[detectron2_ros-2]: started with pid [2778]
WARNING [05/05 00:11:03 d2.config.compat]: Config '/home/eslam/catkin_ws/src/detectron2_ros/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 150, in <module>
    main(sys.argv)
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 146, in main
    node = Detectron2node()
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 34, in __init__
    self.predictor = DefaultPredictor(self.cfg)
  File "/home/eslam/catkin_ws/detectron2_repo/detectron2/engine/defaults.py", line 184, in __init__
    self.model = build_model(self.cfg)
  File "/home/eslam/catkin_ws/detectron2_repo/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 423, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/cuda/__init__.py", line 101, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
[detectron2_ros-2] process has died [pid 2778, exit code 1, cmd /home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros __name:=detectron2_ros __log:=/home/eslam/.ros/log/07e33980-8e54-11ea-9763-64006afb8a06/detectron2_ros-2.log].
log file: /home/eslam/.ros/log/07e33980-8e54-11ea-9763-64006afb8a06/detectron2_ros-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Mohammed-elsabri** [comment]
i have the same issue

**Comment by ppwwyyxx** [comment]
It appears you need to set `DEVICE` to `cpu`. But this project is detectron2. This is not "detectron2_ros".

**Comment by Eslamrady42** [comment]
Where can I set device to CPU ?

**Comment by ppwwyyxx** [comment]
In detectron2 this is set by `cfg.MODEL.DEVICE='cpu'`. But this is the wrong project to ask the question so the answer may not make any sense.

**Comment by Eslamrady42** [comment]
> In detectron2 this is set by `cfg.MODEL.DEVICE='cpu'`. But this is the wrong project to ask the question so the answer may not make any sense.

Thank you for your replay and I’ll find out on the correct project if could the owner answered

**Comment by DavidFernandezChaves** [comment]
The right project is: https://github.com/DavidFernandezChaves/Detectron2_ros

I'm not sure what the problem is, but at first glance, it looks like driver compatibility.
I don't think the problem is the wrapping so to debug I advise you to run Detectron2 without the ROS implementation and check if it works on CPU or GPU. 
If the installation of Detectron2 and the drivers is well done, it uses the GPU by default without changing parameters (in my case).

Probably this will also run on CPU and you can give details on this project.

**Comment by Eslamrady42** [comment]
> The right project is: https://github.com/DavidFernandezChaves/Detectron2_ros
> 
> 
> 
> I'm not sure what the problem is, but at first glance, it looks like driver compatibility.
> 
> I don't think the problem is the wrapping so to debug I advise you to run Detectron2 without the ROS implementation and check if it works on CPU or GPU. 
> 
> If the installation of Detectron2 and the drivers is well done, it uses the GPU by default without changing parameters (in my case).
> 
> 
> 
> Probably this will also run on CPU and you can give details on this project.
> 
> 

The problem is I don’t have a Nvidia device already but I see this error, I don’t know why ??
My project is self driving car based on Odroid N2 board and D435 ,T265 Cameras so I want work on the cpu not gpu

**Comment by DavidFernandezChaves** [comment]
Oh! I see!

The project I uploaded uses the precompiled version of Detectorn 2 for GPU, if you want to use it in CPU you should change the precompiled version.


In https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md

>  Install Pre-Built Detectron2
> # for CUDA 10.1:
> python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
> You can replace cu101 with "cu{100,92}" or "cpu".

Do a clean installation of the project and in step 3, change the line:
pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/index.html
for:
pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html

**Comment by Eslamrady42** [comment]
> Oh! I see!
> 
> The project I uploaded uses the precompiled version of Detectorn 2 for GPU, if you want to use it in CPU you should change the precompiled version.
> 
> In https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md
> 
> > Install Pre-Built Detectron2
> > # for CUDA 10.1:
> > python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
> > You can replace cu101 with "cu{100,92}" or "cpu".
> 
> Do a clean installation of the project and in step 3, change the line:
> pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/index.html
> for:
> pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html

I did it but I found another error ;

(detectron2_ros) eslam@root:~/catkin_ws$ roslaunch detectron2_ros detectron2_ros.launch
... logging to /home/eslam/.ros/log/1d0ede0e-8e9f-11ea-9763-64006afb8a06/roslaunch-root-14568.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://root:34277/

SUMMARY
========

PARAMETERS
 * /detectron2_ros/detection_threshold: 0.5
 * /detectron2_ros/input: semantic_mapping/RGB
 * /detectron2_ros/model: /home/eslam/catki...
 * /detectron2_ros/publish_rate: 100
 * /detectron2_ros/visualization: True
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    detectron2_ros (detectron2_ros/detectron2_ros)

ROS_MASTER_URI=http://localhost:11311

process[detectron2_ros-1]: started with pid [14586]
Traceback (most recent call last):
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 9, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
[detectron2_ros-1] process has died [pid 14586, exit code 1, cmd /home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros __name:=detectron2_ros __log:=/home/eslam/.ros/log/1d0ede0e-8e9f-11ea-9763-64006afb8a06/detectron2_ros-1.log].
log file: /home/eslam/.ros/log/1d0ede0e-8e9f-11ea-9763-64006afb8a06/detectron2_ros-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
(detectron2_ros) eslam@root:~/catkin_ws$

**Comment by DavidFernandezChaves** [comment]
Did you take into account the installation notes?

from: https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md
> Note that:

Such installation has to be used with certain version of official PyTorch release. See releases for requirements. It will not work with your custom build of PyTorch.

**Comment by Eslamrady42** [comment]
> Did you take into account the installation notes?
> 
> from: https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md
> 
> > Note that:
> > Such installation has to be used with certain version of official PyTorch release. See releases for requirements. It will not work with your custom build of PyTorch.

I did all of this then I found another error ;

(detectron2_ros) eslam@root:~$ roslaunch detectron2_ros detectron2_ros.launch
... logging to /home/eslam/.ros/log/0e8c6864-8ec3-11ea-9763-64006afb8a06/roslaunch-root-17245.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://root:46579/

SUMMARY
========

PARAMETERS
 * /detectron2_ros/detection_threshold: 0.5
 * /detectron2_ros/input: semantic_mapping/RGB
 * /detectron2_ros/model: /home/eslam/catki...
 * /detectron2_ros/publish_rate: 100
 * /detectron2_ros/visualization: True
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    detectron2_ros (detectron2_ros/detectron2_ros)

auto-starting new master
process[master]: started with pid [17256]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0e8c6864-8ec3-11ea-9763-64006afb8a06
process[rosout-1]: started with pid [17267]
started core service [/rosout]
process[detectron2_ros-2]: started with pid [17274]
WARNING [05/05 13:25:11 d2.config.compat]: Config '/home/eslam/catkin_ws/src/detectron2_ros/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 150, in <module>
    main(sys.argv)
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 146, in main
    node = Detectron2node()
  File "/home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros", line 34, in __init__
    self.predictor = DefaultPredictor(self.cfg)
  File "/home/eslam/catkin_ws/detectron2/detectron2/engine/defaults.py", line 184, in __init__
    self.model = build_model(self.cfg)
  File "/home/eslam/catkin_ws/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/nn/modules/module.py", line 423, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/home/eslam/.environments/detectron2_ros/lib/python3.6/site-packages/torch/cuda/__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
[detectron2_ros-2] process has died [pid 17274, exit code 1, cmd /home/eslam/catkin_ws/src/detectron2_ros/src/detectron2_ros __name:=detectron2_ros __log:=/home/eslam/.ros/log/0e8c6864-8ec3-11ea-9763-64006afb8a06/detectron2_ros-2.log].
log file: /home/eslam/.ros/log/0e8c6864-8ec3-11ea-9763-64006afb8a06/detectron2_ros-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
(detectron2_ros) eslam@root:~$

**Comment by DavidFernandezChaves** [comment]
This looks like you have a compatibility error between the CUDA and Torch versions you have installed. I'm not an expert on that and I can't help you with that, sorry.

The version of CUDA you have installed may expect NVIDIA graphics. I'm sure other people have had that mistake, try googling it. In any case it is problems of installation requirements.

Good luck!

**Comment by Eslamrady42** [comment]
> This looks like you have a compatibility error between the CUDA and Torch versions you have installed. I'm not an expert on that and I can't help you with that, sorry.
> 
> The version of CUDA you have installed may expect NVIDIA graphics. I'm sure other people have had that mistake, try googling it. In any case it is problems of installation requirements.
> 
> Good luck!

Thank you ..
