### ISSUE TITLE
ResNet stages

### ISSUE THREAD

**Issue by Ilbotre** [facebookresearch/detectron2#1361]
## ❓ There exist any references in order to understand the 5 stages of ResNet that you speak about in the _C.MODEL.BACKBONE section?

note: you wrote this "# Freeze the first several stages so they are not trained.
# There are 5 stages in ResNet. The first is a convolution, and the following
# stages are each group of residual blocks"

**Comment by ppwwyyxx** [comment]
https://arxiv.org/abs/1512.03385
