### ISSUE TITLE
How do I display certain classes when multiple thing_classes exist?

### ISSUE THREAD

**Issue by Vulkanos** [facebookresearch/detectron2#1363]
I have loaded a dataset with music notation and got several thing_classes. 

> classes=['systemSeparator', 'staffGrouping', 'measureSeparator', 'staffLine', 'staffSpace', 'staff']

The tutorial code:

```
from detectron2.data import DatasetCatalog, MetadataCatalog
data_name = "muscimaV2_all_staff_data"
d = "data"
classes=['systemSeparator', 'staffGrouping', 'measureSeparator', 'staffLine', 'staffSpace', 'staff']
DatasetCatalog.register(data_name, lambda d=d: data) # data is the data dict
MetadataCatalog.get(data_name).set(thing_classes=classes)

muscima_metadata = MetadataCatalog.get(data_name)

for d in random.sample(data, 3):
    print(d["file_name"])
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=muscima_metadata, scale=1)
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```

Allows to display all thing_classes which is really cluttered and hard to differentiate all the different bounding boxes. How can I only display certain thing_classes? For example, I would like to only look at the "staff" thing_class, how can I achieve this?

**Comment by ppwwyyxx** [comment]
You can remove other annotations from the data to draw.
