### ISSUE TITLE
Can't Install on MacOS

### ISSUE THREAD

**Issue by marcoistasy** [facebookresearch/detectron2#1367]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote

```
none
```

2. what exact command you run:
```
pip install detectron2==0.1.2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html
```

3. what you observed (including __full logs__):
```
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
```

## Environment:

Provide your environment information using the following command:
```
Traceback (most recent call last):
  File "collect_env.py", line 12, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

I tried installing Detectron2 following this notebook (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=b-i4hmGYk1dL) and this documentation (https://detectron2.readthedocs.io/tutorials/install.html) to no avail. Please advise.

**Comment by ppwwyyxx** [comment]
We do not provide pre-built packages for macOS.
You need to install from source.

**Comment by Alejom334** [comment]
@marcoistasy Were you able to solve this issue?
