### ISSUE TITLE
How to reduce the model size to accelerate the prediction?

### ISSUE THREAD

**Issue by Huarong** [facebookresearch/detectron2#1369]
I train a new model with some newly notated images based on the pre-trained model.
I trained the model on GPUs, but need to do the prediction on CPUs.  And the prediction is of course very slow.

How can I reduce the size of the model to accelerate the prediction even though with a little decline of precision.

**Comment by ppwwyyxx** [comment]
You can train smaller models. We currently don't have them released in detectron2.
