### ISSUE TITLE
Can resNest be used as the backbone in detectron2

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1371]
## 🚀 Feature

Hello, how many backbone networks are available in detectron2, except R-50, R-101, X-101-32x8d, X-152-32x8d-IN5k, R-50-GN, R-101-GN.
**Recently, resNest has proved to work well as a backbone network in object detection tasks? Can resNest be used as the backbone network in detectron2?**

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers --
we only consider papers that have enough significance and prevalance in the object detection field.

We do not take requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory
contains many of such examples.

**Comment by ppwwyyxx** [comment]
It can. And people have done that. https://github.com/zhanghang1989/detectron2-ResNeSt
