### ISSUE TITLE
R_101_FPN  useing different depth predict 

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1372]
i use pretrain model (mask_rcnn_R_101_FPN_3x)  to transfer learning.
when i predict , mask_rcnn_R_101_FPN_3x (without change anything) is great. mask_rcnn_R_101_FPN_3x (depth change to 50 ) also can output, but i got incomplete mask in image.

1. why using 101 depth model can predict at 50 depth model, it  is makes sense?
2. why predict at 50 depth model  will have incomplete mask in image?

thank you

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
