### ISSUE TITLE
What is the Detectron2 Keypoint format and how to save it in COCO format?

### ISSUE THREAD

**Issue by hosnasattar** [facebookresearch/detectron2#1373]
The detectron2 outputs 18 keypoints! I was wondering what are the output format and how I could save it to COCO format. 
I had a look into https://github.com/facebookresearch/detectron2/pull/175 
and I see that the key point output of detectron2 has 0.5 shift?  Could you please clarify on this?
thanks

**Comment by ppwwyyxx** [comment]
The output format is in the documentation: https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

The outputs do not have 0.5 shift. It is the COCO format that presumably has a shift.

**Comment by hosnasattar** [comment]
I can not find the ids for the keypoint! should I assume that the ids are as COCO?
            "name": "person",  # (specific category)
            "supercategory": "person",  #  
            "id": 1, # class id
            "keypoints": [
                "nose",
                "left_eye",
                "right_eye",
                "left_ear",
                "right_ear",
                "left_shoulder",
                "right_shoulder",
                "left_elbow",
                "right_elbow",
                "left_wrist",
                "right_wrist",
                "left_hip",
                "right_hip",
                "left_knee",
                "right_knee",
                "left_ankle",
                "right_ankle"
            ]
        }

**Comment by ppwwyyxx** [comment]
If you use coco dataset, then the ids have the meaning defined by the coco dataset.

**Comment by hosnasattar** [comment]
I am not using COCO data set! but the dependency I am working with need as input coco format keypoints id! I am using detectron2 to get the keypoints but I was wondering if the ordering og the keypoints are the same!
for example as you can see here 
![image](https://user-images.githubusercontent.com/4334952/81226659-7a4a5600-8feb-11ea-9136-87139098f686.png)

**Comment by ppwwyyxx** [comment]
If you use a model trained on coco dataset, then the ids also have the meaning defined by the coco dataset.

**Comment by hosnasattar** [comment]
Thanks for the support and great API :-)

**Comment by smj007** [comment]
> The detectron2 outputs 18 keypoints! I was wondering what are the output format and how I could save it to COCO format.
> I had a look into #175
> and I see that the key point output of detectron2 has 0.5 shift? Could you please clarify on this?
> thanks

Just a small modification, it outputs 17 keypoints per detection, as you have correctly listed them after that!
