### ISSUE TITLE
ResNet-D

### ISSUE THREAD

**Issue by xkszltl** [facebookresearch/detectron2#1374]
## 🚀 Feature

Is there any "official" way to enable ResNet-D from the bag-of-tricks paper (https://arxiv.org/pdf/1812.01187.pdf)?
Basically it added a avg pooling in the shortcut if stride > 1.

If not I can sent out a PR to do it.

## Motivation & Examples

TorchVision model is already ResNet-B.
Based on the paper ResNet-D can provide further improvement.

These are screenshot from the paper:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/5203025/81221113-fa38e600-9014-11ea-9579-cf146ad99e38.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/5203025/81221153-06bd3e80-9015-11ea-94c4-75ab8288fe46.png">

**Comment by ppwwyyxx** [comment]
There isn't. It can be implemented by registering a new backbone.
This method is not popular in the object detection community as far as I know so we'll not consider adding it at this time.

**Comment by xkszltl** [comment]
@ppwwyyxx Registering a new backbone causes too much code duplication.
What we did currently is to overwrite BasicBlock with a class derived from it, before constructing the network.
However, it would be nice if detectron2 can allow configurable resnet blocks, instead of hard-coding it here: https://github.com/facebookresearch/detectron2/blob/1b09e42cc87d47a6e0a3892cd86e780d86a9b122/detectron2/modeling/backbone/resnet.py#L574

**Comment by ppwwyyxx** [comment]
You can do
```
@BACKBONE_REGISTRY.register()
def mybackbone():
    return ResNet(BasicStem(),
       [make_stage(MyBasicBlock, n, s, in_channels=i, out_channels=o)
        for (n, s, i, o) in [...]],
       out_features=["..."])
```
