### ISSUE TITLE
The model can not suport GPU deployment in torchscript

### ISSUE THREAD

**Issue by lyc6749** [facebookresearch/detectron2#1375]
## ❓ How to do something using detectron2

General questions in learning detectron2, like:

I used C++ to load the model ，but it seems can only use cpu for inference. Will this support GPU inference?

**Comment by lyc6749** [comment]
![image](https://user-images.githubusercontent.com/33708958/81249682-cfb94e00-9051-11ea-8ffb-4d6f29364353.png)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
