### ISSUE TITLE
in function draw_sem_seg，the labels output by my dataset trained model is not integers?

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/detectron2#1377]
i used pointrend semantic R101 to train my dataset.
in function draw_sem_seg，the labels output by my dataset trained model is not integers?
print(labels)
[-5.0863366 -2.6080706 -4.277624  ... -1.8117143 -1.811715  20.078917 ]

Traceback (most recent call last):
  File "visualize.py", line 87, in <module>
    point_rend_seg_result = v.draw_sem_seg(pointrend_seg_outputs["sem_seg"].to("cpu")).get_image()
  File "/home/qianjinhao/.local/lib/python3.7/site-packages/detectron2/utils/visualizer.py", line 405, in draw_sem_seg
    text = self.metadata.stuff_classes[label]
TypeError: list indices must be integers or slices, not numpy.float32

i think there is something wrong wtih the following codeline:
labels, areas = np.unique(sem_seg, return_counts=True)

**Comment by ppwwyyxx** [comment]
Each element in `draw_sem_seg` is expected to the label of the pixel. 
So it has to be integers.

**Comment by zhangliyun9120** [comment]
@ppwwyyxx 
I met the same problem, do you know how to fix that?
thank you

**Comment by KuntaiDu** [comment]
@zhangliyun9120 I got a solution here:
```
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), instance_mode=ColorMode.SEGMENTATION)
x = outputs["sem_seg"].argmax(dim=0)
out = v.draw_sem_seg(x.to("cpu"))
```

**Comment by ZhaomengWang** [comment]
@KuntaiDu I have met the same problem and I have successfully fix it by following your solution! Thank you so much！
