### ISSUE TITLE
How to Implement Early Stopping and Save on better model only

### ISSUE THREAD

**Issue by sandeepsign** [facebookresearch/detectron2#1379]
How to Implement Early Stopping and Save on better model only? 
I see that we have MAX iterations in cfg defined, But if my model stops getting better for say 50 consecutive iteration, Can I stop the training automatically? 

Also, I assume checkpoints are created and model's .pth is saved at each latest checkpoint, is there a way to save the model only if it got better score on validation set than previous iterations?

**Comment by ppwwyyxx** [comment]
duplicate of #671 #509
