### ISSUE TITLE
Testing retinanet_R_50_FPN_1x on Custom Dataset

### ISSUE THREAD

**Issue by pervaizniazi** [facebookresearch/detectron2#138]
Hi,

I trained my custom dataset which is in a Pascal VOC format for retinanet_R_50_FPN_1x ( using "register_pascal_voc" from "pascal_voc" module). However, I am not able to test it on test the test set. In fact, I need to extract predicted classes and their bounded boxes. Any help will be much appreciated.

Thanks.

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
