### ISSUE TITLE
test error 

### ISSUE THREAD

**Issue by zhepherd** [facebookresearch/detectron2#1380]
![image](https://user-images.githubusercontent.com/3793108/81276588-ccd85080-9085-11ea-8bdd-929b3c5e6a15.png)

my cuda version is CUDA Version 10.0.130
CUDA Patch Version 10.0.130.1

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
