### ISSUE TITLE
Order of loaded images during training

### ISSUE THREAD

**Issue by philthestone** [facebookresearch/detectron2#1382]
In what order are the images loaded during training?

When preparing my data, I initially used only the originial data. Later I added augmented data. The "first half" of my Coco-style file that I registered containts now the the information for the original images, the "second half" contains the information of the augmented images.

Now i am wondering if Detectron2 loads the images in the same order as in the passed Coco-style file, or if it picks a random (set of) image(s) during training. 

As an example: For the **first** 20 iterations, does it use the **first** 20 images of the Coco-style file, or are these 20 images randomly chosen?

**Comment by ppwwyyxx** [comment]
The order is random in the default data loader.
