### ISSUE TITLE
Training Detectron2 compatible GroupNorm models

### ISSUE THREAD

**Issue by lengstrom** [facebookresearch/detectron2#1384]
## How can I train a Detectron2 compatible Resnet50 GroupNorm model?

Hi! 

I need to train Resnet50 GN models compatible with Detectron2 in regimes not captured by any of the currently offered checkpoints. What is the best way to do this? I saw that the original R50 GN models are ported over from caffe (https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/47261647/R-50-GN.pkl) --- is there an easy way of training compatible models in pytorch?

I found this repository: https://github.com/ppwwyyxx/GroupNorm-reproduce but wasn't sure if it was easy to port the weights over to a Detectron2 compatible format.

Thank you for all the work you do here @ppwwyyxx, your code has been really useful throughout the last 2-3 years of my research :)

**Comment by ppwwyyxx** [comment]
There are a few groupnorm models in our model zoo with training configs and models to use: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#other-settings

**Comment by lengstrom** [comment]
Oh I'm sorry I think I misspecified my question! I'm trying to train R50-GN ImageNet models that are compatible with Detectron2; I know that it is easy once I have them in Detectron2's format to train downstream models.

**Comment by ppwwyyxx** [comment]
I see! We don't have a public imagenet training code that produces this pre-trained model. But https://github.com/ppwwyyxx/GroupNorm-reproduce/tree/master/ImageNet-ResNet-PyTorch together with https://github.com/facebookresearch/detectron2/blob/master/tools/convert-torchvision-to-d2.py should get you pretty close to that.

**Comment by lengstrom** [comment]
Great thank you!
