### ISSUE TITLE
 How many features can be detected per image

### ISSUE THREAD

**Issue by 20160688** [facebookresearch/detectron2#1387]
Currently, I am trying to detect buildings using aerial images by detectron2. In aerial photography, the smallest building is approximately 20 by 20 pixel in size, and there are approximately 300 to 700 buildings in the 800 by 800 image. However, no matter how much training is performed and variable is changed, even the labeled training data image does not exceed 350 features. (for example, input image: about 500 features, output with same image: only around 250 features)

How can I extract many features in a image? Or is there a limit to the number of images that can be recognized and detected by detectron2?

Currently, cfg.test.detections_per_image is set to 1024.

Below is the variable setting used for the current train.
![image](https://user-images.githubusercontent.com/48044309/81380858-8d256d80-9146-11ea-921b-d710523cac13.png)

Thank you in advance.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
