### ISSUE TITLE
AttributeError: Cannot find field 'pred_masks' in the given Instances

### ISSUE THREAD

**Issue by SriRamGovardhanam** [facebookresearch/detectron2#1388]
Hello 
i was trying to get individual mask of all segmented parts using Densepose
for that someone suggested to use `outputs['instances'].pred_masks` but is shows the following error

code:

```
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
cfg = get_cfg()
add_densepose_config(cfg)

# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file("/content/detectron2/projects/DensePose/configs/densepose_rcnn_R_101_FPN_s1x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x/165712084/model_final_c6ab63.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
outputs['instances'].pred_masks
```

it gives me the following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-73-a49b1f86d4a4> in <module>()
     12 predictor = DefaultPredictor(cfg)
     13 outputs = predictor(im)
---> 14 outputs['instances'].pred_masks
     15  

/content/detectron2/detectron2/structures/instances.py in __getattr__(self, name)
     58     def __getattr__(self, name: str) -> Any:
     59         if name == "_fields" or name not in self._fields:
---> 60             raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
     61         return self._fields[name]
     62 

AttributeError: Cannot find field 'pred_masks' in the given Instances!
```
some one please look into this! @ppwwyyxx  @vkhalidov

**Comment by ppwwyyxx** [comment]
By default a densepose model does not predict `pred_masks`. It does have `pred_densepose` from which masks can be extracted.

**Comment by ousim97** [comment]
Hello, 
This is the code I use to visualize the result of prediction but I got the same error:
`from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2 import model_zoo
import os
from detectron2.utils.visualizer import ColorMode
import cv2
from detectron2.engine import DefaultPredictor
from detectron2.utils.visualizer import Visualizer
from detectron2.data import DatasetCatalog, MetadataCatalog


cfg = get_cfg()

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "C:/Users/simsi/Downloads/model_final.pth")  # path to the model we just trained
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set a custom testing threshold
predictor = DefaultPredictor(cfg)

im = cv2.imread("C:/Users/simsi/Downloads/CrackTree260/images/test/6233.jpg")
outputs = predictor(im)  # format is documented at https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
#print(outputs['instances'])
v = Visualizer(im[:, :, ::-1],
                metadata=MetadataCatalog.get("C:/Users/simsi/Downloads/CrackTree260/images/"), 
                scale=0.5, 
                instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels. This option is only available for segmentation models
)
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imshow(out.get_image()[:, :, ::-1])`

Can anyone help me solve it please?

**Comment by vkhalidov** [comment]
@ousim97 you need to use [DensePose-specific visualizers](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/densepose/vis/densepose.py)

**Comment by ousim97** [comment]
> @ousim97 you need to use [DensePose-specific visualizers](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/densepose/vis/densepose.py)

First, thanks for your quick reply. 
I'm not familiar with classes in python so I don't know how to use this code to display the masks results. So how could this be done? and where do I have to load my trained model in the code?
Thanks in advance.

**Comment by vkhalidov** [comment]
@ousim97 I'm a bit confused. DensePose produces `pred_densepose` field. `pred_masks` contains the result of instance segmentation. Which model are you using? What are you trying to visualize?
Please check the [DensePose visualization tool](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/TOOL_APPLY_NET.md) as well.
