### ISSUE TITLE
how detectron2 deal with large amounts of data?

### ISSUE THREAD

**Issue by liulai** [facebookresearch/detectron2#1389]
I have a questions, how detectron2 deal with large amounts of data?

computer configuration:
RAM: 13GB
GPU: 16GB

training data: 20G

**Comment by ppwwyyxx** [comment]
I'm not sure what the issue is asking about. 
Could you clarify what you are asking?

**Comment by liulai** [comment]
> I'm not sure what the issue is asking about.
> Could you clarify what you are asking?

Thanks, I am a newfish, I know what my problem is
