### ISSUE TITLE
Semantic Segmentation - detectron 2

### ISSUE THREAD

**Issue by ashwinpn** [facebookresearch/detectron2#1390]
How to implement Semantic Segmentation with detectron2?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend/#semantic-segmentation has some semantic segmentation models released recently.

**Comment by ashwinpn** [comment]
Okay, Thanks! I just went through the issue list to see if anyone else has mentioned this before - You should probably have a look at #245 and #1055 too.
