### ISSUE TITLE
encounter a problem when running demo.py

### ISSUE THREAD

**Issue by CastleWhite** [facebookresearch/detectron2#1392]
the error message is
RuntimeError: Not compiled with GPU support (ROIAlign_forward 

this kind of error never happened before
is it CUDA problem or what?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
