### ISSUE TITLE
TensorMask annotation problem

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#1393]
Hi,

for a university lab, I have to detect insects (butterflys) with TensorMask. the objects to detect have a a big area of intersection caused by their wings. The specific problem is, that there are objects, which are cutted into two sepearte pieces by another objects element (wing). 
Since you don't answer questions how to train own models, I am curios, if the authors of the TensorMask paper ( https://arxiv.org/pdf/1903.12174.pdf ) faced a same situation and how they solved it. How do I have to annotate in such a situation?
I had a look at the COCO train and val set, which are mentioned in the TensorMask paper for training and validation. To me the annotations appear very imprecise and inconsistent accoring to the problem of annotating objects, which have a big area of intersection, which leads to seperated elements of one object. Sometimes the annotations are interpolated in the unvisible area and sometimes they just stop and leave out the seperated part of the object.
I added a screenshot of the butterflys to make the problem clearer and one picture of the TensorMask paper where the same situation appers (marked by me with red ellipse).
Thank you very much !

<img width="1132" alt="TensorMaskPaper" src="https://user-images.githubusercontent.com/63237627/81494710-3dac8200-92ab-11ea-9830-c73090ae2b5e.PNG">
<img width="606" alt="butterflys_screenshot" src="https://user-images.githubusercontent.com/63237627/81495026-70577a00-92ad-11ea-92f5-c0e314595340.PNG">

**Comment by ppwwyyxx** [comment]
A mask can have multiple parts. If an object has multiple parts, you can annotate them all.
