### ISSUE TITLE
How to use exported Mask-RCNN in Caffe2 Python

### ISSUE THREAD

**Issue by xavierdcruz** [facebookresearch/detectron2#1397]
I want to get the Mask-RCNN model outputs for a single inference image, using Caffe2 Python (without dependencies on detectron2). 

My eventual goal is to export a Mask-RCNN that I fine-tuned on my own dataset for deployment, but to start with I'm just trying to export a standard pre-trained COCO Mask-RCNN, as is shown in the example.

First I followed the instructions here https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/deployment.md#usage

and the script executed successfully, ran inference through several test images, and created a directory `caffe2_model`, containing several files: `coco_instances_results.json 
 instances_predictions.pth  model_init.pb  model.pb  model.pbtxt`

I wrote the following python script to try to make use of the above exported model files:

`run_model.py:`

```
from caffe2.python workspace
import numpy as np
import cv2
print('Imported stuff')


IMAGE_PATH = '1acb46f2-b23f-4696-8049-180ce25e0b51.18aecbee-2d62-4e4d-a527-8e99cc9d74e8.jpg'

with open("model_init.pb", "rb") as f:
    init_net = f.read()
with open("model.pb", "rb") as f:
    predict_net = f.read()
print('Loaded model files')

p = workspace.Predictor(init_net, predict_net)
print('Created a predictor')

SIZE = 224
img = cv2.imread(IMAGE_PATH)
img = cv2.resize(img, (SIZE, SIZE), cv2.INTER_CUBIC)
img = np.reshape(img, (3, SIZE, SIZE))
img = np.float32(np.expand_dims(img, axis=0))
print('Loaded & preprocessed the test image')
print('INput shape: ', img.shape)

print('Forward passing the net...')
results = p.run({'data': img})
print('Forward passed the net')
print(results)
```

I get this shape mismatch error:

```
/home/sal9000/virtualenvs/detectron_env_2/bin/python /home/sal9000/Sources/detectron2/tools/deploy/caffe2_model/run_model.py
Imported stuff
Loaded model files
Created a predictor
Loaded & preprocessed the test image
INput shape:  (1, 3, 224, 224)
Forward passing the net...
Traceback (most recent call last):
  File "/home/sal9000/Sources/detectron2/tools/deploy/caffe2_model/run_model.py", line 34, in <module>
    results = p.run({'data': img})
RuntimeError: [enforce fail at generate_proposals_op.cc:289] im_info_tensor.sizes() == (vector<int64_t>{num_images, 3}). [0] vs 1 3
Error from operator: 
input: "511" input: "512" input: "im_info" input: "_wrapped_model.proposal_generator.anchor_generator.cell_anchors.0" output: "529" output: "530" name: "" type: "GenerateProposals" arg { name: "spatial_scale" f: 0.25 } arg { name: "pre_nms_topN" i: 1000 } arg { name: "post_nms_topN" i: 1000 } arg { name: "nms_thresh" f: 0.7 } arg { name: "min_size" f: 0 } arg { name: "angle_bound_on" i: 1 } arg { name: "angle_bound_lo" i: -180 } arg { name: "angle_bound_hi" i: 180 } arg { name: "clip_angle_thresh" f: 1 } arg { name: "legacy_plus_one" i: 0 } device_option { device_type: 0 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f3d102b34f7 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x23d8030 (0x7f3d4ef6f030 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x1fbb57d (0x7f3d4eb5257d in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #3: caffe2::SimpleNet::Run() + 0x1a9 (0x7f3d4e90d169 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #4: caffe2::Workspace::RunNet(std::string const&) + 0x802 (0x7f3d4e955242 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #5: caffe2::Predictor::run_map_workspace(std::unordered_map<std::string, caffe2::Tensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, caffe2::Tensor> > > const&) + 0x761 (0x7f3d4ebd0a21 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #6: caffe2::Predictor::operator()(std::unordered_map<std::string, caffe2::Tensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, caffe2::Tensor> > > const&, std::vector<caffe2::Tensor, std::allocator<caffe2::Tensor> >*) + 0x19 (0x7f3d4ebd19b9 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x530a2 (0x7f3d5bb9a0a2 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x91e17 (0x7f3d5bbd8e17 in /home/sal9000/virtualenvs/detectron_env_2/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #9: _PyCFunction_FastCallDict + 0x35c (0x5669ac in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #10: /home/sal9000/virtualenvs/detectron_env_2/bin/python() [0x50a5c3]
frame #11: _PyEval_EvalFrameDefault + 0x444 (0x50bfb4 in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #12: /home/sal9000/virtualenvs/detectron_env_2/bin/python() [0x507d64]
frame #13: PyEval_EvalCode + 0x23 (0x50ae13 in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #14: /home/sal9000/virtualenvs/detectron_env_2/bin/python() [0x634c82]
frame #15: PyRun_FileExFlags + 0x97 (0x634d37 in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #16: PyRun_SimpleFileExFlags + 0x17f (0x6384ef in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #17: Py_Main + 0x591 (0x639091 in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #18: main + 0xe0 (0x4b0d00 in /home/sal9000/virtualenvs/detectron_env_2/bin/python)
frame #19: __libc_start_main + 0xe7 (0x7f3d75d20b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #20: _start + 0x2a (0x5b250a in /home/sal9000/virtualenvs/detectron_env_2/bin/python)


Process finished with exit code 1
```

Furthermore, will I have to manually implement the preprocessing steps utilized by the pretrained network? Where can I find exactly what these were?

* Operating system: Ubuntu 18.04
* Compiler version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* CUDA version: N/A
* cuDNN version: N/A
* NVIDIA driver version: N/A
* `PYTHONPATH` environment variable: `:/home/sal9000/Sources/tensorflow/models/research/:/home/sal9000/Sources/tensorflow/models/research/slim`
* `python --version` output: Python 3.6.9
* Anything else that seems relevant: Dell XPS13 9370

**Comment by ppwwyyxx** [comment]
As the [documentation](https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python) says:

> All converted models (the .pb files) take two input tensors

but you only provided one.

You can translate the C++ example https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_mask_rcnn.cpp to python line by line if that's easier.

**Comment by xavierdcruz** [comment]
Thanks for your assistance. By adding that second tensor I was able to forward pass the network successfully for some dummy data (as long as the input image is above a certain size and multiple of 32, I guess because of the downsampling operations in the net).

What about preprocessing steps? The net I'm using here is a standard pretrained MaskRCNN. Where can I find precisely what the preprocessing steps used at training time are (how it handles images of varying size/aspect ratio, mean subtraction etc.), so I can replicate them? 

Furthermore the for the net I fine-tuned myself, I used a high-level abstraction `DefaultTrainer` to handle the training loop, so I'm unaware of what preprocessing steps were applied to my data. Presumably the same as for the original COCO dataset, but the demo training script seemed to handle these details without my intervention.

**Comment by ppwwyyxx** [comment]
Usually we do resize while keeping the aspect ratio unchanged (and pad 0s if not multiple of 32). But that's up to you to decide.

**Comment by xavierdcruz** [comment]
I'm now trying to export my own fine-tuned Mask RCNN, which only has a single category (guitars) instead of COCO's 80 categories.

Presumably this means I need to change this line https://github.com/facebookresearch/detectron2/blob/1b09e42cc87d47a6e0a3892cd86e780d86a9b122/tools/deploy/caffe2_converter.py#L61 

```
    # get a sample data
    data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
    first_batch = next(iter(data_loader))
```

to summon a batch of my own data instead of COCO.

At training time I wrote a method `get_dataset_dicts(img_dir)` where `img_dir` contained my training images and target masks, and I computed bounding boxes for them, finally returning dictionaries that I had to "register" as follows:

```
print('Registering datasets...')
for d in ["train", "val"]:
    DatasetCatalog.register("guitar_" + d, lambda d=d: get_dataset_dicts("data/" + d))
    MetadataCatalog.get("guitar_" + d).set(thing_classes=["guitar"])
guitar_metadata = MetadataCatalog.get("guitar_train")
print('Finished registering datasets.')
```

How should I go about supplying this data to the caffe conversion script? Do I still need to register the datasets in this way? Or do I need to write a new `Dataset` class https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#dataset-class to construct a Guitar `torch.utils.data.DataLoader`? and just call `next` on that?

I already tried exporting my model without any changes and the script executed fully, but the caffe model it outputted still had 80 target classes (I assume it assigned random weights to that final classification layer since mine wouldn't fit or something).

**Comment by xavierdcruz** [comment]
So I managed to get my fine-tuned model (with the single category instead of COCO's 80) with this workaround:

Modify the line:

https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L243

I had initially wanted to modify the conversion script:

```
    cfg = setup_cfg(args)
    cfg.NUM_CLASSES = 1
```

But I got an error saying that cfg object was immutable.

This could be simpler!

**Comment by ppwwyyxx** [comment]
You can use `--opts NUM_CLASSES 1` of `caffe2_converter.py`.
Or modify the `setup_cfg` function.

**Comment by jake221** [comment]
@xavierdcruz have you solved your problem?

I also try the code wrote by you and add im_info data. But I encounter the following problem. Do you know where is the bug?

RuntimeError: [enforce fail at elementwise_ops_utils.cc:56] A_dim == B_dim || A_dim == 1 || B_dim == 1. 

`import os

import torch
from caffe2.python import workspace
import numpy as np
import cv2

print('Imported stuff')

root_dir = '/wjk/d2learn/detectron2_notebook/detectron2/tools/deploy/'

IMAGE_PATH = root_dir + 'task-photo-1582200775851.jpg'

with open(os.path.join(root_dir, 'caffe2_model', 'model_init.pb'), "rb") as f:
    init_net = f.read()
with open(os.path.join(root_dir, 'caffe2_model', "model.pb"), "rb") as f:
    predict_net = f.read()
print('Loaded model files')

p = workspace.Predictor(init_net, predict_net)
print('Created a predictor')

SIZE = 800
img = cv2.imread(IMAGE_PATH)
orig_height, orig_width = img.shape[0:2]

img = cv2.resize(img, (800, int(orig_height * 800 / orig_width)), cv2.INTER_CUBIC)
height, width = img.shape[0:2]
print(height, width)

data = np.reshape(img, (3, height, width))
data = np.float32(np.expand_dims(data, axis=0))
print(data.shape)

im_info = np.float32((height, width, 1))
im_info = np.reshape(im_info, (1, -1))
print(im_info, im_info.shape)
print('Loaded & preprocessed the test image')

print('Forward passing the net...')
results = p.run({'data': data, 'im_info': im_info})
print('Forward passed the net')
print(results)`

**Comment by jake221** [comment]
import os

import torch
from caffe2.python import workspace
import numpy as np
import cv2

print('Imported stuff')

root_dir = '/wjk/d2learn/detectron2_notebook/detectron2/tools/deploy/'

IMAGE_PATH = root_dir + 'task-photo-1582200775851.jpg'

with open(os.path.join(root_dir, 'caffe2_model', 'model_init.pb'), "rb") as f:
    init_net = f.read()
with open(os.path.join(root_dir, 'caffe2_model', "model.pb"), "rb") as f:
    predict_net = f.read()
print('Loaded model files')

p = workspace.Predictor(init_net, predict_net)
print('Created a predictor')

SIZE = 800
img = cv2.imread(IMAGE_PATH)
orig_height, orig_width = img.shape[0:2]

img = cv2.resize(img, (800, int(orig_height * 800 / orig_width)), cv2.INTER_CUBIC)
height, width = img.shape[0:2]
print(height, width)

data = np.reshape(img, (3, height, width))
data = np.float32(np.expand_dims(data, axis=0))
print(data.shape)

im_info = np.float32((height, width, 1))
im_info = np.reshape(im_info, (1, -1))
print(im_info, im_info.shape)
print('Loaded & preprocessed the test image')

print('Forward passing the net...')
results = p.run({'data': data, 'im_info': im_info})
print('Forward passed the net')
print(results)

> ``

**Comment by done420** [comment]
I do get this trouble too, Have you solved it ？
