### ISSUE TITLE
Can I install detectron2 on Mac os X 10.13.6

### ISSUE THREAD

**Issue by sswhqqw** [facebookresearch/detectron2#1399]
## ❓ Can I install detectron2 on Mac os X 10.13.6

1. Can I install detectron2 on Mac os X 10.13.6?
By installing detectron2 on the Mac OS, I wanted to be able to deduce photos using a model on a local computer in the same way as a colab experimental environment.Thanks a lot

**Comment by ppwwyyxx** [comment]
You can

**Comment by Alejom334** [comment]
@ppwwyyxx You really cannot install it simply by the instructions that were given from that article. I get the following error: 

ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2

Wha would you advice me to do?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
