### ISSUE TITLE
PointRend Training: MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES

### ISSUE THREAD

**Issue by YiwuZhong** [facebookresearch/detectron2#1400]
I trained the default PointRend model on my custom dataset for instance segmentation. 

The default setting is `MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True`. Using the default setting, I got a low box mAP (e.g. 44.0). By only changing it to `MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = False`, the box mAP increased quite a lot (e.g. 54.6).

It would be great if anyone can help me with this issue: why the setting  `MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True` will affect the box localization a lot?

Best regards,
Yiwu

**Comment by ppwwyyxx** [comment]
Unfortunately there is a bug introduced on Apr 1 making this option to not work properly. We'll fix it shortly. Thanks for reporting!

**Comment by YiwuZhong** [comment]
Thanks for your reply! Do you mind providing more details about it?

**Comment by ppwwyyxx** [comment]
It was now explained in the commit above.

**Comment by YiwuZhong** [comment]
Thank you so much!
