### ISSUE TITLE
PointRend crashes randomly after ~20k iters

### ISSUE THREAD

**Issue by marcok** [facebookresearch/detectron2#1403]
1. what changes you made (`git diff`) or what code you wrote
nothing in code, only config, I reverted all changes to reproduce.

2. what exact command you run:
python train_net.py --config-file configs/pointrend_semantic_R_101_FPN_1x_cityscapes.yaml --num-gpus 8

3. what you observed (including __full logs__):
I train 15k images with 2 classes for semantic seg. I could reproduce the following behavior.
The crashes are semi random. It never happens if I reduce the training set to < 7k images.
For a certain time, I could just resume and training worked again for a few thousands iters. After ~20k iters each restart crashed before next checkpoint model could be written (i set it to 1000).
I changed batch size for test purposes from 32 to 40 and 48, after that change, 5k iters worked again. Setting the batch size to 24 lead to a crash after only few hundred iters with a different error. At this stage (crashes after resume) I deleted half of train images, after that it worked again until max iters without crash.

error with batch size 24:

`
ERROR [05/12 06:57:41 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 217, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 240, in _detect_anomaly
    self.iter, loss_dict
FloatingPointError: Loss became infinite or NaN at iteration=38414!
loss_dict = {'loss_sem_seg': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_sem_seg_point': tensor(nan, device='cuda:0', grad_fn=<NllLoss2DBackward>)}
[05/12 06:57:41 d2.engine.hooks]: Overall training speed: 412 iterations in 0:01:30 (0.2198 s / it)
[05/12 06:57:41 d2.engine.hooks]: Total training time: 0:01:31 (0:00:00 on hooks)
`

error log with batch size >= 32

The crash log is huge, here some parts of it

`
-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/launch.py", line 89, in _distributed_worker
    main_func(*args)
  File "/home/rsa-key-20190908/detectron2_repo/projects/PointRend/train_net.py", line 120, in main
    return trainer.train()
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/defaults.py", line 401, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 217, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "/home/rsa-key-20190908/detectron2_repo/detectron2/engine/train_loop.py", line 237, in _detect_anomaly
    if not torch.isfinite(losses).all():
RuntimeError: CUDA error: device-side assert triggered
`
`
,0: block: [17/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu,0,0:60] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0: lambda [](int)->auto::operator()(int)->auto], thread: [50` failed.
,0: block: [5/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu,0,0:60] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0: lambda [](int)->auto::operator()(int)->auto` failed.
], thread: [123: block: [10/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [5,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [5,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [5,0,0:60], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: lambda [](int)->auto::operator()(int)->auto: block: [5: block: [17,0,0,0,0], thread: [127], thread: [51,0,0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
` failed.
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [96,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [97,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [98,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [99,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [100,0,0], thread: [56,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [101,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [102,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu` failed.
:60/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/IndexKernel.cu: lambda [](int)->auto::operator()(int)->auto:60: block: [6: lambda [](int)->auto::operator()(int)->auto,0: block: [17,0,0], thread: [103,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds",0` failed.
`

total_loss decline looked actually good to me:
![image](https://user-images.githubusercontent.com/2509708/81652065-d540da80-943b-11ea-8929-ed1ea22e4942.png)

I train with 8 GPU, here the config file. I used the cityscapes loader and config and adjusted it to my own dataset.

`CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 8
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - cityscapes_fine_sem_seg_val
  TRAIN:
  - cityscapes_fine_sem_seg_train
GLOBAL:
  HACK: 1.0
INPUT:
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: false
    SINGLE_CATEGORY_MAX_AREA: 0.75
    SIZE:
    - 512
    - 1024
    TYPE: absolute
  FORMAT: BGR
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MIN_SIZE_TRAIN:
  - 480
  MIN_SIZE_TRAIN_SAMPLING: choice
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
    - - 64
    - - 128
    - - 256
    - - 512
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_fpn_backbone
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    NORM: ''
    OUT_CHANNELS: 256
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_ON: false
  META_ARCHITECTURE: SemanticSegmentor
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 1.0
  - 1.0
  - 1.0
  POINT_HEAD:
    CLS_AGNOSTIC_MASK: false
    COARSE_PRED_EACH_LAYER: true
    COARSE_SEM_SEG_HEAD_NAME: SemSegFPNHead
    FC_DIM: 256
    IMPORTANCE_SAMPLE_RATIO: 0.75
    IN_FEATURES:
    - p2
    NAME: StandardPointHead
    NUM_CLASSES: 2
    NUM_FC: 3
    OVERSAMPLE_RATIO: 3
    SUBDIVISION_NUM_POINTS: 8192
    SUBDIVISION_STEPS: 2
    TRAIN_NUM_POINTS: 2048
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 101
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_WEIGHTS: &id001
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  ROI_BOX_HEAD:
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    CLS_AGNOSTIC_BBOX_REG: false
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FastRCNNConvFCHead
    NORM: ''
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    IOU_LABELS:
    - 0
    - 1
    IOU_THRESHOLDS:
    - 0.5
    NAME: StandardROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: true
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    FC_DIM: 1024
    IN_FEATURES:
    - p2
    NAME: MaskRCNNConvUpsampleHead
    NORM: ''
    NUM_CONV: 4
    NUM_FC: 2
    OUTPUT_SIDE_RESOLUTION: 7
    POINT_HEAD_ON: false
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS: *id001
    BOUNDARY_THRESH: -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    - p6
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    LOSS_WEIGHT: 1.0
    NAME: PointRendSemSegHead
    NORM: GN
    NUM_CLASSES: 2
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
OUTPUT_DIR: ./output
SEED: -1
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: false
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 32
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 120000
  MOMENTUM: 0.9
  NESTEROV: false
  STEPS:
  - 80000
  - 100000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 0
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
`

**Comment by Cyril9227** [comment]
Same for me, it will produce a NaN loss with the default LR, reducing it however seems to allow the training to run

**Comment by marcok** [comment]
@Cyril9227  thanks for the hint, I saw the scheduler is loaded from the model on resume thought. Did you complete restart the training, wrote some code to replace the scheduler or found a config option to reset the scheduler?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
