### ISSUE TITLE
Reasons for separated dataset

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#1404]
As far as I understand, Panoptic FPN network is trained on COCO instances dataset + COCO stuff dataset which is generated from COCO Panoptic dataset (isthing = 0), rather than using Panoptic dataset itself.
What would happen if I try to train PanopticFPN using only COCO Panoptic dataset?

**Comment by ppwwyyxx** [comment]
We trained it this way because it is what the paper did. It's slightly better if I remember it correctly.
