### ISSUE TITLE
pickle dumps support in torch 1.5

### ISSUE THREAD

**Issue by bomri** [facebookresearch/detectron2#1407]
Hello,

Working with torch==1.5 the following line returns a warning regarding pickle support:

`buffer = pickle.dumps(data, protocol=-1)`

warning: "pickle support for Storage will be removed in 1.5. Use `torch.save` instead"

Link to the code line:
https://github.com/facebookresearch/detectron2/blob/273e3b9746473a7469550bf793bbfb4c0a47c7d5/detectron2/data/common.py#L81

**Comment by ppwwyyxx** [comment]
thanks for reporting! We'll update the deprecated use of pickle

**Comment by ppwwyyxx** [comment]
Pytorch added back pickle support in https://github.com/pytorch/pytorch/pull/39003
