### ISSUE TITLE
How to use trained model of custom dataset for inferencing? Error: AssertionError: ColorMode.IMAGE_BW requires segmentation.

### ISSUE THREAD

**Issue by IsaacPatole** [facebookresearch/detectron2#1408]
Hello, 
I am new to Pytorch and Detectron so this might be a obvious or easy question but I am unable to understand some logic behind the script I have.

** have trained a model using the following code:**
register_coco_instances("train_500", {}, "/home/ubuntu/Documents/isaac/detectron2/MRCCN_training/500_coco_label.json", "/home/ubuntu/Documents/isaac/detectron2/MRCCN")

ksh_metadata = MetadataCatalog.get("train_500")
dataset_dicts = DatasetCatalog.get("train_500")

cfg = get_cfg()
cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("train_500",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = 1000   # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output/'

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

**Then I am using this script for inferencing:**

cfg = get_cfg()

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output/'

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
cfg.DATASETS.TEST = ("train_500", )
predictor = DefaultPredictor(cfg)

metadata = MetadataCatalog.get("train_500")

from detectron2.utils.visualizer import ColorMode
path = '/home/ubuntu/Documents/isaac/detectron2/MRCCN/50-45.jpg'
im = cv2.imread(path)
outputs = predictor(im)

v = Visualizer(im[:, :, ::-1],
                   metadata=ksh_metadata, 
                   scale=0.5,
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imwrite("test_image.jpg", v.get_image()[:, :, ::-1])

**This is the error I am getting**

'proposal_generator.anchor_generator.cell_anchors.0' has shape (3, 4) in the checkpoint but (15, 4) in the model! Skipped.
'proposal_generator.rpn_head.conv.weight' has shape (256, 256, 3, 3) in the checkpoint but (1024, 1024, 3, 3) in the model! Skipped.
'proposal_generator.rpn_head.conv.bias' has shape (256,) in the checkpoint but (1024,) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.weight' has shape (3, 256, 1, 1) in the checkpoint but (15, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.bias' has shape (3,) in the checkpoint but (15,) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.weight' has shape (12, 256, 1, 1) in the checkpoint but (60, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.bias' has shape (12,) in the checkpoint but (60,) in the model! Skipped.
'roi_heads.box_predictor.cls_score.weight' has shape (4, 1024) in the checkpoint but (81, 2048) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (4,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (12, 1024) in the checkpoint but (320, 2048) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (12,) in the checkpoint but (320,) in the model! Skipped.
Traceback (most recent call last):
  File "inference_mrcnn.py", line 52, in <module>
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/utils/visualizer.py", line 364, in draw_instance_predictions
    assert predictions.has("pred_masks"), "ColorMode.IMAGE_BW requires segmentations"
AssertionError: ColorMode.IMAGE_BW requires segmentations

Also, I realise that the model is using huge chunk of memory while inferencing which is not optimal, Where am I messing things up?

**Comment by dhaivat666** [comment]
You are using coco's pretrained model which has 80 classes. But you are trying to run inference for 3 classses. Hence, it's not able to load the weights in the ROI-heads of Coco pretrained model as it has 80 classes. To run inference on trained model on your own dataset, you have to ensure that the classes you are expecting to detect is same as the classes being predicted in the pretrained model. Remove `cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3`. You can't predict your set of classes using a model that was trained for detecting completely different classes.

**Comment by IsaacPatole** [comment]
@dhaivat666 Thanks for reaching out, I have removed cfg.MODEL.ROI_HEADS.NUM_CLASSES =3 and training the model again, I thought it represents number of classes while training...  also in inferencing code do I need this line, cfg.DATASETS.TEST = ("train_500", ) since I am using only image from a path directly and why do we need to intialize and know the metadata variable again if we are using weights which are trained on top of that...

**Comment by IsaacPatole** [comment]
@dhaivat666 I am getting the same error even after removing cfg.MODEL.ROI_HEADS.NUM_CLASSES =3 from my training script.

**Comment by dhaivat666** [comment]
You can't use ksh_metadata while inference because now your model is predicting 80 classes and not 3. So you should probably add `coco_metadata = MetadataCatalog.get('coco_2017_val')` and pass coco_metadata in Visualizer class.

**Comment by ppwwyyxx** [comment]
"ColorMode.IMAGE_BW requires segmentations", and the predictions that are provided to the visualizer do not contain segmentations (probably  because it's not a correct model)

**Comment by ppwwyyxx** [comment]
In this situation, it's still better to draw nothing than to fail. We'll remove the assertion.

**Comment by IsaacPatole** [comment]
@dhaivat666 if I add coco_metadata = MetadataCatalog.get('coco_2017_val') then probably it will predict segmented classes based on coco model and not based on my custom model which I saved as 'final_model.pth'. I might be wrong but this is what it seems from the code to me... also for reference, I have actually trained the model with three classes so will it still give me 80 classes and not 3?

**Comment by IsaacPatole** [comment]
@ppwwyyxx this is the model I saved after training using the above code means it should atleast throw wrong segmentations, what do I need to change?

**Comment by IsaacPatole** [comment]
@ppwwyyxx @dhaivat666 my images are 1024, 1280 in shape, is the error coming because of that? or do I need to train more?

**Comment by dhaivat666** [comment]
@IsaacPatole  if you are running inference on your custom model, then your code was correct except one thing. You forgot to merge cfg object with the maskrcnn model. Add `cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")` after `cfg = get_cfg()` and you should be able to run inference with your custom trained model.

**Comment by ppwwyyxx** [comment]
The assertion has been removed in the latest version.

**Comment by IsaacPatole** [comment]
@ppwwyyxx  Adding cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml") and cfg.MODEL.ROI_HEADS.NUM_CLASSES=3 to my inference code solved my problem thanks to @dhaivat666 . Now I am seeing the correctly segmented image, however I am unable to see the class name of it on top of each bounding box. 
Here is the predicted output.
{'instances': Instances(num_instances=4, image_height=1024, image_width=1280, fields=[pred_boxes: Boxes(tensor([[ 869.5235,  443.6144, 1065.4640,  562.0467],
        [ 405.3201,  433.6031,  596.1700,  548.2667],
        [   0.0000,  433.5136,  137.8672,  535.7256],
        [   0.0000,  430.1221,  149.9999,  540.2857]], device='cuda:0')), scores: tensor([0.9788, 0.9636, 0.8739, 0.8568], device='cuda:0'), pred_classes: tensor([0, 0, 1, 0], device='cuda:0')...


meaning in the pred_classes I am getting the predicted class it is just that they are not reflecting on the output image.
