### ISSUE TITLE
A question about ROI pooling and "GeneralizedRCNN"

### ISSUE THREAD

**Issue by shahabty** [facebookresearch/detectron2#1409]
Hello,
I would like to have access to the intermediate outputs in MaskRCNN such as the output of backbone CNN and the proposals before and after ROI pooling. To do so, I have implemented my own version of GeneralizedRCNN called X. However, I do not exactly know which variables in the inference function of GeneralizedRCNN correspond to region proposals before and after ROI POOL (As far as I could understand from the code, ROI pooling is done by StandardROIHeads in "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"). I really appreciate it if anyone could clarify this for me.

Thank you,

**Comment by ppwwyyxx** [comment]
See https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model

If you expand the forward function like the documentation does, you can obtain any tensor that's used during the forward.
