### ISSUE TITLE
Retinanet training error

### ISSUE THREAD

**Issue by Zy1013921842** [facebookresearch/detectron2#1413]
I can successfully train and test using mask-rcnn without any problem, but when I try to train a retinanet I encountered such errors:

yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag: yaml.org, 2002: python/object.apply:eval'

and

AttributeError: module 'yaml' has no attribute 'unsafe_load'

Do you have any idea on how to solve them?
Appreciate!

**Comment by pvtien96** [comment]
Can you clarify your case  following issue templates?

**Comment by ppwwyyxx** [comment]
fvcore requires pyyaml >= 5.1: https://github.com/facebookresearch/fvcore/blob/8b30e98e52de380fa1b76f71f818117b586a1330/setup.py#L45-L46

**Comment by Zy1013921842** [comment]
> fvcore requires pyyaml >= 5.1: https://github.com/facebookresearch/fvcore/blob/8b30e98e52de380fa1b76f71f818117b586a1330/setup.py#L45-L46

That's it, thank you for quick reply!
