### ISSUE TITLE
Does detectron2 support exporting Rotated Faster-RCNN models?

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#1414]
I ask because I tried to do so and encountered a 'Negative Areas' error in `Caffe2ROIPooler` specifically while distributing rpn proposals (`torch.ops._caffe2.DistributeFpnProposals`). Now this is probably due to the differing formats of the boxes (`XYWHA` vs `XYXY`) and/or the caffe2 ops namely `GenerateProposals` and `CollectRpnProposals` not supporting rotated boxes.

While I'll be looking into the cause of this, I just wanted to know if rotated models exports are supported. If not, is it something that is missing in detectron2 or is it at the torch/caffe2 level.

**Comment by ppwwyyxx** [comment]
`DistributeFpnProposals` and `CollectRpnProposals` does not support rotated boxes, so FPN rotated-boxes models cannot export. Only non-FPN models using rotated boxes can export.
