### ISSUE TITLE
Detectron2 performed on the CPU with a "Torch not compiled with CUDA enabled" error

### ISSUE THREAD

**Issue by sswhqqw** [facebookresearch/detectron2#1416]
The Issue:

1. Detectron2 performed on the CPU with a "Torch not compiled with CUDA enabled" error
Configure Detectron2 environment on a computer without GPU graphics card. After the configuration is OK, run the following code. The weight file is downloaded well in advance and placed in a fixed location.
code:
<img width="909" alt="屏幕快照 2020-05-13 下午8 17 13" src="https://user-images.githubusercontent.com/35377837/81811184-cdc22400-9556-11ea-8697-c05ed950aede.png">

errors:
<img width="845" alt="屏幕快照 2020-05-13 下午8 16 59" src="https://user-images.githubusercontent.com/35377837/81811195-d4509b80-9556-11ea-9397-98ab6378b390.png">
The error is shown below:
<img width="546" alt="屏幕快照 2020-05-13 下午8 04 09" src="https://user-images.githubusercontent.com/35377837/81811012-8a67b580-9556-11ea-9d4a-82e7b9be2323.png">

**Comment by ksablauskas** [comment]
Hi, try adding this after cfg.MODEL.WEIGHTS:
`cfg.MODEL.DEVICE = 'cpu'`

**Comment by sswhqqw** [comment]
> Hi, try adding this after cfg.MODEL.WEIGHTS:
> `cfg.MODEL.DEVICE = 'cpu'`

Thank a lot!!!! It's work!
but image show get some problem 

Traceback (most recent call last):
  File "/Users/wenzq/PycharmProjects/masktest/detectron2masktest.py", line 41, in <module>
    cv2.imshow(v.get_image()[:, :, ::-1])
TypeError: Required argument 'mat' (pos 2) not found

<img width="1249" alt="屏幕快照 2020-05-13 下午8 49 07" src="https://user-images.githubusercontent.com/35377837/81814559-838f7180-955b-11ea-94db-f09b3689083a.png">
