### ISSUE TITLE
CocoEvaluator gives AP greater than one

### ISSUE THREAD

**Issue by utkobe** [facebookresearch/detectron2#1420]
I use following codes to evaluate on my dataset and it gives some metrics (AP) greater than 1. From my understanding, it should be between 0 and 1. So i'm quite confused about this.

```
...
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

register_coco_instances('test_dataset', {}, '...' ,'...');
cfg.DATASETS.TEST = [ 'test_dataset' ];
evaluator = COCOEvaluator('test_dataset', cfg, False, output_dir='...');
val_loader = build_detection_test_loader(cfg, 'test_dataset');
 inference_on_dataset(trainer.model, val_loader, evaluator);
```

And it gives out
![image](https://user-images.githubusercontent.com/31037093/81885437-f127b600-95cc-11ea-987e-866077654e0d.png)

**Comment by ppwwyyxx** [comment]
We define AP in range 0 ~ 100.
