### ISSUE TITLE
Unable to get the class name on a bounding box of a segmented image. 

### ISSUE THREAD

**Issue by IsaacPatole** [facebookresearch/detectron2#1421]
I am unable to see the class name on a bounding box but it is showing class prediction accuracy instead of the name. 

**Here is the inferencing script**
cfg = get_cfg()

cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output/'

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model

cfg.DATASETS.TEST = ("train_500")

predictor = DefaultPredictor(cfg)

metadata = MetadataCatalog.get("train_500")

print("----------",metadata.get("thing_classes"))

from detectron2.utils.visualizer import ColorMode

path = '/home/ubuntu/Documents/isaac/detectron2/MRCCN/50-45.jpg'
im = cv2.imread(path)
outputs = predictor(im)
#print(outputs)

v = Visualizer(im[:, :, ::-1],metadata=metadata, scale=0.5)#,instance_mode=ColorMode.IMAGE_BW

v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imwrite("test_image.jpg", v.get_image()[:, :, ::-1])

printing metadata.get("thing_classes") gives me None in the above script, also in visualize.py 
printing
classes = tensor([0,0,1])
labels = [98%, 88%, 88%]

**Comment by ppwwyyxx** [comment]
> printing metadata.get("thing_classes") gives me None in the above script, also in visualize.py

Metadata should be added following the documentation: https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by IsaacPatole** [comment]
@ppwwyyxx adding dataset_dicts = DatasetCatalog.get("train_500") to the inference code solved my problem.

**Comment by Priyabrata017** [comment]
@isaac-223 Can you show the full code. I am also facing the same issue
