### ISSUE TITLE
Training Detectron2 model with only bounding boxes and without segmentation information

### ISSUE THREAD

**Issue by sainatarajan** [facebookresearch/detectron2#1422]
I have a dataset that has only the bounding boxes. But the specification says that I also need to have the segmentation masks in the JSON file, i.e:

```
px = anno["all_points_x"]
py = anno["all_points_y"]
poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
poly = [p for x in poly for p in x]

obj = {
"bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
"bbox_mode": BoxMode.XYXY_ABS,
"segmentation": [poly],
"category_id": 0,
"iscrowd": 0
}
```
I don't have the "all_points_x" and "all_points_y" keys in my JSON since I only want object detection instead of semantic/instance segmentation. Can someone help me with how to train the detectron2 model without the segmentation information?

Thanks!

**Comment by sainatarajan** [comment]
Closing the issue, since 'segmentation' is not a compulsory key.

**Comment by thanoscs** [comment]
> Closing the issue, since 'segmentation' is not a compulsory key.

So the segmentation can be omitted? and use the bounding boxes? because this is exactly what i have.

**Comment by sainatarajan** [comment]
@thanoscs Yeah, you can omit the `segmentation` key.

**Comment by thanoscs** [comment]
> @thanoscs Yeah, you can omit the `segmentation` key.

Thank you very mych @sainatarajan , i tested it and it worked.
