### ISSUE TITLE
Custom object detection dataset labeling 

### ISSUE THREAD

**Issue by chamecall** [facebookresearch/detectron2#1423]
When labeling custom object detection dataset  is that necessary condition to label every object from my classes on an every single image?

Or some objects could be only labeled on my own and other ones may be skipped?
What will be if network predicts the skipped objects correctly but they're unlabeled?
Will it spoil the generalizing ability of the network?

**Comment by ppwwyyxx** [comment]
We only discuss questions that are specific to detectron2 (https://github.com/facebookresearch/detectron2/issues/new/choose) in github issues.
