### ISSUE TITLE
How to achieve semantic parts segmentation in densepose

### ISSUE THREAD

**Issue by SriRamGovardhanam** [facebookresearch/detectron2#1425]
Hello

In the process of understanding densepose, i really like to extract/explore the masks of individual body parts with coordinates, or if it is not possible in detectron2 at-least trying to apply bounding boxes for individual parts. In both the cases this is what i have tried from the last 10 days
this is in reference with the [thread 165](https://github.com/facebookresearch/detectron2/issues/165) and other from github [here](https://github.com/linjunyu/Detectron2-Densepose-IUV2XYZ/blob/master/Detectron2-densepose-IUV2XYZ.ipynb)
i tried like this:
```
INDS = iuv_arr[0,:,:] 
print('INDS shape:', INDS.shape)
C = np.where(INDS >= 1)
mask = np.ascontiguousarray(C)
(contours, _) = cv2.findContours(mask.astype("uint8"), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
for c in contours:
    x, y, w, h = cv2.boundingRect(c)
    cv2.rectangle(im, (x, y), (x + w, y + h), (0, 0, 255), 2)
cv2_imshow(im)
```
tried for applying bounding boxes for every part, which is not happening

Also tried something for getting masks, referencing the [thread](https://github.com/facebookresearch/detectron2/issues/1388) , like this:
```
cfg = get_cfg()
add_densepose_config(cfg)

cfg.merge_from_file("/content/detectron2/projects/DensePose/configs/densepose_rcnn_R_101_FPN_s1x.yaml")
cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x/165712084/model_final_c6ab63.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
outputs['instances'].pred_densepose
```
```
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get('densepose_coco_2014_minival'), scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(v.get_image()[:, :, ::-1])
```
this gives output as BBOX on the person, but not dealing with individual parts.
In both the cases. i failed to get either bounding boxes or generating masks

expecting something like this:
![imgTBB](https://user-images.githubusercontent.com/35695549/81980345-0db70300-964c-11ea-85b0-16b380e02352.png)

Anyone Please help me with this issue @vkhalidov

**Comment by vkhalidov** [comment]
Hello @SriRamGovardhanam,
For axis-aligned bounding box of body part `i`, you need to consider an array `iuv_arr[0, :, :] == i` and derive its bounding box using e.g. `np.where`. [Check here for an example](https://stackoverflow.com/questions/4808221/is-there-a-bounding-box-function-slice-with-non-zero-values-for-a-ndarray-in).
For bounding boxes oriented as in your example, you need to estimate principal directions (eigenvectors) for points `iuv_arr[0, :, :] == i` and fit a rectangle. [Have a look here for an example](https://stackoverflow.com/questions/32892932/create-the-oriented-bounding-box-obb-with-python-and-numpy)

**Comment by SriRamGovardhanam** [comment]
Hii @vkhalidov  
Thank you so much for responding
apart from eigenvectors way, referring the step here `iuv_arr[0, :, :] == i` 1st thing first how can i get specific body part `i` ,  at present i have only these values `INDS`, `IUV` in my hand, leave aside that tilted bbox part how can i get a specific part?
is there a way in detectron2 to generate a mask of every segment detected as mentioned [here](https://github.com/facebookresearch/detectron2/issues/1348)

I really appreciate your time and guidance.

**Comment by vkhalidov** [comment]
@SriRamGovardhanam `INDS` values that are equal to `i>0` are estimated to belong to part `i`. The details on which part corresponds to which index can be found [here](https://github.com/facebookresearch/DensePose/blob/master/challenge/2019_COCO_DensePose/data_format.md)
So by taking non-zero entries of `INDS == i` and applying the bounding box estimation code, you're going to get the bounding box of part `i`

**Comment by SriRamGovardhanam** [comment]
Hello @vkhalidov 
Thank you for such a wonderful contribution
now i have got the desired output
I really appreciate that every time you are genuinely helping others when they get stuck with some issue.
Thank You for Providing the References for Oriented BBOX 😃
