### ISSUE TITLE
COCOEvaluator  AttributeError

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1426]
**this is my code:**
COCOEvaluator(dataset_name='/media/cs431/backup/OCT/final_oct/OCT_train.json',
        cfg='/home/cs431/detectron2-master/train/mask_rcnn_R_50_FPN_3x.yaml',
        distributed=True,
        output_dir='/home/cs431/detectron2-master/output')

**this is my error:**
line 92, in _tasks_from_config
    if cfg.MODEL.MASK_ON:
AttributeError: 'str' object has no attribute 'MODEL'

**this is my config :** 
   _BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/cs431/detectron2-master/output/randomoctv1.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

is my weights get wrong? thank you

**Comment by raijinspecial** [comment]
```
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("Misc/mask_rcnn_R_50_FPN_3x_dconv_c3-c5.yaml"))
```
