### ISSUE TITLE
modification on visualizer.py won't change the output of demo

### ISSUE THREAD

**Issue by jlu-D97** [facebookresearch/detectron2#1428]
I'm just running the demo, and I wish to modify some parts of the visualizer.py file but it won't affect the demo program. The demo runs properly even without the visualizer.py file. 
But I've checked that the demo.py imports VisualizationDemo class from predictor.py and the predictor.py imports the Visualizer class from visualizer.py.

**Comment by ppwwyyxx** [comment]
See http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/

**Comment by jlu-D97** [comment]
Sorry, I can't open the link you posted.

**Comment by ppwwyyxx** [comment]
It's accessible now
