### ISSUE TITLE
COCOEvaluator output nothing 

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1429]
i finish the code like :
COCOEvaluator(dataset_name='oct',
        cfg=get_cfg(),
        distributed=True,
        output_dir='/home/cs431/detectron2-master/train/output')
but i got nothing in my output_dir

i thing my code should be have predictor to produce the results of COCOEvaluator,
but i no idea how to code. anyone may  give me some idea? thank you

**Comment by ppwwyyxx** [comment]
Examples given in the tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
