### ISSUE TITLE
Are there any fast pretrained network trunks for real-time object detection / models for deployment on mobile devices

### ISSUE THREAD

**Issue by xavierdcruz** [facebookresearch/detectron2#1430]
## 🚀 Feature

I've used a big 50 layer resnet, and that is working nicely, but it's slow. I want stuff like mobilenet, squeezenet etc.

## Motivation & Examples

To run on mobile devices, or real time inference on machines without powerful GPUs.

**Comment by ppwwyyxx** [comment]
feature request already exists

**Comment by Shubhambindal2017** [comment]
How can I use detectron2 for Mask RCNN, with MobileNet as the backbone?
