### ISSUE TITLE
Error when register to COCO and verify data loadin #1432

### ISSUE THREAD

**Issue by favervn** [facebookresearch/detectron2#1433]
Hi, I'm getting this error while executing register and verify. Please help me to fix. Thanks

1, I tried to register my coco dataset to Detectron 
```
bird_parrot_metadata = MetadataCatalog.get("bird_parrot")
dataset_dicts = DatasetCatalog.get("bird_parrot")
```
but I got  this error:
```
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.
TypeError: 'NoneType' object is not subscriptable
```

2, Next when I verify the data loading:

```
import random
for d in random.sample(dataset_dicts, 3):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=bird_metadata, scale=0.5)
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```
I got the error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-0de1e9f88dda> in <module>()
      2 for d in random.sample(dataset_dicts, 3):
      3     img = cv2.imread(d["file_name"])
----> 4     visualizer = Visualizer(img[:, :, ::-1], metadata=bird_metadata, scale=0.5)
      5     vis = visualizer.draw_dataset_dict(d)
      6     cv2_imshow(vis.get_image()[:, :, ::-1])

TypeError: 'NoneType' object is not subscriptable
```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by trinanjan12** [comment]
@favervn check the image path for cv2.imread. happened to me for reading an invalid path

**Comment by favervn** [comment]
> @favervn check the image path for cv2.imread. happened to me for reading an invalid path

YESSS I DID IT. Love mate. Thank you so much.
Ive spent days to solve this error. Haha

**Comment by favervn** [comment]
For those for struggling with the same issue.
The problem may occur in you dataset generating progress. You should check the image path in .json file to make sure the path should be in the structure "your_image_name.jpg" not "...\Folder\your_image_name.jpg". After making the path right, re-run labelme2coco.py for new trainval.json and now you can smile :)

**Comment by morganOliveira2018** [comment]
> For those who is struggling with the same issue.
> The problem may occur in you dataset generating progress. You should check the image path in .json file to make sure the path should be in the structure "your_image_name.jpg" not "...\Folder\your_image_name.jpg". After making the path right, re-run labelme2coco.py for new trainval.json and now you can smile :)

**How did you solve the problem? I have the same situation. Could you explain it better?**

**Comment by morganOliveira2018** [comment]
@favervn Can you explain to me how to solve this problem? I am going through the same situation. Please.
**As soon as possible to answer me, thank you very much.**

````
WARNING [11/11 13:14:08 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[11/11 13:14:08 d2.data.datasets.coco]: Loaded 28 images in COCO format from /content/x/train.json
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-e7250c241ebb> in <module>()
      7 for d in random.sample(dataset_dicts, 3):
      8     img = cv2.imread(d["file_name"])
----> 9     v = Visualizer(img[:, :, ::-1], metadata=x_metadata, scale=0.5)
     10     v = v.draw_dataset_dict(d)
     11     plt.figure(figsize = (14, 10))

TypeError: 'NoneType' object is not subscriptable
````

**Comment by awaizahmadfg** [comment]
> For those who is struggling with the same issue.
> The problem may occur in you dataset generating progress. You should check the image path in .json file to make sure the path should be in the structure "your_image_name.jpg" not "...\Folder\your_image_name.jpg". After making the path right, re-run labelme2coco.py for new trainval.json and now you can smile :)

Thank you brother.

**Comment by htw** [comment]
> 

太棒了，就是这个原因

**Comment by The-AlphaApp** [comment]
the problem is caused by the image path 
when you register your dataset using 
DatasetCatalog.register("exmple_train", {} , "dataset/train")
the 3rd parameter is supposed to point to the images directory when registering that path will be added to all images file names 
it will take it from this 
dataset/train/img01.png 
to this :
dataset/train/dataset/train/img01.png
the solution is simple just give an empty directory like this
DatasetCatalog.register("exmple_train", {} , "")
