### ISSUE TITLE
AssertionError: Input boxes to Box2BoxTransform are not valid!

### ISSUE THREAD

**Issue by ChauncyFr** [facebookresearch/detectron2#1434]
This error occurred when I used the PointRend model to train my own dataset. My dataset refers to the coco format, and I set NUMS_CLASSES in the configuration file to the number of categories in my dataset. The number of GPUs is 1 or 2, and the following errors have occurred. Does anyone know what is going on?

![](https://tva1.sinaimg.cn/large/007S8ZIlly1geu3pbh5m5j31lv0u0k25.jpg)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
