### ISSUE TITLE
What's the segmentation parameter  data in the pascal data for using custom data for object detection

### ISSUE THREAD

**Issue by tianke0711** [facebookresearch/detectron2#1435]
Hi I am referring the document https://detectron2.readthedocs.io/tutorials/datasets.html#use-custom-datasets how to use the custom datasets  to create my own data def my_dataset_function() to detect the bounding box in my own dataset: . 

The data format is the pascal voc format: there is bounding box data: xmin, ymin, max, ymax. in the xml file. I am checking the document to write a function about using custom dataset.  
There is parameter called segmentation, I don't know how to get the data from pascal data.
I found the code in the Colab tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 about segmentation like this:

`px = anno["all_points_x"]
            py = anno["all_points_y"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = list(itertools.chain.from_iterable(poly))
           "segmentation": [poly],`

       

How to realize in the pascal format data, I just to detect the bounding box of object in the image.

**Comment by ppwwyyxx** [comment]
What should be in the data loading function depends on what the custom data format looks like, which is unrelated to detectron2. Users should turn custom formats into detectron2's format in this function, as the documentation https://detectron2.readthedocs.io/tutorials/datasets.html#register-a-dataset says.
