### ISSUE TITLE
Is this a correct way to get the shape of an image in resized space?

### ISSUE THREAD

**Issue by SupreethN** [facebookresearch/detectron2#1436]
Is the shape of the tensor in ```image``` field of a dataloader item, the size of the corresponding image in resized image space? 

For example,  [here](https://github.com/facebookresearch/detectron2/blob/62cf3a2b6840734d2717abdf96e2dd57ed6612a6/tools/plain_train_net.py#L152) ```data``` is an item in the ```train_data_loader```. It contains data for ```batch_size``` number of images. If I want to get the resized image shape used by RCNN for the first image in the batch, I was thinking to use ```data[0]['image'].shape```. Is this correct?

**Comment by ppwwyyxx** [comment]
Yes.
Described in https://detectron2.readthedocs.io/tutorials/models.html#model-input-format

> the image input field might be a resized image
