### ISSUE TITLE
More pretrained models of PointRend

### ISSUE THREAD

**Issue by XuYunqiu** [facebookresearch/detectron2#1440]
Hi, thanks for sharing the implementation of PointRend. 
I would ask is there any plan for sharing more pretrained models with larger backbones on COCO, such as `R-101-FPN` or `X-101-FPN`. Or any configs for training those networks?

**Comment by ppwwyyxx** [comment]
No plans for now. You can check some configs [model zoo](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md) for how to use R-101 and X-101.
