### ISSUE TITLE
Pandas convert BoxMode to int

### ISSUE THREAD

**Issue by esgnn** [facebookresearch/detectron2#1441]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
This is the function for DatasetCatalog
```
`def create_data(annotation_data,data_folder_path):
    meta_data = pd.DataFrame(annotation_data['images']).reset_index()[['index','file_name','height','width','id']]
    meta_data.columns = ['index','file_name','height','width','image_id']
    annot_index_data = pd.DataFrame(annotation_data['annotations']).reset_index()
    annot_index_data = annot_index_data[annot_index_data['num_keypoints']!=0][['image_id','bbox','keypoints','category_id','iscrowd']]
    annot_index_data['bbox_mode'] = BoxMode.XYWH_ABS
    annotated_image_list = annot_index_data[['image_id']].drop_duplicates()


    annot_index_data['annotations'] = annot_index_data[['bbox','bbox_mode','keypoints','category_id','iscrowd']].to_dict('records')
    annot_index_data.drop(['bbox','bbox_mode','keypoints','category_id','iscrowd'],axis=1,inplace=True)
    annot_index_data = annot_index_data.groupby('image_id')['annotations'].apply(list).reset_index()


    annotated_image_list = pd.merge(annotated_image_list,meta_data,'left',on='image_id')
    annotated_image_list['file_name'] = annotated_image_list['file_name'].apply(lambda x: data_folder_path+x)

    annotated_image_list_w_annotations = pd.merge(annotated_image_list,annot_index_data,'left',on='image_id')

    data_values_list = annotated_image_list_w_annotations.to_dict('records')

    return data_values_list`
```
2. what exact command you run:
`annot_index_data['bbox_mode'] = BoxMode.XYWH_ABS`
3. what you observed (including __full logs__):
Pandas changed BoxMode.XYWH_ABS to 1, which would later caused problem when training initiated because the type changed to integer.
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
Just create a pandas dataframe and add box as a new column
## Expected behavior:
Expected to retain its type.
## Environment:
Google Colab

**Comment by ppwwyyxx** [comment]
> Expected to retain its type

I'm not sure that is a correct expectation, but since you expect pandas to retain its type, it should be an issue for pandas.

**Comment by esgnn** [comment]
Reported just to let you inform about the issue, and for reference to other people
