### ISSUE TITLE
Finetune coco keypoin model

### ISSUE THREAD

**Issue by trinanjan12** [facebookresearch/detectron2#1442]
I am trying to finetune the coco keypoint_rcnn_R_50_FPN_1x model. Because when the model gets an input image as crop body it doesn't work well. [original coco keypoint model output on crop images](https://lh3.googleusercontent.com/-IN9iYitn374/XrDLmk9AvoI/AAAAAAAABK8/0AraJR05nYI7qpL8l4G7HzNy9gbvcIc4QCK8BGAsYHg/s0/2020-05-04.jpg)

## Data preparation :
1. I had taken 5000 full-body images, extracted the key points of the entire image by using the keypoint_rcnn_R_50_FPN_1x model. Then I cropped the images with detectron custom model and mapped keypoints only for the bottom crop using the original key points of the full-body image. I used the coco format
[data format](https://jsonblob.com/4806724c-9832-11ea-bc2c-d1af3c3d143e)
2 . I had checked the data using detectron2 data catalog and the data looks fine 

from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.utils.visualizer import Visualizer
from detectron2.data.datasets import register_coco_instances
import random

base_dir = '/media/trinanjan/BACKUP/Trinanjan/current_project/virtual_try_on/detectron2/datasets/coco'
register_coco_instances("person_keypoints1", {}, base_dir + "/annotations/person_keypoints_train2017.json",  base_dir + "/train2017")
fruits_nuts_metadata = MetadataCatalog.get("person_keypoints1")
dataset_dicts = DatasetCatalog.get("person_keypoints1")

for d in random.sample(dataset_dicts,2):
    x = np.array(d['annotations'][0]['keypoints'])
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=fruits_nuts_metadata, scale=0.5)
    vis = visualizer.overlay_instances(keypoints = x.reshape(1,17,3))
    cv2.imwrite('test.jpg',vis.get_image()[:, :, ::-1])

 [and the train data looks like this looks like this](https://i.imgur.com/jE7saVJ.jpg)

Note: somethings I am doing while making data, seg is an empty list, all the key points are having visibility of 2 [coco format](http://cocodataset.org/#format-data). bbox is the same size of the image as I am providing the crop of the original full-body image as input. I am not sure how to use the visibility flag value because the coco keypoint_rcnn_R_50_FPN_1x model returns the third value as a score(not visibility). So I can't use that directly.

## The command for training : 
 python train_net.py --config-file ../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 DATALOADER.NUM_WORKERS 0 MODEL.WEIGHTS "./weights/r50_fpn_1x/model_final_04e291.pkl" 

## After Training:
When I test the model using the final model the outputs are not good. Though I can see the crop images are giving little better output but the full-body images are giving bad output

here are some outputs 
[finetuned model](https://imgur.com/a/bNfQgKn)
[original keypoint_rcnn_R_50_FPN_1x ](https://imgur.com/a/KiudAw2)

Even though the crop images have better output but the full-body images become bad. especially the face keypoints.

Is this an expected behavior. Am I missing something here

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
