### ISSUE TITLE
Getting "IndexError: list index out of range" while doing visualization after successfully training my custom model using PointRend

### ISSUE THREAD

**Issue by beta31** [facebookresearch/detectron2#1443]
I successfully trained & evaluated my custom model using PointRend (detectron2-MaskRCNN) successfully but when I'm trying to do visualization i'm getting this "IndexError: list index out of range".
I'm using the normal detectron2 visualization code, I haven't done any such major change in that:
```
for d in random.sample(val_dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=custom_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW  
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2_imshow(v.get_image()[:, :, ::-1])
```
Below is the code where I'm giving trained model path etc.
`cfg = get_cfg()
point_rend.add_pointrend_config(cfg)
cfg.merge_from_file("detectron2_repo/projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_1x_coco.yaml")
cfg.MODEL.WEIGHTS = r'/content/content/output/model_final.pth'
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
predictor = DefaultPredictor(cfg)`

Could anyone please let me know, what I'm doing wrong over here?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
