### ISSUE TITLE
How to compute flops of pooling operation with detectron2.utils.analysis?

### ISSUE THREAD

**Issue by LeonJWH** [facebookresearch/detectron2#1447]
I want to know how to calculate flops of pooling operations with detecron2's analysis API, such as nn.MaxPooling2d, nn.Avgpooling2d and AdativeAvgPool2d.

I have tried to add `pool_flop_jit` like  `conv_flop_jit` in fvcore's `jit_handles.py`, but it seems like that the torch script trace cannot offer pooling kernel sizes because there is no params in pooling operation.

Thank you for your answer!

**Comment by ppwwyyxx** [comment]
Detectron2 or fvcore does not have the feature of "computing flops of pooling operations", and how to implement that is out of the scope of support since it's only about how to use pytorch jit and not relevant to detectron2.
