### ISSUE TITLE
add a feature: save IUV.png and INDS.png.

### ISSUE THREAD

**Issue by wuneng** [facebookresearch/detectron2#145]
In caffe2 implementation, densepose will save two images IUV.png and INDS.png. But densepose in detectron2 dose not have this feature.

**Comment by vkhalidov** [comment]
@wuneng, there's a possibility to dump results to a file (`python apply_net.py dump ...`, see [Apply Net](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/TOOL_APPLY_NET.md) tool doc). Then you can extract IUV from the resulting dump file. Please, check my answer in #165 for more details and references

**Comment by wuneng** [comment]
@vkhalidov thank you for your answer.

**Comment by Taye310** [comment]
did u figure out how to export an IUV.png from the dump file?

**Comment by Taye310** [comment]
> @vkhalidov thank you for your answer.

did u figure out how to export an IUV.png from the dump file?

**Comment by linjunyu** [comment]
@wuneng @Taye310 I reaccomplished the functions of IUV extraction from image and IUV projection on SMPL model, and it worked well in Detectron 2. Check [this](https://github.com/linjunyu/Detectron2-Densepose-IUV2XYZ) out.
