### ISSUE TITLE
Error while using Custom Backbone

### ISSUE THREAD

**Issue by ASKanse** [facebookresearch/detectron2#1451]
## ❓ How do we use a custom backbone?

As mentioned in [Writing Models](https://detectron2.readthedocs.io/tutorials/write-models.html) I included the code block give there in my code and set ```cfg.MODEL.BACKBONE.NAME = 'ToyBackBone'``` but I was getting this error while training:
```AttributeError: cannot assign module before Module.__init__() call``` what could be the reason for this?
I made a copy of the colab notebook provided for getting started, and that's where i am doing this experiment of adding a new backbone

Also can some one point me to a repo where they have used a custom backbone? (just for reference))

EDIT 1: MY training code for reference
```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("Misc/scratch_mask_rcnn_R_50_FPN_3x_gn.yaml"))
cfg.DATASETS.TRAIN = ("neucleus_Train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("Misc/scratch_mask_rcnn_R_50_FPN_3x_gn.yaml")  # Let training initialize from model zoo
cfg.MODEL.BACKBONE.NAME = 'ToyBackBone'
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 3000    # 3000 iterations seems to bee the feasible number for this dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512  # default*2
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 7  # has seven classes 

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Comment by ppwwyyxx** [comment]
Google says: https://stackoverflow.com/questions/43080583/attributeerror-cannot-assign-module-before-module-init-call/43080779

We can improve the documentation better to include this.
