### ISSUE TITLE
How to add cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  in yaml file

### ISSUE THREAD

**Issue by rsinghoyla** [facebookresearch/detectron2#1454]
## ❓ How to do something using detectron2
I am transfer learning from "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"  using train_net.py and yaml config files. I do not know how to specify the MODEL.WEIGHTS for this model. Do I have to add 
`#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml") ` 
in code (train_net.py)? and where?
Or do I specify in yaml file? and where?

Thanks

**Comment by ppwwyyxx** [comment]
You can set it in code when you creat the config.
Or you can set it in yaml file and you can look at the existing yaml files to learn the yaml syntax.

**Comment by rsinghoyla** [comment]
Thanks but I cant find any instance of a yaml file that does not do
`WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"`
and I dont know how to set url for other models

**Comment by ppwwyyxx** [comment]
You can set it to a path to a file, or any URL found in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by rsinghoyla** [comment]
Thanks seems to work except that Coco-detection retinanet model files are given access denied errors. I can make it work with say faster-rcnn models

**Comment by aditjha** [comment]
Is there a way to remove this access denied errors for coco-detection retinanet models? I need retinanet specifically...please help would really appreciate it
