### ISSUE TITLE
Default data augmentation

### ISSUE THREAD

**Issue by RomRoc** [facebookresearch/detectron2#1456]
I'm training an instance segmentation model with custom dataset, I use DefaultTrainer.

Log says:
`TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]`

DefaultTrainer performs any data augmentation (maybe horizontal and vertical flip) by default?

Can I customize data augmentation with any cfg parameter, instead of creating a Custom Dataloader?

Thanks

**Comment by ppwwyyxx** [comment]
> DefaultTrainer performs any data augmentation (maybe horizontal and vertical flip) by default?

Trainer does not. The default data loader does perform flip and resize augmentation.

> Can I customize data augmentation with any cfg parameter, instead of creating a Custom Dataloader?

You can change resize with `INPUT.MIN_SIZE_TRAIN`. More customized augmentation requires a custom dataloader (https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader).
