### ISSUE TITLE
How to get one segmentation mask and save as image?

### ISSUE THREAD

**Issue by 3ventHoriz0n** [facebookresearch/detectron2#1458]
I am trying to extract a single segmentation mask and save it as an image.

Model: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml
Input : 3024x3024 RGB color image
Desired Output: A single segmentation mask for prominent object in the image. 

I passed an image of a coffee cup placed on a study desk. I get 2 masks in `output['instances']` the mask for the cup is at `output['instances'][0]`. When I pass another image of a bottle on the same desk I get the mask for the desk at `output['instances'][0]` and for the bottle at `output['instances'][1]`

I would then like to save this segmentation mask as an image, something to the effect of:
`cv2.imwrite(name,(255*mask).astype(np.uint8))`

I want the masks for the bottle, cup etc which are the prominent objects to always be returned in the same place as I want to pass this mask ahead to another algorithm 

Please advise, thanks!

**Comment by ppwwyyxx** [comment]
The output format is described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

**Comment by pvtien96** [comment]
@3ventHoriz0n you can search 'mask' in issues.
#200 may help you.
