### ISSUE TITLE
Question of TransformGens

### ISSUE THREAD

**Issue by wenjun90** [facebookresearch/detectron2#1460]
Hello @ppwwyyxx 

I would like ask you this problem.
I see this after run trainer:

`"TransformGens used in training: [ResizeShortestEdge(short_edge_length=( 640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]"`

This is process of transform image for augmentation data ou not?
The images will be resize by many 6 sizes from original image to augmented data for training?

Thank you very much.

**Comment by ppwwyyxx** [comment]
Yes

**Comment by wenjun90** [comment]
@ppwwyyxx  Thank you for your answe. What a great Detectron2 with automatic  Augmentation data.

**Comment by wenjun90** [comment]
Hi @ppwwyyxx ,

I would like to set the learning rate like that?

Could you give me an advice to do that?


![lr](https://user-images.githubusercontent.com/64893076/83363720-d2cb0400-a39b-11ea-926b-29e43a0f9e44.png)
![lr](https://user-images.githubusercontent.com/64893076/83363726-de1e2f80-a39b-11ea-83c3-565f46ff8b84.png)

Thank you!
