### ISSUE TITLE
How to avoid repeated predictions on the same objects?

### ISSUE THREAD

**Issue by Zy1013921842** [facebookresearch/detectron2#1461]
When I did inference on one image, I found one object could be detected as more than one class, and the detections were all drew on the image, overlapping with each other. 
How can I make the model to test only one time for one object?
Can changing NMS threshold totally solve this?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
