### ISSUE TITLE
Can densepose and pointrend work together?

### ISSUE THREAD

**Issue by yulong314** [facebookresearch/detectron2#1463]
It would be wonderful if densepose and pointrend can  work together.  I think this way pointrend will improve the accuracy of densepose.  But is it possible? anyone ever thinking about it?

**Comment by ppwwyyxx** [comment]
It is a good idea and you're welcome to try combining them.
We have planned to make some code changes to simplify the integrating pointrend with other models.

**Comment by yulong314** [comment]
Thx, I will be waiting for "code changes"
