### ISSUE TITLE
A quick question for visualizer

### ISSUE THREAD

**Issue by amandayao0208** [facebookresearch/detectron2#1464]
Hi,
I am working on an object detection project using faster rcnn with only one category. The bounding boxes are relatively small, so I am wondering if there is any way to only show the bounding boxes without labels with visualizer.

Thanks!

**Comment by ppwwyyxx** [comment]
You can call https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances directly with boxes, to only draw boxes.
