### ISSUE TITLE
How is does ROIHeads.from_config() work. 

### ISSUE THREAD

**Issue by XiaoSong9905** [facebookresearch/detectron2#1465]
## How does ROIHeads.from_config() works ? 

1. I'm reading the `detectron2/modeling/roi_heads/roi_heads.py/class::StandardROIHeads` 's function `from_config()`. I know this function is used to initialize the ROIHeads (construct different branch & initialize them). But I want to know when is this function called? and by who? I don't see it being called in the `__init__()`.

![Screen Shot 2020-05-22 at 8 17 29 PM](https://user-images.githubusercontent.com/39639112/82717360-a14e8c00-9c69-11ea-9731-57a7a946a897.png)

2. Also, I've install detectron2 on Linux using `python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/index.html` and find the package contain slightly different `class::StandardROIHeads.__init__()` interface. Is there any branch/version that match the Linux package one? I want to make sure the code I developed can be called by the package I installed. The master branch on the github repo does not match the Linux package.

![Screen Shot 2020-05-22 at 8 19 20 PM](https://user-images.githubusercontent.com/39639112/82717349-972c8d80-9c69-11ea-8873-093ee814cc1c.png)

**Comment by ppwwyyxx** [comment]
1. https://detectron2.readthedocs.io/modules/config.html#detectron2.config.configurable
2. You can find the version you installed by `detectron2.__version__` and checkout the corresponding tag with e.g. `git checkout v0.1.3`.

**Comment by XiaoSong9905** [comment]
Thanks!
