### ISSUE TITLE
does detectron2 do data augmentation? if so, where?

### ISSUE THREAD

**Issue by Passinglight** [facebookresearch/detectron2#1466]
For a detection model using standart data (labeled as coco/vol) - does detectron2 use any data augmentation on the data?
if so, where does it happen?
my model uses rotation, scaling and brightness, so far best solution ive got is to manually augment the data and rewrite the labels

**Comment by ppwwyyxx** [comment]
Yes. It happens in the default dataloader -> `DatasetMapper`. See https://detectron2.readthedocs.io/tutorials/data_loading.html
