### ISSUE TITLE
model.pt need more gpu than model.pth

### ISSUE THREAD

**Issue by xyzSHJ** [facebookresearch/detectron2#1470]
I have got a maskrcnn torchscript model successly , but why the model.pt need more gpu than model.pth?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by xyzSHJ** [comment]
I've solved this problem，Thank you.
