### ISSUE TITLE
Converting AP values to mIoU

### ISSUE THREAD

**Issue by cclo-astri** [facebookresearch/detectron2#1475]
## ❓ How to do something using detectron2

I just completed a training with X101-FPN model and I also performed a evaluation. But I could only see AP values of each class. I wonder there exists any APIs or functions to convert AP values to mIoUs. 

## ❓ What does an API do and how to use it?

Attached is the evaluation script that I used.
[eval_py.zip](https://github.com/facebookresearch/detectron2/files/4676891/eval_py.zip)

Please help. Thanks.

**Comment by ppwwyyxx** [comment]
There isn't.
