### ISSUE TITLE
pixel std of train set in a detectron2 pretrained model

### ISSUE THREAD

**Issue by Ilbotre** [facebookresearch/detectron2#1477]
## ❓ What do you mean with MSRA models? 
I saw it  in "Config definition" section, [https://detectron2.readthedocs.io/modules/config.html#config-references](in this documentation page).
I'm using this pretrained detectron2 model:
"COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
but I do not understand if I can insert my own pixel std in _C.MODEL.PIXEL_STD=[...] or it has been alredy absorbed into its conv1 weights.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models

When using a pre-trained model from model zoo, correct results can be obtained only when the PIXEL_STD is kept unchanged.
