### ISSUE TITLE
I want to download python module 'pyautogui'

### ISSUE THREAD

**Issue by K-Rubisco** [facebookresearch/detectron2#1479]
Before question, I'm not American but Asain. So question and explanation in English may not work well.

I opened cmd, set path, upgraded pip with "python -m pip install -- upgrade pip"
And I give "pip install pyautogui" to computer but all I've take is about 20 lines ERROR message.

If I give "python", it works.
If I give "pip", it works.
(So there are no problems in path)
But If I give "pip install pyautogui", it doesn't work.

There is whole error message.
---------------------------------------

Collecting pyautogui
  Using cached PyAutoGUI-0.9.50.tar.gz (57 kB)
Collecting pymsgbox
  Using cached PyMsgBox-1.0.8.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\이채원\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Users\이채원\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\이채원\AppData\Local\Temp\tmposnm0950'
         cwd: C:\Users\이채원\AppData\Local\Temp\pip-install-0lra9dyn\pymsgbox
    Complete output (14 lines):
    running dist_info
    creating C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info
    writing C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\PKG-INFO
    writing dependency_links to C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\dependency_links.txt
    writing top-level names to C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\top_level.txt
    writing manifest file 'C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte (sitecustomize.py, line 21)
    warning: no files found matching '*.py' under directory 'pymsgbox'
    writing manifest file 'C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.egg-info\SOURCES.txt'
    creating 'C:\Users\이채원\AppData\Local\Temp\pip-modern-metadata-v6hd63_l\PyMsgBox.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\이채원\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Users\이채원\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\이채원\AppData\Local\Temp\tmposnm0950' Check the logs for full command output.
---------------------------------------------------

Earthly What is "Command errored out with exit status 1" and "wheel metadate"??
What should I do to download module?

I'm using Window, Python 3.8

**Comment by ppwwyyxx** [comment]
Not related to this project.
