### ISSUE TITLE
How to resume training from last checkpoint?

### ISSUE THREAD

**Issue by var316** [facebookresearch/detectron2#148]
Hi, 

How to resume training from a previous checkpoint on a custom dataset? 
I know that you need to change 
```
trainer.resume_or_load(resume=True)
```
Besides this, what should be the values of ```cfg.merge_from_file and cfg.MODEL.WEIGHTS ```?

Many thanks!

**Comment by ppwwyyxx** [comment]
This is answered in https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load.
If the last checkpoint exists, `cfg` will not be used so it can be anything.

**Comment by Keiku** [comment]
The code of config of resume is as follows.

https://github.com/facebookresearch/detectron2/blob/662cbb71538fc5169dc2361f97ca0e4ed2961f75/detectron2/engine/defaults.py#L48
```
    parser.add_argument(
        "--resume",
        action="store_true",
        help="whether to attempt to resume from the checkpoint directory",
    )
```

The argparse action API doesn't take anything as an argument, it simply gives a true flag. Therefore, if you execute the program as follows, resume training will be performed and the checkpoint described in last_checkpoint of specified OUTPUT_DIR will be loaded. If last_checkpoint does not exist, start normal training.

```
python tools/train_net.py \
    --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml OUTPUT_DIR output \
    --resume
```

**Comment by Ifrahmaqsood** [comment]
I am pretraining a model using visual genome dataset my training got interupted but the checkpoint is now created under "output" directory. How can I resume a training?
I'm using this code

python3.6 train_net.py --num-gpus 1 --config-file configs/R-50-grid.yaml OUTPUT_DIR output --resume

but it gives me an error and i assume i have to make "resume=true" how can i do that?

Command Line Args: Namespace(config_file='configs/R-50-grid.yaml', dist_url='tcp://127.0.0.1:50170', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['OUTPUT_DIR', 'output', '--resume'], resume=False)
Traceback (most recent call last):
File "train_net.py", line 127, in
args=(args,),
File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/launch.py", line 52, in launch
main_func(*args)
File "train_net.py", line 101, in main
cfg = setup(args)
File "train_net.py", line 94, in setup
cfg.merge_from_list(args.opts)
File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 135, in merge_from_list
return super().merge_from_list(cfg_list)
File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 226, in merge_from_list
cfg_list
File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 545, in _assert_with_logging
assert cond, msg
AssertionError: Override list has odd length: ['OUTPUT_DIR', 'output', '--resume']; it must be a list of pairs
$

**Comment by ppwwyyxx** [comment]
> python3.6 train_net.py --num-gpus 1 --config-file configs/R-50-grid.yaml OUTPUT_DIR output --resume

`--resume` has to be before "OUTPUT_DIR"

**Comment by JavierClearImageAI** [comment]
> This is answered in https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load.
> If the last checkpoint exists, `cfg` will not be used so it can be anything.

Just to clarify: "cfg.MODEL.WEIGHTS will not be used.", since it uses the last weights from the model_checkpoint. It also gets the number of iterations and other parameters from there

Some other parameters from the cfg could be changed in the cfg ... I actually changed the iterations then updated the trainer in order to train a model iteratively with multiple slices from a big dataset

**Comment by bjrne** [comment]
For anyone coming here from Google, thinking that their model is lost due to only downloading the pth files and not the "last_checkpoint":
The content of the `last_checkpoint` file (without file ending) that the detectron2 is expecting is simply the filename of the model in the `cfg.OUTPUT_DIR`, but just the model name, without the full path. Nothing more and nothing special, so you can recreate it yourself. Hope this helps.

**Comment by yunshiuan** [comment]
For whoever comes here by Google (like me), note that the checkpoint is default to save every 5000 steps. So if you abort the training before 5000, you will not be able to see any checkpoint files mentioned above. You can customize the period by modifying `solver.checkpoint_period` in the configs.

**Comment by Arnavdas** [comment]
for anyone needing a quick basic code(noobie like me) to refer from, if you have followed their official colab Notebook (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) the last checkpoint file, model weights are stored in an 'output' folder (if you have used cfg.OUTPUT_DIR). You need to get that folder path into the resume_or_load() function, this code snippet worked for me : 

```
cfg_2 = get_cfg()   # get a fresh new config
cfg_2.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg_2.DATASETS.TRAIN = ("balloon_train",)# your registered training folder
cfg_2.DATASETS.TEST = ()# you need to leave this as such even if you have no test folder, refer issue #2012
cfg_2.MODEL.ROI_HEADS.NUM_CLASSES = len(CLASS_NAMES)
cfg_2.SOLVER.IMS_PER_BATCH = 2
cfg_2.SOLVER.BASE_LR = 0.00025
cfg_2.SOLVER.MAX_ITER = max_iter  
cfg_2.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = Batch_size 

resume_dir = os.getcwd()+'/output/' # get the last resume checkpoint file path
trainer_2 = DefaultTrainer(cfg_2) 
trainer_2.resume_or_load(resume_dir)# pass the resume_dir path here 
trainer_2.train()
```

I know some of these lines above are unnecessary, so definitely do point out when and/or what is/isn't required

**Comment by Arnavdas** [comment]
@Harshita-singh-bot I think it should even if it's first time training(refer : https://detectron2.readthedocs.io/en/latest/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load), but have you filled up cfg.MODEL.WEIGHTS parameter before ?

**Comment by MLDeep414** [comment]
@https://github.com/Harshita-singh-bot
> resume = True doesnt start the training, can anyone tell me what is going wrong?

First You might have trained the model with some iterations say, 1600, now change the iteration like 1600+1000(say), update iterations to 2600 and  resume = True works.

**Comment by zhanghang1989** [comment]
```
model = build_model(cfg)
DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
```

**Comment by tan199954** [comment]
worked in google colab
![image](https://user-images.githubusercontent.com/81249766/148976286-4fa38503-0e39-46af-a3ed-1575d0b0e0c0.png)

**Comment by tan199954** [comment]
> 

Tks you

**Comment by amida47** [comment]
but what if we want to resume training and also preserve the weights of the last model, like we have model1 and we want model2 and model3 to pickup from where model1 finished while also keeping model1 weights safe for future use

**Comment by Keiku** [comment]
@litian1 Which version of detectron2 are you using? It is better to match the version when the pre-trained model was provided.
