### ISSUE TITLE
Evaluation value problem

### ISSUE THREAD

**Issue by mesakh123** [facebookresearch/detectron2#1482]
At first, thank you for your hard work to create this API. And sorry for my broke english XD

I tried to train using mask r-cnn with only 2 image data (labeled with labelme, size 224 x 224 image ), and have 1 class, both have same class. I have succeed to train it and predicted result was right.

It is my labeled image dataset :

![image](https://user-images.githubusercontent.com/28601218/83002189-55239300-a03f-11ea-8a37-4176c3279cf2.png)

And it is my prediction result:
![image](https://user-images.githubusercontent.com/28601218/83002263-6c628080-a03f-11ea-9885-0337efe12d26.png)

 But when i tried to evaluate it based on your [colab](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=U5LhISJqWXgM), It produce  "NAN" in both "APs" and "APl" like below

```
WARNING [05/27 16:37:08 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[05/27 16:37:08 d2.data.datasets.coco]: Loaded 2 images in COCO format from ./simple_dataset/annots/train.json
[05/27 16:37:08 d2.data.common]: Serializing 2 elements to byte tensors and concatenating them all ...
[05/27 16:37:08 d2.data.common]: Serialized dataset takes 0.00 MiB
[05/27 16:37:09 d2.evaluation.evaluator]: Start inference on 2 images
[05/27 16:37:10 d2.evaluation.evaluator]: Total inference time: 0:00:00.160260 (0.160260 s / img per device, on 1 devices)
[05/27 16:37:10 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.064233 s / img per device, on 1 devices)
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Saving results to ./output_evaluator_test/coco_instances_results.json
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.00s).
Accumulating evaluation results...
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl  |
|:------:|:------:|:------:|:-----:|:------:|:-----:|
| 50.495 | 50.495 | 50.495 |  nan  | 50.495 |  nan  |
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Note that some metrics cannot be computed.
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.00s).
Accumulating evaluation results...
DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.505
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl  |
|:------:|:------:|:------:|:-----:|:------:|:-----:|
| 50.495 | 50.495 | 50.495 |  nan  | 50.495 |  nan  |
[05/27 16:37:10 d2.evaluation.coco_evaluation]: Note that some metrics cannot be computed.
OrderedDict([('bbox',
              {'AP': 50.49504950495049,
               'AP50': 50.49504950495049,
               'AP75': 50.49504950495049,
               'APs': nan,
               'APm': 50.49504950495049,
               'APl': nan}),
             ('segm',
              {'AP': 50.49504950495049,
               'AP50': 50.49504950495049,
               'AP75': 50.49504950495049,
               'APs': nan,
               'APm': 50.49504950495049,
               'APl': nan})])
```

This is my code , ran in jupyter :

```
#register data and metadata catalog

register_coco_instances("mydata", {}, json_path, img_path)
mydata_metadata = MetadataCatalog.get("mydata")
dataset_dicts = DatasetCatalog.get("mydata")

# config setup

cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))

# initialize model from model zoo
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo

cfg.DATASETS.TRAIN = ("mydata",)
cfg.DATASETS.TEST = ("mydata",)
cfg.DATALOADER.NUM_WORKERS = 10  


cfg.SOLVER.IMS_PER_BATCH = 2
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   
cfg.SOLVER.BASE_LR = 0.00025

cfg.SOLVER.MAX_ITER = 10    
cfg.SOLVER.CHECKPOINT_PERIOD = 100

# we've only one class - plate
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  

ITERS_IN_ONE_EPOCH = int(100 / cfg.SOLVER.IMS_PER_BATCH)

cfg.SOLVER.MAX_ITER = (ITERS_IN_ONE_EPOCH * 100) - 1 # 12 epochs，
cfg.SOLVER.BASE_LR = 0.002
cfg.SOLVER.MOMENTUM = 0.9
cfg.SOLVER.WEIGHT_DECAY = 0.0001
cfg.SOLVER.WEIGHT_DECAY_NORM = 0.0
cfg.SOLVER.GAMMA = 0.1
cfg.SOLVER.STEPS = (700,)
cfg.SOLVER.WARMUP_FACTOR = 1.0 / 10
cfg.SOLVER.WARMUP_ITERS = 10

cfg.SOLVER.WARMUP_METHOD = "linear"
cfg.SOLVER.CHECKPOINT_PERIOD = ITERS_IN_ONE_EPOCH - 1

cfg.TEST.EVAL_PERIOD = ITERS_IN_ONE_EPOCH

#Training

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

#Prepare to predict

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.4   # set the testing threshold for this model
cfg.DATASETS.TEST = ("mydata", )
predictor = DefaultPredictor(cfg)

#Predict test data and show result

for d in random.sample(dataset_dicts, len(dataset_dicts)): 
    print(d["file_name"])
    im = cv2.imread(d["file_name"])
    im = cv2.cvtColor(im,cv2.COLOR_BGR2RGB)
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=mydata_metadata, 
                   scale=0.8
                   #instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    plt.imshow(v.get_image()[:, :, ::-1])
    plt.show()

#Evaluate
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("mydata", cfg, False, output_dir="./output_evaluator_test/")
val_loader = build_detection_test_loader(cfg, "mydata")
trainer.resume_or_load(resume=True)
inference_on_dataset(trainer.model, val_loader, evaluator)

```

## Expecting result:
I was expecting to get high AP score and without  "-1.00"  or "NAN"  value in it , but please inform me whether my expectation of result was wrong.

## Environment:
- Windows 10
- Anaconda with Jupyter notebook 
- pytorch 1.4.0
- detectron2 '0.1.1'
- python 3.6.10

Thank you for your help beforehand

**Comment by ppwwyyxx** [comment]
APs/APl means "small"/"large". If your object is neither small or large the AP is NaN.
See http://cocodataset.org/#detection-eval

**Comment by skye95git** [comment]
> At first, thank you for your hard work to create this API. And sorry for my broke english XD
> 
> I tried to train using mask r-cnn with only 2 image data (labeled with labelme, size 224 x 224 image ), and have 1 class, both have same class. I have succeed to train it and predicted result was right.
> 
> It is my labeled image dataset :
> 
> ![image](https://user-images.githubusercontent.com/28601218/83002189-55239300-a03f-11ea-8a37-4176c3279cf2.png)
> 
> And it is my prediction result:
> ![image](https://user-images.githubusercontent.com/28601218/83002263-6c628080-a03f-11ea-9885-0337efe12d26.png)
> 
> But when i tried to evaluate it based on your [colab](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=U5LhISJqWXgM), It produce "NAN" in both "APs" and "APl" like below
> 
> ```
> WARNING [05/27 16:37:08 d2.data.datasets.coco]: 
> Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.
> 
> [05/27 16:37:08 d2.data.datasets.coco]: Loaded 2 images in COCO format from ./simple_dataset/annots/train.json
> [05/27 16:37:08 d2.data.common]: Serializing 2 elements to byte tensors and concatenating them all ...
> [05/27 16:37:08 d2.data.common]: Serialized dataset takes 0.00 MiB
> [05/27 16:37:09 d2.evaluation.evaluator]: Start inference on 2 images
> [05/27 16:37:10 d2.evaluation.evaluator]: Total inference time: 0:00:00.160260 (0.160260 s / img per device, on 1 devices)
> [05/27 16:37:10 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.064233 s / img per device, on 1 devices)
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Saving results to ./output_evaluator_test/coco_instances_results.json
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluating predictions ...
> Loading and preparing results...
> DONE (t=0.00s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=0.00s).
> Accumulating evaluation results...
> DONE (t=0.00s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
> |   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl  |
> |:------:|:------:|:------:|:-----:|:------:|:-----:|
> | 50.495 | 50.495 | 50.495 |  nan  | 50.495 |  nan  |
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Note that some metrics cannot be computed.
> Loading and preparing results...
> DONE (t=0.00s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *segm*
> DONE (t=0.00s).
> Accumulating evaluation results...
> DONE (t=0.00s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.505
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.500
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
> |   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl  |
> |:------:|:------:|:------:|:-----:|:------:|:-----:|
> | 50.495 | 50.495 | 50.495 |  nan  | 50.495 |  nan  |
> [05/27 16:37:10 d2.evaluation.coco_evaluation]: Note that some metrics cannot be computed.
> OrderedDict([('bbox',
>               {'AP': 50.49504950495049,
>                'AP50': 50.49504950495049,
>                'AP75': 50.49504950495049,
>                'APs': nan,
>                'APm': 50.49504950495049,
>                'APl': nan}),
>              ('segm',
>               {'AP': 50.49504950495049,
>                'AP50': 50.49504950495049,
>                'AP75': 50.49504950495049,
>                'APs': nan,
>                'APm': 50.49504950495049,
>                'APl': nan})])
> ```
> 
> This is my code , ran in jupyter :
> 
> ```
> #register data and metadata catalog
> 
> register_coco_instances("mydata", {}, json_path, img_path)
> mydata_metadata = MetadataCatalog.get("mydata")
> dataset_dicts = DatasetCatalog.get("mydata")
> 
> # config setup
> 
> cfg = get_cfg()
> 
> cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> 
> # initialize model from model zoo
> cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> 
> cfg.DATASETS.TRAIN = ("mydata",)
> cfg.DATASETS.TEST = ("mydata",)
> cfg.DATALOADER.NUM_WORKERS = 10  
> 
> 
> cfg.SOLVER.IMS_PER_BATCH = 2
> cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   
> cfg.SOLVER.BASE_LR = 0.00025
> 
> cfg.SOLVER.MAX_ITER = 10    
> cfg.SOLVER.CHECKPOINT_PERIOD = 100
> 
> # we've only one class - plate
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  
> 
> ITERS_IN_ONE_EPOCH = int(100 / cfg.SOLVER.IMS_PER_BATCH)
> 
> cfg.SOLVER.MAX_ITER = (ITERS_IN_ONE_EPOCH * 100) - 1 # 12 epochs，
> cfg.SOLVER.BASE_LR = 0.002
> cfg.SOLVER.MOMENTUM = 0.9
> cfg.SOLVER.WEIGHT_DECAY = 0.0001
> cfg.SOLVER.WEIGHT_DECAY_NORM = 0.0
> cfg.SOLVER.GAMMA = 0.1
> cfg.SOLVER.STEPS = (700,)
> cfg.SOLVER.WARMUP_FACTOR = 1.0 / 10
> cfg.SOLVER.WARMUP_ITERS = 10
> 
> cfg.SOLVER.WARMUP_METHOD = "linear"
> cfg.SOLVER.CHECKPOINT_PERIOD = ITERS_IN_ONE_EPOCH - 1
> 
> cfg.TEST.EVAL_PERIOD = ITERS_IN_ONE_EPOCH
> 
> #Training
> 
> os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> trainer = DefaultTrainer(cfg) 
> trainer.resume_or_load(resume=False)
> trainer.train()
> 
> #Prepare to predict
> 
> cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
> cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.4   # set the testing threshold for this model
> cfg.DATASETS.TEST = ("mydata", )
> predictor = DefaultPredictor(cfg)
> 
> #Predict test data and show result
> 
> for d in random.sample(dataset_dicts, len(dataset_dicts)): 
>     print(d["file_name"])
>     im = cv2.imread(d["file_name"])
>     im = cv2.cvtColor(im,cv2.COLOR_BGR2RGB)
>     outputs = predictor(im)
>     v = Visualizer(im[:, :, ::-1],
>                    metadata=mydata_metadata, 
>                    scale=0.8
>                    #instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
>     )
>     v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
>     plt.imshow(v.get_image()[:, :, ::-1])
>     plt.show()
> 
> #Evaluate
> from detectron2.evaluation import COCOEvaluator, inference_on_dataset
> from detectron2.data import build_detection_test_loader
> evaluator = COCOEvaluator("mydata", cfg, False, output_dir="./output_evaluator_test/")
> val_loader = build_detection_test_loader(cfg, "mydata")
> trainer.resume_or_load(resume=True)
> inference_on_dataset(trainer.model, val_loader, evaluator)
> ```
> 
> ## Expecting result:
> I was expecting to get high AP score and without "-1.00" or "NAN" value in it , but please inform me whether my expectation of result was wrong.
> 
> ## Environment:
> * Windows 10
> * Anaconda with Jupyter notebook
> * pytorch 1.4.0
> * detectron2 '0.1.1'
> * python 3.6.10
> 
> Thank you for your help beforehand
I also have dataset labeled with labelme, get the json files. What format conversion do you need to do before training? What command did you run to get the mAP? I just want to evaluate the pre-training model on my own dataset. What should I do?
