### ISSUE TITLE
Why is AP score increasing when lowering ".MODEL.ROI_HEADS.SCORE_THRESH_TEST"

### ISSUE THREAD

**Issue by philthestone** [facebookresearch/detectron2#1484]
I have problems understanding why the Average Precision (AP) score (of the COCO metrics) is gradually increasing when lowering the threshold value: "_C.MODEL.ROI_HEADS.SCORE_THRESH_TEST" (https://detectron2.readthedocs.io/modules/config.html).  

Is the intuition drawn in the image correct?

![MAP](https://user-images.githubusercontent.com/61734422/83072760-9fbd0380-a06f-11ea-9b20-03136d919fcc.jpg)

For clarification: When setting the threshold to 0.9, the AP is defined by the yellow area under the "Precision Recall Curve", when setting the the threshold to 0.5 it is defined by the yellow+blue area and when setting the threshold to 0.0 its defined by the yellow, blue and red area. Is this conceputally correct?

**Comment by ppwwyyxx** [comment]
The threshold is not precision or recall. It is for scores of results and explained in https://detectron2.readthedocs.io/modules/config.html#config-references
