### ISSUE TITLE
How to get coordinate data in instant segment specific classes ?

### ISSUE THREAD

**Issue by charlescho64** [facebookresearch/detectron2#1486]
Hello, 

This project is fantastic.
I have run detectron2-pointrend project in colab env and got the good result. 
I try to show coordiantion data of instant segmentation for instants and got like below only for instant segmentation. For instants, there are no problem except "outputs['instances'].pred_masks"
---------------------------------------------------
tensor([[[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]], device='cuda:0') 
---------------------------------------------------

I also read same issue(Is it possible to instant segment specific classes and save masks? #48) , but  I didn't solve.

anyboy help me, how to get coordination data for instant segmentation of object?

**Comment by ppwwyyxx** [comment]
The output format is explained in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format. You can process the outputs further but they are unrelated to detectron2.
