### ISSUE TITLE
performance of AsyncPredictor in predictor.py is not expected

### ISSUE THREAD

**Issue by tsing90** [facebookresearch/detectron2#1488]
I noticed that there is a function in `demo/predictor.py` called [`AsyncPredictor`](https://github.com/facebookresearch/detectron2/blob/master/demo/predictor.py#L132), which is supposed to support multiple GPU.

I tried that by modifying the line in [`demo/demo.py`](https://github.com/facebookresearch/detectron2/blob/master/demo/demo.py#L79) as: `demo = VisualizationDemo(cfg, parrallel=True)`. 

The command I ran was as below:
`python detectron2/demo/demo.py --config-file detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --video-input data/my_video.mov --confidence-threshold 0.6 --output data/my_video_out.mp4 --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl`

It worked, which meant all GPUs were loaded with the model and could do the inference as well. The issue is: the performance is not improved as expected. In my case, I used 4 GPUs, but the speed was only increased by around 50% compared to 1 gpu (it was expected to be around 300% speed-up). From the utilization of GPU, it seemed like the inference on 4 gpus is serialized instead of paralleled (switch from one GPU to another).

Have you (authors) tested this function and seen a similar issue? thanks

**Comment by ppwwyyxx** [comment]
That's expected since drawing the visualization is slow. It's just part of `demo/` and is not meant to be very optimized.

**Comment by vanpersie32** [comment]
@ppwwyyxx With the paralle=True, the model doesn't still inference in parallel, because there is only one image in the queue.
