### ISSUE TITLE
No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.

### ISSUE THREAD

**Issue by IsaacPatole** [facebookresearch/detectron2#1490]
I need to way to stop training before it starts overfitting, so I tried adding data into cfg.DATASETS.TEST which would help me see comparison of traning and vaidation/test on the tensorboard, but I am getting the above error, how can I change my code to know when my model starts overfitting and how can I see a comparitive visualization of train/test in tensorboard?

Also, in order to use pretrained weights on previously trained custom dataset, shall I pass the generated .pth file into cfg.MODEL.WEIGHTS?

This is script I am using for training...

from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("train_6500",)
cfg.DATASETS.TEST = ("test_500",)   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = 10000   # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output2/'

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

**Comment by ppwwyyxx** [comment]
As the error says, 
> No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method. 

The [tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) and [example training script](https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py) have examples showing how to create evaluator for evaluation.
