### ISSUE TITLE
Disable RandomFlip() from TransformGens

### ISSUE THREAD

**Issue by domiurg** [facebookresearch/detectron2#1493]
Hi, I'm trying to train a model on data where random flipping does not make sense. As far as I can tell, it's applied by default at training, as indicated by this line from training output:

`[05/28 11:08:50 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]`

I can't seem to find a corresponding flag in configs, so asking here for assistance.

**Comment by ppwwyyxx** [comment]
It cannot be disabled with config. https://detectron2.readthedocs.io/tutorials/data_loading.html shows how to implement custom data loader.

**Comment by domiurg** [comment]
Got it, thanks
