### ISSUE TITLE
Don't find rpn_output.py file for the configuration setting 

### ISSUE THREAD

**Issue by XiaoSong9905** [facebookresearch/detectron2#1499]
In the configuration setting, it says 
```python
# NOTE: When FPN is used, the meaning of this config is different from Detectron1.
# It means per-batch topk in Detectron1, but per-image topk here.
# See "modeling/rpn/rpn_outputs.py" for details.
_C.MODEL.RPN.POST_NMS_TOPK_TRAIN = 2000
_C.MODEL.RPN.POST_NMS_TOPK_TEST = 1000
```

But I can't find the `modeling/rpn/rpn_outputs.py` file. Is it moved to some new files/classes?

**Comment by TengFeiHan0** [comment]
yes, new detectron2 merged` rpn_outputs.py` into the new [rpn.py](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/proposal_generator/rpn.py#L256)

**Comment by ppwwyyxx** [comment]
fixed! thanks for reporting
