### ISSUE TITLE
Draw binary mask sometimes fail

### ISSUE THREAD

**Issue by alanotmt** [facebookresearch/detectron2#1505]
data_f = 'A.bmp'
        im = cv2.imread(data_f)
        outputs = predictor(im)
        
        
        mask=outputs["instances"].get("pred_masks")
        mask=mask.view(480,480)
        mask=mask.to("cpu")
        mask=mask.numpy()
        
        v = Visualizer(im[:, :, ::-1],
                       metadata=oct_val,
                       scale=1.0,
                       instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
                       )
        #v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
        v = v.draw_binary_mask(mask,color='red',alpha=0)
        img = v.get_image()[:, :, ::-1]
        data_f=data_f[:-4]

        
        cv2.imwrite(data_f+'out.jpg', img)

ValueError:                             

---> 59         v = v.draw_binary_mask(mask,color='red',alpha=0)

~/detectron2-master/detectron2/utils/visualizer.py in draw_binary_mask(self, binary_mask, color, 
--> 970             rgba[:, :, :3] = color

**ValueError: could not convert string to float: 'red'**

When i change to  B.bmp with no error.
A.bmp and B bmp are retina images and same size.

if i change  color = 'red' to  = [1,0,0]  will no error, but output image have no mask in A.bmp,
B.bmp have mask.

i try bmp to png or jpg and output also the same.

i check the predict mask and it have True in binary. should be output the 'True' value, but i got nothing in A.bmp
why and how can i fix it?

**Comment by ppwwyyxx** [comment]
Using "red" should work with the latest commits.

No masks are visible: either the file you provided does not contain visible mask, or its mask is too small to reach the default area threshold (4096) documented at https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.draw_binary_mask.
The default threshold is not very reasonable and we'll change it to 0 instead.
