### ISSUE TITLE
Drone Object Detection

### ISSUE THREAD

**Issue by deeplearninggobrrr** [facebookresearch/detectron2#1506]
## ❓ How to do something using detectron2

I am trying to perform object detection on images taken from a drone. I tried different models from model zoo and the Resnest 50,101 and 200. 
For all them I get very bad results. (AP50 below 1)
The size of training images is [960x540] 
The size of eval set image is [1920x1080]

Here is my training config :

`
    cfg.DATALOADER.NUM_WORKERS = 10

    cfg.SOLVER.IMS_PER_BATCH = 6

    cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR

    cfg.SOLVER.MAX_ITER = 10000   

    cfg.SOLVER.WARMUP_ITERS = 100

    #cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512 

    cfg.MODEL.RPN.IN_FEATURES = ['p2', 'p2', 'p3', 'p4', 'p5', 'p6']    

    cfg.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.25, 0.5, 1.0, 1.5,2.0,4.0]]    

    cfg.MODEL.ANCHOR_GENERATOR.SIZES = [ [8], [16], [32], [64], [128],[256]]

    cfg.MODEL.PIXEL_MEAN = [58.33, 58.33, 58.33] 

    cfg.MODEL.PIXEL_STD = [1.0, 1.0, 1.0]

    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256

    cfg.MODEL.ROI_HEADS.IOU_THRESHOLDS = [0.5] # Intersection over union threshold

    cfg.MODEL.RPN.POST_NMS_TOPK_TEST = 1000 

    cfg.MODEL.RPN.PRE_NMS_TOPK_TEST = 1000

    cfg.TEST.DETECTIONS_PER_IMAGE = 500

`

Environemnt
`[05/31 18:37:18 detectron2]: Environment info:
------------------------  ----------------------------------------------------------------------------------
sys.platform              linux
Python                    3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:43:46) [GCC 7.3.0]
numpy                     1.18.3
detectron2                0.1.1 @/usr/home/visdrone/detectron2-ResNeSt/detectron2
detectron2 compiler       GCC 5.5
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.0+cu101 @/usr/home/anaconda3/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2                 GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-10.0
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    5.0.0
torchvision               0.6.0+cu101 @/usr/home/anaconda3/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.1
------------------------  ----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

`

Any suggestions on how to improve my results?
TIA

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
