### ISSUE TITLE
How to load the trained weight or model trained by the custom data to predict new data

### ISSUE THREAD

**Issue by tianke0711** [facebookresearch/detectron2#1507]
Hi I have followed the https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=h9tECBQCvMv3

tutorial to train mode with custom data using MaskRCNN.
The next step I want to use the trained weight to predict the new image data.

Could you tell me how to save and load the trained the weights of model to predict new image data, please!

**Comment by ppwwyyxx** [comment]
It's in https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=U5LhISJqWXgM
