### ISSUE TITLE
Try to release GPU memory during the inference

### ISSUE THREAD

**Issue by zhangguangxun** [facebookresearch/detectron2#1508]
Hello, I am using detectron2 to get the bounding boxes, feature maps, and predicate labels as the input information for my video caption model, However, when I get all the Infos from one frame, It will cost about 1GB GPU memory. So during the inference, the memory cost is increasing until it OOM. I was wondering if there are some ways I can release that memory? I had tried to delete the variables as well as tried to release the memory by the defaulted PyTorch command torch.cuda.empty_cache() but all are helpless.

**Comment by ppwwyyxx** [comment]
The memory should not increase indefinitely. 

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by zhangguangxun** [comment]
Thanks for your quick reply.
In fact, it is not unexpected behavior, it is normal to consume nearly 1GB GPU memory to predict one picture and I didn't change any code.
Firstly, I cut my video into several frames and use DefaultPredictor to get bounding boxes and labels, and then, use the way from issue #5 https://github.com/airsplay/py-bottom-up-attention to get the feature map from the bbxs. 
My question is that when I finish the inference from the first frame, after getting all the information I  need, the intermediate variables are still in my GPU memory. and after I deal with my second frame,(it is actually another inference process), the GPU memory will be used as 2GB, and so on.
But after inference each frame, the intermediate variables are actually useless, so I want to delete them to release the memory, I am wondering if there is some API so that I can complete it.
In the end, thanks for your gorgeous code.

**Comment by ppwwyyxx** [comment]
> after I deal with my second frame,(it is actually another inference process), the GPU memory will be used as 2GB, and so on

you seem to suggest that it will take 10GB after 10 frames - this is an unexpected behavior, which requires the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by AlexandreLeboucher** [comment]
Same problem here. Memory explodes after several inference processes. Any luck? Thanks!
