### ISSUE TITLE
It seems Detectron2 may not use the mean or standard deviation when traning custom dataset？ 

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#1510]
## ❓ It seems Detectron2 may not use the mean or standard deviation when traning custom dataset？ 

In the task of COCO detection, the means or standard deviations of the pixels would always be considered in many implementations.
So I want to know whether Detectron2 compute the means or standard deviations of the custom dataset?

Any answer or idea will be appreciated!

**Comment by ppwwyyxx** [comment]
You can specify mean / std to use, with `cfg.MODEL.PIXEL_{MEAN,STD}`.

**Comment by songyuc** [comment]
Hi, @ppwwyyxx , there is another question whether Detectron2 provide the APIs for calculating the mean or standard deviations of the custom dataset?

**Comment by ppwwyyxx** [comment]
there is no such APIs

**Comment by SlowMonk** [comment]
how to calculate the mean and the variance?

**Comment by petoor** [comment]
mean = np.mean(img, axis=(0, 1))
std = np.std(img, axis=(0, 1))
or if your image is already a numpy array
img.mean(axis=(0, 1))
img.std(axis=(0, 1))
