### ISSUE TITLE
why the background pixel are ignored when training model in panoptic segmentation?

### ISSUE THREAD

**Issue by vanpersie32** [facebookresearch/detectron2#1511]
I want to ask a question why the background pixel are ignored when training model in panoptic segmentation. According to [link1](https://github.com/facebookresearch/detectron2/blob/master/datasets/prepare_panoptic_fpn.py#L55), the code maps background pixel whose category is 0 to 255. However according to [link2](https://github.com/facebookresearch/detectron2/blob/9c91580b80b06d0062e2dd123e42085efcde49b5/detectron2/config/defaults.py#L381), 255 is ignore in semantic segmentation. I want to ask why the code don't ignore background pixel? @ppwwyyxx

**Comment by ppwwyyxx** [comment]
> why the code don't ignore background pixel

the code ignores background pixels, because

> the code maps background pixel whose category is 0 to 255. However according to link2, 255 is ignore in semantic segmentation
