### ISSUE TITLE
Resize sliding window

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#1512]
Hey,

I need to detect objects with TensorMask, which are quite close to each other. If I divide my input image (size: w:4928, h: 3264) into smaller subimages, detection works fine. If I try to detect these objects on the full image size, results are quite bad. Is there a way to give the sliding windows in TensorMask a new size, so that they can detect better?

Thank you !

**Comment by ppwwyyxx** [comment]
I'm not sure what that means but I don't think there is such a feature. You can probably resize input yourself

**Comment by Bamil** [comment]
Thanks for your fast answer !

I'll try to resize the input.

Thanks a lot
