### ISSUE TITLE
Make random flipping configurable

### ISSUE THREAD

**Issue by nikste** [facebookresearch/detectron2#1513]
## 🚀 Feature
it seems random flipping is hardcoded as a preprocessing step.
https://github.com/facebookresearch/detectron2/blob/9714aa4ab835dd64d45610e175464b93fb18fb43/detectron2/data/detection_utils.py#L516

This is not always a good idea (think traffic signs go left or go right which are symmetric but different).
Would be nice to have an easy way to disable this.

## Motivation & Examples
Symmetric but different objects (Traffic signs left, right arrow)

A config handle saying `RANDOM_FLIP` either `True` or `False`
(or even a list of preprocessing steps)

**Comment by hiyyg** [comment]
Maybe `RANDOM_FLIP_TYPE` with options: `horizontal`, `vertical`, `none` is more suitable, since there users may also want to use vertical flip in some cases.

**Comment by jorgeuliana1** [comment]
Is there any prediction for the solution of this issue? I believe it is pretty important.

**Comment by ppwwyyxx** [comment]
closed by https://github.com/facebookresearch/detectron2/pull/1976
