### ISSUE TITLE
Transfer learning with the COCO weights

### ISSUE THREAD

**Issue by spraharaj3** [facebookresearch/detectron2#1515]
Hi there! I'm training Detectron2 to recognize some custom objects (a guitar, tennis racquets, in COCO format) , and I want these classes to be added to the existing ones in the coco dataset for object detection from the model-zoo. 

So my options are to currently add the images and annotations to the existing COCO dataset and retrain from scratch (Difficult and laborious).

Is there a way to add the weights the model has learnt for custom object detection to the existing pkl file for the COCO dataset so that I'm just adding my custom labels for classification in addition to existing COCO labels?

Thanks!

**Comment by ppwwyyxx** [comment]
> The model files can be arbitrarily manipulated using torch.{load,save} for .pth files or pickle.{dump,load} for .pkl files.

From https://detectron2.readthedocs.io/tutorials/models.html
