### ISSUE TITLE
Potential speed up of paste_masks_in_image (detectron2.layers.mask_ops)

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#1517]
## 🚀 Feature
Perform the thresholding before the pasting in ```paste_masks_in_image``` (```detectron2.layers.mask_ops```).

## Motivation & Examples
I think this might speed up the function, because as it is right now, the thresholding is carried out on an unnecessarily large image, which may contain mostly zeros. Of course, I might be mistaken, and things like the datatypes (float, bool or uint8) of the tensors have a stronger impact on the computational speed (especially on a GPU) than their size.

**Comment by ppwwyyxx** [comment]
> Perform the thresholding before the pasting 

I suppose it will produce less accurate result.

**Comment by maxfrei750** [comment]
> I suppose it will produce less accurate result.

Makes sense, but only if the pasting and resizing of the masks is done in one go. So naively, the best order of operations would be:
1. Resize
2. Threshold
3. Paste

I assume that there is a reason that it is not done that way. Would you care to elaborate?
Thanks.

**Comment by ppwwyyxx** [comment]
There is no traditional "resize" step in the function. The closest thing to "resize" might be the "skip_empty" option which turns out to be useful only for CPU. And when skip_empty is used, thresholding is not applied on the full mask.

If you find faster implementations on CPU or GPU feel free to send PRs.

**Comment by maxfrei750** [comment]
Thanks for elaborating.
