### ISSUE TITLE
TEST EVAL_PERIOD only works with values of 0 and PeriodicWriter._period multiples

### ISSUE THREAD

**Issue by RaymondKirk** [facebookresearch/detectron2#152]
Reguarding the config parameter:

```yaml
TEST:
  EVAL_PERIOD: 0
```

If `EVAL_PERIOD` is set to 0 or a multiple of `PeriodicWriter._period` the desired behaviour of logging to tensor_board/the periodic writers is fine. If any other number is used the evaluation will run but will not be logged to tensorboard.

**Comment by ppwwyyxx** [comment]
That does seem a bit odd, but this behavior is expected. The metrics is computed and gone if no writer is active at that time.

**Comment by RaymondKirk** [comment]
Agreed, when setting the eval period you would expect the results to be saved however the user should set an apropriate `PeriodicWriter._period` to enable this behaviour. Feel free to close the issue.
