### ISSUE TITLE
TTA Usage

### ISSUE THREAD

**Issue by SiftingSands** [facebookresearch/detectron2#1520]
## ❓ How to do something using detectron2

I wanted to try out test-time augmentation (TTA), and it looks like there's a config setting for enable it. `cfg.TEST.AUG.ENABLED = True`

However, I do not see where that boolean is used in the codebase (I tried 'grep -r' various names). So, I'm uncertain if DefaultPredictor is compatible, if I need to wrap the model with the GeneralizedRCNNWithTTA class, or do I need to also to add 'WithTTA' to  `META_ARCHITECTURE: GeneralizedRCNN` in the config?

I tried inference with DefaultPredictor, and it doesn't seem to be calling the TTA functions (I added a debug point, and it's never touched).

**Comment by ppwwyyxx** [comment]
It's used in `tools/train_net.py`. You can also use the `GeneralizedRCNNWithTTA` class manually.

`DefaultPredictor` is for demo purposes and is not meant to include too many features.

**Comment by SiftingSands** [comment]
Got it, followed that script and just wrapped the model `GeneralizedRCNNWithTTA(cfg, model)` Thanks for the fast response!

**Comment by sunny0315** [comment]
> Got it, followed that script and just wrapped the model `GeneralizedRCNNWithTTA(cfg, model)` Thanks for the fast response!

I foud the input of the TTA is the "dataset_dict". So,the TTA is only for the labeled data? can not apply to infer any image?

**Comment by RomRoc** [comment]
Hi @SiftingSands ,
I developed a notebook to train models with custom coco dataset, based on [Getting started colab notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5)

For what I read DefaultPredictor doesn't peform TTA.

How should I modify notebook to add TTA?
Thanks

**Comment by gizemtanriver** [comment]
Hi, 

I am training MaskRCNN with R_50_FPN_3x. I added test_with_TTA class method to my trainer, which creates a model with GeneralizedRCNNWithTTA. Then I enable TTA by setting cfg.TEST.AUG.ENABLED = True, and call my trainer as shown below. I get TTA results at the end but they are far worse than my results without TTA (without TTA: AP50=83, with TTA: AP50=55). Why is this happenning? Thank you!

```
class CocoTrainer(DefaultTrainer):
  @classmethod
  def build_evaluator(cls, cfg, dataset_name, output_folder=None):
      if output_folder is None:
          output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
          os.makedirs(output_folder, exist_ok=True)
      # distributed=True
      return COCOEvaluator(dataset_name, cfg, True, output_folder)

  def build_hooks(self):
      hooks = super().build_hooks()
      hooks.insert(-1, LossEvalHook(
          self.cfg.TEST.EVAL_PERIOD, 
          self.model,
          build_detection_test_loader(
              self.cfg,
              self.cfg.DATASETS.TEST[0],
              DatasetMapper(self.cfg, is_train=True,)
          )
      ))
      return hooks

  @classmethod
  def test_with_TTA(cls, cfg, model):
      logger = logging.getLogger("detectron2.trainer")
      # In the end of training, run an evaluation with TTA
      # Only support some R-CNN models.
      logger.info("Running inference with test-time augmentation ...")
      model = GeneralizedRCNNWithTTA(cfg, model)
      evaluators = [
          cls.build_evaluator(
              cfg, name, output_folder=os.path.join(
                  cfg.OUTPUT_DIR, "inference_TTA")
          )
          for name in cfg.DATASETS.TEST
      ]
      res = cls.test(cfg, model, evaluators)
      res = OrderedDict({k + "_TTA": v for k, v in res.items()})
      return res
```

```
trainer = CocoTrainer(cfg)
trainer.resume_or_load(resume=False)
if cfg.TEST.AUG.ENABLED:
      trainer.register_hooks([hooks.EvalHook(0, lambda: trainer.test_with_TTA(cfg, trainer.model))] )
trainer.train()
```
