### ISSUE TITLE
How to visualize more proposals on tensorboard?

### ISSUE THREAD

**Issue by AlexFridman** [facebookresearch/detectron2#1521]
## ❓ How to visualize more proposals on tensorboard?

Describe what you want to do, including:
1. during training on tensorboard at image tab is see only a few proposals (< 5)
2. during inference setting SCORE_THRESH_TEST: 0.01 gives me a lot of detected objects (true positives)

So, how to see all detected objects on the image during training?
Thank you!

**Comment by ppwwyyxx** [comment]
> how to see all detected objects on the image during training

The R-CNN model does not detect objects during training. If you want you might call `model.eval(); model.forward` manually during training.
