### ISSUE TITLE
gt_mask_logits gives me more than just 0 or 1. 0.5 is included therein.

### ISSUE THREAD

**Issue by Armin199608** [facebookresearch/detectron2#1523]
I think there is a problem here, please forgive me if I have made a mistake.
point_head.py     line 71
        gt_mask_logits = cat(gt_mask_logits)
I think the value of gt_mask_logits can only be 1 or 0.
But I get a decimal somewhere between zero and one.
I think the above sample caused this situation.

**Comment by ppwwyyxx** [comment]
`gt_mask_logits` in point_head.py are expected to be anywhere between 0 and 1. If there is anything unexpected, please follow the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
