### ISSUE TITLE
Implement pre_trained RCNN in demo.py in COCO-Detection did not get result

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1525]
Dear all,

I've edit the file demo.py and change my command to terminal to python3 demo.py --config-file ../configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml\
  --input input1.jpg \
  --opts MODEL.DEVICE cpu MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl

but the output image is the same as before, it seems that no move is made.

Could anyone help me where to edit the demo.py or predictor.py to get my expected result?

Thanks a lot!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by qustions** [comment]
@ppwwyyxx  when we are trying to run `python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input test.jpg` we are not getting any prediction on the image I mean it's not drawing may be something we are missing I have seen the same issue more than 5 and your just giving the answer as unrelated or follow [https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-demo-with-pre-trained-models](https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-demo-with-pre-trained-models) but we are following the same thing still the same issue

**Comment by ppwwyyxx** [comment]
The instructions say:
```
--opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

A question is labeled invalid if the necessary details are not given after being asked for a few days.
