### ISSUE TITLE
Unexpected result when running faster RCNN X101 in demo.py

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1526]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what code you wrote or what changes you made (`git diff`)
```
<put diff or code here>
python3 demo.py --config-file ../configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml\
  --input input1.jpg \
  --opts MODEL.DEVICE cpu MODEL.WEIGHTS detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl
```
2. what exact command you run: python3 demo.py --config-file ../configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml\
  --input input1.jpg \
  --opts MODEL.DEVICE cpu MODEL.WEIGHTS detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl
3. what you observed (including __full logs__): Same photo as before
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
   See https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.
the detections
If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
The model you're using is from https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models and is not an object detection model.
You can take models from tables below such as https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-object-detection-baselines
