### ISSUE TITLE
How to run a pre_trained model in multiple inputs

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1527]
Dear all,

My computer does not have a GPU. I have a file of images that I need to process them using Faster RCNN model. Could you tell me do I have any way to edit the demo.py for running a file of images?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
demo.py already can run on image files: https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-demo-with-pre-trained-models
