### ISSUE TITLE
if EVAL  in the middle of the training,  CUDA Memory Error

### ISSUE THREAD

**Issue by a13668349935** [facebookresearch/detectron2#153]
i run detectron2 on the cityspace semantic task, if i set EVAL_PERIOD=0,the eval will run after training, and it works fine . but when i set EVAL_PERIOD=1000  or others less than the SOLVER.MAX_ITER ,i get the CUDA out of memory  eror.

**Comment by ppwwyyxx** [comment]
What you described doesn't sound like an issue to me. You need more memory to run it then.

**Comment by a13668349935** [comment]
i found the error,because of my image size is very big，i crop the image  and  it‘s works now
