### ISSUE TITLE
No Detection Output seen after running

### ISSUE THREAD

**Issue by deeplearner93** [facebookresearch/detectron2#1530]
I run the following line of code in the terminal:
python3 demo.py --config-file ../configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml --input image.jpg

I get the input image without any detections or bounding box.

**Comment by ppwwyyxx** [comment]
Please follow the command in instructions https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-demo-with-pre-trained-models

**Comment by deeplearner93** [comment]
@ppwwyyxx I think that is exactly my question. The instructions followed is not giving the desired output. I would need support on something more other than the instructions which is a little unclear.  And I really respect the way you are answering the queries. Thank you.

**Comment by ppwwyyxx** [comment]
The instruction requires picking and using a model file:

> Pick a model and its config file from model zoo, for example, mask_rcnn_R_50_FPN_3x.yaml.
We provide demo.py that is able to run builtin standard models. Run it with:
cd demo/
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
  [--other-options]
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
The configs are made for training, therefore we need to specify MODEL.WEIGHTS to a model from model zoo for evaluation.

**Comment by qustions** [comment]
@deeplearner93  did you solve that issue because I am also not getting the prediction  on the output image
