### ISSUE TITLE
Filtering out COCO Instance.

### ISSUE THREAD

**Issue by TemitopeOladokun** [facebookresearch/detectron2#1531]
**Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

Loaded 488 images in COCO format from /content/drive/My Drive/train_folder/test_result.json

Filtered out 3677 instances without valid segmentation. There might be issues in your dataset generation process.**

I got this message while training with a Custom dataset. Please @ppwwyyxx, what am I doing wrong and how can this be solved?

**Comment by ppwwyyxx** [comment]
As the log says there are 3677 instances in the dataset without valid segmentation.
You can check http://cocodataset.org/#download to see what coco dataset should look like

**Comment by ebrahim31** [comment]
Hello @ppwwyyxx 

When I run my code for testing (shown below):

evaluator = COCOEvaluator("MyData", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "MyData")
print(inference_on_dataset(predictor.model, val_loader, evaluator))

I receive a warning like below:

"Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you."

and then an error as below:

 File "/home/administrator/anaconda3/envs/Detectron/lib/python3.6/site-packages/detectron2/evaluation/coco_evaluation.py", line 179, in _eval_predictions
    category_id
AssertionError: A prediction has category_id=34, which is not available in the dataset.

It would be great if you could help with this @ppwwyyxx . Thank you

**Comment by morganOliveira2018** [comment]
@ebrahim31 Can you solve this problem? 
```
WARNING [03/09 14:27:55 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for `you.
```

**Comment by deepakksingh** [comment]
@morganOliveira2018 That is a warning if your category ids are not in that range in your coco JSON file.

**Comment by ebrahim31** [comment]
@morganOliveira2018 The issue I had was that I did not import the entire model. I added the line below which fixed the issue.

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo

**Comment by morganOliveira2018** [comment]
@ebrahim31 
1. My code is like this where it contains this line that you said:

```
# Teste do Backbone - mask-R_50_FPN_3x 
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("fishesSegmentation_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 100
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 38

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

2. I have to change: **model_zoo.get_config_file** -> **model_zoo.get_checkpoint_url** @ebrahim31?

**Comment by morganOliveira2018** [comment]
@deepakksingh Could you help me with this issue? How can I fix it in the case?

**Comment by deepakksingh** [comment]
Hello @morganOliveira2018 ,
I'm still confused as to what the real issue is.
If you are worried about the warning, then you can remap the category ids to start from 1-N by iterating over the annotations and categories in the JSON file.
Let us know if that doesn't fix the issue.

**Comment by morganOliveira2018** [comment]
@deepakksingh Would you have an email for me to direct access to the files and the code for you to better understand the problem?

**Comment by morganOliveira2018** [comment]
@deepakksingh How do i remap the category ids to start from 1-N by iterating over the annotations and categories in the JSON file?

**Comment by deepakksingh** [comment]
I can share the code to externally remap category ids of COCO json file. :)

**Comment by ebrahim31** [comment]
@morganOliveira2018 So my images are located in a folder along with the JSON file.  
** 
from detectron2.data.datasets import register_coco_instances
register_coco_instances("NAME", {}, "./data/merged.json", "./data/")
**
By the way, do you have these lines in your code?

**Comment by morganOliveira2018** [comment]
@ebrahim31 1. Code:
````
from detectron2.data.datasets import register_coco_instances

for d in ["train", "test"]:
    register_coco_instances(f"fishesSegmentation_{d}", {}, f"/content/drive/MyDrive/dataset-fishes/{d}.json", f"/content/drive/MyDrive/dataset-fishes/{d}")
````
2. In short, in the dataset-fishes folder there are 2 folders: (1) train and (2) test and in the dataset-fishes folder there are two files train.json and test.json.

**Comment by zhangmin4215** [comment]
if your question like this : Filtered out xxx instances without valid segmentation. There might be issues in your dataset generation process.
you can do these things:
1. check your coco train.json first, maybe your "segmentation".value format is wrong.
2. FCOS does both detection and segmentation by default, if you only want detection, do some modification in default.py to prevent segmentation.
