### ISSUE TITLE
What does group mean in deformable convolution?

### ISSUE THREAD

**Issue by shikunyu8** [facebookresearch/detectron2#1532]
There is a parameter DEFORM_NUM_GROUPS for deformable convolution. I'm not sure what does group mean in deformable convolution (https://arxiv.org/pdf/1703.06211.pdf). Is it related to group convolution?

If I want to use ResNext-101 model with NUM_GROUPS of 32, should I set DEFORM_NUM_GROUPS as 32 as well?

Thanks!

**Comment by ppwwyyxx** [comment]
See https://github.com/msracver/Deformable-ConvNets/issues/268 for the original author's explanation. 

This hyperparameter does not appear very useful from our experience and we may want to remove it.
