### ISSUE TITLE
How to run pre_trained model to a collection of images and extract the result in JSON file

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1533]
Dear all, 

I want to create a training set of data based on the result of pre_trained model for training purpose. Could you tell me how to do that? As in the training set Ballon, it has a data file accompanied (json file). I also want to create a json file like this based on the pre_trained model.

Thanks in advance!

**Comment by ppwwyyxx** [comment]
The format of model output is described in https://detectron2.readthedocs.io/tutorials/models.html and the format of data is described in https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by Long-Xuan-Do** [comment]
> The format of model output is described in https://detectron2.readthedocs.io/tutorials/models.html and the format of data is described in https://detectron2.readthedocs.io/tutorials/datasets.html

Yes I understand the format but my question is that I want to convert the output to a Json file similar to via_region_data.json in ballon folder.

For example, I have the output from COCO-Detection likes this:

{'instances': Instances(num_instances=2, image_height=1824, image_width=2736, fields=[pred_boxes: Boxes(tensor([[ 238.3251,  496.2638, 2028.9203, 1367.0105],
        [ 795.4240,  765.0603, 2060.3545, 1309.7096]])), scores: tensor([0.9640, 0.7664]), pred_classes: tensor([0, 0])])}

Could you tell me a way to convert to the similar Json file?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
Eventually you need the format in  https://detectron2.readthedocs.io/tutorials/datasets.html in order to train a model, so there is no need to convert to the format of "via_region_data.json".
In fact this is just a random toy dataset I found online and I do not know the specification of this json file.

**Comment by Long-Xuan-Do** [comment]
So could you tell me how can I use this output to build a matrix score AP and AP50?

Thank you so much!
