### ISSUE TITLE
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/kaggle/input/detectron2/fvcore-0.1.dev200505-py3-none-any.whl'  [0m

### ISSUE THREAD

**Issue by harsh2ai** [facebookresearch/detectron2#1535]
while commiting a new version of my kaggle notebook I always get this error in the 

```


# !pip install detectron2==0.1.2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
!pip install ../input/detectron2/pycocotools-2.0.0-cp37-cp37m-linux_x86_64.whl
!pip install ../input/detectron"2"/torch-1.5.0cu101-cp37-cp37m-linux_x86_64.whl
!pip install ../input/detectron2/torchvision-0.6.0cu101-cp37-cp37m-linux_x86_64.whl
!pip install ../input/detectron2/yacs-0.1.7-py3-none-any.whl
!pip install ../input/detectron2/fvcore-0.1.dev200505-py3-none-any.whl
!pip install ../input/detectron2/detectron2-0.1.2cu101-cp37-cp37m-linux_x86_64.whl

```

and this results in all my cells throwing up certain errors how do I resolve them?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by karanjakhar** [comment]
It is indicating that fvcore-0.1.dev200505-py3-none-any.whl is not present. Please check the datasets you added to Kaggle kernel.
