### ISSUE TITLE
How to get mask scores for image segmentation ? 

### ISSUE THREAD

**Issue by dangmanhtruong1995** [facebookresearch/detectron2#1540]
Hi, I'm trying to extract masks for image segmentation using Mask-RCNN. I used the command:

 `outputs = predictor(im) where predictor is a DefaultPredictor`

However, the output has a field called pred_masks which returns only True or False values, while I want it to return a value from 0 to 1 in each pixel (from what I understand while reading the Mask-RCNN paper, it is supposed to return from 0 to 1). Please help me, thank you very much.

**Comment by ppwwyyxx** [comment]
Calling `model.inference(do_postprocess=False)` can provide raw predictions from the layers. They are not exactly in the format you need but are raw enough to create the format you need.

`DefaultPredictor` is only a simple demo and is not meant to support more functionalities like this.

**Comment by pvtien96** [comment]
@dangmanhtruong1995 you may refer to #200

**Comment by dangmanhtruong1995** [comment]
> Calling `model.inference(do_postprocess=False)` can provide raw predictions from the layers. They are not exactly in the format you need but are raw enough to create the format you need.
> 
> `DefaultPredictor` is only a simple demo and is not meant to support more functionalities like this.

So I did as you say and the output has the shape of 1x1x28x28, I think it's one object. Can you help me resize them to the original size ? Thank you very much.
