### ISSUE TITLE
unable to load 'proposal_generator.rpn_head’ 'proposal_generator.anchor_generator' wight

### ISSUE THREAD

**Issue by yangzgtyut** [facebookresearch/detectron2#1542]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote

I ran the baloon example in my local environment, everything is ok.

Then I ran the code with my dataset, similar to COCO’s json annotations with 5 classes. I set cfg.MODEL.ROI_HEADS.NUM_CLASSES = 5.  I didn't modify the cfg except this.

The output show that it's Unable to load 'proposal_generator.anchor_generator’, proposal_generator.rpn_head weights. But complete the training.

output: 

[06/05 12:13:08 d2.data.common]: Serializing 2021 elements to byte tensors and concatenating them all ...
[06/05 12:13:08 d2.data.common]: Serialized dataset takes 2.95 MiB
[06/05 12:13:08 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(800,), max_size=1333, sample_style='choice'), RandomFlip()]
[06/05 12:13:08 d2.data.build]: Using training sampler TrainingSampler
Unable to load 'proposal_generator.anchor_generator.cell_anchors.0' to the model due to incompatible shapes: (3, 4) in the checkpoint but (15, 4) in the model!
Unable to load 'proposal_generator.rpn_head.conv.weight' to the model due to incompatible shapes: (256, 256, 3, 3) in the checkpoint but (1024, 1024, 3, 3) in the model!
Unable to load 'proposal_generator.rpn_head.conv.bias' to the model due to incompatible shapes: (256,) in the checkpoint but (1024,) in the model!
Unable to load 'proposal_generator.rpn_head.objectness_logits.weight' to the model due to incompatible shapes: (3, 256, 1, 1) in the checkpoint but (15, 1024, 1, 1) in the model!
Unable to load 'proposal_generator.rpn_head.objectness_logits.bias' to the model due to incompatible shapes: (3,) in the checkpoint but (15,) in the model!
Unable to load 'proposal_generator.rpn_head.anchor_deltas.weight' to the model due to incompatible shapes: (12, 256, 1, 1) in the checkpoint but (60, 1024, 1, 1) in the model!
Unable to load 'proposal_generator.rpn_head.anchor_deltas.bias' to the model due to incompatible shapes: (12,) in the checkpoint but (60,) in the model!
Unable to load 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (6, 2048) in the model!
Unable to load 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (6,) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (20, 2048) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (20,) in the model!
[06/05 12:13:09 d2.engine.train_loop]: Starting training from iteration 0

## Expected behavior:

load the weight correctly

## Environment:

----------------------  ------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
numpy                   1.18.1
detectron2              0.1.3 @/home/yangzg/Downloads/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.0
detectron2 arch flags   sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/yangzg/.conda/envs/yangzg/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce RTX 2080 Ti
CUDA_HOME               /usr/local/cuda
Pillow                  7.1.2
torchvision             0.5.0 @/home/yangzg/.conda/envs/yangzg/lib/python3.8/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200604
cv2                     4.2.0
----------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by yangzgtyut** [comment]
When i use the trained model to makk prediction, it raise AttributeError: Cannot find field 'pred_masks' in the given Instances!

The cfg.MODEL.MASK_ON is True as default.

[06/05 12:15:34 d2.data.datasets.coco]: Loaded 2025 images in COCO format from datasets/round2/train_restriction.json
[06/05 12:15:34 d2.data.build]: Removed 4 images with no usable annotations. 2021 images left.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
      7     outputs = predictor(im)
      8     v = Visualizer(im[:, :, ::-1], metadata={}, scale=1.0, instance_mode=ColorMode.IMAGE_BW) 
----> 9     v = v.draw_instance_predictions(outputs["instances"].to("cpu"))  # 定义 Visualizer
     10     v.save(os.path.join("output/prediction", d["file_name"].split('/')[-1]))
     11     plt.imshow(v.get_image())

~/Downloads/detectron2/detectron2/utils/visualizer.py in draw_instance_predictions(self, predictions)
    366         if self._instance_mode == ColorMode.IMAGE_BW:
    367             self.output.img = self._create_grayscale_image(
--> 368                 (predictions.pred_masks.any(dim=0) > 0).numpy()
    369             )
    370             alpha = 0.3

~/Downloads/detectron2/detectron2/structures/instances.py in __getattr__(self, name)
     58     def __getattr__(self, name: str) -> Any:
     59         if name == "_fields" or name not in self._fields:
---> 60             raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
     61         return self._fields[name]
     62 

AttributeError: Cannot find field 'pred_masks' in the given Instances!

**Comment by ppwwyyxx** [comment]
Please include "what you did" and __full logs__ following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by yangzgtyut** [comment]
> Please include "what you did" (code change and command) and **full logs** following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

Thanks for reply. I write the code from scrach, it works again, I have no idea what happened.
