### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1546]
Dear Mr. Yuxin Wu

I am again. Today I run an evaluation but I got:

[06/05 22:54:36 d2.evaluation.coco_evaluation]: Evaluating predictions ...
WARNING [06/05 22:54:36 d2.evaluation.coco_evaluation]: No predictions from the model!
OrderedDict([('bbox', {'AP': nan, 'AP50': nan, 'AP75': nan, 'APs': nan, 'APm': nan, 'APl': nan})])

Below is my code I run:
    dataset_dicts = get_dicts("balloon/val")
    pre = DefaultPredictor(cfg)
    from detectron2.evaluation import COCOEvaluator, inference_on_dataset
    from detectron2.data import build_detection_test_loader
    evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
    val_loader = build_detection_test_loader(cfg, "balloon_val")
    print(inference_on_dataset(build_model(cfg), val_loader, evaluator))

Could you help me to figure out the error?

Thank you in advanced!

**Comment by ppwwyyxx** [comment]
in https://detectron2.readthedocs.io/tutorials/models.html

> build_model only builds the model structure and fills it with random parameters. See below for how to load an existing checkpoint to the model and how to use the model object.

**Comment by Long-Xuan-Do** [comment]
Dear Mr. Yuxin Wu
Thank you for replying me. When I run evaluation as you guided me, I got an unexpected result:

Below is the code I run
```	from detectron2.data import DatasetCatalog, MetadataCatalog
	d = "val"
	DatasetCatalog.register("balloon_" + d, lambda d=d: get_dicts("balloon/" + d))
	MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])

	dataset_dicts = get_dicts("balloon/val")

	model = build_model(cfg)
	from detectron2.checkpoint import DetectionCheckpointer
	DetectionCheckpointer(model).load("model_final_68b088.pkl")

	checkpointer = DetectionCheckpointer(model, save_dir="output")
	checkpointer.save("new_model")

	from detectron2.evaluation import COCOEvaluator, inference_on_dataset
	from detectron2.data import build_detection_test_loader
	evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
	val_loader = build_detection_test_loader(cfg, "balloon_val")
	print(inference_on_dataset(model, val_loader, evaluator))
```
And I got:
```
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.02s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
[06/06 10:19:03 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.000 | 0.000  | 0.000  | 0.000 | 0.000 | 0.000 |
OrderedDict([('bbox', {'AP': 0.0, 'AP50': 0.0, 'AP75': 0.0, 'APs': 0.0, 'APm': 0.0, 'APl': 0.0})])
```

**Comment by Long-Xuan-Do** [comment]
Could you help me to figure out the error? Thank you so much!

**Comment by ppwwyyxx** [comment]
I think you're loading a wrong model.
Please check the tutorial:  https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5. Evaluation works there.

**Comment by Long-Xuan-Do** [comment]
Do I need to train it for evaluation? In the tutorial, if I skip the trainning step, I also got this result.

**Comment by Long-Xuan-Do** [comment]
In the tutorial, if I skip the training step, I got the same answer. Could you suggest something for me?

**Comment by Jessica-1213** [comment]
I met the same question, have u guys solved it? I'll appreciate it if someone can tell me how to solve it

**Comment by sineagles** [comment]
DO you have solve this issues?
