### ISSUE TITLE
Sample larger than population or is negative

### ISSUE THREAD

**Issue by Harzva** [facebookresearch/detectron2#1547]
cfg = get_cfg()
# cfg.merge_from_file("/root/data/gvision/detectron2-master/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.merge_from_file("/root/data/gvision/detectron2-master/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")

cfg.SOLVER.BASE_LR = 0.02  # pick a good LR
# 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.SOLVER.IMS_PER_BATCH = 2*5# batch_size=2*5; iters_in_one_epoch = dataset_imgs/batch_size 22302
cfg.TEST.DETECTIONS_PER_IMAGE=200
# ITERS_IN_ONE_EPOCH = int(9254/cfg.SOLVER.IMS_PER_BATCH )
ITERS_IN_ONE_EPOCH = int(61/cfg.SOLVER.IMS_PER_BATCH )
# 保存模型文件的命名数据减1# Save a checkpoint after every this number of iterations
cfg.SOLVER.CHECKPOINT_PERIOD =100
cfg.SOLVER.MAX_ITER =ITERS_IN_ONE_EPOCH * 20 # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.OUTPUT_DIR="/root/data/gvision/dataset/d2_output/my_mask_lr0.02_per200_segclass1"
cfg.DATASETS.TRAIN = ("balloon_train",)
# cfg.DATASETS.TRAIN=("pv_train",) 
cfg.DATASETS.TEST=("balloon_val",) 
# cfg.DATASETS.TEST=("pv_test",) 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 # only has one class (ballon)
cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = 1

roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (2, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (2,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (4, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (4,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (1, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (1,) in the model! Skipped.
Traceback (most recent call last):
  File "my_maskrcnn.py", line 379, in <module>
    main()
  File "my_maskrcnn.py", line 360, in main
    predict_ballon()
  File "my_maskrcnn.py", line 252, in predict_ballon
    for d in random.sample(dataset_dicts, 50):    
  File "/opt/conda/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
root@dgx5:~/data/gvision/my_tools#

**Comment by ppwwyyxx** [comment]
The error is quite clear and does not come from detectron2.
