### ISSUE TITLE
Any plan to incorporate DETR?

### ISSUE THREAD

**Issue by danielgordon10** [facebookresearch/detectron2#1549]
## 🚀 Feature
A clear and concise description of the feature proposal.
Would be awesome to have DETR work in the detectron2 codebase. Seems like a non-trivial addition though, as it needs a new loss setup.
https://arxiv.org/pdf/2005.12872.pdf

## Motivation & Examples
Alternative to FasterRCNN/MaskRCNN pipelines.

**Comment by poodarchu** [comment]
I've made detectron2 to support DETR. https://github.com/poodarchu/DETR.detectron2

**Comment by alcinos** [comment]
We have released the official Detectron2 wrapper for DETR: https://github.com/facebookresearch/detr/tree/master/d2
It is a faithful reproduction of the detection results of the paper.

**Comment by ppwwyyxx** [comment]
Thanks @alcinos and @poodarchu !
