### ISSUE TITLE
"RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented" on Windows

### ISSUE THREAD

**Issue by liuqibj** [facebookresearch/detectron2#1550]
Hi, I export the model to pb format and runs well on ubuntu but it failed on Windows w/ pytorch 1.5 installed. thanks 

Instructions To Reproduce the Issue:

-  what changes you made (git diff) or what code you wrote

na

-  what exact command you run:

    faild on p = workspace.Predictor(init_net, predict_net)

    what you observed (including full logs):

    C:\ProgramData\Anaconda3\python.exe C:/Users/Administrator/Downloads/detectron2-deploy-master/detectron2.py
WARNING:root:This caffe2 python run failed to load cuda module:DLL load failed: ,and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
Detecting input\fungus.jpg
Traceback (most recent call last):
  File "C:/Users/Administrator/Downloads/detectron2-deploy-master/detectron2.py", line 128, in <module>
    detect(input)
  File "C:/Users/Administrator/Downloads/detectron2-deploy-master/detectron2.py", line 89, in detect
    results = p.run({"data": img, "im_info": info})
RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.
Error from operator: 
input: "507" input: "540" output: "545" name: "" type: "RoIAlign" arg { name: "order" s: "NCHW" } arg { name: "spatial_scale" f: 0.25 } arg { name: "pooled_h" i: 7 } arg { name: "pooled_w" i: 7 } arg { name: "sampling_ratio" i: 0 } arg { name: "aligned" i: 1 } device_option { device_type: 0 device_id: 0 }

Process finished with exit code 1

- please also simplify the steps as much as possible so they do not require additional resources to

    run, such as a private dataset.

Expected behavior:

train custom model and export it to pb format
load the pb and run it.
expect it works on windows (work well on ubuntu)
Environment:

Provide your environment information using the following command:

**Comment by ppwwyyxx** [comment]
Looks like a caffe2 installation issue. But we do not provide support for windows.
