### ISSUE TITLE
Registering datasets similar to Cityscapes

### ISSUE THREAD

**Issue by deepakksingh** [facebookresearch/detectron2#1554]
## ❓ How to do something using detectron2
I have a dataset which is similar to Cityscapes with same hierarchy and file structure.
Detectron2 supports custom dataset. 
Is there a way to register dataset similar to cityscapes? Or should I try creating files similar to cityscapes in detectron2?

I have currently converted my dataset to COCO.
While I'm training I'm having issue #1553

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/datasets.html explains how to add datasets of any format.
