### ISSUE TITLE
How training metrics and losses are calculated? 

### ISSUE THREAD

**Issue by ivanpanshin** [facebookresearch/detectron2#1555]
How training metrics (and losses) are computed? By default, all the values are written every 20 iterations. Does that mean that all metrics and losses are aggregated for these 20 iterations (or just for the last iteration)? And if I change 20 to some other value in `ret.append(hooks.PeriodicWriter(self.build_writers(), period=20))` in DefaultTrainer, can I aggregate metrics and losses, for example, over the whole epoch to training set?

**Comment by ppwwyyxx** [comment]
Metrics are aggregated over (by default 20) iterations.

> ret.append(hooks.PeriodicWriter(self.build_writers(), period=20))

It changes how often they are printed/saved/written, but not how long they are aggregated, which is defined by each individual writer from `build_writers`.

**Comment by Walid-Ahmed** [comment]
@ppwwyyxx But how can we print each epoch as we are still  printing each k iterations?
