### ISSUE TITLE
Unable to load ROI and APs is Nan

### ISSUE THREAD

**Issue by TemitopeOladokun** [facebookresearch/detectron2#1559]
Hello @ppwwyyxx , 
Thank you for your speedy response.
Why do I get this message about "Unable to load ROI ..." and my APs = "NAN"?
What am I doing wrong? 

Unable to load 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (4, 1024) in the model!
Unable to load 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (4,) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (12, 1024) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (12,) in the model!
Unable to load 'roi_heads.mask_head.predictor.weight' to the model due to incompatible shapes: (80, 256, 1, 1) in the checkpoint but (3, 256, 1, 1) in the model!
Unable to load 'roi_heads.mask_head.predictor.bias' to the model due to incompatible shapes: (80,) in the checkpoint but (3,) in the model!

**Comment by ppwwyyxx** [comment]
The checkpoint to load is wrong

**Comment by auchtopus** [comment]
Hi @ppwwyyxx, I have a follow up question. I'm getting a similar error, but I don't know what you mean by "checkpoint to load is wrong". 
I am doing
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = "model_final.pth"
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7 
predictor = DefaultPredictor(cfg)
```
model_final.pth loads fine on a colleague's instance, but doesn't work on mine. Our configs are otherwise indistinguishable. 


```
Unable to load 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (2, 1024) in the checkpoint but (81, 1024) in the model!
Unable to load 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (2,) in the checkpoint but (81,) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (4, 1024) in the checkpoint but (320, 1024) in the model!
Unable to load 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (4,) in the checkpoint but (320,) in the model!
Unable to load 'roi_heads.mask_head.predictor.weight' to the model due to incompatible shapes: (1, 256, 1, 1) in the checkpoint but (80, 256, 1, 1) in the model!
Unable to load 'roi_heads.mask_head.predictor.bias' to the model due to incompatible shapes: (1,) in the checkpoint but (80,) in the model!
```

**Comment by ppwwyyxx** [comment]
It means the checkpoint file and the model described by the config file does not match.

**Comment by auchtopus** [comment]
Thank you! I forgot to adjust the number of classes in my inference model

**Comment by TscHOat** [comment]
Hi @ppwwyyxx I'm also getting a similar error, but I don't know what you mean by "checkpoint file and the model described by the config file does not match".  did load predictor would load checkpoint from model that written on the config file?

**Comment by auchtopus** [comment]
@TscHOat 
When you make predictions, you need to create a model and then initialize the weights/biases. The first you do with cfg.merge_from_file, and the weights you load with cfg.MODEL.WEIGHTS. 

A problem might arise when the cfg.MODEL.WEIGHTS are for a model with slightly different parameters than the base model imported with cfg.merge_from_file. For instance, even though the imported structure is the same, the number of classes or the number of regions of interest in the trained model may be different from the number of classes/ROIs in the base stock model. To fix this, after you import your model, you should make the same adjustments you did when while training. For me, I needed to add these settings before importing weights:
```
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
```
because these adjustments were also made to the model that got the weights.

**Comment by TemitopeOladokun** [comment]
Hello @auchtopus , 
Thank you for your explanation but can you share relevant links to cfg.MODEL.WEIGHTS ?

Can you also mention the config you used and what is the maximum number of classes it can work with?
The number of classes I am working with is 20. 

I don't mind if @ppwwyyxx  can help out. Thank you for always helping out.
