### ISSUE TITLE
How to find instance according to predicted box area criteria?

### ISSUE THREAD

**Issue by ismailsalim** [facebookresearch/detectron2#1564]
I'm using the `DefaultPredictor` with the `Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml` configuration.

Given its prediction output for one image, I'd like to know the recommended approach for finding an `Instance` (if one exists)...
1. ...that is most central in the image compared to all the other instances (if they exist).
2. ...with the largest predicted box area compared to all the other instances (if they exist).

Detectron2 reference:
https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

**Comment by ppwwyyxx** [comment]
The output format is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format, from which you can obtain the location of objects.
