### ISSUE TITLE
How to report progress of Dataloader / inference_on_dataset

### ISSUE THREAD

**Issue by tgandor** [facebookresearch/detectron2#1565]
I am running validation on the COCO val2017 dataset, with different architectures.
Some are faster, some are slower.

The nearby code looks like this:
```
  predictor = DefaultPredictor(cfg)
  data_loader = build_detection_test_loader(cfg, 'coco_2017_val')
  evaluator = COCOEvaluator('coco_2017_val', cfg, False)
  start = time.time()
  results = inference_on_dataset(predictor.model, data_loader, evaluator)  # <--- here
  inference_time = time.time() - start
```
I hada chance to use a few different GPUs, from TitanV, V100, T4 to a humble 1060 6GB mobile.

I have done a small code diving session, and the impressive `multiprocessing` solution of dataloaders and samplers made me dizzy. But I see no clear API feature to attach such progress reporting.

How could I do such validation progress - what's the best way to e.g. report it via tqdm or maybe have an object with (even approximate) already processed count?

I have a few ideas, something like:
- use a custom Evaluator, when it gets inputs and outputs, they're already processed,
(but it's not at the very end?)
- subclass DataLoader and override some methods... (would I have to kiss the convenience of `build_detection_test_loader` goodbye?)
- decorate the DataLoader, i.e. wrap it with a class via composition, forward calls, and report the progress as the calls pass through
- provide a custom sampler, but... IterableDataset doesn't work with custom sampler

It doesn't seem to easy - the DataLoader has `__iter__`, and then the rest happens between client code and either `_SingleProcessDataLoaderIter` or `_MultiProcessingDataLoaderIter`.

I wouldn't like to outright kill the performance, or lose the multiprocessing benefits. But I also would like to have an idea, if the current validation will run for another 5, 15 or 120 minutes.

Is there an elegant solution to this, or is it only possible to load the images in a loop manually, run a prediction run the DefaultPredictor(cfg) on them, and feed the results to a COCOEvaluator?

**Comment by ppwwyyxx** [comment]
`inference_on_dataset` already reports its progress. 
If you like a different way to report progress, write a similar function. The code of `inference_on_dataset` is just a few lines if its progress report part is removed.

**Comment by tgandor** [comment]
Wow, thanks. I never looked at `inference_on_dataset` itself.
It turns out you have to set logging to at least `INFO`:
```
import logging
logging.basicConfig(level=logging.INFO)
```
and there come the messages:
```
INFO:detectron2.evaluation.evaluator:Start inference on 5000 images
INFO:detectron2.evaluation.evaluator:Inference done 11/5000. 0.4044 s / img. ETA=0:33:43
INFO:detectron2.evaluation.evaluator:Inference done 24/5000. 0.3955 s / img. ETA=0:32:55
```
Great stuff!
