### ISSUE TITLE
Model converted to Caffe2 output empty arrays.

### ISSUE THREAD

**Issue by karanjakhar** [facebookresearch/detectron2#1567]
I converted the Detectron2 Faster RCNN detection model trained on a custom dataset to Caffe2 model. 
The loaded Detectron2 model gives the correct output. But when I run Caffe2 model using this tutorial https://github.com/facebookarchive/tutorials/blob/master/Loading_Pretrained_Models.ipynb, then I get an empty array. 
Please suggest what could be the reason. What different things I should check.

**Comment by ppwwyyxx** [comment]
Because that tutorial is unrelated to this project and is not the right way to run our models. 
Instructions to use converted models are in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python

**Comment by karanjakhar** [comment]
@ppwwyyxx Please could suggest me how to use that in a mobile application. I am trying to deploy detectron2 faster R-CNN object detection on android mobile.
