### ISSUE TITLE
Trident loss question

### ISSUE THREAD

**Issue by TWDH** [facebookresearch/detectron2#1569]
## 🚀 Feature
As there's no question tags, I just want to ask a question in terms of TridentNet.

## Motivation & Examples
The previous question was stupid and I read the paper again. In my opinion the TridentNet split into three different branches in the backbone network, each branch is connected to a rpn and rcnn header with its own loss(right?).  I just have one question that with 3 different loss, do we calculate loss for each branch and add them together?

I saw you duplicate images and gt_instance in "trident_rpn.py" and "trident_rcnn.py", could you explain briefly why duplicate them will add the 3 branches loss together? really really Thanks!  

## Note
Another Big Thanks!

**Comment by lyttonhao** [comment]
Hi @TWDH, thanks for the question. Yes, we calculate loss for each branch separately. We duplicate the targets in RPN and RCNN for each image, and the Backbone also generates 3 feature maps for each image. In this case, we can simply treat each image as 3 separate samples to calculate the loss in RPN and RCNN. The final loss for the 3 branch will be aggregated just like 3 images.

**Comment by TWDH** [comment]
> Hi @TWDH, thanks for the question. Yes, we calculate loss for each branch separately. We duplicate the targets in RPN and RCNN for each image, and the Backbone also generates 3 feature maps for each image. In this case, we can simply treat each image as 3 separate samples to calculate the loss in RPN and RCNN. The final loss for the 3 branch will be aggregated just like 3 images.

@lyttonhao Thanks for your replying! There’s something confused me recently, that I have a rtx2080s with 8G  memory and it’s fine to train in batch size=2.but when I test the model use test_branch_idx=-1(which use all three branches to test instead of only the middle branch), it gives me CUDA out off memory error. It’s weird that I can train use three branches but can’t test. Not sure if detectron2 use batch size >1 when testing? Looking forward your comment thanks~

**Comment by ppwwyyxx** [comment]
It uses batch size 1 in testing.
