### ISSUE TITLE
sem_seg visualizer not coloring all classes

### ISSUE THREAD

**Issue by Kevin-Delnoije** [facebookresearch/detectron2#1573]
## ❓ How to do something using detectron2
i am using pointrend r101 cityscapes model
Describe what you want to do, including:
1. what inputs you will provide, if any:
i make the dataset mapper with the following keys where sem_seg_file_name is label integer coded image.
```python
                "file_name": image_file,
                "sem_seg_file_name": label_file,
                "height": h,
                "width": w,
```
the metadata is added as follows
```python
    DatasetCatalog.register(name + "_train", lambda x=train_dir: load_semantic_dict(x))
    MetadataCatalog.get(name + "_train").thing_classes =["thing_class"]
    MetadataCatalog.get(name + "_train").stuff_classes = ["background"]
```

visualize like below tried both draw_dataset_dict and draw_sem_seg :
```python
meta = MetadataCatalog.get("DATASET_NAME_train")
for d in random.sample(train_dict, 3):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=meta,instance_mode=ColorMode.SEGMENTATION, scale=1)
    print(d.keys())
    #vis = visualizer.draw_dataset_dict(d)
    sem_mask = cv2.imread(d["sem_seg_file_name"], cv2.IMREAD_UNCHANGED)
    vis = visualizer.draw_sem_seg(sem_mask, area_threshold=None, alpha=0.8)
    plt.figure()
    plt.imshow(vis.get_image())
```
2. what outputs you are expecting:
I want each pixel to be label by color of thing_class or stuff_class. For some reason 
only background is showing up in visualization, where i expect that both background(label=0) and thing_class(label=1) would show up with color overlays  

## [api](https://detectron2.readthedocs.io/modules/utils.html#module-detectron2.utils.visualizer)
the visualizer api for draw_sem_seg  says that it can be used for label and prediction however the model output is [classes, H, W] with confidence for each class instead of [H,W], not sure if this is intended and i need to do post_processing myself or in predictor class? and if so are there default ways to postprocess like the object detection has with cfg.CONF_THRESH and cfg.NMS_THRESH

**Comment by ppwwyyxx** [comment]
>     MetadataCatalog.get(name + "_train").stuff_classes = ["background"]

It only draws the classes that are defined here.
