### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.ops'

### ISSUE THREAD

**Issue by skye95git** [facebookresearch/detectron2#1574]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
<put diff or code here>
```
2. what exact command you run:
My environment is cuda10.0,python3.6,pytorch1.4.0
I want to test instance segmentation，I run the following command：
“python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --input 0011.jpg   --output ./out.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl”
3. what you observed (including __full logs__):
```
<put logs here>
```
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/public/home/detectron2_1/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/public/home/detectron2_1/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/public/home/detectron2_1/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/public/home/detectron2_1/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/public/home/detectron2_1/detectron2/layers/__init__.py", line 5, in <module>
    from .nms import batched_nms, batched_nms_rotated, nms, nms_rotated
  File "/public/home/detectron2_1/detectron2/layers/nms.py", line 5, in <module>
    from torchvision.ops import boxes as box_ops
ModuleNotFoundError: No module named 'torchvision.ops'

I checked the torch version below:
>>> import torch
>>> print(torch.__version__)
1.4.0

I tried to reinstall the virtual environment many times, as well as the torch several times, but got the same wrong results.How can I solve this problem?
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```
which: no nvcc in (/public/home/linjiayi/.conda/envs/detectron2/bin:/public/apps/anaconda3/condabin:/usr/share/gcc-5.4.0/bin:/public/apps/anaconda3/bin:/public/sbin:/public/apps/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/pdsh/bin:/public/home/linjiayi/.local/bin:/public/home/linjiayi/bin)
---------------------  ---------------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
numpy                  1.18.4
detectron2             0.1.3 @/public/home/linjiayi/PCL/detectron2/detectron2
Compiler               GCC 5.4
CUDA compiler          10.0
detectron2 arch flags  sm_60
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.4.0 @/public/home/linjiayi/.conda/envs/detectron2/lib/python3.6/site-packages/torch
PyTorch debug build    False
CUDA available         True
GPU 0,1                PH402 SKU 200
CUDA_HOME              /usr/local/cuda
Pillow                 4.2.1
torchvision            0.2.1 @/public/home/linjiayi/.conda/envs/CenterNet/lib/python3.6/site-packages/torchvision
torchvision            unknown
fvcore                 0.1.1
cv2                    4.2.0
---------------------  ---------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
Please fill the issue template, in particular the "environment" section.

**Comment by skye95git** [comment]
> Please fill the issue template, in particular the "environment" section.
I've filled the environment section.

**Comment by ppwwyyxx** [comment]
follow https://github.com/pytorch/vision#installation to install correct version of torchvision.

**Comment by skye95git** [comment]
> follow https://github.com/pytorch/vision#installation to install correct version of torchvision.
I have found out the cause of the problem,I use the "conda list" command to see the environment as follows:
-----------------------------------------------------------------
torchvision               0.5.0                py36_cu100    pytorch
-----------------------------------------------------------------
but I use the command "wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py", the environment as follows:
----------------------------------------------------------------------------------------------------
PyTorch                1.4.0 @/public/home/linjiayi/.conda/envs/detectron2/lib/python3.6/site-packages/torch
torchvision            0.2.1 @/public/home/linjiayi/.conda/envs/CenterNet/lib/python3.6/site-packages/torchvision
torchvision            unknown
---------------------------------------------------------------------------------------------------
The CenterNet is my other virtual environment. Why was Detectron2 called?

**Comment by ppwwyyxx** [comment]
detectron2 only does `import torchvision`. Which torchvision is used by `import torchvision` depends on how your environment is configured

**Comment by skye95git** [comment]
> detectron2 only does `import torchvision`. Which torchvision is used by `import torchvision` depends on how your environment is configured

Thanks, I don't know why the two environments intersect, but I remove the CenterNet environment, it works.

**Comment by MaheswariR450** [comment]
I am getting below error when using detectron2

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\personDetection_deep_learning.py", line 6, in <module>
    from detectron2 import model_zoo
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\model_zoo\__init__.py", line 8, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url, get_config
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\model_zoo\model_zoo.py", line 9, in <module>
    from detectron2.modeling import build_model
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\modeling\__init__.py", line 2, in <module>
    from detectron2.layers import ShapeSpec
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\layers\__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\layers\deform_conv.py", line 9, in <module>
    from torchvision.ops import deform_conv2d
ModuleNotFoundError: No module named 'torchvision.ops'


versions of torch and torchvision as per python IDLE:
>>> import torch
>>> torch.__version__
'1.7.1+cpu'
>>> import torchvision
>>> torchvision.__version__
'0.2.2'
>>>


Please help me to solve this issue...

**Comment by Draconda** [comment]
> I am getting below error when using detectron2
> 
> Traceback (most recent call last):
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\personDetection_deep_learning.py", line 6, in 
> from detectron2 import model_zoo
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\model_zoo__init__.py", line 8, in 
> from .model_zoo import get, get_config_file, get_checkpoint_url, get_config
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\model_zoo\model_zoo.py", line 9, in 
> from detectron2.modeling import build_model
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\modeling__init__.py", line 2, in 
> from detectron2.layers import ShapeSpec
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\layers__init__.py", line 3, in 
> from .deform_conv import DeformConv, ModulatedDeformConv
> File "C:\Users\Administrator\Desktop\jetson_backup\jan28\FACE\mahi_detectron2\detectron2\layers\deform_conv.py", line 9, in 
> from torchvision.ops import deform_conv2d
> ModuleNotFoundError: No module named 'torchvision.ops'
> 
> versions of torch and torchvision as per python IDLE:
> 
> > > > import torch
> > > > torch.**version**
> > > > '1.7.1+cpu'
> > > > import torchvision
> > > > torchvision.**version**
> > > > '0.2.2'
> 
> Please help me to solve this issue...

It seems torch vision version is too old,
I just solved the issue by just adding

pip install torchvision==0.9.1

at least version==0.9.1 it contains torchvision.ops
