### ISSUE TITLE
Problem about function "polygons_to_bitmask"

### ISSUE THREAD

**Issue by xlzhang1992** [facebookresearch/detectron2#1575]
I want get a instance bitmask ground truth without bounding box from polygons format, I use this function:
    for instances_per_image in instances:
        if len(instances_per_image) == 0:
            continue
        polygons = instances_per_image.gt_masks
        target = [polygons_to_bitmask(poly, height, width) for poly in polygons]
where height and width is the 1/4 input image size. However I got the target whose all the values are zero, which shows there is no target in the image. I don't kown what's wrong with my code?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
