### ISSUE TITLE
How to touch a existing model in modelzoo

### ISSUE THREAD

**Issue by zherlock030** [facebookresearch/detectron2#1588]
Hey, I'm using detectron2 for detection. Now I would like to touch the faster rcnn and rpn in the modelzoo. I want to print the time cost for each module in faster rcnn, or filter some proposals derived by RPN. What should I do? 

I'm new to detectron2, and I didn't find a way to modify the model I used. 
It seems I have no access to the  model structure.
I downloaded the model from modelzoo but is there a file that provide the model structure?

If there are projects achieved sth like this, please tell me.

**Comment by ppwwyyxx** [comment]
> is there a file that provide the model structure?

they are defeind by the code of this project
