### ISSUE TITLE
about TTA result

### ISSUE THREAD

**Issue by sunny0315** [facebookresearch/detectron2#1589]
## ❓ How to use the TTA correctly

I trained a model with my own data（mask-rcnn）, and the prediction effect with ‘DefaultPredictor’ is OK.
When I use  ‘GeneralizedRCNNWithTTA’ the result is not as expected.Is there something wrong with my use？The questions are as follows：
1. Each run may result in different results（box number）.
2. It doesn't seem like detection1 will invert the detected boxes to the original image, and then merge the box.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
