### ISSUE TITLE
Question about the cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST

### ISSUE THREAD

**Issue by ShaggyScraps** [facebookresearch/detectron2#1591]
Hello,
I am confused on how the cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST works for testing images. Not the validation kind that is designed to have annotations along side the training images, but an image just pulled from random that is similiar to the dataset that the network was trained on. If the thresh is supposed to limit the IoU bounding boxes, how can an IoU exist if the equation calls for a ground truth when the test image is passed in without a ground truth for the purpose of receiving a bounding box?
Or another way, when a testing image without annotations is passed into the network to be box bounded, how can a thresh limit the number of bounding boxes, when finding the IoU requires a ground truth?
Sorry if this makes little sense, I am going to use the fail-save and say I am new to all this.

**Comment by ppwwyyxx** [comment]
The score is not an IoU. 
It is a score predicted by the model.
