### ISSUE TITLE
Is it possible to implement CenterNet using detectron2?

### ISSUE THREAD

**Issue by tengerye** [facebookresearch/detectron2#1592]
Hi, I am wondering if detectron2 can be used to implement CenterNet? or will it be more simple not using it? If it is compatible, may I ask for some suggestions or key points I need to take care of? Thank you in advance.

**Comment by ppwwyyxx** [comment]
It can.

Check https://github.com/facebookresearch/detectron2/tree/master/projects/TensorMask or https://github.com/aim-uofa/AdelaiDet for implementation of new models.
