### ISSUE TITLE
How to set ignore label？

### ISSUE THREAD

**Issue by MagicCharles** [facebookresearch/detectron2#1593]
Hi，thanks for your project. Could you tell me how to ignore certain regions during training? For example, KITTI lables some region as 'DontCare' and they should not be regarded as positive samples nor negative samples during training.

Thank you!

**Comment by ppwwyyxx** [comment]
It's not clear what exactly it means to "ignore certain regions during training". But it seems we don't have a functionality similar to this. You may have to implement your idea with a custom model.
