### ISSUE TITLE
How to compute keypoints for 2 classes?

### ISSUE THREAD

**Issue by ivanpanshin** [facebookresearch/detectron2#1595]
Hi! I have a keypoints detection problem, where I have 2 classes: left eye and right eye. The thing is: the order of keypoints is different between eyes. But the model predicts all points inside eyes in 1 order. So my question is: is there a way to predict keypoints for several classes, not just 1? 

And if so, how to construct keypoints part of the dataset? (in terms of keypoint_names and keypoints_flip_map)

**Comment by ppwwyyxx** [comment]
We do not have this feature in detectron2.
