### ISSUE TITLE
Getting the heatmaps from detected keypoints

### ISSUE THREAD

**Issue by spraharaj3** [facebookresearch/detectron2#1596]
I'm using the to_heatmap function specified here, and am getting outputs of size [0,heatmap_size**2-1] as specified in the documentation.

Could you explain the meaning of these outputs? I couldn't find it exactly.

**Comment by ppwwyyxx** [comment]
It is the training target as described in paper "Mask R-CNN".

**Comment by hosnasattar** [comment]
Hi,
could you please let me know how you are getting the heat maps?
