### ISSUE TITLE
Where are transformed images added to dataset?

### ISSUE THREAD

**Issue by Gateway2745** [facebookresearch/detectron2#1597]
Hi. As I understand, the augmentation techniques like random flip, random brightness are applied onto the original image in DatasetMapper. Does this mean that we do not include the original image(before applying the transformations) for training? So the size of our dataset does not change? Thanks.

**Comment by yulong314** [comment]
the augmentation has an chance such as 0.5, when  the transform doesn't get the chance, then the original image is seen by training

**Comment by Gateway2745** [comment]
Yes. But in case the probabilty is greater than 0.5, should we not consider both the original as well as the transformed image for training ?

**Comment by ppwwyyxx** [comment]
What we did is described by @yulong314  correctly.
