### ISSUE TITLE
Is it possible to debug detectron2 in PyCharm in a CPU machine?

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/detectron2#1598]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md
I read the doc that written:
```
For most models, CPU training is not supported.
```
I do not want to train it, but I want to read the code in debug mode.
Thank you very much.

**Comment by ppwwyyxx** [comment]
It is

**Comment by guotong1988** [comment]
???

**Comment by guotong1988** [comment]
It is possible?

**Comment by ppwwyyxx** [comment]
Yes, it is.
