### ISSUE TITLE
Get error when I running "setup.py develop for detectron2"

### ISSUE THREAD

**Issue by fangrenfu** [facebookresearch/detectron2#160]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
include:

## To Reproduce

1. what changes you made / what code you wrote
nothing
2. what command you run
 pip install -e detectron2_repo
3. what you observed (full logs are preferred)
Installing collected packages: tabulate, cloudpickle, python-dateutil, cycler, kiwisolver, pyparsing, matplotlib, werkzeug, markdown, absl-py, grpcio, protobuf, tensorboard, detectron2
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/kiee/anaconda3/envs/dt2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kiee/dt2/detectron2_repo/setup.py'"'"'; __file__='"'"'/home/kiee/dt2/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/kiee/dt2/detectron2_repo/
    Complete output (46 lines):
    running develop
    running egg_info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kiee/dt2/detectron2_repo/setup.py", line 85, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 238, in build_extensions
        self._check_abi()
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 380, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 168, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 144, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/home/kiee/anaconda3/envs/dt2/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/kiee/anaconda3/envs/dt2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kiee/dt2/detectron2_repo/setup.py'"'"'; __file__='"'"'/home/kiee/dt2/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

## Expected behavior

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to work better, only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results documented in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment
---------------------  -------------------------------------------------------------------
sys.platform           linux
Python                 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                  1.17.2
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0
PyTorch Debug Build    False
torchvision            0.4.1a0+d94043a
CUDA available         False
Pillow                 6.2.0
---------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

Please paste the output of `python -m detectron2.utils.collect_env`.
If detectron2 hasn't been successfully installed,
use `python detectron2/utils/collect_env.py`.

**Comment by fangrenfu** [comment]
Now ,I know the reason !
I need to install g++,then it's ok

**Comment by peterhchen** [comment]
I build under window 10 and failed:

Installing collected packages: detectron2
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\14088\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Work\\AI\\11_PyTorch\\FacialRecognition\\detectron2\\setup.py'"'"'; __file__='"'"'C:\\Work\\AI\\11_PyTorch\\FacialRecognition\\detectron2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Work\AI\11_PyTorch\FacialRecognition\detectron2\
    Complete output (96 lines):
==========
(base) C:\Work\AI\11_PyTorch\FacialRecognition\detectron2>python detectron2/utils/collect_env.py .
The filename, directory name, or volume label syntax is incorrect.
----------------------  ------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
numpy                   1.18.1
detectron2              failed to import
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.5.0+cu101 @C:\Users\14088\anaconda3\lib\site-packages\torch
PyTorch debug build     False
CUDA available          True
GPU 0                   GeForce GTX 1060
CUDA_HOME               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC                    Not Available
Pillow                  7.0.0
torchvision             0.6.0+cu101 @C:\Users\14088\anaconda3\lib\site-packages\torchvision
torchvision arch flags  C:\Users\14088\anaconda3\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.1
----------------------  ------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 191627039
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 200203
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS  /GR  /w /EHa /bigobj -openmp -DNDEBUG -DUSE_FBGEMM, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

====
(base) C:\Work\AI\11_PyTorch\FacialRecognition\detectron2>g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/Program\ Files\ (x86)/CodeBlocks/MinGW/bin/../libexec/gcc/x86_64-w64-mingw32/8.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-8.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/lib -L/c/mingw810/prerequisites/x86_64-zlib-static/lib -L/c/mingw810/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

(base) C:\Work\AI\11_PyTorch\FacialRecognition\detectron2>
