### ISSUE TITLE
Registering synthetic datasets

### ISSUE THREAD

**Issue by ckang244** [facebookresearch/detectron2#1604]
## ❓ How to do something using detectron2

I'm interested in integrating some synthetic dataset generation code to detectron2, which creates sets of images with randomized object locations on the fly. It seems that today the only way to do this would be to generate the data outside of the training loop and then register a new custom dataset after each round. Would it be possible to integrate the data generation into the DatasetCatalog/registration process? Thanks.

**Comment by ppwwyyxx** [comment]
> creates sets of images with randomized object locations on the fly

You can put anything (like dummy list) in DatasteCatalog and generate data with https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader.
