### ISSUE TITLE
Serving Detectron 2 using either torchserver or MLflow or Kubeflow

### ISSUE THREAD

**Issue by rajdeeppalrajdeep** [facebookresearch/detectron2#1605]
## ❓ Is there a way to server the models made using Detectron 2 by using any of the following: torch-server or MLflow or Kubeflow

Describe what you want to do, including:
1. I want to deploy a custom model to GCP using Kubernetes, is there a way to do so in detection 2. 
2. If that's not possible can we convert the model to a native PyTorch model?

**Comment by ppwwyyxx** [comment]
> I want to deploy a custom model to GCP using Kubernetes, is there a way to do so in detection 2.

As long as GCP provides you a Linux computer, you can run detectron2 on GCP.
We do not provide help on how to use GCP, though.

> If that's not possible can we convert the model to a native PyTorch model?

I don't think there is a terminology called "native pytorch model". Would be better to explain what it is.

**Comment by rajdeeppalrajdeep** [comment]
> > I want to deploy a custom model to GCP using Kubernetes, is there a way to do so in detection 2.
> 
> As long as GCP provides you a Linux computer, you can run detectron2 on GCP.
> We do not provide help on how to use GCP, though.
> 

What I meant was can we use a serving tool like MLflow or Kubeflow to deploy a model build in detectron2. I want to build a serving API for the same.

**Comment by ppwwyyxx** [comment]
We do not provide support about other third-party services/frameworks, either.
