### ISSUE TITLE
Using Pointrend for Segmentation

### ISSUE THREAD

**Issue by bluesky314** [facebookresearch/detectron2#1606]
I see you have provided pointrend segmentation module but not shown how how to train in deeplabv3. I want like to know how exactly I can apply it in deeplab or my own model for my research? 

I am guessing each PointRendSemSegHead forward pass will give me a output twice the dimension of previous mask. So do I need to create multiple PointRendSemSegHead modules or is it just one being reapplied? 

Also the forward pass only takes in one features but the paper says that we concat earlier features with coarse prediction. What is exactly to be passed in?

**Comment by ppwwyyxx** [comment]
We have no plans at the moment to provide deeplabv3+pointrend models.
We provided semantic FPN+pointrend models, which can be taken as a reference to implement other models.
