### ISSUE TITLE
Can I show model graph in tensorboard?

### ISSUE THREAD

**Issue by p890040** [facebookresearch/detectron2#1607]
Description:

I see that we can write loss value in tensorboard by DefaultTrainer build_writer function.
But can we also show the model graph in some way?

I knew in general case I can use "writer.add_graph(model, tensor)"
But how to do in detectron2?

**Comment by GittersYang** [comment]
I also want to known how to do.   Do you already have the answer？

**Comment by dikshantsagar** [comment]
any update on this?

**Comment by Prussich** [comment]
+

**Comment by ppwwyyxx** [comment]
The graph can be easily produced by:
```
import cv2
import torch
from torch.utils.tensorboard import SummaryWriter
from detectron2 import model_zoo
from detectron2.export import TracingAdapter
model = model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml")
model.eval()

input = cv2.imread("../input.jpg")
input_t = torch.from_numpy(input).permute(2, 0, 1)
input = [{"image": input_t}]

model = TracingAdapter(model, input)
writer = SummaryWriter("./output")
writer.add_graph(model, model.flattened_inputs)
writer.close()
```

However it looks too ugly:
![2021-03-27_18-28](https://user-images.githubusercontent.com/1381301/112739582-442b0300-8f2a-11eb-9755-f1889983c9fc.png)

So I don't think this feature is worth having. Feel free to add if you have any better ideas

**Comment by zhaoyewei** [comment]
> The graph can be easily produced by:
> 
> ```
> import cv2
> import torch
> from torch.utils.tensorboard import SummaryWriter
> from detectron2 import model_zoo
> from detectron2.export import TracingAdapter
> model = model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml")
> model.eval()
> 
> input = cv2.imread("../input.jpg")
> input_t = torch.from_numpy(input).permute(2, 0, 1)
> input = [{"image": input_t}]
> 
> model = TracingAdapter(model, input)
> writer = SummaryWriter("./output")
> writer.add_graph(model, model.flattened_inputs)
> writer.close()
> ```

Model cannot be traced because some model outputs cannot flatten to tensors.
this way , have you ever seen this condition?

**Comment by jmorrey** [comment]
> > The graph can be easily produced by:
> > ```
> > import cv2
> > import torch
> > from torch.utils.tensorboard import SummaryWriter
> > from detectron2 import model_zoo
> > from detectron2.export import TracingAdapter
> > model = model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml")
> > model.eval()
> > 
> > input = cv2.imread("../input.jpg")
> > input_t = torch.from_numpy(input).permute(2, 0, 1)
> > input = [{"image": input_t}]
> > 
> > model = TracingAdapter(model, input)
> > writer = SummaryWriter("./output")
> > writer.add_graph(model, model.flattened_inputs)
> > writer.close()
> > ```
> 
> Model cannot be traced because some model outputs cannot flatten to tensors. this way , have you ever seen this condition?

It seems that some of the Detectron2 models can be flattened/traced and others cannot. I wasn't able to trace the one @ppwwyyxx mentioned.  I *was* able to trace the model associated with detectron2 keypoint detection though.  Also, Tensorboard now has an interactive graph visualization that makes it less messy than the image shown earlier.  I do think it's a useful tool.

**Comment by ppwwyyxx** [comment]
> Also, Tensorboard now has an interactive graph visualization

Could you show us what the new visualization looks like using the model above (whose old visuailzation is terrible)? If it's indeed better, then we can re-open this request

**Comment by jmorrey** [comment]
> > I wasn't able to trace the one @ppwwyyxx mentioned
> 
> My code above shows how to trace it.
> 
> > Also, Tensorboard now has an interactive graph visualization
> 
> Could you show us what the new visualization looks like using the model above (whose old visuailzation is terrible)? If it's indeed better, then we can re-open this request

I get the following error when running your code on my Mac.  It's probably an installation issue:

```
File "/usr/local/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 736, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, use_strict_trace))
  File "/usr/local/lib/python3.9/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 301, in graph
    list_of_nodes = parse(graph, trace, args)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 237, in parse
    nodes_py.append(NodePyOP(node))
  File "/usr/local/lib/python3.9/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 93, in __init__
    self.attributes = str({k: node_cpp[k] for k in node_cpp.attributeNames()}).replace("'", ' ')
  File "/usr/local/lib/python3.9/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 93, in <dictcomp>
    self.attributes = str({k: node_cpp[k] for k in node_cpp.attributeNames()}).replace("'", ' ')
  File "/usr/local/lib/python3.9/site-packages/torch/onnx/utils.py", line 1262, in _node_getitem
    return getattr(self, sel)(k)
AttributeError: 'torch._C.Node' object has no attribute 'ival'
```

That said, it works if I substitute "COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml" for the model.  And here is the visualization for (part) of that model:

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/3588755/162528031-749a16d3-002d-4a11-8920-50f6b5decc5a.png">

In the interface, the nodes are numbered so there aren't so many lines. Also, you can zoom in/out, drill down on nodes, etc.

**Comment by ppwwyyxx** [comment]
Thanks, I can reproduce the error. There seems to be a bug in recent versions of pytorch.

The new visualization looks better and would be worth adding if the above issue of pytorch can be fixed.
