### ISSUE TITLE
Will detectron2 supports dataset level sampling factor?

### ISSUE THREAD

**Issue by chenchr** [facebookresearch/detectron2#1609]
## 🚀 Feature
A clear and concise description of the feature proposal.
support for dataset level sampling factor
## Motivation & Examples
Hi. 
Suppose I have two datasets with 10w and 0.5w images respectively, how can I setup the sampling factor of these two dataset when training a model using image from these two datasets.
Since the size of two dataset has strong imbalance, during training, maybe it would be rational to sample image from the smaller dataset more frequently.
Thanks.

**Comment by ppwwyyxx** [comment]
Answered at https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader
https://detectron2.readthedocs.io/modules/data.html#detectron2.data.samplers.RepeatFactorTrainingSampler can be used in a custom data loader.
