### ISSUE TITLE
May be wrong gt_logit valiue when adding ground truth to proposals

### ISSUE THREAD

**Issue by dishank-b** [facebookresearch/detectron2#1612]
in` add_ground_truth_to_proposals_single_image(gt_boxes, proposals)` function, the logit value of ground truth is calculated as 
`gt_logit_value = math.log((1.0 - 1e-10) / (1 - (1.0 - 1e-10))) ≈ 10`. Shouldn't this be equal to `1`?

Line 48 in proposal_utils.py

**Comment by ppwwyyxx** [comment]
The code is correct.
The sigmoid of it should be 1.
