### ISSUE TITLE
Bottleneck of dataloading

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/detectron2#1613]
## Bottleneck of dataloading:

1. what changes you made (`git diff`) or what code you wrote
When I add classification task to detectron2, I found that https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/samplers/grouped_batch_sampler.py#L42 will greatly slow down the training procedure. This should be also the true when increase batch size to a large number.

2. what exact command you run:
3. what you observed (including __full logs__):
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
"Make something faster" doesn't constitute a valid feature request -- everything can be potentially made faster.  It can be a valid feature request with a proposal on features/functionalities needed to make it faster.

It's not an unexpected issue either. As far as I know it's pretty common to be bottlenecked by data loading in image classification.

**Comment by poodarchu** [comment]
> "Make something faster" doesn't constitute a valid feature request -- everything can be potentially made faster. It can be a valid feature request with a proposal on features/functionalities needed to make it faster.
> 
> It's not an unexpected issue either. As far as I know it's pretty common to be bottlenecked by data loading in image classification.

My point is, I found this can be optimized, and I've already fixed this problem. On the other hand, dataloading of standard imagenet classification, for example, the one in pytorch examples, won't encounter this problem.
So I think you can also fix this too.

**Comment by ppwwyyxx** [comment]
Then you're very welcome to propose what the improvement is (or send a PR directly if it's simple).

The pytorch example does not group images in custom ways like the code you linked to does, so it's expected to be faster.
