### ISSUE TITLE
The AP shows a decrease during training on Cityscapes Dataset.

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/detectron2#162]
I'm doing cityscapes training(mask rcnn) on a single 1080Ti with the default config, and for 8000steps, the AP shows 36.1 and for 16000steps, the AP shows 34.2. Since the result from the original article mask-rcnn is 36.4 on val set, I was wondering what's happening. Maybe I should wait till finish?

**Comment by ppwwyyxx** [comment]
I don't know what your modifications are and we certainly don't help you design changes of configs.
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#cityscapes--pascal-voc-baselines has a config that's pretty close to (or almost the same as) the one used in mask r-cnn.
