### ISSUE TITLE
Is it possible to use the optimizer in our own projects?

### ISSUE THREAD

**Issue by zzzzzz0407** [facebookresearch/detectron2#1620]
## 🚀 Feature
I find that if we treat detectron2 as a package, and then we should use the default SGD optimizer. Is it possible to use our own pre-defined optimizer? I donot want to write these code in solver/build.py which I should re-compile the detectron2. 

## Motivation & Examples

Make the optimizer much more flexible. Just like the backbone (@BACKBONE_REGISTRY.register()) and so on.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers --
we only consider papers that have enough significance and prevalance in the object detection field.

We do not take requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory contains many of such examples.

**Comment by ppwwyyxx** [comment]
> I find that if we treat detectron2 as a package, and then we should use the default SGD optimizer

you can use any pytorch optimizer. See https://detectron2.readthedocs.io/tutorials/training.html#training :

> If your customization is similar to what DefaultTrainer is already doing, you can change behavior of DefaultTrainer by overwriting its methods in a subclass, like what tools/train_net.py does.
If you need something very novel, you can start from tools/plain_train_net.py to implement them yourself.
