### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /home/ubuntu/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:365)

### ISSUE THREAD

**Issue by rsinghoyla** [facebookresearch/detectron2#1621]
## Instructions To Reproduce the 🐛 Bug:

1.  No changes
2.  python train_net.py --config-file configs/mask_rcnn_R_50_FPN_3x.yaml (standard dataset)
3. 
```RuntimeError: CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /home/ubuntu/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:365)```

*Note that networks without a ROIAlign layer for example Retinanet is working fine. *

Output of ```python -m detectron2.utils.collect_env```

```
----------------------  --------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.2 (default, Mar 26 2020, 15:53:00) [GCC 7.3.0]
numpy                   1.18.1
detectron2              0.1.3 @/home/ubuntu/detectron2/detectron2
Compiler                GCC 5.4
CUDA compiler           10.0
detectron2 arch flags   sm_37
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/ubuntu/anaconda3/envs/pytorch1.50/lib/python3.8/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0                   Tesla V100-SXM2-16GB
CUDA_HOME               /usr/local/cuda
Pillow                  7.0.0
torchvision             0.5.0 @/home/ubuntu/anaconda3/envs/pytorch1.50/lib/python3.8/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200602
cv2                     4.2.0
----------------------  --------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, ```

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by rsinghoyla** [comment]
Not sure what to do with the FAQ. I took a look when I built detectron2 and fixed issues that I could find. CUDA versions match and so does the architecture span 6,7. Also again most layers seem to be fine. ROI_Align is the first layer which has run into this RUNTIME problem.

**Comment by ppwwyyxx** [comment]
> Detectron2 or PyTorch/torchvision is not built for the correct GPU architecture (aka. compute compatibility).
The GPU architecture for PyTorch/detectron2/torchvision is available in the “architecture flags” in python -m detectron2.utils.collect_env.
The GPU architecture flags of detectron2/torchvision by default matches the GPU model detected during compilation. This means the compiled code may not work on a different GPU model. To overwrite the GPU architecture for detectron2/torchvision, use TORCH_CUDA_ARCH_LIST environment variable during compilation.

This is from the doc and it applies, because your logs show `detectron2 arch flags   sm_37`

**Comment by rsinghoyla** [comment]
ok... still not getting it though. I built it on a p2 instance in AWS and its not running on p2/p3 anymore. I will try with CUDA_ARCH_LIST env variable.
thanks

**Comment by Fly-dream12** [comment]
I also encountered this problem since i change my gpu device from 1080Ti to 2080Ti. In my log file, the detectron2 arch flags is sm_61. How to try with CUDA_ARCH_LIST ? 

@ rsinghoyla @ppwwyyxx 
Thanks
