### ISSUE TITLE
Inference balloon pic error

### ISSUE THREAD

**Issue by CZMHHH** [facebookresearch/detectron2#1622]
I am a new to detectron2.I want to train the balloon dataset.But I can not find class name on the predicting box.When I want to see the average precison.some error like the follow
json_file was not found in MetaDataCatalog for 'balloon_val'. Trying to convert it to COCO format ...
here is my inference code
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
import os
import numpy as np
import json
from detectron2.structures import BoxMode
from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor
from detectron2.data import DatasetCatalog, MetadataCatalog
import cv2
from detectron2.model_zoo import model_zoo
def get_balloon_dicts(img_dir):
    json_file = os.path.join(img_dir,"via_region_data.json")
    with open(json_file) as f:
        imgs_anns = json.load(f)
    dataset_dicts = []
    for idx, v in enumerate(imgs_anns.values()):
        record = {}

        filename = os.path.join(img_dir,v["filename"])
        height, width = cv2.imread(filename).shape[:2]

        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width

        annos = v["regions"]
        objs = []
        for _, anno in annos.items():
            assert not anno["region_attributes"]
            anno = anno["shape_attributes"]
            px = anno["all_points_x"]
            py = anno["all_points_y"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = [p for x in poly for p in x]

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": 0,
            }
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts
cfg = get_cfg()
for d in ["val"]:
    DatasetCatalog.register("balloon_" + d, lambda d=d: get_balloon_dicts("balloon/" + d))
    MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])
balloon_metadata = MetadataCatalog.get("balloon_val")
dataset_dictsval = get_balloon_dicts("balloon/val")
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.NUM_CLASSES=1
cfg.OUTPUT_DIR = 'output'
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR,"model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = ("balloon_val",)
predictor = DefaultPredictor(cfg)
evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg,"balloon_val")
inference_on_dataset(predictor.model,val_loader,evaluator)
# another equivalent way is to use trainer.test

**Comment by ppwwyyxx** [comment]
> I can not find class name on the predicting box

as expected. see https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer

>  I want to see the average precison.some error like the follow
json_file was not found in MetaDataCatalog for 'balloon_val'. Trying to convert it to COCO format ..

it's a warning and not an error.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by CZMHHH** [comment]
Thank you ver much. I will read the document again. @ppwwyyxx
