### ISSUE TITLE
What is the best way to add new losses for Semantic Segmentation ?

### ISSUE THREAD

**Issue by Cyril9227** [facebookresearch/detectron2#1623]
## ❓What is the best way to add new losses for Semantic Segmentation ?

My goal is to implement some losses such as Focal Loss for Semantic Segmentation, currently in detectron2 it is implemented in the file `detectron2/modeling/meta_arch/semantic_seg.py ` in the `SemSegFPNHead`. I tried to code a new `SemSegFPNHead` but couldn't make it work with the default `SemanticSegmentor` because the new head was not found in the Registry. I ended up implementing both a new `SemanticSegmentor` and `SemSegFPNHead` but I think it's overkill for simply adding new losses. 

What would be the best way to add new losses for Semantic Segmentation in D2 ? 

Thank you

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html shows how to register models, including new semantic segmentation heads.
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by fuaiguo** [comment]
@Cyril9227  hi,  could you solve this issue?

**Comment by Cyril9227** [comment]
> @Cyril9227 hi, could you solve this issue?

Yes, just add your custom loss in the FPN Head python file, not the cleanest way but it works.
