### ISSUE TITLE
ModuleNotFoundError: No module named 'detectron2'

### ISSUE THREAD

**Issue by yuanjunchai** [facebookresearch/detectron2#1624]
When I try to train the model, this happened:

Traceback (most recent call last):
  File "detectron2/projects/PointRend/train_net.py", line 13, in <module>
    import detectron2.utils.comm as comm
ModuleNotFoundError: No module named 'detectron2'

Could you help me if you are free? Thank you!

**Comment by ppwwyyxx** [comment]
detectron2 needs to be installed following https://detectron2.readthedocs.io/tutorials/install.html
