### ISSUE TITLE
Image channel order problem in data augmentation

### ISSUE THREAD

**Issue by sun11** [facebookresearch/detectron2#1625]
## Instructions To Reproduce the 🐛 Bug:
When I use cv2.imwrite to save an image in `RandomSaturation` class in transform_gen:
```
def get_transform(self, img):
    assert img.shape[-1] == 3, "RandomSaturation only works on RGB images"
    w = np.random.uniform(self.intensity_min, self.intensity_max)
    cv2.imwrite('temp.png', img)
    grayscale = img.dot([0.299, 0.587, 0.114])[:, :, np.newaxis]
    return BlendTransform(src_image=grayscale, src_weight=1 - w, dst_weight=w)
```
I found the image color is normal, it proved the image is in BGR order, but `[0.299, 0.587, 0.114]` is for RGB order.
## Expected behavior:
The weight for grayscale image conversion should be [0.114, 0.587, 0.299], and I'm not sure if the channel order is correct in `RandomLighting` class.

**Comment by ppwwyyxx** [comment]
There is no way for RandomSaturation to tell whether an image is RGB or BGR. 
Users should call RandomSaturation with an RGB image.

**Comment by MrGF** [comment]
@ppwwyyxx  The default INPUT.FORMAT is "BGR"，and the default MODEL.PIXEL_MEAN is for "BGR" format as well,  so if we want to use augmentation, we should change the INPUT.FORMAT to "RGB" ?
Maybe change the default INPUT.FORMAT and MODEL.PIXEL_MEAN to "RGB"  will be better?
