### ISSUE TITLE
my custem data has 1M image, run train load very slow

### ISSUE THREAD

**Issue by zbsean** [facebookresearch/detectron2#1626]
use my data has 1M image, run train load very slow about 2 hours, if normal.
the code is register data,

def get_dicts_by_list(path_list):
    dicts=[]
    for path_name in path_list:
        label_path=os.path.join(path_name,"labels_xml")
        image_path=os.path.join(path_name,"images")
        label_list=os.listdir(label_path)
        label_list.sort()
        for label_name in label_list:
            file_name,_=os.path.splitext(label_name)

            label_full_name=os.path.join(label_path,label_name)
            image_full_name=os.path.join(image_path,file_name+".jpg")
            tree = ET.parse(label_full_name)
            r = {
                        "file_name": image_full_name,
                        "image_id": file_name,
                        "height": int(tree.findall("./size/height")[0].text),
                        "width": int(tree.findall("./size/width")[0].text),
            }
            instances = []
            # print(file_name)
            for obj in tree.findall("object"):
                class_name = obj.find("name").text
                # class_name = change_class_name(class_name)
                # We include "difficult" samples in training.
                # Based on limited experiments, they don't hurt accuracy.
                # difficult = int(obj.find("difficult").text)
                # if difficult == 1:
                # continue
                bbox = obj.find("bndbox")
                bbox = [float(bbox.find(x).text) for x in ["xmin", "ymin", "xmax", "ymax"]]
                # Original annotations are integers in the range [1, W or H]
                # Assuming they mean 1-based pixel indices (inclusive),
                # a box with annotation (xmin=1, xmax=W) covers the whole image.
                # In coordinate space this is represented by (xmin=0, xmax=W)
                bbox[0] -= 1.0
                bbox[1] -= 1.0
                instances.append(
                    {"category_id": class_id_to_name.index(class_name), "bbox": bbox, "bbox_mode": BoxMode.XYXY_ABS}
                )
            r["annotations"] = instances
            dicts.append(r)     
    return dicts

**Comment by ppwwyyxx** [comment]
Custom data registration is supposed to be written by users. So the slowness is unrelated to detectron2.
