### ISSUE TITLE
bug in convert_to_coco_dict: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by wangg12** [facebookresearch/detectron2#1627]
When I evaluate my custom dataset using the coco evaluator, I have converted the segmentation to RLE format in the dataset dicts. Then this error occurred:
```
File "/data/detectron2/detectron2/data/datasets/coco.py", line 381, in convert_to_coco_dict
    "counts"
AttributeError: 'str' object has no attribute 'decode'
```
I commented `.decode("ascii")` in `convert_to_coco_dict`, then the error was fixed.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

maybe related: https://github.com/facebookresearch/detectron2/blob/92f85b57dbcd7231b368b66dfa8bb6727b435aac/tests/data/test_coco.py#L58-L77

**Comment by wangg12** [comment]
Because when I construct the dataset dicts, `.decode("ascii")` has already applied to the segmentation. That's why later the code in `convert_to_coco_dict` will complain. I think there should be some check in this function to avoid this bug.

**Comment by ppwwyyxx** [comment]
Users are expected to follow the format defined in https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts in order to use COCOEvaluator with custom dataset.

**Comment by wangg12** [comment]
Maybe something like:
```
if isinstance(coco_annotation["segmentation"], dict):  # RLE
    if not isinstance(coco_annotation["segmentation"]["counts"], str):
        coco_annotation["segmentation"]["counts"] = coco_annotation["segmentation"][
             "counts"
        ].decode("ascii")
```
