### ISSUE TITLE
Why GPU memory keeps increasing in training?

### ISSUE THREAD

**Issue by zj463261929** [facebookresearch/detectron2#163]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
include:

## To Reproduce

1. what changes you made / what code you wrote
2. what command you run
3. what you observed (full logs are preferred)

## Expected behavior

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to work better, only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results documented in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.
If detectron2 hasn't been successfully installed,
use `python detectron2/utils/collect_env.py`.

**Comment by ppwwyyxx** [comment]
It will slowly increase at the beginning and stop increasing, and this is expected.
The reason is because images have different sizes and allocated memory are typically not returned to the driver.

**Comment by engharat** [comment]
It seems weird to me that this is the expected behaviour; At iter 99 the model uses 3200mb of GPU memory, at iter 219 it jumps to 7000mb, at iter 5199 it is 10gb, at iter 15000 I get out of memory message.
