### ISSUE TITLE
Train my own datasets.

### ISSUE THREAD

**Issue by WangAQ126** [facebookresearch/detectron2#1635]
Can i use detectron2 to train a model that can detect the dog keypoints , if i have enough dataset which like the format of COCO？ If it does work, please tell me how to do it, thanks very much!

**Comment by chiboreache** [comment]
https://www.dlology.com/blog/how-to-train-detectron2-with-custom-coco-datasets/

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#use-detectron2-apis-in-your-code
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
