### ISSUE TITLE
Obtaining a three-tiered mask using foreground/background probabilities

### ISSUE THREAD

**Issue by ismailsalim** [facebookresearch/detectron2#1636]
Using the ```Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml``` pre-trained model, I would like to create a three-tiered mask for each instance based on the foreground/background probability for pixels rather than just the binary mask provided by ```DefaultPredictor```. 

Is there a way to use two probability thresholds? The lower for discerning between more likely background and moderately likely foreground and the higher for discerning between moderately likely foreground and highly likely foreground.

**Comment by ppwwyyxx** [comment]
The model does not do this.
So you need to either use the existing model in a different way: https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model
or rewrite (part of) the model: https://detectron2.readthedocs.io/tutorials/write-models.html
