### ISSUE TITLE
register_coco_instances with the same name

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1637]
`AssertionError: Dataset 'train' is already registered!`

would nice *never* seen this

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by chiboreache** [comment]
no, it's pretty expected, it just having a bad design

`register_coco_instances("my_dataset_train", {}, "json_annotation_train.json", "path/to/image/dir")`

when i rerun the code, it raise the error, instead of giving a warning, or even better - rewrite data silently under the hood

**Comment by ppwwyyxx** [comment]
It sounds like this is a feature request, then.

However, allowing a global state to be implicitly overwritten is something better to avoid. I think it's acceptable to allow explicitly removing a dataset with `DatasetCatalog.remove()`, if there is a need to reuse the same name.

**Comment by chiboreache** [comment]
> removing a dataset with `DatasetCatalog.remove()`
to be precise `DatasetCatalog.clear()` 

yeah, that's what i want, thank you @ppwwyyxx !!
works perfectly fine

<img width="406" alt="Screenshot_20200622_103335" src="https://user-images.githubusercontent.com/16459251/85260945-28af3b00-b474-11ea-82ff-b7b719861cb2.png">
