### ISSUE TITLE
How to crop a predicted polygon ?

### ISSUE THREAD

**Issue by aquadzn** [facebookresearch/detectron2#1638]
I can crop some predicted image using pred_boxes, for example:

```
# pred_boxes: Boxes(tensor([[1957.8635, 2152.3313, 2317.2563, 2343.0234]

plt.imshow(cv2.cvtColor(im[552:853, 1687:1939], cv2.COLOR_BGR2RGB))
```

I'm able to get the cropped bounding box, but what if I only want to crop the polygon mask with like a black / transparent background ?

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/models.html#model-output-format says, there is "pred_masks" as well.

**Comment by samjaswanth** [comment]
> I can crop some predicted image using pred_boxes, for example:
> 
> ```
> # pred_boxes: Boxes(tensor([[1957.8635, 2152.3313, 2317.2563, 2343.0234]
> 
> plt.imshow(cv2.cvtColor(im[552:853, 1687:1939], cv2.COLOR_BGR2RGB))
> ```
> 
> I'm able to get the cropped bounding box, but what if I only want to crop the polygon mask with like a black / transparent background ?

Where you able to solve this
