### ISSUE TITLE
The connector of custom backbone such as resnet.

### ISSUE THREAD

**Issue by Nobosaseru** [facebookresearch/detectron2#164]
In writing models , the guide said that  you can use cfg.MODEL.BACKBONE.NAME = 'ToyBackBone' in your config object. build_model(cfg) will then call your ToyBackBone instead. 
      And I don't know which place should be changed after I finished the custom backbone. Could someone tell me some details?
     I will be very grateful.

**Comment by ppwwyyxx** [comment]
When you build the model manually or use `DefaultTrainer` you need to provide a config to the `build_model()` function. You can set the backbone in that config.

**Comment by chansongoal** [comment]
Have you solved this problem? I have trouble with replacing backbone with VGG16. Thanks for your help.
