### ISSUE TITLE
Cascade R-CNN for Detection

### ISSUE THREAD

**Issue by JungUkKim** [facebookresearch/detectron2#1642]
Hi! 

Thank you for providing a gorgeous code.

By the way if I want to run the Cascade R-CNN with Faster R-CNN, 

is it okay if I run "configs/Misc/cascade_mask_rcnn_R_50_FPN_1x.yaml"  selecting MASK_ON = False?

Thanks in advance.

**Comment by ppwwyyxx** [comment]
It is ok.
