### ISSUE TITLE
Does torch==1.5+cu101 and torchvision==0.6.0+cu101 has torch.utils.hipify?

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/detectron2#1643]
Hi, I am trying to reinstall detectron2 on my machine. It works fine in this environment before, but when I removed detectron2 by 'pip uninstall detectron2' and try 'git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2',
It shows in the 12 line of setup.py,  ''No module named torch.utils.hipify".

How to solve this problem? thanks!

**Comment by yaodix** [comment]
I updata pytorch to 1.5.1 ,this error disappear

**Comment by shinezzz** [comment]
I also have this problem. How did you solve it？
