### ISSUE TITLE
Problem with 'id' when working with coco dataset

### ISSUE THREAD

**Issue by GeNiaaz** [facebookresearch/detectron2#1645]
My Notebook is linked below:
https://colab.research.google.com/drive/1_vnmx4TPKhnLAMFuxUcLUTuTmT2DOgFH?usp=sharing

<img width="453" alt="error" src="https://user-images.githubusercontent.com/31181133/85204472-492da700-b347-11ea-9f8b-25a11f6fc571.png">

A sample of my Coco JSON file is shown below:

![image](https://user-images.githubusercontent.com/31181133/85204487-65314880-b347-11ea-9b9f-2fe5976f7917.png)

![image](https://user-images.githubusercontent.com/31181133/85204490-70847400-b347-11ea-9322-fc57885bd40f.png)

**Comment by ppwwyyxx** [comment]
COCO format requires every annotation to have a unique id.

**Comment by GeNiaaz** [comment]
> COCO format requires every annotation to have a unique id.

Do you know an efficient way to insert an id into each annotation?

**Comment by ppwwyyxx** [comment]
```
for id, anno in enumerate(annotations):
    anno["id"]=id
```

**Comment by GeNiaaz** [comment]
Got it, thanks so much !!!
