### ISSUE TITLE
How to add PointRend to custom dataset?

### ISSUE THREAD

**Issue by LuisEdMB** [facebookresearch/detectron2#1649]
Hello, how could I add PointRend to a dataset that I am training? I previously trained a dataset following the tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

With PointRend, what steps would I have to add or do?

Thanks for the reply.

**Comment by ppwwyyxx** [comment]
The same steps as the tutorial (https://detectron2.readthedocs.io/tutorials/datasets.html).
