### ISSUE TITLE
How to solve <Cannot find field 'gt_masks' in the given Instances!> error?

### ISSUE THREAD

**Issue by GeNiaaz** [facebookresearch/detectron2#1650]
My dataset is a collection of 512x512 images. The JSON file is COCO formatted and contains annotations for the bounding boxes for objects in the images, of which the objects belong to only one category. The JSON file and images are in the same directory in my google drive folder, which is mounted in Google colab.

![image](https://user-images.githubusercontent.com/31181133/85217980-8f771a80-b3c8-11ea-97a0-06a908cba2e3.png)

How do I resolve the error above? I have googled and not been able to find something similar.

**Comment by ppwwyyxx** [comment]
It is trying to train a Mask R-CNN, which can only be trained on datasets that have masks.

**Comment by GeNiaaz** [comment]
Right, sorry about that. I will follow the template next time.

Sorry to keep bothering you, but would it be possible to train my dataset with Detectron 2, and if so, which ML model can I use? 
    if it is not possible to train the model without a dataset without masks, is it possible for me to 
    generate masks from my earlier defined bounding boxes?

**Comment by ppwwyyxx** [comment]
You can train Faster R-CNN or RetinaNet. It would be easier to understand what these models are before training them.

**Comment by GeNiaaz** [comment]
It worked, thank you so much !!
