### ISSUE TITLE
draw_instance_predictions(outputs["instances"].to("cpu")) mean?

### ISSUE THREAD

**Issue by ivder** [facebookresearch/detectron2#1653]
In custom training tutorial, when we do the inference there's 1 line of code indicating cpu as below
`draw_instance_predictions(outputs["instances"].to("cpu"))`

What does this line mean? Does it mean we do inference using CPU? If yes, can I just change to ```"gpu"``` to predict using GPU?

**Comment by ashnair1** [comment]
It just means that `output['instances']` is being moved to the cpu and then passed to the `draw_instance_predictions` function. Inference is already complete as `output['instances']` would be the inference result.

**Comment by ivder** [comment]
@anshulrai thanks, so the prediction is done using GPU by default right?
