### ISSUE TITLE
non-class agnostic bounding box regressor

### ISSUE THREAD

**Issue by mandal4** [facebookresearch/detectron2#1655]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
First, thanks for the awesome framework!
I have a question about the Class [FastRCNNOutputLayers](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/fast_rcnn.py).
I found that non class-agnostic box regressor is defined as following code.
`self.bbox_pred = Linear(input_size, num_bbox_reg_classes * box_dim)`  (line 397)

In a previous broadly used code including [this](https://github.com/jwyang/faster-rcnn.pytorch), bbox regressor is defined with the number classes + **1** (for background) 

I wonder is there any practical reason detectron2 not consider +1 dimension for background in bbox regressor. 

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
Bounding box regression for background class will not be trained and will not be used in inference, so it is meaningless to add background class.
