### ISSUE TITLE
dataset processing - segmentation(mask) from bbox

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1656]
having

```json
"annotations": [
        {
            "id": 0,
            "image_id": 0,
            "category_id": 2,
            "bbox": [
                290,
                263,
                70,
                74
            ],
            "area": 5180,
            "segmentation": [],
            "iscrowd": 0
        },
```

getting an error

`AttributeError: Cannot find field 'gt_masks' in the given Instances!`

would be nice to have some sort of converter

**Comment by ppwwyyxx** [comment]
Instance segmentation models cannot be trained without instance segmentation annotations (i.e., `gt_masks`).
You can train a different model.

**Comment by chiboreache** [comment]
i know it, thanks

my point - in the future I will have segmented dataset, but for now, i just wanna make it work

since i changed model to `COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml`
i can't evaluate it with official `mask` code example

```python
    v = Visualizer(im[:, :, ::-1],
                   metadata=meta_valid, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW
```

**Comment by chiboreache** [comment]
ok, the problem was in threshold, since it was very fast(test purpose) training, it just couldn't pass 0.7 barrier 

my bad..
