### ISSUE TITLE
CityscapesEvaluator with Faster

### ISSUE THREAD

**Issue by jimmy-s1** [facebookresearch/detectron2#1657]
## ❓ How to do something using detectron2
Hi, 
how can I use the CityscapesInstanceEvaluator with Faster RCNN to get mAP?
If I do so I get the error "Cannot find field 'pred_masks' in the given Instances", because Faster uses BBoxes instead of Masks. Can I convert the BBox to Masks ?

**Comment by ppwwyyxx** [comment]
CityscapesInstanceEvaluator uses https://github.com/mcordts/cityscapesScripts, which requires masks.
