### ISSUE TITLE
How to make predicted mask transparent / without color?

### ISSUE THREAD

**Issue by ivder** [facebookresearch/detectron2#1660]
Following the google colab tutorial of hot to train and do inference on custom dataset, I'm able to make predictions successfully. Below is the code
```
    im = cv2.imread(x)
    t1 = datetime.datetime.now()
    outputs = predictor(im)
    t2 = datetime.datetime.now()
    tdiff = t2 - t1
    print (int(tdiff.total_seconds() * 1000))

    v = Visualizer(im[:, :, ::-1],
                   metadata=damage_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    cv2.imwrite("result/"+x.split('/')[-1],out.get_image()[:, :, ::-1])
```

Each detected object will be filled in different color as usual. Now I want the detected object colorless or transparent, I only want the boundingbox, segmented shape border but with transparent mask color. I couldn't find the code that specify the segmentation color, how to do this? I installed detectron2 using pip

**Comment by ppwwyyxx** [comment]
I don't understand exactly what style is needed, but it doesn't seem like there is such a feature. Since the masks are already predicted, you can draw them yourself in custom styles.
