### ISSUE TITLE
Download cityscapes build in data

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1661]
Dear all,

Could anyone told me the exact command or program to use to download the build-in cityscapes dataset in Detectron2? I followed https://detectron2.readthedocs.io/tutorials/builtin_datasets.html#expected-dataset-structure-for-cityscapes, I noticed that DETECTRON2_DATASETS is a folder we created but where the data come from? I don't understand clearly this part of the tutorial. I don't know download the script for??? I need to download and use the data.

Particularly, how can I get the cityscapes_fine_instance_seg_train?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
Data comes from cityscapes official website.

**Comment by Long-Xuan-Do** [comment]
Dear,

Sorry since I am a beginner.
I understand that the register_cityscapes function is not provided so I just can use the custom data by self-writing this function. But you told me that "Data comes from cityscapes official website." I got the data before but I don't know how to access to perform evaluation since to perform evaluation, we need to register this data.

As a result, I think that the dataset build-in should provide the link or at least how to access to the cityscapes build-in data set. And this is my question. I don't understand the procedure.

So I have 2 questions:
1. pip install git+https://github.com/mcordts/cityscapesScripts.git for what?
2. All I need is to download the  https://www.cityscapes-dataset.com/file-handling/?packageID=1 and then I change the folder name to DETECTRON2_DATASETS??? Why after changing I run this command: 
```CITYSCAPES_DATASET=$DETECTRON2_DATASETS/cityscapes python cityscapesscripts/preparation/createTrainIdLabelImgs.py.```
 and got an error? What do you mean by this command? Purpose of it?

Thanks in advance!
