### ISSUE TITLE
[PointRend] Custom Dataset Training from scratch unstable

### ISSUE THREAD

**Issue by Chtchou** [facebookresearch/detectron2#1662]
I'm trying to start training PointRend with a ResNeXT-101 Backbone from scratch with a custom Dataset.
For the ResNet50 backbone, when I'm using pre-trained weight the training run without any problem.
Therefore, when I start the training without pre-trained weights, I obtain the following error : 
![image](https://user-images.githubusercontent.com/27629416/85377055-1fed6080-b56b-11ea-9008-427c644fea02.png)

It seems no matter what lr rate I use I got this problem. I tried to unfreeze the first two layers too
Do you any tips to make the training more stable?

Thank you

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
