### ISSUE TITLE
How to extract info from panoptic segmentation?

### ISSUE THREAD

**Issue by zcemycl** [facebookresearch/detectron2#1664]
I have implemented the codes from colab example. But I want to extract useful information from panoptic segmentations, such as strings for instance and stuff classes, and customize the visualization, for example, font scale, font thickness, and transparency of masking. 

From the colab example, the most relevant line is,
`panoptic_seg,segments_info = outputs["panoptic_seg"]
`,
I can understand `panoptic_seg` is an array where each pixel is labeled as cluster id. But `segments_info` is confusing, with `isThing` key to be `False`, does the `category_id` correspond to the stuff label? Is it in the same order as in [https://github.com/nightrome/cocostuff/blob/master/labels.txt](url) ? From lines 92-182? 

What is `instance_id` in `segments_info`?

Can you provide a list of labels? With the way I mentioned above, all stuff labels are wrong.

**Comment by ppwwyyxx** [comment]
> isThing key to be False, does the category_id correspond to the stuff label?

yes

meaning of each category_id is defined in https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets in `thing_classes` and `stuff_classes`.

`instance_id` is not useful for interpreting the results.
