### ISSUE TITLE
How to load_cityscapes_instances?

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1667]
Dear all,

I downloaded the Cityscapes Dataset named: gtFine_trainvaltest.zip (241MB) [md5] and now I try to load it. I load it as:
```
load = load_cityscapes_instances('/content/gtFine/train', '/content/gtFine/train')
```
But I got the error:
```
[06/24 02:58:48 d2.data.datasets.cityscapes]: 18 cities found in '/content/gtFine/train'.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-094bdd007571> in <module>()
----> 1 load = load_cityscapes_instances('/content/gtFine/train', '/content/gtFine/train')

1 frames
/usr/local/lib/python3.6/dist-packages/detectron2/data/datasets/cityscapes.py in get_cityscapes_files(image_dir, gt_dir)
     37 
     38             suffix = "leftImg8bit.png"
---> 39             assert basename.endswith(suffix)
     40             basename = basename[: -len(suffix)]
     41 

AssertionError: 
```

Could anyone told me how to load the dataset? I want to perform evaluation on this dataset. So would have more questions.
Thanks in advance

**Comment by ppwwyyxx** [comment]
answered in the documentation: https://detectron2.readthedocs.io/modules/data.html#detectron2.data.datasets.load_cityscapes_instances

> image_dir (str) – path to the raw dataset. e.g., “~/cityscapes/leftImg8bit/train”.
gt_dir (str) – path to the raw annotations. e.g., “~/cityscapes/gtFine/train”.
