### ISSUE TITLE
Is Detectron2 able to be run in a C++ runtime environment via torchscript?

### ISSUE THREAD

**Issue by erickim555** [facebookresearch/detectron2#1668]
Question: is Detectron2 able to be run in a C++ runtime environment via torchscript? 

I'm aware that it's currently possible to convert a Detectron2 torch module to a Caffe2 format, via the provided [caffe2_converter.py](https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_converter.py) tool. The downside to this conversion is that the conversion isn't perfect: the predicted outputs of the Caffe2 model will slightly differ from that of the torch module, eg some missed boxes, slightly different confidence scores, etc.

Something I've been looking forward is the ability to deploy my Detectron2 torch model "natively" in a C++ runtime environment, using torchscript, that won't suffer from slightly-different-outputs. How close are we to realizing this?

Related question: I did see that there's a "torchscript" target option in the [caffe2_converter.py](https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_converter.py#L34) tool. Looking at the code, it looks like it uses the same codepaths as the Caffe2 exported model. Is it the case that this torchscript-export would suffer from the same conversion-correctness issues as the Caffe2-exported model, and that there's no real benefit from using one over the other?

I apologize if this has been asked already. Thanks!

**Comment by ppwwyyxx** [comment]
It is convertible through the caffe2 codepath. We don't take the small numerical difference as a serious issue in reality.
Other conversion support is not yet supported and was asked in #46
