### ISSUE TITLE
tensorboard metrics looks weird

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1670]
would be grateful for any thoughts

<img width="999" alt="Screenshot_20200623_151236" src="https://user-images.githubusercontent.com/16459251/85515831-3bf21000-b606-11ea-9065-4c05f93b3551.png">
<img width="981" alt="Screenshot_20200623_151250" src="https://user-images.githubusercontent.com/16459251/85515835-3d233d00-b606-11ea-9503-e29b82212820.png">
<img width="993" alt="Screenshot_20200624_103500" src="https://user-images.githubusercontent.com/16459251/85515980-65ab3700-b606-11ea-9e4e-bb845bd8c2c1.png">

Smoothing .99

**Comment by chiboreache** [comment]
cfg.DATALOADER.NUM_WORKERS = 4
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025   
cfg.SOLVER.MAX_ITER = 8000    
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 6

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

I think this looks like a result of writing outputs of multiple training into the same directory.

**Comment by chiboreache** [comment]
> I think this looks like a result of writing outputs of multiple training into the same directory.

you are just right!

<img width="423" alt="Screenshot_20200624_122152" src="https://user-images.githubusercontent.com/16459251/85529314-95ae0680-b615-11ea-95c3-090b753d8a82.png">


once again i wondering why this stupid error exist, it looks obvious, that metrics.json should be wiped or versioned

why google missed it 🤔
