### ISSUE TITLE
PointRend: How to calculate "uncertainty" in semantic segmentation when there is only one class of foreground?

### ISSUE THREAD

**Issue by Leslie0115** [facebookresearch/detectron2#1671]
Hi, I found the calculation of "uncertainty" in "projects/PointRend/point_rend/semantic_seg.py/calculate_uncertainty()",  the code indicates that the input (sem_seg_logits) should contains at least two classes of foreground (torch.topk(k=2)), but my custom dataset has only one class of foreground, how can I calculate the "uncertainty" in this case?
I will be grateful if you can help.

**Comment by ppwwyyxx** [comment]
> but my custom dataset has only one class of foreground

No, it should have a class of foreground and a class of background.
A classification task of one class is not a meaningful task.
