### ISSUE TITLE
How to evaluate the Cityscapes model on Cityscapes Dataset

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1672]
Dear,

I am a beginner in this dataset. So if my questions are stupid, please help me to answer them!

I am working with Cityscapes datasets named ```leftImg8bit``` and ```gtFine``` from Cityscapes Dataset page.
As the tutorial: https://detectron2.readthedocs.io/tutorials/builtin_datasets.html, I set up successfully these steps:
```
import os
os.system("export DETECTRON2_DATASETS='/content/cityscapes'")
CITYSCAPES_DATASET = os.system("$DETECTRON2_DATASETS python /content/cityscapesScripts/cityscapesscripts/preparation/createTrainIdLabelImgs.py")
```
```CITYSCAPES_DATASET = 65280```

But I don't know how to use the CITYSCAPES_DATASET for my next step is the evaluation step? I know that I cannot register this dataset, but I don't know where the name: ```list = [
cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test]```
 come from??? 

Could anyone tell me about how to use CITYSCAPES_DATASET or my any above steps to get one of the ```list``` elements so that I can perform ```CityscapesInstanceEvaluator``` and ```CityscapesSemSegEvaluator``` evaluation?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line is able to train and evaluate all configs provided in detectron2. For example, 
```
python tools/train_net.py --eval-only --config-file configs/Cityscapes/mask_rcnn_R_50_FPN.yaml MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/Cityscapes/mask_rcnn_R_50_FPN/142423278/model_final_af9cf5.pkl
```
evaluates a model on cityscapes.

**Comment by Long-Xuan-Do** [comment]
Dear Mr. Yuxin Wu

Thanks a lot, it works!

I have one more question: Could you advise me how I can evaluate the FasterRCNN on CityPersons???

Thanks in advance
