### ISSUE TITLE
How to fine-tune on my weights to a different problem?

### ISSUE THREAD

**Issue by ranjeetthakur** [facebookresearch/detectron2#1673]
Hi,
I can use the below to use weights from model zoo to fine tune and get some final weights.
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo

Similarily How can I use those final weights to fine tune on some other problem
While doing this I'm facing mismatch of number of classes in my current dataset and in the weights.

**Comment by ppwwyyxx** [comment]
> How can I use those final weights to fine tune on some other problem

https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 shows it.
