### ISSUE TITLE
speed detection

### ISSUE THREAD

**Issue by soheer** [facebookresearch/detectron2#1674]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:

i am using detectron2 in my project but the speed of detection is very low. if the duration of video is 10 seconds, the process will end after 10 minutes. can you supply us in some suggestions(hardware enhancement :  cpu, ram, gpu,...) or it is code problems (i am using your code without any changing)

2. what outputs you are expecting:

get video outputs in very near time

**Comment by ppwwyyxx** [comment]
the speed of each model is provided in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by soheer** [comment]
how to use multiple GPUs during processing detectron2??

**Comment by soheer** [comment]
> the speed of each model is provided in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

i am not working on training in custom dataset , i am using coco . my question is just how i can increase the speed of code processing. we have two gpus we are trying to activate  both using this command line export CUDA_VISIBLE_DEVICES=0,1 but the code is still working on one gpu.  how can i use multiple GPUs ?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md provided inference speed.

We don't have a feature that speeds up inference with multiple GPUs.
