### ISSUE TITLE
Pointrend code help

### ISSUE THREAD

**Issue by bluesky314** [facebookresearch/detectron2#1675]
What is shift and idx in 
```
shift = num_sampled * torch.arange(num_boxes, dtype=torch.long, device=coarse_logits.device)
idx += shift[:, None]
point_coords = point_coords.view(-1, 2)[idx.view(-1), :].view(
        num_boxes, num_uncertain_points, 2
    )
```
doing here https://github.com/facebookresearch/detectron2/blob/e7182d58e013bbe1f6a1f111a5ba72d90c860f47/projects/PointRend/point_rend/point_features.py#L103 ?

**Comment by ppwwyyxx** [comment]
`shift` is used to compute index which is later used for indexing in a flattened tensor. If it's not yet obvious how it works, I don't think I'm able to explain it without taking too much of my time.
In general, explaining what every line of code means is not a [type of issue](https://github.com/facebookresearch/detectron2/issues/new/choose) that we support, therefore closing. If you have difficulty understanding this, it would be easier to run it, print the variables, and read some pytorch documentation.
