### ISSUE TITLE
Loading exported model (to caffe2) gives error

### ISSUE THREAD

**Issue by csingh27** [facebookresearch/detectron2#1679]
I use this code : 

*with open(INIT_NET, "rb") as f:
   init_net = f.read()
with open(PREDICT_NET, "rb") as f:
   predict_net = f.read()
print("---------------------")

p = workspace.Predictor(init_net, predict_net)
print("+++++++++++++++++++++")

#print(p)
#print({'data':image})
#print({'data':im_info})

results = p.run({'data':image},{'data':im_info})
print("Printing Results ...")
print(results)*

I get thie error : 

*results = p.run({'data':image},{'data':im_info})
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: caffe2.python.caffe2_pybind11_state_gpu.Predictor, arg0: List[object]) -> List[object]
    2. (self: caffe2.python.caffe2_pybind11_state_gpu.Predictor, arg0: Dict[str, object]) -> List[object]*

**Comment by ivanpanshin** [comment]
Try using a single dict for that. Like p.run({'data': X, 'im_info': Y})

**Comment by ppwwyyxx** [comment]
Usage is provided in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python already.
Unless the provided usage does not work, we don't consider this as an issue.
