### ISSUE TITLE
Can not get the same inference time as reported in model zoo

### ISSUE THREAD

**Issue by Cold-Winter** [facebookresearch/detectron2#168]
Hi,

Thanks for release such a useful tool for object detection.

I have downloaded the source code and build by myself and i can reproduce the results reported on COCO in model zoo. However, when i use tools/train_net.py eval_only to test on COCO, i can only get the inference time of 0.17s/im which is much slower than 0.06s/im for FPN-R101 which is reported in model zoo. 

I want to make sure whether my installation is correct or not.

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Cold-Winter** [comment]
Hi,

I have get the same inference time when i set gpu_nums=1. I am not sure why it should be so much different when i use gpu_nums=4 (0.17s/im vs 0.06s/img). Any suggestions.

By the way, Do you support batch inference?

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
