### ISSUE TITLE
How to evaluate detection model using citypersons dataset

### ISSUE THREAD

**Issue by Long-Xuan-Do** [facebookresearch/detectron2#1681]
Dear all,

I have found that the JSON annotation for persons dataset are discrete, each annotation per image. Could anyone told me how I can group them together to use build-in detectron2 evaluation functions or how to re-write the build-in functions?

I want to evaluate the Faster RCNN 101 pre-trained model using Citypersons dataset.

Thanks in advance

**Comment by ppwwyyxx** [comment]
We do not provide help about a particular third-party dataset that's not in detectron2.
