### ISSUE TITLE
Pre-trained mask RCNN model cannot be used to predict on an image

### ISSUE THREAD

**Issue by csingh27** [facebookresearch/detectron2#1682]
Here is the code : 

#Load Pytorch model
import torch
print(torch.version.cuda)
from PIL import Image
import numpy as np
print("Loading pytorch model ...")
image_path=".../images/0.jpg"
image = np.asarray(Image.open(image_path))
print(image)
image=torch.tensor(image, dtype = torch.float)
checkpoint = torch.load('.../Pytorchmodel/maskrcnn.pth')
checkpoint.eval()
#checkpoint(np.expand_dims(image, axis=0))
checkpoint(image)

Here is the error : 

  File "/home/cs/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 220, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
IndexError: too many indices for tensor of dimension 1

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
