### ISSUE TITLE
(coco-style) Inference fails for custom dataset without annotations

### ISSUE THREAD

**Issue by wangg12** [facebookresearch/detectron2#1684]
When testing for a custom dataset without annotations, it would fail to convert to coco dict.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment]
What is the usecase for using `inference_on_dataset` on a dataset without annotations?

**Comment by wangg12** [comment]
For example, some test sets of some challenges may not provide the labels. Thus there are no annotations during inference.
The coco evaluator already supports this feature, but only work with the datasets with coco json file. For custom datasets, when trying to converting them to coco format, the inference process will be interrupted due to KeyError.
