### ISSUE TITLE
How to load previously saved weights (from a .pth file)

### ISSUE THREAD

**Issue by GeNiaaz** [facebookresearch/detectron2#1686]
I ran colab last night for 9000 iterations and am happy with the state of the model. I subsequently opened the output folder and downloaded the final_model.pth file. My session has since been disconnected, and I would like to reload the model using those weights, how would I go about doing that?

I get that the basic idea is to get "`cfg.MODEL.WEIGHT = {my_pth_file}`", but have been unable to do so.

I have searched online, and browsed the documentation from Detectron 2 about loading checkpoints, however I only have the .pth file and nothing else. Am I supposed to obtain anything else for this endeavour?

The tutorials I have found online do not pertain specifically to Detectron 2, hence I am posting my question here to hopefully get an answer from someone who has done this before.

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/models.html#load-save-a-checkpoint
