### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by CZMHHH** [facebookresearch/detectron2#1687]
when I first trained voc2012,it succeed.But,today I delete the output folder and want to train again.It breaks down.the error is following
RuntimeError: cuda runtime error (804) : forward compatibility was attempted on non supported HW at /opt/conda/conda-bld/pytorch_1591914855613/work/aten/src/THC/THCGeneral.cpp:47

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by CZMHHH** [comment]
It is a cuda problem.After reboting my computer,this problem disappears.Thank you
