### ISSUE TITLE
Background pixels are unseen in the training set of panoptic segmentation

### ISSUE THREAD

**Issue by vanpersie32** [facebookresearch/detectron2#1696]
According to [link1](https://github.com/facebookresearch/detectron2/blob/master/datasets/prepare_panoptic_fpn.py#L55),  the code maps background pixels whose category are 0 to category 255. According to [link2](https://github.com/facebookresearch/detectron2/blob/9c91580b80b06d0062e2dd123e42085efcde49b5/detectron2/config/defaults.py#L381),  category 255 is ignored in semantic segmentation, which means background pixels are unseen in the 
 training set. What they may be classified as in the inference stage.

**Comment by vanpersie32** [comment]
@ppwwyyxx

**Comment by ppwwyyxx** [comment]
> What they may be classified as in the inference stage.

they may be classified as anything by the model

**Comment by vanpersie32** [comment]
> > What they may be classified as in the inference stage.
> 
> they may be classified as anything by the model

If the background pixels may be classified as anything, misclassification happens and the peformance will drop. Why shoud we ignore background pixels.

**Comment by ppwwyyxx** [comment]
We did it because the paper we follow did it.

You're welcomed to try modifying the models and share your results.

**Comment by vanpersie32** [comment]
> We did it because the paper we follow did it.
> 
> You're welcomed to try modifying the models and share your results.

Thanks for your kind reply.
