### ISSUE TITLE
Provide base implementation of Mask rcnn & faster rcnn

### ISSUE THREAD

**Issue by roya0045** [facebookresearch/detectron2#1697]
## 🚀 Feature

We have some basic components strewn about in disctint part of the code, we have some projects/experimental stuff. But I find that there is no middleground where we have some basic examples of the code used to make the one of the provided MaskRCNN and FasterRCNN.

## Motivation & Examples

This is more flexible for user in combinations with the yaml models as they can do transfer learning and easily modify basic models and experiment with them.

I'm assuming that the code is still somewhere and should be imported easily as basic examples, as fiddling and modyfing the full model is not user friendly.

**Comment by ppwwyyxx** [comment]
Please be more concrete about what exact features you'd like to have. The Mask R-CNN that we provide right now is the "base" implementation of Mask R-CNN. 
One way to do it is to give an example, as the issue template suggests, about what you cannot do with the current implementation of Mask R-CNN but will be doable with the hypothetical "base" Mask R-CNN.

**Comment by roya0045** [comment]
I'm more interested by the faster RCNN implementation to be honest. What I want to do concretely is to take the base implementation and experiment, in this case try to combine Faster rcnn and DETR. Currently the provided Faster RCNN config don't make it easy to take part of the model and reuse them.

With the python file of the implementation its more easier to alter the structure and afterward import the weights.

The same would apply if someone wants to change any component of the base model used and experiment with any other component of the model and retrain them from scratch or by transferring part of the weights.

I hope this makes this more concrete.

**Comment by ppwwyyxx** [comment]
I think this is not getting more concrete. To me, the current implementation already allows changing most of the components in it.

Again, one way to do it is to give a concrete example, with code examples for best clarity, about what you cannot do with the current implementation of Mask R-CNN but how they will be done - with code examples for best clarity - with the hypothetical "base" Mask R-CNN.

**Comment by roya0045** [comment]
At the moment when I'm trying to reuse your architecture what I am doing is the following:
1) download the model
2) split it into parts
3) implement a big class that reuse those parts in the forward method.

This means that I am mostly fumbling about regarding what are the needed inputs for each components and have quite the hard time to figure out where the error are coming from.

Basically I'm using a part of your [colab example ](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=HUjkwRsOn1O0) as a base  and I have figured out what I need to provide to the RPN module, but in this case I have no clue why I get an error on 
```python
/usr/local/lib/python3.6/dist-packages/detectron2/modeling/proposal_generator/rpn_outputs.py in predict_proposals(self)
    307             # Expand anchors to shape (N*Hi*Wi*A, B)
    308             anchors_i = anchors_i.tensor.unsqueeze(0).expand(N, -1, -1).reshape(-1, B)
--> 309             proposals_i = self.box2box_transform.apply_deltas(pred_anchor_deltas_i, anchors_i)
...
RuntimeError: The size of tensor a (18000) must match the size of tensor b (36000) at non-singleton dimension 0```

Despite the fact that I use the same image with this model : "COCO-Detection/faster_rcnn_R_50_DC5_3x.yaml" as the base.

What would be helpful to understand how your models are make would be a simple base implementating such as the following:
https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/faster_rcnn.py

This can be modified by the user and tweaked more easily than fumbling about with prebuild components of a trained model.

Hope this is clearer.

**Comment by ppwwyyxx** [comment]
To use a component in code, you'll need to figure out the input argument for the component. That's basic requirement of programming, so I'm not sure what can be done to address that. We do have documented all the input requirements in the code, in the latest version: https://github.com/facebookresearch/detectron2/blob/63ac73e2d4c35ea353e6c0fa72846a21f4f37c9d/detectron2/modeling/proposal_generator/rpn.py#L143-L199

They seem pretty clear to me, but if not, please request for clarification and we can update them.

I'm not able to see how https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/faster_rcnn.py is different from ours. Structure wise, this file is just combining our GeneralizedRCNN and ROIHeads into one class. The file still uses "prebuild" (in your word) components such as RPN, proposal layer, pooling, heads, in the same way our code uses them. So it seems a user can certainly modify GeneralizedRCNN and ROIHeads as easily as modifying this file.

**Comment by roya0045** [comment]
@ppwwyyxx Good, thanks for the confirmation. I just wanted to make sure that there we no tweaks done to the model that could explain the size mismatch. If the implementation is like the one shown it should be easier to debug.
