### ISSUE TITLE
How to confirm that detectron2 is runing with GPU?

### ISSUE THREAD

**Issue by aqwy1996822** [facebookresearch/detectron2#1699]
How to confirm that detectron2 is runing with GPU?
 I use the 2060 with 100W on my laptop, run the follow code on 720P webcam, only get 5FPS.

CPU 10750H
GPU 2060 100W

python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --webcam --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

I want to know how to confirm the GPU are working
![image](https://user-images.githubusercontent.com/47407711/86165992-ac3cec00-bb46-11ea-8589-fa8b1f36555f.png)
![image](https://user-images.githubusercontent.com/47407711/86166027-ba8b0800-bb46-11ea-9e07-fc1c14c2162b.png)

**Comment by ppwwyyxx** [comment]
I believe the GPU is working fine according to the speed in the image.
