### ISSUE TITLE
ResNet-18 and ResNet-34 pretrained backbones on ImageNet.

### ISSUE THREAD

**Issue by zhuangbohan** [facebookresearch/detectron2#170]

**Comment by ppwwyyxx** [comment]
We do not support ResNet 18/34 or torchvision models. You need to rename weights to match your model if they are different.

**Comment by borisgribkov** [comment]
Maybe my experience will help. As I found no need to use initial weights for RetinaNet training, I have trained RetinaNet-18 from scratch. For 34 the situation is more complicated, first need to use ultra low LR like 1E-7, after use this model as an initial weights.
