### ISSUE TITLE
Using detectron code for deployment in C++

### ISSUE THREAD

**Issue by raghavendraramya** [facebookresearch/detectron2#1701]
How to use a trained model in C++ for inference?

I am trying to use a .pb model for the weights and the network topology and perform inference using it. 
The inputs that will be provided are:
1. A model file in a .pb (Protobuf) format.
2. A weights file in a .pb format.
3. An image on which inference will be performed.

I am trying to use https://github.com/facebookresearch/detectron2/tree/master/tools/deploy and I am having trouble compiling the code. The compiler does not locate where c10 is. So, I moved pytorch/ into this directory. I have been trying to follow the documentation here - https://detectron2.readthedocs.io/tutorials/deployment.html#caffe2-deployment. 
Are there specific ways to install the dependencies? Kindly let me how the code can be compiled.

Thank you,
Ramya.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python has the exact command to compile the code in a docker container.

**Comment by raghavendraramya** [comment]
Hi,

I cannot use docker container for my work. I need to know which flags I
need to use to compile my code. The Makefile generated by the cmake command
does not have the right flags to compile Pytorch/gflags etc.

Kindly guide me on this.

Warm regards,
Ramya.

**Comment by ppwwyyxx** [comment]
We do not provide official support for other build systems because [pytorch does not either](https://pytorch.org/cppdocs/installing.html).
