### ISSUE TITLE
Iteratively improving dataset annotations with trained model

### ISSUE THREAD

**Issue by esox** [facebookresearch/detectron2#1702]
I would like to use the contour of the masks predicted by my detectron2 model to create the annotations for new images. 

So far I have trained a model (using Zoo as a starting point) on a very small dataset (~50 images) and when predicting out of sample, I already get OK-ish results:

```python
from detectron2.utils.visualizer import ColorMode
dataset_dicts = get_all_mushroom_dicts(mushroom_categories, "mushroom_dataset_small/val")
for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    mushroom_outputs = mushroom_predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=mushroom_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    mush_out = v.draw_instance_predictions(mushroom_outputs["instances"].to("cpu"))
    cv2_imshow(mush_out.get_image()[:, :, ::-1])`
```
[https://github.com/esox/Mushroom_Finder/blob/master/download1.png](url)
[https://github.com/esox/Mushroom_Finder/blob/master/download2.png](url)
[https://github.com/esox/Mushroom_Finder/blob/master/download3.png](url)

However as you can tell (especially from the 3rd picture) it's not perfect. I would like to save the contours of the mask as COCO-compliant annotations so I can then manually improve them with my annotation drawing tool. In a sense, I'd be using the current predictor to go most of the heavy lifting for me, with me fixing the masks that were screwed up.

I tried doing so by using "mask_to_polygons" but it seems wrong.

```python
from detectron2.utils.visualizer import GenericMask
output=v.get_output()
masks = np.asarray(mushroom_outputs["instances"].to("cpu").pred_masks)
gm = GenericMask(masks[0], output.height, output.width)
contours, has_holes=gm.mask_to_polygons(masks[0])
```

According to the source code of mask_to_polygons, contours[-1] should have the outer contour (the one i'm interested in) but it doesn't look to me like a list of X,Y coordinates so I'm stuck...

Anyone knows how to solve?

Thanks!

**Comment by ppwwyyxx** [comment]
I'm not sure I understand what this question is about. But if this is asking how to obtain contours from masks, we do not provide this feature as it's not directly related to object detection. You can find other libraries such as opencv to do it.
`GenericMask` is an internal class that does not appear in APIs (https://detectron2.readthedocs.io/modules/index.html) and is not meant for use.

**Comment by esox** [comment]
Hi @ppwwyyxx , I appreciate the response. 

I'm indeed trying to get the contour xy coordinates. I have tried using opencv (see below code and result) but doesn't work. Any chance you could point me in the right direction? much appreciated!

```python
instances = mushroom_outputs["instances"].to("cpu")
mush_out = v.draw_instance_predictions(instances)

image = mush_out.get_image()[:, :, ::-1]
masks = np.asarray(instances.pred_masks)

for mask in masks:
  mask = np.ascontiguousarray(mask)  # some versions of cv2 does not support incontiguous arr
  contours, hierarchy = cv2.findContours(mask.astype("uint8"), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
  cv2.drawContours(image, contours, 0, (0, 255, 0), 2)
cv2_imshow(image)
```
[(https://github.com/esox/Mushroom_Finder/blob/master/download4.png)]

**Comment by ppwwyyxx** [comment]
It might be better to get help about opencv usage from the opencv community.

**Comment by esox** [comment]
For anyone having the same problem, now solved:

https://stackoverflow.com/questions/62682065/storing-given-percentage-of-shape-contour-coordinates/
