### ISSUE TITLE
How do I evaluate a Pre-trained model from the Model Zoo on a Single Class?

### ISSUE THREAD

**Issue by kaushikb11** [facebookresearch/detectron2#1708]
I have filtered the Coco 2017 Dataset for a single class `person`. How do I evaluate the performance of the models on that Single class using the detectron2 API? Thank you!

**Comment by ppwwyyxx** [comment]
See https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=h9tECBQCvMv3 for an example of `inference_on_dataset`.

**Comment by kaushikb11** [comment]
I had gone through it. But I wish to run the COCO evaluator on some defined categories rather than running it on all the categories. I want to evaluate the performance of the models on certain categories. In the example in the colab above, you just get `AP` metric for every category(bbox and segm).

**Comment by ppwwyyxx** [comment]
It evaluates on the categories defined by the dataset. If the dataset defines one category person, it only evaluates person.
