### ISSUE TITLE
Loss weight for the mask head (and possibly the box head)

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#1709]
## 🚀 Feature
Add a LOSS_WEIGHT key to MODEL.ROI_MASK_HEAD (and optionally MODEL.ROI_BOX_HEAD) to control the loss contribution.

## Motivation & Examples
Other heads (e.g. the keypoint head) have individual loss weights to control their contribution to the loss. It would be good to have a way to control the contribution of the mask head as well.

If this feature request is accepted, I can implement the feature and create a PR.

**Comment by ppwwyyxx** [comment]
We're soon having loss_weight for box head. Since both box/keypoint will have it, it sounds reasonable to add one for mask head as well.

**Comment by pieterbl86** [comment]
> We're soon having loss_weight for box head. Since both box/keypoint will have it, it sounds reasonable to add one for mask head as well.

@ppwwyyxx sorry to bother: is there any update regarding this loss weight contribution? I prefer to use this functionality on a short notice... thanks in advance!

**Comment by michaellee1** [comment]
+1

**Comment by hadilou** [comment]
Currently _C.MODEL.ROI_BOX_HEAD.BBOX_REG_LOSS_WEIGHT = 1.0 seems to accept only float values. Is there a way to pass a list of float with each value being a weight for regression and classification loss?

**Comment by hadilou** [comment]
Currently _C.MODEL.ROI_BOX_HEAD.BBOX_REG_LOSS_WEIGHT = 1.0 seems to accept only float values. Is there a way to pass a list of float with each value being a weight for regression and classification loss ?

**Comment by ppwwyyxx** [comment]
You can use 
```
model = GeneralizedRCNN(cfg, roi_heads=StandardROIHeads(cfg, box_predictor=FastRCNNOutputLayers(
  cfg, loss_weight={"loss_cls": 2, "loss_box_reg": 3})))
```
See https://detectron2.readthedocs.io/en/latest/modules/modeling.html#detectron2.modeling.FastRCNNOutputLayers

Yaml file is limited in syntax and is not meant to contain all functionalities
