### ISSUE TITLE
How to extract simple features from inference

### ISSUE THREAD

**Issue by lilostitch96** [facebookresearch/detectron2#1710]
I'm following the Detectron2 Beginner's Tutorial and everything is working. But I can't figure out how to extract information from the inference. For example, how do I access the area of the balloons? Or number of spotted balloons in one image? Those kinds of data I want to be able to save into a csv file.

**Comment by ppwwyyxx** [comment]
The output format is documented in https://detectron2.readthedocs.io/tutorials/models.html

**Comment by lilostitch96** [comment]
> The output format is documented in https://detectron2.readthedocs.io/tutorials/models.html

Thanks a lot!

So I got a bit further. 

```
predictor = DefaultPredictor(cfg) # Where cfg is the 'get_cfg()' with all parameters set already
img = cv2.imread(...)
outputs = predictor(img)
```

This "outputs" is the dictionary with all the predictions made, right? When I print _outputs_ I get the data I want:

`{'instances': Instances(num_instances, image_height, image_width, fields=pred_boxes: Boxes(tensor([[x, y, w, h], [...]], device='cuda:0')), ...)}`

First, I can't seem to figure out how to extract a single parameter (e.g. _num_instances_), since _instances_ is of type _detectron2.structures.instances.Instances_. And second, the "Boxes" contain the tensors of each instance if I understood it correct. I'm just not sure how to make sense of these tensors. Say I want to get the area of each instance, do you have any tips for that?

**Comment by ppwwyyxx** [comment]
These classes are all documented in https://detectron2.readthedocs.io/modules/structures.html. I believe this and https://detectron2.readthedocs.io/tutorials/models.html should have enough information for your questions.

**Comment by lilostitch96** [comment]
Thanks for quick reply again. 

So regarding my first question, I solved it this way:

`print(len(outputs['instances']))`

And regarding the second, I got the boxes and their _area_ with this code:

`print(outputs['instances'].get('pred_boxes').area())`

So that worked out fine. These tensors, they are the rectangular bounding boxes around each instance, right? Is there any way to access the instance encapsulating the object?

**Comment by lilostitch96** [comment]
I'm thinking that _pred_masks_ is the field I'm after. Right now when I print out my _outputs_ I get a _pred_masks_ with only boolean values. Is this because I'm using the _DefaultPredictor_ and the objects are stored as _BitMasks_? 

Do I need to implement a custom model and specify the _gt_masks_ to be stored as _PolygonMasks_ so I then can call the _area()_ function?

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/models.html#model-output-format says, a bit mask is the expected output format. 

How to use the output (e.g. compute the area, convert to polygons) is users' responsibility.
