### ISSUE TITLE
Training a Keypoint RCNN on a Custom Dataset with Multiple Classes 

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#1716]
Hello, 
Is it possible to train a keypoint RCNN, on a custom dataset, which includes more than one class?  
So far I have trained models with only one class, and I used ```register_coco_instances``` with corresponding metadata. 
How does the metadata format change from singleclass to multiclass training (if supported)? Is it a dict with nested dicts for each class? Also, if this is supported I would suggest adding it to the documentations.
Thank you!

**Comment by ppwwyyxx** [comment]
It can if the classes have the same keypoints.
Otherwise, it cannot be done with a classical Keypoint R-CNN and a custom keypoint head will be needed.
