### ISSUE TITLE
Save file after prediction

### ISSUE THREAD

**Issue by WellDL** [facebookresearch/detectron2#1717]
When I use the cv2_imshow code for detecting bounding boxes, I can view the results of the detections on the image. Now I want to save this prediction to Google Drive.

``` 
v = Visualizer(im[:, :, ::-1], metadata=microcontroller_metadata, scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(v.get_image()[:, :, ::-1])
```

However, when I use the demo.py code provided by detectron2, I get results with kites and other classes which are COCO classes but not my custom classes
I use this code to run demo.py

```
!python demo.py --config-file detectron2/configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml --input path/to/Drive.jpg --confidence-threshold 0.2 --output path/to/googledrive/predictionfasterrcnn.jpg --opts MODEL.WEIGHTS output/model_final.pth
```

**Comment by ppwwyyxx** [comment]
demo.py is a demo for builtin models, not for users' models.

A file can be saved with `cv2.imwrite`.

**Comment by WellDL** [comment]
Thanks! Therefore, the code looks as following?
```
cv2.imwrite("filename.jpg", v.get_image()[:, :, ::-1])
```
