### ISSUE TITLE
Can I make detections using pre-trained Imagenet 1K Models?

### ISSUE THREAD

**Issue by alex-grig-ds** [facebookresearch/detectron2#1718]
Can I make detections of Imagnet 1K classes using these pre-trained models:  https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models

As I understand it, I need a *.yaml config files for these models. Can I get it somewhere?

**Comment by ppwwyyxx** [comment]
no, because they are not detection models.

**Comment by alex-grig-ds** [comment]
Ok, thank you!

Отправлено с iPhone
