### ISSUE TITLE
Choose Type of object detector

### ISSUE THREAD

**Issue by WellDL** [facebookresearch/detectron2#1719]
I want to ask how to make use of RetinaNet, Faster R-CNN and R-FCN.

So far as I know, regarding Faster R-CNN I suppose you just need these information:
```
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(classes)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
```
Similarly, for RetinaNet:
```
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/retinanet_R_50_FPN_1x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/retinanet_R_50_FPN_1x.yaml")
cfg.MODEL.RETINANET.NUM_CLASSES = len(classes)
# Loss parameters:
cfg.MODEL.RETINANET.FOCAL_LOSS_ALPHA)
cfg.MODEL.RETINANET.FOCAL_LOSS_GAMMA)
cfg.MODEL.RETINANET.SMOOTH_L1_LOSS_BETA)
cfg.MODEL.RETINANET.SCORE_THRESH_TEST = 0.5
```

Is this everything to make use of two different backbones? Or is ResNet still the backbone?

Yet I wonder, why I do not see R-FCN in detectron2, since it was implemented in detectron1.

**Comment by ppwwyyxx** [comment]
The code looks reasonable.
"R_50" means "ResNet 50", so ResNet is still the backbone.
R-FCN is not implemented.
