### ISSUE TITLE
Where is yaml for imagenet

### ISSUE THREAD

**Issue by M-Younus** [facebookresearch/detectron2#172]
I am unable to find .yaml for imagenet I checked configs folder.

**Comment by ppwwyyxx** [comment]
What do you mean by "yaml for imagenet"?

**Comment by M-Younus** [comment]
In configs folder we have yaml for coco,pascal and cityscape but no yaml for imagenet..?

**Comment by ppwwyyxx** [comment]
People don't often do object detection on imagenet, therefore no.

**Comment by M-Younus** [comment]
> People don't often do object detection on imagenet, therefore no.

ok,right
