### ISSUE TITLE
How to train TridentNet on a Custom Dataset

### ISSUE THREAD

**Issue by Joaquin-aliaga** [facebookresearch/detectron2#1720]
Hi,
I want to train TridentNet model on a custom dataset, using Google Colab.

I was following the guide to train on a custom dataset and i managed to register my dataset. 

But i don't know how to get tridentnet config file using 
`cfg.merge_from_file()`
since trindentnet config folder is "out" of detectron2 package (?)

I could use the "train_net.py" file that is inside TridentNet folder, but i don't have a config file since i'm creating config file in my code.

Any guide to do this will be very welcome.

**Comment by ppwwyyxx** [comment]
> But i don't know how to get tridentnet config file using

They are outside the detectron2 package, so you can obtain them by `git clone`.

The PointRend colab notebook: https://colab.research.google.com/drive/1isGPL5h5_cKoPPhVL9XhMokRtHDvmMVL does something similar.
