### ISSUE TITLE
Implement wrappers around any augmentations in imgaug

### ISSUE THREAD

**Issue by furushchev** [facebookresearch/detectron2#1721]
Hi, I'm now trying to train models using custom dataset.
Is there any way to transform images on data augmentation like we can do using `imgaug` including gaussian blurring, affine / perspective transformations?

https://imgaug.readthedocs.io/en/latest/source/overview/geometric.html#affine
https://imgaug.readthedocs.io/en/latest/source/overview/geometric.html#perspectivetransform
https://imgaug.readthedocs.io/en/latest/source/overview/imgcorruptlike.html#gaussianblur

Thank you in advance!

**Comment by ppwwyyxx** [comment]
It would be nice to implement a wrapper so any augmentations in `imgaug` library can be used.

**Comment by furushchev** [comment]
@ppwwyyxx Thanks for the comment! It is definitely a good idea. I'll try it.
