### ISSUE TITLE
Increase precision of mask in instance segmentation task

### ISSUE THREAD

**Issue by javismiles** [facebookresearch/detectron2#1725]
Good day,
when I compare the masks that the instance segmentation head of detectron2 outputs to something like what https://www.remove.bg/ produces, the mask that detectron2 outputs just doesn´t have enough precision, it maybe uses less points, it misses completely fine features (unlike remove.bg), interpolating between adjacent points, it would be great to have a way to specify the precision of the mask or something similar, thank you

**Comment by ppwwyyxx** [comment]
Closing as it does not belong to any of the [issue category](https://github.com/facebookresearch/detectron2/issues/new/choose).
Detectron2 is a library for users to build good models for their applications, but it's not meant to provide all these models.
