### ISSUE TITLE
inconvenience of getting data from predictor

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1727]
```python
outputs = predictor(im)
o = outputs["instances"]
print(o)
```

getting 

```python 
Instances(num_instances=2, image_height=1024, image_width=1024, fields=[pred_boxes: Boxes(tensor([[502.4290, 721.2902, 582.5986, 820.7645],...
```

accessing to `fields` keys - works perfectly fine

```python 
s = o.scores
p = o.pred_classes
b = o.pred_boxes
```

**BUT** how to get `num_instances` ???

```python 
print(o[0])
print(o['num_instances'])
print(o.num_instances)
```

not working 👆 
It's kinda strange..

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

**Comment by chiboreache** [comment]
> answered in [detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances](https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances)

why it so hard every time?

please read it again, then read your link to **USELESS** docs, and realize - that is not answer on my question...thanks.


```python
print('num_instances' in predictor(im))
> False 
```
