### ISSUE TITLE
Small incoherence in category_id indexing

### ISSUE THREAD

**Issue by rds-itga** [facebookresearch/detectron2#1731]
In the doc it is written:
"category_id (int): an integer in the range [0, num_categories-1] representing the category label. The value num_categories is reserved to represent the “background” category, if applicable."

but if I respect this indexing rule in my coco annotation file I get this warning message during training:
"Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you."

I think there is a small incoherence here. Maybe I am wrong.

Regards

**Comment by ppwwyyxx** [comment]
Our dataset format, as described in https://detectron2.readthedocs.io/tutorials/datasets.html, is not the same as COCO format. In COCO format, categories are represented from [1, #categories]. 

Although it doesn't matter since we'll apply a mapping to convert it into [0, #category-1].

**Comment by deepakksingh** [comment]
I have a use case where my training dataset has category_id : [10,19], testing data has category_id:[0,19], and the model is Faster-RCNN built with NUM_CLASSES: 20. So in this case the data loader will map my training dataset's category_id to [0,9], which I wanted to be [10,19].
Any suggestions as to how to overcome this mapping issue?
Help will be much appreciated.

**Comment by ppwwyyxx** [comment]
Categories are declared in the "categories" field of the COCO-format json file and must be the same between training and testing.
The field can include categories that are never used.
