### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by SillyEyeLid** [facebookresearch/detectron2#1736]
Hey everyone,

In Alexeys YOLOv4 repo, the training time for 2000 iterations take me like 1.5days where as 2000 iterations on Faster-RCNN in this repo takes like 25-40min. My initial thought is that the basic config file for faster-RCNN in detectron2 only retrains the last layers of the CNN therefore the training time is significantly decreased. Is there an easy way to change this? Or is there another reason as to why the training time is so much faster for detectron2 compared to YOLOv4? Im using pretrained weights in both cases.

Im asking this because the accuracy is so much worse for my custom dataset in faster rcnn compared to YOLOv4 and i think the training time is the reason behind it. It also doesnt matter how many iterations i make on Faster-RCNN. I have tried with 30 000 iterations and the mAP is stuck on 62% no matter how long i train it. What can be the reason behind this?

Thanks in advance!

**Comment by ppwwyyxx** [comment]
> detectron2 only retrains the last layers of the CNN therefore the training time is significantly decreased

that was not the case

We do not know about YOLOv4 so we cannot comment on its speed.

About accuracy, as the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
