### ISSUE TITLE
Inference on Dataset is Crashing

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1738]
Hello, 

I am currently running detectron2 on a cpu just to test some items and have trained my own nn on a custom dataset. I can then use the code from colab notebook to predict on images successfully using predictor = DefaultPredictor(cfg).

Then when I try to inference on the dataset, my computer crashes every time. I originally had 66 images in my test dir, and tried it with just 7, and it still crashed, it made it through 5/7 images. This doesn't seem like this behavior should be happening, and I was wondering if anyone has seen something similar. Here is the code I am running: 

> cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
cfg.DATASETS.TEST = ("boat_test", )
predictor = DefaultPredictor(cfg)

> evaluator = COCOEvaluator("boat_test", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "boat_test")
inference_on_dataset(predictor.model, val_loader, evaluator)

I should also note that I am only running object detection unlike the colab tutorial, is there something that I need to specify in the cfg differently?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by wesleylp** [comment]
Hi, @svideloc. Take a look at my issue #1764. Is that your problem?

**Comment by svideloc** [comment]
Hey @wesleylp, I actually solved my issue. It was a memory issues that was solved [over on their github](https://github.com/pytorch/pytorch/issues/27971). Looks like we are having different issues
