### ISSUE TITLE
I WANT  LOAD MY DATA WITH  THE .BoxMode.XYWHA_ABS.

### ISSUE THREAD

**Issue by APeiZou** [facebookresearch/detectron2#1742]
_## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any: I have the  GT-Box's angle information with the bbox (list[float]): list of 5 numbers_ representing the bounding box of the instance.  What should I do ？
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/tutorials/datasets.html      The part  Use Custom Datasets--Register a Dataset with the BoxMode.XYWHA_ABS 

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
You can use XYWHA_ABS in https://detectron2.readthedocs.io/tutorials/datasets.html though we forgot to mention it.

However more is needed to use rotated box models. These are already tracked in an existing issue:  https://github.com/facebookresearch/detectron2/issues/21#issuecomment-595522318
