### ISSUE TITLE
detectron2 just use epoch，no steps?

### ISSUE THREAD

**Issue by wang2020c** [facebookresearch/detectron2#1744]
detectron2/engine/train_loop.py
![AE924BB9-4C4B-4285-A605-4D8E4F873011](https://user-images.githubusercontent.com/66287563/87004943-d189c400-c1f0-11ea-901d-27cbb077889e.png)
![FAD8949A-EF43-4742-9809-190CEAA30DCC](https://user-images.githubusercontent.com/66287563/87004949-d3538780-c1f0-11ea-816a-faad7dfcc5e1.png)

Only the number of iterations is used, the number of steps is not used，just run [start_iter，max_iter]，how to traverse the entire data set?

What I understand is，the program traverses the data set once in each iteration，data size = batch size * steps，where am I going wrong? Please advise

**Comment by ppwwyyxx** [comment]
"iteration" means "step".
