### ISSUE TITLE
How to get and visualize the mask of a single class from pre-trained model?

### ISSUE THREAD

**Issue by farazk86** [facebookresearch/detectron2#1746]
Hi, so following the detectron2 tutorial colab I wanted to use the pretrained model on an image I have:

```
cfg = get_cfg()
# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
```

Using visualizer I visualized the output and it worked very well in detecting all the classes within the image. 

But I want to extract only a single class, say only show or extract all the ``person`` instances from the output. But I cannot seem to identify this class from the generated output.  I checked the documentation on this [here](https://detectron2.readthedocs.io/tutorials/models.html#model-output-format) and see that the masks are stored in ``outputs["instances"].pred_masks`` but this is a collective tensor of all instances detected in image. The command ``print(len(outputs["instances"].pred_masks))`` gives ``18`` for my image. There is no way to connect a mask to a class.

I searched previous issues and found [this](https://github.com/facebookresearch/detectron2/issues/356) and [this](https://github.com/facebookresearch/detectron2/issues/1458) trying to do the same thing but a solution could not be reached there either, is this possible to achieve without retraining the entire model with a single class?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#model-output-format says you can use `pred_classes`

**Comment by farazk86** [comment]
Hi, thanks for answering. 

I knew about ``pred_classes`` but its not as simple as only retaining a certain class.

For example from the default COCO dataset I want to label only the instances of ``chair`` and ``person``. Then I extract these values and indexes using the following code:
```

preds = outputs["instances"].pred_classes.to("cpu").tolist()
# this will get the names of our classes in dataset..
labels_ = MetadataCatalog.get(cfg.DATASETS.TRAIN[0]).thing_classes

# Wanting to only extract chair and person
retain_ = []
retain_.append(labels_.index("chair"))
retain_.append(labels_.index("person"))

# retaining only retain_ from preds
my_masks = [x for x in preds if x in retain_]
my_masks = torch.tensor(my_masks)

outputs["instances].pred_classes = my_masks 
```

But I get error:

AssertionError: Adding a field of length 13 to a Instances of length 18


I'm struggling with making this work? How can I do this please?

Thanks

**Comment by ppwwyyxx** [comment]
You can create a new `Instances` and add fields, or index the original Instances, as shown in https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

**Comment by sachinkun21** [comment]
Hi Farazk. Did you get your query resolved. I am also facing similar issue. let me know if it's done. Thanks

**Comment by Eloi-14855** [comment]
> Hi Farazk. Did you get your query resolved. I am also facing similar issue. let me know if it's done. Thanks.
> I am doing it by looping over instance object and filtering indexes for required class. I am think there might be a better way



> @ppwwyyxx
> 
> Hi, thanks for answering.
> 
> I knew about `pred_classes` but its not as simple as only retaining a certain class.
> 
> For example from the default COCO dataset I want to label only the instances of `chair` and `person`. Then I extract these values and indexes using the following code:
> 
> ```
> 
> preds = outputs["instances"].pred_classes.to("cpu").tolist()
> # this will get the names of our classes in dataset..
> labels_ = MetadataCatalog.get(cfg.DATASETS.TRAIN[0]).thing_classes
> 
> # Wanting to only extract chair and person
> retain_ = []
> retain_.append(labels_.index("chair"))
> retain_.append(labels_.index("person"))
> 
> # retaining only retain_ from preds
> my_masks = [x for x in preds if x in retain_]
> my_masks = torch.tensor(my_masks)
> 
> outputs["instances].pred_classes = my_masks 
> ```
> 
> But I get error:
> 
> AssertionError: Adding a field of length 13 to a Instances of length 18
> 
> I'm struggling with making this work? How can I do this please?
> 
> Thanks

hi farazk86, im facing the same issue, can u pls show me how u get it over your problem, i would be very gratefull

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances answers:
> Indexing: instances[indices] will apply the indexing on all the fields and returns a new Instances. Typically, indices is a integer vector of indices, or a binary mask of length num_instances
category_3_detections = instances[instances.pred_classes == 3]
confident_detections = instances[instances.scores > 0.9]
