### ISSUE TITLE
detectron2 version and config downgrade

### ISSUE THREAD

**Issue by bigswede74** [facebookresearch/detectron2#1747]
I'm trying to downgrade my yaml config but I can find out what version to downgrade to. Is there an API call to print the version of detectron2 that is installed?

https://detectron2.readthedocs.io/modules/config.html

**Comment by ppwwyyxx** [comment]
`detectron2.__version__` is the version of detectron2, like any libraries.

However this has nothing to do with the version of config. The config version has not been changed since detectron2 was open sourced so there is no need to downgrade/upgrade config.
