### ISSUE TITLE
Slight drop on mAP of training reproduction

### ISSUE THREAD

**Issue by MARMOTatZJU** [facebookresearch/detectron2#1748]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
no diff
```
2. what exact command you run:

Reproduction has been conducted on 2 NVIDIA V100 GPUs (32G mem per gpu). 

```
./tools/train_net.py --config-file configs/COCO-Detection/retinanet_R_50_FPN_3x.yaml --num-gpu 2
```

3. what you observed (including __full logs__):

Evaluation results (mAP=38.4):

|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 38.432 | 58.034 | 40.900 | 23.255 | 41.990 | 49.748 |

logs:
[log.txt](https://github.com/facebookresearch/detectron2/files/4901345/log.txt)
[log.txt.rank1.txt](https://github.com/facebookresearch/detectron2/files/4901343/log.txt.rank1.txt)

config backup:
[config.yaml.txt](https://github.com/facebookresearch/detectron2/files/4901348/config.yaml.txt)

tensorboard output：
[events.out.tfevents.1594124804.gpu20113.eu95sqa.500.0.zip](https://github.com/facebookresearch/detectron2/files/4901349/events.out.tfevents.1594124804.gpu20113.eu95sqa.500.0.zip)

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

mAP=38.7 as is indicated [here](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#retinanet), or at least get closer to 38.7, instead of 38.4 which was reproduced on my machone.

I would like to know if this gap in mAP is acceptable for the object detection task (yeah I am new to this task), or maybe my environmental configuration (cuda version / pytorch version / etc.) is incorrect for exact reproduction. I will conduct further research upon Detectron2, so I need to be rigorous with the reproduction.

Thanks in advance!

[UPDATE]
I notice that the training environment for models in [MODEL_ZOO.md](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#retinanet) was “PyTorch 1.3, CUDA 9.2, cuDNN 7.4.2 or 7.6.3”, which is inconsistent w.r.t. to the current Detectron2 version on master branch (e.g. PyTorch 1.4.0 or later). I wonder if this _MODEL_ZOO.md_ is still applicable to default configuration files.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

Included in logs

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
When creating the model zoo we only run each training once. A gap of 0.3 is possible between a lucky and unlucky run.
I obtained 38.5 after running the model the second time.
