### ISSUE TITLE
How can i finetune a model in colab?

### ISSUE THREAD

**Issue by sybrenh** [facebookresearch/detectron2#1752]
Hi, I would like to finetune a model (from @hpanwar08) in Google colab. The model is not present in the model zoo, what would be a good way to access this model? I have already tried to access the model from my drive but this does not seem to work.

The inputs are two datasets I made myself, they contain images as well as a json annotation document. 
Thanks in advance

**Comment by ppwwyyxx** [comment]
demonstrated in the tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
