### ISSUE TITLE
Does keypoints model work with other object if i train, or it only work with human ?

### ISSUE THREAD

**Issue by tienhoang1094** [facebookresearch/detectron2#1753]
?

**Comment by ppwwyyxx** [comment]
if works on other objects if trained on other objects

**Comment by tienhoang1094** [comment]
do u have any túts about training keypoint model( from labeling to training) ?

**Comment by ppwwyyxx** [comment]
Now there are only tutorials for boxes / masks.

**Comment by tienhoang1094** [comment]
could u gime some major advide to train keypoint dêtctection2 model plz ?

**Comment by tienhoang1094** [comment]
![image](https://user-images.githubusercontent.com/58082063/87215960-4c73eb80-c365-11ea-9bf4-7ce729316a3b.png)
can i train only keypoint like that
