### ISSUE TITLE
How can I use multiple gpus when using the colab version of code?

### ISSUE THREAD

**Issue by Ema1997** [facebookresearch/detectron2#1756]
I follow the instructions in the [official colab file](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) to train the networks. However, I have a problem when using multiple gpus with this code. Therefore, would someone tell me how to use multiple gpus when using the colab version of code?

I have tried to set the `cfg.NUM_GPUS = 2`, and I failed.

My code is as below: 

```py
from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("Cityscapes/mask_rcnn_R_50_FPN.yaml"))
cfg.DATASETS.TRAIN = ("train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.NUM_GPUS = 2

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

thanks.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line shows the example training code that does multi-gpu training
