### ISSUE TITLE
error when i run  srtup.py

### ISSUE THREAD

**Issue by zhudd-hub** [facebookresearch/detectron2#176]
when i run the following code,
`python setup.py build develop`
i met the such error:
`/home/workspace/zhudd/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/pybind11/cast.h:1717:68: errors：could not convert ‘pybind11::cast<std::basic_string<char> >((* & std::move<pybind11::object&>((*(pybind11::object*)this))))’ from ‘int’ to ‘std::basic_string<char>’
 template <typename T> T object::cast() && { return pybind11::cast<T>(std::move(*this)); }`
what should i do

**Comment by ppwwyyxx** [comment]
Same as https://github.com/NVIDIA/apex/issues/185

Please post following the issue template and include full logs.

**Comment by zhudd-hub** [comment]
I have solve this problem by updata cuda to 10.1
