### ISSUE TITLE
Evaluating keypoint detection fails with message that a prediction with category_id = 1 doesn't exist, but it does exist.

### ISSUE THREAD

**Issue by VavoTK** [facebookresearch/detectron2#1767]
I am trying to train a facsimile of a "Keypoint Detector" using Detectron2, the training goes as expected, but evaluation fails with 
error message 
![image](https://user-images.githubusercontent.com/8460547/87393199-dc60a200-c5be-11ea-9339-5ecc2485783e.png)

My dataset is in the coco format and here is the category that has id of 1 
![image](https://user-images.githubusercontent.com/8460547/87393284-fb5f3400-c5be-11ea-88a4-b7a5753571cb.png)
**Steps to Reproduce** 
1. Use `register_coco_instances` to register the train and test datasets
2. set cfg.TEST.KEYPOINT_OKS_SIGMAS to be `[1,1,1,1,1]`  
3. set cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS  to be 5
4. Run the default `train_net.py` using these datasets.  
Please find both the training and testing coco.json files in this google drive link [https://drive.google.com/drive/folders/1YdpCYDMfiStWPlCU00UxKQfDILsHp1Ph?usp=sharing](url) 

EDIT: Also please notice that the dataset is correctly registered, but for some reason there's a problem with IDs
![image](https://user-images.githubusercontent.com/8460547/87394493-ebe0ea80-c5c0-11ea-8902-8916b15446d1.png)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by BrunoKryszkiewicz** [comment]
Hello there,
I wonder if you could share with me how were you annotating keypoints? I'm asking because I tried to make annotations in coco-annotator and it didn't work. I mean, I do not really know if it works or not but trying to retrain a model using my dataset definitely do not work.
Cheers.

**Comment by VavoTK** [comment]
I am closing this issue, because I found the issue I had set cfg.MODEL.ROI_HEADS.NUM_CLASSES wrong. 
 @BrunoKryszkiewicz  Hi! I have been using the tool provided by [superannotate.com ](url) Disclaimer! I work there. The actual tooling is free for academic research, but I would seriously suggest you look into the [annotate.online](url) 
I will also look into your question on Stackoverflow. 
Cheers.
