### ISSUE TITLE
GPU memory increase

### ISSUE THREAD

**Issue by zj463261929** [facebookresearch/detectron2#1768]
I modified the code as follows to test： （demo/demo.py）
demo = VisualizationDemo(cfg)

    if args.input:
        if len(args.input) == 1:
            args.input = glob.glob(os.path.expanduser(args.input[0]))
            assert args.input, "The input path(s) was not found"
        for path in tqdm.tqdm(args.input, disable=not args.output):
            # use PIL, to be consistent with evaluation
            img = read_image(path, format="BGR")
            start_time = time.time()
            #######################
            def test():
                start_time = time.time()
                predictions = demo.run_on_image1(img)
                end = time.time() - start_time
                print ("######### :      ", end)
            
            for i in range(10000000): #7
                timer = Timer(0.1, test) #0.5s=500ms
                timer.start()
                time.sleep(0.1) 
                     
            ####################################
            #predictions, visualized_output = demo.run_on_image(img)

result: GPU memory is growing. 
I hope you can provide me with a good solution, thank you.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
