### ISSUE TITLE
KeyError: 'boxes is not a file in the archive'

### ISSUE THREAD

**Issue by divyeshpandav** [facebookresearch/detectron2#1773]
I have converted my video into .npz file using detectron2

(config I use-: keypoint_rcnn_R_101_FPN_3x.yaml)

I want to use them into FacebookVideoPose3D  when I use that in "prepare_data_2d_custom.py" , it throws above error

`File "prepare_data_2d_custom.py", line 91, in <module>
    data, video_metadata = decode(f)
  File "prepare_data_2d_custom.py", line 22, in decode
    bb = data['boxes']
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'boxes is not a file in the archive`

I want to use detectron2 instead of detectron!

I am posting this here, because if i use detectorn then it does not give an error !
can anybody help me what is the problem here?

**Comment by ppwwyyxx** [comment]
The code and error doesn't seem related to detectron2.
If you believe this is a detectron2 issue, please add details following [issue templates](https://github.com/facebookresearch/detectron2/issues/new/choose)

**Comment by divyeshpandav** [comment]
I will do that!
can you tell me, should we use detectron2 for Videopose3D or detectron is better for that??

**Comment by ppwwyyxx** [comment]
I'm not familiar with the VideoPose3D project and this would be a question better suited in that project.
