### ISSUE TITLE
How to modify already trained model?

### ISSUE THREAD

**Issue by j-adamczyk** [facebookresearch/detectron2#1774]
## ❓ How to do something using detectron2

Pre-trained Detectron2 models are great, since they are well trained on a large dataset, so I want to use them, since like many others I don't have high computational power available (like 8 GPUs).
I want to modify the existing instance segmentation model to limit the set of classes for prediction **before** prediction. I know how to filter out classes after it, but I want to also speed up model by predicting only a few of 80 COCO categories.
How can I do that?

**Comment by ppwwyyxx** [comment]
The model weights can be modified by using `torch.save/load` as https://detectron2.readthedocs.io/tutorials/models.html#load-save-a-checkpoint mentioned. However I would not recommend doing what you described since it will probably not speed up the model in any visible way.
