### ISSUE TITLE
How to input box coordinates to bypass region proposal for just masking

### ISSUE THREAD

**Issue by ismailsalim** [facebookresearch/detectron2#1775]
Using the `Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml` model config, how could I input box coordinates, to bypass the region proposal generator stage and just obtain the mask of the instance within that box? (I do not require bounding box offset estimation or class prediction - just the mask)

**Comment by ppwwyyxx** [comment]
see https://detectron2.readthedocs.io/modules/modeling.html#detectron2.modeling.GeneralizedRCNN.inference (`detected_instances`).
