### ISSUE TITLE
AttributeError: 'RoIPool' object has no attribute 'aligned'

### ISSUE THREAD

**Issue by songyanbei** [facebookresearch/detectron2#1776]
Hi, I want to convert the pkl to onyx as follows
` ./caffe2_converter.py --format onnx --config-file ../../configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml --output ./  MODEL.WEIGHTS /Users/deepfinch/Downloads/model_final_721ade.pkl MODEL.DEVICE cpu`

the config as follows
`_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "/Users/deepfinch/Downloads/model_final_721ade.pkl"
  MASK_ON: False
  ROI_BOX_HEAD:
    POOLER_TYPE: ROIPool
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("voc_2012_train",)
  TEST: ('voc_2012_val',)`

but has AttributeError
`AttributeError: 'RoIPool' object has no attribute 'aligned'
`

what should I do?

in addition, in the c10.py, Lines 282 to 288,only have the ROIAlignRotated and the RoIAlign, this version not support the ROIPool? thanks！

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
