### ISSUE TITLE
How to obtain the score for unlabeled semantic segmentation class ?

### ISSUE THREAD

**Issue by MGBzH** [facebookresearch/detectron2#1777]
Hello,

I use detectron2 to do semantic segmentation and I am trying to obtain the probability distribution for each pixel. Given an image detectron2 outputs per pixel scores, I can apply a softmax function to obtain a probability distribution per pixel. However I need the "unlabeled/empty/void" probability that corresponds to unlabeled pixels in the train dataset. Is there a way to obtain this probability ? 

Thank you

**Comment by ppwwyyxx** [comment]
Because they are not trained, they are not predicted.
You can train the model to predict "empty", and then the model will be able to predict it.
