### ISSUE TITLE
Model Zoo Downloaded Model Weights for Fine Tuning

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1778]
Hello,

I am trying to not have to access a url in order to download the model weights with the line of code, prior to training on a custom dataset:

>cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml")  

Can I just download the model weights from the model zoo, and set:

> cfg.MODEL.WEIGHTS = /downloaded/model/path 

Is there another or more correct way to access and apply the weights than described above?

**Comment by ppwwyyxx** [comment]
> Can I just download the model weights from the model zoo, and set:

you can and that's a perfect way.

**Comment by svideloc** [comment]
Thanks!
