### ISSUE TITLE
Why does  metrics.json only update every 20 iterations?

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1780]
I am currently working on a hook that implements Early Stopping, and am parsing the metrics.json output to grab my COCO AP score's each time that the cfg.EVAL_PERIOD comes up. However these results don't write to json unless they match up with the 20 iterations which saves the results (I'm not sure where this 20 is coming from):

Example:

If my cfg.TEST.EVAL_PERIOD = 25, I never get the results for the COCO results written to json until the 100th iteration, when I am needing them for the results at 25/50/75/100 and so on. 

I hope this problem makes sense, but I would be happy to try and clarify more.

Thanks for the help!

**Comment by ppwwyyxx** [comment]
20 is the default log interval of [PeriodicWriter](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.hooks.PeriodicWriter) which is a hook enabled by default in `DefaultTrainer` (https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer), along with many other default settings. To change its behavior, you can refer to https://detectron2.readthedocs.io/tutorials/training.html#trainer-abstraction
