### ISSUE TITLE
How I can register my custom components in detectron2?

### ISSUE THREAD

**Issue by Sonaliam** [facebookresearch/detectron2#1781]
For checking a function behavior of PanopticFPN I need to add some statements in panoptic_fpn.py. 
How I can register my new statements or whole file panoptic_fpn.py having small modification with detectron2?

Below are the lines from the file "detectron2\docs\modules\modeling.rst ":
             you'll likely need to find out the smallest registry which contains that line,
             and register your component to that registry.

Model registry is given in this link : https://detectron2.readthedocs.io/modules/modeling.html#model-registries .

But please guide me for how I can register my modified file?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html

**Comment by SonaliAjankar** [comment]
Thank you for your reply.
