### ISSUE TITLE
about  pointrend  train

### ISSUE THREAD

**Issue by zhenghan408** [facebookresearch/detectron2#1783]
train:
cd /path/to/detectron2/projects/PointRend
python train_net.py --config-file configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_1x_coco.yaml --num-gpus 8

Do I have to use 8gpus?

**Comment by ppwwyyxx** [comment]
you don't, but with a different number of GPUs you may need to change other hyperparameters to obtain reasonable results. https://arxiv.org/abs/1706.02677 provides some of these suggestions.
