### ISSUE TITLE
Is keypoint r-cnn belongs to mask r-cnn or keypoint r-cnn is a branch of mask r-cnn?

### ISSUE THREAD

**Issue by WangAQ126** [facebookresearch/detectron2#1784]
Recently, i want to search a method to detect keypoints of a person, and i find the keypoint r-cnn in detectron2. But i did not find the paper of keypoint r-cnn, so i want to know whether the keypoint r-cnn belongs to mask r-cnn or keypoint r-cnn is a branch of mask r-cnn. Please tell me, thanks!

**Comment by ppwwyyxx** [comment]
Keypoint R-CNN is described in https://arxiv.org/abs/1703.06870

**Comment by WangAQ126** [comment]
So the Keypoint R-CNN is the part of Mask R-CNN ？

**Comment by BriFuture** [comment]
The source code of `torchvision.models.detection`,
`KeypointRCNN` is inherited from `FasterRCNN` while `MaskRCNN` is inherited from `FasterRCNN` too, 

I'm not sure whether `Keypoint rcnn` is a part of `Mask rcnn`. 

By the way, how can I train on custom datasets with a model which can train/predict with Mask & Keypoint simultanenously?
