### ISSUE TITLE
is there a way to extract "stuff classes" from images?

### ISSUE THREAD

**Issue by Betovef** [facebookresearch/detectron2#1785]
## ❓ I want to extract pieces of background from an image. However, it looks like "pred_boxes" and "pred_masks" are only attributes for "instances" and not for "panoptic_seg". 

In this case, I want to extract only the house from the image.

**Output after using panoptic segmentation:**
![example](https://user-images.githubusercontent.com/56320553/87746541-b34e3600-c7a5-11ea-93e5-fac8b343c7ec.png)
**Input:**
          masks = outputs["panoptic_seg"].pred_masks.cpu().numpy()
          print(masks)
**Output:**
----> 1 masks = outputs["panoptic_seg"].pred_masks.cpu().numpy()
      2 
      3 print(masks)
      4 
      5 # numcolors = 256

**AttributeError:** 'tuple' object has no attribute 'pred_masks'

## Model Output Format
https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

**Comment by BingEdison** [comment]
example to obtain grey scale output of stuff classes

            predictions, visualized_output = demo.run_on_image(img)  
            panoptic_stuff = predictions["panoptic_seg"]     
            A_stuff = panoptic_stuff[0].cpu().data.numpy()
            cv2.imwrite("/detectron2/outputs/color_img.jpg", A_stuff)

**Comment by Betovef** [comment]
**How do you do `demo.run_on_image(img)` in google colab?** 

I cloned the repo in google colab and I tried:
`!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --input /content/input.jpg --confidence-threshold 0.6 --output color_img.jpg \
  --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl`

It did give me my image with the panoptic segmentation as an output but how do I set `predictors, visualized_output` to that? 
Please let me know if I am missing something. Thank you so much for your help!

**Comment by zhangfusheng-163** [comment]
I get the same problem,but I have solved the problem.You need to add a line of code.

instances = predictor["instances"].to(torch.device("cpu"))
box = instances.pred_boxes if instances.has("pred_boxes") else None
mask = np.asarray(instances.pred_masks)

it is OK

**Comment by ppwwyyxx** [comment]
If you still need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
