### ISSUE TITLE
How can I use lmdb dataset

### ISSUE THREAD

**Issue by ForrestPi** [facebookresearch/detectron2#1786]
##  How to use lmdb dataset using detectron2

warp the ImageFolderLMDB (https://github.com/Fangyh09/Image2LMDB)
But I cannot how to use it in  detectron2

**Comment by j-adamczyk** [comment]
I don't think you can. To use custom format dataset in Detectron2, you have to create a data loader, as in official Detectron2 tutorial / Google Colab notebook. You need annotations file, however, from which you will get information similar to COCO dataset (also look in the Colab notebook to see what data loader gets and where it writes it). I don't see it in this dataset.

**Comment by ppwwyyxx** [comment]
To do that you'll need to use a custom dataloader https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader, where you can implement custom logic to read images.
