### ISSUE TITLE
Is there a way to calculate the area of each mask in the picture when I am doing the Mask R-CNN?

### ISSUE THREAD

**Issue by chengwen-afk** [facebookresearch/detectron2#1788]
attach the area to the images just like this.
![image](https://user-images.githubusercontent.com/62918889/87768913-7179ca00-c84f-11ea-8b35-3ce30da69b5e.png)

**Comment by j-adamczyk** [comment]
The Instances object returns masks as list of points that form a polygon. Therefore, your task is first to calculate the area of polygon given the points, which can be done with many graphics libraries (like OpenCV and contourArea function). Then you have to map the pixels to the scale of the map, at least I think that areas on those images are in scale of the map. This has to be done using the domain knowledge, computer has no idea about the image scale just from the file.

**Comment by chengwen-afk** [comment]
> The Instances object returns masks as list of points that form a polygon. Therefore, your task is first to calculate the area of polygon given the points, which can be done with many graphics libraries (like OpenCV and contourArea function). Then you have to map the pixels to the scale of the map, at least I think that areas on those images are in scale of the map. This has to be done using the domain knowledge, computer has no idea about the image scale just from the file.

Thanks for the reply.  I have done the job for calculating the area of polygon given the points, so do you have any advice on how to get the list of points from a polygon? and how to output the area to the test images ?

**Comment by j-adamczyk** [comment]
> > The Instances object returns masks as list of points that form a polygon. Therefore, your task is first to calculate the area of polygon given the points, which can be done with many graphics libraries (like OpenCV and contourArea function). Then you have to map the pixels to the scale of the map, at least I think that areas on those images are in scale of the map. This has to be done using the domain knowledge, computer has no idea about the image scale just from the file.
> 
> Thanks for the reply. I have done the job for calculating the area of polygon given the points, so do you have any advice on how to get the list of points from a polygon? and how to output the area to the test images ?

I am not sure what you mean by "list of points from a polygon". Instances object returned by predictor (`output["instances"]` in Colab demo) contains `pred_masks` attribute, which should be used for area and/or polygon bound calculation. Outputting the area to test images requires either using built-in Visualizer from Detectron2 (also see the Colab demo for this) or doing it by hand, i. e. creating bit mask bounded by mask points and copying/pasting image using e. g. OpenCV (see https://stackoverflow.com/questions/48301186/cropping-concave-polygon-from-image-using-opencv-python for example).

**Comment by ppwwyyxx** [comment]
The model output format is given in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format. Counting the pixels in an output mask will give you the mask area. How to count is not related to detectron2, unless the output format is not clear enough.

**Comment by shida666** [comment]
Hi,how to creat the label of [area 76365.5] at the bottom of the bbox ?could you please give me some advice?
