### ISSUE TITLE
Use .pth file  in Opencv after caffe conversion

### ISSUE THREAD

**Issue by jbabis007** [facebookresearch/detectron2#1791]
Hello everyone, Here I followed the tutorial 'Detectron2 Beginner's Tutorial' on google colab, without any problems in the end I get the file 'model_final.pth'.
My goal is to be able to use it with opencv, but of course we cannot use it directly, so after several searches I made this conversion 
#---------------------------------CONVERSION .pht TO Caffe --------------------------------------
cfg1 = get_cfg()
cfg1.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg1.DATASETS.TRAIN = ("balloon_train",)
cfg1.DATASETS.TEST = ()
cfg1.DATALOADER.NUM_WORKERS = 2
cfg1.MODEL.WEIGHTS = '/content/output/model_final.pth'  # Let training initialize from model zoo
cfg1.SOLVER.IMS_PER_BATCH = 2
cfg1.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg1.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg1.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg1.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)

model = build_model(cfg1)
DetectionCheckpointer(model).resume_or_load(cfg1.MODEL.WEIGHTS)
data_loader = build_detection_test_loader(cfg1, cfg1.DATASETS.TRAIN[0])
first_batch = next(iter(data_loader))
caffe2_model = export_caffe2_model(cfg1, model, first_batch)
caffe2_model.save_protobuf('CAFFE_Folder')
#----------------------------------------------------------------------------------------------------------------------

after which I get three files: 'model.pb model.pbtxt model_init .pb '.
Unfortunately I still cannot use it in opencv I would like to use one of the functions like 
cv2.dnn.readNetFromCaffe(model.pbtxt, model_init .pb) or something like that.
If someone can help, it's been a week that I have been stuck on this problem

Thank you in advance for your help.

**Comment by ppwwyyxx** [comment]
We do not provide the functionality to use the model in opencv.
