### ISSUE TITLE
can't install: "Could not find a version .."

### ISSUE THREAD

**Issue by IzzyHibbert** [facebookresearch/detectron2#1793]
Hi.

I am using Ubuntu 18.04, where I made a torch installation (1.4+cpu torchvision==0.5+cpu).
Once using the pre-built version with the given command:

`python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.4/index.html`

I am getting 

  Could not find a version that satisfies the requirement detectron2 (from versions: )
No matching distribution found for detectron2

Python is 3.7
Torch 1.4
pycocotools installed

Any idea ?

**Comment by ppwwyyxx** [comment]
The command is either 
```
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.4/index.html
```

or 
```
python -m pip install detectron2 -f  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.4/index.html
```
Your command is incorrect.

If you still need help, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by IzzyHibbert** [comment]
@ppwwyyxx 
No. The command I used was taken from the documentation and is still visible in the paragraph "**Install Pre-Built Detectron2 (Linux only)**" of the official instructions:

[https://detectron2.readthedocs.io/tutorials/install.html](url)

Have a look.
I wrote it in the message, I am using the cpu one not CUDA. 

I am needing support. Thanks

**Comment by ppwwyyxx** [comment]
The one in the official instruction is identical to the first command  in https://github.com/facebookresearch/detectron2/issues/1793#issuecomment-660687676.
It contains two lines, hence different from the command in the original issue.
