### ISSUE TITLE
GPU not supported

### ISSUE THREAD

**Issue by Hasan6979** [facebookresearch/detectron2#1796]
Hello,

I followed the link here to solve the "GPU not supported issue"
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
When I type in  "  python3.6 -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'   "
it gives me output  " True /usr/local/cuda-10.1  "
But when I try to run the code it still gives me the GPU not supported error.
Can you help me debug this ?

Regards,
Hasan

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
