### ISSUE TITLE
NOTE: this interface is experimental.

### ISSUE THREAD

**Issue by wnynotfaker** [facebookresearch/detectron2#1797]
Why are some classes marked with “NOTE: this interface is experimental”. These classes have many parameters, but I did not understand how these parameters are assigned.What does "NOTE: this interface is experimental" mean for these classes?

Hope you can take time to reply。

**Comment by ppwwyyxx** [comment]
It means certain arguments may be changed/renamed, therefore a user should be reminded if using such interface.
