### ISSUE TITLE
Is there any small backbone like VGG16 surpported? Or  Are there tutorials to replace backbone networks due to resource constraints...

### ISSUE THREAD

**Issue by a954217436** [facebookresearch/detectron2#18]
## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met an unexpected error when using detectron2,
please use the "Unexpected Problems / Bugs" issue category instead.

**Comment by ppwwyyxx** [comment]
VGG16 is not small and we don't have small backbones at the moment. We'll add more in the future.

You can replace the backbone with your own ones using `BACKBONE_REGISTRY`. An incomplete tutorial is at https://detectron2.readthedocs.io/tutorials/models.html, we'll add more details to it later.

**Comment by a954217436** [comment]
OK, Thanks a lot! I appreciate your remarkable work!

**Comment by chansongoal** [comment]
Have you solved this problem? And what's the performance after you replace the Res50 with vgg16? Thanks for your help!

**Comment by chansongoal** [comment]
Hi, @a954217436 
  Have you replaced the backbone with VGG16? I am working on this too. Can you give me some suggestions? Appreciate it if you can provide any help!
