### ISSUE TITLE
How to resume training from model zoo with subset of original classes?

### ISSUE THREAD

**Issue by j-adamczyk** [facebookresearch/detectron2#1800]
## ❓ How to do something using detectron2

I want to take model from the model zoo and add more vehicle images to make it more accurate on them. I don't want to lose the existing capabilities, so I want to resume training, not overwrite it (like regular transfer learning like the one with balloons from demo would do). I have dataset in COCO format with only "car" category currently.
How can I do this? If I just copy-paste the COCO dataset categories (so "categories" document will have all 80 categories) and use `resume=True` option for training, will it suffice?

**Comment by ppwwyyxx** [comment]
> If I just copy-paste the COCO dataset categories (so "categories" document will have all 80 categories) and use resume=True option for training, will it suffice?

It can train. We don't want to predict how well a model will work.

One naive way that probably works better is to add your data into COCO dataset and train from there.

In general, how to do this is more of a machine learning question / research question rather than a detectron2 question, since the answer (like the one you provided or I provided above) is unlikely to be specific to detectron2 in any way. If you have decided what to do, but not sure how to use detectron2 to do it, then it may become something we can help with.

**Comment by j-adamczyk** [comment]
@ppwwyyxx my question was actually about how to do it with Detectron2 API, let me reformulate the question a bit:

If I want use the dataset in COCO format with the same classes that were used for Detectron2 object detection, but do NOT want to overwrite the existing model, should the code be like:
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("my_dataset",)  # dataset in COCO format that I've created and registered
cfg.OUTPUT_DIR = os.getcwd()

cfg.DATALOADER.NUM_WORKERS = 4
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.MAX_ITER = 2000
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.05
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 80


trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=True)
trainer.train()
```
This will additionally train the model from the model zoo on my dataset and save it in the execution directory, is that right?

**Comment by ppwwyyxx** [comment]
More precisely, doing the above would not throw any parts of the pre-trained model away during initialization, because the model architecture defined in the config was not modified. Maybe this is what the question is, though "overwrite" is probably not the word I'd use.

**Comment by j-adamczyk** [comment]
Yes, that's precisely what I wanted to know. I just want to continue training the network from the model zoo on my dataset. So I understand that this will do that, thank you.
