### ISSUE TITLE
Difference test train resolution confusing

### ISSUE THREAD

**Issue by DINOUS11** [facebookresearch/detectron2#1802]
From config size when I changed test size as min:480 and max:640 the model still can run with train size min:1333, max:1333 i wonder how can it like that, usually the input size of model should be unchangeable but detectron2 can somehow???

**Comment by ppwwyyxx** [comment]
> usually the input size of model should be unchangeable

In fact, usually the input size of a model can be changed in object detection.

If you still have questions, please choose one [issue templates](https://github.com/facebookresearch/detectron2/issues/new/choose).
