### ISSUE TITLE
Links in dataset documentation don't work

### ISSUE THREAD

**Issue by kubapok** [facebookresearch/detectron2#1806]
Here:

https://github.com/facebookresearch/detectron2/blob/master/datasets/README.md

> A dataset can be used by accessing DatasetCatalog for its data, or MetadataCatalog for its metadata (class names, etc). This document explains how to setup the builtin datasets so they can be used by the above APIs. Use Custom Datasets gives a deeper dive on how to use DatasetCatalog and MetadataCatalog, and how to add new datasets to them.

DatasetCatalog and other links on the page don't work.

**Comment by Himanshunitrr** [comment]
The links don't work because those pages are not yet created. I will create them if I am given information regarding them.
