### ISSUE TITLE
Custom pretrained backbone

### ISSUE THREAD

**Issue by aksub99** [facebookresearch/detectron2#1809]
Hi, I saw that using a custom backbone is possible with detectron2.
I have pretrained weights of a ResNet. Is it possible for me to load in these weights into a backbone of a detectron2 Faster RCNN?
I would then like to finetune this combined model.

**Comment by ppwwyyxx** [comment]
The weights to load before training is set by `cfg.MODEL.WEIGHTS`. The weights have to be named following the naming convention in detectron2's implementation of ResNet. During loading detectron2 will warn if any weights cannot be loaded.
