### ISSUE TITLE
nvidia-apex work not well

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/detectron2#181]

**Comment by mathpopo** [comment]
excuse me,i put nvidia-apex in your code,i hope it can work,can apex use in this code?
(ubuntu16.04 anaconda cuda9.2)

**Comment by mathpopo** [comment]
amp_opt_level = '01' cannot run
default '00' is ok,
amp_opt_level = '02,3 need  input half()

**Comment by ppwwyyxx** [comment]
Apex is not supported yet. And if you failed to add it, that's not something we can help with because it's not a supported feature.

If this is a feature request, it is already covered by #72.
