### ISSUE TITLE
Error when Adding a field to a Instances

### ISSUE THREAD

**Issue by BoomFan** [facebookresearch/detectron2#1810]
Hi, 

First of all. Thanks for your great work!

Now I can train my own network with the help of Detectron2.

## the Issue:
I'm not sure if here is the best place to post my debugging question. But I'm truly helpless, so I feel like I should give it a try.

Here's my code when I do inference at each checkpoint. I got some error message about `val_loss` here:
```
        results = Instances(image_size)
        results.set('scores', pred_prob)
        results.set('pred_classes', cls_idxs)
        if val_loss is not None:
            print("val_loss =", val_loss)
            print("val_loss.flatten() =", val_loss.flatten())
            results.set('val_loss', val_loss.flatten())
```

Everything seems working fine, in fact, it successfully runs for 200 steps already. But when the code do validation again at the 300th step, I get an error message like this:
```
val_loss = tensor(0.4557, device='cuda:0')
val_loss.flatten() = tensor([0.4557], device='cuda:0')
val_loss = tensor(0.4556, device='cuda:0')
val_loss.flatten() = tensor([0.4556], device='cuda:0')
ERROR [07/22 16:03:56 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
....
  File "XXX_model9.py", line 239, in inference
    logit_im = self.inference_single_image(logit, heights[idx], widths[idx], val_loss=val_loss)
  File "XXX_model9.py", line 287, in inference_single_image
    results.set('val_loss', val_loss.flatten())
  File "XXX/detectron2/structures/instances.py", line 73, in set
    ), "Adding a field of length {} to a Instances of length {}".format(data_len, len(self))
AssertionError: Adding a field of length 1 to a Instances of length 0

```

## My question:
I'm a bit confused about why this error happens. My inference process runs smoothly for a few steps already, but it somehow stops without a clear reason. 

My validation set is the same at each checkpoint. Since my code runs successfully for 2 checkpoints already, I assume my validation set is valid. Well, from the log message above, `val_loss` does have value, but the error still shows up. Could you help me guess what might go wrong?

I'm a newbie, so it is also possible that I'm not using `Instances()` correctly. Could you point it out if there's an obvious error in my code, please?

Thanks for your time.

**Comment by ppwwyyxx** [comment]
As the error says, you cannot add data of different length to `Instances`. See https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances
