### ISSUE TITLE
Automate the process of installation

### ISSUE THREAD

**Issue by Diksha0510** [facebookresearch/detectron2#1813]
## 🚀 Feature
A python script to automate the installation process for all the different requirements according to the user's need.

## Motivation & Examples

These days no one wants to do the hardwork, everyone wants things automated and to work at one click. By automating this process of installation users could simply enter their requirement as to how they want detectron2 on their system and the script would do the rest for them.

There are various options for the user as to the way in which he/she wants to install and use detectron2. For example, ithe script will ask the user if he/she wants to build detectron2 from source or use pre-built module and do the rest for them.

**Comment by ppwwyyxx** [comment]
I believe the way we provide installation instructions follows the common practice of most python projects.

Automating the process even more would lead to maintenance challenges including detecting environments, dealing with package management system, different ways to install dependencies on different systems -- none of them related to this project. And meanwhile it provides marginal value only to users who are not familiar with python (which probably won't get much out of this project anyway). I think this is why most python projects do not do this.
