### ISSUE TITLE
Installation problem: ERROR: File "setup.py" not found. Directory cannot be installed in editable mode

### ISSUE THREAD

**Issue by Wang-zipeng** [facebookresearch/detectron2#1814]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote

I just clone the code and did nothing changed.

2. what exact command you run:

I follow the install.md and build Build Detectron2 from Source.
The command is:
git clone https://github.com/facebookresearch/detectron2.git (it's ok)
python -m pip install -e detectron2 (problem from this command)

3. what you observed (including __full logs__):

it's very simple:
just like this:

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:

I have check "setup.py" with "ls" command and I am sure the path is right.  

I can install with the command "python setup.py install". 
 

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
The issue template asked for full logs. Posting them might help others understand the issue.

My guess is it might be due to very old `pip` version.

Closing since it's unlikely this issue is related to detectron2.

**Comment by raymon-tian** [comment]
I alse meet the problem.

**Comment by Kongsea** [comment]
Either in parent folder of detectron2 using `python -m pip install -e detectron2`
or in the folder detectron2 using `python -m pip install -e .` can fix the problem.
