### ISSUE TITLE
Run evaluation on subset of trained classes

### ISSUE THREAD

**Issue by aksub99** [facebookresearch/detectron2#1815]
Hi, I have one dataset containing 29 classes and another containing 10 classes (subset of the 29 used in training).
Is there any way I can evaluate the trained model on the dataset with 10 classes using `COCOEvaluator`?

When I try, I get the error `AssertionError: A prediction has category_id=27, which is not available in the dataset.`

**Comment by aksub99** [comment]
Sorry, managed to get this fixed. Turned out it was an issue with my test dataset annotations.

**Comment by deepakksingh** [comment]
Hello @aksub99. Could you shared how you resolved this issues? Can the dataset annotation have 29 classes but be evaluated on only 10 classes?

**Comment by aksub99** [comment]
Hi @deepakksingh ! Sorry for the delay in getting back.
That was a long time ago so I don't remember exactly. In my case, I had trained on a dataset of 29 classes and had tried to test on another dataset with only 10 classes. This is definitely possible as long as the class_ids in the json annotation file are the same in the 10 classes dataset as was in the 29 classes dataset.
