### ISSUE TITLE
How do I get my model weights in a .pkl or ONNX format as opposed to the default .pth format?

### ISSUE THREAD

**Issue by Engrgit** [facebookresearch/detectron2#1816]
Hello everyone. I have built a Mask-RCNN instance segmentation model using Detectron2. The model was trained on a custom dataset and my output is a .pth file

The model is to be deployed on Azure which requires an output file in the .pkl or onnx format.  

How do I get the model weights in a .pkl or ONNX format as opposed to the default .pth format?

NOTE:
-I trained the model by following the getting started materials using Google Colab and it all worked fine.
-I have tried Pytorch commands to export to onnx but it isn't working
-All I want is the output to be in .pkl or onnx format and not .pth

**Comment by ppwwyyxx** [comment]
`pkl` is not a model format.

https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_converter.py can convert a model to onnx format. However it does not mean it can be deployed on Azure. We do not provide support for deploying models on Azure.
