### ISSUE TITLE
access denied for most densepose annotations / datasets

### ISSUE THREAD

**Issue by thejanzimmermann** [facebookresearch/detectron2#1817]
A lot of the annotations and datasets in densepose projects have access denied at https://dl.fbaipublicfiles.com/.

This is problematic as a lot of papers out there cite these as being openly available. Please provide/restore access to data and code or retract publications/proceedings since it does not allow other outside investigators to replicate the work.

Thank you in advance

Jan

**Comment by ppwwyyxx** [comment]
Please provide __what URLs__ have access denied issue, and why do you expect those URLs to work (i.e., where do they come from).

**Comment by thejanzimmermann** [comment]
https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/densepose/data/datasets/coco.py

All of these paths are dead. Why do I expect these URLs to work? Because papers published by facebook AI refer to them as the datasets used and they are openly available.

**Comment by ppwwyyxx** [comment]
This is a URL to github. Please provide at least one URL under `dl.fbaipublicfiles` that you expect to work and not working.

**Comment by thejanzimmermann** [comment]
https://dl.fbaipublicfiles.com/densepose/data/densepose_evolution/densepose_chimps
https://dl.fbaipublicfiles.com/densepose/data/densepose_evolution/annotations/densepose_chimps_densepose.json

Both are cited in https://research.fb.com/publications/transferring-dense-pose-to-proximal-animal-classes/ and CVPR2020 proceeding as available.

Kind regards

**Comment by ppwwyyxx** [comment]
The URLs above are actually incorrect and not expected to work because the code reads these files from local disk, not from URLs.
@vkhalidov may know where to obtain the densepose evolution dataset

**Comment by thejanzimmermann** [comment]
Fantastic thank you for the help!

**Comment by vkhalidov** [comment]
@thejanzimmermann the densepose evolution sets have not yet been released, we're going to make an official release of DensePose Evolution framework and associated datasets some time soon, please wait for the official announcement
