### ISSUE TITLE
Predicting on new images question

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1819]
## ❓ Predicting on new images question

Hello, I am trying to predict on images using a model that I have trained, but get the following error if I don't specify cfg.DATASETS.TEST = ("boat_train", ) in my config file. 

> IndexError: tuple index out of range

It appears that it is trying to grab a piece of the metadata from the registered coco dataset, but I guess I don't fully understand why, we can't predict without giving the model this information (I am predicting on an image that is not in that registered dataset)

Thanks!

**Comment by Adithia99** [comment]
yeah i want to ask about same question ,how to predict on images using a new model without registered dataset json?, because i follow gilbert tanner video on youtube, he use the registered dataset with  json too, why? if predict we dont need the json extension too why he used it?

and maybe here have to test on video codes?

**Comment by ppwwyyxx** [comment]
I agree that the dataset should not be required. Will update the code to remove the requirement.

Using the model directly (https://detectron2.readthedocs.io/tutorials/models.html#use-a-model) will not require dataset name, though.

**Comment by svideloc** [comment]
Thank you!

**Comment by Adithia99** [comment]
how to load model and test to video or images? without requirment ? 
(https://detectron2.readthedocs.io/tutorials/models.html#use-a-model)
i confused about this hehe 

i used this code before to load model and test images, but still need requirment (json/registered dataset)

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 
cfg.DATASETS.TEST = ("xxx_test", )
predictor = DefaultPredictor(cfg)


from detectron2.utils.visualizer import ColorMode
dataset_dicts = DatasetCatalog.get("xxxl_test")
for d in random.sample(dataset_dicts, 13):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=microcontroller_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()

which one i must change the code to test without requirement ? 
thank you

**Comment by svideloc** [comment]
@Adithia99 You can basically just copy the code from the defaultPredictor class [here](https://detectron2.readthedocs.io/_modules/detectron2/engine/defaults.html#DefaultPredictor), and just don't add the line of code: 

`self.metadata = MetadataCatalog.get(cfg.DATASETS.TEST[0])`

**Comment by ppwwyyxx** [comment]
This is now implemented in master
