### ISSUE TITLE
ModuleNotFoundError: No module named 'portalocker'

### ISSUE THREAD

**Issue by sonaliashish** [facebookresearch/detectron2#1821]
I am building detectron2 from source:
$cd detectron2
$python setup.py install
While installing it is not showing any errors. My installation terminate successfully as follows:
...
Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for detectron2==0.1.3

**But when I import following modules it gives me error line number is given before $:**
5$import detectron2
6$from detectron2.utils.logger import setup_logger
7$setup_logger()

I have already install following package but still it is showing error:
$pip install -U portalocker

**I am facing following error:**

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-22-3caf173b8d0d> in <module>()
      4 
      5 import detectron2
----> 6 from detectron2.utils.logger import setup_logger
      7 setup_logger()
      8 

1 frames

/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py in <module>()
     11 from urllib.parse import urlparse
     12 
---> 13 import portalocker  # type: ignore
     14 from fvcore.common.download import download
     15 

ModuleNotFoundError: No module named 'portalocker'

**Comment by ppwwyyxx** [comment]
Since it complains about `import portalocker`, `portalocker` should be installed but is not.
If you have difficulty installing it, it is not related to detectron2.
