### ISSUE TITLE
Problems when training with small images and testing on large images

### ISSUE THREAD

**Issue by wanttoimprove** [facebookresearch/detectron2#1829]
Hello community,
I am still quite new in this area. 
And got a problem with my model, which i cannot solve. 

I trained my model after the facebook tutorial. 
During the training I use **small pictures (120x120) pixels**. 
However, I want to test my trained weights now on **larger pictures (1200x230 pixels),** which are containing several objects. 
The problem now is, that it detects everything on the small pictures but nothing on the big ones. 

Maybe someone can help me here and give me a hint. 
That would be great
Thanks

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
