### ISSUE TITLE
How to setup nms-threshold?

### ISSUE THREAD

**Issue by memicalem** [facebookresearch/detectron2#1832]
Where can I see what is the value of nms-threshold and how to change it?

**Comment by Jian-Xi** [comment]
Just put the corresponding settings in to your model config file like:

>   RPN:
- NMS_THRESH: 0.7
>   ROI_HEADS:
- NMS_THRESH_TEST: 0.3

There are many available open sources you can start with to dig in.

**Comment by memicalem** [comment]
What exactly is the difference between RPN and ROI_HEADS? How exactly should I do it? I put 
`self._cfg.MODEL.ROI_HEADS.NMS_THRESH_TEST = self._nms_threshold
  self._cfg.MODEL.RPN.NMS_THRESH = self._nms_threshold`
Is this ok, or I need to put different values for those? What happens internally?

> Just put the corresponding settings in to your model config file like:
> 
> > RPN:
> 
> * NMS_THRESH: 0.7
> 
> > ROI_HEADS:
> 
> * NMS_THRESH_TEST: 0.3
> 
> There are many available open sources you can start with to dig in.
