### ISSUE TITLE
how to load trained custom models in  and use it to predict?

### ISSUE THREAD

**Issue by ajaym416** [facebookresearch/detectron2#1834]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
demonstrated in https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 and documented at https://detectron2.readthedocs.io/tutorials/models.html?highlight=DefaultPredictor#use-a-model

**Comment by ajaym416** [comment]
Thank you for your time,
sir, i am a beginner  with less knowledge of coding . As i understood from
the doc provided that we need to format input image  as in
https://detectron2.readthedocs.io/tutorials/models.html#model-input-format ,
but i column't implement it . Could you please give me the example for
doing so , i am just doing the mask detection (with boundary boxes only)

thank you so much for your time.
