### ISSUE TITLE
Easiest way to evaluate image folder?

### ISSUE THREAD

**Issue by mokadyr** [facebookresearch/detectron2#1839]
Hi,
I have directory which contain some images.
I want to evaluate segmentation and detection, but I don't have any annotations nor any additional information.

What is the easiest way to create this "custom" dataset?
In the documentation creating new dataset involving annotations and other additional information which is not necessary, this is seems to be a little complicated for this simple task.

Thanks

**Comment by ppwwyyxx** [comment]
You can loop over each image and make a prediction on it.
See https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 or https://detectron2.readthedocs.io/tutorials/models.html#use-a-model
