### ISSUE TITLE
extract feature then the size is not matched  

### ISSUE THREAD

**Issue by xingxinggui** [facebookresearch/detectron2#1840]
I want to extract features ,but i meet some problems

the code i use is from #5
`rois = pooler(backbone(img),boxes)`

the img shape is torch.Size([1, 3, 185, 330])
the boxes shape is torch.Size([1, 4])

**then i meet this problem:
File: /detectron2/detectron2/modeling/backbone/fpn.py
prev_features = lateral_features + top_down_features
RuntimeError: The size of tensor a (21) must match the size of tensor b (22) at non-singleton dimension 3**

my cfg is:
COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml
model is from model zoo :
https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl

**Comment by xingxinggui** [comment]
> I want to extract features ,but i meet some problems
> 
> the code i use is from #5
> `rois = pooler(backbone(img),boxes)`
> 
> the img shape is torch.Size([1, 3, 185, 330])
> the boxes shape is torch.Size([1, 4])
> 
> **then i meet this problem: File: /detectron2/detectron2/modeling/backbone/fpn.py prev_features = lateral_features + top_down_features RuntimeError: The size of tensor a (21) must match the size of tensor b (22) at non-singleton dimension 3**
> 
> my cfg is:
> COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml
> model is from model zoo :
> https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl

I transform the image size
but i get the roi which is 0 .
torch.max(rois) == 0 ,why ?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by xingxinggui** [comment]
> If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

my full code :
```
import torch
import numpy as np
import cv2

from detectron2.modeling import build_backbone
from detectron2.modeling.poolers import ROIPooler
from detectron2.structures import Boxes
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.structures import ImageList
import detectron2.data.transforms as T

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
aug = T.ResizeShortestEdge(
    [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
    )
cfg.MODEL.WEIGHTS = "model_final_68b088.pkl"
device = torch.device("cuda")
backbone = build_backbone(cfg).to(device)
pooler = ROIPooler(7, (1.0 / 4, 1.0 / 8, 1.0 / 16, 1.0 / 32), 0, "ROIAlignV2").to(device)
images = []
boxess = []
path = "./image_00062.jpg"
img = cv2.imread(path)
image = aug.get_transform(img).apply_image(img)
image = (image - cfg.MODEL.PIXEL_MEAN) / cfg.MODEL.PIXEL_STD
image = torch.from_numpy(image).float().permute(2,0,1)
images.append(image)
image_list = ImageList.from_tensors(images,32)
final_image = image_list.tensor.to(device)
boxes = np.array([120.6725,  45.5401,  48.3484,  20.6242])
print(boxes)
boxes = torch.from_numpy(boxes).float().unsqueeze(0)
boxes = Boxes(boxes).to(device)
boxess.append(boxes)
feature = backbone(final_image)
features = []
features.append(feature['p3'])
features.append(feature['p4'])
features.append(feature['p5'])
features.append(feature['p6'])
rois = pooler(features,boxess)
print(rois.size())
print(torch.max(rois))
```
the output is:
torch.Size([1, 256, 7, 7]) #rois.size()
tensor(0., device='cuda:0', grad_fn=<MaxBackward1>)#torch.max(rois)

**Comment by xingxinggui** [comment]
> > If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
> 
> my full code :
> 
> ```
> import torch
> import numpy as np
> import cv2
> 
> from detectron2.modeling import build_backbone
> from detectron2.modeling.poolers import ROIPooler
> from detectron2.structures import Boxes
> from detectron2.config import get_cfg
> from detectron2 import model_zoo
> from detectron2.structures import ImageList
> import detectron2.data.transforms as T
> 
> cfg = get_cfg()
> cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
> aug = T.ResizeShortestEdge(
>     [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
>     )
> cfg.MODEL.WEIGHTS = "model_final_68b088.pkl"
> device = torch.device("cuda")
> backbone = build_backbone(cfg).to(device)
> pooler = ROIPooler(7, (1.0 / 4, 1.0 / 8, 1.0 / 16, 1.0 / 32), 0, "ROIAlignV2").to(device)
> images = []
> boxess = []
> path = "./image_00062.jpg"
> img = cv2.imread(path)
> image = aug.get_transform(img).apply_image(img)
> image = (image - cfg.MODEL.PIXEL_MEAN) / cfg.MODEL.PIXEL_STD
> image = torch.from_numpy(image).float().permute(2,0,1)
> images.append(image)
> image_list = ImageList.from_tensors(images,32)
> final_image = image_list.tensor.to(device)
> boxes = np.array([120.6725,  45.5401,  48.3484,  20.6242])
> print(boxes)
> boxes = torch.from_numpy(boxes).float().unsqueeze(0)
> boxes = Boxes(boxes).to(device)
> boxess.append(boxes)
> feature = backbone(final_image)
> features = []
> features.append(feature['p3'])
> features.append(feature['p4'])
> features.append(feature['p5'])
> features.append(feature['p6'])
> rois = pooler(features,boxess)
> print(rois.size())
> print(torch.max(rois))
> ```
> 
> the output is:
> torch.Size([1, 256, 7, 7]) #rois.size()
> tensor(0., device='cuda:0', grad_fn=)#torch.max(rois)

I use another simple code ,but the result is 0 .

```
import torch
import numpy as np
import cv2

from detectron2.layers.roi_align import ROIAlign

device = torch.device("cuda")
roi = ROIAlign((7,7), 7.0/224.0, 0).to(device)
path = "./image_00062.jpg"
img = cv2.imread(path)
final_image = torch.from_numpy(img).float().to(device).unsqueeze(0).permute(0,3,1,2)
print(final_image.shape)#torch.Size([1, 3, 185, 330])
boxes = np.array([  0,  120.6725,  45.5401,  48.3484,  20.6242])
boxes = torch.from_numpy(boxes).float().unsqueeze(0).to(device)
print(boxes)
feat_box = roi(final_image, boxes) 
print(feat_box.size()) #torch.Size
print(torch.max(feat_box))#tensor(0., device='cuda:0')
```

**Comment by ppwwyyxx** [comment]
> roi = ROIAlign((7,7), 7.0/224.0, 0).to(device)

The scale parameter causes the boxes to be almost zero. See docs: https://detectron2.readthedocs.io/modules/layers.html#detectron2.layers.ROIAlign

**Comment by ppwwyyxx** [comment]
> cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
aug = T.ResizeShortestEdge(
    [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
    )
cfg.MODEL.WEIGHTS = "model_final_68b088.pkl"
device = torch.device("cuda")
backbone = build_backbone(cfg).to(device)

The weights are not loaded. See https://detectron2.readthedocs.io/tutorials/models.html

**Comment by xingxinggui** [comment]
> > roi = ROIAlign((7,7), 7.0/224.0, 0).to(device)
> 
> The scale parameter causes the boxes to be almost zero. See docs: https://detectron2.readthedocs.io/modules/layers.html#detectron2.layers.ROIAlign

can you tell me how to change the scale ? I change 7.0/224.0 to 1.0 ,the feat_box result is still 0 .

**Comment by ppwwyyxx** [comment]
> boxes = np.array([  0,  120.6725,  45.5401,  48.3484,  20.6242])


The boxes do not follow the documentation either: https://detectron2.readthedocs.io/modules/layers.html#detectron2.layers.ROIAlign.forward

**Comment by xingxinggui** [comment]
> > boxes = np.array([  0,  120.6725,  45.5401,  48.3484,  20.6242])
> 
> The boxes do not follow the documentation either: https://detectron2.readthedocs.io/modules/layers.html#detectron2.layers.ROIAlign.forward
I change the xywh to xyxy ,then is ok,than you ,the another code is also ok
