### ISSUE TITLE
how to visual object detection + instance segmentation in detectron2, just with one colour per label(class)?

### ISSUE THREAD

**Issue by Adithia99** [facebookresearch/detectron2#1843]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:

# We can use `Visualizer` to draw the predictions on the image.
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(out.get_image()[:, :, ::-1])

so i use this code to visual my data, and it give good result, but every new images he give new colour in that so confused to see that

2. what outputs you are expecting:

i want the result just in one colour , for the example person always red, ballon always blue,car always green in every single new images

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
detectron2 object detection+instance segmentation

which codes i must change or add?

**Comment by ppwwyyxx** [comment]
The "SEGMENTATION" drawing mode https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode does something similar to this. You can also use https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances to specify any color you like.

**Comment by Adithia99** [comment]
thanks, i read that docs, but i still got random colour 

import random
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.utils.visualizer import ColorMode
from detectron2.utils.visualizer import Visualizer
dataset_dicts = DatasetCatalog.get("customnew_train")
microcontroller_metadata = MetadataCatalog.get("customnew_train")



for d in random.sample(dataset_dicts, 4):
    img = cv2.imread(d["file_name"])
    v = Visualizer(img[:, :, ::-1], metadata=microcontroller_metadata, scale=1,instance_mode=ColorMode.SEGMENTATION)
    v = v.draw_dataset_dict(d)
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()

i use this code but still got random colour,

how to call ColorMode ?
i make see the parameter just show value (1 value what i want but still get error)

can u make demo, or fix my code above sir?

thanks

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode.SEGMENTATION explains, instances of the same class will have similar (but not the same) color. We don't have a mode that produces same color for every instance. You can also use https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances to specify any color you like.

**Comment by Adithia99** [comment]
oh yeah similar, thank sir, maybe u can make in future about how to make same colour per class, even i specify what colour what i want if still random that gonna be confused :( , thanks a lot

**Comment by untitled-z** [comment]
Hey, you can change the code 'assigned_colors = [random_color(rgb=True, maximum=1) for _ in range(num_instances)]'
to 'assigned_colors = 'black'' , try it!   Or you may need other colors in the matplotlib.colors.

**Comment by Adithia99** [comment]
Dou have the code? U can give me :)

**Comment by Adithia99** [comment]
Is that still random? But in specify colors?
