### ISSUE TITLE
In cocoeval.cpp,  line 483, the localtime_r() can't compile under windows 10

### ISSUE THREAD

**Issue by minan19605** [facebookresearch/detectron2#1848]
In cocoeval.cpp,  line 483, the localtime_r() can't compile under windows 10. Could you please change to another platform-independent function. 

time_t rawtime;
  struct tm local_time;
  std::array<char, 200> buffer;
  time(&rawtime);
  localtime_r(&rawtime, &local_time);
  strftime(
      buffer.data(), 200, "%Y-%m-%d %H:%num_max_detections:%S", &local_time);

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues says:
> Although detectron2 can be installed on windows with some effort (similar to these), we do not provide official support for it.
PRs that improves code compatibility on windows are welcome
