### ISSUE TITLE
How to add a custom data augmentation method?

### ISSUE THREAD

**Issue by wlsdnen** [facebookresearch/detectron2#1849]
I am developing a model using DefaultTrainer and I want to know how to add a custom data augmentation method which i implemented.
I am trying to take two images in a batch, cut an area randomly from one image, and attach it to another image. 
So I need access to all images in the batch. I tried to find a solution from 'https://detectron2.readthedocs.io/' documents, but couldn't find a clue. 
If anyone knows, please let me know how to add this custom data augmentation method to the input pipeline.

**Comment by Adithia99** [comment]
u can use many method to augmentation, u can use make generator to images , or u can augmentation it manually with some method again (zoom rotate shear flip etc) and get the new image in dataset
