### ISSUE TITLE
Can you save model in a different format ?

### ISSUE THREAD

**Issue by arslanan** [facebookresearch/detectron2#185]
Hi, 

After training a model I would like to use it with openCV. 
But it seems there is no openCV net reader for .pth file. 
Is there a way to convert the .pth file or save the model in another format ? 

Also, after reading the documentation I haven't found how to save the cfg object in .yaml format if it is possible. 

Thanks :)

**Comment by ppwwyyxx** [comment]
1. you can `torch.load` a pth file and convert it whatever format you want.
2. `cfg.dump` is provided by the yacs library.

**Comment by arslanan** [comment]
Thank you,

After loading the .pth file with `torch.load`, how do I convert it in another format (.pb for example). I tried `torch.save` but it seems it only save in torch format. 

Thank you so much for the info on the yacs library !

**Comment by ppwwyyxx** [comment]
`torch.load` gives you a dict. With the dict you have full access to the saved weights and therefore can write arbitrary code to do whatever you want.

**Comment by arslanan** [comment]
Thank you ! :)
