### ISSUE TITLE
doubting about evaluate in detectron2 , is this evaluate right in detectron 2? (instance segmentation + object detection)

### ISSUE THREAD

**Issue by Adithia99** [facebookresearch/detectron2#1850]
i was tried Map and IOU AP (evaluate) in ballon dataset, and my custom dataset , i make it with small images to test it,cause want to see how that evaluate work , but im doubting about the  result.
my reason doubting it :
first in ballon dataset i use visualizer to show the test result, so the result is good enough but when i evaluate the Map just give it like 70+ mAP, "i think oh maybe the Map is right because the test images are much" (i cant calculate in logic and manually  it in more detail, cause the images to much for me), then i use my custom dataset and give just 5 images to test , it give very very good in all classes
images (in visualizer) , so i call function too about evaluate my custom dataset but the evaluating isnt good,( i have 5 class , that evaluate just give 2 classes in 80+ and other just 47 ,57,29 (mAP AP) in bbox and segmentation), if we think in more logic the result must be 90++ for all classes , and i test it in Mask-rcnn matterport the evaluate score is about 98 (mAP AP)

maybe someone can help me? i use demo for evaluate in ballon dataset , so it  must be right in command codes, thanks

**Comment by ppwwyyxx** [comment]
I believe the evaluation is correct unless you have evidence otherwise. At the moment I'm not seeing that.

Also, you seem to assume that 70+ mAP is not a good mAP - that is not true.
A 70+ mAP is very good, and a 98 mAP is basically impossible if using the correct definition of mAP commonly used in papers.

**Comment by Adithia99** [comment]
Yeah i know 70+ is good , and 98 basically impossible , because use test data that include in training data that make the Map so good, but i belive about my visual the result so good but give result score like this sir


AP | AP50 | AP75 | APs | APm | APl
-- | -- | -- | -- | -- | --
70.254 | 100.000 | 77.668 | 51.337 | 79.713 | nan
[07/30 03:35:03 d2.evaluation.coco_evaluation]: Some metrics cannot be computed and is shown as NaN. |   |   |   |   |  
[07/30 03:35:03 d2.evaluation.coco_evaluation]: Per-category bbox AP: |   |   |   |   |  
category | AP | category | AP | category | AP
:----------- | :------- | :----------- | :------- | :----------- | :-------
aorta | 57.640 | hole | 45.033 | la | 77.663
lv | 86.832 | ra | 71.287 | rv | 83.069
Loading and preparing results... |   |   |   |   |  
DONE (t=0.00s) |   |   |   |   |  
creating index... |   |   |   |   |  
index created! |   |   |   |   |  
Running per image evaluation... |   |   |   |   |  
Evaluate annotation type segm |   |   |   |   |  
COCOeval_opt.evaluate() finished in 0.00 seconds. |   |   |   |   |  
Accumulating evaluation results... |   |   |   |   |  
COCOeval_opt.accumulate() finished in 0.01 seconds. |   |   |   |   |  
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.650 |   |   |  
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 1.000 |   |   |  
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.787 |   |   |  
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.440 |   |   |  
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.755 |   |   |  
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.673 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.677 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.677 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.470 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.780 |   |   |  
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000 |   |   |  
[07/30 03:35:03 d2.evaluation.coco_evaluation]: Evaluation results for segm: |   |   |   |   |  
AP | AP50 | AP75 | APs | APm | APl
:------: | :-------: | :------: | :------: | :------: | :-----:
64.958 | 100.000 | 78.713 | 43.968 | 75.453 | nan
[07/30 03:35:03 d2.evaluation.coco_evaluation]: Some metrics cannot be computed and is shown as NaN. |   |   |   |   |  
[07/30 03:35:03 d2.evaluation.coco_evaluation]: Per-category segm AP: |   |   |   |   |  
category | AP | category | AP | category | AP
:----------- | :------- | :----------- | :------- | :----------- | :-------
aorta | 58.059 | hole | 29.877 | la | 68.248
lv | 76.416 | ra | 74.079 | rv | 83.069
OrderedDict([('bbox', |   |   |   |   |  

Maybe can u explain little thing from this?... Im sure that my visual images has very very good and that just 5

**Comment by Adithia99** [comment]
Thank for your help

**Comment by ppwwyyxx** [comment]
I don't know what needs to be explained. The results look good.

**Comment by Adithia99** [comment]
Sorry forget to paste all 

{'AP': 70.25412541254124,
           'AP-aorta': 57.64026402640263,
           'AP-hole': 45.03300330033003,
           'AP-la': 77.66336633663367,
           'AP-lv': 86.83168316831683,
           'AP-ra': 71.28712871287128,
           'AP-rv': 83.06930693069306,
           'AP50': 100.0,
           'AP75': 77.66776677667767,
           'APl': nan,
           'APm': 79.71287128712872,
           'APs': 51.336633663366335}),
         ('segm',
          {'AP': 64.95811724029545,
           'AP-aorta': 58.059405940594054,
           'AP-hole': 29.87741631305988,
           'AP-la': 68.24752475247524,
           'AP-lv': 76.4158415841584,
           'AP-ra': 74.07920792079207,
           'AP-rv': 83.06930693069306,
           'AP50': 100.0,
           'AP75': 78.71287128712872,
           'APl': nan,
           'APm': 75.45297029702971,
           'APs': 43.968411126826965})]) 

So this is my classes lv,la,rv, ra, hole, aorta
In the visualisation images it detect all but in result  ap aorta just 58 and holr just 29? Is that normal? 

And im not sure too about ap50 == 100 whats that mean sir? 

Thanks for your help very helpfull :)

**Comment by Adithia99** [comment]
The first doubting in my mind is aorta, in test visualizer it detect 5 aorta of 5 images and the position is good ,almost perfect but just give 58, that make confused i think at least it 70 , even i think it must be 85+ (because i just use small test and result  very good images)

**Comment by ppwwyyxx** [comment]
I couldn't see anything unexpected in the results. Depends on how you perform visualization, it often does not show all predictions. If you want to report anything unexpected, there is an [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) to follow.

I don't think 85+ is a reasonable expectation of AP. You might need to check the definition of AP.

**Comment by Adithia99** [comment]
"Depends on how you perform visualization, it often does not show all predictions"

i just test 5 images , and the visualization  very good, it mean detect (predict) all classes well , that why i doubt about my score result.  why the different with visualization and score is too far? 
("it often does not show all predictions", it show all sir that why i just put 5 images to be evaluate,it gonna be easy to look is this have unexpected or not)

"I don't think 85+ is a reasonable expectation of AP. You might need to check the definition of AP".

u right if we use much data 70 +- is good Map score, but i do with small test data (5) and the visualization good too, so it possible to get High AP, i use demo ballon.py to evaluate  and no change in that codes

i was tried  with faster rcnn,yolo,ssd and "mask rcnn"(matterport), all MAp like going be good in my dataset, then i try detectron2 that very simple,very fast in train (i think it will be beat mask rcnn in matterport haha) , and the result very good (visualization), but in Map score isnt showing that :(

sorry sir ,im here not to do argument with u sir, just want asking about this

**Comment by ppwwyyxx** [comment]
As I said, an mAP of 70 does mean "very good", and maybe close to perfect to human eyes looking at visualization. And you seem to still have an incorrect expectation of mAP. 
Just saying "good" or "bad" does not lead the conversation to anywhere. There is an [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) to provide actual evidence if you have any evidence that the computed AP is incorrect. You can also evaluate using the official [cocoapi](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI).

> faster rcnn,yolo,ssd and "mask rcnn"(matterport)

I don't know what projects they are exactly, but many github projects use the "AP50" or "AP0.5" metric, which your model gets 100 according to the logs.

**Comment by Adithia99** [comment]
> I don't know what projects they are exactly, but many github projects use the "AP50" or "AP0.5" metric, which your model gets 100 according to the logs.

thanks a lot sir, yeah i read about Map.. and many github use ap 50,that's why i always said  100 hehe sorry :)
can i show  label per class but in ap 50? because if i use ap 50 it will give me good result in (ap 50 per label), in that codes it give me ap per label but in generally not in ap50

which code i must change to show ap50 per class or do u have link that i can read? 

and i tried about evaluate object detection but got error when i used the same codes to evalute instance segmentation , ( i know the problem cause the object detection doesnt have masking , but which function i can call to evaluate just object detection  ?


thank you

**Comment by ppwwyyxx** [comment]
`COCOEvaluator` does not compute AP50 per-class. A custom evaluator can extend it to do so.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
