### ISSUE TITLE
Detectron2 Beginner's Tutorial - google colab | install error

### ISSUE THREAD

**Issue by Passinglight** [facebookresearch/detectron2#1851]
Running the second step in the google colab beginner's tutorial produces an error:
The command:
`
assert torch.__version__.startswith("1.5")
!pip install detectron2==0.2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
`

The error:
`AssertionError                            Traceback (most recent call last)`
`<ipython-input-7-861ff6c98666> in <module>()
      1 # install detectron2: (colab has CUDA 10.1 + torch 1.5)
     2 # See https://detectron2.readthedocs.io/tutorials/install.html for instructions
----> 3 assert torch.__version__.startswith("1.5")
      4 get_ipython().system('pip install detectron2==0.2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html')`

Will appreciate any help

**Comment by ppwwyyxx** [comment]
Google Colab upgrade pytorch to 1.6, the version in tutorial is now updated as well.
