### ISSUE TITLE
different performance on pretrained weights between configs url and model_zoo url 

### ISSUE THREAD

**Issue by VadymBoikov** [facebookresearch/detectron2#1858]
I try to finetune object-detection model.

I found, that performance is degraded, if I use config from `detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml`

On the other hand, if I get configs from   `cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))`, finetuning performance is much better.

The only config difference is storage for pretrained backbones:
`https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl` 

vs `detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl`

What is the difference between two pretraining weights? 
And maybe it is reasonable to have only one pretrained model option?

**Comment by ppwwyyxx** [comment]
See https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models
