### ISSUE TITLE
SizeMismatchError

### ISSUE THREAD

**Issue by woctezuma** [facebookresearch/detectron2#1861]
I want to fine-tune [DETR](https://github.com/facebookresearch/detr) on a tiny dataset (`balloon`). I have managed to do so with vanilla DETR. However, I encounter `SizeMismatchError` (height and width values are swapped) when I try with the detectron2 wrapper around DETR.

What would explain the discrepancy between the two versions of DETR?

Is there any reason why the issue would only arise with the wrapper?

## Instructions To Reproduce the Issue:

1. Acquire the `balloon` dataset
2. Convert the annotations from VIA format to COCO format.
3. Fine-tune in a Colab notebook with vanilla DETR: encounter no error.
4. Register the datasets (already in COCO format) with a few lines:
```python
# from detectron2.data.datasets import register_coco_instances
# register_coco_instances("my_dataset_train", {}, "json_annotation_train.json", "path/to/image/dir")
# register_coco_instances("my_dataset_val", {}, "json_annotation_val.json", "path/to/image/dir")
```
5. Fine-tune in another Colab notebook with detectron2/DETR: encounter `SizeMismatchError`.

## Expected behavior:

I would expect the dataset to be interpreted the same way by vanilla DETR and detectron2/DETR, without any error.

The original dataset is in VIA format, so I had to convert it to COCO format. If the problem were with the JSON annotations, the error should arise with vanilla DETR, so I assume the annotations are initially fine, and are still fine after conversion to COCO format.

For using detectron2/DETR, I have to **register** the COCO datasets, so something might happen there, or later.

## Environment:

Google Colab.

## Similar issues:

#213, #863, #788, #933, #1319.

**Comment by woctezuma** [comment]
Alright, it might be a mistake in my data processing, and vanilla DETR worked fine without warning me.

I will close once I am done checking.

**Comment by woctezuma** [comment]
Sorry, my bad!

**Comment by CarlBhy** [comment]
i have solved this question,You can take a look through this link！
https://github.com/facebookresearch/detectron2/issues/2278#issuecomment-802741341

**Comment by Sendeman** [comment]
Hi, in my case it was due to exif metadata which rotates the image, considering you say your width and height are swapped this may also be the case for you. detectron2 uses Pillow to load in the data during shape checking which does the auto rotation, cv2.imread() however doesnt. To fix this take a look at this answer! https://stackoverflow.com/questions/19786301/python-remove-exif-info-from-images
