### ISSUE TITLE
how to use soft label?

### ISSUE THREAD

**Issue by wlsdnen** [facebookresearch/detectron2#1862]
I'm customizing the 'plain_train_net.py' to apply a custom data augmentation method using a batch.

I found out that I can apply the method by taking out the images and labels saved in 'data' variable.

```
with EventStorage(start_iter) as storage:
        for data, iteration in zip(data_loader, range(start_iter, max_iter)):

```
Now, I want to convert the labels to one-hot, then change it to soft-label after applying the data augmentation method.

But I cannot break the shape of the label since it should be fed as an integer.

How can I solve this?

**Comment by ppwwyyxx** [comment]
You can change `data` however you want as long as the model accepts it.
If your data has to be in some format that the model does not accept, you'll need to change the model.

**Comment by wlsdnen** [comment]
I sill don't get it.
could you give me some details?
I tried to refer 'https://detectron2.readthedocs.io/tutorials/write-models.html' this page but it is too abstract.
