### ISSUE TITLE
panoptic  stuff feature extraction

### ISSUE THREAD

**Issue by kaenkogashi** [facebookresearch/detectron2#1863]
Dear Sir,

Thanks for your excellent work!

Describe what you want to do, including:
1. what inputs you will provide, if any:   any pictures from COCO datasets.
2. what outputs you are expecting: I want to extract stuff segmentation features from panoptic model. I have 2 questions.
first,  I extracted stuff segmentation features with code below.  L176's x have torch.Size([1, 54, 200, 272]) in total.
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/semantic_seg.py
L176: x = self.predictor(x)
I remember COCO datasets have 53 stuff. So one of 54 will be nothing  or background. I am wondering if detectron2's panoptic stuff list order is as same as https://github.com/cocodataset/panopticapi/blob/master/panoptic_coco_categories.json,
then number 54 will be nothing  or background. Is this correct?

Second,  if a picture does not have sky stuff, and however I extracted number 40(which is sky) from torch.Size([1, number40, 200, 272]). Then the extracted feature will contains low confidence of sky?

Thank you very much!

**Comment by ppwwyyxx** [comment]
1. The metadata `stuff_classes` of the dataset contains the name of each stuff class.  See https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

2. I'm not sure I understand the question. But hopefully it would be low confidence because otherwise it would be incorrect.
