### ISSUE TITLE
unexpected error using export_torchscript_with_instances

### ISSUE THREAD

**Issue by neverrop** [facebookresearch/detectron2#1865]
Hi, I'm trying to use caffe2_converter.py to export centermask2(https://github.com/youngwanLEE/centermask2) to torchscript and onnx. 
In order to use CenterROIHeads from centermask, I disabled `with self.roi_heads_patcher.mock_roi_heads()`, and trying to use export_torchscript_with_instances to support scripting outputs with Instance object.

I modified caffe2_moddling.py as follows:
```
# line 264
@mock_torch_nn_functional_interpolate()
    def forward(self, inputs):
        if not self.tensor_mode:
            return self._wrapped_model.inference(inputs)
        images = self._caffe2_preprocess_image(inputs)
        features = self._wrapped_model.backbone(images.tensor)
        proposals, _ = self._wrapped_model.proposal_generator(images, features, None)
        # with self.roi_heads_patcher.mock_roi_heads():
        #     detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
        from .torchscript import export_torchscript_with_instances
        fields={'pred_boxes': "Boxes", 'scores': "Tensor", 'pred_classes': "Tensor", 'locations': "Tensor", 'pred_masks': "Tensor", 'mask_scores': "Tensor"}
        self._wrapped_model.roi_heads = export_torchscript_with_instances(self._wrapped_model.roi_heads, fields)
        detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
        return tuple(detector_results[0].flatten())
```
here, I used export_torchscript_with_instances to support script instance, but I got error like:
```
Unknown type name 'Boxes':
  File "/tmp/detectron27e6nbycd/tmpa8oak1iz.py", line 14
self.image_size = image_size

        self.pred_boxes = torch.jit.annotate(Optional[Boxes], None)
                                                      ~~~~~ <--- HERE
        self.scores = torch.jit.annotate(Optional[Tensor], None)
        self.pred_classes = torch.jit.annotate(Optional[Tensor], None).
```
How to fix this, thanks. @chenbohua3

**Comment by chenbohua3** [comment]
Could you please re-organize your codes to make it more clear?

**Comment by neverrop** [comment]
> Could you please re-organize your code to make it more clear?

fixed now.

**Comment by chenbohua3** [comment]
there may be two possible ways to try：
1. decorate the class `detectron2.structures.Boxes` with `@torch.jit.script`
2. add `from detectron2.structures import Boxes` in `detectron2/structures/instances.py`

This may be a bug of pytorch jit, if none of the above approaches succeed, update your pytorch to master version and try he above approaches again.

**Comment by neverrop** [comment]
> there may be two possible ways to try：
> 
> 1. decorate the class `detectron2.structures.Boxes` with `@torch.jit.script`
> 2. add `from detectron2.structures import Boxes` in `detectron2/structures/instances.py`
> 
> This may be a bug of pytorch jit, if none of the above approaches succeed, update your pytorch to master version and try the above approaches again.

thanks, Tried both, still doesnt work. I'll try export to onnx directly instead.

**Comment by FraPochetti** [comment]
Hi @neverrop have you managed to export and (most importantly) re-load back your model to/from ONNX?
