### ISSUE TITLE
Instance Segmentation on thin objects like wires, threads:

### ISSUE THREAD

**Issue by Prabakaran-Chandran** [facebookresearch/detectron2#1869]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:  we have nearly 1000 images for training  like thin wires , ropes , threads, Tires, Wheels
2. what outputs you are expecting: Instance segmentation of these objects 

**Problem**
the model is able to segment the bigger objects like tires and wheels , but segmentation for thin objects are not produced by the model 

Kindly suggest me to overcome - Do I need to change any config things

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
