### ISSUE TITLE
Small object detection

### ISSUE THREAD

**Issue by RishiMalhotra920** [facebookresearch/detectron2#1870]
I know you have closed previous issues similar issues like this before but I have tried them and it doesn't work. I need help with detecting small objects. **Is this even possible with FASTER-RCNN or other algorithms used in this repo?**

https://github.com/facebookresearch/detectron2/issues/1213

I have tried editing the cfg.MODEL.ANCHOR_SCALE and cfg.MODEL.ANCHOR_GENERATOR.SIZES.

I'm working with FASTER-RCNN. Editing the cfg.MODEL.ANCHOR_SCALE makes no difference to the predictions and editing cfg.MODEL.ANCHOR_GENERATOR.SIZES throws errors and leads to ~ 0 predictions by the algorithm.

**Do I have to train these models with these configs?** I have been using your pretrained models and editing cfg.MODEL.ANCHOR_SCALE and cfg.MODEL.ANCHOR_GENERATOR.SIZES on it and they don't seem to work.

Please don't close this issue without answering. I'm in desperate need of help.

**Comment by swessia** [comment]
If you deal with small and dense objects like many remote sensing images, attempt to enlarge cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN, PRE_NMS_TOPK_TEST, POST_NMS_TOPK_TEST, POST_NMS_TOPK_TRAIN and cfg.TEST. DETECTIONS_PER_IMAGE.
If you use coco metrics, make sure COCOeval.Parameters.maxDets includes cfg.TEST. DETECTIONS_PER_IMAGE

**Comment by RishiMalhotra920** [comment]
To be clear, I am trying to detect small people in the given space. 

1. Would you say that when I make these changes to the cfg, I need to retrain the model?
2. Are there any other cfg settings I would need to change for detecting small **people**?

Thanks so much for your help!! It is very much appreciated.

**Comment by ppwwyyxx** [comment]
I understand you need help, but this is not the right place to get such help about how to improve a model. As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
