### ISSUE TITLE
How to creat a new label at the bottom of the bbox in the picture when I am doing the Mask R-CNN?

### ISSUE THREAD

**Issue by shida666** [facebookresearch/detectron2#1872]
creat the new label to the images just like this.

![image](https://user-images.githubusercontent.com/54310344/89608702-6e9b5380-d8a8-11ea-8ee5-bdbbf5e93de8.png)

I want to create a new label ,and I view the code in

detectron2/detectron2/utils/visualizer.py

line 197
def _create_text_labels(classes, scores, class_names):

line 369
labels = _create_text_labels(classes, scores, self.metadata.get("thing_classes", None))

**How should I change the code to create a new label at the bottom  just like [length:xxxxx]?**

**Comment by ppwwyyxx** [comment]
Libraries such as opencv or matplotlib can draw texts on images. Please refer to their documentation. Such a task is not what detectron2 intends to do.

**Comment by shida666** [comment]
> Libraries such as opencv or matplotlib can draw texts on images. Please refer to their documentation. Such a task is not what detectron2 intends to do.

Thanks!
