### ISSUE TITLE
How to use "max_to_keep"

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1873]
Hello,

I am just a little unclear on how to use "max_to_keep" from detectron2.checkpoint.PeriodicCheckpointer. Is this something that I should be specifying in the cfg?

Thanks,
Sam

**Comment by wangg12** [comment]
I think you need to define a config key by yourself or just add `max_to_keep` to where you call `detectron2.checkpoint.PeriodicCheckpointer`.

**Comment by ppwwyyxx** [comment]
@wangg12 's suggestions are great. also a duplicate of #1803
