### ISSUE TITLE
how to compute AP50 per-class in COCOEvaluator (how to custom that) ? (evaluate instance segmentation)

### ISSUE THREAD

**Issue by Adithia99** [facebookresearch/detectron2#1877]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. full code you wrote or full changes you made (`git diff`)
```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("customnew_test", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "customnew_test")
inference_on_dataset(trainer.model, val_loader, evaluator)

i call function like this, i know we must change in cocoevaluator function in detectron2 , but which one line we must change?

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

answer : no error in evaluate AP, but i want to evaluate AP50 per class

**Comment by ppwwyyxx** [comment]
Understanding the code of `COCOEvaluator`, especially `_derive_coco_results` is necessary to modify it. 
If there are any parts of it that lacks enough documentation we may add them. But we are unable to offer help on the level of what exact lines of code to write or change.

**Comment by ppwwyyxx** [comment]
Adding some more details for reference, since this has been asked frequently. 

To evaluate per-class AP50, what it takes is to change this line
https://github.com/facebookresearch/detectron2/blob/e8fa3d6b48794427d6345c9c26d042e498e2b4ef/detectron2/evaluation/coco_evaluation.py#L332
to 
`precision = precisions[0, :, idx, 0, -1] `
