### ISSUE TITLE
How to draw only selected objects using Visualizer

### ISSUE THREAD

**Issue by rathishkumar** [facebookresearch/detectron2#1878]
Hi,

The model producing below outputs:

```
tensor([ 0, 27,  0, 25])
Boxes(tensor([[   4.9951,   34.6096, 1397.0488, 1370.0684],
        [ 919.4078,  924.9739, 1105.8615, 1381.9260],
        [1847.2627, 1264.7670, 1998.6968, 1384.2725],
        [   0.0000,    0.0000,  540.4465, 1290.1216]]))
tensor([0.9979, 0.9967, 0.1391, 0.0575])
```

I need to filter only` class "0"` and its boxes, score and pass it to visualizer. 

My questions are, whether how do I create `list([dict])` with filtered class/classes and pass it to Visualizer.

OR filter while drawing to image, like:
```
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].(pred_classes=="0").to("cpu"))
```

I don't have data/resources to train custom model and I am okay with built-in model.

**Comment by ppwwyyxx** [comment]
See documentation of `instances`: https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances
