### ISSUE TITLE
Layer activations and other layer visualization

### ISSUE THREAD

**Issue by sadransh** [facebookresearch/detectron2#1879]
## ❓ How to do something using detectron2
I want to see Layer activations, Something similar to what is observable in [matterport](https://github.com/matterport/Mask_RCNN#4layer-activations) implementation.
The main reason is that I want to debug and see what is the network seeing. let me know if there is any better way. Thanks.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model
