### ISSUE TITLE
How to use a custom dataset with only keypoint data and no bbox details

### ISSUE THREAD

**Issue by infinityp913** [facebookresearch/detectron2#1880]
## ❓ How to use custom dataset with no bounding box data using detectron2

I want to use a custom dataset that only contains keypoint data but no bbox details.
In the custom data tutorial (https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts), it's said that the annotation dict must have a bbox and bbox _mode properties.

Any suggestion of what I could do in this situation?

**Comment by ppwwyyxx** [comment]
Boxes are required. Maybe you can create boxes from the keypoints.
