### ISSUE TITLE
Unable to export extended model centermask2 to ONNX.

### ISSUE THREAD

**Issue by neverrop** [facebookresearch/detectron2#1884]
Hi, I'm trying to export [centermask2](https://github.com/youngwanLEE/centermask2) to onnx. It's a FCOS head + maskhead. I did some modifications for using caffe2_converter.py. It seems I cannot use the structure Box or Instance in forward functions.
For example, I modified caffe2_modling, my forward function for FCOS only like this:
```
class Caffe2GeneralizedRCNN(Caffe2MetaArch):
    ......
    ......
    def forward(self, inputs):
        images = self._caffe2_preprocess_image(inputs)
        features = self._wrapped_model.backbone(images.tensor)
        proposals, _ = self._wrapped_model.proposal_generator(images, features, None)
        # FCOS result
        inst = proposals[0]
        return inst.pred_boxes.tensor, inst.scores, inst.pred_classes
        # mask result
        # detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
```
I'll get an error by onnx checker:
```
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '1278' has been used as output names multiple times.
```

So I should not use structure Box or Instance in my network? Or anyway else I can fix this, thanks.
@chenbohua3 @ppwwyyxx

**Comment by SarchWu** [comment]
@neverrop hi，have you successfully convert centermask to onnx？
