### ISSUE TITLE
When training custom dataset: SyntaxError: not a TIFF file (header b'' not valid)

### ISSUE THREAD

**Issue by Julymycin** [facebookresearch/detectron2#1885]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
Actually none, I just want to fine-tune the MHPv2 dataset(has been convert to coco instance dataset format) in Mask R-CNN FPN 3x network.
<put diff or code here>
```
2. what exact command you run:
python train_net
3. what you observed (including __full logs__):
```
the training iteration stop, and shows 
SyntaxError: not a TIFF file (header b'' not valid)
but I cannot locate what the wrong image is,
and when I comment line 180 in detectron2/detectron2/data/detection_utils.py: image = _apply_exif_orientation(image), the training iteration goes well.
So I want to confirm what is wrong, the dataset, the training settings, or anything else?
<put logs here>
```
[08/10 11:17:58] d2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/qiu/Projects/detectron2/detectron2/engine/train_loop.py", line 130, in train
    self.run_step()
  File "/home/qiu/Projects/detectron2/detectron2/engine/train_loop.py", line 210, in run_step
    data = next(self._data_loader_iter)
  File "/home/qiu/Projects/detectron2/detectron2/data/common.py", line 142, in __iter__
    for d in self.dataset:
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiu/Projects/detectron2/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/qiu/Projects/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/qiu/Projects/detectron2/detectron2/data/dataset_mapper.py", line 123, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.image_format)
  File "/home/qiu/Projects/detectron2/detectron2/data/detection_utils.py", line 181, in read_image
    image = _apply_exif_orientation(image)
  File "/home/qiu/Projects/detectron2/detectron2/data/detection_utils.py", line 140, in _apply_exif_orientation
    exif = image.getexif()
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/PIL/Image.py", line 1312, in getexif
    self._exif.load(exif_info)
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/PIL/Image.py", line 3316, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 467, in __init__
    raise SyntaxError("not a TIFF file (header %r not valid)" % ifh)
  File "<string>", line None
SyntaxError: not a TIFF file (header b'' not valid)

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```
sys.platform            linux
Python                  3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
numpy                   1.18.5
detectron2              0.2 @/home/qiu/Projects/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   sm_61
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.5.1 @/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1080 Ti
CUDA_HOME               /usr/local/cuda-10.1
Pillow                  7.2.0
torchvision             0.6.0a0+35d732a @/home/qiu/anaconda3/envs/de2/lib/python3.7/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200716
cv2                     4.3.0
----------------------  -------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
`Pillow` cannot correctly parse certain images in your dataset. You can locate the image that fails:
```
PIL.Image(file_name).getexif()
```
and report to Pillow.

We could catch and ignore such exception.

**Comment by Julymycin** [comment]
Thanks, @ppwwyyxx , I locate those images caused this error. Well, since the number of them seems to be too big, you said that you could catch and ignore such exception, could you please tell me how to do so?

**Comment by ppwwyyxx** [comment]
exceptions are now ignored in https://github.com/facebookresearch/detectron2/commit/a3716115021010837ed6e7f8f0fc43691f4d0112#diff-a064d139ecb038a8512cfc14ac3bfa16

**Comment by tian-design** [comment]
I also encountered such a mistake, can you tell me how you solved it，please

**Comment by Julymycin** [comment]
@tian-design well，just locate and ignore those images 


> exceptions are now ignored in [a371611#diff-a064d139ecb038a8512cfc14ac3bfa16](https://github.com/facebookresearch/detectron2/commit/a3716115021010837ed6e7f8f0fc43691f4d0112#diff-a064d139ecb038a8512cfc14ac3bfa16)
