### ISSUE TITLE
How to modify config file to use smaller images ?

### ISSUE THREAD

**Issue by EsraNT** [facebookresearch/detectron2#1887]
##  ❓ How to modify the input sizes in config file using detectron2 

Hello, 
I am trying to run Deeplab, and as I don't have enough memory I wanted to ask:
1. How to modify correctly the min_size_train/test, max_size_train/test and crop size to train on image with size max 256*256?
2. I obtained errors such as ` pool_kernel_size must be divisible by the shape of inputs. Input size: torch.Size([13, 16]) pool_kernel_size: (16, 16)`   when trying by myself.
Can you give me some advices ?

Thank you,

**Comment by XiaoSong9905** [comment]
For (1), I believe d2 currently only supports resize shorter edge. the min_size/max size in the configuration file are used by default Mapper.  if you want a square input / double constrain (both image size smaller than some value), I recommend build ur own mapper. and have 

```python
data_loader = build_detection_train_loader(cfg, mapper=NewMapper(cfg, is_train=True, dataset_name=cfg.DATASETS.TRAIN[0]))
```

**Comment by EsraNT** [comment]
@XiaoSong9905 Thank you for your suggestion, I will give it a try.

**Comment by EsraNT** [comment]
By using build_detection_train_loader, I managed to modify the size of the images  but I keep having the error concerning the pool_kernel_size ` ValueError:pool_kernel_size must be divisible by the shape of inputs. Input size: torch.Size([32, 32]) pool_kernel_size: (32, 64) `. Does the pool_kernel_size should also be modified and will it affect the performance ?
Thank you

**Comment by ppwwyyxx** [comment]
deeplab first do resize using `MIN_SIZE_TRAIN`, then crop the image to `CROP.SIZE`. This strategy is written in its `train_net.py`.
