### ISSUE TITLE
Train model using multiple gpu

### ISSUE THREAD

**Issue by ranyaphat29** [facebookresearch/detectron2#1889]
## ❓ How to do something using detectron2

How I train model using multiple gpu via config setting like config below?
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("dataset_train",)
cfg.DATASETS.TEST = ("dataset_val",)
cfg. GPU xx

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/getting_started.html#training-evaluation-in-command-line
