### ISSUE TITLE
Limiting the training BBox visualisation to the best prediction per instance.  

### ISSUE THREAD

**Issue by mbary** [facebookresearch/detectron2#1891]
## ❓ How to do something using detectron2

When using the  ```cfg.VIS_PERIOD```
We obtain 20 (by default as hardcoded in rcnn.py) bbox proposals. 
Instead, I would like the visualisation to be X bbox props for X instances in an image; i.e. 1 best prediction per instance.

So my questions are:
 1) Will setting ``` max_vis_prop = X``` get me props with the highest probabilities or do we have to perform non-max suppression at some point?

2) would setting ``` max_vis_prop = len(input['instances']``` dynamically change the max_vis_prop depending on the number of instances in an image?

Thank you!

**Comment by mbary** [comment]
Currently, I am getting the desired number of bboxes, however they are often for a single instance (3 instances in an image, I get 3 bboxes but all 3 on 1 instance).

**Comment by ppwwyyxx** [comment]
1. yes
2. yes

They are often for a single instance likely because they are the top proposals and the code currently visualizes top proposals. If you'd like to visualize something else you'll need to implement them.
