### ISSUE TITLE
Getting parameters/augmentation from TensorMask paper

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#1892]
Hi Everyone,

for a university project I need to detect objects on a custom dataset, using the same parameter settings mentioned in the TensorMask paper [https://arxiv.org/pdf/1903.12174.pdf](url) . There are some mentioned explicit like learning rate and warum up iterations. The authors refer, for the not explicit mentioned parameters, to Detectron1.  [https://github.com/facebookresearch/detectron](url)
But where can I find the parameters there? 
Is the 6X config from [https://github.com/facebookresearch/detectron2/tree/master/projects/TensorMask](url) holding all parameters set in the experiments described in the paper? 
Is there also a source I can find all the augmentation used by the authors of the TensorMask paper? Since it's rarely described in the paper.

Thanks a lot

**Comment by ppwwyyxx** [comment]
The configs in https://github.com/facebookresearch/detectron2/tree/master/projects/TensorMask/configs will reproduce what's used in the paper. You can learn about configs at https://detectron2.readthedocs.io/tutorials/configs.html

**Comment by Bamil** [comment]
Thank you !

Could you may give any further information about the augmentation used by the authors?

Regards

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/b6eae861188e30496c1eeb700717ba4db344d72c/detectron2/data/detection_utils.py#L565

They are not the same.
