### ISSUE TITLE
General Question on Fine Tuning Models

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1898]
When we are training on new data & using the detectron pre-trained models, what parts of the model actually end up getting trained when we are training on the new data?

This may not be the correct place to ask this question, but I can't seem to find it in the docs.

**Comment by ppwwyyxx** [comment]
For any pytorch model, the answer is `print([name for name, x in model.named_parameters() if x.requires_grad])`. In detectron2 it depends on the config file that's used to build the model.
