### ISSUE TITLE
cityscapes_fine_sem_seg_val dataset will report KeyError: 'image_id'

### ISSUE THREAD

**Issue by leftthomas** [facebookresearch/detectron2#190]
## To Reproduce

1. Use config file `semantic_R_50_FPN_1x.yaml`
2. Change datasets and eval period
```
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
TEST:
  EVAL_PERIOD: 30
```
3. Run `cityscapesscripts/preparation/createTrainIdLabelImgs.py` to generate `labelTrainIds.png` for cityscapes dataset.  
4. 
```
python tools/train_net.py --config-file configs/semantic_R_50_FPN_1x.yaml --num-gpus 8
```
It will report `KeyError: 'image_id'`
<img width="846" alt="QQ20191029-110631@2x" src="https://user-images.githubusercontent.com/9991443/67734540-50144c00-fa3c-11e9-91f2-e936ffa2beac.png">

## Environment

------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                     1.17.2
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1a0+d94043a
CUDA available            True
GPU 0,1,2,3,4,5,6,7       Tesla V100-SXM2-32GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.0
cv2                       4.1.1
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Thanks for reporting this. We currently only have instance segmentation support on cityscapes, but this issue for semantic segmentation will be fixed soon.

**Comment by leftthomas** [comment]
@ppwwyyxx does it support `VOC` semantic segmentation now?

**Comment by ppwwyyxx** [comment]
No. Also instance segmentation only.

**Comment by leftthomas** [comment]
@ppwwyyxx does it will support `VOC` semantic segmentation in the near future? Meanwhile,  I also find it doesn't support `poly learning rate policy`, and we can't set `multi scales` for image preprocess, we only could set `multi sizes`. But sometimes we don't know the original image size, we only want to set scales and then crop them. So these features may be add to the library soon, any plan for that? Thanks!

**Comment by ppwwyyxx** [comment]
We only add features that we use. But you can add your own features by extending detectron2: https://detectron2.readthedocs.io/tutorials/extend.html
