### ISSUE TITLE
Pointrend doeas eveluation on train data. 

### ISSUE THREAD

**Issue by Adblu** [facebookresearch/detectron2#1900]
For some reason when I start:
```
python train_net.py --config-file config/pointrend_rcnn_R_50_FPN_3x_coco.yaml --eval-only MODEL.WEIGHTS /home/user/data/output/model_0006199.pth
```

Where do I change this so it will make evaluation only on test set ?

**Comment by ppwwyyxx** [comment]
It does evaluation only on test set

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
