### ISSUE TITLE
How to inference a video from .pth model?

### ISSUE THREAD

**Issue by gauthampkrishnan** [facebookresearch/detectron2#1903]
How to do inference on a video from a .pth model file which is generated while training using Detectron2.??

Please respond someone. The detectron2 is a good library but without knowing the proper way of inference of custom trained dataset its not useful so please someone help me on how to do inference on a video using generated .pth model file.

**Comment by ppwwyyxx** [comment]
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 shows how to inference on an image.

Users can inference on a video by inference on every image frame in the video.
