### ISSUE TITLE
TTA inference in Colab tutorial

### ISSUE THREAD

**Issue by RomRoc** [facebookresearch/detectron2#1904]
I created a colab notebook to train a model using custom coco dataset, very similar to [tutorial.](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) 

I tried a lot to add TTA when I run inference, but I can't find the way to do it. I read in this [post](https://github.com/facebookresearch/detectron2/issues/1520)  I shouldn't use DefaultPredictor because it doesn't perform TTA on inference.
How should I modify "Inference & evaluation using the trained model" in colab tutorial to run TTA inference ? I think it can be useful to other users too.

Thanks

**Comment by ppwwyyxx** [comment]
Create the TTA model: https://detectron2.readthedocs.io/modules/modeling.html#detectron2.modeling.GeneralizedRCNNWithTTA
And call it following its API. It's input and output format is documented in https://detectron2.readthedocs.io/tutorials/models.html#use-a-model
