### ISSUE TITLE
Meaning of variables

### ISSUE THREAD

**Issue by RishiMalhotra920** [facebookresearch/detectron2#1905]
What do the following terms in the cfg mean and what are they used for?  I can't find explanation for the following words in the documentation.

cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN, PRE_NMS_TOPK_TEST, POST_NMS_TOPK_TEST, POST_NMS_TOPK_TRAIN and cfg.TEST. DETECTIONS_PER_IMAGE.

**Comment by Kevin-Delnoije** [comment]
if you fully want to understand it i suggest reading the faster-rcnn paper.
here is a TLDR version which i think is correct:
RPN: region proposal network, find regions where there is a object of interest (class agnostic)
TOPK: selects K detections with highest confidence
NMS: algorithm to remove overlapping bounding boxes, the threshold determines how much overlap is acceptable

**Comment by RishiMalhotra920** [comment]
Thanks for your response. 

1. If I set cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN = 1000, Does that mean faster-rcnn will detect a max of 1000 detections?
2. What's PRE and POST gotta do with all of this?

**Comment by Kevin-Delnoije** [comment]
1. Yh I think it will pick 1000 objects with highest score
2. Before and after the component respectively

**Comment by RishiMalhotra920** [comment]
Thanks for your response.
Im not sure I understand the answer to 2. above. Could you explain it in a little more detail?

**Comment by ppwwyyxx** [comment]
Explaining how a model works is not a [type of question](https://github.com/facebookresearch/detectron2/issues/new/choose) that we provide support for since it's not specific to detectron2. As @Kevin-Delnoije  helpfully point out, you can find more detailed explanation in papers
