### ISSUE TITLE
How to write model to Google Drive while training?

### ISSUE THREAD

**Issue by keremnymn** [facebookresearch/detectron2#1908]
Hello, first of all thank you very much for all the efforts given into this awesome system.
I'd like to write all the output file contents to Google Drive while training in order not to lose the trained files since the training takes too much time and Google Colab kicks me out.
Could you please explain how to do it?

Thanks in advance.

**Comment by reubenwenisch** [comment]
You can try saving checkpoints while training. check this [link](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html#:~:text=To%20save%20multiple%20checkpoints%2C%20you,tar%20file%20extension.) out

**Comment by ppwwyyxx** [comment]
Detectron2 save outputs in the output directory during training. Other tools may be used to copy them to other places but that's not related to detectron2.
