### ISSUE TITLE
Keypoint RCNN

### ISSUE THREAD

**Issue by hazemy** [facebookresearch/detectron2#1914]
As far as I understand (please correct me if I am wrong), "keypoint-rcnn" model is just a mask rcnn with only the 'mask' head (which **directly** does the instance segmentation). I already read the mask rcnn paper (https://arxiv.org/abs/1703.06870) and it is supposed to detect a one-hot mask per keypoint, so no bbox was used. So the question is: Why does "keypoint-rcnn" models in detectron2 require the 2D bbox as input? Is "keypoint-rcnn" even a mask rcnn variant?

**Comment by ppwwyyxx** [comment]
Explaining the mechanism of a well-known model is not a [type of question](https://github.com/facebookresearch/detectron2/issues/new/choose) that we provide support for since it's not specific to detectron2.

**Comment by hazemy** [comment]
@ppwwyyxx However, this is Not a 'well-known' model to begin with. There is no model named 'keypoint rcnn'. My question is simple: are the models in detectron2 named 'keypoint rcnn' referring actually to a modified 'mask rcnn' model (for keypoint detection)?

**Comment by ppwwyyxx** [comment]
It refers to the model described in Sec 5 of https://arxiv.org/pdf/1703.06870.pdf
