### ISSUE TITLE
PyTorch 1.6, Detectron 0.2.1, CPU build, "This overload of nonzero is deprecated"

### ISSUE THREAD

**Issue by apiszcz** [facebookresearch/detectron2#1916]
At the inference step shown below an error is generated.
```
Pytorch 1.6, Detectron 0.2.1, Ubuntu 20.20
Pip install of Pytorch CPU
pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html 
```

```
(Pdb) import detectron2
(Pdb) detectron2.__version__
'0.2.1'
```

```
# code/call line
outputs = predictor(imga) 
```
UserWarning message
```
/usr/local/lib/python3.8/dist-packages/detectron2/layers/wrappers.py:226: UserWarning: This overload of nonzero is deprecated:
        nonzero()
```

**Comment by ppwwyyxx** [comment]
It's expected due to https://github.com/pytorch/pytorch/issues/38718

**Comment by meetgandhi123** [comment]
> It's expected due to [pytorch/pytorch#38718](https://github.com/pytorch/pytorch/issues/38718)

Is there any solution for the warning also, is it possible that because of the warning the processing time increase for detection2?

**Comment by meetgandhi123** [comment]
> It's expected due to [pytorch/pytorch#38718](https://github.com/pytorch/pytorch/issues/38718)



> At the inference step shown below an error is generated.
> 
> ```
> Pytorch 1.6, Detectron 0.2.1, Ubuntu 20.20
> Pip install of Pytorch CPU
> pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html 
> ```
> 
> ```
> (Pdb) import detectron2
> (Pdb) detectron2.__version__
> '0.2.1'
> ```
> 
> ```
> # code/call line
> outputs = predictor(imga) 
> ```
> 
> UserWarning message
> 
> ```
> /usr/local/lib/python3.8/dist-packages/detectron2/layers/wrappers.py:226: UserWarning: This overload of nonzero is deprecated:
>         nonzero()
> 
If you want to avoid the warning message do change the code, (https://github.com/facebookresearch/detectron2/pull/1974). I changed this 2 files and it's working perfectly on my server. 

(torch version 1.6.0+cpu)

**Comment by ppwwyyxx** [comment]
There will be no more warnings after https://github.com/pytorch/pytorch/commit/b66ac1e92886a23126d5c29b4ee87466d5bf96a6
