### ISSUE TITLE
How to pass weight parameter to DeepLabCE  function?

### ISSUE THREAD

**Issue by smalgireddy** [facebookresearch/detectron2#1918]
Thank you so much the for the Project, 
In DeepLab project, there is DeepLabCE class i.e. https://github.com/facebookresearch/detectron2/blob/09c4fa90bb9266214e2869e58eb462af0b99c1f1/projects/DeepLab/deeplab/loss.py#L20 with loss functions with 'weight' parameter of size num_classes to calculate the weighted loss. But in DeepLab model i.e. projects/DeepLab/deeplab/semantic_seg.py at https://github.com/facebookresearch/detectron2/blob/09c4fa90bb9266214e2869e58eb462af0b99c1f1/projects/DeepLab/deeplab/semantic_seg.py#L168  and at https://github.com/facebookresearch/detectron2/blob/09c4fa90bb9266214e2869e58eb462af0b99c1f1/projects/DeepLab/deeplab/semantic_seg.py#L313 there is no option to pass the weight parameter. Is there anyway to pass the weight parameter to loss function as I have very imbalanced dataset to train. Thank you.

**Comment by ppwwyyxx** [comment]
You can implement your own version (or a subclass) of the head and call loss functions in custom ways. e.g. https://detectron2.readthedocs.io/tutorials/write-models.html
