### ISSUE TITLE
How to write a demo for PointRend? 

### ISSUE THREAD

**Issue by xixixijie** [facebookresearch/detectron2#1919]
I try to copy the demo.py in detectron2/demo/demo.py, and modify the config_file and weights with pointrend_rcnn_R_50_FPN_3x_coco.yaml and the model_final.pth, but I get an KeyError: 'Non-existent config key: MODEL.ROI_MASK_HEAD.FC_DIM' when cfg = setup_cfg(args) line123 and cfg.merge_from_file(args.config_file)

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/configs.html#configs-in-projects

**Comment by xmlyqing00** [comment]
> https://detectron2.readthedocs.io/tutorials/configs.html#configs-in-projects

Thank you for your reply. It solved my problem too.

**Comment by wowoyuding** [comment]
> > https://detectron2.readthedocs.io/tutorials/configs.html#configs-in-projects
> 
> 谢谢您的回复。它也解决了我的问题。

你是怎么解决的，我也遇到同样的问题

**Comment by xmlyqing00** [comment]
> > > https://detectron2.readthedocs.io/tutorials/configs.html#configs-in-projects
> > 
> > 
> > 谢谢您的回复。它也解决了我的问题。
> 
> 你是怎么解决的，我也遇到同样的问题

Use this method to add the config file.

cfg = get_cfg()    # obtain detectron2's default config
add_pointrend_config(cfg)  # add pointrend's default config
