### ISSUE TITLE
Registering custom coco dataset. Thing classes not in metadata

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#1922]
I have a custom dataset in the MS COCO format. However when I try to register the dataset, the metadata does not add the thing_classes and mapping etc. Following the tutorials, this was how I tried to register the data:

```
data_dir = "/home/an1/datasets/custom"
for d in ["train", "val"]:
    register_coco_instances("custom1_" + d, {}, data_dir + '/annotations/instances_{}.json'.format(d), data_dir + '/images/{}/'.format(d))
```
But when I check the metadata, thing_classes is not added
```
>> MetadataCatalog.get('custom1_train')
Metadata(evaluator_type='coco', image_root='/home/an1/datasets/custom/images/train/', json_file='/home/an1/datasets/custom/annotations/instances_train.json', name=custom1_train')
```

Would you happen to know why this is the case?

Edit: I do know that we are able to manually set the thing_classes field via `MetadataCatalog.get('custom_train').thing_classes = ['a', 'b' ..]`. However my dataset has a lot of categories and I would prefer them to be read from the json file.

**Comment by ppwwyyxx** [comment]
The annotation file is probably not in the correct format. Class name information should be in the json file and you can take the official COCO dataset for example.
If you believe your data is correct and detectron2 is not, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment]
Oh, the more likely possiblity is that the json file is not loaded at all. Registering the dataset will not load it and therefore class information is not known. Calling the dataset with `DatasetCatalog.get` will load it, after which class name should be available.

**Comment by ashnair1** [comment]
That was exactly the case. After calling `DatasetCatalog.get` the class_names were available.
