### ISSUE TITLE
Learning rate 0.

### ISSUE THREAD

**Issue by Adblu** [facebookresearch/detectron2#1923]
Im training PointRend on my own custom dataset. Here is what I see after some time:

```
[08/13 20:37:42] d2.utils.events INFO:  eta: 1 day, 8:46:57  iter: 4239  total_loss: 1.085  loss_cls: 0.101  loss_box_reg: 0.094  loss_mask: 0.532  loss_rpn_cls: 0.126  loss_rpn_loc: 0.210  time: 4.5741  data_time: 0.0205  lr: 0.000000  max_mem: 7119M
```
Value for learning rate is: ```  lr: 0.000000  ```

Here are configurations: 
```
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.GAMMA = 0.01
cfg.SOLVER.MOMENTUM = 0.9
cfg.SOLVER.WEIGHT_DECAY = 0.0001
cfg.SOLVER.STEPS = (500, 1000)
cfg.SOLVER.WARMUP_FACTOR = 1.0 / 1000
cfg.SOLVER.WARMUP_ITERS = 500
cfg.SOLVER.WARMUP_METHOD = "linear"
```

Is it really 0 ? or it is just displayed like that ? How can I configure logger to see all digits ?

**Comment by ppwwyyxx** [comment]
It's displayed like that.

> How can I configure logger to see all digits ?

You can't configure it but can use custom ones as https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.events.CommonMetricPrinter says. But the class can be improved to show significant digits.

**Comment by ppwwyyxx** [comment]
resolved by https://github.com/facebookresearch/detectron2/commit/8d2f3eb310b4f59b48ac57921e409d77bec87060
