### ISSUE TITLE
Run inference on data_loader object iterating in a loop for batch_size more than 1

### ISSUE THREAD

**Issue by gsrivas4** [facebookresearch/detectron2#1924]
I am trying to run inference on coco-like dataset on object detection model. I want to get the RoI features and bounding box coordinate results. The input is a batch of images. I have loaded the coco dataset in a data_loader object as below:
```
from detectron2.data import (
    MetadataCatalog,
    build_detection_test_loader,
    build_detection_train_loader,
)
data_loader = build_detection_test_loader(cfg, dataset_name)
```

Now I am iterating through data_loader object using a loop, as below:
```
for batch_data in data_loader:
    model.eval()
    batch_outputs = model(batch_data) # The model outputs pred_boxes which is one of the output I am interested in.
    
    # Next I am trying to get the ROI pooled output based on the suggestion here - https://github.com/facebookresearch/detectron2/issues/5#issuecomment-540932497.
    from detectron2.modeling import build_backbone
    from detectron2.modeling.poolers import ROIPooler 
    backbone = build_backbone(cfg)
    pooler = ROIPooler(...)
    rois = pooler(backbone(NCHW_images), [kx4 tensors]) 
```

Below are my queries:
- Is iterating through the data_loader, as I am doing, the correct way to do? I am not using the abstract way to run inference as mentioned plain_train_net.py and train_net.py as I need to get more than one outputs from the network for the same batch of images.
- `build_detection_test_loader` function seems to take one image as an input. How can I change this to multiple images?
- Is there a better way to get output from both ROI pooling layer and predicted bounding boxes by running inference only once? Here, I am running the inference twice for both the outputs.

If there are example code, tutorials which have done similar to what I am trying to do, that would be great.

**Comment by ppwwyyxx** [comment]
1. yes
2. It's not supported as https://detectron2.readthedocs.io/modules/data.html#detectron2.data.build_detection_test_loader says, so writing some custom code will be needed
3. You can continue to compute `pred_boxes` from `rois` so no compute is waste. https://pytorch.org/tutorials/beginner/former_torchies/nnft_tutorial.html#forward-and-backward-function-hooks can also be useful

**Comment by gsrivas4** [comment]
thanks for the reply. About the second point, are there any example code, etc. that I can follow to modify the code for batch_size greater than 1.
