### ISSUE TITLE
Add error msg to config

### ISSUE THREAD

**Issue by jcpayne** [facebookresearch/detectron2#1925]
I discovered the hard way that if you use a colon instead of an equals sign when setting the configuration values, Detectron silently ignores the command and just uses the default instead.  It would be nice if it threw an error if a supplied value was being ignored (I'm not sure whether to submit this as a feature request, but it is so minor that I put it here instead).  

## Instructions To Reproduce the Issue:
Example:
cfg.SOLVER.BASE_LR: 003 #No error -- the value is just ignored and Detectron2 uses the default instead (.001)
cfg.SOLVER.BASE_LR = .003 #Now it works

## Expected behavior:
It would throw an error or warning that the supplied value is being ignored.

## Environment
I built the config in memory instead of putting it all in a file (I imported the default file using cfg = get_cfg(), and then set values as shown above--only I mixed equals signs and colons by mistake).

I admit it's a stupid mistake, but it took me a long time to notice that something was wrong, and other users may make the same mistake.

**Comment by ppwwyyxx** [comment]
```
cfg.SOLVER.BASE_LR: 003
```
is valid python syntax and I think it has no effect to anything detectron2, therefore I don't think it can be possibly detected by detectron2. If you have any working suggestion feel free to let us know.
