### ISSUE TITLE
Possible multi-task network

### ISSUE THREAD

**Issue by simonsapiel** [facebookresearch/detectron2#1929]
How to do something❓

I'm currently in the process of training a instance segmentation network for a dataset which consist of samples looking as follows:

![sample](https://user-images.githubusercontent.com/61185966/90606923-2dd8fe00-e209-11ea-90c7-bf91a4faef10.png)

However the network isn't capable of predicting the walls nor the edges of the doors which are both annotated. I'm quite sure the reason for this is that the bounding boxes in both cases don't have any width to them. 

From here I was left thinking that should I instead use keypoint detection here for the endpoints of both the walls and the door edges? 

If that is the case how should one go about this with detectron2?   

Here is a sample (walls) of the dataset I'm using to create the needed dicts:

```python

    xmin    ymin    xmax    ymax    category_id width   height
30  45.0    58.0    45.0    520.0   wall         0.0    462.0
31  45.0    58.0    754.0   58.0    wall         709.0  0.0
32  302.0   58.0    302.0   520.0   wall         0.0    462.0
33  563.0   58.0    563.0   520.0   wall         0.0    462.0
34  626.0   58.0    626.0   257.0   wall         0.0    199.0
35  754.0   58.0    754.0   321.0   wall         0.0    263.0
36  563.0   159.0   754.0   159.0   wall         191.0  0.0

```

I guess I could just use these four points `(xmin, ymin), (xmax, ymax)` as the keypoints for the required dictionary that detectron2 takes as an input?

**Comment by ppwwyyxx** [comment]
Boxes with almost zero area are unlikely to work. The problem with this task is about how to make the task become a regular object detection problem. We're unable to provide such help on github. As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

**Comment by simonsapiel** [comment]
@ppwwyyxx Could you elaborate a bit. I know that the boxes with almost zero area wouldn't work on instance segmentation, but shouldn't they work with keypoint detection since it's regressing the heatmaps of the keypoints i.e the bounding boxes aren't even relevant for keypoint detection?
