### ISSUE TITLE
any guide for usr to implement ssd detector?

### ISSUE THREAD

**Issue by mlinxiang** [facebookresearch/detectron2#193]

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html

RetinaNet is implemented in one file: https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/retinanet.py

**Comment by bradezard131** [comment]
The write models tutorial doesn't actually give any information as to how one would write an entire new model though, only how one can add new backbones to the Generalised RCNN, and a point to look for implementing custom heads. It would be great to see the docs improved to provide actual guidance on implementing a model that doesn't fit the RCNN pattern

**Comment by ppwwyyxx** [comment]
The documentation mentions that more registries can be found at https://detectron2.readthedocs.io/modules/modeling.html#model-registries. If you register a new meta-arch, you can implement a new model. This is how retinanet is implemented.

**Comment by bradezard131** [comment]
Yes, but IO formats, device placement, etc. are all relevant and not covered clearly. The information is there if you know where to look (e.g. you can dig IO formats out of the using models page) but it's certainly non-trivial. I think this part of the docs could certainly be improved (should I manage to successfully implement my work I'm happy to contribute something when I get there)

**Comment by ppwwyyxx** [comment]
There isn't a fixed IO format. https://detectron2.readthedocs.io/tutorials/models.html documents formats for builtin models but you can have models that take other formats as long as you use your model accordingly.
