### ISSUE TITLE
Panoptic COCO Dataset

### ISSUE THREAD

**Issue by BradleyBrown19** [facebookresearch/detectron2#1930]
## ❓ How to do something using detectron2

How do we download the panoptic_train2017 and panoptic_val2017 datasets? They are not available on the official coco website (only the annotations are there). 

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

https://github.com/facebookresearch/detectron2/tree/master/datasets

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
They are part of the annotation file available at https://cocodataset.org/#download.
