### ISSUE TITLE
seemingly redundant sorting

### ISSUE THREAD

**Issue by Dirtybluer** [facebookresearch/detectron2#1931]
in detectron2/data/datasets/coco.py

```python
def load_coco_json(json_file, image_root, dataset_name=None, extra_annotation_keys=None):
    ...
    if dataset_name is not None:
        meta = MetadataCatalog.get(dataset_name)
        cat_ids = sorted(coco_api.getCatIds())
        cats = coco_api.loadCats(cat_ids)
        # The categories in a custom json file may not be sorted.
        thing_classes = [c["name"] for c in sorted(cats, key=lambda x: x["id"])]
        ...
```

As far as I can see, `cat_ids = sorted(coco_api.getCatIds())` well serves the purpose of sorting the `cat_ids`, which ensure `cats` retrieved from `cats = coco_api.loadCats(cat_ids)` is ordered by id. Then the `sorted()` in getting `thing_classes` seems to redundant.

Maybe I miss some points, if so, please be free to correct me.

**Comment by ppwwyyxx** [comment]
it does seem unnecessary

**Comment by Dirtybluer** [comment]
Thanks for your timely reply. Then maybe you could help to make it a bit neater in the future.
For now I would just close it :)
