### ISSUE TITLE
Relationship between AP and MODEL.ROI_HEADS.SCORE_THRESH_TEST / calculation of AP in Detectron2

### ISSUE THREAD

**Issue by Rotgrunblau** [facebookresearch/detectron2#1935]
Is there any relationship between MODEL.ROI_HEADS.SCORE_THRESH_TEST and die AP when doing inference? 

According to https://detectron2.readthedocs.io/modules/config.html#config-references the treshold sets the confidence of the network in doing a prediction, but shouldn't that change the AP significantly? 

For example when testing with the Colab example notebook and setting the threshold to 0.05, I'm getting a lot more detections, with a ton of false positives,  which is what I expected. 

![image](https://user-images.githubusercontent.com/59969473/90793533-20586c80-e30c-11ea-80c6-93e56b3885f1.png)

And setting it to 0.99 results in basically no detections. 

![image](https://user-images.githubusercontent.com/59969473/90794825-914c5400-e30d-11ea-9468-bb79fa095e01.png)

But the AP stays the same all the time. I assumed the metric is calculated on the detections set with the threshold and there ground truth boxes/segmentations + IOU. But it seems like this is not the case. 

So my question is, on what predictions is the AP actually computed? For example something like the highest scoring prediction (ignoring the threshold) with the highest IOU over an underlying ground truth etc...

**Comment by ppwwyyxx** [comment]
You can find the definition of AP online e.g. https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173. This question is not about detectron2.

**Comment by Rotgrunblau** [comment]
Found the solution. 
Assuming AP calculation is implemented as in http://homepages.inf.ed.ac.uk/ckiw/postscript/ijcv_voc09.pdf 
It should work like this: 

"Detections output by a method were assigned to ground
truth objects satisfying the overlap criterion in order ranked
by the (decreasing) confidence output. Multiple detections
of the same object in an image were considered false detections e.g. 5 detections of a single object counted as 1 correct
detection and 4 false detections – it was the responsibility of
the participant’s system to filter multiple detections from its
output."
