### ISSUE TITLE
Access Denied when trying to access: https://dl.fbaipublicfiles.com/detectron2/137849600/model_final_f10217.pkl

### ISSUE THREAD

**Issue by dragoscosma** [facebookresearch/detectron2#1936]
I'm using this: cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/detectron2/137849600/model_final_f10217.pkl"
and am getting:
File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

tried accessing the URL via browser/curl - Access Denied Received.
How should we access the files? Is there another URL?

trying to leverage segments-ai package under:
W10
CUDA version: 10.2
Anaconda
Python 3.8.3

thank you!

**Comment by ppwwyyxx** [comment]
It is not a valid URL. Not sure where you get it from..

**Comment by dragoscosma** [comment]
resolved by using: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
for more info check here: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md
