### ISSUE TITLE
`valid` variable type change in keypoint_rcnn_loss

### ISSUE THREAD

**Issue by whikwon** [facebookresearch/detectron2#1937]
When `len(heatmaps) == 0` `valid` type might not be changed to `torch.Tensor` and then, `valid.numel() == 0:` will raise error. 
I wonder if there is a case where `len(heatmaps) == 0`

https://github.com/facebookresearch/detectron2/blob/411bf36aff4c6ea8e89e472251419a25c4c19dd1/detectron2/modeling/roi_heads/keypoint_head.py#L70-L82

**Comment by ppwwyyxx** [comment]
If `len(heatmaps) == 0`, `valid.numel()` will not be executed so will not raise error.

**Comment by whikwon** [comment]
@ppwwyyxx Oh, I got it. Thanks for comment.
