### ISSUE TITLE
Fix exception chaining all over the codebase

### ISSUE THREAD

**Issue by akihironitta** [facebookresearch/detectron2#1943]
I would like to suggest a small fix in the way that Python 3's exception chaining is used.

As described in [this article](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with), exception chaining can be used to make exceptions more user-friendly, and in that case, the syntax `raise new_exception from old_exception` needs to be used.

For example,
```python
try:
    something_which_raises_TypeError
except TypeError as e:
    raise ValueError("a more user-friendly exception message.") from e
```
the above should be used instead of
```python
try:
    something_which_raises_TypeError
except TypeError:
    raise ValueError("a more user-friendly exception message.")
```

The following files (or possibly more) can be modified according to this syntax:
- [ ] https://github.com/facebookresearch/detectron2/blob/f3ada7de1fa30f03c330bb701c5100d88f43b429/detectron2/data/catalog.py#L52
- [ ] https://github.com/facebookresearch/detectron2/blob/439134dd6fe7c7aa0df4571d27a6386c1678551f/detectron2/config/config.py#L141
- [ ] https://github.com/facebookresearch/detectron2/blob/f3ada7de1fa30f03c330bb701c5100d88f43b429/detectron2/data/transforms/augmentation.py#L88
- [ ] https://github.com/facebookresearch/detectron2/blob/439134dd6fe7c7aa0df4571d27a6386c1678551f/detectron2/engine/hooks.py#L334

Let me know your thoughts on this!

**Comment by ppwwyyxx** [comment]
closed in https://github.com/facebookresearch/detectron2/pull/1945. thanks for the PR!
