### ISSUE TITLE
Caffe2 Model Uses Too Much RAM on Colab?

### ISSUE THREAD

**Issue by keremnymn** [facebookresearch/detectron2#1944]
Hello, I converted Detectron2 Faster R-CNN model to Caffe2 Model using `caffe2_converter.py`. I'm using this code to get inference with converted model:
`caffe2_model = Caffe2Model.load_protobuf("/content/")
img = cv2.imread("input.jpg")
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
data = {'image': image, 'height': image.shape[1], 'width': image.shape[2]}
output = caffe2_model([data])
print(output)               `

But the problem is, converted model uses too much RAM and crashes Google Colab runtime (which has 12 GB RAM). And input image I'm using is 72 KB and 850x1290. I'm not using GPU or TPU accelerator. After `[08/22 15:34:01 d2.export.caffe2_inference]: Initializing ProtobufModel ...` RAM usage goes up to 8 GB (probably more) and Google Colab runtime crashes.

Model runs with smaller images without a problem (altough so slow). Maybe it's because I'm running on Google Colab or something?

I'm planning to deploy this model so I wonder if I did something wrong at any step?

Thank you very much in advance.

**Comment by ppwwyyxx** [comment]
It's unclear what model is used. For a large model and large image size, 8GB of RAM consumption seems likely.

The warnings from onnx are benign.
