### ISSUE TITLE
Draw boxes based on prediction score

### ISSUE THREAD

**Issue by rathishkumar** [facebookresearch/detectron2#1952]
## ❓ How to draw boxes based on instance scores?

I want to write boxes only, if the score is greater than 0.7
`out = v.draw_instance_predictions((outputs["instances"].scores > 0.7).to("cpu"))`

I am getting below error:
AttributeError: 'Tensor' object has no attribute 'has'

Or How do I filter the instance fields for detected class score greater than 0.7?

I am checking here, https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.draw_instance_predictions, but still I am learning, could not understand. Please assist.

**Comment by ppwwyyxx** [comment]
Answered in "basic usage" at https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

**Comment by rathishkumar** [comment]
Thanks @ppwwyyxx

**Comment by rathishkumar** [comment]
For newbies, who are looking for ways to achieve this, check my answer on SO: https://stackoverflow.com/a/63573053/2156784
