### ISSUE TITLE
how to export nms_rotated/roi_align_rotated to onnx?

### ISSUE THREAD

**Issue by freedenS** [facebookresearch/detectron2#1954]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any: pytorch model including nms_rotated and roi_align_rotated
2. what outputs you are expecting: onnx model including custom op (nms_rotated/roi_align_rotated)

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

**Comment by ppwwyyxx** [comment]
I think the instructions at https://detectron2.readthedocs.io/tutorials/deployment.html may already work for Rotated R-CNN.

**Comment by freedenS** [comment]
Thank you for your reply!
i have tried that, but failed. #1955 
And there is another reason why i open this issue that nms_rotated is replaced with box_with_nms_limit in https://detectron2.readthedocs.io/tutorials/deployment.html, but box_with_nms_limit only has cpu implement.

**Comment by ppwwyyxx** [comment]
We'll keep #1955 open then. We currently only deploy models on CPUs so unfortunately some operators don't have a GPU implementation.

**Comment by freedenS** [comment]
Get it!
Thank you!
