### ISSUE TITLE
.pth -> .onnx (faster_rcnn_R_50_FPN_1x)

### ISSUE THREAD

**Issue by kamilstud** [facebookresearch/detectron2#1958]
Hi!

I am trying to do a conversion: **_*.pth -> *.onnx_** (I will use the onnx file later to inference the new images).

## The steps that I followed so far:

1.  I trained the pre-trained model (**faster_rcnn_R_50_FPN_1x**). Output *pth file was **315MB**

```
from detectron2.config import get_cfg
import os

cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml")

cfg.DATASETS.TRAIN = ("train_data",)
cfg.DATASETS.TEST = ("valid_data",)
cfg.DATALOADER.NUM_WORKERS = 4
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.MAX_ITER = 800 
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
cfg.TEST.EVAL_PERIOD = 300
cfg.OUTPUT_DIR = '/mainDir/content/output'

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

trainer = CocoTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```

2. I saved the model using '_torch.save()_', overriding just trained model's weights. Not quite sure if this step was necessary. The new *pth file had **158MB**.

```
from detectron2.modeling import build_model

cfg.MODEL.WEIGHTS = "/mainDir/content/output/model_final.pth"
model = build_model(cfg)
torch.save(model.state_dict(), '/mainDir/content/output/model.pth')
```

3. **At this step I get only errors**. I am trying to load_state_dict from *pth file saved in step no. 2  and I am passing one of the images from test data as an input tensor example.

```
import PIL
import torch.onnx
import torchvision
import torch
from torchvision import transforms

model.load_state_dict(torch.load('/mainDir/content/output/model.pth'))

to_tensor = transforms.ToTensor()

img_rgb = PIL.Image.open('/mainDir/content/test/191-1489-010.jpg').convert('RGB')
img_rgb = to_tensor(img_rgb)
img_rgb.unsqueeze_(0)

torch.onnx.export(model, img_rgb, "/mainDir/content/output/model_final.onnx", opset_version=11) 
```

## 💥Error
_IndexError: too many indices for tensor of dimension 3_

## ❔❓Questions I have

1. In the build_model(cfg) method description it states: "_Build the whole model architecture, defined by cfg.MODEL.META_ARCHITECTURE. Note that it does not load any weights from cfg_". Is the step no. 2 unnecessary then / done wrong? This would explain why it's almost half of a size of a model saved by the training itself (step no.1)...

2. Are the first two steps done correctly? Maybe something done wrong in one of them makes it impossible to convert the model? (connected with the first question)

## 💌Conclusion

If it might by caused by something that I did not mention here, please let me know. I will try to answer any question. I can also provide the link to the notebook I created on Google Colab along with the data I am using (I mounted my Google Drive to use the files from it). **Thanks in advance**!

---
### 🛠Versions of...everything

- python 3.6.9
- detectron2 -> 0.1.3
- pytorch -> 1.5
- torchvision -> 0.6
- pyyaml -> 5.1
- pycocotools -> 2.0
- environment accelerated by **GPU**

**Comment by ppwwyyxx** [comment]
> Note that it does not load any weights from cfg". Is the step no. 2 unnecessary then / done wrong? 

It is wrong. https://detectron2.readthedocs.io/tutorials/models.html explains how to load models.

> This would explain why it's almost half of a size of a model saved by the training itself (step no.1)

That's unrelated. It's always half of size of training.

>  Maybe something done wrong in one of them makes it impossible to convert the model?

Calling `torch.onnx.export` directly is not the correct way to convert the model. See https://detectron2.readthedocs.io/tutorials/deployment.html and https://detectron2.readthedocs.io/modules/export.html?highlight=caffe2tracer#detectron2.export.Caffe2Tracer.export_onnx
