### ISSUE TITLE
Detectron 2 in Windows

### ISSUE THREAD

**Issue by DanCorvesor** [facebookresearch/detectron2#1959]
This would be super helpful for researchers and practitioners just starting out as a lot of people in that category are unlikely to be using Mac or Linux.

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html says:
> Although detectron2 can be installed on windows with some effort (similar to these), we do not provide official support for it.
PRs that improves code compatibility on windows are welcome.

Community is adding more support for it in #1712
