### ISSUE TITLE
How to convert image input from range [0, 255] to [0, 1] in detectron2

### ISSUE THREAD

**Issue by gsrivas4** [facebookresearch/detectron2#1961]
## ❓ How to do something using detectron2

I am trying to have my image input in range [0, 1]. I looked up for such an option in config file here - https://detectron2.readthedocs.io/modules/config.html#detectron2.config.CfgNode. But, I couldn't find the option in to apply the transform. Is there such a parameter in detectron2. If it is not available what is the correct way to implement the transform in detectron2.

**Comment by ppwwyyxx** [comment]
`cfg.MODEL.PIXEL_{MEAN,STD}` are used to normalize the image in the model.
