### ISSUE TITLE
IOU detectron2

### ISSUE THREAD

**Issue by RishiMalhotra920** [facebookresearch/detectron2#1962]
I have trained a model. 

When testing, I see huge overlaps between my bounding boxes. Is there a way that during testing, I can specify a lower IOU for non-max suppression? 

Is there a way to do this during training?

**Comment by ppwwyyxx** [comment]
> I can specify a lower IOU for non-max suppression?

Search `NMS_THRESH_TEST` in https://detectron2.readthedocs.io/modules/config.html#config-references

> Is there a way to do this during training?

In training, models don't actually predict boxes so I'm not sure what "this" refers to.

**Comment by pvtien96** [comment]
Dear all,
I met a problem related to overlapping bounding boxes during inference time using demo.py
First, I searched and I read all the issues #1277 #1362 #1891 #1962
As far as I understand, with almost detection (or segmentation) models in this repo (eg. MasrRCNN_R_50_FPN_3x), before inference time, the model has already applied Non-Max Suppression with the default: 
'# Overlap threshold used for non-maximum suppression (suppress boxes with IoU >= this threshold)
_C.MODEL.ROI_HEADS.NMS_THRESH_TEST = 0.5'
So my questions are:
With default value NMS_THRESH_TEST = 0.5 using in demo.py, I expect that all the bounding boxes (in same class) that has IoU overlapped >= 0.5 should be suppress (keep the one with higher confidence score). Is that right?
For example: 
![image](https://user-images.githubusercontent.com/25927039/91795862-fd518500-ec48-11ea-8e66-13f26a6d363b.png)
This result is from the official Colab page.
In this image I see that: the ball number 1, 2 and 3 has overlapped >0.5 but why the model still keep all of them? Also the ball 
4 and 5 overlapped > 0.5 but the inference result keep both of them?
Any recommendation is appreciated.
@ppwwyyxx  @RishiMalhotra920 
Many thanks!

**Comment by ppwwyyxx** [comment]
I don't see any two boxes that have IoU > 0.5 in the above image. If you believe otherwise, please print the boxes and compute IoU to verify.
