### ISSUE TITLE
How to run Demo.py that would yield instance detection?

### ISSUE THREAD

**Issue by CBJ16** [facebookresearch/detectron2#1963]
I have trained a  model on a custom datasets below are the configurations 

from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("my_dataset_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = 'detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl'  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4  # classes + 1 

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

##### After running the demo.py the model was unable to detect any instance of the classes

!python demo.py --config-file /content/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml --input /content/drive/My\ Drive/test/Wood\ 016_jpg.rf.929108cdca15a848016b12693b04570a.jpg --output /content/drive/My\ Drive/outputs/ --confidence-threshold 0.80 --opts MODEL.WEIGHTS /content/drive/My\ Drive/outputs/model_999.pth MODEL.ROI_HEADS.NUM_CLASSES 4

#MESSAGE 

[08/26 04:52:51 detectron2]: Arguments: Namespace(confidence_threshold=0.8, config_file='/content/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml', input=['/content/drive/My Drive/test/Wood 016_jpg.rf.929108cdca15a848016b12693b04570a.jpg'], opts=['MODEL.WEIGHTS', '/content/drive/My Drive/outputs/model_999.pth', 'MODEL.ROI_HEADS.NUM_CLASSES', '4'], output='/content/drive/My Drive/outputs/', video_input=None, webcam=False)
[08/26 04:52:55 fvcore.common.checkpoint]: Loading checkpoint from /content/drive/My Drive/outputs/model_999.pth
  0% 0/1 [00:00<?, ?it/s][08/26 04:52:56 detectron2]: /content/drive/My Drive/test/Wood 016_jpg.rf.929108cdca15a848016b12693b04570a.jpg: detected 0 instances in 0.62s
100% 1/1 [00:00<00:00,  1.43it/s]

What did I missed adding/modifying/ that should have been done to yield instance detection by the model?

**Comment by CBJ16** [comment]
This is how I saved the model

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set a custom testing threshold for this model
cfg.DATASETS.TEST = ("my_dataset_val", )
predictor = DefaultPredictor(cfg)

from fvcore.common.checkpoint import Checkpointer
from detectron2.checkpoint import DetectionCheckpointer


#saving model weights
from detectron2.modeling import build_model
model = build_model(cfg)

checkpointer = DetectionCheckpointer(model, save_dir="/content/drive/My Drive/outputs/")
checkpointer.save("model_999")  # save to output/model_999.pth

**Comment by ppwwyyxx** [comment]
I don't think the way you initialize the model will lead to good training results. If you're not sure how to train a model, following the tutorial is the safest way.

As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

**Comment by CBJ16** [comment]
Thank you. The training result were detected in the colab, it's just did not detected in the final run above

**Comment by ppwwyyxx** [comment]
If the same model is able to detect on the same image in Colab, then you can compare `demo.py` and code you wrote in Colab to tell the difference. Most likely a difference in config parameters.
