### ISSUE TITLE
Cropped images

### ISSUE THREAD

**Issue by RishiMalhotra920** [facebookresearch/detectron2#1964]
The pre-trained Faster RCN is able to detect people small in size when I crop an image and run the algorithm on individual crops.
However, when I run the same algorithm on the original image, it does not detect those people.

Currently, the result difference is huge.

Working with a 3*3 crop on image I get ~200 detections (close to ground truth)
Working with original image I get ~100 detections.

Is there a way to alter the configurations so that I can make these detections without cropping?

**Comment by ppwwyyxx** [comment]
`TEST.DETECTIONS_PER_IMAGE` may need to be changed.

As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
