### ISSUE TITLE
Can't install it using Anaconda and Linux 

### ISSUE THREAD

**Issue by sarasarab** [facebookresearch/detectron2#1965]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. full code you wrote or full changes you made (`git diff`)
Following the instructions to install it
2. what exact command you run:
conda create -n mypython3 python=3
conda activate mypython3
conda install -c psi4 gcc-5 
conda install -c anaconda cython
conda install -c anaconda pyyaml
conda install -c conda-forge opencv
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
git clone https://github.com/facebookresearch/detectron2.git
cd detectron2
pip install -e .

3. __full logs__ you observed:
ERROR: Command errored out with exit status 1:
     command: /HOMES/begaj/anaconda3/envs/mypython3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/HOMES/begaj/Desktop/detectron2/setup.py'"'"'; __file__='"'"'/HOMES/begaj/Desktop/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a5lpn2o1
         cwd: /HOMES/begaj/Desktop/detectron2/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/HOMES/begaj/Desktop/detectron2/setup.py", line 10, in <module>
        import torch
      File "/HOMES/begaj/anaconda3/envs/mypython3/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
        from torch._C import *
    ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /HOMES/begaj/anaconda3/envs/mypython3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
Suggestions for such issue are provided in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

Since the error comes from `import torch`, it's unrelated to this project.
