### ISSUE TITLE
Batch Processing with CPU takes 120 seconds, DefaultPredictor takes 5 seconds

### ISSUE THREAD

**Issue by hasansalimkanmaz** [facebookresearch/detectron2#1968]
## Full code to reproduce the issue:

```
import numpy as np
import torch
from PIL import Image
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.config import get_cfg
from detectron2.modeling import build_model
import time

cfg = get_cfg()
cfg.merge_from_file("./entity_extraction_model/hpanwar08-medium-trimmed.cfg")
cfg.MODEL.DEVICE = "cpu"
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 7
cfg.MODEL.WEIGHTS = "./entity_extraction_model/detectron2_v3.pth"
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.01  # set the testing threshold for this model
cfg.MODEL.ROI_HEADS.NMS_THRESH_TEST = 0.25
model = build_model(cfg)  # returns a torch.nn.Module
DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)  # load a file, usually from cfg.MODEL.WEIGHTS

# INPUT
image_path = "tests/test_image_processing/test_files_entity_extraction/1.jpg"

# open image
img = Image.open(image_path).convert('RGB')

img = np.transpose(np.array(img), (2, 0, 1))  # change from HWC to CHW
img_tensor = torch.from_numpy(img)
in_put_list = [{"image": img_tensor}]

model.eval()

s = time.time()
with torch.no_grad():
    outputs = model(in_put_list)
print(f"Total elapsed time {time.time() - s}")
print(outputs)

```
#### LOGS
```
Total elapsed time 123.08564782142639
```

## Expected behavior:

My image size is (2481x3508). I don't know whether image size affects inference time or not. However, how batch-processing takes more time than default_predictor. I think this is unusual.

Note: I am running on CPU

**Comment by ppwwyyxx** [comment]
Explained in https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor

**Comment by hasansalimkanmaz** [comment]
@ppwwyyxx You are directing me to DefaultPredictor. But DefaultPredictor doesn't support batch processing. That's why I am using model api. I think your answer didn't match my question :(

**Comment by ppwwyyxx** [comment]
The documentation explains the difference between DefaultPredictor and calling model manually.
In particular 
> Apply resizing defined by cfg.INPUT.{MIN,MAX}_SIZE_TEST.

**Comment by hasansalimkanmaz** [comment]
My question is why batch processing takes that much long.

**Comment by ppwwyyxx** [comment]
It takes longer than DefaultPredictor because DefaultPredictor has resize to a smaller resolution.

Also, timing the first iteration of a pytorch model often does not give meaningful results.

**Comment by hasansalimkanmaz** [comment]
Thanks for the info @ppwwyyxx
