### ISSUE TITLE
How to get results of anchors in c++ with caffe2 to paste mask in image  ?

### ISSUE THREAD

**Issue by lewnus** [facebookresearch/detectron2#1977]
## ❓ How to get results of anchors in c++ with caffe2 to paste mask in image  ?

I want to inference a detectron2 mask-rcnn model in C++ with Caffe2. Following the offical example caffe2_mask_rcnn.cpp, masks with size of 28x28 are given.  So how to get results of anchors to paste mask in image? 

orz

**Comment by ppwwyyxx** [comment]
Postprocessing like this is currently left for users since there are many possible ways to postprocess. As the simplest approach, you can do a resize.

**Comment by lewnus** [comment]
> Postprocessing like this is currently left for users since there are many possible ways to postprocess. As the simplest approach, you can do a resize.

I know how to paste if the results of the correspondence masks and anchors are given, such as a resize.  But in c++, I can only get "bbox_nms" which  are refined from anchors. But what I want is the location and size of  original correspondence anchor.

**Comment by ppwwyyxx** [comment]
The 28x28 masks in Mask R-CNN do not correspond to anchors but `bbox_nms`. 
So anchors are useless for postprocessing, and therefore are not made available in caffe2.
