### ISSUE TITLE
Great! Everything in GPU!

### ISSUE THREAD

**Issue by xmyqsh** [facebookresearch/detectron2#198]
We have witnessed three generations of Object Detection architecture, the original pipeline, the all-in tensor into computational graph pipeline and the all-in GPU pipeline.
It is not easy from the second to the third for two-stage detection in the most efficient way.

**Comment by ppwwyyxx** [comment]
I don't understand what you mean about the generation but this seems not a bug or feature request. Feel free to reopen if this is not the case.
