### ISSUE TITLE
In detectron2, how could I put the text on image?

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#1980]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

I could do predicting the bounding box. But, I also want to put the bounding box coordinate on the image. For this, I use cv2.putext library. but it did not work. Could you please make the below code can show bounding box coordinate on the images? below is my code.

    from detectron2.utils.visualizer import ColorMode
    import glob
    for imageName in glob.glob(os.path.join(test_path, '*jpg')):
      im = cv2.imread(imageName)
      outputs = predictor(im)
      v = Visualizer(im[:, :, ::-1],
                metadata=train_metadata,
                scale=0.8)
      out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
      cv2_imshow(out.get_image()[:, :, ::-1])

**Comment by MathijsNL** [comment]
Hi Nurungyi,

This is an OpenCV related question. There is loads of information that can be find here:
[https://docs.opencv.org/3.1.0/dc/da5/tutorial_py_drawing_functions.html](https://docs.opencv.org/3.1.0/dc/da5/tutorial_py_drawing_functions.html)

If you loop over outputs["instances"].pred_boxes.cpu().numpy() you could easily put the coords on your image. Good luck!

**Comment by Nurungyi** [comment]
> Hi Nurungyi,
> This is an OpenCV related question. There is loads of information that can be find here:
> https://docs.opencv.org/3.1.0/dc/da5/tutorial_py_drawing_functions.html
> If you loop over outputs["instances"].pred_boxes.cpu().numpy() you could easily put the coords on your image. Good luck!

Thank you for replying it.

I could do get bounding box coordinates using this code "outputs["instances"].pred_boxes"

but I still don't know how to do plot coordinate of bounding box while drawing the bounding box on the image by using detectron2 API

**Comment by ppwwyyxx** [comment]
Yeah, please use libraries like OpenCV if you'd like to draw things that detectron2 does not draw

**Comment by MathijsNL** [comment]
> but I still don't know how to do plot coordinate of bounding box while drawing the bounding box on the image by using detectron2 API

The Visualizer gives an output, which you show with
```
  out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
  cv2_imshow(out.get_image()[:, :, ::-1])
```
What cv2_imshow() shows is an image. Instead of showing it use it to draw the rest of your results. Would probably look something like this:

```
visualized_image = out.get_image()[:, :, ::-1]
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(visualized_image ,'OpenCV',(10,500), font, 4,(255,255,255),2,cv2.LINE_AA)
```

Good luck!
