### ISSUE TITLE
upgrading code written with older version of Detectron2

### ISSUE THREAD

**Issue by gsrivas4** [facebookresearch/detectron2#1987]
## ❓ How to do something using detectron2

I am trying to upgrade a repository which was written with an older version of Detectron2. The repository that I am trying to upgrade is https://github.com/MILVLG/bottom-up-attention.pytorch. I am getting an error when I am trying to run the repository with the version of detectron2 that I am currently using. I am currently using version 0.2 detectron2. The repo was created using this version of detectron2 - https://github.com/facebookresearch/detectron2/tree/5e2a6f62ef752c8b8c700d2e58405e4bede3ddbe. I am getting below error error:

```
Traceback (most recent call last):
  File "extract_features.py", line 133, in <module>
    main()
  File "extract_features.py", line 81, in main
    model = DefaultTrainer.build_model(cfg)
  File "/usr/local/lib64/python3.6/site-packages/detectron2/engine/defaults.py", line 415, in build_model
    model = build_model(cfg)
  File "/usr/local/lib64/python3.6/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/default/ephemeral_drive/work/image_captioning/MILVLG/bottom-up-attention.pytorch/models/bua/rcnn.py", line 40, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
  File "/usr/local/lib64/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/home/default/ephemeral_drive/work/image_captioning/MILVLG/bottom-up-attention.pytorch/models/bua/roi_heads.py", line 52, in __init__
    super().__init__(cfg, input_shape)
  File "/usr/local/lib64/python3.6/site-packages/detectron2/config/config.py", line 147, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/detectron2/config/config.py", line 180, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
TypeError: from_config() takes 2 positional arguments but 3 were given
```
Can you give me some directions about what are the possible changes in the latest version of Detectron2 which might be causing this issue or possible what part are the api changes, etc.

**Comment by ppwwyyxx** [comment]
https://github.com/MILVLG/bottom-up-attention.pytorch/blob/4e7198b2ab4ea7062e40ed2bdf6bce7497931ba7/models/bua/roi_heads.py#L51

should be replaced by `super().__init__(cfg)`.

**Comment by onlyonewater** [comment]
Hi, @ppwwyyxx , I used your advice, but I still get an error.

> 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-e2ed85c57fe0> in <module>
      3 CONF_THRESH = 0.4
      4 
----> 5 model = DefaultTrainer.build_model(cfg)
      6 DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
      7     '../'+cfg.MODEL.WEIGHTS, resume=True

~/projects/bottom-up-attention.pytorch/detectron2/detectron2/engine/defaults.py in build_model(cls, cfg)
    414         Overwrite it if you'd like a different model.
    415         """
--> 416         model = build_model(cfg)
    417         logger = logging.getLogger(__name__)
    418         logger.info("Model:\n{}".format(model))

~/projects/bottom-up-attention.pytorch/detectron2/detectron2/modeling/meta_arch/build.py in build_model(cfg)
     19     """
     20     meta_arch = cfg.MODEL.META_ARCHITECTURE
---> 21     model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
     22     model.to(torch.device(cfg.MODEL.DEVICE))
     23     return model

~/projects/bottom-up-attention.pytorch/models/bua/rcnn.py in __init__(self, cfg)
     38         self.in_features = cfg.MODEL.RPN.IN_FEATURES
     39         self.proposal_generator = build_proposal_generator(cfg, self.backbone.output_shape())
---> 40         self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
     41 
     42         assert len(cfg.MODEL.PIXEL_MEAN) == len(cfg.MODEL.PIXEL_STD)

~/projects/bottom-up-attention.pytorch/detectron2/detectron2/modeling/roi_heads/roi_heads.py in build_roi_heads(cfg, input_shape)
     41     """
     42     name = cfg.MODEL.ROI_HEADS.NAME
---> 43     return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
     44 
     45 

~/projects/bottom-up-attention.pytorch/models/bua/roi_heads.py in __init__(self, cfg, input_shape)
     49 
     50     def __init__(self, cfg, input_shape):
---> 51         super().__init__(cfg, input_shape)
     52 
     53         assert len(self.in_features) == 1

~/projects/bottom-up-attention.pytorch/detectron2/detectron2/config/config.py in wrapped(self, *args, **kwargs)
    145 
    146         if _called_with_cfg(*args, **kwargs):
--> 147             explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
    148             init_func(self, **explicit_args)
    149         else:

~/projects/bottom-up-attention.pytorch/detectron2/detectron2/config/config.py in _get_args_from_config(from_config_func, *args, **kwargs)
    178             if name not in supported_arg_names:
    179                 extra_kwargs[name] = kwargs.pop(name)
--> 180         ret = from_config_func(*args, **kwargs)
    181         # forward the other arguments to __init__
    182         ret.update(extra_kwargs)

TypeError: from_config() takes 2 positional arguments but 3 were given

>

**Comment by Mollylulu** [comment]
> Hi, @ppwwyyxx , I used your advice, but I still get an error.
> 
> > 
> 
> TypeError Traceback (most recent call last)
> in
> 3 CONF_THRESH = 0.4
> 4
> ----> 5 model = DefaultTrainer.build_model(cfg)
> 6 DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
> 7 '../'+cfg.MODEL.WEIGHTS, resume=True
> 
> ~/projects/bottom-up-attention.pytorch/detectron2/detectron2/engine/defaults.py in build_model(cls, cfg)
> 414 Overwrite it if you'd like a different model.
> 415 """
> --> 416 model = build_model(cfg)
> 417 logger = logging.getLogger(**name**)
> 418 logger.info("Model:\n{}".format(model))
> 
> ~/projects/bottom-up-attention.pytorch/detectron2/detectron2/modeling/meta_arch/build.py in build_model(cfg)
> 19 """
> 20 meta_arch = cfg.MODEL.META_ARCHITECTURE
> ---> 21 model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
> 22 model.to(torch.device(cfg.MODEL.DEVICE))
> 23 return model
> 
> ~/projects/bottom-up-attention.pytorch/models/bua/rcnn.py in **init**(self, cfg)
> 38 self.in_features = cfg.MODEL.RPN.IN_FEATURES
> 39 self.proposal_generator = build_proposal_generator(cfg, self.backbone.output_shape())
> ---> 40 self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
> 41
> 42 assert len(cfg.MODEL.PIXEL_MEAN) == len(cfg.MODEL.PIXEL_STD)
> 
> ~/projects/bottom-up-attention.pytorch/detectron2/detectron2/modeling/roi_heads/roi_heads.py in build_roi_heads(cfg, input_shape)
> 41 """
> 42 name = cfg.MODEL.ROI_HEADS.NAME
> ---> 43 return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
> 44
> 45
> 
> ~/projects/bottom-up-attention.pytorch/models/bua/roi_heads.py in **init**(self, cfg, input_shape)
> 49
> 50 def **init**(self, cfg, input_shape):
> ---> 51 super().**init**(cfg, input_shape)
> 52
> 53 assert len(self.in_features) == 1
> 
> ~/projects/bottom-up-attention.pytorch/detectron2/detectron2/config/config.py in wrapped(self, *args, **kwargs)
> 145
> 146 if _called_with_cfg(*args, **kwargs):
> --> 147 explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
> 148 init_func(self, **explicit_args)
> 149 else:
> 
> ~/projects/bottom-up-attention.pytorch/detectron2/detectron2/config/config.py in _get_args_from_config(from_config_func, *args, **kwargs)
> 178 if name not in supported_arg_names:
> 179 extra_kwargs[name] = kwargs.pop(name)
> --> 180 ret = from_config_func(*args, **kwargs)
> 181 # forward the other arguments to **init**
> 182 ret.update(extra_kwargs)
> 
> TypeError: from_config() takes 2 positional arguments but 3 were given
> 
> >

hi~ have you fix this error?
