### ISSUE TITLE
PointRend Out of Memory error on LVIS

### ISSUE THREAD

**Issue by lxtGH** [facebookresearch/detectron2#1989]
Hi! PointRend is most interesting work for segmentation this year to generate high quality mask.
LVIS has high quality mask annotation. So I try to run point rend on LVIS with mask-rcnn-r50.

# Problem: 

The training is OK but when I do evaluation. It report out of memory error.
# What I have done: 

I decrease bs16 -> bs8, it still reports out of memory error.

I use 8 GPU v100 with 32GB memory.

![31598941267_ pic_hd](https://user-images.githubusercontent.com/17202268/91805903-67285980-ec5e-11ea-9cd3-f32cb5a94e99.jpg)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by PytaichukBohdan** [comment]
@lxtGH Have you tried setting net.eval() and with torch.no_grad(): before evaluation?
