### ISSUE TITLE
install problem:/usr/local/cuda/bin/nvcc: not found

### ISSUE THREAD

**Issue by CUIcaicai** [facebookresearch/detectron2#1990]
hello,/usr/local/cuda/bin/nvcc can be found ,and when i run nvcc -V:
(detectron2) cl@CL:~/gitclone$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

but,when i run python -m pip install -e detectron2,I got the error like this:
    :/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/tmp/pip-req-build-f5f0eael/detectron2/layers/csrc -I/home/cl/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/include -I/home/cl/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cl/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/include/TH -I/home/cl/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/cl/anaconda3/envs/detectron2/include/python3.7m -c -c /tmp/pip-req-build-f5f0eael/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /tmp/pip-req-build-f5f0eael/build/temp.linux-x86_64-3.7/tmp/pip-req-build-f5f0eael/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found

how can i solve this problem,could you give some tips,thanks!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by CUIcaicai** [comment]
I have add a new issue，sorry




On 09/01/2020 15:11, Yuxin Wu wrote:

If you need help to solve an unexpected issue you observed, please include details following the "Unexpected behaviors" issue template.
