### ISSUE TITLE
error occurred during install

### ISSUE THREAD

**Issue by zhjw0927** [facebookresearch/detectron2#1993]
my computer not have git.
![image](https://user-images.githubusercontent.com/42128459/91921950-4f54e200-ecff-11ea-8d50-6a052b00abef.png)

 so I select second, download zip && unzip && cd detectron2-master
run `python -m pip install -e detectron2`

![image](https://user-images.githubusercontent.com/42128459/91922118-b7a3c380-ecff-11ea-9b96-ab7d7cd34836.png)

have any suggestion?
Thank you!

**Comment by ppwwyyxx** [comment]
download zip && unzip <del>&& cd detectron2-master</del>
run python -m pip install -e __detectron2-master__
