### ISSUE TITLE
Large model is really slow in inference

### ISSUE THREAD

**Issue by keremnymn** [facebookresearch/detectron2#1997]
I've trained a custom object detection model using Faster R-CNN with [X-101 config file](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml). 

It works really good and I want to deploy this. But the inference takes 8-10 seconds for a single image (which is 620x900) on CPU _(both on my local processor which is i7-8750h and Colab)_. So I don't think it's good for server responses.

I saved config file after training using "[dump](https://detectron2.readthedocs.io/modules/config.html#detectron2.config.CfgNode.dump)" method.

Maybe I'm doing something wrong in **config** file to make it **slower**?

Or if it's slower due to the fact that it's the largest model in model zoo, is there a pruning or quantization option for this?

Any help would be much appreciated,
Thanks in advance.

_[Config file drive link](https://drive.google.com/file/d/1H1fAYxRuCFK6LmSYq6lmT4kk8vBJ8vai/view?usp=sharing)_

**Comment by ppwwyyxx** [comment]
The time sounds not too bad for this model. Models in the model zoo focus more on research in detection and are not the type of model one would want to deploy with CPUs.
More efficient models and quantization are tracked in separate issues

**Comment by keremnymn** [comment]
Oh okay, I'll train my data with a smaller model then. Thank you.
