### ISSUE TITLE
how to export rpn model to caffe2?

### ISSUE THREAD

**Issue by airqj** [facebookresearch/detectron2#2008]
##  how to export rpn model to caffe2?
Because my dataset only have one class,so i train a rpn model based on detectron2.the configuration file is `configs/COCO-Detection/rpn_R_50_C4_1x.yaml`.
But when i export to caffe2 model, the script only support `GeneralizedRCNN, RetinaNet, PanopticFPN`,
when i comment the line `META_ARCHITECTURE: "ProposalNetwork"`, the export process is killed by system,and the output model detect nothing on input image.
so what should i do to export rpn model to caffe2?

**Comment by ppwwyyxx** [comment]
It is not supported, and is unlikely to be supported because a pure RPN is unlikely to be useful for deployment. 
You can use RetinaNet which works similarly to RPN.

**Comment by airqj** [comment]
thank you very 

> It is not supported, and is unlikely to be supported because a pure RPN is unlikely to be useful for deployment.
> You can use RetinaNet which works similarly to RPN.

thank you very much
