### ISSUE TITLE
How to integrate PointRend into instance segmentation which has no ROI information

### ISSUE THREAD

**Issue by ztwe** [facebookresearch/detectron2#2009]
In coarse prediction features branch, ROI information is needed to crop feature map. Mask R-cnn can provide proposals which contain ROI  information. For those algorithms which have no proposals, how to integrate PointRend? For example, SOLO.
@ppwwyyxx

**Comment by ppwwyyxx** [comment]
Github issues of this project are meant for one of the [following topics](https://github.com/facebookresearch/detectron2/issues/new/choose) about code in this repo, not for discussing papers or new ideas.
