### ISSUE TITLE
Using Augmentation with RandomApply

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#2010]
Hey everyone,

1.)
Currently I'm using RandomApply with RandomContrast to make sure, that my contrast augmentation is limited to a special amount of iterations. The line is as follows:
T.RandomApply(T.RandomContrast(1.6, 1.6), 0.05))
Am I right with the my guess, that the contrast augmentation is only applied to 5% of the input data with the specified contrast of 1.6?
2.)
When I define my line as follows:
T.RandomContrast(1.6, 1.6). Does that mean, that every input data is augmented?

Thanks a lot

**Comment by MathijsNL** [comment]
Hey,

I faced the same problem. The best solution to it is to visualize the augmentations (see bottom)

To answer your questions:
1)
Yes you are right. [augmentation_impl.py
](https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/transforms/augmentation_impl.py
)
```
class RandomApply(Augmentation):
    """
    Randomly apply an augmentation with a given probability.
    """

    def __init__(self, tfm_or_aug, prob=0.5):
```
2)
In the same file (augmentation_impl.py) you can find that there are only two augmentations with a probability parameter:
- RandomFlip
- RandomApply
In all other cases it will be always applied.



Example of how to visualize augmentations
```
loader = Trainer.build_train_loader(cfg)
sample_image_batches = 2
f = plt.figure(figsize=(20, 10 * sample_image_batches))
idx = 1

for sample_image_batch_idx, train_image_batch in enumerate(loader):

    for idx, train_image in enumerate(train_image_batch):
        image = train_image["image"].numpy().transpose(1, 2, 0)

        target_fields = train_image["instances"].get_fields()
        labels = [metadata.thing_classes[i] for i in target_fields["gt_classes"]]

        # visualize ground truth
        gt_visualizer = Visualizer(
            image[:, :, ::-1], metadata=metadata, scale=1
        )
        gt_image_vis = gt_visualizer.overlay_instances(
            labels=labels,
            boxes=target_fields.get("gt_boxes", None),
            masks=target_fields.get("gt_masks", None),
            keypoints=target_fields.get("gt_keypoints", None),
        )

        f.add_subplot(sample_image_batches, 2, (2 * sample_image_batch_idx) + idx + 1)
        plt.title(f"Image {train_image['file_name']}")
        plt.imshow(gt_image_vis.get_image())#[:, :, ::-1])

    if sample_image_batch_idx >= sample_image_batches -1:
        break
plt.show()

```

**Comment by Bamil** [comment]
Hi MathijsNL,

thanks a lot, that really helps !
