### ISSUE TITLE
Package import error while using API training

### ISSUE THREAD

**Issue by zhang5957** [facebookresearch/detectron2#2014]
1  import detectron2.utils.comm as comm
2  from detectron2.utils.events import EventStorage
  

AttributeError: module 'detectron2' has no attribute 'utils'

how to fix this，plz

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by chiboreache** [comment]
this is because of stupid imports

work

```python
from detectron2.utils.logger import setup_logger
setup_logger()
```


not work

```python
import detectron2
detectron2.utils.logger.setup_logger()
```

**Comment by LoveU3tHousand2** [comment]
> this is because of stupid imports
> 
> work
> 
> ```python
> from detectron2.utils.logger import setup_logger
> setup_logger()
> ```
> 
> not work
> 
> ```python
> import detectron2
> detectron2.utils.logger.setup_logger()
> ```
Yeah, so stupid.
