### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (detectron2::ROIAlign_forward_cuda at E:/PytorchPro/detectron2-master/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:365) (no backtrace available)

### ISSUE THREAD

**Issue by Grim-John** [facebookresearch/detectron2#2017]
I tried to run detectron2 == 1.3.0 on windows. I successfully installed and ran it on my laptop, but encountered this problem on another windows computer. Is there any solution?
my environment:
pytorch 1.4.0
cuda 10.1
cudnn 7.6.5
torchvison 0.5.0

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
