### ISSUE TITLE
Why install from source will run `build_ext` command twice?

### ISSUE THREAD

**Issue by yelantf** [facebookresearch/detectron2#2019]
Awesome project! I was using the latest version(1.6.0) of PyTorch and when I tried to install this project from source with the 
command `python setup.py build develop`, it compiles those cuda_extensions twice. I am not sure if this is caused by the new default compilation system `ninja` and want to know what could cause this behavior. The output log is attached below. 

[compile_log.txt](https://github.com/facebookresearch/detectron2/files/5192588/compile_log.txt)

As shown in the output, it prints `running build_ext` twice and those CUDA extensions get compiled twice.

**Comment by ppwwyyxx** [comment]
The command is incorrect. Please see https://detectron2.readthedocs.io/tutorials/install.html#build-detectron2-from-source for installation instructions.
