### ISSUE TITLE
Plotting incorrectly - detected score and plotted score

### ISSUE THREAD

**Issue by rathishkumar** [facebookresearch/detectron2#2020]
## Instructions To Reproduce the Issue:

Using default predictor.
`predictor = DefaultPredictor(cfg)`

Running prediction:
`outputs = predictor(image)`

Printing output score:
`print(outputs["instances"].scores)`

Using Visualizer to plot the scores:
`out = v.draw_instance_predictions(outputs["instances"].to("cpu"))`

As of this step everything working as expected.

## Expected behavior:

Predicted score should be plotted to image

Predicted score for person class: `0.9847094416618347, 0.9725064039230347, 0.0621788389980793`
Plotted score on image: `Person 96% & Person 97% & Person 6%`

First value is mismatched for few images.

## Environment:

Provide your environment information using the following command:
`---------------------  -----------------------------------------------------------------------------
sys.platform           linux
Python                 3.8.5 (default, Aug  5 2020, 08:36:46) [GCC 7.3.0]
numpy                  1.19.1
detectron2             0.2.1 @/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.6.0 @/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 7.2.0
torchvision            0.7.0 @/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/torchvision
fvcore                 0.1.1.post20200716
cv2                    4.3.0
---------------------  -----------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,`

**Sample:**
![image](https://user-images.githubusercontent.com/3918929/92559174-b0dff800-f28d-11ea-8192-410b3f82913d.png)

**Comment by ppwwyyxx** [comment]
Please provide self-contained runnable code that reproduces the issue.  See also https://stackoverflow.com/help/minimal-reproducible-example

**Comment by rathishkumar** [comment]
Sure, here is the code which I am using:

```
import os, json, cv2, random, time
import numpy as np 
from pprint import pprint
import detectron2
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

im = cv2.imread("./input.jpg")

cfg = get_cfg()
cfg.MODEL.DEVICE='cpu'
cfg.MODEL.ROI_HEADS.SCORE_THREST_TEST = 0.5 
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml")

predictor = DefaultPredictor(cfg)

outputs = predictor(im)
print(outputs["instances"].pred_classes)
print(outputs["instances"].scores)

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imwrite('predicted.jpg', out.get_image()[:, :, ::-1])
```

**Comment by ppwwyyxx** [comment]
The instruction is incomplete because "input.jpg" is missing

**Comment by rathishkumar** [comment]
I could not share that specific image, I am checking to reproduce similar behavior with some generic image and share the same.

**Comment by rathishkumar** [comment]
Closing the issue, as I am could not reproduce the behavior for any other images. 

Thank you @ppwwyyxx
