### ISSUE TITLE
Changing threshold for the model not working while running the script on local pc.

### ISSUE THREAD

**Issue by meet-VC** [facebookresearch/detectron2#2021]
## Instructions To Reproduce the Issue:

I want to change the threshold for the model to about 0.9. So that the model only predicts the output which is greater or equals to 90% accuracy.

1. full code you wrote or full changes you made (`git diff`)
```
cfg = get_cfg()
# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.9  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
```

## Expected behavior:

All the objects with >90% accuracy should be shown which is working in google colab, but when I run the same code in my personal computer and write 0.9  then also I am getting objects with 30% accuracy.

**Comment by ppwwyyxx** [comment]
>  when I run the same code in my personal computer and write 0.9 then also I am getting objects with 30% accuracy.

I don't think that's possible with the code provided above.
If you still believe there is an issue, please provide full instructions to reproduce the issue (e.g. https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by meet-VC** [comment]
Sorry for the trouble, there was an issue with the server of my personal computer. Thank you so much for helping.
