### ISSUE TITLE
INPUT.RANDOM_FLIP_TRAIN is ignored by DatasetMapper

### ISSUE THREAD

**Issue by erickim555** [facebookresearch/detectron2#2024]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote

I'm on commit 6ed02d8e43a9b2d82d198b3622f51d408689bd7f, with no local changes.

Currently, `cfg.INPUT.RANDOM_FLIP_TRAIN` is ignored by the `DatasetMapper.from_cfg()` method. If I set random flip train to False (eg disable random flip data augmentation), the `DatasetMapper.from_cfg()` will incorrectly use random flip data aug.
The root cause is, in `build_augmentation()`, this line is ignoring the cfg:
https://github.com/facebookresearch/detectron2/blob/729290df8a1b9c0307fb667dd776bed3c4f8bdc5/detectron2/data/detection_utils.py#L582

A simple fix could be:
```
    augmentation = [T.ResizeShortestEdge(min_size, max_size, sample_style)]
-    if is_train:
+    if is_train and cfg.INPUT.RANDOM_FLIP_TRAIN:
        augmentation.append(T.RandomFlip())
    return augmentation
```

## Expected behavior:
When I set `cfg.INPUT.RANDOM_FLIP_TRAIN=False`, DatasetMapper should disable random flip data augmentation.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/pull/1976 will address this
