### ISSUE TITLE
How to adjust GPU memory needed for a model

### ISSUE THREAD

**Issue by colt18** [facebookresearch/detectron2#2025]
I'm on a 8GB GTX 1070 gpu and would like to run [this](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml) X101-FPN for instance segmentation. It is actually a 7.2 GB model as indicated on model zoo and no way it will fit since Windows 10 almost used 1GB of gpu mem. I'd like to edit `cfg` so I can trim some settings and make model fit into my GPU. AFAIK, there is no `batch_size` specification so I assume always a single image is taken into pipeline. Thanks.

**Comment by ppwwyyxx** [comment]
For training: there are a few configs such as `SOLVER.IMS_PER_BATCH`, `MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE` that reduces memory usage. Smaller images (`INPUT.MIN_SIZE_TRAIN`) also reduces memory usage.

Inference takes far less memory.
