### ISSUE TITLE
NMS with multiple classes

### ISSUE THREAD

**Issue by Altair3** [facebookresearch/detectron2#2028]
I am wondering about the behavior of NMS when you are considering boxes from different classes. For example, I have a dress-shirt box and then inside of that I have a necktie box. Does NMS remove the inner (necktie) box? If this is the case, how can I prevent NMS from considering boxes of different classes. Is this doable with the framework?

**Comment by ppwwyyxx** [comment]
> Does NMS remove the inner (necktie) box

It does not. NMS is performed only within each class
