### ISSUE TITLE
multiple GPU trainning not work

### ISSUE THREAD

**Issue by YQYI** [facebookresearch/detectron2#2029]
I try to train with multiple gpu, but it seems only one gpu work,this is my code
![image](https://user-images.githubusercontent.com/28799825/93172989-77f8c500-f75e-11ea-882a-71cab3f4ddc0.png)
this is GPU infomation,  seems only one work!
![image](https://user-images.githubusercontent.com/28799825/93173117-9e1e6500-f75e-11ea-9b3c-1459044e3534.png)

**Comment by ppwwyyxx** [comment]
Please see examples https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py on how to implement multi-gpu training.

**Comment by kimalaacer** [comment]
> I try to train with multiple gpu, but it seems only one gpu work,this is my code
> ![image](https://user-images.githubusercontent.com/28799825/93172989-77f8c500-f75e-11ea-882a-71cab3f4ddc0.png)
> this is GPU infomation, seems only one work!
> ![image](https://user-images.githubusercontent.com/28799825/93173117-9e1e6500-f75e-11ea-9b3c-1459044e3534.png)

I am wondering if you were able to find a solution. 
I am limited in my coding.
