### ISSUE TITLE
Train models with background only images

### ISSUE THREAD

**Issue by pkhigh** [facebookresearch/detectron2#203]
## 🚀 Feature

I want to train images with no object along with images with multiple objects. Specifically for training instance segmentation models.
## Motivation
I need improve precision of the model. 

## Pitch
a simple parameter like INCLUDE_BKG_IMAGES in default conifg file which can be used to train images with no objects along with images with multiple objects.

**Comment by ppwwyyxx** [comment]
duplicate of #80
