### ISSUE TITLE
when I trained my model ,how can I visualize my datasheet

### ISSUE THREAD

**Issue by puZdong** [facebookresearch/detectron2#2030]
Please select an issue template from
https://github.com/facebookresearch/detectron2/issues/new/choose .

Otherwise your issue will be closed.
I useed train_net.py train my datasheet,and i can evaluate my data, but which function to use to visualize data

**Comment by ppwwyyxx** [comment]
You can find some basic instructions in the tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
