### ISSUE TITLE
Add missing checkpoint urls to model zoo mapping

### ISSUE THREAD

**Issue by arjunmajum** [facebookresearch/detectron2#2032]
## 🚀 Feature

It looks like `Misc/scratch_mask_rcnn_R_50_FPN_9x_gn.yaml` and `Misc/scratch_mask_rcnn_R_50_FPN_9x_syncbn.yaml` are missing from the `CONFIG_PATH_TO_URL_SUFFIX` mapping in [`model_zoo.py`](https://github.com/facebookresearch/detectron2/blob/master/detectron2/model_zoo/model_zoo.py).

## Motivation

I'd like to use these models :)

**Comment by ppwwyyxx** [comment]
would you like to send a PR? the URLs are available in the model zoo
