### ISSUE TITLE
caffe2 c++ inference on windows10

### ISSUE THREAD

**Issue by yang-gis** [facebookresearch/detectron2#2037]
## Instructions To Reproduce the 🐛 Bug:

I have installed caffe2 from the source on Windows10 and tested the python code.I found that Cuda (GPU) can be successfully called.Subsequently, I have tested the CPU version of the caffe2 model (init_net.pb and predict_net.pb) by caffe2 c++ api and found that it runs successfully, but the GPU version of the caffe2 model always makes mistakes at "workSpace.RunNetOnce(initNet_)". The error message is:"0x00007FFBCAE6DB9E (ucrtbase.dll) (caffe2_mask_rcnn.exe) has unhandled exception: request for serious program exit."

I don't know if it's caffe2's c++ API that doesn't support gpu models.Besides, could you give me some help?

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html says we do not provide help for windows. GPU inference should work well on Linux.
If you could include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose), maybe someone is able to notice some problems.

**Comment by yang-gis** [comment]
> As https://detectron2.readthedocs.io/tutorials/install.html says we do not provide help for windows. GPU inference should work well on Linux.
> If you could include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose), maybe someone is able to notice some problems.

Thanks for your reply,I will send the details following the issue template.
