### ISSUE TITLE
faster_rcnn_R_50_FPN_1x.yaml Result is not replicable

### ISSUE THREAD

**Issue by shijing001** [facebookresearch/detectron2#2038]
We have attempted to replicate some of your results, but got no luck.

We have tried to use two and four GPUs to replicate the model on CoCo datasets, running faster_rcnn_R_50_FPN_1x.yaml

Your reported average precision AP is 37.9, but we can only get about 33.4, and we have tried batchsize=16, 8, and 4; lr=0.02, 0.01, 0.005

If you can give us more detailed setups, like how to set up pretrained proposal models, that could be helpful.
Thank you

**Comment by ppwwyyxx** [comment]
No pre-trained proposal model is used for this config. The instruction to reproduce is given in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#introduction. 
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
