### ISSUE TITLE
Handling bounding box scales when resizing the input images in Detection models

### ISSUE THREAD

**Issue by aligholami** [facebookresearch/detectron2#2039]
Hi, I'm using a Faster RCNN implementation on my custom dataset. The bounding boxes I have are extracted without resized images. In order to use Detectron2, I need to make sure that all the input images are of equal sizes (I can achieve this with a simple resize). But I'm not sure how to scale the bounding boxes to the new resized images. Does Detectron handle this automatically?

Thanks!

**Comment by ppwwyyxx** [comment]
I'm not able to understand what you expect to do. It would be better if you could explain what inputs you provide and what you expect to achieve in the end, similar to the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=questions-help-support.md). For example, I don't know whether you're trying to train a model or not.

> I need to make sure that all the input images are of equal sizes

I'm also not sure why you need to do this.
