### ISSUE TITLE
train cannot declining

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/detectron2#204]
i use ubuntu16.04,cuda9.2,pytorh1.3, titan v100,test to train the coco detection model,but loss cannot decline,how can i solve it ?

**Comment by mathpopo** [comment]
epoch 200000,loss always lock to 0.5

**Comment by ppwwyyxx** [comment]
As said in the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md), 

> If you expect the model to work better, only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results documented in detectron2 model zoo.
(2) It indicates a detectron2 bug.

If it is one of the two cases, please reopen the issue and provide details following the issue template.
