### ISSUE TITLE
I have a question about dataset unbalance to train detect task. 

### ISSUE THREAD

**Issue by QianLingjun** [facebookresearch/detectron2#2042]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by QianLingjun** [comment]
I have a question about dataset unbalance of target detect task. 
1. First, my dataset have only one target done annotated; 
2. second, 20% positive data was annotated and 80% negative data was not annotated, because the negative sample doesn't have the target I need.
3. In the end, the question is : in target detect task, What is the effect of large sample data imbalance on training? Do I need to change my dataset  distribute, to make the train-set balance. Thanks

**Comment by ppwwyyxx** [comment]
As posted above in the issue template:

> We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.
