### ISSUE TITLE
AssertionError: Requires pyyaml>=5.1

### ISSUE THREAD

**Issue by yangjunting100** [facebookresearch/detectron2#2044]
can someone help, when i "import detectron2", something wrong "AssertionError: Requires pyyaml>=5.1" like this. How can I do.......

**Comment by ppwwyyxx** [comment]
You can install pyyaml>=5.1

**Comment by yangjunting100** [comment]
> You can install pyyaml>=5.1

Sorry, I may not have described it clearly. I can not install pyyaml=5.1, because 
![image](https://user-images.githubusercontent.com/30867357/93656754-3d916f80-fa5f-11ea-9dc2-7187c040abaa.png)

**Comment by ppwwyyxx** [comment]
How to install pyyaml is unrelated to this project so we do not help with it. The cause of such issues are probably described in http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/

**Comment by yangjunting100** [comment]
> How to install pyyaml is unrelated to this project so we do not help with it. The cause of such issues are probably described in http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/

thank too much!!!
