### ISSUE TITLE
The pred_masks field is empty

### ISSUE THREAD

**Issue by ousim97** [facebookresearch/detectron2#2049]
Hello, 
I have trained my model to detect road cracks but unfortunately the output of prediction result is empty:
`{'instances': Instances(num_instances=0, image_height=600, image_width=800, fields=[pred_boxes: Boxes(tensor([], device='cuda:0', size=(0, 4))), scores: tensor([], device='cuda:0'), pred_classes: tensor([], device='cuda:0', dtype=torch.int64), pred_masks: tensor([], device='cuda:0', size=(0, 600, 800), dtype=torch.uint8)])}`

Please, I really need your help as soon as possible.

**Comment by ppwwyyxx** [comment]
That means no object is detected.

As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
