### ISSUE TITLE
reading coco-keypoints data has bugs

### ISSUE THREAD

**Issue by zccyman** [facebookresearch/detectron2#205]
```
CUDA_VISIBLE_DEVICES=3 python tools/train_net.py \
		--config-file configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml
```

Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 143, in main
    trainer = Trainer(cfg)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/defaults.py", line 217, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/defaults.py", line 363, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/build.py", line 335, in build_detection_train_loader
    mapper = DatasetMapper(cfg, True)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/dataset_mapper.py", line 49, in __init__
    self.keypoint_hflip_indices = utils.create_keypoint_hflip_indices(cfg.DATASETS.TRAIN)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 303, in create_keypoint_hflip_indices
    check_metadata_consistency("keypoint_names", dataset_names)
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 355, in check_metadata_consistency
    entries_per_dataset = [getattr(MetadataCatalog.get(d), key) for d in dataset_names]
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 355, in <listcomp>
    entries_per_dataset = [getattr(MetadataCatalog.get(d), key) for d in dataset_names]
  File "/data0/zhangcc/code/detection/detectron2/detectron2/data/catalog.py", line 115, in __getattr__
    key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'keypoint_names' does not exist in the metadata of 'coco_2017_train'. Available keys are dict_keys(['name', 'json_file', 'image_root', 'evaluator_type', 'thing_dataset_id_to_contiguous_id', 'thing_classes', 'thing_colors']).

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by dongyangcai** [comment]
hi, i meet the same question, how do you solve it?

**Comment by jianchaoci** [comment]
> ```
> CUDA_VISIBLE_DEVICES=3 python tools/train_net.py \
> 		--config-file configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml
> ```
> 
> Traceback (most recent call last):
> File "tools/train_net.py", line 161, in
> args=(args,),
> File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/launch.py", line 52, in launch
> main_func(*args)
> File "tools/train_net.py", line 143, in main
> trainer = Trainer(cfg)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/defaults.py", line 217, in **init**
> data_loader = self.build_train_loader(cfg)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/engine/defaults.py", line 363, in build_train_loader
> return build_detection_train_loader(cfg)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/build.py", line 335, in build_detection_train_loader
> mapper = DatasetMapper(cfg, True)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/dataset_mapper.py", line 49, in **init**
> self.keypoint_hflip_indices = utils.create_keypoint_hflip_indices(cfg.DATASETS.TRAIN)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 303, in create_keypoint_hflip_indices
> check_metadata_consistency("keypoint_names", dataset_names)
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 355, in check_metadata_consistency
> entries_per_dataset = [getattr(MetadataCatalog.get(d), key) for d in dataset_names]
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/detection_utils.py", line 355, in
> entries_per_dataset = [getattr(MetadataCatalog.get(d), key) for d in dataset_names]
> File "/data0/zhangcc/code/detection/detectron2/detectron2/data/catalog.py", line 115, in **getattr**
> key, self.name, str(self.**dict**.keys())
> AttributeError: Attribute 'keypoint_names' does not exist in the metadata of 'coco_2017_train'. Available keys are dict_keys(['name', 'json_file', 'image_root', 'evaluator_type', 'thing_dataset_id_to_contiguous_id', 'thing_classes', 'thing_colors']).

I also meet the same question, you have solve it?

**Comment by XtianCarlosQ** [comment]
Hi, I don't see the name of your keypoints, but I have the same problem, and this part of code work for me:

`from detectron2.data import MetadataCatalog

keypoint_names = ['d1_i', 'd1_f', 'd2_i', 'd2_f', 'd3_i', 'd3_f', 'v1_i', 'v1_f', 'v2_i', 'v2_f']
keypoint_flip_map = [('d1_i', 'd1_f'), ('d2_i', 'd2_f'), ('d3_i', 'd3_f'), ('v1_i', 'v1_f'), ('v2_i', 'v2_f')]

for d in ["train", "test"]:
    MetadataCatalog.get(f"fiber_{d}").keypoint_names =  keypoint_names
    MetadataCatalog.get(f"fiber_{d}").keypoint_flip_map =  keypoint_flip_map
`

Also, the documentations:
https://detectron2.readthedocs.io/tutorials/datasets.html

from detectron2.data import MetadataCatalog
MetadataCatalog.get("my_dataset").thing_classes = ["person", "dog"]

**Comment by jianchaoci** [comment]
> Hi, I don't see the name of your keypoints, but I have the same problem, and this part of code work for me:
> 
> `from detectron2.data import MetadataCatalog
> 
> keypoint_names = ['d1_i', 'd1_f', 'd2_i', 'd2_f', 'd3_i', 'd3_f', 'v1_i', 'v1_f', 'v2_i', 'v2_f']
> keypoint_flip_map = [('d1_i', 'd1_f'), ('d2_i', 'd2_f'), ('d3_i', 'd3_f'), ('v1_i', 'v1_f'), ('v2_i', 'v2_f')]
> 
> for d in ["train", "test"]:
> MetadataCatalog.get(f"fiber_{d}").keypoint_names = keypoint_names
> MetadataCatalog.get(f"fiber_{d}").keypoint_flip_map = keypoint_flip_map
> `
> 
> Also, the documentations:
> https://detectron2.readthedocs.io/tutorials/datasets.html
> 
> from detectron2.data import MetadataCatalog
> MetadataCatalog.get("my_dataset").thing_classes = ["person", "dog"]
great! It do works for me!
