### ISSUE TITLE
Choosing input format for inferencing with  a trained model

### ISSUE THREAD

**Issue by colt18** [facebookresearch/detectron2#2050]
I do have `cfg.INPUT.FORMAT="BGR"` and trained the network this way. For inferencing with the trained model with the same config should I input with `BGR` or `RGB`. As the documentation says:

```
Whether the model needs RGB, YUV, HSV etc.
# Should be one of the modes defined here, as we use PIL to read the image:
# https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes
# with BGR being the one exception. One can set image format to BGR, we will
# internally use RGB for conversion and flip the channels over
```
What I understand is detectron2 reads images with PIL and default `PIL.Image.open()` reads files as `RGB`. After reading the images it is converted to `RGB` internally. Is this correct?

So for inferencing a single image with `DefaultPredictor(cfg)` with same `cfg.INPUT.FORMAT="BGR"`, should I present my images with `PIL - RGB` or `cv2 - BGR`. 

Thanks.

**Comment by ppwwyyxx** [comment]
[DefaultPredictor says](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor.__call__) it needs a BGR image. It does necessary conversion internally.
