### ISSUE TITLE
Understanding MODEL.TENSOR_MASK.SCORE_TRESH_TEST with COCO Evaluation

### ISSUE THREAD

**Issue by Bamil** [facebookresearch/detectron2#2051]
Hey,

I have difficulties to understand the MODEL.TENSOR_MASK.SCORE_TRESH_TEST Parameter in context with COCO evaluation.
MODEL.TENSOR_MASK.SCORE_TRESH_TEST filters the confidence scores/ class prediction score(?). Predictions below are considered as false positives, the ones above as true positive. This defines the precision recall curve. How is the confidence score calculated? By IoU or by something else?
COCO evaluates models in 0.05 steps over[0.5, 0.95] (here IoU is used).
When COCO evaluates over the above descirbed interval, what is the purpose of the MODEL.TENSOR_MASK.SCORE_TRESH_TEST, if COCO's Evaluation is using the values in the interval anyway?

Thanks a lot !

**Comment by ppwwyyxx** [comment]
> SCORE_TRESH_TEST filters the confidence scores

yes.

> Predictions below are considered as false positives, the ones above as true positive. This defines the precision recall curve

no. One threshold cannot define a curve. Evaluation considers all score threshold from `SCORE_THRESH_TEST` to the maximum possible scores.

> How is the confidence score calculated

You can find it in `tensormask/arch.py`, looking for "scores". It's recommended to learn the definition of COCO AP online to understand how outputs are evaluated
