### ISSUE TITLE
Different gpu id has different GPU memory allocation when using pytorch 1.6 DDP training

### ISSUE THREAD

**Issue by jiangzhengkai** [facebookresearch/detectron2#2053]
Hi, When using detection2 at pytorch 1.6 DDP training, I notice that different gpu id has different GPU memory allocation. I just want to know why this behavior happens?

## Instructions To Reproduce the Issue:

1. what exact command you run:
```
python3 tools/train_net.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml --num-gpus 8

```
2. __full logs__ you observed:
![image](https://user-images.githubusercontent.com/19780166/93738616-d0293e80-fc18-11ea-9c19-325aabb17bbb.png)

## Expected behavior:

Different gpu id should has similar GPU memory allocation.

## Environment:

![image](https://user-images.githubusercontent.com/19780166/93738566-b2f47000-fc18-11ea-8659-3b50a36ddf00.png)

**Comment by ppwwyyxx** [comment]
This is expected.

It may train on a larger image than other gpus.

**Comment by jiangzhengkai** [comment]
@ppwwyyxx image size may be not exactly the same, but not very big difference. However, the difference of gpu memory is much larger.

**Comment by blueardour** [comment]
Hi, I observed similar phenomenon
memory: [7816, 8198]
