### ISSUE TITLE
How to use voc format evaluation matrix for a coco format dataset?

### ISSUE THREAD

**Issue by Wyman-yang** [facebookresearch/detectron2#2054]
I have trained my model using coco format dataset, and evaluated using pycocotools api in detectron2. However, I need to use voc format matrix to evaluate, how can I do it? Thanks!

**Comment by ppwwyyxx** [comment]
You can implement your own evaluator https://detectron2.readthedocs.io/tutorials/evaluation.html to evaluate with other methods.
