### ISSUE TITLE
How to convert some of the models to pure pytorch code?

### ISSUE THREAD

**Issue by atakann** [facebookresearch/detectron2#2055]
## ❓ How to get pytorch codes of models

1. I want to be able to write some of the models purely in PyTorch
2. I just want to be able to see the torch operations between layers and do micro changes on them ( I can see the model summary before training begins, however the parts of Head, RegionProposal part, BackBone etc. are not given inside the repo.)

I am able to use Detectron2 on my custom dataset and get results, however I am curious of some operations and how they are implemented using PyTorch. I want to know if I am able to get/write pure PyTorch codes based on the models provided in Detectron2.

**Comment by ppwwyyxx** [comment]
>  however the parts of Head, RegionProposal part, BackBone etc. are not given inside the repo

they are all inside this repo. You can search their names and find them.
