### ISSUE TITLE
when use multi gpu(4) the gpu use ratio not very balance and very low, any skills to fix?

### ISSUE THREAD

**Issue by mlinxiang** [facebookresearch/detectron2#206]
i use 4gpu to train r50 fpn mask rcnn with batchsize 32, the gpu not used very high , any skills to fix this?
![image](https://user-images.githubusercontent.com/6283983/67942753-8526c700-fc13-11e9-95be-e8b5f054e2c2.png)

**Comment by ppwwyyxx** [comment]
That's a nice figure, but please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md), and also how this figure is generated (i.e. how and where the data in the figure is obtained).

**Comment by XiaoJiNu** [comment]
@mlinxiang hi, if I want to specify gpus' id to train a model, what shold I do?
