### ISSUE TITLE
can't find "AugmentationList" in detectron2.data.transforms.augmentation

### ISSUE THREAD

**Issue by fhong-jpg** [facebookresearch/detectron2#2066]
I Install the  [Pre-Built Detectron2 (Linux only)](). I read the detectron2’s documentation and I copied the code in the [documentation:](https://detectron2.readthedocs.io/tutorials/augmentation.html#basic-usage), 
![image](https://user-images.githubusercontent.com/54538278/94215969-be91b080-ff10-11ea-9be6-d8d57cff5b68.png)
according to the code in this repository, the class "AugmentationList" is in detectron2.data.transforms.augmentation(https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/transforms/augmentation.py), but I can't find it in my pre-build Detectron2.
https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/transforms/augmentation.py
![image](https://user-images.githubusercontent.com/54538278/94216256-8343b180-ff11-11ea-8d74-00da475e7b37.png)

**Comment by fhong-jpg** [comment]
maybe the Pre-Built versions need to update

**Comment by ppwwyyxx** [comment]
This was answered in https://detectron2.readthedocs.io/tutorials/install.html#install-pre-built-detectron2-linux-only.
We don't build these packages every day. For latest features, please install from source.
