### ISSUE TITLE
Compilation broken on AMD stack with pytorch 1.7 

### ISSUE THREAD

**Issue by hgaspar** [facebookresearch/detectron2#2068]
No diff in detectron2 code, however there was a change in pytorch hipification code that broke detectron2 compilation (details below). It is already too late to revert this change, so we can fix it as a one line change in detectron2 setup.py.

We will make a pull request to fix the issue shortly, so that detectron2 will work with pytorch 1.7 on AMD platform.

Also, we are currently making changes in pytorch hipification to make it generic, i.e. so as to preserve relationship between source and headers, even after hipification. We expect this to be in the scope of pytorch 1.8.
  
To reproduce:
pip3 install -e .

This will unfortunately now create a file under /hip/vision.cpp, while maintaining the vision.cpp in the list of sources, hence leading to failure to link.  The simple one line fix we will implement is to remove that file from the list of sources by hand.

Our plan is to have a robust hipification for extensions in the pytorch 1.8 timeframe. That will also clean up detectron2's setup.py, along the lines discussed before.

**Comment by ppwwyyxx** [comment]
Thanks @hgaspar  and @jithunnair-amd ! Looking forward to the simplifications to come!
