### ISSUE TITLE
Error on run demo.py for Panoptic-DeepLab

### ISSUE THREAD

**Issue by charlescho64** [facebookresearch/detectron2#2072]
Hello, 

I  tested  the projet "Panoptic-DeepLab"  by using demo.py (changed "import add_panoptic_deeplab_config, setting config" ) but I got error like below.
------------------------ log ----------------------------------------------------------------------
  sem_seg_head.predictor.{bias, weight}
  0%|                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demopan.py", line 92, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/appuser/detectron2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/appuser/detectron2/detectron2/engine/defaults.py", line 217, in __call__
    predictions = self.model([inputs])[0]
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/panoptic_seg.py", line 104, in forward
    sem_seg_results, sem_seg_losses = self.sem_seg_head(features, targets, weights)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/panoptic_seg.py", line 301, in forward
    y = self.layers(features)
  File "/home/appuser/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/panoptic_seg.py", line 312, in layers
    y = super().layers(features)
  File "/home/appuser/detectron2/projects/DeepLab/deeplab/semantic_seg.py", line 221, in layers
    proj_x = self.decoder[f]["project_conv"](x)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2/detectron2/layers/aspp.py", line 114, in forward
    "Input size: {} `pool_kernel_size`: {}".format(size, self.pool_kernel_size)
ValueError: `pool_kernel_size` must be divisible by the shape of inputs. Input size: torch.Size([64, 114]) `pool_kernel_size`: (32, 64)
...................................................................................

**Comment by charlescho64** [comment]
Hello, 

I tried to test the project "Panoptic-DeepLab" in colab. I have also same problem

I attach file used in colab. 

[Detectron2_PanopticDeepLab.ipynb.zip](https://github.com/facebookresearch/detectron2/files/5286908/Detectron2_PanopticDeepLab.ipynb.zip)

**Comment by bowenc0221** [comment]
Hi @charlescho64 

Could you try to add `--opts INPUT.CROP.ENABLED False` when you run demo.py?
Or manually change it to False in the config file:
```yaml
INPUT:
  CROP:
    ENABLED: False
```

This would be the easiest fix for your problem. If you want to get a better visualization result, you will need to pad the the image properly.

**Comment by charlescho64** [comment]
Thank you @bowenc0221 

I added "--opts INPUT.CROP.ENABLED False" in run script line like below
-----------------------------------------------------------------------------------------------------------------------------
python demopan.py --config-file /home/appuser/detectron2/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml --input /home/appuser/WaltTestImage/GH010328_1061.jpg --output ./pan_328.jpg  --opts MODEL.WEIGHTS ./model_final_380d9c.pkl  INPUT.CROP.ENABLED False
-----------------------------------------------------------------------------------------------------------------------------

but I still have problem.
I think it is different data label list in your work and my setting, cityscape and coco. 
I now use 'WINDOW_NAME = "COCO detections"' in demo.py.

-----------------------------------------------------------------------------------------------------------------------------
  sem_seg_head.predictor.{bias, weight}
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)
Traceback (most recent call last):
  File "demopan.py", line 93, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/appuser/detectron2/demo/predictor.py", line 55, in run_on_image
    panoptic_seg.to(self.cpu_device), segments_info
  File "/home/appuser/detectron2/detectron2/utils/visualizer.py", line 457, in draw_panoptic_seg_predictions
    pred = _PanopticPrediction(panoptic_seg, segments_info)
  File "/home/appuser/detectron2/detectron2/utils/visualizer.py", line 153, in __init__
    self._sinfo = {s["id"]: s for s in segments_info}  # seg id -> seg info
TypeError: 'NoneType' object is not iterable
-----------------------------------------------------------------------------------------------------------------------------

**Comment by bowenc0221** [comment]
We are working on the demo for Panoptic-DeepLab right now, if you want to try it now, you will need to further generate `segments_info` using this code:
https://github.com/facebookresearch/detectron2/blob/cb7e86f821f0bedb3da8f1e0a527dd821d8e5f7e/detectron2/evaluation/panoptic_evaluation.py#L72-L96

**Comment by charlescho64** [comment]
Hi @bowenc0221  

I hope you finish working demo for Panoptic-DeepLab and let me how to use.  I am really interesting in your work.

Thanks.

**Comment by bowenc0221** [comment]
@charlescho64 Please pull the latest change in master branch.

**Comment by charlescho64** [comment]
Hello @bowenc0221 

I pull latest version and installed it. 

but I still have problem.

1.  Error log 
[09/29 02:52:21 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/home/appuser/detectron2_repo/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml', input=['/home/appuser/WaltTestImage/person.jpg'], opts=['MODEL.WEIGHTS', 'https://dl.fbaipublicfiles.com/detectron2/PanopticDeepLab/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32/model_final_380d9c.pkl', 'INPUT.CROP.ENABLED', 'False'], output='./output_person.jpg', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 80, in <module>
    cfg = setup_cfg(args)
  File "demo.py", line 26, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/appuser/detectron2_repo/detectron2/config/config.py", line 49, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/common/config.py", line 118, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 477, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.RESNETS.RES5_MULTI_GRID'

2. I used below command line 
~$python demo.py --config-file /home/appuser/detectron2_repo/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml --input /home/appuser/WaltTestImage/person.jpg --output ./output_person.jpg --opts MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/PanopticDeepLab/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32/model_final_380d9c.pkl INPUT.CROP.ENABLED False

**Comment by bowenc0221** [comment]
Uncomment these two lines:
https://github.com/facebookresearch/detectron2/blob/5c9e0d9595316ce3447612a4ce1f602911bde2b7/demo/demo.py#L23-L25

**Comment by charlescho64** [comment]
Hi @bowenc0221 

Yes, I don't use those.
I don't modify original demo.py and it is same to your comment. is it right?

Thanks...

**Comment by bowenc0221** [comment]
I mean you should uncomment those two lines in order to add Panoptic-DeepLab config.

**Comment by charlescho64** [comment]
Hello @bowenc0221 

I am so sorry .....

**Comment by bowenc0221** [comment]
Hi @charlescho64 

Can you download the new weight again? (new link: https://dl.fbaipublicfiles.com/detectron2/PanopticDeepLab/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32/model_final_bd324a.pkl)

There is some problem with the old weight.

**Comment by charlescho64** [comment]
Thank you @bowenc0221 

I got some good but I have some problem. 

I got good result for input image in "png" type(from cityscape dataset), but bad result in input image in "jpg" type(from internet).

Do you think I have other thing to your work for getting good result ?

![frank2_out](https://user-images.githubusercontent.com/3125859/94982894-30a16f80-0579-11eb-9121-aff915d7e0fa.png)
![328_out](https://user-images.githubusercontent.com/3125859/94982897-4151e580-0579-11eb-9649-749750cba524.jpg)

**Comment by soldierofhell** [comment]
I've got similar first impression, that the model is overfitted to cityscape images. Don't know if cityscape has such unique features or the model has problem in generalization.

**Comment by bowenc0221** [comment]
@charlescho64 @soldierofhell

I tested with some random images online and could not reproduce your issue. This image below is not a Cityscapes image and Panoptic-DeepLab gives reasonable predictions.

The command I'm using: `python demo/demo.py --config-file projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_dsconv.yaml --input output/8-Figure1-1.png --output output/demo --opts MODEL.WEIGHTS models/model_final_23d03a.pkl`

**Note** that I did not set `INPUT.CROP.ENABLED False`, instead I uncommented these lines in ASPP:

I haven't tried setting `INPUT.CROP.ENABLED False`. But Cityscapes is a dataset with high-resolution images, so I'm not sure if the model generalizes well to low-resolution inputs.

https://github.com/facebookresearch/detectron2/blob/f71d8458e7fb9a45bf46518e8371bef5a8afb93e/detectron2/layers/aspp.py#L131-L136

![8-Figure1-1](https://user-images.githubusercontent.com/25308473/103652673-0caf4a80-4f29-11eb-9629-0d27579a75b0.png)
![demo](https://user-images.githubusercontent.com/25308473/103652680-0f11a480-4f29-11eb-969f-7be4b309c65c.png)

**Comment by Doch88** [comment]
Any real solution to this?
Commenting those lines doesn't seem to be a proper solution to this problem.
As a workaround, it should be better to use pool_kernel_size=None, but that doesn't really solve the problem
