### ISSUE TITLE
 Can you give me some advice for backbone feature extraction with multi-gpu.

### ISSUE THREAD

**Issue by liuhl-source** [facebookresearch/detectron2#2076]
>Is there a cfg parameters I should set to move the backbone model to gpu?

No but you can call `backbone.to('cuda')`. The functions are meant to build only the architecture and `cfg.MODEL.DEVICE` is not used. This is indeed a bit confusing and we'll think about how to improve this

_Originally posted by @ppwwyyxx in https://github.com/facebookresearch/detectron2/issues/1926#issuecomment-675764402_

**Comment by liuhl-source** [comment]
I apply torch.nn.DataParallel while get the error"RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)"

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
