### ISSUE TITLE
How to register my own dataset in caffe2_converter.py?

### ISSUE THREAD

**Issue by x12901** [facebookresearch/detectron2#2077]
## ❓ How to do something using detectron2

I want to convert my training model to call it in c++.I tried to register it.I modify the script to register it.
`register_coco_instances("aline_test", {}, "D:/cwge/detectron2/obj/aline/test.json", "D:/cwge/detectron2/obj/aline/test")`
Or create in the script
```
def register_datasets(root, cfg, dataset_prefix='aline', thing_classes=["long","short1","short2"]):
    for name in ["train", "test"]:
        DatasetCatalog.register(f"{dataset_prefix}_{name}", lambda name=name: load_coco_json(os.path.join(root,
                                                                                                "aline",
                                                                                                f"{name}.json"),
                                                                                    os.path.join(root, name),
                                                                                    f"{dataset_prefix}")
                            )
        MetadataCatalog.get(f"{dataset_prefix}_{name}").set(**{
            "thing_classes": thing_classes,
            "evaluator_type": "coco",

            # "keypoint_names": ['centre'],
            # "keypoint_flip_map": tuple(),
            # "keypoint_connection_rules": [],
        })

    # Update train_test sets name in the cfg.
    cfg.defrost()
    cfg.DATASETS.TRAIN = (f'{dataset_prefix}_train',)
    cfg.DATASETS.TEST = (f'{dataset_prefix}_test',)
    # cfg.MODEL.KEYPOINT_ON = True
    cfg.freeze()

```
This will make the program report errors.
`[W init.h:137] Caffe2 GlobalInit should be run before any other API calls.`
## ❓ What does an API do and how to use it?
 https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_converter.py

**Comment by ppwwyyxx** [comment]
> [W init.h:137] Caffe2 GlobalInit should be run before any other API calls.

this is not an error and can be ignored.

**Comment by x12901** [comment]
> > [W init.h:137] Caffe2 GlobalInit should be run before any other API calls.
> 
> this is not an error and can be ignored.
> If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

Thanks, I've asked a new question.https://github.com/facebookresearch/detectron2/issues/2080#issue-710678070
