### ISSUE TITLE
How to use ground truth bbx instead of RPN when inferencing

### ISSUE THREAD

**Issue by Jianghanxiao** [facebookresearch/detectron2#2078]
I want to use the ground truth bbx when inferencing to see the performance of the network in addition to RPN. Is there some easy to do so? Should I make the RPN return the gt bbx? But will it influence the number of proposals? Could you give me some suggestions? Or is there some solution?

Besides, I'm not sure if it can be a new option in the cfg. I have checked cfg and don't find using gt bbx option.

**Comment by ppwwyyxx** [comment]
You can implement it by calling backbone and roi_heads yourself, similar to https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model
