### ISSUE TITLE
Will the predicted boxes be out of boundary?

### ISSUE THREAD

**Issue by Cknex** [facebookresearch/detectron2#2079]
Hello!

I'm using faster-rcnn to detect objects, and the flag "TRIAN_ON_PRED_BOXES" is set to be True.

However, during **training**, I think it might be dangerous because the predicted box might be outside the image . 
Is it necessary to add a check to ensure the predicted box is inside the image?

**Comment by ppwwyyxx** [comment]
I can't predict if this idea is good or not. If you found it important, feel free to let us know and we may consider it as a feature.
