### ISSUE TITLE
Are there any pre-trained model files available for Trident Net? 

### ISSUE THREAD

**Issue by kira0992** [facebookresearch/detectron2#208]
## ❓ Questions and Help

Are there plans to release pre-trained model files for "projects" too. It would be really helpful to have Dense Pose and Trident Net models too if they are available.

**Comment by lyttonhao** [comment]
Thanks for your interest. We will release the pretrained TridentNet models soon.

**Comment by ppwwyyxx** [comment]
duplicate of #65
