### ISSUE TITLE
Speeding up inference

### ISSUE THREAD

**Issue by jcpayne** [facebookresearch/detectron2#2083]
I have a working 101-layer TridentNet model and I want to run a large number of (500 x 500) images through it.  Inference takes about 1 second / image on a GPU and I'm wondering if anyone has suggestions for how to speed that up. We can't afford to reduce the resolution, unfortunately, because we are looking for very small objects.  I've tried using inference_on_model(), Trainer.test(), as well as DefaultPredictor(), and the speed is about the same for all.  I wrote a custom dataloader to batch the images, but batching doesn't help much (possibly because the batch size is small -- 4).  I haven't yet gotten inference working on multiple GPUs but it seems from the code that the expectation is that multiple GPUs will only be used during training.  Am I missing anything about Detectron2, or is this just a non-Detectron2-specific issue of how to brute force a large job?

**Comment by ppwwyyxx** [comment]
No models provided in https://github.com/facebookresearch/detectron2/tree/master/projects/TridentNet#results-on-ms-coco-in-detectron2 should run as slow as 1 s on a GPU. If that's the case, please provide details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by MathijsNL** [comment]
Hi there,

I took an example model from the link that @ppwwyyxx  posted.

Then I butchered the train_net.py and tested the [tridentnet_fast_R_50_C4_1x](https://dl.fbaipublicfiles.com/detectron2/TridentNet/tridentnet_fast_R_50_C4_1x/148572687/model_final_756cda.pkl)

Test image is a 1934x1214 jpg image. Result on GTX 1080 for 10 images:
**Inference time per image is : 0.23493354320526122 s**

I renamed the model to model.pkl and placed a test.jpg in the projects/TridentNet folder.

Could you check what your time per image is when using below inference script?
```
python train_net.py --config-file configs/tridentnet_fast_R_50_C4_1x.yaml --eval-only MODEL.WEIGHTS model.pkl
```

```
#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

"""
TridentNet Training Script.

This script is a simplified version of the training script in detectron2/tools.
"""

import os

from detectron2.checkpoint import DetectionCheckpointer
from detectron2.config import get_cfg
from detectron2.engine import DefaultTrainer, default_argument_parser, default_setup, launch
from detectron2.evaluation import COCOEvaluator
from detectron2.engine import DefaultPredictor
from tridentnet import add_tridentnet_config
import cv2
import time


class Trainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        return COCOEvaluator(dataset_name, cfg, True, output_folder)


def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    add_tridentnet_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    #cfg.freeze()
    return cfg


def main(args):
    cfg = setup(args)

    if args.eval_only:
        model = Trainer.build_model(cfg)
        DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
            cfg.MODEL.WEIGHTS, resume=args.resume
        )
        res = Trainer.test(cfg, model)
        return res

    trainer = Trainer(cfg)
    trainer.resume_or_load(resume=args.resume)
    return trainer.train()



args = default_argument_parser().parse_args()
print("Command Line Args:", args)
def prepare_pridctor(model_name, model_score):
    # create config
    cfg = setup(args)
    # below path applies to current installation location of Detectron2
    cfg.MODEL.WEIGHTS = "model.pkl"
    cfg.MODEL.DEVICE = "cuda"

    # Prepare a predictor by default
    predictor = DefaultPredictor(cfg)
    print("Predictor has been initialized.")
    return (predictor)

pred = prepare_pridctor("model.pkl", 0.9)
image = cv2.imread("test.jpg")

# Warmup GPU
output = pred(image)

start = time.time()

for x in range (0,10):
    output = pred(image)

print(f"Inference time per image is : {(time.time() - start)/10} s")
```

**Comment by jcpayne** [comment]
Thanks for the suggestion.   I'm out of the office for a few days but I'll try it when I return.
