### ISSUE TITLE
Model gets larger than after training on custom dataset

### ISSUE THREAD

**Issue by mao-jy** [facebookresearch/detectron2#2084]
Pretrained model of  "faster_rcnn_X_101_32x8d_FPN" is 420.8 MB. But after I train on my own data, I obtain a model which is 835.2 MB, much larger than before. How can I keep the model the same size as the pretrained one?

**Comment by ppwwyyxx** [comment]
Not only the model is saved. This is a pytorch question answered in https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training
