### ISSUE TITLE
How to deploy the model in detectron2/project like TridentNet?

### ISSUE THREAD

**Issue by james77777778** [facebookresearch/detectron2#2085]
## ❓ How to do something using detectron2

I trained a TridentNet model and found it better than faster-rcnn model.
I try to deploy TridentNet with `/tools/deploy/caffe2_converter.py` by slightly modifying it.
Using `run_eval`, I cannot get any bbox in validation set, but I can easily deploy another faster-rcnn model trained on my own dataset and got good results.

So is it possible to deploy the model which is provided in `detectron2/project`?

Thanks!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/tree/master/projects/ contains research models that we don't provide deployment support.
