### ISSUE TITLE
Deploying PointRend model with ONNX

### ISSUE THREAD

**Issue by jhagege** [facebookresearch/detectron2#2086]
Hi, I have issues when exporting PointRend model with ONNX.

Particularly, this code gets me the errors below:
![image](https://user-images.githubusercontent.com/7504908/94727981-307e5580-0368-11eb-8d7e-afe218126b43.png)

```
> 2037 defined in (%2037 : Long() = onnx::Mul(%2031, %2036) # detectron/projects/PointRend/point_rend/point_features.py:138:0
> )
E   RuntimeError: Unexpected node type: onnx::Mul

```

Is it officialy supported ? Has anyone had success doing so ? 

Thanks much for any insights.

**Comment by ppwwyyxx** [comment]
Models in https://github.com/facebookresearch/detectron2/tree/master/projects/ are research models that we don't provide deployment support.
