### ISSUE TITLE
Model conversion Pytorch to ONNX 

### ISSUE THREAD

**Issue by aquib23** [facebookresearch/detectron2#2087]
I am trying to convert the PyTorch to onnx and passed two different parameters the 1st and 2nd and getting the AssertionError can you tell where am I doing the mistake I hardly find any implementation of the conversion

```
## Config
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
model = build_model(cfg)

## Loading model
DetectionCheckpointer(model).load("/content/drive/My Drive/Weights/model_final.pth")  

## Conversion ONNX
inputs = torch.randn(1, 1, 1000, 1000)

## trying 1st way of converting
export_onnx_model(cfg, model, inputs)

## trying 2nd way of converting
export_onnx_model(detectron2.export.add_export_config(cfg), detectron2.modeling.build_model(cfg), inputs)
```

**Comment by Nagamani732** [comment]
Hi,

I think this is too late but it might be useful for someone. I have created notebook using colab to convert the detectron2 pytorch model to onnx model. 

Please find it here: https://github.com/Nagamani732/colab_files/blob/main/detectron2_pytorch_to_onnx.ipynb

**Comment by NguyenThanhAI** [comment]
@Nagamani732 Can you run inference with onnxruntime InferenceSession. I encounter with "AliasWithName is not a registered function/op" when run converted onnx model". Can you solve this problem?

**Comment by NguyenThanhAI** [comment]
@Nagamani732  Can you run inference with onnxruntime InferenceSession. I encounter with "AliasWithName is not a registered function/op" when run converted onnx model". Can you solve this problem?

**Comment by NguyenThanhAI** [comment]
@Nagamani732   Can you run inference with onnxruntime InferenceSession. I encounter with "AliasWithName is not a registered function/op" when run converted onnx model". Can you solve this problem?

**Comment by Nagamani732** [comment]
@NguyenThanhAI As of now, you will not able to run using onnxruntime since it is not supported. The exported model contains custom ops only available in caffe2, therefore it cannot be directly executed by other runtime (such as onnxruntime or TensorRT). Thank you

Please have a look: https://detectron2.readthedocs.io/en/latest/modules/export.html#detectron2.export.Caffe2Tracer.export_onnx

**Comment by augustoolucas** [comment]
@Nagamani732 can we use the `torch.onnx.export` method to export the model and then be able to use it with the onnxruntime?

**Comment by Nagamani732** [comment]
@augustoolucas Please refer to my previous comment. Thanks

**Comment by augustoolucas** [comment]
@Nagamani732 yeah, I understand that by using the `export_onnx` method we cannot use the onnxruntime. What I would like to know is whether we could use the `torch.onnx.export` method from PyTorch and, by doing so, be able to use the onnxruntime.
