### ISSUE TITLE
Prebuilt Docker Images

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#2089]
## 🚀 Feature
Along with the prebuilt installation files, it would be nice to have prebuilt docker images with the various possible combinations of CUDA, PyTorch and detectron2. Obviously, the number of combinations is quite large, but the building of the different docker images should be easy to automate.

## Motivation & Examples
It would facilitate testing and deployment.

**Comment by MathijsNL** [comment]
There already is a docker available:
[https://github.com/facebookresearch/detectron2/tree/master/docker](https://github.com/facebookresearch/detectron2/tree/master/docker)

This can be used or adapated to your own needs.

**Comment by maxfrei750** [comment]
@MathijsNL Thanks for the hint. I already use that file, but I still think that it would be a nice feature to have _prebuilt_ images in the docker hub. That way users could just pull the configuration they need without any tweaking. 

For instance, I was about to deploy custom code that was based on detectron2 v0.1. However, since the docker file you refer to always uses the latest version of detectron, it was not compatible. It was easy to fix the docker file, but it would have been great to just pull the required version and run it right away.

**Comment by ppwwyyxx** [comment]
While having more docker images sound great, it's a bit too much overhead for us to maintain the extra releases on dockerhub. All our releases have a very predictable installation URL as in https://github.com/facebookresearch/detectron2/releases. I think using these packages on top of the pytorch dockers should be enough for users to create a dockerfile that accepts detectron2/pytorch/cuda versions as arguments.
