### ISSUE TITLE
Model behavior is different on different machine system on same images with same configurations 

### ISSUE THREAD

**Issue by ashwin580** [facebookresearch/detectron2#2105]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

I have trained the custom models to detects the signature on documents. The model is trained on google colab and  i have generated the model file also.
 But the model is behaving different on different machine. I have tested the model on cpu machine , It give perfect result on cpu machine but when i am testing it on GPU machine it is not detecting the all objects or missing some objects.

The working environment where results are perfect :

sys.platform           linux
Python                 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy                  1.19.1
detectron2             0.2.1 @//detectron/detectron2_repo/detectron2
Compiler               GCC 7.5
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.6.0+cpu @//detectron/lib/python3.6/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 7.2.0
torchvision            0.7.0+cpu @//detectron/lib/python3.6/site-packages/torchvision
fvcore                 0.1.2
cv2                    4.4.0

The second environment which does not detect all the objects : 

sys.platform            linux
Python                  3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy                   1.19.2
detectron2              0.2.1 @//detectron_updated/detectron2_repo/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.0
detectron2 arch flags   6.1
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0+cu101 @//detectron_updated/detectron_env/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1070 (arch=6.1)
CUDA_HOME               /usr/local/cuda-10.0
Pillow                  7.2.0
torchvision             0.7.0+cu101 @//detectron_updated/detectron_env/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2
cv2                     4.4.0
 
I have tested the model on colab and there its working perfect but on GPU machine its not detecting all the objects correctly..

Please provide any solution for these scenarios....

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
