### ISSUE TITLE
Model behavior is different on different machine system on same images with same configurations

### ISSUE THREAD

**Issue by ashwin580** [facebookresearch/detectron2#2107]
## Instructions To Reproduce the Issue:

I have trained the custom models to detects the signature on documents. The model is trained on google colab and i have generated the model file also.
But the model is behaving different on different machine. I have tested the model on cpu machine , It give perfect result on cpu machine but when i am testing it on GPU machine it is not detecting the all objects or missing some objects.

1. configuration used to run the model :
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.DATASETS.TEST = ('doc_data/test',)  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.DEVICE = "cpu"
cfg.MODEL.WEIGHTS = "model_final.pth"
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set the testing threshold for this model

predictor = DefaultPredictor(cfg)
```

## Expected behavior:

The model should give same output on same images on different machine but the model is not giving same result on different machine.

I am using same configuration also but the results are different on GPU Machine.

## Environment:

- The working environment where results are perfect :
```
sys.platform linux
Python 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy 1.19.1
detectron2 0.2.1 @//detectron/detectron2_repo/detectron2
Compiler GCC 7.5
CUDA compiler not available
DETECTRON2_ENV_MODULE
PyTorch 1.6.0+cpu @//detectron/lib/python3.6/site-packages/torch
PyTorch debug build False
GPU available False
Pillow 7.2.0
torchvision 0.7.0+cpu @//detectron/lib/python3.6/site-packages/torchvision
fvcore 0.1.2
cv2 4.4.0
```

-The second environment which does not detect all the objects :
```
sys.platform linux
Python 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy 1.19.2
detectron2 0.2.1 @//detectron_updated/detectron2_repo/detectron2
Compiler GCC 7.5
CUDA compiler CUDA 10.0
detectron2 arch flags 6.1
DETECTRON2_ENV_MODULE
PyTorch 1.6.0+cu101 @//detectron_updated/detectron_env/lib/python3.6/site-packages/torch
PyTorch debug build False
GPU available True
GPU 0 GeForce GTX 1070 (arch=6.1)
CUDA_HOME /usr/local/cuda-10.0
Pillow 7.2.0
torchvision 0.7.0+cu101 @//detectron_updated/detectron_env/lib/python3.6/site-packages/torchvision
torchvision arch flags 3.5, 5.0, 6.0, 7.0, 7.5
fvcore 0.1.2
cv2 4.4.0
```

I have tested the model on colab and there its working perfect but on GPU machine its not detecting all the objects correctly..

Please provide any solution for these scenarios....

**Comment by ppwwyyxx** [comment]
The instructions are not sufficient to reproduce the issue because it is not runnable without certain data and model files.
Please reduce the instructions and try providing something that can be reproduced. https://stackoverflow.com/help/minimal-reproducible-example might help.

**Comment by MathijsNL** [comment]
Are you sure the model is the same on both of the machines? Could you calculate the hashes for them?

**Comment by ashwin580** [comment]
> Are you sure the model is the same on both of the machines? Could you calculate the hashes for them?

Yes, I am using same model on both machine....

**Comment by MathijsNL** [comment]
If you provide some code as @ppwwyyxx mentioned, I can do some inference on both CPU and GPU to see if the results are reproducible.
