### ISSUE TITLE
How to register and modify a new fpn?

### ISSUE THREAD

**Issue by Andrew-Zhu** [facebookresearch/detectron2#2108]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:

I want to modify fpn module in rethinanet. 

But I failed.
All I want to do is change the structure of fpn, and the other settings follow the default settings in retinanet_R_50_FPN_1x.yaml. What should I do? 

I have tried two methods:
1. modify fpn directly in
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/backbone/fpn.py
and run tools/train_net.py

I failed. because I find that the program does not run into the fpn.py file. Maybe it is because I uesd the Pre-Built Detectron2 instead of my own built Detectron2.

2. adding new module called new_fpn.py and register.
https://detectron2.readthedocs.io/tutorials/write-models.html
I can only register it after building and installing a new detectron2 environment.  But this method is tedious, which means I have to install detecteon2 each time I want to change the structure and debug the structure of fpn.  Could you give me an easy method?

3.writing a totally new program.
I have not tried yet, because I think there may be easier way to solve this problem.

2. what outputs you are expecting:

run the model with modified fpn.
I have experimented the retinanet_R_50_FPN_1x.yaml and succeed. All I want is an easy way to change the structure of fpn.py and do some new experiments. Should I install Detectron2 each time I debug a new structure?

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/
https://detectron2.readthedocs.io/tutorials/write-models.html
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/backbone/fpn.py

NOTE:

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.
I have check 
https://detectron2.readthedocs.io/tutorials/write-models.html
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/backbone/fpn.py

**Comment by ppwwyyxx** [comment]
> writing a totally new program.
I have not tried yet, because I think there may be easier way to solve this problem.

I'm not sure what you mean by "writing a totally new program". Users are expected to write new code, instead of modifying the library. You don't have to reinstall the library after making any changes, if the changes are not in the library.

**Comment by Andrew-Zhu** [comment]
"writing a totally new program" means "creating a new project" like "TridentNet" or "PointRend"
So you  suggest to create a new project "Retinanet_newfpn_1x"? Thanks

**Comment by ppwwyyxx** [comment]
I suggest writing code that doesn't live in the library. You can call it a new project, although the "new project" probably only needs one file like if your model is not complicated, like https://github.com/facebookresearch/moco/blob/master/detection/train_net.py
