### ISSUE TITLE
How many GPUs does the training need at least?

### ISSUE THREAD

**Issue by dalanmaobu** [facebookresearch/detectron2#2113]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by MathijsNL** [comment]
In theory zero. You can do training and inference on CPU
```
cfg.MODEL.DEVICE = "cpu"
```

Practical at least 1.

**Comment by ppwwyyxx** [comment]
thanks @MathijsNL  for the answer!

**Comment by MathijsNL** [comment]
A small addition:

Configs are written for 8-GPU training. **For most models, CPU training is not supported.**

```
The configs are made for 8-GPU training. To train on 1 GPU, you may need to change some parameters, e.g.:

./train_net.py \
  --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
  --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
```
[https://detectron2.readthedocs.io/tutorials/getting_started.html](https://detectron2.readthedocs.io/tutorials/getting_started.html)

**Comment by dalanmaobu** [comment]
thanks @MathijsNL for the answer!
