### ISSUE TITLE
Inferences code for detectron2 model to caffe2 format 

### ISSUE THREAD

**Issue by NaeemKhan333** [facebookresearch/detectron2#2119]
Thanks for sharing such a nice work . I have converted the 
-> detectron2 model to caffe2 format 

using the 

https://github.com/facebookresearch/detectron2/tree/master/tools/deploy/caffe2_converter.py

As output , I get the following three files
->model.pb
->model.pbtxt
->model_init.pb

Now I want to do inferences on input image using python , can you provide the inferences script or guide me what are the steps I need to do for designing the script.Thanks

**Comment by ppwwyyxx** [comment]
`caffe2_converter.py` has a command-line option that does inference using python.

**Comment by NaeemKhan333** [comment]
@ppwwyyxx I want to test the converted model to input image and want to see the result. Can you guide me please.Thanks
