### ISSUE TITLE
Replace sigmoid_focal_loss_jit with maskrcnn_benchmark's SigmoidFocalLoss error

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/detectron2#212]
## ❓ Questions and Help

General questions about detectron2.

I merge maskrcnn_benchmark's SigmoidFocalLoss implementation into detectron2 and replace retinanet's loss cls with mrcnn's. But I noticed that your loss implementation is different from maskrcnn_benchmark's, why is this?

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

**Comment by ppwwyyxx** [comment]
I don't think they are mathematically different.
