### ISSUE TITLE
Keep the consistence of the random seed

### ISSUE THREAD

**Issue by serend1p1ty** [facebookresearch/detectron2#2121]
Hi, detectron2 set the random seed at two places
https://github.com/facebookresearch/detectron2/blob/06ff902d1d5eecb07297fe285151b99c42252e9b/detectron2/data/samplers/distributed_sampler.py#L37

https://github.com/facebookresearch/detectron2/blob/06ff902d1d5eecb07297fe285151b99c42252e9b/detectron2/engine/defaults.py#L146

Detectron2 sets the random seed of a worker twice. Is it by design?

**Comment by ppwwyyxx** [comment]
It is.

https://github.com/facebookresearch/detectron2/blob/06ff902d1d5eecb07297fe285151b99c42252e9b/detectron2/data/samplers/distributed_sampler.py#L37 is just a local random number that does not affect anything outside of that class.

**Comment by serend1p1ty** [comment]
Thanks for your response.

I note that the TrainingSample() without passing `cfg.SEED` as an argument.

https://github.com/facebookresearch/detectron2/blob/06ff902d1d5eecb07297fe285151b99c42252e9b/detectron2/data/build.py#L341

So the following code will be run. https://github.com/facebookresearch/detectron2/blob/06ff902d1d5eecb07297fe285151b99c42252e9b/detectron2/data/samplers/distributed_sampler.py#L37

It means the data loaded is different at each time the model is trained.

I don't know the logic of this design, can you give some explanation?

**Comment by ppwwyyxx** [comment]
> It means the data loaded is different at each time the model is trained.

That's correct if `cfg.SEED=-1`.

> how we achieve fully deterministic behavior in data loading?

Setting `cfg.SEED` will achieve deterministic behavior in data loading.

**Comment by hiyyg** [comment]
@ppwwyyxx I have a question. If different GPU has a different seed, will the parameters be initialized differently? Why not use a same seed for all ranks?
