### ISSUE TITLE
Transfer learning on detectron2 using baseline model

### ISSUE THREAD

**Issue by ghazni123** [facebookresearch/detectron2#2124]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
Input 1: COCO Instance Segmentation Baselines with Mask R-CNN 
Input 2: New custom dataset of 'cat' class (high resolution images)

2. what outputs you are expecting:
Transfer learn baseline model "COCO Instance Segmentation Baselines with Mask R-CNN" with new custom data of high quality/resolution of one particular class e.g. 'cat' which is already in cocodataset. However the goal is to retain the ability of segmentation of the rest of the classes as well. Means the transfer-learned-trained model perform better on 'cat' class due to new custom training images but retaining the ability to segment as per quality of the basline model  

The class label is same as one of cocodataset e.g. 'cat'. What is the best way that detectron2 can/will learn better:

Option 1: develop a new dataset in coco format (with label as 'cat' and do transfer-learning or retraining using methods described as in https://detectron2.readthedocs.io/tutorials/datasets.html). 

Option 2: develop a new dataset in coco format with NEW LABEL as 'mycat' which will be new class. In this case there is no conflict with existing classes but I don't know if as a process of re-training the new model might be missed out few things which have already been learned

Could you please a advise which of the options is best to get refinements in one of existing classes in cocodataset with detectron2.

**Comment by ppwwyyxx** [comment]
We do not make predictions on what approach works better - that's a machine learning question that's not related to the library. If there are questions on how to implement those approaches, we might be able to help.
