### ISSUE TITLE
Parallel inference on DensePose

### ISSUE THREAD

**Issue by AbdurNawaz** [facebookresearch/detectron2#2125]
## Program crashes after processing 2-3 frames parallelly

The inputs to my program are a few videos, and the output is the location of the hands of humans in the video which I'm doing using the iuv arrays. I found that after giving input of the 2-3 videos the program crash, I'm currently using colab and the frame size is 1080x1350.

I would like to process more videos in parallel

Am I doing something wrong? can detectron easily process some 10-20 or more frames parallelly on a colab like GPU? Given memory and GPU utilization constraints and I reduce the size of the image a little bit?

the GPU on colab was a Tesla P100 PCIE 16GB

I noticed that when I ran DensePose on only one video stream it was using around 20% of the memory.

If it is not possible, will I be somehow able to optimize it to do so?

**Comment by RSKothari** [comment]
I'm facing similar issues when running the `apply_net` tool. After around 100 frames or so, the GPU memory maxes out and inference using apply_net crashes.
