### ISSUE TITLE
How can someone install intermediate versions between two releases?

### ISSUE THREAD

**Issue by SupreethN** [facebookresearch/detectron2#2126]
I installed Detectron2 on March 31st. 
The v0.1.1 was released on March 5th and v0.1.2 was released on May 4th.

When I installed Detectron2, there were already some changes made to the [v0.1.1 source code](https://github.com/facebookresearch/detectron2/archive/v0.1.1.zip).
For example,  ```detectron2.layers``` already had ```Linear``` (which is not present in v0.1.1 source code). 
Therefore it gives error if I run```from detectron2.layers import Linear``` when using v0.1.1 source code.

Also, the code I installed is not the same as [v0.1.2 source code](https://github.com/facebookresearch/detectron2/archive/v0.1.2.zip).

In a sense, it is an intermediate code between two versions.

I have implemented a project based on my code and I want to release the code for a paper now. So how can I ask someone to install the `intermediate' version I am using? Can I zip my detectron2 code and ask them to build from that? Will that work?

**Comment by ppwwyyxx** [comment]
If you use an intermediate version and want others to use the same version as you, you can give them the commit id you use.

pip can install using id, e.g.:
```
pip install 'black @ git+https://github.com/psf/black@673327449f86fce558adde153bb6cbe54bfebad2'
```

**Comment by SupreethN** [comment]
How can I get the commit ids for all the commits with dates for detectron2?

**Comment by ppwwyyxx** [comment]
`git log`.
