### ISSUE TITLE
Panoptic FPN configuration on Cityscapes dataset

### ISSUE THREAD

**Issue by huang-ziyuan** [facebookresearch/detectron2#2130]
Hi, I trained the panoptic FPN on Cityscapes and only got ~73.8 mIoU for several times, using the sum version.
The configuration is at the end of this issue, where the PlainSemSegFPNHead is just a replication of SemSegFPNHead.
Could you tell me where the configuration is wrong? If would be better if you could provide configurations for Panoptic FPN on Cityscapes to reproduce the 74.5 in the paper.

Thanks!

MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SEM_SEG_HEAD:
    NAME: "PlainSemSegFPNHead"
    NUM_CLASSES: 19
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
SOLVER:
  BASE_LR: 0.01
  STEPS: (40000, 55000)
  MAX_ITER: 65000
  IMS_PER_BATCH: 32
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
VERSION: 2

**Comment by ppwwyyxx** [comment]
I think you mean "Semantic FPN" (using terminology in the paper).
We don't release that particular model and I don't know what exactly setting was used back then. We do have a SemanticFPN + PointRend config&model released here: https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend/. If you remove PointRend from it, it should give a decent baseline (I think better than the number you referred to), although it's probably not exactly what the PanopticFPN paper has used.
