### ISSUE TITLE
Is the data loader a final place where image size is changed?

### ISSUE THREAD

**Issue by SupreethN** [facebookresearch/detectron2#2132]
Is the shape of the tensor in ```image``` field of a dataloader item, the size of the **final** resized image? 

For example,  [here](https://github.com/facebookresearch/detectron2/blob/master/tools/plain_train_net.py#L158) ```data``` is an item in the ```train_data_loader```. It contains data for ```batch_size``` number of images. If I want to get the resized image shape used by RCNN for the first image in the batch, I was thinking to use ```data[0]['image'].shape```. 

Apart from the this point onward, is there any other place where images are resized to different sizes?

**Comment by ppwwyyxx** [comment]
As the code shows `data` is the input to model.
Models in detectron2 do not resize input images.
