### ISSUE TITLE
 I want to get the pose(rx,ry,rz) of the object.

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2135]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

Hello I am working on separating the stacked bolts. Until now, 
the bolt classification has been successful by training, 
but I am suffering because I cannot obtain the pose (axis) of the bolt.

What I'm curious about

1. When using XYWHA-ABS, does the ANGLE value come out?

2. Where does the ANGLE value come from?

3. Is there any way to get the POSE of the object?

4. Doesn't the angle value come out with the data_dataset_dict function? (Only 0 is displayed.)

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
Model can be configured to train/predict XYWHA boxes if your data is annotated with XYWHA boxes.
