### ISSUE TITLE
No detection while reloading the model in a new python file after training on custom dataset

### ISSUE THREAD

**Issue by karankatiyar92** [facebookresearch/detectron2#2137]
Hi , i have trained an instance segmentation model using mask_rcnn-50 layers config model on my custom dataset and after training i tried to test the model . here are my two scenarios:

1) when i train and test the model in same jupyter notebook it works fine .

2) but when i train on seperate notebook and test on seperate jupyter ntbk or  a new python file by loading the model.pth file  and giving the same config(yaml) file while training , it wont detect anything on the same data i tested on the first case . please let me know why is that happening . i am using the below code for testing 

###import all libraries 
from detectron2.utils.visualizer import ColorMode

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth") #the model that i got after training 
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 

predictor = DefaultPredictor(cfg)

dataset_dicts = get_microcontroller_dicts('Microcontroller Segmentation/test')
for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=microcontroller_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()

Thanks

**Comment by ppwwyyxx** [comment]
The config changes made before training need to be used in inference as well.

Alternatively you can load the config file that's saved during training.

**Comment by karankatiyar92** [comment]
i dont see that new config file saved . is it with .yaml extension or some other ?

tHAnks

**Comment by ppwwyyxx** [comment]
oops sorry they are not saved unless you call `cfg.dump`

**Comment by karankatiyar92** [comment]
hi , i tried cfg.dump() but it did not save any config file . any other way to save the updated config after training .any example or sample code you can give would be very helpful

thanks

**Comment by ppwwyyxx** [comment]
`cfg.dump` returns a string.
After training the cfg you used to train is already gone. You can set the values manually before inference by `cfg.A.B = ...`

**Comment by karankatiyar92** [comment]
so you said i need to save new config file , but what i would like to know is how can i do that .

in the new python file for inferencing i will have to do something like this 

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file( "/..to the saved config file" ))
cfg.LOAD model = ''

run infernce code here ....

**Comment by ppwwyyxx** [comment]
cfg.dump returns a string, and the string can be written to a file.

**Comment by karankatiyar92** [comment]
got it . i tried doing like that .basically did print(cfg.dump()) which printed something (looks like a yaml format config) . i manually saved it in a yaml file , loaded it back and then it gave an error .
