### ISSUE TITLE
Dataset size after augmentation

### ISSUE THREAD

**Issue by hazemy** [facebookresearch/detectron2#2138]
Hello,

How do I obtain the exact dataset size after augmentation (i.e: the size by which the model is actually trained)?
I am using the default augmentation operations of random flipping, along with resizing.

**Comment by ppwwyyxx** [comment]
Could you define what is " exact dataset size after augmentation "?

**Comment by hazemy** [comment]
I mean the total number of images after the augmentation operations (defaults used) that are passed to the model for training.

**Comment by ppwwyyxx** [comment]
You can compute it from the values you use in the config. (e.g. x2 if you use flipping).

**Comment by hazemy** [comment]
Yes, but the flipping is random. To put it shortly: is there a way to get the output of the datasetMapper or the dataloader (for ex. as a list[dict]) without having to rewrite one?

**Comment by ppwwyyxx** [comment]
`for output in dataloader:` will get the output of the dataloader

**Comment by hazemy** [comment]
So, basically I need to overwrite the `build_train_loader(cfg)` in order to get access to the dataloader outputs. I was wondering if there is a more direct way when one is using the `DefaultTrainer`
