### ISSUE TITLE
One Question abour Load Weights

### ISSUE THREAD

**Issue by Cknex** [facebookresearch/detectron2#2140]
I use tools/plain_train_net.py to train faster_rcnn.
At first, I set FREEZE_AT=5, then I save the model to 'model__0010000.pth'
Then I restart and set FREEZE_AT=2. If I load 'model_0010000.pth', will the weight between 2 and 5 be optimized?

**Comment by ppwwyyxx** [comment]
Yes.
Only weights are saved in pth file. Settings about the model architecture is not.
