### ISSUE TITLE
how to get the per-category AP?

### ISSUE THREAD

**Issue by GittersYang** [facebookresearch/detectron2#2141]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. I am learnning the cenermask based on detectron2. And i only get the AP ,AP50... with out the per-category AP in the log file. But it can be found in detectron2's log file.
![未命名图片](https://user-images.githubusercontent.com/44436506/96357830-44c99d00-1133-11eb-86f4-4331dd7039a1.png)

The coco_evaluation.py in  detectron2 and centermask is alomost same.

how to get the per-category AP when training the centermask model?

**Comment by GittersYang** [comment]
[](url)

**Comment by ppwwyyxx** [comment]
centermask is not something this repo provides and we could not answer questions about it.
