### ISSUE TITLE
How to get and save output results(inference meta data)? 

### ISSUE THREAD

**Issue by G-Bong** [facebookresearch/detectron2#2142]
Hello.

I just met detectronV2 3 days ago, and really appreciate this amazing work.

With a great explanation, I could do the Mask R-CNN based object detection and segmentation inference step easily.

However, I want to know how to get and save output results(inference metadata) in JSON file.

Is already there any API or codes?

Thank you.

**Comment by ppwwyyxx** [comment]
The output format of a standard model is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

You can write code to convert it to format you like.

**Comment by G-Bong** [comment]
@ppwwyyxx Thanks. I created my own saving python script with the document you wrote above and tutorials.

**Comment by bhavesh2799** [comment]
@G-Bong Hey, are your json outputs in openpose format? Would you please share your script?
