### ISSUE TITLE
not able to the retrain  model from previous checkpoint 

### ISSUE THREAD

**Issue by karankatiyar92** [facebookresearch/detectron2#2145]
hi , i am trying to retrain the detectron instance segmentation model (using mask rcnn -50 layer )from previous checkpoint by giving resume=True in the cfg inputs . but it always starts from 0th iteration .

can one suggest how to fix this .

thanks

**Comment by ppwwyyxx** [comment]
Please see the meaning of `resume=True` at https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load. If you think anything is unexpected, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
