### ISSUE TITLE
 How do I get the segmentation value using this?

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2146]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

out = v.draw_instance_predictions(outputs["instances"].to("cpu"))

How do I get the segmentation value using this?

I did object detection with the trained data to get the desired image, 

but I have to get the information of the subdivided coordinates of the detected object. 

Please tell me how

**Comment by ppwwyyxx** [comment]
The format of the output dictionary is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

**Comment by qodlsrud20712** [comment]
I really don't know how. If the value of pred_masks doesn't come in as False, is it necessary to convert the values ​​into (x,y) tuples when converting the cfg file to a dict?
