### ISSUE TITLE
Can't I get segmentation information from draw_dataset_dict from draw_instance_predictions??

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2147]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

I want to get the segmentation information of an object that can be obtained using draw_dataset_dict.
 Do pred_masks from draw_instance_predictions contain that information?
 But pred_masks returns [false, false, false, ..., false, false, false].

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
The meaning of `pred_masks` is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

**Comment by qodlsrud20712** [comment]
I really don't know how. Is this the cfg file I need to modify? Or do I have to train differently?
