### ISSUE TITLE
 How to get the pixel coordinate information of polygons drawn in bounding box when evaluating performance as a result of training

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2148]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

As a result of training, I implemented object detection and the performance was good.

What I want is information about the pixel coordinates of the polygon drawn more 

accurately within the object drawn in the bounding box. Is there a way?

I've read this https://detectron2.readthedocs.io/tutorials/models.html#model-output-format document, but I'm not sure how.

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
Unfortunately I cannot understand what outcome you expect to see and what is not working.
One way to make it more clear is to follow the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) to describe what is currently unexpected.
