### ISSUE TITLE
 Why is the result of pred_masks returned as False when evaluating performance with trained data?

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2149]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

When I execute object detection with the result of my training, 

values ​​such as pred_box and pred_class come out well,

but only pred_masks returns a tensor full of False. I wonder why.

I've read this https://detectron2.readthedocs.io/tutorials/models.html#model-output-format document, but I'm not sure how.

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
You can test an official model to know if your code is correct.
If your code is correct, then the model you train is not working on the image. 
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions, we do not help users on how well a model works.
