### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by ombretta** [facebookresearch/detectron2#2152]
I get the following error when I try to install detectron2. I use linux, python 3.8.2, torch 1.6.0 with cuda 10.2.

(detectron2) bash-4.2$ python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.6/index.html

Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.6/index.html
Collecting detectron2
  Using cached https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.6/detectron2-0.2.1%2Bcu102-cp38-cp38-linux_x86_64.whl (6.6 MB)
Requirement already satisfied: cloudpickle in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (1.6.0)
Requirement already satisfied: yacs>=0.1.6 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (0.1.8)
Requirement already satisfied: tqdm>4.29.0 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (4.50.2)
Requirement already satisfied: mock in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (4.0.2)
Requirement already satisfied: tabulate in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (0.8.7)
Requirement already satisfied: matplotlib in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (3.3.2)
Requirement already satisfied: fvcore>=0.1.1 in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from detectron2) (0.1.2.post20201016)
Requirement already satisfied: tensorboard in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from detectron2) (2.3.0)
Requirement already satisfied: pycocotools>=2.0.1 in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from detectron2) (2.0.2)
Requirement already satisfied: future in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (0.18.2)
Requirement already satisfied: termcolor>=1.1 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (1.1.0)
Requirement already satisfied: pydot in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from detectron2) (1.4.1)
Requirement already satisfied: Pillow>=7.1 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from detectron2) (8.0.0)
Requirement already satisfied: PyYAML in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from yacs>=0.1.6->detectron2) (5.3.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (2.4.7)
Requirement already satisfied: certifi>=2020.06.20 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (2020.6.20)
Requirement already satisfied: numpy>=1.15 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (1.19.1)
Requirement already satisfied: cycler>=0.10 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from matplotlib->detectron2) (2.8.1)
Requirement already satisfied: portalocker in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from fvcore>=0.1.1->detectron2) (2.0.0)
Requirement already satisfied: setuptools>=41.0.0 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from tensorboard->detectron2) (50.3.0.post20201006)
Collecting requests<3,>=2.21.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting protobuf>=3.6.0
  Using cached protobuf-3.13.0-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.22.1-py2.py3-none-any.whl (114 kB)
Requirement already satisfied: markdown>=2.6.8 in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from tensorboard->detectron2) (3.3.2)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Collecting grpcio>=1.24.3
  Using cached grpcio-1.32.0-cp38-cp38-manylinux2014_x86_64.whl (3.8 MB)
Collecting absl-py>=0.4
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
Requirement already satisfied: six>=1.10.0 in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from tensorboard->detectron2) (1.15.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /tudelft.net/staff-bulk/ewi/insy/VisionLab/ombrettastraff/envs/detectron2/lib/python3.8/site-packages (from tensorboard->detectron2) (0.35.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages (from tensorboard->detectron2) (1.7.0)
Collecting cython>=0.27.3
  Using cached Cython-0.29.21-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Installing collected packages: detectron2, urllib3, idna, chardet, requests, protobuf, werkzeug, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, grpcio, absl-py, cython
ERROR: Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/home/nfs/ombrettastraff/envs/detectron2/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so'

Any suggestions?

Thanks.
Ombretta

**Comment by ppwwyyxx** [comment]
use `pip --user` when you don't have permission.

**Comment by ombretta** [comment]
Thanks for your answer! I could install detectron2, however I still get the error: 

from detectron2 import model_zoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/model_zoo/__init__.py", line 7, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/model_zoo/model_zoo.py", line 8, in <module>
    from detectron2.modeling import build_model
  File "/home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/modeling/__init__.py", line 2, in <module>
    from detectron2.layers import ShapeSpec
  File "/home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/nfs/ombrettastraff/.local/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

How can I solve this?
