### ISSUE TITLE
Large values in feature maps when using ModuleDict

### ISSUE THREAD

**Issue by atapley** [facebookresearch/detectron2#2155]
## Instructions To Reproduce the Issue:

I am attempting to create my own META_ARCH that will allow me to have multiple input heads so that I can input a separate image to each head. Each head would be it's own ResNet101 with FPN, collected within a dictionary with structure {'key': backbone}

META_ARCH file: (equivalent to modeling/meta_arch/rcnn.py)

`
class MyModel(nn.Module):

    @configurable
    def __init__(
        self,
        *,
        backbone: Dict
    ):
        
        super().__init__()
        self.backbone = backbone

    @classmethod
    def from_config(cls, cfg):
        backbone = {}

        for head in enumerate(['h1','h2']):
           backbone[head] = build_backbone(cfg)

        return {
            "backbone": backbone
        }

    def forward(self, batched_inputs):

            heads = [head for head in self.backbone.keys()]

            for head in heads:
                batch = [x[head] for x in batched_inputs]

                images = self.preprocess_image(batch, head)

                features = self.backbone[head](images.tensor)
                print(features)
                exit()
`
I've removed sections of the code that are not relevant to be more concise, so it will not run as is.

## Expected behavior:

When printing out the features dictionary, the values look like:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/23152013/96632222-679bb300-12e5-11eb-885c-b8d926bfe26b.png)

The high values cause NaN and Inf values in later iterations. I am expecting the values to be less than this, typically between -1 and 1.

When I do not use a dictionary, I get expected results. As soon as I use a dictionary the values jump up to the high values seen above. I have not been able to find anything anywhere about similar behavior. I'm not sure if Detectron2 just isn't set up to be used by dictionaries somewhere, or if there is something wrong in the code itself that I am trying.

## Environment:

Provide your environment information using the following command:
```
----------------------  ---------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
numpy                   1.19.1
detectron2              0.2.1 @/opt/conda/envs/detectron2/lib/python3.7/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   /opt/conda/envs/detectron2/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/opt/conda/envs/detectron2/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 Tesla V100-PCIE-32GB
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.7.0 @/opt/conda/envs/detectron2/lib/python3.7/site-packages/torchvision
torchvision arch flags  /opt/conda/envs/detectron2/lib/python3.7/site-packages/torchvision/_C.so; cannot find cuobjdump
fvcore                  0.1.2.post20200929
cv2                     4.4.0
----------------------  ---------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
