### ISSUE TITLE
 How do I get the coordinates of the subdivided object drawn in the box from this image?

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2157]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

I am curious how to get the subdivided coordinates of an object in this photo.
![2020-10-21 (2)](https://user-images.githubusercontent.com/55775446/96656053-f8bc6980-1379-11eb-89e7-0bee1381d53e.png)

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
Segmentation models output masks, in the format described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format. They do not output coordinates.
You can write code to compute coordinates from masks yourself.
