### ISSUE TITLE
 Principle of polygons drawn in bounding box

### ISSUE THREAD

**Issue by qodlsrud20712** [facebookresearch/detectron2#2159]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

How is the outline of the polygon drawn in the box drawn? What function is it drawn using?
![윤곽선궁금](https://user-images.githubusercontent.com/55775446/96675549-11db0f80-13a6-11eb-8c2e-5864f63ef1fb.png)

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
It can be found in documentation: https://detectron2.readthedocs.io/_modules/detectron2/utils/visualizer.html#Visualizer.draw_polygon
