### ISSUE TITLE
Memory leak during inference

### ISSUE THREAD

**Issue by rivered** [facebookresearch/detectron2#2161]
I have an issue when performing inference. When I run inference the first ~200-300 pictures run fine with memory usage running between 3-4.2gb's. Than at a sudden moment the memory starts to increase per image fast. During the last 3 images before my memory runs out, 500mb to 1 gb can be added to memory for a single image. I find this behaviour very strange. 

I know this issue has been mentioned before but I have not been able to find a good solution _without_ using batch inference.

This is what I am currently running: 

To load the model: 
```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128  # 64 is slower but more accurate (128 faster but less accurate)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3 
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_0007499.pth") #Path to the trained model!
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set a custom testing threshold
cfg.DATALOADER.NUM_WORKERS = 16
predictor = DefaultPredictor(cfg)
```
To run inference:
```
#Apply model on complete dataset
from detectron2.utils.visualizer import ColorMode

All_Objects_list=[]
for index, i in enumerate(tqdm(DataList[2001:2500])):    
    im = cv2.imread(i["Ped_Dir"])
    outputs = predictor(im)
    #Some custom functions to retrieve shapes of detected objects:
    Objects_and_masks = retrieve_class_mask(outputs["instances"])
    Shape_of_all_objects=retrieve_shape_objects(im, Objects_and_masks, i)
    All_Objects_list=All_Objects_list+Shape_of_all_objects
    #Clear session and visualize result in selection of images:
    K.clear_session()
    gc.collect()
    if index % 10 == 0:
      v = Visualizer(im[:, :, ::-1],
                    scale=0.8, 
                    instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
      )
      v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
      cv2.imwrite(os.path.join("/some_location/"
      + (i["Pedigree"]+"_"+i["Level"]+"_"+i["Plat_Loc"]+"_"+i["Plat_ID"]+"__"+i["Date"]+".jpg") ), (v.get_image()[:, :, ::-1]))
      gc.collect()
```
I implemented gc.collect() and K.clear_session as mentioned in the other issues, and although relieving the issues (perhaps double the amount of inferences can be done) the root of the problem still persists.

It would be good to mention I am using google colab to run inference. Thank you for your time.

**Comment by ppwwyyxx** [comment]
The code is not runnable. If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

From the code it appears memory leak is expected because results are added to in `All_Objects_list`

**Comment by rivered** [comment]
Although this issue has been closed for many moons, I dove a bit further in my code, and found detectron2 was working perfectly. The data leak came forth from the functions provided in the [PlantCV library](https://plantcv.readthedocs.io/en/stable/).
