### ISSUE TITLE
How to do data augmentation?

### ISSUE THREAD

**Issue by CyberDreamer** [facebookresearch/detectron2#2162]
## ❓ How to do data augmentation?

1. I looked at the [documentation](https://detectron2.readthedocs.io/tutorials/augmentation.html?highlight=augmentation) but examples don't work.

I get this error:
module 'detectron2.data.transforms' has no attribute 'AugmentationList'

2. I remove T.AugmentationList and try to create single Augmentation. But i can't create even RandomCrop():
NameError: name 'RandomCrop' is not defined

3. I try to import all in 
from detectron2.data.transforms.transform import *
from detectron2.data.transforms.augmentation import *

But it's doesn't help. As I understand it, this may be due to incorrect formatting of spaces and tabs. But I do not understand where to fix it and how.

And how do I pass the augmented data to train procedure?

**UPD 1:**
1. I installed detectron2 on another PC and above problem are gone
2. Now i get next problem
```
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fvcore/transforms/transform.py", line 668, in apply_image
    return img[self.y0 : self.y0 + self.h, self.x0 : self.x0 + self.w]
IndexError: too many indices for array
```
But img have (3456, 4608, 3) shape. I load image with cv2. What could be the problem?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by yang-gis** [comment]
> how do I pass the augmented data to train procedure?

 could you show me how to pass the augmented data to train procedure?
