### ISSUE TITLE
How use pretrained weights from a pytorch/resnet50 backbone

### ISSUE THREAD

**Issue by julien314** [facebookresearch/detectron2#2164]
Hello there and thanks for this great work on Detectron2 !

I am interested in object detection / segmentation using maskrcnn and the resnet50 backbone, which I use with msra pretrained weights.

Instead of using these weights I would like to use weights that I have in my possession and that come from a train with pytorch/torchvision with resnet50 .

Any idea how to do this? I have the feeling that the resnet backbones are not exactly the ones that are in torchvision, am I wrong ?

Thanks a lot for your ( I hope ) insights

**Comment by ppwwyyxx** [comment]
See https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models for the source of backbones and how to use torchvision backbones.

**Comment by julien314** [comment]
Thank you so much @ppwwyyxx ! I've read this page ( MODEL_ZOO ) too many times and I've missed the conversion script !

Thanks again :)
