### ISSUE TITLE
Interpolation type of segmentation masks

### ISSUE THREAD

**Issue by aabbas90** [facebookresearch/detectron2#2171]
## 🚀 Feature
Currently the segmentation results are being interpolated through bi-linear interpolation. I think, for integer valued matrices where there is no meaning in between two labels (e.g. cat(label = 1), dog(label=2)), interpolating these two values is not the right way. The segmentation results should be interpolated by nearest neighbors and can possibly improve accuracy of segmentation type images slightly.

## Code location
https://github.com/facebookresearch/detectron2/blob/200c66e7a9ece92e6fb7f78856b9fd3ca5eb1925/detectron2/modeling/postprocessing.py#L96

Change `mode="bilinear"` to `mode="nearest"`. 

This function is used at many places, e.g.:
https://github.com/facebookresearch/detectron2/blob/200c66e7a9ece92e6fb7f78856b9fd3ca5eb1925/detectron2/modeling/meta_arch/semantic_seg.py#L90

**Comment by ppwwyyxx** [comment]
>  for integer valued matrices where there is no meaning in between two labels

This is correct, but we are not interpolating integer-valued matrices. If you found otherwise, please file a bug report.
