### ISSUE TITLE
onnx support for embedded gpu devices

### ISSUE THREAD

**Issue by berkantay** [facebookresearch/detectron2#2179]
## 🚀 Feature

.onnx format export for embedded use cases like NVIDIA jetson boards with GPU support. For real-time applications

## Motivation & Examples

I have been working with embedded ai projects for 3 months. I tried several training and inferring frameworks and I believe that detectron2 is one of the bests among them. Embedded use of ai is a hot topic. It would nice to use detectron2 for all pre-inference tasks configuring, training etc. and export the final model to .onnx with gpu support. Then use this model for inference on embedded devices that has GPU in it.

```

export_to_onnx("<name_of_the_torch_model>.pth","<path/to/your/onnx>")
```

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers -- we only consider papers that have enough significance and prevalance in the object detection field.

We do not take requests for most projects in the `projects/` directory, because they are research code release that is mainly for other researchers to reproduce results.

"Make X faster/accurate" is not a valid feature request. "Implement a concrete feature that can make X faster/accurate" can be a valid feature request.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory contains many of such examples.

**Comment by ppwwyyxx** [comment]
> export_to_onnx("<name_of_the_torch_model>.pth","<path/to/your/onnx>")

This API is impossible because the `pth` file does not contain model structure.

Please find how to do onnx conversion in existing issue.
