### ISSUE TITLE
How to do multi task training

### ISSUE THREAD

**Issue by animareversed** [facebookresearch/detectron2#218]
Hi, 
Thanks for yours work. 
I was wondering: is it possible to train the network on different task? I mean, for example training it simultaneously on semantic segmentation and object detection?
Thanks,

**Comment by ppwwyyxx** [comment]
You just need to [write a model](https://detectron2.readthedocs.io/tutorials/write-models.html) that does the two task. The included `PanopticFPN` model is already doing both tasks.
