### ISSUE TITLE
NotImplementedError   in training for instance segmentation

### ISSUE THREAD

**Issue by Randheerkumar** [facebookresearch/detectron2#2180]
## ❓Not able to train due to "NotImplementedError"

Getting following error during training
instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/masks.py", line 204, in get_bounding_boxes
    raise NotImplementedError
NotImplementedError

I am training on v5 dataset and using **cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml** .

 I have converted mask (binary image ) into dict using
**pycocotools.mask.encode(np.asarray(mask, order="F"))**
Is error coming due to this conversion

**Comment by ppwwyyxx** [comment]
> detectron2/structures/masks.py", line 204, in get_bounding_boxes
raise NotImplementedError

This is implemented in github master version of the project.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by Randheerkumar** [comment]
@ppwwyyxx 
 Same error coming in master branch also, kindly look it.

**Comment by ppwwyyxx** [comment]
> File "/usr/local/lib/python3.6/dist-packages/detectron2/structures/masks.py", line 204, in get_bounding_boxes
raise NotImplementedError

The master branch doesn't even have this line of code: https://github.com/facebookresearch/detectron2/blob/29e85f9a21e57f883de1e4dac09392c833f19ab2/detectron2/structures/masks.py#L202, so it's impossible to produce the same error.

If you run into other errors, please open new issues and include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by Randheerkumar** [comment]
@ppwwyyxx  thanks a lot.  I have installed from https://github.com/facebookresearch/detectron2/commit/29e85f9a21e57f883de1e4dac09392c833f19ab2 and it worked for me.
