### ISSUE TITLE
AttributeError: Cannot find field 'pred_masks' in the given Instances! ::  Mask-RCNN

### ISSUE THREAD

**Issue by Randheerkumar** [facebookresearch/detectron2#2181]
**I  am training and testing a mask-rcn model as below , but pred_mask is not there**

**I have trained as below**

![Screenshot 2020-10-23 173921](https://user-images.githubusercontent.com/35561608/97002429-99b44b80-1557-11eb-847e-02033fd21e21.png)

**I have tested as**
![Screenshot 2020-10-23 174008](https://user-images.githubusercontent.com/35561608/97002502-b486c000-1557-11eb-8456-d33a6b062359.png)

![Screenshot 2020-10-23 174039](https://user-images.githubusercontent.com/35561608/97002575-c8cabd00-1557-11eb-95cd-dff5a66c9a34.png)

![Screenshot 2020-10-23 174100](https://user-images.githubusercontent.com/35561608/97002577-cb2d1700-1557-11eb-9798-93cd9b241938.png)

@ppwwyyxx,  
Please look into it

**Comment by ppwwyyxx** [comment]
> I have tested as

The config that's used in training should be used in testing.
