### ISSUE TITLE
PanopticSeg -predmask

### ISSUE THREAD

**Issue by glcsvg** [facebookresearch/detectron2#2182]
`outputs = predictor(im)` 

 How can I get the pred_mask obtained here at panoptic_seg

`panoptic_seg, segments_info = predictor(im)["panoptic_seg"]`

**Comment by ppwwyyxx** [comment]
Unfortunately I'm not able to understand what you try to obtain. Please try describing your question in one of the [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
