### ISSUE TITLE
Sample script needs to be updated.

### ISSUE THREAD

**Issue by rdesc** [facebookresearch/detectron2#2184]
https://github.com/facebookresearch/detectron2/blob/d35c3c36dcee1b01faf46144625193f8979996d2/tools/plain_train_net.py#L159

The above line needs to be updated since it currently fails. The fix should be `storage.step()`.

**Comment by ppwwyyxx** [comment]
It does not fail with the github master version of detectron2.
You can also use an old version of `plain_train_net.py` if you're using older version of detectron2.
