### ISSUE TITLE
How to train and debug PointRend? We add configs of PointRend but the program doesn't seem to be working.

### ISSUE THREAD

**Issue by GuoRuohao** [facebookresearch/detectron2#2186]
The console only shows four losses including loss_cls, loss_box_reg, loss_rpn_cls, and loss_rpn_loc when we run the projects/PointRend/train_net.py. We cannot find the loss_mask.  We set a breakpoint in roi_heads (losses = {"loss_mask": mask_rcnn_loss(mask_coarse_logits, proposals)}) and then we debug the program. The program cannot stop at the breakpoint. It would be appreciated if you let me know what needs to be changed for the problem.

```
def setup(args):
    cfg = get_cfg()

    point_rend.add_pointrend_config(cfg)

    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.SOLVER.IMS_PER_BATCH = 4
    cfg.DATALOADER.NUM_WORKERS = 0
    cfg.OUTPUT_DIR = "./output"
    cfg.freeze()
    default_setup(cfg, args)
    return cfg
```

```
eta: 4:14:02  iter: 62  total_loss: 0.7852  loss_cls: 0.3064  loss_box_reg: 0.1001  loss_rpn_cls: 0.2844  loss_rpn_loc: 0.1046  time: 0.6069  data_time: 0.0130  lr: 0.0012388  max_mem: 5506M
```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
