### ISSUE TITLE
prediction mask

### ISSUE THREAD

**Issue by glcsvg** [facebookresearch/detectron2#2188]
I want to keep score, pred mask, stuff and thing classes in coco in instance  segmentation.
```
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
>>outputs["instances"]
```
Output:
`Instances(num_instances=15, image_height=480, image_width=640, fields=[pred_boxes: Boxes(tensor([[126.6035, 244.8977, 459.8291, 480.0000],
        [251.1083, 157.8127, 338.9731, 413.6379],...
        [594.5663, 283.4820, 609.0577, 311.4124]], device='cuda:0')), 
scores: tensor([0.9997, 0.9957, 0.9915, 0.9882, 0.9861, ....
        0.9037, 0.8870, 0.8575, 0.6592, 0.5899, 0.5767], device='cuda:0'), pred_classes: tensor([17,  0,  0,  0,  0,  0,  0,  0, 25.....
       device='cuda:0'), pred_masks: tensor([[[False, False, False,  ..., False, False, False]`

but stuff  classes don't have pred masks score class id

or 

I want to add pred-masks,class_id etc in the segment_info on panoptic-segmentation

```
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml")
predictor = DefaultPredictor(cfg)
panoptic_seg, segments_info = predictor(im)["panoptic_seg"]
```
Output:
```
>>segments_info
....
 {'area': 1431.0,
  'category_id': 0,
  'id': 13,
  'instance_id': 13,
  'isthing': True,
  'score': 0.658846378326416},
 {'area': 175992.0, 'category_id': 37, 'id': 14, 'isthing': False},
 {'area': 26254.0, 'category_id': 38, 'id': 15, 'isthing': False},
 {'area': 27412.0, 'category_id': 47, 'id': 16, 'isthing': False}]
```

**Comment by ppwwyyxx** [comment]
Unfortunately I'm not able to understand what you try to obtain. Please try describing your question in one of the [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
