### ISSUE TITLE
 ImportError: cannot import name 'dump_torchscript_IR'

### ISSUE THREAD

**Issue by TannerGilbert** [facebookresearch/detectron2#2190]
## Instructions To Reproduce the 🐛 Bug:

Open [example notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) in Google Colab and try to import `dump_torchscript_IR`.

Output
![import_error](https://user-images.githubusercontent.com/36239763/97094600-6f958300-1656-11eb-978a-791abcb9b303.PNG)

**Comment by ppwwyyxx** [comment]
As expected because the notebook does not use the latest version of detectron2 from github.
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
