### ISSUE TITLE
dataset filter

### ISSUE THREAD

**Issue by syusukee** [facebookresearch/detectron2#2191]
If I want to ignore some images in COCO that I don't need(e.g there's no keypoints annotations on the image) , how can I realize it? Cause I've just found I can only modify the meta data, but can't operate deleting all annotations related to a specified image. Hope for u reply!! @stepancheg

**Comment by syusukee** [comment]
@likethesky @yfeldblum @jvlmdr Hope for anyone can help me!! Thanks a lot!!

**Comment by syusukee** [comment]
@ppwwyyxx Could you give me some advice? Thanks a lot!!

**Comment by ppwwyyxx** [comment]
They are already ignored by default  (see cfg.MODEL.ROI_KEYPOINT_HEAD.MIN_KEYPOINTS_PER_IMAGE)
