### ISSUE TITLE
inference custom model on video detectron2 on colab

### ISSUE THREAD

**Issue by FirasAbdennadher** [facebookresearch/detectron2#2193]
I used this command to inference video using the code in demo.py:

!python demo/demo.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --video-input ../video-clip.mp4 --confidence-threshold 0.6 --output ../video-output.mkv
--opts MODEL.WEIGHTS /content/model_final.pth

Output video has no bounding boxes, either mask drawn.
by the way,the custom trained model works well on some selected images. The input video was downloaded from YouTube (as per the demo).
What could be the problem?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
