### ISSUE TITLE
Cross Validation with Detectron2

### ISSUE THREAD

**Issue by thanoscs** [facebookresearch/detectron2#2194]
Hello and congratulations on the work done on Detectron2,

I would like to ask you, whether it is possible to perform cross validation with detectron2.

e.g.: to pass as input a dataset in the format that accepts it and to perform lets say a k-fold with k=5 or another value.

If the above it cannot be yet performed, it is possible to build a custom function doing it?
For example i have thought to split the dataset if k=5 to 5 different ones and then in a loop to run the expirement for 5 times changing the test set and using  the remaining k-1 for training. After this i would keep the metrics.json and when completed afer having seen all the k-datasets i will average the metrics.

Thank you in advance!

**Comment by ppwwyyxx** [comment]
> For example i have thought to split the dataset if k=5 to 5 different ones and then in a loop to run the expirement for 5 times changing the test set and using the remaining k-1 for training. After this i would keep the metrics.json and when completed afer having seen all the k-datasets i will average the metrics.

You can certainly implement such logic. We have no plan to add this to detectron2 though.

**Comment by thanoscs** [comment]
> > For example i have thought to split the dataset if k=5 to 5 different ones and then in a loop to run the expirement for 5 times changing the test set and using the remaining k-1 for training. After this i would keep the metrics.json and when completed afer having seen all the k-datasets i will average the metrics.
> 
> You can certainly implement such logic. We have no plan to add this to detectron2 though.

ok, thank you very much for the reply.
