### ISSUE TITLE
errors during install the detectron2 under win10 system

### ISSUE THREAD

**Issue by lmw0320** [facebookresearch/detectron2#2198]
When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
I  don't know how to solve it...Hope someone can help me, thanks in advance.

**Comment by yang-gis** [comment]
> When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
> ![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
> I don't know how to solve it...Hope someone can help me, thanks in advance.

The facebook employee had told us it had not been supported for windows officely.

**Comment by lmw0320** [comment]
> > When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
> > ![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
> > I don't know how to solve it...Hope someone can help me, thanks in advance.
> 
> The facebook employee had told us it had not been supported for windows officely.

But I have seen someone installed the detectron2 sucessfully under win10 system....

**Comment by lmw0320** [comment]
> > When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
> > ![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
> > I don't know how to solve it...Hope someone can help me, thanks in advance.
> 
> The facebook employee had told us it had not been supported for windows officely.

你是福大的？ 做GIS的？

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues that we do not provide support for windows.

**Comment by yang-gis** [comment]
> > > When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
> > > ![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
> > > I don't know how to solve it...Hope someone can help me, thanks in advance.
> > 
> > 
> > The facebook employee had told us it had not been supported for windows officely.
> > 关键是我见过很多博客写着如何在win10下安装这个detectron2的教程。。
> > 另外，你是福大的？ 做GIS的？

是的。我没有在windows下装过这个repo，所以不确定能否装上。根据他们的技术人员说官方上不支持windows
另外我是福大gis

**Comment by lmw0320** [comment]
> > > > When I install the detectron2 by running the command : python setup.py build --force develop, I got the reports as below:
> > > > ![1](https://user-images.githubusercontent.com/37755235/97262580-2151d100-185c-11eb-8166-5b185f2aec1f.png)
> > > > I don't know how to solve it...Hope someone can help me, thanks in advance.
> > > 
> > > 
> > > The facebook employee had told us it had not been supported for windows officely.
> > > 关键是我见过很多博客写着如何在win10下安装这个detectron2的教程。。
> > > 另外，你是福大的？ 做GIS的？
> 
> 是的。我没有在windows下装过这个repo，所以不确定能否装上。根据他们的技术人员说官方上不支持windows
> 另外我是福大gis

好巧。。我的qq: 253455496 , 私聊
