### ISSUE TITLE
Unable to stop the stream: Inappropriate ioctl for device //Problem with loading a video doing the tutorial on Inference with Pre-trained Models

### ISSUE THREAD

**Issue by AntonBaumannDE** [facebookresearch/detectron2#22]
## ❓ Questions and Help

Thank you for this great work! I tried the Colab Notebook tutorial and it worked perfectly fine to infer the pre-trained network on images of my choice. Unfortunately I am facing a problem when **trying to infer on a video**. I copied the same exact Installation-steps from the tutorial into my own Colab Notebook, installed everything as in the tutorial and tried to execute following command: 

!python detectron2_repo/demo/demo.py --config-file detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --video-input video.mp4 \
	 --opts MODEL.WEIGHTS detectron2://COCO- 
            InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

Here is the output from my Colab Notebook: 
 
![error](https://user-images.githubusercontent.com/49437200/66694935-e9f89c80-ecb9-11e9-8b19-180bf460cfe8.JPG)

I assume it might have to do with ffmpeg and OpenCV not being able to load the video, which is why I have tried this: 
!apt install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavresample-dev
!apt install ffmpeg
It says everything is already installed though and doesn't change anything. 
I also made sure that the video.mp4 exists using: os.path.exists('video.mp4')  

Here is the full output: [10/12 04:17:56 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input='video.mp4', webcam=False)
WARNING [10/12 04:17:56 d2.config.compat]: Config 'detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Unable to stop the stream: Inappropriate ioctl for device
0it [00:00, ?it/s]

**Comment by sophia-hxw** [comment]
I also face the same problem. Could you please share the solution? Thanks a lot~

**Comment by AntonBaumannDE** [comment]
Hi Sophia :) For now i have not figured out yet how to enable H.264 encoding for ffmpeg and to compile openCV in the Colab runtime. I can send you a workaround in my notebook though. I will do that as soon as I am back home.
