### ISSUE TITLE
torch version upgrade

### ISSUE THREAD

**Issue by Warday** [facebookresearch/detectron2#2201]
torch seems te be upgraded mekind the command in balloon example in colab network (Detectron2 Beginner's Tutorial) to fail
!pip install -U torch torchvision 
install version 17 that is uncompatible with cuda 10.1 
Fixed replacing with
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
That error started today. I report in case it help.

**Comment by ppwwyyxx** [comment]
Thanks! I added the new command to the tutorial.
