### ISSUE TITLE
How to display bounding box on Android?

### ISSUE THREAD

**Issue by KhyatiMehta3** [facebookresearch/detectron2#2205]
## ❓ How to do something using detectron2
Hello! 
I'd like to take the bounding box shown in the output from detectron2 after prediction, and display that on an Android application as a bounding box over an image. Can anyone guide me on how this can be done? Or is there a standardized way to doing this?

This is what my bounding box looks like:
```Boxes(tensor([[ 20.3178,   0.0000, 219.9704, 166.3912],\n        [ 35.7135,   0.0000, 214.5163, 163.8396]]))```

**Comment by ppwwyyxx** [comment]
Detectron2 is responsible for making the predictions, which you already obtain. How to display it on android is not within the scope of this project.
