### ISSUE TITLE
Running deployed model inference

### ISSUE THREAD

**Issue by juvebogdan** [facebookresearch/detectron2#2206]
Hello,

I am trying to run inference using deploy guide from here https://detectron2.readthedocs.io/tutorials/deployment.html. but this guide is not clear and I couldn't complete it.

I managed to create model.pb, model_init.pb.
The guide from above also says this:

To use the converted model in python, we provide a python wrapper around the converted model, in the Caffe2Model.__call__ method. This method has an interface that’s identical to the pytorch versions of models so I tried it like this:

from detectron2.export import Caffe2Model
import cv2

model = Caffe2Model.load_protobuf("./")
im = cv2.imread("../valid/1.jpg")
inputs = [{"image": im)}]
outputs = model(inputs)

this does not work and I get AttributeError: 'numpy.ndarray' object has no attribute 'dim' so I tried this:

import cv2

model = Caffe2Model.load_protobuf("./")
im = cv2.imread("../valid/1.jpg")
inputs = [{"image": torch.from_numpy(im))}]
outputs = model(inputs)

this also does not work: I get: 
assert bbox_nms is not None
AssertionError

This particular image runs fine during caffe_converter evaluation.

Is there a chance you can help me with this?

**Comment by ppwwyyxx** [comment]
As the guide says, the input should follow the format in https://detectron2.readthedocs.io/tutorials/models.html#model-input-format.
The inputs you provided do not follow the format.

If you need more help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
