### ISSUE TITLE
How to interpret the visibility score output from keypoint output

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detectron2#2208]
During labeling/dataset creation, the visibility flag for a keypoint is set according to:

_The visibility flag follows the COCO format and must be one of three integers:
    * v=0: not labeled (in which case x=y=0)
    * v=1: labeled but not visible
    * v=2: labeled and visible_

I am not sure how to interpret the visibility score for predicted keypoints.  In my custom training labels, I have all non-labeled points set to x=0,y=0,v=0 as per the above COCO guideline.  I do not use v=1 because I don't ever label invisible keypoints.

At inference time, what is the correct way to filter out keypoints that are invisible (i.e. outside the image frame)?  Most of my objects have at least one keypoint outside of the image frame.  I am getting false positive keypoints often at the edge of the image (but not outside the image frame).  At first I tried thresholding by the output visibility value but I found that many true positive visible keypoints have very low predicted visibility values (e.g. 0.1). Therefore, thresholding doesn't seem to be reliable.

I notice the visualizer filter out keypoints that have visibility score under certain threshold: 

`_KEYPOINT_THRESHOLD = 0.05`
Source: https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py#L33

How is 0.05 determined?  It seems like a magic number to me.

My real question is how to I reliably filter out invisible keypoints at inference time?

**Comment by ppwwyyxx** [comment]
The model does not output visibility score. Outputs are described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format - it's just a confidence score.

**Comment by jackkwok** [comment]
Is the confidence score reliable?  I found that many true positive visible keypoints have very low predicted scores (e.g. 0.1).  I suspect that's why this threshold is so low:

_KEYPOINT_THRESHOLD = 0.05
