### ISSUE TITLE
detectron2_repo/detectron2/layers/csrc/vision.o: file not recognized: file format not recognized

### ISSUE THREAD

**Issue by FantDing** [facebookresearch/detectron2#221]
I have trouble installing detectron2
## To Reproduce
1. install requirements as mentioned in 'INSTALL.md'
2. git clone https://github.com/facebookresearch/detectron2 detectron2_repo
3. cd detectron2_repo
4. python setup.py build develop

## Expected behavior
Succeed in installing.
But I met errors, said "......./detectron2_repo/detectron2/layers/csrc/vision.o: file not recognized: file format not recognized"

## Environment
- manjaro 18.1.2
- g++ (GCC) 9.2.0
- torch 1.3
- python 3.6.9

**Comment by ppwwyyxx** [comment]
Please post full error logs and environment information following the issue template.

**Comment by kHarshit** [comment]
@FantDing You need to downgrade binutils to 2.30-5. Check #23

**Comment by ppwwyyxx** [comment]
Seems a duplicate. Thanks for flagging this

**Comment by FantDing** [comment]
Thank you !!!  I solved it

**Comment by david-morris** [comment]
Hi, I'm reopening this because binutils 2.30 has been expired from the Arch Linux Archive. I'm looking for another workaround, ideally one that does not require downgrading binutils system-wide.

**Comment by ppwwyyxx** [comment]
Either downgrade or upgrade, to avoid a version of binutils that has bugs.

I don't think it needs to be reopened since it's unrelated to detectron2 and there isn't much we can do
