### ISSUE TITLE
keypoints shape mismatch

### ISSUE THREAD

**Issue by rogertrullo** [facebookresearch/detectron2#2212]
Hi, I am trying to define a custom dataset with keypoints. In [here ](https://detectron2.readthedocs.io/tutorials/datasets.html) it is said that the keypoints field should be a list : `[x1, y1, v1,…, xn, yn, vn]`
Then in https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/detection_utils.py#L418-L420 

    if len(annos) and "keypoints" in annos[0]:
        kpts = [obj.get("keypoints", []) for obj in annos]
        target.gt_keypoints = Keypoints(kpts)

we get a `List[List[float]]]` and when converting to the `Keypoint ` structure the following check is done:
https://github.com/facebookresearch/detectron2/blob/master/detectron2/structures/keypoints.py#L29-L31

        keypoints = torch.as_tensor(keypoints, dtype=torch.float32, device=device)
        assert keypoints.dim() == 3 and keypoints.shape[2] == 3, keypoints.shape
        self.tensor = keypoints

It seems to me that when converting a `List[List[float]]]` to a torch tensor, it will have  2 dimensions instead of 3, making the assertion to be raised.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
