### ISSUE TITLE
Prediction not available in the dataset

### ISSUE THREAD

**Issue by sarmientoj24** [facebookresearch/detectron2#2213]
I am getting this error:

```
ERROR [10/31 15:56:24 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 133, in train
    self.after_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 154, in after_step
    h.after_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/hooks.py", line 350, in after_step
    self._do_eval()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/hooks.py", line 324, in _do_eval
    results = self._func()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 352, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 518, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/evaluator.py", line 176, in inference_on_dataset
    results = evaluator.evaluate()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/coco_evaluation.py", line 143, in evaluate
    self._eval_predictions(set(self._tasks), predictions)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/coco_evaluation.py", line 165, in _eval_predictions
    category_id
AssertionError: A prediction has category_id=19, which is not available in the dataset.
[10/31 15:56:24 d2.engine.hooks]: Total training time: 0:00:16 (0:00:16 on hooks)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-6dffec0fbf9e> in <module>()
     31 trainer = CocoTrainer(cfg)
     32 trainer.resume_or_load(resume=False)
---> 33 trainer.train()

9 frames
/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/coco_evaluation.py in _eval_predictions(self, tasks, predictions)
    163                     category_id in reverse_id_mapping
    164                 ), "A prediction has category_id={}, which is not available in the dataset.".format(
--> 165                     category_id
    166                 )
    167                 result["category_id"] = reverse_id_mapping[category_id]

AssertionError: A prediction has category_id=19, which is not available in the dataset.
```

## Config
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"))
cfg.DATASETS.TRAIN = ("dataset_train",)
cfg.DATASETS.TEST = ("dataset_val",)

cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR =  0.00025

cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.MAX_ITER = 10 #adjust up if val mAP is still rising, adjust down if overfit
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.05


cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 20 #your number of classes + 1
```

I am pretty sure I have 19 categories on both train and test json

[10/31 15:56:08 d2.data.build]: Distribution of instances among all 19 categories:
|   category    | #instances   |   category    | #instances   |   category    | #instances   |
|:-------------:|:-------------|:-------------:|:-------------|:-------------:|:-------------|
| Alligator_C.. | 33           | Block_Crack.. | 79           | Bumps_Sags_FP | 4            |
| Corner_Brea.. | 0            | Divided_Sla.. | 0            | Durability_.. | 0            |
| Edge_Crack_FP | 0            |   Joint_RP    | 108          | Joint_Spall.. | 0            |
| Linear_Crac.. | 0            | Longitudina.. | 20           | Manhole_Cover | 0            |
| Miscellanio.. | 32           | Patch_Utili.. | 0            |  Pothole_FP   | 8            |
|  Rutting_FP   | 0            | Slippage_Cr.. | 0            | Transverse_.. | 21           |
| Weather_Rav.. | 0            |               |              |               |              |
|     total     | 305          |               |              |               |              |
```

### **This is the coco.json**

```
{
            "supercategory": "none",
            "id": 18,
            "name": "Transverse_Crack_FP"
        },
        {
            "supercategory": "none",
            "id": 19,
            "name": "Weather_Raveling_FP"
        }
```

## Expected behavior
No error  

My intuition is that on my test/val.json, sometimes it does not have any representative of some classes

**Comment by ppwwyyxx** [comment]
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = 20 #your number of classes + 1

It should be number of classes, not +1.

**Comment by sarmientoj24** [comment]
should i still have a background class labelled 0 in my coco.json or not?
also, should I start my classes from 0 to num_classes - 1 or 1 to num_classes?

When i tried the latter, it still has some errors

**Comment by sarmientoj24** [comment]
I literally have num of classes = 18 and labels inside coco.json 1-17 or 0-16 and still getting this
```
AssertionError: A prediction has category_id=17, which is not available in the dataset.
```

**Comment by ppwwyyxx** [comment]
Number of classes should be equal to `len(json['categories'])`.

If your labels are 1-17, or 0-16, then number of classes is 17.

**Comment by sarmientoj24** [comment]
i see thank you!

**Comment by Brainkite** [comment]
I have the same type of error. 
I have only one class to detect and the model sometimes outputs other category_id than 0, but this shouldn't break the code in my opinion, just considered as a wrong detection.
Here's a sample of the classes in the model's output:
` tensor(0),
  tensor(0),
  tensor(36),
  tensor(0),
  tensor(0),
  tensor(0),
  tensor(0),
  tensor(0),
  tensor(30),
  tensor(0),
  tensor(0),
  tensor(31),
  tensor(0),
  tensor(0),
  tensor(0),`
