### ISSUE TITLE
What does "C_1, ..., C_K,"  indicate in ImageList?

### ISSUE THREAD

**Issue by Dirtybluer** [facebookresearch/detectron2#2214]
I'm having trouble in understanding a piece of doc strings in [`ImageList.from_tensors()`](https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.ImageList.from_tensors).

It describes one of the arguments `tensors` as below:

> tensors – a tuple or list of torch.Tensors, each of shape (Hi, Wi) or **(C_1, …, C_K, Hi, Wi) where K >= 1**. The Tensors will be padded to the same shape with pad_value.

As I go through the source code, I suppose that `tensors` represents a list of images as Tensor. Therefore, each image in the list should be in C x H x W shape. Then why there would be extra dimensions as `C_1, ..., C_K`?

Not sure what I've misunderstood, hope someone can help me out!

**Comment by ppwwyyxx** [comment]
`C x H x W` is a special case when K=1.
K can also be zero, or possibly 2 if doing video frames.

**Comment by Dirtybluer** [comment]
Thanks for your replay! Failed to take video frames into account before.
