### ISSUE TITLE
MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

### ISSUE THREAD

**Issue by GittersYang** [facebookresearch/detectron2#2216]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. I found"MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)"in yaml.file.
What is the input size of images of training  in d2?

**Comment by ppwwyyxx** [comment]
See https://detectron2.readthedocs.io/modules/config.html#config-references for documentation.
They will be used by https://detectron2.readthedocs.io/modules/data_transforms.html#detectron2.data.transforms.ResizeShortestEdge

**Comment by priteshgohil** [comment]
So is it possible to change MAX_SIZE_TRAIN: 512 and also MIN_SIZE_TRAIN: (512,) ?

**Comment by ppwwyyxx** [comment]
I think this was answered by https://detectron2.readthedocs.io/modules/data_transforms.html#detectron2.data.transforms.ResizeShortestEdge
