### ISSUE TITLE
How to reduce the pred_mask size?

### ISSUE THREAD

**Issue by sarigha** [facebookresearch/detectron2#2221]
By using this [https://github.com/facebookresearch/detectron2/issues/984]() I get a mask image perfectly for text detection, but getting some overlapped `pred_masks` in images. So I decided to reduce the size of the detected `pred_masks` in the mask image.

```
    mask_array = outputs['instances'].pred_masks.numpy()
    num_instances = mask_array.shape[0]
    #print('num_instances',num_instances)
    mask_array = np.moveaxis(mask_array, 0, -1)
    #print('mask_array',mask_array)
    mask_array_instance = []
    output = np.zeros_like(im)
    #print('output',output)
    for i in range(num_instances):        
        mask_array_instance.append(mask_array[:, :, i:(i+1)])
        output = np.where((mask_array_instance[i] == True) , 255, output)
    cv2.imwrite(mask_path+'/'+item+'.jpg',output)#mask
    return outputs
```
![img](https://user-images.githubusercontent.com/64319123/97834620-46cc5800-1cfe-11eb-86ec-d70b7fbcecad.png)

**Comment by ppwwyyxx** [comment]
The question doesn't seem to be in the scope of object detection/segmentation. Image processing functions in opencv may help.
