### ISSUE TITLE
Label list for Panoptic Segmentation

### ISSUE THREAD

**Issue by Palanivelg** [facebookresearch/detectron2#2226]
## ❓ How to map the labels with class id using detectron2

Invoked panoptic segmentation using the demo application,
https://github.com/facebookresearch/detectron2/blob/master/demo/demo.py

Using the model from,
https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml

I could see the segmented output but would like to map the labels with the class ID. Could you please point me to the labels to class ID list?.

**Comment by ppwwyyxx** [comment]
explained in https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets
