### ISSUE TITLE
error about module 'PIL.TiffTags' has no attribute 'IFD'

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#2229]
Hi,

I am using well detectron2 for three months. for this time, there is no any issue and problem.

But, today I run code and I could have below error

![image](https://user-images.githubusercontent.com/34012266/98193027-22e25f80-1f14-11eb-9bf7-1e4fac003847.png)

This code is exactly same as detectron2 tutorial code without any change (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=dq9GY37ml1kr) 

Could you please original detectron2 tutorial code? This is happening for me?

if something is wrong. please let me know

Thank you.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment]
continued in #2231
