### ISSUE TITLE
color-based classification.

### ISSUE THREAD

**Issue by ccssmania** [facebookresearch/detectron2#223]
At first thank you so much, detectron and detectron2 were so useful in previous researches.

Now I'm teaming up in a research project, as part of my master's degree thesis, which consists in categorize and classify an avocado on differents scales of maturity, the previous approach was only taking the mean of RGB and check it in the scale.
Now we have a dataset in COCO annotations in which each class corresponds to a maturity scale level.
But all the images are avocados with different colors and textures just classified by maturity in COCO Annotations.

I will appreciate any response.

**Comment by ppwwyyxx** [comment]
I do not see a question in your issue. Therefore I do not understand what response you expect.

**Comment by ccssmania** [comment]
Ok I'm sorry, the question is, is it possible to train a model in detectron2 using a dataset of only avocados but characterized by maturity?.
in other words, class 1 is gonna be green avocados and class 2 is gonna be matured avocados.
The main difference between those classes is the color.
Then the response that I want, is an object detection with those classes.
I don't know if is that possible, sorry if I'm not clear.

BTW thank you for your quickly response.

**Comment by ppwwyyxx** [comment]
You can.

**Comment by ccssmania** [comment]
thank you so mucho!
