### ISSUE TITLE
Detectron2 on Google colab error : 'PIL.TiffTags' has no attribute 'IFD'

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#2231]
# Instructions To Reproduce the Issue:

I tried to run detectron2 tutorial on colab environment without any change

1. Full runnable code or full changes you made:
```
No changes.  Running the Detectron2 tutorial on Google colab
```

2. What exact command you run:

```
# install dependencies: 
!pip install pyyaml==5.1 'pycocotools>=2.0.1'
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

import torch, torchvision
print(torch.__version__, torch.cuda.is_available())
!gcc --version
# opencv is pre-installed on colab

# install detectron2: (Colab has CUDA 10.1 + torch 1.6)
# See https://detectron2.readthedocs.io/tutorials/install.html for instructions
assert torch.__version__.startswith("1.6")
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html

# Some basic setup:
# Setup detectron2 logger
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

!wget http://images.cocodataset.org/val2017/000000439715.jpg -q -O input.jpg
im = cv2.imread("./input.jpg")
cv2_imshow(im)
```

3. __Full logs__ you observed:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

5 frames
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py in ImageFileDirectory_v2()
    666                 (TiffTags.FLOAT, "f", "float"),
    667                 (TiffTags.DOUBLE, "d", "double"),
--> 668                 (TiffTags.IFD, "L", "long"),
    669             ],
    670         )

AttributeError: module 'PIL.TiffTags' has no attribute 'IFD'
<PIL.Image.Image image mode=RGB size=640x480 at 0x7FEF8E2B3198>
```

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
colab environment
```

**Comment by ppwwyyxx** [comment]
Colab will ask you to "restart runtime" after installation. You should click "restart runtime"

**Comment by Nurungyi** [comment]
I does work very well thank you!!

**Comment by Nurungyi** [comment]
It does work very well

**Comment by janicel** [comment]
can you kindly describe how you resolve this issue? I had the same error when running Detectron2 on google colab. Thank you!

**Comment by phideltaee** [comment]
same issue here. Is there a difference using the hosted runtime and local runtime? How did you solve it?

**Comment by Nurungyi** [comment]
Hi,

After installation pytorch and detectron2, you need to restart runtime, not initialize run time.
Just try, and please let me know whether it doesn’t work or not.

Thank you

**Comment by Nurungyi** [comment]
Hi,

To be honest, I don’t know a difference between hosted runtime and local runtime.
I think that you need to restart runtime, not initialize run time after installation of pytorch and detectron2.
Just try, and please let me know whether it doesn’t work or not.

Thank you

**Comment by Nurungyi** [comment]
And also ppwwyyxx<https://github.com/ppwwyyxx> added a new short code in colab ‘exit(0)  # After installation, need to "restart runtime" in Colab. This line can also restart runtime’

Please check this it can make restarting runtime without execution of runtime restart manually.

Thank you

**Comment by janicel** [comment]
thank you! It's working!!

**Comment by TemitopeOladokun** [comment]
Try these approaches 
1. Install the latest version of pillow using this code !pip3 install --upgrade Pillow.
2. Restart your runtime .

Then you are fine
