### ISSUE TITLE
How to get 18 keypoint coco json output in openpose format

### ISSUE THREAD

**Issue by bhavesh2799** [facebookresearch/detectron2#2234]
Can anyone share a script to get 18 keypoints coco output. 
OPENPOSE:
It would be great if it could convert the output of body25 model to coco 18 keypoints output. I tried using the openpose write_coco_json, but it gave the result in an entirely different format than usual. I don't have much experience with json, so any help would be appreciated. I am currently implementing it in colab, while body25, face and hand model work fine, I cannot find a way to get a coco 18 keypoint output in the same json format.
DETECTRON2:
Currently I am using the model 'COCO Person Keypoint Detection' which outputs the input image  along with the keypoints, but I don't know how to write a json file of these keypoints in json, in openpose format. 
![4](https://user-images.githubusercontent.com/53915319/98336104-4d274080-202c-11eb-89db-2b5e7e8d42e2.jpg)

**Comment by ppwwyyxx** [comment]
The output format of detectron2 models are described in https://detectron2.readthedocs.io/tutorials/models.html. Issues regarding formats of other libraries are not relevant to this project.
