### ISSUE TITLE
Mask RCNN caffe2 model working with pre/post processing?

### ISSUE THREAD

**Issue by hpanwar08** [facebookresearch/detectron2#2237]
Has anyone managed to get the Mask RCNN/Faster RCNN caffe2 model (converted from pytorch) working with pre/post processing without the need for Detectron2 pre/post processing?

The current examples
https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_modeling.py
https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_inference.py
are confusing and keeps on calling detectron2 pre/post processing functions.

I read the code mentioned here https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python
but it is not very helpful.

**Comment by ppwwyyxx** [comment]
The python examples need to call detectron2 pre/post processing functions because they need to use detectron2's inputs and outputs format.

The C++ example is there and runnable, and does not depend on detectron2. What other information do you expect?

**Comment by hpanwar08** [comment]
I don't know c++, it's hard for me to convert c++ code to python line by line.

Does the c++ example do the resizing of the image, add padding if not divisible by 32 and resize the prediction to the original image size?

How do I load the model the model in caffe2 in python and run it on image?

**Comment by ppwwyyxx** [comment]
The C++ example does not include pre/post processing. It's up to users to provide images of correct size.

https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_inference.py is the equivalece of the C++ example in python. It does not depend on detectron2 except for the pre/post processing functions.

**Comment by hpanwar08** [comment]
Thanks for the info. 
Just to list down the pre/post processing steps

Pre processing steps:
* resize shortest side to 800 and max size of larger side not more than 1333
* both sides need to be made divisible by 32
* normalize image (is it done in the model itself?)

Post processing steps:
* convert/resize the output mask/bounding box which are 28x28 pixel to the original image size/aspect ratio

Are these steps correct?
Another question, if I update following values in the cfg, will they be included in the converted caffe2 model after conversion or this needs to be done in post processing?
`MODEL.RPN.POST_NMS_TOPK_TEST: 3000 # originally 1000`
`MODEL.RPN.PRE_NMS_TOPK_TEST: 3000 # originally 1000`

**Comment by ppwwyyxx** [comment]
> resize shortest side to 800 and max size of larger side not more than 1333

Most official models do this, but it is up to you. 

> both sides need to be made divisible by 32

This is required by most but not all models.

> normalize image (is it done in the model itself?)

Included in the model

> MODEL.RPN.POST_NMS_TOPK_TEST: 3000 # originally 1000
MODEL.RPN.PRE_NMS_TOPK_TEST: 3000 # originally 1000

These are included in the model

**Comment by hpanwar08** [comment]
Thanks for confirming the details. 
While going through the python implementation (https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_inference.py), I noticed images are not being resized to 800, they are just being made divisible by 32. I think because of this, the caffe2 inference takes more than a minute on large images. Is it intentional?

**Comment by ppwwyyxx** [comment]
> I noticed images are not being resized to 800

it's not done by the model because we prefer to let user decide the size of inputs.

**Comment by hpanwar08** [comment]
One more question I have, in detectron2 `DefaultPredictor`, image normalization is done as part of preprocessing in `GeneralizedRCNN` class in `preprocess_image` function. Does the image normalization also happens inside the converted caffe2 model or it needs to be done outside the model as part of preprocessing. I don't see the image normalization step in the caffe2 python inference code.

**Comment by ppwwyyxx** [comment]
normalization is included in the converted model as well

**Comment by hpanwar08** [comment]
Thanks for the information.

I had set 
```
MODEL:  
  RPN:  
    POST_NMS_TOPK_TEST: 5000 # optional originally 1000  
    PRE_NMS_TOPK_TEST: 5000 # optional originally 1000  
TEST:  
  DETECTIONS_PER_IMAGE: 500 # originally 100  
```
in the cfg before the caffe2 conversion, but the output results are still limited to 100. Do these settings go some where else?

**Comment by ppwwyyxx** [comment]
These settings don't go somewhere else.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by hpanwar08** [comment]
Never mind, found the issue.
Thank you for your prompt replies and patience.
