### ISSUE TITLE
Save and load trained model

### ISSUE THREAD

**Issue by AvivSham** [facebookresearch/detectron2#224]
Hi all,
I trained Fast-RCNN model and I want to save the model and load it on a remote server. since I don't want to hold the whole repo on the remote server, just the model how can that been done?
In other words, how can I initialize the model without the whole repo?

**Comment by ppwwyyxx** [comment]
You cannot. Pytorch models are represented by python code and therefore requires the corresponding python code to run.
We will try to support some recent solutions such as torchscript in the future.

**Comment by AvivSham** [comment]
OK.
I have another question I'm using csv file in which each row represent an object in an image and I have a total of 30K images. Each image has a shape of (320X240).
How should I split train/test? by image or by a row? 
How long should it take me to train? (now when I split train/test according to the rows it took around 5 minutes and the train stopped after one iteration which doesn't make sense to me.

**Comment by ppwwyyxx** [comment]
> How should I split train/test? by image or by a row?

usually by image, but it's up to you.

> How long should it take me to train?

That's up to you.

**Comment by AvivSham** [comment]
It looks like the model is training for one epoch and no more even if passing MAX_ITERATIONS > 1.
BTW another question:
How to load a model?  I have used the final_model.pth file after training to load a new model but kept receiving errors
```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml")
model = build_model(cfg)
model.load_state_dict(torch.load("./model_final.pth", map_location='cpu'))
```
This is the error I got:
```
RuntimeError: storage has wrong size: expected -5043789083544642214 got 256
```
Can you guide me please?

**Comment by ppwwyyxx** [comment]
> It looks like the model is training for one epoch

I do not know what you saw exactly so I cannot comment.

> How to load a model?

https://detectron2.readthedocs.io/tutorials/models.html

**Comment by AvivSham** [comment]
I'm having difficulties infernce images to loaded model.
tried both this:
```
model = build_model(cfg)
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml")
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(classes)
cfg.MODEL.WEIGHTS = "/content/drive/My Drive/Data/Fast_RCNN_model/fast_rcnn.pth"
DetectionCheckpointer(model).load("/content/drive/My Drive/Data/Fast_RCNN_model/fast_rcnn.pth")
```
and this:
```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml")
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(classes)
cfg.MODEL.WEIGHTS = "/content/drive/My Drive/Data/Fast_RCNN_model/fast_rcnn.pth"
model = build_model(cfg)
```

and inference:
```
from detectron2.utils.visualizer import ColorMode
for d in random.sample(val_dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = model(im)
    visualizer = Visualizer(im[:, :, ::-1],
                   metadata=clever_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```

but I keep getting this error on `outputs = model(im)`:
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
I think it's because I'm not mentioning the dataset over `cfg.DATASETS.TEST` isn't it?
please help :)

**Comment by ppwwyyxx** [comment]
`model(im)` is wrong because `im` is not the input format. The input format is documented in https://detectron2.readthedocs.io/tutorials/models.html

**Comment by AvivSham** [comment]
still even with:
```
from detectron2.utils.visualizer import ColorMode
for d in random.sample(val_dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    h, w, c = im.shape
    im = torch.tensor(im).view(h,w,c)
    print(im.shape)
    outputs = model(im)
    visualizer = Visualizer(im[:, :, ::-1],
                   metadata=clever_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```

got `IndexError: too many indices for tensor of dimension 3`

even tried to add the batch axis as new axis

**Comment by AvivSham** [comment]
still even with:
```
from detectron2.utils.visualizer import ColorMode
for d in random.sample(val_dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    h, w, c = im.shape
    im = torch.tensor(im).view(c,h,w)
    print(im.shape)
    outputs = model(im)
    visualizer = Visualizer(im[:, :, ::-1],
                   metadata=clever_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```

got this error:
` IndexError: too many indices for tensor of dimension 2`

even tried to add the batch axis as new axis didn't do the trick

**Comment by ppwwyyxx** [comment]
The input of the model, as said in https://detectron2.readthedocs.io/tutorials/models.html#model-input-format, is a list of dict with "image" as key. `.view(c,h,w)` is also a wrong way to operate the image. 
If you don't have the related background knowledge it's recommended to follow the colab tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 instead of making your own code.

**Comment by AvivSham** [comment]
I mad mistake that should be transpose. but I want to inference the link you gave asks for BB as part of the dicts attributes. I feel like I'm missing here something.

**Comment by AvivSham** [comment]
@ppwwyyxx any thoughts?
I want to take random image from the net and inference it. what are the steps from loading saved model to passing the image through it?
for example let's say I have 24 classes and trained FastRCNN model.

**Comment by ppwwyyxx** [comment]
The colab tutorial contains the steps https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

**Comment by AvivSham** [comment]
@ppwwyyxx  Can you please help me?
I have a csv file with the following columns:
1) file name
2) object class
3) X
4) Y 
5) W
6) H

and I'm using the following script to generate dataset dicts:
```
def get_dataset_dicts(dataframe):
    dataset_dicts = []
    for img in dataframe.filename.unique():
      record = {}
      objects = []
      record = {}
      for index, row in dataframe[dataframe.filename == img].iterrows():
          objs = []
          filename = './OD_data/' + row['filename']
          x = row['X']
          y = row['Y']
          height = row['height']
          width = row['width']

          obj = {
              "bbox": [x, y, width, height],
              "bbox_mode": BoxMode.XYWH_ABS,
              "category_id": classes.index(row['object_class']),
              "iscrowd": 0
          }
          objects.append(obj)
      record['file_name'] = filename
      record['height'] = 240
      record['width'] = 320
      record['annotations'] = objects
      dataset_dicts.append(record)
    return dataset_dicts
```
then I followed the steps on your tutorial but when I inference the model the output does not contain any BB and if I lower the threshold I get noisy BBs
I thought it might have to do with overfitting so I tried to play with `cfg.SOLVER.MAX_ITER` but even if using 10000 or 100 the result is still the same. My train set contains ~29K images and the task is to detect basic objects (like in CLEVER) in an image.

This is how I setup the cfg:

```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml")
cfg.DATASETS.TRAIN = ("clever_train/train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_C4_3x/137849393/model_final_f97cb7.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 16
cfg.SOLVER.BASE_LR = 0.0025
cfg.SOLVER.MAX_ITER = 100
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(classes)

```
Can you please guide me?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says:

> If you expect the model to work better, note that we do not help you train your model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

**Comment by AvivSham** [comment]
OK. 
please help me with other thing.
I tried to infernece training image and even then no boxes detected!
```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_3x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.8 # set threshold for this model
cfg.MODEL.WEIGHTS = "./output/model_final.pth"
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 22
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
try:
  print(outputs["instances"].perd_boxes)
except:
  print("no boxes detected")
```
Is this the right way to load and inference model?

**Comment by ppwwyyxx** [comment]
It is the right way. If you replace the model with the corresponding model from the model zoo (and set correct NUM_CLASSES), it should produce reasonable output.
