### ISSUE TITLE
Possible issue in help document and ram optimizations.

### ISSUE THREAD

**Issue by Warday** [facebookresearch/detectron2#2248]
Hi, I was checking the command
_C.MODEL.ANCHOR_GENERATOR.SIZES = [[32, 64, 128, 256, 512]]
from
https://detectron2.readthedocs.io/modules/config.html
In maskrcnn I use that command to force the detection of object of certain size and ignore smaller or bigger objects. When I try the command on detectron2 I saw 2 things. 
First: the command make the detection fail, even with the default value [[32, 64, 128, 256, 512]], I had to comment the line to avoid the error. 
Second. When I change the value to [[32], [64], [128], [256], [512]], it stop failing but the modification of the values doesn't make a difference on the detection. That command is used in a already trained network (inference).
Ram optimizations. 
I used colab to train and test the network and then I install D2 in my computer to test. Mask RCNN worked without problem in my 4gb graphic card but D2 failed because of insufficient ram. When I used CPU it consume around 3-3,5 gb of ram (it worked). I use the same configurations as the example for inference (I moved my colab to pycharm). Is there any config to reduce amount of ram?
the idea is to execute Detectron2 or mask-rcnn on a intel neurostik.

**Comment by ppwwyyxx** [comment]
> Is there any config to reduce amount of ram?

easiest way is to use smaller image size, smaller batch size (for ROI Head), shallower models.
