### ISSUE TITLE
How much percentage of images/annotations gets transformed when using transformation?

### ISSUE THREAD

**Issue by gaurav-oviva** [facebookresearch/detectron2#2252]
I have used four transformations.

T.RandomFlip(prob=0.6, horizontal=True, vertical=False),
T.RandomFlip(prob=0.6, horizontal=False, vertical=True),
T.RandomContrast(0.8, 3),
T.RandomBrightness(0.8, 1.6)

Does this mean that for each annotation it will create 4 more annotations that will use one transformation at a time or for each image it will create 4 more images?
This part is not much explained in the documentation. Could you please shed some light on this?

**Comment by ppwwyyxx** [comment]
We don't know what exactly you did, but usually, every image (plus its annotations) is transformed before it's used for training.
