### ISSUE TITLE
Error when register to COCO and verify data loadin #1433

### ISSUE THREAD

**Issue by morganOliveira2018** [facebookresearch/detectron2#2253]
@favervn Can you explain to me how to solve this problem? I am going through the same situation. Please.
**As soon as possible to answer me, thank you very much.**

````
WARNING [11/11 13:14:08 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[11/11 13:14:08 d2.data.datasets.coco]: Loaded 28 images in COCO format from /content/x/train.json
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-e7250c241ebb> in <module>()
      7 for d in random.sample(dataset_dicts, 3):
      8     img = cv2.imread(d["file_name"])
----> 9     v = Visualizer(img[:, :, ::-1], metadata=x_metadata, scale=0.5)
     10     v = v.draw_dataset_dict(d)
     11     plt.figure(figsize = (14, 10))

TypeError: 'NoneType' object is not subscriptable
````

_Originally posted by @morganOliveira2018 in https://github.com/facebookresearch/detectron2/issues/1433#issuecomment-725424480_

**Comment by ppwwyyxx** [comment]
The file name provided in your dicts: `d["file_name"]` is not readable.

**Comment by morganOliveira2018** [comment]
@ppwwyyxx And what would a readable way or image look like for: d ["file_name"]? 
Could you exemplify me.

**Comment by morganOliveira2018** [comment]
@kpy815 Why did you laugh at my question?

**Comment by kpy815** [comment]
`พูดไม่เก่ง`

**Comment by ppwwyyxx** [comment]
The tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 is an example.

**Comment by kpy815** [comment]
ผมมา ทำงาน ที่เรียกว่า การเปลี่ยนแปลง ระบบ ส่วนความ
ตั้งใจของผม คือ ทำไห้ ภาษา
ทั่งโลกเป็นแบบเดวกัน...
อีก อย่างคือ แผนที่ ทั่ง ระบบ
กับ วิทยาการ สำหรับ โลกบุกคนที่ 3 อย่างผม ผมไม่มีความคิดร้ายกับไคร ผมแค่คนจนคน
หนึ่งที่ มีโอกาส ..``
