### ISSUE TITLE
Not handled case: CUDA without CUDA_HOME set

### ISSUE THREAD

**Issue by MiroPsota** [facebookresearch/detectron2#2254]
When installing `torch` from pip, `from torch.utils.cpp_extension import CUDA_HOME` returns `None`, nevetheless CUDA works just fine.

In detectron2, `os.path.isdir(CUDA_HOME)` in this line expects `CUDA_HOME` to be not None.
https://github.com/facebookresearch/detectron2/blob/f1d0c05bc5580388348388213e0a77d722d90f17/detectron2/utils/collect_env.py#L136

As a temporary workaround, I'm setting `CUDA_HOME=/`. 

Environment:
As provided script is not working (it uses mentioned code), I'm just listing code to recreate env:
```shell
conda create -n detectron2 -y
conda activate detectron2

conda install python=3.8 -y

pip install \
  -f https://download.pytorch.org/whl/torch_stable.html \
  torch==1.7.0+cu101 \
  torchvision==0.8.1+cu101 \
  pycocotools \
  -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html \
  detectron2==0.3
```

**Comment by jennyjenny04** [comment]
This is my Facebook and Desirae little stole my identity and Facebook and Joshua Daniel Jones I will be SUEING BORH TOMORROW I AM TIERED OF ME AND OUR SON FROM JOSHUA DANIEL JONES DIEING CAUSE OF OUR TAXES DISABILITY MONEY AND ETC BEING STOLEN FROM PEOPLE LIKE YALL NO GOOD FOR UNITED STATES AND WILL BE ILLEGAL WHEN IM DONE TOMORROW
