### ISSUE TITLE
How to find the contour of each mask in detectron2/modeling/roi_heads/roi_heads.py?

### ISSUE THREAD

**Issue by ustczhouyu** [facebookresearch/detectron2#2255]
Hello, how to find the contour of each mask in detectron2/modeling/roi_heads/roi_heads.py in the reference stage? Please help me, thank you.

**Comment by ppwwyyxx** [comment]
It's unclear what you need to do and it doesn't sound like a feature of detectron2. Please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) if you think it's a relevant question.
