### ISSUE TITLE
Unexpected error with fast_rcnn_R_50_FPN_1x.yaml model

### ISSUE THREAD

**Issue by JaviMota** [facebookresearch/detectron2#2259]
Hi,

Im trying to run the fast_rcnn_R_50_FPN_1x model but the predictor raise an error: assert "proposals" in batched_inputs[0]

This is how I have configured the predictor:
cfg = get_cfg()
cfg.MODEL.DEVICE = 'cpu'
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = thesh  # set threshold for this model
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml")
metadata = MetadataCatalog.get(cfg.DATASETS.TRAIN[0])

predictor = DefaultPredictor(cfg)
outputs = predictor(frame) --> error

I have tried with other models like mask_rcnn_R_50_FPN_3x and it works fine.

Thanks for helping me.

**Comment by ppwwyyxx** [comment]
This is expected for Fast R-CNN as documented in https://detectron2.readthedocs.io/tutorials/datasets.html, that it needs extra proposal data. If you don't know how to obtain them, please use other models (like Faster R-CNN) instead.
