### ISSUE TITLE
ข้อกำหนด HTML 4.01

คำแนะนำ W3C 24 ธันวาคม 2542



### ISSUE THREAD

**Issue by kpy815** [facebookresearch/detectron2#2263]
ข้อกำหนด HTML 4.01
คำแนะนำ W3C 24 ธันวาคม 2542

**Comment by yang-gis** [comment]
> ข้อกำหนด HTML 4.01
> คำแนะนำ W3C 24 ธันวาคม 2542

please use English to express your questions
