### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by FirasAbdennadher** [facebookresearch/detectron2#2264]
i have annotated a custom dataset using VGG annotator  ( 699 for train & 200 for val)
when running this code:
`from detectron2.structures import BoxMode

def get_building_dicts(img_dir):
    """This function loads the JSON file created with the annotator and converts it to
    the detectron2 metadata specifications.
    """
    # load the JSON file
    json_file = os.path.join(img_dir, "via_region_data.json")
    with open(json_file) as f:
        imgs_anns = json.load(f)

    dataset_dicts = []
    # loop through the entries in the JSON file
    for idx, v in enumerate(imgs_anns.values()):
        record = {}
        # add file_name, image_id, height and width information to the records
        filename = os.path.join(img_dir, v["filename"])
        height, width = cv2.imread(filename).shape[:2]
        print(filename +" HEIGHT="+str(height)+" Width ="+str(width))
        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width

        annos = v["regions"]

        objs = []
        # one image can have multiple annotations, therefore this loop is needed
        for annotation in annos:
            # reformat the polygon information to fit the specifications
            anno = annotation["shape_attributes"]
            px = anno["all_points_x"]
            py = anno["all_points_y"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = [p for x in poly for p in x]

            

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": 0,
                "iscrowd": 0,
            }
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)

    return dataset_dicts
`
after that when i call the function 
`get_building_dicts("/content/drive/My Drive/udes/dataset/vgg/train")`

***** Error log *****
/content/drive/My Drive/udes/dataset/vgg/train/1.jpg HEIGHT=654 Width =980
/content/drive/My Drive/udes/dataset/vgg/train/2.jpg HEIGHT=600 Width =1000
/content/drive/My Drive/udes/dataset/vgg/train/3.jpg HEIGHT=528 Width =940
.
.
.
/content/drive/My Drive/udes/dataset/vgg/train/466.jpg HEIGHT=220 Width =280
/content/drive/My Drive/udes/dataset/vgg/train/467.jpg HEIGHT=249 Width =400
/content/drive/My Drive/udes/dataset/vgg/train/468.jpg HEIGHT=1301 Width =969
/content/drive/My Drive/udes/dataset/vgg/train/469.jpg HEIGHT=932 Width =1400
/content/drive/My Drive/udes/dataset/vgg/train/470.jpg HEIGHT=448 Width =337
/content/drive/My Drive/udes/dataset/vgg/train/471.jpg HEIGHT=338 Width =600
/content/drive/My Drive/udes/dataset/vgg/train/472.jpg HEIGHT=381 Width =678
/content/drive/My Drive/udes/dataset/vgg/train/473.jpg HEIGHT=371 Width =660
/content/drive/My Drive/udes/dataset/vgg/train/474.jpg HEIGHT=522 Width =763
/content/drive/My Drive/udes/dataset/vgg/train/476.jpg HEIGHT=810 Width =1440
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c3337715204d> in <module>()
----> 1 get_building_dicts("/content/drive/My Drive/udes/dataset/vgg/train")

<ipython-input-2-11af344359ef> in get_building_dicts(img_dir)
     16         # add file_name, image_id, height and width information to the records
     17         filename = os.path.join(img_dir, v["filename"])
---> 18         height, width = cv2.imread(filename).shape[:2]
     19         print(filename +" HEIGHT="+str(height)+" Width ="+str(width))
     20         record["file_name"] = filename

AttributeError: 'NoneType' object has no attribute 'shape'
I dont know if detectron support only a small dataset? 
Yet, i used the same dataset to train a model using maskrcnn ! 
Thanks.

**Comment by ppwwyyxx** [comment]
The error is not thrown from inside detectron2. There is no indication that this error is related to detectron2.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
