### ISSUE TITLE
function of inference_on_dataset for evaluation without re-training

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#2270]
## 🚀 Feature
Now, 'inference_on_dataset' takes (trainer.model, val_loader, evaluator) in tutorial of detectron2 as input. If I run tutorial page in detectron2, I can get a test result of trained model from  'inference_on_dataset'. However, If I close the detectron2 page,  I need to run 'trainer.train' again from the first for knowing a test result of trained model from  'inference_on_dataset'. I mean re-training is required.

## Motivation & Examples

I am not sure that it is possible to know 'inference_on_dataset' without re-training after closing the detectron2 page
Re-training is very time consuming sometimes. Please make the code run without
Now, predictor = DefaultPredictor(cfg) can be loaded by loading saved weight. like this, please make the code of  'inference_on_dataset' without re-training

**Comment by ppwwyyxx** [comment]
If you [load a model](https://detectron2.readthedocs.io/tutorials/models.html#load-save-a-checkpoint) following the doc, and inference on it, you don't need to re-train it.
