### ISSUE TITLE
Does the image should be in range [0, 1] for `RandomLighting`

### ISSUE THREAD

**Issue by OneDirection9** [facebookresearch/detectron2#2271]
Hi,

  The constant value of `RandomLighting` is :
``` 
    self.eigen_vecs = np.array(
        [[-0.5675, 0.7192, 0.4009], [-0.5808, -0.0045, -0.8140], [-0.5836, -0.6948, 0.4203]]
    )
    self.eigen_vals = np.array([0.2175, 0.0188, 0.0045])
```

Does this mean the image argument passing to `BlendTransform` should be in range [0, 1]?

And `RandomSaturation` too?

**Comment by ppwwyyxx** [comment]
> Does this mean the image argument passing to BlendTransform should be in range [0, 1]?

The image inputs of BlendTransform can have any range as long as they are consistent.

For `RandomLighting`, the range is controlled by its `scale` argument.

**Comment by OneDirection9** [comment]
Hi @ppwwyyxx ,

  Thanks for your reply. 
  So for the `RandomLighting`, if the `image` is in range [0, 255], the `scale` should be set to `255`. And `[0, 1]` w.r.t `scale=1`. Am I right?

**Comment by ppwwyyxx** [comment]
Yes
