### ISSUE TITLE
Combined masks and boxes with only some classes

### ISSUE THREAD

**Issue by Altair3** [facebookresearch/detectron2#2272]
I'm trying to train a network in the maskRCNN style where I propose regions and then segment only the inferred boxes. However, with the dataset I'm working with a few of the classes do not have segmentation masks, and I have yet to figure out how to set up the network to ignore those classes during the mask phase. 

Does anybody have experience with this type of training job?

**Comment by ppwwyyxx** [comment]
There is no such feature. This probably needs to be implemented as a new ROIHeads (https://detectron2.readthedocs.io/tutorials/write-models.html).
