### ISSUE TITLE
Error for run caffe2_mask_rcnn

### ISSUE THREAD

**Issue by xrxin72** [facebookresearch/detectron2#2273]
hello, I have exported a caffe2 model, run caffe2_mask_rcnn, an exception exits at CAFFE_ENFORCE(workSpace.RunNet(predictNet_.name()));

E:\detectron2\detectron2-master\tools\deploy\build\Release>caffe2_mask_rcnn.exe
[E ..\..\caffe2\core\init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E ..\..\caffe2\core\init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E ..\..\caffe2\core\init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
predictNet_.name: torch-jit-export_predict

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues says, we do not provide support for windows.
