### ISSUE TITLE
Pretrained weights in Resnet stem with >3 channels

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#2274]
Would it be possible to load the pretrained resnet stem weights despite the stem having multiple channels?

I'm trying to train a custom segmentation model with resent as the backbone. My input has 4 channels. So while trying to use the pretrained model, I get a warning that states that due to weight mismatch (3 channels vs 4 channels) stem weights will not be loaded.

However, I would like to load the pretrained stem weights for the RGB channels and initialise the 4th channel with zeros. Any suggestions on how I can go about doing this?

**Comment by ppwwyyxx** [comment]
You can modify the weights after `pickle.load` and set it to values you like.

**Comment by ashnair1** [comment]
How exactly do we do this if we're using detectron2 as a library? Doesn't detectron2 internally load the pretrained backbone weights? How can we intercept it?

**Comment by ppwwyyxx** [comment]
You can use `pickle.save` to save modified weights to a file. Then load the file with detectron2.

**Comment by Mnsy-Syl** [comment]
Hello, I'm also using detectron2 to process four channel data(tif format). Is there a situation that the value of MAP and AP are very small (almost 0) in your training results? Because I received the same warning as you when using the pretrained model.Thanks!
