### ISSUE TITLE
How to turn off any data augmentation methods in basic detectron2

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#2275]
## ❓ How to do something using detectron2

Describe what you want to do, including:

Hi,

If basic detectron2 in detectron2 tutorial (here : https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5), some augmentations are automatically applied. How can I turn off easily this function, which means not apply any data augmentation methods?

Thank you

**Comment by ppwwyyxx** [comment]
For simple switches: `cfg.INPUT.MIN_SIZE_TRAIN = (800,)` and `cfg.INPUT.RANDOM_FLIP="none"`.
more complicated customizations need https://detectron2.readthedocs.io/tutorials/data_loading.html

**Comment by Nurungyi** [comment]
Many thanks, but is it possible to simply turn off resize augmentation method (ResizeShortestEdge(short_edge_length=(800,), max_size=1333, sample_style='choice'), which may be rescale augmentation.?

**Comment by ppwwyyxx** [comment]
This would be a customization that can be done through https://detectron2.readthedocs.io/tutorials/data_loading.html. Following the doc:
```
dataloader = build_detection_train_loader(cfg,
   mapper=DatasetMapper(cfg, is_train=True, augmentations=[
  # nothing
   ]))
```

**Comment by Nurungyi** [comment]
Thank you, I think that you are genius!
