### ISSUE TITLE
How to add metadata when custom model is used to run prediction on videos

### ISSUE THREAD

**Issue by AnupamaRajkumar** [facebookresearch/detectron2#2279]
## ❓ How to do something using detectron2

I have created a custom model from which I have generated a custom config file. When I use the saved model path and custom config file, I can see segmented section in the video but I am unable to see the metadata values. How can I add metadata value when running the prediction on video using command line?

This is how I am running prediction on the video
!python detectron2/demo/demo.py --config-file /content/output/config.yaml --video-input video.mp4 --confidence-threshold 0.5 --output video-output_1.mkv \
  --opts MODEL.WEIGHTS /content/output/model_final.pth

My metadata looks like this:
MetadataCatalog.get("SimpsonsSet_" + d).set(thing_classes=["Homer", "Marge", "Maggie", "Lisa", "Bart"])

The prediction works find when run on static images as I pass metadata as a parameter to the visualizer but I am not sure how I can so that for videos

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work" for something you did, please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
> The prediction works find when run on static images as I pass metadata as a parameter to the visualizer but I am not sure how I can so that for videos

`VideoVisualizer` also has the "metadata" parameter.

**Comment by AnupamaRajkumar** [comment]
@ppwwyyxx you're right, I saw that VideoVisualizer takes "metadata" parameter. But i dont know how can I pass that through the command line 
!python detectron2/demo/demo.py --config-file /content/output/config.yaml --video-input video.mp4 --confidence-threshold 0.5 --output video-output_1.mkv
--opts MODEL.WEIGHTS /content/output/model_final.pth

any pointers?

**Comment by ppwwyyxx** [comment]
`demo.py` is an example tool that shows the capability of `VideoVisualizer`. It's not intended to be used directly on any model and any dataset.
Users need to write code to use `VideoVisualizer` just like how they use `Visualizer`.
