### ISSUE TITLE
How to change visualizer options?

### ISSUE THREAD

**Issue by derornos** [facebookresearch/detectron2#228]
## ❓ 

Hi. I am wondering how to change visualization options.

ex.
mask alpha: 0.8 to 0.5
label text (taxi, car, person, ...): ON -> OFF

My command line is as follows.
`python3 demo/demo.py --config-file configs/ --output outputFolder --input ../blahblah.img --opts MODEL.WEIGHTS ./models/model_r101_panoptic_fpn_coco.pkl`

**Comment by ppwwyyxx** [comment]
alpha can be set at 
https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances

class names will not show if the metadata you provide to https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.__init__ does not contain the class names.

**Comment by derornos** [comment]
Thx!!!
