### ISSUE TITLE
what is the result of visualize_json_results.py

### ISSUE THREAD

**Issue by GittersYang** [facebookresearch/detectron2#2280]
I want  visualizes the json predictions using visualize_json_results.py? but ,Why does a picture have two results?
What are the two of them
![Snipaste_2020-11-18_09-33-12](https://user-images.githubusercontent.com/44436506/99471579-c8b8b400-2981-11eb-9acc-97943146b940.png)

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment]
According to the code the two results are ground truth and predictison. 
https://github.com/facebookresearch/detectron2/blob/84a09834f6d838534951907fd9ef90fec73614d2/tools/visualize_json_results.py#L82-L87

**Comment by GittersYang** [comment]
OK  thanks .I couldn't believe it is  ground truth at first，because many edges of the visualization are not very fine.

now, i have another issue,what is another file(instances_prediction) in the folder(inference older)

**Comment by GittersYang** [comment]
OK thanks .I couldn't believe it is ground truth at first，because many edges of the visualization are not very fine.

now, i have another issue.What is another file(instances_prediction) in the folder(inference older)?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.COCOEvaluator.__init__

**Comment by GittersYang** [comment]
The ground truth result of ground truth visualization is not refined.The edge of each instance are not smooth
How does the visual operation work?
Is the edge of each instance a polygon connected by some points?

**Comment by ppwwyyxx** [comment]
The source code is in https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py
