### ISSUE TITLE
Is it possible to simply turn off a resize augmentation method (ResizeShortestEdge)??

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#2282]
## ❓ How to do something using detectron2

Describe what you want to do, including:

Teacher, I think that if we follow a code based on official detectron2 tutorial for object detection, two data augmentation methods are automatically used (ResizeShortestEdge, and flip). 

You taught me that how to simply turn off  a data augmentation method of flip (here : https://github.com/facebookresearch/detectron2/issues/2275). Is it possible to simply turn off a resize augmentation method (ResizeShortestEdge(short_edge_length=(800,), max_size=1333, sample_style='choice'), which may be rescale augmentation?

I tried to add this one cfg.INPUT.MIN_SIZE_TRAIN = (800,) and cfg.INPUT.RANDOM_FLIP="none". However, It could only turn off rondom_flip. Maybe If I use 'Datamapper' function, I can control the data augmentation methods but I want to do this easily.

Please let me know. Many thanks,

**Comment by ppwwyyxx** [comment]
See #2275
