### ISSUE TITLE
3D skeletons

### ISSUE THREAD

**Issue by rirri93** [facebookresearch/detectron2#2283]
## ❓ How to do something using detectron2
I've seen that with Detectron is possible to have a sort of 3D mask of the body. 
Is it possible to obtain 3D skeletons starting from these masks?
I need to give a monocular RGB video (with more than one human subject per frame) in input and obtain an estimation of the 3D pose of the human body. 
Thanks.

**Comment by ppwwyyxx** [comment]
Detectron2 does not include these types of models.

**Comment by archonic** [comment]
Sorry to comment on an old issue, but there seems to be a skeleton in the last example in this image in the readme:
https://user-images.githubusercontent.com/1381301/66535560-d3422200-eace-11e9-9123-5535d469db19.png

Is that not from detectron2?
