### ISSUE TITLE
Cant install detectron2 on MacOS

### ISSUE THREAD

**Issue by IsaacPatole** [facebookresearch/detectron2#2285]
Hello
After cloning the repo, I am trying to run the following command: CC=clang CXX=clang++ python3 -m pip install -e .

The error: error: command 'clang' failed with exit status 1

ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jv/kr7cwggn2530jr81_rh1rjnr0000gn/T/pip-install-l9m83oor/pycocotools/setup.py'"'"'; __file__='"'"'/private/var/folders/jv/kr7cwggn2530jr81_rh1rjnr0000gn/T/pip-install-l9m83oor/pycocotools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jv/kr7cwggn2530jr81_rh1rjnr0000gn/T/pip-record-1pvcqhhn/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/Isaac/Library/Python/3.8/include/python3.8/pycocotools Check the logs for full command output.

I tried: export MACOSX_DEPLOYMENT_TARGET=10.14.6 becaues anything other than this gives me an error.

Would be really helpful if someone can help me with this...

Regards,
Isaac Patole

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by harshitsankhla** [comment]
@IsaacPatole I've successfully built it today on my MacBook Pro running macOS 10.15 using the normal command - 
`python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`

**Comment by IsaacPatole** [comment]
Ohh I see, then thats awesome! I solved my issue by adding export ARCHFLAGS="-arch x86_64"
 before the CC=clang CXX=clang++ python -m pip install e .


as per #2288

**Comment by apivovarov** [comment]
Strange, I tried to use `export ARCHFLAGS="-arch x86_64"` but `pycocotools` installation still fails - `#error Unsupported architecture`
```
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/Library/Python/3.8/site-packages/numpy/core/include -I./common -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c ./common/maskApi.c -o build/temp.macosx-10.14.6-x86_64-3.8/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
  In file included from ./common/maskApi.c:8:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:30:
  /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
  #error Unsupported architecture
```

**Comment by apivovarov** [comment]
ok, I found the issue, I need to use `ARCHFLAGS` after `sudo`:
```
sudo ARCHFLAGS="-arch x86_64" python3 -m pip install -U pycocotools
```
