### ISSUE TITLE
tridentnet inference demo?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#229]
## 🚀 Feature

Tridennet inference demo? Any single-image inference and  visualization  support in projects/TridentNet?

**Comment by ppwwyyxx** [comment]
Please refer to the colab tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 on how to write a few lines of code to load a model and run inference.
