### ISSUE TITLE
AssertionError: Attribute 'thing_classes' in the metadata of 'Fishes_train' cannot be set to a different value!

### ISSUE THREAD

**Issue by morganOliveira2018** [facebookresearch/detectron2#2290]
1. Adapted executed code:
Use Custom Datasets/Register a COCO Format Dataset - https://detectron2.readthedocs.io/tutorials/datasets.html#register-a-coco-format-dataset
````
from detectron2.data.datasets import register_coco_instances

for d in ["train", "test"]:
    register_coco_instances(f"Fishes_{d}", {}, f"/content/fish_segmentation_instance/fish segmentation instance/{d}.json", f"/content/fish_segmentation_instance/fish segmentation instance/{d}")
    MetadataCatalog.get(f"Fishes_{d}").set(thing_classes=['fish_ariaco', 'fish_cavala'])

````
2. Error displayed:
````
AssertionError: Attribute 'thing_classes' in the metadata of 'Fishes_train' cannot be set to a different value!
['fish_ariaco', 'fish_cavala'] != ['body', 'fish', 'fish']
````

**3. Doubt:**

**Is it possible to set new labels for (thing classes)? Has anyone managed to do this? I want to rename the ones I registered.**

**Comment by morganOliveira2018** [comment]
@ppwwyyxx Since my dataset is in the COCO format, I only ran these three lines below:
````
from detectron2.data.datasets import register_coco_instances

for d in ["train", "test"]:
    register_coco_instances(f"Fishes_{d}", {}, f"/content/fish_segmentation_instance/fish segmentation instance/{d}.json", f"/content/fish_segmentation_instance/fish segmentation instance/{d}")
    MetadataCatalog.get(f"Fishes_{d}").set(thing_classes=['fish_ariaco', 'fish_cavala'])

````

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by morganOliveira2018** [comment]
@ppwwyyxx Okay, I formatted and opened a new question using the template.

**Comment by john2020-210** [comment]
I met the same problem,have you solved that?

**Comment by morganOliveira2018** [comment]
@john2020-210 Yes, I was setting on the things_classes the labels that were not recognized in the train.json file, I had to correct the Labelme labels, I rewrote 'fish_ariaco' -> 'fish ariaco', putting the spaces recognized in the train.json class. These classes ['body', 'fish', 'fish'] were generated automatically in Labelme, as if they were generic classes.
