### ISSUE TITLE
Why not use distributed.Store.get/set instead of comm.gather during test?

### ISSUE THREAD

**Issue by FateScript** [facebookresearch/detectron2#2293]
## 🚀 Feature
During testing, Detectron2 is using a self-defined [gather](https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/comm.py#L177 ), which is complicated. 

I wanderi why not using dist.Stoge.get/set to do such a communication across dist process since get/set is much easier.
Could you tell me the reason if you have considered such an implementation before ?

## Motivation & Examples

dist.Store.get/set is much easier to understand for users.

**Comment by ppwwyyxx** [comment]
The code is written before `dist.store.get/set` exists, so we have not considered it.

The same function exists in pytorch: https://github.com/pytorch/pytorch/blob/ec256ab2f2f7c65c3fa25e16438a467f9959937c/torch/distributed/distributed_c10d.py#L1439-L1472 If you think there are easier ways to implement it, it's better to improve it in pytorch first.
