### ISSUE TITLE
How to  Transfer Learning?

### ISSUE THREAD

**Issue by iot-hunter** [facebookresearch/detectron2#230]
I want to train DeepFashion2 dataset but i don not have mang GPU   so i want to transfer coco result ? 
what should I do?

**Comment by TannerGilbert** [comment]
Take a look at the[ "Train on a custom dataset" section](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=b2bjrfb2LDeo) of the ["Detectron2 Tutorial" notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5). It shows how to use transfer learning with a custom data-set

**Comment by Aashish243** [comment]
I think there are only limited models that you can train without GPU.
