### ISSUE TITLE
What does mask_accuracy mean？

### ISSUE THREAD

**Issue by GittersYang** [facebookresearch/detectron2#2301]
![Snipaste_2020-11-22_17-03-24](https://user-images.githubusercontent.com/44436506/99899526-f769be00-2ce4-11eb-8dbf-be5487d3a783.png)

Can you explain in detail what mask_accuracy means? I read the source code but did not understand.
thanks!!!

**Comment by ppwwyyxx** [comment]
It means the accuracy of the mask head prediction during training.
