### ISSUE TITLE
Add example config for rotated faster-rcnn

### ISSUE THREAD

**Issue by MrParosk** [facebookresearch/detectron2#2303]
## Motivation & Examples

At the moment, finding a working yaml-config for rotated faster-rcnn is a bit tricky (need to go through github issues and find for example https://github.com/facebookresearch/detectron2/issues/21).

It would be nice to have an example under the config folder, e.g. in the misc folder: rotated_faster_rcnn_R_101_C4.yaml.

## Note

**Comment by ppwwyyxx** [comment]
Duplicate of #21.
