### ISSUE TITLE
how to train "maskrcnn" using the voc dataset? 

### ISSUE THREAD

**Issue by GittersYang** [facebookresearch/detectron2#2304]
I want to train "maskrcnn" using the voc dataset. 
But the bug is:  AttributeError: Cannot find field 'gt_masks' in the given Instances!

Can't the voc dataset be used for instance segmentation?

**Comment by ppwwyyxx** [comment]
> Can't the voc dataset be used for instance segmentation?

No, because we did not include instance segmentation annotations of the dataset.

**Comment by GittersYang** [comment]
OK ，thanks：）
