### ISSUE TITLE
How to get pixel level accurate segmentation map?

### ISSUE THREAD

**Issue by sarath0993** [facebookresearch/detectron2#2306]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
Input image(RGB)

2. what outputs you are expecting:
After making panoptic prediction on image, patches are created. I saved image using `visualizer.draw_sem_seg` and `cv2.imwrite(opdir + item + "_sem.png", vis_output.get_image()[:, :, ::-1])` It follows color as per stuff_colors. But it produces more unwanted colors at the edges between masks(like the screenshot attached below). 
I have done some modifications like `edge_color=color`, so that it applies same color for both fill and edge pixels. But it still produces unwanted colors at the mask intersection.

I want a clean RGB segment map, it should contain RGB values only listed on "stuff_colors".

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

![Screenshot from 2020-11-23 20-41-59](https://user-images.githubusercontent.com/47630821/99979111-c82e7c00-2dcc-11eb-8d37-146e8beeee1f.png)

**Comment by ppwwyyxx** [comment]
The output format of the model is documented in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
You can take the outputs to draw them in ways you like.
