### ISSUE TITLE
How to train a detectron2 model using a pytorch-lightning Trainer?

### ISSUE THREAD

**Issue by hiyyg** [facebookresearch/detectron2#2308]
The pytorch-lightning's Trainer allows users to use different backends, eg. ddp, ddp_spawn, dp, horovod, etc. 
Is it possible to train a detectron2 model using the trainers from pytorch-lightning?

**Comment by ppwwyyxx** [comment]
We've heard users do it, so it is possible.
We do not provide support for questions regarding using other libraries.

**Comment by ozen** [comment]
@ppwwyyxx Will you become a part of this initiative:
https://ai.facebook.com/blog/reengineering-facebook-ais-deep-learning-platforms-for-interoperability
