### ISSUE TITLE
How to train on certain classes?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#231]
## ❓ Questions and Help

How to train certain classes inside coco, say, just need `car, dog, perdestrian, trafficlight` all other categories ignored. Is that an easy way to do this?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/datasets.html and the colab notebook already have instructions and code to train on custom datasets.

**Comment by jinfagang** [comment]
Not custom dataset, but select certain classes out from coco to train, rather than load them all.

**Comment by ppwwyyxx** [comment]
"Dataset" means images and the annotations. Therefore it is a custom dataset.
You can register a dataset that loads coco dataset (with https://detectron2.readthedocs.io/modules/data.html#detectron2.data.datasets.load_coco_json) and remove classes you don't need.
