### ISSUE TITLE
How to know if the instance is in the specific area?

### ISSUE THREAD

**Issue by manmani3** [facebookresearch/detectron2#2311]
For the title question, I thought the way#1 about the instance's coordinate at first.
The instance segmentation result with my custom dataset is good, but, way#1 needs the detected result's coordinates.
For example, the test image has three detected instance, then I need the each coordinate as a annotation coordinates(= some boundary points list), not box format(= (0, 0, 10, 10)).
So, check if the instance's partition is in my specific area(e. g. 0, 0, 20, 20) with instance coordinates info.
But, I couldn't find the API that returns instance's coordinates info.

Or is there any best way(#2, #3...) to getting know if the instance is in my specific area?

**Comment by ppwwyyxx** [comment]
The question doesn't seem related to detectron2 (it does not mention detectron2).
Detectron2 predicts the segmentation result in the documented format. How to derive other information from the result is up to users.
