### ISSUE TITLE
when I using the trained model in server，there are appearing many smaller bboxes than normal bbox

### ISSUE THREAD

**Issue by shehuimao** [facebookresearch/detectron2#2314]
train environment： torch==1.8.0 detectron2==0.3
server environment: torch==1.3.1 detectron2 ==0.1

when I using the trained model in server，there are appearing many smaller bboxes than normal bbox. 
But when I use the demo/demo.py I can  detect correctly the bbox which I am needed.
I am confused!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
