### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not GeneralizedRCNN

### ISSUE THREAD

**Issue by liuzimo** [facebookresearch/detectron2#2315]
## Instructions To Reproduce the 🐛 Bug:

`# You may need to restart your runtime prior to this, to let your installation take effect
# Some basic setup:
# Setup detectron2 logger
import detectron2
import os
import math
# import some common libraries
import numpy as np
import cv2
import torch

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer, ColorMode
from detectron2.data import MetadataCatalog
coco_metadata = MetadataCatalog.get("coco_2017_val")

def getpath(l):
    a = str(l)
    for i in range(6 - len(a)):
        a = "0"+a
    return a

def getpredictor():
  cfg = get_cfg()
  cfg.merge_from_file(model_zoo.get("COCO-InstanceSegmentation\\mask_rcnn_R_50_FPN_3x.yaml"))
  cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
  cfg.MODEL.WEIGHTS = model_zoo.get("COCO-InstanceSegmentation\\mask_rcnn_R_50_FPN_3x.yaml")
  mask_rcnn_predictor = DefaultPredictor(cfg)
  return mask_rcnn_predictor

label = 0
mask_rcnn_predictor = getpredictor()`

Building wheels for collected packages: fvcore
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.2.post20201122-py3-none-any.whl size=44459 sha256=165fad93b686f186c25ed08f85233ca2092ddacfaadbd60e9ab9d40b54bc9b3b
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\49\aa\18\c24ea861404ea40f2b7845be25f6891d4c3de4a0111cc381c7
Successfully built fvcore
Installing collected packages: fvcore
Successfully installed fvcore-0.1.2.post20201122

C:\Users\Admin\Desktop\main>python mask.py
Traceback (most recent call last):
  File "mask.py", line 35, in <module>
    mask_rcnn_predictor = getpredictor()
  File "mask.py", line 28, in getpredictor
    cfg.merge_from_file(model_zoo.get("COCO-InstanceSegmentation\\mask_rcnn_R_50_FPN_3x.yaml"))
  File "e:\detectron2\detectron2\config\config.py", line 30, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
  File "C:\Users\Admin\Anaconda3\lib\site-packages\fvcore\common\file_io.py", line 737, in isfile
    return self.__get_path_handler(path)._isfile(path, **kwargs)  # type: ignore
  File "C:\Users\Admin\Anaconda3\lib\site-packages\fvcore\common\file_io.py", line 622, in __get_path_handler
    path = os.fspath(path)  # pyre-ignore
TypeError: expected str, bytes or os.PathLike object, not GeneralizedRCNN

**Comment by ppwwyyxx** [comment]
See docs: https://detectron2.readthedocs.io/modules/model_zoo.html#detectron2.model_zoo.get_config_file
