### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/train2017/0000265_05000_d_0000011.txt

### ISSUE THREAD

**Issue by vishaldhull09** [facebookresearch/detectron2#2316]
i am training a custom dataset which is in instance_train2017.json format and images under folder 'datasets/coco/train2017/'  but why it is still looking for txt file when we need json file for annotation?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
