### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by soad89** [facebookresearch/detectron2#2317]
Hello. I have recently tried to export mask_rcnn_R_50_FPN to ONNX and went through, but as expected it fails at GPU runtime enviroment because of unsuported ATen op. Is a plan to replace ATen or is this more related task for Pytroch or ONNX team to support it? Thanks

**Comment by ppwwyyxx** [comment]
There is no plan for us to support runtime other than pytorch and caffe2. Users may need to convert the graph for other runtime.
