### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by XuekuanWang** [facebookresearch/detectron2#2318]
If you do not know the root cause of the problem, and wish someone to help you,

the Issue is:

Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.1.1)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.2.8)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard->detectron2==0.3) (3.1.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from rsa<5,>=3.1.4; python_version >= "3.5"->google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.4.8)
Requirement already satisfied: zipp>=0.5 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard->detectron2==0.3) (3.4.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (3.1.0)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.3+cu101
    Uninstalling detectron2-0.3+cu101:
      Successfully uninstalled detectron2-0.3+cu101
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/dell/anaconda3/envs/py37_pytorch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dell/wxk_workspace/tmp/detectron2/setup.py'"'"'; __file__='"'"'/home/dell/wxk_workspace/tmp/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/dell/wxk_workspace/tmp/detectron2/
    Complete output (49 lines):
    running develop
    running egg_info
    creating detectron2.egg-info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    creating /home/dell/wxk_workspace/tmp/detectron2/build
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlignRotated
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlign
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/cocoeval
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/nms_rotated
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/box_iou_rotated
    creating /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/deformable
    Emitting ninja build file /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.1
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/detectron2
    g++ -pthread -shared -B /home/dell/anaconda3/envs/py37_pytorch/compiler_compat -L/home/dell/anaconda3/envs/py37_pytorch/lib -Wl,-rpath=/home/dell/anaconda3/envs/py37_pytorch/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/vision.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/cuda_version.o -L/home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/detectron2/_C.cpython-37m-x86_64-linux-gnu.so
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/vision.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o: 没有那个文件或目录
    g++: error: /home/dell/wxk_workspace/tmp/detectron2/build/temp.linux-x86_64-3.7/home/dell/wxk_workspace/tmp/detectron2/detectron2/layers/csrc/cuda_version.o: 没有那个文件或目录
    error: command 'g++' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of detectron2
  Moving to /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages/detectron2-0.3+cu101.dist-info/
   from /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages/~etectron2-0.3+cu101.dist-info
  Moving to /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages/detectron2/
   from /home/dell/anaconda3/envs/py37_pytorch/lib/python3.7/site-packages/~etectron2
ERROR: Command errored out with exit status 1: /home/dell/anaconda3/envs/py37_pytorch/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dell/wxk_workspace/tmp/detectron2/setup.py'"'"'; __file__='"'"'/home/dell/wxk_workspace/tmp/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

## Environment:

ubuntu18.04
cuda10.1
conda
python3.7
g++ 7.5 or g++5

**Comment by ppwwyyxx** [comment]
Please provide ways to reproduce the issue. Otherwise we cannot help.

**Comment by Be997398715** [comment]
Have you finished it? I have this error now.
