### ISSUE TITLE
Is there a way to obtain coordinates of points of a particular body part ?

### ISSUE THREAD

**Issue by sid0407** [facebookresearch/detectron2#2319]
I have been trying this for a while and not seem to get any conclusive answer. I want to compare the coordinates of hands of multiple persons present in the same image but I am not able to obtain the coordinates. Can someone tell me how do I do this?

**Comment by ppwwyyxx** [comment]
It's unclear what it means to "obtain coordinates of points of a particular body part". Detectron2 includes keypoint detection for people and densepose for body parsing (demo in https://ai.facebook.com/blog/-detectron2-a-pytorch-based-modular-object-detection-library-/) - if it's not what you need you'll need to implement something on your own.
