### ISSUE TITLE
Which model provides the entire image segmentation?

### ISSUE THREAD

**Issue by rakshitagouni** [facebookresearch/detectron2#2322]
I am trying to segment images that primarily include road, vehicles, and vegetation. I noticed on the very main github for this project, that there is this a model that segments the entire image for such labels. I've looked through most of the models listed here: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md but can't find one that matches what I am looking for.

Does anyone know which model does this?
![Image of Main Page](https://octodex.github.com/images/yaktocat.png
<img width="850" alt="Screen Shot 2020-11-27 at 8 25 01 PM" src="https://user-images.githubusercontent.com/59705912/100491024-a3991380-30ee-11eb-985e-9ed1885677b5.png">
)

My Image (need the road and vegetation to also be labeled):
![My Image with One of the Models](https://octodex.github.com/images/yaktocat.png <img width="703" alt="Screen Shot 2020-11-27 at 8 26 42 PM" src="https://user-images.githubusercontent.com/59705912/100491054-dfcc7400-30ee-11eb-958e-317510e3f047.png">
)

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-panoptic-segmentation-baselines-with-panoptic-fpn
