### ISSUE TITLE
Can I implement my own AnchorGenerator without inheriting from nn.Module

### ISSUE THREAD

**Issue by DianCh** [facebookresearch/detectron2#2324]
## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/_modules/detectron2/modeling/anchor_generator.html?highlight=DefaultAnchorGenerator

Hi, I'm trying to write my own anchor generator, and noticed that the `DefaultAnchorGenerator` inherits from `nn.Module`. To my understanding the anchor generator only generates a grid of anchor boxes given the input feature map shape; no backprop is needed in this process. So why is `DefaultAnchorGenerator` inherited from `nn.Module`? Can I implement a generator simply as a plain `object` class? Please correct me if I'm missing something here.

Thank you for your help!

**Comment by ppwwyyxx** [comment]
As a nn.Module, anchor generator contains states that are saved together with the model. Sometimes the state is needed when loading a checkpoint, but often not necessary.
