### ISSUE TITLE
Can I run detectron2 with a Rrtx30 series GPU

### ISSUE THREAD

**Issue by kyliao426** [facebookresearch/detectron2#2325]
as title,
 I want to upgrade my device recently.
Is detectron2 already support in Rtx 30 series GPU?
If yes, how can I do that?

thanks

**Comment by Sterbenair** [comment]
i don't know others guys, but the detectron2 can't install in my RTX 3090. 
an error occured in compiling:
nvcc fatal   : Unsupported gpu architecture 'compute_86'

**Comment by ppwwyyxx** [comment]
It can build if a pytorch bug is fixed: https://github.com/pytorch/pytorch/pull/47585

**Comment by dyd19970512** [comment]
i successfully install pytorch 1.7 + cuda 11.1 on my rtx 3070, It can run normally, but detectron2 still can't run.It looks like a compatibility issue.

**Comment by ppwwyyxx** [comment]
In pytorch 1.7 the above bug was not fixed.

**Comment by dyd19970512** [comment]
> In pytorch 1.7 the above bug was not fixed.

So if i want to run detectron2 on rtx 3070, can it be achieved? or i should wait for the bug to be fixed.

**Comment by Sterbenair** [comment]
@ppwwyyxx Did you try the preview version of pytorch 1.7 with CUDA11.1 or CUDA11.0? are they fixed?

**Comment by sarath0993** [comment]
Any solution for this?

**Comment by markstrefford** [comment]
Here's how I did it on Windows 10 using WSL2. It uses CUDA11.2 and an RTX3070 GPU https://github.com/markstrefford/running-detectron2-on-windows-wsl2-rtx30xx
