### ISSUE TITLE
Turn off text labels for COCO-Panoptic segmentations

### ISSUE THREAD

**Issue by rakshitagouni** [facebookresearch/detectron2#2331]
I'm running COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml to semantically segment my images. Is there any way to delete the text labels (and only keep the colors)?

![image](https://user-images.githubusercontent.com/59705912/100660012-73848700-331f-11eb-8ad8-40b205ee652a.png)
 (i.e delete the black boxes that have text for tree, bike, person, etc.)

**Comment by ppwwyyxx** [comment]
See docstring of https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer

**Comment by rakshitagouni** [comment]
So I have made changes to the _detectron2/utils/visualizer.py_ file. Is this the correct file? 
I have changed the **draw_binary_text** function to not take in text as a parameter and made the necessary changes in the rest of the file. Also, in predictor.py I have changed it so that only the **draw_sem_seg** function is called. I am still getting the black text labels to show up. 

Also, my command that I'm running is:
`python demo.py --config-file ../configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml --input input1.png input2.png --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_50_3x/139514569/model_final_c10459.pkl MODEL.DEVICE cpu`

Any help would be greatly appreciated!

Thank you!!

**Comment by ppwwyyxx** [comment]
As the link above says: the visualizer don't aim to provide different drawing styles. You can use primitive methods like `draw_{text,box,circle,line,binary_mask,polygon}` to draw the elements yourself. If you don't draw texts, there will be no texts.

While using these methods, if you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
