### ISSUE TITLE
AttributeError: Cannot find field 'gt_keypoints' in the given Instances

### ISSUE THREAD

**Issue by peyman-sabouri** [facebookresearch/detectron2#2333]
## ❓ How to do keypoint detection using detectron2 with custom dataset

I am able to load my dataset using load_coco_json. I am also able to plot the bouding_boxes and keypoints similar to what is described in colab tutorial. However, when I run training (trainer.train()), I get this error:

AttributeError: Cannot find field 'gt_keypoints' in the given Instances!Please read & provide the following

## ❓ AttributeError: Cannot find field 'gt_keypoints' in the given Instances?

I am using the following functions:

DatasetCatalog.clear()
DatasetCatalog.register("my_data", lambda: load_coco_json(json_file,
                                       images, dataset_name=None,
                                        extra_annotation_keys=["iscrowd", "bbox", "keypoints"
                                         "keypoints_names", "keypoint_flip_map","bbox_mode"]))
MetadataCatalog.get("my_data").set(thing_classes=["person"],
                                                         keypoint_names=["bl","tl","top","tr","br","bottom","middle"],
                                                         keypoint_flip_map=[["bl", "br"], ["tl" ,"tr"]],
                                                         json_file=json_file,
                                                         image_root=images,
                                                         extra_annotation_keys=["iscrowd", "bbox", "keypoints", "bbox_mode", 
                                                        "keypoints_names", "keypoint_flip_map"])

**Comment by ppwwyyxx** [comment]
I believe your keypoint annotation is not in COCO format. 
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by peyman-sabouri** [comment]
@ppwwyyxx 
Thank you for your response. I found that I need to add info key in my dataset.
