### ISSUE TITLE
May detectron2 provide pre-trained proposal files for COCO like in detectron

### ISSUE THREAD

**Issue by bsun0802** [facebookresearch/detectron2#2336]
## 🚀 Feature

May detectron2 provides pre-trained proposal files in the model zoo, as in detectron.

## Motivation & Examples

Detectron provide RPN proposal `.pkl` files for COCO2014, I wonder will detectron2 model zoo provide the proposals files, preferably for COCO2017? 

Here is the [link](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) for proposals model zoo from detectron.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml includes some. The format is the same so all proposals provided in detectron can be used as well.
