### ISSUE TITLE
❓ How to add some additional features in maskrcnn (e.g p7, p8) to RPN  using detectron2

### ISSUE THREAD

**Issue by zunairaR** [facebookresearch/detectron2#2337]
## ❓ How to add some additional features (e.g p7, p8) to RPN  using detectron2
 I want to compute features from multiple backbones e.g. 1= resnet50fpn, 2= vgg, 3= resnet18. Now giving all these features( p2, p3, p4, p5 and p6 from backbone 1 and e.g p7, p8 from backbone 2, and so on) to RPN. 
Now, where should I introduce my backbones and how can I add these extra features to RPN. Which code files should I change?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html#register-new-components shows how to write new backbones.
`RPN.IN_FEATURES` control what features RPN uses.
