### ISSUE TITLE
How to assigned downloaded pkl file weight 

### ISSUE THREAD

**Issue by jakeum** [facebookresearch/detectron2#2338]
I downloaded the pkl file from 
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

and I loaded like this 
 ```
   model_name = 'Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml'
   cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(model_name)  # Let training initialize from model zoo    
   cfg.MODEL.WEIGHTS = os.path.join("/home/min/Gits/kogas_pytorch/kogas_detectron2/weights/model_final_480dd8.pkl")
```
but this gave 

 ```
  }[depth]
KeyError: 51
```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
