### ISSUE TITLE
How to use mask-rcnn without COCO-pretrained?

### ISSUE THREAD

**Issue by yamiefun** [facebookresearch/detectron2#2339]
Hi,

The `mask_rcnn_R_50_FPN_3X.yaml` in model zoo is pretrained on COCO right?
How can I create a mask-rcnn without pretrained on COCO, but the backbone (ResNet-50) need to be pretrained on ImageNet?

Thanks very much!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#use-models
