### ISSUE TITLE
What's the lr decay step for 6x?

### ISSUE THREAD

**Issue by lzrobots** [facebookresearch/detectron2#234]
Hi,

I would like to know the lr decay step for 6x (eg, used by Tensormask paper).
Thanks.

**Comment by ppwwyyxx** [comment]
480k, 520k, 540k.
Tensormask cites https://arxiv.org/pdf/1811.08883.pdf when mentioning 6x, and https://arxiv.org/pdf/1811.08883.pdf explains what is 6x.
