### ISSUE TITLE
I have a questioned about pretrained model 

### ISSUE THREAD

**Issue by jakeum** [facebookresearch/detectron2#2340]
cascade_mask_rcnn_R_50_FPN_3x.yaml
let say this is pretrained with imagenet. 
then is it mean the whole cascade network is pretrained with imagenet localization?
or just backbone(resnet-50) is pretrained with imagenet classification? 
If I want to use the backbone as R_101 and pretrained weight(which I can not find) 
How should I made the pretrained model with resnet-101 backbone?

**Comment by ppwwyyxx** [comment]
> let say this is pretrained with imagenet.

we didn't say this, so we don't know what it means.

pretrained weights are available in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md
