### ISSUE TITLE
❓ Problem with 'trainer = CocoTrainer(cfg)'

### ISSUE THREAD

**Issue by morganOliveira2018** [facebookresearch/detectron2#2341]
## ❓ During the training I did this part that ran perfectly:

I am trying to use the version of 0.1.3 because it allows to check the evolution of the mAP of a custom data set. Before starting training, we need to make sure that the model validates against our validation set. Unfortunately, this does not happen by default. 

1. We can easily do this by defining our custom trainer based on the Default Trainer with the COCO Evaluator. 
````
# We are importing our own Trainer Module here to use the COCO validation evaluation during training. Otherwise no validation eval occurs.

from detectron2.engine import DefaultTrainer
from detectron2.evaluation import COCOEvaluator

class CocoTrainer(DefaultTrainer):

  @classmethod
  def build_evaluator(cls, cfg, dataset_name, output_folder=None):

    if output_folder is None:
        os.makedirs("coco_eval", exist_ok=True)
        output_folder = "coco_eval"

    return COCOEvaluator(dataset_name, cfg, False, output_folder)
````

2. Performing custom data set training:
```
#from .detectron2.tools.train_net import Trainer
#from detectron2.engine import DefaultTrainer
# select from modelzoo here: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-object-detection-baselines

from detectron2.config import get_cfg
from detectron2.evaluation.coco_evaluation import COCOEvaluator
import os

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("Fishes_train",)
cfg.DATASETS.TEST = ("Fishes_test",)

cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.001

cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.MAX_ITER = 500 #adjust up if val mAP is still rising, adjust down if overfit
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.05

cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4 # your number of classes + 1

cfg.TEST.EVAL_PERIOD = 500

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = CocoTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```

3. Error presented after executing the previous code:

````
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-0a2b8e641cd2> in <module>()
     28 
     29 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
---> 30 trainer = CocoTrainer(cfg)
     31 trainer.resume_or_load(resume=False)
     32 trainer.train()

12 frames
/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 207 column 9 (char 4731)
````
4. Expected behavior:
The training will run for a while and print out evolution of metrics like mAP on our validation set. 

5. Dependencies of the Colab execution environment:
```
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install cython pyyaml==5.1
!pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())
!gcc --version
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html

```
Please check the link for more details: [How to Train Detectron2 on Custom Object Detection Data](https://towardsdatascience.com/how-to-train-detectron2-on-custom-object-detection-data-be9d1c233e4)

**Comment by morganOliveira2018** [comment]
@alexriedel1 or @ppwwyyxx could you help me with any suggestions?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by morganOliveira2018** [comment]
I tried to adapt the question better, could you help me @ppwwyyxx?

**Comment by ppwwyyxx** [comment]
Please show full logs as the issue template asks for. There are 12 frames omitted.

**Comment by morganOliveira2018** [comment]
@ppwwyyxx Where are these full logs? how can i identify?

**Comment by morganOliveira2018** [comment]
@lhoestq and @JainSahit Would you help me? Note that a similar issue has been resolved in [#751](https://github.com/huggingface/datasets/issues/751)

**Comment by alexriedel1** [comment]
DId you already try what they did in https://github.com/huggingface/datasets/issues/751 ? Did you check your dataset for wrong formatting as the error actually says ?

**Comment by morganOliveira2018** [comment]
How do I clear the cache as I suggested in # 715? Can you tell?

>

**Comment by lhoestq** [comment]
Hi ! If you're using the `datasets` library then the cache is by default located at `~/.cache/huggingface/datasets`
The `JSONDecodeError` you're having suggests that the file is corrupted, by clearing the cache and loading the dataset again it should fix your issue

**Comment by geep33** [comment]
Wtf that does 0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by morganOliveira2018** [comment]
@lhoestq Thanks! Can you tell if there is any version of detectron2 that I can segment instances and check evolution of mAP metrics?

**Comment by ppwwyyxx** [comment]
> Where are these full logs? how can i identify?

Your IDE or whatever programming environment must have hidden them. How to correctly obtain logs is not related to this project and not something we support.

**Comment by alexriedel1** [comment]
> @alexriedel1 @lhoestq Thanks! Can you tell if there is any version of detectron2 that I can segment instances and check evolution of mAP metrics?

You should probably check the Semantic Segmentation Evaluator https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.SemSegEvaluator

**Comment by morganOliveira2018** [comment]
> > Onde estão esses logs completos? como posso identificar?
> 
> Seu IDE ou qualquer ambiente de programação deve tê-los ocultado. Como obter logs corretamente não está relacionado a este projeto e não é algo que apoiamos.

Okay, sorry for the type of question then.
