### ISSUE TITLE
mAP is zero after 15000 maximum iterations

### ISSUE THREAD

**Issue by Atul997** [facebookresearch/detectron2#2343]
I am training an object detection model to detect some specific types of layouts in documents and using  `faster_rcnn_X_101_32x8d_FPN_3x.yaml` for training the model. The maximum number of iterations for training is 15000 but mAP is still zero or very less. Below are my training steps - 

    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
    cfg.DATASETS.TRAIN = ("layout_train",)
    cfg.DATASETS.TEST = ("layout_val",)

    cfg.DATALOADER.NUM_WORKERS = 1
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")  # Let 
    training initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 1
    cfg.SOLVER.BASE_LR = 0.00025

    cfg.SOLVER.WARMUP_ITERS = 10
    cfg.SOLVER.MAX_ITER = 15000 #adjust up if val mAP is still rising, adjust down if overfit
    cfg.SOLVER.STEPS = (100, 150)
    cfg.SOLVER.GAMMA = 0.02
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 2
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 5 #number of classes + 1
    cfg.TEST.EVAL_PERIOD = 500
    model = build_model(cfg)
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    checkpointer = DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
    checkpointer = DetectionCheckpointer(model, save_dir="output")
    checkpointer = PeriodicCheckpointer(checkpointer, period=500,max_iter = 100)
    checkpointer.save("model")
    trainer = CocoTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()

and these the metrics that I got at every step- 
    
    Evaluate annotation type *bbox*
    COCOeval_opt.evaluate() finished in 0.06 seconds.
    Accumulating evaluation results...
    COCOeval_opt.accumulate() finished in 0.01 seconds.
    Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
    Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.001
    Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
    Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
    Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
    Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.001
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.001
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
    Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
    Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
    Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
    [12/03 09:50:45 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
    |  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
    |:-----:|:------:|:------:|:-----:|:-----:|:-----:|
    | 0.041 | 0.079  | 0.026  | 0.000 | 0.165 | 0.036 |
    [ 12/03 09:50:45 d2.evaluation.coco_evaluation]: Per-category bbox AP: 
    | category   | AP    | category   | AP    | category   | AP    |
    |:-----------|:------|:-----------|:------|:-----------|:------|
    | figure     | 0.107 | text       | 0.099 | title      | 0.000 |
    | list       | 0.000 | table_form | 0.000 |            |       |

What I am doing wrong here, please let me know and suggest needful steps.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
