### ISSUE TITLE
Can't get the outline of each object, I need your help. In the documentation, the answer is incorrect.

### ISSUE THREAD

**Issue by ScantyDaemon** [facebookresearch/detectron2#2345]
Good afternoon, my question is how can I get the outline of each object. The documentation says: “pred_masks”: a Tensor of shape (N, H, W), masks for each detected instance. 
In practice, I only get an array of False.

But if I output the self-mask from the Visualizer function, I get a normal data array from which I can take the contour I need.

Should it be so? And how do I get the outline of each object? I **did not find** an answer in the documentation.

```
cfg = get_cfg()
cfg.MODEL.DEVICE=("cpu")
cfg.merge_from_file("../configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.MODEL.WEIGHTS = "detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl"

predictor = DefaultPredictor(cfg)
im = cv2.imread("1.png")
outputs = predictor(im)
class_names = MetadataCatalog.get(cfg.DATASETS.TRAIN[0]).stuff_classes
print(np.array(outputs["instances"].pred_masks)) #return array where only 'False'
```

The array after executing my code looks like this:
`[False False False ... False False False] [False False False ... False False False] [False False False ... False False False] [False False False ... False False False]...`

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

> how do I get the outline of each object

Detectron2 predicts masks, not the "outline" - whatever the word means. You can write code using libraries like opencv to process the masks into other formats.

> The array after executing my code looks like this:
[False False False ... False False False] [False False False ... False False False] [False False False ... False False False] [False False False ... False False False]...

This does not show that the array is "an array of False." It only shows the array contains many False.

**Comment by ScantyDaemon** [comment]
Thank you very much for your help. I wrote a new script. Now I can display the mask of each found object in a separate file. Everything worked out!
 
```
   outputs = predictor(im)
    s=np.array(outputs["sem_seg"])
    s=(s.astype(int))
    print(s)
    s=(np.where(s>=1, 255, s))
    acount=0
    for yi in s:
        cv2.imwrite(str(acount)+'maske.jpg', yi)
        acount+=1
```
