### ISSUE TITLE
How to save a trained model with a custom dataset and how to use it in demo.py

### ISSUE THREAD

**Issue by YuyaOkubo** [facebookresearch/detectron2#2346]
Hello.
https://detectron2.readthedocs.io/tutorials/models.html
I looked at the above site to see how to save and load the model, but I didn't know how to use it. Also, how can I use the trained models in demo.py?

from detectron2.utils.logger import setup_logger
setup_logger()

import matplotlib.pyplot as plt
import numpy as np
import cv2

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.data.datasets import register_coco_instances

register_coco_instances("animals_dataset", {}, "/home/nagalab/labelme/examples/instance_segmentation/aaaa/annotations.json", "/home/nagalab/labelme/examples/instance_segmentation/aaaa")
animals_metadata = MetadataCatalog.get("animals_dataset")
dataset_dicts = DatasetCatalog.get("animals_dataset")

import os
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer

cfg = get_cfg()
model = build_model(cfg)
cfg.merge_from_file("/home/nagalab/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_DC5_3x.yaml")
cfg.DATASETS.TRAIN = ("animals_dataset",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_DC5_3x/137849551/model_final_84107b.pkl"
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.0025
cfg.SOLVER.MAX_ITER = 600
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

**Comment by ppwwyyxx** [comment]
The official tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 has gone through the basics.
