### ISSUE TITLE
Error while evaluating Trident

### ISSUE THREAD

**Issue by vishaldhull09** [facebookresearch/detectron2#2347]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

python projects/TridentNet/train_net.py --config-file projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml --num-gpus 2 --resume --eval-only MODEL.WEIGHTS output/model_final.pth

Base config file:
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_trident_resnet_backbone"
  ROI_HEADS:
    NAME: "TridentRes5ROIHeads"
    POSITIVE_FRACTION: 0.5
    BATCH_SIZE_PER_IMAGE: 128
    PROPOSAL_APPEND_GT: False
  PROPOSAL_GENERATOR:
    NAME: "TridentRPN"
  RPN:
    POST_NMS_TOPK_TRAIN: 500
  TRIDENT:
    NUM_BRANCH: 3
    BRANCH_DILATIONS: [1,2,3]
    TEST_BRANCH_IDX: 1
    TRIDENT_STAGE: "res4"
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 120000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2

## Expected behavior:
testing should work fine 

## Error
[12/04 12:36:11 d2.data.common]: Serializing 1575 elements to byte tensors and concatenating them all ...
[12/04 12:36:11 d2.data.common]: Serialized dataset takes 5.92 MiB

Traceback (most recent call last):
  File "projects/TridentNet/train_net.py", line 76, in <module>
    args=(args,),
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/detectron2/engine/launch.py", line 54, in launch
    daemon=False,
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/detectron2/engine/launch.py", line 89, in _distributed_worker
    main_func(*args)
  File "/home/payal/Desktop/detec2/projects/TridentNet/train_net.py", line 59, in main
    res = Trainer.test(cfg, model)
  File "/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 510, in test
    evaluator = cls.build_evaluator(cfg, dataset_name)
  File "/home/payal/Desktop/detec2/projects/TridentNet/train_net.py", line 33, in build_evaluator
    return COCOEvaluator(dataset_name, output_dir=output_folder)
TypeError: __init__() missing 2 required positional arguments: 'cfg' and 'distributed'

## Environment:
[12/04 12:35:34 detectron2]: Environment info:
------------------------  ------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
numpy                     1.19.2
detectron2                0.1.3 @/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.1+cu101 @/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1                   TITAN Xp
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 9.2, V9.2.148
Pillow                    8.0.1
torchvision               0.6.1+cu101 @/home/payal/anaconda3/envs/edge/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                    0.1.2.post20201122
cv2                       4.4.0

```
```

**Comment by ppwwyyxx** [comment]
Please make sure the library is not older than where the example code is take nfrom.
You're using TridentNet taken from the latest github master but an older detectron2 release.

**Comment by vishaldhull09** [comment]
> Please make sure the library is not older than where the example code is take nfrom.
> You're using TridentNet taken from the latest github master but an older detectron2 release.

but i used the following commmand

git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2

am i missing anything??

**Comment by ppwwyyxx** [comment]
The error says:
> return COCOEvaluator(dataset_name, output_dir=output_folder)
TypeError: init() missing 2 required positional arguments: 'cfg' and 'distributed'


the latest code on github don't actually require these arguments: https://github.com/facebookresearch/detectron2/blob/0263797634b79208414db202b9f8e1343181412c/detectron2/evaluation/coco_evaluation.py#L41-L46

**Comment by vishaldhull09** [comment]
> The error says:
> 
> > return COCOEvaluator(dataset_name, output_dir=output_folder)
> > TypeError: init() missing 2 required positional arguments: 'cfg' and 'distributed'
> 
> the latest code on github don't actually require these arguments:
> 
> https://github.com/facebookresearch/detectron2/blob/0263797634b79208414db202b9f8e1343181412c/detectron2/evaluation/coco_evaluation.py#L41-L46

ok thanks there was issue with local installation and system wide. I got it
