### ISSUE TITLE
Pointrend：why not update maskloss and only update maskpointloss？

### ISSUE THREAD

**Issue by RuohGuo** [facebookresearch/detectron2#2350]
Hello，Pointrend：why not update maskloss and only update maskpointloss？thanks！

**Comment by ppwwyyxx** [comment]
Please explain what it means to "update maskloss" and "update maskpointloss"

**Comment by RuohGuo** [comment]
Sorry, I've got it. But I have a new question. When I added the pointrend module to blendmask, I found that the mask loss of blendmask was falling more slowly and get worse segmentation accuracy. 
1.blendmask to train:89.2%
2.blendmask and pointrend to train, only blendmask to predict:89.0%
3.blendmask and pointrend to train, blendmask and pointrend to predict:88.5%
Do you know why? I would appreciate it if you could let me know. Thanks！

**Comment by ppwwyyxx** [comment]
This is not among the [types of issues](https://github.com/facebookresearch/detectron2/issues/new/choose) we answer.
