### ISSUE TITLE
Evaluating Cityscape model

### ISSUE THREAD

**Issue by slulura** [facebookresearch/detectron2#2352]
When i run this command 

>python tools/train_net.py --eval-only --config-file configs/Cityscapes/mask_rcnn_R_50_FPN.yaml MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/Cityscapes/mask_rcnn_R_50_FPN/142423278/model_final_af9cf5.pkl

I get this error 

>/detectron2/detectron2/config/config.py", line 30, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file 'configs/Cityscapes/mask_rcnn_R_50_FPN.yaml' does not exist!

**Comment by ppwwyyxx** [comment]
Please make sure the file you use exists. 
It's at https://github.com/facebookresearch/detectron2/tree/master/configs/Cityscapes
