### ISSUE TITLE
assert len(class_names) == precisions.shape[2]

### ISSUE THREAD

**Issue by jakeum** [facebookresearch/detectron2#2354]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
my original class has 4 classes but I want to change it to 3 classes
2. what outputs you are expecting:
 assert len(class_names) == precisions.shape[2]

my question is which part of code they dicide the shape of precisions.shape[2]???

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
