### ISSUE TITLE
How to get input and output tensor names and input dimensions for caffe2 model

### ISSUE THREAD

**Issue by tejasshah2227** [facebookresearch/detectron2#2357]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

Code: 

The following code gives the output and I want the input tensor and input dims as well. Is there any changes required

from caffe2.python import workspace
import numpy as np
from detectron2.export import Caffe2Model
import torch 

print(torch.__version__)

import cv2
img = cv2.imread('test.png')
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
data = {'image': image, 'height': image.shape[1], 'width': image.shape[2]}
caffe2_model = Caffe2Model.load_protobuf('.')
output  = caffe2_model([data])
print('\nOuput:\n',output)

NOTE:

print(torch.__version__)
print ("Creating random data")
data = np.random.rand(3, 2)
#print(data)
print ("Adding data to workspace ...")
workspace.FeedBlob("mydata", data)
print ("Retrieving data from workspace")
mydata = workspace.FetchBlob("mydata")
#print(mydata)

import cv2
img = cv2.imread('test.png')
image = torch.as_tensor(img.astype("float32").transpose(2, 0, 1))
data = {'image': image, 'height': image.shape[1], 'width': image.shape[2]}
caffe2_model = Caffe2Model.load_protobuf('.')
output  = caffe2_model([data])
print('\nOuput:\n',output)

**Comment by ppwwyyxx** [comment]
I may have misunderstood the question, but inputs are provided by users, therefore users already have information about input tensor and their dimensions.
