### ISSUE TITLE
Getting Weird Results for 0.3 Version of Detectron 2

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/detectron2#2362]
Do you know what is the reason for the discrepancy in results I get from running the Jupyter notebook locally vs on Google colab? I don't understand how I can fix it. I have PyTorch 1.6 and Ubuntu 20.04.

local results: 
![local_results](https://user-images.githubusercontent.com/1892917/101551828-b4b01300-397f-11eb-8764-474f0301c8a0.png)

[colab results](https://colab.research.google.com/drive/1QIoL2g0jdt5E-vYKCIojkIz21j3jyEvo?usp=sharing): 
![colab_results](https://user-images.githubusercontent.com/1892917/101551848-baa5f400-397f-11eb-9be6-f5df05ed0068.png)

I have:
```
(base) mona@mona:~/research/phosa$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.6.0'
>>> import detectron2
>>> detectron2.__version__
'0.3'
>>> import neural_renderer as nr
>>> nr.__version__
'1.1.3'


```

Please also have a look here for link to PHOSA: https://github.com/facebookresearch/phosa/issues/15

## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
```
(base) mona@mona:~/research/phosa/external/detectron2$ git rev-parse HEAD; git diff
d06fd8521d90241f7c37a24e726d514a075b680d
```





## Environment:

```
$ wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
----------------------  -------------------------------------------------------------------
sys.platform            linux
Python                  3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy                   1.18.5
detectron2              0.3 @/home/mona/anaconda3/lib/python3.7/site-packages/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/home/mona/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce RTX 2070 (arch=7.5)
CUDA_HOME               /usr
Pillow                  7.2.0
torchvision             0.7.0 @/home/mona/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201204
cv2                     3.4.9
----------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/phosa/issues/15
