### ISSUE TITLE
Why sigmoid_focal_loss_jit and sigmoid_focal_loss yield different loss value and grad？

### ISSUE THREAD

**Issue by GeoffreyChen777** [facebookresearch/detectron2#2363]
## Expected behavior:

The loss and grad of pure `sigmoid_focal_loss` and `sigmoid_focal_loss_jit`, What's the reason?

I use totally same model, same init weight, same inputs.

Thanks!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
