### ISSUE TITLE
How to run caffe2_mask_rcnn executable

### ISSUE THREAD

**Issue by tejasshah2227** [facebookresearch/detectron2#2369]
## ❓ How to do something using detectron2

Describe what you want to do, including:
I was able to convert the detectron model from Pytorch to Caffe2 using the [documentation](https://detectron2.readthedocs.io/tutorials/deployment.html)

As per the [README](https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/README.md), I am trying to run the executable for the C++ Application but couldn't find one.

Where do we find the executable to run the following commands ?

./caffe2_mask_rcnn --predict_net=output/model.pb --init_net=output/model_init.pb --input=input.jpg

./torchscript_traced_mask_rcnn output/model.ts input.jpg

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/README.md#build produces the executable in the build directory.
