### ISSUE TITLE
cuda runtime error (710) : device-side assert

### ISSUE THREAD

**Issue by huangfeng95** [facebookresearch/detectron2#2373]
I am trying to do object detection on the custom dataset using detectron2.
I had the same problem with #2365 ,and made the changes as [2bf306d](https://github.com/facebookresearch/detectron2/commit/2bf306d63c6f1029130bd52aefbd23071709b272) do, but could not find my invalid classes.
Here is my log.txt, hope it will help to find my problem.
[log.txt](https://github.com/facebookresearch/detectron2/files/5676898/log.txt)

**Comment by ppwwyyxx** [comment]
As the environment info shows the CUDA version of detectron2 does not match pytorch's. https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

The error suggests the same cause as #2365. You can add checks such as in 2bf306d63c6f1029130bd52aefbd23071709b272 to find errors in the dataset.
If this does not help, we can only further investigate with instructions to reproduce the error.

**Comment by huangfeng95** [comment]
@ppwwyyxx Thank you for your answer, but it seems that after I change the configuration I still encounter this problem, can you give me some hints so that I can continue to modify.
Here is my latest log.txt
[log.txt](https://github.com/facebookresearch/detectron2/files/5679638/log.txt)

**Comment by ppwwyyxx** [comment]
If this does not help, we can only further investigate with instructions to reproduce the error.

**Comment by betegon** [comment]
@huangfeng95  I have faced this problem before. Here  Here are the 2 things causing that could 
1. Having category
