### ISSUE TITLE
Using trained model on tensorflow js

### ISSUE THREAD

**Issue by FahriBilici** [facebookresearch/detectron2#2377]
Hello, I trained a model using my custom dataset and I want to use that on to web application. Is there a way convert into tensorflow js or use that on nodejs or something?

**Comment by ppwwyyxx** [comment]
I'm not aware of such a way. Some other projects can convert a few models to tf format: https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN/convert_d2
