### ISSUE TITLE
What happens if len(SIZES) == 1 in RPN?

### ISSUE THREAD

**Issue by Mstfakts** [facebookresearch/detectron2#2382]
Hello,
Even though I have checked the documentation for several times, I am still confused about what is happening if I set the 
- `MODEL.ANCHOR_GENERATOR.SIZES = [[32, 64, 128, 256, 512]]` (It has length of 1)
--or--
- `MODEL.ANCHOR_GENERATOR.SIZES = [[32], [64], [128], [256], [512]]` (It has length of 5).

In the config>defaults.py (or[ here line 173](https://detectron2.readthedocs.io/modules/config.html?highlight=%5B%5B32%2C%2064%2C%20128%2C%20256%2C%20512%5D%5D#config-references)), It says that _"len(SIZES) == 1 is true and size list SIZES[0] is used for all IN_FEATURES."_ .

In my knowledge, each value of [[32], [64], [128], [256], [512]] corresponds to five levels of feature maps (P2 to P6) ( [Source](https://medium.com/@hirotoschwert/digging-into-detectron-2-part-4-3d1436f91266) ). For example, 32 (and its aspect ratio versions) corresponds to P2 level. However, if len(SIZES) == 1 (I mean this  [[32, 64, 128, 256, 512]]), then are all the sizes applied to each levels of feature maps?

**Comment by ppwwyyxx** [comment]
> then are all the sizes applied to each levels of feature maps?

yes

**Comment by Mstfakts** [comment]
- So, is it correct that if len(SIZES) == 5, each anchor sizes correspond to each level of the feature map, and if len(SIZES) == 1, all the sizes correspond to all the level of feature map?

- Is that true, len(SIZES) can not be other than 1 or 5.

- Also,  could you please clarify to me more how detectron2 does this? I mean, which methods are responsible for that, the documentation does not clearly mention this.

Thank you for your response. Regards.

**Comment by ppwwyyxx** [comment]
That's correct. It's done in 

https://github.com/facebookresearch/detectron2/blob/60d7a1fd33cc48e58968659cd3301f3300b2786b/detectron2/modeling/anchor_generator.py#L52
