### ISSUE TITLE
How to export trained model

### ISSUE THREAD

**Issue by FahriBilici** [facebookresearch/detectron2#2383]
Hello i check the docs and didnt understand how to export object detection model on onnx or caffe2 format. can someone explain to me?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/deployment.html

**Comment by FahriBilici** [comment]
i check that part too but it didnt explain well and also it throw me assertation error

**Comment by mewforest** [comment]
> https://detectron2.readthedocs.io/tutorials/deployment.html

Why official collab hasn't export part, it's a huge leak for newcomers.

**Comment by ppwwyyxx** [comment]
> Why official collab hasn't export part

Because Colab does not have pytorch 1.8, which is required for export.

**Comment by Mrgove10** [comment]
So there is no way to export when using detectron with pytorch 1.7 ?

**Comment by mewforest** [comment]
> > Why official collab hasn't export part
> 
> Because Colab does not have pytorch 1.8, which is required for export.

Currently `1.8.1` is a default version of Pytorch in Google Colab. Do you plan to add the export part to the official collab?
