### ISSUE TITLE
How to get Pytorch(.pth) version of the model

### ISSUE THREAD

**Issue by tejasshah2227** [facebookresearch/detectron2#2386]
## ❓ How to do something using detectron2

Hi, I have converted a Panoptic segmentation  model to Caffe2 and after visualizing it in Netron, it looks something like this:
![image](https://user-images.githubusercontent.com/75329515/102075562-5317fa80-3dfe-11eb-89cc-17d4e19076b1.png)

However, when I tried loading config and converting a pkl file to a pytorch file using  the code, I get an incorrect model. Visualization in netron:

![image](https://user-images.githubusercontent.com/75329515/102076047-084ab280-3dff-11eb-97bf-d1e4dd545e03.png)

Model to be converted: https://dl.fbaipublicfiles.com/detectron2/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl

The link to the used model is here, https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/panoptic_fpn_R_101_dconv_cascade_gn_3x.yaml

Code:

from detectron2.config import get_cfg
from detectron2 import model_zoo
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file('COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml'))
cfg.MODEL.DEVICE = "cpu"
#cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 # Set threshold for this model
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml") # Set path model .pth
#cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
#predictor = DefaultPredictor(cfg)

from detectron2.modeling import build_model
model = build_model(cfg)
print('\n\nModel', model)

from detectron2.checkpoint import DetectionCheckpointer
#DetectionCheckpointer(model).load(file_path_or_url)  # load a file, usually from cfg.MODEL.WEIGHTS
checkpointer = DetectionCheckpointer(model, save_dir="output")
checkpointer.save("model_999")  # save to output/model_999.pth

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work" for something you did, please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
> However, when I tried loading config and converting a pkl file to a pytorch file using the code, I get an incorrect model. Visualization in netron

It's working as expected because only weights are saved by the code above.

**Comment by tejasshah2227** [comment]
How do we freeze the weight in this case then ? Can you provide link/documentation for the same ?

**Comment by ppwwyyxx** [comment]
What do you mean by "freeze the weight"? please specify what inputs you will provide, and what outcome you expect to obtain

**Comment by tejasshah2227** [comment]
I want to freeze the layers and I am not sure how to do so for this specific detectron2 model.

I want to run this model across particular input dimensions. Attached an example of inception v3:
(https://pytorch.org/hub/pytorch_vision_inception_v3/)
![image](https://user-images.githubusercontent.com/75329515/102125705-fdfdd800-3e41-11eb-8eca-9ac7e6b86cb6.png)
