### ISSUE TITLE
Are images scaled between 0-255 after mean-std normalization?

### ISSUE THREAD

**Issue by FraPochetti** [facebookresearch/detectron2#2387]
Hi,
I cannot find this info anywhere so asking here, please.
Are images scaled between 0-255 after mean-std normalization (or at some point) by detectron2?

**Comment by ppwwyyxx** [comment]
It's up to the users to choose what values to scale the images. Usually they are not scaled to 0-255.

**Comment by FraPochetti** [comment]
> It's up to the users to choose what values to scale the images

Do you mean outside of Detectron (as part of an independent pipeline) or is it possible to achieve the scaling with some parameter in the config?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/issues/2298

**Comment by FraPochetti** [comment]
Thanks a lot
