### ISSUE TITLE
Export model as onnx/caffe2 format

### ISSUE THREAD

**Issue by FahriBilici** [facebookresearch/detectron2#2388]
I need to open this issue again because my previous issue closed without good explanation. I couldnt export model as caffe2 or onnx. it gives me assertation error and i didnt understand that. How can i export my model with custom dataset trained detectron2 as onnx format? Please just dont send me docs links because i already checked that

**Comment by ppwwyyxx** [comment]
> it gives me assertation error and i didnt understand that

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by FahriBilici** [comment]
I will post detailed error on that post but can you explain how you are exporting detectron models? can you do it right now? documentation not clear about this

**Comment by ppwwyyxx** [comment]
Running the exact command in https://detectron2.readthedocs.io/tutorials/deployment.html#id2 exports the example model.

**Comment by FahriBilici** [comment]
can i use this command for my custom trained dataset? because my model is .pth file not pkl

**Comment by ppwwyyxx** [comment]
Immediately after the command, the tutorials says:
> The conversion needs valid weights & sample inputs to trace the model. That’s why the script requires the dataset. You can modify the script to obtain sample inputs in other ways.
