### ISSUE TITLE
How to pretrain different modules of Faster R-CNN on different weights

### ISSUE THREAD

**Issue by jah3xc** [facebookresearch/detectron2#2389]
## ❓ How to do something using detectron2

I know that Faster R-CNN are composed of 
1. A feature extractor usually convolutional
2. A region proposal network (RPN)
3. A detector that combines the visual features from (1) and the proposed regions from (2), which is Fast R-CNN 

If I have a set of weights for some backbone / feature extractor and a DIFFERENT set of weights for the RPN, how can I initialize the feature extractor with a set of weights from one file, the RPN with a set of weights from a different file, and then randomly initialize the Fast R-CNN?

**Comment by ppwwyyxx** [comment]
You can use `torch.load/torch.save` to create a single file with both weights, and load this file.
