### ISSUE TITLE
PanopticFCN onnx export not supported?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#2391]
```
detectron2/detectron2/export/api.py", line 95, in _get_traceable
    C2MetaArch = META_ARCH_CAFFE2_EXPORT_TYPE_MAP[self.cfg.MODEL.META_ARCHITECTURE]
KeyError: 'PanopticFCN'

```

Hi, is that PanopticFCN arch model will supported in ONNX export?

**Comment by jinfagang** [comment]
Oh, it seems this is a decent arch different then PanopticFPN.

Does there any straight way for custom model exportation not using caffe2_converter.py?

**Comment by ppwwyyxx** [comment]
What export methods are supported depend on the model architecture. Since the "PanopticFCN" architecture is not in this project we cannot answer this.
