### ISSUE TITLE
QAT on RetinaNet with Detectron2  

### ISSUE THREAD

**Issue by yayapa** [facebookresearch/detectron2#2395]
Hello everyone, 
I managed to train the already configured RetinaNet (retinanet_R_50_FPN_1x.yaml) on my own dataset (I created the special annotations in coco format for my dataset), as it was explained in the tutorials. It worked great, thanks.

 My next step is trying to quantize the same configuration of retinanet using PyTorch. I would like to use QAT (https://pytorch.org/docs/stable/quantization.html). As I understood, I need to do 3 main steps 1)insert QuantStub() and DequantStub() in the end and beginning of the Network in __init__ 2) the same in forward() 3) fuse the modules(the layers inside). 
What is the best practice for that in detectron2? Should I implement the existing interface (https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/retinanet.py) and then completely rewrite the whole net inserting these Dequant and Quant stubs. Then, where can I take the implementations of this net, so as not to break something? Is the any way not to rewrite, but to add new layers(Quant/DequantSubs) at the beginning/end of the net? So, I would like to know how could I start? Unfortunately I was not able to find any examples or documentation (e.g. here: https://detectron2.readthedocs.io/tutorials/write-models.html)

EDIT: I tried to register and then implement the RetinaNet, in order to quantize first only the backbone, namely only 2 first layers of FPN and got an error:
 NotImplementedError: Cannot fuse modules: (<class 'detectron2.layers.wrappers.Conv2d'>, <class 'detectron2.layers.wrappers.Conv2d'>)
Does it mean that I need to reimplement(rewrite) even Layers?

Thank you in advance for any info.
Best regards, 
yayapa

**Comment by ppwwyyxx** [comment]
Closing in favor of https://discuss.pytorch.org/t/qat-runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least-two-devices-cuda-0-and-cpu/106727/3
