### ISSUE TITLE
g++ error found during installation

### ISSUE THREAD

**Issue by lmw0320** [facebookresearch/detectron2#2399]
I met a new problem as below during running the command：
`git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2`

![1](https://user-images.githubusercontent.com/37755235/102588198-0444ca80-4148-11eb-9a96-5d71e0d5e9fa.png)
![2](https://user-images.githubusercontent.com/37755235/102588214-0a3aab80-4148-11eb-8978-fe1c662400fd.png)

My base environments are as follows:
Ubuntu18.04, py3.6.5, cuda10.1, pytorch 1.6.0+cu101, opencv 3.4.2.17

1. I have pre-installed the detectron2  by the instruction of Install Pre-Built Detectron2 (Linux only), and it seems installed successfully. And I have run the import command, no errors found.  Unfortunately, When I install the ABCnet, a problem found. Then I thought the detectron2 havn't installed correctly.
2.  I uninstall the pre-install version, and redo the installation by the official steps, the  error occur which is same as the problem found during installing the ABCnet。。 
So I came here for help...Hope someone can tell me the reason..

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by lmw0320** [comment]
> If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

I have almost following the instruction as your request:
1. the exact command I have run. ---For I did not change anything, the full code is no need to paste.
2. The snapshot of log have been shown in the question.
3. My base environment also have been described. And I also described my actions done before.
So could you tell me which part I missed，but not just write the word to ask me  to following the Unexpected behaviors issue template....

**Comment by ppwwyyxx** [comment]
- The logs are not complete.
- The environment info should be produced by the following command, as the issue template says:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

**Comment by ppwwyyxx** [comment]
Requested information was not provided in 7 days, so we're closing this issue.
