### ISSUE TITLE
transfer model trained by Detectron and maskrcnn-benchmark

### ISSUE THREAD

**Issue by hyliu-deepnorth** [facebookresearch/detectron2#24]
## ❓ Questions and Help

How to transfer the Detectron and maskrcnn-benchmark model to Detectron2 framework?
Do I need to retrain them with Detectron2?

**Comment by ppwwyyxx** [comment]
See https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-detectron.
maskrcnn-benchmark models are compatible with Detectron, therefore the above link also applies.
