### ISSUE TITLE
Is it possible to make the Colab create a 3D model from a single image of a whale?

### ISSUE THREAD

**Issue by hmatt843** [facebookresearch/detectron2#2400]
Hi,
I went through a Colab example (PHOSA Colab https://colab.research.google.com/drive/1QIoL2g0jdt5E-vYKCIojkIz21j3jyEvo?usp=sharing ) without having issues. But when I tried to change it to a whale jpg (https://bdmlr.org.uk/wp-content/uploads/2020/01/animal-humpback_whale.png) it failed out on several code blocks.
Is what I'm trying to do (get a 3D model through the Colab) not possible with Detectron2 technology?

**Comment by ppwwyyxx** [comment]
PHOSA is a different project. Unless the question is particularly about detectron2 we cannot answer it here.
