### ISSUE TITLE
Why the mAP of detectron2 is higher than detectron

### ISSUE THREAD

**Issue by Chrisfsj2051** [facebookresearch/detectron2#2403]
Hi! Currently I'm learning how to use detectron2, while I found that the mAP result of some model in detectron2 is quite higher than the same model of detection. For example, the mAP of FRCNN-FPN 1x on COCO is 36.7 in detection and 37.9 in detectron2, what might be the reason?

detectron2 results: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

detectron results: https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md

**Comment by ppwwyyxx** [comment]
answered in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#common-settings-for-coco-models
