### ISSUE TITLE
dataset is not registered error while exporting model as caffe2 model

### ISSUE THREAD

**Issue by FahriBilici** [facebookresearch/detectron2#2404]
Hi, I trained my model with a custom coco dataset. For using caffe2_converter script I cloned GitHub repo and using in Colab. I am checking `DatasetCatalog.list()` and my dataset in there but it seems the script is not seeing that DatasetCatalog. How can I fix that?

**Comment by ppwwyyxx** [comment]
This is how Colab works. Code in Colab cells do not affect code written in scripts.
