### ISSUE TITLE
Instance Segmentation masks

### ISSUE THREAD

**Issue by Oyla-Inc** [facebookresearch/detectron2#2405]
## ❓ How to do something using detectron2

in readdocs two methods of specifying segmentation/annotation
list[list[float]] or dict
But in code `detections_utils.py`

> Supported types are: polygons as list[list[float] or ndarray],"
                        " COCO-style RLE as a dict, or a full-image segmentation mask "
                        "as a 2D ndarray

I am not clear about the 2D ndarray input in particular what does "full-image" segementaion mask mean? Are the dimensions of the mask == dimensions of image or dimensions of the polygon? Also can entries be float/int or have to be binary?

**Comment by ppwwyyxx** [comment]
It has to be a binary mask of shape (H, W). We'll clarify it.
