### ISSUE TITLE
how to use two backbones for feature extraction simulnateously before feeding to a region proposal network in one MRCNN using Detectron2

### ISSUE THREAD

**Issue by zunairaR** [facebookresearch/detectron2#2407]
What if I want to use two backbones like resnet50 and resnet101 for feature extraction and then concatenating their features before feeding these features to RPN. But both of these backbones should be used simultaneously. When i feed an input image, it goes to backbone1 and backbone2 simultaneously. Can anyone please guide me how I can change config and rcnn.py files.

**Comment by zunairaR** [comment]
Author of this issue [https://github.com/facebookresearch/detectron2/issues/1276#issuecomment-619270752](url) may help

**Comment by zunairaR** [comment]
@SupreethN Can you help?

**Comment by ppwwyyxx** [comment]
You need to implement such a model with pytorch. See for example https://detectron2.readthedocs.io/tutorials/write-models.html

**Comment by zunairaR** [comment]
So I need to create new backbone or should i change the metaarchitecture. As I want to train multiple backbones at a time, concatenating feature maps from multiple backbones (Resnets).
