### ISSUE TITLE
Question about the dimension of the keypoint detection output.

### ISSUE THREAD

**Issue by AminAnsarian** [facebookresearch/detectron2#2412]
I am working on the pose estimation module of detectron2. 
When predicting on a sample and getting this output:

`
outputs = predictor(I'm)
`
`
outputs = outputs["instances"].pred_keypoints.to("cpu")
`
The result is a 17x3 array. why is it 3 if it is 2D keypoint detection? what is the last value per joint?

Thank you.

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
