### ISSUE TITLE
How can predict any image not included in test_metadata?

### ISSUE THREAD

**Issue by metempasa** [facebookresearch/detectron2#2416]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1) Trained model
2) Any random image not in registered coco instance. Just any image like jpg,jpeg or png

## ❓ What does an API do and how to use it?

How can i predict boxes on any random image, i can just do it in test_metadata and when i choose any other image not included in metadata, label doesnt show up. How can i predict any random image with predictor?

**Comment by ppwwyyxx** [comment]
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
