### ISSUE TITLE
i have created a custom dataset with proper annotation but i am getting this error can anyone help ? what this error suugests i have go thrrough the link from which it was occurning but still i am not able to correct it 

### ISSUE THREAD

**Issue by mu745511** [facebookresearch/detectron2#2418]
TypeError Traceback (most recent call last)
in
1 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
----> 2 trainer = NFL_Trainer(cfg)
3 trainer.resume_or_load(resume=False)
4 trainer.train()

/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py in init(self, cfg)
282 model = self.build_model(cfg)
283 optimizer = self.build_optimizer(cfg, model)
--> 284 data_loader = self.build_train_loader(cfg)
285
286 # For training, wrap with DDP. But don't need this for inference.

/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py in build_train_loader(cls, cfg)
471 Overwrite it if you'd like a different data loader.
472 """
--> 473 return build_detection_train_loader(cfg)
474
475 @classmethod

/opt/conda/lib/python3.7/site-packages/detectron2/config/config.py in wrapped(*args, **kwargs)
199 def wrapped(*args, **kwargs):
200 if _called_with_cfg(*args, **kwargs):
--> 201 explicit_args = _get_args_from_config(from_config, *args, **kwargs)
202 return orig_func(**explicit_args)
203 else:

/opt/conda/lib/python3.7/site-packages/detectron2/config/config.py in _get_args_from_config(from_config_func, *args, **kwargs)
234 if name not in supported_arg_names:
235 extra_kwargs[name] = kwargs.pop(name)
--> 236 ret = from_config_func(*args, **kwargs)
237 # forward the other arguments to init
238 ret.update(extra_kwargs)

/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py in _train_loader_from_config(cfg, mapper, dataset, sampler)
307 if cfg.MODEL.KEYPOINT_ON
308 else 0,
--> 309 proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
310 )
311

/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py in get_detection_dataset_dicts(dataset_names, filter_empty, min_keypoints, proposal_files)
244 class_names = MetadataCatalog.get(dataset_names[0]).thing_classes
245 check_metadata_consistency("thing_classes", dataset_names)
--> 246 print_instances_class_histogram(dataset_dicts, class_names)
247 except AttributeError: # class names are not available for this dataset
248 pass

/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py in print_instances_class_histogram(dataset_dicts, class_names)
178
179 data = list(
--> 180 itertools.chain(*[[short_name(class_names[i]), int(v)] for i, v in enumerate(histogram)])
181 )
182 total_num_instances = sum(data[1::2])

/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py in (.0)
178
179 data = list(
--> 180 itertools.chain(*[[short_name(class_names[i]), int(v)] for i, v in enumerate(histogram)])
181 )
182 total_num_instances = sum(data[1::2])

/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py in short_name(x)
173 def short_name(x):
174 # make long class names shorter. useful for lvis
--> 175 if len(x) > 13:
176 return x[:11] + ".."
177 return x

TypeError: object of type 'int' has no len()

**Comment by mu745511** [comment]
i have a question i am assigning class name as integer ! i guess in detectron2 we need class name as a string name not integer am i right ??

**Comment by ppwwyyxx** [comment]
You're right: https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets
