### ISSUE TITLE
How to get sequence of predicted classes

### ISSUE THREAD

**Issue by programmer8396** [facebookresearch/detectron2#2420]
I got output of predicted bboxes and class indexes  **but I want the bbox in sequence same as in the image i.e. first bbox in the list must be first bbox in image  and so on**
current output is :
  
![Screenshot from 2020-12-26 17-51-17](https://user-images.githubusercontent.com/57538011/103151428-1526b900-47a4-11eb-8d06-540ba3ff9ad9.png)

As you can see in the screenshot the list of **pred_classes**  are  prediction class indexes.

predicted class indexes  -----  class labels
      4____________________17 
      6 ___________________ 19
      12 __________________  24
     10___________________ 23
    11 ___________________  25
   14 ___________________ 27
   19 ____________________503

![download (1)](https://user-images.githubusercontent.com/57538011/103151835-a77c8c00-47a7-11eb-82b4-6d74441c76c6.png)

I want to know to  how the bboxes are placed in the list, what are the things predictor search at first ?

**Comment by ppwwyyxx** [comment]
> I want to know to how the bboxes are placed in the list,

They are placed without any particular order.

**Comment by programmer8396** [comment]
Can you provide the solution that howcan i sort them from left to rigth and top to bottom

**Comment by ppwwyyxx** [comment]
If you can define how they should be sorted, they can be sorted by using python's sort function.
