### ISSUE TITLE
Detectron2 for instance segementation with custom data not in COCO format.

### ISSUE THREAD

**Issue by Paragjain10** [facebookresearch/detectron2#2427]
Hello,

I am trying to implement Centremask2 which uses detectron2 on my custom dataset which is not coco format.
 
1. I have a custom dataset that consists of original RGB images and the ground truth images with all the instances labeled both in png format.
2. In the documentation it said, giving the path of the full ground truth of the images directly also could work for instance segmentation. But turns out, when I try to visualize my data I cannot see the mask of the instances.
3. So, then I tried removing the X, Y coordinates of each instance in the image and stored them in a dict, and used them as polygon coordinates. And I did that using the following code snippet:
    
``` 
def my_dataset_function(img_dir):
          img_path = os.path.join(img_dir, "images")
          ann_path = os.path.join(img_dir, "Annotations")
          dataset_dicts = []
          for idx, v in enumerate(os.listdir(img_path)):
              record = {}
      
              filename = os.path.join(img_path, v)
              height, width = cv2.imread(filename).shape[:2]
              label = filename.replace("images", "Annotations").replace("rgb", "im")
              img = cv2.imread(label)
              plt.imshow(img)
              hist, bins = np.histogram(img.ravel(), 256, [0, 256])
              i = np.where(hist != 0)[0]
      
              allinstances = []
              for z in range(1, len(i)):
                 y = np.zeros(img.shape, dtype=int)
                  x = np.where(img == i[z])
                  y[x] = int(i[z])
                  y = y[::-1, :, ::-1]
                  y = Image.fromarray((y).astype(np.uint8))
                  y = ImageOps.grayscale(y)
                  counts = plt.contour(y, levels=[60], colours='black', origin='image')
                  p = counts.collections[0].get_paths()[0]
                  v = p.vertices
                  px = [c[0] for c in v]
                  py = [c[1] for c in v]
                  poly = [(x, y) for x, y in zip(px, py)]
                  poly = [p for x in poly for p in x]
                  instann = {}
      
      
      
                  instann["segementation"] = [poly]
                  instann["category_id"] = int(str((i[z]))[0]) - 1
                  instann["bbox"] = [np.min(px), np.min(py), np.max(px), np.max(py)]
                  instann["bbox_mode"] = BoxMode.XYXY_ABS
      
                  allinstances += [instann]
      
                  plt.close()
      
              record["file_name"] = filename
              record["image_id"] = idx
              record["height"] = height
              record["width"] = width
              record["annotations"] = allinstances
      
              dataset_dicts += [record]
        return dataset_dicts
```

3. Now while visualizing I can see a bbox for my instances but yet cannot see the mask.
4. While I try to train any network as well I get an error saying:
 raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!

Can you help me with this, Can you let me know if my understanding of the implementation is correct or no. What else can be done here?

**Comment by ppwwyyxx** [comment]
You may have mispelled "segmentation" as "segementation". 

In general we cannot help with such issue unless there is runnable code to reproduce it, following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by jaqub-manuel** [comment]
Hey Dear @ppwwyyxx,
I also have similar question,

I only have about 1000 RGB images and their ground truth images. There is no problem with training with Faster R-CNN, but when I try to do it with mask-rcnn, I get an error "Cannot find field 'gt_masks' in the given Instances". How can I register dataset with ground truth without json segmentation file? In other words, ground truth is sufficient with RGB images to do instance segmentation, or how can I do it.

Thanks a lot in advance.
