### ISSUE TITLE
how to get config file for densepose in colab

### ISSUE THREAD

**Issue by ak9250** [facebookresearch/detectron2#2428]
followed colab https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
 to this step

cfg = get_cfg()
# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)

how do you replace densepose yaml from here 
https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose/configs
for 
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
model zoo config for densepose isnt in the right directory to fetch?
and since this is pip installed cant move config file manually

**Comment by ppwwyyxx** [comment]
As the [documentation](https://detectron2.readthedocs.io/modules/model_zoo.html) says, the API does not include densepose configs.

You can clone the repo to access them.

**Comment by ak9250** [comment]
@ppwwyyxx when I try the build steps Directory cannot be installed in editable mode: /model/detectron2
