### ISSUE TITLE
Make an onnx_export mode for onnx exportable

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#243]
## 🚀 Feature

Currently, all modeling using a dict as input in forward function, which not support in onnx export, such as :

```
def forward(self, batched_inputs):
        """
        Args:
            batched_inputs: a list, batched outputs of :class:`DatasetMapper` .
                Each item in the list contains the inputs for one image.
                For now, each item in the list is a dict that contains:

                * image: Tensor, image in (C, H, W) format.
                * instances (optional): groundtruth :class:`Instances`
                * proposals (optional): :class:`Instances`, precomputed proposals.

                Other information that's included in the original dicts, such as:

                * "height", "width" (int): the output resolution of the model, used in inference.
                    See :meth:`postprocess` for details.

        Returns:
            list[dict]:
                Each dict is the output for one input image.
                The dict contains one key "instances" whose value is a :class:`Instances`.
                The :class:`Instances` object has the following keys:
                    "pred_boxes", "pred_classes", "scores", "pred_masks", "pred_keypoints"
        """
        if not self.training:
            return self.inference(batched_inputs)
```

When inference, the img_height and img_width actually doesn't needed since `self.inference` simply get `images` from dict.

Is that possible using an `onnx_export` mode take only image as input so that make it more onnx_export friendly? Or is there any more easier and clean to make it support onnx export?

**Comment by ppwwyyxx** [comment]
I don't think it's reasonable to have onnx mode, torchscript mode, tpu mode, just because each of these platforms have something they do not support.

It would be better if the conversion script to onnx handles various unsupported features there. This is how we currently use onnx to convert detectron2 models.

**Comment by jinfagang** [comment]
Doesn't finally conversion calls `torch.onnx.export`? this doesn't supports dict as input when tracing the model.

Many modes indeed breaks simplicity, does internal onnx export script will also opensource too?

**Comment by mlinxiang** [comment]
is any roadmap or pipeline for pytorch's or detectron2 model deployment online, now is very confuse about how to do these!!!!!   the future is onnx or torchscripts or other @ppwwyyxx

**Comment by ppwwyyxx** [comment]
The conversion can use `torch.onnx.export` on submodules instead of the out-most level model. We have plans to open source conversion scripts though there isn't a concrete timeline yet. We'll update in #8 instead, so closing this issue.
