### ISSUE TITLE
AssertionError: Dataset 'densepose_coco_2014_train' is already registered!

### ISSUE THREAD

**Issue by ak9250** [facebookresearch/detectron2#2430]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-e3cb0fa891ed> in <module>()
----> 1 from detectron2_repo.projects.DensePose.densepose.config import add_densepose_config
      2 from detectron2.engine import DefaultPredictor
      3 from detectron2.config import get_cfg
      4 
      5 cfg = get_cfg()

7 frames
/content/detectron2_repo/projects/DensePose/densepose/__init__.py in <module>()
      1 # Copyright (c) Facebook, Inc. and its affiliates.
----> 2 from .data.datasets import builtin  # just to register data
      3 from .converters import builtin as builtin_converters  # register converters
      4 from .config import (
      5     add_densepose_config,

/content/detectron2_repo/projects/DensePose/densepose/data/__init__.py in <module>()
      2 
      3 from .meshes import builtin
----> 4 from .build import (
      5     build_detection_test_loader,
      6     build_detection_train_loader,

/content/detectron2_repo/projects/DensePose/densepose/data/build.py in <module>()
     26 from .combined_loader import CombinedDataLoader, Loader
     27 from .dataset_mapper import DatasetMapper
---> 28 from .datasets.coco import DENSEPOSE_KEYS_WITHOUT_MASK as DENSEPOSE_COCO_KEYS_WITHOUT_MASK
     29 from .datasets.coco import DENSEPOSE_MASK_KEY as DENSEPOSE_COCO_MASK_KEY
     30 from .datasets.dataset_type import DatasetType

/content/detectron2_repo/projects/DensePose/densepose/data/datasets/__init__.py in <module>()
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 
----> 3 from . import builtin  # ensure the builtin datasets are registered
      4 
      5 __all__ = [k for k in globals().keys() if "builtin" not in k and not k.startswith("_")]

/content/detectron2_repo/projects/DensePose/densepose/data/datasets/builtin.py in <module>()
      8 
      9 
---> 10 register_coco_datasets(COCO_DATASETS, DEFAULT_DATASETS_ROOT)
     11 register_coco_datasets(BASE_COCO_DATASETS, DEFAULT_DATASETS_ROOT)
     12 

/content/detectron2_repo/projects/DensePose/densepose/data/datasets/coco.py in register_datasets(datasets_data, datasets_root)
    362     """
    363     for dataset_data in datasets_data:
--> 364         register_dataset(dataset_data, datasets_root)

/content/detectron2_repo/projects/DensePose/densepose/data/datasets/coco.py in register_dataset(dataset_data, datasets_root)
    341         )
    342 
--> 343     DatasetCatalog.register(dataset_data.name, load_annotations)
    344     MetadataCatalog.get(dataset_data.name).set(
    345         json_file=annotations_fpath,

/content/detectron2/detectron2/data/catalog.py in register(self, name, func)

AssertionError: Dataset 'densepose_coco_2014_train' is already registered!

I am getting this error after following this issue to run densepose in google colab

https://github.com/facebookresearch/detectron2/issues/258

using this

from detectron2_repo.projects.DensePose.densepose.config import add_densepose_config
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg

cfg = get_cfg()
add_densepose_config(cfg)
cfg.merge_from_file("./detectron2_repo/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x.yaml")
# Find a model from detectron2's model zoo. You can either use the https://dl.fbaipublicfiles.... url, or use the following shorthand

cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/143908701/model_final_dd99d2.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)

I first did 
!git clone https://github.com/facebookresearch/detectron2.git
!python -m pip install -e detectron2

and !pip install av

everything else is the same as in the colab other in cd into densepose dir

**Comment by ppwwyyxx** [comment]
The correct way is `from densepose.config import add_densepose_config`
