### ISSUE TITLE
How can I get the same color map and results as used by PHOSA repo?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/detectron2#2432]
The result that is shown in Google Colab of PHOSA repo linked here https://colab.research.google.com/drive/1QIoL2g0jdt5E-vYKCIojkIz21j3jyEvo?usp=sharing :

![Screenshot from 2020-12-29 18-18-17](https://user-images.githubusercontent.com/76495162/103320184-7055e700-4a02-11eb-9795-aaddb5c24659.png)

The result that I get running the Jupyter notebook locally:
![Screenshot from 2020-12-29 18-18-34](https://user-images.githubusercontent.com/76495162/103320228-88c60180-4a02-11eb-9c88-d7d5ecf67520.png)
```

$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import detectron2
>>> detectron2.__version__
'0.2'
>>> import torch
>>> torch.__version__
'1.7.1'
```

```
[37007:3298 0:1220] 06:22:33 Tue Dec 29 [mona@goku:pts/6 +1] ~/research/code/phosa-dawnlight
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any: getting different results
2. what outputs you are expecting: same exact results or better than PHOSA

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work" for something you did, please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by monacv** [comment]
ran it again and got a different color
![Uploading Screenshot from 2020-12-29 18-29-11.png…]()

**Comment by ppwwyyxx** [comment]
The color is random as expected. https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer
