### ISSUE TITLE
How to speed up DefaultPredictor on cpu

### ISSUE THREAD

**Issue by dhyaaalayed** [facebookresearch/detectron2#2435]
I made transform learning of the model_zoo X152 on my dataset which has A4 images to detect tables, but after I finished training on colab, I used the DefaultPredictor of this model on my cpu and it is very slow. It takes 6 seconds to process one image.
Is there anyway to speed up the prediction on the cpu? For example by changing something in the configuration or by using parallel programming like multithreading or any other way?

**Comment by ppwwyyxx** [comment]
The timing of 6 seconds is pretty reasonable for this model.
