### ISSUE TITLE
Cut&Mix & Mosaic dataaugmentation

### ISSUE THREAD

**Issue by Practical-AI** [facebookresearch/detectron2#2437]
I've been working with detectron2 for a while; I wanted to write a custom dataloader for cut&mix and mosaic augmentations. I used a custom mapper, as mentioned in [https://detectron2.readthedocs.io/tutorials/data_loading.html](https://detectron2.readthedocs.io/tutorials/data_loading.html).
There is a problem that the mapper takes a dataset_dict, which contains information for an image. It's not possible to implement the requested augmentation. 
How we can access more than one image in the mappers or build_detection_train_loader?

**Comment by ppwwyyxx** [comment]
It's up to you how to implement the mapper. 

For example, if it's implemented as a class, it can access attributes like `self.xxx`.

**Comment by mona0809** [comment]
I would like to use this augmentation as well. @Practical-AI would you share your code?
