### ISSUE TITLE
use transforms/data augmentations

### ISSUE THREAD

**Issue by doursand** [facebookresearch/detectron2#244]
Is there a way i can specific specific transforms and/or data augmentations for my training dataset (like in "regular" pytorch) ?

**Comment by ppwwyyxx** [comment]
I don't know what do you mean by "like in regular pytorch". You can change use custom transforms as part of your custom dataset mapper (https://detectron2.readthedocs.io/tutorials/data_loading.html).

**Comment by doursand** [comment]
excellent this is what i was looking for :-) thanks
