### ISSUE TITLE
multi-GPU not working

### ISSUE THREAD

**Issue by kimalaacer** [facebookresearch/detectron2#2449]
I tried: 
!export CUDA_VISIBLE_DEVICES=0,1,2,3 
!export NGPU=4 
!python -m torch.distributed.launch --nproc_per_node=4 ./tools/train_net.py \
--num-gpus 4 \
--config-file './configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml' \
--num-machines 1 \
#--machine-rank =0 \
--dist-url 'auto' \
--resume False \
--eval-only False\

but I am getting an error:  train_net.py: error: unrecognized arguments: --local_rank=0

it seems the torch is adding a --local_rank to the args.

_Originally posted by @kimalaacer in https://github.com/facebookresearch/detectron2/issues/2442#issuecomment-754256288_

**Comment by ppwwyyxx** [comment]
These are not the correct way to do multi-gpu training. Please see the example https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py on how to implement multi-gpu training. 
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
