### ISSUE TITLE
semantic segmantation training error

### ISSUE THREAD

**Issue by CF2220160244** [facebookresearch/detectron2#245]
How to train semantic segmantation only，
it seems the project no semantic segmantation only？

**Comment by ppwwyyxx** [comment]
It is supported but we haven't implemented many good models for it. There is only one small example at https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/semantic_R_50_FPN_1x.yaml.

**Comment by CF2220160244** [comment]
i find also find the semantic_R_50_FPN_1x.yaml，but there is not the trained final model in the https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md,
can you provide the final model?

**Comment by ppwwyyxx** [comment]
We have no plans to provide models for this config because it's not yet a standard/popular model for semantic segmentation.

**Comment by CF2220160244** [comment]
Do you mean the R_50_FPN in this project is not good as other popular sematic segmentation network?

**Comment by pvtien96** [comment]
@CF2220160244 Hey, did you successfully train your semantic segmentation model? I'm interested in.

**Comment by benkoger** [comment]
For semantic segmentation you may want to look at this implementation of DeepLab3/+ https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab

**Comment by ppwwyyxx** [comment]
As mentioned above, there are instructions in https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab and also https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend for semantic segmentation.
