### ISSUE TITLE
AssertionError: Checkpoint https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl not found!Please read & provide the following

### ISSUE THREAD

**Issue by Thanossrs** [facebookresearch/detectron2#2453]
1) Running below

#from .detectron2.tools.train_net import Trainer
#from detectron2.engine import DefaultTrainer
 #select from modelzoo here: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-object-detection-baselines

from detectron2.config import get_cfg
#from detectron2.evaluation.coco_evaluation import COCOEvaluator
import os

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("my_dataset_train",)
cfg.DATASETS.TEST = ("my_dataset_val",)

cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.001

cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.MAX_ITER = 1500 #adjust up if val mAP is still rising, adjust down if overfit
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.05

cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2 #your number of classes + 1

cfg.TEST.EVAL_PERIOD = 500

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = CocoTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

### **and 2) get the below error**

WARNING [01/06 11:01:46 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[01/06 11:01:46 d2.data.datasets.coco]: Loaded 106 images in COCO format from /content/train/_annotations.coco.json
[01/06 11:01:46 d2.data.build]: Removed 2 images with no usable annotations. 104 images left.
[01/06 11:01:46 d2.data.common]: Serializing 104 elements to byte tensors and concatenating them all ...
[01/06 11:01:46 d2.data.common]: Serialized dataset takes 0.03 MiB
[01/06 11:01:46 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[01/06 11:01:46 d2.data.build]: Using training sampler TrainingSampler
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-f8cfbee44079> in <module>()
     34 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
     35 trainer = CocoTrainer(cfg)
---> 36 trainer.resume_or_load(resume=False)
     37 trainer.train()

2 frames
/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py in load(self, path, checkpointables)
    118         if not os.path.isfile(path):
    119             path = self.path_manager.get_local_path(path)
--> 120             assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
    121 
    122         checkpoint = self._load_file(path)

AssertionError: Checkpoint https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl not found!

COULD SOMEONE PLEASE EXPLAIN TO ME WHY I GET THIS ERROR AND HOW I COULD FIX IT?

THANK YOU

**Comment by ppwwyyxx** [comment]
This should be fixed by https://github.com/facebookresearch/fvcore/commit/44e2a9fd496030a603c9ba778f21cd4f657fd457 now. Upgrading to latest version of detectron2 on github should also fix it.
