### ISSUE TITLE
'cuda out of memory' problem

### ISSUE THREAD

**Issue by bigbrotherwei** [facebookresearch/detectron2#2457]
l just pull docker image of detectron2 and use 
`./train_net.py \
  --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml   --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025`  to train, but l got this problem `cuda out of memory, tried to allocate 50MiB(GPU 0; 1.96GiB totalcapacity;1.33GiB already allocated; 43.5MiB free;1.36 GiB reserved in total by Pytorch)`

l tried to change the batch size to 1, but it still occured.  cuda version is 11.0 and torch version is 1.7.0+cua101. does anyone else have this problem ?

**Comment by ppwwyyxx** [comment]
Using >2G memory is expected, therefore closing.

**Comment by RSKothari** [comment]
@ppwwyyxx When I use `apply_net`, GPU memory consumption increases until after 100 images, it makes out my 12GB GPU and crashes. I tried adding cuda memory flush, but no effect :(

**Comment by a1596394** [comment]
Met the same problem here. I use the train_net.py which provide form the detectron2/tools and train the coco instance segmentation datasets got the same problem. Don't know if there have any solution?

**Comment by bigbrotherwei** [comment]
> Met the same problem here. I use the train_net.py which provide from the detectron2/tools and train the coco instance segmentation datasets got the same problem. Don't know if there have any solution?
> I have 8GB GPU and crashes at the beginning of training.

use another GPU with more memory is the most effective way, otherwise, try to reduce batch-size or img_size. if your config is in the lowest level and you still have this problem, l think change GPU is the only way.  my original GPU just has 2G memory , so l have no choice but to change a new GPU with 8G memory to solve this problem. good luck to you.
