### ISSUE TITLE
How to run trainer.train() inside of a loop

### ISSUE THREAD

**Issue by AceMcAwesome** [facebookresearch/detectron2#2459]
Hi, I would like to train inside of a loop so that I can run an evaluate after each 100 iterations are so, so that I can manually save my models by best validation accuracy.  My setup looks like this, adapted from one of the common tutorials:

  cfg = get_cfg()
  cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
  cfg.DATASETS.TRAIN = ("balloon_train",)
  cfg.DATASETS.TEST = ()
  #cfg.TEST.EVAL_PERIOD = 100
  cfg.DATALOADER.NUM_WORKERS = 2
  cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
  cfg.SOLVER.IMS_PER_BATCH = 2
  cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
  cfg.SOLVER.MAX_ITER = 100    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
  cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
  cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon). 
  
  os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
  trainer = DefaultTrainer(cfg) 
  
  trainer.resume_or_load(resume=False)

for i in range(30):
    print("TRAINING STEP", i)
    trainer.train()
    ### my evaluation step comes here
    trainer.resume_or_load(resume=True)

however, when i do this, I get the following error:
Traceback (most recent call last):
  File "scratch.py", line 132, in <module>
    trainer.train()
  File "/home/VRC/robert.harris/anaconda3/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 413, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/VRC/robert.harris/anaconda3/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 144, in train
    self.after_train()
  File "/home/VRC/robert.harris/anaconda3/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 153, in after_train
    h.after_train()
  File "/home/VRC/robert.harris/anaconda3/lib/python3.6/site-packages/detectron2/engine/hooks.py", line 358, in after_train
    self._do_eval()
  File "/home/VRC/robert.harris/anaconda3/lib/python3.6/site-packages/detectron2/engine/hooks.py", line 328, in _do_eval
    results = self._func()
AttributeError: 'EvalHook' object has no attribute '_func'

Following that error into hooks.py, it seems like it's because of the del self._func at the end of after_train().  However simply commenting that out creates other errors, as it's likely there for a reason.

What is a good way to manually train inside of a loop, saving the optimizer and weights, without errors?

Thanks!
-Bobby

**Comment by ppwwyyxx** [comment]
`trainer.train` cannot be called more than once for a trainer.

https://detectron2.readthedocs.io/tutorials/training.html explains how to customize training. https://github.com/facebookresearch/detectron2/issues/2114 describes how to save best model.
