### ISSUE TITLE
How to decode paired object boxes?

### ISSUE THREAD

**Issue by urbaneman** [facebookresearch/detectron2#2460]
## ❓ How to decode paired object boxes using detectron2

There are paired object boxes in some datasets, like CrowdHuman(one person with head, full-body, and visible body), the format like:

> "gtboxes": [{"fbox": [72, 202, 163, 503], "tag": "person", "hbox": [171, 208, 62, 83], "extra": {"box_id": 0, "occ": 0}, "vbox": [72, 202, 163, 398], "head_attr": {"ignore": 0, "occ": 0, "unsure": 0}},...]

I want to use the relationship between head and full-body, but the default coco only has one `bbox`. 

So, what should I do to decode the boxes with paired?

**Comment by ppwwyyxx** [comment]
See "Custom Dataset Dicts for New Tasks": https://detectron2.readthedocs.io/tutorials/datasets.html#custom-dataset-dicts-for-new-tasks
