### ISSUE TITLE
How to migrate to iopath version of PathManager?

### ISSUE THREAD

**Issue by bluegiraffe-sc** [facebookresearch/detectron2#2461]
Hi everybody,
when doing instance segmentation with a mask-RCNN model, I got the following message:

> ** fvcore version of PathManager will be deprecated soon. **
> ** Please migrate to the version in iopath repo. **
> https://github.com/facebookresearch/iopath

My dumb trial to solve the issue was installing iopath from PypI, but I got:

> Requirement already satisfied: iopath in ./venv/cv/lib/python3.6/site-packages (0.1.2)
> Requirement already satisfied: portalocker in ./venv/cv/lib/python3.6/site-packages (from iopath) (2.0.0)
> Requirement already satisfied: tqdm in ./venv/cv/lib/python3.6/site-packages (from iopath) (4.55.0)

What should I do?

**Comment by ppwwyyxx** [comment]
Upgrading to github's latest version of detectron2, or downgrading to an older version of fvcore will solve it.

**Comment by JosephKJ** [comment]
To downgrade fvcore, you may 
```
```

**Comment by bluegiraffe-sc** [comment]
Thanks to both of you!

**Comment by gabrielhuang** [comment]
This solved it for me: `pip install -U iopath`
