### ISSUE TITLE
Number of images to AP relation.

### ISSUE THREAD

**Issue by meetgandhi123** [facebookresearch/detectron2#2462]
## 🚀 Feature
Can you add a number of images to AP relation, like how many images are needed to AP? 

## Motivation & Examples

I was making a model with a new dataset, when I was asked how many images do you need minimum to get around 60 AP. At that time I had to test it manually. 

Can you provide a general estimation for a number of images - Batch size - epoch and AP?

**Comment by ppwwyyxx** [comment]
The question is about object detection and not specific to detectron2. 
We also don't have an answer for it.
