### ISSUE TITLE
where I need to change the code

### ISSUE THREAD

**Issue by Jeyakumar-johnny-jonathan** [facebookresearch/detectron2#2463]
hi this is my error , do you know how to solve it?
```
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image /content/data/Images/137.jpg, got (3264, 2448), expect (2448, 3264)

```

_Originally posted by @morestart in https://github.com/facebookresearch/detectron2/issues/194#issuecomment-585803699_

**Comment by farazk86** [comment]
Its best to give more info related to your problem. How are you calling the function? Show your code.

Just from this error, its clear that you have your ``H`` and ``W`` mixed up. But would need more info to give proper response.

**Comment by morestart** [comment]
change another annotation tool and retry

**Comment by CarlBhy** [comment]
hi,i have solved this problem.This bad code is in the detectron2-master/detectron2/data/detection_utils.py line 186 to 209,I will post my modified code later.I think this error will not affect our training model, so I commented out part of the code and successfully solved the problem.

`def check_image_size(dataset_dict, image):
    """
    Raise an error if the image does not match the size specified in the dict.
    """
    if "width" in dataset_dict or "height" in dataset_dict:
        image_wh = (image.shape[1], image.shape[0])
        # expected_wh = (dataset_dict["width"], dataset_dict["height"])
        # if not image_wh == expected_wh:
        #     raise SizeMismatchError(
        #         "Mismatched image shape{}, got {}, expect {}.".format(
        #             " for image " + dataset_dict["file_name"]
        #             if "file_name" in dataset_dict
        #             else "",
        #             image_wh,
        #             expected_wh,
        #         )
        #         + " Please check the width/height in your annotation."
        #     )

    # To ensure bbox always remap to original image size
    if "width" not in dataset_dict:
        dataset_dict["width"] = image.shape[1]
    if "height" not in dataset_dict:
        dataset_dict["height"] = image.shape[0]`
Hope my answer is useful for you！
