### ISSUE TITLE
Which model is used to segment trees as shown in readme gif?

### ISSUE THREAD

**Issue by farazk86** [facebookresearch/detectron2#2464]
The example shown in the readme.md file: https://github.com/facebookresearch/detectron2 has the trees segmented in instance segmentation. Which model was used to achieve this?

I need to segment trees in my images and I cannot replicate the example output shown as shown in image below.

![image](https://user-images.githubusercontent.com/33456896/104057008-47dfa100-51e9-11eb-9be8-35618bf6a499.png)

The tutorial also does not produce the trees segmentation and as can be seen from the image, is not detected.

![download](https://user-images.githubusercontent.com/33456896/104056457-6b561c00-51e8-11eb-931c-f3c50c2d1168.png)

I tried to predict above image with ``COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x`` and ``COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x``, both failed to detect/segment trees.

Which model do I use to detect trees please?

Thanks

## Instructions To Reproduce the Issue

Just follow the beginner tutorial colab.

## Environment:

Google colab+ GPU - following beginner tutorial.

**Comment by ppwwyyxx** [comment]
This is a panoptic segmentation model trained on COCO, not instance segmentation.
