### ISSUE TITLE
unfreeze backbone layers of checkpoint module

### ISSUE THREAD

**Issue by xQsM3** [facebookresearch/detectron2#2465]
Hi,

I trained the RetinaNet101 and the RCNN x101 on my custom dataset with a custom class. It performs quite well but I expected the generalization to be a bit better. I tried 16-512 Batch size, 16 BS was the best for generalization. Now, I got the tip to unfreeze the first layers (if they are freezed by default ?) in order to get better generalization. If I do the following:

cfg.MODEL.BACKBONE.FREEZE_AT = 0
 
with: 

trainer.resume_or_load(resume=True)

I get the error:

loaded state dict has a different number of parameter groups

I understand that this is because the amount of layers is not the same anymore. Is there a possibility to do this on another way? thank you

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/issues/898#issuecomment-675811128
