### ISSUE TITLE
About the GroupedBatchSampler

### ISSUE THREAD

**Issue by Remember2018** [facebookresearch/detectron2#247]
Hi @ppwwyyxx Yuxin, I read the source code of `detectron2` and the `maskrcnn-benchmark`, it seems there are two different implementations on the `GroupedBatchSampler` for the data sampling based on the aspect ratios.  In `detectron2`, the implemetation is 
https://github.com/facebookresearch/detectron2/blob/6a422717df9480f23b062be0777f56a227cad33a/detectron2/data/samplers/grouped_batch_sampler.py#L6

In `maskrcnn_benchmark`, the implementation is as follows:
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/data/samplers/grouped_batch_sampler.py

It seems the implementation in `detectron2` is much simpler than that of `maskrcnn_benchmark`. My question is, will this have some influences on the accuracy? Thanks.

**Comment by ppwwyyxx** [comment]
They don't seem to affect accuracy.

**Comment by Remember2018** [comment]
Thank you Yuxin! @ppwwyyxx
