### ISSUE TITLE
Can I just get the bounding box or coordinates corresponds to human/person class?

### ISSUE THREAD

**Issue by akshayag** [facebookresearch/detectron2#2470]
## ❓ How to do something using detectron2
I was able to run both demo and predict.py code; however, interested in the following output (only person class and if coordinates of the individual attribute of human such as the face, hand, legs, etc)

Describe what you want to do, including:
1. what inputs you will provide, if any:
Either using the predict.py or demo.py or the collab code (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=7d3KxiHO_0gb) using pretrained model

I am looking for both video-based and image-based prediction

2. what outputs you are expecting:
I am the predictions corresponding to persona/human class only. Does the code also provide the coordinates ralted to individual attributes of the person such as where the hand, the leg is? 
## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work" for something you did, please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by ppwwyyxx** [comment]
> Does the code also provide the coordinates ralted to individual attributes of the person such as where the hand, the leg is?

The tutorial models don't have such capability.

https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose might help.
