### ISSUE TITLE
Is DeformConv in detectron2 based on pure PyTorch or partial C code?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#2471]
Hi, guys,
I am a learner of detectron2, and I want to know whether DeformConv is based on pure PyTorch or partial C code?

Your answer or idea will be appreciated!

**Comment by ppwwyyxx** [comment]
code: https://github.com/facebookresearch/detectron2/tree/master/detectron2/layers/csrc/deformable
