### ISSUE TITLE
wondering if there is a func for showing gt bboxes and pred bboxes in an image at the same time

### ISSUE THREAD

**Issue by BreezeHavana** [facebookresearch/detectron2#2477]
## Motivation & Examples

Sometimes developers are eager to know the similarities in FP bboxes and FN objects in object detection. If gt and pred bboxes shown in an image at the same time, developers may know their models' weakness, like small objects or overlapping objects. If there isn't a function yet, I may add a pull request later.
Thx.

**Comment by jdegeus** [comment]
You can use the [Visualizer ](https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances)class. Initialize it with your original image, then run the method "overlay_instances" twice with once the annotations and once the predictions. It also accepts masks.
```python
visualizer = Visualizer(img, metadata=metadata, scale=scale)
visualizer.overlay_instances(boxes=annotation_boxes, assigned_colors=colors_annotations, alpha=0.5)
output = visualizer.overlay_instances(boxes=prediction_boxes, assigned_colors=colors_predictions, alpha=0.5)
img_result = output.get_image()
```

**Comment by BreezeHavana** [comment]
> You can use the [Visualizer ](https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances)class. Initialize it with your original image, then run the method "overlay_instances" twice with once the annotations and once the predictions. It also accepts masks.
> 
> ```python
> visualizer = Visualizer(img, metadata=metadata, scale=scale)
> visualizer.overlay_instances(boxes=annotation_boxes, assigned_colors=colors_annotations, alpha=0.5)
> output = visualizer.overlay_instances(boxes=prediction_boxes, assigned_colors=colors_predictions, alpha=0.5)
> img_result = output.get_image()
> ```

Thx, very helpful
