### ISSUE TITLE
Values of AP50 above 1.0 on validation results in tensorboard

### ISSUE THREAD

**Issue by gmxmb** [facebookresearch/detectron2#2478]
After step 100k, there is a gradual increase in AP50 with values above 1.0 . The graph at the center shows the strange behavior in AP50.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/59872667/104318270-ef94f180-54bd-11eb-94b4-a07846ab8276.png)

The custom training configuration:

```
cfg.DATALOADER.NUM_WORKERS = 1
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")

cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.WARMUP_ITERS = 210000
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.MAX_ITER = 250000
cfg.SOLVER.STEPS = (210000, 250000) #adjust up if val mAP is still rising, adjust down if overfit
cfg.SOLVER.GAMMA = 0.1

cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 #your number of classes + 1

cfg.TEST.EVAL_PERIOD = 500
```

The custom dataset were composed into 974 images of 512x512 px (3 channels); And splitted into 70 / 10 / 20 (train, test, validation)

I don't know if it's a bug or some inconsistent value on the dataset. I think it's technically impossible to achieve values above 1.0 on average precision metrics.

**Comment by ppwwyyxx** [comment]
We define AP between 0 and 100.
