### ISSUE TITLE
Stride in Backbones

### ISSUE THREAD

**Issue by mbsariyildiz** [facebookresearch/detectron2#248]
Hello! Thank you for sharing this amazing library.

I'd like to understand why there is "stride" attribute stored in backbones. Why do we need to compute this variable (especially when there are multiple conv and pooling layers)? What does this represent actually? 

Thanks.

**Comment by ppwwyyxx** [comment]
Stride means how much the feature map is downsampled from the input image. It can tell you what's the original box size of a box cropped on the feature map.

**Comment by mbsariyildiz** [comment]
Thanks!

**Comment by mbsariyildiz** [comment]
Can it be a floating-point number? Let's say I have a CNN that produces 13x13 spatial grid of features given a 224x224 image. In that case 224 / 13 = 17.23076923076923 . May I just set 
```python
self._out_features_strides = {"some_label": 17.2}
```
in a backbone class?

**Comment by ppwwyyxx** [comment]
In theory you can define it like this, but many modules in detectron2 requires or assumes integer strides.

**Comment by mbsariyildiz** [comment]
Good to know, many thanks!
