### ISSUE TITLE
No documentation for latest release (v 0.3)

### ISSUE THREAD

**Issue by AnnikaLindh** [facebookresearch/detectron2#2488]
## Instructions To Reproduce the 🐛 Bug:
Go to https://detectron2.readthedocs.io/modules/model_zoo.html
and compare to the source for v 0.3: https://github.com/facebookresearch/detectron2/archive/v0.3.zip

## Expected behavior:
I expected the documentation to describe only the functions and parameters included in the latest release of the source.
Instead, functions and parameters that do not exist in v 0.3 are described, for example:
 - get_config() does not exist in the code
 - the 'device' parameter in get() does not exist in the code

## Environment:
Ubuntu 16, python 3.6.12, PyTorch 1.7.

**Comment by ppwwyyxx** [comment]
The documentation corresponds to latest code on github, rather than v0.3

**Comment by AnnikaLindh** [comment]
> 
> 
> The documentation corresponds to latest code on github, rather than v0.3

Thank you for the reply. Are there any plans to export documentation for each stable release? It's possible to keep multiple versions on readthedocs and it seems a bit strange to have releases without documentation for them. Thanks!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/en/v0.3/index.html
