### ISSUE TITLE
data type error running pretrained network

### ISSUE THREAD

**Issue by edwardchaos** [facebookresearch/detectron2#250]
Running a pretrained network using weights: model_final_a3ec72.pkl
The following error occurs when concatenating ground truth labels, no modification to network architecture or connection from previous layer.
Using custom dataset and input ground truth is initialized as:

snippet from my custom dataset __getitem__ function:
object_instances = Instances((1024, 1024))
class_tensor = torch.FloatTensor(class_labels)
object_instances.gt_classes = class_tensor

RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 2 in sequence argument at position #1 'tensors'
> /home/edwardchaos/detectron2_repo/detectron2/modeling/roi_heads/fast_rcnn.py(169)__init__()
-> self.gt_classes = cat(templist, dim=0)

I modified the cat line in fast_rcnn.py for debugging purposes like so:

templist = [p.gt_classes for p in proposals]
self.gt_classes = cat(templist, dim=0)

Problem was solved when I casted the tensor to float as follows:
templist = [p.gt_classes.float() for p in proposals]
self.gt_classes = cat(templist, dim=0)

## Environment

------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                     1.17.2
Detectron2 Compiler       GCC 5.5
Detectron2 CUDA Compiler  9.2
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1a0+d94043a
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-9.2
NVCC                      Cuda compilation tools, release 9.2, V9.2.148
Pillow                    6.2.0
cv2                       4.1.1
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
As the error says, `gt_classes` should have type long.

**Comment by edwardchaos** [comment]
I'll have to verify it tomorrow, was going insane a little. I know for sure adding float passed that runtime error though.

**Comment by edwardchaos** [comment]
Ok, it seems class labels should be initialized as LongTensor instead.
Removing my changes in fast_rcnn.py and changing the input from:
class_tensor = torch.FloatTensor(class_labels)
to
class_tensor = torch.LongTensor(class_labels)
solves this problem.

I was under the impression that all datatypes when dealing with pytorch should be in float.
