### ISSUE TITLE
export_model as TorchScript has Caffe2 Operators?

### ISSUE THREAD

**Issue by CodeSammich** [facebookresearch/detectron2#2500]
When I export `model.ts` from the provided script untils `tools` using tracing, I get a model that is able to be detected and begin to run on Android using PyTorch 1.8.0 nightly builds.

However, the model itself contains Caffe2 ops, which is not included in PyTorch Android. 

> unknown op: caffe2:GenerateProposals

Is there a way to export to TorchScript without having to include Caffe2 ops? 

I want to emphasize: **regular .pt models have run successfully using the same code**.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/deployment.html has answered this. The other methods require torchvision ops instead.
