### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by davidqing2000** [facebookresearch/detectron2#251]
When try to run the demo, I always got below error, how to fix it?

D:\development\detectron2-master>python ./demo/demo.py --config-file ./configs/C
OCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input D:\TEMP\INPUT.JPG --
opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/
137849600/model_final_f10217.pkl
[11/06 10:10:01 detectron2]: Arguments: Namespace(confidence_threshold=0.5, conf
ig_file='./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=
['D:\\TEMP\\INPUT.JPG'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegme
ntation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, v
ideo_input=None, webcam=False)
WARNING [11/06 10:10:01 d2.config.compat]: Config './configs/COCO-InstanceSegmen
tation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible
with latest v2.
Traceback (most recent call last):
  File "./demo/demo.py", line 83, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "D:\development\detectron2-master\demo\predictor.py", line 48, in run_on_
image
    predictions = self.predictor(image)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py",
 line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "D:\development\detectron2-master\detectron2\engine\defaults.py", line 17
7, in __call__
    predictions = self.model([inputs])[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\development\detectron2-master\detectron2\modeling\meta_arch\rcnn.py",
 line 66, in forward
    return self.inference(batched_inputs)
  File "D:\development\detectron2-master\detectron2\modeling\meta_arch\rcnn.py",
 line 124, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\development\detectron2-master\detectron2\modeling\roi_heads\roi_heads
.py", line 568, in forward
    pred_instances = self._forward_box(features_list, proposals)
  File "D:\development\detectron2-master\detectron2\modeling\roi_heads\roi_heads
.py", line 615, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposal
s])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\development\detectron2-master\detectron2\modeling\poolers.py", line 2
08, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\development\detectron2-master\detectron2\layers\roi_align.py", line 9
5, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self
.aligned
  File "D:\development\detectron2-master\detectron2\layers\roi_align.py", line 2
0, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, a
ligned
RuntimeError: CUDA error: no kernel image is available for execution on the devi
ce (ROIAlign_forward_cuda at D:/development/detectron2-master/detectron2/layers/
csrc/ROIAlign/ROIAlign_cuda.cu:361)
(no backtrace available)

----------------The information of configuration about GPU and Cuda------------------
D:\development\detectron2-master>python -m detectron2.utils.collect_env
Failed to load OpenCL runtime

------------------------  ------------------------------------------------------
-----------------------------
sys.platform              win32
Python                    3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32
) [MSC v.1900 64 bit (AMD64)]
Numpy                     1.14.2
Detectron2 Compiler       MSVC 191125506
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1
CUDA available            True
GPU 0,1                   Tesla P40
CUDA_HOME                 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10
.1
NVCC                      Not Available
TORCH_CUDA_ARCH_LIST      7.0
Pillow                    5.0.0
cv2                       3.2.0
------------------------  ------------------------------------------------------
-----------------------------
PyTorch built with:
  - MSVC 191125547
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Int
el(R) 64 architecture applications
  - OpenMP 200203
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=c
ompute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_6
1,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=s
m_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.5.1
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLA
GS=/DWIN32 /D_WINDOWS  /GR  /w /EHa /MP /bigobj -openmp, DISABLE_NUMA=1, PERF_WI
TH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF,
USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=
OFF, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
I don't know why you would have `TORCH_CUDA_ARCH_LIST 7.0` in your environment variables, but please just remove it.

**Comment by davidqing2000** [comment]
Thank for your help, it's fixed with above setting now.

**Comment by Franciszzj** [comment]
@ppwwyyxx I had the same problem, but I don't have ```TORCH_CUDA_ARCH_LIST 7.0``` Env.

The error info is:
```
error in modulated_deformable_col2im_coord_cuda: no kernel image is available for execution on the device
error in modulated_deformable_col2im_cuda: no kernel image is available for execution on the device
```

My Env is:
```
[07/20 13:46:17] detectron2 INFO: Rank of current process: 0. World size: 8
[07/20 13:46:17] detectron2 INFO: Environment info:
----------------------  ---------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.8 (default, Aug 10 2019, 06:54:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
numpy                   1.16.5
detectron2              0.1.3 @/running_package/PanopticSeg/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.0
detectron2 arch flags   sm_70
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0+cu100 @/running_package/py3.6-env/lib64/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla P40
CUDA_HOME               /usr/local/cuda
Pillow                  6.1.0
torchvision             0.5.0+cu100 @/running_package/py3.6-env/lib64/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200623
cv2                     3.4.5
----------------------  ---------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

Hope your help!

**Comment by ppwwyyxx** [comment]
the issue and its solution were described in more details at https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by Franciszzj** [comment]
Thanks for your replay, this suit for me.
