### ISSUE TITLE
Clarifying type of default proposals for fast R-CNN

### ISSUE THREAD

**Issue by jd730** [facebookresearch/detectron2#2521]
## 📚 Documentation

Hi, I found that there is no description of which type of proposal (e.g., Selective Search, EdgeBox, MCG, etc.) is used for https://github.com/facebookresearch/detectron2/blob/ee487bbfcb8411ca3642774b5be911d9c4a59a0a/configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml#L12

According to the original Fast R-CNN paper, It might be a Selective Search.

* Links to the relevant documentation/comment:

I think clarifying it would be better in 
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#rpn--fast-r-cnn

and 
https://github.com/facebookresearch/detectron2/blob/ee487bbfcb8411ca3642774b5be911d9c4a59a0a/configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml#L12

Thank you.

**Comment by ppwwyyxx** [comment]
They are generated from the corresponding RPN model, e.g.

```
 PROPOSAL_FILES_TRAIN: ("detectron2://COCO-Detection/rpn_R_50_FPN_1x/137258492/coco_2017_train_box_proposals_21bc3a.pkl", ) 
```
is generated from RPN with model id 137258492. The model can be found in model zoo.
