### ISSUE TITLE
Order of channels in the input normalization

### ISSUE THREAD

**Issue by mbsariyildiz** [facebookresearch/detectron2#254]
## ❓ Questions and Help

Hello.

I am trying to evaluate Faster-RCNN model on Pascal-VOC2007 dataset. To do that, I simply run
```bash
python tools/train_net.py \
    --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml \
    --eval-only
```
The program runs without any error. However, I notice that the config file contains these keywords for `MODEL`:
```yaml
PIXEL_MEAN: [103.53, 116.28, 123.675]
PIXEL_STD: [1.0, 1.0, 1.0]
```
`PIXEL_MEAN` is actually the flipped `mean_norm` * 255, that is used in normalizing inputs for 
 [torchvision models](https://pytorch.org/docs/stable/torchvision/models.html). So my question is, do models accept images in B-R-G format instead of R-G-B format,  or is it just a coincidence?

Thanks!

**Comment by ppwwyyxx** [comment]
The image format is defined by `INPUT.FORMAT`.

**Comment by mbsariyildiz** [comment]
Ups, didn't see that, thanks.
