### ISSUE TITLE
Is it possible to train with multiple datasets?

### ISSUE THREAD

**Issue by qbeer** [facebookresearch/detectron2#2544]
## 📚 Documentation

I could fine an example in the provided configs and in the code, or the documentation and was wondering whether it would be possible to use several registered COCO-like datasets during training if I have several instances of the same type of data but from different locations, e.g.:

```json
DATASETS:
  TRAIN: ("my_data1", "my_data2", "my_data3", ...)
  TEST : ("my_test_data1",)
```

I would assume that all the training data is collected, shuffled, etc. and used as one. I can create a new, merged data set but would be nicer if I could use the currently available separate files.

Having only 1 test data set would suffice, I could run the algorithm several times for the different evaluation sets.

Thanks in advance,
Alex

**Comment by ppwwyyxx** [comment]
> I would assume that all the training data is collected, shuffled, etc. and used as one

It is already supported this way when config is given like the example you provided.
