### ISSUE TITLE
Changing the default Pascal-VOC* root directory

### ISSUE THREAD

**Issue by mbsariyildiz** [facebookresearch/detectron2#255]
## 🚀 Feature

Setting the root dataset directory somewhere different than ./datasets.

## Motivation

When training a model on a GPU cluster with multiple nodes, it is more efficient to copy a data set to a local disk of the server which the job is assigned to than loading the data from a shared disk. In such cases, the root directory of the dataset needs to be set accordingly.

## Pitch

For the moment, I am interested in changing the root directory of Pascal VOC datasets. I think adding the following line [here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/builtin.py#L204)  is enough.
```python
root = os.environ.get("VOC{}_HOME".format(year), "datasets")
```

**Comment by mbsariyildiz** [comment]
Or maybe before registering builtin datasets [here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/builtin.py#L210) like that
```python
_datasets_root = os.environ.get("DATASETS_HOME", "datasets")
register_all_pascal_voc(_datasets_root)
...
```

**Comment by ppwwyyxx** [comment]
You can soft-link the data from anywhere to `./datasets`.

**Comment by mbsariyildiz** [comment]
But then I need to move the source folder each time I run experiment on a different node in the cluster. Because I don't want to load images from a shared disk.

The second thing I proposed solves my issue. I am closing the issue.
Thanks

**Comment by ppwwyyxx** [comment]
The default can now be changed. See https://github.com/facebookresearch/detectron2/tree/master/datasets
