### ISSUE TITLE
use instance detection box for instance segmentation or key-point estimation

### ISSUE THREAD

**Issue by mreza3650** [facebookresearch/detectron2#2554]
I like to use the instance detection bounding box output for later using in instance segmentation or key-point estimation. The reason is for me, faster-rcnn is very good in detecting the bounding box detection task, but while when I use the default predictor for key-point estimation from scratch, it will miss many of people inside the frame. 
I will be very glad if some one has any idea for making the predictor able to accept the suggested proposed boxes.
Thanks.

**Comment by ppwwyyxx** [comment]
Already supported in https://detectron2.readthedocs.io/en/latest/modules/modeling.html#detectron2.modeling.GeneralizedRCNN.inference

**Comment by mreza3650** [comment]
Thanks a lot,
To achieve a better understanding for implementation, may I ask you to provide an example of usage. 
It's a bit confusing for me,
Best regards
