### ISSUE TITLE
What is meant by the abbreviations C2 and C4 used in detectron2 code. 

### ISSUE THREAD

**Issue by dishank-b** [facebookresearch/detectron2#256]
## ❓ C2 and C4 abbreviations in code

C2 and C4 are used in the source code as abbreviations. As far as I could understand **C2 refers to caffe2** and **C4 is associated with Conv4 layer of ResNet**, it that right?

**Comment by ppwwyyxx** [comment]
Yes.
C2 may often mean conv2, but that's always clear by context.
