### ISSUE TITLE
Install detectron2 on ubuntu problem: Running setup.py install for pycocotools ... error

### ISSUE THREAD

**Issue by wubinbai** [facebookresearch/detectron2#2560]
## 📚 Documentation

* Links to the relevant documentation/comment: https://detectron2.readthedocs.io/en/latest/tutorials/install.html
With gcc and g++ 7.3.0, ubuntu 18.04

Here is a full command line log:
within the github repository: run with command: 
pip3 install -e .
(please read the last lines of error)

Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///media/b/PSSD/git/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (1.1.0)
Requirement already satisfied: Pillow>=7.1 in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (8.0.1)
Requirement already satisfied: yacs>=0.1.6 in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (0.1.8)
Requirement already satisfied: tabulate in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (0.8.7)
Collecting cloudpickle
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Requirement already satisfied: matplotlib in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (3.3.3)
Requirement already satisfied: tqdm>4.29.0 in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (4.55.0)
Requirement already satisfied: tensorboard in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (2.2.2)
Collecting fvcore<0.1.3,>=0.1.2
  Using cached fvcore-0.1.2.post20210128-py3-none-any.whl
Requirement already satisfied: iopath>=0.1.2 in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (0.1.3)
Collecting pycocotools>=2.0.2
  Using cached pycocotools-2.0.2.tar.gz (23 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Requirement already satisfied: pydot in /home/b/.local/lib/python3.6/site-packages (from detectron2==0.3) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /home/b/.local/lib/python3.6/site-packages (from fvcore<0.1.3,>=0.1.2->detectron2==0.3) (5.4.1)
Requirement already satisfied: numpy in /home/b/.local/lib/python3.6/site-packages (from fvcore<0.1.3,>=0.1.2->detectron2==0.3) (1.19.4)
Requirement already satisfied: portalocker in /home/b/.local/lib/python3.6/site-packages (from iopath>=0.1.2->detectron2==0.3) (2.2.0)
Requirement already satisfied: setuptools>=18.0 in /home/b/.local/lib/python3.6/site-packages (from pycocotools>=2.0.2->detectron2==0.3) (51.1.0.post20201221)
Requirement already satisfied: cython>=0.27.3 in /home/b/.local/lib/python3.6/site-packages (from pycocotools>=2.0.2->detectron2==0.3) (0.29.21)
Requirement already satisfied: python-dateutil>=2.1 in /home/b/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.3) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/b/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.3) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/b/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/b/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.3) (1.3.1)
Requirement already satisfied: six in /home/b/.local/lib/python3.6/site-packages (from cycler>=0.10->matplotlib->detectron2==0.3) (1.15.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (3.14.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3/dist-packages (from tensorboard->detectron2==0.3) (2.6.9)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (1.7.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (0.4.2)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (1.24.0)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard->detectron2==0.3) (0.30.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (1.34.0)
Requirement already satisfied: absl-py>=0.4 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (0.11.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/b/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.3) (2.25.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/b/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.6)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/b/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/b/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/b/.local/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/b/.local/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (2018.1.18)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (1.22)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (2.6)
Requirement already satisfied: oauthlib>=3.0.0 in /home/b/.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (3.1.0)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py): started
  Building wheel for pycocotools (setup.py): finished with status 'error'
  Running setup.py clean for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools, fvcore, future, cloudpickle, detectron2
    Running setup.py install for pycocotools: started
    Running setup.py install for pycocotools: finished with status 'error'

###  the followings are printed in red:

   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zbqqcdat
       cwd: /tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/
  Complete output (69 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/mask.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/coco.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.6/pycocotools
  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
  /home/b/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/pycocotools/_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pycocotools._mask' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/common
  creating build/temp.linux-x86_64-3.6/pycocotools
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/b/.local/lib/python3.6/site-packages/numpy/core/include -I./common -I/usr/include/python3.6m -c ./common/maskApi.c -o build/temp.linux-x86_64-3.6/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
  ./common/maskApi.c: In function ‘rleDecode’:
  ./common/maskApi.c:46:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
         ^~~
  ./common/maskApi.c:46:49: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
         for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
                                                   ^
  ./common/maskApi.c: In function ‘rleFrPoly’:
  ./common/maskApi.c:166:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
     ^~~
  ./common/maskApi.c:166:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
     for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
                                                        ^
  ./common/maskApi.c:167:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
     ^~~
  ./common/maskApi.c:167:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
     for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
                                                        ^
  ./common/maskApi.c: In function ‘rleToString’:
  ./common/maskApi.c:212:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(more) c |= 0x20; c+=48; s[p++]=c;
         ^~
  ./common/maskApi.c:212:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
         if(more) c |= 0x20; c+=48; s[p++]=c;
                             ^
  ./common/maskApi.c: In function ‘rleFrString’:
  ./common/maskApi.c:220:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
     while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
     ^~~~~
  ./common/maskApi.c:220:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
     while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
                        ^~~~
  ./common/maskApi.c:228:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
       if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
       ^~
  ./common/maskApi.c:228:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
       if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
                                    ^~~~
  ./common/maskApi.c: In function ‘rleToBbox’:
  ./common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                                 ^
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/b/.local/lib/python3.6/site-packages/numpy/core/include -I./common -I/usr/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
  pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gp1aref5/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/b/.local/include/python3.6m/pycocotools
         cwd: /tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/
    Complete output (67 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pycocotools
    copying pycocotools/mask.py -> build/lib.linux-x86_64-3.6/pycocotools
    copying pycocotools/coco.py -> build/lib.linux-x86_64-3.6/pycocotools
    copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.6/pycocotools
    copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.6/pycocotools
    running build_ext
    skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
    building 'pycocotools._mask' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/common
    creating build/temp.linux-x86_64-3.6/pycocotools
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/b/.local/lib/python3.6/site-packages/numpy/core/include -I./common -I/usr/include/python3.6m -c ./common/maskApi.c -o build/temp.linux-x86_64-3.6/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
    ./common/maskApi.c: In function ‘rleDecode’:
    ./common/maskApi.c:46:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
           for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
           ^~~
    ./common/maskApi.c:46:49: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
           for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
                                                     ^
    ./common/maskApi.c: In function ‘rleFrPoly’:
    ./common/maskApi.c:166:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
       for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
       ^~~
    ./common/maskApi.c:166:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
       for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
                                                          ^
    ./common/maskApi.c:167:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
       for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
       ^~~
    ./common/maskApi.c:167:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
       for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
                                                          ^
    ./common/maskApi.c: In function ‘rleToString’:
    ./common/maskApi.c:212:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
           if(more) c |= 0x20; c+=48; s[p++]=c;
           ^~
    ./common/maskApi.c:212:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
           if(more) c |= 0x20; c+=48; s[p++]=c;
                               ^
    ./common/maskApi.c: In function ‘rleFrString’:
    ./common/maskApi.c:220:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
       while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
       ^~~~~
    ./common/maskApi.c:220:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
       while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
                          ^~~~
    ./common/maskApi.c:228:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
         ^~
    ./common/maskApi.c:228:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
         if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
                                      ^~~~
    ./common/maskApi.c: In function ‘rleToBbox’:
    ./common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                                   ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/b/.local/lib/python3.6/site-packages/numpy/core/include -I./common -I/usr/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
    pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bnn8kw21/pycocotools_f13f62aaf49546019dc9923edf4326fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gp1aref5/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/b/.local/include/python3.6m/pycocotools Check the logs for full command output.

Can anyone help me with this?? Thanks!!!

**Comment by ppwwyyxx** [comment]
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by wubinbai** [comment]
@ppwwyyxx Thanks for the link. However when I tried the solution:
sudo apt-get install python3-dev it showed:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-dev : Depends: python3 (= 3.6.5-3) but 3.6.5-3ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

So any following solutions? thanks!

**Comment by OrjwanZaafarani** [comment]
I'm having the same problem
