### ISSUE TITLE
wrong docker command

### ISSUE THREAD

**Issue by chris-the-wiz** [facebookresearch/detectron2#2561]
## 📚 Documentation

* Links to the relevant documentation/comment:
https://github.com/facebookresearch/detectron2/blob/master/docker/README.md

After building the base detectron2 container as above, do:

# Build:
docker build -t detectron2-deploy:v0 -f deploy.Dockerfile

SHOULD BE: 

docker build -t detectron2-deploy:v0 -f deploy.Dockerfile .
_(missing dot at the end)_

**Comment by ppwwyyxx** [comment]
fixed
