### ISSUE TITLE
Multi-Node multi-process distributed training

### ISSUE THREAD

**Issue by p517332051** [facebookresearch/detectron2#259]
## ❓ Questions and Help

General questions about detectron2.

NOTE:
Detectron2 support  Multi-Node multi-process distributed training ？

**Comment by ppwwyyxx** [comment]
Yes.

**Comment by p517332051** [comment]
有没有教程啊，我看的都是单机多卡的。我对pytorch不是太了解



---Original---

**Comment by ppwwyyxx** [comment]
Then you can learn about pytorch distributed at https://pytorch.org/docs/stable/distributed.html or https://pytorch.org/tutorials/intermediate/dist_tuto.html, etc.

**Comment by githubgsq** [comment]
@ppwwyyxx hi, yuxin，I also tried multi-nodes distributed training.
on 1st node, I run:
export NCCL_SOCKET_IFNAME=eth0
python tools/train_net.py --num-gpus 8 \
    --config-file configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml \
    --num-machines 2 \
    --machine-rank 0 \
    --dist-url "tcp://IP:8686"

on 2nd node, I run:
export NCCL_SOCKET_IFNAME=eth0
python tools/train_net.py --num-gpus 8 \
    --config-file configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml \
    --num-machines 2 \
    --machine-rank 1 \
    --dist-url "tcp://IP:8686"

on 1st node, logger only output:
 Command Line Args: Namespace(config_file='configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml', dist_url='tcp://IP:8686', eval_only=False, machine_rank=0, num_gpus=8, num_machines=2, opts=[], resume=False)
and no any other output

the other node outputs: 
Command Line Args: Namespace(config_file='configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml', dist_url='tcp://IP:8686', eval_only=False, machine_rank=1, num_gpus=8, num_machines=2, opts=[], resume=False)
also no more otputs.

GPU-util 100%, but no log.txt generated, it looks that multi-node didn't work, how to address the issue please?

**Comment by ppwwyyxx** [comment]
That means your two machines cannot find each other with pytorch's distributed module. This should be unrelated to detectron2 and you need to check your environment setup.

**Comment by githubgsq** [comment]
How to ensure that the two machines can find each other please?
1. both the 2 machines use 1st machine's IP, and the 2nd machine can ping 1st machine successfully.
2. I run: ldd lib-path/site-packages/torch/lib/libtorch.so, libnccl.so.2, libibverbs.so.1, libhiredis.so.0.14, libmpi.so.40 exist, what else specified library is needed please? how to check whether the environment is ready please?

**Comment by p517332051** [comment]
你看看你的两个机器torch是不是都是1.3以上。



---Original---

**Comment by githubgsq** [comment]
@p517332051 same environment: pytorch1.3 + cuda9.2 + cudnn7.6.4
I tried to simulate multi-nodes distributed training on one node successfully, so it should be the machines' fault. Next I would try machines in the same network segment.

**Comment by p517332051** [comment]
我之前和你情况一样，后来全部换成同样的pytorch版本就可以跑了。



---Original---

**Comment by ppwwyyxx** [comment]
Further questions should be directed to pytorch distributed since this issue is unrelated to detectron2.

**Comment by Viczyf** [comment]
> @p517332051 same environment: pytorch1.3 + cuda9.2 + cudnn7.6.4
> I tried to simulate multi-nodes distributed training on one node successfully, so it should be the machines' fault. Next I would try machines in the same network segment.

Hello, I meet the same problem with you. Have you ever solved it? I still can't train models on muilti-nodes.

**Comment by Zy1013921842** [comment]
> @p517332051 same environment: pytorch1.3 + cuda9.2 + cudnn7.6.4
> I tried to simulate multi-nodes distributed training on one node successfully, so it should be the machines' fault. Next I would try machines in the same network segment.

Hi, friend, have you solved it yet? I just got the same problem, no respounding after I typed the commands, please let me know if you made it. Appreciate much! @githubgsq @Viczyf
