### ISSUE TITLE
batch inference outputs wrong predictions

### ISSUE THREAD

**Issue by xQsM3** [facebookresearch/detectron2#2596]
# Problem description

Hi, I would like to do batch inference but my models output is empty when I use model(inputs). It is working fine for the default predictor but not when i use model(inputs for batch inference. here is my code for creating both model and predictor object:

>  def load_model(conf_thresh):
> 
>   cfg = get_cfg()
>   cfg.merge_from_file("./cfg/faster_rcnn_X_101_32x8d_FPN_3x.yaml")
>   cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[32*0.75, 64*0.75, 128*0.75, 256*0.75, 512*0.75]]
>   cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = conf_thresh # Set threshold for this model
>   cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
>   model = build_model(cfg) # returns a torch.nn.Module
>   cfg.MODEL.WEIGHTS = "./models/bb_rcnn.pth"    
>   DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
>   model.train(False) # inference mode
>   predictor = DefaultPredictor(cfg)
>   return model,predictor'
> 

as I said, predictor for one image works fine:

> model,predictor = load_model(conf_thresh=0.95)'
> image = cv.imread("/image.jpg")
> outputs = predictor(image)

with output:

> {'instances': Instances(num_instances=2, image_height=1710, image_width=1696, fields=[pred_boxes: Boxes(tensor([[ 580.7190, 1111.2963, 629.8201, 1160.1562], [ 666.4766, 1595.6615, 719.6202, 1648.0587]], device='cuda:0')), scores: tensor([0.9961, 0.9881], device='cuda:0'), pred_classes: tensor([0, 0], device='cuda:0')])}

if I run the models(inputs) now as suggested in https://detectron2.readthedocs.io/en/latest/tutorials/models.html#use-models and here in the comments:

> img = np.transpose(image,(2,0,1))
> img_tensor = torch.from_numpy(img)
> inputs = [{"image":img_tensor}] # inputs is ready
> outputs = model(inputs)

I get no instances:

> {'instances': Instances(num_instances=0, image_height=1710, image_width=1696, fields=[pred_boxes: Boxes(tensor([], device='cuda:0', size=(0, 4), grad_fn=)), scores: tensor([], device='cuda:0', grad_fn=), pred_classes: tensor([], device='cuda:0', dtype=torch.int64)])}]

EDIT: It appears that for a lower confidence threshold the model(inputs) finds two inferences as well (with a big offset). So it looks like the model somehow does not load all my custom trained weights, but the predictor does?
any help?

# Environment
ubuntu 18.04
detectron2
pytorch 1.7.1

# reproduce 
here is a dropbox link for the model and an example image:
https://www.dropbox.com/sh/0bi8pxruvun1762/AAC_6X2_IPn_plCIsA-T41NKa?dl=0

**Comment by ppwwyyxx** [comment]
Difference between predictor and model is expected and is documented at https://detectron2.readthedocs.io/en/latest/modules/engine.html#detectron2.engine.defaults.DefaultPredictor

**Comment by xQsM3** [comment]
Thanks for the reply but it doesn't help me with the issue. I know the difference between predictor and model. I know that predictor is taking one image as input and predicting on it while model takes a batch of images and predicts on them simultaneously. Since I want to do batch inference, the predictor is useless for me. So I want to use the model method but as stated above, it predicts nonsense. So there must be something wrong either in loading the model or in calling the model. Please help. I think it somehow either doesn't load all my custom weights or maybe not my custom anchor size?

**Comment by ppwwyyxx** [comment]
> I know the difference between predictor and model.  I know that predictor is taking one image as input and predicting on it while model takes a batch of images and predicts on them simultaneously. 

There are other differences that explain the different predictions.
