### ISSUE TITLE
Dilation in ResNet is Wrong and Inconsistent with Torchvision 

### ISSUE THREAD

**Issue by zhanghang1989** [facebookresearch/detectron2#2598]
## Instructions To Reproduce the 🐛 Bug:

For dilated network, the first block should keep the dilation rate the same as previous layer and change the following layers. However, Detectron2 change the dilation ratio for the entire stage. See implementation:

https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/backbone/resnet.py#L635

## Expected behavior:

The torchvision implementation is correct:
https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L220-L221 

## Your Environment:

N/A

**Comment by zhanghang1989** [comment]
@ppwwyyxx FYI, is this a known issue?

**Comment by ppwwyyxx** [comment]
torchvision is not our source of truth. AFAIK using dilations in our way is a convention in object detection that's first used in https://arxiv.org/pdf/1605.06409.pdf and also in https://arxiv.org/pdf/1703.06211.pdf.

You can use `dilations_per_block` if you'd like to customize it further: https://detectron2.readthedocs.io/en/latest/modules/modeling.html#detectron2.modeling.ResNet.make_stage

**Comment by zhanghang1989** [comment]
Thanks for the fast reply!

The only issue of keeping the dilation ratio the same per-stage is not well aligned with the pretrained weights. This does lead to ~1% performance drop for my case. If someone want an ad-hoc fix, the following code works:

```
backbone.stages[-1][0].conv2.dilation = (1, 1)
backbone.stages[-1][0].conv2.padding = (1, 1)
```

I am closing the issue, since it is not considered as a bug.
