### ISSUE TITLE
About Panoptic-DeepLab on COCO.

### ISSUE THREAD

**Issue by stormstoutzhang** [facebookresearch/detectron2#2600]
The batch size of Panoptic-DeepLab on COCO is 64. How mang GPUs is used? And what type GPU is used?  I used 8 Nvidia 3090Ti, shold the batch size be 64 or 16?

**Comment by ppwwyyxx** [comment]
answered in https://github.com/facebookresearch/detectron2/tree/master/projects/Panoptic-DeepLab
