### ISSUE TITLE
Error: No Output when exporting model to c++ using CPU Device

### ISSUE THREAD

**Issue by JJKau** [facebookresearch/detectron2#2608]
## Instructions To Reproduce the Issue:

I tried running the tutorial for deployment from the link below:
https://github.com/facebookresearch/detectron2/tree/master/tools/deploy
Following this example:
export-method=caffe2_tracing, format=torchscript:
./export_model.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --output ./output --export-method caffe2_tracing --format torchscript \
    MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \
    MODEL.DEVICE cpu

./build/torchscript_traced_mask_rcnn output/model.ts input.jpg caffe2_tracing

1. Running the following command on Anaconda Prompt to export a model:
python ./export_model.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./output --export-method caffe2_tracing --format torchscript MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cpu

2. I obtained a model.ts from it and pass it as input on torchscript_traced_mask_rcnn.cpp. I am using the default COCO dataset(2017) as input (Similar to tutorial  args: output/model.ts input.jpg caffe2_tracing)

3. For CPU device, I receive an empty output as follows:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/35526954/107306393-c2892e00-6abf-11eb-8a00-5ee2357c92b1.png)

4. For GPU device, which is the following command:
python ./export_model.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./output --export-method caffe2_tracing --format torchscript MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cuda

I am able to get an output using the same input image(Similar to tutorial  args: output/model.ts input.jpg caffe2_tracing):
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/35526954/107306647-34617780-6ac0-11eb-97e2-5cc2fde4d238.png)

I tried using a custom dataset with similar results as above. There is no output for CPU device.

## Expected behavior:
Expecting result similar to GPU device for the CPU device.

## Environment:

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/35526954/107307474-b69e6b80-6ac1-11eb-837e-4618cc136bfc.png)
cpp is compiled through visual studio, the following are the actual versions of the libraries:
libtorch : 1.7.1
opencv: 4.2.0
cuda: 10.2

**Comment by ppwwyyxx** [comment]
```diff
diff --git i/tools/deploy/torchscript_traced_mask_rcnn.cpp w/tools/deploy/torchscript_traced_mask_rcnn.cpp
index c83e0d93..ae18e06d 100644
--- i/tools/deploy/torchscript_traced_mask_rcnn.cpp
+++ w/tools/deploy/torchscript_traced_mask_rcnn.cpp
@@ -28,7 +28,7 @@ c10::IValue get_caffe2_tracing_inputs(cv::Mat& img, c10::Device device) {
   input = input.to(device, torch::kFloat).permute({0, 3, 1, 2}).contiguous();
 
   std::array<float, 3> im_info_data{height * 1.0f, width * 1.0f, 1.0f};
-  auto im_info = torch::from_blob(im_info_data.data(), {1, 3}).to(device);
+  auto im_info = torch::from_blob(im_info_data.data(), {1, 3}).clone().to(device);
   return std::make_tuple(input, im_info);
 }

```

This should fix it

**Comment by JJKau** [comment]
Issue is fixed. Thanks for the help.
