### ISSUE TITLE
Not able to run torch.jit.script command

### ISSUE THREAD

**Issue by yousaf446** [facebookresearch/detectron2#2613]
I am trying to run following command torch.jit.script in order to generate model compatible with pytorch-mobile android

I have made changes in following file
https://github.com/facebookresearch/detectron2/blob/a9f5d2e6a0f736c70c81414fb0c2f3574238e044/tools/deploy/export_model.py#L99

I added these lines

# Jit scripting
pt_model = torch.jit.script(WrapModel(), (image,))
torch.jit.save(pt_model, "model.pt")

This is the command which I try to run in terminal

./tools/deploy/export_model.py --config-file config.yaml --output ./output_X101_gpu --export-method tracing --format torchscript MODEL.WEIGHTS model_final.pth MODEL.DEVICE cuda

These are logs of the command

[02/10 19:57:23 detectron2]: Command line arguments: Namespace(config_file='/media/kv/11020DE711020DE7/dataset-3-be987d8e/dataset-3-be987d8e/output/G-Endcap_W-SpecialHardwareFeature_subcat_4_camview_15_16_dataset3_detectron2_X-101_FPN_v1/config.yaml', export_method='tracing', format='torchscript', opts=['MODEL.WEIGHTS', '/media/kv/11020DE711020DE7/dataset-3-be987d8e/dataset-3-be987d8e/output/G-Endcap_W-SpecialHardwareFeature_subcat_4_camview_15_16_dataset3_detectron2_X-101_FPN_v1/model_final.pth', 'MODEL.DEVICE', 'cuda'], output='./output_X101_gpu', run_eval=False)
WARNING [02/10 19:57:40 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[02/10 19:57:40 d2.data.datasets.coco]: Loaded 1994 images in COCO format from /media/kv/11020DE711020DE7/dataset-3-be987d8e/dataset-3-be987d8e/annotations/data_module/G-Endcap_W-SpecialHardwareFeature_subcat_4_camview_15_16_dataset3_detectron2_X-101_FPN_v1_val.json
[02/10 19:57:40 d2.data.build]: Distribution of instances among all 4 categories:
|   category    | #instances   |   category    | #instances   |   category    | #instances   |
|:-------------:|:-------------|:-------------:|:-------------|:-------------:|:-------------|
| G0D1_CENTER.. | 994          | G0E7_CENTER.. | 1000         | W0P1_SHF-NF.. | 982          |
| W0P3_SHF-SY.. | 1012         |               |              |               |              |
|     total     | 3988         |               |              |               |              |
[02/10 19:57:40 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[02/10 19:57:40 d2.data.common]: Serializing 1994 elements to byte tensors and concatenating them all ...
[02/10 19:57:40 d2.data.common]: Serialized dataset takes 6.21 MiB
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py:204: UserWarning: 'keypoint_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  "Consider removing it.".format(name))
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py:204: UserWarning: 'mask_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  "Consider removing it.".format(name))
/home/kv/Photo-Gauge/detectron2/detectron2/structures/image_list.py:92: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert t.shape[:-2] == tensors[0].shape[:-2], t.shape
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:161: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  tensor = torch.as_tensor(tensor, dtype=torch.float32, device=device)
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert tensor.dim() == 2 and tensor.size(-1) == 4, tensor.size()
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:78: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  topk_scores_i = logits_i.narrow(1, 0, num_proposals_i)
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:79: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  topk_idx = idx.narrow(1, 0, num_proposals_i)
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:101: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not valid_mask.all():
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:203: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert torch.isfinite(self.tensor).all(), "Box tensor contains infinite or NaN!"
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/tensor.py:570: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/kv/Photo-Gauge/detectron2/detectron2/layers/nms.py:16: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.shape[-1] == 4
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/poolers.py:217: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  0
/home/kv/Photo-Gauge/detectron2/detectron2/layers/roi_align.py:105: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.dim() == 2 and rois.size(1) == 5
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py:138: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not valid_mask.all():
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py:154: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1611130241393/work/torch/csrc/utils/python_arg_parser.cpp:983.)
  filter_inds = filter_mask.nonzero()
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py:155: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_bbox_reg_classes == 1:
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_script.py:930: UserWarning: `optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead
  "`optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead"
Traceback (most recent call last):
  File "./tools/deploy/export_model.py", line 166, in <module>
    exported_model = export_tracing(torch_model, first_batch)
  File "./tools/deploy/export_model.py", line 109, in export_tracing
    pt_model = torch.jit.script(WrapModel(), (image,))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_script.py", line 938, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 370, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 382, in create_script_module_impl
    method_stubs = stubs_fn(nn_module)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 618, in infer_methods_to_compile
    stubs.append(make_stub_from_method(nn_module, method))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 52, in make_stub_from_method
    return make_stub(func, method_name)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 37, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 271, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 305, in build_def
    build_stmts(ctx, body))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 278, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: import statements aren't supported:
  File "./tools/deploy/export_model.py", line 95
            outputs = self.torch_model.inference(inputs, do_postprocess=False)[0]
            outputs = outputs.get_fields()
            from detectron2.utils.analysis import _flatten_to_tuple
            ~~~~ <--- HERE
        
            return _flatten_to_tuple(outputs)

Please help me. I need to know whether I am doing something wrong or this functionality is currently not supported in detectron2.

**Comment by yousaf446** [comment]
I am using torch 1.8.0 and torchvision 0.9.0

**Comment by ppwwyyxx** [comment]
> I have made changes in following file

I believe the original code can run without change. The changes are not expected to work.
