### ISSUE TITLE
Seed for deterministic train

### ISSUE THREAD

**Issue by RomRoc** [facebookresearch/detectron2#2615]
https://github.com/facebookresearch/detectron2/blob/d4646c3b345178aa7e7f1d3b1cb8d69d629db4b0/detectron2/utils/env.py#L21

I need to run train in a deterministic way, to compare results with different cfg settings. I run it in Google Colab with GPU enabled.

If I set `cfg.SEED = 42` I get different results in various training processes.

To achieve very similar results among training processes, I run:

```
seed = 42

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed_everything(seed)
```

Don't you think you should set seed even for cuda (last 3 settings) when you train on gpu enabled environment?
In this case I can pull requests if you want.

Thanks

**Comment by ppwwyyxx** [comment]
>     torch.cuda.manual_seed(seed)

This is already included with `torch.manual_seed`.

>     torch.backends.cudnn.deterministic = True

This could make all training slower. So I think users should opt into this themselves if needed.

>     torch.backends.cudnn.benchmark = True

I don't think this makes training more deterministic.
