### ISSUE TITLE
Metadata for panoptic segmentation

### ISSUE THREAD

**Issue by vinx-2105** [facebookresearch/detectron2#2619]
## 📚 Documentation

* Links to the relevant documentation/comment:
https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html
panoptic_root, panoptic_json: Used by panoptic evaluation.

I don't understand what these fields in the metadata mean. Can someone please explain in more detail.

**Comment by ppwwyyxx** [comment]
panoptic_root (str) – directory which contains panoptic annotation images
panoptic_json (str) – path to the json panoptic annotation file

Both in COCO format.

see also https://detectron2.readthedocs.io/en/latest/modules/data.html#detectron2.data.datasets.register_coco_panoptic
