### ISSUE TITLE
what is the image size and images per iteration used in detectron2 benchmarks?

### ISSUE THREAD

**Issue by rbavery** [facebookresearch/detectron2#2635]
## 📚 Documentation
The TF Object Detection API reports that images are all 600x600 for their inference speed and accuracy benchmarks. What size were the images for the detectron [inference speed benchmarks](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-object-detection-baselines) and [training speed benchmarks](https://detectron2.readthedocs.io/en/latest/notes/benchmarks.html)? I'm mainly curious which framework is faster for inference and by how much. It looks like detectron2 reports inference in seconds per iteration while Tensorflow reports in seconds per image, so it would also be helpful to know how many images were used in each iteration for the benchmarks.

* Links to the relevant documentation/comment: https://detectron2.readthedocs.io/en/latest/notes/benchmarks.html
* because I'm interested to compare speed and accuracy performance with TF v1.5, also: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md#coco-trained-models

**Comment by ppwwyyxx** [comment]
> What size were the images for the detectron inference speed benchmarks and training speed benchmarks? 

This is defined by each config file. Most are 800x(800~1333).

> It looks like detectron2 reports inference in seconds per iteration

No we report seconds per img: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#coco-object-detection-baselines

**Comment by rbavery** [comment]
ah gotcha, I got mixed up with train time, which is reported in seconds per iteration. Thanks for the quick response!
