### ISSUE TITLE
where is the self.basez_lrs?

### ISSUE THREAD

**Issue by sophia-hxw** [facebookresearch/detectron2#264]
## ❓ where is the self.basez_lrs?

Thanks for the great work of detectron2.
I am reading the code in detectron2 and I am wonder that how can I find the definition of self.base_lrs in ./detectron2/solver/lr_scheduler.py line 44?

Thanks a lot~

`
    def get_lr(self) -> List[float]:
        warmup_factor = _get_warmup_factor_at_iter(
            self.warmup_method, self.last_epoch, self.warmup_iters, self.warmup_factor
        )
        return [
            base_lr * warmup_factor * self.gamma ** bisect_right(self.milestones, self.last_epoch)
            for base_lr in self.base_lrs
        ]

`

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

**Comment by bradezard131** [comment]
It's an inherited property from the superclass torch.optim.lr_scheduler._LRScheduler

**Comment by sophia-hxw** [comment]
@bradezard131 
OK, Thanks a lot~
