### ISSUE TITLE
Google colab' GPU out of memory

### ISSUE THREAD

**Issue by MISSEY** [facebookresearch/detectron2#2650]
1. Full runnable code or full changes you made:
```
from detectron2.engine import DefaultTrainer
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("street_val_dataset",)
cfg.DATASETS.TEST = ()

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300   # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.SOLVER.STEPS = []        # do not decay learning rate
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128 # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
cfg.INPUT.MIN_SIZE_TRAIN = (640,)

# cfg.MODEL.RPN.PRE_NMS_TOPK_TRAIN = 200
# cfg.MODEL.RPN.POST_NMS_TOPK_TRAIN = 200
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
 ```

  ```
  trainer = DefaultTrainer(cfg) 
  trainer.resume_or_load(resume=False)
  trainer.train()
  ```
Colab link : https://colab.research.google.com/drive/1go3bhqA_scpC4gg3nh2YelV0lAERJgNu?usp=sharing

Changed the dataset size, cfg.INPUT.MIN_SIZE_TRAIN = (640,) but still gpu run out of memory. 

What are the possible reasons ?? 

One reason may be the total number of instances which is 23531 (that is too high)

![detectron2_issues1](https://user-images.githubusercontent.com/11891755/108717878-15ca9a00-751e-11eb-914c-90a2e73955c7.png)

Please help

**Comment by ppwwyyxx** [comment]
From the logs it seems there is an average of 1000 objects per image - which will take a large amount of memory.
This is expected.

One possible approach that might help is to make our code support sparse matrices in pairwise box computation.

**Comment by MISSEY** [comment]
@ppwwyyxx Yes you are right, there are lots of objects per image, can you please tell me which file I should edit ?? 

Thank you so much

**Comment by KnightOfTheMoonlight** [comment]
One suggestion is to reduce `ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128`. Other suggestion is double-check other default ` BATCH_SIZE` settings.
