### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by xxsalehxx140** [facebookresearch/detectron2#2662]
When I try to run this cell 
```
!git clone https://github.com/facebookresearch/detectron2
!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --output video-output.mkv \
  --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl

```
I got this error 
```
fatal: destination path 'detectron2' already exists and is not an empty directory.
Traceback (most recent call last):
  File "detectron2/demo/demo.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```
 I search on the internet but I don’t find a solution to that.

**Comment by ppwwyyxx** [comment]
opencv is required to run the demo

**Comment by yunshiuan** [comment]
I'd like to follow up on this issue. I have installed opencv and can successfully import `cv2` (version 4.1.2). But I am running into the same issue when running the demo `!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --output video-output.mkv \
  --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl`.

I'd greatly appreciate any guidance. Thanks!
