### ISSUE TITLE
How FastRCNN can be deployed in C++?

### ISSUE THREAD

**Issue by deeplearning666** [facebookresearch/detectron2#2663]
Hello! It is an amazing projects!
I want to use FastRCNN in my C++ program. However, how can I use it? FastRCNN in detectron2 can work correctly in my python program. However, when I want to deploy it in my C++ program, I don't kow how to export the model for C++. 
I'm looking for ward to hearing from you soon!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html

**Comment by deeplearning666** [comment]
Hello! Thanks for replying! I have deployed FasterRCNN and MaskRCNN successfully in my C++ program according to the tutorials. However, FastRCNN need the proposals as input. How can I trace the FastRCNN models? What should I change in export_model.py and torchscript_traced_mask_rcnn.cpp?
Thanks for your replying soon!

**Comment by ppwwyyxx** [comment]
Sorry I misunderstood it for "Faster RCNN". We don't plan to support deploying FastRCNN, because it requires proposals and this means this model is rarely useful for any production.

**Comment by deeplearning666** [comment]
OK! If I want to use FastRCNN in my C++ program, may I deploy it in my C++ program by modifying code slightly? I know few about deployment, so I want to modify as few as possible to apply FastRCNN in my C++ program. Is Detectron2 a good choice?
