### ISSUE TITLE
Inference fails for script-exported torchscript model unless `export_torchscript_with_instances` is called first in same process

### ISSUE THREAD

**Issue by coreystatensg** [facebookresearch/detectron2#2665]
## Instructions To Reproduce the 🐛 Bug:

The following code executes successfully and saves a torchscript model to `model.pt`, then loads the saved model and successfully performs inference:
```
import torch
from torch import Tensor

from detectron2 import model_zoo
from detectron2.export.torchscript import export_torchscript_with_instances
from detectron2.structures import Boxes

if __name__ == '__main__':
    model = model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml", trained=True)
    model.eval()
    fields = {
        "proposal_boxes": Boxes,
        "objectness_logits": torch.Tensor,
        "pred_boxes": Boxes,
        "scores": torch.Tensor,
        "pred_classes": torch.Tensor,
        "pred_masks": torch.Tensor,
        "pred_keypoints": torch.Tensor,
        "pred_keypoint_heatmaps": torch.Tensor,
    }
    ts_model = export_torchscript_with_instances(model, fields)
    with open("model.pt", "wb") as f:
        torch.jit.save(ts_model, f)
    loaded = torch.jit.load("model.pt")
    sample_input = [{"image": torch.zeros((3,500,500))}]
    scripted_instance = loaded.inference(sample_input, do_postprocess=False)[0].to_instances()
```

However inference fails if you load the saved model in a separate process, without having first run `export_torchscript_with_instances`, e.g.:
```
import torch
from torch import Tensor

from detectron2 import model_zoo
from detectron2.export.torchscript import export_torchscript_with_instances
from detectron2.structures import Boxes

if __name__ == '__main__':
    loaded = torch.jit.load("model.pt")
    sample_input = [{"image": torch.zeros((3,500,500))}]
    scripted_instance = loaded.inference(sample_input, do_postprocess=False)[0].to_instances()
```
gives the following error message:
```
minimal_example.py:11: UserWarning: Output 0 of SelectBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:547.)
  scripted_instance = loaded.inference(sample_input, do_postprocess=False)[0].to_instances()
Traceback (most recent call last):
  File "minimal_example.py", line 11, in <module>
    scripted_instance = loaded.inference(sample_input, do_postprocess=False)[0].to_instances()
RuntimeError: classType INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/python/pybind_utils.h":724, please report a bug to PyTorch. 
```

Running `export_torchscript_with_instances` beforehand fixes the problem even if its output is not used; the following runs successfully:
```
import torch
from torch import Tensor

from detectron2 import model_zoo
from detectron2.export.torchscript import export_torchscript_with_instances
from detectron2.structures import Boxes

if __name__ == '__main__':
    model = model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml", trained=True)
    model.eval()
    fields = {
        "proposal_boxes": Boxes,
        "objectness_logits": torch.Tensor,
        "pred_boxes": Boxes,
        "scores": torch.Tensor,
        "pred_classes": torch.Tensor,
        "pred_masks": torch.Tensor,
        "pred_keypoints": torch.Tensor,
        "pred_keypoint_heatmaps": torch.Tensor,
    }
    export_torchscript_with_instances(model, fields)
    loaded = torch.jit.load("model.pt")
    sample_input = [{"image": torch.zeros((3,500,500))}]
    scripted_instance = loaded.inference(sample_input, do_postprocess=False)[0].to_instances()
```

## Expected behavior:

Inference with the loaded torchscript model should work without needing to call the `export_torchscript_with_instances` function first in the same process.

## Environment:

----------------------  --------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.7 (default, Feb 17 2021, 23:18:07) [GCC 10.2.0]
numpy                   1.20.1
detectron2              0.3 @/home/user/.local/share/virtualenvs/streamvision-swPxdcrg/lib/python3.8/site-packages/detectron2
Compiler                GCC 10.2
CUDA compiler           CUDA 11.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0.dev20210208+cu110 @/home/user/.local/share/virtualenvs/streamvision-swPxdcrg/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2               GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /opt/cuda
Pillow                  8.1.0
torchvision             0.9.0.dev20210211+cu110 @/home/user/.local/share/virtualenvs/streamvision-swPxdcrg/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.3.post20210225
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.0, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by ppwwyyxx** [comment]
This has the same cause as #2582.
