### ISSUE TITLE
Precomputed Proposals for VOC etc.

### ISSUE THREAD

**Issue by bradezard131** [facebookresearch/detectron2#271]
There is a demo for Fast R-CNN on COCO that uses precomputed proposals. Are proposals available for Pascal VOC too? Otherwise, is there any guide as to how to properly format the proposals if one were to try converting the original Matlab files?

**Comment by ppwwyyxx** [comment]
> Are proposals available for Pascal VOC too

no

> is there any guide as to how to properly format the proposals 

nothing official.
The code that loads the proposals are at https://github.com/facebookresearch/detectron2/blob/ffa5213215bc41681bbd5fb6a8ed96b2dfeea6dc/detectron2/data/build.py#L102
The proposal file is basically a dict with `boxes`, `scores` and `ids`. Each is a list with length=#images. 

The code may have some other assumptions, e.g. the dataset dicts may have to be sorted by image ids for this function to work. Improvements and more docs can be made but we likely won't work on it since Fast R-CNN is not commonly used by us.

**Comment by bradezard131** [comment]
Sure. I'm working on implementing some weakly-supervised models, which all use pre-computed proposals a-la Fast R-CNN, and are usually eval'd on VOC. I guess I'll see how I go with it, maybe try to submit some PRs to the docs once I find out how it works

**Comment by bradezard131** [comment]
Okay, so I've got some working proposals for VOC now, selective search so the scores are filler but otherwise good. You were correct about the dict needing to be sorted by image IDs. 

If I were going to add some info on this into the docs, where would be appropriate? The docs for the `load_proposals_into_dataset` function?

**Comment by ppwwyyxx** [comment]
Thanks! Some more docs in this function would be great. Sorting is just an implementation-specific limitations, and it would be good to implement it without relying on this assumption.

**Comment by bradezard131** [comment]
Oh just realised I still had this issue open. I do have some proposal files prepared for VOC now, if you'd be willing to host them alongside the COCO ones. They're from the .mat files for selective search from the original fast rcnn implementation, so the objectness scores are just straight 1s but otherwise fine.

If you'd rather not host them then I'll put them somewhere myself. Either way I think I can close the issue once I have a response one way or the other.

**Comment by ppwwyyxx** [comment]
I think we would rather not host them since we do not often work with either VOC or Fast R-CNN.

**Comment by JosephKJ** [comment]
Hi @bradezard131: Can you share your implementation of `load_proposals_into_dataset` for loading the Selective Search proposals? If you have it in a separate branch or fork, please do let me know, I can dig it up. 

Thanks!

**Comment by bradezard131** [comment]
my changes for loading the proposals were merged in #363 If you're looking for my converted VOC07 proposals I can upload them somewhere and provide a link
