### ISSUE TITLE
Detectron2 Tutorial is not working

### ISSUE THREAD

**Issue by jakee417** [facebookresearch/detectron2#2711]
## Instructions To Reproduce the 🐛 Bug:
1. Run second cell of Detectron2 Tutorial.ipynb (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5)
2. `import torch
assert torch.__version__.startswith("1.7")`

## Expected behavior:

I think torch was upgraded to 1.8.0 on Google Colab and now the tutorial isn't working? I am new to Detectron2 so unsure if this worked in the past.

## Environment:

Standard Google Colab session

**Comment by ShaneMoreno** [comment]
It was working earlier today but Google Collab upgraded to torch 1.8.0+cu101 

The second cell of Detectron2 Tutorial installs from the torch1.7 wheel. There is no torch1.8 wheel at the link below:
`!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html`

Please update. Thank you.

**Comment by sahilchinoy** [comment]
I'm running into the same issue; in case it's helpful, running `!pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2` at the top of the notebook seems to be a temporary fix.

**Comment by ppwwyyxx** [comment]
now upgraded to use torch 1.8
