### ISSUE TITLE
Error:"Unsupported gpu architecture 'compute_75'"

### ISSUE THREAD

**Issue by Alex-Sol** [facebookresearch/detectron2#272]
Thanks for your sharing,but when I install it on my compute ,I meet the error:"Unsupported gpu architecture 'compute_75'".

## Environment

RTX2060
CUDA9.2

python3.6.2
torch1.3.0

## What can I do to solve this problem?

**Comment by ppwwyyxx** [comment]
cuda 9.2 is old and cannot compile code that runs on RTX2060.
It's always better to include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Alex-Sol** [comment]
Thank you!
I need cuda10.x or cuda9.x？





------------------ Original ------------------

**Comment by ppwwyyxx** [comment]
you need at least cuda 10

**Comment by Alex-Sol** [comment]
Thank you very much!





------------------ Original ------------------
