### ISSUE TITLE
wrong torch version with dockerfile

### ISSUE THREAD

**Issue by heizie** [facebookresearch/detectron2#2720]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
FROM nvidia/cuda:10.1-cudnn7-devel
...
RUN pip install --user torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 -f https://download.pytorch.org/whl/cu101/torch_stable.html
...
RUN python -c "import torch; print(torch.__version__)"
```
2. What exact command you run:
```
docker build --build-arg USER_ID=$UID -t detectron2:v0 .

docker run -it -p 8888:8888 -p 6006:6006 \
  --shm-size=8gb --env="DISPLAY"   -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/lin/docker/:/home/appuser --gpus all \
  --name=detectron2 detectron2:v0 bash
```
3. __Full logs__ or other relevant observations:
```
 ---> 057086df642b
Step 25/26 : RUN python -c "import torch; print(torch.__version__)"
 ---> Running in 0ef6e05f89de
1.7.1+cu101
....
appuser@f6848a4acb9f:~$ python -c "import torch; print(torch.__version__)"
1.8.0
```

## Expected behavior:
I've changed the torch version to 1.71 in dockerfile, and let it print the version at the end of the dockerfile. seems nice, it shows 1.7.1, it is what i need.
But if i run inside the container, ` python -c "import torch; print(torch.__version__)"`
then it'll show it is version 1.8.0

And i've found that if i running in different workspace, not `appuser`, then the i'll got version 1.7.1
specifically, using different `WORKDIR` in Dockerfile, e.g. `WORKDIR /home/abc/detectron2_repo `

AND i've found torch 1.8 in ` /home/appuser/detectron2_repo'. why did this happen?
e.g.

AND if i don't add my extra volume,  then the i'll got version 1.7.1
```
...
 -v /tmp/.X11-unix:/tmp/.X11-unix:rw (without -v /home/lin/docker/:/home/appuser) 
...
```

## Environment:
nvidia/cuda:10.1-cudnn7-devel

**_BTW. you can't using torch 1.8 with cuda 10.1!!!!! pls fix this first!_**

**Comment by ppwwyyxx** [comment]
> AND i've found torch 1.8 in ` /home/appuser/detectron2_repo'. why did this happen?

Because you add extra volume `-v /home/lin/docker/:/home/appuser` it's not using what's in docker.

> BTW. you can't using torch 1.8 with cuda 10.1

Yes we can (e.g. https://download.pytorch.org/whl/cu101/torch-1.8.0%2Bcu101-cp36-cp36m-linux_x86_64.whl). Please file issues if otherwise.

**Comment by heizie** [comment]
> Because you add extra volume `-v /home/lin/docker/:/home/appuser` it's not using what's in docker.
this type of volume allows you to get access to your other directories. What I've found important is, there is something weird inside the `/home/appuser`. When i "combind" the volume with `-v /home/lin/docker/:/home/appuser`, then it'll show you the pytorch 1.8. I can tell you that, in my system there is nothing relative to pytorch. 

>Yes we can (e.g. https://download.pytorch.org/whl/cu101/torch-1.8.0%2Bcu101-cp36-cp36m-linux_x86_64.whl). Please file issues if otherwise.
NO you can't. Why i'm doing this is not just for fun. Just try to using the docker file and run whatever demo you want. then it'll show something like 
`linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv`
and pls read again the official website like you said in the dockerfile, if you using 1.8 version, then the ony choice is cuda 10.1 
https://pytorch.org/get-started/locally/
