### ISSUE TITLE
No local packages or working download links found for fvcore

### ISSUE THREAD

**Issue by baiyubaiyu** [facebookresearch/detectron2#273]

**Comment by yangyu12** [comment]
The same problem occurred to me. Solved by manually installing it.
`pip install git+https://github.com/facebookresearch/fvcore.git`

**Comment by ppwwyyxx** [comment]
The `setup.py` has fvcore as well as its download link: https://github.com/facebookresearch/detectron2/blob/master/setup.py.

When installing detectron2, pip or setuptools should know where to look for fvcore from this file. 
Is this mechanism not working for you? Could you be more clear about __what you did__ and __what errors you saw__ ?

**Comment by baiyubaiyu** [comment]
多谢，我手动装了fvcore，然后在setup中将fvcore一行注释掉，重新运行即可。（写中文了，受不了我自己的渣渣英语了）

**Comment by ppwwyyxx** [comment]
We've found that the issue is caused by https://github.com/facebookresearch/detectron2/pull/225 and we will revert it

**Comment by yangyu12** [comment]
Sorry for the late response. 
- What I did: install the detectron2 as `python setup.py build develop`
- What errors I saw: everything is good except following error information:
`Searching for fvcore@ git+https://github.com/facebookresearch/fvcore.git
Reading https://pypi.org/simple/fvcore/
Couldn't find index page for 'fvcore' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for fvcore@ git+https://github.com/facebookresearch/fvcore.git
error: Could not find suitable distribution for Requirement.parse('fvcore@ git+https://github.com/facebookresearch/fvcore.git')`

- What I did to solve it: manually install fvcore by `pip install git+https://github.com/facebookresearch/fvcore.git`

I think you may already find out the problem. Thanks anyway!
