### ISSUE TITLE
MetadataCatalog.get("my_dataset") shows inconsistent behavior over multiple runs

### ISSUE THREAD

**Issue by PrabhjotKaurGosal** [facebookresearch/detectron2#2735]
1. Full runnable code or full changes you made:
```
<from detectron2.data.datasets import register_coco_instances
register_coco_instances("my_dataset, {}, "/path/to/json/file/annotations.json", "path to the images folder")
my_dataset_metadata = MetadataCatalog.get("my_dataset")
print(my_dataset_metadata>
```
2. What exact command you run:
```
<my_dataset_metadata = MetadataCatalog.get("my_dataset")
print(my_dataset_metadata)>
```
3. __Full logs__ or other relevant observations:
```
I have observed that when I try to register the data and metadata, and then print the metadata after registering. I do not see the thing_classes and thing_dataset_id_to_contiguous_id in the first few runs. Below is what I see for the first few runs.
But after several runs, thing_classes and thing_dataset_id_to_contiguous starts appear.  I am not sure why this function is behaving this way. 

```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

Metadata(evaluator_type='coco', image_root='/path/to/images', json_file='/path/to/json/file/annotations.json', name='my_dataset', thing_classes=['OBJDET', '0', '1', '2', '3'], thing_dataset_id_to_contiguous_id={0: 0, 1: 1, 2: 2, 3: 3, 4: 4})

I have observed that when I try to register the data and metadata, and then print the metadata after registering. I do not see the thing_classes and thing_dataset_id_to_contiguous_id in the first few runs. Below is what I see for the first few runs.
But after several runs, thing_classes and thing_dataset_id_to_contiguous starts appear.  I am not sure why this function is behaving this way. 

Metadata(evaluator_type='coco', image_root='/path/to/images', json_file='/path/to/json/file/annotations.json', name='my_dataset')

My dataset is already in the COCO format and I am able to confirm that the bounding boxes are correct through visualization of random images from the dataset.

## Environment:

Provide your environment information using the following command:
```
Python 3.8
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
Please provide code that others can run to reproduce the issue

**Comment by PrabhjotKaurGosal** [comment]
@ppwwyyxx The code above is all I have. After installing detectron2 and all other dependencies, I try to register my custom dataset and its metadata, using register_coco_instances()  and my_dataset_metadata = MetadataCatalog.get("my_dataset") MetadataCatalog.get("my_dataset"), respectively. . .  After that, I simply try to see the output of the metadata by using the print(my_dataset_metadata = MetadataCatalog.get("my_dataset")) command.

**Comment by PrabhjotKaurGosal** [comment]
Here is more information on what I have observed since my last post.

```
from detectron2.data.datasets import register_coco_instances
register_coco_instances("RF_train", {}, "/home/jyoti/Desktop/csc8800/datasets/Roboflow/train/_annotations.coco.json", "/home/jyoti/Desktop/csc8800/datasets/Roboflow/train")
register_coco_instances("RF_test", {}, "/home/jyoti/Desktop/csc8800/datasets/Roboflow/valid/_annotations.coco.json", "/home/jyoti/Desktop/csc8800/datasets/Roboflow/valid")
RF_metadata = MetadataCatalog.get("RF_train")

```

**Comment by ppwwyyxx** [comment]
The code cannot be run by other people, therefore we cannot use it to reproduce the issue. Please provide ways to reproduce the issue.

> I am unsure why calling DatasetCatalog.get("dataset_name ") would alter the metadata output.

Because data (and metadata) is loaded when you call this function to get them, so this is not unexpected.
