### ISSUE TITLE
Potential bug in visualizer.py

### ISSUE THREAD

**Issue by tenres** [facebookresearch/detectron2#2739]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
Following the balloon example for training on a custom data set. Error happens before training, when verifying annotations. Can be reproduced by saving the bounding box annotations in XYWH_ABS format instead of XYXY_ABS like in the balloon example. 
```
2. What exact command you run:
Following all the steps of the balloon example as is, the error occurs at "out = visualizer.draw_dataset_dict(d)".

3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/utils/visualizer.py", line 521, in draw_dataset_dict
  File "/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/utils/visualizer.py", line 521, in <listcomp>
  File "/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/structures/boxes.py", line 74, in convert
    ] and from_mode.value not in [
AttributeError: 'int' object has no attribute 'value'```

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:
The issue seems to be that in visualizer.draw_dataset_dict(), the line:
boxes = [BoxMode.convert(x["bbox"], x["bbox_mode"], BoxMode.XYXY_ABS) for x in annos]
calls convert by passing just the integers x["bbox_mode"], BoxMode.XYXY_ABS, whereas convert is expecting BoxMode. Hence, the from_mode.value and to_mode.value errors. Note that this is not an issue when the two modes are the same since convert() returns immediately and .value is not run. Changing the line to: 
boxes = [BoxMode.convert(x["bbox"], BoxMode(x["bbox_mode"]), BoxMode(BoxMode.XYXY_ABS)) for x in annos] doesn't error.

## Environment:

Provide your environment information using the following command:
```
----------------------  ---------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.2.1 @/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.0
detectron2 arch flags   sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 Quadro RTX 8000
CUDA_HOME               /usr
Pillow                  8.1.2
torchvision             0.5.0 @/home/user/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.3.post20210306
cv2                     3.4.2
----------------------  ---------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
> Following the balloon example for training on a custom data set. ... Can be reproduced by saving the bounding box annotations in XYWH_ABS format instead of XYXY_ ...

This is not done in the balloon example. 

Since some custom code is added that causes the error, please provide ways for others to reproduce the error.

**Comment by tenres** [comment]
Thanks for looking into this.

The error can be reproduced by following the balloon example as is and changing two lines in def get_balloon_dicts(img_dir):
Current:
"bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
"bbox_mode": BoxMode.XYXY_ABS,
Changed:
"bbox": [np.min(px), np.min(py), np.max(px)-np.min(px), np.max(py)-np.min(py)],
"bbox_mode": BoxMode.XYWH_ABS,
 
The error is not related to custom code, but the argument mismatch between lines:
boxes = [BoxMode.convert(x["bbox"], x["bbox_mode"], BoxMode.XYXY_ABS) for x in annos] in visualizer.draw_dataset_dict()
and
def convert(box: _RawBoxType, from_mode: "BoxMode", to_mode: "BoxMode") -> _RawBoxType: in boxes.py

convert is expecting BoxMode and not just an integer. Hence when it calls from_mode.value on the passed x["bbox_mode"], it throws the above error. With the below change, it doesn't error any more:
boxes = [BoxMode.convert(x["bbox"], BoxMode(x["bbox_mode"]), BoxMode(BoxMode.XYXY_ABS)) for x in annos]

**Comment by ppwwyyxx** [comment]
> The error can be reproduced by following the balloon example as is and changing two lines in def get_balloon_dicts

No it runs correctly after making this change: https://colab.research.google.com/drive/1LYbZ1vjM_zE9_qK18IHJ_YF5mTrTczJh

Please provide ways for others to reproduce the error.

**Comment by tenres** [comment]
I can confirm the issue is on my side. I had read the balloon data json into the required structure like in the example, but had written that to file again for some reason. Now, when I read that file back into my code, the "bbox_mode" enums are no longer enums but just integers. Hence, I was passing "bbox_mode" as integers to visualizer.py, which was throwing an error upon calling .value on them. After converting the bbox_mode to BoxMode enum again, there was no error. 

Thanks for your support!
