### ISSUE TITLE
Update from v0.3 Prebuild for linux to v0.4

### ISSUE THREAD

**Issue by Harry-Rogers** [facebookresearch/detectron2#2749]
## 📚 Documentation

* Links to the relevant documentation/comment:
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md

In the above installation process there is no mention of being able to upgrade from one version to another regarding the prebuilt linux version. Is it possible to add documentation for this? 

I'm currently trying to update my prebuilt version from v0.3 to v0.4 since this was released a few days ago.

**Comment by ppwwyyxx** [comment]
Same as all python packages: optionally uninstall the old version, and install the new one. I don't feel this needs to be explicitly documented
