### ISSUE TITLE
How to produce results on COCO test-dev? Thank you.

### ISSUE THREAD

**Issue by ChenJoya** [facebookresearch/detectron2#275]
## ❓ Questions and Help

Hi, I have tried to incorporate ```"coco_2017_testdev": ("coco/test2017", "coco/annotations/image_info_test-dev2017.json"),``` with ```detectron2/data/datasets/builtin.py``` to produce results on COCO test-dev, but it encounter this issue:

```
File "/home/.../lib/python3.7/site-packages/pycocotools/coco.py", line 142, in getAnnIds
    anns = self.dataset['annotations']
KeyError: 'annotations'
```

What should we do for producing results on ```coco_2017_testdev```? Thanks!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/83670010fdf6a646b77bf0b5cefafa1b804a8c6c/detectron2/evaluation/coco_evaluation.py#L57-L59

we only tested this for lvis but seems like this line does not work for COCO.

**Comment by ChenJoya** [comment]
Pretty good. Thanks!
