### ISSUE TITLE
Use PyTorch core for some utils in utils/comm.py

### ISSUE THREAD

**Issue by rohan-varma** [facebookresearch/detectron2#2750]
## Use PyTorch core for some utils in utils/comm.py

The distributed utils file over at https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/comm.py has some APIs to perform all_gather, gather, etc on arbitrary pickable data. As of 1.8, PyTorch now provides these features natively, so it would be great to move these utils to use those APIs so that we can eliminate unnecessary code and benefit from upstream PyTorch improvements.

Happy to send the PR as needed

**Comment by ppwwyyxx** [comment]
Thanks for bringing this up! We have this task (T78636059) but currently we can't switch because we still support pytorch 1.6. Maybe we can start with trying the version in pytorch under `if TORCH_VERSION > ...` just to make the transition smoother.

**Comment by Epiphqny** [comment]
Hi @rohan-varma , I am also confused by this problem, could you open-source the code? Thank you very much.
