### ISSUE TITLE
RegNetY Backbone

### ISSUE THREAD

**Issue by imjwang** [facebookresearch/detectron2#2751]
## 🚀 Feature
Release RegNetY backbone family from [SEER](https://arxiv.org/pdf/2103.01988.pdf?fbclid=IwAR1P6PN8B7U1Aq3d2lr8KD2Fm71bnCLaS-NE4PSQKQrQ_PHfyw8GVYWHQ1Q) pretrained on 1B Instagram pictures.

## Motivation & Examples
The pretrained RegNets seem like great few shot learners. Maybe they will be great for downstream tasks with limited data.

I could not find the model on VISSL.

**Comment by ppwwyyxx** [comment]
Please ask in the vissl project instead.
