### ISSUE TITLE
About changing the working directory

### ISSUE THREAD

**Issue by kangmintong** [facebookresearch/detectron2#2752]
When using detectron2, I got the error 'ImportError: cannot import name '_C' from 'detectron2'' first and after changing the working directory I found it work well for this problem. 
But after changing the working directory, it reports 'KeyError: 'Non-existent config key:{xx}' . I actually have the config key in ./detectron2/config/defaults.py  but it still have the error. Someone said that the problem lay in the working directory(it should be the root directory of detectron2).
So I'm confused about how to solve it. I'll appreciate it if you can provide me any help.

**Comment by deepakksingh** [comment]
You may trying rebuilding detectron2 and also look at FAQ section for the error `cannot import name '_C' `
