### ISSUE TITLE
Panoptic DeepLab error while training

### ISSUE THREAD

**Issue by matteosodano** [facebookresearch/detectron2#2753]
I am trying to run [Panoptic DeepLab](https://github.com/facebookresearch/detectron2/tree/master/projects/Panoptic-DeepLab) on my machine. I already have downloaded the CityScape dataset and organized it as required [here](https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html#expected-dataset-structure-for-cityscapes).
When running:
`python train_net.py --config-file configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_dsconv.yaml --num-gpus 1`,
I find out the following error:
`Traceback (most recent call last):`
  `File "train_net.py", line 170, in <module>
    launch(`
  `File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)`
  `File "train_net.py", line 152, in main
    cfg = setup(args)`
  `File "train_net.py", line 144, in setup
    cfg.merge_from_file(args.config_file)`
  `File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)`
  `File "/home/matteo/.local/lib/python3.8/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)`
  `File "/home/matteo/.local/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])`
  `File "/home/matteo/.local/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])`
  `File "/home/matteo/.local/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])`
  `File "/home/matteo/.local/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))`
`KeyError: 'Non-existent config key: MODEL.SEM_SEG_HEAD.USE_DEPTHWISE_SEPARABLE_CONV'
`

However, in the file `path/to/detectron2/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_dsconv.yaml` there is 
`SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True` under `MODEL`. 

Moreover, in the file `train_net.py`, the function `setup(args)` looks like this:
    `def setup(args):`  
        `cfg = get_cfg()`
    `add_panoptic_deeplab_config(cfg)`
    `cfg.merge_from_file(args.config_file)`
    `cfg.merge_from_list(args.opts)`
    `cfg.freeze()`
    `default_setup(cfg, args)`
    `return cfg`

General information:
- Ubuntu 20.04
- Python 3.8.5
- Pytorch 1.7.1
- Torchvision 0.8.2
- Cuda 11.2

Any hint?

**Comment by ppwwyyxx** [comment]
I ran this command: `python train_net.py --config-file configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024_dsconv.yaml --num-gpus 1` and did not see the error.

Please provide ways to reproduce the issue.

**Comment by matteosodano** [comment]
I have nothing to add: I only [installed](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) Detectron2, run the demo and then tried Panoptic DeepLab.
Can you share the content of the `setup(args)` function you have? I see that lots of people have had the same problem and there was an `add_something_config(cfg)` missing there. Maybe it's my case too.
Also, if you can share your `yaml` file(s) it would be great.

**Comment by matteosodano** [comment]
A short edit that may be useful: if I comment the two lines corresponding to the `SEM_SEG_HEAD` in the config file, I obtain the exact same error with `MODEL.PANOPTIC_DEEPLAB.USE_DEPTHWISE_SEPARABLE_CONV`.
It seems like the config file is not read correctly for some reason.

**Comment by ppwwyyxx** [comment]
I think you're experiencing this issue: https://detectron2.readthedocs.io/en/latest/tutorials/install.html#install-pre-built-detectron2-linux-only

> New packages are released every few months. Therefore, packages may not contain latest features in the master branch and may not be compatible with the master branch of a research project that uses detectron2 (e.g. those in projects/).

Still, reproducible instructions are required before we could investigate it.

**Comment by matteosodano** [comment]
For reproducibility:
- environment: Ubuntu 20.04 with Python 3.8.5, Pytorch 1.7.1, Torchvision 0.8.2, Cuda 11.2.
- installation: from [pre-built package]{https://detectron2.readthedocs.io/en/latest/tutorials/install.html#install-pre-built-detectron2-linux-only}
- dataset: [CityScapes]{https://www.cityscapes-dataset.com/downloads/} organized as required [here]{https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html#expected-dataset-structure-for-cityscapes} (downloaded `gtFine_trainvaltest.zip (241MB) [md5]` and `leftImg8bit_trainvaltest.zip (11GB) [md5]`, then run the scripts as in the previously-linked page).
- run: as pointed out above in the first message.


(probably useless info, but still...) My work environment: `~/detectron2`. Inside here:
- `.../datasets/cityscapes/` with `gtFine` and `leftImg8bit` (and subfolders/subfiles as required)
- `.../projects/Panoptic-DeepLab/` with the training file and the `configs` folder
- everything else.


I didn't modify anything about the downloaded code yet, so there is nothing else to notify.


If I'm experiencing the issue you pointed out, what do you suggest?

**Comment by matteosodano** [comment]
I also attach the list of installed packages:

> Package                              Version              Location
------------------------------------ -------------------- -----------------------------------------------------------------
absl-py                              0.11.0
appdirs                              1.4.4
apturl                               0.5.2
argcomplete                          1.12.2
astunparse                           1.6.3
atomicwrites                         1.1.5
attrs                                19.3.0
bcrypt                               3.1.7
beautifulsoup4                       4.8.2
blinker                              1.4
Brlapi                               0.7.0
cachetools                           4.2.1
catkin-pkg                           0.4.23
catkin-pkg-modules                   0.4.23
certifi                              2019.11.28
chardet                              3.0.4
cityscapesScripts                    2.2.0
Click                                7.0
cloudpickle                          1.6.0
colcon-argcomplete                   0.3.3
colcon-bash                          0.4.2
colcon-cd                            0.1.1
colcon-cmake                         0.2.26
colcon-common-extensions             0.2.1
colcon-core                          0.6.1
colcon-defaults                      0.2.5
colcon-devtools                      0.2.2
colcon-library-path                  0.2.1
colcon-metadata                      0.2.5
colcon-notification                  0.2.13
colcon-output                        0.2.12
colcon-package-information           0.3.3
colcon-package-selection             0.2.10
colcon-parallel-executor             0.2.4
colcon-pkg-config                    0.1.0
colcon-powershell                    0.3.6
colcon-python-setup-py               0.2.7
colcon-recursive-crawl               0.2.1
colcon-ros                           0.3.21
colcon-test-result                   0.3.8
colcon-zsh                           0.4.0
colorama                             0.4.3
coloredlogs                          15.0
command-not-found                    0.3
cov-core                             1.15.0
coverage                             4.5.2
cryptography                         2.8
cupshelpers                          1.0
cycler                               0.10.0
Cython                               0.29.22
dbus-python                          1.2.16
defer                                1.0.6
detectron2                           0.3+cu110
distlib                              0.3.0
distro                               1.4.0
distro-info                          0.23ubuntu1
docutils                             0.16
duplicity                            0.8.12.0
empy                                 3.3.2
entrypoints                          0.3
fasteners                            0.14.1
flake8                               3.7.9
flake8-blind-except                  0.2.0
flake8-builtins                      1.5.3
flake8-class-newline                 1.6.0
flake8-comprehensions                3.3.1
flake8-deprecated                    1.3
flake8-docstrings                    1.5.0
flake8-import-order                  0.18.1
flake8-quotes                        3.2.0
flatbuffers                          1.12
future                               0.18.2
fvcore                               0.1.3.post20210310
gast                                 0.3.3
google-auth                          1.27.0
google-auth-oauthlib                 0.4.2
google-pasta                         0.2.0
grpcio                               1.32.0
h5py                                 2.10.0
html5lib                             1.0.1
httplib2                             0.14.0
humanfriendly                        9.1
idna                                 2.8
ifcfg                                0.18
importlib-metadata                   1.5.0
iniconfig                            1.1.1
iopath                               0.1.4
Keras-Preprocessing                  1.1.2
keyring                              18.0.1
kiwisolver                           1.0.1
language-selector                    0.1
lark-parser                          0.8.1
launchpadlib                         1.10.13
lazr.restfulclient                   0.14.2
lazr.uri                             1.0.3
lockfile                             0.12.2
louis                                3.12.0
lxml                                 4.5.0
macaroonbakery                       1.3.1
Mako                                 1.1.0
Markdown                             3.3.4
MarkupSafe                           1.1.0
matplotlib                           3.1.2
mccabe                               0.6.1
mock                                 3.0.5
monotonic                            1.5
more-itertools                       4.2.0
mypy                                 0.761
mypy-extensions                      0.4.3
netifaces                            0.10.4
nose                                 1.3.7
nose2                                0.9.1
notify2                              0.3
numpy                                1.19.5
oauthlib                             3.1.0
olefile                              0.46
opencv-python                        4.5.1.48
opt-einsum                           3.3.0
packaging                            20.3
panopticapi                          0.1
paramiko                             2.6.0
pbr                                  5.4.5
pexpect                              4.6.0
Pillow                               8.1.2
pip                                  21.0.1
pluggy                               0.13.0
portalocker                          2.2.1
protobuf                             3.15.3
psutil                               5.5.1
py                                   1.10.0
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pycairo                              1.16.2
pycocotools                          2.0.2
pycodestyle                          2.5.0
pycups                               1.9.73
pydocstyle                           2.1.1
pydot                                1.4.1
pyflakes                             2.1.1
Pygments                             2.3.1
PyGObject                            3.36.0
pygraphviz                           1.5
PyJWT                                1.7.1
pymacaroons                          0.13.0
PyNaCl                               1.3.0
pyparsing                            2.4.6
PyQt5                                5.14.1
pyquaternion                         0.9.9
pyRFC3339                            1.1
pytest                               6.2.2
pytest-cov                           2.8.1
pytest-mock                          1.10.4
pytest-repeat                        0.9.1
pytest-rerunfailures                 9.1.1
python-apt                           2.0.0+ubuntu0.20.4.4
python-dateutil                      2.7.3
python-debian                        0.1.36ubuntu1
pytz                                 2019.3
pyxdg                                0.26
PyYAML                               5.3.1
reportlab                            3.5.34
requests                             2.22.0
requests-oauthlib                    1.3.0
requests-unixsocket                  0.2.0
roman                                2.0.0
rosdep                               0.20.0
rosdep-modules                       0.20.0
rosdistro                            0.8.3
rosdistro-modules                    0.8.3
rospkg                               1.2.10
rospkg-modules                       1.2.10
rsa                                  4.7.2
scipy                                1.6.1
screen-resolution-extra              0.0.0
SecretStorage                        2.3.1
setuptools                           45.2.0
simplejson                           3.16.0
sip                                  4.19.21
six                                  1.15.0
snowballstemmer                      2.0.0
soupsieve                            1.9.5
ssh-import-id                        5.10
systemd-python                       234
tabulate                             0.8.9
tensorboard                          2.4.1
tensorboard-plugin-wit               1.8.0
tensorflow                           2.4.1
tensorflow-estimator                 2.4.0
termcolor                            1.1.0
toml                                 0.10.2
torch                                1.7.1
torchvision                          0.8.2
tqdm                                 4.59.0
typed-ast                            1.4.1
typing                               3.7.4.3
typing-extensions                    3.7.4.3
ubuntu-advantage-tools               20.3
ubuntu-drivers-common                0.0.0
ufw                                  0.36
unattended-upgrades                  0.1
urllib3                              1.25.8
usb-creator                          0.3.7
vcstool                              0.2.15
wadllib                              1.3.3
wcwidth                              0.1.8
webencodings                         0.5.1
Werkzeug                             1.0.1
wheel                                0.36.2
wrapt                                1.12.1
xkit                                 0.0.0
yacs                                 0.1.8
zipp                                 1.0.0

**Comment by ppwwyyxx** [comment]
The issue template has provided a better way to collect environment information.

> If I'm experiencing the issue you pointed out, what do you suggest?

If you have to use detectron2 v0.3, you should clone the v0.3 version and use PanopticDeeplab from there. And vice-versa
