### ISSUE TITLE
Training keypoints + detection heads jointly 

### ISSUE THREAD

**Issue by ashkanaev** [facebookresearch/detectron2#276]
Hi!
Is it possible to train multi head network using detectron2? i want to train a model with keypoints head and detection head on COCO dataset. I haven't found any sort of config for such a task. 
What needs to be done for launch training? 
Thanks!

**Comment by ppwwyyxx** [comment]
All existing keypoint configs train a object detection head because this is how keypoint r-cnn works.

**Comment by ashkanaev** [comment]
Does it mean object detection head train for whole list of classes or only for persone?

ps: Thanks for really fast reply )

**Comment by ppwwyyxx** [comment]
It trains only for person as the dataset it uses only contains person annotations.

**Comment by ashkanaev** [comment]
what if to train separately: firstly start training for object detection head for all classes and then start training keypoints head (penalize person prediction only). Could it be the way how to join detection + keypoints? Or there is any other solution?
