### ISSUE TITLE
ColorMode.IMAGE_BW fails to "Remove the colors of unsegmented pixels"

### ISSUE THREAD

**Issue by gulmert89** [facebookresearch/detectron2#2760]
Hello folks,

This will be a short one: 
On the **Detectron2 Tutorial** [notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5), under the ***Inference & evaluation using the trained model*** title, one can see that the unsegmented pixels are converted to black & white format i.e. their colors are removed as stated. Only the balloons have the colors. 

However, while I was studying, I saw that even though the <code>ColorMode.IMAGE_BW</code> was specified as the<code>instance_mode</code> by default, the images appeared in color entirely. Tweaking with the instance_mode didn't change anything.

This is the original version of the notebook which was run on July 9, 2020 for the last time.
You can see that it is just fine:
![original](https://user-images.githubusercontent.com/60785603/111482469-fac9ff00-8744-11eb-9b7c-68228d2dd174.jpg)

Then I rerun the original notebook without changing anything at all throught it 
and the result was the same. It didn't remove the colors of the unsegmented parts.

![new](https://user-images.githubusercontent.com/60785603/111483875-45984680-8746-11eb-994a-701868651ed2.jpg)

Has anyone experienced it? Am I missing something?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ashutoshbk** [comment]
I am also facing same issue. It was working correctly yesterday. but now without change single line of code I am facing this issue. My image inference is black and white.

**Comment by Ziyadmysterio** [comment]
Any leads on this? I got the same issue after re running the model several times. First few iterations it was fine . The error started popping up without any change to the code
