### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by AjayPayattuparambil** [facebookresearch/detectron2#2766]
Hi,
    I installed detecrton2 in Ubuntu 18.04 with pytorch 1.7. No GPU present in the system. When  the installation shown issues I tried GPU version also. I can import detectron2.config import get_cfg. But when I tried importing other methods like model_zoo, predictor etc. It's showing this error.

>>> import detectron2
>>> from detectron2 import model_zoo
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/model_zoo/__ init__.py", line 7, in <module>
from .model_zoo import get, get_config_file, get_checkpoint_url
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/model_zoo/mo del_zoo.py", line 8, in <module>
from detectron2.modeling import build_model
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/modeling/__i nit__.py", line 2, in <module>
from detectron2.layers import ShapeSpec
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/layers/__ini t__.py", line 3, in <module>
from .deform_conv import DeformConv, ModulatedDeformConv
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/layers/defor m_conv.py", line 10, in <module>
from detectron2 import _C
ImportError: /home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/_C.cpyt hon-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDat aInstanceISt7complexIfEEEPKNS_6detail12TypeMetaDataEv
>>> File "<stdin>", line 1, in <module>
File "<stdin>", line 1
File "<stdin>", line 1, in <module>
^
IndentationError: unexpected indent
>>> File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/model_zoo/__ init__.py", line 7, in <module>
File "<stdin>", line 1
File "/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2/model_zoo/__ init__.py", line 7, in <module>
^
IndentationError: unexpected indent

I tried solutions for common issues provided here: [https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md](url)

But the issue still persist. 

Any help would be appreciated. 

I tried running the code below. But no output was there.
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

**Comment by ppwwyyxx** [comment]
> I tried running the code below. But no output was there.

This might be due to a networking issue. removing `-q` from the command should provide more information

**Comment by AjayPayattuparambil** [comment]
Thanks. Let me check

**Comment by AjayPayattuparambil** [comment]
Tried running the command without -q and sharing the results.

No CUDA runtime is found, using CUDA_HOME='/home/crsi/anaconda3'
--------------------- -------------------------------------------------------------------
sys.platform linux
Python 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0]
numpy 1.19.2
detectron2 0.2 @/home/crsi/anaconda3/lib/python3.7/site-packages/detectron2
detectron2._C failed to import
Compiler c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
DETECTRON2_ENV_MODULE <not set>
PyTorch 1.7.1 @/home/crsi/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build False
GPU available False
Pillow 8.1.2
torchvision 0.8.2 @/home/crsi/anaconda3/lib/python3.7/site-packages/torchvision
fvcore 0.1.3.post20210223
cv2 4.5.1
--------------------- -------------------------------------------------------------------
PyTorch built with:
- GCC 7.3
- C++ Version: 201402
- Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- NNPACK is enabled
- CPU capability usage: AVX2
- Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by ppwwyyxx** [comment]
How did you install detectron2?

According to https://github.com/facebookresearch/detectron2/releases, detectron2 0.2 does not support pytorch 1.7

**Comment by AjayPayattuparambil** [comment]
I followed instructions provided here: https://detectron2.readthedocs.io/en/latest/tutorials/install.html

**Comment by ppwwyyxx** [comment]
The above link provides many options. Could you copy paste what exactly you did?

**Comment by AjayPayattuparambil** [comment]
Used this command : python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.7/index.html

**Comment by ppwwyyxx** [comment]
If this is successful, then you'll not obtain the environment information provided earlier, because https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.7/index.html does not contain detectron2 0.2.

**Comment by AjayPayattuparambil** [comment]
Actually, I tried Anaconda also.(conda install -c conda-forge detectron2   link:https://anaconda.org/conda-forge/detectron2/files).  That may be the reason environment information showing detectron2 0.2

**Comment by ppwwyyxx** [comment]
detectron2 from conda-forge (in fact, probably anything from conda-forge) is non-official and unmaintained. It's not in our official instructions and should not be used

**Comment by AjayPayattuparambil** [comment]
Ok, Thanks
