### ISSUE TITLE
Does the model save automatically during training, if no where to add that?

### ISSUE THREAD

**Issue by Dayan-Zhanchi** [facebookresearch/detectron2#277]
## ❓ Questions and Help

Does the model save automatically when being trained or do we have to add that? If we have to add it where would be a good place to do it if we want to save for every epoch instead of at the very end of the training?

**Comment by ppwwyyxx** [comment]
controlled by config `SOLVER.CHECKPONT_PERIOD`.

**Comment by jas-nat** [comment]
How to save the model in .pth format? If using cfg.OUTPUT_DIR is the answer, why can I not find the output in the current directory I use?

**Comment by ppwwyyxx** [comment]
It is saved every `SOLVER.CHECKPOINT_PERIOD` iterations.

**Comment by jas-nat** [comment]
> It is saved every `SOLVER.CHECKPOINT_PERIOD` iterations.

Sorry I cannot find the documentation in the documentation website. How to export it into model.pth format?

**Comment by ppwwyyxx** [comment]
The model will be saved to `.pth` format during training after every SOLVER.CHECKPOINT_PERIOD iterations.

**Comment by jas-nat** [comment]
Can we rename the model_final.pth ?

**Comment by ppwwyyxx** [comment]
You cannot choose the name. You can rename it after it is saved.
