### ISSUE TITLE
detectron2 0.4, compile windows, pip._vendor.pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by apiszcz** [facebookresearch/detectron2#2796]
Detectron2 will not build with fvcore 0.1.4?
Python 3.7
Windows 10/64
Is there a fix?

pip._vendor.pkg_resources.ContextualVersionConflict: (fvcore 0.1.4 (C:\python\lib\site-packages), Requirement.parse('fvcore<0.1.4,>=0.1.3'), {'detectron2'})

**Comment by ppwwyyxx** [comment]
The latest version does support fvcore 0.1.4.

For the old version - we don't know.
