### ISSUE TITLE
How to train on a subset of training dataset?

### ISSUE THREAD

**Issue by Dayan-Zhanchi** [facebookresearch/detectron2#280]
## ❓ Questions and Help

Is there an easy way to train on a subset of a training dataset? Let's say I originally have a training dataset of size 10k, but only want to train on 100 samples from the original training dataset. Is there an easy way to achieve this, or does the current code not support this functionality and instead I have to change the code in how the dataset is registered? For instance I could maybe modify the for loop in the load_coco_json function in coco.py file to only create x amount of records that are appended to the dataset_dicts list?

I know that you can use DatasetCatalog.get(name_of_dataset) to get a dataset dictionary and then extract a subset from that, but when training and in particular using the DefaultTrainer, it requires a config object and not a dataset dictionary. So that's why I later thought that maybe I need to somehow change the code in how the dataset is registered.

**Comment by ppwwyyxx** [comment]
You should register a new dataset.

**Comment by Dayan-Zhanchi** [comment]
Then that means I have to mess with my original training dataset file, as in I have to create new files containing a subset of the original training dataset file? What if I merely want to extract a subset of my original training dataset in the code and then train that without having to provide a new file that contains the subset of the original training dataset?

**Comment by ppwwyyxx** [comment]
You register a function when registering a new dataset, so you can do whatever you want in that function. Whether you want to mess up with the original dataset in that function is up to you.

**Comment by Dayan-Zhanchi** [comment]
yea okay, and that function is load_coco_json? If I want to extract a subset of my dataset then I have to change the for loop in load_coco_json function I'm guessing?

**Comment by ppwwyyxx** [comment]
You can call `load_coco_json` in your own function and return a subset of the results in your own function.

**Comment by Dayan-Zhanchi** [comment]
Fair enough, thank you! I'll close this issue now
