### ISSUE TITLE
I want to change  model  to  only onnx model that  it doesn.t have ops._caffe2.op  ? 

### ISSUE THREAD

**Issue by XUDINGYI312** [facebookresearch/detectron2#2817]
I have  build  the modle。

    torch_model = Trainer.build_model(cfg)
    DetectionCheckpointer(torch_model).resume_or_load(cfg.MODEL.WEIGHTS)
    torch_model.eval()
 data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
    first_batch = next(iter(data_loader))

    images = [x["image"] for x in first_batch]
    images = ImageList.from_tensors(images, torch_model.backbone.size_divisibility)

    with torch.no_grad():
        torch.onnx.export(
            torch_model,
            (images,),
            "my.onnx",
            # operator_export_type=OperatorExportTypes.ONNX,
            #verbose=True,  # NOTE: uncomment this for debugging
            export_params=True,
            training=False,
            #keep_initializers_as_inputs=True,
        )

    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type ImageList

I want to konw how chang the input ?  and  I want to change  mask rcnn model to onnx model that no have  ops,caffes2 Op

**Comment by XUDINGYI312** [comment]
detectron2             0.1.3       
Win10 operating system
Anconda   env

**Comment by ppwwyyxx** [comment]
According to https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html this is not a feature we support.
