### ISSUE TITLE
What values are expected to be in keypoint_names and keypoint_flip_map?

### ISSUE THREAD

**Issue by Dayan-Zhanchi** [facebookresearch/detectron2#285]
## ❓ Questions and Help

When training the model on keypoints I noticed that you need to add keypoint_names and keypoint_flip_map as key value pairs respectively in the dictionary in MetadataCatalog, otherwise you will get an error saying that these two don't exist as an attribute in the dictionary in MetadataCatalog when you try to train the model on keypoints. What values are expected to be in these two keys? I'm not sure if my dataset has these values, especially values for the keypoint_flip_map.

As far as I know, my dataset only has keypoints for individual items and categories.

**Comment by ppwwyyxx** [comment]
See docs at https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by Dayan-Zhanchi** [comment]
Unfortunately my original dataset don't seem contain those required values for the metadatacatalog? I think I found something corresponding to the keypoint_names for each category in my original dataset, but I can't find the keypoint_flip_map, which I believe is not included in the standard coco-format. 

So my question is:
How do you create/calculate the values for keypoint_flip_map? My dataset don't seem to have these.

**Comment by ppwwyyxx** [comment]
They are not included in any dataset and you should construct them by yourself based on the concept of keypoints in your dataset.

**Comment by Dayan-Zhanchi** [comment]
Why are they important to include in the dictionary in MetadataCatalog for training the keypoints? What happens if I skip including them somehow, is that possible? Especially the keypoint_flip_map seems only necessary if you are to do some image augmentations if I understand correctly, but is that essential thing to do? Did detectron1 do that when training on keypoint detection?

**Comment by Dayan-Zhanchi** [comment]
The description on the docs says 

```
keypoint_names (list[str]): Used by keypoint localization. A list of names for each keypoint.
keypoint_flip_map (list[tuple[str]]): Used by the keypoint localization task. A list of pairs of names, where each pair are the two keypoints that should be flipped if the image is flipped during augmentation.
```

I tried to follow the description closely, by creating a list of strings (keypoint names) for the keypoint_names attribute and a list of pairs of names for keypoint_flip_map, but at training time I got the following error: 
`RuntimeError: CUDA error: device-side assert triggered`

I'll make sure to send a detailed report on my error by following the issue template, but I don't have time to do it right now. I guess I'll create a new issue for that.

However, I got some questions, since it seems that I'm misunderstanding keypoint_names and keypoint_flip_map:
I know that you don't have any insights to my dataset, but could you provide a simple example on how the construction could look like in general (not my dataset)?

I think I just need to understand what these attributes are in relation to my own dataset and how they are used so that I can properly construct them.

**Comment by ppwwyyxx** [comment]
The metadata looks like this for coco:
https://github.com/facebookresearch/detectron2/blob/ebb9f8c9166765c508f8ac53d9ed2004739b28d1/detectron2/data/datasets/builtin_meta.py#L144-L167

the error you have seems to suggest a memory corruption. If you have >17 keypoints you need to set `MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS`.

**Comment by Dayan-Zhanchi** [comment]
Thanks alot! I didn't realize that I had to change that parameter. The training on keypoints works now! However, I seem to run out of memory at inference time (working on jupyter notebook). Are there any parameters in the configs that you can suggest me to lower in order to preserve some more memory?

The error I get is:
<details>
<p>

```
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-8-46d9e326b29c> in <module>
      1 for d in random.sample(dataset_val_dicts, 1):
      2     im = cv2.imread(d["file_name"])
----> 3     outputs = predictor(im)
      4     v = Visualizer(im[:, :, ::-1],
      5                    metadata=cloth_val_metadata,

f:\detectron2\env\lib\site-packages\torch\autograd\grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

F:\detectron2\detectron2\engine\defaults.py in __call__(self, original_image)
    175 
    176         inputs = {"image": image, "height": height, "width": width}
--> 177         predictions = self.model([inputs])[0]
    178         return predictions
    179 

f:\detectron2\env\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

F:\detectron2\detectron2\modeling\meta_arch\rcnn.py in forward(self, batched_inputs)
     64         """
     65         if not self.training:
---> 66             return self.inference(batched_inputs)
     67 
     68         images = self.preprocess_image(batched_inputs)

F:\detectron2\detectron2\modeling\meta_arch\rcnn.py in inference(self, batched_inputs, detected_instances, do_postprocess)
    122                 proposals = [x["proposals"].to(self.device) for x in batched_inputs]
    123 
--> 124             results, _ = self.roi_heads(images, features, proposals, None)
    125         else:
    126             detected_instances = [x.to(self.device) for x in detected_instances]

f:\detectron2\env\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

F:\detectron2\detectron2\modeling\roi_heads\roi_heads.py in forward(***failed resolving arguments***)
    569             # During inference cascaded prediction is used: the mask and keypoints heads are only
    570             # applied to the top scoring box detections.
--> 571             pred_instances = self.forward_with_given_boxes(features, pred_instances)
    572             return pred_instances, {}
    573 

F:\detectron2\detectron2\modeling\roi_heads\roi_heads.py in forward_with_given_boxes(self, features, instances)
    595 
    596         instances = self._forward_mask(features, instances)
--> 597         instances = self._forward_keypoint(features, instances)
    598         return instances
    599 

F:\detectron2\detectron2\modeling\roi_heads\roi_heads.py in _forward_keypoint(self, features, instances)
    708             keypoint_features = self.keypoint_pooler(features, pred_boxes)
    709             keypoint_logits = self.keypoint_head(keypoint_features)
--> 710             keypoint_rcnn_inference(keypoint_logits, instances)
    711             return instances

F:\detectron2\detectron2\modeling\roi_heads\keypoint_head.py in keypoint_rcnn_inference(pred_keypoint_logits, pred_instances)
    105     bboxes_flat = cat([b.pred_boxes.tensor for b in pred_instances], dim=0)
    106 
--> 107     keypoint_results = heatmaps_to_keypoints(pred_keypoint_logits.detach(), bboxes_flat.detach())
    108     num_instances_per_image = [len(i) for i in pred_instances]
    109     keypoint_results = keypoint_results.split(num_instances_per_image, dim=0)

f:\detectron2\env\lib\site-packages\torch\autograd\grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

F:\detectron2\detectron2\structures\keypoints.py in heatmaps_to_keypoints(maps, rois)
    175         max_score, _ = roi_map.view(num_keypoints, -1).max(1)
    176         max_score = max_score.view(num_keypoints, 1, 1)
--> 177         tmp_full_resolution = (roi_map - max_score).exp_()
    178         tmp_pool_resolution = (maps[i] - max_score).exp_()
    179         # Produce scores over the region H x W, but normalize with POOL_H x POOL_W

RuntimeError: CUDA out of memory. Tried to allocate 474.00 MiB (GPU 0; 6.00 GiB total capacity; 3.12 GiB already allocated; 162.63 MiB free; 1.01 GiB cached)
```
</p>
</details>

So it's just a simple case of using too much memory when training. But I don't know what parameters that causes the most memory consumption, or what parameters are good to change in general to preserve some memory.

**Comment by ppwwyyxx** [comment]
There are many parameters that affects memory consumption, e.g., number of proposals, number of rois, number of layers in your model. 294 keypoints is also a large number.
Closing as now it seems nothing unexpected is going on. We do not help users pick parameters.
