### ISSUE TITLE
How to speed up the data loader?

### ISSUE THREAD

**Issue by invisprints** [facebookresearch/detectron2#286]
## ❓ Questions and Help
I followed the Tutorials to use custom datasets(DeepFashion 2). But I found it very slow when run `trainer = DefaultTrainer(cfg)`. It seems that it takes much time in loading datas, maybe 20-30mins. I changed `cfg.DATALOADER.NUM_WORKERS` from 1 to 4 to 12, it didn't help(my cpu have 12 cores), results shows even worse. So how to speed up the data loader? 
I write a script to test loading data with multi-thread, finding it only takes 4-5mins. Is it pytorch problems?

**Comment by protossw512** [comment]
I am experiencing exactly the same issue. It seems like the dataloader is trying to load all data into memory before it starts training. When I was training on a 8 GPU machine with a train size of 50000, it consumed more than 400GB of memory to load the dataset before the training process starts.
When I have a training dataset with 110000 data samples, I have to reduce the number of workers in to avoid out of memory issues.

**Comment by invisprints** [comment]
Maybe you read image matrix in custom datasets. In my case, I just write image file name in custom instead of image itself. It just loads slow but costs little memory. And I think the reasons why it runs slowly is that there’re too many small config files.
I write a script to convert my datasets to coco format config (just one file). Now it run much faster than before.

**Comment by protossw512** [comment]
@invisprints I did not put images into my json files. You are probably right I should merge all json files into one and see how that goes. Thank you very much.

**Comment by ppwwyyxx** [comment]
The original code that loads COCO dataset is fast enough for training builtin models.

If you found the dataloader slow for your dataset, then the reason could be in your dataset, your custom dataloader, your machine. Without any details provided about what you did or what you observed, we cannot give a valid response. So closing.

**Comment by amjindal** [comment]
i'm experiencing this error when i'm training my dataset.
I'm using custom dataset formed in coco data format. 
the below code i use to run on GPU server with ample amount of ram(512 GB)


cfg = get_cfg() # obtain detectron2's default config
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))# load values from a file
cfg.DATASETS.TRAIN = ("my_dataset_train",)
cfg.DATASETS.TEST = ("my_dataset_val",)

cfg.DATALOADER.NUM_WORKERS = 1 # The speed of dataload to the ram once at a time. I reduced it from the genral value 4 to 2 and 1.
cfg.MODEL.WEIGHTS = "/home/rajib/amar_work/output/model_final_68b088.pkl"
#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 4    #images per batch i.e if 4 GPU than each GPU will see 1 image only.
cfg.SOLVER.BASE_LR = 0.00025 # pick a good LR


cfg.SOLVER.WARMUP_ITERS = 1000
cfg.SOLVER.MAX_ITER = 50000 #adjust up if val mAP is still rising, adjust down if overfit
cfg.SOLVER.STEPS = (1000, 1500)
cfg.SOLVER.GAMMA = 0.05

#epoch = (batch_size*no of iterations)/Total images 
#1 epoch means one time data is fed completly.

cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 # only has one class textline. (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
#your number of classes + 1(this comment is from older one)

cfg.TEST.EVAL_PERIOD = 500  #After this no of iteration, the validation data will evaluate the model accuracy.


#print(cfg.dump())  # print formatted configs
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = CocoTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()


I try to reduce the num_worker but still facing this issue.
