### ISSUE TITLE
Pre-built binary v0.4 is missing.

### ISSUE THREAD

**Issue by dennis-park-TRI** [facebookresearch/detectron2#2868]
## 📚 Documentation

* Link to the relevant documentation/comment:
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md

* What is missing or inaccurate?
The link for pytorch 1.7 x CUDA 10.1 (https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html) does not contain v0.4 binary. This cause the following pip-install to fail:
`python -m pip install detectron2==0.4 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html`

**Comment by ppwwyyxx** [comment]
Thanks for reporting! should be fixed now
