### ISSUE TITLE
How to asynchronize learning between semantic segmenatation and bbox regression?

### ISSUE THREAD

**Issue by Soo95** [facebookresearch/detectron2#289]
## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

####

Hi, I started to learn detectron2, thanks for building this awesome open-source.
I wonder it is possible to train semantic segmentation branch and RPN asynchronously from backbone's output.
I want to concatenate the output of semantic segmentation into backbone's output. And put it into RPN network as an input.
Is there a possible way to do this?

**Comment by ppwwyyxx** [comment]
I don't know what you mean by training them asynchronously. But I suppose it's possible as long as you write some model code or training code to implement it.

**Comment by Soo95** [comment]
@ppwwyyxx Thanks for replying. I'm gonna try it and reopen this issue if I have a problem.
