### ISSUE TITLE
Load pickle (.pkl) weights 

### ISSUE THREAD

**Issue by jigsawcoder** [facebookresearch/detectron2#2890]
## 🚀 Feature
Is there a way to load pickle (.pkl) weights in detectron2 i.e. cfg.MODEL.WEIGHTS??

## Motivation & Examples

Many times the weights are stored as pickle file so directly loading it to detectron2 to start/resume the training is quite useful.

**Comment by ppwwyyxx** [comment]
A pickle file can contain *anything*, so "support loading pickle weights" is not a well-defined feature.

The easiest way is to let users convert the weights into a format that can be loaded.
