### ISSUE TITLE
Is RTX support provided in this version?

### ISSUE THREAD

**Issue by qbeer** [facebookresearch/detectron2#29]
## ❓ Questions and Help

Hello!

 I have been using Detectron for a while and when I switched out the dual 1070s in our server machine to dual 2080Tis Detectron threw an unexpected error and I found people facing the same issue in the Issues section of Detectron on GitHub. I would like to experiment with Detectron2 but if RTX support is still unavailable I'll just rather stick to my solution using GTX cards. Has anyone tried RTX cards?

Thanks in advance,
Alex

**Comment by ppwwyyxx** [comment]
It is supported, according to the user of https://github.com/facebookresearch/detectron2/issues/27.

**Comment by qbeer** [comment]
Nice, thanks.
