### ISSUE TITLE
build error: .../torch/include/c10/util/ArrayRef.h(148): error: this declaration has no storage class or type specifier

### ISSUE THREAD

**Issue by blueardour** [facebookresearch/detectron2#290]
Hi, Dear author, 

I met the build error when compiling the repo. I tried to keep the package version as require I still can not build it. Could you please give me some advise? Thanks 

## How To Reproduce the Issue

1. clone complete new of the repo, on master branch
2. following the instructions from INSTALL.md and error occur when run: python setup.py build develop
3. what you observed (including the full logs):
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITH_CUDA -I/workspace/git/detectron2/detectron2/layers/csrc -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/TH -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenp/.pyenv/versions/3.7.3/include/python3.7m -c /workspace/git/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/workspace/git/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/workspace/git/detectron2/detectron2/layers/csrc -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/TH -I/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenp/.pyenv/versions/3.7.3/include/python3.7m -c /workspace/git/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o build/temp.linux-x86_64-3.7/workspace/git/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h(148): error: this declaration has no storage class or type specifier

/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h(148): error: expected a ";"

/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h(175): warning: parsing restarts here after previous syntax error

/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/core/MemoryFormat.h(48): error: no operator "[]" matches these operands
            operand types are: c10::IntArrayRef [ int ]

/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/core/MemoryFormat.h(49): error: no operator "[]" matches these operands
            operand types are: c10::IntArrayRef [ int ]

/home/chenp/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/include/c10/core/MemoryFormat.h(50): error: no operator "[]" matches these operands
            operand types are: c10::IntArrayRef [ int ]

/usr/local/cuda/include/cuda_fp16.h(155): error: identifier "__host__" is undefined

/usr/local/cuda/include/cuda_fp16.h(155): error: expected a ";"

/usr/local/cuda/include/cuda_fp16.h(169): error: identifier "__host__" is undefined

/usr/local/cuda/include/cuda_fp16.h(169): error: variable "__device__" has already been defined

/usr/local/cuda/include/cuda_fp16.h(169): error: expected a ";"

/usr/local/cuda/include/cuda_fp16.h(183): error: identifier "__host__" is undefined

/usr/local/cuda/include/cuda_fp16.h(183): error: variable "__device__" has already been defined

/usr/local/cuda/include/cuda_fp16.h(183): error: expected a ";"

/usr/local/cuda/include/cuda_fp16.h(198): error: identifier "__host__" is undefined

/usr/local/cuda/include/cuda_fp16.h(198): error: variable "__device__" has already been defined

/usr/local/cuda/include/cuda_fp16.h(198): error: expected a ";"

/usr/local/cuda/include/cuda_fp16.h(213): error: identifier "__host__" is undefined

/usr/local/cuda/include/cuda_fp16.h(213): error: variable "__device__" has already been defined

/usr/local/cuda/include/cuda_fp16.h(213): error: expected a ";"

/usr/local/cuda/include/cuda_fp16.h(227): error: identifier "__host__" is undefined
```

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.
If detectron2 hasn't been successfully installed,
use `python detectron2/utils/collect_env.py`.

---------------------  --------------------------------------------------
sys.platform           linux
Python                 3.7.3 (default, Nov  8 2019, 20:47:06) [GCC 7.4.0]
Numpy                  1.17.3
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.1
PyTorch Debug Build    False
torchvision            0.4.2
CUDA available         True
GPU 0                  GeForce RTX 2080 Ti
CUDA_HOME              /usr/local/cuda
NVCC                   Cuda compilation tools, release 10.1, V10.1.243
Pillow                 6.2.1
---------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by blueardour** [comment]
BTW, I aslo tried downgrade the pytorch version from 1.3.1 to 1.3.0. but it does not help.

**Comment by ppwwyyxx** [comment]
What's your `gcc --version`?

**Comment by blueardour** [comment]
gcc -v  gives:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

ps. And I successfully build the code on 1080TI machines but faild on the 2080TI, don't know whether it matters.

**Comment by blueardour** [comment]
Hi, I just installed gcc-5 on 2080ti machine which failed to build the code.  After link the the system level  /usr/bin/gcc-5 to /usr/bin/gcc, the error is still the same.

gcc -v:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1)

Also failed to build the repo~~~    

Another try is to switch python 3.7.3 to python 3.6.8. But not help.

**Comment by ppwwyyxx** [comment]
This seems more of an issue of your environment rather than with specific type of GPUs. You may want to double check your cuda installation, or some spurious environment variables such as `CPATH`.
I don't have other ideas and cannot help more since we cannot reproduce such issues. If you manage to create a docker or something to let other reproduce, we can look into that further.

**Comment by blueardour** [comment]
@ppwwyyxx Hi, thanks for your comment.

I nearly give up building the repo on this machine util I noticed that my gpu driver version is much higher than the one provided in the cuda package (and also the sucessful machine to build). I down-graded the nvdia driver from 430.14 to 418.87.00. And it works.

Very thanks for your advise to insipre the version check.
