### ISSUE TITLE
Can not process video in the colab example.

### ISSUE THREAD

**Issue by josenxx** [facebookresearch/detectron2#2901]
## 📚 Documentation
I try to run the colab example and it breaks in the video part.
* Link to the relevant documentation/comment:
here is error message
# Run frame-by-frame inference demo on this video (takes 3-4 minutes) with the "demo.py" tool we provided in the repo.
!git clone https://github.com/facebookresearch/detectron2
!python detectron2/demo/demo.py --config-file detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --output video-output.mkv \
  --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl
* What is missing or inaccurate?
*May be there is an error about video encoder.
change：fourcc=cv2.VideoWriter_fourcc(*"x264")
to：fourcc=cv2.VideoWriter_fourcc(*"mp4v"), # x264 ==> mp4

**Comment by ppwwyyxx** [comment]
Yes, the opencv on colab is missing x264 codec so a workaround is to change it to use mp4. Added a note to colab.

Ideally there should be a utility function that first checks if x264 is available (by writing to a temp video file). Leaving this open as an enhancement.

**Comment by ArtistBanda** [comment]
@ppwwyyxx could this be solved just for colab like:
```python
if "google.colab" in sys.modules:
     [required changes...]
```
Ideally, it should be able to catch the exception raised by C++ but I don't know how to do that, if you could guide me or maybe I could apply the above fix?

P.S : This is my first time contributing to detectron2

**Comment by ppwwyyxx** [comment]
solved by #3077

**Comment by Ayaan-Sharif** [comment]
`import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding  `
this works for me google colab

**Comment by Ayaan-Sharif** [comment]
`import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding`
