### ISSUE TITLE
deploy maskrcnn on windows 10

### ISSUE THREAD

**Issue by zpmmehrdad** [facebookresearch/detectron2#2908]
Hi,

I get this error on this:
auto module = torch::jit::load("D:\\model.ts");

Error: 
**c10::Error at memory location 0x...**

OS: Win 10
Cuda: 10.2
TorchScript: 1.8

**Comment by yang-gis** [comment]
> Hi,
> 
> I get this error on this:
> auto module = torch::jit::load("D:\model.ts");
> 
> Error:
> **c10::Error at memory location 0x...**
> 
> OS: Win 10
> Cuda: 10.2
> TorchScript: 1.8

hello，have you solved this problem？
