### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by monacv** [facebookresearch/detectron2#2913]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
```
(frank) mona@goku:~/research/code/frankmocap$ pip uninstall detectron2
Found existing installation: detectron2 0.4+cu111
Uninstalling detectron2-0.4+cu111:
  Would remove:
    /home/mona/venv/frank/lib/python3.8/site-packages/detectron2-0.4+cu111.dist-info/*
    /home/mona/venv/frank/lib/python3.8/site-packages/detectron2/*
Proceed (y/n)? y
  Successfully uninstalled detectron2-0.4+cu111
(frank) mona@goku:~/research/code/frankmocap$ python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-6hero4cq
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-6hero4cq
Requirement already satisfied: Pillow>=7.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (8.1.0)
Requirement already satisfied: cloudpickle in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.6.0)
Requirement already satisfied: future in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.18.2)
Collecting fvcore<0.1.6,>=0.1.5
  Using cached fvcore-0.1.5.post20210415.tar.gz (48 kB)
Collecting iopath<0.1.8,>=0.1.7
  Using cached iopath-0.1.7-py3-none-any.whl (19 kB)
Requirement already satisfied: matplotlib in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (3.3.3)
Collecting omegaconf==2.1.0.dev22
  Using cached omegaconf-2.1.0.dev22-py3-none-any.whl (66 kB)
Requirement already satisfied: pycocotools>=2.0.2 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (2.0.2)
Requirement already satisfied: pydot in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.4.1)
Requirement already satisfied: tabulate in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.8.7)
Requirement already satisfied: tensorboard in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (2.4.1)
Requirement already satisfied: termcolor>=1.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.1.0)
Requirement already satisfied: tqdm>4.29.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (4.56.0)
Requirement already satisfied: yacs>=0.1.6 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.1.8)
Requirement already satisfied: numpy in /home/mona/venv/frank/lib/python3.8/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.4) (1.19.5)
Requirement already satisfied: pyyaml>=5.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.4) (5.3.1)
Requirement already satisfied: portalocker in /home/mona/venv/frank/lib/python3.8/site-packages (from iopath<0.1.8,>=0.1.7->detectron2==0.4) (2.0.0)
Requirement already satisfied: cycler>=0.10 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (2.4.7)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4-python3-runtime-4.8.tar.gz (112 kB)
Requirement already satisfied: cython>=0.27.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (0.29.21)
Requirement already satisfied: setuptools>=18.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (44.0.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.24.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.7.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.36.2)
Requirement already satisfied: absl-py>=0.4 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.11.0)
Requirement already satisfied: six>=1.10.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.15.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.4.2)
Requirement already satisfied: grpcio>=1.24.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (2.25.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (3.3.3)
Requirement already satisfied: protobuf>=3.6.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (3.14.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (1.3.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (1.26.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/mona/venv/frank/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (3.1.0)
Building wheels for collected packages: detectron2, fvcore, antlr4-python3-runtime
  Building wheel for detectron2 (setup.py) ... done
  Created wheel for detectron2: filename=detectron2-0.4-cp38-cp38-linux_x86_64.whl size=6323671 sha256=917b8b3129b6dcd9d08adcfe416a1642b1098bf55bb558459a3a05d980526016
  Stored in directory: /tmp/pip-ephem-wheel-cache-qzirlv_s/wheels/19/ac/65/e48e5e4ec2702274d927c5a6efb75709b24014371d3bb778f2
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20210415-py3-none-any.whl size=59309 sha256=db8695b22ae60461ff8dfc7784e246666c2fc5b5d4904ab045878705d2f93753
  Stored in directory: /home/mona/.cache/pip/wheels/fc/05/a0/ba4b3385c0294621f870e0b3762ebf2da773407544d2b41212
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141230 sha256=f11b31d25f85f2303391f69b71a20c7f14bec0d07f7d6fdb849c6e51ed716e61
  Stored in directory: /home/mona/.cache/pip/wheels/c8/d0/ab/d43c02eaddc5b9004db86950802442ad9a26f279c619e28da0
Successfully built detectron2 fvcore antlr4-python3-runtime
Installing collected packages: iopath, fvcore, antlr4-python3-runtime, omegaconf, detectron2
  Attempting uninstall: iopath
    Found existing installation: iopath 0.1.2
    Uninstalling iopath-0.1.2:
      Successfully uninstalled iopath-0.1.2
  Attempting uninstall: fvcore
    Found existing installation: fvcore 0.1.3.post20210311
    Uninstalling fvcore-0.1.3.post20210311:
      Successfully uninstalled fvcore-0.1.3.post20210311
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.0.6
    Uninstalling omegaconf-2.0.6:
      Successfully uninstalled omegaconf-2.0.6
Successfully installed antlr4-python3-runtime-4.8 detectron2-0.4 fvcore-0.1.5.post20210415 iopath-0.1.7 omegaconf-2.1.0.dev22
(frank) mona@goku:~/research/code/frankmocap$ python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mona/research/code/frankmocap/demo/demo_frankmocap.py", line 25, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/mona/research/code/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
(frank) mona@goku:~/research/code/frankmocap$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import detectron2
>>> detectron2.__version__
'0.4'
>>> import fvcore
>>> fvcore.__version__
'0.1.5.post20210415'
```

```
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

```

(frank) mona@goku:~$ python collect_env.py
----------------------  --------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
numpy                   1.19.5
detectron2              0.4 @/home/mona/venv/frank/lib/python3.8/site-packages/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1650 Ti with Max-Q Design (arch=7.5)
CUDA_HOME               /usr
Pillow                  8.1.0
torchvision             0.9.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20210415
iopath                  0.1.7
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 


```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

```
$ gdb -ex "r" -ex "bt" -ex "quit" --args python -m detectron2.utils.collect_env
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(No debugging symbols found in python)
Starting program: /home/mona/venv/frank/bin/python -m detectron2.utils.collect_env
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff458d700 (LWP 11066)]
[New Thread 0x7ffff3d8c700 (LWP 11067)]
[New Thread 0x7fffeb58b700 (LWP 11068)]
[New Thread 0x7fffe2d8a700 (LWP 11069)]
[New Thread 0x7fffd2589700 (LWP 11070)]
[New Thread 0x7fffc9d88700 (LWP 11071)]
[New Thread 0x7fffc1587700 (LWP 11072)]
[New Thread 0x7fffc0d86700 (LWP 11073)]
[New Thread 0x7fffb0585700 (LWP 11074)]
[New Thread 0x7fffa7d84700 (LWP 11075)]
[New Thread 0x7fff9f583700 (LWP 11076)]
[Thread 0x7fff9f583700 (LWP 11076) exited]
[Thread 0x7fffa7d84700 (LWP 11075) exited]
[Thread 0x7fffb0585700 (LWP 11074) exited]
[Thread 0x7fffc0d86700 (LWP 11073) exited]
[Thread 0x7fffc1587700 (LWP 11072) exited]
[Thread 0x7fffc9d88700 (LWP 11071) exited]
[Thread 0x7fffd2589700 (LWP 11070) exited]
[Thread 0x7fffe2d8a700 (LWP 11069) exited]
[Thread 0x7fffeb58b700 (LWP 11068) exited]
[Thread 0x7ffff3d8c700 (LWP 11067) exited]
[Thread 0x7ffff458d700 (LWP 11066) exited]
[Detaching after fork from child process 11077]

[New Thread 0x7fff9f583700 (LWP 11087)]
[Detaching after fork from child process 11088]
[Detaching after fork from child process 11089]
[Detaching after fork from child process 11090]
[Detaching after fork from child process 11092]
----------------------  --------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
numpy                   1.19.5
detectron2              0.4 @/home/mona/venv/frank/lib/python3.8/site-packages/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1650 Ti with Max-Q Design (arch=7.5)
CUDA_HOME               /usr
Pillow                  8.1.0
torchvision             0.9.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20210415
iopath                  0.1.7
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

[New Thread 0x7fffa7d84700 (LWP 11094)]
[New Thread 0x7fffb0585700 (LWP 11095)]
[Thread 0x7fffa7d84700 (LWP 11094) exited]
[Thread 0x7fff9f583700 (LWP 11087) exited]
[Thread 0x7ffff7be0740 (LWP 11062) exited]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 11062) exited normally]
No stack.


```

https://github.com/facebookresearch/frankmocap/issues/96

**Comment by ppwwyyxx** [comment]
Error comes from `hand_object_detector/lib/model/_C`, not from detectron2.
