### ISSUE TITLE
IPython.embed() function is abnormal

### ISSUE THREAD

**Issue by weihaosky** [facebookresearch/detectron2#2917]
The function of `IPython.embed()` is abnormal with detectron2. When I embed an `IPython.embed()` in the model `forward()` function, the behavior of the interactive shell is unusual.
e.g., the auto-completion by double-click 'Tab' fails, and it often crashes if a wrong command is input.
This heavily impacts the debug and behaviors using IPython.embed(). Is it possible to solve this? Many thanks!

## Instructions To Reproduce the Issue:
e.g., 
1. add `import IPython; IPython.embed()` in `run_on_image()` in `demo/predictor.py`.
2. run `demo.py` according to the tutorial
3. then you will run into the interactive shell. Within this shell, the behavior is abnormal

## Environment:

any environment

## Solution:
I found the solution. This is caused by some impact between jedi-0.18.0 and detectron2. 
IPython.embed() is normal with jedi-0.18.0 in other python codes.
Change jedi to 0.17.2 by `pip install jedi==0.17.2` solve this problem.

**Comment by ppwwyyxx** [comment]
Please provide precise instructions to reproduce the issue.

**Comment by ppwwyyxx** [comment]
> add import IPython; IPython.embed() in run_on_image() in demo/predictor.py.
run demo.py according to the tutorial
then you will run into the interactive shell. Within this shell, the behavior is abnormal

Works fine for me. I'm using jedi 0.18.0. 

Unless given some way to reproduce this issue (e.g. a docker), we'll have to close it.
