### ISSUE TITLE
Unexpected behavior for non-maximum suppression

### ISSUE THREAD

**Issue by moziada** [facebookresearch/detectron2#2919]
i am trying to use MODEL.ROI_HEADS.NMS_THRESH_TEST to remove all the boxes that have IOU larger than 0.1 but there are an overleaping boxes on the bus and refuses to suppress any one of them 
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.NMS_THRESH_TEST = 0.1
cfg.MODEL.WEIGHTS = 'models/model_final_2d9806.pkl'
pred = DefaultPredictor(cfg)
outputs = pred(img)
```
![1533130050-cairo_main_bboxes3](https://user-images.githubusercontent.com/60968402/115029960-d473bc80-9ec6-11eb-8e66-1ec874ebecb8.jpg)

**Comment by QianLingjun** [comment]
hi, the predicted overleaping boxes label is same? or different? if different, it is OK, no issue. I checked NMS, no find a problem like you.

**Comment by moziada** [comment]
> hi, the predicted overleaping boxes label is same? or different? if different, it is OK, no issue. I checked NMS, no find a problem like you.

yes i have found they are different, one of the boxes belongs to class 5 with score 0.98, and the other belongs to class 7 with score 0.26. do you know how do i keep only the highest score box?

**Comment by ppwwyyxx** [comment]
See #978
