### ISSUE TITLE
demo.py don't run on webcam

### ISSUE THREAD

**Issue by Thanossrs** [facebookresearch/detectron2#2925]
Can anyone tell me how to fill the below problem?
I try to run demo.py on video for keypoint detection and get the below error. (DETECTRON2) 

**cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-s8zh4qlk/opencv/modules/highgui/src/window.cpp:634: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'**

Thank you

**Comment by ppwwyyxx** [comment]
Opencv is unable to display images in your environment. This is unrelated to detectron2.
