### ISSUE TITLE
Add Coco Evaluation into Default Trainer

### ISSUE THREAD

**Issue by PeiSeng** [facebookresearch/detectron2#294]
Hi all, may i know how do i add CocoEvaluator into Default Trainer to do evaluation while training? When I configure cfg.DATASETS.TEST to my test dataset, I keep getting error. Is there any guidance on this?

**Comment by ppwwyyxx** [comment]
please see
https://github.com/facebookresearch/detectron2/blob/1dd6d42c6946dd998723605a322b69b3f2adcdb0/tools/train_net.py
 or
https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/train_net.py
as
examples.

**Comment by Jacobsolawetz** [comment]
Why not just make this the `from detectron2.engine import DefaultTrainer`?
