### ISSUE TITLE
use 2 gpus to train the modified network

### ISSUE THREAD

**Issue by lixiuyu-cumt** [facebookresearch/detectron2#2944]
Based on the detectron2, i modified the structure of MASK Head, but when i wanted to train, it reported CUDA memory out, so i wanted to train the new network by two GPUS, the following problem came:

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by Lenazhou** [comment]
I meet the same question, if you have solved, please tell me how to fix it.

**Comment by deepakksingh** [comment]
I'm facing the same issue when I added a custom loss on a custom head on the FastRCNNOutputLayers module.
Please let us know if you have a fix.

**Comment by WeitaoVan** [comment]
Hi, I also meet the same issue, does anyone have a solution? thanks

**Comment by Johnqczhang** [comment]
Try passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel` when using multiple GPUs.
