### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by baiyubaiyu** [facebookresearch/detectron2#297]
I run the demo:
`python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
   --input /home/baiyu/ObjectDetection/detectron2/demo/16004479832_a748d55f21_k.jpg \
   --output /home/baiyu/ObjectDetection/detectron2/output/ok.jpg \
   --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \`

The feedback:

WARNING [11/11 17:54:09 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' **has no VERSION**. Assuming it to be compatible with latest v2.
  0%|                                                                              | 0/1 [00:00<?, ?it/s]
**Segmentation fault**
(bai) [root@localhost /home/baiyu/ObjectDetection/detectron2]/root/anaconda3/envs/bai/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: **There appear to be 1 leaked semaphores to clean up at shutdown**
  len(cache))

So actually I have three questions, just like the bold content above.

## Environment
the output of `python -m detectron2.utils.collect_env`:
`Segmentation fault`
Ithe output of  `python detectron2/utils/collect_env.py`:
`Segmentation fault`

**Comment by ppwwyyxx** [comment]
Please see https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md
