### ISSUE TITLE
Semantic head results in UnboundLocalError

### ISSUE THREAD

**Issue by petoor** [facebookresearch/detectron2#2981]
Loading e.g mask_rcnn_R_50_FPN_3x.yaml and changing the MODEL.META_ARCHITECTURE = "SemanticSegmentor"
and then calling the model with for instance
`trainer.model([{"image": torch.ones((224,224))}])`

Results in UnboundLocalError: local variable 'x' referenced before assignment
from line https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/semantic_seg.py#L223

Calling with
```
trainer.model([{"image": torch.ones((224,224, 3))}])
RuntimeError: Given groups=1, weight of size [16, 1, 3, 3], expected input[1, 224, 224, 3] to have 1 channels, but got 224 channels instead
trainer.model([{"image": torch.ones((3, 224,224, 3))}])
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 5-dimensional input of size [1, 3, 224, 224, 3] instead
```

**Comment by ppwwyyxx** [comment]
> Loading e.g mask_rcnn_R_50_FPN_3x.yaml and changing the MODEL.META_ARCHITECTURE = "SemanticSegmentor"
and then calling the model

This does not result in a valid model.

**Comment by petoor** [comment]
Hi @ppwwyyxx 

It is discussed in https://github.com/facebookresearch/detectron2/issues/1055 but in the examples you point to pointrend and DeepLabV3+ which modifies the default config with different SEM_SEG_HEAD.NAME (and other modifications as well)

Since there is a notion of semantic segmentation in the default config file (https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py). What exactly needs to be changed in the default in order to do semantic segmentation?

Assuming of course that the data mapper and data loader is written correct for semantic segmentation.
