### ISSUE TITLE
what is the  ./output/inference/* use?

### ISSUE THREAD

**Issue by Ashinhuang** [facebookresearch/detectron2#2989]
Dear sir,

Thanks for your good work!
when I use "train_net.py" to train model,  under the ./output folder, there is  a "inference" folder

![image](https://user-images.githubusercontent.com/33593302/116529953-101f7500-a910-11eb-8cb9-47723190c913.png)

under the inference,there are "coco_instances_results.json" and "instances_predictions.pth"
what are the two files use?

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/en/latest/modules/evaluation.html#detectron2.evaluation.COCOEvaluator.__init__
