### ISSUE TITLE
Could the CVPR21 BCNet on instance segmentation built on detectron2 listed in external project link?

### ISSUE THREAD

**Issue by lkeab** [facebookresearch/detectron2#2991]
## 📚 Documentation

* Link to the relevant documentation/comment/tutorials:
External project link: https://github.com/facebookresearch/detectron2/tree/master/projects
CVPR21 BCNet code: https://github.com/lkeab/BCNet
CVPR21 BCNet paper: https://arxiv.org/abs/2103.12340

* What is missing, inaccurate, or imprecise?
Could BCNet on instance segmentation support FCOS detector be added? BCNet supasses centermask, blendmask, htc etc.

**Comment by ppwwyyxx** [comment]
Feel free to send a PR
