### ISSUE TITLE
densepose inference

### ISSUE THREAD

**Issue by wuneng** [facebookresearch/detectron2#30]
Is there a brief intro of the usage which covers how to run densepose inference with single image in detectron2?

**Comment by ppwwyyxx** [comment]
It was mentioned in https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose#tools.

We haven't released models for densepose yet. For now you can use a temporary link at https://dl.fbaipublicfiles.com/detectron2/e2e_densepose_R_50_FPN_s1x/124238535/model_final_5f3d7f9875229310fdfe6649459c0157.pkl

**Comment by Aswantm** [comment]
about by the use of standard word embeddings when training machine learning .... one pixel in an image was modified by an attacker. ..... NLU or need a brief introduction to the fie

**Comment by ppwwyyxx** [comment]
We have released densepose models at https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/MODEL_ZOO.md
