### ISSUE TITLE
Box tensor contains infinite or NaN! when tracer.export_caffe2() 

### ISSUE THREAD

**Issue by billy800413** [facebookresearch/detectron2#3003]
Hi, I used COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml to train a segmentation model with my dataset. After the training, I tested the model and got good results. However, when I tried to export the model (tracer.export_caffe2) with the same dataset, it showed the error message (Box tensor contains infinite or NaN!).
## Instructions To Reproduce the Issue and Full Logs:
1. test code
register_coco_instances(f"testData", {}, f"PathOfTestData", f"")
dataset_dicts = DatasetCatalog.get("testData")
test_metadata = MetadataCatalog.get("testData")
cfg = get_cfg()
cfg.merge_from_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = "final.pth"
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1
cfg.DATASETS.TEST = ("testData", )
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
predictor = DefaultPredictor(cfg)
for d in random.sample(dataset_dicts,  10):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=test_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    imgR = cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB)
    cv2.imshow('My Image', imgR)
    cv2.waitKey(0)

2. export code
register_coco_instances(f"testData", {}, f"PathOfTestData", f"")
dataset_dicts = DatasetCatalog.get("testData")
test_metadata = MetadataCatalog.get("testData")
cfg = get_cfg()
cfg.merge_from_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = "final.pth"
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1
cfg.DATASETS.TEST = ("testData", )
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
cfg.freeze()
torch_model = build_model(cfg)
DetectionCheckpointer(torch_model).resume_or_load(cfg.MODEL.WEIGHTS)
data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
first_batch = next(iter(data_loader))
tracer = Caffe2Tracer(cfg, torch_model, first_batch)
caffe2_model = tracer.export_caffe2()
caffe2_model.save_protobuf("outPutPath")

log
/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py:209: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py:209: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/home/ubuntu/Desktop/detectron2/detectron2/export/c10.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert tensor.dim() == 2 and tensor.size(-1) in [4, 5, 6], tensor.size()
/home/ubuntu/Desktop/detectron2/detectron2/export/caffe2_modeling.py:275: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  proposals[0].image_size = (image_size_tensor[0, 0].item(), image_size_tensor[0, 1].item())
/home/ubuntu/Desktop/detectron2/detectron2/export/c10.py:370: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert box_regression.shape[1] % box_dim == 0
/home/ubuntu/Desktop/detectron2/detectron2/structures/boxes.py:192: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert torch.isfinite(self.tensor).all(), "Box tensor contains infinite or NaN!"
Traceback (most recent call last):
  File "convert2cc.py", line 54, in <module>
    caffe2_model = tracer.export_caffe2()
  File "/home/ubuntu/Desktop/detectron2/detectron2/export/api.py", line 111, in export_caffe2
    predict_net, init_net = export_caffe2_detection_model(model, inputs)
  File "/home/ubuntu/Desktop/detectron2/detectron2/export/caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "/home/ubuntu/Desktop/detectron2/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/jit/__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/Desktop/detectron2/detectron2/export/caffe2_modeling.py", line 278, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/detectron2/detectron2/modeling/roi_heads/cascade_rcnn.py", line 151, in forward
    pred_instances = self._forward_box(features, proposals)
  File "/home/ubuntu/Desktop/detectron2/detectron2/modeling/roi_heads/cascade_rcnn.py", line 173, in _forward_box
    proposals = self._create_proposals_from_boxes(prev_pred_boxes, image_sizes)
  File "<string>", line 3, in _create_proposals_from_boxes
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/mock/mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/mock/mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/mock/mock.py", line 1167, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/home/ubuntu/Desktop/detectron2/detectron2/export/c10.py", line 432, in __call__
    boxes_per_image.clip(image_size)
  File "/home/ubuntu/Desktop/detectron2/detectron2/structures/boxes.py", line 192, in clip
    assert torch.isfinite(self.tensor).all(), "Box tensor contains infinite or NaN!"
AssertionError: Box tensor contains infinite or NaN!

## Environment:
2021-05-04 09:38:19 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/master/detectron2/utils/collect_env.py [7340/7340] -> "collect_env.py" [1]
----------------------  --------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.2.1 @/home/ubuntu/Desktop/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   6.1
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.5.0 @/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1080 Ti (arch=6.1)
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.6.0a0+82fd1c8 @/home/ubuntu/anaconda3/envs/webtest/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201218
cv2                     3.4.0
----------------------  --------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Tracing requires valid inputs that the model can make non-emtpy predictions on. In this case the model fails to make predictions using the given inputs because it encounters infinite of NaNs.

**Comment by billy800413** [comment]
Hi ppwwyyxx, thanks for your response. But If the data is not a valid input, why I can use it in test code and it works perfectly?
test code
register_coco_instances(f"testData", {}, f"PathOfTestData", f"")
dataset_dicts = DatasetCatalog.get("testData")
test_metadata = MetadataCatalog.get("testData")
cfg = get_cfg()
cfg.merge_from_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = "final.pth"
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1
cfg.DATASETS.TEST = ("testData", )
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
predictor = DefaultPredictor(cfg)
for d in random.sample(dataset_dicts, 10):
im = cv2.imread(d["file_name"])
outputs = predictor(im)
v = Visualizer(im[:, :, ::-1],
metadata=test_metadata,
scale=0.8,
instance_mode=ColorMode.IMAGE_BW # remove the colors of unsegmented pixels
)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
imgR = cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB)
cv2.imshow('My Image', imgR)
cv2.waitKey(0)

**Comment by ppwwyyxx** [comment]
If `model(first_batch)` produces non-empty results, `tracer = Caffe2Tracer(cfg, model, first_batch)` should work, for the types of models we support.

If you found the above not true using latest detectron2, please provide full runnable code with the necessary data to reproduce the problem.

From the stack trace you seem to be using cascade r-cnn, which is not a model we support using caffe2 (https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html#deployment-with-caffe2-tracing)
