### ISSUE TITLE
How to train on Cityscape dataset

### ISSUE THREAD

**Issue by zhengjie6** [facebookresearch/detectron2#3005]
When I run the default training code to train on cityscape dataset with the config file at mask_rcnn_R_50FPN.yaml, it will automatically find the dataset file at datasets/cityscapes/gtFine

I wish to use the gtCoarse dataset. May I know how to change it. Where is the line of code that points Datasets.Train: “cityscapes_file_instance_seg_train” to that?

Thanks

**Comment by trongan93** [comment]
In my opinion, a good option is to registry a custom dataset.

**Comment by zhengjie6** [comment]
Ok. Thank you.
