### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by marcoippolito** [facebookresearch/detectron2#301]
I'm trying to execute the following piece of code:

    import detectron2
    from detectron2.utils.logger import setup_logger
    setup_logger()
    import numpy as np
    import cv2
    from detectron2.engine import DefaultPredictor
    from detectron2.config import get_cfg
    from detectron2.utils.visualizer import Visualizer
    from detectron2.data import MetadataCatalog

    im = cv2.imread("./input.jpg")

    cfg = get_cfg()
    cfg.merge_from_file("../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

    cfg.MODEL.DEVICE = "cpu"
    cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x
    /137849600/model_final_f10217.pkl"
    predictor = DefaultPredictor(cfg)
    outputs = predictor(im)

But I get this error message:

    (base) marco@pc:~/detectron2/demo$ python3 detectron2Tutorial.py 
    WARNING [11/11 16:10:10 d2.config.compat]: Config '../configs/COCO-InstanceSegmentation
    /mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
    Traceback (most recent call last):
      File "detectron2Tutorial.py", line 32, in <module>
        outputs = predictor(im)
      File "/home/marco/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in 
    decorate_no_grad
        return func(*args, **kwargs)
      File "/home/marco/anaconda3/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 172, 
    in __call__
        height, width = original_image.shape[:2]
    AttributeError: 'NoneType' object has no attribute 'shape'

How to solve this problem?

**Comment by ppwwyyxx** [comment]
It's saying that your image is None.

**Comment by marcoippolito** [comment]
This is the image file:

(base) marco@pc:~/detectron2/demo$ ls -lah input.jpg
-rw-rw-r-- 1 marco marco 88M Jul 11  2018 input.jpg

**Comment by ppwwyyxx** [comment]
That doesn't help. You should check by yourself why you provide a None object to detectron2's predictor.

**Comment by marcoippolito** [comment]
Solved thanks

**Comment by sgaurav07** [comment]
> Solved thanks

How did you solved it please reply?

**Comment by aAnkur463** [comment]
import turtle

wn = turtle.Screen()
pen = turtle.Turtle()
pen.Speed(300)
i = 0


def drawCircle(x, y, r):
    global i
    color = ['red', 'yellow', 'green', 'blue', 'purple', 'magneta']
    pen.color(color[i])
    i += 1
    if i > 6:
        i = 0
    pen.up()
    pen.goto(x, y - r)
    pen.down()
    pen.circle(r)


def make_picture(x, y, r):
    if r < 10:
        pass
    else:
        drawCircle(x, y, r)
        make_picture(x + r, y, r//2)
        make_picture(x - r, y, r//2)
        make_picture(x, y + r, r//2)
        make_picture(x, y - r, r//2)


make_picture(0, 0, 200)
turtle.done()
_i got an error (    pen.Speed(300)
AttributeError: 'NoneType' object has no attribute 'Speed')_
