### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by marcoippolito** [facebookresearch/detectron2#302]
In Ubuntu 18.04.02 Server Edition I'm trying to execute the inference with pre-trained model:

    (base) marco@pc:~$ python /home/marco/detectron2/demo/demo.py --config-file /home/marco
    /detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input 
    /home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg --opts MODEL.DEVICE cpu

First lines of the logging : 

    [11/11 17:00:22 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/home
    /marco/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=
    ['/home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg'], opts=['MODEL.DEVICE', 'cpu'], 
    output=None, video_input=None, webcam=False)
    WARNING [11/11 17:00:22 d2.config.compat]: Config '/home/marco/detectron2/configs/COCO-
    InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be 
    compatible with latest v2.

Last lines of the logging:

    [11/11 17:00:24 detectron2]: /home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg: 
    detected 0 instances in 1.52s
    : cannot connect to X server 
    /home/marco/anaconda3/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: 
   semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

Complete log file: 
[completeLogDetectronError.txt](https://github.com/facebookresearch/detectron2/files/3832149/completeLogDetectronError.txt)

**Comment by ppwwyyxx** [comment]
See https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-with-pre-trained-models


> This command will run the inference and show visualizations in an OpenCV window.
> ...
> To save outputs to a directory (for images) or a file (for webcam or video), use --output.

**Comment by marcoippolito** [comment]
Adding --output :   

    (base) marco@pc:~$ python /home/marco/detectron2/demo/demo.py --config-file /home/marco
    /detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input 
    /home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg --opts MODEL.DEVICE cpu --output 
    /home/marco/detectron2/demo/outputFile

    [11/11 17:21:11 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/home
     /marco/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=
     ['/home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg'], opts=['MODEL.DEVICE', 'cpu', '--
    output', '/home/marco/detectron2/demo/outputFile'], output=None, video_input=None, webcam=False)
    WARNING [11/11 17:21:11 d2.config.compat]: Config '/home/marco/detectron2/configs/COCO-
    InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be 
    compatible with latest v2.
    Traceback (most recent call last):
      File "/home/marco/detectron2/demo/demo.py", line 71, in <module>
        cfg = setup_cfg(args)
      File "/home/marco/detectron2/demo/demo.py", line 24, in setup_cfg
        cfg.merge_from_list(args.opts)
      File "/home/marco/anaconda3/lib/python3.7/site-packages/fvcore/common/config.py", line 130, in 
    merge_from_list
        return super().merge_from_list(cfg_list)
      File "/home/marco/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 243, in 
    merge_from_list
        _assert_with_logging(subkey in d, "Non-existent key: {}".format(full_key))
      File "/home/marco/anaconda3/lib/python3.7/site-packages/yacs/config.py", line 521, in 
    _assert_with_logging
        assert cond, msg
    AssertionError: Non-existent key: --output

**Comment by ppwwyyxx** [comment]
```
╰─$python demo/demo.py --help
usage: demo.py [-h] [--config-file FILE] [--webcam]
               [--video-input VIDEO_INPUT] [--input INPUT [INPUT ...]]
               [--output OUTPUT] [--confidence-threshold CONFIDENCE_THRESHOLD]
               [--opts ...]
```

`--opts` has to be the last arguments because it can be arbitrarily long.

**Comment by marcoippolito** [comment]
Ok. Thank you. Now it seems working.
I suggest to update https://detectron2.readthedocs.io/tutorials/getting_started.html to clarify that the order of the various parameters is important
