### ISSUE TITLE
RuntimeError: CUDA driver error: a PTX JIT compilation failed

### ISSUE THREAD

**Issue by TWangQing** [facebookresearch/detectron2#3021]
## 📚 Documentation

* Link to the relevant documentation/comment/tutorials:
![image](https://user-images.githubusercontent.com/22674866/117542853-f509df00-b04c-11eb-9288-86e506c4c21c.png)

* What is missing, inaccurate, or imprecise?
when I try to train on my own dataset, I met the  issue. Could you please help me? thanks a lot!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
