### ISSUE TITLE
Could you please provide more accurate infomation about pre-load models?

### ISSUE THREAD

**Issue by Pengfei-Hu** [facebookresearch/detectron2#3025]
It seems that there is no document about the pre-load ***.pkl.
For example, MODEL.WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl", which appears in config/****.yaml. I think it is from pre-trained on ImageNet as our backbone. But I am not sure about it. Could you please provide more accurate infomation about these pre-pretrained models?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models
