### ISSUE TITLE
Is it correct that the output file seems to be the same of the input file a part from the format (input: jpg, output: png)? And what kind of output should I get?

### ISSUE THREAD

**Issue by marcoippolito** [facebookresearch/detectron2#303]
In Ubuntu 18.04.02 Server Edition I ran the inference example:

    (base) marco@pc:~$ python /home/marco/detectron2/demo/demo.py --config-file /home/marco
    /detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input 
    /home/marco/detectron2/demo/federico-fellini-9292860-1-402.jpg --output /home/marco/detectron2
    /demo/outputFile --opts MODEL.DEVICE cpu

    [11/11 17:50:37 d2.checkpoint.c2_model_loading]: The checkpoint contains parameters not used by 
    the model:
      fc1000_b
      fc1000_w
      conv1_b
      0%|                                                                                                                                                                                       
    | 0/1 [00:00<?, ?it/s][11/11 17:50:39 detectron2]: /home/marco/detectron2/demo/federico-fellini-
    9292860-1-402.jpg: detected 0 instances in 1.60s
    100%      

    (base) marco@pc:~/detectron2/demo$ ls -lah | grep output
    -rw-rw-r--  1 marco marco 1.1M Nov 11 17:50 outputFile.png

This is the input file: https://drive.google.com/open?id=1yHvZlpVmh8tH3duf4ftf3Zs-mqA57CnE
and this is the outputfile: https://drive.google.com/open?id=1yHvZlpVmh8tH3duf4ftf3Zs-mqA57CnE

Is it correct that the output file seems to be the same of the input file a part from the format (input: jpg, output: png)? And what kind of output should I get?

**Comment by ppwwyyxx** [comment]
Please follow https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-with-pre-trained-models. You need to load a model with `MODEL.WEIGHTS`.

**Comment by marcoippolito** [comment]
Before with the load specification it gave me error, may be due to the order of the parameters.
Now it works.
Thanks a lot!
