### ISSUE TITLE
installation&environments

### ISSUE THREAD

**Issue by xuejiancai** [facebookresearch/detectron2#3048]
## Instructions To Reproduce the Issue:
cd detectron2 && pip install -e .
Running setup.py develop for detectron2
 /home/**/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/utils/cpp_extension.py:286: UserWarning:

                                   !! WARNING !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using c++, and then you can also use
    c++ to compile your extension.

    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                  !! WARNING !!
## Environment:
ubuntu16.04,python 3.6,cuda 10.2,pytorch 1.8.1
PyTorch built with:
  - GCC 7.3

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
