### ISSUE TITLE
Official colab demo -> !pip install numpy==1.19.3

### ISSUE THREAD

**Issue by jgrizou** [facebookresearch/detectron2#3055]
## 📚 Documentation Improvements

* Provide a link to the relevant documentation/comment/tutorial: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
 
* How should  the above documentation/comment/tutorial improve: ```import torch``` is failing due to incompatible numpy version. Fixed by forcing install of numpy v1.19.3 using ```!pip install numpy==1.19.3``` in first cell.

![Screenshot 2021-05-18 at 11 18 37](https://user-images.githubusercontent.com/1609708/118634743-cb7a5180-b7ca-11eb-8e47-0536b69dbb87.png)

Try here: https://colab.research.google.com/drive/15XgUlSuFKLqtpWi7KckjO6D7Wu6uh0hQ

**Comment by jgrizou** [comment]
![Screenshot 2021-05-18 at 11 17 25](https://user-images.githubusercontent.com/1609708/118634618-a259c100-b7ca-11eb-90d3-e2c54584e3c0.png)

**Comment by ppwwyyxx** [comment]
`import torch` in the first cell worked correctly when I try it just now.
