### ISSUE TITLE
How to speed up detection

### ISSUE THREAD

**Issue by GrininViktor** [facebookresearch/detectron2#308]
Sorry! From model zoo page(Instance Segmentation) I understood  "inference time (s/im)"  like a model prediction time. Is it true?  In table for all models this metric is less then 1 s/im. However, my rtx 2060 need more then 1 s/im and the performance is weakly dependent on the size of  image.  What performance can be achieved?

**Comment by ppwwyyxx** [comment]
As the model zoo says https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#common-settings the speed is measured by `tools/train_net.py --eval-only`. Please use it to measure the speed as your own measurement may be wrong.

**Comment by cbasavaraj** [comment]
The inferences times reported on the Model Zoo page were calculated on what image sizes? I hope not 224 x 224. I'm trying with 720p images (720 x 1280), and getting much higher time / image. For example R101-FPN for Object Detection is taking 170 ms instead of reported 63 ms.

**Comment by ppwwyyxx** [comment]
They are calculated using the corresponding config of the model. The image size is set by the config and is often 800 shortest edge.

**Comment by cbasavaraj** [comment]
Oh right! Any idea why it's so much slower for me? I'm using a nice Tesla P100 GPU. Used to do 70 ms for the faster-rcnn from here https://github.com/jwyang/faster-rcnn.pytorch, but after migrating to detectron2, it's above 150 ms for R101-C4 / R101-FPN. Thanks

**Comment by ppwwyyxx** [comment]
I do not know what you did to measure speed and what you observed to get conclusion about the speed. It would be helpful to provide details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by cbasavaraj** [comment]
Thanks, I've just opened an issue here: https://github.com/facebookresearch/detectron2/issues/359
