### ISSUE TITLE
Wrong typing of batched_inputs

### ISSUE THREAD

**Issue by lampercy** [facebookresearch/detectron2#3080]
https://github.com/facebookresearch/detectron2/blob/543fd075e146261c2e2b0770c9b537314bdae572/detectron2/modeling/mmdet_wrapper.py#L161

The type of `batched_inputs` should be `Tuple[Dict[str, torch.Tensor], ...]` to represent a variable-length tuple.
That makes the exported model by scripting fail to accept tuple of inputs longer than 1

**Comment by ppwwyyxx** [comment]
Scripting for mmdet wrapper (the one you linked to) is not supported. But it's true this should be fixed for other models to support >1 inputs.
