### ISSUE TITLE
BoxeSizeType

### ISSUE THREAD

**Issue by XiaoJiNu** [facebookresearch/detectron2#309]
Hi, what's type  of  BoxeSizeType ? The type of variable proposal_boxes is BoxeSizeType , but when I use torch.cat(proposal_boxes , objectness_logits) where objectness_logits is a tensor whose shape is 1000x1 and shape of proposal_boxes  is 1000x4.  A bug appeared as follow:
rois = torch.cat([objectness_logits, proposals_boxes], dim=1)
TypeError: expected Tensor as element 1 in argument 0, but got Boxes

the following figure shows proposal_boxes 
![图片](https://user-images.githubusercontent.com/30587645/68734811-ab3a6700-0616-11ea-82c8-b9bf40d5f062.png)

What can I do to extract the tensor form proposal_boxes ?

**Comment by XiaoJiNu** [comment]
I solved it by using proposal_boxes.tensor, but what's type of BoxeSizeType ?

**Comment by ppwwyyxx** [comment]
>  The type of variable proposal_boxes is BoxeSizeType

that's not true and I wonder how you got that conclusion.

**Comment by XiaoJiNu** [comment]
@ so what's the Boxes ?

**Comment by ppwwyyxx** [comment]
You can find `Boxes` in the API documentation: https://detectron2.readthedocs.io/modules/structures.html

**Comment by XiaoJiNu** [comment]
@ppwwyyxx thank you
