### ISSUE TITLE
I keep getting Build errors when I try building from Source

### ISSUE THREAD

**Issue by Mathuran-Mang** [facebookresearch/detectron2#3092]
I am trying to build Detectron2 from source but I keep getting these errors. I have tried many things like downgrading my CUDA version to 10.1 or downgrading my gcc version to 5.4.0 but none of it seems to work. I am also using pytorch==1.7.1 torchvision==0.8.2. I seen there was a similar issue to mine but I tried all the recommendations that were given under that specific issue

ERROR: Command errored out with exit status 1: 'C:\Users\Mathuran\anaconda3\envs\detectron\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Mathuran\detectron2\setup.py'"'"'; file__='"'"'C:\Users\Mathuran\detectron2\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

ERROR: Command errored out with exit status 1:command: 'C:\Users\Mathuran\anaconda3\envs\detectron\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Mathuran\detectron2\setup.py'"'"'; file_='"'"'C:\Users\Mathuran\detectron2\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(_file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
----------------------  --------------------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
numpy                   1.17.0
detectron2              imported a wrong installation
detectron2._C           not built correctly: No module named 'detectron2._C'
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @C:\Users\Mathuran\anaconda3\envs\myenv\lib\site-packages\torch
PyTorch debug build     False
GPU available           True
GPU 0                   NVIDIA GeForce RTX 3070 (arch=8.6)
CUDA_HOME               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
Pillow                  8.2.0
torchvision             0.8.2 @C:\Users\Mathuran\anaconda3\envs\myenv\lib\site-packages\torchvision
torchvision arch flags  C:\Users\Mathuran\anaconda3\envs\myenv\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
cv2                     Not found
----------------------  --------------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

**Comment by Mathuran-Mang** [comment]
Kind of, I am using google colab now instead of building it from source using anaconda command prompt

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues says we don't provide support for windows
