### ISSUE TITLE
Prediction Mask for thin objects

### ISSUE THREAD

**Issue by rds-itga** [facebookresearch/detectron2#312]
Hi guys,
I trained Detectron2 on line images with the parameters of the balloon example from Colab Notebook tutorial. I observed that when the thickness of the line is too small the prediction is not able to retrieve the mask of the line (I get a mask full of false). In your opinion which parameters should i tune before the training to obtain the right mask for thin objects?
Regards

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says, we do not help users train their models or tune parameters.
