### ISSUE TITLE
Replacing np.zeros_like with np.zeros for speed improvements

### ISSUE THREAD

**Issue by Denbergvanthijs** [facebookresearch/detectron2#3123]
## 🚀 Feature
Replacing np.zeros_like with np.zeros for speed improvements.

## Motivation & Examples
After writing tests for my own code and looking into the tests of `detectron2/tests/test_visualizer.py` I came across np.zeros_like. While reading about it in [this StackOverflow post ](https://stackoverflow.com/a/27464738/10603874) I saw some possibilities for small speed improvements.

With numpy version 1.20.3 I get the following timings:

```bash
python -m timeit --setup="import numpy as np;x=np.zeros((12488, 7588, 3), np.uint8)"  "np.zeros_like(x)"
>>> 5 loops, best of 5: 55.4 msec per loop

python -m timeit --setup="import numpy as np"  "np.zeros((12488, 7588, 3), np.uint8)"
>>> 20000 loops, best of 5: 19.4 usec per loop
```
With a quick search through the repository, I found 8 function calls that could be replaced. If there's interest in this, I would be happy to implement the speed improvements myself and send a pull request!

I have not found someone else mentioning this in any issue or pull request.

Greetings,
Thijs

**Comment by ppwwyyxx** [comment]
If this answer https://stackoverflow.com/a/27485152 is true, then there will be no difference in overall speed. `np.zeros` only delays the initialization to a later point. 

If there is really a substantial difference, numpy would be a better place to fix it. Changing it in detectron2 likely won't have any visible difference in speed, while leading to slightly longer code
