### ISSUE TITLE
Using detectron2 in install_requires with setuptools fails

### ISSUE THREAD

**Issue by raguiar2** [facebookresearch/detectron2#3124]
## Instructions To Reproduce the 🐛 Bug:
Detectron2 is unusable as a dependency in other projects where pytorch is not already installed on a given system. This is a problem if detectron2 is being used in a `setup.py` file as it renders the file totally unusable without external workarounds.

### Steps to reproduce
Create a `setup.py` file [for a project](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html)

Add detectron2 to the install_requires dependencies

```
install_requires = [
    deps["detectron2 @ git+https://github.com/facebookresearch/detectron2.git"]
]
```

and later in the file

```
setup(
...
install_requires=install_requires,
...
)
```

After setup.py is written, run install for the project with something like

`pip install -e . "[dev]"`

You will get an output like

```
File "/tmp/pip-install-i2cu73e0/detectron2_4abf6fe5c5d149118d10470adc3113bd/setup.py", line 10, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
```

and the entire build will fail

## Expected behavior:

A compatible version of torch should be downloaded as a prerequisite to detectron2 if it is missing from the enviornment, instead of failing the entire download. Or, there should be at least a guide in the Install.MD about this issue.

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

This is an installation related issue, but it's installing in the sense of adding detectron2 as a dependency to an external library, rather than installing it on an existing system. I have tried to solve it with the instructions in the installation issues - but the instructions do not account for using detectron2 with `install_requires` as a dependency of a package when torch might not be installed on the machine.

**Comment by ppwwyyxx** [comment]
> Or, there should be at least a guide in the Install.MD about this issue.

There is, https://detectron2.readthedocs.io/en/latest/tutorials/install.html#requirements says pytorch is required at the beginning.

If you have better suggestions please let us know. Otherwise the behavior is expected.
