### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.ops'

### ISSUE THREAD

**Issue by sunjeet95** [facebookresearch/detectron2#3146]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
```
2. What exact command you run: python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \ --input input1.jpg input2.jpg
3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "/home/sunjeet/detectron2/demo/demo.py", line 14, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2/layers/deform_conv.py", line 9, in <module>
    from torchvision.ops import deform_conv2d
ModuleNotFoundError: No module named 'torchvision.ops'

```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
---------------------  ----------------------------------------------------------------------------------
sys.platform           linux
Python                 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) [GCC 9.3.0]
numpy                  1.20.3
detectron2             0.4 @/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.8.1 @/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.2.0
torchvision            0.2.2 @/home/sunjeet/anaconda3/envs/opencv/lib/python3.9/site-packages/torchvision
fvcore                 0.1.3.post20210317
cv2                    4.5.2
---------------------  ----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by maheshs11** [comment]
uninstall torchvision 
and then dont install from pip
build from source or install specific version like torchvision= 0.9.0 or 0.8.2

**Comment by sunjeet95** [comment]
This is what I get after using the command you mentioned:

Requirement already satisfied: torchvision in ./anaconda3/envs/opencv/lib/python3.9/site-packages (0.2.2)
Requirement already satisfied: numpy in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.20.3)
Requirement already satisfied: six in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.16.0)
Requirement already satisfied: torch in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.8.1)
Requirement already satisfied: pillow>=4.1.1 in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (8.2.0)
Requirement already satisfied: typing_extensions in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torch->torchvision) (3.10.0.0)

**Comment by maheshs11** [comment]
> This is what I get after using the command you mentioned:
> 
> Requirement already satisfied: torchvision in ./anaconda3/envs/opencv/lib/python3.9/site-packages (0.2.2)
> Requirement already satisfied: numpy in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.20.3)
> Requirement already satisfied: six in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.16.0)
> Requirement already satisfied: torch in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (1.8.1)
> Requirement already satisfied: pillow>=4.1.1 in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torchvision) (8.2.0)
> Requirement already satisfied: typing_extensions in ./anaconda3/envs/opencv/lib/python3.9/site-packages (from torch->torchvision) (3.10.0.0)

in armv7l raspberry pi 4 it installed that when i ran that command .
for your purpose try removing everything and build from source

**Comment by ppwwyyxx** [comment]
According to torchvision: https://github.com/pytorch/vision#installation
Pytorch1.8 requires torchvision 0.9
