### ISSUE TITLE
Can I predict non-exclusive classification/attribution?

### ISSUE THREAD

**Issue by wuyuanyi135** [facebookresearch/detectron2#315]
Hi,
I wonder whether I can predict a non-exclusive label? For example, I want to train a model to be able to classify two labels: car/truck. For each prediction, I have another attribution: parked that identify whether the vehicle is stopped. How should I train the network if I want the network outputs both class (truck or car) and the attribution (parked)?

**Comment by ppwwyyxx** [comment]
You need either an extra box head, or equivalently, a custom ROIHeads that uses a different loss function.

**Comment by wuyuanyi135** [comment]
@ppwwyyxx thank you!

**Comment by ppwwyyxx** [comment]
Anything about custom models are implemented following this tutorial: https://detectron2.readthedocs.io/tutorials/write-models.html
