### ISSUE TITLE
In the example of the training balloon model of the colab notebook, why is there no category name in the predicted box? How can I add a category name?

### ISSUE THREAD

**Issue by zwf2381540** [facebookresearch/detectron2#316]
There is category information in the predicted outputs. Why is there no category name in the  predicted box?

## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

**Comment by ppwwyyxx** [comment]
Because when there is only one class, we deliberately do not show class names since it conveys no information.

**Comment by zwf2381540** [comment]
Thank you very much!

**Comment by zwf2381540** [comment]
@ppwwyyxx Thank you very much!

**Comment by maiskovich** [comment]
@ppwwyyxx can we please add this information to the documentation? I spent hours searching why this was failing until I found your comment
