### ISSUE TITLE
Training custom model for retreiving  keypoints

### ISSUE THREAD

**Issue by codingforpleasure** [facebookresearch/detectron2#3173]
I have created a new dataset and annotated it and (have generated the corresponding json files).
The dataset holds a single category. I have set the MetadataCatalog with the following metadata fields:
thing_classes, thing_colors, keypoint_names, keypoint_flip_map.
before the training I get a preview of the annotated images with their keypoints by the visualizer, which means the annotation file is written well (I think).
right before training the model I have set the config file:

```
cfg = get_cfg()

res = model_zoo.get_config_file("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")
cfg.merge_from_file(res)
 
cfg.DATASETS.TRAIN = ("lamp_train",)
cfg.DATASETS.TEST = ("lamp_val",)  #
cfg.DATALOADER.NUM_WORKERS = 2

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")

cfg.SOLVER.IMS_PER_BATCH = 2

cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 1000
cfg.SOLVER.STEPS = []  # do not decay learning rate
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128  
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 4
cfg.TEST.KEYPOINT_OKS_SIGMAS = 4 # <- I'm not sure!!
 
trainer = Trainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```
Before the actual training I receive a crash, how come?

The Tracback log is:

> 
> [06/23 09:18:35 d2.data.build]: Using training sampler TrainingSampler
> [06/23 09:18:35 d2.data.common]: Serializing 103 elements to byte tensors and concatenating them all ...
> [06/23 09:18:35 d2.data.common]: Serialized dataset takes 0.09 MiB
> Skip loading parameter 'roi_heads.keypoint_head.score_lowres.weight' to the model due to incompatible shapes: (512, 17, 4, 4) in the checkpoint but (512, 4, 4, 4) in the model! You might want to double check if this is expected.
> Skip loading parameter 'roi_heads.keypoint_head.score_lowres.bias' to the model due to incompatible shapes: (17,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
> [06/23 09:18:35 d2.engine.train_loop]: Starting training from iteration 0
> /home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/modeling/roi_heads/fast_rcnn.py:103: UserWarning: This overload of nonzero is deprecated:
>   nonzero()
> Consider using one of the following signatures instead:
>   nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
>   num_fg = fg_inds.nonzero().numel()
> ...
> ...
> 
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [82,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [82,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [82,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [82,0,0], thread: [30,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [82,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> Traceback (most recent call last):
>   File "/home/diy/PycharmProjects/detectron_with_GPU/paper_recognize_with_detectron2/paper_train_with_keypoints.py", line 195, in <module>
>     trainer.train()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 431, in train
>     super().train(self.start_iter, self.max_iter)
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 138, in train
>     self.run_step()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 441, in run_step
>     self._trainer.run_step()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 240, in run_step
>     losses.backward()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
>     Variable._execution_engine.run_backward(
> RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
> ERROR [06/23 09:18:35 d2.engine.train_loop]: Exception during training:
> Traceback (most recent call last):
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 138, in train
>     self.run_step()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 441, in run_step
>     self._trainer.run_step()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 240, in run_step
>     losses.backward()
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/diy/.local/share/virtualenvs/detectron_with_GPU-ll85W_57/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
>     Variable._execution_engine.run_backward(
> RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
> [06/23 09:18:35 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
> [06/23 09:18:35 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 3499M

**Comment by codingforpleasure** [comment]
never mind...

**Comment by juanmed** [comment]
@codingforpleasure I am having the same issue, where you able to solve this?

**Comment by juanmed** [comment]
@codingforpleasure now I understand your "nevermind" .... a simple re-run solved the issue.
