### ISSUE TITLE
Getting installation issue with detectron while importing: from detectron2 import _C

### ISSUE THREAD

**Issue by shubhangi27397** [facebookresearch/detectron2#3175]
ImportError                               Traceback (most recent call last)
<ipython-input-8-9283645e3740> in <module>()
     11 
     12 # import some common detectron2 utilities
---> 13 from detectron2 import model_zoo
     14 from detectron2.engine import DefaultPredictor
     15 from detectron2.config import get_cfg

4 frames
/usr/local/lib/python3.7/dist-packages/detectron2/layers/deform_conv.py in <module>()
      9 from torchvision.ops import deform_conv2d
     10 
---> 11 from detectron2 import _C
     12 
     13 from .wrappers import _NewEmptyTensorOp

ImportError: /usr/local/lib/python3.7/dist-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

**Comment by VishalBalaji321** [comment]
Seems like a problem with CUDA Environment. Try installing CUDA Toolkit for your GPU from the **Nvidia Website itself** and then reinstall PyTorch and Detectron2.
