### ISSUE TITLE
How to apply same behavior to boxes if image resized in ImageList.from_tensors

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#3183]
`ImageList.from_tensors` will resize image with ResizeShortestEdge, and it will add padding, so how to apply same transform to boxes in detection?

I know there is `detectron2.data.transform` to do so, but I look a lot project just call this:

```
images = [x["image"].to(self.device) for x in batched_inputs]
        bs = len(images)
        images = [self.normalizer(x) for x in images]

        images = ImageList.from_tensors(
            images, size_divisibility=0)
```
and then directly get boxes from Instance without any coordinates transform. Why? I found it actually not work when I logged the boxes coordinates out, so how should I transform it simply enough 
**if I don't have any other transform applied just this resize?**

**Comment by ppwwyyxx** [comment]
> ImageList.from_tensors will resize image with ResizeShortestEdge

No it will not. It only adds padding, so boxes don't need any transform.

**Comment by jinfagang** [comment]
@ppwwyyxx Got it. Fixed my problem.
