### ISSUE TITLE
Got error "cannot import name '_new_empty_tensor' from 'torchvision.ops'" in colab

### ISSUE THREAD

**Issue by yichun-hub** [facebookresearch/detectron2#3191]
Hi, I got the error when I run the Panoptic segmentation using DETR provided by detectron2

Link：
https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/DETR_panoptic.ipynb#scrollTo=5uUW5iRnJhxM

When I run to the code 
`model, postprocessor = torch.hub.load('facebookresearch/detr', 'detr_resnet101_panoptic', pretrained=True, return_postprocessor=True, num_classes=250)
model.eval();`
I got the error "cannot import name '_new_empty_tensor' from 'torchvision.ops'"

Does anyone solve this issue?
I really sure I could run the code successfully two weeks ago, but I have no idea why the error occur recently.

**Comment by ppwwyyxx** [comment]
The colab notebook in question is not from this project.

**Comment by m-ali-awan** [comment]
You need to install torch, and torchvision like this:

!pip install torch==1.8.0 torchvision==0.9.0 -qq

And then restart the notebook, and it will work..
