### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.ops'

### ISSUE THREAD

**Issue by lfydegithub** [facebookresearch/detectron2#32]
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input ./images/16004479832_a748d55f21_k.jpg ./images/pose.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

-----------------------------
pytorch 1.3
torchvision     0.2.2

**Comment by litingsjj** [comment]
Have you solved?

**Comment by jadielam** [comment]
If you are getting this error, likely your torchvision version is less than 0.3.0
