### ISSUE TITLE
Recieving identical n keypoints

### ISSUE THREAD

**Issue by codingforpleasure** [facebookresearch/detectron2#3204]
I have generated 1K rectangles images and the corresponding json files (annotation files with `segmentation` and `keypoints`).
each image holds a simple single rectangle, and in the json file I have listed all 4 corners as 4 keypoints.

moreover I have configured the metadataCatalog with:

>         MetadataCatalog.get(name="...").set(keypoint_names=["corner_a", "corner_b", "corner_c", "corner_d"])
>         MetadataCatalog.get(name="...").set(keypoint_flip_map=[("corner_a", "corner_b"),("corner_d", "corner_c")])
>         MetadataCatalog.get(name="...").keypoint_connection_rules = [
>             ['corner_a', 'corner_b', (255, 0, 0)],
>             ['corner_b', 'corner_c', (0, 255, 0)],
>             ['corner_c', 'corner_d', (0, 0, 0)],
>             ['corner_d', 'corner_a', (0, 0, 255)]
>         ]

I have trained the model and have used the config file `keypoint_rcnn_R_50_FPN_3x.yaml`, 
and have modified the number of keypoints: `cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 4`

After training phase, it seems during inference for some of the images the 4 keypoints got found 
and for the other images it **returns only two or three distinct keypoints** (**few keypoints with identical coordinates**)
for example:
> 
> tensor([[[315.6059, 279.6248,   0.7483],
>          [469.6873, 279.6248,   0.8404],
>          [469.6873, 279.6248,   1.2162],
>          [315.6059, 279.6248,   1.1040]]])

* (x, y, confidence score)

How can it be? Is there a bug?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
