### ISSUE TITLE
How to print config nicely?

### ISSUE THREAD

**Issue by Soo95** [facebookresearch/detectron2#324]
![image](https://user-images.githubusercontent.com/32061883/68924810-ef6b6a00-07c4-11ea-8781-ed2fc8e423e4.png)

Hi, I want to see a config in detail, but I don't know how to print it.
It's hard to read a config as you can see above.
Is there a nice way to print CfgNode?

**Comment by ppwwyyxx** [comment]
you can use `cfg.dump()`

**Comment by Soo95** [comment]
@ppwwyyxx Awesome! Thanks a lot
