### ISSUE TITLE
torch/distributed/distributed_c10d.py", line 1870, in all_gather     work.wait() RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#3243]
I evaluated about 938 images on a 8 GPUs server, everytime calls evaluation will pop this error:

```
torch/distributed/distributed_c10d.py", line 1870, in all_gather
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete

```

Anyidea what caused this? And how to solve it? (My coco exp can run evaluation properly)

**Comment by WeixiongLin** [comment]
> I evaluated about 938 images on a 8 GPUs server, everytime calls evaluation will pop this error:
> 
> ```
> torch/distributed/distributed_c10d.py", line 1870, in all_gather
>     work.wait()
> RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete
> ```
> 
> Anyidea what caused this? And how to solve it? (My coco exp can run evaluation properly)

hello, have you solved this issue?

**Comment by FedyHajali** [comment]
> ```
> torch/distributed/distributed_c10d.py", line 1870, in all_gather
>     work.wait()
> RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete
> ```

I have the same issue, do you have any news or solution?
