### ISSUE TITLE
tutorials/models.html#model-input-format, “image”: Tensor, what dtype?

### ISSUE THREAD

**Issue by johngrabner** [facebookresearch/detectron2#3246]
## 📚 Documentation Improvements

* Provide a link to the relevant documentation/comment/tutorial:
https://detectron2.readthedocs.io/en/latest/tutorials/models.html#model-input-format

----
* How should  the above documentation/comment/tutorial improve:
`“image”: Tensor in (C, H, W) format. The meaning of channels are defined by cfg.INPUT.FORMAT. Image normalization, if any, will be performed inside the model using cfg.MODEL.PIXEL_{MEAN,STD}.
`

What is the type of this tensor, uint8, float32?

-----
* How should  the above documentation/comment/tutorial improve:

`“height”, “width”: the desired output height and width, which is not necessarily the same as the height or width of the image field. For example, the image field contains the resized image, if resize is used as a preprocessing step. But you may want the outputs to be in original resolution. If provided, the model will produce output in this resolution, rather than in the resolution of the image as input into the model. This is more efficient and accurate.`

"If provided" implies optional, but if not provided detectron2 crashes using the training loop
-----

**Comment by puneeth-y** [comment]
Hey, I am trying to give a input tensor with shape of (4,1080,2160) which is giving me an error while training the model('The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0'). Tried changes in the cfg file but couldn't crack it. Any suggestions on what could be done. Thank you.

**Comment by andreaceruti** [comment]
@johngrabner This is the exact same problem I am facing, there is no specification of what dtype the input tensor should have.
I would prefer to give as input a float32 but It seems I can only give uint8 images as input
