### ISSUE TITLE
Newbie facing issues with config file 

### ISSUE THREAD

**Issue by Tinabr7** [facebookresearch/detectron2#325]
I'm new to Machine Learning and trying out couple of things. Can someone point what is  wrong here? 
![image](https://user-images.githubusercontent.com/8765432/68928575-3ca4f880-073f-11ea-8639-a4dca9e615d9.png)

Thanks!

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
