### ISSUE TITLE
There is no label on the predicted image

### ISSUE THREAD

**Issue by zsc1220** [facebookresearch/detectron2#326]
I detect two types of targets with the demo file successfully , but it is only percent values on the picture , but no corresponding labels . How to add the corresponding labels to the image?

If I use directly with coco training model and coco datas , There are both percent and tags on the picture , It's really strange

**Comment by ppwwyyxx** [comment]
I do not know what you did exactly so I cannot give an answer. But it sounds like the same as #316.

**Comment by zsc1220** [comment]
Hi @ppwwyyxx 
Thank you for your reply ! Yes , It is the same as #316 , but now I have more than one classes , I want to show the class names . So how should I show them ?

**Comment by ppwwyyxx** [comment]
They will be shown as long as the metadata you provided to visualizer contains the class names. The names are set like this: https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by zsc1220** [comment]
Hi @ppwwyyxx
Thank you so much ! Great , it works , when I write the following code in the file of demo.py .
`from detectron2.data import MetadataCatalog
 MetadataCatalog.get("car_val").thing_classes = ["class1", "calss2"]`
