### ISSUE TITLE
Detectron2 - fasterRcnn operating values after every ReLU

### ISSUE THREAD

**Issue by SyedShaQutub** [facebookresearch/detectron2#3282]
## enhancement

Hi, 

Detectron2 is quite well-written and optimized code, thanks for making it open source.
 I believe one of the design approaches while building the package was to cater to the research needs through easy hacking - basically to make and break things without breaking much sweat. 

My question is mainly on 'How to' with regards to the repo. On a similar line, I'm currently trying to control the values after every activation layer (relu). For this, I need to build abstract info coming out of these layers and later use the same to control it.

I could use PyTorch forward hooks but they have limited functionality in the case of detectron2, since the modules() won't return all the hidden relu layers. Especially all the modules are wrapped using detectron2 classes like base stem, fpn, proposal, roi.
Maybe this is already possible using the fvcore package, and I may have missed the use of the feature. If so, could you please point me to the right approach?
If not, according to your knowledge, is there any quick way of achieving this?

This could be interesting to many especially for the ones who want to understand the networks learning at any intermediate layers and also to visualise using gradient update methods.

Thanks in advance for your time!
:)

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/en/latest/tutorials/models.html#partially-execute-a-model.

If you have any concrete suggestions that make the solutions easier, feel free to suggest as a feature request. In fact it might better be a feature request to pytorch, because your question apply to any pytorch models (not just detectron2).
