### ISSUE TITLE
X152 map is poor

### ISSUE THREAD

**Issue by johnlanbor** [facebookresearch/detectron2#329]
I use cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml
and modified the lr and batchsize, at begin I set lr to 0.04 but the loss will be Nan soon, so  I change the lr to 0.02, and train 5w iter.
but I only got 26map in coco detection.
Is that normal? if not, can you tell me how to train X152 to get your result.
Thanks a lot.

`
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "X152-32x8d-IN5k.pth"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 152 
    DEFORM_ON_PER_STAGE: [False, True, True, True]
  ROI_HEADS:
    NAME: "CascadeROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    NUM_CONV: 8
    NORM: "GN"
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32
  STEPS: (140000, 180000)                                                                                                                                                       
  MAX_ITER: 200000
  BASE_LR: 0.02
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 2500

`

**Comment by ppwwyyxx** [comment]
Training the config with no change will result in the model in the model zoo.

**Comment by johnlanbor** [comment]
so, I can not get a reasonable map is due to X152 or a small lr for GN?

**Comment by ppwwyyxx** [comment]
As mentioned in the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md#expected-behavior), we do not help users tune these parameters.

**Comment by johnlanbor** [comment]
ok,Thanks
