### ISSUE TITLE
Unable to save and use a config file in inference, evaluation and deployment

### ISSUE THREAD

**Issue by avadhutbhosarekar** [facebookresearch/detectron2#3299]
I am not able to use the yaml file (that I am saving via the cfg.dump() method ) for inference, evaluation and deployment.

## Instructions To Reproduce the Issue: 
I have  recreated the issue in the below Google Colab Notebook: https://colab.research.google.com/drive/1NzcARQKYV4rFdly4nAo6sm2y9tZSb_h4?usp=sharing 

The inference, evaluation work fine when the cfg file is not loaded from disk and I do not know how to tackle this issue...

**Comment by ppwwyyxx** [comment]
The correct way to load a config file is given in docs: https://detectron2.readthedocs.io/en/latest/tutorials/configs.html#basic-usage
`load_cfg` does something else.

**Comment by avadhutbhosarekar** [comment]
After saving the config to a yaml file via the  cfg.dump() method. I tried loading it with cfg.merge_from_file(yaml_file_path) method as mentioned in the link that you provided and here it threw an exception.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-48d5ac7686f1> in <module>()
      4 
      5 new_config = get_cfg()
----> 6 new_config.merge_from_file("/content/video_analytics/model_artifacts_trained/model_config_trained.yml")
      7 det_model = build_model(new_config)

2 frames
/usr/local/lib/python3.7/dist-packages/yacs/config.py in _create_config_tree_from_dict(cls, dic, key_list)
    121         """
    122         dic = copy.deepcopy(dic)
--> 123         for k, v in dic.items():
    124             if isinstance(v, dict):
    125                 # Convert dict to CfgNode

AttributeError: 'str' object has no attribute 'items'`

The docs link that you have provided do not give any information about how to save a config to a yaml file (and then how to subsequently load it in a later )...it merely provides a way to print them to the console via the cfg.dump() method.

**Comment by ppwwyyxx** [comment]
Output of cfg.dump should be written to a file directly. We will add this to the doc.

**Comment by avadhutbhosarekar** [comment]
I was able to resolve this issue with the following  cell block
`
        import yaml
        from yaml import Dumper
        
        str_config = cfg.dump()
        yaml_config = yaml.full_load(str_config)
        
        stream = open("/content/video_analytics/model_artifacts_trained/model_config_trained.yml",'w')
        yaml.dump(yaml_config,stream,Dumper=Dumper)
        stream.close()
        
        new_config = get_cfg()
        new_config.merge_from_file("/content/video_analytics/model_artifacts_trained/model_config_trained.yml")
`
The inference and evaluation code are working as expected after this change but during deployment the **export_model.py script** (provided in detectron 2 ) does not recognize the datasets that I have registered in the earlier cell blocks and gives the following exception.  How do i register the datasets that I trained the models on so the the deployment script recognizes them.
`
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py", line 51, in get
            f = self[name]
          File "/usr/lib/python3.7/collections/__init__.py", line 1027, in __getitem__
            raise KeyError(key)
        KeyError: 'dataset_val'
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/content/detectron2/tools/deploy/export_model.py", line 219, in <module>
            sample_inputs = get_sample_inputs(args)
          File "/content/detectron2/tools/deploy/export_model.py", line 159, in get_sample_inputs
            data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
          File "/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py", line 192, in wrapped
            explicit_args = _get_args_from_config(from_config, *args, **kwargs)
          File "/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py", line 229, in _get_args_from_config
            ret = from_config_func(*args, **kwargs)
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 410, in _test_loader_from_config
            else None,
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 227, in get_detection_dataset_dicts
            dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 227, in <listcomp>
            dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py", line 57, in get
            ) from e
        KeyError: "Dataset 'dataset_val' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"
`
