### ISSUE TITLE
How to test with multi gpu and increase test batches?

### ISSUE THREAD

**Issue by joeythegod** [facebookresearch/detectron2#33]
Hi, I would like to know how to test with multi gpu and increase test batches?

**Comment by ppwwyyxx** [comment]
`tools/train_net.py --num-gpu 8`

Testing with batch size > 1 is unsupported at the moment, mainly because for most models it will not produce the exact same output due to padding, therefore not very useful for research.

**Comment by Aswantm** [comment]
If a TensorFlow operation has both CPU and GPU implementations, TensorFlow will automatically place the operation to run on a GPU device first. If you have more than one GPU, the GPU with the lowest ID will be selected by default. However, TensorFlow does not place operations into multiple GPUs automatically

**Comment by asanakoy** [comment]
@joeythegod but if you still want to increase the batch, you can do it by hacking the code here: https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/build.py#L398
Just change the batch size in the `BatchSampler`.

**Comment by ppwwyyxx** [comment]
Closing as all the models do support batch size >1 for inference from the beginning.
We probably don't want to support batch size > 1 for evaluation, due to reasons mentioned above.
