### ISSUE TITLE
Requirements.txt git clone detectron2 issues

### ISSUE THREAD

**Issue by bokelai1989** [facebookresearch/detectron2#3312]
@ppwwyyxx Hello! Hope you are doing well! 

I have been using Detectron2 model to do instance segmentation in my project, and I have successfully created an inference endpoint in Sagemaker last week by following this github guide. 

But today when I re-deploy the inference endpoint using the same script as last week, I encountered issues in installing detectron2 through the [requriement.txt](https://github.com/aws-samples/end-to-end-object-detection-detectron2-sagemaker/blob/main/source/requirements.txt). It seems "git+https://github.com/facebookresearch/detectron2.git@e883afb9afe2b5196b7cba7485583a1d063a9991". does not work any more. I also checked this link (https://github.com/facebookresearch/detectron2.git@e883afb9afe2b5196b7cba7485583a1d063a9991), it shows "Not Found". **I am wondering whether there is any change on this link? What link should I use to in my requirements.txt to make it work again?**  Is this a version issue?   Thanks a lot in advance!!

**************************************
I tried "git+https://github.com/facebookresearch/detectron2" and also "git+https://github.com/facebookresearch/detectron2.git" in the requirements.txt. But it gives me below error: needing Pytorch >=1.7. 

![image](https://user-images.githubusercontent.com/38841207/127912590-04aa8530-a8f7-4892-b448-ba6207703e30.png)

But when I changed the framework version to 1.7 as below code shows, the error shows "unsupported version"  

`# build the PyTorchModel framework 
remote_model = PyTorchModel(
                     name = model_name, 
                     model_data=model_url,
                     role=role,
                     sagemaker_session = sess,
                     entry_point="inference.py",
                     # image=image, 
                     source_dir = "code", 
                     **framework_version="1.7.0",**
                     py_version='py3'
                    )

remote_predictor = remote_model.deploy(
                         instance_type='ml.g4dn.xlarge',   #'ml.p3.2xlarge',  # 'ml.g4dn.xlarge', ml.g4dn.4xlarge
                         initial_instance_count =1,
                         # update_endpoint = True, # comment or False if endpoint doesns't exist
                         endpoint_name=endpoint_name, # define a unique endpoint name; if ommited, Sagemaker will generate it based on used container
                         wait=True 
                         )`

**Comment by ppwwyyxx** [comment]
> But when I changed the framework version to 1.7 as below code shows, the error shows "unsupported version"

This error does not come out of detectron2 so we cannot answer it.

The official installation instructions are at https://detectron2.readthedocs.io/en/latest/tutorials/install.html. We are not able to help with other ways to install detectron2.
