### ISSUE TITLE
sem_seg_evaluation.py", line 97, in process     (self._num_classes + 1) * pred.reshape(-1) + gt.reshape(-1), ValueError: operands could not be broadcast together with shapes (206647,) (619941,) 

### ISSUE THREAD

**Issue by rihab13** [facebookresearch/detectron2#3314]
Hi , 
I tried to train semantic segmentation deeplabv3 plus project on custom dataset.
The dataset contains RGB images and gray images (sem_seg path gets truth)
I succeeded to generate checkpoint model, but in inference I get this error
 File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 608, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/evaluator.py", line 164, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/sem_seg_evaluation.py", line 97, in process
    (self._num_classes + 1) * pred.reshape(-1) + gt.reshape(-1),
ValueError: operands could not be broadcast together with shapes (206647,) (619941,) 

I think it's due to number image channel so I convert the gt to gray using opencv, but I get this error cannot reshape 141 arrays into (6,6) (I had 6 classes in my dataset) what should I do!!

![image](https://user-images.githubusercontent.com/81234166/127922562-31c49939-1d3f-43cc-8d3d-10d9b0b52fd5.png)

**Comment by Camillo4eyes** [comment]
I have the same problem, what is the solution?
