### ISSUE TITLE
local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by amiralipour** [facebookresearch/detectron2#3316]
x is not initiated in the `else:`:

https://github.com/facebookresearch/detectron2/blob/9eb0027d795bb9a38098bb05e2ceb273bfc9cf41/detectron2/modeling/meta_arch/semantic_seg.py#L237

Yields error: 
File "/opt/conda/lib/python3.6/site-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 238, in layers
    x = self.predictor(x)
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by ppwwyyxx** [comment]
This is not a bug. It happens because the model is not initialized with a valid config.

We should print an error in this case, though.

**Comment by amiralipour** [comment]
I tried to initialized model with random weights (ie did not use any predefined model) and I am getting this any suggestion to randomly init the model?
