### ISSUE TITLE
Size Missmatch issue . Not solved Before Please read & provide the following

### ISSUE THREAD

**Issue by jaideep11061982** [facebookresearch/detectron2#3328]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
```
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.
 utils.check_image_size(dataset_dict, image)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/detection_utils.py", line 204, in check_image_size
    + " Please check the width/height in your annotation."
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image ../input/covid-dataset-scaled-down-by-half/0012ff7358bc.png, got (1528, 1272), expect (512, 512). Please check the width/height in your annotation.

## Expected behavior:
Above check is done before applying the transformation that resizes the image to bbx size.  We dont get this error when validation is done during training time.  But at inference this is a  check done prior to applying a transformation so we face this issue. Code should not expect the run the inference the dataset with already resized image size, one may chose to do so durign course of training or inference.
If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by jaideep11061982** [comment]
This issue can be resolved by simply moving this check  post augmentations

as shown below

```
      image = utils.read_image(dataset_dict["file_name"], format=self.image_format)
        utils.check_image_size(dataset_dict, image)  #should not be here 

        # USER: Remove if you don't do semantic/panoptic segmentation.
        if "sem_seg_file_name" in dataset_dict:
            sem_seg_gt = utils.read_image(dataset_dict.pop("sem_seg_file_name"), "L").squeeze(2)
        else:
            sem_seg_gt = None

        aug_input = T.AugInput(image, sem_seg=sem_seg_gt)
        transforms = self.augmentations(aug_input)
       utils.check_image_size(dataset_dict, image)    #should be here

```

**Comment by ppwwyyxx** [comment]
No repro is given so it's unclear what the issue is. The above code is correct because "height" and "width" are supposed to be the size before transform.

**Comment by jaideep11061982** [comment]
Why does it works fine when validation is done during train ?
If  what you said is  correct then one has to keep  dataset  image in same
size as is target train size .

**Comment by ppwwyyxx** [comment]
> one has to keep  dataset  image in same size as is target train size .

I don't think that's true and not sure why you'd think so.

As the error says for itself, the height/width in the annotation is incorrect because they don't match the image shape. If instead you think the code is incorrect, please provide a way for others to reproduce a problem.

**Comment by jaideep11061982** [comment]
Ok , let me ask you this
If
Source image size hs ; ws
And I pass
Annotations size ,same wrt to source
And provide Resized height  ,resized width same as source hs,ws
Now my annotations  are same ,I wont get the error .

Then I
Give solver.ims size =  512

Will detectron2 take care of resizing annotations to 512 during training
and validations  ?

**Comment by ppwwyyxx** [comment]
I cannot understand this question. If you think the library is behaving incorrectly, please provide code (not just words) that others can run to reproduce a problem.

For arbitrary questions, you can use [discussions](https://github.com/facebookresearch/detectron2/discussions) and if someone in the community understands the question they might be able to answer.

**Comment by jaideep11061982** [comment]
Will give
