### ISSUE TITLE
KeyError: 'image_id'

### ISSUE THREAD

**Issue by Chi-Zaozao** [facebookresearch/detectron2#333]
## How To Reproduce the Issue

1.  I am trying to follow the project TridentNet, but I  am using a custom dataset. 
2. I register the dataset as follows：

from projects.TridentNet.tridentnet.coco_format import get_simimage_dicts
from detectron2.data import DatasetCatalog, MetadataCatalog

get_simimage_dicts('simImage/val')
for d in ['train','val']:
    DatasetCatalog.register('simImage/'+d, lambda d = d: get_simimage_dicts('simImage/'+d))
    MetadataCatalog.get('simImage/'+d).set(thing_classes=['object'])
    MetadataCatalog.get('simImage/'+d).set(json_file='simImage/'+d+'/annotations.json')
object_metadata=MetadataCatalog.get('simImage/train') 
3. I changed the cfg:
cfg.DATASETS.TRAIN = ('simImage/train',)
cfg.DATASETS.TEST = ('simImage/val',)
4. The class Trainer:
from detectron2.engine import DefaultTrainer
from detectron2.evaluation import COCOEvaluator, verify_results
from detectron2.checkpoint import DetectionCheckpointer

class Trainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        return COCOEvaluator(dataset_name, cfg, True, output_folder)
4.when I run `trainer.train()`, I got this error:
```
......
[11/18 08:39:54 d2.checkpoint.c2_model_loading]: Some model parameters are not in the checkpoint:
  proposal_generator.anchor_generator.cell_anchors.0
  proposal_generator.rpn_head.anchor_deltas.{bias, weight}
  proposal_generator.rpn_head.conv.{bias, weight}
  proposal_generator.rpn_head.objectness_logits.{bias, weight}
  roi_heads.box_predictor.bbox_pred.{bias, weight}
  roi_heads.box_predictor.cls_score.{bias, weight}
[11/18 08:39:54 d2.checkpoint.c2_model_loading]: The checkpoint contains parameters not used by the model:
  fc1000_b
  fc1000_w
  conv1_b
[11/18 08:39:54 d2.engine.train_loop]: Starting training from iteration 0
[11/18 08:39:56 fvcore.common.checkpoint]: Saving checkpoint to ./output/model_final.pth
[11/18 08:39:59 d2.evaluation.evaluator]: Start inference on 26 images
[11/18 08:40:00 d2.engine.hooks]: Total training time: 0:00:04 (0:00:04 on hooks)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-2e4ae3838e13> in <module>()
      1 trainer = Trainer(cfg)
      2 trainer.resume_or_load(resume=args.resume)
----> 3 trainer.train()

/detectron2_repo/detectron2/engine/defaults.py in train(self)
    327             OrderedDict of results, if evaluation is enabled. Otherwise None.
    328         """
--> 329         super().train(self.start_iter, self.max_iter)
    330         if hasattr(self, "_last_eval_results") and comm.is_main_process():
    331             verify_results(self.cfg, self._last_eval_results)

/detectron2_repo/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    131                     self.before_step()
    132                     self.run_step()
--> 133                     self.after_step()
    134             finally:
    135                 self.after_train()

/detectron2_repo/detectron2/engine/train_loop.py in after_step(self)
    149     def after_step(self):
    150         for h in self._hooks:
--> 151             h.after_step()
    152         # this guarantees, that in each hook's after_step, storage.iter == trainer.iter
    153         self.storage.step()

/detectron2_repo/detectron2/engine/hooks.py in after_step(self)
    302         is_final = next_iter == self.trainer.max_iter
    303         if is_final or (self._period > 0 and next_iter % self._period == 0):
--> 304             results = self._func()
    305 
    306             if results:

/detectron2_repo/detectron2/engine/defaults.py in test_and_save_results()
    292 
    293         def test_and_save_results():
--> 294             self._last_eval_results = self.test(self.cfg, self.model)
    295             return self._last_eval_results
    296 

/detectron2_repo/detectron2/engine/defaults.py in test(cls, cfg, model, evaluators)
    410                 else cls.build_evaluator(cfg, dataset_name)
    411             )
--> 412             results_i = inference_on_dataset(model, data_loader, evaluator)
    413             results[dataset_name] = results_i
    414             if comm.is_main_process():

/detectron2_repo/detectron2/evaluation/evaluator.py in inference_on_dataset(model, data_loader, evaluator)
    119             torch.cuda.synchronize()
    120             total_compute_time += time.time() - start_compute_time
--> 121             evaluator.process(inputs, outputs)
    122 
    123             if (idx + 1) % logging_interval == 0:

/detectron2_repo/detectron2/evaluation/coco_evaluation.py in process(self, inputs, outputs)
     91             #add finished here
     92 
---> 93             prediction = {"image_id": input["image_id"]}
     94 
     95             # TODO this is ugly

KeyError: 'image_id'
```

## Expected behavior
I don't actually know.

## Environment

Failed to load OpenCL runtime
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Numpy                     1.13.3
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1
CUDA available            True
GPU 0                     GeForce GTX 1060 6GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.0
cv2                       3.2.0
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

Any assistance you can provide would be greatly appreciated.

**Comment by ppwwyyxx** [comment]
Each image in your dataset has to have a distinct "image_id" if you want to enable COCO AP evaluation.

**Comment by Chi-Zaozao** [comment]
Sorry, I have a distinct "image_id" in the json file but I didn't register it. 
Thank you very much!
