### ISSUE TITLE
Getting error TypeError: 'AugmentationList' object is not iterable in python3.8/site-packages/detectron2/data/transforms/augmentation.py

### ISSUE THREAD

**Issue by anirbankonar123** [facebookresearch/detectron2#3349]
## Instructions To Reproduce the 🐛 Bug:

class CFUTrainer(DefaultTrainer):
    """Extend the Detectron2 DefaultTrainer to better augment and evaluate data."""

    augmentations_train: List[Augmentation] = [
        T.RandomApply(T.RandomBrightness(intensity_min=0.7, intensity_max=1.3), prob=1),
        T.RandomApply(T.RandomContrast(intensity_min=0.7, intensity_max=1.3), prob=1),
        T.RandomApply(T.RandomLighting(scale=1.0), prob=1),
        T.RandomApply(T.RandomSaturation(intensity_min=0.7, intensity_max=1.3), prob=1),
        T.RandomRotation(angle=[0.0, 360.0], sample_style="range", interp=cv2.INTER_CUBIC,),
        T.RandomCrop_CategoryAreaConstraint(crop_type="relative_range", crop_size=(0.5, 0.5)),
        T.ResizeShortestEdge(  # Randomly rescales the image to one of the short_edge_length sizes
            short_edge_length=(1200), max_size=1500, sample_style="choice"
        ),
    ]
    augmentations_test: List[Augmentation] = [
        T.RandomRotation(angle=[0.0, 360.0], sample_style="range", interp=cv2.INTER_CUBIC,)
    ]

    @classmethod
    def build_train_loader(
        cls, cfg: CfgNode, augmentations: Optional[List[Augmentation]] = None
    ) -> Union[AspectRatioGroupedDataset, DataLoader]:  # type: ignore
        """
        Create a training data loader.

        Returns
        -------
        iterable
        """
        return build_detection_train_loader(
            cfg,
            mapper=CFUDatasetMapper(
                cfg,
                is_train=True,
                augmentations=augmentations if augmentations else cls.augmentations_train,
                recompute_boxes=True,  # to tighten the bboxes that got widened after transforms like rotation
            ),
        )

    @classmethod
    def build_test_loader(
        cls, cfg: CfgNode, dataset_name: str, augmentations: Optional[List[Augmentation]] = None
    ) -> DataLoader:  # type: ignore
        """
        Create a test data loader.

        Returns
        -------
        iterable
        """
        return build_detection_test_loader(  # type: ignore
            cfg,
            dataset_name=dataset_name,
            mapper=CFUDatasetMapper(
                cfg,
                is_train=False,
                augmentations=augmentations if augmentations else cls.augmentations_test,
                recompute_boxes=True,  # to tighten the bboxes that got widened after transforms like rotation
            ),
        )

    @classmethod
    def build_evaluator(
        cls, cfg: CfgNode, dataset_name: str, output_folder: Optional[str] = None
    ) -> Union[DatasetEvaluators, DatasetEvaluator]:
        """
        Create evaluator(s) for a given dataset.

        This uses the special metadata "evaluator_type" associated with each builtin dataset.
        For your own dataset, you can simply create an evaluator manually in your
        script and do not have to worry about the hacky if-else logic here.
        """
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        # Delete pre-existing evaluation folder to ensure a new one gets created and no old cache is being used
        if os.path.isdir(output_folder):
            logger.info(f"Overwriting existing: {output_folder}.")
            delete_folders([output_folder])

        # remove any dataset json_file metadata if any to ensure such cache gets recreated by the COCOEvaluator.
        # The cache issue is that as soon as the dataset gets extended, benchmarks using the old cache will be meaningless
        _metadata = MetadataCatalog.get(dataset_name)
        if hasattr(_metadata, "json_file"):
            del _metadata.json_file

        evaluator_list = [
            CFUEvaluator(),
            COCOEvaluator(dataset_name, cfg, True, output_folder),
        ]

        if len(evaluator_list) == 0:
            raise NotImplementedError(f"No Evaluator for the dataset {dataset_name}.")

        elif len(evaluator_list) == 1:
            return evaluator_list[0]

        return DatasetEvaluators(evaluator_list)

2. What exact command you run: 
trainer = CFUTrainer(cfg)
trainer.resume_or_load(resume=True)
trainer.train()
3. __Full logs__ or other relevant observations:
[08/10 07:31:57 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [<detectron2.data.transforms.augmentation_impl.RandomApply object at 0x2aab8b13a760>, <detectron2.data.transforms.augmentation_impl.RandomApply object at 0x2aab8b13ab80>, <detectron2.data.transforms.augmentation_impl.RandomApply object at 0x2aab8b13adf0>, <detectron2.data.transforms.augmentation_impl.RandomApply object at 0x2aab8b13aeb0>, RandomRotation(angle=[0.0, 360.0], interp=2), RandomCrop_CategoryAreaConstraint(crop_type='relative_range', crop_size=(0.5, 0.5)), ResizeShortestEdge(short_edge_length=(1200, 1200), max_size=1500, sample_style='choice')]
[08/10 07:31:58 d2.data.build]: Removed 208 images with no usable annotations. 100 images left.
[08/10 07:31:58 d2.data.build]: Using training sampler TrainingSampler
[08/10 07:31:58 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[08/10 07:31:58 d2.data.common]: Serialized dataset takes 1.18 MiB
WARNING [08/10 07:31:58 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
[08/10 07:31:58 d2.engine.train_loop]: Starting training from iteration 0
ERROR [08/10 07:31:58 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 267, in run_step
    data = next(self._data_loader_iter)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/common.py", line 179, in __iter__
    for d in self.dataset:
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/hpc/scratch/hdd1/.../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/hpc/scratch/hdd1/.../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/axk88432/VXGIOQ-CFU-Counting-ML/notebooks/../src/vxgioq_cfu_counting_ml/training/dataset_mapper.py", line 49, in __call__
    transforms = aug_input.apply_augmentations(self.augmentations)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/transforms/augmentation.py", line 347, in apply_augmentations
    return AugmentationList(augmentations)(self)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/transforms/augmentation.py", line 259, in __init__
    self.augs = [_transform_to_aug(x) for x in augs]
TypeError: 'AugmentationList' object is not iterable

[08/10 07:31:58 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[08/10 07:31:58 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 3469M
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-561a43508324> in <module>
      1 trainer = CFUTrainer(cfg)
----> 2 trainer.train()
      3 cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, MODEL_WEIGHTS_NAME)

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/defaults.py in train(self)
    485             OrderedDict of results, if evaluation is enabled. Otherwise None.
    486         """
--> 487         super().train(self.start_iter, self.max_iter)
    488         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    489             assert hasattr(

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    147                 for self.iter in range(start_iter, max_iter):
    148                     self.before_step()
--> 149                     self.run_step()
    150                     self.after_step()
    151                 # self.iter == max_iter can be used by `after_train` to

/hpc/scratch/hdd1/...../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/defaults.py in run_step(self)
    495     def run_step(self):
    496         self._trainer.iter = self.iter
--> 497         self._trainer.run_step()
    498 
    499     @classmethod

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/engine/train_loop.py in run_step(self)
    265         If you want to do something with the data, you can wrap the dataloader.
    266         """
--> 267         data = next(self._data_loader_iter)
    268         data_time = time.perf_counter() - start
    269 

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/common.py in __iter__(self)
    177 
    178     def __iter__(self):
--> 179         for d in self.dataset:
    180             w, h = d["width"], d["height"]
    181             bucket_id = 0 if w > h else 1

/hpc/scratch/hdd1/...../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/hpc/scratch/hdd1/...../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1201             else:
   1202                 del self._task_info[idx]
-> 1203                 return self._process_data(data)
   1204 
   1205     def _try_put_index(self):

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1227         self._try_put_index()
   1228         if isinstance(data, ExceptionWrapper):
-> 1229             data.reraise()
   1230         return data
   1231 

/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    423             # have message field
    424             raise self.exc_type(message=msg)
--> 425         raise self.exc_type(msg)
    426 
    427 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/...../VXGIOQ-CFU-Counting-ML/notebooks/../src/vxgioq_cfu_counting_ml/training/dataset_mapper.py", line 49, in __call__
    transforms = aug_input.apply_augmentations(self.augmentations)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/transforms/augmentation.py", line 347, in apply_augmentations
    return AugmentationList(augmentations)(self)
  File "/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2/data/transforms/augmentation.py", line 259, in __init__
    self.augs = [_transform_to_aug(x) for x in augs]
TypeError: 'AugmentationList' object is not iterable
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.


## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Tried the same exact version of libs as given in tutorial:
pip install pyyaml==5.1
pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html
pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.9/index.html

Using python 3.8
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py

---------------------  ----------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
numpy                  1.21.1
detectron2             0.5 @/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          CUDA 10.2
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.9.0+cu102 @/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          No: torch.cuda.is_available() == False
Pillow                 8.3.1
torchvision            0.10.0+cu102 @/hpc/scratch/hdd1/..../conda_envs/cfu2_env/lib/python3.8/site-packages/torchvision
fvcore                 0.1.5.post20210804
iopath                 0.1.8
cv2                    4.5.3
---------------------  ----------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,


If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues - tried this.

Thanks

**Comment by anirbankonar123** [comment]
Please note : we are running in GPU env in onDemand Jupyter notebook, though this is given in virtual env:GPU available          No: torch.cuda.is_available() == False
!nvidia-smi in notebook shows:
Tue Aug 10 09:16:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:02:00.0 Off |                  N/A |
| 23%   30C    P8     8W / 250W |   7287MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     10329      C   ..._envs/cfu2_env/bin/python     7283MiB |
+-----------------------------------------------------------------------------+

**Comment by anirbankonar123** [comment]
Tried with cuda111 , and getting same error as well:
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html

python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html

output of collect_env.py:
---------------------  ----------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
numpy                  1.21.1
detectron2             0.5 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          CUDA 11.1
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.9.0+cu111 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          No: torch.cuda.is_available() == False
Pillow                 8.3.1
torchvision            0.10.0+cu111 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/torchvision
fvcore                 0.1.5.post20210804
iopath                 0.1.8
cv2                    4.5.3
---------------------  ----------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by anirbankonar123** [comment]
Inside the Jupyter notebook: collect_Env.py gives:

----------------------  -----------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
numpy                   1.21.1
detectron2              0.5 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   /hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu111 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   GeForce GTX 1080 Ti (arch=6.1)
CUDA_HOME               None - invalid!
Pillow                  8.3.1
torchvision             0.10.0+cu111 @/hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/torchvision
torchvision arch flags  /hpc/scratch/hdd1/axk88432/conda_envs/cfu3_env/lib/python3.8/site-packages/torchvision/_C.so
fvcore                  0.1.5.post20210804
iopath                  0.1.8
cv2                     4.5.3
----------------------  -----------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by ppwwyyxx** [comment]
> transforms = aug_input.apply_augmentations(self.augmentations)

This line in your dataset mapper does not follow the API of `apply_augmentations`.
An easier way to apply augmentation is shown in the default dataset mapper: https://github.com/facebookresearch/detectron2/blob/7825f076c28103933d6424ecf2caaad59943c5d5/detectron2/data/dataset_mapper.py#L163-L164

**Comment by anirbankonar123** [comment]
Thanks, this resolved the issue.
