### ISSUE TITLE
Maximal number of object is not taken into account in coco evaluator

### ISSUE THREAD

**Issue by akkiss** [facebookresearch/detectron2#3359]
I've trained a detector model with the [tools/train_net.py](https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py) tool using a config yaml. In my application, there are many objects in an image so I had to increase the TEST.DETECTIONS_PER_IMAGE value to 1000 but this resulted in poor AP results with the COCOEvaluator even though the overlay images seemed pretty good.

The problem is that this setting is not handed over to the evaluator. The COCOEvaluator class does not store such value, and when the evaluation is actually done, the COCOEval or COCOEval_opt classes are instantiated in [_evaluate_predictions_on_coco](https://github.com/facebookresearch/detectron2/blob/7825f076c28103933d6424ecf2caaad59943c5d5/detectron2/evaluation/coco_evaluation.py#L553]) function where they are set up with default parameters and are not updated any more. Hence even though the inference may pass 1000 detections to the evaluation, only the top 100 is kept for evaluation by default.

For my use case I simply modified the default values but of course this is not a proper solution. I'm not familiar enough with the detectron2 code to confidently solve the issue. Would it be acceptable to propagate object number limits to COCOEvaluator constructor and later update COCOEval/COCOEval_opt.params.maxDets accordingly?

## Instructions To Reproduce the 🐛 Bug:

Evaluate any model with COCOEvaluator that generally detects much more than 100 objects per image.

__Full logs__ or other relevant observations: evaluator reports poor results even when the detector works well.

## Expected behavior:

The setting for maximal number of objects per sample should be applied during evaluation.

## Environment:

```
----------------------  ----------------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.9.6 | packaged by conda-forge | (default, Jul  6 2021, 08:46:02) [MSC v.1916 64 bit (AMD64)]
numpy                   1.21.0
detectron2              0.5 @d:\kakos\vaofflinealgo\detectron2\detectron2
Compiler                MSVC 192930038
CUDA compiler           CUDA 10.1
detectron2 arch flags   d:\kakos\vaofflinealgo\detectron2\detectron2\_C.cp39-win_amd64.pyd; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1 @d:\conda\envs\torch\lib\site-packages\torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1                 TITAN RTX (arch=7.5)
CUDA_HOME               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
Pillow                  8.2.0
torchvision             0.9.1 @d:\conda\envs\torch\lib\site-packages\torchvision
torchvision arch flags  d:\conda\envs\torch\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.5.post20210630
iopath                  0.1.8
cv2                     4.5.2
----------------------  ----------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
```

**Comment by ppwwyyxx** [comment]
Agree that COCOEvaluator constructor should accept an argument that defines the maximum number of objects.

**Comment by akkiss** [comment]
In my case for example the objects also tend to be small which means that the size ranges (small/medium/large) should also be adjusted. I've added maximal number of detections and size ranges to default configuration, passed these to _COCOEvaluator_ initialization and apply these settings to the _COCOeval_ objects created during evaluation. The default settings mean no modification to _COCOeval.params_. If this is considered a sensible solution I can send a pull request for it.

**Comment by ppwwyyxx** [comment]
An option is added to COCOEvaluator: https://detectron2.readthedocs.io/en/latest/modules/evaluation.html#detectron2.evaluation.COCOEvaluator
