### ISSUE TITLE
Missing hardware setup for inference time in model zoo. 

### ISSUE THREAD

**Issue by vighneshbirodkar** [facebookresearch/detectron2#3362]
## 📚 Documentation Issue

* Provide a link to an existing documentation/comment/tutorial:
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

* How should the above documentation/comment/tutorial improve:
Clarify the hardware setup for inference time measurements. I would guess it is V100, but would be nice to state it in the zoo page.

**Comment by ppwwyyxx** [comment]
The doc now says " All numbers were obtained on Big Basin servers with 8 NVIDIA V100 GPUs & NVLink".
