### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by gentlezr** [facebookresearch/detectron2#3367]
Hi I use one GPU to re-train the RetinaNet but I cannot get the results from your paper. I run the train_net.py follow your guide .

When I run:
`
./train_net.py --config-file ../configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025  OUTPUT_DIR BaseOutput
`
The training process can end normally，but the results are very far from your reported in the paper.

I think the learning rate may influence this results so I change the command and run below:
`
./train_net.py --config-file ../configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 OUTPUT_DIR BaseOutputDefaultLR
`
I set the default LR  but the training breaks with a error which err-msg is below:
`FloatingPointError: Loss became infinite or NaN at iteration=3666!
loss_dict = {'loss_cls': nan, 'loss_box_reg': inf}
`
So my questing is bellow:

1. Are there any skills to set the learning rate? 
2. What result is acceptable when I only have one GPU?

Thanks a lot and have a good time!

**Comment by anas-zafar** [comment]
@gentlezr were you able to solve the problem?
