### ISSUE TITLE
How to run demo.py?

### ISSUE THREAD

**Issue by ZYN-guy** [facebookresearch/detectron2#337]
I successfully trained mask_rcnn_R_50_FPN_1x.
But when I run:
 python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
  --input 000000000001.jpg \
	[--other-options]
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137849600/model_final.pkl

Result:
 000000000001.jpg: detected 0 instances in 0.28s
Qt: Cannot set locale modifiers:

How to solve this problem？

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md#expected-behavior) says:

> If there are no obvious error in "what you observed" provided above, please tell us the expected behavior.
If you expect the model to work better, note that we do not help you train your model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

**Comment by lkmy** [comment]
the MODEL.WEIGHTS should be the loccation of your trained model 
eg. 
--opts MODEL.WEIGHTS {detectron2 home}/output/model_final.pth

**Comment by ZYN-guy** [comment]
Thank you for your reply！
I run:
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
  --input 000000000001.jpg \
	[--other-options]
  --opts MODEL.WEIGHTS detectron2:/home/zhangyanan/Desktop/pytorch/aa/detectron2/output/model_final.pth

It still doesn't work. Could you give me a complete command? 
Thank you

**Comment by ppwwyyxx** [comment]
I don't know what you meant by "doesn't work". That's why the issue template says:
> If there are no obvious error in "what you observed" provided above, please tell us the expected behavior.

If you think there are errors, could you tell what you expect?

**Comment by ZYN-guy** [comment]
I'm sorry I didn't make myself clear.  I mean, after training, how to test？
eg.
I run python tools/train_net.py \
	--config-file configs/COCO-Detetion/retinanet_R_101_FPN_3x.yaml \
	SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
Successful and I get model_final.pth
How do I detecte images by model.final.py?
Could you give me a complete command?
Thank you!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-with-pre-trained-models

**Comment by ZYN-guy** [comment]
Run:
python demo/demo.py --config-file configs/COCO-Detection/retinanet_R_101_FPN_3x.yaml \
  --input 000000000001.jpg 000000000448.jpg \
	[--other-options]
  --opts MODEL.WEIGHTS detectron2://output/model_final.pth
Results:
The checkpoint contains parameters not used by the model
And I only get a  original image. I don't think my code is wrong.

**Comment by ppwwyyxx** [comment]
I don't think this command will run at all because there is no model called "detectron2://output/model_final.pth". Please post the correct command.
You should use the path to your model, without "detectron2://".
