### ISSUE TITLE
Don't pin black dependency

### ISSUE THREAD

**Issue by piegamesde** [facebookresearch/detectron2#3384]
## 🚀 Feature
The `setup.py` requires `black==21.4b2`. Please make it work with newer black versions (`black>=21.4b2`), otherwise pip will throw `ERROR: Could not find a version that satisfies the requirement black==21.4b2 (from detectron2)`.

## Motivation & Examples

I'm a downstream package maintainer and the distro provides black version `21.7b0`, which is newer. If `black` is following SemVer, they ought to be compatible.

**Comment by ppwwyyxx** [comment]
> If black is following SemVer, they ought to be compatible.

The reality is they are not compatible. And we have to pin to a specific version that facebook is using internally. So unfortunately I think there is no better solution.

**Comment by piegamesde** [comment]
That's sad. Can you please elaborate in which ways those are or may not be compatible?

**Comment by ppwwyyxx** [comment]
When trying it I found that the main issue is that all black releases are pre-releases, and as a result pip cannot install them using version specifiers like `black>=21`:
```
$pip install --user -U 'black>=20'
ERROR: Could not find a version that satisfies the requirement black>=20
ERROR: No matching distribution found for black>=20
```
