### ISSUE TITLE
How to customise the directory for pretrained model

### ISSUE THREAD

**Issue by lzrobots** [facebookresearch/detectron2#340]
I see the the directory for the pretrained model is in `~/.torch/fvcore_cache`
https://github.com/facebookresearch/fvcore/blob/master/fvcore/common/file_io.py#L33

How to set `FVCORE_CACHE` for this repo detectron2?

**Comment by ppwwyyxx** [comment]
`export FVCORE_CACHE=/some/where`.
You can learn more about environment variables from google.
