### ISSUE TITLE
Location of pickle files for DensePose

### ISSUE THREAD

**Issue by aowais2** [facebookresearch/detectron2#341]
This might be something of a newbie question, but I am currently trying to reproduce the DensePose results using Google Collaboratory.
I am following the "Getting started with DensePose" directions and am trying to run the following code

!python apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl image.jpg dp_contour,bbox --output image_densepose_contour.png

I get an error to the effect that the pickle file is not found. I understand that this is because I do not reference such a file anywhere since I cannot find it in the Detectron2_repo.
Do I need to download the pickle file using some sort of a URL? I know the other implementations have URLs from which they download pickle files such as:
detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl

Here's the full error for reference:
Config 'configs/densepose_rcnn_R_50_FPN_s1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "apply_net.py", line 309, in <module>
    main()
  File "apply_net.py", line 305, in main
    args.func(args)
  File "apply_net.py", line 73, in execute
    predictor = DefaultPredictor(cfg)
  File "/content/detectron2_repo/detectron2/engine/defaults.py", line 154, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py", line 100, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint densepose_rcnn_R_50_FPN_s1x.pkl not found!

**Comment by ppwwyyxx** [comment]
The models are downloaded from the model zoo: https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/doc/MODEL_ZOO.md#coco-densepose-baselines-with-densepose-rcnn
