### ISSUE TITLE
I can't take the tensor out of Boxes

### ISSUE THREAD

**Issue by danke1** [facebookresearch/detectron2#3424]
**I have a bbox which type is "detectron2.structures.boxes.Boxes" by using detectron2_tutorial** 

(https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=Vk4gID50K03a)

**I want to change the bbox's type to 1-dimensional list.**
Boxes(tensor([[394.0943, 182.6578, 528.1948, 585.4409]], device='cuda:0'))

**How can I take the tensor out of Boxes???**

**Comment by ppwwyyxx** [comment]
Please see https://detectron2.readthedocs.io/en/latest/modules/structures.html#detectron2.structures.Boxes.tensor

**Comment by danke1** [comment]
I did like this, very simple.
list(boxes)[0].tolist()
