### ISSUE TITLE
Custom Mapper tutorial does not work

### ISSUE THREAD

**Issue by mjack3** [facebookresearch/detectron2#3427]
## 📚 Documentation Issue or not clear
Hello, I am following [this](https://detectron2.readthedocs.io/en/latest/tutorials/data_loading.html#write-a-custom-dataloader) in order to replycate how to use a custom mapper.

So if I just copy the example in the documentation

```
def custom_mapper(dataset_dict):
    dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below
    # can use other ways to read image
    image = utils.read_image(dataset_dict["file_name"], format="BGR")
    # See "Data Augmentation" tutorial for details usage
    auginput = T.AugInput(image)
    transform = T.Resize((800, 800))(auginput)
    image = torch.from_numpy(auginput.image.transpose(2, 0, 1))
    annos = [
        utils.transform_instance_annotations(annotation, [transform], image.shape[1:])
        for annotation in dataset_dict.pop("annotations")
    ]
    return {
        # create the format that the model expects
        "image": image,
        "instances": utils.annotations_to_instances(annos, image.shape[1:])
    }
```

And then, follwing [this](https://detectron2.readthedocs.io/en/latest/tutorials/data_loading.html#use-a-custom-dataloader) i overwrited the build_{train,test}_loader method

```
class MyTrainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg):
        train_dataloader =  build_detection_train_loader(cfg, mapper=custom_mapper)
        return train_dataloader

    @classmethod
    def build_test_loader(cls, cfg):
        test_dataloader = build_detection_train_loader(cfg, mapper=custom_mapper)
        return test_dataloader
```
I get this error when start to train

```
w, h = d["width"], d["height"]
KeyError: 'width'
```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by mjack3** [comment]
I solved the error

**Comment by narenakash** [comment]
@mjack3 I'm also facing the same issue. Could you share how you solved it?

Thanks in advance.

**Comment by mjack3** [comment]
@narenakash 

Yes, if you check the [documentation](https://detectron2.readthedocs.io/en/latest/tutorials/data_loading.html#write-a-custom-dataloader), it says 

# create the format that the model expects

In my case, it is faster 50, so the input model format acording to the [documentation](https://detectron2.readthedocs.io/en/latest/tutorials/models.html#model-input-format) also needs:

“height”, “width”:

**Comment by andreped** [comment]
@mjack3 I'm completely failing to see what I am doing wrong here...

I had already added both height and width to the JSON-file.

Could you share a simple script where you got it working? Maybe it is easier to spot what was missing?

I am also working with custom mappers, as my images are stored in a unorthodox, nonsupported format.
