### ISSUE TITLE
how to add 'ignore' label in my coco-style datasets?

### ISSUE THREAD

**Issue by sophia-hxw** [facebookresearch/detectron2#343]
hi,

I'm doing some training with a coco-style dataset which have two kind of labels that are 'person' and 'ignore'. My problem is I do not know where can I add the 'ignore' label to my dataset? And how can I used the label in my training with detectron2?

my data is like:

1. info 
- something

2. annotations
- segmentation
- area
- iscrowed
- bbox
- image_id
- category_id
- id

3. images
- something

4. categories
- something

Thanks a lot~
Best wishes!

**Comment by ppwwyyxx** [comment]
I don't think I understand what your expected behavior is. If you simply don't want to train on the second category you can remove them from your annotations. Wouldn't this work?
