### ISSUE TITLE
Add new loss

### ISSUE THREAD

**Issue by animareversed** [facebookresearch/detectron2#345]
Hi,
Where should I add a new loss in order to display it in the CommonMetricPrinter?
Thanks

**Comment by ppwwyyxx** [comment]
Return it in the model together with other losses, and make sure the name contains the word "loss".

**Comment by animareversed** [comment]
Thanks, and how can I show also images in tensorboard?

**Comment by ppwwyyxx** [comment]
we'll work on adding image support soon
