### ISSUE TITLE
What is the default PROBABILITY when using detectron2.data.transforms.ResizeShortestEdge in config?

### ISSUE THREAD

**Issue by melodjia** [facebookresearch/detectron2#3460]
When we tune augmentation in config, we have a detectron2.data.transforms.RandomFlip. The default probability is 0.5 and we can change this value. 
1) But what is the default PROBABILITY when using detectron2.data.transforms.ResizeShortestEdge in config (INPUT.MIN_SIZE_TRAIN, INPUT.MAX_SIZE_TRAIN, INPUT.MIN_SIZE_TRAIN_SAMPLING) 
2) and how can we change this value? Maybe use detectron2.data.transforms.RandomApply?

**Comment by ppwwyyxx** [comment]
This augmentation always do resize, so there is no probability setting. You can use `RandomApply` on it to give it a probability.
