### ISSUE TITLE
What is the input image resolution of different models in the Detectron2 Model Zoo?

### ISSUE THREAD

**Issue by melodjia** [facebookresearch/detectron2#3461]
What is the input image resolution (image size) of different models in the Detectron2 Model Zoo? For example, when using an image with a 4K resolution as input, to what size does it transform, for example, in the R50-FPN model or another model? Where can I find this information?

**Comment by AmitAilianiSDC** [comment]
Following!!

**Comment by sukjunhwang** [comment]
Unless changes from the default config file (detectron2/config/defaults.py) are noted, the default test pipeline resizes the input images with the parameters below.
```
_C.INPUT.MIN_SIZE_TEST = 800
_C.INPUT.MAX_SIZE_TEST = 1333
```

Please refer to the implementation of **ResizeShortestEdge** in detectron2/data/transforms/augmentation_impl.py to see how the images get transformed with the parameters.

**Comment by melodjia** [comment]
> Если не будут отмечены изменения из файла конфигурации по умолчанию (detectron2/config/defaults.py), тестовый конвейер по умолчанию изменяет размер входных образов с параметрами ниже.
> 
> ```
> _C.INPUT.MIN_SIZE_TEST = 800
> _C.INPUT.MAX_SIZE_TEST = 1333
> ```
> 
> Пожалуйста, ознакомьтесь с реализацией **ResizeShortestEdge **в detectron2/data/transforms/augmentation_impl.py, чтобы узнать, как изображения трансформируются с помощью параметров.


You did not understand me.  Different models have different input sizes and must match the size of the image.  My question is: What is the input image resolution of different models in the Detectron2 Model Zoo?

**Comment by ppwwyyxx** [comment]
> Image resolution must match the input size of the pre-trained.

No. You can use any image resolution that you think is reasonable for any models in detectron2 model zoo. 

The default resolution that we use is answered above by https://github.com/facebookresearch/detectron2/issues/3461#issuecomment-914920231

**Comment by mahilaMoghadami** [comment]
> Unless changes from the default config file (detectron2/config/defaults.py) are noted, the default test pipeline resizes the input images with the parameters below.
> 
> ```
> _C.INPUT.MIN_SIZE_TEST = 800
> _C.INPUT.MAX_SIZE_TEST = 1333
> ```
> 
> Please refer to the implementation of **ResizeShortestEdge** in detectron2/data/transforms/augmentation_impl.py to see how the images get transformed with the parameters.

hello
you mean that for image with size (900*900), which resizing is done in detectrone2?
