### ISSUE TITLE
Urgently! About input image resolution of different pre-trained MODELS

### ISSUE THREAD

**Issue by melodjia** [facebookresearch/detectron2#3464]
Different pre-trained models have different input sizes because **already have a architecture defined**. Image resolution must match the input size of the pre-trained. My question is: What is the input image resolution of different pre-trained models in the Detectron2 Model Zoo? Maybe I don't understand something.. Please explain how the correspondence of the image size and the input size of the pre-trained model in Detectron2 **is achieved**

**Comment by ppwwyyxx** [comment]
Duplicate of #3461
