### ISSUE TITLE
After changing DefaultTrainer from  inheritance to composition

### ISSUE THREAD

**Issue by edwardpwtsoi** [facebookresearch/detectron2#3483]
When I run the latest version of detectron2 on a old project it result in an attribute error saying trainer has no attribute _data_loader_iter

After reviewing recent changes I think this line should be changed from super().train() to self._trainer.train()

https://github.com/facebookresearch/detectron2/blob/ce5b1c5afe93919d14adf0fef27d608300a5171e/detectron2/engine/defaults.py#L483

let me know if I misunderstood, Thank you for your great work!

**Comment by ppwwyyxx** [comment]
We found that not enough information is provided about this issue.
Please provide details following the issue template.
