### ISSUE TITLE
Lossing the file: box_iou_rotated_cuda.obj 文件缺失

### ISSUE THREAD

**Issue by Louis24** [facebookresearch/detectron2#3487]
After install all dependency
run this commend
python setup.py build develop

got the error
(base) C:\Users\vorte\Downloads\detectron2-main>python setup.py build develop
c:\users\vorte\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\vorte\anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\users\vorte\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
running build
running build_py
running build_ext
c:\users\vorte\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in p
osition 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'detectron2._C' extension
Emitting ninja build file C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /M
ANIFESTUAC:NO /LIBPATH:c:\users\vorte\anaconda3\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib/x64" /LIBPATH:C:\Users\v
orte\Anaconda3\libs /LIBPATH:C:\Users\vorte\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMF
C\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSD
K\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10
.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit__C C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Re
lease\Users\vorte\Downloads\detectron2-main\detectron2\layers\csrc\vision.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloa
ds\detectron2-main\detectron2\layers\csrc\box_iou_rotated\box_iou_rotated_cpu.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Dow
nloads\detectron2-main\detectron2\layers\csrc\cocoeval\cocoeval.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detectr
on2-main\detectron2\layers\csrc\nms_rotated\nms_rotated_cpu.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detectron2-
main\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cpu.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detectr
on2-main\detectron2\layers\csrc\box_iou_rotated\box_iou_rotated_cuda.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\de
tectron2-main\detectron2\layers\csrc\deformable\deform_conv_cuda.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detect
ron2-main\detectron2\layers\csrc\deformable\deform_conv_cuda_kernel.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\det
ectron2-main\detectron2\layers\csrc\nms_rotated\nms_rotated_cuda.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detect
ron2-main\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.obj C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\d
etectron2-main\detectron2\layers\csrc\cuda_version.obj /OUT:build\lib.win-amd64-3.6\detectron2\_C.cp36-win_amd64.pyd /IMPLIB:C:\Users\vorte\Downloads\detectron2-main\build
\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detectron2-main\detectron2\layers\csrc\_C.cp36-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\vorte\Downloads\detectron2-main\build\temp.win-amd64-3.6\Release\Users\vorte\Downloads\detectron2-main\detectron2\la
yers\csrc\box_iou_rotated\box_iou_rotated_cuda.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

"Instructions To Reproduce the Issue and Full Logs"
pip install --ignore-installed -e .

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues says we don't provide support for issues on windows.
