### ISSUE TITLE
Bug of performance in trainer.model and predictor.model

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#3493]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
The below two codes are same except for using "trainer.model" and "predcitor.model" for evaluation of performance.
 
```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("balloon_val")
val_loader = build_detection_test_loader(cfg, "balloon_val")
print(inference_on_dataset(trainer.model, val_loader, evaluator))
```

```
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("balloon_val")
val_loader = build_detection_test_loader(cfg, "balloon_val")
print(inference_on_dataset(predictor.model, val_loader, evaluator))
```

While trainer.model can be done after trainer should be defined and finished, predictor.model can be executed with pre trained weight without execution of trainer. So, in most of real applications, "predictor.model" may be more practical.
However, currently, the performance is decreased more in "predictor.model" when compared to "trainer.model".

Why two are different?

## Environment:

```Detectron2 basic configuration```

**Comment by ppwwyyxx** [comment]
That depends the code & config that creates `trainer` and `predictor`. With same config options & model weights, they are expected to produce same results. 
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
