### ISSUE TITLE
Potential Issue in NMS Implementation 

### ISSUE THREAD

**Issue by IssacCyj** [facebookresearch/detectron2#3496]
Not sure if this counts as a bug, but I found that in the implementation of NMS, there might be a corner case where a bbox is assigned several different classes after NMS during inference. [In [faster_rcnn_inference_single_image() funtion](https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/roi_heads/fast_rcnn.py#L118)]

Here's an example, if bbox \Beta has prediction scores higher than nms_thresh for class A (score_A) and class B (score_B). And in the meantime, score_A rank top K among all the bboxes for class A, and same for score_B in class B. You will end up having two duplicate boxes \Beta with prediction classes for class A and class B. I'm wondering if this is an expected behavior for multi-class NMS or it's an implementation issue?

Please correct me if I'm wrong, thanks!

Yujia

**Comment by ppwwyyxx** [comment]
This is an expected behavior.
