### ISSUE TITLE
building error : undefined reference to `google::protobuf::RepeatedPtrField<std::string>::begin() const'

### ISSUE THREAD

**Issue by ahong007007** [facebookresearch/detectron2#3508]
## Instructions To Reproduce the 🐛 Bug:
1. I follow the example:
"detectron2/tools/deploy/" 
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/tmp/datasets/driver/libtorch ..

![image](https://user-images.githubusercontent.com/22077027/134310762-1cc3bf01-0ab6-41c3-9e28-98c80afafd03.png)

ERROR happends:An error occurred

undefined reference to `google::protobuf::RepeatedPtrField<std::string>::begin() const'

When I compiled protobuf, I used the official mirroring method. 
“”detectron2/docker/deploy.Dockerfile“”
![image](https://user-images.githubusercontent.com/22077027/134309803-858f5ee6-3715-4c33-af83-e1402bee6121.png)

when i set export CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 or export CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=1,The end result is the same

2.Although, torchscript_traced_mask_rcnn still generates an executor, the model model can happen correctly. If you do not perform the problem solving, thank you for the consequences of your project?
![image](https://user-images.githubusercontent.com/22077027/134311226-e1f9e894-928b-4fb2-bc0c-b99a0e020120.png)

**Comment by ppwwyyxx** [comment]
The build should work in our docker file. If you can provide a docker file that reproduces the failure then we can take a look.

`torchscript_traced_mask_rcnn` is different from the binary that fails to build. if `torchscript_traced_mask_rcnn` is all you need then the failure can be ignored.
