### ISSUE TITLE
how to make data loader from format similar to (but not same as) LabelMe format

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/detectron2#351]
Suppose you have thousands of XML files containing the object/semantic annotations for each of a corresponding number of JPEG image files (1 XML file per 1 JPG file).

How to write a data loader to parse the directory of XML files and create a single .JSON file in the format that Detectron2 expects (similar to the trainval.json or via_region_data.json example files from the balloon tutorial)?

Here we see that we need to get the model input format to 

>  take a list[dict] as the inputs. Each dict corresponds to information about one image.

Our annotation is based off the LabelMe format, with XML files in the following format:

```

<?xml version="1.0"?>

-<annotation>

<filename>2019_image_file.jpg</filename>

<folder>uploads</folder>


-<source>

<sourceImage>The MIT-CSAIL database of objects and scenes</sourceImage>

<sourceAnnotation>LabelMe Webtool</sourceAnnotation>

</source>


-<object>

<name>my_class_label_name_1</name>

<deleted>0</deleted>

<verified>0</verified>

<occluded/>

<attributes/>


-<parts>

<hasparts/>

<ispartof/>

</parts>

<date>27-Jun-2019 22:00:32</date>

<id>0</id>


-<polygon>

<username>my_user_name</username>


-<pt>

<x>399</x>

<y>401</y>

</pt>


-<pt>

<x>376</x>

<y>415</y>

</pt>


-<pt>

<x>379</x>

<y>433</y>

</pt>


-<pt>

<x>396</x>

<y>435</y>

</pt>

<xmin>376</xmin>

<ymin>401</ymin>

<xmax>399</xmax>

<ymax>435</ymax>

</polygon>

</object>
```

How to get this into a COCO format such that it can be ingested into Detectron2?
Trying to load the dataset into detectron2's standard format.
Then register the dataset using `register_coco_instances`  (or now `register_coco.py`)

**Comment by ppwwyyxx** [comment]
You should write your own function with python for your custom format, similar to the balloon tutorial.

**Comment by sshl** [comment]
This script [https://github.com/aaronlelevier/mlearning/blob/master/mlearning/coco.py](url) may help you generating COCO 2014 formatted annotations from Labelme annotations' format.

**Comment by sshl** [comment]
This script [https://github.com/aaronlelevier/mlearning/blob/master/mlearning/coco.py](url) may help you generating COCO 2014 formatted annotations from Labelme annotations' format.

**Comment by sshl** [comment]
This script [https://github.com/aaronlelevier/mlearning/blob/master/mlearning/coco.py](https://github.com/aaronlelevier/mlearning/blob/master/mlearning/coco.py) may help you generating COCO 2014 formatted annotations from Labelme annotations' format.
