### ISSUE TITLE
Problem to follow installation instructions

### ISSUE THREAD

**Issue by Zawarud** [facebookresearch/detectron2#3510]
## 📚 Documentation Issue
If I follow the instructions from the site to install. In my case (pytorch 1.9 cuda 111): 
```
pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html
```
give me : 
```
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
```
Using win10, py3.9 in a venv.

**Comment by ppwwyyxx** [comment]
As the instruction says, this installation method is linux only. https://detectron2.readthedocs.io/en/latest/tutorials/install.html#install-pre-built-detectron2-linux-only
