### ISSUE TITLE
Changing  "FrozenBN" to "BN" reduces AP

### ISSUE THREAD

**Issue by Vibashan** [facebookresearch/detectron2#3545]
I wanted to include Batchnorm parameters during training. So I changed _C.MODEL.RESNETS.NORM = "FrozenBN" to "BN".

However, when using FrozenBN, the model produces "AP50: 71.8," but while using BN, the model performance reduces to 40.9. Why does the "BN" model performance reduce? Am I missing something?

My config file:
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    NORM: "BN"
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval",)
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 8

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
