### ISSUE TITLE
Getting only the masks of detected objects

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#356]
Hello,
I'm using detectron2 to detect beds in images.
I want to get an image of only the masks, I saw some posts about doing this using the original detectron ("detectron1") but couldn't do it in detectron2. 

In addition to that, how do I make it so that the masks are only in black (and with no alpha)? 

Thanks! 
btw, I am very new to detectron2 so I hope my questions are not irrelevant.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

As the above link says, each output of a model has `output['instances'].pred_masks`.

**Comment by ItamarSafriel** [comment]
OK, thanks, completely missed this. 

Can you please explain me how do I detect only one class (again, found some posts on doing this in "detectron1" but couldn't do it in 2). 

BTW, I don't know if I am supposed to open a new issue or its fine to ask this here.
Thanks in advance!

**Comment by ppwwyyxx** [comment]
The official [colab tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) does train a model to detect only one class.

**Comment by ItamarSafriel** [comment]
OK,thank you very much!
I need to detect only beds, do you know where can I find an data-set containing only beds? I tried playing around with the COCO data-set but failed:(

**Comment by ppwwyyxx** [comment]
The original issue is resolved. If you met other problems, please post about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
