### ISSUE TITLE
SOLVER.IMS_PER_BATCH and SOLVER.BASE_LR setting

### ISSUE THREAD

**Issue by TakeruIto** [facebookresearch/detectron2#357]
## ❓ Questions and Help

GETTING_STARTED.md mentions that 
SOLVER.IMS_PER_BATCH:8 and SOLVER.BASE_LR:0.01 are for 8 GPUs. So when we train with 1 GPU, change SOLVER.IMS_PER_BATCH 2 and SOLVER.BASE_LR 0.0025.

I think SOLVER.IMS_PER_BATCH 1 and SOLVER.BASE_LR 0.00125 is correct for single GPU. Which is correct?

**Comment by ppwwyyxx** [comment]
> GETTING_STARTED.md mentions that
SOLVER.IMS_PER_BATCH:8 and SOLVER.BASE_LR:0.01 are for 8 GPUs. 

No it does not mention this.

You can also you batch=1, it's all up to you.
