### ISSUE TITLE
How to add a validation set in detectron2_tutorial notebook

### ISSUE THREAD

**Issue by yon100** [facebookresearch/detectron2#358]
In the detectron2_tutorial notebook the following line appears:
`cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset`
Indeed, setting  `cfg.DATASETS.TEST` to `("balloon_val",)` results in NotYetImplemented error.
How can I nevertheless add a validation set to the training? 
I understand (https://github.com/facebookresearch/Detectron/issues/173) that in Detectron there was a field named `FORCE_JSON_DATASET_EVAL` under `DATASETS.TEST`, which should have been set to `True` for using COCO evaluation, but it no longer exists.

**Comment by ppwwyyxx** [comment]
The code should have thrown the instructions together with the error:
https://github.com/facebookresearch/detectron2/blob/f485b4684c5cf58b53263706be386f57e28d1841/detectron2/engine/defaults.py#L415-L425

The builtin `tools/train_net.py` supports evaluation of validation set already.

**Comment by yon100** [comment]
@ppwwyyxx, thanks!
