### ISSUE TITLE
Ray Tune or any other Parameter tuning  

### ISSUE THREAD

**Issue by Programmer-RD-AI** [facebookresearch/detectron2#3595]
## 🚀 Feature
Ray Tune or any other Parameter tuning.
Example
`params = {'A':[59,98,59,59],'B':[479]}`
`DefaultTrainer(cfg,params=params).resume_or_load(resume=False).train()`

## Motivation & Examples

It's useful for Parameters tuning 

With best regards,
Ranuga

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory contains many such examples.

**Comment by ppwwyyxx** [comment]
We don't plan to add features like this. Detectron2 can accept parameters and do training, so I believe such features can already be implemented independently outside of detectron2.
