### ISSUE TITLE
Train on datasets larger than memory

### ISSUE THREAD

**Issue by juaniio** [facebookresearch/detectron2#3605]
I wish to train a MaskRCNN model, but I can't fit all training set annotations as a `list[dict]` in memory (as I understand, this is needed when using `DatasetCatalog`).

How can we train really large models, where the annotations alone are vastly larger than the memory size?

**Comment by ishank-juneja** [comment]
@juanilarregui did you figure it out?

**Comment by zhanghang1989** [comment]
D2Go support disk cache option. You might be interested in https://github.com/facebookresearch/d2go/commit/87374efb134e539090e0b5c476809dc35bf6aedb

**Comment by ishank-juneja** [comment]
Thanks, I think I won't need it since we pass a path to an image and not the images themselves but will keep in mind

**Comment by austinmw** [comment]
@zhanghang1989 Hey, does D2Go cache option require training from the more limited D2Go Model Zoo? If so, is there any way to train on datasets where annotations don't fit into memory and still be able to choose from any detectron2 model?

**Comment by zhanghang1989** [comment]
> @zhanghang1989 Hey, does D2Go cache option require training from the more limited D2Go Model Zoo? If so, is there any way to train on datasets where annotations don't fit into memory and still be able to choose from any detectron2 model?
> 
> (I have a very large dataset to train, but am not interested in a model optimized for mobile deployment)

D2Go should support training for all Detectron2 model configs.
