### ISSUE TITLE
Sequential Training Sampler

### ISSUE THREAD

**Issue by rozeappletree** [facebookresearch/detectron2#3630]
Is there any training sampler that does training in sequence (based on ascending order record ids in data dictionaries). I have frame by frame image detection annotation data where objects are moving. I want to use them in their exact sequence. Ability to add a small lstm head will be a big plus

**Comment by INF800** [comment]
As in this line, https://github.com/facebookresearch/detectron2/blob/175b2453c2bc4227b8039118c01494ee75b08136/detectron2/config/defaults.py#L121

How do we set `shuffle=False`

**Comment by meowpass** [comment]
I also have the problem. Acutally, I find that we can only designate the kind of sampler, but cannot set the 'shuffle=False'. Have you handled that? I really need somebody's help!

>
