### ISSUE TITLE
Question about docs:  should image_id be str or int?

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/detectron2#364]
Question about format of Dataset.  From the docs,
https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/datasets.md

the image_id is supposed to be a string, which is unusual, as typically we use an integer for IDs.

> image_id (str): a string to identify this image. Used during evaluation to identify the image, but a dataset may use it for different purposes.

Also, the balloon tutorial does NOT use a str for the image_id.  Rather it uses an int:

```
    for idx, v in enumerate(imgs_anns.values()):
        record = {}
        
        filename = os.path.join(img_dir, v["filename"])
        height, width = cv2.imread(filename).shape[:2]
        
        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width
```

So I am confused by this inconsistency:  should we use a string or an integer for our image_id key?  Thanks

**Comment by ppwwyyxx** [comment]
It can be either a string or an int. We'll update the docs to reflect this.
