### ISSUE TITLE
How to load and merge cfg from '.py' file instead of '.yaml' file?

### ISSUE THREAD

**Issue by HugoHann** [facebookresearch/detectron2#3640]
If I use the models from new_baselines, I must load and merge cfg from .py file. But seems like there is no function to do these, there are only load_yaml_with_base function in merge_from_file. What should I do?

**Comment by ppwwyyxx** [comment]
python configs can be loaded according to https://detectron2.readthedocs.io/en/latest/tutorials/lazyconfigs.html

The concept of "merging" is invalid for python config files because they don't have pre-defined structures. So there is no such functionality.
