### ISSUE TITLE
What are the difference between instances_predictions.pth and the model files saved outside the inference folder? 

### ISSUE THREAD

**Issue by PeiSeng** [facebookresearch/detectron2#365]
Hi, 

May I know what are the difference between instances_predictions.pth and the model files saved outside the inference folder? 

Thanks.

**Comment by ppwwyyxx** [comment]
`instances_predictions.pth` are the predictions made by the model on the validation set.

**Comment by Musbell** [comment]
@ppwwyyxx may i know their use cases maybe in terms of deployment?

**Comment by sameer00123** [comment]
I have a similar question. I ran the evaluation on a 3000-image set; however, got a numpy.float64 error right before the AP results.  When I checked the inference folder, found this "instances_prediction.pth" file there. Is there a way to load it and not run the predictions again?
