### ISSUE TITLE
performance of VisualizationDemo(parallel) / AsyncPredictor demonstrated is not expected and some other questions.

### ISSUE THREAD

**Issue by seangaringle** [facebookresearch/detectron2#3652]
hi [@ppwwyyxx](https://github.com/ppwwyyxx), I've been trapped in the unexpected speed when doing inference with `VisualizationDemo(parallel=True) / AsyncPredictor` for a period of time. Classes mentioned above are from `detectron2/demo/predictor.py`.

I've searched some related quetions in Issues like [https://github.com/facebookresearch/detectron2/issues/1488](https://github.com/facebookresearch/detectron2/issues/url) for answers; and tried to read and understand some related code files but still didn't get a convincing explanation, so I open this issue to see if you may offer some helps and inspirations, thanks!

Here are my experiments:

(1) I did something like:
```
demo = VisualizationDemo(cfg, parallel=False or True)
imgs_list = [img_1, img_2, ..., img_n]  # img = cv2.imread(...)
for img in imgs_list:
​    pred, vis = demo.run_one_image(img)  # or I removed some part codes about drawing, see below
```
test dataset contains 100 jpgs and each of them has `height, width = 1000, 1000`

(2) I have 4 gpus in one machine; when `parallel=False`, the inference costs about 14s **while 25s when True**; (this result of time-consuming is tested many times but still just a rough estimation, but also I've ever tested on different datasets, just finding the similar phenomenon as a result.)

From my poor and limited understanding:
(1) when I create an instance of the class `VisualizationDemo` like
```
vd = VisualizationDemo(cfg, instance_mode=ColorMode.IMAGE, parallel=True)
```
the attribute `vd.predictor` is an instance of the class `AsyncPredictor`, which will create 4 instances of the `_PredictWorker` (an inner class in AsyncPredictor).

(2) And also there are two `mp.Queue()` （`self.task_queue`  and `self.result_queue`）for put&get inference tasks and results for **asynchronism purpose**.

(3) class `_PredictWorker` inherits from `multiprocessing.Process` ; the 4 instances are appended in attribute `self.procs`(a python list); when calling like `p.start()`【for p in self.procs】, the function `run()` defined in class `_PredictWorker` starts working like a continuous service, respectively; each of them keeps monitoring the `self.task_queue` and does inferencing when a task is in and puts the inference result into the `self.result_queue.`

(4) when we apply `AsyncPredictor()(image)` （something related is in `VisualizationDemo.run_on_image`, it returns prediction results in an asynchronous way. It seems not like the explanation mentioned in issue1488 because the inferencing is still slow even I removed codes related with visualizer in `run_on_image` or changed the codes in `AsyncPredictor` to use only 2 or 3 gpus.

(5) From my observations, I really don't understand why 4/3/2 gpus work such slower than 1 gpu; when in 4 gpus task, I observe gpu-util panel,  it seems not all gpus are used at the same time in every moment even the `task_queue` keeps accepting tasks; besides I print the process-id of the `_PredictWorker` instance, the tasks are certainly distributed to different processes. btw, the `self.task_queue()` seems never be full (`print(self.task_queue.full())` before or after I call `AsyncPredictor(image)`) even I set `self.task_queue = mp.Queue(maxsize=1)`. Maybe it's a python mechanism of the Queue or something beyond my knowledge.
![image](https://user-images.githubusercontent.com/35868485/141042621-e58f05b1-4481-44c6-896b-93d876dde509.png)

(6) In addition, I tried the evaluator way (class method `DefaultTrainer.test` in `detectron2/engine/defaults.py`), it improves in inference speed but it seems not supporting my needs (I need models cached in gpu memory and work like a continuous service waiting for inference tasks passed in, I don't know how to describe it accurately, sorry). Anyway, from my experiments on the evaluator way, I failed to keep evaluators working the way I expected and somehow it seems that there is an oom phenomenon (evaluators are cached in gpu memory while the memories that images occupied cannot be released after inference done).

Therefore I'm just so confused for a long time, looking forward some advices and hints. Thank you very much!

**Comment by seangaringle** [comment]
Would you give me some suggestions? Thanks! @ppwwyyxx

**Comment by ppwwyyxx** [comment]
It seems like you expect
> run_one_image

to run faster when `parallel=True`.

This is not a correct expectation. When running against only one image, `parallel=True` does do any paralleism. So this is not an unexpected issue.

**Comment by seangaringle** [comment]
> It seems like you expect
> 
> > run_one_image
> 
> to run faster when `parallel=True`.
> 
> This is not a correct expectation. When running against only one image, `parallel=True` does do any paralleism. So this is not an unexpected issue.

Thanks. Like you said, I expected `run_on_image` to run faster when `parallel=True`, but not with only one image. Assume I have 100 images, and the inference costs 200ms per image when `parallel=False`, which means it costs 20s to infer 100 images. And I'm expecting this work could be done within like 5s(?) when `parallel=True` because I have 4 gpus; or even 10s is accpetable. But `demo.run_on_image(parallel=True)` seems not to work as the expcetation mentioned above. 
Could it satisfy this task or maybe I just use it in the wrong way?

**Comment by seangaringle** [comment]
@ppwwyyxx sorry for disturbance, not sure if you received replys above.

**Comment by seangaringle** [comment]
@ppwwyyxx sorry for disturbance, not sure if you received replys above.
