### ISSUE TITLE
SyncBatchNorm does not support empty inputs

### ISSUE THREAD

**Issue by rakhimovv** [facebookresearch/detectron2#366]
## ❓ Questions and Help

Hi! my model fails due to empty tensors appearing in NaiveSyncBatchNorm. Could you please suggest a way to overcome this issue?

Motivation:
One wants to use blocks with batchnorm inside bbox/mask/densepose/... heads

**Comment by ppwwyyxx** [comment]
It's just not implemented and such implementation would probably be tricky.

**Comment by fanq15** [comment]
I meet this bug too.

**Comment by ppwwyyxx** [comment]
This is supported with `NaiveSyncBatchNorm(stats_mode="N")`. 
Note that it is not exposed as a config option, so if you need you have to call this module yourself.
