### ISSUE TITLE
depoly torch script return model not same as the pytorch script in results 

### ISSUE THREAD

**Issue by AhmedHessuin** [facebookresearch/detectron2#3675]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
i just changed the anchors size and aspect ratio in the cfg
```
cfg.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.25, 0.5, 1.,2,2.5]]
cfg.MODEL.ANCHOR_GENERATOR.SIZES= [[8], [16], [32], [64], [128]]
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff
<put code or diff here>
2. What exact command you run:
```
/home/appuser/detectron2_repo/tools/deploy/export_model.py --config-file cfg.yaml    --output ./output --export-method tracing --format torchscript --sample-image input.jpg    MODEL.WEIGHTS model_final.pth MODEL.DEVICE cpu
```
3. __Full logs__ or other relevant observations:
```
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.
i trained model normally with default anchor boxes sizes and ratio once, and with modified aspect ratio and anchor boxes sizes once
## Expected behavior:
when transferring the pytorch to torch script with default anchors size and ratio i get the same result example, training with anchors     32 64 128 256 512 and using the deploy docker with anchors    32 64 128 256 512 in the configuration i get the same result (pytorch model and the torch scipt )

when transferring the pytorch to torch script with modified anchors size and ratio i get a different results, not 1% change but new result example training with      8 16 32 64 128 and using the deploy docker with anchors         8 16 32 64 128  in the configuration i get different results.
expected to get the same result when changing the anchors size, noted that i changed it in the cfg.yaml given to export model

## Environment:
using the docker image in ```https://github.com/facebookresearch/detectron2/tree/master/docker```
Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

**Comment by ppwwyyxx** [comment]
I found it difficult to understand what is unexpected. Do you mean that:
1. you train a model with modified anchor size (8 16 32 64 128)
2. you run inference using this model in python without export
3. you export this model using `export_model.py` with modified config that contains modified anchor size
4. you run inference using the exported model from step (3)
5. results of step (2) and step (4) are very different

If the above is correct, then step(5) is an unexpecetd behavior. Please provide necessary information to reproduce it, i.e. the model file from step(1) and the config/code/command in step(2-4).
