### ISSUE TITLE
how to choose the gpu id to train my data?

### ISSUE THREAD

**Issue by Dhgalaw** [facebookresearch/detectron2#3677]
## how to choose the gpu id to train data:

I have tried both ```CUDA_VISIBLE_DEVICES=3 python train.py --num-gpus 1``` and ```os.environ["CUDA_VISIBLE_DEVICES"] = "3"```,but them didn't work at all. My program still use gpu 0 to train my data. 

It said ```RuntimeError: CUDA out of memory. Tried to allocate 850.00 MiB (GPU 0; 10.76 GiB total capacity; 9.00 GiB already allocated; 301.12 MiB free; 9.47 GiB reserved in total by PyTorch)``` because GPU 0 is using by others.But GPU 3 is available.

who can help me to choose other gpus? thanks a lot.

**Comment by Dhgalaw** [comment]
the environment is Detectron2 v0.5, python 3.6, pytorch 1.8

**Comment by anahithambardzumyan** [comment]
I have 3 gpu's , so I used  this line to set the training on the third gpu cfg.MODEL.DEVICE = "cuda:2"

**Comment by ppwwyyxx** [comment]
> It said RuntimeError: CUDA out of memory. Tried to allocate 850.00 MiB (GPU 0; 10.76 GiB total capacity; 9.00 GiB already allocated; 301.12 MiB free; 9.47 GiB reserved in total by PyTorch) 

The message does not support the claim that "My program still use gpu 0 to train my data.". The first GPU that the program uses is always named "GPU 0" regardless of which GPU it is on the physical machine.
