### ISSUE TITLE
Keypoint detection training advice

### ISSUE THREAD

**Issue by abhisuri97** [facebookresearch/detectron2#368]
## ❓ Questions and Help

Hello, I am training detectron2 to recognize keypoints and masks on spinal segmentations. I was able to successfully adapt the network to create masks; however, I am unsure if I am using the "right" (I understand this term can be vague) training parameters for training the final layer on keypoint rcnn. I had a couple of questions as follows:

1. What are the acceptable values for the visibility parameter? I know the minimum is 0, but what is the particular meaning of a higher value? Is there an upper bound on said value?
2. For training the network, is the recommended value of 300 iterations still valid, or does keypoint RCNN, in general, require more iterations to achieve a "good" result (if this question is too vague to answer, I understand).

**Comment by ppwwyyxx** [comment]
The definition of visibility is at http://cocodataset.org/#format-data

300 is a very small number of iterations.

**Comment by abhisuri97** [comment]
Thank you!

**Comment by darwinharianto** [comment]
Hi, can you tell me how detectron2 behave on 1 and 2 visibility?
For visibility 0, i assume it is not calculated for loss and won't update weight files.

For 1 and 2, do they behave the same? calculate loss and have effect on weights update

**Comment by KMint1819** [comment]
visibility flag defined as v=0: not labeled, v=1: labeled but not visible, and v=2: labeled and visible.
Refer [to this link](https://cocodataset.org/#format-data)

**Comment by darwinharianto** [comment]
Hi, thanks for the clarification. I just want to know how detectron2 treats flag 1 and 2.  I believe 0 means it does not calculated when calculating for loss. For 1 and 2, Does it behave differently on calculating loss and weight updates?
