### ISSUE TITLE
Ctrl+C cannot stop demo.py after a visualization

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/detectron2#369]
I use demo.py to visualize a result and after that I try to stop the process py ctrl+c, however it could not stop. Ctrl+d also meets the same problem. So how to stop it?

**Comment by ppwwyyxx** [comment]
When the opencv visualization window is active, ctrl-c does not stop the process. You'll also need to close the window (e.g. by pressing any key on the window). This is specific to opencv and not related to detectron2.

**Comment by SkeletonOne** [comment]
@ppwwyyxx I simply closed the opencv window and it cause stuck. But when I do as what you said, which is pressing anykey on the window the problem disappears. Thanks.
