### ISSUE TITLE
Issue detecting dense object

### ISSUE THREAD

**Issue by ladanisavan** [facebookresearch/detectron2#3696]
Hi there

I am using newly added regnetx_4gf_dds_FPN from "new_baselines" to detect words from A4 size documents. The issue that I am facing is after training on a good amount of data __(300k samples)__ model is not able to detect all the words from the document image. I have tried multiple things but nothing worked. Any help would be appreciated.  

Architecture/model used (without any change in configuration)
__regnetx_4gf_dds_FPN__

Things I have tried

- increasing limit of __model.roi_heads.box_predictor.test_topk_per_image__ from 100 to 2000 (which would be a sufficient IMO)
- increasing the __model.proposal_generator.pre_nms_topk__ to (2000, 8000)
- increasing the __model.proposal_generator.post_nms_topk__ to (1000, 8000)
- model input image size is changed to __1024 x 1024__
- trained for __50 epochs__

Here is a sample prediction 

![image](https://user-images.githubusercontent.com/14819841/141817906-d7b97440-00ef-4a54-b06d-db06b3935aed.png)

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect a model to converge / work better, we do not help with such issues, unless a model fails to reproduce the results in detectron2 model zoo, or proves existence of bugs.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
