### ISSUE TITLE
Model.Weights for Pascal VOC

### ISSUE THREAD

**Issue by jas-nat** [facebookresearch/detectron2#370]
Hello I am still new to use Detectron. I am trying to implement KITTI datasets for object detection using VOC baselines. From these commands: 

cfg = get_cfg()
cfg.merge_from_file("./configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
**cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"**
predictor = DefaultPredictor(cfg)
outputs = predictor(im)

How can I know which model.weights that is suitable for particular model, in this case Pascal VOC? In the documentation it says I should refer to the ModelCatalog but I cannot find any. Please give any examples if you don't mind.

**Comment by ppwwyyxx** [comment]
All models we provided are in the model zoo https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by jas-nat** [comment]
I understand all models are provided there. However, I do not understand how to include the model in the Model.Weights. Which does directory of "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"correspond to?

**Comment by ppwwyyxx** [comment]
It corresponds to the model "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x" available in the model zoo.

**Comment by jas-nat** [comment]
In this case if I want to use Pascal VOC baselines, is it the correct model.weight I should input:

**cfg.MODEL.WEIGHTS = "detectron2://PascalVOC-Detection/faster_rcnn_R_50_C4/142202221/model_final_b1acc2.pkl"**

Please correct me if I am wrong

**Comment by ppwwyyxx** [comment]
If you train with this config using `DefaultTrainer`, it will then load this model to start with.

**Comment by icantdothisbro** [comment]
@ppwwyyxx if I want to add weights from a .pth file , how should i do that?
Should I just write cfg.MODEL.WEIGHTS = "path_to_file"
TIA
