### ISSUE TITLE
python demo/demo.py   ocurr   OSError: cannot identify image file <_io.BufferedReader name='input.jpg'>

### ISSUE THREAD

**Issue by huangpan2507** [facebookresearch/detectron2#371]
## ❓ Questions and Help

General questions about detectron2.

NOTE:
when I try to run :
>python3 demo/demo.py      --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml     --input input.jpg --output outputs/     --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl

it ocurr that 
>OSError: cannot identify image file <_io.BufferedReader name='input.jpg'>

I have put an pic  named  "input.jpg"  in the path   
>/home/huangpan/git_download/detectron2/input.jpg  

enter the path 
>/home/huangpan/git_download/detectron2/

 I run 
>python3 demo/demo.py

under the path  /home/huangpan/git_download/detectron2/     there are

>build        datasets          detectron2              dev             docs                  input.jpg      LICENSE         projects      setup.cfg                      tests
configs      demo         detectron2.egg-info     Dockerfile      GETTING_STARTED.md       INSTALL.md  MODEL_ZOO.md  README.md  setup.py                    tools

so. who can explain these commands below ?
>python3 demo/demo.py      --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml     --input input.jpg --output outputs/     --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl

and 
>--config-file  --input input.jpg --output outputs/ 

what does  those commands  mean ?
any suggestion is appreciated

**Comment by mvmnt** [comment]
Hi @huangpan2507 
Just a disclaimer, I'm quite a novice in this field and I have no idea if my suggestion might be of any use, but I'll try to explain based on my limited understanding:

>so. who can explain these commands below ?

>python3 demo/demo.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --input input.jpg --output outputs/ --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl

this command uses the configuration set out in the yaml file to outline how the model should interact with the specified input, whether it be an image, or video. the MODEL.WEIGHTS parameter retrieves the file from a cdn to apply the desired effect.
This is just my understanding however, it might not be correct, but if it isn't, I'd appreciate any clarity on the matter.

Another thing I've noticed, is that you are using python3. By chance, is that python version 3.5? If it is, you might have better luck running the demo using python 3.6 and above.

Really hope this helps to make your journey smoother.

**Comment by huangpan2507** [comment]
> 
> 
> Hi @huangpan2507
> Just a disclaimer, I'm quite a novice in this field and I have no idea if my suggestion might be of any use, but I'll try to explain based on my limited understanding:
> 
> > so. who can explain these commands below ?
> 
> > python3 demo/demo.py --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml --input input.jpg --output outputs/ --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl
> 
> this command uses the configuration set out in the yaml file to outline how the model should interact with the specified input, whether it be an image, or video. the MODEL.WEIGHTS parameter retrieves the file from a cdn to apply the desired effect.
> This is just my understanding however, it might not be correct, but if it isn't, I'd appreciate any clarity on the matter.
> 
> Another thing I've noticed, is that you are using python3. By chance, is that python version 3.5? If it is, you might have better luck running the demo using python 3.6 and above.
> 
> Really hope this helps to make your journey smoother.

ok, thanks a lot .I'm reading your reply right now.

**Comment by ppwwyyxx** [comment]
That means the Pillow library cannot read your image. Please check your images or report bugs to Pillow instead.
