### ISSUE TITLE
Mask R-CNN has different speeds in the py and yaml configuration formats

### ISSUE THREAD

**Issue by hhaAndroid** [facebookresearch/detectron2#3726]
## Instructions To Reproduce the Issue:

I used 8 cards to train the Mask R-CNN model, but found that the training speed of the py format is slower than that of the yaml format. The `data_time`  is close, but `time` difference is large Why is this？ 

![image](https://user-images.githubusercontent.com/17425982/143520758-7c18c989-c03d-47d2-9d89-7053d886fb02.png)

The left is yaml, the right is py. The config file is `configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml` and `configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.py`. 

We did not modify any code.

**Comment by RamanHacks** [comment]
I did notice the same in with mask-rcnn template. The lazy-config is far slower than the normal yaml configs! 

Here is the Environment details: 
![image](https://user-images.githubusercontent.com/17014540/143624002-a0f15032-1ed5-4b53-b7af-7d582b4ff11a.png)

**Comment by alekseynp** [comment]
Asking if either of you identified the cause?
I'm in the process of updating my detectron2 version and I'm finding version 0.5 is slower than what I was on.
