### ISSUE TITLE
How can I make the same reult of trainer.model and predictor.model?

### ISSUE THREAD

**Issue by Nurungyi** [facebookresearch/detectron2#3729]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue:

1. Full runnable code or full changes you made:
```
cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("my_dataset_train",)
cfg.DATASETS.TEST = ()
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")  # Let training initialize from model zoo


cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 5000

cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = number_of_class

cfg.OUTPUT_DIR = 'gdrive/My Drive/save_model/faster_rcnn/' # output will be saved here
```

```
cfg.OUTPUT_DIR = 'gdrive/My Drive/save_model/faster_rcnn/' # weight will be loaded
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.DATASETS.TEST = ("my_dataset_test",)

cfg.MODEL.ROI_HEADS.NUM_CLASSES = number_of_class
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model

predictor = DefaultPredictor(cfg)
```

```
evaluator = COCOEvaluator("my_dataset_test")
val_loader = build_detection_test_loader(cfg, "my_dataset_test")
# print(inference_on_dataset(trainer.model, val_loader, evaluator))
print(inference_on_dataset(predictor.model, val_loader, evaluator))
```

## Expected behavior:

While trainer.model can be done after trainer should be defined and finished, predictor.model can be executed with pre trained weight without execution of trainer. So, in most of real applications, "predictor.model" may be more practical.
However, currently, the performance is decreased more in "predictor.model" when compared to "trainer.model".

I did not change the configurations of Detectron2. Why two are different? Trinaer.model is higher than predictor.model.

Could you please kindly teach me?

## Environment:

Paste the output of the following command:
```
colab environment
```

If your issue looks like an installation issue / environment issue,
please first check common issues in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
Runnable code or full logs as requested by the issue template are not provided, so we cannot investigate.

From the code pieces, it appears that predictor has config `cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7` but trainer does not. If that is true, it could cause performance difference.

**Comment by Nurungyi** [comment]
In test, I initialize the config through 'get_cfg = cfg()'. And, as you said, if 'cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST' is not defined in a test process exactly same as a traning process, it showed different result. After making it same, it works properly, thank you for giving very informative advice.

Thank you!!
