### ISSUE TITLE
Output average RGB color of each segmented class

### ISSUE THREAD

**Issue by Wilann** [facebookresearch/detectron2#3740]
## 🚀 Feature
Output the average RGB color of each segmented class

Appologies if this is already implemented, but I don't see anything about RGB colors in the [Model Output Format docs](https://detectron2.readthedocs.io/en/latest/tutorials/models.html#model-output-format). Otherwise, is there any other way I can achieve this? 

## Motivation & Examples

This would be useful when segmenting people in sports application to keep track of their teams.

**Comment by MiXaiLL76** [comment]
In the model outputs, the segmentation instance has a field
“Pred_masks”: a Tensor of shape (N, H, W), masks for each detected instance.

Let's imagine that the model detects red circles.
Here is the picture that was submitted to the predictor
![изображение](https://user-images.githubusercontent.com/31501945/145557717-3a4d1360-06a5-459f-8dae-4e0ccfa35d36.png)

For each red object there is a mask H, W that looks like this:
![изображение](https://user-images.githubusercontent.com/31501945/145557773-4800f427-9121-4dee-8596-7a9ba8dd0907.png)

As a result, using functions from opencv, you can calculate the average color value.
```
means, stds = cv2.meanStdDev(orig_image, mask=model_output_mask)
print(f"{means=}")
```

means=array([[201.16522183],
       [ 28.34778174],
       [  0.        ]])



Code to repeat:
```
import matplotlib.pyplot as plt
import numpy as np
import cv2

h,w = 100, 100

orig_image = np.zeros((h,w,3), dtype=np.uint8)

center = 45, 45
radius = 25
cv2.circle(orig_image,center,radius,(255, 0, 0),-1)

center = 70, 70
radius = 15
cv2.circle(orig_image,center,radius,(0, 255, 0),-1)

center = 25, 25
radius = 10
cv2.circle(orig_image,center,radius,(0, 0, 255),-1)

plt.title('input orig image')
plt.imshow(orig_image)
plt.show()


model_output_mask = np.zeros((h,w), dtype=np.uint8)
center = 50, 50
radius = 25
cv2.circle(model_output_mask,center,radius,255,-1)

plt.title('model_output_mask')
plt.imshow(mask)
plt.show()

means, stds = cv2.meanStdDev(orig_image, mask=model_output_mask)
print(f"{means=}")
```

**Comment by ppwwyyxx** [comment]
Answered above. This can be done by users given the outputs.
