### ISSUE TITLE
Unable to export to TorchScript and run on Windows CPU only

### ISSUE THREAD

**Issue by michael-kutschera** [facebookresearch/detectron2#3744]
## Instructions To Reproduce the Issue:
Used code from [https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py](url) to export sample project to a traced torchscript **CPU-only** model:

1. Full runnable code or full changes you made:
2. What exact command you run:

`./export_model.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --output ./output --export-method tracing --format torchscript \
    MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \
    MODEL.DEVICE cpu`
    
(changed MODEL.DEVICE from cuda to cpu)

## Environment Export:
linux, python 3.7
cudatoolkit  10.2.89
detectron2   0.6+cu102
opencv       3.4.2
torch        1.10.0
torchaudio   0.7.0
torchvision  0.11.1

## Environment Deployment:
windows, VC ++ 16.11.7
libtorch-win-shared-with-deps-1.10.0+cpu (release+debug) installed

## Behavior:
directly throws memory exeption on loading traced model "model.ts" right away at the start of [https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/torchscript_mask_rcnn.cpp](url):
`[line140]:    auto module = torch::jit::load(argv[1]);`

Has anyone tried to export a RCNN traced model to torchscript on Windows CPU-only?
(no CUDA hardware avaiable on target device...)
Any ideas?
(screened all FAQs, readme.md, available posts -> nothig found)...

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues mentions we do not provide support for windows. The code should run fine inside the official (linux) docker we provided.
