### ISSUE TITLE
COCO and boxmode support

### ISSUE THREAD

**Issue by jloveric** [facebookresearch/detectron2#3749]
Looking at the documentation for mscoco, it states that
```
bbox_mode (int, required): the format of bbox. It must be a member of structures.BoxMode. Currently supports: BoxMode.XYXY_ABS, BoxMode.XYWH_ABS.
```
Is this still the case?  Or does it also support BoxMode.XYXY_REL (or are there simple ways to make boxes work that are using relative coordinates [0,1]?

**Comment by ppwwyyxx** [comment]
> Looking at the documentation for mscoco

This is not the documentation for mscoco. https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#standard-dataset-dicts this is the documentation for "standard dataset dicts" which is a format we defined that users' custom dataset needs to follow. 

According to the doc it seems `XYXY_REL` is not supported.
