### ISSUE TITLE
Are 'x_shifts' and 'y_shifts' in '_create_grid_offsets' correct?

### ISSUE THREAD

**Issue by jalabort** [facebookresearch/detectron2#378]
Hi, first of all, thanks for making this excellent project open source.

My colleague @aoikonomop and I have been recently looking at the matching between `gt_boxes` and `anchors` for the `RetinaNet` model. In doing so, we have observed that `grid-anchors` seem to be centered at the position [(0, 0)](https://github.com/facebookresearch/detectron2/blob/fbd447d4de532311b8a93495e118785d9e904b95/detectron2/modeling/anchor_generator.py#L43-L46) relative to the `cells` in the response maps where the final predictions are made (`p3`, `p4`, ...). We were expecting these `grid-anchors` to be centered at the position `(stride/2, stride/2)` relative to the `cells`. Because `cell-anchors` themselves are centered at [(0, 0)](https://github.com/facebookresearch/detectron2/blob/fbd447d4de532311b8a93495e118785d9e904b95/detectron2/modeling/anchor_generator.py#L166) it seems to us that all `grid-anchors` are unnecessarily shifted toward the upper left of the cells. This, in turn, seems to produce some unnexpected (nonoptimal?) matchings for some simple cases, see this [gist](https://gist.github.com/jalabort/2b181e36d5af29fce4e49f3f79d405b1) for an example. Is this behaviour intended?

We have managed to get the matching results we were expecting by simply changing the `0`s in [here](https://github.com/facebookresearch/detectron2/blob/fbd447d4de532311b8a93495e118785d9e904b95/detectron2/modeling/anchor_generator.py#L43-L46) for `stride/2` which seems to make sense given our prior intutition.

**Comment by ppwwyyxx** [comment]
This seems like an unintended issue. 

@rbgirshick When we switch from the original matlab anchor generator to the new floating-point one, the anchors are shifted by stride/2. (The original anchors were centered at roughly stride/2 but now they are centered at 0). The outcome is that the final grid of anchors are not symmetric on the image.

This probably does not affect overall performance but maybe has some effect for objects at boundaries of images.

**Comment by rbgirshick** [comment]
I agree that centering on stride/2 is more natural and this appears to be an accident. Unfortunately changing it at this point in time is difficult as it would invalidate the model zoo. I also expect that the impact on standard benchmark datasets is likely near 0. If a substantial impact, either on a benchmark or common/important use case, can be demonstrated then we can think about remedies.

**Comment by ArutyunovG** [comment]
What about #488 to preserve model zoo and add option of training new models with expected anchor locations?
