### ISSUE TITLE
yaml file for regnet? 

### ISSUE THREAD

**Issue by Suzan009** [facebookresearch/detectron2#3805]
we can do 

```
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml") 
```

from this how to use 

![image](https://user-images.githubusercontent.com/45315076/146612759-8a88226b-d8d4-4a9f-b35c-25688418f1d2.png)

or 

https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-InstanceSegmentation/mask_rcnn_regnetx_4gf_dds_fpn_1x.py

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md#how-to-read-the-tables has explained how to use the model zoo.
