### ISSUE TITLE
Use a non-root docker user.

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#381]
## 🚀 Feature
Use a non-root docker user for security reasons (see https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

## Motivation
Running everything in the docker container as root imposes a security risk. Even without possible security concerns, it can be tedious that everything that is written to the disk by the container belongs to root and can only be deleted by a root user (e.g. with sudo).

## Pitch
Fix the Dockerfile, so that the container can be run with `--user=$UID` or have a user with known UID and limited rights inside the docker container.

At the moment, doing the former resutls in errors like the following:
> FileNotFoundError: [Errno 2] No such file or directory: '/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl.lock'

**Comment by ppwwyyxx** [comment]
Sounds good. The error is probably because `$HOME` is not correctly set because the pretrained models will be downloaded to somewhere under $FVCORE_CACHE if exists, or $HOME

**Comment by ppwwyyxx** [comment]
closed by #385 . Thanks!
