### ISSUE TITLE
How to train rotating bounding box

### ISSUE THREAD

**Issue by weiyidawang** [facebookresearch/detectron2#3813]
## 📚 Documentation Issue

I don't know the steps of training the rotating bounding box.
Can anyone help me? Thank you very much.

**Comment by zhanghang1989** [comment]
You may try using RandomRotation transformation 
https://github.com/facebookresearch/detectron2/blob/6545979631eb96144a415609c48f9a32a8aeb3e2/detectron2/data/transforms/augmentation_impl.py#L248

**Comment by ppwwyyxx** [comment]
Duplicated of https://github.com/facebookresearch/detectron2/issues/21
