### ISSUE TITLE
Save the planet by not downloading pretrained models over and over again, when using docker.

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#382]
## 🚀 Feature
It would be great to find a way that the use of docker does not result in models being downloaded over and over again.

## Motivation
Models are quite large. Their repetitive download wastes precious resources, such as energy, time, bandwidth and money.

## Pitch
There should be a solution to avoid the repetitive model download, when using docker.

Any ideas?

**Comment by bendidi** [comment]
just mount the FVCORE_CACHE volume into your container at run time

**Comment by maxfrei750** [comment]
Thanks for the advice. I already thought about that and it is definitively the easiest solution. However, I was not sure whether it is a wise idea to reduce the isolation of the container and the host. On the other hand, the only other solution that I see would be to include the models into the docker image, which would severely bloat it.
