### ISSUE TITLE
Environment files for COCO Instance Segmentation new baselines are missing

### ISSUE THREAD

**Issue by aegonwolf** [facebookresearch/detectron2#3839]
## 📚 Documentation Issue

This issue category is for problems about existing documentation, not for asking how-to questions.

* Provide a link to an existing documentation/comment/tutorial:
* https://github.com/facebookresearch/detectron2/tree/main/configs/new_baselines

* How should the above documentation/comment/tutorial improve:
* Add the links to the .yaml files like with all other models in the model zoo

**Comment by ppwwyyxx** [comment]
We don't know what are "Environment files". Please explain what are missing.
