### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by fcakyon** [facebookresearch/detectron2#3844]
I want to install cpu version of detectron via pip.

In installation documentation it says:

```
python -m pip install detectron2 -f \ https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html
```

When I run this line in Python 3.8 Ubuntu 18.04 I get this error:

```
Looking in links:  https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html
WARNING: Location ' https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html' is ignored: it is either a non-existing path or lacks a specific scheme.
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
```

**Comment by ppwwyyxx** [comment]
`\ ` is a line break character. Please remove it if the whole command is in the same line.

If you still need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
