### ISSUE TITLE
Some questions about Faster-RCNN

### ISSUE THREAD

**Issue by qdd1234** [facebookresearch/detectron2#3852]
Hi, I want to ask a question about the implementation of Faster-RCNN in detectron2. Whether the faster-rcnn to assign foreground and background labels according to the IOU? or according to scores? Where can I find the assignment code?

**Comment by zhanghang1989** [comment]
The gt labels are matched with anchors based on IoU and a portion of positive and negative samples are sampled randomly. See details at

https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/proposal_generator/rpn.py#L339-L352
