### ISSUE TITLE
Res5ROIHeadsExtraNorm

### ISSUE THREAD

**Issue by Kevinz-code** [facebookresearch/detectron2#3855]
Hi, first thanks to detectron2 repo.

My question is, when I run the voc0712 detection task using configs provided in MoCo:
https://github.com/facebookresearch/moco/blob/main/detection/configs/Base-RCNN-C4-BN.yaml

Specifically,
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    NORM: "SyncBN"
TEST:
  PRECISE_BN:
    ENABLED: True
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02

Then I'm facing an error said:
KeyError: "No object named 'Res5ROIHeadsExtraNorm' found in 'ROI_HEADS' registry!"

## Environment
pytorch 1.10.1

I was wondering if I have done something wrong?

Many thanks!

**Comment by nikky4D** [comment]
Where you able to fix this error? I'm facing something similar with my model
