### ISSUE TITLE
Tutorial Translation

### ISSUE THREAD

**Issue by eric-yoo** [facebookresearch/detectron2#3863]
## 📚 Documentation Issue

* How should the above documentation/comment/tutorial improve:

Creating an issue to inquire authors (@ppwwyyxx) of detectron2 if it would be okay to:
  - translate the official tutorials into Korean and make it accessible publicly (with appropriate license)
  - possibly include the translated project as part of [PyTorch Korea organization](https://github.com/PyTorchKorea)

**Comment by zhanghang1989** [comment]
Thanks for interested in contributing the community with Korean translations! It would be a good addition to the toolkit.
@pwwyyxx do you think this is a good idea? Any concerns?

**Comment by eric-yoo** [comment]
@zhanghang1989 @ppwwyyxx Hi, could you inform me of any updates?

**Comment by ppwwyyxx** [comment]
Feel free to translate the documentation. Thanks for doing this!
