### ISSUE TITLE
How does the Registry work?

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#388]
## ❓ Questions and Help
```
To register an object:
 .. code-block:: python

@BACKBONE_REGISTRY.register()
class MyBackbone():
```

I'm not familiar with the python usage of the above implementation.
I.e.,  put  `@BACKBONE_REGISTRY.register()`  above the class definition and the corresponding backbone will be registered in `BACKBONE_REGISTRY`.

Can anyone give me a link that introduces this usage method of python?
Thanks very much.
I hope I've expressed my confusion clearly.

**Comment by ppwwyyxx** [comment]
https://wiki.python.org/moin/PythonDecorators
