### ISSUE TITLE
metrics.json should contain ETA (time remaining)

### ISSUE THREAD

**Issue by yanicklandry** [facebookresearch/detectron2#389]
## 🚀 Feature
There are multiple logger implemented, two of them are the console output and a file (metrics.json). An ETA (Estimated Time of Arrival, or time remaining) is being generated for the console output but not for the metrics.json.

## Motivation
You could want to monitor training to display in a GUI by looking at metrics.json.

## Pitch

By running the exact same training code, the ETA should be both displayed and logged to metrics.json.

**Comment by ppwwyyxx** [comment]
```diff
--- a/detectron2/utils/events.py
+++ b/detectron2/utils/events.py
@@ -156,6 +156,7 @@
             data_time = storage.history("data_time").avg(20)
             time = storage.history("time").global_avg()
             eta_seconds = storage.history("time").median(1000) * (self._max_iter - iteration)
+            storage.put_scalar("eta_seconds", eta_seconds, smoothing_hint=False)
             eta_string = str(datetime.timedelta(seconds=int(eta_seconds)))
         except KeyError:  # they may not exist in the first few iterations (due to warmup)
             pass
```

This line is sufficient to implement this feature. Could you send a PR with this?

**Comment by yanicklandry** [comment]
@ppwwyyxx : Sure, I just added it on my pull request : https://github.com/facebookresearch/detectron2/pull/390/files
