### ISSUE TITLE
NameError: name 'quantization' is not defined

### ISSUE THREAD

**Issue by fardinadii** [facebookresearch/detectron2#3890]
## Instructions To Reproduce the 🐛 Bug:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-a688561fe05f> in <module>

--> 372     trainer.resume_or_load(resume=False)
    373     trainer.train()

/workspace/detectron2/detectron2/detectron2/engine/defaults.py in resume_or_load(self, resume)
    410             resume (bool): whether to do resume or not
    411         """
--> 412         self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
    413         if resume and self.checkpointer.has_checkpoint():
    414             # The checkpoint stores the training iteration that just finished, thus we start

/opt/conda/lib/python3.6/site-packages/fvcore/common/checkpoint.py in resume_or_load(self, path, resume)
    225             return self.load(path)
    226         else:
--> 227             return self.load(path, checkpointables=[])
    228 
    229     def tag_last_checkpoint(self, last_filename_basename: str) -> None:

/workspace/detectron2/detectron2/detectron2/checkpoint/detection_checkpoint.py in load(self, path, *args, **kwargs)
     50             if not has_file:
     51                 path = None  # don't load if not readable
---> 52         ret = super().load(path, *args, **kwargs)
     53 
     54         if need_sync:

/opt/conda/lib/python3.6/site-packages/fvcore/common/checkpoint.py in load(self, path, checkpointables)
    154 
    155         checkpoint = self._load_file(path)
--> 156         incompatible = self._load_model(checkpoint)
    157         if (
    158             incompatible is not None

/workspace/detectron2/detectron2/detectron2/checkpoint/detection_checkpoint.py in _load_model(self, checkpoint)
    101             )
    102         # for non-caffe2 models, use standard ways to load it
--> 103         incompatible = super()._load_model(checkpoint)
    104 
    105         model_buffers = dict(self.model.named_buffers(recurse=False))

/opt/conda/lib/python3.6/site-packages/fvcore/common/checkpoint.py in _load_model(self, checkpoint)
    295                     has_observer_base_classes = (
    296                         TORCH_VERSION >= (1, 8)
--> 297                         and hasattr(quantization, "ObserverBase")
    298                         and hasattr(quantization, "FakeQuantizeBase")
    299                     )

NameError: name 'quantization' is not defined

## Expected behavior:

NameError: name 'quantization' is not defined

## Environment:

sys.platform linux
Python 3.6.10 |Anaconda, Inc.|
numpy 1.19.2
detectron2 0.6 @/workspace/detectron2/detectron2/detectron2
Compiler GCC 7.5
CUDA compiler CUDA 11.1
detectron2 arch flags 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
DETECTRON2_ENV_MODULE
PyTorch 1.8.0a0+17f8c32 @/opt/conda/lib/python3.6/site-packages/torch
PyTorch debug build True
GPU available Yes
GPU 0 GeForce RTX 3090 (arch=8.6)
Driver version 455.23.04
CUDA_HOME /usr/local/cuda
TORCH_CUDA_ARCH_LIST 5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX
Pillow 8.4.0
torchvision 0.8.0a0 @/opt/conda/lib/python3.6/site-packages/torchvision
torchvision arch flags 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
fvcore 0.1.5.post20211023
iopath 0.1.9
cv2 3.4.1

**Comment by ppwwyyxx** [comment]
Your pytorch version is older than what we minimally support and causing fvcore to fail at a version check. Please use at least the official 1.8 release.

**Comment by fardinadii** [comment]
> Your pytorch version is older than what we minimally support and causing fvcore to fail at a version check. Please use at least the official 1.8 release.

Thanks for the reply, my Pytorch version is 1.8 and I use detectron2 version 4. This error occurs when my dataset has one class but this error does not happen when I use a multi-class dataset.

**Comment by ppwwyyxx** [comment]
> my Pytorch version is 1.8 

No, your pytorch version is `1.8.0a0+17f8c32`. "a0" means "alpha0" so this is older than 1.8.

```
╭─ Work/projects/detectron2
╰─$ from packaging import version

╭─ Work/projects/detectron2
╰─$ version.parse("1.8.0a0+17f8c32") < version.parse("1.8")
Out[3]: True
```

**Comment by fardinadii** [comment]
> > my Pytorch version is 1.8
> 
> No, your pytorch version is `1.8.0a0+17f8c32`. "a0" means "alpha0" so this is older than 1.8.
> 
> ```
> ╭─ Work/projects/detectron2
> ╰─$ from packaging import version
> 
> ╭─ Work/projects/detectron2
> ╰─$ version.parse("1.8.0a0+17f8c32") < version.parse("1.8")
> Out[3]: True
> ```


I use this container:

http://nvcr.io/nvidia/pytorch:20.11-py3

And all versions have the Alpha series. Even version 1.9 has the Alpha series.
Thank you for guiding me on which version to use.
