### ISSUE TITLE
Lvis model produce inconsistent mAP

### ISSUE THREAD

**Issue by joeythegod** [facebookresearch/detectron2#39]
Hi, I downloaded the model in the model zoo and try to test the validation data by using:
python tools/train_net.py --config-file configs/LVIS-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_1x.yaml --eval-only --num-gpus 8 MODEL.WEIGHTS checkpoints/model_final_016c14.pkl
But the mAP is only 0.023, I have checked the path of validation folder and validation json and I didn't do any change with the config, how can I reproduce the result of 0.27X?
Thanks.

**Comment by ppwwyyxx** [comment]
Thanks for catching this. We released a wrong model for this config.

**Comment by ppwwyyxx** [comment]
The models have been updated.
