### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by ccssmania** [facebookresearch/detectron2#393]
## ❓ Hello, how can I get the confusion matrix.

I have my own dataset in coco format and I get the inferences and evaluations using the trained model, but I need the confusion matrix.

**Comment by ppwwyyxx** [comment]
I don't know if there is a definition of confusion matrix for object detection. But since you can run inference with the trained model, you can compute that yourself if you have such a definition.

**Comment by morganOliveira2018** [comment]
@ccssmania Were you able to implement the confusion matrix?
