### ISSUE TITLE
Installing Detetron2 on GPU:  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by jaiswati** [facebookresearch/detectron2#3931]
Hello,

Need help with following  (updated for Command and error msg)

**Commands**
installed these requirement
 !pip install git+https://github.com/facebookresearch/fvcore
 !pip install cython
 !pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

after that
!python -m  pip install  'git+https://github.com/facebookresearch/detectron2.git' 

!export PATH=/usr/local/cuda/bin:$PATH
#CUDA_HOME='/usr/local/cuda'
!export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

**Error-MSG**
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-4uy_32v8
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-4uy_32v8
    ERROR: Command errored out with exit status 1:
     command: /anaconda/envs/azureml_py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4uy_32v8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4uy_32v8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-plpogdv4
         cwd: /tmp/pip-req-build-4uy_32v8/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4uy_32v8/setup.py", line 14, in <module>
        assert torch_ver >= [1, 8], "Requires PyTorch >= 1.8"
    AssertionError: Requires PyTorch >= 1.8
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jaiswati** [comment]
Hello 

Pls find the GPU summary as below and torch version is 1.9
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000001:00:00.0 Off |                    0 |
| N/A   46C    P0    55W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000002:00:00.0 Off |                    0 |
| N/A   37C    P0    73W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000003:00:00.0 Off |                  Off |
| N/A   41C    P0    58W / 149W |      0MiB / 12206MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000004:00:00.0 Off |                  Off |
| N/A   34C    P0    71W / 149W |      0MiB / 12206MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by ppwwyyxx** [comment]
Please provide environment information following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
