### ISSUE TITLE
Accelerate setup.py

### ISSUE THREAD

**Issue by Hafplo** [facebookresearch/detectron2#394]
## 🚀 Feature

Reduce time required to install with setup.py
Bonus 1: remove the requirement to "import torch"
Bonus 2: add progress / logs during installation (might be unsupported by Python's setuptools package) 

## Motivation

Installing the detectron2 package with the given setup.py (i.e. through the supplied Dockerfile), takes a lot of time.
Also it is unclear if it is stuck or progressing.

## Pitch

Go over what's taking time during installation (copying models? running tests? low quality code?) and improve it to reduce the time required to install (and deploy / build / docker / scale / etc.)

**Comment by ppwwyyxx** [comment]
The compilation of ops is taking time. We'd like to improve it but likely cannot do much about it.
Python's setuptools does not allow progress.

If you have more concrete request or idea on how to improve installation time we can start from there.
