### ISSUE TITLE
detectron2 for very small objects instance segmentation

### ISSUE THREAD

**Issue by Otabek0626** [facebookresearch/detectron2#3949]
# detectron2 for very small objects instance segmentation

Hello
I have trained detectron2 for very small objects instance segmentation and I have faced a very weird situation. I increased the number of objects per image from 100 to 1000 and Google Colab GPU became full and it crashed.

### cfg.TEST.DETECTIONS_PER_IMAGE = 1000

Can you please help to tackle the crash?

thanks in advance

**Comment by zhanghang1989** [comment]
I guess it is due to out of memory
