### ISSUE TITLE
Caffe2_tracer export

### ISSUE THREAD

**Issue by FrancescoMandru** [facebookresearch/detectron2#3963]
I'm trying to export a Detectron2 model with Caffe2_Tracer which should export also the model in ONNX format as you describe [here](https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html). I use your [export_model.py](https://github.com/facebookresearch/detectron2/blob/main/detectron2/export/c10.py) with the following command:

`python export_model.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./output --export-method caffe2_tracing --format onnx MODEL.WEIGHTS C:\prj\AI\detectron\jupyters\output\model_final.pth  MODEL.DEVICE cpu`

The only thing that I have done differenrly is to hard coding the input image file path in the export_model.py in the `--sample-image` argument. However when I run the above command I get the following:

```
  File "c:\prj\ai\detectron\detectron2\detectron2\export\c10.py", line 360, in forward
    assert roi_feat_shuffled.numel() > 0 and rois_idx_restore_int32.numel() > 0, (
AssertionError: Caffe2 export requires tracing with a model checkpoint + input that can produce valid detections. But no detections were obtained with the given checkpoint and input!
```

and I'm not able to fix it. 

I'm not able to attach and share with you the model.pth and a sample image which should be enough to reproduce this issue as I don't use any other custom model or any other particular changes.

My environment is the standard environment of Detectron2 with no upgraded version of any library

**Comment by FrancescoMandru** [comment]
Update, this error seems to be not determistic as running it multiple times gives different results. Sometimes it works sometimes not.

**Comment by ppwwyyxx** [comment]
The error message is pretty self-explanatory:  `it needs a model checkpoint + input that can produce valid detections. But no detections were obtained with the given checkpoint and input!`.
The official example in the repo (before it's removed) always work because it uses a model+input with detections.

Also, caffe2_tracer support was removed from latest detectron2. So we're not going to continue to help on issues about it.

**Comment by FrancescoMandru** [comment]
> The error message is pretty self-explanatory: `it needs a model checkpoint + input that can produce valid detections. But no detections were obtained with the given checkpoint and input!`. 

I'm totally agree with you. However I was confused because this seems to be an hard constraint and I was wondering if it was something that I didn't get. 

> Also, caffe2_tracer support was removed from latest detectron2. So we're not going to continue to help on issues about it.

Which is the support that you provide for deploying detectron2 in c++? Do you have a detailed documentation on how to properly export the weights in order to be loaded on c++? I would really appreciate it

**Comment by qmcreeper** [comment]
Maybe you input images which the model get none result.In my onnx file , the first dim of outputs are the number of object.If the input image is a random noise, maybe you would get the same error.
