### ISSUE TITLE
Change AP metrics threshold

### ISSUE THREAD

**Issue by teddybear0212** [facebookresearch/detectron2#397]
I'm currently using COCOEvaluator for testing. I get AP50 and AP75 fairly easily, and it's really useful for benchmarking.  However, I wonder whether it would be possible for me to change the IOU threshold of the AP metrics? Or get the ROC curve of the model?

**Comment by sshl** [comment]
It seems that these  metrics and thresholds are defined in cocoapi [https://github.com/cocodataset/cocoapi/blob/aca78bcd6b4345d25405a64fdba1120dfa5da1ab/PythonAPI/pycocotools/cocoeval.py#L427](https://github.com/cocodataset/cocoapi/blob/aca78bcd6b4345d25405a64fdba1120dfa5da1ab/PythonAPI/pycocotools/cocoeval.py#L427). You would extend COCOeval class in cocoapi to define your own metrics, and replace COCOeval in COCOEvaluator.
