### ISSUE TITLE
Pytorch1.3?

### ISSUE THREAD

**Issue by LaoYang1994** [facebookresearch/detectron2#4]
The official pytorch version is "1.2". How to install the v1.3-one?

**Comment by ppwwyyxx** [comment]
The latest pytorch version is 1.3: https://github.com/pytorch/pytorch/releases/tag/v1.3.0

**Comment by LaoYang1994** [comment]
@ppwwyyxx Thanks.

**Comment by Angzz** [comment]
@ppwwyyxx pytoch1.1 or pytorch1.2 ok??? thx

**Comment by ppwwyyxx** [comment]
It requires pytorch 1.3

**Comment by MarsTT** [comment]
The pytorch1.3 must CUDA version is 10.0?

**Comment by ppwwyyxx** [comment]
There is no requirement on CUDA 10.0

**Comment by unademo** [comment]
Can I modify some specific codes to make it compatible to previous Pytorch version? (>=1.0)

**Comment by yustaub** [comment]
> Can I modify some specific codes to make it compatible to previous Pytorch version? (>=1.0)

can u run it on pytorch1.0 now?

**Comment by shiyongde** [comment]
k40M is no longer using in pytorch 1.3 . SO  annyone can  run it In pytorch 1.2 ???
