### ISSUE TITLE
I used a custom dataset which on segmentation gave a compressed count->

### ISSUE THREAD

**Issue by hiroto01** [facebookresearch/detectron2#4004]
I used a custom dataset which on segmentation gave a compressed count-> 
[{'size': [256, 256], 'counts': b'0a21`M00e20[M0P50PK0k20UM0j40VK0P30PM00e40[K0U30kL0a40_K0Y30gL0\\40dK0_30aL0W40iK0c30]L0S40mK0Z10fN00000000000020N00000000000000[10eN0P........}]
making use of **pycocotools.mask.encode(np.asarray(png,  order="F"))**
also while visualising my mask(not consisting of poly and bbox..its more like an outline that i want over my image) does not comes over the image...can someone please guide it would be a great help!

**or is it necessary to have polys and bboxes??to work with detectron2?**

_Originally posted by @hiroto01 in https://github.com/facebookresearch/maskrcnn-benchmark/issues/521#issuecomment-1054561517_

**Comment by hiroto01** [comment]
Plzzz Help!!!!!!!!

**Comment by ppwwyyxx** [comment]
Closing as it does not follow the issue template. It seems to be a "how-to" questions which is not in the supported issue categories.
