### ISSUE TITLE
Update black to 22.1.0

### ISSUE THREAD

**Issue by BruegelN** [facebookresearch/detectron2#4005]
## 🚀 Feature

Update black, the code formatter, to version 22.1.0.
I've already did the changes over here: https://github.com/facebookresearch/detectron2/compare/main...BruegelN:update-black

## Motivation & Examples

Version 22.1.0 is the first stable release of black: https://github.com/psf/black/releases/tag/22.1.0

With this version they provide a [stability policy](https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy).

## Note

When including detectron2 into another project which is also using black it's nice to share the same (stable) version of black. The fist non-beta release of black is most likely used by some projects or they're willing to upgrade.

BUT: Updating black will also include a huge diff due to the changed codestyle guidelines: https://github.com/BruegelN/detectron2/commit/844538858bb6867a78e49d128346732d5cc3ea0d
I've already did all the required changes over here: https://github.com/facebookresearch/detectron2/compare/main...BruegelN:update-black

I'm aware this is an opinionated proposal, please let me know what you think.

**Comment by jbcpollak** [comment]
this is a big deal, the pinned version of black is causing conflicts with other dependencies in our project. Please change the black dependency to use the `>=` operator.

**Comment by aawor** [comment]
we face the same problem. please update.

**Comment by lpasselin** [comment]
We are also having the same problem. Is black really required for detectron2?
