### ISSUE TITLE
If you want support Ukraine, please also support Iraq, Syria, Libya, Palestine, Lebanon.

### ISSUE THREAD

**Issue by inter2202** [facebookresearch/detectron2#4016]
If you only support Ukraine, you are on the highest tier of hypocrisy.

**Comment by zhaoshishuang** [comment]
🐮🍺

**Comment by fxxkusa** [comment]
[Dmitry Vinnik](https://github.com/dmitryvinn) He did this commit. 
Fuck off the US, fuck off the NATO.

**Comment by happynear** [comment]
Russia invades Ukraine for safety. US invaded Iraq for Petrodollar system.
Who is more evil?
![image](https://user-images.githubusercontent.com/3897999/156730253-af40ad7f-ce31-45c5-95a0-d41e2c46c02e.png)

**Comment by Abyssaledge** [comment]
Teacher told kids: America is the country of justice and never start a war
Kids in New York: We wanna go to America !!!

**Comment by fxxkukraine** [comment]
Stop Ukraine NAZI](https://github.com/fxxkukraine/stop_ukraine_nazi
Stop Ukraine NAZI!!!
Support Russia, support Putin to destroy NAZI!!!

**Comment by innat** [comment]
To get support, here are the minimum quality a person has to have: 😄 

- **blue eyes**
- **white skin**
- **golden hair**

**Comment by innat** [comment]
(Just for fun)

![main-qimg-7f91df7d3a654411980385e1204070eb](https://user-images.githubusercontent.com/17668390/156970643-28f33d64-73a3-49a8-8b6b-946ee0092c1c.jpg)

**Comment by ExtReMLapin** [comment]
> To get support, here are the minimum quality a person has to have: 😄
> 
>     * **blue eyes**
> 
>     * **white skin**
> 
>     * **golden hair**

stay mad pajeet

**Comment by ExtReMLapin** [comment]
> To get support, here are the minimum quality a person has to have: 😄
> 
>     * **blue eyes**
> 
>     * **white skin**
> 
>     * **golden hair**

stay mad

**Comment by Suzan009** [comment]
[GREATEST LIVE TV MOMENT OF ALL TIME!!!](https://www.youtube.com/watch?v=MjoLh1tAOFM) 🤣🤣🤣 #USA #Biden
