### ISSUE TITLE
V0.6 from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler

### ISSUE THREAD

**Issue by 2653888596** [facebookresearch/detectron2#4027]
When I installed detectron2 0.6 version, I couldn't find the following two functions .
from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler
Has their location changed?

**Comment by ppwwyyxx** [comment]
You can find them with search: https://github.com/facebookresearch/detectron2/search?q=def+add_deeplab_config
