### ISSUE TITLE
evaluate the AP and num workers

### ISSUE THREAD

**Issue by GiovanniPasq** [facebookresearch/detectron2#403]
i have used the following code for the training and testing:
#######TRAINING#########
register_coco_instances("dataset_Training", {}, "./drive/My Drive/dataset/BellomoDataset/Object_annotations/Training_annotations.json", "./drive/My Drive/dataset/BellomoDataset/images")
register_coco_instances("dataset_TestSet", {}, "./drive/My Drive/dataset/BellomoDataset/Object_annotations/TestSet_annotations.json", "./drive/My Drive/dataset/BellomoDataset/images")
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/retinanet_R_101_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("dataset_Training",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCODetection/retinanet_R_101_FPN_3x/138363263/model_final_59f53c.pkl" 
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 3000 
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 16 

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
##### problem#####
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/detectron2_repo/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/detectron2_repo/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/detectron2_repo/detectron2/data/dataset_mapper.py", line 74, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/content/detectron2_repo/detectron2/data/detection_utils.py", line 46, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py", line 411, in open
    path, mode, buffering=buffering
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py", line 242, in _open
    return open(path, mode, buffering=buffering)
OSError: [Errno 5] Input/output error: './drive/My Drive/dataset/BellomoDataset/images/Navigation_03/Rgb/Rgb_image_00006651.jpg'

1) i had to change cfg.DATALOADER.NUM_WORKERS from 2 to 1 because sometime i have an error (images is present in the right folder). Why? (dataset has 26k images)

##############TESTING#################
cfg.DATALOADER.NUM_WORKERS = 1
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.8
cfg.DATASETS.TEST = ("dataset_TestSet", )
evaluator = COCOEvaluator("dataset_TestSet", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "dataset_TestSet")
inference_on_dataset(trainer.model, val_loader, evaluator)

and i had the problem:

Total inference time: 4:33:13 (0.668556 s / img per device, on 1 devices)
[11/26 14:51:08 d2.evaluation.evaluator]: Total inference pure compute time: 4:28:41 (0.657471 s / img per device, on 1 devices)
[11/26 14:51:14 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)
<ipython-input-4-1c36c8017536> in <module>()
      7 evaluator = COCOEvaluator("dataset_TestSet", cfg, False, output_dir="./output/")
      8 val_loader = build_detection_test_loader(cfg, "dataset_TestSet")
----> 9 inference_on_dataset(trainer.model, val_loader, evaluator)

2 frames
/content/detectron2_repo/detectron2/evaluation/coco_evaluation.py in _eval_predictions(self, tasks)
    145             }
    146             for result in self._coco_results:
--> 147                 result["category_id"] = reverse_id_mapping[result["category_id"]]
    148 
    149         if self._output_dir:

KeyError: 55

**Comment by ppwwyyxx** [comment]
```
File "/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py", line 242, in _open
return open(path, mode, buffering=buffering)
OSError: [Errno 5] Input/output error: './drive/My Drive/dataset/BellomoDataset/images/Navigation_03/Rgb/Rgb_image_00006651.jpg'
```

as the log says, python cannot open this file.

```
146 for result in self._coco_results:
--> 147 result["category_id"] = reverse_id_mapping[result["category_id"]]
148
149 if self._output_dir:

KeyError: 55
```
your model is predicting a category 55 however your COCO annotation file does not specify >=56 categories.
