### ISSUE TITLE
How to quick eval model?

### ISSUE THREAD

**Issue by iot-hunter** [facebookresearch/detectron2#404]
## ❓ Questions and Help

General questions about detectron2.
I have save many model like model_iterNum.pth, what should I do to find the best model ?
NOTE:
I have save many model like model_iterNum.pth,    what should I do to find the best model ?
I am not sure which model is the eval best model!!

**Comment by ppwwyyxx** [comment]
You can evaluate them.

One example using train_net.py is given in https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#use-detectron2-in-command-line.
