### ISSUE TITLE
Parallel VOC eval

### ISSUE THREAD

**Issue by bradezard131** [facebookresearch/detectron2#405]
## 🚀 Feature
Parallelise evaluation on VOC with python multiprocessing.

## Motivation

Evaluation on VOC is incredibly slow, often taking over an hour even on a reasonably powerful server. This is because the entire evaluation for every class at every threshold is done sequentially in one thread.

## Pitch

At a minimum modify this block to use a multiprocessing pool and call the different thresholds with Pool.starmap
https://github.com/facebookresearch/detectron2/blob/4a0407dad12305c75cc7d9a9b80b3fa68cf206e7/detectron2/evaluation/pascal_voc_evaluation.py#L94-L103

Alternatively, break the per-class processing into a separate function and do the same thing at the class level with this loop:
https://github.com/facebookresearch/detectron2/blob/4a0407dad12305c75cc7d9a9b80b3fa68cf206e7/detectron2/evaluation/pascal_voc_evaluation.py#L88

It is also possible to rewrite the `voc_ap` function itself to use vectorised operations for better performance, however this would break consistency with py-faster-rcnn if that is important. I have tested this and floating-point errors did accumulate enough to be about ±2e-10 the same rather than exactly the same.

**Comment by ppwwyyxx** [comment]
The evaluation takes 1 minute in our logs. If you think it took one hour, it sounds like an unexpected issue and please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
