### ISSUE TITLE
prediction results of roi_heads.box_predictor.inference  and from DefaultPredictor() are different

### ISSUE THREAD

**Issue by shubhamsharma1609** [facebookresearch/detectron2#4052]
The no. of predicted instances(no. of predicted bounding boxes along with predicted classes) from the roi_heads.box_predictor.inference and the ones predicted using a Default predictor() are completely different. Kindly guide as to why the predictions are different.

**Comment by ppwwyyxx** [comment]
This is expected and the behavior of `DefaultPredictor` is already documented in https://detectron2.readthedocs.io/en/latest/modules/engine.html#detectron2.engine.defaults.DefaultPredictor , which says it does more than just using the model directly.

Closing as it's not an unexpected issue.
