### ISSUE TITLE
Rebuild

### ISSUE THREAD

**Issue by SunAnLan** [facebookresearch/detectron2#407]
## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

Do I need to rebuild the detectron2 if I want to modify some code like adding focal loss in rpn_output.py?

**Comment by ppwwyyxx** [comment]
You don't have to recompile the ops.
But you need to make sure you'll run the code that you modified -- and that depends on how you install detectron2.

**Comment by PkuRainBow** [comment]
@ppwwyyxx I also have concerns on how to avoid rebuild the code when updating the operators.

For example, I have built the detectron2 on several remote GPU dev-machines based on the code-v1. Then we update some operators and push the updates to the remote GPU dev-machines. Currently, I will have to rebuild the detectron2 on these remote GPU dev-machines to support the updated operators. 

I am wondering how to avoid the rebuilding operation on the remote GPU dev-machines. 

Thanks!

**Comment by ppwwyyxx** [comment]
You can build them on other machines and distribute the built package rather than source code.

**Comment by PkuRainBow** [comment]
Thanks for your quick reply.

Yeah, currently, I rebuild the detectron2 (newest version) within the docker image after updating the operators and then load the docker image to the remote GPU dev-machines, which is similar to the mentioned solution.

In fact, I have a small concern about the above pipeline.  According to my understanding of the implementing mechanism of the "Projects" examples, e.g., if we update the **point_head.py** within the _PointRend_ folder by adding a new class named **StandardPointHeadV2** and register it with **POINT_HEAD_REGISTRY**, then we do not need to rebuild the detectron2 project. Right?

**Comment by ppwwyyxx** [comment]
C/C++ code needs to be built.
Python code does not need to be built and can be used if put at the right place.

**Comment by PkuRainBow** [comment]
Thanks! I am wondering what the "**right place**" means? Are there any documents that I can learn the details?

**Comment by ppwwyyxx** [comment]
If it's a modification to an existing python file, overwriting the existing file will work.
