### ISSUE TITLE
Make the exported TorchScript model available on different devices

### ISSUE THREAD

**Issue by CescMessi** [facebookresearch/detectron2#4080]
## 🚀 Feature
Make the exported TorchScript model independent of a specific device.

## Motivation & Examples

When I export the TorchScript model using trace mode on CUDA:0, I can run the model well on CUDA:0 devices on other machines. But when I try to run the model on CPU or CUDA:1, I get a "tensor on a different device" error. I found that there were some codes similar to  `to(device)` in detectron2 models. In the exported TorchScript model code, device would be fixed to the device at the time of export, resulting in inconsistency with the device at run time, thus causing errors. 

I wonder if there is a solution to this problem? I have tried exported models in TorchVision, it can run on different devices.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers -- we only consider papers that have enough significance and prevalance in the object detection field.

We do not take requests for most projects in the `projects/` directory, because they are research code release that is mainly for other researchers to reproduce results.

"Make X faster/accurate" is not a valid feature request. "Implement a concrete feature that can make X faster/accurate" can be a valid feature request.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/main/projects/) directory contains many of such examples.

**Comment by Z-star1** [comment]
have you "Target "torchscript_mask_rcnn" links to target "Python3::Python" but the
  target was not found. " this problems??thank you

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/pull/4132 fixed the issue. Now if the exported torchscript can be moved to different devices by `model.to`.
