### ISSUE TITLE
Is it possible to train detector on images with NO object to suppress the false detection

### ISSUE THREAD

**Issue by HaiyueZhu** [facebookresearch/detectron2#4082]
## 🚀 Feature
Does anyone have suggestion on how to train detector using images with NO objects (no annotations)? 

## Motivation & Examples
This is in order to suppress the false detection in many cases where the samples with object annotation are not too much. I am trying to using the current COCOdataset, but it seems it samples image base on annotated objects, if there is no annotation it will not sample the image.

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html:
> If annotations is an empty list, it means the image is labeled to have no objects. Such images will by default be removed from training, but can be included using DATALOADER.FILTER_EMPTY_ANNOTATIONS.

**Comment by kaushikepi** [comment]
@ppwwyyxx How do we train the model if the training set has negative samples i.e Images with no annotated object? So the annotation: list[dict] will not be empty. Still, it will have a filled dict with bbox information for images with bbox annotation information but an empty dict or no dictionary for negative samples.

How do we create annotation list for training set having both true and negative samples

**Comment by rgkannan676** [comment]
DATALOADER.FILTER_EMPTY_ANNOTATIONS = False, will include the negative samples.
