### ISSUE TITLE
What config parameters to use to replicate Detectron1 results?

### ISSUE THREAD

**Issue by manyaafonso** [facebookresearch/detectron2#409]
I obtained a mAP of 92% on my dataset using detectron1 with the ResNet50 architecture and the configuration e2e_mask_rcnn_R-50-FPN_2x.yaml
https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_2x.yaml

How do I set the corresponding config parameters in detectron2 to get the same metric?
I had a look at the configs here:
https://github.com/facebookresearch/detectron2/tree/master/configs/COCO-InstanceSegmentation
but could not find a similar one.

Is there a script to migrate a detectron1 config yaml file to detectron2?

Thanks in advance.

**Comment by ppwwyyxx** [comment]
Answered in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md already.
