### ISSUE TITLE
Explanation of the RepeatFactorTrainingSampler.repeat_factors_from_category_frequency(`repeat_thresh`)

### ISSUE THREAD

**Issue by marijnl** [facebookresearch/detectron2#4095]
## 📚 RepeatFactorTrainingSampler.repeat_factors_from_category_frequency

From the docs [repeat_factors_from_category_frequency](https://detectron2.readthedocs.io/en/v0.4.1/modules/data.html?highlight=repeat_factors_from_category_frequency#detectron2.data.samplers.RepeatFactorTrainingSampler.repeat_factors_from_category_frequency) 
```
repeat_thresh (float) – frequency threshold below which data is repeated. If the frequency is half of repeat_thresh, the image will be repeated twice.
```
In the source code i find these lines:
```
# 2. For each category c, compute the category-level repeat factor:
#    r(c) = max(1, sqrt(t / f(c)))
```

Now if `f(c) = frequency = 0.5` and `t = repeat_thresh = 1` then `r(c) = 1.41`

Can someone explain the docstring "If the frequency is half of repeat_thresh, the image will be repeated twice." to me? Based on the example above i would expect that every image in `c` to be repeated `1.41` times, not `2.0` as the doc suggests.

**Comment by s0tt** [comment]
Hi @marijnl ,
you are right, repeat factors are fractional. But as written a few lines below :

`        # Since repeat factors are fractional, we use stochastic rounding so
        # that the target repeat factor is achieved in expectation over the
        # course of training
        rands = torch.rand(len(self._frac_part), generator=generator)
        rep_factors = self._int_part + (rands < self._frac_part).float()`
        
This means during training sometimes it repeats by the next highest integer and sometimes only by the clipped off integer part.
Otherwise you wouldn't achieve a fractional resampling, like you already pointed out.
Hope this answers your question.

**Comment by chawins** [comment]
@marijnl Have you figured this out? I believe that the documentation is incorrect as well, even though the implementation matches the description in the referenced paper. It looks like this resampling technique mitigates the class imbalance but does not completely rectify it (i.e., make all classes balanced).

**Comment by chawins** [comment]
Thanks for the answer! In my case, I created a custom `RepeatFactorTrainingSampler` just without the `sqrt()`.
