### ISSUE TITLE
Different settings in config compared to maskrcnn_benchmark

### ISSUE THREAD

**Issue by xiyinmsu** [facebookresearch/detectron2#41]
Hello, 

I have noticed that the numbers reported in this repo. is better than that in maskrcnn_benchmark repo. After comparing the training config settings, there are several differences that cause the performance gap. 

First of all, I checked the configs in configs/COCO-Detection/. All "1x" settings do not overwrite the MAX_ITER in the default config (MAX_ITER=40K by default). But from the description in the MODEL_ZOO and also in maskrcnn_benchmark, the "1x" setting is for MAX_ITER=90K and BATCH_SIZE=16. This is not consistent. So how much iterations are these models "1x" trained for? 

Second, the BASE_LR is set to 0.001 in this repo. and maskrcnn_benchmark uses BASE_LR=0.02. I am just curious will 0.001 be too small so that you argue "1x" is under-trained? 

Third, the other two parameters that I think will contribute to this performance gap and also increase training time. MODEL.RPN.POST_NMS_TOPK_TRAIN = 2000 in this repo and 1000 for maskrcnn. And MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 14 Iin this repo. and 7 for maskrcnn. 

I wanted to point these out because otherwise the results might be mis-leading when comparing between these two repositories. Could you please confirm the iterations for "1x"?

**Comment by ppwwyyxx** [comment]
You need to look at the base configs for each config, e.g. https://github.com/facebookresearch/detectron2/blob/master/configs/Base-RCNN-FPN.yaml.

**Comment by xiyinmsu** [comment]
Okay. I see that now. Thank you for your quick reply!

**Comment by xiyinmsu** [comment]
Then, is the performance gap mainly coming from the multi-scale training? INPUT.MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

**Comment by ppwwyyxx** [comment]
>  the performance gap 

I don't know "what" performance gap you mean.

As the model zoo said, https://github.com/facebookresearch/detectron2/tree/master/configs/Detectron1-Comparisons has configs that are closer to Detectron1 settings.

**Comment by xiyinmsu** [comment]
Sorry I mean the results in maskrcnn_benchmark repo: https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md

Now I see most of the config settings are the same except the INPUT.MIN_SIZE_TRAIN.

**Comment by ppwwyyxx** [comment]
`INPUT_MIN_SIZE_TRAIN` is also the same in  https://github.com/facebookresearch/detectron2/tree/master/configs/Detectron1-Comparisons
