### ISSUE TITLE
[Feature Request] Iterable-style datasets

### ISSUE THREAD

**Issue by austinmw** [facebookresearch/detectron2#4102]
## 🚀 Feature
I'd like to be able to train on iterable-style datasets. 
(iterable-style datasets only have `__iter__`, whereas map-style datasets have `__len__` and `__getitem__`).

## Motivation & Examples

Some vision datasets are very large, and iterable-style becomes more easy to work with compared to map-style. WebDataset has [been advertised by PyTorch blog](https://pytorch.org/blog/efficient-pytorch-io-library-for-large-datasets-many-files-many-gpus/) as an efficient library for large datasets, and with the release of PyTorch 1.11 and TorchData, it seems iterable-style datasets will continue to gain significant traction.

Having the capability to train iterable datasets from WebDataset, TorchData, and NVIDIA DALI would make training large and/or remote datasets much more accessible. This may also inprove dataloading speeds under certain circumstances. 

I think the best way to implement this would be similar to the map-style dataset tutorials. First have one or two built-in iterable dataset examples, and then follow this up by describing how to register the balloon dataset as an iterable (maybe starting from tar files rather than the current example of creating a list of dicts from a json).

**Comment by ppwwyyxx** [comment]
Iterable datasets are already supported.
If `build_detection_train_loader` is used to build dataloader like this https://github.com/facebookresearch/detectron2/blob/6886f85baee349556749680ae8c85cdba1782d8e/projects/Panoptic-DeepLab/train_net.py#L98, users can pass in their iterable dataset by `dataset=iterable_dataset` argument of this function.
Other functions that accept `dataset` argument all accept iterable datasets.

**Comment by austinmw** [comment]
> Iterable datasets are already supported. If `build_detection_train_loader` is used to build dataloader like this
> 
> https://github.com/facebookresearch/detectron2/blob/6886f85baee349556749680ae8c85cdba1782d8e/projects/Panoptic-DeepLab/train_net.py#L98
> 
> , users can pass in their iterable dataset by `dataset=iterable_dataset` argument of this function.
> Other functions that accept `dataset` argument all accept iterable datasets.

Ah I see thanks. Does this still build a list(dict) across the whole dataset and potentially run into RAM issues if annotations can't fit into memory? I saw that D2Go has a caching option so wasn't sure if base detectron2 supported large iterable datasets.
