### ISSUE TITLE
list indices must be integers or slices, not str on custom dataset

### ISSUE THREAD

**Issue by an99990** [facebookresearch/detectron2#4115]
## Instructions To Reproduce the 🐛 Bug:
1. I have a custom dataset that I loaded in a json file according to COCO annotations and I am trying to train a detectron2 model but i keep getting the same issue with the indexes.. I believe this is related to how i write my annotation file. I have put a sample of the generated json. 

Please let me know if i can provide any other information

3. What exact command you run:
 ```
for d in ['train']:
    DatasetCatalog.register(f"norway_groceries_{d}", lambda d=d : annotations)
    MetadataCatalog.get(f"norway_groceries_{d}").set(thing_classes = [
  "Alpro_Soya_Chocolate",
  "Alpro_Soya_NoSugars",
  "Eldorado_GoEco_OkologiskeKidneybonner",
  "GoGreen_Kdneybonor",
  "GoGreen_Kikarter",
  "GoGreen_RodaLinser",
  "GoGreen_SvartaBonor",
  "Heinz_BeanzInTomatoSauce",
  "Heinz_KrossadeTomater",
  "Monster_Energy",
   "Monster_Ultra",
   "Nora_TomatBonner",
   "Sopps_Spaghetti",
   "Zalo",
   "Zalo_Sitron"
])

from detectron2.model_zoo import model_zoo

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("norway_groceries_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 1000
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 15
cfg.OUTPUT_DIR = "/home/le/train"

trainer = DefaultTrainer(cfg) 

trainer.resume_or_load()
train_results = trainer.train()
```
4. __Full logs__ or other relevant observations:
```
ERROR [03/31 14:50:14 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/engine/train_loop.py", line 267, in run_step
    data = next(self._data_loader_iter)
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/data/common.py", line 234, in __iter__
    for d in self.dataset:
  File "/home/le/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/le/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/le/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/le/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/le/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/le/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2/data/dataset_mapper.py", line 154, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.image_format)
TypeError: list indices must be integers or slices, not str

[03/31 14:50:14 d2.engine.hooks]: Total training time: 0:00:04 (0:00:00 on hooks)
[03/31 14:50:14 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 173M
```
5. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:
Linux
```
sys.platform            linux
Python                  3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
numpy                   1.22.2
detectron2              0.6 @/home/le/ros_ws/src/le-segmentation/le_segmentation/models/detectron2/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 11.3
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.0+cu113 @/home/le/.local/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   Quadro T2000 with Max-Q Design (arch=7.5)
Driver version          470.103.01
CUDA_HOME               /usr/local/cuda
Pillow                  8.4.0
torchvision             0.11.1+cu113 @/home/le/.local/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220119
iopath                  0.1.9
cv2                     4.5.4
----------------------  -------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```
[[{"file_name": "/home/le/Desktop/data_synthetic/strongpoint_efficientPose/data/1/rgb/1389.jpg", "height": 960, "width": 540, "annotations": {"segmentation": [[181.0, 367.9980392156863, 215.0, 361.9980392156863, 216.99803921568628, 360.0, 214.99803921568628, 272.0, 213.0, 257.0019607843137, 196.0, 257.0019607843137, 188.0, 259.0019607843137, 186.0, 256.0019607843137, 175.0, 257.0019607843137, 167.00196078431372, 260.0, 168.0, 264.0019607843137, 157.00196078431372, 267.0, 160.00196078431372, 363.0, 175.0, 367.9980392156863, 181.0, 367.9980392156863]], "image_id": 2000, "category_id": 1, "bbox": [157.00196078431372, 256.0019607843137, 59.99607843137255, 111.99607843137255], "bbox_mode": 1, "area": 6109.918635140331}}, {"file_name": "/home/le/Desktop/data_synthetic/strongpoint_efficientPose/data/1/rgb/1389.jpg", "height": 960, "width": 540, "annotations": {"segmentation": [[181.0, 367.9980392156863, 215.0, 361.9980392156863, 216.99803921568628, 360.0, 214.99803921568628, 272.0, 213.0, 257.0019607843137, 196.0, 257.0019607843137, 188.0, 259.0019607843137, 186.0, 256.0019607843137, 175.0, 257.0019607843137, 167.00196078431372, 260.0, 168.0, 264.0019607843137, 157.00196078431372, 267.0, 160.00196078431372, 363.0, 175.0, 367.9980392156863, 181.0, 367.9980392156863]], "image_id": 2000, "category_id": 1, "bbox": [157.00196078431372, 256.0019607843137, 59.99607843137255, 111.99607843137255], "bbox_mode": 1, "area": 6109.918635140331}}, {"file_name": "/home/le/Desktop/data_synthetic/strongpoint_efficientPose/data/1/rgb/1389.jpg", "height": 960, "width": 540, "annotations": {"segmentation": [[181.0, 367.9980392156863, 215.0, 361.9980392156863, 216.99803921568628, 360.0, 214.99803921568628, 272.0, 213.0, 257.0019607843137, 196.0, 257.0019607843137, 188.0, 259.0019607843137, 186.0, 256.0019607843137, 175.0, 257.0019607843137, 167.00196078431372, 260.0, 168.0, 264.0019607843137, 157.00196078431372, 267.0, 160.00196078431372, 363.0, 175.0, 367.9980392156863, 181.0, 367.9980392156863]], "image_id": 2000, "category_id": 1, "bbox": [157.00196078431372, 256.0019607843137, 59.99607843137255, 111.99607843137255], "bbox_mode": 1, "area": 6109.918635140331}}, {"file_name": "/home/le/Desktop/data_synthetic/strongpoint_efficientPose/data/1/rgb/1389.jpg", "height": 960, "width": 540, "annotations": {"segmentation": [[181.0, 367.9980392156863, 215.0, 361.9980392156863, 216.99803921568628, 360.0, 214.99803921568628, 272.0, 213.0, 257.0019607843137, 196.0, 257.0019607843137, 188.0, 259.0019607843137, 186.0, 256.0019607843137, 175.0, 257.0019607843137, 167.00196078431372, 260.0, 168.0, 264.0019607843137, 157.00196078431372, 267.0, 160.00196078431372, 363.0, 175.0, 367.9980392156863, 181.0, 367.9980392156863]], "image_id": 2000, "category_id": 1, "bbox": [157.00196078431372, 256.0019607843137, 59.99607843137255, 111.99607843137255], "bbox_mode": 1, "area": 6109.918635140331}},

**Comment by jameshgrn** [comment]
I have this same issue, the docs state that a custom mapper (my case) should take a list of dicts as specified by "dataset_dict", but passing the custom mapper, or even the default mapper in this case seems to fail with this input

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#register-a-dataset says the custom dataset has to be a `list[dict]`. But according to your sample:
```
[[{"file_name": "/home/le/Desktop/data_synthetic/strongpoint_efficientPose/data/1/rgb/1389.jpg"
```
it starts with `[[{"file_name": ` so it is a `list[list[dict]]` instead. Therefore the failure is expected.
