### ISSUE TITLE
Duplicate proposals sorting in RPN.

### ISSUE THREAD

**Issue by PkuDavidGuan** [facebookresearch/detectron2#412]
I think the proposals sorting is duplicated in https://github.com/facebookresearch/detectron2/blob/38fedca84c9a04399149fa1bd64743c983d39ff3/detectron2/modeling/proposal_generator/rpn.py#L185.

since they are sorted in https://github.com/facebookresearch/detectron2/blob/38fedca84c9a04399149fa1bd64743c983d39ff3/detectron2/layers/nms.py#L25

**Comment by ppwwyyxx** [comment]
makes sense.
In our original implementation we did not use `batched_nms` so the results are not sorted. Now it seems there is a redundancy.
