### ISSUE TITLE
How to find the "scale-aware" implementation in the project of TridentNet

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#413]
## ❓ Questions and Help

Where is the implementation of the "scale-aware" training scheme as described in Sec 4.2.  in [Scale-Aware Trident Networks for Object Detection](https://arxiv.org/abs/1901.01892)

Thank you!

**Comment by ppwwyyxx** [comment]
It's not implemented (and I don't think we will work on this)
