### ISSUE TITLE
detectron2-0.1 in cuda11.1

### ISSUE THREAD

**Issue by sssimpleboy** [facebookresearch/detectron2#4145]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
Due to some reasons,I have to install detectron2-0.1 on cuda11.1.
Could you tell me how to change the code?
Thank you !

```
2. What exact command you run: python setup.py build develop
3. __Full logs__ or other relevant observations:
```
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
> Due to some reasons,I have to install detectron2-0.1 on cuda11.1.
Could you tell me how to change the code?

Detectron2 0.1 does not support cuda11.1.
