### ISSUE TITLE
ROI box heads box predictor giving final detections as 100 boxes

### ISSUE THREAD

**Issue by shubhamsharma1609** [facebookresearch/detectron2#4148]
I ran predictions for my model and as a result for each image I am getting 100 predictions per image and the prediction for each image has 100 bboxes with first detection having highest confidence score. I had set the `cfg.TEST.DETECTIONS_PER_IMAGE `to 100 that means maximum 100 detections will be there in each image but each image of my test data does not have so many detections. I think the NMS threshold has not been applied correctly as I am getting 100 boxes per image arranged in decreasing order of scores. Earlier,I used to get 4 to 10 detections but this time it sounds alarming that I am having 100 detections per image arranged in decreasing order of scores. Earlier, also I had used the same configuration setting of `cfg.TEST.DETECTIONS_PER_IMAGE` to 100 but got reasonable no. of bounding boxes. Kindly guide.

**Comment by hiroto01** [comment]
Hi shubham i know this might be outbof context but can you plz look into this issue and tell whats wrong if possible!? plz that might be really helpful!!
https://github.com/facebookresearch/detectron2/issues/4147#issue-1199364615

**Comment by zhanghang1989** [comment]
You may change 

_C.MODEL.RPN.PRE_NMS_TOPK_TEST
_C.MODEL.RPN.POST_NMS_TOPK_TEST

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
