### ISSUE TITLE
features extraction 

### ISSUE THREAD

**Issue by rabahMoulai** [facebookresearch/detectron2#4155]
hello, I am new here, I would like to know how can i have the features corresponding to each object detected in an inference ? I imagine that we can get them as output of box head but they are the features of all object proposals before the NMS and not the objects detected in the inference

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/en/latest/tutorials/models.html#partially-execute-a-model has explained how to do this.
