### ISSUE TITLE
production environment

### ISSUE THREAD

**Issue by kl720** [facebookresearch/detectron2#416]
how to deployment model to production environment,when can we see detectron2go?

**Comment by ruxiaobao** [comment]
I second, also will detectron2go support pytorch->onnx->tensorRT pipeline?

**Comment by ppwwyyxx** [comment]
detectron2go will support pytorch->onnx->caffe2's efficient inference on server/mobile CPUs. We don't have any GPU inference pipeline.
We hope to release it soon but no concrete timeline.

**Comment by ruxiaobao** [comment]
@ppwwyyxx got it, thanks!
