### ISSUE TITLE
Hi, the demo script gives segmentation fault on the example provided.

### ISSUE THREAD

**Issue by saksham15082** [facebookresearch/detectron2#42]
The ipynb provided here:
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 has a demo code for maskrcnn instance segmentation.

## To Reproduce
Running the code till outputs = predictor(im)
The program just exits with a segmentation fault and no other output.

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.

Output : Segmentation fault (core dumped)

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template you deleted.

**Comment by saksham15082** [comment]
@ppwwyyxx  Update the comment. I tried on two different machines but it leads to the same segmentation fault.

**Comment by ppwwyyxx** [comment]
Cannot import `detectron2.utils.collect_env` means that you have issues in your installation of pytorch/opencv/torchvision etc. It's best if you could clean up your environment, uninstall and reinstall all dependencies. If you're unable to do so, you can also use the provided [dockerfile](https://github.com/facebookresearch/detectron2/blob/master/Dockerfile).

If you know how to use gdb, running `gdb --args python -m detectron2.utils.collect_env` and `bt` when it crashed can tell you more about which software in your environment is causing the crash.

**Comment by batrlatom** [comment]
@saksham15082  how did you resolve it? I have same problem

**Comment by ppwwyyxx** [comment]
@batrlatom  your issue is in fact more similar to #62 than this.
