### ISSUE TITLE
Tensor RT conversion

### ISSUE THREAD

**Issue by AndreiBaraian** [facebookresearch/detectron2#4202]
I have tried converting the Generalized RCNN (Mask R-CNN) to Tensor RT. However, the execution loops indefinitely when converting the traced model to Tensor RT format. Has anyone been able to solve this? No errors encountered, just that nothing happens and it looks like the program is executing (30 min.+).

**Comment by fortianyou** [comment]
You can have a try on [TorchBlade](https://github.com/alibaba/BladeDISC/tree/main/pytorch_blade/benchmark). This is a related issue I have created previously: https://github.com/facebookresearch/detectron2/issues/4083.

**Comment by zhiqwang** [comment]
Just FYI , TensorRT also provide a Mask R-CNN sample https://github.com/NVIDIA/TensorRT/tree/main/samples/python/detectron2#detectron-2-mask-r-cnn-r50-fpn-3x-in-tensorrt

**Comment by hcw-00** [comment]
The only problem is Detectron's native structures(Instances, Boxes, etc..). Replace those structures to the python's data structures, like list, tuple, etc.., and try to convert to onnx. It will work.

**Comment by zhiqwang** [comment]
Hi @hcw-00 

I agree with your conclusion here. BTW both the above TorchBlade and the new solution provided by TensorRT have some new approaches to the solution. For example, TensorRT's solution, it's an end-to-end approach where they embed the NMS into the ONNX graph.

**Comment by hcw-00** [comment]
@zhiqwang 
Yeah, I'm totally agree with you. I forgot to mention but, ops like nms might be replaced by compatible Plugins.
