### ISSUE TITLE
I want to do inference with the model I trained

### ISSUE THREAD

**Issue by isagastiberri** [facebookresearch/detectron2#421]
## ❓ Questions and Help

Hello! I trained a model for instance segmentation using the balloon example and I saved it in _final_model.pth_. I want to test a few images, but using the model I trained, so when I do merge from file I use the same .yaml that I used for training but changing the Weights parameter to the model I trained. To be sure, I also changed the model weight with **cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")** in my inference script but I'm still getting the warning

```
'roi_heads.box_predictor.cls_score.weight' has shape (67, 1024) in the checkpoint but (81, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (67,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (264, 1024) in the checkpoint but (320, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (264,) in the checkpoint but (320,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (66, 256, 1, 1) in the checkpoint but (80, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (66,) in the checkpoint but (80,) in the model! Skipped.
```
I assume this means it ignoring the predictor, so I can't infere correctly. How should I load the model to do inference with my model?

Thanks a lot

**Comment by ppwwyyxx** [comment]
> I use the same .yaml that I used for training but changing the Weights parameter to the model I trained

You've made more changes on the config before training that are not included in the config file.

**Comment by isagastiberri** [comment]
oh, of course! Thanks a lot for the help, now it works :)
