### ISSUE TITLE
Unable to export correct weights for TorchScript

### ISSUE THREAD

**Issue by ArgoHA** [facebookresearch/detectron2#4212]
## General info:

Hi! I have trained maskrcnn with detectron2 and have exported with [this](https://github.com/facebookresearch/detectron2/tree/main/tools/deploy) instructions (I used scripting) torch script model (model.ts). The problem is that this export does not give me weights in .pt, but as I see in pytorch docs, I need .pt file as weights of a model. And yes, I've tried to use .ts instead of .pt and model does not load.

When I save weights for torchscript in pytorch - I get .pt weights:

```
m = torch.jit.script(MyModule())

torch.jit.save(m, 'scriptmodule.pt')
```

Could you please provide some information on that? Am I doing something wrong?
My goal is to train model with Detectron2, export torchscript weights and deploy it in torchserve.

## Instructions To Reproduce the Issue and Full Logs:

1) Train maskrcnn with custom dataset and save .pth
2) change one function in export_model.py:

```
def setup_cfg(args):
    register_coco_instances('valid_dataset_name', {}, "/home/argo/segmentation/detectron2/dataset_segment/label/valid.json", "/home/argo/segmentation/detectron2/dataset_segment/data/valid")

    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
    cfg.MODEL.WEIGHTS = os.path.join('/home/argo/segmentation/detectron2/output/model_final.pth')
    cfg.DATASETS.TEST = ('valid_dataset_name', )
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 6
    cfg.DATALOADER.NUM_WORKERS = 2
    return cfg
```

3) use scripting for export with command:

```
python3 export_model_custom.py --config-file configs/mask_rcnn_R_50_FPN_3x.yaml \
    --output output --export-method scripting --format torchscript \
    MODEL.WEIGHTS output/model_final.pth
```

4) Get .ts weights. I tried to use them with torch serve ([commands](https://github.com/pytorch/serve/tree/master/examples/object_detector/maskrcnn)) torch serve and got issues:

```
java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String; at org.pytorch.serve.util.ConfigManager.readFile(ConfigManager.java:235) at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:139) at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:285) at org.pytorch.serve.ModelServer.main(ModelServer.java:83)
```

## Environment:
Detectron2 version: 0.6
torchserve version: 0.5.3
torch-model-archiver version: 0.5.3
torch version: 1.10.1+cu111
torchvision version [if any]: 0.11.2+cu111
java version: 1.8.0_312
Operating System and version: Ubuntu 20.04.4

`----------------------  -----------------------------------------------------------------------
sys.platform            linux
Python                  3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
numpy                   1.22.3
detectron2              0.6 @/home/argo/.local/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.3
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.1+cu111 @/home/argo/.local/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA RTX A5000 (arch=8.6)
Driver version          470.103.01
CUDA_HOME               /usr
Pillow                  9.0.1
torchvision             0.11.2+cu111 @/home/argo/.local/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220414
iopath                  0.1.9
cv2                     4.5.5
----------------------  -----------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, `

**Comment by ArgoHA** [comment]
Added  "Instructions To Reproduce the Issue and Full Logs"

**Comment by ArgoHA** [comment]
Is there a way to get .pt weights from detectron2?

**Comment by ppwwyyxx** [comment]
There is no such concepts as ".pt weights". "pt" is just a file name that can be anything.

It seems your expectation is to let the model work under torchserve. However torchserve is a separate project and we don't provide help for using it nor are we familiar with it. 

I'm pretty sure though the code in https://github.com/pytorch/serve/tree/master/examples/object_detector/maskrcnn are written purely for torchvision and therefore are not going to work for detectron2. So the failure you observed are expected.
