### ISSUE TITLE
where is the downloaded model located?

### ISSUE THREAD

**Issue by zzzxxxttt** [facebookresearch/detectron2#423]
My GPU server can't access the Internet so the training fails when downloading the pretrained model (R-50.pkl). I guess I can download it on my computer and upload it to the server before training, but where should I put the R-50.pkl file?

**Comment by ppwwyyxx** [comment]
You can put it anywhere and use its absolute path instead of a link

**Comment by zzzxxxttt** [comment]
get it, I just need to modify the config file, thank you very much!
