### ISSUE TITLE
Problem with installing detectron2 on MacOS 10.15.7

### ISSUE THREAD

**Issue by safe-fk** [facebookresearch/detectron2#4238]
I try to install detectron2 on MacOS 10.15.7 and run into the following issues

Instructions To Reproduce the Issue and Full Logs

**Code I run:**

python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

**Output:**

Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/1r/pjlpc9p94zsgyh4q53_ngp100000gn/T/pip-req-build-k8yx7de7
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/1r/pjlpc9p94zsgyh4q53_ngp100000gn/T/pip-req-build-k8yx7de7
  Resolved https://github.com/facebookresearch/detectron2.git to commit 42c44b622eb7b179576bdac218c84c107fff8eab
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: -11
  ╰─> [0 lines of output]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Expected behavior:**
Install detectron2

**Your Environment**
MacOS 10.15.7

Anyone an idea? Many thanks!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
