### ISSUE TITLE
CPU Utilization is 100% during training. Is it normal?

### ISSUE THREAD

**Issue by xuhuasheng** [facebookresearch/detectron2#424]
## ❓ Questions and Help

CPU resources are consumed heavily during training, and the 6 cores of CPU usage are almost 100%. Is this normal?

I used tools/train_net.py with 1080TI,  intel i5 9th.

**Comment by ppwwyyxx** [comment]
It is

**Comment by shuri** [comment]
How come? Is this preventable in code or in implementation?
