### ISSUE TITLE
error instantiating baseline model due to omegaconf

### ISSUE THREAD

**Issue by maidmentdaniel** [facebookresearch/detectron2#4254]
## Instructions To Reproduce the 🐛 Bug:
I'm using a conda environment where I have installed the following:
1. `conda install pytorch torchvision torchaudio cpuonly -c pytorch-lts`
2. `python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.8/index.html`

### Simplified runnable code:
> ```
> from detectron2.config import LazyConfig, instantiate
> from detectron2.engine import (
>     default_argument_parser,
>     default_setup,
>     launch,
> )
> from detectron2.model_zoo import get_config
> 
> 
> def main(args):
>     cfg = get_config('new_baselines/mask_rcnn_R_50_FPN_100ep_LSJ.py', trained=True)
>     default_setup(cfg, args)
> 
>     model = instantiate(cfg.model)
>     print("Model:\n{}".format(model))
> 
> 
> if __name__ == "__main__":
>     parser = default_argument_parser()
>     args = parser.parse_args()
>     launch(
>         main,
>         args.num_gpus,
>         num_machines=args.num_machines,
>         machine_rank=args.machine_rank,
>         dist_url=args.dist_url,
>         args=(args,),
>     )
> ```

# The problem
Hi all,

I'm attempting to train mask-rcnn on a custom dataset. I'm new to the detectron2 framework, so please bare with me.

I'm registering a dataset and calling a baseline config as follows:
```
register_coco_instances("seg_train", {}, train_annot, train_src)
register_coco_instances("seg_validate", {}, validate_annot, validate_src)
cfg = get_config('new_baselines/mask_rcnn_R_50_FPN_100ep_LSJ.py', trained=True)
cfg.dataloader.train.dataset.names = "seg_train"
cfg.dataloader.test.dataset.names = "seg_validate"
default_setup(cfg, args)
```
Then running do_train as taken from [tools/lazyconfig_train_net.py](https://github.com/facebookresearch/detectron2/blob/main/tools/lazyconfig_train_net.py)
```
model = instantiate(cfg.model)
```
As a result I get the following Traceback:
>```
> Traceback (most recent call last):
>   File "train_net.py", line 117, in <module>
>     launch(
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
>     main_func(*args)
>   File "train_net.py", line 106, in main
>     do_train(args, cfg)
>   File "train_net.py", line 53, in do_train
>     model = instantiate(cfg.model)
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in instantiate
>     cfg = {k: instantiate(v) for k, v in cfg.items()}
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in <dictcomp>
>     cfg = {k: instantiate(v) for k, v in cfg.items()}
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in instantiate
>     cfg = {k: instantiate(v) for k, v in cfg.items()}
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in <dictcomp>
>     cfg = {k: instantiate(v) for k, v in cfg.items()}
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 77, in instantiate
>     return cls(**cfg)
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/config/config.py", line 192, in wrapped
>     init_func(self, *args, **kwargs)
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/detectron2/modeling/roi_heads/box_head.py", line 49, in __init__
>     self._output_size = (input_shape.channels, input_shape.height, input_shape.width)
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/omegaconf/listconfig.py", line 181, in __getattr__
>     self._format_and_raise(
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
>     format_and_raise(
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
>     _raise(ex, cause)
>   File "/home/dmaidment/miniconda3/envs/tron/lib/python3.8/site-packages/omegaconf/_utils.py", line 771, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
> omegaconf.errors.ConfigAttributeError: ListConfig does not support attribute access
>     full_key: [channels]
>     object_type=list
>```

## Environment:
>```
> sys.platform           linux
> Python                 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
> numpy                  1.22.3
> detectron2             0.6
> Compiler               GCC 7.3
> CUDA compiler          not available
> DETECTRON2_ENV_MODULE  <not set>
> PyTorch                1.8.2
> PyTorch debug build    False
> GPU available          No: torch.cuda.is_available() == False
> Pillow                 9.0.1
> torchvision            0.9.2
> fvcore                 0.1.5.post20220512
> iopath                 0.1.9
> cv2                    Not found
> ---------------------  -----------------------------------------------------------------------------------
> PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 
>```

I'm aware that the environment is pretty sparse, this is just for basic dev, not that actual training.

**Comment by maidmentdaniel** [comment]
So, I solved the problem.
It turns out that the prebuilt installation of detectron installs `omegaconf==2.2.1` and downgrading to `omegaconf==2.1 `solves the problem

**Comment by ppwwyyxx** [comment]
Either downgrade omegaconf, or https://github.com/facebookresearch/detectron2/pull/4253 should fix it as well.

**Comment by ppwwyyxx** [comment]
Fixed by https://github.com/facebookresearch/detectron2/pull/4253
