### ISSUE TITLE
Colab session crashes while importing detectron2 what(): std::bad_alloc

### ISSUE THREAD

**Issue by jigsawcoder** [facebookresearch/detectron2#4259]
I am using detectron2 to train my custom dataset but whenever I try to import detecton2, my colab system crashes automatically. 

Environment used:

CUDA : 11.2

TORCH : 1.11.0+cu102 (I tried install installing torch for cuda 11.2 but didn't work)

DETECTRON2 : python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.10/index.html

When I tried to import the following : 
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.engine import DefaultTrainer

My Colab system crashes..

RUNTIME LOGS:

|Timestamp|Level|Message|
|---|---|---|
|May 23, 2022, 2:48:23 PM|WARNING|WARNING:root:kernel 003c06fd-57d8-416a-883c-d8a1e0a675da restarted|
|May 23, 2022, 2:48:23 PM|INFO|KernelRestarter: restarting kernel \(1/5), keep random ports|
|May 23, 2022, 2:48:20 PM|WARNING|  what\():  std::bad_alloc|
|May 23, 2022, 2:48:20 PM|WARNING|terminate called after throwing an instance of 'std::bad\_alloc'|
|May 23, 2022, 2:47:38 PM|INFO|Kernel restarted: 003c06fd-57d8-416a-883c-d8a1e0a675da|
|May 23, 2022, 2:46:15 PM|WARNING|WARNING:root:kernel 003c06fd-57d8-416a-883c-d8a1e0a675da restarted|
|May 23, 2022, 2:46:15 PM|INFO|KernelRestarter: restarting kernel \(1/5), keep random ports|
|May 23, 2022, 2:46:12 PM|WARNING|  what\():  std::bad_alloc|
|May 23, 2022, 2:46:12 PM|WARNING|terminate called after throwing an instance of 'std::bad\_alloc'|
|May 23, 2022, 2:44:42 PM|WARNING|WARNING:root:kernel 003c06fd-57d8-416a-883c-d8a1e0a675da restarted|
|May 23, 2022, 2:44:42 PM|INFO|KernelRestarter: restarting kernel \(1/5), keep random ports|
|May 23, 2022, 2:44:41 PM|WARNING|  what\():  std::bad_alloc|
|May 23, 2022, 2:44:41 PM|WARNING|terminate called after throwing an instance of 'std::bad\_alloc'|
|May 23, 2022, 2:41:30 PM|INFO|Adapting to protocol v5\.1 for kernel 003c06fd-57d8-416a-883c-d8a1e0a675da|
|May 23, 2022, 2:40:40 PM|INFO|Adapting to protocol v5\.1 for kernel 003c06fd-57d8-416a-883c-d8a1e0a675da|
|May 23, 2022, 2:40:39 PM|INFO|Kernel started: 003c06fd-57d8-416a-883c-d8a1e0a675da|
|May 23, 2022, 2:40:31 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation).|
|May 23, 2022, 2:40:31 PM|INFO|http://172\.28.0.2:9000/|
|May 23, 2022, 2:40:31 PM|INFO|The Jupyter Notebook is running at:|
|May 23, 2022, 2:40:31 PM|INFO|0 active kernels|
|May 23, 2022, 2:40:31 PM|INFO|Serving notebooks from local directory: /|
|May 23, 2022, 2:40:31 PM|INFO|google\.colab serverextension initialized.|
|May 23, 2022, 2:40:31 PM|WARNING|    	/root/\.jupyter/jupyter_notebook_config.json|
|May 23, 2022, 2:40:31 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation).|
|May 23, 2022, 2:40:31 PM|INFO|http://172\.28.0.12:9000/|
|May 23, 2022, 2:40:31 PM|INFO|The Jupyter Notebook is running at:|
|May 23, 2022, 2:40:31 PM|INFO|0 active kernels|
|May 23, 2022, 2:40:31 PM|INFO|Serving notebooks from local directory: /|
|May 23, 2022, 2:40:31 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter_notebook_config.json|
|May 23, 2022, 2:40:31 PM|INFO|google\.colab serverextension initialized.|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.d/panel-client-jupyter.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/root/\.jupyter/jupyter_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.d/panel-client-jupyter.json|
|May 23, 2022, 2:40:31 PM|WARNING|    	/etc/jupyter/jupyter\_notebook_config.json|
|May 23, 2022, 2:40:31 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook_cookie_secret|
|May 23, 2022, 2:40:31 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook_cookie_secret|

**Comment by ppwwyyxx** [comment]
The official colab works fine.

> CUDA : 11.2
TORCH : 1.11.0+cu102 (I tried install installing torch for cuda 11.2 but didn't work)
DETECTRON2 : python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.10/index.html

Torch versions don't match and therefore are not supposed to work at all.
