### ISSUE TITLE
How to see the architecture of a specific network, and how to see the outputs of intermediate layers?

### ISSUE THREAD

**Issue by jhonygiraldo** [facebookresearch/detectron2#426]
Hi and greetings,

I do not know if this is a silly question, but I would like to know if there is any way to see (or display) the specific architecture of, let's say Mask R-CNN with a specific backbone.

Also, is there any way to get the outputs of an intermediate layer in a network, let's say the previous layer to the output of Mask R-CNN? Thanks in advance.

**Comment by ppwwyyxx** [comment]
(1) no
(2) you can run the model until the layer you want. an example is like #5

**Comment by cpoptic** [comment]
@jhonygiraldo https://github.com/lutzroeder/netron is a great way to visualize a NN architecture

**Comment by jhonygiraldo** [comment]
@ppwwyyxx  and @cpoptic, thank you for your kind reply.
Best regards.

**Comment by Labaien96** [comment]
Any updates on this? Does anyone know how I can access intermediate layers on detecttron2? If it is not possible yet, are you considering it for the future?
