### ISSUE TITLE
Get features per detected object

### ISSUE THREAD

**Issue by drapado** [facebookresearch/detectron2#427]
Hi, I would like to get the feature vector prior to the classification step in Mask R-CNN per detected object. How could I do it?
Thanks!

**Comment by ppwwyyxx** [comment]
You can run the model until the layer you want. an example is like #5

**Comment by drapado** [comment]
Hi @ppwwyyxx, thanks for your answer!
However, doing just that is not enough as I still need to detect objects (with a mask) in an image. Therefore I need to associate the corresponding feature vector to the detected object in the image, which is the tricky part. Any idea? Thanks!

**Comment by ppwwyyxx** [comment]
You'll need to follow what the original code in `roi_heads.py` is doing in inference time so you know what layers to run until you get the features you want.
