### ISSUE TITLE
KeyError: "No object named 'PointRendMaskHead' found in 'ROI_MASK_HEAD' registry!"

### ISSUE THREAD

**Issue by wangxueping78** [facebookresearch/detectron2#4280]
![image](https://user-images.githubusercontent.com/43226404/170816961-c203ec31-f113-484d-b188-b9cc327a120f.png)

When I run PointRend' codes ,I got this error:KeyError: "No object named 'PointRendMaskHead' found in 'ROI_MASK_HEAD' registry!"   
Can you help me ?

**Comment by jieruyao49** [comment]
> ![image](https://user-images.githubusercontent.com/43226404/170816961-c203ec31-f113-484d-b188-b9cc327a120f.png)
> 
> When I run PointRend' codes ,I got this error:KeyError: "No object named 'PointRendMaskHead' found in 'ROI_MASK_HEAD' registry!" Can you help me ?

I have the same problem. Have you solved it？

**Comment by wangxueping78** [comment]
I re-created a virtual environment specifically for running pointrend, which solved the problem.
