### ISSUE TITLE
Model file size increased by a lot somewhere after release 0.6

### ISSUE THREAD

**Issue by MathijsNL** [facebookresearch/detectron2#4282]
1. Full runnable code or full changes you made:

You can use the [Colab notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) to reproduce.

2. What exact command you run:

Run the notebook, change the commit hash to release 0.6:
```
# Detectron 0.6 d1e04565d3bec8719335b88be9e9b961bf3ec464
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@d1e04565d3bec8719335b88be9e9b961bf3ec464'
```

Run for a few iterations and let the model save.

```
file_size = os.path.getsize('output/model_final.pth')
print(f"File Size is : {(file_size / 1024 / 1024):.2f}M")
>>> File Size is : 168.05M
```

Do the exact same thing with the latest commit hash that passed all tests:
```
# Detectron May 25, 2022 45b3fcea6e76bf7a351e54e01c7d6e1a3a0100a5
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@45b3fcea6e76bf7a351e54e01c7d6e1a3a0100a5'
```
After saving the model:

```
file_size = os.path.getsize('output/model_final.pth')
print(f"File Size is : {(file_size / 1024 / 1024):.2f}M")
>>> File Size is : 334.76M
```

## Expected behavior:

The expected behavior would be to get a model with file size around 168M instead of 334M.

I can't find anything in the commits from the release of 0.6 till now, so I don't know if something got reversed or that this is unwanted behavior.

**Comment by ppwwyyxx** [comment]
This might be due to https://github.com/facebookresearch/detectron2/pull/3628 and is an expected behavior: optimizer states should be saved but wasn't saved before.

**Comment by MathijsNL** [comment]
I searched the issues but didn't see this one in the list of PRs. Thanks for the clarification.
