### ISSUE TITLE
Target "torchscript_mask_rcnn" links to target "Python3::Python" but the   target was not found.  

### ISSUE THREAD

**Issue by Z-star1** [facebookresearch/detectron2#4304]
/Downloads/detectron2-main/tools/deploy/build$ cmake ..
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found OpenCV: /usr (found suitable version "3.2.0", minimum required is "3.2.0") 
-- Configuring done
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "torchscript_mask_rcnn" links to target "Python3::Python" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by Z-star1** [comment]
fuck

**Comment by ppwwyyxx** [comment]
The deployment example is accompanied with dockerfiles https://github.com/facebookresearch/detectron2/tree/main/docker where the example builds correctly (if not please file a bug). For ubuntu-like systems it requires `python3-dev` and a recent enough cmake according to the dockerfile. Users are responsible for figuring out how to install these on their own systems.

Also related to https://github.com/pytorch/vision/issues/5863. Seems like torchvision is going to remove this python dependency.

**Comment by vincedupuis** [comment]
I got the same error and I added the following line to CMakeLists.txt

find_package (Python3 COMPONENTS Interpreter Development)
