### ISSUE TITLE
No Predicted Masks in Keypoint R-CNN

### ISSUE THREAD

**Issue by Nyandwi** [facebookresearch/detectron2#4305]
Hi,

I wanted to visualize the outputs of Keypoint R-CNN, mainly visualizing predicted object masks(instance segmentation) and key points. But it seems that in the output of the Keypoint R-CNN predictor, `pred_masks` is not available.

## Instructions To Reproduce the Issue:

I am performing normal inference with [Keypoint R-CNN, R50 FPN](https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml).

1. Full runnable code or full changes you made:
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")
keypoint_predictor = DefaultPredictor(cfg)
```

2. What exact command you run:

When visualizing the output with `viz.draw_instance_predictions(outputs["instances"].to("cpu")).get_image()`, it works. I get the predicted objects boxes and keypoints but unfortunately not object masks.

I found the issue when I attempted to use `overlay_instances(*, boxes=None, labels=None, masks=None, keypoints=None, assigned_colors=None, alpha=0.5)` to draw the masks and keypoints since [viz.overlay_instances()](https://detectron2.readthedocs.io/en/latest/modules/utils.html#detectron2.utils.visualizer.Visualizer.overlay_instances) allows you to choose what you want to draw from the output.

Below is the function that I use to visualize the outputs with `iz.overlay_instances()`.

```
def make_inference_visualize_outputs(predictor, image):
  outputs = predictor(image)
  #boxes = outputs["instances"].pred_boxes
  keypoints = outputs["instances"].pred_keypoints
  masks = outputs["instances"].pred_masks

  # Visualize the output masks and keypoints

  viz = Visualizer(image[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TEST[0]), scale=1.0, instance_mode=ColorMode.SEGMENTATION)
  insta_viz = viz.overlay_instances(boxes=None, labels=None, masks=masks.to("cpu"), keypoints=keypoints.to("cpu")).get_image()
  cv2_imshow((insta_viz)[:, :, ::-1])
```

The function above works well when given boxes and keypoints, but with masks, it throws out the error that says `Cannot find field 'pred_masks' in the given Instances!`

Since I really want only the object masks and keypoints, I was wondering if the problem might be on my end or if the provided Keypoint R-CNN doesn't produce masks. Keypoint R-CNN being a modification of Mask R-CNN, I thought it might also provide people masks which would actually be cool for human pose tasks.

3. __Full logs__ or other relevant observations:

```
I also tried to use draw_and_connect_keypoints(keypoints) and it works but it only accepts keypoints for one object.

```

## Expected behavior:

Keypoint R-CNN does not provide object masks in the output of the predictor.

## Environment:

I am using Colab. Detectron2 is built from source.

Thank you! I have been enjoying Detectron2 :-)

**Comment by ppwwyyxx** [comment]
> if the provided Keypoint R-CNN doesn't produce masks

That's correct, so the behavior is expected.
