### ISSUE TITLE
The fraction of positives is not guaranteed in extreme situations.

### ISSUE THREAD

**Issue by PkuDavidGuan** [facebookresearch/detectron2#431]
I think the fraction of positive proposals may not be guaranteed in extreme situations in 
https://github.com/facebookresearch/detectron2/blob/5d098717a063507d80d8f80de44f61f91b97c91b/detectron2/modeling/sampling.py#L7

For example, given `num_samples=16`, `len(positive)=15` and `len(positive_fraction)=0.25`, subsample_labels will sample 4 positives and 1 negative, then the fraction of positives are 400% but not 25%.

Just a small bug.....

**Comment by ppwwyyxx** [comment]
This is expected behavior but should be documented more clearly.
