### ISSUE TITLE
benchmarking with comparison to yolov3

### ISSUE THREAD

**Issue by M-Younus** [facebookresearch/detectron2#432]

**Comment by ppwwyyxx** [comment]
I don't understand what this issue is about. As #215  said we do not support yolo.

**Comment by M-Younus** [comment]
nop just want to know the comparison of FPS and map etc.

**Comment by ppwwyyxx** [comment]
detectron2 does not provide yolov3 so it cannot benchmark it.

FPS for other models are provided already, although inference in pytorch is not the most optimal way to run a model.

**Comment by M-Younus** [comment]
> detectron2 does not provide yolov3 so it cannot benchmark it.
> 
> FPS for other models are provided already, although inference in pytorch is not the most optimal way to run a model.

right,get it.Thanks

**Comment by M-Younus** [comment]
> detectron2 does not provide yolov3 so it cannot benchmark it.
> 
> FPS for other models are provided already, although inference in pytorch is not the most optimal way to run a model.

Can you please suggest most optimum way,like is it onnx or anything else?
