### ISSUE TITLE
Increasing GPU memory usage even after 10000 iters

### ISSUE THREAD

**Issue by engharat** [facebookresearch/detectron2#433]
Hi,
From a previous reply I see that having an increase GPU memory allocation after some iterations is a normal behaviour - but I'm getting increasing GPU memory usage even after 10000 iterations, until I get CUDA out of memory error.
I'm working with iSAID instance segmentation dataset, I tried to use mask_rcnn_R_50_FPN_3x.yaml, mask_rcnn_R_50_FPN_1x.yaml and retinanet with no success. With mask rcnn I get the following behaviour:
memory consumption starts at 3gb, increasing to 5gb after few dozen of iters, then 7gb after 100-500 iters, and finally getting out of memory error at 3000-10000 iters, so I cannot do any training actually.
I tried to use the following modifications, without success (the dataset is made of 800x800 images patches, plus some lower resolution images):
cfg.DATALOADER.NUM_WORKERS = 1
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.MIN_SIZE_TRAIN = (800,)
cfg.MAX_SIZE_TRAIN = (800,)

The GPU is a TitanX 12gb, pytorch 1.13 and CUDA 10.
Edit: I tried also putting a torch_cuda_empty_cache call every few iterations, with no success: the training seem to use lesser gpu memory, but still ends up with oom error after some more iterations.

**Comment by ppwwyyxx** [comment]
An image will consume much more memory than others if it has a large number of instances.

**Comment by engharat** [comment]
Thank you for your reply. The issue is then on the peculiar feature of iSAID dataset: a huge number of small instances (cars) on some few images. Any suggestion on how to solve this issue? Is there any flag to put a limit to the number of instances for each image? Or could you suggest where to put a custom check to discard the minibatch/image if it has too many instances?

**Comment by ppwwyyxx** [comment]
Using a smaller `RPN.PRE_NMS_TOPK_TRAIN` and `RPN.POST_NMS_TOPK_TRAIN`, e.g., 200 each may help. If not I'll need you to fill out the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md) with full logs.

**Comment by engharat** [comment]
Unfortunately it did not fixed the issue. I will submit the full issue template with logs and example of code.

**Comment by ppwwyyxx** [comment]
Closing and continue in #438
