### ISSUE TITLE
AssertionError: ColorMode.IMAGE_BW requires segmentations using RetinaNet

### ISSUE THREAD

**Issue by Tinabr7** [facebookresearch/detectron2#434]
I'm trying to use RetinaNet for Graffiti detection using this tutorial: https://gilberttanner.com/blog/detectron-2-object-detection-with-pytorch

1. Included my own Dataset using register_coco_instances

2. Trained it using Config file retinanet_R_101_FPN_3x.yaml and pre-trained model weights (detectron2://ImageNetPretrained/MSRA/R-101.pkl) 
![image](https://user-images.githubusercontent.com/8765432/69906427-f921cf80-1377-11ea-8a95-6651bd5428b7.png)

![image](https://user-images.githubusercontent.com/8765432/69906431-fe7f1a00-1377-11ea-9d03-18184bcc16c0.png)

3. what you observed (including the full logs):
**Getting error** 
AssertionError: ColorMode.IMAGE_BW requires segmentations
![image](https://user-images.githubusercontent.com/8765432/69906420-e909f000-1377-11ea-8f0c-d35b04d89f42.png)

I was able to get visualizer work for Masked R-CNN config like the output below however I don't understand what's wrong here. I'm new to ML and Python. 
![image](https://user-images.githubusercontent.com/8765432/69906470-9b41b780-1378-11ea-92b6-6fc145ee9a24.png)

**Comment by ppwwyyxx** [comment]
RetinaNet does not do segmentation.
So you should not use `ColorMode.IMAGE_BW`.
