### ISSUE TITLE
How to extract data after inference

### ISSUE THREAD

**Issue by frostedtips-jpg** [facebookresearch/detectron2#436]
While doing inference on images, I am looking for a way to extract data from the API.

I trained on a custom dataset and I am doing an instance segmentation of coco type. Trying to get
- Pixel total of detected (class of my custom data)
- Position of each pixel in x,y associated with (class of my custom data)

I am looking to extract this in a JSON file.

**Comment by ppwwyyxx** [comment]
The model's [output format](https://detectron2.readthedocs.io/tutorials/models.html#model-output-format) already has all the information that you can extract.

**Comment by frostedtips-jpg** [comment]
Lets say I have an image with (person 98%, dog 99%, person 100%) as inference result.
I would like to get the mask data corresponding to the person class additionally to the total number of pixels in those masks and export it in a JSON file.

Is that possible with the actual output format ? I looked it up but I can't see the class/mask association through the dictionary.

Your help is appreciated.

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/models.html#model-output-format says, `['instances'].pred_masks` contains the masks and you can then count the pixels of the masks.

**Comment by frostedtips-jpg** [comment]
Yes, that's what I used, but in the case we have multiple masks, we can't separate them by classes. In my case, I can only get the pixels of all the masks at once, instead of lets say "person 24000 pixels, dog 2000 pixels"

I am working on a script that will extract the data in the case we find "person" in the label list, but I don't think it is the most efficient way to get the mask...

**Comment by ppwwyyxx** [comment]
You can know the class of each mask from `['instances'].pred_classes`. So you can count the pixel of different classes.

**Comment by frostedtips-jpg** [comment]
So in this case, I would count pixels this way ?

`np.count_nonzero(predictions.pred_masks)`

**Comment by ppwwyyxx** [comment]
`.pred_masks[i]` is a mask whose class is `.pred_classes[i]`. 

I explained the output format. What/How you want to compute from this output is unrelated to detectron2.
