### ISSUE TITLE
where should the coco dataset be placed

### ISSUE THREAD

**Issue by fadaishaitaiyang** [facebookresearch/detectron2#4360]
If I want to use ViTDet as a project, where should the coco dataset be placed?Many thanks for your help

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html:

> Detectron2 has builtin support for a few datasets. The datasets are assumed to exist in a directory specified by the environment variable DETECTRON2_DATASETS. Under this directory, detectron2 will look for datasets in the structure described below, if needed.
You can set the location for builtin datasets by export DETECTRON2_DATASETS=/path/to/datasets. If left unset, the default is ./datasets relative to your current working directory.

**Comment by yashika-git** [comment]
@ppwwyyxx, 

In reference to,

> You can set the location for builtin datasets by export DETECTRON2_DATASETS=/path/to/datasets. 

Might come across as an extremely naive question as I'm a beginner, 
Could you please tell where do I need to place this 'export DETECTRON2_DATASETS=/path/to/datasets' statement?

Thank You
