### ISSUE TITLE
build_model(cfg) vs trainer.model

### ISSUE THREAD

**Issue by yklose** [facebookresearch/detectron2#437]
I do not understand the difference between build_model(cfg) and trainer.model. I thought there is no difference between:
```
model = build_model(cfg)
DetectionCheckpointer(model).load("/.../.../output/model_final.pth")

evaluator = COCOEvaluator("testset_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "testset_val")
inference_on_dataset(model, val_loader, evaluator)
```
and 
```
evaluator = COCOEvaluator("testset_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "testset_val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```

But when comparing the results on a super small subset, the evaluation metrics are not the same. 

I already checked the *cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST* and the load directory is the right directory where the trainer saves the model. 

Any suggestions why this is happening?

**Comment by ppwwyyxx** [comment]
It was not clear to me what you did (e.g. how did you get the trainer). 
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by yklose** [comment]
I followed the Colab tutorial to get my trainer:
```
cfg = get_cfg()
cfg.merge_from_file(PATH + config_path)
cfg.DATASETS.TRAIN = ("testset_val",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = weights_path
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 5000   
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64 t
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 5  # only has 5 classes
cfg.MODEL.MASK_ON = False

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```
when this model is finished, it saves a the weights into a file ```/.../.../ouput/model_final.pth```. Now to evaluate the model, the Colab suggests to use this:
```
evaluator = COCOEvaluator("testset_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "testset_val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```
This works fine and I get a result. However it should also work the same if I load the model directly from the output as shown below:
```
model = build_model(cfg)
DetectionCheckpointer(model).load("/.../.../output/model_final.pth")
```
and again for evaluation:
```
evaluator = COCOEvaluator("testset_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "testset_val")
inference_on_dataset(model, val_loader, evaluator)
```
with "model" instead of "trainer.model".

Here is my problem. The results are not the same, even though in my opinion they should be. Does this make sense?

**Comment by ppwwyyxx** [comment]
I added 
```
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer
model = build_model(cfg)
DetectionCheckpointer(model).load("output/model_final.pth")
evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "balloon_val")
inference_on_dataset(model, val_loader, evaluator)
```
to the colab tutorial and it produces the same results as `trainer.model`.


To save some time, please include instructions to reproduce your issue

**Comment by ppwwyyxx** [comment]
Closing as it's not reproducible.
