### ISSUE TITLE
polygon is incomplete when drawing annotations with Visualizer

### ISSUE THREAD

**Issue by andreaceruti** [facebookresearch/detectron2#4378]
## Instructions To Reproduce the Issue:

Just register the dataset with coco annotations as in the detectron2 tutorial and visualize the dataset sample.
This is the image I am using as example, save it as "124.png" to match the json file that I have provided following to reproduce the visualization. 

![124](https://user-images.githubusercontent.com/44469014/177358492-520bd710-9bda-4c51-baf6-2c67645a2e2a.png)

`{
  "licenses": [
    {
      "name": "",
      "id": 0,
      "url": ""
    }
  ],
  "info": {
    "contributor": "",
    "date_created": "",
    "description": "",
    "url": "",
    "version": "",
    "year": ""
  },
  "categories": [
    {
      "id": 3,
      "name": "cabinet",
      "supercategory": ""
    },
    {
      "id": 4,
      "name": "ceiling",
      "supercategory": ""
    },
    {
      "id": 5,
      "name": "chair",
      "supercategory": ""
    },
    {
      "id": 7,
      "name": "counter",
      "supercategory": ""
    },
    {
      "id": 12,
      "name": "garbage bin",
      "supercategory": ""
    },
    {
      "id": 15,
      "name": "paper",
      "supercategory": ""
    },
    {
      "id": 17,
      "name": "refridgerator",
      "supercategory": ""
    },
    {
      "id": 19,
      "name": "table",
      "supercategory": ""
    },
    {
      "id": 24,
      "name": "sink",
      "supercategory": ""
    },
    {
      "id": 26,
      "name": "box",
      "supercategory": ""
    },
    {
      "id": 28,
      "name": "door",
      "supercategory": ""
    },
    {
      "id": 36,
      "name": "desk",
      "supercategory": ""
    },
    {
      "id": 42,
      "name": "shelves",
      "supercategory": ""
    },
    {
      "id": 49,
      "name": "monitor",
      "supercategory": ""
    },
    {
      "id": 55,
      "name": "bag",
      "supercategory": ""
    },
    {
      "id": 59,
      "name": "window",
      "supercategory": ""
    },
    {
      "id": 64,
      "name": "picture",
      "supercategory": ""
    },
    {
      "id": 80,
      "name": "blinds",
      "supercategory": ""
    },
    {
      "id": 83,
      "name": "sofa",
      "supercategory": ""
    },
    {
      "id": 85,
      "name": "books",
      "supercategory": ""
    },
    {
      "id": 88,
      "name": "bookshelf",
      "supercategory": ""
    },
    {
      "id": 89,
      "name": "curtain",
      "supercategory": ""
    },
    {
      "id": 119,
      "name": "pillow",
      "supercategory": ""
    },
    {
      "id": 122,
      "name": "mirror",
      "supercategory": ""
    },
    {
      "id": 135,
      "name": "towel",
      "supercategory": ""
    },
    {
      "id": 141,
      "name": "clothes",
      "supercategory": ""
    },
    {
      "id": 143,
      "name": "floor mat",
      "supercategory": ""
    },
    {
      "id": 144,
      "name": "lamp",
      "supercategory": ""
    },
    {
      "id": 157,
      "name": "bed",
      "supercategory": ""
    },
    {
      "id": 158,
      "name": "night stand",
      "supercategory": ""
    },
    {
      "id": 169,
      "name": "dresser",
      "supercategory": ""
    },
    {
      "id": 172,
      "name": "television",
      "supercategory": ""
    },
    {
      "id": 331,
      "name": "person",
      "supercategory": ""
    }
  ],
  "images": [
    {
      "id": 124,
      "width": 620,
      "height": 460,
      "file_name": "124.png",
      "license": 0,
      "flickr_url": "",
      "coco_url": "",
      "date_captured": 0
    }
  ],
  "annotations": [
    {
      "segmentation": [
        [
          99,
          300,
          98,
          301,
          97,
          301,
          96,
          302,
          95,
          302,
          94,
          303,
          93,
          303,
          92,
          304,
          91,
          304,
          90,
          305,
          89,
          305,
          88,
          306,
          87,
          306,
          85,
          308,
          84,
          308,
          83,
          309,
          82,
          309,
          81,
          310,
          80,
          310,
          79,
          311,
          78,
          311,
          77,
          312,
          76,
          312,
          75,
          313,
          74,
          313,
          73,
          314,
          72,
          314,
          71,
          315,
          70,
          315,
          68,
          317,
          67,
          317,
          67,
          328,
          68,
          329,
          68,
          342,
          69,
          343,
          69,
          355,
          70,
          356,
          70,
          368,
          71,
          369,
          71,
          382,
          72,
          383,
          72,
          395,
          73,
          396,
          73,
          408,
          74,
          409,
          74,
          421,
          75,
          422,
          75,
          435,
          76,
          436,
          76,
          448,
          77,
          449,
          77,
          459,
          619,
          459,
          619,
          378,
          618,
          377,
          618,
          359,
          614,
          359,
          613,
          358,
          610,
          358,
          609,
          359,
          608,
          359,
          607,
          358,
          571,
          358,
          569,
          356,
          569,
          355,
          568,
          354,
          568,
          353,
          567,
          352,
          567,
          351,
          566,
          350,
          566,
          349,
          565,
          348,
          565,
          347,
          564,
          346,
          564,
          345,
          563,
          344,
          563,
          342,
          562,
          341,
          527,
          341,
          527,
          362,
          526,
          363,
          525,
          362,
          521,
          362,
          520,
          361,
          515,
          361,
          514,
          360,
          510,
          360,
          509,
          359,
          505,
          359,
          504,
          358,
          499,
          358,
          498,
          357,
          494,
          357,
          493,
          356,
          489,
          356,
          488,
          355,
          483,
          355,
          482,
          354,
          478,
          354,
          477,
          353,
          472,
          353,
          471,
          352,
          467,
          352,
          466,
          351,
          462,
          351,
          461,
          350,
          453,
          350,
          452,
          349,
          443,
          349,
          442,
          348,
          442,
          347,
          441,
          347,
          439,
          345,
          439,
          344,
          438,
          343,
          438,
          341,
          437,
          340,
          437,
          339,
          436,
          338,
          436,
          337,
          435,
          336,
          428,
          336,
          427,
          335,
          420,
          335,
          419,
          334,
          412,
          334,
          411,
          333,
          404,
          333,
          403,
          332,
          377,
          332,
          376,
          331,
          376,
          329,
          373,
          329,
          372,
          328,
          363,
          328,
          362,
          327,
          354,
          327,
          353,
          326,
          346,
          326,
          345,
          325,
          342,
          325,
          341,
          324,
          334,
          324,
          333,
          323,
          326,
          323,
          325,
          322,
          306,
          322,
          305,
          323,
          292,
          323,
          291,
          324,
          290,
          324,
          289,
          323,
          283,
          323,
          282,
          322,
          276,
          322,
          275,
          321,
          269,
          321,
          268,
          320,
          261,
          320,
          261,
          322,
          260,
          323,
          259,
          322,
          254,
          322,
          253,
          321,
          247,
          321,
          246,
          320,
          241,
          320,
          240,
          319,
          222,
          319,
          221,
          318,
          220,
          318,
          220,
          319,
          219,
          320,
          199,
          320,
          198,
          319,
          198,
          318,
          197,
          318,
          196,
          317,
          171,
          317,
          170,
          316,
          169,
          316,
          168,
          317,
          167,
          317,
          166,
          316,
          146,
          316,
          145,
          315,
          143,
          315,
          143,
          316,
          142,
          317,
          141,
          317,
          140,
          316,
          126,
          316,
          125,
          315,
          123,
          315,
          121,
          313,
          121,
          307,
          120,
          306,
          120,
          302,
          119,
          301,
          110,
          301,
          109,
          300
        ]
      ],
      "area": 70585,
      "iscrowd": 0,
      "image_id": 124,
      "bbox": [
        67,
        300,
        553,
        160
      ],
      "category_id": 36,
      "id": 1
    },
    {
      "segmentation": [
        [
          576,
          269,
          575,
          270,
          575,
          287,
          574,
          288,
          574,
          304,
          573,
          305,
          573,
          321,
          572,
          322,
          572,
          339,
          571,
          340,
          571,
          355,
          581,
          355,
          582,
          356,
          594,
          356,
          595,
          357,
          607,
          357,
          608,
          358,
          609,
          358,
          609,
          347,
          610,
          346,
          610,
          333,
          611,
          332,
          611,
          320,
          612,
          319,
          612,
          307,
          613,
          306,
          613,
          293,
          614,
          292,
          614,
          280,
          615,
          279,
          601,
          279,
          600,
          280,
          598,
          278,
          598,
          276,
          597,
          275,
          597,
          272,
          596,
          271,
          596,
          270,
          595,
          270,
          594,
          269
        ]
      ],
      "area": 3341,
      "iscrowd": 0,
      "image_id": 124,
      "bbox": [
        571,
        269,
        45,
        90
      ],
      "category_id": 26,
      "id": 2
    }
  ]
}`

And this is the image I see with your Visualizer
![Screenshot from 2022-07-05 17-06-28](https://user-images.githubusercontent.com/44469014/177359425-a59f2b6c-04b2-4ef6-b608-9e67118f1f87.png)
The image is cropped and does not match the original dimension, anyway you can see that at bottom right the mask is not complete. And this visualization problem is repeated trough all my images, not for all objects, but just the objects that are on the side of the images.

## Expected behavior:

I expect to see an image as this. I have used cv2.drawContours loading contours from json file in this way:
```
for i, ann in enumerate(json_anns["annotations"]):
     segs = ann["segmentation"]
     cv2.drawContours(image, segs, -1, (0,255,0), 3)
```

![example](https://user-images.githubusercontent.com/44469014/177360137-6d6d20d4-15b2-43b7-8d7d-eaf2bcdd7b70.png)

with all the mask that should be filled

## Environment:

Google Colab and last version of detectron2

**Comment by Soulaimene** [comment]
That would be better if you provide your "Detectron's Visualizer code"

**Comment by andreaceruti** [comment]
@Soulaimene there was a problem in the annotations
