### ISSUE TITLE
Regarding detectron2 handling the federated nature of LVIS

### ISSUE THREAD

**Issue by joaqo** [facebookresearch/detectron2#439]
Hi, I've been training some things with detectron2 and have had a really really good experience with it. I think this is going to be my go to repo for a long time when training detection models. Thanks a lot for this!

At the moment though, I am trying some more unconventional training jobs and a question popped up when working with LVIS. The main question I have is: Do the LVIS trained models in the model zoo have any consideration for the federated nature of LVIS? I've been searching the codebase for mentions of `not_exhaustive_category_ids` and `neg_category_ids`, to see how detectron manages this but I think that apart from just adding them to the records in [lvis.py](https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/lvis.py) they're largely ignored.

If I understand correctly, you'd need to take special consideration with your training when using federated datasets as pictures are not exhaustively labeled for all categories on all pictures, so if you don't take this into account when training you'll have lots of objects unlabeled in lots of pictures which the model will interpret as background and make training erratic I think.

Am I missing something? Am I misunderstanding something about how you trained your LVIS models?

---

On a separate note, and please feel free to ignore this part, I am asking this because I want to train a network using some categories from COCO (as it has a huge amount of labeled instances) and one category from LVIS (because it isn't present in COCO) and I was thinking of the best way to merge these two datasets.

Currently I think I'll just make datasampler that will form batches that consist exclusively of COCO annotations or LVIS annotations, and dynamically freeze the roi head layer of the category missing from the batch. So when using a COCO batch I'll freeze the LVIS category roi head layer as it won't be labeled, and viceversa for an LVIS batch. This way sounds too complicated though, am I overthinking this?

Again, thanks for the awesome repo!

**Comment by ppwwyyxx** [comment]
You're right that these baselines did not apply any special treatment to non-exhaustively labeled images.

**Comment by joaqo** [comment]
Gotcha, thanks. This means that the current checkpoint is kind of suboptimal due to all the conflicting labels the model is receiving right?

**Comment by rbgirshick** [comment]
That's correct. The provided LVIS models are simple baselines and it should be possible to improve upon them in many ways. You may be interested to read Appendix B of https://arxiv.org/abs/1908.03195 for more details. The tech reports that describe the methods submitted to the recent LVIS Challenge at ICCV 2019 are also available at https://www.lvisdataset.org/challenge (click the team names on the leaderboard for the report PDFs). Some of these methods contain special treatment for non-exhaustive labeling.

**Comment by joaqo** [comment]
Sweet, there are some great ideas in those papers! Thanks!
