### ISSUE TITLE
Getting issue while importing detectron2.export.api.Caffe2Tracer

### ISSUE THREAD

**Issue by vivekkaushik1992** [facebookresearch/detectron2#4398]
I am importing Caffe2Tracer from detectron2.export.api.Caffe2Tracer. In document old version format is mentioned and do correct that.

Once importing this, Getting Caffe2.porto "metanet_pb2" not found. 

Can you share proper instruction to follow to export ONNX model from Detectron2@v0.6.

Instructions To Reproduce the Issue:

1> Install latest Detectron2
2>  Import detectron2.export.api.Caffe2Tracer

import module not found " metanet_pb2" in " caffe2.porto "

I think's there is some issue with incompatibility of Torch version and Detectron version.

**Comment by tintn** [comment]
With Pytorch version `1.12.0` installed with conda, the same error occurs when running:
```
from caffe2.proto import caffe2_pb2
```
I think it's the problem with PyTorch, not Detectron2.

Downgrading PyTorch to `1.10.1` fixed the error for me

**Comment by ppwwyyxx** [comment]
Caffe2 is no longer supported by latest pytorch.
