### ISSUE TITLE
Some questions on ViTDet

### ISSUE THREAD

**Issue by xyupeng** [facebookresearch/detectron2#4408]
Hi there,
Thanks for the great work of ViTDet! I encountered some problems when I tried to reproduce:

1. Pre-training: pre-training seems to be a crucial part, but I didn't find how many epochs you pre-train MAE models in the paper? And could you please elaborate a bit more about the pre-trained model used in the code, e.g., where does the model `detectron2://ImageNetPretrained/MAE/mae_pretrain_vit_base.pth` come from? What is the url and local path for detectron2 to download this model? And is it the state_dict of [MaskedAutoencoderViT](https://github.com/facebookresearch/mae/blob/main/models_mae.py)?

2. Why is the [residual_block_indexes](https://github.com/facebookresearch/detectron2/blob/main/configs/common/models/mask_rcnn_vitdet.py) empty? In my understanding, it should correspond to global propagation blocks? Or the config of global propagation blocks is placed somewhere else? Please tell me if I miss it!

Sorry for so many questions proposed! But I think are the key points and hope to get some advice!

**Comment by CarlBhy** [comment]
The initial weight ''detectron2://ImageNetPretrained/MAE/mae_pretrain_vit_base.pth'' provided by detectron2 was pretrained on MAE (base), thus it has the same state_dict to MAE. For paths of downloaded initial weights, you could use "locate detectron2://ImageNetPretrained/MAE/mae_pretrain_vit_base.pth" (/home/usr/.torch/iopath_cache/detectron2/ImageNetPretrained/MAE/mae_pretrain_vit_base.pth) to find it in ubuntu.

**Comment by CarlBhy** [comment]
Want to help you, I wish you success!
