### ISSUE TITLE
How do I test a trained tridentnet model?

### ISSUE THREAD

**Issue by Hondlus** [facebookresearch/detectron2#442]

**Comment by ppwwyyxx** [comment]
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=Vk4gID50K03a

**Comment by Hondlus** [comment]
> https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=Vk4gID50K03a

I have trained a tridentnet model. How can I test the model mAP on my own server Ubuntu16.04?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/tree/master/projects/TridentNet/#evaluation
