### ISSUE TITLE
Mesh R-CNN implementation

### ISSUE THREAD

**Issue by automata** [facebookresearch/detectron2#443]
I noticed a "coming soon" on Mesh R-CNN project. Is there any ETA on it?

**Comment by gkioxari** [comment]
Our goal is to release Mesh R-CNN and pytorch3d (our 3D deep learning library) by the end of December.

**Comment by automata** [comment]
@gkioxari thanks, looking forward to it. Closing this one for now.

**Comment by automata** [comment]
@gkioxari any news? Thanks in advance!

**Comment by zimenglan-sysu-512** [comment]
any update? thanks.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/meshrcnn
