### ISSUE TITLE
Check number of keypoints in COCOEvaluator or support NUM_KEYPOINTS != 17.

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#445]
## 🚀 Feature
Check number of keypoints in COCOEvaluator or support *NUM_KEYPOINTS != 17*.

## Motivation

When using data with *NUM_KEYPOINTS != 17* (e.g. *NUM_KEYPOINTS=20*) the following error is raised.
```
detectron2_1  | Traceback (most recent call last):
detectron2_1  |   File "/opt/project/evaluate_model.py", line 33, in <module>
detectron2_1  |     inference_on_dataset(trainer.model, val_loader, evaluator)
detectron2_1  |   File "/detectron2_repo/detectron2/evaluation/evaluator.py", line 153, in inference_on_dataset
detectron2_1  |     results = evaluator.evaluate()
detectron2_1  |   File "/detectron2_repo/detectron2/evaluation/coco_evaluation.py", line 129, in evaluate
detectron2_1  |     self._eval_predictions(set(self._tasks))
detectron2_1  |   File "/detectron2_repo/detectron2/evaluation/coco_evaluation.py", line 166, in _eval_predictions
detectron2_1  |     if len(self._coco_results) > 0
detectron2_1  |   File "/detectron2_repo/detectron2/evaluation/coco_evaluation.py", line 473, in _evaluate_predictions_on_coco
detectron2_1  |     coco_eval.evaluate()
detectron2_1  |   File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 149, in evaluate
detectron2_1  |     for imgId in p.imgIds
detectron2_1  |   File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 150, in <dictcomp>
detectron2_1  |     for catId in catIds}
detectron2_1  |   File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 229, in computeOks
detectron2_1  |     e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
detectron2_1  | ValueError: operands could not be broadcast together with shapes (20,) (17,) ****
```

## Pitch

The easiest solution is to check for the number of keypoints in *COCOEvaluator._tasks_from_config*:

```
...
if cfg.MODEL.KEYPOINT_ON and cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS == 17:
    tasks = tasks + ("keypoints",)
...
```
However, I am not sure how to best handle the situation. Possible solutions:
* Raise a more meaningful error.
* Do not evaluate keypoints and issue a warning.
* Do not evaluate keypoints.
* Fix evaluation so that it supports *NUM_KEYPOINTS != 17*.

**Comment by rbgirshick** [comment]
Evaluation should work for `NUM_KEYPOINTS != 17` if `TEST.KEYPOINT_OKS_SIGMAS` has length of `NUM_KEYPOINTS`. These "sigma" values are required by the definition of keypoint AP; for more information see http://cocodataset.org/#keypoints-eval.

Given this, I think the best solution is to provide an informative error message telling the user that these sigma values must be specified and providing a pointer to the COCO keypoint AP documentation.

**Comment by maxfrei750** [comment]
Mr. Girshick himself!

![Silently Fangirling](https://em.wattpad.com/a90d3a112b3fe1bd924a9e145a856ed14c8c483a/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f2d4562352d422d4530434b3172673d3d2d3536333932353637352e3135323733353037616632313138356638393137383336363738302e676966?s=fit&w=720&h=720)

😄  Thanks for the quick reply. I'll prepare a small PR.
