### ISSUE TITLE
When does the Detectron2go be released?

### ISSUE THREAD

**Issue by pwllr** [facebookresearch/detectron2#448]
Hello, I want to use the detectron2 in C++ on Windows, do you have the plan to Implementing related interfaces？And does the Detectron2go has related function to do that? When dose the detectron2go released?

**Comment by reneschulte** [comment]
I'd be interested as well. It was mentioned in another thread that it will be released in November. Either we missed it or it did not happen in November. Any ETA?

**Comment by gabrielebaris** [comment]
Hi, I would be interested too. Any news?

**Comment by shuxp** [comment]
any news about detectron2go?

**Comment by xiaozhaxie777** [comment]
any news？

**Comment by tensorflower** [comment]
any news?

**Comment by dragen1860** [comment]
Still a long way to go.

**Comment by ppwwyyxx** [comment]
Exporting and running a model in caffe2 is already open source a few weeks ago.
The only other feature we currently plan to open source from detectron2go is efficient FBNet-based models, tracked in #696. So closing this issue to avoid duplication.
