### ISSUE TITLE
How to setup the gup number for my training?

### ISSUE THREAD

**Issue by davidqing2000** [facebookresearch/detectron2#449]
I write a code for training with my dataset.

Can I setup the gup number with object from function-'get_cfg()'? 

for example:

cfg = get_cfg()

cfg.GPU_NUM=XXXX

cfg.DATASETS.TRAIN = ("mousetrain",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 4
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02

**Comment by ppwwyyxx** [comment]
It is determined when you call `launch`. See `train_net.py`.
