### ISSUE TITLE
How could I convert torchvision formatted ResNet weight into the ".pkl" format?

### ISSUE THREAD

**Issue by jackroos** [facebookresearch/detectron2#450]
## ❓ Questions and Help

Hi,

I want to load pre-trained ResNet weight of my own (torchvision ".pth" format) and use detectron2 to do downstream tasks finetuning (e.g., COCO detection), how could I do that since I notice that the pre-trained format of detectron2 is ".pkl"? Thanks! 

(Example of torchvision formatted weight: https://download.pytorch.org/models/resnet50-19c8e357.pth)

**Comment by ppwwyyxx** [comment]
We support pth weights as well.
The weights are mappings from names to tensors, and in detectron2 we use different names from torchvision, there are also different definition of "resnet" that are not equivalent. If you're careful enough in the conversion you can use torchvision weights in detectron2.

**Comment by jackroos** [comment]
Got it! Thanks! I would try to convert the weights.

**Comment by ppwwyyxx** [comment]
Instructions to use torchvision resnets are provided in 32570b767e1b69516c58734fe6cc46005bab2aae

**Comment by jackroos** [comment]
@ppwwyyxx Thanks!
