### ISSUE TITLE
RandomBrightness (Bug?)

### ISSUE THREAD

**Issue by Atotem** [facebookresearch/detectron2#4546]
https://github.com/facebookresearch/detectron2/blob/0703e08a5f589f7503a3fbfce41309c80204eec8/detectron2/data/transforms/augmentation_impl.py#L556

Why would you ask 'image' as an argument and do nothing with it?

**Comment by kretes** [comment]
It seems to me that this is not a bug. This method returns an instance of `BlendTransform` and this is the real transformation (see https://github.com/facebookresearch/fvcore/blob/main/fvcore/transforms/transform.py#L811) - just for creating the definition of the transformation - the actual image is not used, it is here, as this is the common API.

See another example https://github.com/facebookresearch/detectron2/blob/0703e08a5f589f7503a3fbfce41309c80204eec8/detectron2/data/transforms/augmentation_impl.py#L588 - where the argument `image` is just used for assering the shape

**Comment by satpalsr** [comment]
Hey @kretes, how should this be used with a trainer?
Like, `cfg.INPUT.RANDOM_LIGHTING = True` should work?

**Comment by Atotem** [comment]
Hi @kretes , I tried to replicate the official tutorial for data augmentation (@satpalsr ): https://github.com/facebookresearch/detectron2/blob/main/docs/tutorials/augmentation.md

But got several errors. For the case of RandomContrast() for example, I was getting one value, and I think it was because one of the arguments is the average of the whole picture: https://github.com/facebookresearch/detectron2/blob/0703e08a5f589f7503a3fbfce41309c80204eec8/detectron2/data/transforms/augmentation_impl.py#L530
