### ISSUE TITLE
ValueError: Failed to use mask_format=='polygon' from the given annotations!

### ISSUE THREAD

**Issue by 15024287710Jackson** [facebookresearch/detectron2#4548]
File "/root/miniconda3/envs/detectronTwoEth/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/detectronTwoEth/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/root/autodl-tmp/code/detectron2/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/root/autodl-tmp/code/detectron2/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/root/autodl-tmp/code/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/root/autodl-tmp/code/detectron2/detectron2/data/dataset_mapper.py", line 189, in __call__
    self._transform_annotations(dataset_dict, transforms, image_shape)
  File "/root/autodl-tmp/code/detectron2/detectron2/data/dataset_mapper.py", line 131, in _transform_annotations
    instances = utils.annotations_to_instances(
  File "/root/autodl-tmp/code/detectron2/detectron2/data/detection_utils.py", line 405, in annotations_to_instances
    raise ValueError(
ValueError: Failed to use mask_format=='polygon' from the given annotations!

When I train with Fashionpedia whose segmentation is birmask, I do not how to solve the problem.  

Can someone help me ?

![image](https://user-images.githubusercontent.com/42542657/190843883-2661db09-a810-42a9-9f62-095d1d9a6e3c.png)

**Comment by owardlaw** [comment]
What are you using to label your images?

**Comment by 15024287710Jackson** [comment]
Dear, I just use the dataset called Fashionpedia, Here is Link : https://github.com/cvdfoundation/fashionpedia
![image](https://user-images.githubusercontent.com/42542657/190893572-1179eb89-a58a-4075-bb86-a9387983456c.png)
Some annotations of segmentation use polygon format, and the other annotations of segmentation use RLE format. I want know how I can transfer the RLE format to the polygon format.

**Comment by ppwwyyxx** [comment]
Please show full log as the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) asked for.

**Comment by owardlaw** [comment]
@15024287710Jackson 

I label my data with labelme, 'pip install labelme'. 



`# function for data reading
def get_data_dicts(directory, classes):
    dataset_dicts = []
    for filename in [file for file in os.listdir(directory) if file.endswith('.json')]:
        json_file = os.path.join(directory, filename)
        with open(json_file) as f:
            img_anns = json.load(f)

        record = {}
        
        filename = os.path.join(directory, img_anns["imagePath"])
        
        record["file_name"] = filename
        annos = img_anns["shapes"]
        record["height"] = img_anns["imageHeight"]
        record["width"] = img_anns["imageWidth"]

        objs = []
        for anno in annos:
            px = [a[0] for a in anno['points']] # x coord
            py = [a[1] for a in anno['points']] # y-coord
            poly = [(x, y) for x, y in zip(px, py)] # poly for segmentation
            poly = [p for x in poly for p in x]

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": classes.index(anno['label']),
                "iscrowd": 0
            }
            
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts

# Define classes 
classes = ['X', 'X']

# Path to dir where test and train datasets are stored
data_path = './XXXXX'

# Looping through files in test/train dirs
for d in ["train", "test"]:
    DatasetCatalog.register(
        "category_" + d, 
        lambda d=d: get_data_dicts(data_path+d, classes)
    )
    MetadataCatalog.get("category_" + d).set(thing_classes=classes)

microcontroller_metadata = MetadataCatalog.get("category_train")`

**Comment by 15024287710Jackson** [comment]
@ppwwyyxx

**Comment by 15024287710Jackson** [comment]
I copy the wrong setting for you. 

I does not add cfg.INPUT.MASK_FORMAT='bitmask' when I train the model.

**Comment by ppwwyyxx** [comment]
Detectron2 does not automatically turn RLE into polygons because there isn't an accurate implementation that can do this. If you must, https://github.com/facebookresearch/detectron2/blob/7c2c8fb168a2093ce06a531c1208fba48d2984ec/detectron2/utils/visualizer.py#L119-L136 this function can be a reference so you can do the conversion yourself. But it's inaccurate.

If your input contains RLE annotations it's recommended to use `MASK_FORMAT='bitmask'`.
