### ISSUE TITLE
make `config.compat` more moduar and expandable (by registring new versions of cfg as defined by the user)

### ISSUE THREAD

**Issue by bendidi** [facebookresearch/detectron2#455]
## 🚀 Feature

The current cfg versioning is kind of hardcoded, and it would be nice if it can more modular as the rest of the framework.

I'll be happy to make a PR, if you think it's pertinent

**Comment by ppwwyyxx** [comment]
What does it mean to make it "more modular"? What changes do you expect?

**Comment by rbgirshick** [comment]
The config system is modular to some extent in the sense that projects using d2 as a library can extend the config in a project-specific fashion. Does this address what you are thinking about?

For example see:
https://github.com/facebookresearch/detectron2/blob/master/projects/TensorMask/train_net.py#L31-L32
https://github.com/facebookresearch/detectron2/blob/master/projects/TensorMask/tensormask/config.py#L7-L50

**Comment by bendidi** [comment]
> The config system is modular to some extent in the sense that projects using d2 as a library can extend the config in a project-specific fashion. Does this address what you are thinking about?

I'm not only trying to extend my project using d2 as a library but also to keep my own private compatibility registry of that extension.

a simple example is loading and using models from `maskrcnn-benchmark`, provided a config (`config.yaml`) and a model (`model_final.pth`), my idea is to add a `VERSION: 1.5` in the `config.yaml` file and then register a new compat classes in the config registry (`ConvertV1_5`).

this would allow users to keep their own backward compatibility just by expanding the compat of detectron2 and not having to make their own.

and it can even be useful for future dev and versions in detectron2
thanks !

**Comment by ppwwyyxx** [comment]
The `config.compat` module is based on the incremental increase of version number. It sounds like allowing arbitrary user-specific version number might make it too complicated so we're likely not going to add it. To maintain compatibility for your project, you can implement a similar functionality that converts existing configs.

**Comment by bendidi** [comment]
fair enough, thanks for the reply :)
