### ISSUE TITLE
ModuleNotFoundError: No module named 'fvcore.common.registry'

### ISSUE THREAD

**Issue by RUiSss** [facebookresearch/detectron2#458]
1、what exact command you run: 
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml  --input 0.jpg 3.jpg --output /home/amax/iKang/dsr/Project/det2/output [--other-options]  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.p
```
2. what you observed (including the full logs):
```
Traceback (most recent call last):
  File "demo/demo.py", line 16, in <module>
    from predictor import VisualizationDemo
  File "/home/amax/iKang/dsr/Project/det2/demo/predictor.py", line 10, in <module>
    from detectron2.engine.defaults import DefaultPredictor
  File "/home/amax/iKang/dsr/Project/det2/detectron2/engine/__init__.py", line 12, in <module>
    from .defaults import *
  File "/home/amax/iKang/dsr/Project/det2/detectron2/engine/defaults.py", line 34, in <module>
    from detectron2.modeling import build_model
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/__init__.py", line 6, in <module>
    from .anchor_generator import build_anchor_generator, ANCHOR_GENERATOR_REGISTRY
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/anchor_generator.py", line 10, in <module>
    from detectron2.utils.registry import Registry
  File "/home/amax/iKang/dsr/Project/det2/detectron2/utils/registry.py", line 6, in <module>
    from fvcore.common.registry import Registry  # noqa
ModuleNotFoundError: No module named 'fvcore.common.registry'

```

**Comment by ppwwyyxx** [comment]
You need to update to latest fvcore.

**Comment by RUiSss** [comment]
Thank you very much for your answer. May I know your fvcore version?

**Comment by ppwwyyxx** [comment]
You should use the latest fvcore by `pip install -U 'git+https://github.com/facebookresearch/fvcore'`.

**Comment by RUiSss** [comment]
Thank you very much. The problem has been solved :)

**Comment by RUiSss** [comment]
Hello, are you a Chinese? I have some little problems , I hope I can get your help！may I write with chinese？
 1、what exact command you run:
 python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml&nbsp; --input 0.jpg 3.jpg --output /home/amax/iKang/dsr/Project/det2/output --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
 2、what you observed (including the full logs):
 Traceback (most recent call last):
&nbsp; File "demo/demo.py", line 13, in <module&gt;
&nbsp;&nbsp;&nbsp; from detectron2.data.detection_utils import read_image
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/data/__init__.py", line 4, in <module&gt;
&nbsp;&nbsp;&nbsp; from .build import (
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/data/build.py", line 13, in <module&gt;
&nbsp;&nbsp;&nbsp; from detectron2.structures import BoxMode
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/structures/__init__.py", line 2, in <module&gt;
&nbsp;&nbsp;&nbsp; from .boxes import Boxes, BoxMode, pairwise_iou
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/structures/boxes.py", line 8, in <module&gt;
&nbsp;&nbsp;&nbsp; from detectron2.layers import cat
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/layers/__init__.py", line 3, in <module&gt;
&nbsp;&nbsp;&nbsp; from .deform_conv import DeformConv, ModulatedDeformConv
&nbsp; File "/home/amax/iKang/dsr/Project/det2/detectron2/layers/deform_conv.py", line 10, in <module&gt;
&nbsp;&nbsp;&nbsp; from detectron2 import _C
ImportError: /home/amax/iKang/dsr/Project/det2/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Yuxin Wu"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月4日(星期三) 下午2:56
 收件人:&nbsp;"facebookresearch/detectron2"<detectron2@noreply.github.com&gt;;
 抄送:&nbsp;"RUiSs"<2810054551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [facebookresearch/detectron2] ModuleNotFoundError: No module named 'fvcore.common.registry' (#458)

 

 
Closed #458.

**Comment by ppwwyyxx** [comment]
You need to uninstall and reinstall detectron2 https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues.

**Comment by fatalfeel** [comment]
git clone https://github.com/facebookresearch/fvcore
cd fvcore
I solved the problem

python3 ./setup.py build develop
(fvcore will make /usr/local/lib/python3.7/site-packages/fvcore.egg-link to /usr/local/lib/python3.7/dist-packages/fvcore)
(pip3 install 'git+https://github.com/facebookresearch/fvcore' will not make link)
