### ISSUE TITLE
A prediction has category_id=10, which is not available in the dataset

### ISSUE THREAD

**Issue by AliNaqvi110** [facebookresearch/detectron2#4596]
## Instructions To Reproduce the 🐛 Bug:
I have 10 classes for which I want to train faster rcnn
It gives me error after completing 0th iteration training and evaluation. The error is:

"A prediction has category_id=10, which is not available in the dataset."

`AssertionError                            Traceback (most recent call last)
[<ipython-input-12-e2b33cf0b72a>](https://localhost:8080/#) in <module>
     39 trainer = CocoTrainer(cfg)
     40 trainer.resume_or_load(resume=False)
---> 41 trainer.train()

9 frames
[/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/coco_evaluation.py](https://localhost:8080/#) in _eval_predictions(self, tasks, predictions)
    163                     category_id in reverse_id_mapping
    164                 ), "A prediction has category_id={}, which is not available in the dataset.".format(
--> 165                     category_id
    166                 )
    167                 result["category_id"] = reverse_id_mapping[category_id]

AssertionError: A prediction has category_id=10, which is not available in the dataset.`

**Comment by AliNaqvi110** [comment]
Running on colab 
Using Coco datasets pretrained weights for 'COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml'
60k images for training and 10k for validation, 10k for test

10 classes = ["car", "bus", "person", "bike", "truck", "motor", "train", "rider", "traffic sign", "traffic light"]
labelled from 1 to 10 as in coco annotations

**Comment by AliNaqvi110** [comment]
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 11 #your number of classes + 1

**Comment by ppwwyyxx** [comment]
As the [documentation](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#update-the-config-for-new-datasets) says, `NUM_CLASSES` is the number of classes. Not the number of classes +1....

**Comment by AliNaqvi110** [comment]
thanks for directing dumb like me, but it was mentioned in comments to include background class as well
