### ISSUE TITLE
raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by WuYue99** [facebookresearch/detectron2#460]
I followed the documentation，then.... 

File "/home/xx/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/torch/cuda/__init__.py", line 95, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ppwwyyxx** [comment]
Closing as it's a pytorch installation issue.
