### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by canglangzhige** [facebookresearch/detectron2#4631]
I tried to run demo.py with the following command:

python demo/demo.py  \
    --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --webcam \
    --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

But it takes about 5-6 seconds to  infer an image. Check that the GPU is in use through "nvidia smi". Why is it so slow? Is this normal？
Similarly, I use detectron2 to run panoptic segmentation so slowly.
In addition, can you tell which model is used for panoptic segmentation?

**Comment by SixK** [comment]
5-6 s to infer first image could be normal.
but then you should be around 0,3s (and less) per image depending on your hardware.

Note if you don't use --output parameter, detectron will try to show you infered image and inference time will be the time to click for next image


Here is what I get using directory with jpg files:
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input=/alarme/1606150655/*.jpg --output=/tmp/bla --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

Note time for my 2 first images : 2.32s and then 

[11/02 17:32:35 detectron2]: /alarme/1606150655/16061506550121.jpg: detected 5 instances in 2.32s
  0%|▊                                                                                                                                                                                        | 1/241 [00:02<09:29,  2.37s/it][11/02 17:32:36 detectron2]: /alarme/1606150655/16061506550123.jpg: detected 5 instances in 0.12s
  1%|█▌                                                                                                                                                                                       | 2/241 [00:02<04:16,  1.07s/it][11/02 17:32:36 detectron2]: /alarme/1606150655/16061506550007.jpg: detected 8 instances in 0.14s
  1%|██▎                                                                                                                                                                                      | 3/241 [00:02<02:39,  1.50it/s][11/02 17:32:36 detectron2]: /alarme/1606150655/16061506550238.jpg: detected 6 instances in 0.12s
  2%|███                                                                                                                                                                                      | 4/241 [00:02<01:51,  2.12it/s][11/02 17:32:36 detectron2]: /alarme/1606150655/16061506550141.jpg: detected 4 instances in 0.12s

nivida-smi should show a line with python when running:
```
Wed Nov  2 17:32:40 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:26:00.0  On |                  N/A |
| 79%   49C    P2    94W / 170W |   2679MiB / 12052MiB |     57%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3678      G   /usr/lib/xorg/Xorg                141MiB |
|    0   N/A  N/A      3880      G   /usr/bin/gnome-shell               69MiB |
|    0   N/A  N/A      6539      G   ...7/usr/lib/firefox/firefox      176MiB |
|    0   N/A  N/A     23796      C   python                           2287MiB |
+-----------------------------------------------------------------------------+
```
