### ISSUE TITLE
script on mask_rcnn_inference

### ISSUE THREAD

**Issue by gaosanyuan** [facebookresearch/detectron2#4644]
I built an object detector model base on detectron2. When trying to script the model, I find something strange.

if using the detectron2.modeling.roi_heads.mask_head.make_rcnn_inference directly, the scripting is ok, but the scripting will be failed if I copy the make_rcnn_inference code to self package and the use it locally instead of the one from detectron2.

The error comes when I use the scipt model with different input, and located in this line: mask_probs_pred = mask_probs_pred.split(num_boxes_per_image, dim=0)
/usr/local/lib/python3.8/dist-packages/torch/_tensor.py(515): split

Ask for some suggestions, thanks.

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose). Closing as details are not given.
