### ISSUE TITLE
how to Infer only few classes rather than all?

### ISSUE THREAD

**Issue by ezorfa** [facebookresearch/detectron2#467]
Hello Team,

I want to infer the instance masks in an image. Therefore I use Instance segmentation. However, I would like to infer only certain classes like `Car` and `Person` but not `Cycle`. How do i achieve this?

Thankyou!

**Comment by ppwwyyxx** [comment]
If you know how mathematically you want to achieve this, we can help you achieve this in implementation using detectron2.
If you don't know, this is then a machine learning question unrelated to detectron2, and we do not answer such general questions.

**Comment by ezorfa** [comment]
What i mean is, there should be some file mentioning what coco classes have been used while training the model. Can we not edit that file to contain less classes?

**Comment by ppwwyyxx** [comment]
>  Can we not edit that file to predict less classes?

No you cannot.

You can achieve this by removing all the predictions from classes you don't like.
