### ISSUE TITLE
Visualizer tutorial

### ISSUE THREAD

**Issue by jas-nat** [facebookresearch/detectron2#468]
Is there any tutorial on how to use visualizer step by step clearly? Because when I want to try to show a picture similar to the balloon dataset, my picture is messed up and it shows all annotations. 
The picture is like below

![Result](https://user-images.githubusercontent.com/52592216/70219244-d0d70e00-1787-11ea-963c-5b80e54ef2b3.png)

**Comment by ppwwyyxx** [comment]
The balloon tutorial is a step-by-step tutorial that uses visualizer

**Comment by jas-nat** [comment]
>visualizer = Visualizer(img[:, :, ::-1], metadata=balloon_metadata, scale=0.5)
In that line, what does img[:,:,::-1] do?

**Comment by ppwwyyxx** [comment]
`img[:,:,::-1]` is an image. See https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.Visualizer

**Comment by RubenS02** [comment]
@jas-nat is converts an image [:,:,[BGR]] to [:,:,[RGB]]

**Comment by jas-nat** [comment]
> @jas-nat is converts an image [:,:,[BGR]] to [:,:,[RGB]]

Thank you for the explanation RubenS02. I found the mistake already in my labelling
