### ISSUE TITLE
 build\lib.win-amd64-cpython-39\detectron2\_C.cp39-win_amd64.pyd : fatal error LNK1120: 2 个无法解析的外部命令

### ISSUE THREAD

**Issue by LeonYeah** [facebookresearch/detectron2#4687]
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Anaconda\envs\solq\lib\site-packages\torch\lib /LIBPATH:D:\Anaconda\envs\solq\libs /LIBPATH:D:\Anaconda\envs\solq /LIBPATH:D:\Anaconda\envs\solq\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\box_iou_rotated\box_iou_rotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\cocoeval\cocoeval.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\nms_rotated\nms_rotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\vision.obj /OUT:build\lib.win-amd64-cpython-39\detectron2\_C.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated\_C.cp39-win_amd64.lib
      正在创建库 build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated\_C.cp39-win_amd64.lib 和对象 build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated\_C.cp39-win_amd64.exp
    正在生成代码
    已完成代码的生成
    vision.obj : error LNK2001: 无法解析的外部符号 __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
    vision.obj : error LNK2001: 无法解析的外部符号 __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
    build\lib.win-amd64-cpython-39\detectron2\_C.cp39-win_amd64.pyd : fatal error LNK1120: 2 个无法解析的外部命令
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
    [end of output]

So, how can i  solve this problem???????

--configs:
Windows11
CUDA 11.6
Pytorch 1.12

**Comment by bouachalazhar** [comment]
> "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Anaconda\envs\solq\lib\site-packages\torch\lib /LIBPATH:D:\Anaconda\envs\solq\libs /LIBPATH:D:\Anaconda\envs\solq /LIBPATH:D:\Anaconda\envs\solq\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\box_iou_rotated\box_iou_rotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\cocoeval\cocoeval.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\nms_rotated\nms_rotated_cpu.obj build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\vision.obj /OUT:build\lib.win-amd64-cpython-39\detectron2_C.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated_C.cp39-win_amd64.lib 正在创建库 build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated_C.cp39-win_amd64.lib 和对象 build\temp.win-amd64-cpython-39\Release\Code\AI\detectron2-0.6\detectron2\layers\csrc\ROIAlignRotated_C.cp39-win_amd64.exp 正在生成代码 已完成代码的生成 vision.obj : error LNK2001: 无法解析的外部符号 __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA vision.obj : error LNK2001: 无法解析的外部符号 __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA build\lib.win-amd64-cpython-39\detectron2_C.cp39-win_amd64.pyd : fatal error LNK1120: 2 个无法解析的外部命令 error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\link.exe' failed with exit code 1120 [end of output]
> 
> So, how can i solve this problem???????
> 
> --configs: Windows11 CUDA 11.6 Pytorch 1.12

I have the same problem. If you find a solution share it, I'm trying to solve it !

**Comment by qingkongwanli0l** [comment]
same problem too  -_-

**Comment by bouachalazhar** [comment]
I found this link : https://9to5answer.com/install-detectron2-on-windows-10.
But you can try with this https://app.circleci.com/pipelines/github/facebookresearch/detectron2.

**Comment by qingkongwanli0l** [comment]
来信已收到，我会尽快查看
