### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (nms_cuda at /tmp/pip-req-build-8d3_7_rq/torchvision/csrc/cuda/nms_cuda.cu:127)

### ISSUE THREAD

**Issue by RUiSss** [facebookresearch/detectron2#469]
2. what exact command you run:
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml  --input 0.jpg 3.jpg --output /home/amax/iKang/dsr/Project/det2/output    --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
3. what you observed (including the full logs):
```
[12/05 17:34:31 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['0.jpg', '3.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output='/home/amax/iKang/dsr/Project/det2/output', video_input=None, webcam=False)
WARNING [12/05 17:34:31 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
  0%|                                                                                                                           | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "demo/demo.py", line 83, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/amax/iKang/dsr/Project/detectron2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/engine/defaults.py", line 188, in __call__
    predictions = self.model([inputs])[0]
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 66, in forward
    return self.inference(batched_inputs)
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 119, in inference
    proposals, _ = self.proposal_generator(images, features, None)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 179, in forward
    self.training,
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/modeling/proposal_generator/rpn_outputs.py", line 137, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/home/amax/iKang/dsr/Project/detectron2/detectron2/layers/nms.py", line 17, in batched_nms
    return box_ops.batched_nms(boxes, scores, idxs, iou_threshold)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 72, in batched_nms
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 33, in nms
    return _C.nms(boxes, scores, iou_threshold)
RuntimeError: CUDA error: no kernel image is available for execution on the device (nms_cuda at /tmp/pip-req-build-8d3_7_rq/torchvision/csrc/cuda/nms_cuda.cu:127)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7efddd6c7e7d in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: nms_cuda(at::Tensor const&, at::Tensor const&, float) + 0x8d1 (0x7efdb05f7e96 in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #2: nms(at::Tensor const&, at::Tensor const&, float) + 0x183 (0x7efdb05bbe9f in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #3: <unknown function> + 0x79cbd (0x7efdb05d5cbd in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #4: <unknown function> + 0x76578 (0x7efdb05d2578 in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #5: <unknown function> + 0x70ce6 (0x7efdb05ccce6 in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #6: <unknown function> + 0x70f8a (0x7efdb05ccf8a in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
frame #7: <unknown function> + 0x5be18 (0x7efdb05b7e18 in /home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/_C.so)
<omitting python frames>
```
------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1,2,3,4,5,6,7       GeForce RTX 2080 Ti
CUDA_HOME                 /usr/local/cuda-10.0
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.1
cv2                       4.1.2
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.4
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/work=/usr/local/src/conda/pytorch-1.3.1 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
You installed or built a version of torchvision incompatible with your environment. Closing as it's unrelated to detectron2.

**Comment by dihuangdh** [comment]
Exactly same problem here, the only difference is I am using cuda9.2 for TITAN V

[Here](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md), the doc says `Detectron2 or PyTorch/torchvision is not built with the correct compute compatibility for the GPU model` may leed to this problem.  However, for my situation, cuda9.2 is ok for TITAN V's compute compatibility( 7.0 ). It should work.   Even when I set `TORCH_CUDA_ARCH_LIST=7.0`, still same error.  For @RUiSss 's situation, I believe the nvcc architecture flags shows the compute compatibility should be ok, too.

What do you mean by `incompatible with the environment` ?   Could you explain it?  @ppwwyyxx 

I download pytroch and torchvision from https://pytorch.org/

![image](https://user-images.githubusercontent.com/57213566/71880172-b1f2df80-316a-11ea-8a7e-220860c2c5f1.png)

![image](https://user-images.githubusercontent.com/57213566/71880447-54ab5e00-316b-11ea-95d2-ff72848f607f.png)

**Comment by ppwwyyxx** [comment]
You installed a version of torchvision that's incompatible with your environment. The log in the screenshot does not show what compiler or compute compatibility was used to build torchvision because torchvision does not provide such APIs.
