### ISSUE TITLE
Loading the model from final_model.pth checkpoint does not load due to mismatch of keys

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/detectron2#470]
Hi, I've trained a model and have several checkpoints (~350 MB) containing presumably the entire model weights, optimizer state, etc, including the final checkpoint `model_final.pth`

All is good.  But when I try to load the model I just finished training, using `torch.load('model_final.pth')` produces the error

The result of `torch.load('model_final.pth')` has 4 keys,  state_dict: `"model", "optimizer", "scheduler", "iteration"`,  but none of which are 'state_dict`.

How to access the `state_dict` if it does not exist as a key in the final model checkpoint?

`model.load_state_dict(checkpoint['state_dict'])`

```
Error(s) in loading state_dict for GeneralizedRCNN:
	Missing key(s) in state_dict: "backbone.stem.conv1.weight", "backbone.stem.conv1.norm.weight", "backbone.stem.conv1.norm.bias", "backbone.res2.0.shortcut.weight", "backbone.res2.0.shortcut.norm.weight", "backbone.res2.0.shortcut.norm.bias", "backbone.res2.0.conv1.weight", "backbone.res2.0.conv1.norm.weight", "backbone.res2.0.conv1.norm.bias", "backbone.res2.0.conv2.weight", "backbone.res2.0.conv2.norm.weight", "backbone.res2.0.conv2.norm.bias", "backbone.res2.0.conv3.weight", "backbone.res2.0.conv3.norm.weight", "backbone.res2.0.conv3.norm.bias", "backbone.res2.1.conv1.weight", "backbone.res2.1.conv1.norm.weight", "backbone.res2.1.conv1.norm.bias", "backbone.res2.1.conv2.weight", "backbone.res2.1.conv2.norm.weight", "backbone.res2.1.conv2.norm.bias", "backbone.res2.1.conv3.weight", "backbone.res2.1.conv3.norm.weight", "backbone.res2.1.conv3.norm.bias", "backbone.res2.2.conv1.weight", "backbone.res2.2.conv1.norm.weight", "backbone.res2.2.conv1.norm.bias", "backbone.res2.2.conv2.weight", "backbone.res2.2.conv2.norm.weight", "backbone.res2.2.conv2.norm.bias", "backbone.res2.2.conv3.weight", "backbone.res2.2.conv3.norm.weight", "backbone.res2.2.conv3.norm.bias", "backbone.res3.0.shortcut.weight", "backbone.res3.0.shortcut.norm.weight", "backbone.res3.0.shortcut.norm.bias", "backbone.res3.0.conv1.weight", "backbone.res3.0.conv1.norm.weight", "backbone.res3.0.conv1.norm.bias", "backbone.res3.0.conv2.weight", "backbone.res3.0.conv2.norm.weight", "backbone.res3.0.conv2.norm.bias"...
	Unexpected key(s) in state_dict: "model", "optimizer", "scheduler", "iteration".
```

What specific code to run actually load the newly trained model from a checkpoint file?

Is it necessary to simply call `torch.save(model.state_dict(), PATH)` after the model is finished training?

Or simply instantiate the model class and then call load_state_dict() on that model?

```
cfg = get_cfg()
# override the specific config parameters in cfg
model = TheModelClass(cfg)    # e.g I load my Mask Rcnn model via passing in the cfg file to the model class detectron2.meta_arch.rcnn.GeneralizedRCNN(cfg)
model.load_state_dict(torch.load(PATH))
```

**Comment by ppwwyyxx** [comment]
> The result of torch.load('model_final.pth') has 4 keys, state_dict: "model", "optimizer", "scheduler", "iteration", but none of which are 'state_dict`.

Yeah, but why do you expect there is a key called "state_dict"?

The doc https://detectron2.readthedocs.io/tutorials/models.html has instructions on how to load a model.

**Comment by cpoptic** [comment]
I've followed the doc you listed, but still an error.
```
from detectron2.modeling import build_model
model = build_model(cfg)  # returns a torch.nn.Module
DetectionCheckpointer(model).load(FINAL_MODEL_CHECKPOINT)  # <- This checkpoint is a .pth file
```

But still getting an error regarding the keys of the resulting dictionary:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-164-c988b10df534> in <module>
----> 1 DetectionCheckpointer(model).load(FINAL_MODEL_CHECKPOINT)

~/anaconda3/envs/detectron2_cuda_10_1/lib/python3.7/site-packages/fvcore/common/checkpoint.py in load(self, path)
    101 
    102         checkpoint = self._load_file(path)
--> 103         self._load_model(checkpoint)
    104         for key, obj in self.checkpointables.items():
    105             if key in checkpoint:

~/repos/detectron2/detectron2/checkpoint/detection_checkpoint.py in _load_model(self, checkpoint)
     57             checkpoint["model"] = model_state_dict
     58         # for non-caffe2 models, use standard ways to load it
---> 59         super()._load_model(checkpoint)

~/anaconda3/envs/detectron2_cuda_10_1/lib/python3.7/site-packages/fvcore/common/checkpoint.py in _load_model(self, checkpoint)
    195         """
    196         checkpoint_state_dict = checkpoint.pop("model")
--> 197         self._convert_ndarray_to_tensor(checkpoint_state_dict)
    198 
    199         # if the state_dict comes from a model that was wrapped in a

~/anaconda3/envs/detectron2_cuda_10_1/lib/python3.7/site-packages/fvcore/common/checkpoint.py in _convert_ndarray_to_tensor(self, state_dict)
    245                 raise ValueError(
    246                     "Unsupported type found in checkpoint! {}: {}".format(
--> 247                         k, type(v)
    248                     )
    249                 )

ValueError: Unsupported type found in checkpoint! state: <class 'dict'>

**Comment by ppwwyyxx** [comment]
https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict

> A state_dict is simply a Python dictionary object that maps each layer to its parameter tensor. 

Looks like the state_dict for your custom model is not.

If that does not solve your issue, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
