### ISSUE TITLE
How to save the model instead of just the model parameters

### ISSUE THREAD

**Issue by chenjun19950315** [facebookresearch/detectron2#472]
Thank you for this awesome work,I want to save the model instead of the model parameters，I used the default DefaultPredictor to load the model and trained parameters, but something went wrong when saving the complete model (not the model parameters).The error is as follows
my code：
 cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_0219999.pth")
 predictor = DefaultPredictor(cfg)
torch.save(predictor.model, 'model_complete.pkl')

error:
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type GeneralizedRCNN. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type FPN. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Conv2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type LastLevelMaxPool. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type ResNet. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BasicStem. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type FrozenBatchNorm2d. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Sequential. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BottleneckBlock. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type RPN. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type DefaultAnchorGenerator. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type BufferList. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type StandardRPNHead. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type StandardROIHeads. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type ROIPooler. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type ModuleList. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type ROIAlign. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type FastRCNNConvFCHead. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Linear. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type FastRCNNOutputLayers. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
Traceback (most recent call last):
  File "/home/wang/cj/detectron2/test4.py", line 225, in <module>
    torch.save(predictor.model, '/home/wang/cj/detectron2/model_complete.pkl')
  File "/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py", line 185, in _with_file_like
    return body(f)
  File "/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py", line 260, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/wang/.local/lib/python3.6/site-packages/torch/serialization.py", line 332, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'GeneralizedRCNN.__init__.<locals>.<lambda>'

1.Where is the save function of the Checkpointer class called during network training.I did not find that the save function was called during network training

2.How should i solve this problem

**Comment by ppwwyyxx** [comment]
Pickling the model class is not supported (and is a bad idea in general). You can save `model.state_dict()` instead.
