### ISSUE TITLE
How to show the segmentation results of TensorMask？

### ISSUE THREAD

**Issue by lyc6749** [facebookresearch/detectron2#474]
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, or how to improve your training.

**Comment by ppwwyyxx** [comment]
The same way as all other models. 
See https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 for example.
