### ISSUE TITLE
How to use roi align in detectron2 

### ISSUE THREAD

**Issue by FateScript** [facebookresearch/detectron2#475]
##  How to use roi align in detectron2 
Hi, I noticed that detectron2 use 0.5 offset in roi align v2 and I get the following questions:
* Is this related to bilinear process? Could you please tell me the reason of doing this ?
* When should we use roi align v2?

thanks :)

**Comment by ppwwyyxx** [comment]
1. Explained in https://github.com/facebookresearch/detectron2/blob/master/detectron2/layers/roi_align.py

2. You should always use v2 unless you're matching Detectron 1.

**Comment by FateScript** [comment]
> 1. Explained in https://github.com/facebookresearch/detectron2/blob/master/detectron2/layers/roi_align.py
> 2. You should always use v2 unless you're matching Detectron 1.

Thx~
