### ISSUE TITLE
Please read & provide the follWhether the GeneralizedRCNN model (trained by detectron2) can be converted to Onnx with torch.onnx.export()?owing

### ISSUE THREAD

**Issue by htlbayytq** [facebookresearch/detectron2#4763]
I've been trying for days to use torch.onnx.export() to convert my trained detectron2 model to onnx.

The detectron2 model is a GeneralizedRCNN model, It is also the ideal model that took me a long time to train, using my own data set.

Now I want to convert it to onnx to deploy it, but there are always various errors.

When I read the official document today, I found that it seems that the model of type "recurrent network" cannot be converted with torch.onnx.export()?  It is said that torch.jit.trace() cannot convert it.

Sincerely and eagerly requesting an answer, is it possible to use torch.onnx.export() to complete the conversion of the detectron2 trained  GeneralizedRCNN model?

I have been tortured for many days, please help me dear experts!

**Comment by RajUpadhyay** [comment]
I have seen various blogs where people have used the detectron2 and then trained the model with custom balloon dataset and then converted it to onnx.
I will share a link, maybe it could help.
https://medium.com/@frankvanpaassen3/how-to-optimize-custom-detectron2-models-with-tensorrt-2cd710954ad3
