### ISSUE TITLE
How to fine-tune a specific layer?

### ISSUE THREAD

**Issue by marsggbo** [facebookresearch/detectron2#478]
How to fine-tune a specific layer (e.g. backbone or roi_head)? Can we modify the config file to specify which layer to finetune, or is there any other simple methods to implement this requirement? Thanks

**Comment by ppwwyyxx** [comment]
There is no config for it.
One way is to set `requires_grad` attribute for parameters in the model. 
Closing as it's a pytorch question.  You can get better answers in https://discuss.pytorch.org/
