### ISSUE TITLE
How to deploy detectron2 on Android ?

### ISSUE THREAD

**Issue by yzmean** [facebookresearch/detectron2#479]
## ❓ How to deploy detectron2 on Android ?

I want to do a traffic sign detection on the Android phone,So is their any way to do it ?

**Comment by ppwwyyxx** [comment]
We'll release code soon to convert detectron2 models to caffe2 and then it can be deployed to android. We'll update in #8.

**Comment by MentalGear** [comment]
How soon is soon ? :P
