### ISSUE TITLE
Is it possible to instant segment specific classes and save masks?

### ISSUE THREAD

**Issue by iPsych** [facebookresearch/detectron2#48]
Is it possible to instant segment specific classes (i.e. cars) and save masks?

**Comment by ppwwyyxx** [comment]
You can obtain masks by `outputs['instances'].pred_masks` from the [colab tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5).

**Comment by iPsych** [comment]
> You can obtain masks by `outputs['instances'].pred_masks` from the [colab tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5).

It gives tensor contains all 'False's.
shouldn't it be a series of image or pixel data?

**Comment by ppwwyyxx** [comment]
False means the pixel is not part of the mask.
The output format is explained in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format.

**Comment by wuqijin** [comment]
ds

**Comment by iPsych** [comment]
ppwwyyxx, Thanks.

**Comment by qodlsrud20712** [comment]
Hello, all of the information of pred_masks is false. Have you ever solved this problem??
