### ISSUE TITLE
Invalid URL in configs.md

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#480]
At the [configs.md](https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/configs.md#use-configs-1), the   [Config References](https://github.com/facebookresearch/detectron2/blob/master/docs/modules/config.html#config-references) link is 404.

**Comment by ppwwyyxx** [comment]
The docs are meant for reading on https://detectron2.readthedocs.io/tutorials/configs.html
