### ISSUE TITLE
ground truth visualization

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#483]
How to visualization the coco val2017 annotated by the ground truth?
Is there a convenient way to get the ground truth annotated images just as the `tools/demo.py` generated?

Thank you very much!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/tools/visualize_data.py

**Comment by ShoufaChen** [comment]
Thank you very much..
