### ISSUE TITLE
Unable to properly export custom keypoint RCNN to ONNX

### ISSUE THREAD

**Issue by jhonatanbds** [facebookresearch/detectron2#4834]
I am trying to properly export a custom trained keypoint RCNN FPN50 model to ONNX. I can export it in torchscript format and the inference works, but it does not when I do it in ONNX. The `tools/deploy/export_model.py` won't work and I am using the code from tests  in this [PR](https://github.com/facebookresearch/detectron2/pull/4205/files#diff-7d768d0cd0f46e5999dcab0cb5f2f7a101611e771ff0483869568aa01e0b5240R144-R173). I have also tried to use the code from the `testKeypointHead` test in this [commit](https://github.com/facebookresearch/detectron2/commit/1523b3e9929a06d798871eb9afc4c9f770743baf), but this code only do the trick for the keypoint head and I cant replicate for the full model.

## Instructions To Reproduce the Issue:

I have trained a Keypoint R-CNN FPN-50 in a custom dataset using 4 keypoints and 12 classes. I have tried to export using the following two methods:

1. Default RCNN export script from the PR mentioned above
```python
def export_onnx(torch_model, inputs):
    image = cv2.imread(args.sample_image)
    image = cv2.resize(image, (224,224))
    image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))

    inputs = tuple([image])
    
    def inference_func(model, images):
            with warnings.catch_warnings(record=True):
                inputs = [{"image": image} for image in images]
            inst = model.inference(inputs, do_postprocess=False)[0]
            return [{"instances": inst}]
    import onnx

    f = io.BytesIO()
    adapter_model = TracingAdapter(torch_model, inputs, inference_func)
    adapter_model.eval()
    with torch.no_grad():
        try:
            torch.onnx.enable_log()
        except AttributeError:
            # Older ONNX versions does not have this API
            pass
        torch.onnx.export(
            adapter_model,
            adapter_model.flattened_inputs,
            f,
            training=torch.onnx.TrainingMode.EVAL,
            opset_version=STABLE_ONNX_OPSET_VERSION,
            verbose=True,
        )
    onnx_model = onnx.load_from_string(f.getvalue())

    assert onnx_model is not None
    onnx.save(onnx_model, os.path.join(args.output, "model.onnx"))
```
This method can successful export the model but it won't load on ONNXRuntime with the following error
```
Traceback (most recent call last):
  File "/home/jhonatan.silva/workspace/document-keypoint-detection/onnxtest.py", line 12, in <module>
    ort_sess = ort.InferenceSession('outcnh2021onnxkp/model2.onnx')
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from outcnh2021onnxkp/model2.onnx failed:Node (Loop_2744) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Node (Resize_2764) Op (Resize) [ShapeInferenceError] Number of elements of input 'sizes' (0) must be same as rank of input 'X' (4).
```
I have managed to load it by changing some attributes with onnx graph surgeon, but it produces empty outputs.

2. Keypoint head export method from the commit above
```python
with patch_builtin_len():
        onnx_model = _test_model(
            model,
            gen_input(1, 2),
            #inference_func,
            input_names=["features", "pred_boxes", "pred_classes"],
            output_names=["box1", "box2"],
            dynamic_axes={
                "features": {0: "batch", 1: "static_four", 2: "height", 3: "width"},
                "pred_boxes": {0: "batch", 1: "static_four"},
                "pred_classes": {0: "batch", 1: "static_four"},
                "box1": {0: "num_instance", 1: "K", 2: "static_three"},
                "box2": {0: "num_instance", 1: "K", 2: "static_three"},
            },
        )
    
    assert has_dynamic_axes(onnx_model)
```
I have tried several inference functions but it leaves me with errors related to the forward and/or inference_function like the following
```
Traceback (most recent call last):
  File ".../export_model.py", line 395, in <module>
    exported_model = exportKeypointHead(torch_model)
  File ".../export_model.py", line 143, in exportKeypointHead
    onnx_model = _test_model(
  File ".../export_model.py", line 86, in _test_model
    torch.onnx.export(
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/jhonatan.silva/workspace/detectron2/detectron2/export/flatten.py", line 294, in forward
    outputs = self.inference_func(self.model, *inputs_orig_format)
  File "/home/jhonatan.silva/workspace/detectron2/detectron2/export/flatten.py", line 259, in <lambda>
    inference_func = lambda model, *inputs: model(*inputs)  # noqa
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 4 were given
```
Any idea if this is unsupported or what I am doing wrong?

## Environment:
```
----------------------  -----------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.9.11 (main, Mar 29 2022, 19:08:29) [GCC 7.5.0]
numpy                   1.21.2
detectron2              0.6 @/home/jhonatan.silva/workspace/detectron2/detectron2
Compiler                GCC 9.4
CUDA compiler           CUDA 11.3
detectron2 arch flags   8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.13.1+cu117 @/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce RTX 3050 Laptop GPU (arch=8.6)
Driver version          510.108.03
CUDA_HOME               /usr/local/cuda-11.3
Pillow                  9.0.1
torchvision             0.14.1+cu117 @/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220305
iopath                  0.1.9
cv2                     4.5.5
----------------------  -----------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
```

**Comment by bouachalazhar** [comment]
> J’essaie d’exporter correctement un modèle RCNN FPN50 à point clé formé personnalisé vers ONNX. Je peux l’exporter au format torchscript et l’inférence fonctionne, mais ce n’est pas le cas lorsque je le fais sous ONNX. Le ne fonctionnera pas et j’utilise le code des tests de ce [PR.](https://github.com/facebookresearch/detectron2/pull/4205/files#diff-7d768d0cd0f46e5999dcab0cb5f2f7a101611e771ff0483869568aa01e0b5240R144-R173) J’ai également essayé d’utiliser le code du test dans ce [commit,](https://github.com/facebookresearch/detectron2/commit/1523b3e9929a06d798871eb9afc4c9f770743baf) mais ce code ne fait que l’affaire pour la tête de point clé et je ne peux pas répliquer pour le modèle complet.`tools/deploy/export_model.py``testKeypointHead`
> 
> ## Instructions pour reproduire le problème :
> J’ai formé un Keypoint R-CNN FPN-50 dans un ensemble de données personnalisé en utilisant 4 points clés et 12 classes. J’ai essayé d’exporter en utilisant les deux méthodes suivantes :
> 
> 1. Script d’exportation RCNN par défaut à partir du PR mentionné ci-dessus
> 
> ```python
> def export_onnx(torch_model, inputs):
>     image = cv2.imread(args.sample_image)
>     image = cv2.resize(image, (224,224))
>     image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))
> 
>     inputs = tuple([image])
>     
>     def inference_func(model, images):
>             with warnings.catch_warnings(record=True):
>                 inputs = [{"image": image} for image in images]
>             inst = model.inference(inputs, do_postprocess=False)[0]
>             return [{"instances": inst}]
>     import onnx
> 
>     f = io.BytesIO()
>     adapter_model = TracingAdapter(torch_model, inputs, inference_func)
>     adapter_model.eval()
>     with torch.no_grad():
>         try:
>             torch.onnx.enable_log()
>         except AttributeError:
>             # Older ONNX versions does not have this API
>             pass
>         torch.onnx.export(
>             adapter_model,
>             adapter_model.flattened_inputs,
>             f,
>             training=torch.onnx.TrainingMode.EVAL,
>             opset_version=STABLE_ONNX_OPSET_VERSION,
>             verbose=True,
>         )
>     onnx_model = onnx.load_from_string(f.getvalue())
> 
>     assert onnx_model is not None
>     onnx.save(onnx_model, os.path.join(args.output, "model.onnx"))
> ```
> 
> Cette méthode peut réussir l’exportation du modèle, mais elle ne se chargera pas sur ONNXRuntime avec l’erreur suivante
> 
> ```
> Traceback (most recent call last):
>   File "/home/jhonatan.silva/workspace/document-keypoint-detection/onnxtest.py", line 12, in <module>
>     ort_sess = ort.InferenceSession('outcnh2021onnxkp/model2.onnx')
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from outcnh2021onnxkp/model2.onnx failed:Node (Loop_2744) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Node (Resize_2764) Op (Resize) [ShapeInferenceError] Number of elements of input 'sizes' (0) must be same as rank of input 'X' (4).
> ```
> 
> J’ai réussi à le charger en changeant certains attributs avec onnx graph surgeon, mais il produit des sorties vides.
> 
> 2. Méthode d’exportation de tête de point clé à partir de la validation ci-dessus
> 
> ```python
> with patch_builtin_len():
>         onnx_model = _test_model(
>             model,
>             gen_input(1, 2),
>             #inference_func,
>             input_names=["features", "pred_boxes", "pred_classes"],
>             output_names=["box1", "box2"],
>             dynamic_axes={
>                 "features": {0: "batch", 1: "static_four", 2: "height", 3: "width"},
>                 "pred_boxes": {0: "batch", 1: "static_four"},
>                 "pred_classes": {0: "batch", 1: "static_four"},
>                 "box1": {0: "num_instance", 1: "K", 2: "static_three"},
>                 "box2": {0: "num_instance", 1: "K", 2: "static_three"},
>             },
>         )
>     
>     assert has_dynamic_axes(onnx_model)
> ```
> 
> J’ai essayé plusieurs fonctions d’inférence mais cela me laisse avec des erreurs liées au transfert et / ou à la inference_function comme les suivantes
> 
> ```
> Traceback (most recent call last):
>   File ".../export_model.py", line 395, in <module>
>     exported_model = exportKeypointHead(torch_model)
>   File ".../export_model.py", line 143, in exportKeypointHead
>     onnx_model = _test_model(
>   File ".../export_model.py", line 86, in _test_model
>     torch.onnx.export(
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
>     _export(
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
>     graph, params_dict, torch_out = _model_to_graph(
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
>     graph, params, torch_out, module = _create_jit_graph(model, args)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
>     graph, torch_out = _trace_and_get_graph_from_model(model, args)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
>     trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
>     outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
>     graph, out = torch._C._create_graph_by_tracing(
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
>     outs.append(self.inner(*trace_inputs))
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
>     result = self.forward(*input, **kwargs)
>   File "/home/jhonatan.silva/workspace/detectron2/detectron2/export/flatten.py", line 294, in forward
>     outputs = self.inference_func(self.model, *inputs_orig_format)
>   File "/home/jhonatan.silva/workspace/detectron2/detectron2/export/flatten.py", line 259, in <lambda>
>     inference_func = lambda model, *inputs: model(*inputs)  # noqa
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
>     result = self.forward(*input, **kwargs)
> TypeError: forward() takes 2 positional arguments but 4 were given
> ```
> 
> Une idée si cela n’est pas pris en charge ou ce que je fais mal?
> 
> ## Environnement:
> ```
> ----------------------  -----------------------------------------------------------------------------------------------
> sys.platform            linux
> Python                  3.9.11 (main, Mar 29 2022, 19:08:29) [GCC 7.5.0]
> numpy                   1.21.2
> detectron2              0.6 @/home/jhonatan.silva/workspace/detectron2/detectron2
> Compiler                GCC 9.4
> CUDA compiler           CUDA 11.3
> detectron2 arch flags   8.6
> DETECTRON2_ENV_MODULE   <not set>
> PyTorch                 1.13.1+cu117 @/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torch
> PyTorch debug build     False
> GPU available           Yes
> GPU 0                   NVIDIA GeForce RTX 3050 Laptop GPU (arch=8.6)
> Driver version          510.108.03
> CUDA_HOME               /usr/local/cuda-11.3
> Pillow                  9.0.1
> torchvision             0.14.1+cu117 @/home/jhonatan.silva/anaconda3/envs/cuda3/lib/python3.9/site-packages/torchvision
> torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
> fvcore                  0.1.5.post20220305
> iopath                  0.1.9
> cv2                     4.5.5
> ----------------------  -----------------------------------------------------------------------------------------------
> PyTorch built with:
>   - GCC 9.3
>   - C++ Version: 201402
>   - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.7
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
>   - CuDNN 8.5
>   - Magma 2.6.1
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
> ```

Have you find a solution ?
