### ISSUE TITLE
Why ground truth visualization gets a horizontally flip result

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#487]
I use the https://github.com/facebookresearch/detectron2/blob/master/tools/visualize_data.py to visualize and save the ground truth coco_2017_val. 

I found **_some_** of the saved results are horizontally flip as the original image.
Example:
Original:
![000000000785](https://user-images.githubusercontent.com/28682908/70419408-53214400-1aa0-11ea-98ac-24087937be94.jpg)

Results:
![785](https://user-images.githubusercontent.com/28682908/70419432-616f6000-1aa0-11ea-8d7b-0f1e8aa9339c.jpg)

**Comment by ppwwyyxx** [comment]
The script supports visualization of both the training data (with augmentation) or training dataset annotations. You're visualizing the training data.
