### ISSUE TITLE
Problem with fuction polygons_to_bitmask when transforming hierarchical contours, e.g. to a mask with a hole?

### ISSUE THREAD

**Issue by yangjzx** [facebookresearch/detectron2#489]
I have found a problem when using polygon annotations having hierarchical relationship for instance segmentation using COCO format. 
For example, when I have a "segmentation" item as [[100, 100, 400, 100, 400, 400, 100, 400], [200, 200, 300, 200, 300, 300, 200, 300]], I expected a mask as the following:
![problem1](https://user-images.githubusercontent.com/51399644/70422633-fa08de80-1aa6-11ea-93c0-6ef39f33a984.png)
However, when using the function polygons_to_bitmask, I will get a mask with no hole, as the function uses cocoapi which will calculated the union of the parts.
![problem2](https://user-images.githubusercontent.com/51399644/70423044-bd89b280-1aa7-11ea-885b-697a217022d6.png)
As a learner, I am not sure is it a problem relating to the repo? 
Or should I annotate mask in the case above as just the external contour?

**Comment by ppwwyyxx** [comment]
>  I expected a mask as the following

That is an incorrect expectation.

You can represent masks with holes by union of multiple polygons, or you can use `BitMasks` as inputs to the model directly.

**Comment by yangjzx** [comment]
Thanks for the reply!
However, it is easy to find solutions for self-made annotations. However, will this implementation be problem for open resourced datasets with polygons annotations such as coco? I haven't found discussions about these details about how the groundtruths are annotated in these cases.

**Comment by ppwwyyxx** [comment]
Some public datasets do have such issues, and there is nothing we can do about them.

**Comment by yangjzx** [comment]
OK! Thanks!

**Comment by zhixuanli** [comment]
@ppwwyyxx 
I have searched for many pages but still cannot find materials about how to use `BitMasks`.

Could you give an example?

Thanks a lot, it's really important to me.
