### ISSUE TITLE
how to eval or infer by batch, instead of one img by one image?

### ISSUE THREAD

**Issue by Wu-Xiang123** [facebookresearch/detectron2#4890]
as title show, I failed to find a config param to set it, SOLVER.IMS_PER_BATCH not helps, thanks a lot.

**Comment by wat3rBro** [comment]
`SOLVER.IMS_PER_BATCH` only controls the batch size during training, for inference the `batch_size` is default to `1`, you can change it by manually passing the batch size when calling `build_detection_test_loader` (https://github.com/facebookresearch/detectron2/blob/main/detectron2/data/build.py#L488).
