### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#490]
Hello,

So I have been trying to train my own model from a COCO dataset. 
My computer is very weak so I wanted to do the training on a colab notebook and then download the model and use it when predicting. I followed the steps from the [provided notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) (I loaded the data a bit differently - but as you can see in [my](https://colab.research.google.com/drive/12SldkuBx3ryQ140g3Pn-l4xr4hBnHYgK) notebook, it works). 

My problem is, when I get to the training part (again, using the provided code), I get: 
 "CUDA error: device-side assert triggered"... (I added the notebook above so you can recreate the problem. Just a note, I download the train Images directly to the VM - if there is a better way, I am more then happy to hear it).

I don't know what causes this problem. My dataset is much bigger than the one given in the example (mine is 2500+ images, the one provided is 61) but I am using the same parameters while training (maybe that is the problem or maybe it's the size of the Images... just some thoughts). 

Thanks in advance,
Itamar

**Comment by ppwwyyxx** [comment]
You set the category_id in your dataset to 65 and you also set `cfg.MODEL.ROI_HEADS.NUM_CLASSES` to 2.
