### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by phdfar** [facebookresearch/detectron2#4902]
Hi. in detectron2/utils/events.py in @cached_property  
this added code not compatible with python 3.7

"ImportError: cannot import name 'cached_property' from 'functools' (/opt/conda/lib/python3.7/functools.py)"

**Comment by Thyshy08** [comment]
I also meet this error, is the only way to solve this problem is to change the python version?

**Comment by RajUpadhyay** [comment]
Try installing newer versions of python, try 3.8, if not then 3.9.
