### ISSUE TITLE
How to inference  a video by densepose model?

### ISSUE THREAD

**Issue by vicchu** [facebookresearch/detectron2#491]

**Comment by ppwwyyxx** [comment]
Extract a frame, and inference on the frame.

**Comment by italojs** [comment]
please, check this solution code at issue https://github.com/facebookresearch/detectron2/issues/481#issuecomment-563001802

**Comment by GeorgPopp** [comment]
> Extract a frame, and inference on the frame.

Hey there, 
I was trying to inference on a sequence with the following code: !python ./apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/165712039/model_final_162be9.pkl "frame*.jpg" dp_contour,bbox --output output_frame.png

but it seems that DensePose is not converting the right sequence of images so I would get a shuffled video which is useless. Any idea how to use this command to get the right output_frame sequence?

Thanks
