### ISSUE TITLE
getting low scores

### ISSUE THREAD

**Issue by Aashish243** [facebookresearch/detectron2#492]
I am training X101-FPN mask RCNN model with around 6000 images.
The objects I am training vary largely in size. some are very small and some are very big. 

training stats  
ITERATIONS  : 35000 
lr = 0.001
MODEL.BACKBONE.FREEZE_AT = 2
no. of classes = 2

I am getting very low object scores (around 0.30) after 35000.
Please suggest

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says, 

> If you expect the model to converge / work better, note that we do not help you train your model.
