### ISSUE TITLE
 No module named 'densepose'

### ISSUE THREAD

**Issue by wangsen1312** [facebookresearch/detectron2#493]
After the installation, I can import the detectron2 module but can't import densepose module

**Comment by ppwwyyxx** [comment]
You need to be in the DensePose directory https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose to use densepose.

**Comment by wangsen1312** [comment]
@ppwwyyxx Thank you very much! got it !

**Comment by RSKothari** [comment]
The strange thing is that I'm getting the same error when I try to load saved pickle data from another folder. I even tried adding DensePose to my path, that did not help.

**Comment by mathuse** [comment]
> @ppwwyyxx Thank you very much! got it !

how to use the densepose in the Densepose  directory?

**Comment by yufeng1707** [comment]
> The strange thing is that I'm getting the same error when I try to load saved pickle data from another folder. I even tried adding `detectron2` to my path, that did not help. I've also imported the pip install using `import detectron2`.
> 
> Solved it: Need to add `DensePose` to my path, not the main project page.

can you explain a little more, because I also have this issue.
