### ISSUE TITLE
Detectron2 CUDA Compiler not available

### ISSUE THREAD

**Issue by jas-nat** [facebookresearch/detectron2#496]
After so many commits since October, I tried to reinstall my Detectron2. However, I met some problems with the code

1. what changes you made (`git diff`) or what code you wrote
```
I didn't change anything

```
2. what exact command you run:
I tried to install by typing `python setup.py build develop`

3. what you observed (including the full logs):
```  
File "setup.py", line 63
    def get_model_zoo_configs() -> List[str]:
                                ^
SyntaxError: invalid syntax
```
## Expected behavior
File "setup.py", line 63
    def get_model_zoo_configs() -> List[str]:
                                ^
SyntaxError: invalid syntax

## Environment

sys.platform           linux
Python                 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Numpy                  1.17.4
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0
PyTorch Debug Build    False
torchvision            0.4.1
CUDA available         True
GPU 0                  GeForce RTX 2070 SUPER
CUDA_HOME              None
Pillow                 6.2.1
cv2                    3.2.0
---------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
I believe that's valid python syntax. Either you may have modified the code, or you're not using python 3.6+, or your python interpreter has bugs.

**Comment by jas-nat** [comment]
Actually, when I first installed Detectron2 I followed what's written in 
[INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) 

It says 

```
git clone https://github.com/facebookresearch/detectron2.git
cd detectron2
python setup.py build develop
# or if you are on macOS
# MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py build develop
# or, as an alternative to `setup.py`, do
# pip install [--editable] .
```
I used "pip install" but now I think it's been edited. What should be in [--editable] ? If I want to use pip install does the command become: `pip install setup.py`?

**Comment by jas-nat** [comment]
I finally managed to install the new installation by typing `python3 setup.py build develop`

Now I am facing a new problem where it's the same as mentioned in  #267 . However, I found that my environment is different than what has been discovered
```
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  not available
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     GeForce RTX 2070 SUPER
CUDA_HOME                 None
Pillow                    6.2.1
cv2                       3.2.0
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

My Detectron2 CUDA Compiler is not detected. I have tried to reinstall pytorch with the same version as my CUDA version. However, the Detectron2 CUDA compiler is still not detected. What am I supposed to do?

**Comment by ppwwyyxx** [comment]
> CUDA_HOME                 None

This means pytorch cannot find cuda compiler. You can verify this by 
```
from torch.utils.cpp_extension import CUDA_HOME
```
and print it. 
This is then not a detectron2 issue.

You can try including nvcc in your `$PATH` or some other ways to inform pytorch of your cuda installation. You can also ask in https://discuss.pytorch.org/.

Closing as the original issue is solved and the new issue is not about detectron2.

**Comment by jas-nat** [comment]
Thank you very much for the explanation. Sorry for asking question outside of detectron2
