### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/detectron2-main/detectron2/model_zoo/configs'

### ISSUE THREAD

**Issue by LLL-YUE** [facebookresearch/detectron2#4972]
After the instruction
python -m pip install -e detectron2-main
I met this error
How to deal with this situation?

**Comment by xiaoliujapan** [comment]
me too, same issue. i use Windows10

**Comment by damdafayton** [comment]
you need to give permissions to the folder content.
if you are on docker like this
`RUN sudo chmod -R 777 detectron2_repo`
