### ISSUE TITLE
very confuse when use model_zoo api.

### ISSUE THREAD

**Issue by lansinuote** [facebookresearch/detectron2#4973]
I'm follow https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=HUjkwRsOn1O0 to begin my very first time learning.

I'm not running it on Colab but in my local machine.

when I run `model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")` it give me error: `RuntimeError: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml not available in Model Zoo!` .

I think maybe `COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml` is a local file? because I can find it in `detectron2/configs` folder.

so I change the code to `model_zoo.get_config_file("./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")` the error still same.

so the string `COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml` dose not means a file name.

I think it maybe is a id for remote download like use Huggingface hub. but that also wrong.

I tryed `help(model_zoo.get_config_file)` I see the hint : 
`config_path (str): config file name relative to detectron2's "configs/"
            directory, e.g., "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"`

so I tryed `model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml")` I get the error `RuntimeError: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml not available in Model Zoo!`

so this api wrong with it's won help document???

I'm really confused, please tell me what is the `config_path` is? I have no idea about it...

**Comment by lansinuote** [comment]
OK, I roughly understand.

when run `model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")`

it's actually looking in dir `/root/code/detectron2/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml`

why? I have no idea, but it's just run this way. so I copy every thing in `detectron2/configs` to `/root/code/detectron2/detectron2/model_zoo/configs`

then every thing works fine.

**Comment by ppwwyyxx** [comment]
The colab says this clearly:

> # Note: This is a faster way to install detectron2 in Colab, but it does not include all functionalities.
# See https://detectron2.readthedocs.io/tutorials/install.html for full installation instructions

Model zoo is not included in this "fast" installation.

**Comment by ppwwyyxx** [comment]
I just tried running the first cell of the colab:
```
!python -m pip install pyyaml==5.1
import sys, os, distutils.core
# Note: This is a faster way to install detectron2 in Colab, but it does not include all functionalities (e.g. compiled operators).
# See https://detectron2.readthedocs.io/tutorials/install.html for full installation instructions
!git clone 'https://github.com/facebookresearch/detectron2'
dist = distutils.core.run_setup("./detectron2/setup.py")
!python -m pip install {' '.join([f"'{x}'" for x in dist.install_requires])}
sys.path.insert(0, os.path.abspath('./detectron2'))
```

and then
```
from detectron2 import model_zoo
model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
```

it just works fine.
