### ISSUE TITLE
Performance drop when replacing BN by syncBN

### ISSUE THREAD

**Issue by txytju** [facebookresearch/detectron2#498]
After changing BN(4 GPUs, BatchSize=20) to SyncBN that you implemented in this repo, I got Performance drop (AP=72.2 to AP=70.8) on my own dataset. I have no clue on how to debug this problem. Do you have any suggestions?

**Comment by ppwwyyxx** [comment]
We've already provided configs that use SyncBN correctly.

As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md#expected-behavior) says:

> If you expect the model to converge / work better, note that we do not help you train your model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
