### ISSUE TITLE
How to extract feature from any layer in a pre-trained detector?

### ISSUE THREAD

**Issue by goolhanrry** [facebookresearch/detectron2#5]
Thanks for your great work! The performances of the detectors are amazing!

I have some questions on detectron2.
1. Now I have a list of bbox coordinates with respect to some images, how can I run a pre-trained detector (i.e. Faster-RCNN-R50-FPN) on these images, and crop the feature map (i.e. extract the 7x7 rois in the detector) according to the bbox coordinates? Is there an API in detectron2 to do the work?
2. How can I generate the proposals for Fast-RCNN, should I run the RPN directly to get the `.pkl` file?

Thank you again for your attention!

**Comment by ppwwyyxx** [comment]
1. 
```python
from detectron2.modeling import build_backbone
from detectron2.modeling.poolers import ROIPooler
backbone = build_backbone(cfg)
pooler = ROIPooler(...)
rois = pooler(backbone(NCHW_images), [kx4 tensors])
```

2. Running inference on a dataset with a RPN-only model will produce the proposals for the dataset in `output/inference`.
An example command is 
```
python tools/train_net.py --config-file configs/COCO-Detection/rpn_R_50_FPN_1x.yaml --eval-only
```

**Comment by goolhanrry** [comment]
Thank you for your kind reply!

As for Q1, regarding that the coordinates of the bboxes (either abs or rel ones) might change due to the pre-processing of images (i.e. padding or scaling), should I modify the `[kx4 tensors]` in your code manually to meet these transforms?

**Comment by ppwwyyxx** [comment]
The boxes should be absolute coordinates in XYXY, on the scale of [0, H or W], where H or W matches the size of tensor you give to the backbone.

**Comment by goolhanrry** [comment]
Thanks

**Comment by kachiO** [comment]
Hello, 
I have a related question. After running inference with Detectron2 and I get the class predictions and bounding boxes, how do I get the features associated with each detected object/region? It seems redundant to have to run re-run the images via the backbone and ROIPool.

**Comment by ppwwyyxx** [comment]
@kachiO the densepose example does what you described:
https://github.com/facebookresearch/detectron2/blob/817050985edb0a6a5ee6b795a6653dceed36d933/projects/DensePose/densepose/roi_head.py#L84-L85

**Comment by aligholami** [comment]
@ppwwyyxx I am confused. I think this line
```
rois = pooler(backbone(NCHW_images), [kx4 tensors])
```
has already generated a features for the regions. Is that right?

**Comment by ppwwyyxx** [comment]
That's right.

**Comment by Programmnix** [comment]
Hi,

for everybody how is interested in feature extraction for bounding boxes. There is a fork of this repo with example code. https://github.com/airsplay/py-bottom-up-attention

**Comment by albertchristianto** [comment]
Hi @ppwwyyxx,
given this line of code
```
rois = pooler(images_features, bboxes_coordinates)
```
rois are contain features of the bounding boxes and are corresponding each other, right? 
for example
rois[0] is for bbox[0], and so on. 

this image below is my implementation about it.
![image](https://user-images.githubusercontent.com/32095448/82534819-691b5080-9b78-11ea-8943-2290ab7e22a1.png)

is it good ? or detectron2 already provides some function that can be use to extract features easily.
I want to extract the features and use it as inputs to my object tracker.  

best regards,
Albert Christianto

**Comment by mahsaep** [comment]
> ```python
> from detectron2.modeling import build_backbone
> from detectron2.modeling.poolers import ROIPooler
> backbone = build_backbone(cfg)
> pooler = ROIPooler(...)
> rois = pooler(backbone(NCHW_images), [kx4 tensors])
> ```
> 
> 1. Running inference on a dataset with a RPN-only model will produce the proposals for the dataset in `output/inference`.
>    An example command is
> 
> ```
> python tools/train_net.py --config-file configs/COCO-Detection/rpn_R_50_FPN_1x.yaml --eval-only
> ```
Thanks for the code!
Is the built backbone initialized with pretrained weights?
Cheers,
Mahsa

**Comment by etiennedupont** [comment]
Hi @mahsaep,

1. The backbone when built is initialised randomly.
Basically you can use the model and `DetectionCheckpointer` to load the weights referenced in the config file:
```
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.modeling import build_model

model = build_model(cfg)
checkpointer = DetectionCheckpointer(model)
checkpointer.load(cfg.MODEL.WEIGHTS)
# Now the model (including its backbone) contains the weights in cfg.MODEL.WEIGHTS
backbone = model.backbone
```
2. Yes, the standard workflow used inside the models is below
```
from detectron2.structures import ImageList

# batched_inputs: a list, batched outputs of :class:`DatasetMapper`
images = [x["image"].to(model.device) for x in batched_inputs]
images = [(x - cfg.MODEL.PIXEL_MEAN.pixel_mean) / cfg.MODEL.PIXEL_MEAN.pixel_std for x in images]
images = ImageList.from_tensors(images, model.backbone.size_divisibility)
features = self.backbone(images.tensor)
```

**Comment by mahsaep** [comment]
> Hi @mahsaep,
> 
> 1. The backbone when built is initialised randomly.
>    Basically you can use the model and `DetectionCheckpointer` to load the weights referenced in the config file:
> 
> ```
> from detectron2.checkpoint import DetectionCheckpointer
> from detectron2.modeling import build_model
> 
> model = build_model(cfg)
> checkpointer = DetectionCheckpointer(model)
> checkpointer.load(cfg.MODEL.WEIGHTS)
> # Now the model (including its backbone) contains the weights in cfg.MODEL.WEIGHTS
> backbone = model.backbone
> ```
> 
> 1. Yes, the standard workflow used inside the models is below
> 
> ```
> from detectron2.structures import ImageList
> 
> # batched_inputs: a list, batched outputs of :class:`DatasetMapper`
> images = [x["image"].to(model.device) for x in batched_inputs]
> images = [(x - cfg.MODEL.PIXEL_MEAN) / cfg.MODEL.PIXEL_STD for x in images]
> images = ImageList.from_tensors(images, model.backbone.size_divisibility)
> features = model.backbone(images.tensor)
> ```

Thank you very much!

**Comment by ssd-ls-a** [comment]
@ppwwyyxx 
I want to use the RoI Pooled features from mask head (using Mask R-CNN). How is that possible?

**Comment by ppwwyyxx** [comment]
The tutorial has examples for such questions: https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model

**Comment by ssd-ls-a** [comment]
Thank you very much!

**Comment by asadnorouzi** [comment]
@ppwwyyxx @mahsaep @etiennedupont Thank you for your comments here in this thread. I have an issue getting the features of the predicted masks.

I'm obtaining the  predicted masks from the DefaultPredictor and the features from the model eval as below:

```
self.predictor = DefaultPredictor(cfg)
self.model = build_model(cfg)

outputs = self.predictor(input_img)
masks = np.asarray(outputs['instances'].pred_masks.to("cpu")
pred_boxes = np.asarray(outputs['instances'].pred_boxes.to("cpu")
class_ids = ...
scores = ...

inputs = [{"image": image, "height": height, "width": width}]
self.model.eval()
with torch.no_grad():
     images = self.model.preprocess_image(inputs)
     features = self.model.backbone(images.tensor)
     proposals, _ = self.model.proposal_generator(images, features)
     instances, _ = self.model.roi_heads(images, features, proposals)
     mask_features = [features[f] for f in self.model.roi_heads.in_features)
     mask_features = self.model.roi_heads.mask_pooler(mask_features, [x.pred_boxes for x in instances])
```

What would be the correct way to get the features of the predicted masks corresponding to the original image size? In other words, get the pixel-wise features for each masked region.

I have another question regarding the behavior of the model in evaluation mode. The number of proposals varies at every run. This is OK, but sometimes it's 0! How does the model make predictions without any proposal? This doesn't happen in the DefaultPredictor. It only happens when model eval is used to retrieve the features.

**Comment by zhangliyun9120** [comment]
> Hi,
> 
> for everybody how is interested in feature extraction for bounding boxes. There is a fork of this repo with example code. https://github.com/airsplay/py-bottom-up-attention

@ppwwyyxx @Programmnix 
hello， I use this but got a problem：

torch.nn.modules.module.ModuleAttributeError: 'StandardROIHeads' object has no attribute 'shared_roi_transform'

code is：

        # 1, Get W and H of raw image input
        raw_height, raw_width = raw_image.shape[:2]
        print("Original image size: ", (raw_height, raw_width))

        # 2, Preprocessing raw image
        image = predictor.aug.get_transform(raw_image).apply_image(raw_image)  # transform the W and H of raw image
        print("Transformed image size: ", image.shape[:2])
        image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))  # ndarray to tensor and (h,w,c) to (c,h,w)
        inputs = [{"image": image, "height": raw_height, "width": raw_width}]
        images = predictor.model.preprocess_image(inputs)  # get a ImageList of Detectron2

        # 3, Get feature of backbone via FPN
        features = predictor.model.backbone(images.tensor)
        print("Backbone Features:", features)  # a dict for backbone feature (p2, p3, p4, p5, p6) layers

        # 4, Get proposals feature of proposal_generator via RPN
        proposals, _ = predictor.model.proposal_generator(images, features)  # list proposed boxes for image regions
        print("Generate proposals via RPN:", proposals)

        # 5, Run RoI head for each proposal (RoI Pooling + Res5)
        proposal_boxes = [x.proposal_boxes for x in proposals]
        features = [features[f] for f in predictor.model.roi_heads.in_features]
        box_features = predictor.model.roi_heads._shared_roi_transform(      ###### problem!!!!
            features, proposal_boxes
        )

How can I solve this？ thank you.

@ppwwyyxx  And I think as the partial code is more suitable to extract the fixed size RoI feature as you mentioned :

from detectron2.modeling import build_backbone
from detectron2.modeling.poolers import ROIPooler
backbone = build_backbone(cfg)
pooler = ROIPooler(...)
rois = pooler(backbone(NCHW_images), [kx4 tensors])

Could you provide a more detail code based on this?
Thank you very much.

**Comment by ssd-ls-a** [comment]
Hello, how can I get RoI Pooled features from mask head before the second stage?
