### ISSUE TITLE
Does detectron2 supports custom dataset training for panoptic segmentation ?

### ISSUE THREAD

**Issue by rsrikanth314** [facebookresearch/detectron2#5007]
While going through the issues related to panoptic segmentation in this repo. Many cases it was written that panoptic segmentation custom dataset training is not supported. Would like to know whether is it supported or not ?

**Comment by satishjasthi** [comment]
Hi @rsrikanth314 

You can use detecton2 to train on panoptic segmentation tasks with custom data as long as you can register your custom data in the format mentioned in the Standard Dataset Dicts section in the [documentation](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html)
