### ISSUE TITLE
Error: cannot import name '_C' on windows 10

### ISSUE THREAD

**Issue by muna-cs** [facebookresearch/detectron2#501]
I get the following error
**cannot import name '_C'**

> Traceback (most recent call last):
>   File "D:/detectron2-master(1)/detectron2-master/demo/demo.py", line 12, in <module>
>     from detectron2.data.detection_utils import read_image
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\data\__init__.py", line 4, in <module>
>     from .build import (
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\data\build.py", line 13, in <module>
>     from detectron2.structures import BoxMode
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\structures\__init__.py", line 2, in <module>
>     from .boxes import Boxes, BoxMode, pairwise_iou
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\structures\boxes.py", line 8, in <module>
>     from detectron2.layers import cat
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\layers\__init__.py", line 3, in <module>
>     from .deform_conv import DeformConv, ModulatedDeformConv
>   File "D:\detectron2-master(1)\detectron2-master\detectron2\layers\deform_conv.py", line 10, in <module>
>     from detectron2 import _C
> ImportError: cannot import name '_C'

## Environment

--------------------------------------------------------------------------------------------------------

> sys.platform           win32
> Python                 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
> Numpy                  1.17.4
> detectron2._C          failed to import
> DETECTRON2_ENV_MODULE  <not set>
> PyTorch                1.3.1
> PyTorch Debug Build    False
> torchvision            0.4.2
> CUDA available         True
> GPU 0                  GeForce GTX 1060
> CUDA_HOME              C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
> NVCC                   Not Available
> Pillow                 6.2.1
> cv2                    4.0.0

--------------------------------------------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
You need to build and install detectron2.

Example commands for linux/macOS are in https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#build-detectron2. We do not provide support for windows. Users in #9 have tried in on windows.
