### ISSUE TITLE
`PIL.Image.LINEAR` no longer exists

### ISSUE THREAD

**Issue by ydshieh** [facebookresearch/detectron2#5010]
`Pillow 10.0.0` is released on July 1. 

The previous warning
```
`LINEAR` is deprecated and will be removed in Pillow 10 (2023-07-01). Use BILINEAR or Resampling.BILINEAR instead. 
```
is now an exception.

In `detectron2`, there are still usage of `PIL.Image.LINEAR`, fro example, 

(https://github.com/facebookresearch/detectron2/blob/67ac149947124670f6678e1bdd75f89dbf0dd5e7/detectron2/data/transforms/transform.py#L46)

It would be great if such usage could be updated to avoid failure. Thank you 🙏

**Comment by ydshieh** [comment]
cc @ppwwyyxx

**Comment by rayryeng** [comment]
The latest commit to `master` (as of July 10, 2023) has now fixed this error and has corrected it to `Image.BILINEAR`. This should no longer be an issue now: https://github.com/facebookresearch/detectron2/commit/ff53992b1985b63bd3262b5a36167098e3dada02

**Comment by ydshieh** [comment]
Thanks! Do you have a plan for a release, even a minor version?

**Comment by rayryeng** [comment]
The change has been committed to the mainline so you should be able to install directly from Git and pip.

**Comment by Aman-Preet-Singh-Gulati** [comment]
I'm still facing this issue -> AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

**Comment by rayryeng** [comment]
> I'm still facing this issue -> AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
> cc: @rayryeng 

Try installing at the point where the rides it:

`python3 -m pip install -U 'git+https://github.com/facebookresearch/detectron2.git@ff53992b1985b63bd3262b5a36167098e3dada02'`

**Comment by Moltes74** [comment]
Hi,

I still have this issue but I don't figure out how to fix it ... Can someone help me ??

**Comment by MelindaDong** [comment]
Hi, I'm facing the same issue, "AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
And can't install 'python3 -m pip install -U 'git+https://github.com/facebookresearch/detectron2.git@ff53992b1985b63bd3262b5a36167098e3dada02'' properly, there is error 'ModuleNotFoundError: No module named 'torch''

BUT I do have torch=2.0.1 and pip=23.2.1.

**Comment by Rabbitzzc** [comment]
> Hi, I'm facing the same issue, "AttributeError: module 'PIL.Image' has no attribute 'LINEAR' And can't install 'python3 -m pip install -U 'git+https://github.com/facebookresearch/detectron2.git@ff53992b1985b63bd3262b5a36167098e3dada02'' properly, there is error 'ModuleNotFoundError: No module named 'torch'' BUT I do have torch=2.0.1 and pip=23.2.1.
> 
> Fixed by downgrade 'pillow=9.1.0'

just run `pip3 install torch`

**Comment by lcc815** [comment]
run `pip install pillow==9.5.0` will solve this problem.

**Comment by hiepbk** [comment]
> run `pip install pillow==9.5.0` will solve this problem.

Right, It works.
