### ISSUE TITLE
what will happen without pretrained models during training?

### ISSUE THREAD

**Issue by FanShuixing** [facebookresearch/detectron2#502]
Hi. Thanks for your work.I have a question about the usage of pretrained model.I noticed that there is a pretrained model in configs/xxx.yaml, and I don't know where or how did these pretrained model produced? If I don't use these pretrained model, is there  some parameter should be updated(example:lr,max_iter)?

**Comment by ppwwyyxx** [comment]
> I don't know where or how did these pretrained model produced

https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models

> If I don't use these pretrained model, is there some parameter should be updated(example:lr,max_iter

That's a general question of algorithms that's not specific to detectron2, so we do not answer. You can refer to papers such as https://arxiv.org/abs/1811.08883

**Comment by FanShuixing** [comment]
Thanks!
