### ISSUE TITLE
What kind of labeling format does Detectron2 uses?

### ISSUE THREAD

**Issue by frankkim1108** [facebookresearch/detectron2#503]
I am currently trying to train a pre-trained model to increase the accuracy. However, I only have raw picture data. What format do I have to label this data to make it trainable? Are there any papers for detectron 2?

**Comment by ppwwyyxx** [comment]
There is a full example in https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
