### ISSUE TITLE
Proper way to do inference in fp16 mode

### ISSUE THREAD

**Issue by ArtificialNotImbecile** [facebookresearch/detectron2#504]
## ❓ How to use Detectron2
`predictor.model.half(); predictor(image)` will throw `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same.`  

So I have to , in retinanet, for example, change [`features = self.backbone(images.tensor)`](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/retinanet.py#L130) to `features = self.backbone(images.tensor.half())` manually. This works but it modifies the source code. 

Are there any other ways to set the input image type? Tried change  `image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))` to `image = torch.as_tensor(image.astype("float16").transpose(2, 0, 1))`  in `DefaultPredictor` but didn't work
`

**Comment by Ishaan28malik** [comment]
Is this being assigned to anyone?
And is the input image is only needed to be set or `features = self.backbone(images.tensor.half())` is also required to be changed?
@ppwwyyxx

**Comment by ppwwyyxx** [comment]
1. no. we don't have plans to work on this very soon.
2. no

**Comment by azuryl** [comment]
@ppwwyyxx do you have method  which transfer the model to int8 
thank you

**Comment by ppwwyyxx** [comment]
We convert models to int8 for deployment, but no promise on when it will be open source (maybe in a few months).

**Comment by azuryl** [comment]
@ppwwyyxx  can you open RetinaNet R50 let us try it

**Comment by azuryl** [comment]
or can you convert the RetinaNet R50 to ONNX format ,then I use another tools to quantz

**Comment by ArtificialNotImbecile** [comment]
I end up using apex for mixed-precision inference. The accuracy is comparable with fp32 mode while utilizing less GPU memory(also a little bit faster).

**Comment by iradpeleg** [comment]
> ## ❓ How to use Detectron2
> `predictor.model.half(); predictor(image)` will throw `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same.`
> 
> So I have to , in retinanet, for example, change [`features = self.backbone(images.tensor)`](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/retinanet.py#L130) to `features = self.backbone(images.tensor.half())` manually. This works but it modifies the source code.
> 
> Are there any other ways to set the input image type? Tried change `image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))` to `image = torch.as_tensor(image.astype("float16").transpose(2, 0, 1))` in `DefaultPredictor` but didn't work
> `

Is there a solution for inference in fp16 mode?
I’m using faster_rcnn_R_50_FPN and got the same RuntimeError.
also tried to convert the input with image.half().
when running self.normalizer() in class GeneralizedRCNN the input is converted back to 32bit.
this forced me to modify source code.
self.backbone(images.tensor.half()) works for me as well but only for the backbone.
results, _ = self.roi_heads(images, features, proposals, None) did not work no matter what.
even after setting all arguments to half precision.


see error message:
RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type Variable[CUDAFloatType] does not equal Variable[CUDAHalfType] (while checking arguments for ROIAlign_forward_cuda) (checkSameType at /pytorch/aten/src/ATen/TensorUtils.cpp:140)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fb5e8549813 in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: at::checkSameType(char const*, at::TensorArg const&, at::TensorArg const&) + 0x1e2 (0x7fb579fcc2f2 in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: at::checkAllSameType(char const*, c10::ArrayRef<at::TensorArg>) + 0x3e (0x7fb579fcc51e in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libtorch.so)

ideally, I would like to solve it without touching detectron2/modeling/meta_arch/rcnn.py
is it possible?
Thanks

**Comment by ArtificialNotImbecile** [comment]
> > ## ❓ How to use Detectron2
> > `predictor.model.half(); predictor(image)` will throw `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same.`
> > So I have to , in retinanet, for example, change [`features = self.backbone(images.tensor)`](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/retinanet.py#L130) to `features = self.backbone(images.tensor.half())` manually. This works but it modifies the source code.
> > Are there any other ways to set the input image type? Tried change `image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))` to `image = torch.as_tensor(image.astype("float16").transpose(2, 0, 1))` in `DefaultPredictor` but didn't work
> > `
> 
> Is there a solution for inference in fp16 mode?
> I’m using faster_rcnn_R_50_FPN and got the same RuntimeError.
> also tried to convert the input with image.half().
> when running self.normalizer() in class GeneralizedRCNN the input is converted back to 32bit.
> this forced me to modify source code.
> self.backbone(images.tensor.half()) works for me as well but only for the backbone.
> results, _ = self.roi_heads(images, features, proposals, None) did not work no matter what.
> even after setting all arguments to half precision.
> 
> see error message:
> RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type Variable[CUDAFloatType] does not equal Variable[CUDAHalfType] (while checking arguments for ROIAlign_forward_cuda) (checkSameType at /pytorch/aten/src/ATen/TensorUtils.cpp:140)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fb5e8549813 in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libc10.so)
> frame #1: at::checkSameType(char const*, at::TensorArg const&, at::TensorArg const&) + 0x1e2 (0x7fb579fcc2f2 in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libtorch.so)
> frame #2: at::checkAllSameType(char const*, c10::ArrayRefat::TensorArg) + 0x3e (0x7fb579fcc51e in /opt/conda/envs/torch131/lib/python3.6/site-packages/torch/lib/libtorch.so)
> ...
> 
> ideally, I would like to solve it without touching detectron2/modeling/meta_arch/rcnn.py
> is it possible?
> Thanks

Try apex, it works out of the box
