### ISSUE TITLE
FloatingPointError: Loss became infinite or NaN at iteration=27（Possible problem）

### ISSUE THREAD

**Issue by chenjun19950315** [facebookresearch/detectron2#508]
When I trained my datasets for object detection, I got the following error：
FloatingPointError: Loss became infinite or NaN at iteration=27!
loss_dict = {'loss_cls': tensor(nan, device='cuda:0', grad_fn=), 'loss_box_reg': tensor(0.2576, device='cuda:0', grad_fn=)}

Possible problem：I use the default WarmupMultiStepLR，and My successful training model when cfg.SOLVER.BASE_LR = 0.001，but set to 0.02，I got the above error.Maybe the learning rate is too large?

Question:Where is the entrance to the definition of the network(eg,faster rcnn-FPN-101),I just find
def build_model(cfg):
    """
    Built the whole model, defined by `cfg.MODEL.META_ARCHITECTURE`.
    """
    meta_arch = cfg.MODEL.META_ARCHITECTURE
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
Where should I look at the flow of the network,Thank you

**Comment by ppwwyyxx** [comment]
The training diverges.

The model is implemented in https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/rcnn.py
