### ISSUE TITLE
Trying to use the densepose result to measure chest girth or hip girth.

### ISSUE THREAD

**Issue by frankkim1108** [facebookresearch/detectron2#511]
I have two questions.
### **1. How do I utilize U,V coordinates to measure human body sizes?**

I got the U,V coordinates from running apply_net.
What I want to do next is use these U,V coordinates to measure human body sizes, 
such as chest girth or hip girth.
I followed a tutorial where I applied the coordinates to a SMPL model.
I am trying to measure the perimeter(circumference) of a specific area of the 3D model to get the measurements such as chest girth or hip girth. 
Could you give me any hints on how to do this? Or is there a better way to measure human body sized with Detectron2?

### **2. How to get a matching SMPL model to match the person in the picture.**

I used apply_net to get the U,V coordinates.
I only saw tutorials using these coordinates and apply them on a 3D SMPL model. But I could choose which model to use. It only used a default male model. Is there a way to choose the model to match the person in the picture?

**Comment by frankkim1108** [comment]
@ppwwyyxx Can anyone give me some advice please?

**Comment by ppwwyyxx** [comment]
Such feature is not provided in this project.
Since you seem to have successfully obtained outputs of our models, how to use these outputs to implement other algorithms is out of the scope of this project.
I am not familiar with densepose and could not give any personal suggestions either.

**Comment by prathamsss** [comment]
how did you solved this?

**Comment by prathamsss** [comment]
@frankkim1108
