### ISSUE TITLE
Unable To Fix "no kernel image is available for execution" Error

### ISSUE THREAD

**Issue by SamuelJakes** [facebookresearch/detectron2#512]
I'm unable to fix this error, despite following the recommended fix documented in the INSTALL.md under common issues. I have tried setting my Compute Capability via TORCH_CUDA_ARCH_LIST to the recommended value for my processor (3.5), found at https://developer.nvidia.com/cuda-gpus. I also only have 1 version of CUDA installed, so I don't think the error could be arising from "You build detectron2 with one version of CUDA but run it with a different version", as per the INSTALL.md. I cannot find any information to make progress on this issue. 

## Instructions To Reproduce the Issue

1. Changes I Made
```
The only change I have made to the code is in the demo.py file at line 105, I changed:
cam = cv2.VideoCapture(0)
To:
cam = cv2.VideoCapture(4)
To get the video to work with my particular webcam. (Intel Realsense D435)
```
2. The Command I Run:

python3 demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --webcam   --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

3. Observed Error:
```
[12/12 12:29:16 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=True)
WARNING [12/12 12:29:16 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
0it [00:00, ?it/s]Traceback (most recent call last):
  File "demo/demo.py", line 106, in <module>
    for vis in tqdm.tqdm(demo.run_on_video(cam)):
  File "/home/jssl/.local/lib/python3.6/site-packages/tqdm/std.py", line 1102, in __iter__
    for obj in iterable:
  File "/home/jssl/.local/share/Trash/files/detectron2/demo/predictor.py", line 129, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/jssl/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/jssl/detectron2/detectron2/engine/defaults.py", line 188, in __call__
    predictions = self.model([inputs])[0]
  File "/home/jssl/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jssl/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 66, in forward
    return self.inference(batched_inputs)
  File "/home/jssl/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 114, in inference
    images = self.preprocess_image(batched_inputs)
  File "/home/jssl/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 147, in preprocess_image
    images = [self.normalizer(x) for x in images]
  File "/home/jssl/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 147, in <listcomp>
    images = [self.normalizer(x) for x in images]
  File "/home/jssl/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 39, in <lambda>
    self.normalizer = lambda x: (x - pixel_mean) / pixel_std
RuntimeError: CUDA error: no kernel image is available for execution on the device
0it [00:00, ?it/s]

```

## Environment

------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     GeForce GT 730
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
TORCH_CUDA_ARCH_LIST      3.5
Pillow                    6.2.1
cv2                       4.1.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
> NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37

This is from the pytorch built information. Your GPU is too old and the pytorch version you're using does not contain 3.5. You may need to build pytorch yourself.
