### ISSUE TITLE
Error with installing pyyaml==5.1

### ISSUE THREAD

**Issue by Frn1nd0** [facebookresearch/detectron2#5122]
Hi everyone, I got issues with running this code in google colab:

!python -m pip install pyyaml==5.1
import sys, os, distutils.core
!git clone 'https://github.com/facebookresearch/detectron2'
dist = distutils.core.run_setup("./detectron2/setup.py")
!python -m pip install {' '.join([f"'{x}'" for x in dist.install_requires])}
sys.path.insert(0, os.path.abspath('./detectron2'))

The output always show:

Collecting pyyaml==5.1
  Downloading PyYAML-5.1.tar.gz (274 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.2/274.2 kB 5.0 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Cloning into 'detectron2'...

I am still new to python, detectron2, object detection, all these areas, so, I have no idea on what is happening here, can someone please guide me? Thanks

**Comment by Rusab** [comment]
Facing the same issue

**Comment by nourhan142** [comment]
did you know how to solve this issue

**Comment by rmast** [comment]
The issue is the pyyaml build fails with a reference to an outdated setup-procedure. If you add -vvv to the pip command it will show on your screen. Why does detectron2 depend on that old pyyaml? There is a newer one already availabe in colab.

**Comment by rmast** [comment]
pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==5.1
seems to work with Python 3.10.

**Comment by Rusab** [comment]
I was running on Colab. I fixed the issue by using the preinstalled pyyaml version which is 6.0.1

**Comment by rmast** [comment]
If pyyaml 6.0.1 is allowed then the colab-tutorial referred to on this page should be updated, as it now explicitly installs a fixed version 5.1:

https://detectron2.readthedocs.io/en/latest/tutorials/install.html


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
