### ISSUE TITLE
A bug in HFlip of densepose annotation process

### ISSUE THREAD

**Issue by wangxuanhan** [facebookresearch/detectron2#513]
Please see line 160 in projects/DensePose/densepose/structures.py
(1) The gt UV coordinates do not change when i is 0 or 1, which indicates that gt UV of class 'torso' is kept same when HFLIP is done.
(2) This will lead to V_loss is much higher than U_loss, which makes it hard to reproduce the results in model zoo.
(3) To fix it, simply change the condition "pt_label_symmetries[i + 1] != i + 1"  to "i + 1 in self.i" , which is consistent to implementations in DensePose-1.
----------------------------------------------------------------------------------------------------------------

**Comment by vkhalidov** [comment]
Dear @wangxuanhan 

Thanks for looking into the code! I do not understand what is the problem you report here. `point_label_symmetries` is a list that contains target labels `j` for each source label `i` under "left-right flip" symmetry transform. Labels can be `0` (=background) or `1-24` (=part indices). Line 160 contains a check whether part index `i+1` is changed under the symmetry transform. Background labels `0` are skipped. Torso has 2 corresponding labels: 1 (=back) and 2 (=front). These labels are indeed invariant under left-right flip symmetry transform. I'm not sure I understand the implication with losses.

Could you please give some more details on the bug you encountered?

**Comment by wangxuanhan** [comment]
Hi @vkhalidov
Surface labels(i.e., gt_I) of "torso" are invariant under left-right flip symmetry transform. But the UV labels(i.e., gt_V) of "torso" should be changed under left-right flip symmetry transform.

**Comment by vkhalidov** [comment]
Dear @wangxuanhan ,
UV labels are treated on [lines 165-166](https://github.com/facebookresearch/detectron2/blob/master/projects/DensePose/densepose/structures.py#L165) of the same file (method `_flip_iuv_semantics`).
Could you please give a concrete example where the symmetry transform does not give the result you expect?

**Comment by vkhalidov** [comment]
OK, I see. The condition on line 160 prevents UV coordinates flipping for parts with flip-invariant labels. Thanks for reporting this!

**Comment by ppwwyyxx** [comment]
fixed in 5ac96b29155d6b27811e0c83b9054e8d735d56b4.
this seems to give an improvement of 1~2 densepose AP.
