### ISSUE TITLE
Detectro 2 deployment inference interpretation

### ISSUE THREAD

**Issue by blackHorz** [facebookresearch/detectron2#5156]
I have tried to replicate the torchscript C++ inference file into Python. I am getting the results similar to what is expected. However I am not sure on how to map my pred_masks over my original image size.

Which C++ script i am talking about.
https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/torchscript_mask_rcnn.cpp

How did i export my model to .ts
https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/export_model.py

Which method I have used (scripting)

The output of the pred_masks is (batch_size, 1, 28, 28). Whereas original image size was 2048x2448, which i resize to 800x1333.

How can i get the masks that corresponds to my original image size?

1. Full runnable code or full changes you made:
```
def get_scripting_inputs(img, device):
    height, width, channels = img.shape
    print("DEBUG 1 : ", height, width, channels)
    #img_tensor = torch.from_numpy(img).view(height, width, channels).to(torch.uint8)
    img_tensor = torch.from_numpy(img).view(height, width, channels).to(torch.float32)
    img_tensor = img_tensor.to(device, torch.float).permute(2, 0, 1).contiguous()

    dic = {'image': img_tensor}
    return (dic,)

class MaskRCNNOutputs:
    def __init__(self, pred_boxes, pred_classes, pred_masks, scores):
        self.pred_boxes = pred_boxes
        self.pred_classes = pred_classes
        self.pred_masks = pred_masks
        self.scores = scores

    def num_instances(self):
        return self.pred_boxes.size(0)

def get_outputs(outputs):
    out_dict = outputs[0]
    return MaskRCNNOutputs(out_dict['pred_boxes'], out_dict['pred_classes'], out_dict['pred_masks'], out_dict['scores'])

def main():


    image_file = 'TOP.png'

    #fusion_strategy = {torch.jit.FusionType.DYNAMIC: 1}
    torch.jit._set_fusion_strategy([("DYNAMIC", 2)])
    torch.set_grad_enabled(False)

    module = torch.jit.load('D:\\AI\\Research\\YOLOV8\\n_o\\model.ts')
    assert len(list(module.buffers())) > 0

    # Assume that the entire model is on the same device.
    # We just put input to this device.
    device = list(module.buffers())[0].device

    input_img = cv2.imread(image_file, cv2.IMREAD_COLOR)
    input_img = cv2.resize(input_img,(1333,800), interpolation=cv2.INTER_LINEAR)
    inputs = get_scripting_inputs(input_img, device)

    # Run the network
    output = module.forward(inputs)
    if torch.cuda.is_available():
        torch.cuda.current_stream().synchronize()

    # Run 3 more times to benchmark
    N_benchmark, N_warmup = 3, 1

    for i in range(N_benchmark + N_warmup):
        output = module.forward(inputs)
        if torch.cuda.is_available():
            torch.cuda.current_stream().synchronize()



    # Parse Mask R-CNN outputs
    rcnn_outputs = get_outputs(output)
    print("Number of detected objects:", rcnn_outputs.num_instances())
    print("pred_boxes:", rcnn_outputs.pred_boxes, rcnn_outputs.pred_boxes.size())
    print("scores:", rcnn_outputs.scores, rcnn_outputs.scores.size())
    print("pred_classes:", rcnn_outputs.pred_classes, rcnn_outputs.pred_classes.size())
    print("pred_masks:", rcnn_outputs.pred_masks, rcnn_outputs.pred_masks.size())
```

**Comment by kirillmeisser** [comment]
Hi @blackHorz,

I'm also challenged by the export of a fine-tuned object detection Detectron2 model. Your script really helped me solve a problem. However, in my case, my model does not want a dictionary as input (just the image as a Tensor) and it also does not output a dictionary of outputs but a tuple that looks like this:
```
(tensor([[377.6366, 397.9915, 779.1143, 561.9951], [550.6393, 388.4034, 778.9048, 546.3689]], grad_fn=<IndexBackward0>), tensor([0, 0]), tensor([0.9840, 0.0890], grad_fn=<IndexBackward0>), tensor([1527,  990]))
```

Do you know how you managed to get the model to accept input and output in the dictionary format? It seems to match the documented behavior, whereas mine does not.

To answer your question, can it be that the masks are relative to the bounding box origin (top-left point of the bounding box)? I have also noticed that you do not have to resize the image if you do not want to. In that case, Detectron2 will output the coordinates in the unresized image dimensions. However, in that case, as I understood, larger images will require longer computation.
