### ISSUE TITLE
 Problems with installing detectron2

### ISSUE THREAD

**Issue by xwcUP** [facebookresearch/detectron2#5162]
When I execute the following code in the terminal

![1](https://github.com/facebookresearch/detectron2/assets/150986190/008f66be-13f5-4855-afda-1be70a26d74d)
happening：
![image](https://github.com/facebookresearch/detectron2/assets/150986190/ed0a3ef0-5a10-4be4-acc2-bb6160545475)

**Comment by oktaysabak** [comment]
Same issue here:
```bash
❯ pip install 'git+https://github.com/facebookresearch/detectron2.git'
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/22/sxp0ryq923s3qz4_fx4jxg_h0000gn/T/pip-req-build-4r3x2713
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/22/sxp0ryq923s3qz4_fx4jxg_h0000gn/T/pip-req-build-4r3x2713
  Resolved https://github.com/facebookresearch/detectron2.git to commit 017abbfa5f2c2a2afa045200c2af9ccf2fc6227f
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: -11
  ╰─> [0 lines of output]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by gau-nernst** [comment]
I found the solution. Install the corresponding NVCC (CUDA compiler) and CUDA development libraries from conda

```bash
conda install "cuda-nvcc==11.8.*" "cuda-libraries-dev==11.8.*" -c nvidia
```

Make sure the version matches your PyTorch CUDA version.

**Comment by lenguyen2592004** [comment]
> I found the solution. Install the corresponding NVCC (CUDA compiler) and CUDA development libraries from conda
> 
> ```shell
> conda install "cuda-nvcc==11.8.*" "cuda-libraries-dev==11.8.*" -c nvidia
> ```
> 
> Make sure the version matches your PyTorch CUDA version.

When I install it, I got this bug 
![image](https://github.com/user-attachments/assets/97261c6e-cae2-4b5b-bcdd-80ac784a598b)

**Comment by gau-nernst** [comment]
My solution was using conda, not pip

**Comment by lenguyen2592004** [comment]
> My solution was using conda, not pip

I edited my command and it could installed nvidia but when I install the github link, I got this bug. What should I do?
![image](https://github.com/user-attachments/assets/24b853da-006e-4e6c-b7a4-c99f3e48e81c)

**Comment by gau-nernst** [comment]
Downgrade your numpy, just like the errors say

```
pip install "numpy==1.24"
```
