### ISSUE TITLE
Please provide some examples of use 

### ISSUE THREAD

**Issue by krzysztoffiok** [facebookresearch/detectron2#517]
Dear Sirs,

i managed to install at my local machine and launch the inference example provided at https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=HUjkwRsOn1O0

Unfortunately i have trouble using different models than the one provided in this example. I'm aware of the config files here https://github.com/facebookresearch/detectron2/tree/master/configs and model files here https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md but somehow i cannot make them working.

I'm interested particularly in the ones trained on Imagenet so i'd like to use e.g. https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/FAIR/X-101-32x8d.pkl model.

I understand i always have to use the cfg.merge_from_file() and cfg.MODEL.WEIGHTS commands right? But probably i provide wrong arguments.

Any help will be appreciated. Thank you.

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by krzysztoffiok** [comment]
Ok, so here are the details:

1. the whole code i'm using is derived from your colab tutorial:

import torch, torchvision
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()
import numpy as np
import cv2
import random
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
import pandas as pd

# read images
images = []
images.append(cv2.imread("./input.jpg"))

# model config and weights
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml")

cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl"

# define predictor and output df
predictor = DefaultPredictor(cfg)
result = pd.DataFrame(columns=["class_ids"])

# predict and create results
for num, im in enumerate(images):
    outputs = predictor(im)
    classes = outputs["instances"].pred_classes
    boxes = outputs["instances"].pred_boxes
    scores = outputs["instances"].scores
    result.loc[num] = [classes.tolist()]

# save results
result.to_excel("results.xlsx")

--- end of code---

2. i called this python code t1.py so i run this simply with python3 t1.py

3. i observe:
WARNING [12/13 03:24:51 d2.config.compat]: Config './detectron2_repo/configs/Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml' has no VERSION. Assuming it to be compatible with latest v2.

here there is a lot of information like (i can't print it all it's too much space):
"[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.res5.2.conv2.norm.weight          loaded from res5_2_branch2b_bn_s        of shape (2048,)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.res5.2.conv2.weight               loaded from res5_2_branch2b_w           of shape (2048, 64, 3, 3)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.res5.2.conv3.norm.bias            loaded from res5_2_branch2c_bn_b        of shape (2048,)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.res5.2.conv3.norm.weight          loaded from res5_2_branch2c_bn_s        of shape (2048,)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.res5.2.conv3.weight               loaded from res5_2_branch2c_w           of shape (2048, 2048, 1, 1)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.stem.conv1.norm.bias              loaded from res_conv1_bn_b              of shape (64,)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.stem.conv1.norm.weight            loaded from res_conv1_bn_s              of shape (64,)
[12/13 03:28:01 d2.checkpoint.c2_model_loading]: backbone.bottom_up.stem.conv1.weight                 loaded from conv1_w                     of shape (64, 3, 7, 7)
"

later

[12/13 03:24:55 d2.checkpoint.c2_model_loading]: Some model parameters are not in the checkpoint:
( a very long list of parameters) like:
roi_heads.box_head.2.conv3.norm.{bias, weight}
  roi_heads.box_head.2.conv3.weight
  roi_heads.box_head.2.conv4.norm.{bias, weight}
  roi_heads.box_head.2.conv4.weight
  roi_heads.box_head.2.fc1.{bias, weight}
  roi_heads.box_predictor.0.bbox_pred.{bias, weight}
  roi_heads.box_predictor.0.cls_score.{bias, weight}
  roi_heads.box_predictor.1.bbox_pred.{bias, weight}
  roi_heads.box_predictor.1.cls_score.{bias, weight}
  roi_heads.box_predictor.2.bbox_pred.{bias, weight}
  roi_heads.box_predictor.2.cls_score.{bias, weight}
  roi_heads.mask_head.deconv.{bias, weight}
  roi_heads.mask_head.mask_fcn1.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn1.weight
  roi_heads.mask_head.mask_fcn2.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn2.weight
  roi_heads.mask_head.mask_fcn3.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn3.weight
  roi_heads.mask_head.mask_fcn4.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn4.weight
  roi_heads.mask_head.mask_fcn5.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn5.weight
  roi_heads.mask_head.mask_fcn6.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn6.weight
  roi_heads.mask_head.mask_fcn7.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn7.weight
  roi_heads.mask_head.mask_fcn8.norm.{bias, weight}
  roi_heads.mask_head.mask_fcn8.weight
  roi_heads.mask_head.predictor.{bias, weight}


[12/13 03:25:53 d2.checkpoint.c2_model_loading]: The checkpoint contains parameters not used by the model:
  pred_b
  pred_w

---execution stops---

4. environment:

sys.platform              linux
Python                    3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]
Numpy                     1.17.4
Detectron2 Compiler       GCC 9.2
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     TITAN RTX
CUDA_HOME                 /usr
NVCC                      Cuda compilation tools, release 10.1, V10.1.168
Pillow                    6.2.1
cv2                       4.1.2
------------------------  -----------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

I hope this is all information you need. Thanks for help.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says:

> Expected behavior
If there are no obvious error in "what you observed" provided above, please tell us the expected behavior.

There is no error in your logs and I don't know what you expected.

**Comment by krzysztoffiok** [comment]
Well there is no prediction going on (or it finds no objects). If i use the colab example config and weights, i get my predictions (this is the colab example image im inferring so there are some people, horse, umbrella...).

**Comment by ppwwyyxx** [comment]
You need to find the corresponding model for a config from the tables in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#other-settings. The correct URL is https://dl.fbaipublicfiles.com/detectron2/Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv/18131413/model_0039999_e76410.pkl.

**Comment by krzysztoffiok** [comment]
Yes, it works now.

I guess i found some wrong model url's.

But i understand this is still a MS CoCo trained model? Can i ask for an example model trained on imagenet + config (correct urls)? I'm looking for a model that outputs more classes than in MS CoCo.

Thank you.

**Comment by ppwwyyxx** [comment]
The wrong link you used is from https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#imagenet-pretrained-models and as it says it is trained on imagenet.

However imagenet is not a detection dataset and detectron2 does not have code to use it.
