### ISSUE TITLE
Drop classes found within a class for panoptic segmentation

### ISSUE THREAD

**Issue by joehoeller** [facebookresearch/detectron2#518]
## ❓ How to use Detectron2

Lets say I want to ID roads and boulevards, and all the boulevards have grass on them, while roads are cement/gray colored (to make this simple). 

How do I make it drop, or simply not search the areas ID'd as boulevards (regions of interest) for other classes that might be found within that segmentation of boulevards.

[class boulevard[nested classes -> drop]]
[class road[nested classes -> ID -> stop sign, traffic light, people, etc]]

**Comment by ppwwyyxx** [comment]
Post processing heuristics for panoptic FPN is implemented in https://github.com/facebookresearch/detectron2/blob/31696514cb92fab66e2c154be0d2c0ecd63ee823/detectron2/modeling/meta_arch/panoptic_fpn.py#L119-L127.
You'll need to write your custom version of it to implement your strategies.

**Comment by joehoeller** [comment]
Thanks for the tip!
