### ISSUE TITLE
a problem about perdicted uv coordinates 

### ISSUE THREAD

**Issue by uyzhang** [facebookresearch/detectron2#522]
when I reappeared the paper's (https://arxiv.org/pdf/1905.08776.pdf) result, the problem about DensePose appeared.
There are the results when I used DensePose to infer.
I used the model downloaded from the Model zoo, url(https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x/143908726/model_final_ad63b5.pkl)

the images:
![hd_00_00_10750](https://user-images.githubusercontent.com/26193836/70786090-ce4b6880-1dc6-11ea-82ee-5b7c4f24544a.jpg)
![hd_00_00_10765](https://user-images.githubusercontent.com/26193836/70786144-ecb16400-1dc6-11ea-8b81-f753996f12dd.jpg)

the v coordinate results show:
![10750 0001](https://user-images.githubusercontent.com/26193836/70782143-575fa100-1dc1-11ea-95b5-004b95a45c29.jpg)
![10765 0001](https://user-images.githubusercontent.com/26193836/70782173-5b8bbe80-1dc1-11ea-98d5-77f4ebda90b8.jpg)

the textures that get using densepose results and images:
![ts_2](https://user-images.githubusercontent.com/26193836/70782229-752d0600-1dc1-11ea-9335-956e13e68a96.png)
![ts_2(1)](https://user-images.githubusercontent.com/26193836/70782234-7827f680-1dc1-11ea-9478-9a422f51eb1e.png)

So, why can get contrary v coordinate of chest part in the same view？
And, the textures of chest get from uv coordinate and image with the two actions are contrary

**Comment by xduzy16** [comment]
I just used the old model(https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl) in the Model zoo, the problem did not happen again.  So the best model(https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x/143908726/model_final_ad63b5.pkl) has some problems?

**Comment by vkhalidov** [comment]
Dear @xduzy16, the problem with flipped body coordinates has recently been fixed in 5ac96b2, the model zoo will be updated soon.

**Comment by xduzy16** [comment]
thanks!

**Comment by vkhalidov** [comment]
the bug has been fixed in 5ac96b2
the model zoo has been updated on Feb 26 in 7c25819
body coordinates should not be flipped any more
