### ISSUE TITLE
Fine-tune panoptic segmentation model on object detection dataset

### ISSUE THREAD

**Issue by Tixierae** [facebookresearch/detectron2#523]
Is there any way to fine-tune a panoptic segmentation model (e.g., panoptic_fpn_R_101_3x) on an object detection task (not segmentation). So, on a new dataset that features only bounding box annotations?

I'd like to benefit from the nice capabilities of the panoptic segmentation model while also being able to detect new objects.

Thank you in advance, and sorry if my question is stupid or if this is not the best place to ask, I'm a newbie here.

**Comment by ppwwyyxx** [comment]
You can load the old model with `cfg.MODEL.WEIGHTS` to train on new datasets. Though it probably won't have both capabilities. 

If you don't know what exactly you want to do yet, we cannot tell you how.

**Comment by Tixierae** [comment]
Thank you for the quick reply. To clarify: I have a dataset with **bounding box annotations only**. Some of the object categories appear in COCO, but some do not (like the balloon category in the balloon tutorial). I want to train a model that:
* can detect the new object classes
* still be able to recognize the COCO things and stuff categories

(1) Is this possible at all (e.g., via fine-tuning a panoptic model)? If yes, how exactly?
Or, (2) will fine-tuning overwrite all of the previous model prediction capabilities?

If (2), one solution I'm seeing is to call two models on my images in production. My fine-tuned model that can recognize the new objects, and the pre-trained COCO panoptic model. But this is not optimal/elegant.
