### ISSUE TITLE
Unexpected label for background proposals

### ISSUE THREAD

**Issue by k-sokolov** [facebookresearch/detectron2#524]
I think it is worth mentioning somewhere in the docs that now the background proposals have label Nclasses, instead of 0 that was in mrcnn_benchmark or matterport`s maskrcnn. 
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L181

**Comment by ppwwyyxx** [comment]
This is mentioned in https://detectron2.readthedocs.io/notes/compatibility.html.
We could mention maskrcnn-benchmark together with detectron.
