### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device (nms_cuda at /tmp/pip-req-build-9d9zypi6/torchvision/csrc/cuda/nms_cuda.cu:127)

### ISSUE THREAD

**Issue by chenqiang19** [facebookresearch/detectron2#531]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue

1. what changes you made (`git diff`) or what code you wrote
```
I had set TORCH_CUDA_ARCH_LIST when execute setup.py build delelop
 TORCH_CUDA_ARCH_LIST = ALL python setup.py build delelop
```
2. what exact command you run:
3. what you observed (including the full logs):
```
![image](https://user-images.githubusercontent.com/43142884/70858406-b4339680-1f3c-11ea-9369-2f517503f7e6.png)

```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train your model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`,
or use `python detectron2/utils/collect_env.py`
if detectron2 hasn't been successfully installed.

**Comment by chenqiang19** [comment]
![Uploading Selection_001.png…]()

**Comment by chenqiang19** [comment]
![Selection_001](https://user-images.githubusercontent.com/43142884/70858522-556f1c80-1f3e-11ea-857c-88990ec4691c.jpg)

**Comment by ppwwyyxx** [comment]
You have mixed cuda 10.0 and cuda 10.1 in build time or runtime in your environment
