### ISSUE TITLE
Cannot install Detectron2

### ISSUE THREAD

**Issue by Ly-Lynn** [facebookresearch/detectron2#5329]
![image](https://github.com/user-attachments/assets/6b8c220a-5c09-4fb4-92af-d31c37929083)
The problem occurred when I try to `python -m pip install -e detectron2` after cloning the repo.
This is torch and python version
![image](https://github.com/user-attachments/assets/f5c272fb-a200-498a-a6c7-86722510ace5)
Thank you!

**Comment by Programmer-RD-AI** [comment]
Hi,
Please refer to: #5162
Thank You
