### ISSUE TITLE
How does training works in detectron2?

### ISSUE THREAD

**Issue by danielbispov** [facebookresearch/detectron2#535]
## Detectron2 'standard' training

2. How does detectron2 manage to train so fast, like the balloon dataset? More specifically, does detectron2 training method in the tutorial manage to freeze the weights of the detector? Or only from the feature extractor?

**Comment by ppwwyyxx** [comment]
> does detectron2 training method in the tutorial manage to freeze the weights of the detector

It freezes the first two layers of the backbone, a standard practice in object detection.

**Comment by ortegatron** [comment]
Hi @ppwwyyxx , thanks for the answer was useful for me to find the FREEZE_AT CFG. 
Could your mention me where could I read more about this practice? Like ,any paper recommending freezing at stage two?
