### ISSUE TITLE
Unable to install from source code.

### ISSUE THREAD

**Issue by Vawter-001** [facebookresearch/detectron2#5363]
**I tried to install detectron2 by the following code：**
_git clone https://github.com/facebookresearch/detectron2.git
cd detectron2
python setup.py install_

**but I got a error：**
_gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1_

**What should I do  to solve it?**

**Comment by JacobB33** [comment]
Try making sure your gcc and g++ versions are the same. I had to run this: 
sudo apt install gcc-12 g++-12
