### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by Lin-UH** [facebookresearch/detectron2#5364]
Install detectron2 on linux
conda create --prefix ./envs python==3.10
source activate ./envs
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
pip install opencv-python
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2

Run demo 

cd demo/
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

**Get error
from vision.fair.detectron2.demo.predictor import VisualizationDemo
ModuleNotFoundError: No module named 'vision'**

**Comment by yingqichao** [comment]
i encountered the same. how did you resolve it? thx~

**Comment by yfq512** [comment]
> i encountered the same. how did you resolve it? thx~

i encountered the same.  did you resolve it?……

**Comment by shaaaaron** [comment]
Replace the line from `vision.fair.detectron2.demo.predictor import VisualizationDemo` in demo.py with `from predictor import VisualizationDemo`.
Because VisualizationDemo is implemented in predictor.py, maybe a slip here.
