### ISSUE TITLE
demo.py icvExtractPattern

### ISSUE THREAD

**Issue by chenying99** [facebookresearch/detectron2#537]
I run on google colab

run command:

python3 demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
--video-input /content/tiger.mp4 \
--output /content/ \
--opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

throws error:

OpenCV(4.1.2) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /content/tiger.mkv in function 'icvExtractPattern'

no generate tiger.mkv file

**Comment by ppwwyyxx** [comment]
Closing as it's an opencv issue.

Trying different output format may fix it.
