### ISSUE TITLE
how to only visualize object have score large in outputs?

### ISSUE THREAD

**Issue by LeHoaiLinh278** [facebookresearch/detectron2#539]
## Pitch

Note that you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
See [projects](https://github.com/facebookresearch/detectron2/tree/master/projects/) for some examples.
We would only consider adding new features if they are relevant to many users.

**Comment by ppwwyyxx** [comment]
You can use `visualizer.draw_instance_predictions(predictions[predictions.score > 0.8])`
