### ISSUE TITLE
python setup.py  build develop gets wrong

### ISSUE THREAD

**Issue by wbyiml** [facebookresearch/detectron2#540]
when I run    python setup.py  build develop, the terminal output:

/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/deformable/deform_conv.h:344:5: note: in expansion of macro ‘AT_CHECK’
     AT_CHECK(offset.type().is_cuda(), "offset tensor is not on GPU!");
     ^
In file included from /home/nls1/.local/lib/python3.7/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/vision.cpp:3:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:325:13: note: declared here
 inline void deprecated_AT_CHECK() {}
             ^
gcc -pthread -B /home/nls1/.conda/envs/test1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/nls1/tmp/detectron2_1/detectron2/layers/csrc -I/home/nls1/.local/lib/python3.7/site-packages/torch/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/TH -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/include -I/home/nls1/.conda/envs/test1/include/python3.7m -c /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:3:
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp: In lambda function:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:446:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
   AT_DISPATCH_FLOATING_TYPES_AND_HALF(
   ^
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp: In lambda function:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp:497:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
   AT_DISPATCH_FLOATING_TYPES_AND_HALF(
   ^
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^
gcc -pthread -B /home/nls1/.conda/envs/test1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/nls1/tmp/detectron2_1/detectron2/layers/csrc -I/home/nls1/.local/lib/python3.7/site-packages/torch/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/TH -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/include -I/home/nls1/.conda/envs/test1/include/python3.7m -c /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.7/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:3:
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp: In lambda function:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:429:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
   AT_DISPATCH_FLOATING_TYPES_AND_HALF(input.type(), "ROIAlign_forward", [&] {
   ^
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp: In lambda function:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:116:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp:481:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES_AND_HALF’
   AT_DISPATCH_FLOATING_TYPES_AND_HALF(grad.type(), "ROIAlign_forward", [&] {
   ^
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^
gcc -pthread -B /home/nls1/.conda/envs/test1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/nls1/tmp/detectron2_1/detectron2/layers/csrc -I/home/nls1/.local/lib/python3.7/site-packages/torch/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/TH -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/include -I/home/nls1/.conda/envs/test1/include/python3.7m -c /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/nls1/.conda/envs/test1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/nls1/tmp/detectron2_1/detectron2/layers/csrc -I/home/nls1/.local/lib/python3.7/site-packages/torch/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/TH -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/include -I/home/nls1/.conda/envs/test1/include/python3.7m -c /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated.h:3,
                 from /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:3:
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp: In lambda function:
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:103:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:67:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
   ^
/home/nls1/.local/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:31:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^
/usr/local/cuda:/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/nls1/tmp/detectron2_1/detectron2/layers/csrc -I/home/nls1/.local/lib/python3.7/site-packages/torch/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/TH -I/home/nls1/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/include -I/home/nls1/.conda/envs/test1/include/python3.7m -c /home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o build/temp.linux-x86_64-3.7/home/nls1/tmp/detectron2_1/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
unable to execute '/usr/local/cuda:/usr/local/cuda/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/usr/local/cuda/bin/nvcc' failed with exit status 1

## Environment

---------------------  ------------------------------------------------------------------------------
sys.platform           linux
Python                 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) [GCC 7.3.0]
Numpy                  1.17.3
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.1
PyTorch Debug Build    False
torchvision            0.4.2
CUDA available         True
GPU 0,1                GeForce RTX 2080 SUPER
CUDA_HOME              /usr/local/cuda:/usr/local/cuda
Pillow                 6.2.1
---------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
I think your environment variable `CUDA_HOME` is wrong.
Please make sure ` python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` produce reasonable result.

**Comment by smile-care** [comment]
> I think your environment variable `CUDA_HOME` is wrong.
> Please make sure ` python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'` produce reasonable result.

remain wrong
