### ISSUE TITLE
3D Data

### ISSUE THREAD

**Issue by abhisuri97** [facebookresearch/detectron2#541]
Can detectron2 be trained on 3D data such as MRI data? So far, it has been able to work amazingly on segmenting spine images from a single MRI slice (see attached); however, I was wondering if it would be able to somehow handle 3D data (i.e. multiple slices) for training (and if so, how the network should be modified to accommodate that). 

<img width="848" alt="Screen Shot 2019-12-17 at 11 31 44 AM" src="https://user-images.githubusercontent.com/4992430/71015119-0f8e9180-20c1-11ea-813c-ca2ecdbf6057.png">

**Comment by ppwwyyxx** [comment]
Detectron2 can be extended to new data types or models, and the [densepose project](https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose) is one such example. Mesh R-CNN (to be released in a month) is 3D data.

How the network should be modified is a research question which we do not discuss.
