### ISSUE TITLE
How to solve AssertionError: The input path(s) was not found

### ISSUE THREAD

**Issue by Hung-Hsiang-617** [facebookresearch/detectron2#542]
Please select an issue template from
https://github.com/facebookresearch/detectron2/issues/new/choose .

Otherwise your issue will be closed.
when I run
 python demo/demo.py --config-file ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --input input1.jpg    --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

it happened with [12/18 02:23:59 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['input1.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
WARNING [12/18 02:23:59 d2.config.compat]: Config './configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/demo.py", line 78, in <module>
    assert args.input, "The input path(s) was not found"
AssertionError: The input path(s) was not found

Please help me to solve problems. I really appreciated.

**Comment by ppwwyyxx** [comment]
As it says, the input file you provided does not exist.

**Comment by Hung-Hsiang-617** [comment]
![image](https://user-images.githubusercontent.com/53552921/71050677-cbfb5c80-2180-11ea-968d-4a2e09a27d7f.png)

but, I sure the input1.jpg in the correct path.
It is strange.

**Comment by Hung-Hsiang-617** [comment]
Oh! I found the problem that what happened. I already solved it. Thank you.

**Comment by kp421** [comment]
How did you solve this?

**Comment by byq-luo** [comment]
> Oh! I found the problem that what happened. I already solved it. Thank you.

How did you solve this?

**Comment by swapp1990** [comment]
If you are running the demo.py, and cd into demo, make sure the input path is set correctly. Atleast that's the mistake I made.
