### ISSUE TITLE
Is the AP in pascal_voc_evaluation.py a mAP?How to output each category of AP in VOC PASCAL?

### ISSUE THREAD

**Issue by Hondlus** [facebookresearch/detectron2#549]
1. I trained a TridentNet model to test its performance, and the result showed AP:..AP50,.., AP75:...Used VOC Pasacal 07 metric.Does this AP refer to a mAP?
2.I want to output each category of AP in VOC Pascal, how do I do that?
Thank you

**Comment by ppwwyyxx** [comment]
1. Yes
2. We do not have such feature.

**Comment by Hondlus** [comment]
> 1. It refers to COCO style AP[0.5:0.95:0.05]
> 2. We do not have such feature.

Can this feature be added to later versions?

**Comment by ppwwyyxx** [comment]
We don't have such plans. 
It's very easy though, a PR about it is welcome.
