### ISSUE TITLE
How detectron2 does augment and evaluation?

### ISSUE THREAD

**Issue by Ghul-huan** [facebookresearch/detectron2#551]
1.
 When train or test in detectron2 ,the default augment of images  only see  T.ResizeShortestEdge() ,did not see   resize the data to a fixed size,so different sizes of data putting the network?

2.
When verifying, the image was augmented by T.ResizeShortestEdge (), but the label was not processed (get the label from self._coco_api = COCO (json_file) ), so will there be problems?

**Comment by ppwwyyxx** [comment]
1. Every call of `ResizeShortestEdge` contains a size

2. There will not be problems because the outputs are resized back to the original size.

**Comment by Ghul-huan** [comment]
1.What confuses me is that ResizeShortestEdge makes the short sides of all images the same(MIN_SIZE_TRAIN), but the other side of the image is likely to be different(scale *MIN_SIZE_TRAIN), so the input image size is different？

2. Got the second question,thanks.

**Comment by ppwwyyxx** [comment]
1. Yes
