### ISSUE TITLE
detected person when no person present in image

### ISSUE THREAD

**Issue by miwojc** [facebookresearch/detectron2#554]
I used the code form quick start notebook: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

and run the code on an image from unspash. there is no person in the image, however detectron gives category of 0 - which is person. There are more images like that. Any way to correct this?
image link: https://images.unsplash.com/photo-1470813740244-df37b8c1edcb

output:
![index](https://user-images.githubusercontent.com/32404415/71167807-b146e780-2255-11ea-8a36-9933e33498b0.png)

Thanks...

**Comment by ppwwyyxx** [comment]
All machine learning models can make mistakes. 
Closing because it's normal.
