### ISSUE TITLE
Detectron2 with an Autonomous Mobile Robot

### ISSUE THREAD

**Issue by AbdelrahmanAEmam** [facebookresearch/detectron2#555]
Is detecron2 suitable for real-time implementation for an autonomous mobile robot, that runs on Nvidia Jetson TX2?

**Comment by ppwwyyxx** [comment]
Detection/segmentation models can easily run in real-time on a GPU. You just need to train a smaller model. Papers like https://arxiv.org/abs/1903.11752 has models that run real-time on CPUs.

We plan release some smaller models suitable for CPU applications based on https://arxiv.org/abs/1812.03443 in a few months.
