### ISSUE TITLE
where could I find the network architecture of each model

### ISSUE THREAD

**Issue by amiltonwong** [facebookresearch/detectron2#557]
Hi, all,

Besides loading the provided model, where could I find the network architecture of each model? e.g.

```
class mask_rcnn_R_50_FPN(nn.Module):

    def __init__(self):

    def forward(self, x):

``` 

THX!

**Comment by ppwwyyxx** [comment]
The model is defined by its `MODEL.META_ARCHITECTURE`, e.g., "class GeneralizedRCNN", and can be found at https://github.com/facebookresearch/detectron2/tree/master/detectron2/modeling/meta_arch
