### ISSUE TITLE
ETA is not accurate

### ISSUE THREAD

**Issue by wangg12** [facebookresearch/detectron2#559]
Currently `ETA` is calculated by `median(1000)`, but in my case it is very inaccurate.
```
eta: 1 day, 15:59:52(median) 4 days, 1:44:12(global_avg) 4 days, 4:01:56(avg(20))
```

**Comment by ppwwyyxx** [comment]
If the iteration time is unstable (they are usually unstable at the beginning) then there is simply no way to estimate it accurately.

**Comment by wangg12** [comment]
The actual problem is similar to this [https://discuss.pytorch.org/t/data-loader-takes-a-lot-of-time-for-every-nth-iteration/10831/17](https://discuss.pytorch.org/t/data-loader-takes-a-lot-of-time-for-every-nth-iteration/10831/17), which leads to the inaccurate estimated time with median.
