### ISSUE TITLE
build error - features.h no such file or directory

### ISSUE THREAD

**Issue by vobecant** [facebookresearch/detectron2#561]
Hi everyone,
I just tried to install detectron2 and observed the following error. I tried to deal with it on my own but with a little success. Can you please help me? Thanks in advance!

## Instructions To Reproduce the Issue

1. what changes you made (`git diff`) or what code you wrote
None

2. what exact command you run:
python setup.py build develop

3. what you observed (including the full logs):
running build
running build_py
running build_ext
building 'detectron2._C' extension
gcc -pthread -B /home/vobecant/miniconda3/envs/py-36_pytorch-10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/vobecant/PhD/detectron2/detectron2/layers/csrc -I/home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include -I/home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/TH -I/home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/THC -I/opt/apps/software/CUDA/10.1.105-GCC-8.2.0-2.31.1/include -I/home/vobecant/miniconda3/envs/py-36_pytorch-10/include/python3.7m -c /home/vobecant/PhD/detectron2/detectron2/layers/csrc/vision.cpp -o build/temp.linux-x86_64-3.7/home/vobecant/PhD/detectron2/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /opt/apps/software/GCCcore/8.2.0/include/c++/8.2.0/x86_64-pc-linux-gnu/bits/c++config.h:508,
                 from /opt/apps/software/GCCcore/8.2.0/include/c++/8.2.0/cstddef:49,
                 from /home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5,
                 from /home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:3,
                 from /home/vobecant/miniconda3/envs/py-36_pytorch-10/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/vobecant/PhD/detectron2/detectron2/layers/csrc/vision.cpp:3:
/opt/apps/software/GCCcore/8.2.0/include/c++/8.2.0/x86_64-pc-linux-gnu/bits/os_defines.h:39:10: fatal error: features.h: No such file or directory
 #include <features.h>
          ^~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

## Expected behavior
instalation of detectron2

## Environment

---------------------  --------------------------------------------------
sys.platform           linux
Python                 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                  1.17.2
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0
PyTorch Debug Build    False
torchvision            0.4.1a0+d94043a
CUDA available         True
GPU 0,1,2,3            GeForce GTX 1080 Ti
CUDA_HOME              /opt/apps/software/CUDA/10.1.105-GCC-8.2.0-2.31.1
NVCC                   Cuda compilation tools, release 10.1, V10.1.105
Pillow                 6.2.0
cv2                    4.1.1
---------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Your compiler toolchain is broken. This is unrelated to detectron2.
