### ISSUE TITLE
can detectron2 run in pytorch1.0?

### ISSUE THREAD

**Issue by yustaub** [facebookresearch/detectron2#562]
the nvidia driver version of the server is 390.67, and it support cuda9.0 at most, can detectron2 run in pytorch1.0?

**Comment by ppwwyyxx** [comment]
duplicated of https://github.com/facebookresearch/detectron2/issues/4#issuecomment-540955849

pytorch 1.3 supports cuda 9.0 as well.

**Comment by yustaub** [comment]
I got that pytorch1.3 requires cuda 9.2 at least,and thanks to your reply
pytorch==1.3.0 -&gt; cudatoolkit[version='&gt;=10.0,<10.1|&gt;=10.1,<10.2|&gt;=9.2,<9.3']




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yuxin Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月22日(星期天) 凌晨1:59
收件人:&nbsp;"facebookresearch/detectron2"<detectron2@noreply.github.com&gt;;
抄送:&nbsp;"staub、"<1034397129@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detectron2] can detectron2 run in pytorch1.0? (#562)




duplicated of #4 (comment)
 
pytorch 1.3 supports cuda 9.0 as well.
