### ISSUE TITLE
Hidden Dependency CUDA > 9.1?

### ISSUE THREAD

**Issue by mauriciofloresML** [facebookresearch/detectron2#563]
## Instructions To Reproduce the Issue

1. I think I am running into one of your common issues:

```
Undefined cuda symbols. The version of NVCC you use to build detectron2 or torchvision does not match the version of cuda you are running with.
```

My CUDA version is 9.1 (and I cannot change it). Running your Colab inference code on my machine, I get this error message:

```
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

It seems that my CUDA version isn't entirely compatible with Pytorch 1.3, is that right?
If that's the case, is it still possible to use Detectron2? Is there a workaround this?

I am using a Linux machine, and installed all the dependencies listed in INSTALL.md, just don't have the right CUDA version apparently.

Thanks!

**Comment by yustaub** [comment]
> ## Instructions To Reproduce the Issue
> 1. I think I am running into one of your common issues:
> 
> ```
> Undefined cuda symbols. The version of NVCC you use to build detectron2 or torchvision does not match the version of cuda you are running with.
> ```
> 
> My CUDA version is 9.1 (and I cannot change it). Running your Colab inference code on my machine, I get this error message:
> 
> ```
> The NVIDIA driver on your system is too old (found version 9010).
> Please update your GPU driver by downloading and installing a new
> version from the URL: http://www.nvidia.com/Download/index.aspx
> Alternatively, go to: https://pytorch.org to install
> a PyTorch version that has been compiled with your version
> of the CUDA driver.
> ```
> 
> It seems that my CUDA version isn't entirely compatible with Pytorch 1.3, is that right?
> If that's the case, is it still possible to use Detectron2? Is there a workaround this?
> 
> I am using a Linux machine, and installed all the dependencies listed in INSTALL.md, just don't have the right CUDA version apparently.
> 
> Thanks!

my machine is cuda9.0, and I also want to know whether it can run with cuda9.0

**Comment by yustaub** [comment]
pytorch==1.3.0 -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=9.2,<9.3']
I got that pytorch1.3 requires cuda 9.2 at least

**Comment by mauriciofloresML** [comment]
@yustaub: Did you also follow the instructions in INSTALL.md and run into the same error?

**Comment by yustaub** [comment]
> @yustaub: Did you also follow the instructions in INSTALL.md and run into the same error?

I test the torch.cuda.is_available() at first, and show 'False', pytorch1.3 support cuda 9.2 at least, and my machine can support cuda9.0 at most

**Comment by ppwwyyxx** [comment]
Whether pytorch 1.3 requires cuda>=9.2 or not is a pytorch question. I guess it is true but you'll get better answers from https://discuss.pytorch.org/
