### ISSUE TITLE
Custom Dataset and COCO format.

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#564]
1) All the example I have seen about detectron2 is related to bigger objects. I have a cancer dataset and I have to do detection and segmentation. Is detectron2 suited for this task?

2) Do I have to make my own dataloader or can I use detectron2 dataloader by converting my dataset in COCO format? (I will be using pycococreator https://github.com/waspinator/pycococreator)

**Comment by ppwwyyxx** [comment]
Please see https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
