### ISSUE TITLE
Load weights of trained model

### ISSUE THREAD

**Issue by AvivSham** [facebookresearch/detectron2#565]
I used your magnificent repo to train FRCNN model on a custom dataset, Now I want to use the trained model in my project but without holding the whole detectron repo since I want my project to be as lightweight as possible. I tried to use `from torchvision.models.detection import fasterrcnn_resnet50_fpn` but encountered errors due to layers' names. What is the right way to load the weights without using all Detectron2 repo?

**Comment by ppwwyyxx** [comment]
That's not currently supported.

**Comment by AvivSham** [comment]
Any other way to do this? maybe to save the models architecture?
Is it even possible to build a model given its architecture in an automatic way?
