### ISSUE TITLE
How to do detection without segmentation.

### ISSUE THREAD

**Issue by wbyiml** [facebookresearch/detectron2#566]
I want to train on a dataset only contains boxs annotations, without segmentation annotations. 

Can I use this repo for it?

**Comment by ppwwyyxx** [comment]
Yes.
See "object detection" in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by wbyiml** [comment]
my code:

import cv2
import numpy as np
import json
import random
from detectron2.structures import BoxMode
from detectron2.utils.visualizer import Visualizer
from detectron2.engine import DefaultTrainer,DefaultPredictor
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.config import get_cfg
import itertools
import xml.etree.ElementTree as ET

im = cv2.imread("./input.jpg")
cfg = get_cfg()
cfg.merge_from_file("../configs/COCO-Detection/rpn_R_50_FPN_1x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = "detectron2://COCO-Detection/rpn_R_50_FPN_1x/137258492/model_final_02ce48.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
print(outputs)

output:
{'proposals': Instances(num_instances=1415, image_height=480, image_width=640, fields=[proposal_boxes = Boxes(tensor([[ 49.5091, 277.1474,  81.1809, 344.8791],
        [117.5095, 224.6727, 362.8096, 473.7539],
        [562.8272, 271.9781, 595.3329, 337.0448],
        ...,
        [253.1892,   0.0000, 640.0000,  97.3933],
        [  0.0000,   3.7973, 136.7002, 150.8748],
        [438.7827,   0.0000, 640.0000,  67.2175]], device='cuda:0')), objectness_logits = tensor([ 8.7242,  8.4834,  7.5928,  ..., -8.6042, -8.6718, -9.2946],
       device='cuda:0'), ])}


I try to use the object detection model and predict an image, but why the output is "proposal" instead of "pred_boxes"

**Comment by ppwwyyxx** [comment]
Because you're using RPN and RPN stands for "Region __Proposal Network__". You're recommended to understand the relevant papers before using detectron2.
