### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by pjoshi0621** [facebookresearch/detectron2#568]
I wish to use detectron2 with my custom dataset which follows the same COCO format. I follow the instruction given at the https://detectron2.readthedocs.io/tutorials/datasets.html URL. But at the same time I do not want to register other pre-defined dataset other than my dataset.

So, I commented the function definition which register all those pre-defined dataset. And modified below mentioned two scripts of detectron2 based on my requirement:

- https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/builtin.py

- https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/builtin_meta.py
Now, the detectron2 trains a model using only my custom dataset.

I have one question regarding this,
What I have done is correct or not?
Please help me with it.

**Comment by ppwwyyxx** [comment]
Please see examples at https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
