### ISSUE TITLE
Custom dataset is not registering.

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#575]
**I have a dataset in COCO format and I tried to register it using the example in the docs like**

**register.py**
from detectron2.data.datasets import register_coco_instances
register_coco_instances("my_dataset", {}, "json_annotation.json", "path/to/image/dir")

**but it didn't work so I tried this**

from detectron2.data import DatasetCatalog
name='cancer_train'
json_file='train.json'
image_root='/home/shroud/FYP/detector/detectron2_repo/datasets/train'
DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))

**When I run the file it does nothing, doesn't even give me an error when I try to register it again. When I tried to run my train file then it gives an error that cancer_train is not registered.**

**Train.py**

from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file("./configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("cancer_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/137849600/model_final_f10217.pkl" 
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 1000   
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE =   128 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

**KeyError: "Dataset 'cancer_train' is not registered!**

**Comment by ahsan44411** [comment]
I solved the issue. If you are using your own pc not the colab. You must register and write code for training in the same file.
Quite a silly mistake by me.

**Comment by ppwwyyxx** [comment]
Or you can import the file.
