### ISSUE TITLE
Training starts and stop itself

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#576]
**unexpected behaviour I get when I try to train my model.**

**Expected Result:**
Training should have started and I should have seen the model structure like in the colab example.

**Actual Result:**
I got these warning which is because number of classes are different but it does not proceed any further than this and the program stops.

Config './configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (2, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (2,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (4, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (4,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (1, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (1,) in the model! Skipped.

Operating system: Ubuntu 18.04
CUDA version:  10.0
GPU models (for all devices if they are not all the same): GTX 1070 Ti
python --version output: 3.7

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ahsan44411** [comment]
@ppwwyyxx  I have changed the format of my question. Please answer it now

**Comment by ppwwyyxx** [comment]
There is a lot of missing information. Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
