### ISSUE TITLE
How do you visually test a picture with a trained model?

### ISSUE THREAD

**Issue by Hondlus** [facebookresearch/detectron2#577]
I trained a tridentnet model.I want to test a picture with a model.Take a look at the accuracy of the prediction box.What should we do?

**Comment by ppwwyyxx** [comment]
Please see the colab tutorial colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

**Comment by JosephKJ** [comment]
In case if you want to visualize the detections, a slim code: https://gist.github.com/JosephKJ/e523f77af6c5768538eda0c7e2af375a
