### ISSUE TITLE
Getting COCO format annotations for my dataset using pre-trained model

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#578]
I am new to Detectron2. I have a dataset consisting about 50k images in the context of autonomous driving. I would like to generate object detection annotations (pedestrian, cars, etc.) for these images using pre-trained Cascade R-CNN. As per Detectron2 Colab documentation, it only shows inference on a per-image basis. 

How can I get COCO format annotations for the whole dataset instead of iterating on each image? 

Also, how can I choose specific classes to be detected and annotated such as only pedestrian and cars?

**Comment by ahsan44411** [comment]
I used pycococreator (https://github.com/waspinator/pycococreator). It pretty much takes care of creating the COCO dataset and making it JSON form. 
But if you find a better way please let me know.

**Comment by Kbkartik** [comment]
> I used pycococreator (https://github.com/waspinator/pycococreator). It pretty much takes care of creating the COCO dataset and making it JSON form.
> But if you find a better way please let me know.

I think you misunderstood my question. I would like to use existing pre-trained models to generate annotations for my datasets instead of manually labelling them.

**Comment by ppwwyyxx** [comment]
This is not supported and will not be supported. You can run inference with the model and do what you want by yourself.
