### ISSUE TITLE
Cuda Out of memory

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#579]
**I have about 1000 images of cancer dataset, with nearly 1 - 10 tumor globs in each image. I am trying to perform image segmentation**. Whenever the training starts, I get an error that CUDA has run out of memory.

**The dataset has different image sizes.**
1) 2000x2000 (.tif format)
2) 5000x5000(.tif format)
3) 2252x2250 (.bmp)
4) 1539x1376(.jpg)

**Error**
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.93 GiB total capacity; 775.71 MiB already allocated; 14.88 MiB free; 14.29 MiB cached)

**How to recreate it:** 
I just simply used the training code from the COLAB example. 
Image Batch Size = 1
Max_ITER: 300
Num Classes=1

**Here is what I use to train.**
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("cancer",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 300 
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128  
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

**System:**

OS: Ubuntu 18.04
CUDA: 10.0
Pytorch:1.3.1
torchvision: 0.4.0
1 GPU: Nvidia GeForce GTX 1070 Ti 6GB memory

**!! Important !!**
**If the different dimensions of Images sets is the problem, is it possible that I first train it on one set of images than use its weights to train the second set of images of different dimensions?**

**Comment by ppwwyyxx** [comment]
You need either better GPUs, or smaller models/images.

**Comment by ahsan44411** [comment]
Can you please elaborate on what you mean by smaller models? What model should I use?

**Comment by ppwwyyxx** [comment]
Detectron2 currently does not include smaller models (e.g. models with fewer layers). They can be implemented by users.

**Comment by ahsan44411** [comment]
@ppwwyyxx  what if I crop the images into smaller sizes like 512x512. Would number of images affect the training processes?

**Comment by ppwwyyxx** [comment]
Using smaller images in the dataset you registered will reduce memory usage. Augmenting the images to smaller sizes (`cfg.INPUT.MIN_SIZE_TRAIN`) will reduce memory usage.
Number of images in the dataset does not affect GPU memory usage.

**Comment by ahsan44411** [comment]
@ppwwyyxx  thank you, you helped me a lot

**Comment by roeetal** [comment]
You can also reduce cfg.SOLVER.IMS_PER_BATCH

**Comment by Rustastra** [comment]
Hi, where can I look up GPU memory requirements for Detectron2? 
@ahsan44411 have you managed to run the "big" detectron model on your dataset after compressing/cropping the images?
Thanks
