### ISSUE TITLE
assert self.groups[0].item() == 0 and self.groups[-1].item() == len(self.groups) - 1

### ISSUE THREAD

**Issue by cruigo93** [facebookresearch/detectron2#58]
## ❓ Questions and Help

General questions about detectron2.
![Screenshot from 2019-10-14 17-16-21](https://user-images.githubusercontent.com/9817816/66747449-60f28880-eea6-11e9-933b-c26fa7d5b5a8.png)
I have binary masks for objects and I just make little changes to demo code to train Mask-RCNN. Visualization is fine but I cannot train model
![Screenshot from 2019-10-14 17-18-59](https://user-images.githubusercontent.com/9817816/66747594-baf34e00-eea6-11e9-8544-d49a8b06478b.png)

**Comment by ppwwyyxx** [comment]
It looks like all your images have similar aspect ratio (all width > height, or the other way around) and in this case you cannot use `cfg.DATALOADER.ASPECT_RATIO_GROUPING` (default to True). Setting it to False should work. We'll also address it in the code so it does not throw an error.
