### ISSUE TITLE
Error when evaluate: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer

### ISSUE THREAD

**Issue by hungthanhpham94** [facebookresearch/detectron2#580]
## Instructions To Reproduce the Issue

1. what changes you made (`git diff`) or what code you wrote
I don't change code in Detectron2 repo
I just prepare COCO dataset following instruction
git diff is empty
2. what exact command you run:
Training: python tools/train_net.py --num-gpus 2 --config-file configs/COCO-Detection/retinanet_R_50_FPN_3x.yaml SOLVER.IMS_PER_BATCH 4
Evaluate: python tools/train_net.py --config-file configs/COCO-Detection/retinanet_R_50_FPN_3x.yaml --eval-only MODEL.WEIGHTS output/model_final.pth

3. what you observed (including the full logs):
![detectron2](https://user-images.githubusercontent.com/22211711/71432553-0d55b400-270d-11ea-85b0-81d6b57837c2.png)

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior

I expect that process will show AP result

## Environment
![detectron2_2](https://user-images.githubusercontent.com/22211711/71432634-805f2a80-270d-11ea-9b44-ed2a7466a848.png)

Thanks for your help!

**Comment by ppwwyyxx** [comment]
It's an issue of coco API: it does not work with numpy 1.18. Downgrading to 1.17 will help.

I'll try to fix this in COCO API.
