### ISSUE TITLE
Any Plan to open source PointRend?

### ISSUE THREAD

**Issue by txytju** [facebookresearch/detectron2#581]

**Comment by ppwwyyxx** [comment]
PointRend for instance segmentation will be available in a month.

**Comment by startupgurukul** [comment]
If we notice in the gif, Densepose isnt very accurate at the edges, hoping that would also improve with the PointRend  
![image](https://user-images.githubusercontent.com/1381301/66535560-d3422200-eace-11e9-9123-5535d469db19.png)

**Comment by zsef123** [comment]
[PointRend-PyTorch](https://github.com/zsef123/PointRend-PyTorch)

Now I'm working for Semantic Segmentation.
But it's not fully implementation and not tested yet.

**Comment by mtkociuba** [comment]
> [PointRend-PyTorch](https://github.com/zsef123/PointRend-PyTorch)
> 
> Now I'm working for **Semantic Segmentation**.
> But it's not fully implementation and not tested yet.

Can I download this and start testing it out? Or the library isnt working at all?

**Comment by zsef123** [comment]
@corporate-slave 

You can running only train networks. 
But I checked only a few steps run(loss decreases well)
And I'm not implement inference phase.

**Comment by tomer-avrahami** [comment]
Hi @ppwwyyxx,

PointRend paper describes different point selection techniques for training and inference. In addition, different  parameters were used for different tasks.
Can you please share how much effect it had on your final results for instance segmentation? Did you see a  major difference in your final results or stability improvements with different techniques?
Do you think that better technique could get better results? 

Thanks,
Tomer

**Comment by startupgurukul** [comment]
Pointrend is like adding reason to segmentation, it would be interesting to see how mobile models accuracy improves
Will it be significant? Possibly compete with the likes of Resnet.

**Comment by jay2002** [comment]
Hi @ppwwyyxx 
Is the PointRend available?

**Comment by xmyqsh** [comment]
@zsef123 
You have misunderstood the point sampling process.
Maybe I can help you.

**Comment by zsef123** [comment]
@xmyqsh 
issue or PR are welcome anytime

**Comment by xmyqsh** [comment]
@zsef123 
I'm implementing PointRend for instance segmentation.
I will help you after that.

**Comment by bluesky314** [comment]
@zsef123 Is the implementation complete?

**Comment by rbgirshick** [comment]
We've released code yesterday for PointRend instance segmentation under `detectron2/projects` here: https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend.

The PointRend semantic segmentation code is nearly ready for release and will be available soon.

**Comment by ppwwyyxx** [comment]
FYI we just released a colab notebook that visualizes the internal steps of PointRend: https://colab.research.google.com/drive/1isGPL5h5_cKoPPhVL9XhMokRtHDvmMVL

**Comment by bluesky314** [comment]
Awesome! I will go through this.
