### ISSUE TITLE
speed of multi GPU inference

### ISSUE THREAD

**Issue by lydials** [facebookresearch/detectron2#582]
I observe that the average speed of inference on multiple GPUs is slower than using one GPU, and I think it is caused by high cost of CPU. As in my case, I compare with these two setting:

```
python tools/train_net.py --eval-only --num-gpus 1 \
--config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl`
```

and 

```
python tools/train_net.py --eval-only --num-gpus 8 \
--config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

, and the speeds are:

```
[12/26 04:53:35 d2.evaluation.evaluator]: Total inference time: 0:07:01.895830 (0.084464 s / img per device, on 1 devices) 
[12/26 04:53:35 d2.evaluation.evaluator]: Total inference pure compute time: 0:04:55 (0.059172 s / img per device, on 1 devices)
```

and

```
[12/26 04:59:53 d2.evaluation.evaluator]: Total inference time: 0:02:38.385152 (0.255460 s / img per device, on 8 devices)
[12/26 04:59:53 d2.evaluation.evaluator]: Total inference pure compute time: 0:01:55 (0.186390 s / img per device, on 8 devices)
```

I notice that the CPU cost is high when only one GPU is using as the first command, which is shown in the figure. 

<img width="933" alt="截屏2019-12-26下午1 07 53" src="https://user-images.githubusercontent.com/17929120/71459074-cb963d80-27e0-11ea-8a3c-0668d4cca9a0.png">

I wonder that if there is any suggestion to get the same per GPU speed when using multiple GPUs?

## My Environment:

------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1,2,3,4,5,6,7       TITAN RTX
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
cv2                       4.1.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
I cannot reproduce similar slow down on a DGX machine with 8 V100s. My guess is that the interconnect on your machine may have lower bandwidth and becomes a bottleneck. 

We in general do not prioritize in optimizing multi-gpu inference speed since it's not a very useful scenario in practice.

**Comment by lydials** [comment]
Thanks for your reply. After some profilings I find that the slow down occurs when moving images from CPU to GPU. I think this problem is related to my hardware.

**Comment by lydials** [comment]
Hi @ppwwyyxx ,

I find that the reason of slow down is that the tensor is not contiguous before moving into GPU. I change the code below

https://github.com/facebookresearch/detectron2/blob/fd3edf27a6936ad6ee37c678daef4d330a6f1f69/detectron2/data/dataset_mapper.py#L101

to

```
        dataset_dict["image"] = torch.as_tensor(image.transpose(2, 0, 1).astype("float32")).contiguous()
```

and the speed of multi-GPU inference becomes similar of that of single GPU.

**Comment by ppwwyyxx** [comment]
Thanks! Although we didn't observe similar slow down, this sounds like a cheap optimization we could do. I'll add this later.
