### ISSUE TITLE
Should I change _C.INPUT_MIN_SIZE_TRAIN and _C.INPUT_MAX_SIZE_TRAIN if the sizes of my images for training are beyond the default scale?

### ISSUE THREAD

**Issue by Zy1013921842** [facebookresearch/detectron2#583]
As the title says, my images have several sizes and all of them are beyond the default scale: 800*1300. Will it influence the final evalution results if I don't adjust the default value to contain my image sizes?

Thanks for replying!

**Comment by BUAAtao** [comment]
Do you how to  set fixed size？ 
If I changed   MAX_SIZE_TRAIN: 300，  MIN_SIZE_TRAIN: 300
the input in model forward would be (256,320) or (288, 320) and so on.
How can I set the fixed size and make input size  (300, 300) fixed？

**Comment by ppwwyyxx** [comment]
@Zy1013921842  We do not answer general machine learning / computer vision questions that are not specific to detectron2.

@BUAAtao This is unrelated to the original issue, but you'll need to write a custom dataset mapping function that resizes the images (https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader).
