### ISSUE TITLE
How to get F-Measure from detectron2

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#586]
## ❓ How to use Detectron2

I want to get the F-measure during training along with the loss that it gives and during evaluation. Where do I write the code and what do I use?

**Comment by ahsan44411** [comment]
Go to C:\Users\Ahsan\Desktop\detectron2-master\detectron2-master\detectron2\modeling\roi_heads\fast_rcnn you will find variables called num_accurate and num_false_negative under _log_accuracy which are true positives and false negatives respectively. You can use them to calculate the F measure.

**Comment by DINOUS11** [comment]
Oh is there anything like that for mask rcnn to know the number of FP, FN, TP, TN? @ahsan44411  @ppwwyyxx

**Comment by suprimnakarmi** [comment]
@ahsan44411 How to access the num_accurate and num_false_negative to apply in the code?
