### ISSUE TITLE
Detailed tutorial on how  to train a Densepose model on a custom dataset

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#587]
Hello,
Does any one have a detailed tutorial on how to train a Densepose model on a custom dataset? 
E.g. - how the annotations are constructed? can you use detectron2 pipeline for training? is there any pre-processing that needs to be done to the images? 

I would like to do it via code (not the via pre-written functions and the terminal) so if you have a written notebook (or any other format) that would be great!

Thanks in advance!

**Comment by ppwwyyxx** [comment]
We currently have no plans to support densepose on a custom dataset. It will likely be very complicated.
You can learn about the dataset collection process in the densepose paper.
