### ISSUE TITLE
How can we use image pyramid during inference

### ISSUE THREAD

**Issue by woolpeeker** [facebookresearch/detectron2#592]
## ❓ How to use Detectron2
Is there any way to use image pyramid during inference.
I'm a newcomer to Detectron2. It seems that there is not any image pyramid in detectron2, so Is there anyone know the best way to implement it.

**Comment by ppwwyyxx** [comment]
Test-time augmentation using different scales is implemented in https://detectron2.readthedocs.io/modules/modeling.html#detectron2.modeling.GeneralizedRCNNWithTTA.
