### ISSUE TITLE
Undefined symbol on centos7

### ISSUE THREAD

**Issue by Mabinogiysk** [facebookresearch/detectron2#593]
Hi,
I got `undefined symbol` when running the example in tutorial and I have tried solutions in `Common Installation Issues`.
```
  File "/root/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/root/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /root/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```

System platform: CentOS Linux release 7.2.1511 (Core)
I followed the installation steps in tutorial. The only difference is gcc version. I installed gcc 4.9 and 
 switched to it with:
```
yum install devtoolset-3
scl enable devtoolset-3 bash
```
Then I run the example in tutorial and got this error.

Output of `gdb -ex "r" -ex "bt" -ex "quit" --args python -m detectron2.utils.collect_env`
```
gdb -ex "r" -ex "bt" -ex "quit" --args python -m detectron2.utils.collect_env
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/anaconda3/bin/python3.7...done.
Starting program: /root/anaconda3/bin/python -m detectron2.utils.collect_env
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /root/anaconda3/lib/python3.7/site-packages/mkl/../../../libiomp5.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/2f/6a88b5d1a44463ab69c8cd6e8461149a2e775a.debug
Detaching after fork from child process 250.
Missing separate debuginfo for /root/anaconda3/lib/python3.7/site-packages/cv2/.libs/libz-a147dcb0.so.1.2.3
[New Thread 0x7fff93184700 (LWP 252)]
Detaching after fork from child process 253.
---------------------  --------------------------------------------------
sys.platform           linux
Python                 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                  1.17.2
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.1
PyTorch Debug Build    False
torchvision            0.4.2
CUDA available         True
GPU 0                  Tesla P40
CUDA_HOME              /usr/local/cuda-9.2/
NVCC                   Cuda compilation tools, release 9.2, V9.2.148
Pillow                 6.2.0
cv2                    3.4.2
---------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.4
  - Magma 2.4.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/conda-bld/pytorch_1574452261149/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574452261149/work=/usr/local/src/conda/pytorch-1.3.1 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574452261149/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[Thread 0x7fff93184700 (LWP 252) exited]
[Inferior 1 (process 246) exited normally]
No stack.
```

**Comment by ppwwyyxx** [comment]
After switching to gcc4.9, could you remove the files you built (build/, **/*.so) and rebuild them?

**Comment by Mabinogiysk** [comment]
> After switching to gcc4.9, could you remove the files you built (build/, **/*.so) and rebuild them?

I also removed the whole anaconda3 and detectron2 and reinstalled all of them from the beginning.

**Comment by ppwwyyxx** [comment]
What are your steps to install pytorch in a fresh anaconda?

The issue most likely comes from a messy environment of multiple installations or bad environment variables. I might not be able to offer further help unless you have instructions (e.g. a docker) to reproduce the issue. Some notes that might be relevant to you:

1. check that you don't have multiple pytorch/torchvision installation. [this tip](http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/#Use-python--c-'import-lib'-to-confirm-uninstallation) might help.
2. use latest version of detectron2
3. check for suspicious environment variables (CPATH, LIBRARY_PATH, etc) and clear them.

**Comment by Mabinogiysk** [comment]
> What are your steps to install pytorch in a fresh anaconda?
> 
> The issue most likely comes from a messy environment of multiple installations or bad environment variables. I might not be able to offer further help unless you have instructions (e.g. a docker) to reproduce the issue. Some notes that might be relevant to you:
> 
> 1. check that you don't have multiple pytorch/torchvision installation. [this tip](http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/#Use-python--c-'import-lib'-to-confirm-uninstallation) might help.
> 2. use latest version of detectron2
> 3. check for suspicious environment variables (CPATH, LIBRARY_PATH, etc) and clear them.

Thanks, I will rechecked it.

**Comment by Mabinogiysk** [comment]
It seemed this error caused by `-D_GLIBCXX_USE_CXX11_ABI=1`:
https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/6
https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

My pytorch complied with `-D_GLIBCXX_USE_CXX11_ABI=1`:
```
>>> torch._C._GLIBCXX_USE_CXX11_ABI
True
```

My detectron2 also complied with `-D_GLIBCXX_USE_CXX11_ABI=1`:
```
gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/detectron2/detectron2/layers/csrc -I/root/anaconda3/lib/python3.7/site-packages/torch/include -I/root/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.2/include -I/root/anaconda3/include/python3.7m -c /root/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.7/root/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
```

I have tried gcc 5.3 but got the same error. Is there any suggestion?

**Comment by Mabinogiysk** [comment]
> What are your steps to install pytorch in a fresh anaconda?
> 
> The issue most likely comes from a messy environment of multiple installations or bad environment variables. I might not be able to offer further help unless you have instructions (e.g. a docker) to reproduce the issue. Some notes that might be relevant to you:
> 
> 1. check that you don't have multiple pytorch/torchvision installation. [this tip](http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/#Use-python--c-'import-lib'-to-confirm-uninstallation) might help.
> 2. use latest version of detectron2
> 3. check for suspicious environment variables (CPATH, LIBRARY_PATH, etc) and clear them.


I have located this error, it caused by `CXX11_ABI`.  I installed pytorch1.3.1 by `conda install pytorch=1.3.1`. One can check the symbol in "*.so" with the command：
```
find  ~/anaconda3/lib/python3.6/site-packages/torch.bak/ -name "*.so" -exec bash -c "nm -D {} | grep SourceLocation" \;
```
(https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627)

The output like this, cxx11 means c++11 api:
```
0000000000031e10 T _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000000031e10 T _ZN3c105ErrorC2ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
000000000002eab0 T _ZN3c107Warning13print_warningERKNS_14SourceLocationEPKc
000000000002ffe0 T _ZN3c107Warning19set_warning_handlerEPFvRKNS_14SourceLocationEPKcE
```

At the same time,  command `torch._C._GLIBCXX_USE_CXX11_ABI`  is True.

My colleague happened to installed pytorch with pip and the symbols in *.so are:
```
0000000000de2a80 V _ZTVN5torch3jit14SourceLocationE
                 U _ZN3c105ErrorC1ENS_14SourceLocationERKSs
                 U _ZN3c107Warning4warnENS_14SourceLocationESs
                 U _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```
Command `torch._C._GLIBCXX_USE_CXX11_ABI`  is False.

But why detectron2 complied without c++11 api?

**Comment by ppwwyyxx** [comment]
> But why detectron2 complied without c++11 api on my compute?

Why do you think detectron2 was compiled without c++11 ABI? The log you posted earlier suggested otherwise.

Detectron2 will be compiled with the ABI pytorch was built with. That's why multiple different installations of pytorch it may cause issue.

**Comment by Mabinogiysk** [comment]
> Why do you think detectron2 was compiled without c++11 ABI? The log you posted earlier suggested otherwise.

On my colleague's compute, `torch._C._GLIBCXX_USE_CXX11_ABI` is False and symbol `_ZN3c105ErrorC1ENS_14SourceLocationERKSs` can be found in .so file.
While on my compute  `torch._C._GLIBCXX_USE_CXX11_ABI` is True and symbol `_ZN3c105ErrorC1ENS_14SourceLocationERKSs` cannot be found, which suggested `detectron2/_C.cpython-37m-x86_64-linux-gnu.so` are not build with c++ api, otherwise the symbol in `detectron2/_C.cpython-37m-x86_64-linux-gnu.so` should be `_ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`


> Detectron2 will be compiled with the ABI pytorch was built with. That's why multiple different installations of pytorch it may cause issue.

I installed pytorch with the command `conda install pytorch=1.3.1 cudatoolkit=9.2`(fvcore and its dependencies are installed with pip).  Mybe this is the reason.

**Comment by ppwwyyxx** [comment]
That reasoning makes sense, but as you suggested earlier with a command (though it's incomplete), your detectron2 is built with `CXX11_ABI=1`.

One possibility is that you could also have multiple installations of detectron2 and you're not running the version you build. Similarly, [this tip](http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/) might help:

> ... you can try `__file__` which will tell you where the library is.
>  ... always use import to confirm when you intend to uninstall something.

**Comment by Mabinogiysk** [comment]
> That reasoning makes sense, but as you suggested earlier with a command (though it's incomplete), your detectron2 is built with `CXX11_ABI=1`.
> 
> One possibility is that you could also have multiple installations of detectron2 and you're not running the version you build. Similarly, [this tip](http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/) might help:
> 
> > ... you can try `__file__` which will tell you where the library is.
> > ... always use import to confirm when you intend to uninstall something.

Now I have two version pytorch and detectron2.
1. Pytorch installed with pip and corresponding detectron2, labeled them as `pytorch_pip`, `detectron2_pip`;
2. Pytorch installed with conda and corresponding detectron2, labeled them as `pytorch_conda`, `detectron2_conda`;
Running `pytorch_conda` would get the error "undefined symbol" while `pytorch_pip` worked well. 
Now I replace the `.so` file in `detectron2_pip` with the same file in `detectron2_conda`, `pytorch_pip` also worked! So the key point is the version of pytorch.

I compared the log for compiling detectron2 , the only difference is `-D_GLIBCXX_USE_CXX11_ABI=0` (`pytorch_pip`) or `-D_GLIBCXX_USE_CXX11_ABI=1` (`detectron2_conda`).

I thought maybe you could repeated this error by:
1. Install anaconda3
2. Install pytorch with `conda`
3. compile detectron2

**Comment by ppwwyyxx** [comment]
You simply should avoid having multiple versions due to all the issues of multiple installation mentioned in the note. You could easily run `pytorch_A` together with a wrong `detectron2_B`, depending on how you install them or how your environment is set up.

**Comment by Mabinogiysk** [comment]
> You simply should avoid having multiple versions due to all the issues of multiple installation mentioned in the note. You could easily run `pytorch_A` together with a wrong `detectron2_B`, depending on how you install them or how your environment is set up.

Many thanks for all your support.
