### ISSUE TITLE
DensePose 15 & 25(fine) classes doc ?

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/detectron2#594]
could you give a doc to describe the DensePose 15 & 25(fine) classes?

**Comment by mathpopo** [comment]
right pic,i cannot know  which index color point what?i just guess from the point color ,but not right.
![12](https://user-images.githubusercontent.com/21274466/71566780-49b25700-2af5-11ea-864f-650093f79662.png)

**Comment by ppwwyyxx** [comment]
The data format is officially documented at https://github.com/facebookresearch/DensePose/blob/master/challenge/2019_COCO_DensePose/data_format.md

**Comment by mathpopo** [comment]
@ppwwyyxx ok,very thank you 

1, 2 = Torso, 3 = Right Hand, 4 = Left Hand, 5 = Left Foot, 6 = Right Foot, 7, 9 = Upper Leg Right, 8, 10 = Upper Leg Left, 11, 13 = Lower Leg Right, 12, 14 = Lower Leg Left, 15, 17 = Upper Arm Left, 16, 18 = Upper Arm Right, 19, 21 = Lower Arm Left, 20, 22 = Lower Arm Right, 23, 24 = Head;
![123](https://user-images.githubusercontent.com/21274466/71570894-6f9a2480-2b12-11ea-8c07-89a85f7519e7.png)
