### ISSUE TITLE
For Panormic FPN, how do I output the target detection box when I'm using the trained model to test the image/video? 

### ISSUE THREAD

**Issue by tensorflowt** [facebookresearch/detectron2#596]
hi
First of all, thank you very much for your open source project, very excellent! Here is a question to ask you!

For Panormic FPN, how do I output the target detection box when I'm using the trained model to test the image/video? At present, I can only output instance segmentation and panorama segmentation information.

What changes do I need to make during the test? Or does the algorithm not support the output of the det box?

**Comment by ppwwyyxx** [comment]
In the demo we only draw Panoptic Segmentation, but the output of Panoptic FPN contains the "instances" key and therefore contains bounding boxes. Model output format is described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
