### ISSUE TITLE
Is there an implementation of Faster RCNN based on detectron2?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#597]
## ❓ Is there an implementation of Faster RCNN based on detectron2?
I am wondering if there is an implementation of Faster RCNN based on detectron2, because I will do my research about object detection based on Mask RCNN. And if only considering the task of object detection instead of segmentation, the only difference between Mask RCNN and Faster RCNN is the use of RoI Align.

In fact, I also don't quite understand the relation between Mask RCNN and detectron2.

**Comment by yc-zc** [comment]
Yes there is. 
You can find the config files of faster rcnn at https://github.com/facebookresearch/detectron2/tree/master/configs/COCO-Detection

detectron2 is the next generation of detectron, it is a software system that implements sota object detection algorithms, and I believe you know that Mask RCNN is one of the sota algorithms.

**Comment by songyuc** [comment]
> Yes there is.
> You can find the config files of faster rcnn at https://github.com/facebookresearch/detectron2/tree/master/configs/COCO-Detection
> 
> detectron2 is the next generation of detectron, it is a software system that implements sota object detection algorithms, and I believe you know that Mask RCNN is one of the sota algorithms.

I could see that it seems the detectron2 build a model by the `.yaml` config file, which I am not quite familiar.

And another question of mine is that I need to change the structure of the Faster RCNN to do my research experiment, like the anchors in the Faster RCNN, about which I am not sure whether detectron2 could realize my goal?

**Comment by yc-zc** [comment]
> > Yes there is.
> > You can find the config files of faster rcnn at https://github.com/facebookresearch/detectron2/tree/master/configs/COCO-Detection
> > detectron2 is the next generation of detectron, it is a software system that implements sota object detection algorithms, and I believe you know that Mask RCNN is one of the sota algorithms.
> 
> I could see that it seems the detectron2 build a model by the `.yaml` config file, which I am not quite familiar.
> 
> And another question of mine is that I need to change the structure of the Faster RCNN to do my research experiment, like the anchors in the Faster RCNN, about which I am not sure whether detectron2 could realize my goal?

You can definitely "realize your goal", but the config files in detectron2 are less detailed, which means you cannot change the structure by simply edit the config file, what you need to do is to rewrite the code. Or instead, you could also ask @ppwwyyxx if there's a plan to move the structure config to the config file, like what they do in https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml
