### ISSUE TITLE
Is there any memory-efficient function computing iou？

### ISSUE THREAD

**Issue by LaoYang1994** [facebookresearch/detectron2#598]
## 🚀 Feature

A memory-efficient iou computing function.
## Motivation

In general scene, there are only a few (maybe about 10 ~ 20) objects in a image. But in dense scene, such as supermarker, the number of objects in one image can reach 100 ~ 200, where the "pairwise_iou" function may cost too much memory.

**Comment by ppwwyyxx** [comment]
It's good to make every function more memory efficient, run faster, etc. But without a concrete suggestion on how to achieve it it's hard to consider it as a "feature request".
