### ISSUE TITLE
Output detection metrics/bounding boxes overlaid on ground truth boxes

### ISSUE THREAD

**Issue by djpecot** [facebookresearch/detectron2#599]
Using the tutorial [https://gilberttanner.com/blog/detectron-2-object-detection-with-pytorch](here), I managed to get my custom dataset running and detecting (NOTE: My dataset is a single class, and I am doing plain old non-rotated bounding boxes). I have registered my coco instances using the following chunk of code to get separate train/validation sets:

`# Register training dataset
register_coco_instances("breaks_train", {}, "/gdrive/blah/drive/here/folder/train.json", "/gdrive/some/folder/here/trainandvalidfolders/Train")
`

`# Register validation dataset
register_coco_instances("breaks_valid", {}, "/gdrive/blah/drive/here/folder/valid.json", "/gdrive/some/folder/here/trainandvalidfolders/Valid")
`

After training, I would like to get back the AP and AR, and any other metrics that may be useful. Ideally, I'd like to be able to ouput a Precision-Recall curve for various IOU values like in the COCO challenge. I'm kind of a noob to object detection and pytorch in general, so any code snippets or chunks would be very appreciated!

**Comment by ppwwyyxx** [comment]
The official colab tutorial at https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 contains code to run evaluation and produce AP/AR.
It also stores all predictions made on the dataset at `./output/inference` in COCO format so you can compute more custom metrics using the predictions..

**Comment by djpecot** [comment]
> The official colab tutorial at https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 contains code to run evaluation and produce AP/AR.
> It also stores all predictions made on the dataset at `./output/inference` in COCO format so you can compute more custom metrics using the predictions..

Thank you very much! Missed that detail. I don't see any code for uploading predicted bounding boxes on top of GT boxes though. Is there any code that exists to perform this kind of visualization task?

**Comment by ppwwyyxx** [comment]
No. You can use https://detectron2.readthedocs.io/modules/utils.html#module-detectron2.utils.visualizer to draw them yourself.

**Comment by Labaien96** [comment]
Hi @djpecot , I also want to visualize bot GT boxes and predicted boxes in the same image, do you know how to do it?

**Comment by datleeee** [comment]
Hi @djpecot @Labaien96 , did you guys figure out how to do it?
