### ISSUE TITLE
So "pip install -e ." is the rebuild operation?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#600]
## ❓ So "pip install -e ." is the rebuild operation?

I see the Note in the Installation that said "you often need to rebuild detectron2 after reinstalling PyTorch.", but there are multiple commands in that section, as
```git clone https://github.com/facebookresearch/detectron2.git
cd detectron2
pip install -e .

# or if you are on macOS
# MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install -e .

# or, as an alternative to `pip install`, use
# python setup.py build develop
```

So my question is whether the "pip install -e ." is the rebuild operation other than any others?

**Comment by ppwwyyxx** [comment]
You need to `rm -rf build **/*.so` and then rerun `pip install`

**Comment by songyuc** [comment]
@ppwwyyxx , thank you for your reponse!
I see there is something about `.so`, so Detectron2 is not a pure Python library, am I right?

**Comment by ppwwyyxx** [comment]
You're right.

**Comment by songyuc** [comment]
@ppwwyyxx Thank you for the explanation.
Happy new year!!!

**Comment by songyuc** [comment]
@ppwwyyxx , I still have a little quetion that, as the Installation that said "you often need to rebuild detectron2 after reinstalling PyTorch.", does it mean that Detectron2 is strongly dependent on the version PyTorch, so if we reinstalled another version of PyTorch, we would need to our Detectron2 so they could be compatible, am I right?

**Comment by ppwwyyxx** [comment]
Yes.
