### ISSUE TITLE
How to close the command window?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#601]
## ❓ How to close the command window?

I am doing a little experiment in the [GETTING_STARTED.md](https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md), with
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
	[--other-options]
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
And here is my result,
![图片](https://user-images.githubusercontent.com/27288110/71638756-655b6000-2ca3-11ea-9e4c-d112fbecf3af.png)
and it shows there is 0 instances.

Question1: why it shows no instances? Is it due to my special case of my picture?
And here is the picture,
![图片](https://user-images.githubusercontent.com/27288110/71638766-a05d9380-2ca3-11ea-8bb3-cc7b03d4457c.png)

Question2: how to close this command window? Could I just close it, or is there any shortkey like `ctrl + C` or something like that?
I have tried `ctrl + C`, which seems to be not useful.

**Comment by ppwwyyxx** [comment]
> Question1: why it shows no instances? Is it due to my special case of my picture?

You did not follow the `MODEL.WEIGHTS` part of the command.

> Question2: how to close this command window?
 
https://github.com/facebookresearch/detectron2/blob/2ff292c82bb449aaddbc40b310fd0b4d485096a6/demo/demo.py#L90-L102

**Comment by songyuc** [comment]
@ppwwyyxx let me check it.
Do you mean I should change the `MODEL.WEIGHTS` in `configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml`?
I opened it and found this,
![图片](https://user-images.githubusercontent.com/27288110/71639696-1e2a9a80-2cb6-11ea-8a43-1f6060326dc4.png)
So if I used the command,
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
	[--other-options]
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
I should changed the config as,
`WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"`
am I right?

**Comment by ppwwyyxx** [comment]
You should use the command
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
  --input input1.jpg input2.jpg \
  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```

**Comment by songyuc** [comment]
@ppwwyyxx I am sorry for that, because I am a beginner.
And I found something like a bug,
I used the above command,
and in fact, there is no `input2.jpg`, only `input1.jpg` in the folder,
And at this time, the program cannot quit even if I press esc button,
and would show this,
![图片](https://user-images.githubusercontent.com/27288110/71639822-e83ae580-2cb8-11ea-8974-d7cce8af523c.png)

**Comment by ppwwyyxx** [comment]
Esc needs to be pressed on the image window to close the image window.

**Comment by songyuc** [comment]
@ppwwyyxx Appreciate it very much!
