### ISSUE TITLE
How to solve WARNING [01/01 18:07:49 d2.config.compat]: Config '***/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#602]
## ❓ How to solve WARNING [01/01 18:07:49 d2.config.compat]: Config '***/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.

When I did my experiment today, I have always seen these is a warning as,
> WARNING [01/01 18:07:49 d2.config.compat]: Config '***/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.

So how can I solve this, do I need to add some information into the .yaml file?

Your suggestion will be appreciated!

**Comment by ppwwyyxx** [comment]
This is working as expected since the official configs are not versioned. We'll improve the message

**Comment by hosnasattar** [comment]
could we remove this warning print out?

**Comment by doctorcolossus** [comment]
Wondering the same... How to specify the correct version in our yaml?
