### ISSUE TITLE
The reason of using itertools.chain.from_iterable to produce the polygon coordinates list

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#606]
## ❓ The reason of using `itertools.chain.from_iterable` to produce the `poly` list

Questions like:
Today I am reading the code of Detectron2 Tutorial.ipynb to learn how to write a custom dataset loader, and I saw this snippet,
```Python
annos = v["regions"]
objs = []
for _, anno in annos.items():
    assert not anno["region_attributes"]
    anno = anno["shape_attributes"]
    px = anno["all_points_x"]
    py = anno["all_points_y"]
    poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
    poly = list(itertools.chain.from_iterable(poly))

    obj = {
        "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
        "bbox_mode": BoxMode.XYXY_ABS,
        "segmentation": [poly],
        "category_id": 0,
        "iscrowd": 0
    }
    objs.append(obj)
record["annotations"] = objs
dataset_dicts.append(record)
```
And you can see that, here the function `itertools.chain.from_iterable` was used to transform the `poly` list, which seems not to be that intuitive.
I feel that `itertools.chain.from_iterable` is an efficient way to concatenate multiple iterables, but as here the chain iterables `itertools.chain.from_iterable(poly)` is finally transformed into a list as `list(chain_iterables )`, so the efficient purpose does not apply here.

So I am wondering the reason of using `itertools.chain.from_iterable` to produce the `poly` list?

Your answer will appreciated!

**Comment by ppwwyyxx** [comment]
There is no specific reason other than that it works.

**Comment by songyuc** [comment]
@ppwwyyxx It seems strange, as `poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]` is `list` indeed.
What is the purpose of this additional code `poly = list(itertools.chain.from_iterable(poly))`?

**Comment by ppwwyyxx** [comment]
As you said it is to concatenate multiple iterables (multiple tuples in this case).
