### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found 

### ISSUE THREAD

**Issue by riven314** [facebookresearch/detectron2#609]
I encountered the following error when executing ```from detectron2.utils.visualizer import Visualizer```:   
```
>>> from detectron2.utils.visualizer import Visualizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/whlau/faster-rcnn/detectron2/detectron2/utils/visualizer.py", line 7, in <module>
    import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/whlau/anaconda3/envs/detectron2/lib/python3.6/site-packages/../../libopencv_objdetect.so.4.2)
````  
The above error suggests that the error possibly comes from ```import cv2```, but strange thing is when I do ```import cv2``` independently, no error occurs as shown:
```
>>> import cv2
>>> 
```

#### Reproducing My Error  
The OS I am using is Ubuntu 16.04.3 LTS. I install prerequisite and Detectron2 by the following commands:  
1. ```$ conda create --name detectron2 python=3.6```
2. ```$ conda activate detectron2```
3. ```$ pip install -U torch torchvision```
4. ```$ pip install cython; pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'```
5. ```$ conda install -c conda-forge opencv```
6. ```$ git clone https://github.com/facebookresearch/detectron2.git```
7. ```$ cd detectron2```
8. ```$ pip install -e .```
9. open Python and run my command (i.e. ``` from detectron2.utils.visualizer import Visualizer```)

#### Output From ```python -m detectron2.utils.collect_env```
```
$ python -m detectron2.utils.collect_env
------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  not available
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            False
Pillow                    6.1.0
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
We cannot help much with environment issues unless we can reproduce them easily (in a docker or colab, for example). The following in `INSTALL.md` is relevant and may help you:
>  Undefined C++ symbols in `detectron2/_C*.so`.
Usually it's because the library is compiled with a newer C++ compiler but run with an old C++ run time. This can happen with old anaconda.
Try conda update libgcc. Then remove the files you built (build/, **/*.so) and rebuild them.

**Comment by ciaobladoo** [comment]
I had the exact same problem and observation. Did you resolve the issue?

**Comment by deepak242424** [comment]
I am also facing the same issue. @riven314 were you able to solve it?
