### ISSUE TITLE
What is the meaning of lambda d=d: get_balloon_dicts("balloon/" + d)

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#611]
## ❓ What is the meaning of `lambda d=d: get_balloon_dicts("balloon/" + d)`
Today I continue reading the code of Detectron2 Tutorial.ipynb to learn how to write a custom dataset loader, and I saw this snippet,
```Python
from detectron2.data import DatasetCatalog, MetadataCatalog
for d in ["train", "val"]:
    DatasetCatalog.register("balloon_" + d, lambda d=d: get_balloon_dicts("balloon/" + d))
    MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])
balloon_metadata = MetadataCatalog.get("balloon_train")
```
Here I saw an kind of  `lamda` expression I have never seen before as `lambda d=d: get_balloon_dicts("balloon/" + d)`,
so what is the meaning of "d=d" here?

Your answer will appreciated!

**Comment by ppwwyyxx** [comment]
Detectron2 issue is not a good place to learn about the python language.

You may read something at https://stackoverflow.com/questions/10452770/python-lambdas-binding-to-local-values.
