### ISSUE TITLE
Error in Colab Notebook example

### ISSUE THREAD

**Issue by tema7707** [facebookresearch/detectron2#612]
I encountered an error when running the Detectron2 example in [Colab Notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5).

> /usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py in <module>()
>       3 import sys
>       4 import math
> ----> 5 from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
>       6 try:
>       7     import accimage
> 
> ImportError: cannot import name 'PILLOW_VERSION'

The error is not in Detectron2, but in PyTorch. But you can change the tutorial by adding `!pip install Pillow==6.2.2` in the notebook until the bug is fixed in the PyTorch. Then people will not be confused. 

Thanks!

**Comment by ppwwyyxx** [comment]
Already fixed in torchvision (https://github.com/pytorch/vision/issues/1490), but nothing can be done on old versions of torchvision.

**Comment by ppwwyyxx** [comment]
According to https://github.com/pytorch/vision/issues/1712#issuecomment-570286349 the new release next week will not have this issue.

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin
