### ISSUE TITLE
 Cannot import name 'PILLOW_VERSION'

### ISSUE THREAD

**Issue by nodechef** [facebookresearch/detectron2#615]
## Instructions To Reproduce the Issue:

1. Using Google Colab and everything was installed perfectly but when importing 
from detectron2.engine import DefaultPredictor. It throws this error.  
```
ImportError                               Traceback (most recent call last)
<ipython-input-24-765b2c17dc47> in <module>()
----> 1 from detectron2.engine import DefaultPredictor

8 frames
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py in <module>()
      3 import sys
      4 import math
----> 5 from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
      6 try:
      7     import accimage

ImportError: cannot import name 'PILLOW_VERSION'
```
2. what exact command you run: **from detectron2.engine import DefaultPredictor**
3. Tried to install Pillow but still facing this error.

**Comment by nodechef** [comment]
Duplicate.

**Comment by xjtlbc** [comment]
how did u solve this problem

**Comment by ppwwyyxx** [comment]
It's a duplicate of #614
