### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.TENSOR_MASK'

### ISSUE THREAD

**Issue by wiamadaya** [facebookresearch/detectron2#616]
I am trying to run a pre-trained TensorMask model, but encounter the following error:

`KeyError: 'Non-existent config key: MODEL.TENSOR_MASK'`

this is how i load the config and the model:

```
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/detectron2/TensorMask/tensormask_R_50_FPN_1x/152549419/model_final_8f325c.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
```

**Comment by ppwwyyxx** [comment]
This is what the tensormask code does: https://github.com/facebookresearch/detectron2/blob/0a7a9d10c414f49e3c5bd1d32fbfae7c3606c9af/projects/TensorMask/train_net.py#L27-L37
