### ISSUE TITLE
Is Detectron2 a good choice for deployment?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#617]
## ❓ Is Detectron2 a good choice for deployment?

Recently, I am working on a engeering program of pedestrian detection and recognition. After my study these days, I found Detectron2 is like packaging of torch for vision task, but the model procedure seems not that visible, which is described in the `.yaml` file. So I am worrying whether Detectron2 is a good choice for engineering deployment.

Any answer or suggestion will be appreciated!

**Comment by ppwwyyxx** [comment]
please search for "deployment" in issues and you'll see issues like #8 or  #12
