### ISSUE TITLE
Mean Std Normalization in COCO models

### ISSUE THREAD

**Issue by ahsan44411** [facebookresearch/detectron2#618]
## ❓ How to use Detectron2

In the comments of config/default.py  ( https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py  )it is mention that it Normalizes the data according to ImageNet with the default mean and std normalization values. Does Detectron 2 normalize data when using COCO model?

**Comment by ppwwyyxx** [comment]
Detectron2 normalizes data according to the config.

**Comment by ahsan44411** [comment]
The default values for STD in mask_rcnn_X_101_32x8d_FPN_3x is [57.375, 57.120, 58.395] but that is a file for ImageNet weights will it work the same for COCO weights and if so what are the values for MEAN normalization?

**Comment by ppwwyyxx** [comment]
It will

**Comment by ahsan44411** [comment]
Values for MEAN normalization?

**Comment by ppwwyyxx** [comment]
The values that's currently used by the config will work.
