### ISSUE TITLE
Is it possible to get scores for semantic segmentation?

### ISSUE THREAD

**Issue by isagastiberri** [facebookresearch/detectron2#619]
Hello, I see that instance segmentation has **score** as one of the fields but not semantic segmentation. , which is the output format for COCO. I'd like to get scores for semantic segmentation, which I suppose it's possible as internally they are needed to decide which id to assign to that pixel but I can't find where this is in the code. Could you tell me where to find this? Thanks a lot!

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/models.html#model-output-format

The output for semantic segmentation:
> “sem_seg”: Tensor of (num_categories, H, W), the semantic segmentation prediction.

are already scores

**Comment by isagastiberri** [comment]
@ppwwyyxx thanks for the quick reply! When I check the sem_seg value in the output, it has [67, 966, 1280] which I understand it means that there is 67 classes and the values are the probability of the pixel being that class. But, when I look at the values I have something like [-1.9294, -1.9294, -1.9030,  ..., -1.3107, -1.1679, -0.9644]. How do these values correspond with probabilities?

**Comment by isagastiberri** [comment]
@ppwwyyxx I'm looking at detectron2/modeling/meta_arch/panoptic_fpn.py and I see that to get semantic segmentation of the image by class you do sem_seg.argmax(dim=0) and that gives you the class id, so to get those max score value I did sem_seg.max(dim=0) and the scores I get are tensor([[4.2200, 4.2200, 4.2563,  ..., 5.2198, 5.2282, 5.2282],
        [4.2200, 4.2200, 4.2563,  ..., 5.2198, 5.2282, 5.2282],
        [4.2261, 4.2261, 4.2596,  ..., 5.2588, 5.2718, 5.2718],
        ...,
        [5.0020, 5.0020, 4.7738,  ..., 6.8770, 6.9219, 6.9219],
        [5.0820, 5.0820, 4.8797,  ..., 6.7089, 6.7481, 6.7481],
        [5.2660, 5.2660, 5.0926,  ..., 6.5988, 6.6351, 6.6351]],
       device='cuda:0')
Is there any way to convert those into probabilities so that I can have the score value in the segments_info like it's already done for instances?

**Comment by isagastiberri** [comment]
I just realised that I can just apply a softmax to sem_seg over dimension 0 to convert the values into probabilities. Thanks for your help anyways!
