### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by soheer** [facebookresearch/detectron2#620]
When I run this command :
python setup.py build develop or "pip install -e ."
I got this error :

![image](https://user-images.githubusercontent.com/15982135/71721117-a3d05680-2e2c-11ea-8db9-9830046a65b6.png)

Thank you

**Comment by ahsan44411** [comment]
Try using python setup.py build develop

**Comment by ppwwyyxx** [comment]
Your cuda installation is broken. If you do have `cicc` in `/usr/lib/cuda/nvvm/bin`, please add `/usr/lib/cuda/nvvm/bin` to your PATH to workaround this. 

closing as it's unrelated to detectron2.
Next time please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
