### ISSUE TITLE
 How will I run tensormask？

### ISSUE THREAD

**Issue by woshiwoyali** [facebookresearch/detectron2#623]
python demo.py  --config-file  /home/zjs/Downloads/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml  --input /home/zjs/Desktop/1.jpeg  --opts MODEL.WEIGHTS  https://dl.fbaipublicfiles.com/detectron2/TensorMask/tensormask_R_50_FPN_1x/152549419/model_final_8f325c.pkl

Error occurred

[01/04 16:06:08 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/home/zjs/Downloads/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml', input=['/home/zjs/Desktop/1.jpeg'], opts=['MODEL.WEIGHTS', 'https://dl.fbaipublicfiles.com/detectron2/TensorMask/tensormask_R_50_FPN_1x/152549419/model_final_8f325c.pkl'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 71, in <module>
    cfg = setup_cfg(args)
  File "demo.py", line 23, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/zjs/Downloads/detectron2/detectron2/config/config.py", line 45, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.TENSOR_MASK'

import numpy as np
import cv2
from matplotlib import pyplot
import matplotlib.pyplot as plt
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()
import sys
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
path=sys.argv[1]
im = cv2.imread(path)
cfg = get_cfg()
cfg.merge_from_file("/home/zjs/Downloads/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml")
cfg.merge_from_list("/home/zjs/Downloads/model_final_8f325c.pkl")
cfg.freeze()
default_setup(cfg, args)
predictor = DefaultPredictor(cfg)
outputs = predictor(im)

#
pred_classes = outputs["instances"].pred_classes
pred_boxes = outputs["instances"].pred_boxes
print(pred_classes)
print(pred_boxes)

#在原图上画出检测结果
v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.0)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
plt.figure(2)
plt.imshow(v.get_image()[:, :, ::-1])
plt.show()

python 123.py  /home/zjs/Desktop/1.jpeg 

Error occurred

Traceback (most recent call last):
  File "123.py", line 16, in <module>
    cfg.merge_from_file("/home/zjs/Downloads/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml")
  File "/home/zjs/Downloads/detectron2/detectron2/config/config.py", line 45, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.TENSOR_MASK'

How will I run tensormask?

**Comment by ppwwyyxx** [comment]
`demo.py` is a detectron2 script and tensormask is not part of detectron2. Therefore `demo.py` cannot run a tensormask model.

You need to do `import tensormask` and add_tensormask_config` in demo.py so that it knows what is tensormask.

**Comment by woshiwoyali** [comment]
In demo.py, I import tensormask and add tensormask config (CFG), but there are still errors. NameError: name 'add tensormask config' is not defined
Execution code:
import numpy as np
Import CV2
from matplotlib import pyplot
import matplotlib.pyplot as plt
import tensormask
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()
Import sys
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
path=sys.argv[1]
im = cv2.imread(path)
cfg = get_cfg()
add_tensormask_config(cfg)
cfg.merge_from_file("/home/zjs/Downloads/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml")
cfg.merge_from_list("/home/zjs/Downloads/model_final_8f325c.pkl")
Cfg.freeze ()
default_setup(cfg, args)
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
pred_classes = outputs["instances"].pred_classes
pred_boxes = outputs["instances"].pred_boxes
print(pred_classes)
print(pred_boxes)




#Draw the test result on the original picture

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.0)

v = v.draw_instance_predictions(outputs["instances"].to("cpu"))

plt.figure(2)

plt.imshow(v.get_image()[:, :, ::-1])

Plt.show ()



So which Python script should I use to execute tensormask? If it doesn 't have demo.py?

**Comment by ppwwyyxx** [comment]
`add_tensormask_config` is defined in tensormask.
You need `from tensormask import add_tensormask_config`

**Comment by woshiwoyali** [comment]
Downloads/detectron2/projects/TensorMask$ tree ./
./
├── build
│   ├── lib.linux-x86_64-3.6
│   │   └── tensormask
│   │       ├── arch.py
│   │       ├── _C.cpython-36m-x86_64-linux-gnu.so
│   │       ├── config.py
│   │       ├── __init__.py
│   │       └── layers
│   │           ├── __init__.py
│   │           └── swap_align2nat.py
│   └── temp.linux-x86_64-3.6
│       └── home
│           └── zjs
│               └── Downloads
│                   └── detectron2
│                       └── projects
│                           └── TensorMask
│                               └── tensormask
│                                   └── layers
│                                       └── csrc
│                                           ├── SwapAlign2Nat
│                                           │   └── SwapAlign2Nat_cuda.o
│                                           └── vision.o
├── configs
│   ├── Base-TensorMask.yaml
│   ├── tensormask_R_50_FPN_1x.yaml
│   └── tensormask_R_50_FPN_6x.yaml
├── output
│   ├── config.yaml
│   └── log.txt
├── README.md
├── setup.py
├── tensormask
│   ├── arch.py
│   ├── _C.cpython-36m-x86_64-linux-gnu.so
│   ├── config.py
│   ├── __init__.py
│   ├── layers
│   │   ├── csrc
│   │   │   ├── SwapAlign2Nat
│   │   │   │   ├── SwapAlign2Nat_cuda.cu
│   │   │   │   └── SwapAlign2Nat.h
│   │   │   └── vision.cpp
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-36.pyc
│   │   │   └── swap_align2nat.cpython-36.pyc
│   │   └── swap_align2nat.py
│   └── __pycache__
│       ├── arch.cpython-36.pyc
│       ├── config.cpython-36.pyc
│       └── __init__.cpython-36.pyc
├── tensormask.egg-info
│   ├── dependency_links.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   └── top_level.txt
├── tests
│   ├── __init__.py
│   └── test_swap_align2nat.py
└── train_net.py

25 directories, 36 files

Which script do I need to run tensormask?

**Comment by ppwwyyxx** [comment]
If you want to run a tensormask inference demo like `demo.py`, there is no script that does it. Taking `demo.py` to create your own is the easiest way.
