### ISSUE TITLE
anchor_generator caffe2 conversion choice in RetinaNet

### ISSUE THREAD

**Issue by ArutyunovG** [facebookresearch/detectron2#626]
I'm just curious, what was the reason of not utilising PriorBoxOp which was performing tiling of cell anchors with continious coordinates (I'm refering to pytorch PR on SSD inference)?
When doing that work, I didn't like the fact, that GenerateProposals needs tiling as well, and having the same functionality twice is actually duplication of code. But modifiying GenerateProposals was unnessesary to solve the task of exporting SSDs and I left GenerateProposals with the thinking 'the less changes the better'.
But serialising anchor_generator instead of using a dedicated unified (between GenerateProposals and RetinaNet) tiling operator / function, as it is done now feels a bit unexpected.

**Comment by ArutyunovG** [comment]
I'd like to emphasize once again, that this question comes out of professional curiosity.
It is not a problem to finalize conversion on my side in any way I'll need, and I thank you for the presented exporting code.

**Comment by ppwwyyxx** [comment]
cc @wat3rBro: this is about https://github.com/pytorch/pytorch/pull/14697 that contains a caffe2 op to generate anchors.

**Comment by ppwwyyxx** [comment]
Closing as we will remove caffe2 deployment support and only use torchscript. Torchscript will have no issue saving the anchors as part of the model.

**Comment by ArutyunovG** [comment]
@ppwwyyxx Thanks for letting know this in advance. If you have plans to remove caffe2 completely from pytorch repository which can be disclosed it will be nice to know it to be ready as well.

**Comment by ppwwyyxx** [comment]
I don't have info on that. I think caffe2 will live in pytorch repo for a long time but likely won't be included inside future binary releases of pytorch.
