### ISSUE TITLE
Zero loss_box_reg

### ISSUE THREAD

**Issue by adauphin** [facebookresearch/detectron2#627]
Hello,

I am trying to train on my custom dataset (only one class, one bbox per image, no segmentation). My goal is to predict the correct class and the bbox after training. I followed the tutorial of detectron2 but I see a difference when I train: the loss_box_reg is always 0. Also, the prediction after training works 

For example: `total_loss: 0.850  loss_cls: 0.848  loss_box_reg: 0.000  loss_mask: 0.000  loss_rpn_cls: 0.002  loss_rpn_loc: 0.000`

Do you have an idea why it is so?

**Comment by ppwwyyxx** [comment]
If you didn't make other mistakes, then it means the prediction is good.

Closing as this is not an unexpected issue, a feature request, or about how to do something.

**Comment by djpecot** [comment]
It looks like your model is masking as well. You mentioned you are just doing bbox and no segmentation, so you might try loading up one of the "Object Detection Baseline" models and it's corresponding weights. 

https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by cybaj** [comment]
In my case, this results occurred when my annotations have it's `category_id` property which *starts from 1, not 0*. Maybe you should check this out.

**Comment by GalAllegroAi** [comment]
@adauphin, @djpecot, you can also set cfg.MODEL.MASK_ON = False. It will work with the MaskRCNN Model as well.

**Comment by KangolHsu** [comment]
I remove empty "segmentation" value in coco format json file，then it goes right now
