### ISSUE TITLE
caffe2export problem

### ISSUE THREAD

**Issue by kl720** [facebookresearch/detectron2#629]
python3 caffe2_export.py ,RuntimeError:No such operator caffe2::AliasWithName

**Comment by ppwwyyxx** [comment]
The new export feature to be added requires pytorch built from master.

**Comment by kl720** [comment]
any doc or examples?

**Comment by ppwwyyxx** [comment]
it's a new feature, so not yet.

**Comment by chiehpower** [comment]
Hi all, 

Is there any update?
I also met this same problem...

**Comment by ppwwyyxx** [comment]
The documentation https://detectron2.readthedocs.io/tutorials/deployment.html has instructions how to use the export feature.
