### ISSUE TITLE
Is there an implementation of SSD?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#631]
## ❓ Is there an implementation of SSD?

Hi, guys!
I want to know whether there is an implementation of SSD in Detectron2?
I have checked in the [Detectron2 Model Zoo and Baselines](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#detectron2-model-zoo-and-baselines), in which there is nothing mentioned about SSD.

Any answer will be appreciated!

**Comment by ppwwyyxx** [comment]
There isn't.

**Comment by songyuc** [comment]
@ppwwyyxx thank you!
