### ISSUE TITLE
how to test with a dataset to get the "output/results.json"?

### ISSUE THREAD

**Issue by garyliu0816** [facebookresearch/detectron2#632]
## ❓ how to test with a dataset to get the "output/results.json"?

 1. If the dataset has no annotations, how to register it?
 2. Can I test the dataset in command line?

**Comment by ppwwyyxx** [comment]
If by "test" you mean run the model and get results, it's documented in https://detectron2.readthedocs.io/tutorials/models.html.

You can still register the dataset the same way as https://detectron2.readthedocs.io/tutorials/datasets.html#register-a-dataset

**Comment by garyliu0816** [comment]
It's difficult to register the dataset, because there is no annotations. when register the dataset you need to write a function which return the dicts include images's annotations. How to ignore it?

**Comment by ppwwyyxx** [comment]
You can just return dicts that do not include annotations.
