### ISSUE TITLE
Dense Pose Dataset Not Match

### ISSUE THREAD

**Issue by dihuangdh** [facebookresearch/detectron2#633]
Hi @ppwwyyxx 

Thanks for your awesome work!

In dense pose project, the dense pose coco datasets are named like `densepose_train2014.json`, but when I download the data from original repo, the dataset files are named like `densepose_coco_2014_train.json` . What's the difference of them? 

Aslo, seems the original repo doesn't provide `densepose_minival2014_100.json`. 

Will you add some lines about dataset configuration to the doc?

Thx

**Comment by ppwwyyxx** [comment]
> What's the difference of them?

there is not difference but the naming.

> seems the original repo doesn't provide densepose_minival2014_100.json.

we forget to provide it though it's for testing only.

**Comment by dihuangdh** [comment]
Thanks for your quick reply.
