### ISSUE TITLE
Added an installation video need someone to merge it in master

### ISSUE THREAD

**Issue by jaskarannagi19** [facebookresearch/detectron2#634]
## 🚀 Feature
Added How to Install Video

## Motivation

Simple to get beginner by following the steps to install detectron

## Pitch

Note that we only consider adding new features if they are relevant to many users.
We do not take requests to implement recent research papers --
we only consider papers that have enough significance and prevalance.

We don't take feature requests for most projects in the `projects/` directory,
because they are research code release that is mainly for other researchers to reproduce results.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory
contains many of such examples.

**Comment by ppwwyyxx** [comment]
responded in #630
