### ISSUE TITLE
How to train only a particular head?

### ISSUE THREAD

**Issue by ranjeetthakur** [facebookresearch/detectron2#635]
Hi,
I want to train only my classification head of MaskRCNN keeping all heads freezed.
Please tell me how can I do this.
I found a way to freeze backbone using freeze_at option but how to freeze all heads except one?

**Comment by ppwwyyxx** [comment]
There is no option that does this. You need to write code.
You can freeze parameters by using `requires_grad` on parameters and please refer to pytorch documentation/community for that.

**Comment by nihal-rao** [comment]
Hi @ppwwyyxx , can I just place the forward pass for the head I want to freeze under  `with torch.no_grad()`  ? Is it the right way to do this?
