### ISSUE TITLE
Purpose of Having Dictionaries as Feature Inputs to The proposal_generator?

### ISSUE THREAD

**Issue by aligholami** [facebookresearch/detectron2#637]
Hi, I would like to know more about the rationale of using a dictionary as the features input to the `proposal_generator` that you have specified here: https://github.com/facebookresearch/detectron2/issues/628#issuecomment-571000885
Thanks!

**Comment by ppwwyyxx** [comment]
We want those features to have names since it matches the common academic terminologies.
