### ISSUE TITLE
Lost region index in a batch of images, when using ROIPooler (Performs aggregation)

### ISSUE THREAD

**Issue by aligholami** [facebookresearch/detectron2#638]
Hi. Please correct me if I'm wrong. When using `ROIPooler` to convert a batch of images, let's say a batch of 128 images to a bunch of region features, the `ROIPooler` automatically performs the aggregation step. So the output could be any number of regions, corresponding to the whole 128 images. Does that make sense when using the region features for tasks such as `object classification`?
Because when processing region features with a model like a `Graph Neural Network`, the regions are corresponding to different images, not objects within a single image!

I'm not sure if this is an issue, but I think it would be more reasonable to have the `ROIPooler` generate the regions while keeping the batch dimension. Although there might be a different number of regions and that makes things a bit harder to handle, we can easily set a maximum number of regions for all the images in a batch and fill those pointing to no object with zeros everywhere.

Thanks!

**Comment by ppwwyyxx** [comment]
> So the output could be any number of regions

no. the output number of regions, equal to the total number of boxes you provide as an argument, as documented https://detectron2.readthedocs.io/modules/modeling.html#detectron2.modeling.poolers.ROIPooler

you can get features per image by using `torch.split` on the outputs

**Comment by aligholami** [comment]
@ppwwyyxx Thanks. I think the parameter that you are referring to is `M` which is not an argument based on the docs. How do I set the parameter 'M` for my proposal network?

**Comment by aligholami** [comment]
For example, the `Base-RCNN-FPN.yaml` config file has no information about the number of output boxes for each image. Yet when I manually output the number of regions per image it is set to `19`.

**Comment by ppwwyyxx** [comment]
I don't know what's the context that you need this information. The total number of boxes is defined by the inputs to `proposal_generator` already and in the context of your previous issue #628 it is defined by you.
