### ISSUE TITLE
How to specify a tuple as a commandline argument

### ISSUE THREAD

**Issue by jasonyzhang** [facebookresearch/detectron2#639]
Currently, any argument at the end of the training command is used to override configs eg `python train_net.py OUTPUT_DIR output_dir`.

Is there any way to specify a tuple when overriding configs? My primary usecase for this is for specifying datasets which are tuples of strings in the config.

**Comment by ppwwyyxx** [comment]
`DATASETS.TRAIN '("dataset1", "dataset2")'`
