### ISSUE TITLE
how do you installing detectron2 on MacOS

### ISSUE THREAD

**Issue by aamirdogar** [facebookresearch/detectron2#644]
i have installed all pre-requisites already. but the final step of installation doesnt go as planned, it stops with error status 1 (What does this mean? as the syntax error doesnt tell much to fix)

HERE IS THE EXTRACT

Aam-MacBook:detectron2 aam$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install -e .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///Users/aam/detectron2
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/aam/detectron2/setup.py'"'"'; __file__='"'"'/Users/aam/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /Users/aam/detectron2/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/aam/detectron2/setup.py", line 86
        def get_model_zoo_configs() -> List[str]:
                                    ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Aam-MacBook:detectron2 aam$

**Comment by ppwwyyxx** [comment]
Install following [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md), and as the document says we do not support python 2.
