### ISSUE TITLE
panoptic_stuffonly bug

### ISSUE THREAD

**Issue by Baibaifan** [facebookresearch/detectron2#649]
## ❓ How to use Detectron2

Questions like:

1. How to do panoptic_stuffonly with detectron2?

NOTE:

1. In panoptic_stuffonly mode, the default calculation of detector_results and detector_losses in the panoptic_fpn.py script is problematic and cannot be commented out. Subsequent calculation of loss will also encounter problems.

**Comment by ppwwyyxx** [comment]
"panoptic_stuffonly" is a name of files. So I don't know what do you mean by "do panoptic_stuffonly". If you want to perform semantic segmentation, you can start with https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/semantic_R_50_FPN_1x.yaml though we don't have much support for it. 

If you met any unexpected problems and want to know why, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Baibaifan** [comment]
Hello, I adjusted it in my yaml file “ MODEL: META_ARCHITECTURE: "SemanticSegmentor". But in the last,  I started with https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-PanopticSegmentation/Base-Panoptic-FPN.yaml and changed "coco_2017_train_panoptic_separated" to "coco_2017_train_stuffonly". when I runned it , I met program errors in https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/panoptic_fpn.py line 95. I wanna konw the differents between MODEL: META_ARCHITECTURE: "SemanticSegmentor" and MODEL: META_ARCHITECTURE: "PanopticFPN" in the yaml file.

**Comment by Baibaifan** [comment]
Hello, I adjusted “ MODEL: META_ARCHITECTURE: "SemanticSegmentor" in my yaml file, and then the program is ok. But in the last, I started with https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-PanopticSegmentation/Base-Panoptic-FPN.yaml and changed "coco_2017_train_panoptic_separated" to "coco_2017_train_stuffonly". when I runned it , I met program errors in https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/panoptic_fpn.py line 95. I wanna konw the differents between MODEL: META_ARCHITECTURE: "SemanticSegmentor" and MODEL: META_ARCHITECTURE: "PanopticFPN" in the yaml file.
    On Wednesday, January 8, 2020, 10:07:35 AM PST, Yuxin Wu <notifications@github.com> wrote:  
 
 
"panoptic_stuffonly" is a name of files. So I don't know what do you mean by "do panoptic_stuffonly". If you want to perform semantic segmentation, you can start with https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/semantic_R_50_FPN_1x.yaml though we don't have much support for it.

If you met any unexpected problems and want to know why, please include details about the problem following the issue template.
