### ISSUE TITLE
any tridentnet pretrained-models?

### ISSUE THREAD

**Issue by patienceFromZhou** [facebookresearch/detectron2#65]
@jsoref  could you share links of tridentnet model in https://github.com/facebookresearch/detectron2/blob/master/projects/TridentNet/README.md for quick evaluations, thanks~

**Comment by jsoref** [comment]
@patienceFromZhou: eh? I have no affiliation with this repository nor with this entity.

**Comment by lyttonhao** [comment]
Thanks for your interest. We will release the pretrained TridentNet models soon.

**Comment by jsoref** [comment]
@patienceFromZhou: could you please remove me from the issue description?

**Comment by ppwwyyxx** [comment]
added by @lyttonhao
