### ISSUE TITLE
How to do multi-person pose tracking with detecron2?

### ISSUE THREAD

**Issue by plmsmile** [facebookresearch/detectron2#651]
## ❓ How to use Detectron2 to do multi-person pose tracking?

What I want like this [LightTrack](https://github.com/Guanghan/lighttrack):
1. Multi-Person pose estimation.
2. Identity each person with an ID.

![image](https://github.com/Guanghan/lighttrack/raw/master/demo/10F_mp.gif)

**Comment by ppwwyyxx** [comment]
Detectron2 includes Keypoint R-CNN for pose estimation and is demoed in https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5. It does not support pose tracking.
