### ISSUE TITLE
How to use other pytorch models in detectron2?

### ISSUE THREAD

**Issue by plmsmile** [facebookresearch/detectron2#653]
## ❓How to use [Higher-HRNet](https://github.com/HRNet/Higher-HRNet-Human-Pose-Estimation) in detectron2?  
Because I found its coco-keypoints performance is much better than the detectron2 model zoo models.
 
Simply:
1. How to use Higher-HRNet in detectron2 ?
2. How to use other excellent pytorch models in detectron2 ?

**Comment by ppwwyyxx** [comment]
The model does not exist in detectron2 and you can implement it yourself. See https://detectron2.readthedocs.io/tutorials/write-models.html .
