### ISSUE TITLE
Pre-defined color for dataset in COCO format

### ISSUE THREAD

**Issue by wiamadaya** [facebookresearch/detectron2#655]
How to use `stuff_colors` to pre-defined color for each stuff category for dataset in COCO format?

**Comment by ppwwyyxx** [comment]
I'm not sure I understand what you're trying to do, but `stuff_colors` is explained in docs: https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by wiamadaya** [comment]
I register my dataset as COCO and has set the `stuff_colors ` but the visualizer still give me random color, i did the following at the inference stage, or should it be done from the training stage?

```
register_coco_instances("my_dataset", {}, "./training.json", "./images")
dataset_metadata = MetadataCatalog.get("my_dataset")
MetadataCatalog.get("my_dataset").stuff_colors = [(102,255,102), (102,255,255), (102,102,255)]
```

**Comment by ppwwyyxx** [comment]
You should use "thing_colors" which is missing in documentation. "Stuff" means it's not for instances.

**Comment by wiamadaya** [comment]
i can't seem to get it worked neither prior to training nor inference, the color always came out random

`MetadataCatalog.get("my_dataset").thing_colors = [(102,255,102), (102,255,255), (102,102,255)]`

**Comment by ppwwyyxx** [comment]
Answered in docs https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode

**Comment by tom-bu** [comment]
I feel like the documentation is a little unclear that SEGMENTATION= 1 also covers thing AND stuff segmentation. I believe it also makes the bounding box color fixed per class.

**Comment by tom-bu** [comment]
I see now. If you set the stuff_color in the metadata, those colors will be fixed but the instances (thing classes) will still be randomized. If you set the instance_mode = ColorMode.SEGMENTATION, then all of the thing classes will follow the colors in the thing_color. I believe it not only affect the mask but also the bounding box coloring too.

**Comment by tom-bu** [comment]
I see now. If you set the stuff_color in the metadata, those colors will be fixed but the instances (thing classes) will still be randomized. If you set the instance_mode = ColorMode.SEGMENTATION, then all of the thing classes will follow the colors in the thing_color. I believe it not only affects the mask but also the bounding box coloring as well.

**Comment by DIANSLEE** [comment]
I believe that there are some bugs with setting thing_colors. after I set thing_colors to (255, 68, 79) and (255, 42, 4), the modified color is out of boundary which is 0.9999999998, 1.00000002,1.00000002

![Image](https://github.com/user-attachments/assets/cd0653f6-4373-47e6-9699-aaf03698b40a)

 return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "C:\Users\dians\Desktop\deep\detectron2-0.6\AppleKey\p2c-1k.py", line 48, in <module>
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
  File "C:\Users\dians\Desktop\deep\detectron2-0.6\detectron2\utils\visualizer.py", line 426, in draw_instance_predictions
    self.overlay_instances(
  File "C:\Users\dians\Desktop\deep\detectron2-0.6\detectron2\utils\visualizer.py", line 735, in overlay_instances
    self.draw_text(
  File "C:\Users\dians\Desktop\deep\detectron2-0.6\detectron2\utils\visualizer.py", line 880, in draw_text
    color = np.maximum(list(mplc.to_rgb(color)), 0.2)
  File "C:\Users\dians\.conda\envs\python10\lib\site-packages\matplotlib\colors.py", line 496, in to_rgb
    return to_rgba(c)[:3]
  File "C:\Users\dians\.conda\envs\python10\lib\site-packages\matplotlib\colors.py", line 299, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "C:\Users\dians\.conda\envs\python10\lib\site-packages\matplotlib\colors.py", line 395, in _to_rgba_no_colorcycle
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range
