### ISSUE TITLE
Getting annotation dicts after registering custom coco-format dataset

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#658]
Hi, I registered a custom COCO-format dataset using the [Detectron2 Colab notebook tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5). I would like to verify if the dataset is registered and I can see the bounding boxes on my images. 

![code](https://user-images.githubusercontent.com/30231581/72057730-dd093a80-32f4-11ea-9521-f5c60c1063f2.png)

However, I get the following error even though I have my dataset registered as per Dataset catalog list. I am able to get the meta_data for it too.

![error](https://user-images.githubusercontent.com/30231581/72056985-a67ef000-32f3-11ea-9026-39895b4f45ef.png)

**Comment by ppwwyyxx** [comment]
Please follow the documentation  
https://detectron2.readthedocs.io/modules/data.html#detectron2.data.get_detection_dataset_dicts

**Comment by Kbkartik** [comment]
Got it working. Thanks!
