### ISSUE TITLE
Set Scores to -1! (evaluate a model)

### ISSUE THREAD

**Issue by meltemtokgoz** [facebookresearch/detectron2#660]
Hello to everyone,

I train my own data using Detectron2 and I want to validation it with final_model.pth.
However, I cannot get a prediction result despite validation with the same data. 

Here is file structure

coco
	-images
		-val2017
			1.jpg
			2.jpg
			...
		-train2017
			1.jpg
			2.jpg
			...
	-annotations
		-instances_train2017.json
		-instances_val2017.json

Here is the command I run:

python tools/train_net.py --config-file configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0001 SOLVER.MAX_ITER 100

And it outputs like this. 

![Ekran Görüntüsü (184)](https://user-images.githubusercontent.com/24324909/72065897-581c2200-32f0-11ea-9dcf-1e42c4bef766.png)

What should I do?
Thank you.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) says, 
> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
