### ISSUE TITLE
How to install detectron2 without cloning git repository?

### ISSUE THREAD

**Issue by marcespano** [facebookresearch/detectron2#664]
## ❓ How to install detectron2 without cloning repository?

Hi,
I wanted to know if it is possible to install detectron2 using just a pip command like "pip install git+https://github.com/facebookresearch/detectron2"?
If not, is it possible to add detectron2 to my project folder and then import it to my Python script without installing it?

Thanks!

**Comment by ppwwyyxx** [comment]
`pip install 'git+https://github.com/facebookresearch/detectron2.git'`
