### ISSUE TITLE
caffe2 speed_benchmark on Android aborts

### ISSUE THREAD

**Issue by zetyquickly** [facebookresearch/detectron2#669]
Hello, 

First of all, I do understand that developing is in progress.

Taking into account the latest commits up to https://github.com/facebookresearch/detectron2/commit/b7ec43667df44fe5a483e0058ade2d44691e96bf. I've tried to run exported model on mobile.

According to https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html I've used `speed_benchmark` built from `pytorch==1.5.0a0` sources.

These runs are failing. For example running of the model from `Base-RetinaNet.yaml` which doesn't contain `nms` nor `roi_align`: 
`./speed_benchmark  --net /data/local/Detectron2Mobile/models/Base-RetinaNet.pb --init_net /data/local/Detectron2Mobile/models/Base-RetinaNet_init.pb --input_dims '1,3,800,1088;1,3' --input 'data,im_info' --input_type 'float;float'`

Stops with message `Killed` and smartphones UI restarts. I cannot figure out how to produce more meaningful logs. If you do let me help the development with such information

Note that models that worked before are still working with this build.

**Comment by ppwwyyxx** [comment]
`--input_dims '1,3,800,1088;1,3'` will not produce valid inputs for the model. Also the builtin retinanet is much larger than what is typically deployed on mobile so may require much more memory.

**Comment by zetyquickly** [comment]
Thank you, for the response @ppwwyyxx 
You are definitely right builtin retinanet was too tough for my test device. For anyone who wants to test new feature I would recommend fasterrcnn on R50, ofcourse for some phones this model might exceed device's RAM too
About `--input_dims '1,3,800,1088;1,3'` I think these are right inputs for the model according to tensor shapes that are passed to C2 model in `ProtobufModel.inference()`

**Comment by ppwwyyxx** [comment]
An example using the caffe2 model in C++ is provided in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python.
