### ISSUE TITLE
I cannot open the out put "events.out.tfevents.1571020886.2354ff163c7b.166.0" file with tensorboard...

### ISSUE THREAD

**Issue by a954217436** [facebookresearch/detectron2#67]
I use "tensorboard --logdir=./DIR". But it seems that the tensorboard cannot recognize the file...

**Comment by PumayHui** [comment]
The same question...

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template you deleted, which starts with:
```
If you do not know the root cause of the problem / bug, and wish someone to help you, please
include:
```

**Comment by ppwwyyxx** [comment]
The colab example now includes tensorboard visualization. It generates valid events file.
