### ISSUE TITLE
Missing information for LVIS dataset

### ISSUE THREAD

**Issue by ggalan87** [facebookresearch/detectron2#670]
I noticed a problem in lvis api wrapper. From [lvis spec](https://www.lvisdataset.org/dataset) the expected fields for annotations are  'id', 'area', 'bbox', 'bbox_mode', 'category_id', 'segmentation', however both 'id' and 'area' are discarded in the code below

https://github.com/facebookresearch/detectron2/blob/4f68200db39ce43d58a97c42e6fc82075a843cea/detectron2/data/datasets/lvis.py#L125-L142

**Comment by ppwwyyxx** [comment]
they are discarded because they are not useful to us
