### ISSUE TITLE
Using hooks to implement early stopping

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#671]
Hi,

With respect to an issue raised earlier ([How to implement early stopping?](https://github.com/facebookresearch/detectron2/issues/509)), it is mentioned that one could use hooks to implement early stopping. How can I use them to implement early stopping based on a mAP/mAR performance metric?

**Comment by ppwwyyxx** [comment]
If would be easier for you to just use this script https://github.com/facebookresearch/detectron2/blob/555200fa414e7cd35ad35a00a3e98f0545f5832e/tools/plain_train_net.py#L175, use the test metrics returned here and break the loop.
