### ISSUE TITLE
Empty prediction instances

### ISSUE THREAD

**Issue by Nicky-V** [facebookresearch/detectron2#675]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. I trained a network for object detection by Google Colab example from my Docker container
```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("logo",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.0002
cfg.SOLVER.MAX_ITER = (3000)
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (256)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 352

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```
2. After training, I try to run recognition on test data.
3. I use the following code to output the results, but the output with the coordinates of the bbox is empty
```
from detectron2.utils.visualizer import ColorMode

for d in random.sample(dataset_dicts, 1):
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=logo_metadata,
                   scale=0.8
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    
    
    plt.figure(figsize=(10,10))
    plt.imshow(v.get_image())[:, :, ::-1]
    print(outputs)
```
`    {'instances': Instances(num_instances=0, image_height=600, image_width=800, fields= 
   [pred_boxes = Boxes(tensor([], device='cuda:0', size=(0, 4))), scores = tensor([], device='cuda:0'), 
    pred_classes = tensor([], device='cuda:0', dtype=torch.int64), ])}`

## Expected behavior:
Why are the output results returned to the model empty?

**Comment by ppwwyyxx** [comment]
likely because the model is not trained well.
As the issue template says:
> If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.
