### ISSUE TITLE
How to plot AP / AP50 / AP75 of validation in each iteration with tensorboard?

### ISSUE THREAD

**Issue by Keiku** [facebookresearch/detectron2#676]
## ❓ How to use Detectron2

Sorry for the beginner questions. I have the following questions in the PascalVOC-Detection task.

Questions:

1. How can I get the value of AP / AP50 / AP75 of validation in each iteration?
2. How can I display the AP of validation obtained by the above on tensorboard? And how to save to `metrics.json` ?

I understand that the last checkpoint can be evaluated by executing the following command.

```
python tools/train_net.py \
    --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml \
    SOLVER.IMS_PER_BATCH 2 \
    SOLVER.BASE_LR 0.0025
```

**Comment by ppwwyyxx** [comment]
If you use `train_net.py` then,
1. `TEST.EVAL_PERIOD=1`
2. they will be on tensorboard

**Comment by Keiku** [comment]
By executing the following command, the AP could be displayed at each iteration.

```
python tools/train_net.py \
    --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml \
    SOLVER.IMS_PER_BATCH 2 \
    SOLVER.BASE_LR 0.0025 \
    SOLVER.MAX_ITER 40 \
    SOLVER.CHECKPOINT_PERIOD 20 \
    TEST.EVAL_PERIOD 20
```

If the period is less than **20**, it will not be displayed well, so be careful when debugging.

**Comment by Keiku** [comment]
Additional experiments were performed.

```
python tools/train_net.py \
    --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml \
    SOLVER.IMS_PER_BATCH 2 \
    SOLVER.BASE_LR 0.0025 \
    TEST.EVAL_PERIOD 5000
```

![image](https://user-images.githubusercontent.com/199433/72235679-da6d5480-3616-11ea-83f7-5636ebb0dbe0.png)
