### ISSUE TITLE
If anyone knows how to extract the image within mask area? 

### ISSUE THREAD

**Issue by sswhqqw** [facebookresearch/detectron2#681]
## ❓ How to extract the image within mask area with detectron2?

![微信图片_20200112223538](https://user-images.githubusercontent.com/35377837/72220481-ea8c2200-358b-11ea-9fb9-c32d4fae7825.png)

I would like get 'horseface' mask area image and 'longwideshootingstarnosewhite' mask area image both of them.
Thanks a lot!!!!!!!!!!!!!!!!!

**Comment by ppwwyyxx** [comment]
Detectron2 provides you the output mask (https://detectron2.readthedocs.io/tutorials/models.html#model-output-format). What to do with the output is unrelated to detectron2.
