### ISSUE TITLE
Demo run on CPU not using all threads, why?

### ISSUE THREAD

**Issue by myozinaung** [facebookresearch/detectron2#683]
I ran the demo program on Ubuntu 18.04 (CPU only). My PC has 4 core intel CPU (8 threads with hyperthreading). But the demo program is using only 4 threads 100%. Other threads are not used. So CPU usage shows only around 50%. 
I turned off the hyperthreading in the BIOS setting (so, 4 cores/4 threads only) and tested again. The CPU usage shows 100%, but I could not see the speed jump in the demo testing. (no noticeable changes in sec/item). Why?
I would like to know how these things work.

**Comment by ppwwyyxx** [comment]
That's about how pytorch handles threads and unrelated to detectron2.

If convolution is well optimized, theoretically there shouldn't be much speed difference with regard to hyperthreading anyway.
