### ISSUE TITLE
Am I able to become a contributor of Detectron2

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#684]
## ❓ Am I able to become a contributor of Detectron2

Hi, guys,
I want to become a contributor of Detectron2,
and I am wondering if only the employee of FAIR can be a contributor of Detectron2?

Your answer will be appreciated.
Thanks!

**Comment by ppwwyyxx** [comment]
Yes.

See https://detectron2.readthedocs.io/notes/contributing.html
