### ISSUE TITLE
Will detectron2 support FCOS detector?

### ISSUE THREAD

**Issue by Anikily** [facebookresearch/detectron2#685]

**Comment by ppwwyyxx** [comment]
Currently we don't have such plans

**Comment by Keiku** [comment]
The FCOS author seems to be considering it.
https://github.com/tianzhi0549/FCOS/issues/203

**Comment by wdsd641417025** [comment]
https://github.com/aim-uofa/adet

**Comment by theotheo** [comment]
This issue looks like it could be closed.

**Comment by ganesh3** [comment]
It's under BSD-2 licences and only for academic use

**Comment by lkeab** [comment]
Our project in cvpr21 can support fcos: https://github.com/lkeab/BCNet

**Comment by ppwwyyxx** [comment]
FCOS was added: https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Detection/fcos_R_50_FPN_1x.py

**Comment by darkhan-s** [comment]
> FCOS was added: https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Detection/fcos_R_50_FPN_1x.py

Is there any example on how we can use it?

**Comment by andrealoddo** [comment]
> FCOS was added: https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Detection/fcos_R_50_FPN_1x.py

How can it be used inside detectron?

**Comment by FionaZhangJ** [comment]
> > FCOS was added: https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-Detection/fcos_R_50_FPN_1x.py
> 
> How can it be used inside detectron?

Have you could use it inside detectron2? I have the same question.

**Comment by andrealoddo** [comment]
No, unfortunately, I haven't. I managed to use it with AdelaiDet library (https://github.com/aim-uofa/AdelaiDet).

**Comment by FionaZhangJ** [comment]
Ok. Thank you.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/11/2024 23:18 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [facebookresearch/detectron2] Will detectron2 support FCOS detector? (#685) |

No, unfortunately, I haven't. I managed to use it with AdelaiDet library (https://github.com/aim-uofa/AdelaiDet).
