### ISSUE TITLE
EVALUATION COST ON BOTH CPU AND GPU

### ISSUE THREAD

**Issue by tamyxgopenx** [facebookresearch/detectron2#688]
## Issue:
Run prediction but it used both cpu and gpu
![image](https://user-images.githubusercontent.com/36707772/72251472-8a9b8700-3630-11ea-953e-d56d30a38798.png)
And use 1.2G GPU
Is this because of my code or it will always be like this?

**Comment by tamyxgopenx** [comment]
Why running this line  from detectron2.engine import DefaultPredictor the cpu loaded 2.7 GB, @ppwwyyxx  do you know the reason?

**Comment by ppwwyyxx** [comment]
Taking a few GBs of RAM seems normal to me. If you think anything is unexpected, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
