### ISSUE TITLE
How to use the Tutorials Of Use Models of DatasetMapper in one list[dict]  format image dataset?

### ISSUE THREAD

**Issue by sswhqqw** [facebookresearch/detectron2#689]
## ❓ How to use the Tutorials Of Use Models of DatasetMapper in one list[dict]  format image dataset?

Questions like:

1. How to use the Tutorials Of Use Models of DatasetMapper  for one image dataset?
2. How can I get a list[dict]  format for a image dataset as the inputs?

NOTE:

1. when I used Used Docs » Tutorials »Models. I met a problem
How it connects to data loader as inputs in Use Models

2. when I used DatasetMapper.__call__(d), (I print type of d,it is dict),why TypeError is __call__() missing 1 required positional argument: 'dataset_dict'?
thanks a lot!!!!!

![屏幕快照 2020-01-13 下午7 17 11](https://user-images.githubusercontent.com/35377837/72252820-0d294400-363b-11ea-871b-2da4e7bf1354.png)
![屏幕快照 2020-01-13 下午7 26 21](https://user-images.githubusercontent.com/35377837/72252836-16b2ac00-363b-11ea-89a2-1d93ac293d6a.JPG)
![屏幕快照 2020-01-13 下午7 27 10](https://user-images.githubusercontent.com/35377837/72252852-1f0ae700-363b-11ea-8536-8b51a2edc387.JPG)

**Comment by bamwani** [comment]
yo, did you find how to generate an input for built-in models on pretrained dataset?
