### ISSUE TITLE
Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by mgmayank18** [facebookresearch/detectron2#69]
I am using the following

## Specifications

1. Ubuntu 14.04
2. CUDA-8.0
3. Python 3.7.3
4. gcc4.9.4

I am encountering the following error when I do python setup.py build develop

error: command 'gcc' failed with exit status 1

Can someone help me install Detectron2 on my machine?

## LOG

`running build
running build_py
running build_ext
building 'detectron2._C' extension
gcc -pthread -B /home/mayankgupta/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-8.0/lib64/include -I/home/mayankgupta/anaconda3/include/python3.7m -c /usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/vision.cpp -o build/temp.linux-x86_64-3.7/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/mayankgupta/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-8.0/lib64/include -I/home/mayankgupta/anaconda3/include/python3.7m -c /usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o build/temp.linux-x86_64-3.7/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp: In function ‘at::Tensor detectron2::nms_rotated_cpu_kernel(const at::Tensor&, const at::Tensor&, float)’:
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:31:50: error: expected primary-expression before ‘>’ token
   auto suppressed = suppressed_t.data_ptr<uint8_t>();
                                                  ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:31:52: error: expected primary-expression before ‘)’ token
   auto suppressed = suppressed_t.data_ptr<uint8_t>();
                                                    ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:32:38: error: expected primary-expression before ‘>’ token
   auto keep = keep_t.data_ptr<int64_t>();
                                      ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:32:40: error: expected primary-expression before ‘)’ token
   auto keep = keep_t.data_ptr<int64_t>();
                                        ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:33:40: error: expected primary-expression before ‘>’ token
   auto order = order_t.data_ptr<int64_t>();
                                        ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:33:42: error: expected primary-expression before ‘)’ token
   auto order = order_t.data_ptr<int64_t>();
                                          ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:52:36: error: expected primary-expression before ‘>’ token
           dets[i].data_ptr<scalar_t>(), dets[j].data_ptr<scalar_t>());
                                    ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:52:38: error: expected primary-expression before ‘)’ token
           dets[i].data_ptr<scalar_t>(), dets[j].data_ptr<scalar_t>());
                                      ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:52:66: error: expected primary-expression before ‘>’ token
           dets[i].data_ptr<scalar_t>(), dets[j].data_ptr<scalar_t>());
                                                                  ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:52:68: error: expected primary-expression before ‘)’ token
           dets[i].data_ptr<scalar_t>(), dets[j].data_ptr<scalar_t>());
                                                                    ^
In file included from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated.h:3,
                 from /usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:3:
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp: In lambda function:
/home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:70:52: warning: ‘c10::ScalarType detail::scalar_type(const at::Type&)’ is deprecated (declared at /home/mayankgupta/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:46) [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(TYPE);                        \
                                                    ^
/usr0/home/mayankgupta/Detectron2/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp:67:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
   ^
error: command 'gcc' failed with exit status 1
`

**Comment by ppwwyyxx** [comment]
What's your pytorch version?

**Comment by Wangweilai1** [comment]
Ubuntu 16.04
GTX 1080Ti
CUDA-8.0
Python 3.7.3
gcc7.3
pytorch 1.3.1

when  i run python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input ./1.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

[11/22 20:18:29 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['./1.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
WARNING [11/22 20:18:29 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/demo.py", line 73, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/root1/Detection/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/root1/Detection/detectron2/detectron2/engine/defaults.py", line 149, in __init__
    self.model = build_model(self.cfg)
  File "/home/root1/Detection/detectron2/detectron2/modeling/meta_arch/build.py", line 18, in build_model
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/root1/Detection/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 37, in __init__
    pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
  File "/root/anaconda2/envs/detectron2/lib/python3.7/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/root/anaconda2/envs/detectron2/lib/python3.7/site-packages/torch/cuda/__init__.py", line 111, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError:
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

Detectron2 not work in CUDA 8.0?

**Comment by ppwwyyxx** [comment]
Your system may have cuda 8.0 but your pytorch seems to be built with cuda 10. You need an up-to-date driver for cuda 10.
If you have any other unexpected issues please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
