### ISSUE TITLE
Confused on  level_ids  and  assign_boxes_to_levels

### ISSUE THREAD

**Issue by DW9363** [facebookresearch/detectron2#690]
In  this  RegionProposal (RPN)  ->  ROIHeads (ROIPooler + box/keypoint/mask heads)  routine, 
the function **find_top_rpn_proposals**  in rpn_outputs.py  already  calculated  **level_ids** for every topk proposals.
but  in poolers.py, ROIPooler use  the function **assign_boxes_to_levels** to calculate level_ids  for those topk proposals. 
this seems unnecessary to me,  So i am kind of confused here.  anyone knows why ?

**Comment by ppwwyyxx** [comment]
Please read about modeling details in the relevant papers, such as https://arxiv.org/abs/1612.03144

**Comment by DW9363** [comment]
@ppwwyyxx   i read the paper, and i still have some questions to discuss with you. Thank you for your time.
1.  the var **level_ids** in the function  **find_top_rpn_proposals** is not returned.  what is the original purpose to calculate **level_ids** ?
2.  in the paper, the FPN + RPN Structure is like: (correct me if i am wrong)  
Fea level         AnchorSize           Proposals Size
P2                      32*32                (AnchorBox + Deltas).size()
P3                      64*64
P4                    128*128
P5                    256*256
P6                    512*512
when deltas is relatively small, then  according to **k = k0 + log2( (w*h)/ (224*244))**,  the proposals from P5 is k0, and P4 is k0 - 1, and so on.   
in this case, the  **level_ids**  and the result in **assign_boxes_to_levels** always matches.

the case they don't match is when deltas are large.   but  does this happens ?   
let's say if an anchor in P5 has a large delta, and produce a proposal in P4.  but if this happens, shouldn't the anchor in P4 produce a better proposal than the anchor in P5 ? 

3  just my shallow idea， if we don't consider speed, could we use all the features from fpn ?  not juse one level which is assigned by k = k0 + log2( (w*h)/ (224*244)).
the structure is like below:
FeaLevel      Anchors        Proposals                      ROI                            Concat or Sum     BoxHead/....
P2                 32*32                                                ROIPooler 7*7
P3                 64*64                                                ROIPooler 7*7
P4                128*128        SelectedProPosals        ROIPooler 7*7
P5                256*256                                             ROIPooler 7*7
when we have a proposal in P4, the origin ROIPooler just use the P4 Fea to extract roi feas.
but how about using several ROIPoolers to extract roi feas, and then merge all these features to predict ?   would this achieve better performance in mAP ?
Proposal size like 168*168 are kind of between P4 and P5, just one level feamap seems to lost some information to me.  Although  this all feas approach is no doubtly slower than one level.

**Comment by ppwwyyxx** [comment]
1. `level_ids` is computed because it is used in the function.
2. you're welcome to try your ideas in detectron2. However such discussions do not belong to github issues (https://github.com/facebookresearch/detectron2/issues/new/choose)
3. same as (2).
