### ISSUE TITLE
training detectron2 for hand keypoints detection, how to create keypoint_flip_map?

### ISSUE THREAD

**Issue by umarasif** [facebookresearch/detectron2#694]
## ❓ How to use Detectron2
Hi,

I wish to use detectron2 for detecting hand keypoints but do not know how to create values for `keypoint_flip_map` used in MetadataCatalog. My dataset contains 21 keypoints on a hand image which are not symmetric (like the person pose keypoints in coco). How do I determine which keypoints should be paired for the flip map? 

Thanks

**Comment by ppwwyyxx** [comment]
COCO keypoint has "nose" which is simply not paired.

**Comment by umarasif** [comment]
> 
> 
> COCO keypoint has "nose" which is simply not paired.

So, if my all 21 keypoints cannot be paired, can I leave `keypoint_flip_map` empty? I think the code does not allow empty `keypoint_flip_map`.

**Comment by ppwwyyxx** [comment]
> I think the code does not allow empty keypoint_flip_map.

I think it is allowed. Note that empty does not mean "not provided". You still need to set it to an empty list.

**Comment by umarasif** [comment]
> 
> 
> > I think the code does not allow empty keypoint_flip_map.
> 
> I think it is allowed. Note that empty does not mean "not provided". You still need to set it to an empty list.

Thank you. Yes, it allows empty `keypoint_flip_map`

**Comment by n1dhi** [comment]
Hi I am trying to create a key point detector for a shelf, where there is no symmetry. I haev set keypoint_flip_map to an empty list but I am still getting the following error
```
keypoints = keypoints[keypoint_hflip_indices, :]
IndexError: arrays used as indices must be of integer (or boolean) type
```
