### ISSUE TITLE
FBnet backbone

### ISSUE THREAD

**Issue by startupgurukul** [facebookresearch/detectron2#696]
## fbnet backbone for 🚀 like inference
Edge AI is always awesome and unlocks solutions for lot of humanitys problems

## Motivation
Considering mobile processors are offering so much power via their additional NN processing Unit, detectron2 mobile friendly models can empower building apps which can run locally and can empower internet limited users aswell

## Pitch
this has been on the roadmap, this issue is a placeholder

**Comment by startupgurukul** [comment]
Fbnet + pointrend accuracy would be interesting to observe

**Comment by youngwanLEE** [comment]
@startupgurukul 

I implemented efficient backbone networks, [_VoVNet_](https://github.com/youngwanLEE/vovnet-detectron2),  for detectron2.

**Comment by Samjith888** [comment]
> @startupgurukul
> 
> I implemented efficient backbone networks, [_VoVNet_](https://github.com/youngwanLEE/vovnet-detectron2), for detectron2.

Please maintain repo and resolve the issues which is open in ur repo

**Comment by breznak** [comment]
@youngwanLEE would you try to merge your models to Detectron2 here?

**Comment by youngwanLEE** [comment]
@breznak 

We already tried to merge our vovnet like [this](https://github.com/facebookresearch/detectron2/issues/646).

**Comment by Dorozhko-Anton** [comment]
@startupgurukul @ppwwyyxx  Would you like an implementation from scratch and then you will train it or an implementation compatible with maskrcnn_benchmark weights for fbnet ?

**Comment by startupgurukul** [comment]
Any love for this folks, supposed to ETA was around 1-2 weeks  when issue was created. 

https://github.com/facebookresearch/detectron2/issues/12#issuecomment-565566046

**Comment by startupgurukul** [comment]
Hello folks if you can kindly consider taking a look

**Comment by ppwwyyxx** [comment]
FBNet-based detectors are already open sourced in https://github.com/facebookresearch/d2go/tree/master/d2go/modeling/backbone.

Maybe we will move them into detectron2 at some point but it can already be used the same way as other models.
