### ISSUE TITLE
AttributeError: module 'detectron2.model_zoo' has no attribute 'get_checkpoint_url'

### ISSUE THREAD

**Issue by sagilehman** [facebookresearch/detectron2#699]
the script is giving the following error:

> AttributeError: module 'detectron2.model_zoo' has no attribute 'get_checkpoint_url'

for the following line:
`cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")`
my files are up to date, do you have any idea what may cause it?

**Comment by ppwwyyxx** [comment]
I think your code is not up to date.

If you still have issues, 
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
