### ISSUE TITLE
TensorMask implementation?

### ISSUE THREAD

**Issue by yonkshi** [facebookresearch/detectron2#70]
## ❓ Questions and Help

Hi, 
In the blog post you guys mentioned that a implementation of TensorMask (https://arxiv.org/pdf/1903.12174.pdf) is included in the Detectron2, I was wondering if there are any tentative timeline in releasing this implementation?

Best
Yonk

**Comment by ppwwyyxx** [comment]
It will be released in 1~2 weeks.

**Comment by jiangzhengkai** [comment]
Really looking forward to TensorMask code

**Comment by jinfagang** [comment]
@ppwwyyxx  2 weeks pasted, how's everything going?

**Comment by endernewton** [comment]
Thanks for the interest! The code is ready to release but under a final round of review -- you will see it very soon!

**Comment by jiangzhengkai** [comment]
@endernewton  Any new?

**Comment by SkeletonOne** [comment]
@endernewton Anything new?

**Comment by mcamila777** [comment]
Is it going to be released soon? 
Thanks!

**Comment by yonkshi** [comment]
I'm starting to think that getting through fb code review is a bigger challenge than ICCV peer review

**Comment by endernewton** [comment]
Please check out: https://github.com/facebookresearch/detectron2/tree/master/projects/TensorMask
