### ISSUE TITLE
Tutorial on how to train panoptic segmention on coco dataset?

### ISSUE THREAD

**Issue by dragen1860** [facebookresearch/detectron2#700]
HI all:
  Could anone give some tutorials on how to train and evaluate on coco panoptic dataset using existing configs?
  I feel confused on how to prepare the coco panoptic dataset and how to write train scripts. Very few documents on how to train coco panoptic experiments. Help me. Thank you.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#training--evaluation-in-command-line
