### ISSUE TITLE
Total training time is not accurate

### ISSUE THREAD

**Issue by ScXfjiang** [facebookresearch/detectron2#701]
## Total training time is not accurate

Thank you for great jobs, it is really amazing for Detectron2!!!

I want to calculate total training time and training time per iteration. I found Total training time in log is different from time record by my iPhone (Total training time in log is 276s and time record by my iPhone is 310s for some task training 1000 iters).

Tracing the code to IterationTimer hook:

> Under the convention that :meth:`before_step` of all hooks should only
    take negligible amount of time, the :class:`IterationTimer` hook should be
    placed at the beginning of the list of hooks to obtain accurate timing.

However, putting IterationTimer in the first place of list results in both running IterationTimer::before_step and IterationTimer::after_step before other hook, thus other hooks' after_step operations are not taken into account by IterationTimer. Consequently, you get a shorter total training time and training time per iteration than real time.

My proposal is running after_step in reverse order:
```python
class TrainerBase:
    ....
    def before_step(self):
        for h in self._hooks:
            h.before_step()

    def after_step(self):
        # for h in self._hooks:
        for h in self._hooks[::-1]:
            h.after_step()
        # this guarantees, that in each hook's after_step, storage.iter == trainer.iter
        self.storage.step()
    ....
```

Thank you for response.

**Comment by ppwwyyxx** [comment]
> thus other hooks' after_step operations are not taken into account by IterationTimer.

This is not true because the total training time is computed in the `after_train` method, not `after_step.

The reason of the timing gap you saw may be because we did not include the warmup time in the total training time, because they don't contribute meaningfully to the speed computation. You're welcome to try and fix this in `IterationTimer` if you like.

**Comment by ScXfjiang** [comment]
Yes, the Total training time in log is correct. Let me explain more precisely.

There are two lines about time in log:
> [01/16 03:46:45 d2.engine.hooks]: Overall training speed: 100 iterations in 0:00:33 (0.3330 s / it)
[01/16 03:46:45 d2.engine.hooks]: Total training time: 0:00:56 (0:00:23 on hooks)

The second line's Total training time is correct which is calculated by two timestamps in IterationTimer's before_train and after_train.

I still have other two questions:
1. Why exclude hooks' time when calculating time per iteration (the first line's results: 0:00:33 (0.3330 s / it))? I think hooks are also part of training which should be taken into account when calculating time per iteration.
2. Even though exclude hooks' time, it is not record correctly. The hooks' time is calculated by:
```python
hook_time = total_time - total_time_minus_hooks
```
The total_time is correct which is the first line result in log. However, the total_time_minus_hooks is not accurate which is record by IterationTimer::_total_timer.
```python
class IterationTimer(HookBase):
    ....
    def before_step(self):
        self._step_timer.reset()
        self._total_timer.resume()

    def after_step(self):
        # +1 because we're in after_step
        iter_done = self.trainer.iter - self.trainer.start_iter + 1
        if iter_done >= self._warmup_iter:
            sec = self._step_timer.seconds()
            self.trainer.storage.put_scalars(time=sec)
        else:
            self._start_time = time.perf_counter()
            self._total_timer.reset()

        self._total_timer.pause()
    ....
```
As we know, the IterationTimer is placed in the first of hooks list. This timer is resumed in before_step and paused in after_step, which means the rest hooks's after_step time is not taken into account.

The same problem also occurs in _step_timer and results in shorter time than real time.

Is it done on purpose or the hooks' order should be adjusted more carefully?

**Comment by ppwwyyxx** [comment]
1. That's the time we're interested in, mainly because hooks don't affect training.

2. 
> This timer is resumed in before_step and paused in after_step, which means the rest hooks's after_step time is not taken into account.

You're correct and it's working as expected. 
They are not taken into account so we can compute the time they took.

**Comment by ppwwyyxx** [comment]
Closing as there is nothing unexpected
