### ISSUE TITLE
Multiple instance detected on a single object 

### ISSUE THREAD

**Issue by shivSD** [facebookresearch/detectron2#704]
@ppwwyyxx  
Trained detectron2 with custom dataset with one class (background and object-1) with 5000 training images for 4-5 hours, during inference  multiple instances detected (small segments) on single object. How to overcome this issue so that instead of multiple instance (segments) it detects one single mask/color.

single gpu training
here is the command line for training:
python3 tools/train_net.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x_object1.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025

**Comment by ppwwyyxx** [comment]
As mentioned in the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md), we do not give suggestions on how to train a new model
