### ISSUE TITLE
Why not use `python -m torch.distributed.launch --nproc_per_node` to launch the trainer

### ISSUE THREAD

**Issue by lbin** [facebookresearch/detectron2#706]
Maybe it's easier to let apex in.

**Comment by ppwwyyxx** [comment]
If you have any suggestions feel free to speak them out. Otherwise I don't see reasons why we should use it.

**Comment by mckunkel** [comment]
Because allowing for APEX and tje ability to use 
`python -m torch.distributed.launch --nproc_per_node` to launch the trainer
would greatly increase the usability of detectron2 in use cases outside the current binding framework.
