### ISSUE TITLE
Can't import detectron2 inside provided container

### ISSUE THREAD

**Issue by ndalton12** [facebookresearch/detectron2#711]
Inside detectron2/docker, I ran

- docker build ./
- docker run -it <name of image> bash

Inside the image, I ran

- python3
- import detectron2

which returns a ModuleNotFoundError. Any advice?

**Comment by ppwwyyxx** [comment]
The usage is given in https://github.com/facebookresearch/detectron2/tree/master/docker.

If you met any unexpected behaviors, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
