### ISSUE TITLE
Image without Objects Removed before Training

### ISSUE THREAD

**Issue by danielfather7** [facebookresearch/detectron2#712]
As title, why are those images without mask labels removed before training when I tried to train a maskrcnn? Isn’t it good to still view them as whole background and help training?

If there is no specific reason, how can I include them in training?

Thanks!

**Comment by ppwwyyxx** [comment]
Duplicate of #80 
Added in https://github.com/facebookresearch/detectron2/commit/62522b6a9dc3d30cfa7b639e49997a0ee0d8dca0
