### ISSUE TITLE
installing Detectron2 on Docker image

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/detectron2#718]
Thank you for the Dockerfile, @ppwwyyxx, this was a big help. That Dockerfile is for building an image with a fresh install of Detectron via `git clone` and `pip install`.

But what if we have already installed Detectron2 locally and have a trained model ready to deploy via Docker container?  It would not make sense to redownload the repo, as presumably it would likely be more recent version than the one used earlier to train the model, and therefore has some changes to the Detectron2 library that could be not backwards-compatible with the older version of Detectron2.

Therefore, we should not `git pull` a fresh install, but rather `pip install` our local (not most recent) version of the Detectron2 library to use in the Docker image.

Say we have our detectron2 stored under /repos/detectron2/
and have previously set our docker `WORKDIR working_dir`

To copy and install detectron2 from host machine into the Docker image, which command should be used?

```
RUN cd /working_dir/repos/detectron2/ && \
    pip install -e .
```
or
```
RUN cd /working_dir/repos/detectron2/ && \
    python setup.py build develop
```

Thanks

**Comment by ppwwyyxx** [comment]
We in general do not make changes that will let an old model produce different results.

About your question: both command are OK.

**Comment by cpoptic** [comment]
Ok thank you!
