### ISSUE TITLE
Multi-gpu in notebook

### ISSUE THREAD

**Issue by asparamancer** [facebookresearch/detectron2#719]
How do I make the notebook use multi-gpu, e.g. specifying the --num-gpus 8 like for the cli version? 

I've tried standard CUDA_VISIBLE_DEVICES, exporting num_gpus in the notebook but always seems to use one. config file is set to one of the normal ones which use 8 too.

**Comment by ppwwyyxx** [comment]
Run `train_net.py` with `--num-gpus==8` will use multi gpus.
You can look at the code of train_net to see how it is implemented if you want to rewrite it in a notebook.

**Comment by asparamancer** [comment]
Yes, I know that's how you do it in train_net - I said that in the first line of my question. I've tried looking at that and getting it to run in the notebook but it's not working, do you know how?

**Comment by ppwwyyxx** [comment]
If you copy everything in train_net.py into the notebook (and if your machine does have multiple gpus) then it should work.

If it doesn't, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by asparamancer** [comment]
I've done that, and it still runs out of memory -  nvidia-smi shows utilisation on only 1 gpu. 
8 gpus are detected:
------------------------  -------------------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                     1.17.4
detectron2                0.1 @/home/jupyter/detectron2/detectron2
detectron2 compiler       GCC 6.3
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_70
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @/opt/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3,4,5,6,7       Tesla V100-SXM2-16GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.2
torchvision               0.4.2 @/opt/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  -------------------------------------------------------------
Command Line Args: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)

how do I get the notebook to take the arg num_gpus=8?

**Comment by ppwwyyxx** [comment]
You can add `args.num_gpus=8` to the code.

**Comment by asparamancer** [comment]
Yeah I tried that already but `SyntaxError: keyword can't be an expression`

**Comment by ppwwyyxx** [comment]
Then you probably added it to the wrong place. Please be clear what you've tried.

You can add it to:
```python
    args = default_argument_parser().parse_args()
    args.num_gpus=8
```
