### ISSUE TITLE
Support for mixed precision training 

### ISSUE THREAD

**Issue by sadanand-singh** [facebookresearch/detectron2#72]
## ❓

Is there any plan to support mixed precision training soon? It was already being supported in the maskrcnn-benchmark code.

**Comment by lbin** [comment]
@ppwwyyxx  I would like to send a PR for apex training. https://github.com/lbin/detectron2/blob/apex/projects/ApexTrainer/README.md

**Comment by blueardour** [comment]
@lbin Hi, Thanks for the great contribution.

I recently also focused in the FP16 training. After checking your code, it seemed that only the amp.initialize and amp.scale_loss APIs are employed. With my experience in image classification scenario, the DistributedDataParallel should also be replaced by from apex.parallel import DistributedDataParallel as DDP. However, I noticed you comment out line 75 in apex_trainer.py.  Is there any reason why not using the amp DDP?

BTW, I'm also confused by the data in page https://github.com/lbin/detectron2/blob/apex/projects/ApexTrainer/README.md   
The speed and memory cost are higher for the ApexTrainer case, which I expected to be lower than the FP32 version.

Appreciated if you can give some clarification.   Thanks

**Comment by lbin** [comment]
@blueardour I used batchsize 32 not 16, so the speed and memory are higher in my case.

for ddp:
https://github.com/NVIDIA/apex/tree/master/examples/imagenet#distributed-training

**Comment by blueardour** [comment]
@lbin Thanks for the tips.

**Comment by meetshah1995** [comment]
Given that Pytorch natively supports mixed precision training, is there plan to integrate that?

**Comment by indigoviolet** [comment]
At least for RetinaNet, it was quite straightforward to use mixed precision training. You can see how I did it: https://github.com/indigoviolet/detectron2/commit/d175f4a823cfdcce417e5ea38acbabc5215b9294

**Comment by lbin** [comment]
@indigoviolet I think we should move to pytorch 1.6

**Comment by ppwwyyxx** [comment]
We plan to add support this year. https://github.com/facebookresearch/detectron2/pull/925 is a good example of how to do it with apex.

**Comment by alexge233** [comment]
@ppwwyyxx Hi, sorry to ask again, can I force only `fp16` for models and training, or is this still work in progress?
