### ISSUE TITLE
why don't have output video when i run demo.py

### ISSUE THREAD

**Issue by yunchangxiaoguan** [facebookresearch/detectron2#725]
I used the keypoint model.when my input is picture it has result produce.But when my input is video it has no result file.And the code run has no bug

(detectron2) [xx@aboluo01 demo]$ python demo.py --config-file ../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml --video-input ../datasets/input/test.mp4 --output /home/guanxiao/project/detectron2/datasets/outvideo --opts MODEL.WEIGHTS '../models/keypoint/model_final_a6e10b.pkl'
[01/20 16:54:06 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', '../models/keypoint/model_final_a6e10b.pkl'], output='/home/guanxiao/project/detectron2/datasets/outvideo', video_input='../datasets/input/test.mp4', webcam=False)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 332/332 [02:26<00:00,  2.27it/s]

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by yunchangxiaoguan** [comment]
> Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

我加上去了，大佬你知道这是怎么回事么，输出格式也我改过
  if args.output:
            if os.path.isdir(args.output):
                output_fname = os.path.join(args.output, basename)
                output_fname = os.path.splitext(output_fname)[0] + ".avi"
            else:
                output_fname = args.output
            assert not os.path.isfile(output_fname), output_fname
            output_file = cv2.VideoWriter(
                filename=output_fname,
                # some installation of opencv may not support x264 (due to its license),
                # you can try other format (e.g. MPEG)
                #fourcc=cv2.VideoWriter_fourcc(*"x264"),
                fourcc=cv2.VideoWriter_fourcc('X', 'V', 'I', 'D')

**Comment by ppwwyyxx** [comment]
If you expect output to be written to a directory called `datasets/outvideo` you need to create the directory first.

**Comment by yunchangxiaoguan** [comment]
thanks,I add --output /home/guanxiao/project/detectron2/datasets/outvideo.avi  then it can be done
