### ISSUE TITLE
How to add dropout layers during inference?

### ISSUE THREAD

**Issue by RovelMan** [facebookresearch/detectron2#727]
## ❓ How to add dropout layers during inference?

Hi,

My goal is to train a model for instance segmentation with Mask R-CNN using Detectron2.

I just need a quick guide on where I have to look and where I can implement a simple Dropout(0.5) layer which will be used during "inference". Is this easy to do?

I want to do this in order to: Calculate the mask uncertainty of each prediction in an image by doing multiple inferences on the same image using dropout.

Thank you so much!
Let me know if more info is needed.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html

**Comment by RovelMan** [comment]
Thank you! I totally forgot about looking into the docs when writing this. My bad!
