### ISSUE TITLE
Adding an extra regression head to faster-rcnn.

### ISSUE THREAD

**Issue by DecentMakeover** [facebookresearch/detectron2#728]
Hello 

Thanks for sharing this work with the community.

Along with the classification head and a bbox regression head, i wanted to add another score classification head.What steps can i follow to achieve this. Thanks.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/write-models.html

The densepose project adds a new densepose head and can be used as an example.
