### ISSUE TITLE
How can I only format Keypoint result and don't format fastrcnn reuslt on picture

### ISSUE THREAD

**Issue by yunchangxiaoguan** [facebookresearch/detectron2#732]
As the title.When i run demo.py with keypoint model I don't want the boundingbox drawn in result.How can i do this

**Comment by ppwwyyxx** [comment]
You can remove bounding boxes from results before giving the results to visualization.

https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

**Comment by yunchangxiaoguan** [comment]
> You can remove bounding boxes from results before giving the results to visualization.
> 
> https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.Instances

thanks，but i can't find the place where i need add this code to remove b-box.And I have read the document but I can't understand how to use detectron2.structures.Instances.Can you tell me how to do this? thanks a lot!

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/0bf1ae2cd1b87ae9e61732776ccd816bc5a16ae7/demo/predictor.py#L63-L64

**Comment by yunchangxiaoguan** [comment]
> https://github.com/facebookresearch/detectron2/blob/0bf1ae2cd1b87ae9e61732776ccd816bc5a16ae7/demo/predictor.py#L63-L64

大哥，这到底是什么意思啊，我注释了上面那两行就报错了，还是说我要改什么内容？
Traceback (most recent call last):
  File "demo.py", line 138, in
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/home/guanxiao/anaconda3/envs/detectron2/lib/python3.7/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/home/guanxiao/project/detectron2/demo/predictor.py", line 130, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/guanxiao/project/detectron2/demo/predictor.py", line 106, in process_predictions
    vis_frame = cv2.cvtColor(vis_frame.get_image(), cv2.COLOR_RGB2BGR)
UnboundLocalError: local variable 'vis_frame' referenced before assignment

要怎么改这一段啊？我找了半天，从predictions一直找到cfg，我怎么选择不进行maskrcnn，只进行keypoint呢，大神你能说的再直白点么
