### ISSUE TITLE
Feature Proposal: Support balanced sampling for multiple train datasets of differing lengths

### ISSUE THREAD

**Issue by lasnik** [facebookresearch/detectron2#734]
## 🚀 Feature
Add option to match sampling frequency of multiple train datasets.

## Motivation
Currently the behaviour in data.build.get_detection_dataset_dicts is such that multiple datasets are simply chained. When these datasets differ in length significantly this leads to oversampling of longer datasets. During training there are scenarios in which it can be preferable to ensure balanced sampling between datasets, for example in the presence of domain shift.

## Pitch
One solution could be to make this logic configurable. To ensure balanced sampling, a `DATASET.EQUAL_FREQUENCY` flag could be set in the config. When `True`, instead of simply calling `itertools.chain.from_iterable` on the list of datasets (line 235), a function could be called that returns an iterable delivering samples from all datasets in alternating fashion. To retain previous behavior `DATASET.EQUAL_FREQUENCY` should default to `False`.

Rough outline:
```python
def match_detection_dataset_sampling_frequency(dataset_dicts):
    """
    Makes sure sampling between multiple datasets is balanced by returning samples from each
    dataset in alternating fashion, repeating shorter datasets to match the length of the longest.

    Args:
        dataset_dicts (list[list[dict]]): The registered datasets. First level of nested lists
            corresponds to the different datasets, while the second level corresponds to the
            examples in a datset.

    Returns:
        dataset_dicts (list[dict]): A list containing alternating dicts from all datasets.
    """
    dataset_lengths = list(map(len, dataset_dicts))

    if not len(set(dataset_lengths)) > 1:
        logger = logging.getLogger(__name__)
        if len(dataset_lengths) == 1:
            logger.warning(
                "Sampling frequency matching is enabled but only a single dataset was supplied."
            )
        else:
            logger.warning(
                "All datasets are already the same length. No frequency matching is applied."
            )
        return list(itertools.chain.from_iterable(dataset_dicts))

    longest_dataset_idx = dataset_lengths.index(max(dataset_lengths))
    longest_dataset = dataset_dicts.pop(longest_dataset_idx)
    # Create repeating iterables of shorter datasets
    shorter_datasets = map(itertools.cycle, dataset_dicts)
    return list(itertools.chain.from_iterable(zip(longest_dataset, *shorter_datasets)))
```

**Comment by lasnik** [comment]
P.s.: If this is a welcome feature I would be happy to open a PR.

**Comment by lasnik** [comment]
Oh and I would of course be happy to open a PR of this is a welcome feature.

**Comment by lasnik** [comment]
Oh and I would of course be happy to open a PR if this is a welcome feature.

**Comment by ppwwyyxx** [comment]
Your implementation is not ideal because for the smaller dataset the returned list[dict] will include some samples more times than others, and as a result won't give every sample in one dataset equal weights.

It looks like users can achieve this feature by just writing a custom data loader and I'm not sure if it's needed by many users. Following the principles in https://detectron2.readthedocs.io/notes/contributing.html we probably won't add this feature at this point.

**Comment by lasnik** [comment]
Implementing this with a custom data loader of course works but results in a lot of duplicate code to just change one aspect of the logic. However if this is not a feature many users would need it of course makes no sense to include it. Thanks for your feedback.
