### ISSUE TITLE
Register Coco Instances `Annotation file format {} not supported`

### ISSUE THREAD

**Issue by ysefwakil** [facebookresearch/detectron2#735]
Hi there,
I am having trouble registering my json file using the register_coco_instances method as suggested [here](https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/datasets.md) for custom datasets. I am currently getting this error when running my code: 

> Traceback (most recent call last):
  File "testingformat.py", line 36, in <module>
    DatasetCatalog.get("fruit_datatset")
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/catalog.py", line 62, in get
    return f()
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/datasets/register_coco.py", line 32, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/datasets/coco.py", line 59, in load_coco_json
    coco_api = COCO(json_file)
  File "/home/appuser/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 85, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
AssertionError: annotation file format <class 'list'> not supported

currently this is my code that I am running: 
`import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import cv2
import random

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
import os
import numpy as np
import json
from detectron2.structures import BoxMode
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.utils.visualizer import ColorMode
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

from detectron2.data.datasets import register_coco_instances

register_coco_instances("fruit_datatset", {}, "annotationsx.json", "testingimage/")

for d in ["train", "test"]:
    MetadataCatalog.get("fruit_" + d).set(thing_classes=["fruit"])
fruit_metadata = MetadataCatalog.get("fruit_train")

DatasetCatalog.get("fruit_datatset")`

---

My JSON file has been converted using the code in this [page](https://www.immersivelimit.com/create-coco-annotations-from-scratch)

Thanks!

**Comment by ppwwyyxx** [comment]
Your dataset is not in COCO format and that page is just wrong.

**Comment by igygi** [comment]
I've been following the immersive limit site for quite some time now and the custom datasets I have been generating worked fine. I suggest you double check how you created your dataset and that you followed the proper structure (annotations should be a dict). Then try again.

**Comment by acl21** [comment]
> I've been following the immersive limit site for quite some time now and the custom datasets I have been generating worked fine. I suggest you double check how you created your dataset and that you followed the proper structure (annotations should be a dict). Then try again.

This [page](https://www.immersivelimit.com/create-coco-annotations-from-scratch) is correct but incomplete, only shows how to create the annotations. You may want to check out [pycococreator](https://github.com/waspinator/pycococreator) and this [post](https://patrickwasp.com/create-your-own-coco-style-dataset/) for full (definitely better) solution.
