### ISSUE TITLE
ROIAlign error

### ISSUE THREAD

**Issue by animareversed** [facebookresearch/detectron2#740]
Hi,
When I run detection training I get this error:

## Error
RuntimeError: CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x2b718c608813 in .local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: detectron2::ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0x9e4 (0x2b71965bfcd5 in detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #2: detectron2::ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0x99 (0x2b7196554019 in detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x52674 (0x2b7196565674 in detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x4cfa5 (0x2b719655ffa5 in detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
< omitting python frames >
frame #10: THPFunction_apply(_object*, _object*) + 0x936 (0x2b7143e6e7e6 in .local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

I did not change anything in the code, maybe it is related to multi gpus processing? Because when I run the same code with a single gpu (in another computer) it works.

## Environment:

sys.platform              linux
Python                    3.7.2 (default, Aug 12 2019, 11:09:58) [GCC 8.2.0]
numpy                     1.16.2
detectron2                0.1 @detectron2/detectron2
detectron2 compiler       GCC 8.2
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_60
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @.local/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla P100-PCIE-16GB
CUDA_HOME                 /share/apps/software/Compiler/GCC/8.2.0-2.31.1/CUDA/10.1.105
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
Pillow                    6.2.2
torchvision               0.4.2 @.local/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.1
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
If your environment information is obtained in the same shell where the error happens, then it's an uncommon issue I've not seen. I can take a further look if there is a reproducible environment (e.g. docker).

**Comment by animareversed** [comment]
I run the code on a cluster where each node has two gpus (and I use just one node). The installation of detectron2 was performed directly on the cluster, so I don't think it's related to the installation.

**Comment by ppwwyyxx** [comment]
That does not answer my doubt on whether "your environment information is obtained in the same shell where the error happens". If, for example, they are executed on different machines, then the environment information is obviously not useful

**Comment by animareversed** [comment]
Ok, sorry. I just run the command where I run the code, here the output:

sys.platform              linux
Python                    3.7.2 (default, Aug 12 2019, 11:09:58) [GCC 8.2.0]
numpy                     1.16.2
detectron2                0.1 @detectron2/detectron2
detectron2 compiler       GCC 8.2
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_60
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @.local/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla V100-PCIE-16GB
CUDA_HOME                 /share/apps/software/Compiler/GCC/8.2.0-2.31.1/CUDA/10.1.105
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
Pillow                    6.2.2
torchvision               0.4.2 @.local/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.1
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
The solution to your issue is in https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md:

> Detectron2 or PyTorch/torchvision is not built with the correct compute compatibility for the GPU model.
The compute compatibility for PyTorch is available in python -m detectron2.utils.collect_env.
The compute compatibility of detectron2/torchvision defaults to match the GPU found on the machine during building, and can be controlled by TORCH_CUDA_ARCH_LIST environment variable during building.
Visit developer.nvidia.com/cuda-gpus to find out the correct compute compatibility for your device.
