### ISSUE TITLE
one object detected as multiple objects

### ISSUE THREAD

**Issue by M-Younus** [facebookresearch/detectron2#743]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
 **None**

2. what exact command you run:
`python demo/demo.py --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml --video-input demo/multiple-men-exercise.mp4 --output demo/multiple-men-exercise-det-voc-output.mp4 --opts MODEL.WEIGHTS demo/model_final_b1acc2.pkl`

3. what you observed (including the full logs):
 one object detected as multiple objects.(Image attached)
![Screenshot from 2020-01-23 17-01-30](https://user-images.githubusercontent.com/13608139/72983997-714ec380-3e04-11ea-9794-42f8fa714657.png)

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
Simple run the command,by downloading the models from model zoo.
## Expected behavior:
It should not detect one chair as two chairs

## Environment:

Please paste the output of `python -m detectron2.utils.collect_env`.
If detectron2 hasn't been successfully installed, use `python detectron2/utils/collect_env.py`.

[log-for-issue.txt](https://github.com/facebookresearch/detectron2/files/4103023/log-for-issue.txt)

**Comment by ppwwyyxx** [comment]
No model is perfect. This is not an unexpected issue.
