### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Auth0rM0rgan** [facebookresearch/detectron2#745]
Hello, I have some questions about instances segmentation with detectron2:

1. Is it possible to get only the masks without the captions and the accuracies in demo.py for instances segmentation?
2. what is the maximum FPS I can get with detectron2/instances segmentation? Is it possible to achieve fps between 25 and 30?
3. Is it possible to train the model with a bigger image_size like 1024x1024 and what was the image_size you trained the models?

Thanks!

**Comment by ppwwyyxx** [comment]
1. Detectron2 models give you raw outputs and you can do whatever you want with them. demo.py is just an example.
2. You can implement smaller models though we have not released them yet. 
3. Yes. The config for a model is in its config file.

**Comment by Auth0rM0rgan** [comment]
Hey @ppwwyyxx, Thanks for the quick response!

Could you provide more details about my first question? How am I going to do that?
I need to do instances segmentation for real-time. I tried most of the model and the maximum fps I can achieve is 9 FPS. Any suggestion? 

Thanks in advance!

**Comment by ppwwyyxx** [comment]
The outputs of a detectron2 model (and how to use them) are given in https://detectron2.readthedocs.io/tutorials/models.html.
demo.py is an example and you can look at how a model is used there.
