### ISSUE TITLE
Max number of iterations

### ISSUE THREAD

**Issue by rds-itga** [facebookresearch/detectron2#746]
Hi everybody,

I wonder if I have to consider the number of ROIs or the number of images to set the number of max iterations.
Assuming I have 1000 images with two ROIs on each image, so I have 2000 ROIs in total.
With a batch size of 2, 1 epoch will be 500 iterations or 1000 iterations?
I ask this because in this case the log output say:

> [12/06 09:09:12] d2.data.build INFO: Removed 0 images with no usable annotations. 2000 images left.

whereas I have only 1000 different images (but 2000 ROIs)

Thank you for your help

**Comment by ppwwyyxx** [comment]
> [12/06 09:09:12] d2.data.build INFO: Removed 0 images with no usable annotations. 2000 images left.
whereas I have only 1000 different images (but 2000 ROIs)

Then you probably used a wrong dataset format. The size of dataset must be the number of images, not instances.
Please see https://detectron2.readthedocs.io/tutorials/datasets.html.
