### ISSUE TITLE
Caffe2 C++ deployment input format 

### ISSUE THREAD

**Issue by r2dliu** [facebookresearch/detectron2#747]
I have a detectron2 model that most definitely works in python, converted into caffe2 format, and I'm attempting to run it in C++, testing on images that I know come out with detections in python land.

score_nms, class_nms, and bbox_nms blobs are all empty. I printed out some of the intermediate layers, like softmax, and confirmed that the network is actually running and calculating values. However, the softmax layer seems to indicate that it isn't detecting anything and only finding background. 

I've read through https://detectron2.readthedocs.io/tutorials/deployment.html#inputs-outputs, and I think this might simply be an issue with how I'm loading my images into the network. I have them in BGR format as an array of floats, 512x512 image, but I'm not sure if I should be preprocessing them in some way before loading them into the data blob. I've tried normalizing the BGR pixel values (/255), subtracting by mean pixel values from imagenet, [103.53, 116.28, 123.675], trying RGB format, etc. but not getting any good results.  

It feels like it's just missing some preprocessing step. Any suggestions? Suggested size of images? the network appears to only accept square images with width/height of powers of 2.

**Comment by ppwwyyxx** [comment]
As the document says: 
> Due to different inputs & outputs formats, the Caffe2Model.__call__ method includes pre/post-processing code in order to match the formats of original detectron2 models. They can serve as a reference for pre/post-processing in actual deployment.

You can use it to verify your model and reimplement the logic in C++.

**Comment by ppwwyyxx** [comment]
If you follow `Caffe2Model.__call__`, you'll find that the input preprocessing before entering the caffe2 model is at https://github.com/facebookresearch/detectron2/blob/85cfd95b033a79e3c0601978ebf014782fb25bc2/detectron2/export/caffe2_inference.py#L100. So:
1. no need to subtract mean
2. no need for size to be power of 2. But need to be multiple of 32 for most models.

**Comment by haoyankai** [comment]
@r2dliu I have this same issue,could you share the way how you solved this?

**Comment by ppwwyyxx** [comment]
An example using the caffe2 model in C++ is provided in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python.
