### ISSUE TITLE
Should I share a trained/fine tuned model on my own dataset with a cc-by-sa compatible license, when I use the model weights from the zoo?

### ISSUE THREAD

**Issue by jpizarrom** [facebookresearch/detectron2#748]
The models weights in the model zoo are licensed under cc-by-sa [1].

If I train a model with my own dataset and I use a model weights from the model zoo. Do I need to use a cc-by-sa compatible license to share my model?

[1] https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#license

**Comment by ppwwyyxx** [comment]
That seems true according to the license: https://creativecommons.org/licenses/by-sa/3.0/

**Comment by jpizarrom** [comment]
The models weights in the model zoo are licensed under cc-by-sa [1].

If I train a model with my own dataset and I use a model weights from the model zoo, and  I provide a rest service with that model(not sharing the model, only using it). Do I need to use a cc-by-sa compatible license and do I need share my model?


Do I need to use a cc-by-sa compatible license to share my model?
