### ISSUE TITLE
Expected dir structure for the Pascal VOC train and test

### ISSUE THREAD

**Issue by gunshi** [facebookresearch/detectron2#749]
## ❓ How to use Detectron2
Hi,
The documentation says that the directory structure for Pascal VOC needs to be :

```
VOC20{07,12}/
  Annotations/
  ImageSets/
  JPEGImages/
```

However it is unclear about whether we should merge the trainval and the test folders for pascal voc 2007 since they have the exact same directory structure but possibly clashing files, and the config file faster_rcnn_R_50_C4.yaml specifies that it will use both the trainval and test splits from VOC expecting a folder by the name of VOC2007 for both.

Upon running
`python tools/train_net.py --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025`
 I get:
`FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOC2007/ImageSets/Main/test.txt'`

since I have the trainval folders of both pascal voc 2012 and 2007 named as VOC2007 and VOC2012
in my datasets folder, but not the test. I'm unsure about whether i should try to merge in the test folder for VOC2007 into the train one because that might mess up the naming of the files.
How can I go about training on the VOC data in this case?
Thanks for your help,
Gunshi

**Comment by gunshi** [comment]
My workaround for now would be to change the paths here:
https://github.com/facebookresearch/detectron2/blob/afaf2e44c0c03ed22e2590cd02dc538e48d05f56/detectron2/data/datasets/builtin.py#L195

to incorporate '_train' and 'test' in the names.
but would be interested to know if there is an official/recommended solution.
Thanks

**Comment by ppwwyyxx** [comment]
They are expected to be in one directory.
