### ISSUE TITLE
how you calculate inference time

### ISSUE THREAD

**Issue by M-Younus** [facebookresearch/detectron2#750]
Please share machine configuration on which you calculated `inference time` showed in `model zoo` tables.I am using nvidia `GeForce GTX 1050 ` and for detection using `pascal-voc` I only got 2+ FPS.

**Comment by ppwwyyxx** [comment]
V100.

Also note this from model zoo:
>Inference speed is measured by tools/train_net.py --eval-only, or inference_on_dataset(), with batch size 1 in detectron2 directly. Measuring it with your own code will likely introduce other overhead.
