### ISSUE TITLE
Training of Tensormask does not work

### ISSUE THREAD

**Issue by joppichristian** [facebookresearch/detectron2#756]
Training loop calls a not yet implemented method "run_step(self)" of TrainerBase class.

**Comment by ppwwyyxx** [comment]
That is not true.

**Comment by joppichristian** [comment]
SimpleTrainer has not train method, so super().train(self.start_iter, self.max_iter) called the superclass method (TrainerBase). I talk about Tensormask! 

![image](https://user-images.githubusercontent.com/8223905/73167543-4a400c80-40f8-11ea-84e4-064054e5161d.png)

**Comment by ppwwyyxx** [comment]
You appear to have misunderstanding of how Python works.

I believe the issue you describe does not exist. If you found anything not working, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
