### ISSUE TITLE
Rotated Box Detector Error. CUDA error: invalid configuration argument (box_iou_rotated_cuda at detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu:95)

### ISSUE THREAD

**Issue by ssaru** [facebookresearch/detectron2#757]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote

My cfg setting
```
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"))
cfg.MODEL.PROPOSAL_GENERATOR.NAME = "RRPN"
cfg.MODEL.ANCHOR_GENERATOR.NAME = "RotatedAnchorGenerator"
cfg.MODEL.ANCHOR_GENERATOR.ANGLES = [[0, 45, 90, 135, 180]]
cfg.MODEL.ROI_HEADS.NAME = "RROIHeads"
cfg.MODEL.ROI_BOX_HEAD.POOLER_TYPE = "ROIAlignRotated"
cfg.SOLVER.IMS_PER_BATCH = 1
```
2. what exact command you run:

use default Trainer class
```
trainer = Trainer(cfg)
trainer.resume_or_load(resume=True)
trainer.train()
```

3. what you observed (including the full logs):

```
Traceback (most recent call last):
  File "model/rrbox_detector.py", line 367, in <module>
    trainer.train()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 125, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rrpn.py", line 53, in forward
    losses = outputs.losses()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn_outputs.py", line 323, in losses
    gt_objectness_logits, gt_anchor_deltas = self._get_ground_truth()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rrpn_outputs.py", line 218, in _get_ground_truth
    match_quality_matrix = pairwise_iou_rotated(gt_boxes_i, anchors_i)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/structures/rotated_boxes.py", line 503, in pairwise_iou
    return pairwise_iou_rotated(boxes1.tensor, boxes2.tensor)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/detectron2/layers/rotated_boxes.py", line 24, in pairwise_iou_rotated
    return _C.box_iou_rotated(boxes1, boxes2)
RuntimeError: CUDA error: invalid configuration argument (box_iou_rotated_cuda at /home/ubuntu/Documents/dev/DeepBaksuVision/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu:95)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fd27ca9c813 in /home/ubuntu/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: detectron2::box_iou_rotated_cuda(at::Tensor const&, at::Tensor const&) + 0x5b6 (0x7fd2722273b0 in /home/ubuntu/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: detectron2::box_iou_rotated(at::Tensor const&, at::Tensor const&) + 0x65 (0x7fd2721ce435 in /home/ubuntu/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x338f4 (0x7fd2721d28f4 in /home/ubuntu/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x3ac90 (0x7fd2721d9c90 in /home/ubuntu/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: python3() [0x50ac25]
<omitting python frames>
frame #7: python3() [0x509d48]
frame #8: python3() [0x50aa7d]
frame #10: python3() [0x509d48]
frame #11: python3() [0x50aa7d]
frame #13: python3() [0x509d48]
frame #14: python3() [0x50aa7d]
frame #16: python3() [0x508245]
frame #17: python3() [0x50a080]
frame #18: python3() [0x50aa7d]
frame #20: python3() [0x508245]
frame #22: python3() [0x595311]
frame #25: python3() [0x508245]
frame #27: python3() [0x595311]
frame #28: python3() [0x54b1e1]
frame #30: python3() [0x50abb3]
frame #32: python3() [0x508245]
frame #34: python3() [0x595311]
frame #37: python3() [0x508245]
frame #39: python3() [0x595311]
frame #40: python3() [0x54b1e1]
frame #42: python3() [0x50abb3]
frame #44: python3() [0x509d48]
frame #45: python3() [0x50aa7d]
frame #47: python3() [0x509d48]
frame #48: python3() [0x50aa7d]
frame #50: python3() [0x508245]
frame #51: python3() [0x50a080]
frame #52: python3() [0x50aa7d]
frame #54: python3() [0x508245]
frame #56: python3() [0x635222]
frame #61: __libc_start_main + 0xe7 (0x7fd29d431b97 in /lib/x86_64-linux-gnu/libc.so.6)
```

i find entrypoint at here
https://github.com/facebookresearch/detectron2/blob/495b1166b5faf6a620fcde10de9548780dcdebcb/detectron2/structures/rotated_boxes.py#L483

i captured `boxes1.tensor`, `boxes2.tensor` with shape.
```
boxes1.tensor
tensor([[2037.702,  520.998,  110.123,  607.710,   30.151]], device='cuda:0')

boxes1.tensor.shape
torch.Size([1, 5])

boxes2.tensor
tensor([[   0.000,    0.000,   45.255,   22.627,    0.000],
        [   0.000,    0.000,   45.255,   22.627,   45.000],
        [   0.000,    0.000,   45.255,   22.627,   90.000],
        ...,
        [2944.000, 2944.000,  362.039,  724.077,   90.000],
        [2944.000, 2944.000,  362.039,  724.077,  135.000],
        [2944.000, 2944.000,  362.039,  724.077,  180.000]], device='cuda:0')

boxes2.tensor.shape
torch.Size([11299035, 5])
```

i use private dataset in here
https://dacon.io/competitions/official/235492/leaderboard/

## Expected behavior:
Calculate loss value

## Environment:

------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Numpy                     1.16.4
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.2
cv2                       3.4.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Could you use `pickle.dump` to capture the input boxes and see if calling `box_iou_rotated` can reproduce your issue?

**Comment by ssaru** [comment]
appreciate your reply

here are my pickle file (`boxes1`, `boxes2`)

**NOTE**
`boxes1`, `boxes2` are `torch.tensor` in cpu
because it was need check `pickle.dump` working right or not
it were dumped `torch.tensor` in cpu

[boxes1,2.zip](https://github.com/facebookresearch/detectron2/files/4117990/boxes1.2.zip)
