### ISSUE TITLE
Use of del in ROI head

### ISSUE THREAD

**Issue by raghavgoyal14** [facebookresearch/detectron2#762]
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L381

I noticed the heavy use of `del` in the above `forward()`. Is it of any advantage here?

Thanks,
Raghav

**Comment by ppwwyyxx** [comment]
In theory it reduces peak memory usage. 
We have not checked whether it has an advantage in reality. It is just kept as a good coding practice.
