### ISSUE TITLE
inference_on_dataset VS DefaultPredictor

### ISSUE THREAD

**Issue by soad89** [facebookresearch/detectron2#765]
Hello, I have found unexpected behaviour on folowing approaches to predict on images on trained model. 

When I use for inference this pcs of code i can identify some images in my validation dataset to be 0 instances.
```
val_loader = build_detection_test_loader(cfg, "validation")
inference_on_dataset(DefaultPredictor(cfg).model,val_loader,Counter())

class Counter(DatasetEvaluator):
    def process(self, inputs, outputs):
    for input, output in zip(inputs, outputs):
        if(len(output["instances"])==0):  print(input["file_name"])
```
When I process printed paths to images with 0 detected instances with following code:

```
predictor = DefaultPredictor(cfg)
im = cv2.imread(PathToSameImage)
output = predictor(im)
```
I get some predictions in `output["instances"]` . And vice versa, sometimes what detects `inference_on_dataset` i could not replicate with simple `DefaultPredictor `call. Does anybody have an idea what could cause that?

**Comment by ppwwyyxx** [comment]
As [documentation](https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor) of DefaultPredictor says, it does a few extra preprocessing (and it takes a BGR image) so its behavior is not identical to using the model directly.

Also, you're using opencv to read the image but `build_detection_test_loader` use Pillow. This could also produce different inputs.
