### ISSUE TITLE
How to use trained model as new weights file

### ISSUE THREAD

**Issue by ysefwakil** [facebookresearch/detectron2#766]
Hi there,

is there anyway for me to add my trained model_final.pth file to be the current weights file I run inference on. Cheers

**Comment by ppwwyyxx** [comment]
How do you currently run inference?

**Comment by ashkanaev** [comment]
Ok, thank you!

**Comment by ysefwakil** [comment]
`cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.1  

#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = "./output/model_final.pth"
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1

predictor = DefaultPredictor(cfg)
outputs = predictor(im)`

**Comment by ppwwyyxx** [comment]
You can let the predictor use your weights by setting `cfg.MODEL.WEIGHTS` to your weights, as you're already doing.
