### ISSUE TITLE
Hanging after Starting training from iteration 0

### ISSUE THREAD

**Issue by asparamancer** [facebookresearch/detectron2#767]
This isn't a bug as such I don't think, but after it gives `[01/30 02:45:17 d2.engine.train_loop]: Starting training from iteration 0` it just hangs there, it seems to be doing something though as it's reading from disk according to stackdriver but there's no GPU usage. 

Machine is 64 core 240GB 8GPU instance, training coco deepfashion2 (194k images). How long should it remain on `Starting training from iteration 0` for? Command is train_net.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --num-gpus 8

```
sys.platform linux
Python 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy 1.17.4
detectron2 0.1 @/home/jupyter/detectron2/detectron2
detectron2 compiler GCC 6.3
detectron2 CUDA compiler 10.1
detectron2 arch flags sm_70
DETECTRON2_ENV_MODULE
PyTorch 1.3.1 @/opt/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build False
CUDA available True
GPU 0,1,2,3,4,5,6,7 Tesla V100-SXM2-16GB
CUDA_HOME /usr/local/cuda
NVCC Cuda compilation tools, release 10.1, V10.1.243
Pillow 6.2.2
torchvision 0.4.2 @/opt/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags sm_35, sm_50, sm_60, sm_70, sm_75
cv2 4.1.2


```

**Comment by ppwwyyxx** [comment]
Depending on your pytorch build options or characteristics of your specific dataset it could require up to 10 minutes for the first iteration. 
The environment information you provided is incomplete and it would help to provide them.

**Comment by asparamancer** [comment]
Yeah, I left it for a 90 minutes and it was still hanging. I think it's GCP oddness, with 8 V100s on 16 ims batch it OOMs

Resolution so far: Set disk to SSD for higher IO, and decrease dataloader workers to 1. I'll update this with any configuration suggestions that might help people in future. 

But thanks for replying, looks like it's an environment issue
