### ISSUE TITLE
In testing, sudden interruption at 25 frames 

### ISSUE THREAD

**Issue by Wallzrid** [facebookresearch/detectron2#768]
I have the following problem.

When I try to recognize it, it stops at 25 frames.
When I run a heavy video, it stops at 25 frames. 
But there's nothing wrong with running light videos.

What is the problem?

=================================================================

command : python demo/demo.py --config-file configs/riv/cascade_mask_rcnn_R_50_FPN_3x.yaml --video-input ./test.mp4 --opts MODEL.WEIGHTS model_final_480dd8.pkl

(riv is the folder I created randomly.)

result :

[01/30 14:50:01 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/riv/cascade_mask_rcnn_R_50_FPN_3x.yaml', input=None, opts=['MODEL.WEIGHTS', 'model_final_480dd8.pkl'], output=None, video_input='./test.mp4', webcam=False)
  0%|                                      | 25/14446 [00:15<2:28:42,  1.62it/s]

It only stops at 25 frames. Thanks...

**Comment by ppwwyyxx** [comment]
Since the issue is specific to your own input data, could you provide a colab notebook to reproduce it? Otherwise there is not much we can do.

**Comment by Wallzrid** [comment]
Sorry, that's going to be hard. I'm comparing the available data with the unavailable data. If I find a difference, I'll post it further. Thanks.

**Comment by Wallzrid** [comment]
Clearly, my data has a problem, but i don't know what it happen...
