### ISSUE TITLE
How to detect object in images from a directory using pre-trained models? How to do inference using pre-trained model? How to load pre-trained model and config file? 

### ISSUE THREAD

**Issue by RishiGss** [facebookresearch/detectron2#769]
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md#inference-demo-with-pre-trained-models
