### ISSUE TITLE
Detection pattern

### ISSUE THREAD

**Issue by nainauy** [facebookresearch/detectron2#770]
I have a problem with the detection of objects close to the first object. There is a class name in datasets and the other object does not. When detection is displayed as the same object.
How can I solve this ploblem.

Default backbone restnet-50 step train 300,000

**Comment by ppwwyyxx** [comment]
No model is perfect. This is not an unexpected issue.

Also, as the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.
