### ISSUE TITLE
How to load only weights?

### ISSUE THREAD

**Issue by ashkanaev** [facebookresearch/detectron2#771]
I trying to start new train stage without loading optimizer and scheduler from previous checkpoint. The resume flag is set to false, but these states(optimizer, scheduler) are still loaded.... and i can't valuably configure new stage of training procedure.
How do i configure the train config to load only weights?

**Comment by ppwwyyxx** [comment]
You can read/write the weight file using `torch.load/save` and modify the object directly.

**Comment by wangg12** [comment]
[https://github.com/tianzhi0549/FCOS/blob/master/tools/remove_solver_states.py](https://github.com/tianzhi0549/FCOS/blob/master/tools/remove_solver_states.py)
