### ISSUE TITLE
Where is MODEL.WEIGHTS placed after download from model_zoo?

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#773]
## ❓ How to use Detectron2

After running 
"python demo/demo.py --config-file configs/COCO-Detection/retinanet_R_101_FPN_3x.yaml --input input/input.png --output output_retinanet_101_3x.jpg --opts MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_101_FPN_3x/138363263/model_final_59f53c.pkl"
I see that the model weights will be downloaded from the link provided in the MODEL_ZOO and the next time I run with another input this model weights won't be download anymore. So my question is **where is the downloaded file** ("https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_101_FPN_3x/138363263/model_final_59f53c.pkl") **is placed**? I've searched everywhere in the folder detectron2/ in the whole computer but I can't find anything?
And assume that the model is place in the folder X, so I wonder if I can download all the model zoo and place in that folder X and then I won't need to download anymore every time I want to test a new model?
Many thanks!

**Comment by ppwwyyxx** [comment]
It's saved in "$FVCORE_CACHE" or "~/.torch/fvcore_cache".

**Comment by pvtien96** [comment]
Yes, they are in ~/.torch/fvcore_cache/detectron2:
.
├── COCO-Detection
│   └── retinanet_R_101_FPN_3x
│       └── 138363263
│           ├── model_final_59f53c.pkl
│           └── model_final_59f53c.pkl.lock
├── COCO-InstanceSegmentation
│   ├── mask_rcnn_R_50_FPN_3x
│   │   └── 137849600
│   │       ├── model_final_f10217.pkl
│   │       └── model_final_f10217.pkl.lock
│   └── mask_rcnn_X_101_32x8d_FPN_3x
│       └── 139653917
│           ├── model_final_2d9806.pkl
│           └── model_final_2d9806.pkl.lock
├── COCO-PanopticSegmentation
│   └── panoptic_fpn_R_101_3x
│       └── 139514519
│           ├── model_final_cafdb1.pkl
│           └── model_final_cafdb1.pkl.lock
└── ImageNetPretrained
    └── MSRA
        ├── R-50.pkl
        └── R-50.pkl.lock
But when I download model from model zoo, I get only one file model_final.pkl, so I think that I won't download and place mode weights manually beacause there's no guide to construct this folder as well as I don't have the file ".pkl.lock", right?
Many thanks to you, @ppwwyyxx

**Comment by ppwwyyxx** [comment]
The ".lock" file is not necessary.
You can download the file from model zoo and set `WEIGHTS` to the path of the file.
