### ISSUE TITLE
Weight & Biases support

### ISSUE THREAD

**Issue by truskovskiyk** [facebookresearch/detectron2#774]
## 🚀 Feature
Adding support for [wandb](https://docs.wandb.com/quickstart) library

## Motivation

W&B is one of the most advanced and feature-rich experiment tracking tools. It would be great to have support in detectron2. 
Great example: https://app.wandb.ai/syllogismos/keras-retinanet

## Pitch

I implemented it in my own project as `wanbb_writer.py` module

```
import wandb
from detectron2.utils.events import (
    EventWriter,
    get_event_storage,
)


class WAndBWriter(EventWriter):
    """
    Write all scalars to a wandb tool.
    """

    def __init__(self, window_size: int = 20):
        self._window_size = window_size

    def write(self):
        storage = get_event_storage()
        for k, v in storage.latest_with_smoothing_hint(self._window_size).items():
            wandb.log({f"{k}": v}, step=storage.iter)

        if len(storage.vis_data) >= 1:
            for img_name, img, step_num in storage.vis_data:
                self._writer.add_image(img_name, img, step_num)
            storage.clear_images()

    def close(self):
        pass

```
and add this class as one of the `writer` here
https://github.com/facebookresearch/detectron2/blob/master/tools/plain_train_net.py#L136

If someone finds this feature useful as I do, I would be happy to send a PR with W&B writer and tests for it.

cc: @cvphelps

**Comment by kenhktsui** [comment]
Syncing tensorboard in wandb does the same thing thanks to the TensorboardXWriter. But it doesn't track the AP/AR during training as in your example.

**Comment by ppwwyyxx** [comment]
I suppose wandb will be enabled by just adding `import wandb; wandb.init(sync_tensorboard=True)` to your code. It doesn't look like we need to do anything for it.

AP curves will be available if you set `TEST.EVAL_PERIOD`.

**Comment by Csanad98** [comment]
I have followed the suggestion by @ppwwyyxx and added `import wandb; wandb.init(sync_tensorboard=True)` to my Colab training session. However, I get the following error repeatedly:
`wandb: ERROR Unable to log event [Errno 95] Operation not supported: '/content/gdrive/.shortcut-targets-by-id/1zWeNeHzrg6jXlkkpPMjpgtrJArsDu-Ri/DL-Panoramic-Images/Data/output/events.out.tfevents.1598531893.f62daae8a623.103.2' -> '/content/gdrive/.shortcut-targets-by-id/1zWeNeHzrg6jXlkkpPMjpgtrJArsDu-Ri/DL-Panoramic-Images/Data/wandb/run-20200827_123503-21i52v19/events.out.tfevents.1598531893.f62daae8a623.103.2'`

In wandb it registers the run and I can see hardware related plots but nothing else is logged. Could you help me to figure out what's going wrong?

**Comment by markuzo** [comment]
> I have followed the suggestion by @ppwwyyxx and added `import wandb; wandb.init(sync_tensorboard=True)` to my Colab training session. However, I get the following error repeatedly:
> `wandb: ERROR Unable to log event [Errno 95] Operation not supported: '/content/gdrive/.shortcut-targets-by-id/1zWeNeHzrg6jXlkkpPMjpgtrJArsDu-Ri/DL-Panoramic-Images/Data/output/events.out.tfevents.1598531893.f62daae8a623.103.2' -> '/content/gdrive/.shortcut-targets-by-id/1zWeNeHzrg6jXlkkpPMjpgtrJArsDu-Ri/DL-Panoramic-Images/Data/wandb/run-20200827_123503-21i52v19/events.out.tfevents.1598531893.f62daae8a623.103.2'`
> 
> In wandb it registers the run and I can see hardware related plots but nothing else is logged. Could you help me to figure out what's going wrong?

There's a similar issue on Windows because it's not possible to create the symlinks due to permissions. Running in admin mode fixes that.

**Comment by EricCousineau-TRI** [comment]
Just to check, is there a simple way to also reflect the relevant configuration bits to `wandb`? (and possibly have `wandb` also override these for things like sweeps?)

(Will search and then play with this briefly, and edit this comment if I have an update)

**Comment by marcosterland** [comment]
Probably something has changes meanwhile, but the example of @truskovskiyk doesn't work for me. Below is my adaptation, which works with v0.3.
I've noticed W&B has issues with `/` in the metric names.

```python
class WAndBWriter(EventWriter):
    """
    Write all scalars to a wandb tool.
    """

    def __init__(self, window_size: int = 20):
        self._window_size = window_size

    def write(self):
        storage = get_event_storage()
        stats = {}
        for k, v in storage.latest_with_smoothing_hint(self._window_size).items():
            stats[k.replace("/", "-")] = v[0]
        wandb.log(stats, step=storage.iter)

        if len(storage._vis_data) >= 1:
            for img_name, img, step_num in storage._vis_data:
                self._writer.add_image(img_name, img, step_num)
            storage.clear_images()

    def close(self):
        pass
```

**Comment by XBeg9** [comment]
hey @marcosterland , would love if you share an example colab notebook or a bit more context how you actually use this writer. Thanks

**Comment by dorbittonn** [comment]
> 

any updates regarding this? successful ?
