### ISSUE TITLE
Saving checkpointable objects

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#775]
1) From Detectron2 codebase, I see that it uses fvcore's [checkpoint.py](https://github.com/facebookresearch/fvcore/blob/master/fvcore/common/checkpoint.py) class to save every checkpointable object. Is my understanding correct? Does this mean that weights, optimizer, scheduler, etc. are all saved as a Python dict?

2) When loading a model to resume training or inference, does detectron2 load all the checkpointable objects? Or only the weights?

3) How can I customize the saving/loading of checkpointable objects in detectron2?

**Comment by ppwwyyxx** [comment]
1. yes
2. all objects
3. the easiest way is to remove objects you don't want to load from the checkpoint. The not-so-easy way is to create a checkpointer without optimizer/scheduler etc, and use it initialize the training, instead of using the default logic provided by detectron2.
