### ISSUE TITLE
Evaluate on Custom Dataset With a `COCOEvaluator`

### ISSUE THREAD

**Issue by joe3141** [facebookresearch/detectron2#781]
According to the [documentation](https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.COCOEvaluator), I can use a `COCOEvaluator` if the dataset has the path to the json file as part of its metadata, or if it's in Detectron2's standard dataset format.

I have followed the tutorial on training on custom datasets, successfully registered the dataset I am using and trained on it, however when I want to apply the `COCOEvaluator`, I get an error that the json file is missing. Shouldn't it be already in Detectron2's standard dataset format?

On another note, is there's a way to quickly transform Detectron2's dataset dicts and dump it to a json file that should have the format of a COCO dataset?

In hindsight, I think it would have been much more convenient to start with converting my dataset into coco format and just use the builtin registerer for it, since then I could also reuse it for evaluation without much effort.

**Comment by ppwwyyxx** [comment]
A dataset that is in Detectron2's standard dataset format will be evaluated and there is nothing specific you need to do about it. The colab tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 demonstrates this.

If you met an error that you don't know why, 
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by joe3141** [comment]
I have interpreted the warning: `json_file was not found in MetaDataCatalog for '` as an indication that it would not evaluate, but this seems to have been not the case. So I was mistaken in this regards.

However when I run the evaluation block that has the function `inference_on_dataset`, I get this warning: `No predictions from the model! Set scores to -1` and all the metrics are just -1.
Keeping in mind that I do successfully get (decent) mask predictions and scores from input images, and from the same input images that are from the evaluation dataset. So there are definitely some valid predictions from the model.

So what do you think have gone wrong in my pipeline?

**Comment by dhaivat666** [comment]
@joe3141 I am not sure if this is related but I had similar problem and the reason was that there is this `./output` directory created which saves the jason file. Now, the code is not overwriting it and hence when you run your code for the second time, it gives such problem. When you define your evaluator, ensure that you have deleted your old directory, or give path to any new directory. 

evaluator = COCOEvaluator("kitti/test", cfg, False, output_dir="./resnet-50_FPN/")

Something like above, the output_dir should be new so you don't end up using anything from your previous executions.

**Comment by tshead2** [comment]
I had too many problems to count, trying to use a custom dataset in Detectron2 format with COCOEvaluator ... the path of least resistance was to convert my dataset into COCO format and register it using `detectron2.data.datasets.register_coco_instances()`

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md). They are not provided so far, so closing.
