### ISSUE TITLE
How to save model after training it? (for later inference use)

### ISSUE THREAD

**Issue by frankkim1108** [facebookresearch/detectron2#785]
## ❓ How to use Detectron2

Hi, I was following the [tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=roTj1N9F5uJ5) and I was training the model with the Balloon Data.

**However, I wanted to export and save the trained model at a specific directory.**
I made **train.py** and **predict.py**.
     In **train.py**, 
     I got balloon data as input and trying to output the trained model to use in predict.py.
     In **predict.py**, 
     I am going to get trained model as an input and inference it on the balloon data. 

**Is there anyway to save the trained model at a specific directory??**

**Comment by ppwwyyxx** [comment]
The tutorial saves the model in the "output" directory.

**Comment by frankkim1108** [comment]
Thank you for your quick response.

**Comment by Dimbinantenaina** [comment]
Hi.
I would like to know how to change the 'output' directory to my own directory when using DefaultTrainer.
