### ISSUE TITLE
Manipulating config parameters while training

### ISSUE THREAD

**Issue by Kbkartik** [facebookresearch/detectron2#786]
How can I manipulate config parameters while training a model? By default, in the setup method of base plain_train_net.py, the config object 'cfg' is frozen. Is there any particular reason on why this is done? I assumed that config parameters are frozen only after the training is complete and the model is ready for inference.

**Comment by ppwwyyxx** [comment]
The cfg object is not used during training so there is no point to manipulate it.

See https://meta.stackexchange.com/a/66378
