### ISSUE TITLE
I have a custom dataset of kitti format. How can i use it with Detectron2 ?

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#787]
I have a custom dataset with one class, which contains several resolution images.. All label files are in kitti format.. How can i use it with Detectron2 ?
 
I have already read about register custom dataset . I would like to get some code for that

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by ZJC1013** [comment]
@Samjith888 My implementation of training detectron2 Mask R-CNN on KITTI might help you. https://github.com/ZJC1013/detectron2_on_kitti
