### ISSUE TITLE
Exif metadata causes training to fail with SizeMismatchError

### ISSUE THREAD

**Issue by information-security** [facebookresearch/detectron2#788]
## Instructions To Reproduce the Issue:
I'm following **Detectron2 Beginner's Tutorial** Colab notebook to train my custom dataset. Images in my dataset have orientation exif metadata tag. I can see that Detectron2 has had a PR (#262) which implies that it supports exif orientation tag. I'm using [VGG Image Annotator (VIA)](http://www.robots.ox.ac.uk/~vgg/software/via/) to label my images. VIA tool loads images with respect to their orientation value and therefore polygons drawn on images are suitable for rotated images (I'm opening VIA tool in Safari/Chrome in OSX. I've read somewhere it makes difference).

Only modification I've made in colab notebook's code is to alter `get_balloon_dicts` function to read my classes from `region_attributes` section of `via_region_data.json` file which is left intact in tutorial code. I can see Detectron2 is successfully showing table of distribution of categories  which means my code works perfectly however training fails with following error:
```
model_final_f10217.pkl: 178MB [00:06, 26.5MB/s]                           
'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (25, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (25,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (96, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (96,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (24, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (24,) in the model! Skipped.
[02/02 21:16:42 d2.engine.train_loop]: Starting training from iteration 0
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:603: UserWarning: Metadata Warning, tag 282 had too many entries: 2, expected 1
  % (tag, len(values))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:603: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  % (tag, len(values))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:603: UserWarning: Metadata Warning, tag 282 had too many entries: 2, expected 1
  % (tag, len(values))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:603: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  % (tag, len(values))
ERROR [02/02 21:16:45 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/content/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/content/detectron2_repo/detectron2/engine/train_loop.py", line 208, in run_step
    data = next(self._data_loader_iter)
  File "/content/detectron2_repo/detectron2/data/common.py", line 109, in __iter__
    for d in self.dataset:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
detectron2.data.detection_utils.SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/detectron2_repo/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/detectron2_repo/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/detectron2_repo/detectron2/data/dataset_mapper.py", line 76, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/content/detectron2_repo/detectron2/data/detection_utils.py", line 87, in check_image_size
    expected_wh,
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image dataset/train/img19.jpg, got (3024, 4032), expect (4032, 3024)

/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:603: UserWarning: Metadata Warning, tag 34853 had too many entries: 9, expected 1
  % (tag, len(values))
[02/02 21:16:46 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
```
`SizeMismatchError` exception thrown with indication of expected (4032, 3024) but getting (3024, 4032) for `img19.jpg` makes me think that it is has something to do with orientation tag since this file has an orientation of 90 degrees. Interesting part is that there are some images with orientation tag that get passed this error (or at least I think so)!

Note that in my `get_balloon_dicts` function I'm reading height and width of images with following code:
```
height, width = cv2.imread(filename).shape[:2]
record["height"] = height
record["width"] = width
```
I've also tried followings without any luck:

1. `height, width = cv2.imread(filename, cv2.IMREAD_UNCHANGED).shape[:2]` (Described below why)
2. `height, width = skimage.io.imread(filename).shape[:2])`
3. `height, width = skimage.io.imread(filename, plugin='pil').shape[:2])`

Also note that in the section of verifying data loading:
```
dataset_dicts = get_balloon_dicts("balloon/train")
for d in random.sample(dataset_dicts, 3):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=balloon_metadata, scale=0.5)
    vis = visualizer.draw_dataset_dict(d)
    cv2_imshow(vis.get_image()[:, :, ::-1])
```
Images are shown without considering their respective orientation value and therefore their annotations are shown falsely. I fixed that by changing
`    img = cv2.imread(d["file_name"])`
to
`    img = cv2.imread(d["file_name"], cv2.IMREAD_UNCHANGED)`
As a result, I thought applying same change to `imread` call in `get_balloon_dicts` function would help but doing so had no effect and same error showed up. 

## Environment:

I'm running the code in Google's Colab notebook

**Comment by ppwwyyxx** [comment]
We use Pillow to read images https://github.com/facebookresearch/detectron2/blob/94d0f138e49c3d7e202025941b2d1890831f07fa/detectron2/data/detection_utils.py#L49-L55

If it does not read the correct size, this sound like a bug you could report to Pillow.

**Comment by information-security** [comment]
> If it does not read the correct size, this sound like a bug you could report to Pillow.

Wow, thanks. You are right seems to be a bug of Pillow. A quick test code shows that:
```
file_name = "/content/dataset/train/img19.jpg"
img = cv2.imread(file_name, cv2.IMREAD_UNCHANGED)
print (img.shape[:2])

from PIL import Image, ImageOps
from fvcore.common.file_io import PathManager
with PathManager.open(file_name, "rb") as f:
  image = Image.open(f)
  image = ImageOps.exif_transpose(image)
  image = np.asarray(image)
  print (image.shape[:2])
```
Returns:
(4160, 2080) -> This is the correct size
(2080, 4160)

> We use Pillow to read images during training

@ppwwyyxx  Sorry if it seems a silly question but why aren't you simply using `cv2.imread` with having `cv2.IMREAD_UNCHANGED` flag set? I guess relying on OpenCV rather than Pillow is more of a correct decision here, isn't it?

In the meantime, If I manually change the definition of `read_image` function to use `cv2.imread` do I break anything? It's kind of pain to wait until Pillow guys start to fix this bug considering the fact that I can not give then my sample image because it's proprietary.

**Comment by ppwwyyxx** [comment]
We're evaluating whether we should use opencv. The main issue with it is opencv has led to a few system level issues in the past in the way it uses threads and exposes symbols.

You can change it to use cv2.

**Comment by information-security** [comment]
Sharing the code that worked for me in case anyone might find it useful:
```
def read_image(file_name, format=None):
    img = cv2.imread(file_name, cv2.IMREAD_UNCHANGED)
    if format == "BGR":
        # PIL only supports RGB, so convert to RGB and flip channels over below
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        # flip channels
        img = img[:, :, ::-1]
    # PIL squeezes out the channel dimension for "L", so make it HWC
    if format == "L":
        img = np.expand_dims(img, -1)
    return img
```

It's definitely incomplete and needs to be improved for different types of formats. I tested it for BGR only.

**Comment by ppwwyyxx** [comment]
I don't think that's correct for other modes. Note that "format" means the target format the image will be in.

**Comment by woctezuma** [comment]
Hello,

I chime in, because I encounter the same issue with the same dataset (balloon). I have used a small utility to convert the dataset from VIA format into COCO format. Afterwards, I can use directly fine-tune vanilla [DETR](https://github.com/facebookresearch/detr), or register the dataset and fine-tune DETR in the detectron2 wrapper with a few lines like these:

```python
# from detectron2.data.datasets import register_coco_instances
# register_coco_instances("my_dataset_train", {}, "json_annotation_train.json", "path/to/image/dir")
# register_coco_instances("my_dataset_val", {}, "json_annotation_val.json", "path/to/image/dir")
```

What is weird is that vanilla DETR was fine, and only detectron2/DETR returns this error. Is there any reason why the issue would only arise with the wrapper?
