### ISSUE TITLE
Config References link need to be updated

### ISSUE THREAD

**Issue by Jeoker** [facebookresearch/detectron2#789]
Hi, 
I am new to detectron2 and was trying to find the references for configration parameters. I was trying to open this link given in this page: [docs/tutorials/config.md](https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/configs.md), but it gave me an 404 error, please update this page, thank you

**Comment by ppwwyyxx** [comment]
The docs are meant to be read on https://detectron2.readthedocs.io/.

**Comment by Jeoker** [comment]
Thanks Yixin, but please remove the obselete link, it's confusing.
