### ISSUE TITLE
weight configurations for some models are not correct

### ISSUE THREAD

**Issue by kindloaf** [facebookresearch/detectron2#79]
In several yaml configuration files, the weights are not configured correctly.

For example, in [faster_rcnn_R_50_FPN_1x.yaml](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml), the current value of the weights is: 
`detectron2://ImageNetPretrained/MSRA/R-50.pkl`

But according to [model_zoo](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md), the correct value should be:
`detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl`

**Comment by ppwwyyxx** [comment]
The configs are for training the model. So it does not load a model that's already trained.

You can set the config value to a model that's already trained, if you need to evaluate the model.

**Comment by kindloaf** [comment]
I see, it makes sense. Thanks for the explanation.
For clarity, this should probably be added to GETTING_STARTED.md, where the evaluation command line is discussed.
