### ISSUE TITLE
Question about PointRend

### ISSUE THREAD

**Issue by xmyqsh** [facebookresearch/detectron2#792]
Thanks for sharing `PointRend`. @alexander-kirillov The modeling is elegant and efficient.

I have a question about `CoarseMaskHead`.
It uses an [`FC` layer](https://github.com/facebookresearch/detectron2/blob/master/projects/PointRend/point_rend/coarse_mask_head.py#L70) instead of a `Conv1x1` layer for mask prediction as usual.
In other words, there is no weight sharing on spatial.
What is the consideration behind the choice? I have not got the ablation discussion about this in the paper.
Comparingly, the [`PointHead`](https://github.com/facebookresearch/detectron2/blob/master/projects/PointRend/point_rend/point_head.py#L131) use a `Conv1d` on prediction which could share the weights on virtual spatial.

**Comment by BrianPugh** [comment]
In this context, `Conv1d` and `Linear` are functionally equivalent.

**Comment by alexander-kirillov** [comment]
Dear @xmyqsh, detectron2 github issues are for reporting bugs or feature requests, not discussing research topics (see https://github.com/facebookresearch/detectron2/issues/new/choose). Please, reach out by email!
