### ISSUE TITLE
Please help me on customizing training datasets

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#795]
## ❓ How to use Detectron2

Hi guys, thanks for reading.
I'm currently working on instance segmentation with only one class "X" and I get troubles on training model.
I have a data set with n sample, each one is a pair of an original RGB image and a binary mask image.
I've read the docs very carefully: the Detectron2's official tutorial ([Use custom datasets](https://detectron2.readthedocs.io/tutorials/datasets.html)) and the [Colab Notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) with the example on training ballon dataset. Also, I searched for code to transform binary-mask datasets to COCO-form dataset, like [this](https://github.com/cocodataset/cocoapi/issues/131)
But I still can't handle my case. So I was wondering if you can give me some recommendations (is there any code available? what should I do?)
Below is a sample of my data: a pair of original image and a a binary mask segmented image.
![original](https://user-images.githubusercontent.com/25927039/73662441-60d4fd80-46ce-11ea-9a90-98c5748ff970.jpg)
![mask](https://user-images.githubusercontent.com/25927039/73662440-603c6700-46ce-11ea-807b-418cb8718187.png)

Any help is highly appreciated!

**Comment by information-security** [comment]
@pvtien96 You can use Canny algorithm to detect edges of your objects then get location of white pixels:

![Unknown-2](https://user-images.githubusercontent.com/4983612/73690773-59b9e980-46e6-11ea-8f93-2951c9ffcaf0.png)


```
import numpy as np
import cv2 as cv

img = cv.imread('PATH TO YOUR IMAGE', 0)
edges = cv.Canny(img,100,200),
annotations = np.argwhere(edges == 255)
``` 
`annotations` contains X,Y location of your polygon. Keep in mind that this method works only if you have one object per image and there is no overlapping. In those cases you need to do more tweaking.

**Comment by ppwwyyxx** [comment]
As our [documentation](https://detectron2.readthedocs.io/tutorials/datasets.html#register-a-dataset) says, you can provide per-pixel segmentation mask in COCO's RLE format.

You can convert a uint8 segmentation mask of 0s and 1s into an RLE by `pycocotools.mask.encode(np.asarray(mask, order="F"))`. We'll add this to the docs as well.
