### ISSUE TITLE
gpu model export: what version of pytorch?

### ISSUE THREAD

**Issue by r2dliu** [facebookresearch/detectron2#797]
Noted that recently changes were made to detectron2 to allow exporting a GPU model, but only when using pytorch's master. 

Do you happen to know exactly what version of pytorch was being used at that time? Knowing the hash would be nice. Detectron2 has problems installing with both nightly builds and master, but installs fine with 1.4. Appears to be an issue during compilation

``/usr/include/c++/8/bits/basic_string.tcc:1067:1:` error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1``

python 3.6/3.7, gcc8, cuda 10.1/10.2. have tested various combinations

**Comment by ppwwyyxx** [comment]
That sounds like bugs with nvcc. It does not currently work with gcc8.
