### ISSUE TITLE
Summary model for detectron2 model

### ISSUE THREAD

**Issue by tamyxgopenx** [facebookresearch/detectron2#799]
## 🚀 Feature

Hi talented team, i wonder is there any summary function for model detectron2, try to use torchsummary but it's keep error as IndexError: too many indices for tensor of dimension 3
## Motivation
To check the main different from detectron2 and mask rcnn beside the different framework (pytorch and tensoflow) is there any other different that make my detectron2 yeild better result for my dataset 

## Pitch
What i wished for :3

![image](https://user-images.githubusercontent.com/36707772/73723329-5d3b8800-475b-11ea-92a4-6e70263757fa.png)

**Comment by przemb** [comment]
hi @ppwwyyxx 
do you have any suggestions what will be the best place to put such a function? 
should it be in one of files from [utils](https://github.com/facebookresearch/detectron2/tree/master/detectron2/utils)? 
I could try to provide initial version :)

**Comment by ppwwyyxx** [comment]
"utils/analysis.py" is where we plan to put such code.

A linear Keras-style summary is definitely a bad idea for complicated models -- I agree with the arguments from the pytorch issue. I expect a recursive presentation: just like what `print(model)` shows now, but with shapes. We have an internal implementation that does something similar, but it has many internal dependencies and it's currently not on top of our list of work to open source it.

**Comment by jk78346** [comment]
A follow up question: 
Did you guys reveal any detail implementation of models in detectron2 such in publication or in source code? For example, I want to use COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml in my research, while I cannot find out the layers design of it so far from my searching.

**Comment by jaan1729** [comment]
@ppwwyyxx any update on this enhancement?

**Comment by ppwwyyxx** [comment]
This was done in `tools/analyze_model.py` a long time ago.
