### ISSUE TITLE
So Detectron2 do not support direct registration of Cityscape-style data set?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#800]
## ❓ So Detectron2 do not support direct registration of Cityscape-style data set?
Because I did not find a anything like `register_cityscape_instances`.

Any answer and suggestion would be appreciated.

**Comment by ppwwyyxx** [comment]
that's right.

**Comment by songyuc** [comment]
Hi, @ppwwyyxx,
so is there a conveniet way for me to use Detectron2 to use my data set in Cityscape format?

**Comment by ppwwyyxx** [comment]
There isn't.
Given how complicated the format is, it seems quite rare and unnecessary to build a custom dataset in cityscapes format. We do not plan to support such feature.

You can use https://detectron2.readthedocs.io/modules/data.html#detectron2.data.datasets.load_cityscapes_instances to implement your own `register_cityscape_instances`

**Comment by slulura** [comment]
Can you use register_all_cityscape ?
