### ISSUE TITLE
What are FPN strides in the context of a new backbone ? 

### ISSUE THREAD

**Issue by Cyril9227** [facebookresearch/detectron2#801]
##  What is the correct way to use strides in FPN ❓

Hello,

I'm implementing a new backbone for detectron2 API, currently it yields a set of feature maps as expected `{"stage1" : <feature_map1>, ..., "stageN" : <feature_mapN>}` . However, the FPN expects strides for each feature maps and I'm really not sure what is it supposed to be.   

```     # Feature map strides and channels from the bottom up network (e.g. ResNet)
        input_shapes = bottom_up.output_shape()
        in_strides = [input_shapes[f].stride for f in in_features]
        in_channels = [input_shapes[f].channels for f in in_features]```

Could someone explains me how to set these attributes for all my output feature maps ? 

Thank's in advance.

**Comment by ppwwyyxx** [comment]
stride means the relative spatial scale of the input image v.s. the feature map.
For example, if the input image goes through a stride-2 max pooling and a stride-2 convolution, then the stride becomes 4.

**Comment by Cyril9227** [comment]
Thank you @ppwwyyxx for your answer. So just to make sure I understood well, if my inputs are `(1024, 1024)` RGB images and my backbone yields : 
```stage1: torch.Size([1, 16, 250, 250])
stage2: torch.Size([1, 24, 125, 125])
stage3: torch.Size([1, 48, 62, 62])
stage4: torch.Size([1, 88, 31, 31])
stage5: torch.Size([1, 120, 15, 15])
stage6: torch.Size([1, 208, 7, 7])
stage7: torch.Size([1, 352, 3, 3])```


Then my strides would be `[2, 4, 8, 16, 33, 71, 166]`

Correct ?
