### ISSUE TITLE
How to load a model trained on a custom dataset and perform inference.

### ISSUE THREAD

**Issue by Aaronzinhoo** [facebookresearch/detectron2#802]
I am currently having trouble trying to load the model I trained and use it to perform inference on new images. 

`   
register_coco_instances("clothing_style", {}, "./data/Style_Datatset-1.json", "./data/images")
    dataset_dicts = DatasetCatalog.get("clothing_style")
    style_metadata = MetadataCatalog.get("clothing_style")
    cfg = get_cfg()
    cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")
    cfg.DATASETS.TEST = ("clothing_style", )
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
    cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8
    model = build_model(cfg)  # returns a torch.nn.Module
    DetectionCheckpointer(model).load("./output/model_final.pth")
    model.train(False)
    img = np.transpose(cv2.imread(sys.argv[1]),(2,0,1))
    img_tensor=torch.from_numpy(img)
    inputs = [{"image":img_tensor}, {"image":img_tensor}] 
    print(model(inputs))
`

When I print the outputs, everything runs normally but nothing is detected. My images are standard images from the dataset. Heres the output:

`
[{'instances': Instances(num_instances=0, image_height=389, image_width=295, fields=[pred_boxes = Boxes(tensor([], device='cuda:0', size=(0, 4))), scores = tensor([], device='cuda:0', grad_fn=<IndexBackward>), pred_classes = tensor([], device='cuda:0', dtype=torch.int64), ])}, {'instances': Instances(num_instances=0, image_height=389, image_width=295, fields=[pred_boxes = Boxes(tensor([], device='cuda:0', size=(0, 4))), scores = tensor([], device='cuda:0', grad_fn=<IndexBackward>), pred_classes = tensor([], device='cuda:0', dtype=torch.int64), ])}]
`

Lastly my environment is 

`
------------------------  ------------------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1 @/home/aaron/Development/DONKI/Fashion_Color_Pattern_Pipeline/style_detection/detectron2_repo/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/aaron/.virtualenvs/style/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2070 SUPER
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.2
torchvision               0.5.0 @/home/aaron/.virtualenvs/style/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

`

**Comment by Aaronzinhoo** [comment]
Any help would be appreciated, I read the docs and the tutorials and followed them step by step for the most part except that I split up the work between training and inference in two scripts rather than a google colab sheet. Thanks in advance

**Comment by ppwwyyxx** [comment]
You can load an official model instead to know whether the code you provided is correct or not.

**Comment by Aaronzinhoo** [comment]
Ok, so changing the loading path to a pretrained model from detectron resulted in predictions. So then it must be the checkpoint that I am loading, but the training went smoothly it seemed. 
`
DetectionCheckpointer(model).load("./output/model_final.pth")

DetectionCheckpointer(model).load("detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl")
`

The main differences are the file formats, but from the docs, both are supported right? I dont really get the "detectron2://" path but I dont think that would be an issue either. Any thoughts?

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.

**Comment by Aaronzinhoo** [comment]
I understand, I thought this was a usage type of question since I am clearly missing something with loading a local model checkpoint file. This isnt a suggestion on how to train or asking about the work or coverage.
