### ISSUE TITLE
Minor implementation difference between forward pass and backward pass of roi align

### ISSUE THREAD

**Issue by jackalcooper** [facebookresearch/detectron2#804]
##### Excerpt from roi align cuda implementation
in forward pass:
```cpp
    // We do average (integral) pooling inside a bin
    // When the grid is empty, output zeros.
    const T count = max(roi_bin_grid_h * roi_bin_grid_w, 1); // e.g. = 4
```
in backward pass:
```cpp
    // We do average (integral) pooling inside a bin
    const T count = roi_bin_grid_h * roi_bin_grid_w; // e.g. = 4
```
Could you explain why there is no `max` when computing the count in the backward pass of roi align?

**Comment by ppwwyyxx** [comment]
Thanks. That does look odd. 
However the `max()` part will take effect if and only if the roi is a box of zero area, which almost never happens. 
Maybe it could only happen in rare cases of floating point precision issues.
But we will consider making them more consistent.

**Comment by ppwwyyxx** [comment]
After a closer look, max(, 1) is only used to avoid division-by-zero, which exists only in forward. So there is nothing left to do.
