### ISSUE TITLE
Apm and APi has -100 value after evaluation.

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#806]
**Here i have two questions.**
1) After evaluation, i got the -100 value for Apm and APi ? What is meant by 
AP50 , AP75 ,  APs ,  APm  ,  APl this?
2) Got '[1]    24895 segmentation fault (core dumped) ' after evaluation. How to solve this ? Gcc version is 7.

Model used : configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml
Class : person

**Environment** 

output of python -m detectron2.utils.collect_env

![gcc](https://user-images.githubusercontent.com/39676803/73813281-8c0e3880-4805-11ea-945b-719974197027.png)

**Training output log**

![20000iter](https://user-images.githubusercontent.com/39676803/73813303-96303700-4805-11ea-821f-09c57417831a.png)

**Comment by ppwwyyxx** [comment]
1. It means these metrics cannot be computed.
2. There are a million ways an environment or installation could go run so we would require a reproducible environment in order to investigate such issues.

**Comment by Samjith888** [comment]
>     1. It means these metrics cannot be computed.
> 
>     2. There are a million ways an environment or installation could go run so we would require a reproducible environment in order to investigate such issues.

what is APm and Api metrics means?

**Comment by ppwwyyxx** [comment]
http://cocodataset.org/#detection-eval
medium and large.
