### ISSUE TITLE
Use a custom trained model with DefaultPredictor(cfg)

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/detectron2#808]
Hello, 
I have seen some issues that have similar problems (but not exact) and I have read the detectron2 decontamination but I haven't manged to solve this. 

I have train a model in a colab notebook.
Using the colab tutorial provided here,the model is being saved to a folder named 'output' and is used to get new predictions. When I use the training notebook to get predictions everything works great, but when I try and save my model then load it in a new file I get really strange predictions. 

I tried:
1. Just downloading the file called 'finel_model.pth' then using this code to get a prediction: 
`cfg = get_cfg() cfg.merge_from_file(model_zoo.get_config_file("COCOInstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS  = ("finel_model.pth path")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)`  (the lines got massed up while coping them to github, I dont know why) 

2. Using torch.save(model.state_dict(), 'checkpoint.pth') to save to model, 
DetectionCheckpointer(model).load('checkpoint.pth path') to load the model and then use 
predictor = DefaultPredictor(cfg) to get predictions. 

both of the methods above failed completely (no errors but the predictions are very strange, just random boxes and polygons) 

Can some one please help? how do I use the model I trained with DefaultPredictor(cfg)?

**Comment by ggalan87** [comment]
When you train for your own dataset, during test phase I think you only need to set cfg.MODEL.ROI_HEADS.NUM_CLASSES, then possibly also, cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 and if you need to evaluate with the whole dataset: cfg.DATASETS.TEST must point to the registered dataset's name.

**Comment by ppwwyyxx** [comment]
@ggalan87 's comment is correct. Basically you need configs that you used in training.
