### ISSUE TITLE
How to get category name by category_id

### ISSUE THREAD

**Issue by myc00** [facebookresearch/detectron2#811]
I used the following code to get the accuracy and category_id,

     instances=predictions["instances"]
     fields=instances._fields
     for x in fields["scores"]:
             print(x)
     for x in fields["pred_classes"]:
             print(x)

this is the result:
   
![2020-02-06 13-42-11屏幕截图](https://user-images.githubusercontent.com/43663596/73909057-876d8100-48e6-11ea-9228-aa1c12d2e533.png)

what should I do to get category name by category_id

**Comment by ppwwyyxx** [comment]
Access `thing_classes` on your dataset. See instructions at https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by myc00** [comment]
> Access `thing_classes` on your dataset. See instructions at https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

Thank you for your reply, but I didn't use the custom datasets, just run the demo. so I want to get the category name of the dataset used in the demo, thanks

**Comment by ppwwyyxx** [comment]
The name of dataset used by the demo is defined by the config file you use, usually `coco_2017_val`.

**Comment by myc00** [comment]
> The name of dataset used by the demo is defined by the config file you use, usually `coco_2017_val`.

Very grateful for your help, it worked, thankyou!
