### ISSUE TITLE
Adding custom area ranges to CocoEvaluator

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#815]
My dataset is in COCO format but the sizes of my objects are quite different from those in MS-COCO dataset. So how could I go about changing the area ranges (0, 32, 96...) in CocoEvaluator? Or do I have to make the change in pycocotools' cocoeval.py to achieve this?

**Comment by ppwwyyxx** [comment]
We do not provide ways to customize options in pycocotools and you may need to do this yourself. It seems it's doable through `cocoeval.params.areaRng`.
