### ISSUE TITLE
Using a custom dataset for Detectron2: can't visualize annotations

### ISSUE THREAD

**Issue by iskode** [facebookresearch/detectron2#816]
Hi everyone,
I’m working on a custom dataset following the [custom dataset  tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) .
I’ve have tested (print out) my image annotations and they are all there but I just see the image without annotation overlays using the instruction in the tutorial. Below is the output of an image I’m trying to visualize the annotations. I showed only the first 10 items of the segmentation key.

> nb of labels : 3
label 0
bbox : [38, 61, 54, 80]
bbox_mode : 0
category_id : 0
iscrowd : 0
segmentation: [63.5, 62.5, 64.5, 61.5, 66.5, 61.5, 67.5, 62.5, 68.5, 61.5]
.....

Some images don’t have my target objects so I set category_id to num_categories (in my case 3) to indicate that this image is only background. Did I really get it correctly from the [docs](https://detectron2.readthedocs.io/tutorials/datasets.html) ?:

> `category_id (int)`: an integer in the range [0, num_categories) representing the category label. The value num_categories is reserved to represent the “background” category, if applicable.

As I work in google colab, I’ve tried to modify the source from my drive where I installed the Detectron2 repo in order to add some print in the `overlay_instances, draw_dataset_dict` methods that overlay the annotations on the image. But nothing appears, only the image appears.

Finally I've installed Detectron2 locally on my PC and tried to add some print in the same methods even raising en exception but it doesn't take effect. So my guess is the repo is not in an editable/developer mode that's why there is no effect. However the CLI instruction is clear:
`pip install -e path/to/repo`. From my weak knowledge -e means --editable. But why nothing happens ?
Am I missing something ??

Thank you in advance.

**Comment by ppwwyyxx** [comment]
It's not clear what you did. 
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Perhaps you didn't see this in https://detectron2.readthedocs.io/tutorials/datasets.html
> annotations (list[dict]): the per-instance annotations of every instance in this image. Each annotation dict may contain:

**Comment by iskode** [comment]
THank you for your timely feedback.
I made tiny dumb error. I forgot to add a "s" at the end of the "annotation**s**" key inside the label.
Now I could see the overlay annotation on my data.
Thank you again.
