### ISSUE TITLE
How to label a complete training image as background (no target exist)

### ISSUE THREAD

**Issue by iskode** [facebookresearch/detectron2#819]
Hi, in my custom dataset, there are images with no target object. As I want my model to be able to correctly assess that there is no target object in images, how can I assign such label it following COCO’s json annotations ?

**My unsuccessful attempt**
I've seen this in the doc:
> `category_id (int)`: an integer in the range [0, num_categories) representing the category label. The value num_categories is reserved to represent the “background” category, if applicable.

For say image IM where, there is no target object, when writing the dataset_dict, I set `category_id (int)` to 3 as in my case (`thing_classes = [cat1, cat2, cat3]`). But I got an error when trying to visualize IM, it raised an exception mentioning that 3 is out of range which normal as `thing_classes` max index is 2. However Detectron2 doesn't use the background as specified in the doc.

Finally, I've added manually 'background' to the thing_classes and set the bbox to []. I got another error as the length must be 4. I don't know where to go then ?

Thus, how could I solve this  ?
I think the solution should be added in the doc to make this subtle situation clear.

Thank you so much.

but don't understand the use case

**Comment by ppwwyyxx** [comment]
Set "annotations" to an empty list.

https://detectron2.readthedocs.io/tutorials/datasets.html#register-a-dataset

**Comment by ppwwyyxx** [comment]
btw, you'll also want `cfg.DATALOADER.FILTER_EMPTY_ANNOTATIONS=False`.
