### ISSUE TITLE
Ablation studies on differences with Detectron1

### ISSUE THREAD

**Issue by goolhanrry** [facebookresearch/detectron2#824]
According to `configs/Detectron1-Comparisons/README.md`, Detectron2 has the following differences in default configs:

* Use scale augmentation during training.
* Use L1 loss instead of smooth L1 loss.
* Use `POOLER_SAMPLING_RATIO=0` instead of 2.
* Use `ROIAlignV2`.

But I doubt whether all these changes have positive effects on the baseline models. Are there any ablation studies on each of these differences? More specifically, I understand that using multi-scale training and `ROIAlignV2` should make sense, but why using L1 loss but not smooth L1 loss and setting `POOLER_SAMPLING_RATIO=0`?

Thank you for your attention :)

**Comment by ppwwyyxx** [comment]
The main reason for using L1 loss is it's simpler. It has some effect on AP described in https://detectron2.readthedocs.io/notes/compatibility.html.

Setting `POOLER_SAMPLING_RATIO=0` is equivalent to "Precise ROIAlign" proposed in https://arxiv.org/abs/1807.11590. By its design, it should more accurately captures all information from a large region. Although we did not observe any difference in accuracy.

**Comment by c1aris** [comment]
Thank you so much!
