### ISSUE TITLE
Cityscapes & PVOC Baselines model license

### ISSUE THREAD

**Issue by klintan** [facebookresearch/detectron2#827]
Cityscapes say this for their license

> This dataset is made freely available to academic and non-academic entities for non-commercial purposes such as academic research, teaching, scientific publications, or personal experimentation. Permission is granted to use the data given that you agree

However in the model zoo Cityscapes & Pascal VOC Baselines model are listed as CC3.0-sharalike, how is this possible? Have you gotten an exception from the "non-commerical" use.

This also leads me to my next question: If I use this model to infer crude annotations for new images (CC0) and then manually fine tuned. Am I free to set the license to CC0 for this new annotated dataset? 

Perhaps the last question is better asked on SO but wanted to start here.

Many thanks in advance, and thanks for all your hard work!

**Comment by ppwwyyxx** [comment]
I don't quite understand what issues you're seeing. I believe our use of cityscapes dataset is for non-commercial purposes and therefore comply with their license.

It's best to consult professionals regarding Interpretation of a license.

**Comment by cygerts** [comment]
However Detectron shares model trained on dataset with non-commercial license, using license that allows commercial usage (CC 3.0) which is a clear conflict. I think it is the most safe not to use those models for commercial purpose.
