### ISSUE TITLE
How to output detections into a text file?

### ISSUE THREAD

**Issue by anzy0621** [facebookresearch/detectron2#830]
Hi all, I'd like to know if there's a way to output the resulting detections into a text file?

**Comment by ppwwyyxx** [comment]
The output format is described in https://detectron2.readthedocs.io/tutorials/models.html#model-output-format.
You can write it to a text file yourself.

**Comment by anzy0621** [comment]
I tried writing the text file but it was empty.

-output vidout.txt was the command I used amongst the others and it did output the mentioned text file but it was just blank.
Any suggestions?
