### ISSUE TITLE
Multiple ROI heads for predicting multiple attributes as in bottom-up attention

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/detectron2#841]
I'm trying to use detectron for predicting not only the bounding box and object label but also for other attributes.

For instance, I'm trying to predict the shape, angle and color of the object as well. 

I looked at the issue #798 #405. It seems that the multi label they are referring to has a similar problem with mine. If a multi label solution is hard to detectron2, is it able to accomodate more than one roi head?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose and https://github.com/facebookresearch/meshrcnn/tree/master/meshrcnn both use detectron2 to predict extra attributes by extending ROIHeads.

The last few slides of https://www.dropbox.com/s/o83efjejx1kfrsy/ICCV19_Detectron2.pdf?dl=0 also describes something similar.

**Comment by ggaemo** [comment]
Thanks for you r help, is the code in the pdf all there is? Are there only snippets of the code?

**Comment by ppwwyyxx** [comment]
The pdf is just a brief tutorial, and real examples are provided in the comment above.

**Comment by amrahsmaytas** [comment]
@ggaemo Are you able to find out the solution for multilabel?
