### ISSUE TITLE
How to evaluate coco 80 categories with lvis annotations?

### ISSUE THREAD

**Issue by zzzzzz0407** [facebookresearch/detectron2#845]
Just like the evaluation in PointRend ? Thanks very much!

**Comment by ppwwyyxx** [comment]
We generate a new json for COCO evaluation using data from lvis annotations.
We will later release code for it.

**Comment by zzzzzz0407** [comment]
Thanks very much. I try to generate myself, however, I find that the file [(https://github.com/lvis-dataset/lvis-api/blob/master/data/coco_to_synset.json)] cannot match well with the lvis categories in detectron2.
e.g. the oven.n.01 in coco_to_synset.json cannot match the category in lvis category.
Could you please release code as soon as possible.
Thanks very much.
