### ISSUE TITLE
PointRend Semantic Segmentation

### ISSUE THREAD

**Issue by bluesky314** [facebookresearch/detectron2#846]
When will the semantic segmentation of PointRend model be uploaded? Really looking forward to it

**Comment by bluesky314** [comment]
@ppwwyyxx Is it coming any time soon?

**Comment by bluesky314** [comment]
@ppwwyyxx any update? Its been over a month

**Comment by bluesky314** [comment]
@ppwwyyxx Any update??

**Comment by bluesky314** [comment]
@ppwwyyxx

**Comment by Eason270** [comment]
When will the code of  PointRend for semantic segmentation  be uploaded?

**Comment by Venka97** [comment]
@ppwwyyxx Any update on this.

**Comment by alexander-kirillov** [comment]
We've finally released code for semantic segmentation under the same `detectron2/projects` as instance segmentation.

**Comment by bluesky314** [comment]
💯
