### ISSUE TITLE
Install Permanently Detectron2 in Colab

### ISSUE THREAD

**Issue by chho-work** [facebookresearch/detectron2#851]
Thanks for making Mask RCNN and object detection easy for us! 

I would like to know if there is a procedure or if it is possible at all, to install Detectron2 permanently in Colab(or in Gdrive), so that we don't have to build it again each time we resume work.
 
Perhaps this is not a Detectron2 issue or a feature that you can implement.  However, if it can be implemented, it would help those, like me, who uses Colab in day to day work. 

Many thanks!

**Comment by ppwwyyxx** [comment]
You do not have to build it each time if you look at our latest colab.

And this is not a detectron2 issue. You may ask people who are familiar with colab, or google for help.
