### ISSUE TITLE
How to get classwise/category-wise map(precisions) on eval dataset?

### ISSUE THREAD

**Issue by Siddsouza19** [facebookresearch/detectron2#855]
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by cpoptic** [comment]
Yes, I second this also.
For smaller size object categories (e.g. potted plant or notebook in the COCO dataset), the model's AP will likely be smaller than the AP for larger sized objects (e.g. car, truck).

Therefore, how can we adjust the cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST  threshold on a per-class basis?  Thanks

**Comment by ppwwyyxx** [comment]
`COCOEvaluator` already provides per-class AP.

I don't think setting a per-class threshold is useful for evaluation given how AP is calculated.
If you want a per-class threshold for inference (which is common) you can implement that by processing the output.
