### ISSUE TITLE
AttributeError: 'PolygonMasks' object has no attribute 'tensor'

### ISSUE THREAD

**Issue by TengFeiHan0** [facebookresearch/detectron2#856]
when excuting this below command,

```
masks_ori = targets_per_im.gt_masks.device(locations.device)
masks_ori = masks_ori.permute(1, 2, 0) # h, w, n

```
I got an error,

```
File detectron2/detectron2/structures/masks.py", line 279, in device
    return self.tensor.device
AttributeError: 'PolygonMasks' object has no attribute 'tensor'
```
then I tried to use another function
`masks_ori = targets_per_im.gt_masks.to(device=locations.device)`
but it returns a different problem when running this line,` masks_ori = masks_ori.permute(1, 2, 0) # h, w, n`
`AttributeError: 'PolygonMasks' object has no attribute 'permute'`
It seems like our masks_ori is not a tensor. So how to transform a polygonMasks object into a tensor? thank you in advance.

**Comment by ppwwyyxx** [comment]
thanks, this is a bug. However the device for `PolygonMasks` should always be `torch.device('cpu')` so you can use it instead.

**Comment by TengFeiHan0** [comment]
@ppwwyyxx  I'm so sorry to trouble you again and leave a comment on a closed issue. 
why the device for `PolygonMasks` should always be `torch.device('cpu')`? if possible, could you give me some cues? if `PolygonMasks` is not a tensor, the following operations, such as `permute()`, `mask.shape`, become meaningless.  how to solve the new arising problem? probably `BitMasks` is an alternative for `PolygonMasks`?

**Comment by ppwwyyxx** [comment]
`.device` is just to provide a similar interface to tensor/BitMasks - although it's not a tensor - so that the same code that uses `.device` can work on all three common types of mask representation.

**Comment by TengFeiHan0** [comment]
if `mask `is an object of PolygonMasks, what I want to do is acquire its shape, like `n, h, w = mask.shape`  then I got an error `'PolygonMasks' object has no attribute 'shape'`, which means shape operation for  `PolygonMasks `is prohibited. So where am I wrong? thank you in advance.

**Comment by ppwwyyxx** [comment]
There is no `shape` attribute.
If you want to get the BitMask representation of a PolygonMask, you need https://detectron2.readthedocs.io/modules/structures.html#detectron2.structures.BitMasks.from_polygon_masks
