### ISSUE TITLE
Detectron2 custom  data augumentation

### ISSUE THREAD

**Issue by nikky4222** [facebookresearch/detectron2#857]
Hello,

I have implemented a custom mapper and passed the mapper as below
class CustomDatasetMapper1(DatasetMapper):
    def __call__(self, dataset_dict):
        dataset_dict = copy.deepcopy(dataset_dict)
        
        out1=convert1(dataset_dict['annotations'])
        out1=np.asarray(out1)
        img = cv2.imread(dataset_dict['file_name'])[:,:,::-1]
        img, bboxes= Resize(224)(img.copy(), out1.copy())
        if np.random.random()>0.5:
            seq=Sequence([RandomHorizontalFlip()])
            img_, bboxes_ = seq(img.copy(), bboxes.copy())
        else:
            seq=Sequence([RandomRotate(10)])
            img_, bboxes_ = seq(img.copy(), bboxes.copy())
        dataset_dict["image"] = torch.as_tensor(img_.transpose(2, 0, 1).astype("float32"))
        convert_inplace(dataset_dict,bboxes_)
        instances = utils.annotations_to_instances(dataset_dict['annotations'], img_.shape[:2])
        dataset_dict["instances"] = utils.filter_empty_instances(instances)
        dataset_dict.pop("annotations", None)
        return dataset_dict

class Trainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name= "NIKE_train"):
        output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        evaluators = [COCOEvaluator(dataset_name, cfg, True, output_folder)]
        if cfg.MODEL.DENSEPOSE_ON:
            evaluators.append(DensePoseCOCOEvaluator(dataset_name, True, output_folder))
        return DatasetEvaluators(evaluators)

    @classmethod
    def build_test_loader(cls, cfg, dataset_name):
        return build_detection_test_loader(cfg, dataset_name, mapper= CustomDatasetMapper1(cfg, False))
    
    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg,mapper=CustomDatasetMapper1(cfg))

where RandomHorizontalFlip() and  RandomRotate(10) are custom functions used to perform data augumentation.But when I run the model it displays
02/12 13:35:01 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
and I dont see my custom augmentations mentioned here

**Comment by ppwwyyxx** [comment]
The `__init__` method of `DatasetMapper`, which you did not overwrite, created the old transforms and printed the above logs. Although the transforms it created is not used in `__call__`.

**Comment by nikky4222** [comment]
so you are telling that the argumentation has been applied but since the __init__ isn't overwritten it is showing the defaults?

**Comment by ppwwyyxx** [comment]
Yes.

**Comment by nikky4222** [comment]
Hi,

I tied implementing the __init__ but can you please let me know why am I still seeing the message with default argumentation.

class CustomDatasetMapper1(DatasetMapper):
    def __init__(self, cfg, is_train=True):
        print("yooooooooooooooo")
       
        self.tfm = Sequence([Resize(224),RandomHorizontalFlip(),RandomRotate(10)])
        self.is_train = is_train
    def __call__(self, dataset_dict):
        dataset_dict = copy.deepcopy(dataset_dict)
        
        out1=convert1(dataset_dict['annotations'])
        out1=np.asarray(out1)
        img = cv2.imread(dataset_dict['file_name'])[:,:,::-1]
        img_, bboxes_=  self.tfm(img.copy(), out1.copy())
        print("imgggg",img_.shape)
        #if np.random.random()>0.5:
         #   seq=Sequence([RandomHorizontalFlip()])
          #  img_, bboxes_ = seq(img.copy(), bboxes.copy())
        #else:
         #   seq=Sequence([RandomRotate(10)])
          #  img_, bboxes_ = seq(img.copy(), bboxes.copy())
        dataset_dict["image"] = torch.as_tensor(img_.transpose(2, 0, 1).astype("float32"))
        convert_inplace(dataset_dict,bboxes_)
        instances = utils.annotations_to_instances(dataset_dict['annotations'], img_.shape[:2])
        dataset_dict["instances"] = utils.filter_empty_instances(instances)
        dataset_dict.pop("annotations", None)
        return dataset_dict

I still see
02/13 21:34:29 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[02/13 21:34:29 d2.data.build]: Using training sampler TrainingSampler

**Comment by ppwwyyxx** [comment]
Then you're not calling your CustomDatasetMapper1

**Comment by nikky4222** [comment]
![image](https://user-images.githubusercontent.com/21250932/74499945-f29cf180-4eaa-11ea-8205-4a6251df4a15.png)

I am calling it.

**Comment by ppwwyyxx** [comment]
If you don't see "yooooooooooooo" then you're not calling it -- this is what you should expect from the Python language so I'm not the person to help with it.

If you see both "yooooooooooooo" and "TransformGens used in training:" then you called `DatasetMapper` in some other places.

**Comment by nikky4222** [comment]
I can see Yoo and I see transformations being applied in data_dict.But while running it I see the defaults being printed out.
