### ISSUE TITLE
sizeMismatch error

### ISSUE THREAD

**Issue by morestart** [facebookresearch/detectron2#863]
when i use custom data to run a official demo, i got sizeMisMatch error, I annotate my data with rectlabel, and export to coco json data.
```
ERROR [02/13 14:51:15 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 208, in run_step
    data = next(self._data_loader_iter)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 109, in __iter__
    for d in self.dataset:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
detectron2.data.detection_utils.SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/dataset_mapper.py", line 76, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py", line 87, in check_image_size
    expected_wh,
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image /content/data/Images/130.jpg, got (3264, 2448), expect (2448, 3264)
```

**Comment by morestart** [comment]
(W,H), but  (3264, 2448) is correct width and height, i dont't know why have this problem

**Comment by morestart** [comment]
this is my train code
```
from detectron2 import model_zoo
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.utils.logger import setup_logger
import os
setup_logger()




cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("fruits_nuts",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Comment by ppwwyyxx** [comment]
We use Pillow to read the image: https://github.com/facebookresearch/detectron2/blob/e41931e3087737d4c22de077b4437a8e9ec25921/detectron2/data/detection_utils.py#L49-L55
and transpose it (flip its x and y) if it has rotation flag.

So the error you're seeing means either of the two:

1. your annotation is wrong. The image has rotation information but not in the annotation
2. Pillow is wrong. In which case you should find the image and report to Pillow.

**Comment by ryouchinsa** [comment]
Hi, 

RectLabel and macOS Viewer show images with Exif orientation flags in the same way.
According to the Exif orientation flag, each image is rotated and shown in the front orientation.

So that the annotation file on RectLabel assume that the image is rotated and shown in the front orientation.

EXIF Orientation-flag example images
https://github.com/recurser/exif-orientation-examples

EXIF Orientation Handling Is a Ghetto
https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

Best regards,
Ryo

**Comment by zlszhonglongshen** [comment]
所以这个问题该怎么解决呀？ 标注文件没有错呢

**Comment by zlszhonglongshen** [comment]
> this is my train code
> 
> ```
> from detectron2 import model_zoo
> from detectron2.engine import DefaultTrainer
> from detectron2.config import get_cfg
> from detectron2.utils.logger import setup_logger
> import os
> setup_logger()
> 
> 
> 
> 
> cfg = get_cfg()
> cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> cfg.DATASETS.TRAIN = ("fruits_nuts",)
> cfg.DATASETS.TEST = ()
> cfg.DATALOADER.NUM_WORKERS = 2
> cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> cfg.SOLVER.IMS_PER_BATCH = 2
> cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> 
> os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> trainer = DefaultTrainer(cfg) 
> trainer.resume_or_load(resume=False)
> trainer.train()
> ```



> this is my train code
> 
> ```
> from detectron2 import model_zoo
> from detectron2.engine import DefaultTrainer
> from detectron2.config import get_cfg
> from detectron2.utils.logger import setup_logger
> import os
> setup_logger()
> 
> 
> 
> 
> cfg = get_cfg()
> cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> cfg.DATASETS.TRAIN = ("fruits_nuts",)
> cfg.DATASETS.TEST = ()
> cfg.DATALOADER.NUM_WORKERS = 2
> cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> cfg.SOLVER.IMS_PER_BATCH = 2
> cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> 
> os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> trainer = DefaultTrainer(cfg) 
> trainer.resume_or_load(resume=False)
> trainer.train()
> ```

请问你解决了吗？

**Comment by morestart** [comment]
> > this is my train code
> > ```
> > from detectron2 import model_zoo
> > from detectron2.engine import DefaultTrainer
> > from detectron2.config import get_cfg
> > from detectron2.utils.logger import setup_logger
> > import os
> > setup_logger()
> > 
> > 
> > 
> > 
> > cfg = get_cfg()
> > cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> > cfg.DATASETS.TRAIN = ("fruits_nuts",)
> > cfg.DATASETS.TEST = ()
> > cfg.DATALOADER.NUM_WORKERS = 2
> > cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> > cfg.SOLVER.IMS_PER_BATCH = 2
> > cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> > cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> > cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> > cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> > 
> > os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> > trainer = DefaultTrainer(cfg) 
> > trainer.resume_or_load(resume=False)
> > trainer.train()
> > ```
> 
> > this is my train code
> > ```
> > from detectron2 import model_zoo
> > from detectron2.engine import DefaultTrainer
> > from detectron2.config import get_cfg
> > from detectron2.utils.logger import setup_logger
> > import os
> > setup_logger()
> > 
> > 
> > 
> > 
> > cfg = get_cfg()
> > cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> > cfg.DATASETS.TRAIN = ("fruits_nuts",)
> > cfg.DATASETS.TEST = ()
> > cfg.DATALOADER.NUM_WORKERS = 2
> > cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> > cfg.SOLVER.IMS_PER_BATCH = 2
> > cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> > cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> > cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> > cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> > 
> > os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> > trainer = DefaultTrainer(cfg) 
> > trainer.resume_or_load(resume=False)
> > trainer.train()
> > ```
> 
> 请问你解决了吗？

先看下图像有没有EXIF信息，后来使用rectlabel后，标注的图像不是带有exif信息的手机拍摄的就没有这个错误了

**Comment by zlszhonglongshen** [comment]
> > > this is my train code
> > > ```
> > > from detectron2 import model_zoo
> > > from detectron2.engine import DefaultTrainer
> > > from detectron2.config import get_cfg
> > > from detectron2.utils.logger import setup_logger
> > > import os
> > > setup_logger()
> > > 
> > > 
> > > 
> > > 
> > > cfg = get_cfg()
> > > cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> > > cfg.DATASETS.TRAIN = ("fruits_nuts",)
> > > cfg.DATASETS.TEST = ()
> > > cfg.DATALOADER.NUM_WORKERS = 2
> > > cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> > > cfg.SOLVER.IMS_PER_BATCH = 2
> > > cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> > > cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> > > cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> > > cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> > > 
> > > os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> > > trainer = DefaultTrainer(cfg) 
> > > trainer.resume_or_load(resume=False)
> > > trainer.train()
> > > ```
> > 
> > 
> > > this is my train code
> > > ```
> > > from detectron2 import model_zoo
> > > from detectron2.engine import DefaultTrainer
> > > from detectron2.config import get_cfg
> > > from detectron2.utils.logger import setup_logger
> > > import os
> > > setup_logger()
> > > 
> > > 
> > > 
> > > 
> > > cfg = get_cfg()
> > > cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
> > > cfg.DATASETS.TRAIN = ("fruits_nuts",)
> > > cfg.DATASETS.TEST = ()
> > > cfg.DATALOADER.NUM_WORKERS = 2
> > > cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
> > > cfg.SOLVER.IMS_PER_BATCH = 2
> > > cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
> > > cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
> > > cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
> > > cfg.MODEL.ROI_HEADS.NUM_CLASSES = 10  # only has one class (ballon)
> > > 
> > > os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
> > > trainer = DefaultTrainer(cfg) 
> > > trainer.resume_or_load(resume=False)
> > > trainer.train()
> > > ```
> > 
> > 
> > 请问你解决了吗？
> 
> 先看下图像有没有EXIF信息，后来使用rectlabel后，标注的图像不是带有exif信息的手机拍摄的就没有这个错误了

那好奇怪啊，只能用rectlabel吗？

**Comment by morestart** [comment]
> > > 
> > > 
> > > 请问你解决了吗？
> > 
> > 
> > 先看下图像有没有EXIF信息，后来使用rectlabel后，标注的图像不是带有exif信息的手机拍摄的就没有这个错误了
> 
> 那好奇怪啊，只能用rectlabel吗？
应该不是，只要是coco格式的标注数据 应该都是可以的吧

**Comment by zlszhonglongshen** [comment]
> > > > 请问你解决了吗？
> > > 
> > > 
> > > 先看下图像有没有EXIF信息，后来使用rectlabel后，标注的图像不是带有exif信息的手机拍摄的就没有这个错误了
> > 
> > 
> > 那好奇怪啊，只能用rectlabel吗？
> 
> 应该不是，只要是coco格式的标注数据 应该都是可以的吧

是呀 我是coco格式，我在mask-RCNN上没问题。但是换到这里就不行了

**Comment by morestart** [comment]
你用的什么标注工具呀，我试试

**Comment by zlszhonglongshen** [comment]
> 你用的什么标注工具呀，我试试


[new.json.txt](https://github.com/facebookresearch/detectron2/files/4632978/new.json.txt)

**Comment by zlszhonglongshen** [comment]
> > 你用的什么标注工具呀，我试试
> 
> [new.json.txt](https://github.com/facebookresearch/detectron2/files/4632978/new.json.txt)

这是我的json文件，你看下
