### ISSUE TITLE
Custom model export methodology

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#865]
If we want to export a custom model built in detectron2, do we have to write corresponding caffe2 versions of the blocks in order to utilise the caffe2 converter?

For example, if my model has custom FPN and ROI Pooler modules, should I build new Caffe2 versions of it ? What is the recommended method for custom exports or is there no formal way for it yet?

**Comment by ppwwyyxx** [comment]
It depends on whether the ops used in your custom model is already supported.

For example, code in `detectron2/export` does nothing about FPN because FPN only has standard ops like convolution - therefore already supported by caffe2.
Code in `detectron2/export` handles ROIPooling differently because it uses operators that do not map directly to caffe2.

**Comment by ashnair1** [comment]
Ok, so if I wanted to export a custom model with a custom RoI Pooler, I would have to:
1. Write a caffe2 version of it (Caffe2CustomROIPooler)
2. Pass it to `export/patcher.py` so that the caffe2_converter would replace instances of RoIPooler with the caffe2 versions of it like below:

In `export/c10.py`
```
# Write Caffe2 version of custom pooler
class Caffe2CustomROIPooler(Caffe2Compatible, poolers.ROIPooler):
................
...............
```
In `export/patcher.py`
```
from .c10 import CaffeCustomROIPooler

# Specify for the custom pooler to be utilised while patching model for export
def patch_generalized_rcnn(model):
    ccc = Caffe2CompatibleConverter
    model = patch(model, rpn.RPN, ccc(Caffe2RPN))
    #model = patch(model, poolers.ROIPooler, ccc(Caffe2ROIPooler))
    model = patch(model, poolers.ROIPooler, ccc(Caffe2CustomROIPooler))
    return model
```

Would that be a possible workflow?

**Comment by ppwwyyxx** [comment]
Yes

**Comment by ashnair1** [comment]
On a side note, wouldn't this approach go against detectron2's design ? Shouldn't the detectron2 library be separate from the projects that use it? We wouldn't want our projects to be a part of detectron2 just so it can be exported.  So instead of manually modifying the scripts in the `export` folder to add Caffe2 versions of custom RPNs and Poolers, wouldn't it be better to have a registry for these as well?

**Comment by ppwwyyxx** [comment]
At Facebook we do not have the need to deploy any models that's not yet mapped to caffe2 by `detectron2/export/`. The types of models that are considered practically useful for our deployment are very few and evolve much slower.
So you're right that it can be improved but this isn't a major issue we're concerned with. For now you can pass your implementation of caffe2 compatible model to `caffe2_export.export_caffe2_detection_model()`, which would solve most of the problems I think.
