### ISSUE TITLE
Failed to load OpenCL runtime

### ISSUE THREAD

**Issue by choasup** [facebookresearch/detectron2#87]
Although it can train successfully, but does anyone know how can I solve the bug?

## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.

`
Failed to load OpenCL runtime
Command Line Args: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', dist_url='tcp://127.0.0.1:49152', eval_only=False, machine_rank=0, num_gpus=8, num_machines=1, opts=
[], resume=False)
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Failed to load OpenCL runtime
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[10/16 06:32:13 detectron2]: Rank of current process: 0. World size: 8
[10/16 06:32:13 detectron2]: Environment info:
---------------------  --------------------------------------------------
Python                 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
Detectron2 Compiler    GCC 7.4
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0
PyTorch Debug Build    False
CUDA available         True
GPU 0,1,2,3,4,5,6,7    Tesla P40
Pillow                 6.2.0
cv2                    3.2.0
`

**Comment by ppwwyyxx** [comment]
`Failed to load OpenCL runtime` is expected and is not a bug.

**Comment by ppwwyyxx** [comment]
The annoying message will disappear if you use opencv>=3.4 (see https://github.com/tensorpack/tensorpack/issues/502)

**Comment by choasup** [comment]
nice!
