### ISSUE TITLE
Detectron2 - minimum hardware requirements

### ISSUE THREAD

**Issue by przemb** [facebookresearch/detectron2#873]
Hi, 
I tried to repeat steps from Detectron tutorial locally:
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=7unkuuiqLdqd

I have a problem with below line:
```trainer.train()```

Is is possible to fine tune pretrained model with old GPU card? ( <8 GB)
I tried different values for below parameters:
```
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128 
```
but all the time I am getting error releated to lack of memory... (I made sure that before each execution of _train()_ my memory was free...)
Could you tell me what are minimum hardware requirements of detectron2?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md has memory requirements
