### ISSUE TITLE
How to import Caffe2 model with device 'gpu'

### ISSUE THREAD

**Issue by zetyquickly** [facebookresearch/detectron2#874]
Hello,

I've been investigating the `detectron2/export` functionality and find out that there are options for exporting model to `device == 'gpu'` but the only way to export model using API is to use `cuda` as a parameter.

Is there a way to export model with GPU backend with `device == 'gpu'`?

**Comment by zetyquickly** [comment]
The purpose is to use it on mobile GPU

**Comment by ppwwyyxx** [comment]
Mobile GPUs are not supported

**Comment by zetyquickly** [comment]
Hi, @ppwwyyxx 
I've noticed some activity inside the `export` submodule. May enabling of `model.to(device)` lead to mobile GPU utilisation?

**Comment by ppwwyyxx** [comment]
No. There will not be mobile GPU support in the foreseeable future
