### ISSUE TITLE
Can detectron use in the detection in deepsort?

### ISSUE THREAD

**Issue by yustaub** [facebookresearch/detectron2#878]
## ❓ How to use Detectron2

How to do the detection in deepsort with detectron2?

I want to change the detector(yolov3) in deepsort with the detectron2, can detectron use in the detection in deepsort?

**Comment by ppwwyyxx** [comment]
I do not know what deepsort needs, so I cannot answer. This is not a detectron2 question.

**Comment by pvtien96** [comment]
@yustaub hey, have you done these experiments? detectron with deepsort?
