### ISSUE TITLE
WEIGHT_DECAY_NORM seems useless

### ISSUE THREAD

**Issue by kakaluote** [facebookresearch/detectron2#881]
i set breakpoint at here https://github.com/facebookresearch/detectron2/blob/5d452a0ec0b8bc21e61c6cb4cfef34ef7fefdb90/detectron2/solver/build.py#L40
it seems the 'if' never passed.

**Comment by ppwwyyxx** [comment]
That just means your model doesn't have a module in `norm_module_types`:
https://github.com/facebookresearch/detectron2/blob/5d452a0ec0b8bc21e61c6cb4cfef34ef7fefdb90/detectron2/solver/build.py#L39
