### ISSUE TITLE
How to debug with detectron2 under multi-GPU distributed mode?

### ISSUE THREAD

**Issue by Ze-Yang** [facebookresearch/detectron2#882]
How to debug with detectron2 under multi-GPU distributed mode? I can debug it with pycharm under single GPU mode, but when it comes to multi-GPU, it just gets stuck as the below picture shows. Could you advise? Thanks.
![image](https://user-images.githubusercontent.com/42920710/74618384-7df8da00-516c-11ea-8ed6-1930ae90c214.png)

**Comment by ppwwyyxx** [comment]
If the same code runs well without pycharm, that sounds like pycharm unable to debug multiple processes, which you need to ask pycharm for support.

**Comment by guotong1988** [comment]
Thank you. I just want to debug detectron2.

**Comment by trevor-taeyeop** [comment]
@guotong1988, Have you soloved this part??
