### ISSUE TITLE
Can I implement Detectron model into Detectron 2?

### ISSUE THREAD

**Issue by herruli** [facebookresearch/detectron2#883]
Hi, I saw a custom Detectron model which I want to try to implement it into Detectron 2. I just want to know whether Detectron model and config files are run  in Detectron2? Thanks

The custom model I would like to use
https://github.com/doc-analysis/TableBank/blob/master/MODEL_ZOO.md

**Comment by ppwwyyxx** [comment]
The config files and models are not compatible.
Explained in https://detectron2.readthedocs.io/notes/compatibility.html
