### ISSUE TITLE
Keypoint Detector detects Birds and classifies them as Humans

### ISSUE THREAD

**Issue by lagidigu** [facebookresearch/detectron2#889]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

I used the same settings as outlined in the '[Other types of builtin models](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=GYJrlXZC5M-J)' section, and visualized the results.  

1. what changes you made (`git diff`) or what code you wrote

```
im = cv2.imread(bird_img_path)
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7  # set threshold for this model
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
v = Visualizer(im[:,:,::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(v.get_image()[:, :, ::-1])
```

2. what exact command you run:
See above.

3. what you observed (including the full logs):

`outputs['instances'].pred_classes.numpy()` returns 0, which is the class index for 'persons'. 

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

Sample image can be found [here](https://previews.123rf.com/images/nukie13/nukie131412/nukie13141200005/34221343-bird-flying-on-a-sunny-day.jpg), for example.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

There should either be nothing detected, or the class should be animal or bird...

**Comment by ppwwyyxx** [comment]
Keypoint detectors can only detect human.
No model is perfect. This is not an unexpected issue, therefore closing.
