### ISSUE TITLE
How to fine-tune on previously saved model w/o loading other checkpointables

### ISSUE THREAD

**Issue by ad12** [facebookresearch/detectron2#891]
## ❓ How to use Detectron2
Currently when `MODEL.WEIGHTS` is specified, the trainer loads weights into the model as well as re-loads checkpoints for other checkpointables (`num_iter`, `scheduler`, etc.).

Is there a standard way to load only the weights into the model without loading other checkpointables?

**Comment by ppwwyyxx** [comment]
Duplicate of https://github.com/facebookresearch/detectron2/issues/771
