### ISSUE TITLE
custom dataset and custom train_net.py runtime error

### ISSUE THREAD

**Issue by servercalap** [facebookresearch/detectron2#893]
I get this error when I run mask rcnn resnet50 model in my own dataset. What would be the reason?

02/17 21:54:35 d2.checkpoint.c2_model_loading]: The checkpoint contains parameters not used by the model:
  fc1000_b
  fc1000_w
  conv1_b
[02/17 21:54:35 d2.engine.train_loop]: Starting training from iteration 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "train_mask_demo.py", line 170, in <module>
    args=(args,),
  File "/home/rem_vision/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/rem_vision/detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/rem_vision/train_mask_demo.py", line 158, in main
    return trainer.train()
  File "/home/rem_vision/detectron2/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/rem_vision/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/rem_vision/detectron2/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rem_vision/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 129, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rem_vision/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 586, in forward
    losses = self._forward_box(features_list, proposals)
  File "/home/rem_vision/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 646, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rem_vision/detectron2/detectron2/modeling/poolers.py", line 233, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rem_vision/detectron2/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/rem_vision/detectron2/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: Not compiled with GPU support (ROIAlign_forward at /home/rem_vision/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign.h:73)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f2df2018627 in /home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: detectron2::ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0x16a (0x7f2ddcc2835a in /home/rem_vision/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1fb55 (0x7f2ddcc37b55 in /home/rem_vision/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1fc7e (0x7f2ddcc37c7e in /home/rem_vision/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1a5c0 (0x7f2ddcc325c0 in /home/rem_vision/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #5: _PyMethodDef_RawFastCallKeywords + 0x264 (0x556910210114 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #6: _PyCFunction_FastCallKeywords + 0x21 (0x556910210231 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x4e9d (0x556910274a5d in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #8: _PyFunction_FastCallDict + 0x10b (0x5569101ca73b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #9: THPFunction_apply(_object*, _object*) + 0xa0f (0x7f2e1daeba1f in /home/rem_vision/anaconda3/envs/torch_p37/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: _PyMethodDef_RawFastCallKeywords + 0x1e0 (0x556910210090 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #11: _PyCFunction_FastCallKeywords + 0x21 (0x556910210231 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x4764 (0x556910274324 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #13: _PyFunction_FastCallDict + 0x10b (0x5569101ca73b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #15: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #18: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #19: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #20: <unknown function> + 0x17512a (0x55691022412a in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #21: _PyObject_FastCallKeywords + 0x48b (0x55691022518b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x4a66 (0x556910274626 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #23: _PyFunction_FastCallDict + 0x10b (0x5569101ca73b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #24: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #25: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #27: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #28: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #29: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #30: <unknown function> + 0x17512a (0x55691022412a in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #31: _PyObject_FastCallKeywords + 0x48b (0x55691022518b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x52cf (0x556910274e8f in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #33: _PyFunction_FastCallKeywords + 0xfb (0x55691020f68b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x4b09 (0x5569102746c9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #35: _PyEval_EvalCodeWithName + 0xc30 (0x5569101ca030 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #36: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #37: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #38: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #39: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #40: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #41: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #42: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #43: <unknown function> + 0x17512a (0x55691022412a in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #44: _PyObject_FastCallKeywords + 0x48b (0x55691022518b in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x52cf (0x556910274e8f in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #46: _PyEval_EvalCodeWithName + 0xc30 (0x5569101ca030 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #47: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #48: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #49: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #50: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #51: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #52: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #53: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)

frame #54: <unknown function> + 0x17512a (0x55691022412a in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #55: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #56: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #57: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #58: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #59: _PyObject_Call_Prepend + 0x63 (0x5569101e5943 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #60: PyObject_Call + 0x6e (0x5569101d8b9e in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #61: _PyEval_EvalFrameDefault + 0x1e35 (0x5569102719f5 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #62: _PyEval_EvalCodeWithName + 0x2f9 (0x5569101c96f9 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)
frame #63: _PyFunction_FastCallDict + 0x1d5 (0x5569101ca805 in /home/rem_vision/anaconda3/envs/torch_p37/bin/python)

pytorch --v :1.4
cuda --v : 9.2

Would you share any thoughts on the matter? It would help me a lot.
Thank you very much!

**Comment by ppwwyyxx** [comment]
As the error says: "RuntimeError: Not compiled with GPU support".

See https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by servercalap** [comment]
it runs , thank you @ppwwyyxx
