### ISSUE TITLE
Which parameters determine the input shape of the forward pass of the box head?

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#895]
Just to make sure that I understand this correctly:

The input shape of `x` in `detectron2.modeling.roi_heads.box_head.FastRCNNConvFCHead.forward` is `[m, c, p, p]`.

`p` is the pooler resolution (`cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION`)
`c` is the number of output channels of the Feature Pyramid Network (`cfg.MODEL.FPN.OUT_CHANNELS`)
`m` is the number of ROI in the image and is calculated as follows:

`m = cfg.SOLVER.IMS_PER_BATCH * cfg.RPN.BATCH_SIZE_PER_IMAGE * 2`

Is this correct? If so: Where does this factor 2 come from?

Thanks.

**Comment by ppwwyyxx** [comment]
> m = cfg.SOLVER.IMS_PER_BATCH * cfg.RPN.BATCH_SIZE_PER_IMAGE * 2

It should be `SOLVER.IMS_PER_BATCH * MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE`.

**Comment by maxfrei750** [comment]
Ok, that makes sense. However, from my perspective, it has to be:

`SOLVER.IMS_PER_BATCH * MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE * MODEL.ROI_HEADS.POSITIVE_FRACTION`

Do you agree?

**Comment by ppwwyyxx** [comment]
> SOLVER.IMS_PER_BATCH * MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE * MODEL.ROI_HEADS.POSITIVE_FRACTION
Do you agree?

Actually not, because the box head takes both positives and negatives as inputs.

**Comment by maxfrei750** [comment]
What confuses me is that when I train a Mask R-CNN with the following properties:
`SOLVER.IMS_PER_BATCH = 20`
`MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512` (default)
`MODEL.ROI_HEADS.POSITIVE_FRACTION = 0.25` (default)

I get a shape of `[2560, 256, 7, 7]` for `x` in `detectron2.modeling.roi_heads.box_head.FastRCNNConvFCHead.forward`.

**Comment by ppwwyyxx** [comment]
I don't think that will happen if you use a single GPU.

**Comment by maxfrei750** [comment]
Ugh... of course! 🤦‍♂ 

So it's actually `SOLVER.IMS_PER_BATCH * MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE / num_gpus`.

Thanks for clearing that up. 👍
