### ISSUE TITLE
total_loss is stuck between 0.100-0.180 while training custom coco model

### ISSUE THREAD

**Issue by bamwani** [facebookresearch/detectron2#896]
![Screenshot from 2020-02-18 18-22-09](https://user-images.githubusercontent.com/20405602/74739080-28145700-527e-11ea-84a5-6ebb8fb05205.png)
I'm training a custom coco model for single class. Used 4k images. but total loss is stuck between 0.100-0.180 even after 3000 iterations. Although total_loss reached 0.100 at 1000 iterations.

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
