### ISSUE TITLE
ValueError: loaded state dict has a different number of parameter groups

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#898]
I'm just trying to resume training from a trained weight.

code :

`    """cfg = get_cfg()

    cfg.MODEL.WEIGHTS = "/remote/samjit/detectron2/checkpoints/model_final.pth"
    cfg.merge_from_list(args.opts)
    cfg.DATASETS.TRAIN = ("train", )
    cfg.DATASETS.TEST = ("val", )
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.0025
    cfg.SOLVER.WEIGHT_DECAY = 0.00015
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
    cfg.SOLVER.MAX_ITER =1000
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128 
    cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[8,16,32,64,128, 256, 320, 448, 512]]

    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg) 
    trainer.resume_or_load(resume=True)
    trainer.train() 

**Error**

```
[02/18 18:24:44 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(800,), max_size=1333, sample_style='choice'), RandomFlip()]
[02/18 18:24:44 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(800,), max_size=1333, sample_style='choice'), RandomFlip()]
[02/18 18:24:44 d2.data.build]: Using training sampler TrainingSampler
[02/18 18:24:44 d2.data.build]: Using training sampler TrainingSampler
[02/18 18:24:44 fvcore.common.checkpoint]: Loading checkpoint from /remote/samjith/detectron2/vovnet-detectron2/checkpoints/model_final.pth
WARNING [02/18 18:24:44 fvcore.common.checkpoint]: 'proposal_generator.rpn_head.conv.weight' has shape (256, 256, 3, 3) in the checkpoint but (1024, 1024, 3, 3) in the model! Skipped.
WARNING [02/18 18:24:44 fvcore.common.checkpoint]: 'proposal_generator.rpn_head.conv.bias' has shape (256,) in the checkpoint but (1024,) in the model! Skipped.
WARNING [02/18 18:24:45 fvcore.common.checkpoint]: 'proposal_generator.rpn_head.objectness_logits.weight' has shape (27, 256, 1, 1) in the checkpoint but (27, 1024, 1, 1) in the model! Skipped.
WARNING [02/18 18:24:45 fvcore.common.checkpoint]: 'proposal_generator.rpn_head.anchor_deltas.weight' has shape (108, 256, 1, 1) in the checkpoint but (108, 1024, 1, 1) in the model! Skipped.
WARNING [02/18 18:24:45 fvcore.common.checkpoint]: 'roi_heads.box_predictor.cls_score.weight' has shape (2, 1024) in the checkpoint but (2, 2048) in the model! Skipped.
WARNING [02/18 18:24:45 fvcore.common.checkpoint]: 'roi_heads.box_predictor.bbox_pred.weight' has shape (4, 1024) in the checkpoint but (4, 2048) in the model! Skipped.
[02/18 18:24:45 fvcore.common.checkpoint]: Some model parameters are not in the checkpoint:
```

```
>:[02/18 18:24:45 fvcore.common.checkpoint]: Loading optimizer from /remote/samjith/detectron2/checkpoints/model_final.pth
> Traceback (most recent call last):
>   File "train.py", line 85, in <module>
>     trainer.resume_or_load(resume=True)
>   File "/home/detectron2/detectron2/engine/defaults.py", line 279, in resume_or_load
>     self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
>   File "/home/anaconda3/envs/detectron2/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 164, in resume_or_load
>     return self.load(path)
>   File "/home/anaconda3/envs/detectron2/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 107, in load
>     obj.load_state_dict(checkpoint.pop(key))
>   File "/home/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/optim/optimizer.py", line 111, in load_state_dict
>     raise ValueError("loaded state dict has a different number of "
> ValueError: loaded state dict has a different number of parameter groups
```

Getting this 'ValueError: loaded state dict has a different number of parameter groups' error when i resume training with  faster_rcnn, retinanet  etc. trained models

**Comment by ppwwyyxx** [comment]
You're loading a file with a different model architecture from the model you're trying to train -- that's what the error and the warning suggests.

If you want to load some parts of the weight file you can modify it following #771.

**Comment by Samjith888** [comment]
> You're loading a file with a different model architecture from the model you're trying to train -- that's what the error and the warning suggests.
> 
> If you want to load some parts of the weight file you can modify it following #771.

I have trained the model using 'faster_rcnn_V_99_FPN_3x.yaml' and i used the same trained weight for resume. I got this same  issue when i tried resume from a weight in tridentnet , retinanet even with same model architecture.

**Comment by ppwwyyxx** [comment]
trident net, retinanet, and faster_rcnn_V_99_FPN_3x.yaml are different model architectures.

**Comment by Samjith888** [comment]
> trident net, retinanet, and faster_rcnn_V_99_FPN_3x.yaml are different model architectures.

I meant that eg: i trained with trident net and tried to resume in trident_net, trained in retinanet and tried to resume in retinanet etc.

**Comment by jiashenC** [comment]
I am seeing the similar issue. I have the exact model but got error `ValueError: loaded state dict has a different number of parameter groups`. Not really sure what causes the problem, but after I add `cfg.MODEL.BACKBONE.FREEZE_AT = 0`, the code works fine. Maybe it is somehow related to how I save the frozen model architecture.

**Comment by r5sb** [comment]
@Samjith888 @jiashenC @ppwwyyxx Hello, did you find the solution to this error? I am facing the same error right now. I trained the model using mask_rcnn_R_50_FPN_3x.yaml and then want to finetune by unfreezing all layers so also added `cfg.MODEL.BACKBONE.FREEZE_AT = 0` for a few epochs. However when loading the model and trying to train it gives the same error as yours. I'd appreciate any help if you were able to solve it. Thank you!

**Comment by ppwwyyxx** [comment]
This no longer happens if `resume=False` is used in https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultTrainer.resume_or_load

**Comment by r5sb** [comment]
@ppwwyyxx Thanks for your reply. This however restarts the training from step 0 correct? What I am trying to do for example is:

1. Train model mask_rcnn_R_50_FPN_3x.yaml with `cfg.MODEL.BACKBONE.FREEZE_AT = 0` for 1000 steps.
2. Save this in model_final.pth
3. Load model again and finetune using mask_rcnn_R_50_FPN_3x.yaml with `cfg.MODEL.BACKBONE.FREEZE_AT = 2` for further 500 steps.

**Comment by ppwwyyxx** [comment]
That's correct. There are many data in a checkpoint - some of which you want to resume but some not, so it's unlikely we'll have something that exactly fits what you need. In this case you don't want optimizer (since it has different parameters) but you want the rest, so you can use `torch.load/save` to edit the checkpoint.

**Comment by r5sb** [comment]
@ppwwyyxx Thank you for your help. I am able to train now after deleting the 'optimizer' and 'scheduler' from the checkpoint file. At the time of model training, the entire model architecture is printed. However, no information on which layers are frozen/unfrozen is printed. Is there a way to verify what layers are frozen/unfrozen within Detectron2. In torch there is a trainable attribute of the layer to check whether it is frozen. Is there something similar withing Detectron2? Thank you!

**Comment by ppwwyyxx** [comment]
The question is off-topic. please see https://github.com/facebookresearch/detectron2/issues/1898

**Comment by git-haddadz** [comment]
> 
> 
> Thank you for your help. I am able to train now after deleting the 'optimizer' and 'scheduler' from the checkpoint file. At the time of model training, the entire model architecture is printed. However, no information on which layers are frozen/unfrozen is printed. Is there a way to verify what layers are frozen/unfrozen within Detectron2? Thank you!

@r5sb did you use resume=True? I keep having the error even after deleting the optimizer and scheduler with the torch.load/save
