### ISSUE TITLE
How to calculate the mAP, LAMR? Also printing testing accuracy in tensorboard?

### ISSUE THREAD

**Issue by mefahimrahman** [facebookresearch/detectron2#899]
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by ppwwyyxx** [comment]
Detectron2 calculates mAP using COCO API or other APIs provided by different datasets.
Detectron2 does not calculate LAMR.
Detectron2 already shows test accuracy in tensorboard, by default at the end of training. You can change `cfg.TEST.EVAL_PERIOD` to make it more frequent.

**Comment by alekhka** [comment]
Setting EVAL_PERIOD to low value (I set it to 5000) crashed my training after a while. It seems like the eval results after each eval run isn't deleted and after 10 or so evaluations it goes out of memory (on a 300GB RAM system). Is that expected or am I doing something wrong?

**Comment by ppwwyyxx** [comment]
It's not expected and if you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by mefahimrahman** [comment]
@ppwwyyxx after training the output folder structure -

output
-events.out.tfevents.1582636641.13f26e5de6d5.495.0
-last_checkpoint
-metrics.json
-model_final.pth

After the testing no changes in this folder. So would you please help me to how can I get the testing accuracy?
