### ISSUE TITLE
need SoftmaxFocalLoss

### ISSUE THREAD

**Issue by shiyongde** [facebookresearch/detectron2#90]
## 🚀 Feature
The detectron has SoftmaxFocalLoss , I think It's useful for some cases. 

The pytorch already has the code : 
https://github.com/pytorch/pytorch/blob/821b5f138a987807032a2fd908fe10a5be5439d9/modules/detectron/softmax_focal_loss_op.cu

Could you merge this ?

**Comment by ppwwyyxx** [comment]
duplicate of https://github.com/facebookresearch/fvcore/issues/5
