### ISSUE TITLE
Can we use multiple GPU on inference?

### ISSUE THREAD

**Issue by tamyxgopenx** [facebookresearch/detectron2#902]
## 🚀 Feature
Prediction using multiple GPU without 
## Motivation
I want to speed up the prediction time with more GPUs
## Pitch
It should be easier if you can use config for this, like config.CPU_DEVICE_COUNT = 2
Is there anyway to do it? i have seen python tools/train_net.py --num-gpus 4 --config-file configs/modanet.yaml but i guess it for training, i only want to predict frame.

**Comment by ppwwyyxx** [comment]
See #716, #586, #33, etc.

**Comment by tamyxgopenx** [comment]
@ppwwyyxx  thanks for you answer but is there a function that make gpu parallel computing one frame only?

**Comment by ppwwyyxx** [comment]
there isn't
