### ISSUE TITLE
For Object Detection, how to get the last layer of the roi head, from which the class of a detection gets predicted?

### ISSUE THREAD

**Issue by Siddsouza19** [facebookresearch/detectron2#904]
I want to implement Active Learning. For this I need the last layer which contains the scores of all the classes of a detection, and not its argmax value, which determines which class the detection belongs to.
eg. If I have 3 classes, want the scores of all the classes like this [0.45, 0.33, 0.22];
and not just 0.45, which is the prediction with the highest score.

**Comment by ppwwyyxx** [comment]
Answered in https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model
