### ISSUE TITLE
load_coco_json does not load more than one annotation per image in its dictionary.

### ISSUE THREAD

**Issue by Siddsouza19** [facebookresearch/detectron2#906]
1) So I ran this command to register my test data coco instances:

      from detectron2.data.datasets import register_coco_instances
      register_coco_instances("test", {}, "test_data.json", "signdata_test/")

2) But when I run the load_coco json command function, the resultant dictionary contains only one annotation per image, even though my json file has multiple annotations per image.

      from detectron2.data.datasets import load_coco_json
      test_dict=load_coco_json("test_data.json", "signdata_test/", dataset_name="test", 
      extra_annotation_keys=None)

3) Similarly when I use the following function, only one annotation gets registered in the dictionary, when there are 2 bounding boxes in the image being verified:

      dataset_dicts = DatasetCatalog.get("test")
      print(dataset_dicts[204])

output: 

{'file_name': 'signdata_test/bc7c157f-047d-464b-9654-c118746b0da9.jpeg', 'height': 2000, 'width': 3264, 'image_id': 205, 'annotations': [{'iscrowd': 0, 'bbox': [1133, 1194, 111, 105], 'category_id': 4, 'bbox_mode': <BoxMode.XYWH_ABS: 1>}]}

This particular image has 2 boxes annotated. But this outputs only one box.
Thus even in the visualiser code of google colab, only one bounding box per image is shown in every image.

      from detectron2.utils.visualizer import ColorMode
      import matplotlib.pyplot as plt
      %matplotlib inline
      for d in random.sample(dataset_dicts, 30):
          print(d['file_name'])
          img = cv2.imread(d["file_name"])
          visualizer = Visualizer(img[:, :, ::-1], metadata=test_metadata, scale=0.5)
          vis = visualizer.draw_dataset_dict(d)
          plt.figure(figsize=(30, 30))
          plt.imshow(vis.get_image(),cmap='gray',interpolation='none')
          plt.show()

**Comment by ppwwyyxx** [comment]
>  even though my json file has multiple annotations per image

Please show some evidence? This happens probably because your json is not in correct COCO format.
