### ISSUE TITLE
RuntimeError: No such operator _caffe2::CopyGPUToCPU

### ISSUE THREAD

**Issue by keyang512** [facebookresearch/detectron2#907]
## Instructions To Reproduce the Issue:
I am running this command to export a GPU model 

!python detectron2_repo/tools/caffe2_converter.py  --config-file detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml  --output ./model MODEL.WEIGHTS ./output/model_final.pth

But I got following errors:

[02/19 22:09:50 d2.export.caffe2_export]: Exporting a Caffe2GeneralizedRCNN model via ONNX ...
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/caffe2_export.py", line 136, in export_caffe2_detection_model
    predict_net, init_net = _export_via_onnx(model, (tensor_inputs,))
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/caffe2_export.py", line 48, in _export_via_onnx
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/caffe2_modeling.py", line 265, in forward
    proposals, _ = self._wrapped_model.proposal_generator(images, features)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/c10.py", line 220, in forward
    input_list = [to_device(x, "cpu") for x in (rpn_rois_list + rpn_roi_probs_list)]
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/c10.py", line 220, in <listcomp>
    input_list = [to_device(x, "cpu") for x in (rpn_rois_list + rpn_roi_probs_list)]
  File "/home/ec2-user/SageMaker/detectron2_repo/detectron2/export/shared.py", line 37, in to_device
    return torch.ops._caffe2.CopyGPUToCPU(t)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator _caffe2::CopyGPUToCPU

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/deployment.html#usage

**Comment by keyang512** [comment]
Hi @ppwwyyxx , 
Thanks for the quick response.   When I add MODEL.DEVICE cpu,  the export still not working

**Comment by ppwwyyxx** [comment]
Since it's a different issue, please provide details following  [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Also, it's good to avoid using a file (your model_final.pth) that other people cannot access to reproduce your issue.

**Comment by ppwwyyxx** [comment]
If the above you posted are all logs that you observe, then you're probably having the issue answered at the end of https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md

**Comment by keyang512** [comment]
Hi @ppwwyyxx 

The error is "Segmentation fault".


sh-4.2$ gdb -ex "r" -ex "bt" -ex "quit" --args python -m detectron2.utils.collect_envGNU gdb (GDB) Amazon Linux (7.6.1-64.33.amzn1)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-amazon-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/python3.6...done.
Starting program: /home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/python -m detectron2.utils.collect_env
warning: File "/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /lib64/libthread_db-1.0.so
line to your configuration file "/home/ec2-user/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/ec2-user/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Detaching after fork from child process 17688.
Missing separate debuginfo for /usr/lib64/libstdc++.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/87/91ddd49348603cd50b74652c5b25354d8fd06e.debug
Missing separate debuginfo for /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libgomp-7c85b1e2.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/0c/0cf5452435739ebddf30a881ede53634718e67.debug
Missing separate debuginfo for /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/cv2/.libs/libz-a147dcb0.so.1.2.3
Missing separate debuginfo for /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/cv2/.libs/libbz2-7225278b.so.1.0.3
Detaching after fork from child process 17705.
Detaching after fork from child process 17706.
Detaching after fork from child process 17707.
Detaching after fork from child process 17710.
------------------------  ---------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1 @/home/ec2-user/SageMaker/detectron2_repo/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_37
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0+cu100 @/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla K80
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    7.0.0
torchvision               0.5.0+cu100 @/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ---------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[LWP 17681 exited]
[Inferior 1 (process 17681) exited normally]
No stack.

**Comment by ppwwyyxx** [comment]
Then your observation matches what's at the end of https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md, and the solution is provided there.

**Comment by ppwwyyxx** [comment]
To clarify, I'm referring to the item " ONNX conversion segfault after some "TraceWarning". in `INSTALL.md`.

**Comment by keyang512** [comment]
Hi @ppwwyyxx ,

Thanks for being so helpful. I gave up the export model in the sagemaker.  Try my local Macos, works well. :-)
