### ISSUE TITLE
STRIDE_IN_1x1 is not set in a right way?

### ISSUE THREAD

**Issue by FateScript** [facebookresearch/detectron2#909]
## Expected behavior:

Hi, I am using your sync-bn and I find something strange: in your norm-related yaml files(for example, [this one](https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/mask_rcnn_R_50_FPN_3x_syncbn.yaml)), STRIDE_IN_1x1 is set to False, but False is used for non-MSRA pretrained model.   
I set it to True and trained a 1x maskrcnn model, actually it got a higher point.  
Is there anything wrong in your setting?

**Comment by ppwwyyxx** [comment]
Thanks, our setting is wrong. We'll rerun the experiments.

**Comment by ppwwyyxx** [comment]
Now updated. On 1x we saw slightly better (~0.3 AP) after the fix. On 3x, no improvement was observed.
