### ISSUE TITLE
How to set anchor sizes to specific values?

### ISSUE THREAD

**Issue by GorkemP** [facebookresearch/detectron2#910]
Hi,

1) In the config file documentation [(config documentation)](_C.MODEL.ANCHOR_GENERATOR.SIZES), for the anchor sizes, it is stated that 

> anchor sizes given in absolute pixels w.r.t. the scaled network input.

And default values are [[32, 64, 128, 256, 512]].

By absolute pixels, does it mean total area or do values represent only one dimension (width or height)?

2) Is it possible to use specific anchor size values such as

[(16, 18), (32, 30), (128, 128), ... ]

where each tuple corresponds to (width, height).

**Comment by ppwwyyxx** [comment]
1. It width and height for anchors with aspect ratio=1.
2. No. The default anchor generator are parameterized by size and aspect ratio. You will need to define your own anchor generator if you need something else.

**Comment by GorkemP** [comment]
So, for size=32 and aspect_ratio=0.5, width will be 16 and height will be 32 right? 
Or is it arranging width and height so that total area is the same (32*32 = width*height).

**Comment by GorkemP** [comment]
Ok, I saw in `generate_cell_anchors` function that it is arranging so that the size is same.
