### ISSUE TITLE
AttributeError: Attempted to set WEIGHTS to /model_final.pth, but CfgNode is immutable

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#911]
Here I'm trying evaluate on  a specific weight (model_) , The code is here

```
cfg = get_cfg()
cfg.DATASETS.TRAIN = ("train", )
cfg.DATASETS.TEST = ("val", )
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.MODEL.WEIGHTS = project_root+"/checkpoints/model_0024999.pth" 

model = trainer.build_model(cfg)
predictor = DefaultPredictor(cfg) #evaluation
DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(cfg.MODEL.WEIGHTS, resume=False)

#Evaluation with AP metric
from detectron2.evaluation import COCOEvaluator, inference_on_dataset, DatasetEvaluators
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("val", cfg, True, output_dir=project_root+"/checkpoints/COCO_evaluator")
val_loader = build_detection_test_loader(cfg, "val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```
I got the following error 

Traceback (most recent call last):
  File "val.py", line 73, in <module>
    cfg.MODEL.WEIGHTS = project_root+"/checkpoints/model_0024999.pth" 
  File "/home/detect/anaconda3/envs/detectron2/lib/python3.7/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/detect/anaconda3/envs/detectron2/lib/python3.7/site-packages/yacs/config.py", line 147, in __setattr__
    name, value
AttributeError: Attempted to set WEIGHTS to /home/checkpoints//model_0024999.pth, but CfgNode is immutable

**Comment by freedom521jin** [comment]
@Samjith888 I got the same error, could you tell me how did you make it ?

**Comment by Paddy-Xu** [comment]
same, any updates? thanks a lot
