### ISSUE TITLE
Training steps for instance segmentation 

### ISSUE THREAD

**Issue by iamkingpin** [facebookresearch/detectron2#912]
I want to train my images for which i want to make annotations in **COCO dataset** format. So is there any **annotation tool/script** using which i can make my **annotations in COCO instance segmentation format**.
Also is there any use of registering my dataset in COCO format if I already make annotations/images in
COCO format!
Or simply can help with providing **training steps/ dataset (annotations)** structure.

**Comment by ppwwyyxx** [comment]
We don't help on making annotations as this is not in the scope of detectron2.

https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 has demos on how to train on custom datasets. The tutorial is https://detectron2.readthedocs.io/tutorials/datasets.html
