### ISSUE TITLE
How to replicate speed performance results as reported in Model ZOO

### ISSUE THREAD

**Issue by jadielam** [facebookresearch/detectron2#913]
I would like to know how Detectron2 performance results reported in model zoo (https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md) were computed. I have used the Dockerfile provided in repository on a p2 instance on AWS and my speed numbers are far worse than the ones reported.

So my question is, why are they different? Was a different GPU used? If so, which one? Was the Dockerfile of the repository used? If not, could that unknown Dockerfile be provided?

**Comment by ppwwyyxx** [comment]
answered in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#how-to-read-the-tables
