### ISSUE TITLE
Loading more than 2 images with DefaultPredictor on one GPU

### ISSUE THREAD

**Issue by orishko-py** [facebookresearch/detectron2#916]
I followed the[ balloon](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=hBXeH8UXFcqU) tutorial for my own dataset that has 37 classes and 120 images each. 
`cfg.SOLVER.IMS_PER_BATCH = 2`
The model only considers 2 per batch - is there a builtin way to subdivide a larger batch to load on one GPU for one update using DefaultPredictor? If no, what is the alternative? Thanks.

**Comment by ppwwyyxx** [comment]
I could not understand what it means to " subdivide a larger batch to load on one GPU ". Could you clarify.

**Comment by orishko-py** [comment]
I guess I'm referring to something included in implementations of [PyTorch-YOLOv3](https://github.com/DeNA/PyTorch_YOLOv3) called a subdivision: 

`BATCHSIZE: 4 
 SUBDIVISION: 16 # num of minibatch inner-iterations`

My question is how do I increase batch size without adding more GPUs? I looked at the documentation [here](https://detectron2.readthedocs.io/modules/config.html) to find 

`# Number of images per batch across all machines.
# If we have 16 GPUs and IMS_PER_BATCH = 32,
# each GPU will see 2 images per batch.
_C.SOLVER.IMS_PER_BATCH = 16`

If I try to set it a number larger than 2 I run into Runtime errors due to memory allocation. Any way to go about this? Sorry if I am not making this clear.

**Comment by ppwwyyxx** [comment]
We do not provide this option in our default trainer but this can be easily implemented in any pytorch training loop.
