### ISSUE TITLE
How do I control training/inference printing?

### ISSUE THREAD

**Issue by Divadi** [facebookresearch/detectron2#920]
Is there an easy way to tell the training loop to print every 200 iterations, not 20, or control printing of "Inference done 824/3712. 0.0542 s / img. ETA=0:02:40" for testing?

**Comment by ppwwyyxx** [comment]
1. training: this is a default parameter set at this line https://github.com/facebookresearch/detectron2/blob/c14fcaee32b253e9b76b78a56053f159e5e5ada0/detectron2/engine/defaults.py#L340 that you can overwrite in subclasses. Or use https://github.com/facebookresearch/detectron2/blob/master/tools/plain_train_net.py

2. inference: there is no way to control it

**Comment by Divadi** [comment]
Thank you!

For 2), I tracked down https://github.com/facebookresearch/detectron2/blob/5db4ea37627cf578b7763cb9dc2e110f96f4dbf6/detectron2/evaluation/evaluator.py#L140
And overwrote it
