### ISSUE TITLE
My own registered dataset was overwritten when using DatasetCatalog

### ISSUE THREAD

**Issue by LaoYang1994** [facebookresearch/detectron2#922]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```python

def merge_to_panoptic_sog(detection_dicts, sem_seg_dicts, pan_dicts):
    results = []
    sem_seg_file_to_entry = {x["file_name"]: x for x in sem_seg_dicts}
    pan_file_to_entry = {x["file_name"]: x for x in pan_dicts}
    assert len(sem_seg_file_to_entry) > 0

    for det_dict in detection_dicts:
        dic = copy.copy(det_dict)
        dic.update(sem_seg_file_to_entry[dic["file_name"]])
        dic.update(pan_file_to_entry[dic["file_name"]])
        results.append(dic)
    return results

_PREDEFINED_SPLITS_COCO_PANOPTIC_SOG = {
    "coco_2017_train_panoptic_sog": (
        "coco/train2017",
        # generate by running the scripts in datasets
        "coco/annotations/instances_sog_train2017.json",
        "coco/panoptic_seg_train2017",
        "coco/annotations/panoptic_train2017.json",
        "coco/panoptic_all_cat_train2017",
        ["pan_id"],
    ),
    "coco_2017_val_panoptic_sog": (
        "coco/val2017",
        "coco/annotations/instances_val2017.json",
        "coco/panoptic_val2017",
        "coco/annotations/panoptic_val2017.json",
        "coco/panoptic_all_cat_val2017",
        [],
    )
}

for (
    prefix, (image_root, instances_json, panoptic_root, panoptic_json, semantic_root, extra_keys),
) in _PREDEFINED_SPLITS_COCO_PANOPTIC_SOG.items():

    image_root     = os.path.join("datasets", image_root)
    instances_json = os.path.join("datasets", instances_json)
    panoptic_root  = os.path.join("datasets", panoptic_root)
    panoptic_json  = os.path.join("datasets", panoptic_json)
    sem_seg_root   = os.path.join("datasets", semantic_root)

    DatasetCatalog.register(
        prefix,
        lambda: merge_to_panoptic_sog(
            load_coco_json(instances_json, image_root, prefix, extra_keys),
            load_sem_seg(sem_seg_root, image_root),
            load_pan_seg(panoptic_root, image_root)
        )

    print(len(DatasetCatalog.get('coco_2017_train_panoptic_sog')))
```
2. what exact command you run:
Just put the above code in a python file and run it. At the same time, you may need to import "DatasetCatalog", "load_coco_json", "load_sem_seg" from detectron2.

3. what you observed (including the full logs):
The output is
```
get:  coco_2017_train_panoptic_sog
json_file: datasets/coco/annotations/instances_sog_train2017.json
118287
get:  coco_2017_train_panoptic_sog
json_file: datasets/coco/annotations/instances_val2017.json
5000
```

## Expected behavior:

```
get:  coco_2017_train_panoptic_sog
json_file: datasets/coco/annotations/instances_sog_train2017.json
118287
get:  coco_2017_train_panoptic_sog
json_file: datasets/coco/annotations/instances_sog_train2017.json
118287
```
"get: xxx" was shown when calling "DatasetCatalog.get('xxx')"

"json_file: xxx" was shown when calling "load_coco_json"

From the output above, I think my own registered dataset("coco_2017_train_panoptic_sog") was overwritten.
## Environment:

------------------------  ------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                     1.17.2
detectron2                0.1 @/home/xxx/Project/detectron2/detectron2
detectron2 compiler       GCC 5.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_70
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/xxx/Env/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3               Tesla V100-PCIE-16GB
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
Pillow                    6.2.0
torchvision               0.5.0 @/home/xxx/Env/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
A python question. See https://stackoverflow.com/questions/19837486/python-lambda-in-a-loop
