### ISSUE TITLE
How to get the segmented parts of the image? Detectron2

### ISSUE THREAD

**Issue by LuisEdMB** [facebookresearch/detectron2#924]
Hello, I am using Detectron2, and I would like to know how to get the segmented images of an image.

Reference images:

From:

![imagen](https://user-images.githubusercontent.com/21093220/75122183-0db8ef80-5669-11ea-8a45-23cbcdd7c9fa.png)

Get:

![imagen](https://user-images.githubusercontent.com/21093220/75122187-21645600-5669-11ea-8a96-d1899861654c.png)

![imagen](https://user-images.githubusercontent.com/21093220/75122193-3214cc00-5669-11ea-9b2a-470f056bddb2.png)

Thanks for the help.

**Comment by ppwwyyxx** [comment]
You can write code to parse https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
