### ISSUE TITLE
When I ran the quick start colab, I got the following error, I just clicked all to run

### ISSUE THREAD

**Issue by jialianchen** [facebookresearch/detectron2#928]
When I ran the  [colab](https://colab.research.google.com/drive/1isGPL5h5_cKoPPhVL9XhMokRtHDvmMVL) I got the following error, but I just clicked all to run
![RQJA}$()1()3$Q(J50}FPPG](https://user-images.githubusercontent.com/38684111/75124765-359d6700-56ec-11ea-9c62-11d86bc8cd0a.png)

**Comment by ppwwyyxx** [comment]
The colab uses an old version of detectron2 with a newer (latest) version of code. Now it's fixed.
