### ISSUE TITLE
any caffe2 model C++ inference and acceleration?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#929]
now that caffe2 model exported, will it optimized such as more light model, quantitate or C++ inference accleration?

to be precisely, how to make it running realtime or near realtime on mobile devices?

**Comment by ppwwyyxx** [comment]
Small models plus caffe2 quantization will enable models to run on mobile devices. Such as those in https://github.com/caffe2/models/tree/master/mask_rcnn_2go. 

There is work in progress to open source some relatively smaller models. Quantization is not yet in our plan for open source so it won't be available in the next few months.
