### ISSUE TITLE
Attempting to copy inputs of <function pairwise_iou at > to CPU due to CUDA OOM

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#932]
Network : retinanet_R_101_FPN_3x.yaml

1. what changes you made (`git diff`) or what code you wrote:

`
cfg = get_cfg()
cfg.merge_from_file(project_root+"/configs/COCO-Detection/rpn_R_50_FPN_1x.yaml") 
cfg.DATASETS.TRAIN = ("train",)
cfg.OUTPUT_DIR =  os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.DATASETS.TEST = ('val',)  
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
cfg.SOLVER.IMS_PER_BATCH = 2 
cfg.SOLVER.CHECKPOINT_PERIOD = 50000  # Save
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64   # faster, and good enough for this toy 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 
cfg.SOLVER.STEPS = (50000,100000,150000,)
cfg.SOLVER.BASE_LR = 0.000099 #learning rate
cfg.SOLVER.MAX_ITER = 200000 
cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[8,16,32,64, 128, 256, 512]]
cfg.TEST.AUG.MIN_SIZES = (8,16,32,400, 500, 600, 700, 800, 900, 1000, 1100, 1200)

`

2. what exact command you run:

     Python filename.py

3. what you observed (including the full logs):

      After 1000 iteration '**Attempting to copy inputs of <function pairwise_iou at > to CPU due to    CUDA OOM**' is coming up. And then this is increasing and the training failed after several iterations.

![error_fpn](https://user-images.githubusercontent.com/39676803/75214982-49f96680-57b5-11ea-9cad-be512719b6f7.png)

**Environment**

output of python -m detectron2.utils.collect_env

`$ python -m detectron2.utils.collect_env
------------------------  ------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1 @/home/detectcv/.conda/envs/detectron2/lib/python3.7/site-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/detectcv/.conda/envs/detectron2/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1                   GeForce GTX 1080
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.105
Pillow                    7.0.0
torchvision               0.5.0 @/home/detectcv/.conda/envs/detectron2/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       3.4.2
------------------------  ------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
`

I tried 'https://github.com/facebookresearch/detectron2/issues/433' solutions from this issue , but still getting the same error

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Samjith888** [comment]
> If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md)

Please look at the updated command

**Comment by ppwwyyxx** [comment]
CUDA out of memory means your GPU does not have sufficient memory to run the code.

**Comment by Samjith888** [comment]
> CUDA out of memory means your GPU does not have sufficient memory to run the code.

I have 8GB `GeForce RTX 2070 SUPER GPU` . And i tried by setting lower batch size
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64
