### ISSUE TITLE
check_image_size    ... bug?

### ISSUE THREAD

**Issue by JavierClearImageAI** [facebookresearch/detectron2#933]
I think there is a bug in here: 

https://github.com/facebookresearch/detectron2/blob/316469de26f9ef8914762fd144b2c1b2ce2ffa90/detectron2/data/detection_utils.py#L73

it works wrong with images that are not landscape images... so if I use a vertical video, it shows the next error sometimes:

```
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/data/detection_utils.py", line 87, in check_image_size
    expected_wh,
```

```
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image /home/ubuntu/new_logs_v5/train/Walnut_Veneer_Logs_0476l.jpg, got (720, 960), expect (960, 720)
```

I compared my json height and weight and the images sizes opening them with CV2, then  im.shape() and they are OK.

**Comment by ppwwyyxx** [comment]
We use `PIL` to read image:
https://github.com/facebookresearch/detectron2/blob/316469de26f9ef8914762fd144b2c1b2ce2ffa90/detectron2/data/detection_utils.py#L49-L69

Please try it and if it reads wrong size, please report bugs to PIL.
