### ISSUE TITLE
Multi-GPU training output

### ISSUE THREAD

**Issue by justinkay** [facebookresearch/detectron2#937]
I am confused by the log output for multi-GPU training. I am using 8 GPUs, and only the GPU with rank 0 seems to output anything to its log file during training. During evaluation, all 8 have output. Does this mean that only 1/8 of the batch is actually being used for training?

This occurs for training with mostly default parameters on COCO for bounding box detection. TEST.EVAL_PERIOD set to a small value to demonstrate what I observe.

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
No changes.

2. what exact command you run:
```
python tools/train_net.py --num-gpus 8 --config-file configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml DATALOADER.NUM_WORKERS 2 TEST.EVAL_PERIOD 100
```

3. what you observed (including the full logs):

Training is run for 200 iterations, so 2 evaluation steps. As you can see, in log.txt.rank[1-7] (note I added an additional .txt to each log to permit github upload), there is no output during training after "INFO: Starting training from iteration 0".

[log.txt](https://github.com/facebookresearch/detectron2/files/4247812/log.txt)
[log.txt.rank1.txt](https://github.com/facebookresearch/detectron2/files/4247814/log.txt.rank1.txt)
[log.txt.rank2.txt](https://github.com/facebookresearch/detectron2/files/4247815/log.txt.rank2.txt)
[log.txt.rank3.txt](https://github.com/facebookresearch/detectron2/files/4247817/log.txt.rank3.txt)
[log.txt.rank4.txt](https://github.com/facebookresearch/detectron2/files/4247818/log.txt.rank4.txt)
[log.txt.rank5.txt](https://github.com/facebookresearch/detectron2/files/4247819/log.txt.rank5.txt)
[log.txt.rank6.txt](https://github.com/facebookresearch/detectron2/files/4247820/log.txt.rank6.txt)
[log.txt.rank7.txt](https://github.com/facebookresearch/detectron2/files/4247821/log.txt.rank7.txt)

## Environment:

This is running on a Google Compute Engine VM:
Machine type: n1-highmem-8 (8 vCPUs, 52 GB memory)
GPUs: 8 x NVIDIA Tesla K80

sys.platform              linux
Python                    3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1 @/home/justinkay92/pelagix_ml/lib/detectron2/detectron2
detectron2 compiler       GCC 6.3
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_37
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/justinkay92/.conda/envs/py37/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3,4,5,6,7       Tesla K80
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.0.0
torchvision               0.5.0 @/home/justinkay92/.conda/envs/py37/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ---------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=
compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute
_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3

**Comment by ppwwyyxx** [comment]
This is part of the predefined default training logic (of `DefaultTrainer`). The reason is that the logs during training will be almost, if not completely identical among workers and are not free of cost to collect and log.
