### ISSUE TITLE
Using "bitmask" to label dataset,DatasetMapper:"dataset_dict = copy.deepcopy(dataset_dict)" can be very time consuming.

### ISSUE THREAD

**Issue by PipeBlack** [facebookresearch/detectron2#939]
Has anyone encountered this problem?

**Comment by ppwwyyxx** [comment]
You can implement your own mapper if the default is not enough for you: https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader

**Comment by PipeBlack** [comment]
> You can implement your own mapper if the default is not enough for you: https://detectron2.readthedocs.io/tutorials/data_loading.html#write-a-custom-dataloader

ok,thanks
