### ISSUE TITLE
about the bbox mode in the coco_instances_results.json

### ISSUE THREAD

**Issue by yustaub** [facebookresearch/detectron2#943]
when I train the balloon dataset and eval it and get the result, in the coco_instances_results.json
`{"image_id": 0, "category_id": 0, "bbox": [0.0, 1530.7779541015625, 184.1992645263672, 517.2220458984375], "score": 0.5507305860519409, "segmentation": {"size": [2048, 1323], "counts": "T`7c?]`1000000000O1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000UFe_NQ4[`1nKg_NQ4Y`1nKi_NQ4W`1nKk_NQ4U`1mKo_NQ4Q`1nKQ`NQ4o_1iI\\`NPNHU8l_1eIf`NPNBY8h_1jHP`NoMQ1h0^O[8a_1lHkaNcNlN\\8Y_1QIlaN`NnN^8V_1QImaNaNnN]8U_1RImaNaNoN\\8T_1SImaNaNQOZ8R_1UImaNbNROW8Q_1WIlaNcNVOS8n^1ZIlaNcN[On7i^1^IoaN]N@R8a^1aIQbNSNG[8Y^1aI^dN^6b[1bI_dN]6a[1bIbdN\\6^[1dIddNZ6\\[1fIfdNX6Z[1hIgdNW6Y[1iIidNU6W[1kIkdNS6U[1mImdNQ6S[1oIodNo5Q[1PJReNn5nZ1SJReNl5nZ1TJSeNk5mZ1UJUeNi5kZ1WJWeNg5iZ1YJYeNe5gZ1[J\\eNb5dZ1_J^eN^5bZ1bJaeN[5_Z1eJceNY5]Z1gJdeNX5\\Z1iJeeNU5[Z1kJheNR5XZ1nJjeNP5VZ1QKW`NkMn4R7kZ1TKQ`NQNT5i6kZ1WKk_NWN[5_6jZ1[Ke_N]Nb5U6iZ1YLWeNe3iZ1]LXeN`3hZ1aLYeN]3gZ1dLZeNZ3fZ1gL\\eNV3dZ1jL_eNS3aZ1nLaeNo2_Z1QMceNm2]Z1TMeeNi2Wj[W2"}}`
`bbox": [0.0, 1530.7779541015625, 184.1992645263672, 517.2220458984375]`
may I ask the bbox mode is [x_center,y_center,w,h]? if it is ,can I change the output bbox mode to [xmin,ymin,xmax,ymax],and how can I change it?

**Comment by ppwwyyxx** [comment]
> may I ask the bbox mode is [x_center,y_center,w,h]

Yes

> can I change the output bbox mode to [xmin,ymin,xmax,ymax],and how can I change it?

You cannot because this file is designed to follow COCO submission format on purpose.

You can use `instance_predictions.pth`.

**Comment by yustaub** [comment]
thank for your reply!
