### ISSUE TITLE
Upgrade to use body part segmentation

### ISSUE THREAD

**Issue by hazel0504** [facebookresearch/detectron2#944]
## 🚀 Feature
Use Body Part Segmentation to improve performance of openings between arms and legs.

## Motivation

Detectron2 tends to fill in the openings between arms and legs for humans.  Approaches that use body parts and then connect body parts seem to outperform in this area.  An example is here, you can see an example with hands on hips:   https://github.com/kevinlin311tw/CDCL-human-part-segmentation (though this seems to be focused on use of synthetic data - their study was done with a body parts approach).  I have no idea if this is easily added or how it affects run time, but I believe it would increase accuracy, not only for openings, but also for the the outer edge of person - particularly with PointRend.

## Pitch

Specific body part information and more accurately representing arms and legs has benefits for a number of applications.  Perhaps this could be an add on, like pointRend.

**Comment by ppwwyyxx** [comment]
You can implement them with detectron2 https://detectron2.readthedocs.io/tutorials/write-models.html

It wouldn't make sense for detectron2 issues to be filled with feature request for every arxiv paper about detection.
