### ISSUE TITLE
Add more baseline results by others

### ISSUE THREAD

**Issue by chongruo** [facebookresearch/detectron2#949]
Is it ok for others to add more baseline results and models to Model_Zoo.md, like Mask-RCNN-R101-FPN-1x, Cascade-R101-1x(3x), which are not listed there?  It might be helpful for the comparison in the future. Thanks

**Comment by ppwwyyxx** [comment]
Hi, having more models will be great but we don't have the additional bandwidth to maintain more combination of models. You can set up a new repo with results & models you trained, and we can provide additional links at https://github.com/facebookresearch/detectron2/tree/master/projects/ to good external projects.
