### ISSUE TITLE
No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#951]
What changes i made :

```
cfg.merge_from_file(project_root+"/TridentNet/configs/tridentnet_fast_R_101_C4_3x.yaml")
cfg.DATASETS.TRAIN = ("train", )
cfg.OUTPUT_DIR =  os.path.join(cfg.OUTPUT_DIR)
cfg.DATASETS.TEST = ("val", )
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.MAX_ITER = 50000 #300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.TEST.EVAL_PERIOD = 1000
cfg.SOLVER.CHECKPOINT_PERIOD = 1000

from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

#Evaluation with AP metric
from detectron2.evaluation import COCOEvaluator, inference_on_dataset, DatasetEvaluators
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("val", cfg, False, output_dir=project_root+"/vovnet-detectron2/checkpoints/COCO_evaluator")
val_loader = build_detection_test_loader(cfg, "val")
inference_on_dataset(trainer.model, val_loader, evaluator)
```

Here I'm trying to evaluate the model after each 1000 iteration by uisng `cfg.TEST.EVAL_PERIOD = 1000`  . But evaluation not done and getting the below warning  after each 1000 iteration.

> No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.

**Comment by ppwwyyxx** [comment]
> No evaluator found. Use DefaultTrainer.test(evaluators=), or implement its build_evaluator method.

The evaluator comes from training because you set `cfg.DATASET.TEST` for training.

**Comment by Samjith888** [comment]
> > No evaluator found. Use DefaultTrainer.test(evaluators=), or implement its build_evaluator method.
> 
> The evaluator error comes from training because you set `cfg.DATASET.TEST` for training.

What changes i have to make for getting evaluation after each 1000 iteration ?

**Comment by ppwwyyxx** [comment]
>  or implement its build_evaluator method

See examples https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py

**Comment by Samjith888** [comment]
> > or implement its build_evaluator method
> 
> See examples https://github.com/facebookresearch/detectron2/blob/master/tools/train_net.py

I just  removed `cfg.DATASET.TEST` from training config, Now i got the following error
```
    dataset = json.load(open(annotation_file, 'r'))                                                                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_val2017.json' 
```

**Comment by ppwwyyxx** [comment]
As the log says, it is looking for datasets/coco/annotations/instances_val2017.json
You're probably not asking it to use your dataset.

If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Samjith888** [comment]
> As the log says, it is looking for datasets/coco/annotations/instances_val2017.json
> You're probably not asking it to use your dataset.
> 
> If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Please look at the updated issue according to the provided template

**Comment by ppwwyyxx** [comment]
The answer is to implement its build_evaluator method given above at https://github.com/facebookresearch/detectron2/issues/951#issuecomment-591627858

**Comment by niujiabenben** [comment]
Another solution to bypass FileNotFoundError error is to keep an empty testset: `cfg.DATASET.TEST=()`
