### ISSUE TITLE
Mask r cnn coco occluded objects

### ISSUE THREAD

**Issue by cenggokhan** [facebookresearch/detectron2#953]
I added my dataset to train mask r cnn, my dataset is in coco format and some of my objects in images are occluded, therefore these objects have multiple Segmentation records, when I visualize the dataset images with masks, only first Segmentation is colorized always and other Segmentation records of that object is not colorized, is detectron2 using coco style dataset supports occluded (multi Segmentation) objects.

I used detectron2.utils.visualizer Visualizer like:
```
visualizer = Visualizer(img[:, :, ::-1], metadata=dataset_metadata, scale=0.5)
vis = visualizer.draw_dataset_dict(x)
cv2.imshow("result", vis.get_image()[:, :, ::-1])
```

Object data example:
```
{
	...
		"segmentation": [
			[271, 887, 267, 896, 266, 933, 271, 942, 282, 945, 301, 932, 301, 895, 289, 887, 271, 887, 271, 887],   **//only this segmentation is colorized**
			[312, 885, 308, 943, 345, 946, 345, 906, 330, 909, 328, 884, 312, 885, 312, 885] **//this segmentation is not colorized and showed**
		],
		"iscrowd": 0,
		"category_id": 44,
		"bbox": [266, 884, 81, 62],
		"area": 3492.0
	}],
	"source": "dataset_crawl_1",
	"main_file": "1.jpg"
}
```

**Comment by ppwwyyxx** [comment]
Multiple parts can be visualized correctly as you can see in https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5.

If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
