### ISSUE TITLE
How to save trained model from DefaultTrainer? and How to load trained model to DefaultPredictor?

### ISSUE THREAD

**Issue by heartking** [facebookresearch/detectron2#958]
I used DefaultTrainer for training my data, but I don't know how to save trained model to *.pth or *.pkl.
And I also don't know how to load trained model to DefaultPredictor?
Could anyone give me some advice? 
Thanks.

**Comment by ppwwyyxx** [comment]
1. `torch.save(trainer.model, ...)`.
2. documented in https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.defaults.DefaultPredictor

**Comment by heartking** [comment]
cfg = get_cfg()
cfg.merge_from_file(
    "/home/leon/PycharmProjects/maskrcnn/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
)
cfg.DATASETS.TRAIN = ("train_dataset",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = (
    100
)  
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
    128
)  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8  

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
torch.save(trainer.model, 'checkpoint.pth')

I used your advice and got error Can't pickle local object 'GeneralizedRCNN.__init__.<locals>.<lambda>'
Could you tell me where I should modify?

**Comment by ppwwyyxx** [comment]
Sorry that wasn't the best way. Please use Checkpointer in https://detectron2.readthedocs.io/modules/checkpoint.html instead then.

**Comment by VJatla** [comment]
Hi, I was trying to do similar thing. This is how I broke up training and testing pipeline. I am only sharing testing code here.

```python
# Configuration setup for testing
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 0
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = ("kb_tst", )


predictor = DefaultPredictor(cfg)
dataset_dicts = reg2detectron2(imgs_path, tst_csv_path)

for d in random.sample(dataset_dicts, 3):
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im,
                   metadata=kb_metadata, 
                   scale=1,
                   instance_mode =  ColorMode.IMAGE
        )
    print(outputs['instances'].pred_classes)
    print(outputs["instances"].pred_boxes)
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    imshow(v.get_image())


evaluator = COCOEvaluator("kb_tst", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "kb_tst")
inference_on_dataset(predictor.model, val_loader, evaluator)
```

**Comment by heartking** [comment]
Hi,

Thank you very much.
your code is helpful.

VJatla <notifications@github.com> 於 2020年6月18日 週四 上午3:18寫道：
