### ISSUE TITLE
train new model has a bug:BlockingIOError

### ISSUE THREAD

**Issue by linmengnan** [facebookresearch/detectron2#959]
1. 、when i train my custom data，code(test.py) as folloes：
`import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import cv2
import random
# from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.data.datasets import register_coco_instances
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
register_coco_instances("cats_pets", {}, "/home/lmn/data2/instances_default.json", "/home/lmn/data2/images")
# print("register successful")
# dataset_dicts = MetadataCatalog.get("cats_pets")
# print(dataset_dicts['name'])
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os
cfg = get_cfg()
cfg.merge_from_file("/home/lmn/detetron/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
# cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("cats_pets",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
# cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256  # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 # only has one class (ballon)
print ("ready to train!")
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
`
2. I use python test.py run my code 
 
3. after  run my code ,it occurs:

<img width="1440" alt="屏幕快照 2020-02-27 下午5 43 51" src="https://user-images.githubusercontent.com/51906636/75432045-c2fce780-5988-11ea-92ea-205247838d74.png">

Thank you!

**Comment by ppwwyyxx** [comment]
Clearly an environment issue and we cannot investigate it unless you can provide an environment to reproduce the issue.

You can remove "~/.torch/fvcore_cache" and try again.

**Comment by linmengnan** [comment]
thank you，it can work normally！
