### ISSUE TITLE
Methods to convert the fields of Instances objects to numpy arrays and torch tensors. 

### ISSUE THREAD

**Issue by maxfrei750** [facebookresearch/detectron2#961]
## 🚀 Feature
`detectron2.structures.instances.Instances` offers the method `to()`, which can come in very handy during the postprocessing of detections. Analogously, I propose the introduction of two methods, which convert fields into numpy arrays or torch tensors, where applicable.

## Motivation
Often during the postprocessing of detections, the data needs to be converted to numpy, because other libraries can't handle torch tensors. It would be good to have methods to convert the instances to numpy arrays and back. 

## Pitch
If you are interested in including this functionality, I can create a PR.

**Comment by ppwwyyxx** [comment]
`.to()` makes sense for anything that __uses__ array-like storage.
However `.numpy()` makes sense only for things that __are__ array-like storage. This probably does not apply for many types of data we may put in instances.

For example, assume a polygon-like structure with `a.polygons = list[tensor]` and `a.shape = (h, w)` saved inside: what do you expect `a.numpy()` to return?

**Comment by maxfrei750** [comment]
I rather had the default properties (e.g. `pred_masks`, `pred_keypoints`, etc.) in mind, because they are most likely to be used in some sort of postprocessing. However, even then the problem that you describe occurs for `pred_boxes`. I see two possible solutions:

1. Convert only properties that support the conversion.
_pro: very straight forward, outcome of the conversion is very predictable
con: excludes many possible properties, even one of the defaults_
2. Try to recursively convert properties that do not support the conversion.
_pro: will convert many easy nested structures like `pred_boxes` or the list of tensors that you gave as an example
con: might become bulky, if one wanted to handle all eventualities_

IMHO it is better to implement this feature with certain, well documented, limitations, than to not implement it at all. That way, many people may benefit from it right away and the rest is not off worse than before.

**Comment by ppwwyyxx** [comment]
I think it is not worth adding new a new API which only means to save a few characters of `.numpy()` for users, and which only works for **certain** fields. Having a `.numpy()` call that returns something that's a mix of numpy & tensors can cause more confusion.
