### ISSUE TITLE
Evalution metrics in tensorboard

### ISSUE THREAD

**Issue by litvinich** [facebookresearch/detectron2#962]
Hello! I faced next problem: I put `TEST.EVAL_PERIOD=1000` and after each evaluation I see metrics only in logs. I want to see it also in my tensorboard graphics, but I got metrics displayed in tensorboard only for last evaluation. How can I fix it?

**Comment by ppwwyyxx** [comment]
`tools/train_net.py` does put metrics in tensorboard.

If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
