### ISSUE TITLE
How to post process the output of a deployed Caffe2 model to get prediction, scores, ...etc.

### ISSUE THREAD

**Issue by asebaq** [facebookresearch/detectron2#964]
I have deployed my caffe2 model after the conversion of detectron2 model, I got a list of numpy arrays as output and these are their shapes:
i = 0 : (3,)
i = 1 : (1, 256, 64, 80)
i = 2 : (1, 256, 32, 40)
i = 3 : (1, 256, 16, 20)
i = 4 : (1, 256, 8, 10)
i = 5 : (1, 256, 4, 5)
i = 6 : (1, 9, 64, 80)
i = 7 : (1, 36, 64, 80)
i = 8 : (1, 9, 32, 40)
i = 9 : (1, 36, 32, 40)
i = 10 : (1, 9, 16, 20)
i = 11 : (1, 36, 16, 20)
i = 12 : (1, 9, 8, 10)
i = 13 : (1, 36, 8, 10)
i = 14 : (1, 9, 4, 5)
i = 15 : (1, 36, 4, 5)

They are 15 arrays for 15 layers, and the 1st one is for the im_info, I would like to process these outputs to get a result similar to the one generated from detectron2 model.

**Comment by ppwwyyxx** [comment]
According to https://detectron2.readthedocs.io/tutorials/deployment.html#inputs-outputs:
> the Caffe2Model.__call__ method includes pre/post-processing code in order to match the formats of original detectron2 models. They can serve as a reference for pre/post-processing in actual deployment.

**Comment by asebaq** [comment]
I've read this comment before but it's not that useful as the __call__ function continues to reference other functions and this keeps going like forever and at the end, you did not know what is exactly the post-processing in actual deployment.

Can you please recommend something else more helpful than this __call__ function?

**Comment by ppwwyyxx** [comment]
There are a few "get_outputs_converter" functions in https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_modeling.py that processes the outputs. They are what's eventually get called by `Caffe2Model.__call__`

**Comment by asebaq** [comment]
These "get_outputs_converter" functions will make my reuse the detectron2 framework and this is not what I wanted, I converted the model for a reason which is to be able to use it without detectron2 dependency.
I generated this issue to be able to translate the output without detectron2 dependency.
Can you help me with that or do I just close this issue?

**Comment by ppwwyyxx** [comment]
According to https://detectron2.readthedocs.io/tutorials/deployment.html#inputs-outputs:

>  The models only produce raw outputs from the final layers that are not post-processed, because in actual deployment, an application often needs its custom lightweight post-processing (e.g. full-image masks for every detected object is often not necessary)..... They can serve as a reference for pre/post-processing in actual deployment.

What it suggests is that you'll need to know what the outputs are, and write code to post-process them into a format you need for your deployment. The functions in `get_outputs_converter` are references for post-processing them into detectron2's format.

**Comment by ppwwyyxx** [comment]
An example using the caffe2 model in C++ is provided in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python.
