### ISSUE TITLE
How To Generate Keypoint Score Heatmap

### ISSUE THREAD

**Issue by cm107** [facebookresearch/detectron2#965]
## Background
Following the advice from #754 I was able to display keypoint heatmaps during video inference.
https://github.com/facebookresearch/detectron2/issues/754
However, I am having a hard time comparing the keypoint scores to their respective heatmaps.
I am using a score threshold to determine whether or not to display the keypoints, but I can't tell where the threshold region begins and ends on the heatmap.

## Question
I can create a separate threshold for the raw magnitude of the heatmap itself and display that, but this doesn't relate with the score threshold. I don't completely understand how the score is calculated, so it may very well be impossible to calculate a score heatmap for all I know.

Is it possible to generate a score heatmap?

**Comment by ppwwyyxx** [comment]
The code to compute score is referred to in https://github.com/facebookresearch/detectron2/issues/319#issuecomment-565773345
