### ISSUE TITLE
Why use "acc_valid = pos_gt > 0" to get acc_valid in sem_seg_evaluation.py?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/detectron2#966]
## ❓ Why use` acc_valid = pos_gt > 0` to get `acc_valid` in [sem_seg_evaluation.py](https://github.com/facebookresearch/detectron2/blob/e0274eece86bb587870f76411e82dfe9479b7747/detectron2/evaluation/sem_seg_evaluation.py#L119)?

Hi, guys,
I am learning the implementation of mIoU in detectron2, 
and I saw the `evaluate()` code would use [acc_valid = pos_gt > 0](https://github.com/facebookresearch/detectron2/blob/e0274eece86bb587870f76411e82dfe9479b7747/detectron2/evaluation/sem_seg_evaluation.py#L119) to get acc_valid,
is this due to the 0 stands for the background class in COCO data set?

Any answer or idea will be appreciated!

**Comment by ppwwyyxx** [comment]
0 means there are no ground truth of this class so no accuracy can be computed for this class..
