### ISSUE TITLE
Cannot train deformable rcnn

### ISSUE THREAD

**Issue by Jerryzcn** [facebookresearch/detectron2#967]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
I did not make any change.
2. what exact command you run:
`python tools/train_net.py --num-gpus 8 --config-file configs/Misc/mask_rcnn_R_50_FPN_3x_dconv_c3-c5.yaml`
3. what you observed (including the full logs):
encountered 
`error in deformable_im2col: invalid device function`
following
`
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/self-taught-rcnn/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/ubuntu/self-taught-rcnn/tools/train_net.py", line 150, in main
    return trainer.train()
  File "/home/ubuntu/self-taught-rcnn/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/self-taught-rcnn/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ubuntu/self-taught-rcnn/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/self-taught-rcnn/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/self-taught-rcnn/detectron2/modeling/roi_heads/roi_heads.py", line 582, in forward
    losses = self._forward_box(features, proposals)
  File "/home/ubuntu/self-taught-rcnn/detectron2/modeling/roi_heads/roi_heads.py", line 643, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/self-taught-rcnn/detectron2/modeling/poolers.py", line 233, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/self-taught-rcnn/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/ubuntu/self-taught-rcnn/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /home/ubuntu/self-taught-rcnn/detectron2/layers/csrc/ROIAlign/ROIAlig
n_cuda.cu:364)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f2a77866627 in /home/ubuntu/anaconda3/lib/python3.6/site-packages
/torch/lib/libc10.so)
`
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

I'm expecting to be able to train w/o error.

## Environment:

Run `python -m detectron2.utils.collect_env` in the environment where you observerd the issue, and paste the output.
------------------------  ---------------------------------------------------------------------
sys.platform              linux
Python                    3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) [GCC 7.2.0]
numpy                     1.16.4
detectron2                0.1.1 @/home/ubuntu/self-taught-rcnn/detectron2
detectron2 compiler       GCC 5.4
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_70
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3,4,5,6,7       Tesla V100-SXM2-32GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    5.4.1
torchvision               0.5.0 @/home/ubuntu/anaconda3/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
------------------------  ---------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
This is an environment issue but your environment information looks OK to me.
I would try uninstall everything and make sure they are not "import"-able, then reinstall pytorch & torchvision, then detectron2 using the official instructions.

**Comment by Jerryzcn** [comment]
@ppwwyyxx Thanks!

**Comment by Jerryzcn** [comment]
Close for now. Will reopen if i have issues

**Comment by Jerryzcn** [comment]
Want to give some update. I reinstalled numpy to use the non mkl version fixed the problem

**Comment by Jerryzcn** [comment]
uninstall numpy-mkl and reinstall standard numpy seems to fix the problem

**Comment by ppwwyyxx** [comment]
That is very strange and unlikely. Could you confirm that, based on your current working situation where the above command produces no errors, if you:
1. uninstall numpy
2. then, install numpy-mkl (and btw, how do you install numpy-mkl)
3. run the command above
You'll see the exact same error as you posted above?

**Comment by Jerryzcn** [comment]
The mkl version of numpy in my specific AMI is built by Amazon, which is different than the standard numpy-mkl.
