### ISSUE TITLE
Adding 3D object detection support

### ISSUE THREAD

**Issue by xudong19** [facebookresearch/detectron2#971]
## 🚀 3D Object Detection
Current design library only support 2D object detection, for examples, the 'Boxes' class and related transformation functions are limited to 2D bounding boxes. Extending those design to 3D object detection can greatly enhance the application of detectron2

## Motivation
3D object detection is a genuine extension to 2D object detection, which are also gaining a lot of momentum recently in both academia and industry. For example, almost all the perception algorithms in autonomous driving context are moving away from pure 2D object detection to 3D real world object detection. It is very important to have 3D object detection support for detectron2 as FAIR's next-generation platform for object detection and segmentation.

## Pitch
What I am proposing here is not a simple customized extension to detectron2 functions, but rather a bundle of design changes in many basic classes and functions. Only doing so can make detectron2 support 3D object detection seamlessly and really server the purpose of FAIR's next-generation platform for object detection and segmentation.

**Comment by ppwwyyxx** [comment]
Having the ability to detect everything is certainly nice, but we will only focus on the core detection capabilities and features like what you described would be better fitted into a downstream project that depends on detectron2 as form of extensions. If anything in detectron2 stops you from making such extensions, they can be brought up as individual requests.

As an example, [Mesh R-CNN](https://github.com/facebookresearch/meshrcnn/) makes 3D predictions using detectron2.
