### ISSUE TITLE
How to set dataset path?

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#976]
My coco dataset is not in this project. How to set coco dataset dir?

**Comment by ppwwyyxx** [comment]
As said in https://github.com/facebookresearch/detectron2/tree/master/datasets the default path is "./datasets/" relative to the current working directory. It does not require you to put dataset into the project.

**Comment by Yoline777** [comment]
@ppwwyyxx How to change the default path. For example '../../datasets/coco_datasets'.

**Comment by ppwwyyxx** [comment]
The builtin path cannot be changed. However you can register datasets at a different location using `register_coco_instances` (https://detectron2.readthedocs.io/tutorials/datasets.html).

**Comment by ppwwyyxx** [comment]
The default can now be changed. See https://github.com/facebookresearch/detectron2/tree/master/datasets

**Comment by leop123** [comment]
I wonder where I could see the default dataset keywords. As in `maskrcnn_benchmark` we can see and manually insert our COCO format dataset in [path_catalog.py](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/paths_catalog.py). And also for register custom dataset in [here](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html), is it permanently or should we register it every time we run the code? Where is the dataset keywords dictionary permanently stored?
