### ISSUE TITLE
Compared with detectron1, detectron2 seems get a poor performance with my own datasets

### ISSUE THREAD

**Issue by wuqi930907** [facebookresearch/detectron2#977]
First, Thank you for your efforts, I am a loyal supporter of detectron series.
However, I have trained my own datasets between detectron1 and dectron2, I find detectron1 always get a better result on the whole. Following is my command and environment.

Detectron1:
python2.7 Ubuntu16.04 CUDA9.0 CUDNN7.0.5
python tools/train_net.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_1x.yaml \
    OUTPUT_DIR /tmp/detectron-output
Detectron2:
python3.6 Ubuntu16.04 CUDA10.0 CUDNN7.6.4 Pytorch1.3.0
python tools/train_net.py --num-gpus 8 \
	--config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml

Following pictures are part of my test results, the left half side in every picture is detectron2's result and the right half side is detectron's. Some categories always get a poor performance, such as "9_People", "4.1_TrafficLights".
Could you help me improve my detectron2's model's performance?
![14](https://user-images.githubusercontent.com/34122261/75746596-b811d080-5d55-11ea-8896-34911146353e.jpg)
![20](https://user-images.githubusercontent.com/34122261/75747075-f3f96580-5d56-11ea-80af-eacc4017ff4f.jpg)
![50](https://user-images.githubusercontent.com/34122261/75748238-e691aa80-5d59-11ea-8165-08ad354686cb.jpg)
![54](https://user-images.githubusercontent.com/34122261/75748408-5b64e480-5d5a-11ea-813f-a5cccc511e09.jpg)

**Comment by ppwwyyxx** [comment]
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.
