### ISSUE TITLE
Applying NMS for all or only some classes

### ISSUE THREAD

**Issue by GorkemP** [facebookresearch/detectron2#978]
Hi,
I have trained a faster r-cnn. Then I checked the IoU of predicted bounding boxes and realized that NMS is only applied to same class types.

1) Is NMS only applied for same class types (also in other models)?
2) If yes, can we modify it to apply all classes, I have examined configuration settings but did not find anything related.

Thank you.

**Comment by ppwwyyxx** [comment]
1. yes
2. there is no such feature. If you need you'll have to implement it yourself. One easy way is to just call `nms` again on the predictions without considering their classes.

**Comment by GorkemP** [comment]
Is this the normal behaviour of NMS in faster R-CNN or you just implemented in that way? In the original paper it is written as follows:

> ...Some RPN proposals highly overlap with each other. To reduce redundancy, we adopt non- maximum suppression (NMS) on the proposal regions based on their cls scores...

Maybe I am mistaken but I suppose it is class independent.

**Comment by ppwwyyxx** [comment]
The original paper says:
> We then perform non-maximum suppression independently for each
class using the algorithm and settings from R-CNN.

in https://arxiv.org/pdf/1504.08083.pdf

**Comment by GorkemP** [comment]
Thank you for your fast and explanatory responses.

**Comment by adesgautam** [comment]
Hi GorkemP, can you please tell how did you train Faster R-CNN on custom dataset ? And how many images did you used ?

**Comment by GorkemP** [comment]
Hi @adesgautam , you can check the following repository. Faster R-CNN, Cascade R-CNN and RetinaNet are implemented on custom dataset. 

https://github.com/GorkemP/Endoscopic-Artefact-Detection

You can see the models in `models` folder

**Comment by 2008hsk** [comment]
@adesgautam you can look at this notebook for training on custom dataset.

https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=b2bjrfb2LDeo

**Comment by moziada** [comment]
Hi GorkemP, have you found any practical solutions? i realized that this is not an issue and NMS affects the objects that belongs to the same class, and here on my case i have overleaping boxes on the bus, one of the boxes belongs to class 5 with score 0.98, and the other belongs to class 7 with score 0.26, is there anyway to keep only the highest score box.
![1533130050-cairo_main_bboxes3](https://user-images.githubusercontent.com/60968402/115029960-d473bc80-9ec6-11eb-8e66-1ec874ebecb8.jpg)

**Comment by MaxwellHogan** [comment]
@moziada, this is just my two cents, you can apply NMS on the output again - as @GorkemP suggested above he might do above

One thing I have found though is that applying NMS across all classes can result in more false negatives, for example it could result in the algorithm suppressing the bounding box around the lady as it overlaps with the bus. 

Therefore, you could apply NMS but you would need to make sure you set an IOU threshold high enough that you don't significantly increase your false negatives but, not so high that it doesn't catch the false positive.

this is different for different datasets - so you may need to run some kind of optimization algorithm to find the best thresholds and even then it may not be appropriate for real life deployment

**Comment by GorkemP** [comment]
@moziada You should apply your own custom NMS regarding the all classes as a post-processing step, there are many code online (you can use the pytorch function torchvision.ops.nms).

As @MaxwellHogan said, NMS is all about tradeoffs, you should design (set trehshold) it according to your own needs and dataset. You should also check soft-NMS, which may increaes performance in some cases.

**Comment by MaxwellHogan** [comment]
While I have you @GorkemP, were you able to get the raw output of models - prior to NMS, just because I am working on that at the moment and would help if someone has done it already so I don't have to

**Comment by GorkemP** [comment]
I directly applied the all-class NMS on top of the final predictions (which are already processed by single-class NMS).

**Comment by MaxwellHogan** [comment]
thanks
