### ISSUE TITLE
Question about empty tensor nn.Linear

### ISSUE THREAD

**Issue by lsrock1** [facebookresearch/detectron2#982]
Thank you for the awesome repo!
Detectron2 has wrapper conv2d to handle empty tensor.
I think, faster rcnn linear head should handle this empty tensor too. Why does detectron2 use normal linear? Is this intended?

https://github.com/facebookresearch/detectron2/blob/c824e7ab4074043c388a7361abe6004af9555433/detectron2/modeling/roi_heads/fast_rcnn.py#L379

**Comment by ppwwyyxx** [comment]
Handled by pytorch already.
