### ISSUE TITLE
How to cancel ROI_HEADS?

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#983]
Is 'ROI_BOX_HEAD' necessary?
I want to use 'ROI_HEADS' only. 
I delete 'ROI_BOX_HEAD' in yaml. But 'ROI_BOX_HEAD' registration error happened.

**Comment by ppwwyyxx** [comment]
If you are asking "how to do something", please be more clear what you want to do.

If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Yoline777** [comment]
I want change the loss function. What is the most appropriate method？
My idea is to modify ‘ROI_HEADS’ and cancel 'ROI_BOX_HEAD'.
I comment 'ROI_BOX_HEAD' in yaml.
`#  ROI_BOX_HEAD:
#    NAME: "FastRCNNConvFCHead"
#    NUM_FC: 2
#    POOLER_RESOLUTION: 7`
But this error occurred.
**KeyError: "No object named '' found in 'ROI_BOX_HEAD' registry!"**
So I want to know the right way to cancel 'ROI_BOX_HEAD' or change the loss function.

**Comment by ppwwyyxx** [comment]
Please explain what it means to "cancel ROI_BOX_HEAD".

Changing the loss function for box head is a duplicate question of https://github.com/facebookresearch/detectron2/issues/974

**Comment by Yoline777** [comment]
Sorry for my pool English.
I have changed the loss function by ROI_HEADS_REGISTRY and want to cancel the back propagation of the box loss.

**Comment by Yoline777** [comment]
Problem solved by inherit ROIHeads instead of StandardROIHeads
