### ISSUE TITLE
Convert `outputs['instances'].pred_masks` to numpy array?

### ISSUE THREAD

**Issue by asparamancer** [facebookresearch/detectron2#984]
outputs['instances'].pred_masks returns a tensor, is it possible to convert that to a numpy array like for pred_boxes.tensor.numpy()? In order to just extracted the masked ROI area? 

```
def inference(img_path):
    im = cv2.imread(img_path)
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=df2_val_metadata, 
                   scale=0.8, 
                   #instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    _object = cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB)
    mask = outputs['instances'].pred_masks
    _class = outputs['instances'].pred_classes
    #return(_object, mask, _class)
    return(mask)
```

**Comment by ppwwyyxx** [comment]
`outputs['instances'].pred_masks.numpy()`.

**Comment by pvtien96** [comment]
Hi @ppwwyyxx 
Sorry for bothering you again,
Is there any way to **draw/save** `outputs["instances"].pred_masks.numpy()` to **binary mask**?
I was able to get the following image using your Visualizer
![image](https://user-images.githubusercontent.com/25927039/76006853-1f0cc200-5edb-11ea-9efc-53e49e7ee486.png)
But I want the output like this 
![image](https://user-images.githubusercontent.com/25927039/76006928-3ba8fa00-5edb-11ea-8a25-b79bd9817c97.png)
Is there any available/quick way? 
Thank you!

**Comment by ppwwyyxx** [comment]
It is already a binary mask. 
How to draw it is not relevant to detectron2.

**Comment by asparamancer** [comment]
If it helps the below function should do it:

```
from matplotlib.image import imread
import scipy.misc
from PIL import Image  

def cropper(org_image_path, mask_array, out_file_name):
    img = imread(org_image_path)
    mask_array = np.moveaxis(mask_array, 0, -1)
    mask_array = np.repeat(mask_array, 3, axis=2)
    output = np.where(mask_array==False, 0, 
         (np.where(mask_array==True, 255, img)))
    im = Image.fromarray(output)
    im.save(out_file_name)
```
where mask_array = outputs["instances"].pred_masks.numpy()

you'd use it cropper('path/to/input/image', mask_array, 'path/to/save/image')

**Comment by pvtien96** [comment]
Thanks, @asparamancer 
Yes, it works!
It generates 
![image](https://user-images.githubusercontent.com/25927039/76009679-9a707280-5edf-11ea-9d3e-a60c63eedd68.png)
But I cann't read this image using cv2.imread("out_file_name path")
When I print(type(cv2.imread("out_file_name path")), I got <class 'NoneType'>
How should I read the image?
By the way, print(type(mask_array)), it shows: (1, 720, 960) where 720 960 is width height of the original image, 1 means 1 channel, right? But how can I read this mask_array by cv2 or PIL?

**Comment by asparamancer** [comment]
I'm not quite sure what you mean by read the image? Can you give an example of what you're passing into cv2.imread(img)? At the moment it looks like you've got a string that's not a path or combination of variables written as a string

**Comment by pvtien96** [comment]
Yyes! you''re GENIUS !
I''m stupid for wrong path! Now it works!
By the way, I'm making a small pipeline using detectron2 to train with binary mask datasets.
Do you work on this idea also?

**Comment by asparamancer** [comment]
Happy to help No, I've not worked on that I'm afraid.

**Comment by pvtien96** [comment]
Hi @asparamancer , sorry for bothering you again.
Your cropper function just work with binary masks that has only 1 instance.
So in case, if the predictor detect that there are **n instances** (for example, n=2 in the below image), so how can I do to convert mask_array to only 1 binary mask of 0s and 1s that contains all the instances (0s for non-objects, 1s for every instances, I don't need to distinguish instances. I just need semantic segmentation).
Here's the ouput:
![image](https://user-images.githubusercontent.com/25927039/76231293-69ec4980-61fb-11ea-9799-a76e93f77cab.png)
And then the mask_array.shape = (2, 720, 960) (means 2 instances).
And I want to save an output like this: 
![image](https://user-images.githubusercontent.com/25927039/76231615-dcf5c000-61fb-11ea-9263-ac1ac8b10de7.png)
Any suggestion? Many thanks!

**Comment by asparamancer** [comment]
You'd have to add in some login to separate out each array based on the tensor.shape[i] field. I guess something like the below is a quick way to do it, but there's probably a more elegant way to get it to take in the mask_array.shape[i] and then go from there, rather than having a big series of if statements incrementing up 1 each time. 

```
def cropper(org_image_path, mask_array, out_file_name):
        if mask_array.shape[0] == 1:
            mask_array = np.moveaxis(mask_array, 0, -1)
            img = imread(str('static/'+org_image_path))
            mask_array = np.repeat(mask_array, 3, axis=2)
            output = np.where(mask_array==False, 255, img)
            im = Image.fromarray(output)
            result = im.save('static/'+out_file_name.split('.')[0]+"/"+out_file_name)
        elif mask_array.shape[0]==2:
            mask_array = np.moveaxis(mask_array, 0, -1)
            mask_array_1 = mask_array[:,:,0:1]
            mask_array_2 = mask_array[:,:,1:2]
            img = imread(str('static/'+org_image_path))
            output = np.where((mask_array_1==False) & (mask_array_2==False), 255, img)
            im = Image.fromarray(output)
            im.save('static/'+out_file_name.split('.')[0]+"/"+out_file_name)
            output_1 = np.where(mask_array_1==False, 255, img)
            output_2 = np.where(mask_array_2==False, 255, img)
            im_1 = Image.fromarray(output_1)
            im_2 = Image.fromarray(output_2)
            im_1.save('static/'+out_file_name.split('.')[0]+"/one-"+out_file_name)
            im_2.save('static/'+out_file_name.split('.')[0]+"/two-"+out_file_name)
```

**Comment by pvtien96** [comment]
@asparamancer 
I don't understand why do you write `'static/'+out_file_name.split('.')[0]+"/"+out_file_name` (this raised error and I change it like below)
while we just need to save im.save(out_file_name)
Here's your result:
![image](https://user-images.githubusercontent.com/25927039/76233133-1b8c7a00-61fe-11ea-98c1-a6d0c04627c4.png)
Ok, so can you change code to make it just 0s (black) and 1s (white)?
I will try to write codes in general case of n instances.
Thanks

**Comment by pvtien96** [comment]
@asparamancer Yes, it finally works!
```
def cropper(org_image_path, mask_array, out_file_name):
    num_instances = mask_array.shape[0]
    mask_array = np.moveaxis(mask_array, 0, -1)
    mask_array_instance = []
    img = imread(str(org_image_path))
    output = np.zeros_like(img)
    for i in range(num_instances):
        mask_array_instance.append(mask_array[:, :, i:(i+1)])
        output = np.where(mask_array_instance[i] == True, 255, output)
    im = Image.fromarray(output)
    im.save(out_file_name)
```
Thank you!

**Comment by asparamancer** [comment]
Happy to help, yes did it in a rush before yours is a lot more efficient
