### ISSUE TITLE
Installing detectron2 linux from source on pytorch & torchvision from source 

### ISSUE THREAD

**Issue by ahiranandani** [facebookresearch/detectron2#985]
Question : To use https://github.com/facebookresearch/detectron2/blob/master/tools/caffe2_converter.py

I installed pytorch & torchvision from source (as recommended) in a conda environment. 
Can you please tell how to install detectron2 in a conda environment?

**Comment by ppwwyyxx** [comment]
It can be installed in a conda environment following https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md

**Comment by ahiranandani** [comment]
That doesn't work:

pip can't find torch. torch is installed from source in a conda environment.

**Comment by ppwwyyxx** [comment]
pip does not need to find torch.
I don't think any of the instructions at https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md will ask pip to find torch.

**Comment by ahiranandani** [comment]
Not true. 

Screenshot when running setup.py for detectron2. 
![Screen Shot 2020-03-04 at 4 59 57 PM](https://user-images.githubusercontent.com/22099784/75937422-a99ce500-5e39-11ea-847d-bf77cc777e2f.png)

**Comment by ahiranandani** [comment]
Not true.

See screenshot./ 
![Screen Shot 2020-03-04 at 4 59 57 PM](https://user-images.githubusercontent.com/22099784/75937479-d5b86600-5e39-11ea-965d-ff8584374c74.png)

**Comment by ppwwyyxx** [comment]
By "find torch" I assumed you mean "find torch to install".
This is not `pip` can't find torch to install. This is python can't find an already-installed torch and you need to use a different python (i.e. the one in your anaconda environment) to run pip.

This sort of bugs are explained in http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/ and you need `python -m pip` with the correct python.
