### ISSUE TITLE
Documentation for Partial Model Execution

### ISSUE THREAD

**Issue by DunaiFuentes** [facebookresearch/detectron2#986]
Using detectron2 from COLAB and following the docs for "partially executing a model" ([here](https://detectron2.readthedocs.io/tutorials/models.html#partially-execute-a-model)) `mask_features = model.roi_heads.mask_pooler(features, [x.pred_boxes for x in instances])` raises an error using the model defined by `COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml`.
The issue is fixed by running `features = [features[f] for f in model.roi_heads.in_features]` right before.
I would suggest:
```
model = build_model(cfg)
model.eval()
checkpointer = DetectionCheckpointer(model)
checkpointer.load(cfg.MODEL.WEIGHTS)
with torch.no_grad():
    images = ImageList(...)  # preprocessed input tensor
    features = model.backbone(images.tensor)
    proposals, _ = model.proposal_generator(images, features)
    instances = model.roi_heads._forward_box(features, proposals)
    features = [features[f] for f in model.roi_heads.in_features]
    mask_features = model.roi_heads.mask_pooler(features, [x.pred_boxes for x in instances])
```

**Comment by ppwwyyxx** [comment]
thanks! Indeed the docs were incorrect

**Comment by ppwwyyxx** [comment]
fixed

**Comment by deepakksingh** [comment]
Hello @DunaiFuentes, I'm trying to execute a faster-rcnn model partially to get its features, proposals.
I'm following the updated tutorial page https://detectron2.readthedocs.io/en/latest/tutorials/models.html
I tried executing the following:
```python
#load only 1 image from train dataloader
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.DATALOADER.NUM_WORKERS = 1
# train_data_loader = build_detection_train_loader(cfg, mapper=DatasetMapper(cfg, is_train=True))
train_data_loader = build_detection_train_loader(cfg, mapper=DatasetMapper(cfg))
model.eval()
with torch.no_grad():
    for data_item in train_data_loader:
        print(data_item)
        features = model.backbone(data_item[0]['image'].unsqueeze(0))
        print(features)
```
But it throws :```RuntimeError: _thnn_conv2d_forward not supported on CUDAType for Byte```
Could you share how you pre-processed the tensors using ImageList, as mentioned in your comment.

Thanks in advance

**Comment by deepakksingh** [comment]
Nevermind, Resolved it.
```Python
model.eval()
with torch.no_grad():
    for data_item in data_loader:
        images_list = [x['image'].float() for x in data_item]
        images = ImageList.from_tensors(images_list,size_divisibility=32).to('cuda')
        features = model.backbone(images.tensor)
        proposals, _ = model.proposal_generator(images, features)
        instances, _ = model.roi_heads(images, features, proposals)
```
