### ISSUE TITLE
Tried to train PanopticFPN but got CUDA out of memory

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#987]
1. what changes you made (`git diff`) or what code you wrote
```
None
```
2. what exact command you run:

* For dataset
pip install git+https://github.com/cocodataset/panopticapi.git
python prepare_panoptic_fpn.py

* run training
python tools/train_net.py --num-gpus 4 --config-file configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml
(I tried num-gpus value from 1 to 4)

3. what you observed (including the full logs):

log file : 
[log_20200305.txt](https://github.com/facebookresearch/detectron2/files/4290671/log_20200305.txt)

partial log:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 162, in <module>
    args=(args,),
  File "/home/emjay/Documents/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/emjay/Documents/detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/emjay/Documents/detectron2/tools/train_net.py", line 150, in main
    return trainer.train()
  File "/home/emjay/Documents/detectron2/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/emjay/Documents/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/emjay/Documents/detectron2/detectron2/engine/train_loop.py", line 228, in run_step
    losses.backward()
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 802.00 MiB (GPU 3; 10.76 GiB total capacity; 7.76 GiB already allocated; 742.62 MiB free; 405.93 MiB cached)

/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
## Expected behavior:
train without cuda out of memory

## Environment:
------------------------  ---------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
numpy                     1.17.4
detectron2                0.1.1 @/home/emjay/Documents/detectron2/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3               GeForce RTX 2080 Ti
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
torchvision               0.4.2 @/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.0
------------------------  ---------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by emjay73** [comment]
Well, simple batch size adjustment solved the issue
* Base-RCNN-FPN.yaml
SOLVER:
  IMS_PER_BATCH: 8 #16

**Comment by emjay73** [comment]
So when it comes to multi-GPU, what is the meaning of IMS_PER_BATCH?
For instance what if IMS_PER_BATCH = 8 and I have 4 GPUs,
what is the batch size handled by single GPU? 2? or 8?

**Comment by ppwwyyxx** [comment]
Your GPUs don't have enough memory - so it's expected.

Changing the batch size can help.

**Comment by ppwwyyxx** [comment]
> So when it comes to multi-GPU, what is the meaning of IMS_PER_BATCH?
For instance what if IMS_PER_BATCH = 8 and I have 4 GPUs,
what is the batch size handled by single GPU? 2? or 8?

Explained in https://detectron2.readthedocs.io/modules/config.html#config-references

**Comment by emjay73** [comment]
Well if this is the case, batch size 2 seems too small if there's batch normalization. What do you think?
Can I expect reasonable results with IMS_PER_BATHC=8 WITH 4 GPUS setting?

**Comment by ppwwyyxx** [comment]
Seems so.

FYI, the config you're using does not use batch normalization.

**Comment by emjay73** [comment]
Thanks! It was helpful. :)
