### ISSUE TITLE
Caffe2 Model Inference after converting from Detectron2 model

### ISSUE THREAD

**Issue by sidsathi** [facebookresearch/detectron2#989]
Is there any example to run inference using the converted caffe2 model? I have converted the model to Caffe2 format. I am new to Detectron2 so any help would be appreciated!

**Comment by ahiranandani** [comment]
Have successfully used the caffe2 converter file provided. Thanks for the functionality,
However, there seem to be few instructions on how to use the resulting pb file for inference? 
Can someone help with that? Much appreciated.

**Comment by ppwwyyxx** [comment]
`Caffe2.__call__` is the code to use the pb file for inference. It eventually calls into https://github.com/facebookresearch/detectron2/blob/master/detectron2/export/caffe2_inference.py.
Copying the code there to an independent location (or translate them to C++) would make an inference example.

**Comment by ahiranandani** [comment]
Thanks for answering that! 
I have one more follow up question - the .__call__ function (and the forward function in ProtobufDetectionModel) expects an input (or batched inputs) that should be a dictionary, can you clarify what dictionary this exact is?

How do we convert an image to this form? 

Thanks

**Comment by ppwwyyxx** [comment]
It uses standard detectron2 models' input format documented at https://detectron2.readthedocs.io/tutorials/models.html

**Comment by ppwwyyxx** [comment]
An example using the caffe2 model in C++ is provided in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python.

**Comment by ahiranandani** [comment]
Thanks a lot @ppwwyyxx. It says that this would run with detectron2 installed. Are there plans for running inference without this dependency in windows? detectron2 does not officially support windows and Pytorch installation on Windows does not contain caffe2 functions.

**Comment by ppwwyyxx** [comment]
It's C++ code so it runs without detectron2.

**Comment by Tushig-creator** [comment]
I`m new with Detectron2 and i want to use it on mobile application. Any documentations or guides with it would be great. Suggestion?  Thanks :)

**Comment by TarunSharmaNT** [comment]
> Have successfully used the caffe2 converter file provided. Thanks for the functionality,
> However, there seem to be few instructions on how to use the resulting pb file for inference?
> Can someone help with that? Much appreciated.

hii could you please tell like how you will able to convert the .pth file into the caffe2 model of detectron2.
