### ISSUE TITLE
How to load 'gt_masks' in coco

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#990]
Here are my dataset register code and meta_arch register
`register_coco_instances("my_dataset", {}, "../../datasets/coco/annotations/instances_train2017.json", "../../datasets/coco/train2017")`
```
@META_ARCH_REGISTRY.register()
class AAA(nn.Module):
...
      def forward(self, batched_inputs):
```
**When I set breakpoint at forward. The instances of batched_inputs have 'gt_boxes' and 'gt_classes'， no 'gt_masks'.**
Is there something I missed and how to load 'gt_masks'.

**Comment by ppwwyyxx** [comment]
did you set `cfg.MODEL.MASK_ON`?

**Comment by Yoline777** [comment]
Thanks, solved by set `cfg.MODEL.MASK_ON`.
