### ISSUE TITLE
Do we have a quick register way for a custom dataset which is in Pascal VOC format? I tried to use register_pascal_voc but it won't work.

### ISSUE THREAD

**Issue by SkeletonOne** [facebookresearch/detectron2#991]
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by ppwwyyxx** [comment]
No. The function is made for pascal voc dataset only.

**Comment by nodechef** [comment]
So for custom dataset in Pascal VOC, do we have to write a custom dataloader function ?

**Comment by ppwwyyxx** [comment]
[Use Custom Datasets](https://detectron2.readthedocs.io/tutorials/datasets.html#use-custom-datasets) explains how to use custom datasets.

**Comment by SkeletonOne** [comment]
@nodechef A solution is to use scripts to transfer VOC format to COCO format, then it will be easy to use register_coco_instances to register it.

**Comment by nodechef** [comment]
@SkeletonOne have you developed any script ? I looked into https://github.com/yukkyo/voc2coco
but it's giving some errors. if you haven't than I would probably fix this one.

**Comment by SkeletonOne** [comment]
@nodechef I think the script in https://github.com/yukkyo/voc2coco is correct. Note that the only thing you should pay attention to while training is to remove the 'ignore' annotation, as https://github.com/facebookresearch/detectron2/issues/1089 says.

**Comment by SkeletonOne** [comment]
@nodechef This method is just an easy way to train your dataset and the credibility cannot be guaranteed. I would not recommend using this method for serious purposes.

**Comment by nodechef** [comment]
This ```register_coco_instances``` ? Or converting voc2coco ?

**Comment by SkeletonOne** [comment]
@nodechef Both works well.

**Comment by nodechef** [comment]
I am confused a little bit. Which method were you talking about ? I'm training the model for production purposes. So I need to make sure that everything is implemented in optimized way.

**Comment by SkeletonOne** [comment]
@nodechef 
The function register_coco_instances works perfectly in this situation. 

But the credibility of the script ' https://github.com/yukkyo/voc2coco' cannot be guaranteed. If you really need to use it, you should check the ground truth of your converted .json file. You can visualize the ground truth using the Colab Tutorial in Detectron2, https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5.

If you need to be ensure everything is accurate, there are two options:
1. Write a script of converting voc to coco by yourself, then use register_coco_instances.
2. write your own dataloader following https://detectron2.readthedocs.io/tutorials/datasets.html#use-custom-datasets. 

There are no direct method for training on custom data in pascal voc format. I hope I've made myself clear.

**Comment by nodechef** [comment]
Yeah. That makes total sense. Thank you 👍

**Comment by SkeletonOne** [comment]
@pakornvs Thanks for your effort. But will you please give an instruction on how to use it to register a voc-style custom dataset?
