### ISSUE TITLE
config-description-eng

### ISSUE THREAD

**Issue by Bekovmi** [facebookresearch/detectron2#992]
## 🚀 Feature
A clear and concise description of the feature proposal.
Full description of config like in Catalyst (https://github.com/catalyst-team/catalyst/blob/master/examples/configs/config-description-eng.yml).
## Motivation & Examples
Dear developers of Detectron2. I like you product. But I have problems with you configs. Sometimes I don't understand, meaning of field in config. 
Thank in Advance!

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory
contains many of such examples.

**Comment by ppwwyyxx** [comment]
https://detectron2.readthedocs.io/modules/config.html#config-references

**Comment by litvinich** [comment]
@ppwwyyxx I think this issue is relative to all config questions, so I will post my question here. In config there is field `MODEL.BACKBONE.FREEZE_AT = 2`. As I understand it freezes first 2 stages of ResNet by default. So for not freezing at all I should make `MODEL.BACKBONE.FREEZE_AT = 0`?

**Comment by ppwwyyxx** [comment]
Yes

**Comment by litvinich** [comment]
@ppwwyyxx what is the purpose of freezing first 2 conv layers and make it default value?

**Comment by ppwwyyxx** [comment]
Papers of these algorithms do it.

**Comment by rbgirshick** [comment]
When Fast R-CNN was originally developed, there wasn't enough GPU memory to perform the backward pass on the first 2 resolution stages with VGG-16, so they were frozen to make training feasible. Subsequently, we've found that when using ImageNet pretraining, freezing the first two resolution stages typically improves AP (as well as reducing memory usage and making training faster).

**Comment by litvinich** [comment]
Thanks, I got it. May be it happens because of "common" domain between ImageNet and COCO, so it worth to experiment with unfreezing on custom datasets.
