### ISSUE TITLE
Freeze Panoptic FPN instance segmentation layer 

### ISSUE THREAD

**Issue by luczeng** [facebookresearch/detectron2#994]
## ❓ How to fine tune Panoptic FPN semantic segmentation branch alone.

I would like to use Panoptic FPN only to fine tune the semantic segmentation branch. I can only find the "FREEZE_AT" option for the backbone.

One option I could think of was to give empty annotations for the instance and panoptic segmentations fields. 
Another option would be to modify manually the instance segmentation network to not propagate the gradient.

Would the above options work? Is there a better way to process?

**Comment by ppwwyyxx** [comment]
This is a pytorch question so you can refer to pytorch community such as https://discuss.pytorch.org/t/how-to-freeze-the-part-of-the-model/31409
