### ISSUE TITLE
Confused about batched_inputs

### ISSUE THREAD

**Issue by Yoline777** [facebookresearch/detectron2#999]
Batched_inputs is a input of META_ARCH_REGISTRY. 
The 'height' and 'width' in my batched_inputs[0] are 358 and 640, but the shape of 'image' tensor in my batched_inputs[0] is [3, 676, 1201].
I want to know their mapping relationship or transform code location.
I tried to find it but couldn't find it. Can you remind me?

**Comment by ppwwyyxx** [comment]
documented in https://detectron2.readthedocs.io/tutorials/models.html#model-input-format

it's produced by `DatasetMapper`.
